### ISSUE TITLE
Widget does not cascade when the list is opened

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#1002]
Demo: http://demos.telerik.com/kendo-ui/dropdownlist/cascadingdropdownlist

Steps:

1. Open the 'Categories' DropDownList
2. Navigate with the keyboard (up/down arrows)

Result: 'Products' dataSource is read every time when the user navigates.
Expected: 'Products' dataSource should be read only after an item is selected and list is closed.

**Comment by ggkrustev** [comment]
Probably is related to the issue reported in TicketID: 966711
