### ISSUE TITLE
Ability to have autofocus on DropDownList in iOS

### ISSUE THREAD

**Issue by IlBaffo** [telerik/kendo-ui-core#1006]
# Description
It is not possible to autofocus the filter text input when a dropdownlist (web, not mobile) is opened in iOS.
## Steps
1. Place a filterable DropDownList
2. Set the 'open' Event to execute this: `if (this.filterInput) { this.filterInput.focus(); }`
3. View the page in iOS Safari (I tried with 8.0+, I don't know with older versions)

Demo: http://dojo.telerik.com/OdAkA

## Possible reason of the behaviour
This is because, in iOS, the "focus" method can only be invoked within a click event and the DropDownList uses a `setTimeOut` to invoke the open event.

### Sources
http://stackoverflow.com/questions/12204571/mobile-safari-javascript-focus-method-on-inputfield-only-works-with-click
http://stackoverflow.com/questions/18728166/programatically-focus-on-next-input-field-in-mobile-safari

## Considerations
This is inevitable to properly wait for the opening animation to complete but, even disabling the animation a `setTimeout` is used.

## Suggested resolution
Do not use a timeout when opening animation is disabled so this can be used as a workaround.

**Comment by ggkrustev** [comment]
Hi @IlBaffo ,

Thanks for your post, and for your interest in Kendo UI Core! **This issues list is for bugs only**, not feature requests, so I’m going to close this issue with this comment. 

That said, we do want your feedback and feature requests, which is why we’ve set up a [User Voice portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) for just this purpose. By funneling feedback through a dedicated feedback portal, we’re able to gauge customer interest, clarify needs and measure the status of requests over time. It has been a critical part of our product development over the last two years, so I do hope you’ll [head on over to the portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback) to enter this request.

Thanks again!

**Comment by ggkrustev** [comment]
Hi again @IlBaffo,

After an internal discussion, we've reached to a conclusion that the best enhancement will be to implement a **specific configuration option** that will tell the widget whether to focus or not the filter input in mobile devices. It will be great if you can post such suggestion in UserVoice portal.

For now, you can focus the input using the `activate` event of the popup widget. There you will need to set specific internal fields to prevent the popup close on wrapper blur. Basically, this is the [_focusElement](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.dropdownlist.js#L774) method, but without the mobile checks. Here is a Dojo demo that shows how to accomplish this task:
- http://dojo.telerik.com/@ggkrustev/Iqolo

**Comment by IlBaffo** [comment]
Hi, thank you for the provided workaround.

Since I am using the MVVM framework I made up a global handler with a custom attribute called `data-mobile-autofocus` that disables the animation and triggers your code when in iOS.

    var customDropDownList = (function (init) {
      return kendo.ui.DropDownList.extend({
        options: {
          name: 'DropDownList',
          mobileAutofocus: false
        },
        init: function (_element, _options) {
          var dropDownList = this;
          if (_options && _options.mobileAutofocus === true) {
            if (kendo.support.mobileOS && kendo.support.mobileOS.name === "ios") {        
              _options.animation = false;
            }
          }
          init.apply(dropDownList, arguments);
          if (_options && _options.mobileAutofocus === true) {
            dropDownList.popup.bind("activate", function () {
              dropDownList._prevent = true;
              dropDownList._focused = dropDownList.filterInput.focus();
            });
          }
        }
      });
    })(kendo.ui.DropDownList.fn.init);
    kendo.ui.plugin(customDropDownList);

This solution did work well with almost every dropdown but, in case of a little delay in the datasource read, the dropdown starts to behave incorrectly.
At the first open the focus is not set and the keyboard is popped up just after the first blur of the widget, it then starts to work on the next open.
For now I avoided the issue by pre-fetching the datasource.

This is a demo of the global handler, in the last DropDown you can see what happens when there is a delay in the datasource read function (always in iOS).

* http://dojo.telerik.com/EJISA

**Comment by ggkrustev** [comment]
Hi @IlBaffo,

Please excuse me for the late reply (I was off for several weeks).

You are absolutely right. The browser does not open virtual keyboard when binding slows down a bit. The strange thing here is that in both cases (slow binding or not), the `activate` event is triggered after the popup is visible and there should be no difference for the browser. Unfortunately it has.
After several different tries I failed in finding a proper solution/workaround for this particular misbehavior. I am afraid that I am out of ideas in this case. 

If you or someone else find in future, it will be very nice to post the workaround here.
