### ISSUE TITLE
Grid selection causes unexpected scrolling

### ISSUE THREAD

**Issue by boog** [telerik/kendo-ui-core#1011]
In Chrome a selectable Grid with keyboard navigation scrolls unexpectedly on selection/focus of the Grid. Issue does not exist in IE because code is slightly different for IE to avoid scrolling. Here is the snippet from  kendo.grid.js which is causing the issue,
```javascript
var condition = true || msie && table.parent().is(".k-grid-content,.k-grid-header-wrap"),
    scrollTop, scrollLeft;
if (condition) {
    scrollTop = table.parent().scrollTop();
    scrollLeft = table.parent().scrollLeft();
}
 
if (msie) {
    try {
        //The setActive method does not cause the document to scroll to the active object in the current page
        table[0].setActive();
    } catch(e) {
        table[0].focus();
    }
} else {
    table[0].focus(); //because preventDefault bellow, IE cannot focus the table alternative is unselectable=on
}
 
if (condition) {
    table.parent().scrollTop(scrollTop);
    table.parent().scrollLeft(scrollLeft);
}
```
The code that is wrapped in if(condition) is intended to record and reset the scroll position, however in most cases the parent container of the Grid is not the element that scrolls, replacing this with $(document).scrollTop() etc fixes the issue in Chrome for me.

[Reproduction here](http://dojo.telerik.com/EQiQO).

**Comment by KirilNN** [comment]
Hi @boog,

Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (Professional, UI for MVC, PHP, JSP) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI!
