### ISSUE TITLE
Sortable to only drag on handler when specified

### ISSUE THREAD

**Issue by boniestlawyer** [telerik/kendo-ui-core#1024]
When using sortable elements that have the handler specified - the draggable action should only work on the handler and ignore all other elements. The option to ignore elements within the sortable/draggable doesn't quite catch all that I need (without being overly complex).

The draggable widget could take an`only` option similar to the `ignore` option and then the draggable `_shouldIgnoreTarget` could check that the element is the only element. The sortable widget would then pass the `handler` to the only option of the draggable widget it creates.

Something like this:

```javascript
kendo.ui.Draggable.prototype._shouldIgnoreTarget = function (target) {
    var ignoreSelector = this.options.ignore;
    var onlySelector = this.options.only;
    return (ignoreSelector && $(target).is(ignoreSelector)) ||
        (!onlySelector || !$(target).is(onlySelector));
};

kendo.ui.Sortable.prototype._createDraggable = function() {
    var that = this,
        element = that.element,
        options = that.options;

    return new kendo.ui.Draggable(element, {
        filter: options.filter,
        hint: kendo.isFunction(options.hint) ? options.hint : $(options.hint),
        holdToDrag: options.holdToDrag,
        container: options.container ? $(options.container) : null,
        cursorOffset: options.cursorOffset,
        axis: options.axis,
        only: options.handler,
        ignore: options.ignore,
        autoScroll: options.autoScroll,
        dragstart: $.proxy(that._dragstart, that),
        dragcancel: $.proxy(that._dragcancel, that),
        drag: $.proxy(that._drag, that),
        dragend: $.proxy(that._dragend, that)
    });
}
```

**Comment by valchev** [comment]
The `only` options overlaps with `ignore`.
@boniestlawyer can you provide an example which demonstrates something that cannot be achieved with `filter` and `ignore`?
