### ISSUE TITLE
Prevent popup close on scroll "how-to" does not work with Kendo 2015 Q2 and Q2 SP1 but works fine for older versions

### ISSUE THREAD

**Issue by nemalp** [telerik/kendo-ui-core#1025]
Can be reproduced here: http://dojo.telerik.com/iyuri

Unable to scroll the list with mousewheel.

Reported in TicketID: 960420

**Comment by dimodi** [comment]
Fixed by https://github.com/telerik/kendo-ui-core/commit/77a6ddd3395ad472c912744253333bb7d9fa07c5
