### ISSUE TITLE
Initializing MaskedTextBox with mask containing only digits (no literals) with kendo.init fails to parse the mask

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#1030]
The problem can be observed in the following example:
http://dojo.telerik.com/IDIxu/7

The issue is within the parseOption method (called within the  kendo.initWidget), where the "0000" mask is handled as a number and it is parsed to float:
function parseOption(element, option) {
	....
    } else if (numberRegExp.test(value)) {
        value = parseFloat(value);
    }
	...
}

**Comment by ggkrustev** [comment]
The described is a limitation of the data attribute parse functionality used in Kendo UI, as it is described in the description. I am afraid that we do not have plans to enhance the attribute inferring behavior.

The only feasible workaround that I can suggest is to use MVVM binding that will set the mask value dynamically. Check this "how-to" demo:
- http://docs.telerik.com/kendo-ui/web/maskedtextbox/how-to/MVVM/custom-mask-binding

**Comment by Alex-Bubblemaster** [comment]
Also reported in 1081200.

It is possible to add a zero width no-break spaces `&#xfeff;` character to overcome this limitation:

[Dojo](http://dojo.telerik.com/iYeso)
