### ISSUE TITLE
Filters are sent wrongly to the server during the first request when minLength and value are applied in the MultiSelect configuration

### ISSUE THREAD

**Issue by pablofm86** [telerik/kendo-ui-core#1034]
This behavior is observed in the MultiSelect widget when the serverFiltering option is set to true and the options minLenght (> 0), value (an array with values) and autoBind (false) are set too. It occurs the first time you try to request data.

For example if you take the demo page for the MultiSelect / Server filtering (http://demos.telerik.com/kendo-ui/multiselect/serverfiltering) and you add the minLenght option, then the issue is observed.

Instead of sending the filter object as you expect, which by default is something like this:

filter[logic]: and
filter[filters][0][field]: name
filter[filters][0][operator]: startswith
filter[filters][0][value]: Jane
filter[filters][0][ignoreCase]: true

It is sent uncomplete as in the following example:

0[value]: Ja
0[field]: name
0[operator]: startswith
0[ignoreCase] :true

Telerik Dojo: http://dojo.telerik.com/@pfermena/UsIxu (in this example is a little bit different because it is an odata request, but the issue is still observable)

**Comment by ggkrustev** [comment]
After further investigation, it seems that the issue is related to a specific configuration set of the widget:
- `autoBind` should be set to *false*
- widget should have initial values, like in the demo

The problem is how the filter is passed to the dataSource.read method:
- https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.list.js#L221

It should be:
```javascript
            if (filter) {
                expression = {
                    filters: expression.filters || [],
                    logic: expression.logic
                };

                expression.filters.push(filter);
            }

            if (!force) {
                dataSource.filter(expression);
            } else {
                dataSource.read(expression);
            }
```

**Comment by pablofm86** [comment]
Hi Georgi,

Introducing the change you mention, the filter logic that was previosly sent (filter[logic]: and) is not part of the request anymore. Is this the expected behavior?

**Comment by ggkrustev** [comment]
Basically, before the `read` method was not called correctly. It requires a normalized filter expressions - one with { filters: [], logic: "and/or" } structure. The `filter` method does this normalization, but the `read` doesn't. That is why we need to normalize the filter before pass it to the `read` method.

Does this answer your question?

**Comment by pablofm86** [comment]
Ok thanks, I understand, but to me, the problem is that:

In the filter method normalization the filter logic if the required conditions are met is hardcoded with the value "and".

In your fix, if the expression.logic is undefined, this parameter is not sent with the request, and I don't know if this is the expected behavior.

It's just to be sure I'm handling the request in a proper way taking into account this parameter is optional.

Thanks again.

**Comment by ggkrustev** [comment]
Well, the `logic` will always "and". The widget does not support "or" anyway and thus will fallback to the default filter logic which is "and".
