### ISSUE TITLE
"k-state-focused" class is set to the first tab when selecting another tab in IE11

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-ui-core#1040]
Reported in ticket: 961503. Can be reproduced in the online demos -> http://demos.telerik.com/kendo-ui/tabstrip/index

**Comment by vladimirivanoviliev** [comment]
It seems that this is a browser issue:

- [MS IE11, bug: 1028411](https://connect.microsoft.com/IE/feedback/details/1028411/ie-11-span-and-div-elements-without-the-tabindex-attribute-should-not-be-focusable)
