### ISSUE TITLE
List does not fill the specified height when headerTemplate is set

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#1042]
Example: http://dojo.telerik.com/eCETu

Reported by client in ticket 962338

**Comment by ggkrustev** [comment]
The described behavior is actually expected, because the `headerTemplate` needs to have a single parent element. In other words, all elements that needs to be added should be wrapped in single element:
- http://dojo.telerik.com/eCETu/2

> This will be documented to avoid further misunderstandings
