### ISSUE TITLE
Title element is not removed on time in IE11

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#1043]
It looks like a timing issue, which causes the browser to show the original tooltip. Can be reproduced in the online demos, but requires precise clicking in order to get the correct timing.

**Comment by Iankodj** [comment]
Using this demo (http://demos.telerik.com/kendo-ui/tooltip/index), I am unable to reproduce that anymore. It might have been a browser quirk or something else that is already fixed.
