### ISSUE TITLE
Calling resize() on a slider breaks the ability to select a value by clicking on the label

### ISSUE THREAD

**Issue by nemalp** [telerik/kendo-ui-core#1048]
Can be reproduced here: http://dojo.telerik.com/erehu

Reported in TicketID: 963339

**Comment by theyo** [comment]
I took a quick look at the code figured out that I could resolve the issue by calling slider.enable(true) after calling slider.resize() in the dojo sample.

I'm not sure that adding the enable(true) call is the appropriate solution in the source, but wanted to provide the extra information.

I created an updated repro with this fix here: http://dojo.telerik.com/ehOLE/2
