### ISSUE TITLE
Widget clicks and taps do not work as expected in iOS 8.4.1

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1056]
Vague description of the change is present here:

https://support.apple.com/en-us/HT205030

Random fixes and suggestions pop up here:

http://stackoverflow.com/questions/32034503/links-and-clicks-fail-to-open-with-cordova-on-ios-8-4-1/32063461#32063461

So far, we know that the window close button is affected. Most likely, a lot more.

**Comment by brenak** [comment]
We are experiencing the same thing.  Close button is not working, and Drop Down Lists are not opening as they should, you have to hit the chevron exactly or it will not open.

**Comment by rshenton** [comment]
.k-window-actions a.k-window-action.k-link, k-window-actions a.k-window-action.k-link.k-state-hover {
     opacity:1;
}

**Comment by brenak** [comment]
rshenton's comment fixes our close window problem.  We are working on the DDL now, we think its the same thing as the chevron has an opacity of 1 by default and works, the rest of the DDL does not.  Apples quote on what everyone thinks is causing this is:

"Impact: A malicious website can make a tap event produce a synthetic click on another page Description: An issue existed in how synthetic clicks are generated from tap events that could cause clicks to target other pages. The issue was addressed through restricted click propagation."

**Comment by rshenton** [comment]
For dropdownlist: .k-dropdown .k-select span.k-icon.k-i-arrow-s { opacity: 1 }

**Comment by rshenton** [comment]
More generically: .k-i-arrow-n, .k-i-arrow-s, .k-i-arrow-w, .k-i-arrow-e, .k-i-seek-w, .k-i-seek-e {  opacity:1; }

**Comment by LanceMcCarthy** [comment]
For PanelBar, the following is temporary fix:

.k-header, .k-icon{
        opacity: 1;
 }

For runnable repo, load http://dojo.telerik.com/@Lance/UQaSO

**Comment by rshenton** [comment]
The Timepicker has a particular issue after the list shows on IOS devices where a tap doesn't select an item. On DropDownList this was resolved with .k-icon{ opacity: 1; }, but not Timepicker even though they have the same markup.

**Comment by LanceMcCarthy** [comment]
The class name for the TimePicker's clock is "k-icon k-i-clock" and the drop down items's class is "k-item".

You can try to set opacity to 1 for those classes and see if it works.

**Comment by nemalp** [comment]
Group the grid by dragging a column header cells does not work on iOS 8.4.1
Repro: http://demos.telerik.com/kendo-ui/grid/index

**Comment by naskog** [comment]
The issue seems to be addressed by Apple in iOS 9 Beta

**Comment by IlBaffo** [comment]
It is indeed fixed in iOS 9 but it should be addressed for the 8.4.1 anyway, because not every businesses will allow to upgrade their devices immediately.

**Comment by underlog** [comment]
@IlBaffo I may suggest that you apply the workarounds suggested above and remove them once you consider them unnecessary.
