### ISSUE TITLE
"change" event is not triggered in some cases

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1059]
Repro snippet: 
[http://dojo.telerik.com/@andrew/oCiWe/2](http://dojo.telerik.com/@andrew/oCiWe/2)

Sample steps to reproduce:
1) Click in the date box, and then type 20/8/15.
2) Press Tab (or click outside the date box, so that it loses focus). 

Result:
The dateString variable contains the unparsed value: 20/8/15

Related to #532 
Regression since 2015 Q1 SP2
Reported in Ticket ID: 963681

**Comment by KirilNN** [comment]
related to https://github.com/telerik/kendo-ui-core/issues/1155
