### ISSUE TITLE
SASS Version

### ISSUE THREAD

**Issue by brunowego** [telerik/kendo-ui-core#1061]
I would like to work in a Kendo UI version using SASS. If I do that, have one chance to accept it or not have plans for SASS support?

**Comment by andrecost** [comment]
+1

**Comment by juliopontes** [comment]
Really nice feature to done, I wish this implementation :+1:

**Comment by lucasbarcellos** [comment]
That would be awesome!

**Comment by andersonjunqueira** [comment]
+1

**Comment by dublado** [comment]
+1

**Comment by WendellAdriel** [comment]
+1

**Comment by brayann** [comment]
+1

**Comment by spillere** [comment]
+1

**Comment by gcdesigner** [comment]
+1

**Comment by underlog** [comment]
Hi @brunowego , I am not sure that I understand the wording. Do you submit a feature request, or do you suggest that you will maintain a SASS fork of the official LESS stylesheets?

**Comment by brunowego** [comment]
Hi @underlog, thanks to reply. I think the best way is a pull request, but if it is not a option, a fork is possible? It would be a problem have a fork?

**Comment by underlog** [comment]
Hi,

We won't accept a pull request If you plan to add sass sources or replace the current less ones. We don't have any current plans to maintain a SASS based source.

**Comment by brunowego** [comment]
Alright, thanks @underlog :+1:
