### ISSUE TITLE
An item is not correctly selected in case the value is set synchronously to three cascading dropdownlists with server filtering enabled

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-ui-core#1063]
Reported in ticket: 964318 
The ticket contains a sample project which demonstrates the issue. 
To reproduce, click on the product 1 link and then on the product 4 or 5 links. The last dropdownlist does not show a selected value even though its value is set.

**Comment by ggkrustev** [comment]
Fixed with 79f5a9d1a75ea5f74dfaa04dd3a6b3e1fe7e502c
