### ISSUE TITLE
re-structure the Welcome to Kendo UI introduction

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1067]
Currently, the docs homepage lacks a clear getting started with Kendo UI flow. We may show some simple, runnable samples with "Edit", and also provide the most relevant links for the installation.

**Comment by dmihaylo** [comment]
Due to the general restructuring of the Kendo UI documentation, now an independent Getting Started folder is maintained. It consists of 3 sub-folders related to the prerequisites and installation, widgets basics, and additional resources.
