### ISSUE TITLE
Custom install using `git submodule` ??

### ISSUE THREAD

**Issue by jesperronn** [telerik/kendo-ui-core#1074]
Documentation page mentions several ways of installing kendoUI and integrating it into my project

http://docs.telerik.com/kendo-ui/install/custom

However, I am missing something. Can you help me to verify if this is possible

I would like to pull the build in via git, by including kendo-ui-core as a Git submodule.

So my procedure would be something like (from my applications assets folder):

1. `git submodule add https://github.com/telerik/kendo-ui-core`
2. customize my build with `grunt custom:autocomplete,dropdownlist`

Is this possible? Or is there something I overlook? (licenses or similar)

**Comment by underlog** [comment]
Hi @jesperronn, 

the Kendo UI Core license permits you to do that, there is nothing you overlook here. However, if you decide to go that route, make sure that you choose the commit of the submodule. The `master` branch is the tip of our development efforts, and you may end up with a very unexpected state :).

**Comment by jesperronn** [comment]
thanks @underlog, for clarifying. 

Actually two things prevent me from this strategy presently:

1. #1075, since I would need the released versions to be available as git tags I can refer to.
2. I realized that none of the professional widgets are available in kendo-ui-core. And I need some of them (at least the `grid` component at my current project work)

The latter point was really surprising to me. This means that I am probably back to downloading a big bucket of files, and then manually clean and maintain upon every version update. Or am I missing something?

**Comment by underlog** [comment]
If custom build + pro features is what you are looking for, you won't be able to avoid the manual download. The good news is that the download bundle contains a Gruntfile (same like the one in this repo) which will allow you to skip the manual clean and file picking.

**Comment by underlog** [comment]
I think that your best bet would be to use our pro bower package and copy the Grunt build we have done in your own project. From there on, you can use Bower to keep things up-to-date, while still having a custom built file.
