### ISSUE TITLE
Kendo Grid ExportAsPDF 

### ISSUE THREAD

**Issue by xavi-99** [telerik/kendo-ui-core#1076]
Hello

I have a problem with the ExportAsPdf function for the kendo Grid.

On set the AllPages parameter to true, the result of the exported pdf is not printed as expected.

![exportpdf](https://cloud.githubusercontent.com/assets/8780445/9543638/a181cbda-4d7a-11e5-8034-f5ee25e724e2.png)

As you can see, the second page has the values overflappeds with the values of the first page i think.

This is the code that I use to print the grid as pdf form an external button 

![exportaspdfcode](https://cloud.githubusercontent.com/assets/8780445/9543696/01e8300e-4d7b-11e5-875c-b293cf5cc315.png)

Is the error in my side? or its a known issue of kendo
Thanks

**Comment by tsvetomir** [comment]
Hi,

Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (Professional, UI for MVC, PHP, JSP) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI!
