### ISSUE TITLE
support for per-item click callbacks

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-ui-core#1078]

**Comment by slavtsekov** [comment]
The MVC wrapper of the Menu widget generates HTML, which in turn populates the items of the widget. As a result, in order to be able to set an item click callback via the MVC wrapper, there should be a way to specify it when the widget is initialized through HTML markup.

Perhaps this can be achieved by introducing a custom attribute that will be set in the **li** tags of the markup, for example `k-select`.

**Comment by KirilNN** [comment]
What would be the use case for this, as we already have the select event of the Kendo UI Menu? Providing callback attribute for every item of the menu does not make much sense, as if we have a callback it should be one with different context, but again - we have the select event for this, don't we?

Maybe @petyosi can give us some more background on the problem.

**Comment by petyosi** [comment]
The use case would be different event handlers for different items. Handling it all in a single event results in a wall of `switch case` boilerplate.

**Comment by KirilNN** [comment]
What if you provide `onclick` attribute via `HtmlAttribues`? I think it will be the same. 

Great example here is the HTML `select` that does not have `change` event for the individual items, but a single one with the correct context. As for the `switch case` boilerplate - maybe the customer can use a dictionary instead?

On a side note - if we go with this implementation, then we should have it for the treeview, panelbar and tabstrip as well.

**Comment by slavtsekov** [comment]
For MVC and MVC Core wrappers using `HtmlAttributes` to set the `onclick` attribute is indeed the simplest way to do it.

In JSP and PHP wrappers the menu is initialized via HTML as well, so there I added a new `select` property for each item. Its value is set to the `onclick` attribute of the menu item element when the HTML is generated thus providing an option to set a click handler in this case.
