### ISSUE TITLE
Unexpected animation plays on close when animation.close is false

### ISSUE THREAD

**Issue by IdontKnowAname** [telerik/kendo-ui-core#1086]
Hi,

if I try to disable the close animation of an kendo window, there are some strange effects.
You can reproduce it, using this dojo http://docs.telerik.com/kendo-ui/api/javascript/ui/window#configuration-animation.close
I used Chrome with latest kendo ui version.

Regards

**Comment by KirilNN** [comment]
@IdontKnowAname thanks for reporting this.

**Comment by gyoshev** [comment]
Fixed by 93e30ea91
