### ISSUE TITLE
Nova mobile theme radio buttons and checkboxes are missing selected state on Android devices

### ISSUE THREAD

**Issue by bundyo** [telerik/kendo-ui-core#1097]
The reason is that all other mobile themes use font icons for the checked state and there is .km-icon class set on the checkboxes and radio buttons. The Nova theme however uses background for colorization and it gets overridden by an Android webkit-mask icons reset. 

You can fix it by either removing .km-icon from the checkable input elements and eventually fixing all other mobile themes or by using font icons in Nova.

There is a third alternative - deprecating/removing iOS6 and webkit-mask icons support + the said workarounds would also fix it.

**Comment by inikolova** [comment]
Fixed -> 5558dc718043208ee1efe7c7
