### ISSUE TITLE
Upgrade the CI stack

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1100]
our karma version is ancient by the web standards. Most likely, this is the cause for the random failures we experience. 

I have done some stuff [here](https://github.com/telerik/kendo-ui-core/tree/update-karma), however the tests don't pass because QUnit needs to be upgraded, too. And this clashes with our QUnit.fixture implementation.

**Comment by tsvetomir** [comment]
That would be jolly good. Let me know if you need help.

**Comment by underlog** [comment]
https://github.com/karma-runner/karma/issues/1144#issuecomment-53633076 - something we may try, too. This will allow us to migrate to the new travis infrastructure, too.

**Comment by underlog** [comment]
Done
