### ISSUE TITLE
Server filtering on Windows Phone does not work correctly

### ISSUE THREAD

**Issue by nemalp** [telerik/kendo-ui-core#1101]
Repro: http://demos.telerik.com/kendo-ui/dropdownlist/serverfiltering
1. Open the link in Windows Phone browser
2. Open DropDownList at the top of the page
3. Try to insert some text in the filter input field
4. The DropDownList closes.

Reported in support thread: 969199

**Comment by Alex-Bubblemaster** [comment]
Reported for IE Mobile in ticket ID 1062311. Possibly related to [#801](https://github.com/telerik/kendo-ui-core/issues/801)

**Comment by zdravkov** [comment]
Seems to be working correctly when adding the following metatag that is required for mobile devices:

`<meta name="viewport" content="width=device-width, initial-scale=1.0" />`
