### ISSUE TITLE
[$compile:tplrt] error in Chrome

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1104]
The following [sample](http://runner.telerik.io/fullscreen/@naskog/UvIhI) is running OK in Firefox but JS error is thrown in Chrome

The example is created in order to test workitem #586

**Comment by underlog** [comment]
Problem is most likely related to the newly introduced web components, as they overlap the tag names of the existing directives - hence the "Chrome only" issue. Simplified the case to this:

http://dojo.telerik.com/@petyosi/iPIgi

Workaround suggested: disable web component registration if we detect Angular 1.* environment. Reverse detection is present here:

https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.angular.js#L18

CC: @tapopov
