### ISSUE TITLE
What is the license of Kendo UI Core 

### ISSUE THREAD

**Issue by bnvk** [telerik/kendo-ui-core#1105]
I don't see a license file in the repo nor is it specified in the package.json considering you offer paid versions and some components that are only available that way, it seems quite important to clearly state what the license for the UI core components is

**Comment by naskog** [comment]
Hi @bnvk,
Please refer to the following link:
[https://github.com/telerik/kendo-ui-core#license-information](https://github.com/telerik/kendo-ui-core#license-information)

Thanks for your post, and for your interest in Kendo UI Core! **This issues list is for bugs only**, not help or support requests, so I’m going to close this issue with this comment.

**Comment by underlog** [comment]
Thank you @bnvk  for your suggestion, we will add a license file at the conventional path.

**Comment by underlog** [comment]
Done in ad966c2

**Comment by bnvk** [comment]
@underlog cool, thanks for that!
