### ISSUE TITLE
Fix incorrect LESS file paths to work with webpack require

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#1112]
To use less styles as follows with webpack:

```
var loader = require('../styles/app.theme.' + theme + '.less');
loader(function(style) {
    style.use();
});
```

where ```app.theme.default.less``` is:

```
@import "./vendor/kendo/web/kendo.default.mobile.less";
@import "./vendor/kendo/dataviz/kendo.dataviz.default.less";
@import "./vendor/kendo/web/kendo.default.less";
@import "app.template.less";
```

and for the sake of giving another example, ```app.theme.flat.less``` is

```
@import "./vendor/kendo/web/kendo.flat.mobile.less";
@import "./vendor/kendo/dataviz/kendo.dataviz.flat.less";
@import "./vendor/kendo/web/kendo.flat.less";
@import "app.template.less";
```

and where ```app.template.less``` is a set of custom styles for our application using kemdo ui less constants, for example

```
html, body, body>div.k-loading-image{
    background-color: @content-background-color;
}

a {
    color: @widget-text-color;
}
a:hover {
    color: @hover-text-color;
    text-decoration: none;
}
a:active {
    color: @active-text-color;
    text-decoration: none;
}
``` 

There are two issues to fix otherwise webpack fails.

### 1. Styles need to be modified using the following commands because some paths are wrong:

(run in the style directory)

```
sed -i 's/fonts\/DejaVu\/Deja/Deja/g' web/fonts/DejaVu/dejavu.less
sed -i 's/"textures/"..\/textures/g' web/common/ie7.less
sed -i 's/"textures/"..\/textures/g' web/common/inputs.less
sed -i 's/"images/"..\/images/g' mobile/common/icons.less
```

Please check and correct paths.

### 2. The nova style misses several constants and needs to be fixed as follows:

```
@import "./vendor/kendo/web/kendo.nova.mobile.less";
@import "./vendor/kendo/dataviz/kendo.dataviz.nova.less";
@import "./vendor/kendo/web/kendo.nova.less";

/* missing from nova theme */
@widget-gradient: none;
@content-background-color: @background;
@active-text-color: @normal-text-color;
@hover-background-color: @hover-background;
@hover-border-color: @hover-background;
@selected-border-color: @accent;
@focused-shadow: none;
@drop-down-text-color: @normal-text-color;
@drop-down-background: @base;
@drop-down-border-color: @accent;
@shadow-color: rgba(0, 0, 0, .2);
@window-shadow-style: 0 0 0 1px;
@inner-border-radius: @main-border-radius - 1.2;
@calendar-border-radius: @border-radius;

@import "app.template.less";
```

Please make sure all themes implement the same constants even if they are not used because we might use theme in our own extended themes.

**Comment by gyoshev** [comment]
Thank you for the feedback, @jlchereau.

We are currently fixing the incorrect paths and will push out the update in the next few days.

Regarding the missing variables in the Nova theme, this is intentional. In 2015.Q2, we significantly reduced the amount of variables used in themes. You can rely on [the variables in our current themes](https://github.com/telerik/kendo-ui-core/blob/master/styles/web/kendo.black.less) to be available for any given theme, and define other colors as you need them.
