### ISSUE TITLE
AutoScroll does not work as expected in Firefox

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1113]
Reproduction: http://dojo.telerik.com/@petyosi/IgOkU

**Comment by alexburr** [comment]
This is still not working in Firefox: http://dojo.telerik.com/ULuso

**Comment by underlog** [comment]
@alexburr This works, though: http://dojo.telerik.com/ULuso/2 - does it suit your case?

**Comment by alexburr** [comment]
It does. I'm not thrilled about having to display the horizontal scroll as well as vertical, but it's better than not working at all. Thanks!

**Comment by underlog** [comment]
`overflow: auto` should work, too. The horizontal scroll should not appear, unless the items in the list are larger than the container.
