### ISSUE TITLE
Popup is misplaced after device rotation

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1116]
Steps:
Navigate to [http://demos.telerik.com/kendo-ui/dropdownlist/index](http://demos.telerik.com/kendo-ui/dropdownlist/index)
Tap onto the DropDownList to open its popup
Change device orientation (Landscape <-> Portrait)

Result:
The popup is not aligned with the dropdownlist input

Reported in Ticket ID: 971180

**Comment by naskog** [comment]
Another report in Ticket ID: 974705
 " if you have a DropdownList on the screen and tap on it; the selection box appears correctly EXCEPT if you are zoomed (pinched)"

**Comment by naskog** [comment]
In IE11 touch there are cases in which the misplaced popup steals the focus (moves the visible area a bit) and closes itself. - refer to Ticket ID 974483

**Comment by ggkrustev** [comment]
We will re-position the popup on [orientationchange](https://developer.mozilla.org/en-US/docs/Web/Events/orientationchange).

**Comment by ggkrustev** [comment]
Fixed with 82b348cbd6697702bda5c8cf5f3dcde88178d593, 3ef2f1cf4084ef508fb4f92cd6f61d691b9ff298, 59f85f08f0da8a63551da73e3be963cae55a7c41

**Comment by naskog** [comment]
Works in iPad/iPhone. Does NOT work in Android.

**Comment by ggkrustev** [comment]
I am afraid that for time being, we will not be able to address this issue on Android. We settled down to use the `orientationchange` event to re-position the popup. This "should" work in all mobile browsers. Unfortunately, this is not the case.

We are open for pull-requests for this one.

**Comment by ggkrustev** [comment]
The last commit should have fixed the issue with the Android devices.
