### ISSUE TITLE
Grid responsive pager in material theme looks inconsistent

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1127]
Dojo: http://runner.telerik.io/fullscreen/@petyosi/UQIhe

Small screen width screenshot attached.
![screen shot 2015-09-22 at 9 35 46 am](https://cloud.githubusercontent.com/assets/13347/10012155/618004f6-610d-11e5-9b8f-aebc75e7238a.png)

**Comment by yordanov** [comment]
The pager is fixed now:

![pager](https://cloud.githubusercontent.com/assets/1118895/10134161/7b590362-65ec-11e5-9bde-eb80f6e16393.png)
