### ISSUE TITLE
AngularJS Autocomplete not working on second try

### ISSUE THREAD

**Issue by marcoangheben** [telerik/kendo-ui-core#1131]
Hi guys.
I am experiencing a wrong behaviour on angularjs autocomplete component.
As you can try on http://dojo.telerik.com/,
1) you type in "It"
2) you choose "Italy"
3) the label updates on "Italy"
4) you clean the input field
5) you type in "It"
6) you choose "Italy"
7) the label updates on just "It"
Is there a workaround to this?
Thanks.
Regards, 
Marco

**Comment by naskog** [comment]
@marcoangheben , please provide complete link to the dojo snippet

**Comment by marcoangheben** [comment]
You can find the snippet by selecting "Edit this example" on http://demos.telerik.com/kendo-ui/autocomplete/angular .
Regards

**Comment by ggkrustev** [comment]
The issue seems to be related to this fix:
- https://github.com/telerik/kendo-ui-core/issues/532
