### ISSUE TITLE
support getter/setter for k-ng-model 

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-ui-core#1132]
The mechanism is described here (bottom):

https://docs.angularjs.org/api/ng/directive/ngModel 

perhaps we should also provide `k-ng-model-options` to facilitate it.

**Comment by markhayton** [comment]
Has this been added to Kendo yet?
I am trying to use ng-model-options with gettersetter and it does not work with the calendar, numeric spinner controls. Thanks

**Comment by KirilNN** [comment]
Hi @markhayton,

This feature is not added yet, as soon as any progress is made the issue will be updated/closed.

Thanks!

**Comment by zeniale** [comment]
Any news?

**Comment by underlog** [comment]
Hi @zeniale - we accept pull requests for this enhancement - feel free to submit one. Thanks!

**Comment by Dimitar-Goshev** [comment]
Closing this issue - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
