### ISSUE TITLE
Add reference to the chart in the series.visual function (e.sender)

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#1134]

**Comment by realjoker** [comment]
This would be useful also for all the *.visual functions (e.g. series.labels.visual), e.g. to see align data labels to either the left or right side of the chart.

**Comment by tsvetomir** [comment]
Will be available in the next internal builds as well as 2015 Q3 SP1

**Comment by realjoker** [comment]
Hi. Will this be available in the series.visual only or also in all the other visuals (see my previous comment)?

**Comment by tsvetomir** [comment]
It will be available for other visuals as well (almost anything besides the legend). See commits 47a1add1d57cd9d1d883c246a09942c32f7320bd and 4207f1d7b85eda8f2199c082e01983da64b16987
