### ISSUE TITLE
Encoding problem with title attribute

### ISSUE THREAD

**Issue by madcodemonkey** [telerik/kendo-ui-core#1144]
I was working on solving some cross site scripting issues when I noticed that the title attribute is not properly encoding text.  This is an issue for us because the title attribute is used by Foundation Zurb when creating tool tips.  The title text is pulled and placed elsewhere on the screen and the inject script runs when you hover over the tool tip item. 

Here is a simpler example, as a picture, of what I'm entering and what's coming out (because this is script, I can't just paste it in):

![problem](https://cloud.githubusercontent.com/assets/11081006/10145420/9b4ac074-65e8-11e5-88f7-0cfee197db7b.jpg)

I've tested this against the latest version: 2015.2.902

Here is a jsFiddle to play with as well:
http://jsfiddle.net/MadCodeMonkey/p80fhdgk/

**Comment by underlog** [comment]
Hi,

If I understand your case correctly, the encoding problem is not in the data binding itself - the title attribute update does not result in the alert being executed, since it is encoded just fine. The alert comes from the fact that you obtain the title attribute value and, **without encoding it again**, append it to another container.

**Comment by madcodemonkey** [comment]
For some reason, if the template or data-bind syntax is used with attributes other than the TEXT attribute on a SPAN, you get partially encoded text.   I'm not sure why there is a difference between the title or a custom attribute and the text attribute.  I would think they should be treated the same, but they are not.  At the VERY least, using template syntax #: projectName # should NOT care where it is being used, but these two are NOT treated the same:
<span title="#: projectName #"></span>
<span>#: projectName #</span>
 
I've also seen the same problem with custom attribute on a DIV.  Since it is attempting to encode it, I would say this is still a bug.
 
Date: Wed, 30 Sep 2015 06:09:53 -0700

**Comment by madcodemonkey** [comment]
For others....

Petyo explained "the title attribute value itself is encoded as expected. In fact, we rely on the built-in DOM method setAttribute for that purpose."

My reply:
All I really wanted was for the Kendo template encoding syntax to be treated the same no matter where it was in the template; however,  I think I understand what you are saying.  You are telling me that Kendo does NOT handle the encoding for attributes and relies upon the JavaScript framework's setAttribute method to encode the text.  When I used setAttribute to inject the script via the Chrome console, I do see the partial encoding that I was talking about.  This explains why the attribute is partially encoded for the title attribute and correctly encoded when the template syntax is used elsewhere.   How strange.  I would have expected the "encoded" template syntax (#: field #) to be used as a maker, the contents to first be encoded and then do a simple substitution.  If I really meant to inject script, I would have used the html keyword.

Thank you for clearing up my confusion.
