### ISSUE TITLE
AngularJS bindings don't work for widgets that are instantiated from HTML

### ISSUE THREAD

**Issue by alFReD-NSH** [telerik/kendo-ui-core#1149]
For example things like this, used to work:

```
<div ng-app="app" ng-controller="MyCtrl">
    <ul kendo-tree-view>
      <li ng-repeat="item in tree">
        {{item.text}}
        <ul>
          <li ng-repeat="item in item.items">
            {{item.text}}
          </li>
        </ul>
      </li>
    </ul>
</div>
<script>
angular.module("app", ["kendo.directives"]).controller("MyCtrl", function($scope) {
    $scope.tree = [
      { text: "Foo", items: [
        { text: "Foo 1" },
        { text: "Foo 2" } ] },
      { text: "Bar", items: [
        { text: "Bar 1" },
        { text: "Bar 2" } ] },
    ];
});
</script>
```

Which was taken from [here](http://docs.telerik.com/kendo-ui/AngularJS/notes-on-ng-repeat). The problem started with this commit: 0a4912ea9c14b2924d9914a5108ae2c2f636e4ed

**Comment by underlog** [comment]
Hi, 

the approach does not work any more. It was supported accidentally and unreliably - further mutations of the bindings break the widget. You should use the built-in widget data-binding capabilities instead. 

We should update our documentation accordingly.
