### ISSUE TITLE
Avoid registering web components more than once

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-ui-core#1170]
Loading both kendo.all and kendo.web leads to the following error:
>Failed to execute 'registerElement' on 'Document': Registration failed for type 'kendo-surface'. A type with that name is already registered.

Reported in ticket 977441

**Comment by tapopov** [comment]
Commit 6082b028c2c1343d5ea8a64994cefb45f783498b re-introduced the issue and it is still reproducible.

**Comment by Snbidkar** [comment]
I am also getting such a error

**Comment by Snbidkar** [comment]
how to solve such a error while loading grid


Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'kendo-surface'. A type with that name is already registered.
