### ISSUE TITLE
kendo.mobile.view.js uses Angular debugging functions

### ISSUE THREAD

**Issue by 17cupsofcoffee** [telerik/kendo-ui-core#1171]
The Angular integration for the mobile view component uses element.scope(), [which returns undefined when debugging info is turned off](https://docs.angularjs.org/guide/production#disabling-debug-data). This causes the application to throw an error when navigating to a view with a controller for the second time, as [_invokeNgController()](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.mobile.view.js#L320) tries to get the element's scope using that method. It also seems to be used in the [destroy()](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.mobile.view.js#L129) function, although that hasn't caused me issues yet.

I found [another issue/commit from earlier in the year](https://github.com/telerik/kendo-ui-core/commit/f6f6d08d26b87f92e3f0041d297616aadb0b55f5) that seems to have fixed every other occurrence of this kind of issue, and searching for "element.scope" in this repo didn't seem to come up with any other results outside of the test suite, so I think this is the only thing stopping Kendo from working with debug mode off.

**Comment by underlog** [comment]
Thanks, I will check this out. We should store the scope somewhere instead of getting it from an element.

**Comment by 17cupsofcoffee** [comment]
Thanks!
