### ISSUE TITLE
MaskedTextBox does not move caret on Android 5.0.1 Samsung device

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#1172]
Customer reported that this issue can be reproduced in the online demos. More info is available in 976610. I was not able to reproduce the issue on any of the test devices, so please investigate it further.

I have set the invalid tag until further investigation is done.

**Comment by ggkrustev** [comment]
Reported in TicketID: 1055809. A working open-source widget could be found here - https://github.com/angular-ui/ui-mask
