### ISSUE TITLE
Blackberry: Popup is closed when trying to scroll the values

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1178]
Can be replicated on: [http://demos.telerik.com/kendo-ui/dropdownlist/remotedatasource](http://demos.telerik.com/kendo-ui/dropdownlist/remotedatasource)

Steps: 
Open the DropDown
Scroll the popup in order to see the values not currently visible

Reproduced on Blackberry 7 and 10
Reported in Ticket ID: 978012

**Comment by Sriraghu-Alapati** [comment]
Hi,
   Any updates on this issue from the team

**Comment by ggkrustev** [comment]
The issue is still in the low priority task queue. Currently, the issue is not planned for Q2 2016. I would suggest you monitor the "Milestone" state of the issue to see whether the issue is scheduled for fix.
