### ISSUE TITLE
JS error when adding new value after the widget's values were cleared

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1192]
Replicated on the latest build - ServerFiltering demo

Steps:
Remove the default values (Chang, Uncle Bob's...)
Click in the Products control

Result: Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by ggkrustev** [comment]
No need to remove items. The issue reproduces when user tries to open the popup,

**Comment by ggkrustev** [comment]
Fixed with 4f238d63bb07dfa8a58917c83bbe55c271d61ef0
