### ISSUE TITLE
TypeScript definitions is missing the binders definitions 

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-ui-core#1195]
https://github.com/borisyankov/DefinitelyTyped/blob/master/kendo-ui/kendo-ui.d.ts#L486

The module should include the widget module [listed here](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.binder.js#L311).

**Comment by zdravkov** [comment]
It is already available here - https://github.com/telerik/kendo-ui-core/blob/master/typescript/kendo.all.d.ts#L1413
