### ISSUE TITLE
kendoDropDownList doesn't inherting select element inline style properties to wrapper after initialization

### ISSUE THREAD

**Issue by Sajankumar005** [telerik/kendo-ui-core#1197]
kendo-ui dropdownlist using StylesText property insteadof cssText property while initializing and it using a function named object.Styles(object) insteadof jQuery([selector]).css(object) method. Both modifications are in same version v2013.3.1316. So it caused an issue that it doesn't inheriting css properties while intilizing the select element with inline styles.

**Comment by Sajankumar005** [comment]
v2013.3.1316
(e = n.wrap("<span />").parent(), e[0].style.StylesText = i.style.StylesText)
&&
t.wrapper = e.addClass("k-widget k-dropdown k-header").addClass(i.className).Styles("display", "")

VS

version  v2013.3.1316
(e = n.wrap("<span />").parent(), e[0].style.cssText = i.style.cssText)
&&
t.wrapper = e.addClass("k-widget k-dropdown k-header").addClass(i.className).css("display", "")

**Comment by ggkrustev** [comment]
Hi @Sajankumar005,

In general, we copy the styles to the wrapper using cssText property:
https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.dropdownlist.js#L1107

Could you attach a demo that shows the erroneous behavior?

**Comment by Sajankumar005** [comment]
Hi @ggkrustev 

I cant you show you the demo as per the security guidlines, but I can provide you the screenshot i've taken from the script file, Please take a look.


![kendo-issue](https://cloud.githubusercontent.com/assets/13799915/10628209/21f778a2-77e0-11e5-9308-80b0376fc97d.png)

**Comment by ggkrustev** [comment]
Hi @Sajankumar005,

Probably, I am missing something, but I couldn't find any tracks on the `StylesText` used in Kendo UI. Check this screencast that show the usage of cssText and that there is no `StylesText`:

- http://screencast.com/t/79ikUJk3
