### ISSUE TITLE
DatePicker does not apply correctly max value when in Brasilian timezone (GMT-03)

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#1203]
### Description
The DatePicker (Calendar in particular), does not set max value correctly when DST happens in the same day. In Brasilia timezone this result in not showing the max date.

Repro demo: http://dojo.telerik.com/amuju (open in GMT-3)
Screencast: http://screencast.com/t/PF3Zu0vPw

Reported in TicketID: 980425

**Comment by KirilNN** [comment]
fixed with the following commit: 75f6bfcce8b6e18b43a28b19520e280055cb3df5
