### ISSUE TITLE
Slider value is not updated accordingly as the handle position is changed quickly

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1225]
Happens when the slider is quickly dragged and dropped in the two opposite directions around the current value

[http://screencast.com/t/MnKcoySD9](http://screencast.com/t/MnKcoySD9) - after 0:15 can be observed that the drag handle is over "6" but slider value is still "4"

**Comment by KirilNN** [comment]
@naskog,

tried to reproduce issue in a stand alone example, but to no avail. Please try to extract a Dojo where the problem can be *steadily* reproduced, so we can investigate the problematic behavior.

Thanks!

**Comment by KirilNN** [comment]
The issue can be reproduced only with automated tests, and it is impossible to reproduce in a live scenario.
