### ISSUE TITLE
Gird , navigate event not firing

### ISSUE THREAD

**Issue by gauravsoni1** [telerik/kendo-ui-core#1227]
The kendo grid navigate event is not firing , this can be demonstrated by trying the navigate event example mentioned here [Kendo gird navigate event]( http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#events-navigate.)

**Comment by KirilNN** [comment]
Hi @gauravsoni1,

Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (Professional, UI for MVC, PHP, JSP) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI!
