### ISSUE TITLE
IE10: Disabled button is still clickable

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1245]
Steps:
Navigate to: [http://demos.telerik.com/kendo-ui/button/angular](http://demos.telerik.com/kendo-ui/button/angular)
Check "Disable"
Click "Support for ngDisabled" button

Result: The button switches to selected state

Repro video: [http://screencast.com/t/qnwJ2ltr7wG](http://screencast.com/t/qnwJ2ltr7wG)

**Comment by underlog** [comment]
No longer reproducible.
