### ISSUE TITLE
Selecting time generates wrong date if the OS date has changed

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-ui-core#1248]
Steps to reproduce:

1. Clear the widget's value
2. Change the OS clock date
3. Select a time from the DateTimePicker

Expected results:
The widget's value should be today's date (from OS clock) and the time selected from the picker

Actual results:
The date prior the OS clock change is used along with the selected time

Reported in ticket 986630

**Comment by KirilNN** [comment]
When the system date is changed, new Date() still returns the previously set date until the page is refreshed. This is a browser specific behavior that cannot be worked around.

**Comment by tapopov** [comment]
Actually the browser does get the new system time after a while (30 seconds or so) and the issue can be reproduced using the below example and steps:
[Example and workaround](http://dojo.telerik.com/@popov/ibAGe)
1 Run the code above with the console open
2 Pop open the picker you'll see today is correct
3 Move the clock forward a day (simulating it going past midnight)
4 Wait for the date to change in the console log (can take ~30 second)
5 Pop open the picker again and todays date will now be yesterday

**Comment by KirilNN** [comment]
After further consideration, we think that this method for detecting the current OS date is unreliable, so we will refrain from implementing it for now.
