### ISSUE TITLE
Kendo Bug - Grid - Sub column values got wrongly mapped when reordering the Column

### ISSUE THREAD

**Issue by ravikumarkendo** [telerik/kendo-ui-core#1257]
Check below  url
http://dojo.telerik.com/AguGO/2

1) Drag the column header "Ship City" along with its sub columns to two columns before.
2) After dragging is done, the sub column values are wrongly placed.
3) Screen shots were attached for the reference

![before-reorder](https://cloud.githubusercontent.com/assets/15846916/11163944/a0ec6c36-8b08-11e5-9d33-0b4806b9475a.jpg)

![after-reorder](https://cloud.githubusercontent.com/assets/15846916/11163943/9b8bfef0-8b08-11e5-9536-194a40580cf1.jpg)

**Comment by naskog** [comment]
Hi @ravikumarkendo,

Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (Professional, UI for MVC, PHP, JSP) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI!
