### ISSUE TITLE
Not able to perform native scroll on Win Phone devices

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1258]
Reproducible on: Win Phone 8 (IE); Win Phone 10 (Edge mobile)

Steps:
Navigate to [http://demos.telerik.com/kendo-ui/m/index](http://demos.telerik.com/kendo-ui/m/index)
Scroll down to the bottom of the demos list

Result: Scrolling is not possible (when "Web Preference" of the browser is set to the default "mobile version")
The issue seems to be introduced in 2015 Q3 SP1 (does not appear in 2015.3.930).

**Comment by naskog** [comment]
Reported in Ticket ID: 988195

**Comment by grantkiwi** [comment]
Hi, is there an ETA for this fix?

**Comment by grantkiwi** [comment]
Hi has this been fixed and released in an internal build? This was report 24 days ago!!
