### ISSUE TITLE
PanelBar latest change appears to cause problems with nested kendo angular directives

### ISSUE THREAD

**Issue by gxedwards** [telerik/kendo-ui-core#1265]
In the latest version there seems to be a conflict between the panel bar and nested multi select children. 

http://dojo.telerik.com/IPejO/3

Running under Kendo UI 2015 Q3 it correctly shows 1 multi select
Running under Kendo UI 2015 Q3 SP1 2 multi select controls are shown. 

1 extra multi select is created for every panel in the panel bar.

It appears that it is initializing multiple times

**Comment by KirilNN** [comment]
Hi @gxedwards,

This issue should be resolved with this:
https://github.com/telerik/kendo-ui-core/commit/3ddf5407924cbb473dc18c7cb3fd1589d78d1a9c

The patch will be available with the next internal build
