### ISSUE TITLE
Error on build on Windows 7 - '.' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by gxedwards** [telerik/kendo-ui-core#1266]
I just followed the instructions to GIT Clone but it fails on the step 'npm run build.'

I cleared everything out and ran in verbose mode to verify the same issue. Attached is the npm-debug log. The command line also says (which is not in the log) ''.' is not recognized as an internal or external command, operable program or batch file.'

[npm-debug.txt](https://github.com/telerik/kendo-ui-core/files/39173/npm-debug.txt)

Just wanted to verify that someone can build on windows

**Comment by gxedwards** [comment]
A colleague tried also on unix and got the following error

C:\development\kendo-ui-core\gulpfile.js:36
        .pipe(gulpIf((file) => file.path.match(/.less$/), license() ))
                            ^^
SyntaxError: Unexpected token =>

Looks like a typescript expression

**Comment by tsvetomir** [comment]
You need to use NodeJS 4.x in order to get the build running.

I'll update the README as it currently says "Node.js/npm latest".
