### ISSUE TITLE
MultiSelect. Loading new data when using Virtualization and scrolling on the Open Dialog 

### ISSUE THREAD

**Issue by gxedwards** [telerik/kendo-ui-core#1268]
I am trying to reload the data that is shown in a multi select and I am seeing strange behaviour when I have scrolled down on the popup window which appears to be related to the page size and scrolling in the popup.

This is a local datasource.

I have an example at the following

http://dojo.telerik.com/IwEXu/5

This works
1) Run script
2) Open popup  - scroll to the bottom and then the top
3) Close the popup
4) Click the load. This will load 100 items into the datasource
5) Open the popup and only 50 items will show

This fails
1) Run script
2) Open popup and scroll to the bottom - should be 50 values in the list (page size is 40)
3) Close the popup
4) Click the load. This will load 100 items into the datasource
5) Open the popup and only 50 items will show even though I have loaded 100 into the datasource

**Comment by gxedwards** [comment]
Appears to be some sort of issue with the way the scroller and paging interact which is not what I would expect

**Comment by ggkrustev** [comment]
Hi @gxedwards,

I reviewed the case and can confirm that the desired behavior is not supported for the time being. It, however, will work once this #1276 change is live. It will allow you to change the whole source at once like that:
```
multiselect.setDataSource(new kendo.data.DataSource({
        data: generate(100)
}));
```
