### ISSUE TITLE
Building local docs with Ruby 2.2 fails

### ISSUE THREAD

**Issue by dodumosu** [telerik/kendo-ui-core#1270]
Attempting to build the local docs with Homebrew Ruby (as at the time of writing, 2.2.3) fails with a NoMethodError. Investigation reveals that it's related to this issue (https://github.com/dtao/safe_yaml/issues/67), which happens with safe_yaml version 1.0.3. Upgrading locally to safe_yaml 1.0.4 fixed the issue.

**Comment by tsvetomir** [comment]
We're yet to migrate on a newer Ruby / Jenkins version. For the moment it only builds with Ruby 1.9.3
