### ISSUE TITLE
RangeSlider - JS error on slide

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1291]
Steps:
Navigate to [http://demos.telerik.com/kendo-ui/slider/events](http://demos.telerik.com/kendo-ui/slider/events)
Drag and drop the left handle of the  RangeSlider
Drag and drop the right handle of the  RangeSlider

Result: Uncaught TypeError: Cannot read property 'draggable' of undefined
This is regression introduced in 2015.3.1111 (not present in 2015.3.930)
Reported in Ticket ID: 991524

**Comment by KirilNN** [comment]
The problem is fixed and cannot be reproduced with the latest staging scripts

**Comment by jeremyhallden** [comment]
No fix for 2015.Q3?

**Comment by KirilNN** [comment]
Fixed with the latest internal build.
