### ISSUE TITLE
Still cannot disable menuButtons of splitButton in kendo.ui.ToolBar (since 2013)

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#1296]
See http://www.telerik.com/forums/cannot-disable-menubuttons-of-splitbutton

**Comment by underlog** [comment]
Hi,

Please notice that the issue tracker of this repository is meant to serve as a collaboration platform for the open source part of the Kendo UI project. We don't accept escalation of issues or feature requests here, unless a pull request is submitted.
