### ISSUE TITLE
Deprecated (removed?) create() "class methods"

### ISSUE THREAD

**Issue by dwiyatci** [telerik/kendo-ui-core#1302]
If I remember correctly, a few months ago, there was this "class methods" called `create()` in `kendo.Class`, `kendo.ui.Widget` and anything inherits from `kendo.ui.Widget` that serves as syntactic sugar for creating a new instance.

I just wanted to know what's the reason behind the removal of this `create()` class methods. Thought it was kinda a step forward to create new instances of objects without `new()`-ing things.

**Comment by gyoshev** [comment]
Hello @dwiyatci ! I don't believe that such methods have existed in the framework. Can you point to the commit that removes such methods, or where they are documented? There is a [`Class.extend`](https://github.com/telerik/kendo-ui-core/blob/4a678de887a1505ac7c4311ade29956b776aae0a/src/kendo.core.js#L44), which allows you to extend a class, but no `create`.

**Comment by dwiyatci** [comment]
Oops, sorry. I guess I was daydreaming back then. :sweat_smile: I may have misread the API doc from [DataSource .create()](http://docs.telerik.com/kendo-ui/api/javascript/data/datasource#create) instead.

**Comment by gyoshev** [comment]
Since it's not available, you can use a [generic method for constructing objects](http://dojo.telerik.com/@gyoshev/ESOZe) -- and attach it to the widget classes if necessary.
