### ISSUE TITLE
Popover .close() method does not fire the close event

### ISSUE THREAD

**Issue by venelinpetrov** [telerik/kendo-ui-core#1306]
If you try to grammatically close the popup the close event does not fire.
Here is an example: http://dojo.telerik.com/@vpetrov/ewIjI/3

1. Open the popover
2. Blur --> close event fires
3. Open the popover
4. Click close button --> close event doesn't fire

**Comment by KirilNN** [comment]
Hi @venelinpetrov,

In general calling the api methods will not fire the respective events in Kendo UI. So we consider this behavior expected.

**Comment by venelinpetrov** [comment]
Documentation?

**Comment by KirilNN** [comment]
There is no explicit documentation stating this, but there are plenty of resources on the internet, where this exact behavior is discussed. We will consider adding a more explicit information somewhere.

**Comment by venelinpetrov** [comment]
I know, I implicitly asked you to include this information in more centralized place like official documentation, because developers (especially with background in another technology) expect quite the opposite behavior.

**Comment by KirilNN** [comment]
Documentation is added. It will be live on the following page after the build is finished:

http://docs.telerik.com/kendo-ui/intro/installation/events-and-methods
