### ISSUE TITLE
iOS: Not able to swipe-open the Drawer after back navigation

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1315]
Happens only when data-click-on="down" is set for the Back button

Reproducible on:
[http://dojo.telerik.com/ugIMi/2](http://dojo.telerik.com/ugIMi/2)

Steps:
Open the Drawer
Go to "Settings"
Navigate Back (using the button from the NavBar)

Result:
It is not possible to open the Drawer by swiping

Reported in Ticket ID: 992078

**Comment by naskog** [comment]
Another report in Ticket ID: 995456
[http://dojo.telerik.com/eSiZU](http://dojo.telerik.com/eSiZU)

**Comment by sspasova** [comment]
Closing this as the mobile suite is now deprecated. You can read more information here: https://docs.telerik.com/kendo-ui/controls/hybrid/introduction
