### ISSUE TITLE
kendoGrid filter isn't cleared after deleting value

### ISSUE THREAD

**Issue by torfeld6** [telerik/kendo-ui-core#1323]
Steps:
1. Click on the "Filter" button.
2. Select any type of filter.
3. Enter value and click on the "Filter" button.
4. When result displayed open filter again, delete value and click on the "Filter" button.
5. Observe results.

Actual result: Result from step 3 still displayed.
Expected result: Results should be cleared.

Screen recording: http://we.tl/ZQUE9bw7BP

**Comment by KirilNN** [comment]
Hi @torfeld6,

Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (Professional, UI for MVC, PHP, JSP) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI!

**Comment by torfeld6** [comment]
Hi @KirilNN 

Thanks for the quick response. I created a thread in the mentioned forum.

Bests
Joshua

**Comment by KirilNN** [comment]
Hi @torfeld6,

Thanks for that!
