### ISSUE TITLE
Selected token with long value exceeds MultiSelect 's width

### ISSUE THREAD

**Issue by gartmeier** [telerik/kendo-ui-core#1328]
### Bug report
If the value is long and without whitespace, the block goes beyond the width of the select.

### Reproduction of the problem
Dojo: https://dojo.telerik.com/eMeRAqaH

### Current behavior
![image](https://user-images.githubusercontent.com/6614183/49147991-d1380000-f30e-11e8-8fa1-db866a086bc2.png)

### Expected/desired behavior
Token does not exceed MultiSelect's width by:
 - Trimming token text with ellipsis OR
 - Token becomes multiple lines high:
![image](https://user-images.githubusercontent.com/6614183/49148091-15c39b80-f30f-11e8-8497-fa7c3a971579.png)

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by ggkrustev** [comment]
Reported also in TicketID: 1068212

**Comment by nenchef** [comment]
We are planning to add a Chip component to the suite, hence, the MultiSelect tokens will be replaced by it. The described issue won't be replicable, as the Chip component will automatically care about its size.

**Comment by eyupyusein** [comment]
Doesn't seem to be reproduced in the latest version with the new rendering.

**Comment by dtopuzov** [comment]
I can confirm that it looks ok with `2022.1.119`.
