### ISSUE TITLE
ComboBox virtualization filtering not working accordingly

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1331]
Issue is only present internally for Q1 2016

Steps:
Navigate to ComboBox virtualization demo
Type "Ern"
Press Enter

Result: Nothing is selected
Expected: "Ernst Handel" is selected

**Comment by ggkrustev** [comment]
The issue is reproducible only when filtering is not enabled (filter: 'none'). In general, this is not very common scenario for the virtualized list. Nevertheless, we will address it, but I will lower the severity level.
