### ISSUE TITLE
Using MVVM with an observable object with "trigger" as a property doesn't work

### ISSUE THREAD

**Issue by zshall** [telerik/kendo-ui-core#1339]
If you have a `kendo.observable` JSON object with a property named `trigger` that you want to edit using an MVVM template and `kendo.bind()`, this property will cause an error upon binding: `n.trigger is not a function.`

[Dojo Example](http://dojo.telerik.com/Osili)

When this page is run, there are two views and two observable objects. The first one uses a text input data-bound to the property `_trigger` (some word other than `trigger`) and the second uses `trigger`. Notice how the second input field is blank when the example is run, and in the console we get this message:

```
TypeError: n.trigger is not a function. (In 'n.trigger(ye,{field:e})', 'n.trigger' is "Lorem Ipsum")
```

**Comment by naskog** [comment]
Thank you for your feedback, @zshall. Trigger method is internally used to fire events. It is a kind of "reserved" field. 
For details please refer to the api reference:
[http://docs.telerik.com/kendo-ui/api/javascript/observable#methods-trigger](http://docs.telerik.com/kendo-ui/api/javascript/observable#methods-trigger)
