### ISSUE TITLE
Inconsistent filling of the available space on init and on re-size

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#1341]
To reproduce:
1. Go to the following [Dojo](http://dojo.telerik.com/aGaVI)
2. Make the right side large enough to show all the buttons (including Left/Center/Right and Bold/Italic/Underline)
3. Now move the slider to the right - the buttons are removed (alone or in groups) according the order (reverse order) they appear on the toolbar...
4. Make the toolbar hide both groups (Left/Center/Right and Bold/Italic/Underline), but leave enough empty space to fit the Bold/Italic/Underline trio
5. Click on 'Run' button

You can see that after 5. the toolbar hides the Left/Center/Right group and displays the Bold/Italic/Underline group...
 Kendo UI 2017.3.1026
Browsers: all

**Comment by Iankodj** [comment]
The scenario is discussed with @lkarakoleva and it was decided to follow the resize logic for hiding/showing tools on initialization. 

I.e., hiding tools in order disregarding sufficient space for items after the hidden one.
