### ISSUE TITLE
Virtualized MultiSelect does not fire its change event if there are no initially selected values

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#1342]
Example: http://dojo.telerik.com/owicO

Select any value, note that the change event does not fire.

**Comment by simonwaterer** [comment]
But if the virtualized MultiSelect is value bound to an initially empty array, then the array won't be updated at all as items are selected or unselected.

Example: http://dojo.telerik.com/@simon_waterer/IFaMu

If you comment out the code that configures it to be virtual, you will see that it then behaves properly.

I added a test here https://github.com/simonwaterer/kendo-ui-core/commit/5298faf5af535846a5971e8092564f1ba2902469 if you would like to check it.

Likewise, if you comment out the code that configures it to be virtual, the test will start to pass.

Please can you check this?
