### ISSUE TITLE
Cant open PSD file in Photoshop CC 2015

### ISSUE THREAD

**Issue by raashidA** [telerik/kendo-ui-core#1347]
![image](https://cloud.githubusercontent.com/assets/2629666/12163584/e0d0357a-b534-11e5-9252-8926abbe5fc1.png)

Some error coming when i trying open PSD file in Photoshop CC 2015. Please check and upgrade the photoshop files / I tried to open ( sprite.blueopal.psd & sprite.blueopal @2x.psd)

**Comment by yordanov** [comment]
Hello @raashidA,

We've just tested the PSDs in Photoshop CC (2015.1.1 Release) and they all seem be just fine. Everything works as expected:

![psd-in-pscc](https://cloud.githubusercontent.com/assets/1118895/12167246/b55b2d74-b533-11e5-8271-9748ac80ad97.png)

It might be that the file is corrupted on disk. Or the system somehow interprets the two dots in the file name as different file type. Can you please try downloading the files again and/or renaming them e.g. from sprite.blueopal.psd to blueopal.psd.
