### ISSUE TITLE
Impossible to select all day event by directional key kendo scheduler

### ISSUE THREAD

**Issue by furyscript** [telerik/kendo-ui-core#1359]
I have alreay open a question to `SackOverflow`, but nobody ask me.

Check this: http://stackoverflow.com/questions/34740068/impossible-to-select-all-day-event-by-directional-key-kendo-scheduler

Thanks, 
FS

**Comment by underlog** [comment]
Hi,

Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (Professional, UI for MVC, PHP, JSP) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI!
