### ISSUE TITLE
Question About QR Code

### ISSUE THREAD

**Issue by vdanelia** [telerik/kendo-ui-core#1364]
I want to create QR Code for the site, I found and downloaded file "kendo.dataviz.qrcode.min.js" But can't make it work, then downloaded "kendo.all.min.js" and worked perfectly, tested every option.
Now I have some questions:

How to add additional value? 
For example...

$("#qrCode").kendoQRCode({
value: "mailto:mail@mymail.com",
value: "url:myweb.com",  
value: "tel:577493586",
etc.

Can't make it to work together, please help and suggest me how to add one or more values like vcard or mecard, something like

Thank You in Advanced!

**Comment by vdanelia** [comment]
I only Need QR Code Component :)

**Comment by underlog** [comment]
Hi, 

the QR code component and an accompanying support (like your current query) is part of our commercial Kendo UI offering. More details about the pricing are [available here](http://www.telerik.com/kendo-ui#GeneralContent_C282_Col00).

**Comment by vdanelia** [comment]
Hello I read it and downloaded and testing, but I cant manage this QR Code some instances and tried to post here for someone to explain it well...

Thank you for your reply
