### ISSUE TITLE
AMD module names are incorrect in the minified files available on CDN

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1367]
As a result, the requirejs integration from our examples no longer works. The string substitution of the module names does not work as expected.

**Comment by jlchereau** [comment]
As far as webpack is concerned, new 2016.1.112 AMD definitions in non-minified js files of the zipped commercial version also break builds that used to work with previous versions of Kendo UI.

See http://www.telerik.com/forums/new-amd-definitions-in-v2016-1-112-are-incompatible-with-webpack.

**Comment by 17cupsofcoffee** [comment]
I think the issue is present in the minified versions in the zipped download as well, not just the CDN. I'm using Webpack to shim and load kendo.all.min.js, which used to not contain AMD definitions, whereas now my build is throwing up several 'could not resolve module' errors. I was able to get around it using imports-loader to disable AMD, but it gave me a bit of a shock!

**Comment by underlog** [comment]
@17cupsofcoffee - my bad, the title may be misleading indeed. The problem affects the zip versions, too (they are the same in fact). 

@jlchereau I think that the best thing we can do is to provide a webpack example in our documentation. Will try to do that shortly.

**Comment by underlog** [comment]
Fix here - bbcd3d4.

**Comment by jlchereau** [comment]
Hi. I know this site is about kendo-ui-core and not the commercial version, but you might be interested to know that same *src* files (kendo.listview.js, kendo.menu.js) have different UMD wrappers in the commercial version and in the core version and if I replace the former (commercial) by the later (core), it fixes webpack errors for these files.

**Comment by underlog** [comment]
Just documented the suggested way of webpack bundling here - https://github.com/telerik/kendo-ui-core/blob/master/docs/third-party/webpack/index.md.

Using ./ would work (and is better), but we are shipping several "composite" widgets in the commercial distribution. The charts for example, are assembled from multiple modules. Because of this, the are shipping kendo.chart.js file (the one in the `src` folder) contains **multiple named modules** in it - these modules should be named ones. Since we are using the same build script for all widgets (available in this repo, too), this affects the single-file widgets too. 

Hope this makes sense. Let me know if you need any help with the problem. Unfortunately, the last fix made for the cultures AMD (https://github.com/telerik/kendo-ui-core/commit/abbf7c040a6e9210c3581527f3d71438aac19b72) did not make it in today's internal build.

**Comment by 17cupsofcoffee** [comment]
That example is really helpful, thanks for taking the time to write it up :+1:

**Comment by jlchereau** [comment]
All good. Thx.

**Comment by underlog** [comment]
As I have linked this issue at several locations, worth mentioning is the SystemJS support article:

https://github.com/telerik/kendo-ui-core/blob/master/docs/third-party/systemjs.md

**Comment by nathansmith** [comment]
Maybe this is a dumb question, but is this still affecting the Kendo professional trial download?

I'm attempting to use the latest `2016.1.112` with RequireJS, but it's not working.

(Yes, I know RequireJS is old and Webpack is better. But this is a "legacy" app.)

**Comment by JohannesHoppe** [comment]
Yes, this bug is not fixed!
Pro version more or less breaks with `require.js`.

```js
// BEFORE: kendo.button.js
define([ "./kendo.core" ], f); // <!-- yay, this resolves to a relative path
```

```js
// AFTER: kendo.button.js
define('kendo.button', ['kendo.core'], f);  // <!-- doh! this resolves to my baseUrl: '/',
```
This fordes me to write a really BIG path-mapping in my `require.config.js`.
Thanks! :-1:

**Comment by JohannesHoppe** [comment]
ok, this is a very detailed explanation why they broke the AMD packages by design:
https://github.com/telerik/kendo-ui-core/issues/2080#issuecomment-240777744

Conclusion: a big [require config-paths](http://requirejs.org/docs/api.html#config-paths) mapping to the rescue!
