### ISSUE TITLE
Popup in IE11 is not positioned correctly when placed in a scrolled container (jQuery 1.12.0/2.2.0)

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#1375]
### Description
It seems that the popup is misplaced due to incorrect `offset` information returned from jQuery 1.12

Repro demo: http://dojo.telerik.com/OviKu/2
Steps:
1. Resize IE to show a vertical scrollbar inside the result page
2. Scroll the container
3. Open the popup

Reported in TicketID: 1002498

**Comment by ggkrustev** [comment]
The issue seems to affected jQuery UI too:
https://github.com/jquery/jquery/issues/2828

**Comment by ggkrustev** [comment]
After further investigation, it seems that $.position() method is broken in IE11. The affected jQuery versions are `1.12.0` and `2.2.0`. According jQuery team, they will fix the issue in a patch version `1.12.1` - https://github.com/jquery/jquery/issues/2836#issuecomment-171900265

Based on this, we will not fix that part on our side, as patching the code for particular jQuery version will be impossible to maintain.

**Comment by Antonnz** [comment]
Note that this also affects Google Chrome 47 on Ubuntu 14.04 64bit in some way, not just IE.
(https://issues.apache.org/jira/browse/WICKET-6100):

     Uncaught TypeError: Cannot read property 'opener' of null
     jquery-1.12.0-ver-1456109363000.js:6704
