### ISSUE TITLE
Wrong k-content background-color in Moonlight theme

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-ui-core#1376]
Background-color should be: #414550

**Comment by jlchereau** [comment]
Also .k-input misses a border IMHO

Without border (AS IS):

![image](https://cloud.githubusercontent.com/assets/2556751/12425970/34382e22-becf-11e5-8079-35e5275cd1af.png)

With border (Suggested correction):

![image](https://cloud.githubusercontent.com/assets/2556751/12426030/78408984-becf-11e5-9379-1d2c1683f7c8.png)

**Comment by yordanov** [comment]
It is the main background that is wrong, resulting in invisible borders. This is the initial design:

![pickers](https://cloud.githubusercontent.com/assets/1118895/12545629/abba8554-c34c-11e5-90ed-4d0e1264b571.png)
