### ISSUE TITLE
Can't load kendo.directives with angulaAMD for this version, it work with old version (2015.Q3)

### ISSUE THREAD

**Issue by vknvnn** [telerik/kendo-ui-core#1378]
<meta charset="utf-8" />
    <link rel="stylesheet" href="//cdn.kendostatic.com/2016.1.112/styles/kendo.common.min.css" />
    <link rel="stylesheet" href="//cdn.kendostatic.com/2016.1.112/styles/kendo.default.min.css" />

    <script src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.16/require.min.js"></script>

    <script>
      require.config({
        paths: {
         
          kendo: "//cdn.kendostatic.com/2016.1.112/js", // 2015.3.1111 it work with old version
          jquery: "//code.jquery.com/jquery-1.9.1.min",
          angular: "//ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min"
        },
        shim: {
          "kendo/kendo.core.min": {
            deps: [ "jquery", "angular" ]
          },
          angular: {
            deps: [ "jquery" ],
            exports: "angular"
          }
        }
      });
    </script>

    
    <script>
      require([ "kendo/kendo.datepicker.min", "kendo/kendo.angular.min" ], function(){
        var app = angular.module("MyApp", [ "kendo.directives" ]);
        app.controller("MyCtrl", [ "$scope", function($scope){
          $scope.test = "Hello World";
        }]);

        // bootstrap Angular when document has finished loading
        $(document).ready(function(){
          angular.bootstrap(document, [ "MyApp" ]);
        });
      });
    </script>

**Comment by underlog** [comment]
Please test the same setup after the fix here:

https://github.com/telerik/kendo-ui-core/issues/1367

**Comment by vknvnn** [comment]
i think, it will not working with (angularjs + angularamd + requirejs)

do u think?

**Comment by jvinhit** [comment]
Yeap, this not work!!! AngularAMD not work with kendo
