### ISSUE TITLE
Compiled AMD modules no longer export `kendo`

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1380]
this has broken several customers' setups who rely on the kendo classes from the import.

**Comment by andreasandreou** [comment]
in what release will this fix be available?
I checked 2016.1.125 and it's still not there.

**Comment by underlog** [comment]
The fix was done on January 20th, so it should be available. I may suggest that you submit a support ticket with a reproduction of your check, as I may be missing something in this case.
