### ISSUE TITLE
Kendo Numeric text box automatically changes the last odd digit to 0 if the length is more than 16

### ISSUE THREAD

**Issue by jayesh-jayakumar** [telerik/kendo-ui-core#1381]
Hello All,
 I want to pull your attention to another issue related to rounding.

Today while testing, I inserted the 12345678987654321 number to a kendo numeric textbox having configuration (min: 0, format: "#", decimal: 0). To my surprise on tabbing, the number got changed automatically to 12345678987654320. I also noticed the same behavior happens only when the 17th digit is an odd number (1,3,5,7,9).

1 -> 0
3 -> 4
5 -> 4
7 -> 8
9 -> 8

Is this a issue with my configuration or a bug with Kendo Numeric text box control ?

Snippet goes here .. : http://dojo.telerik.com/@jayesh-jayakumar/azULU

**Comment by ggkrustev** [comment]
The issue is related to telerik/kendo-ui-core#132 issue. As it was described there, the issue is related to the JavaScript Number limitation.

The discussed behavior is not related to the widget itself and as such I will close the thread. Please feel free to comment to the related #132 thread.
