### ISSUE TITLE
Keep custom filters when filtration is not enabled

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#1382]
### Description
Widget will clear the applied filter expressions that match the `dataValueField` option when developer tries to select new value using `value` method

Repro demo: http://dojo.telerik.com/OLaxu/4

Reported in TicketID: 1003231

**Comment by witoldlitwin** [comment]
I'm experiencing a similar problem with MultiSelect - everything is cleared when I try to select new value using `value` method

**Comment by ggkrustev** [comment]
The fix also affect `MultiSelect`. Check the Q1 2016 SP1 release once it is out
