### ISSUE TITLE
Zurb Foundation theme

### ISSUE THREAD

**Issue by milmazz** [telerik/kendo-ui-core#1389]
According to [this page][1]:

> All components integrate well with grid-layout frameworks, such as Bootstrap and Zurb Foundation

I was wondering if you have plans to develop a theme for [Zurb Foundation](http://foundation.zurb.com/), the same way as you did with Bootstrap. If not, I want to know if you're interested in something like this, I can give it a shot. 

[1]: http://www.telerik.com/kendo-ui/responsive-features

**Comment by yordanov** [comment]
Thank you for the suggestion @milmazz. We've just added it to our [feedback portal](http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/11586021-zurb-foundation-inspired-ui-theme) to check if such UI theme would be of interest to our community. 

Currently, we play nice with the Foundation Grid layout only (no additional foundation styles loaded).  Foundation framework styling (e.g. typography, forms, tables) clashes and overrides Kendo UI’s, as  it uses heavier global CSS selectors like `table` or `input[type="text"]`. That said, we work with Foundation on a layout level only and we do not conform to their theme (as we do with Bootstrap).
