### ISSUE TITLE
k-ng-model binding does not work if value is not present in first data page

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#1401]
Example: http://dojo.telerik.com/ohoma/2

Expected result: Values with IDs [10265, 10363] are pre-selected

The example works fine if the value is present in 1st data page e.g. when `$scope.selectedIds = [10265]`

**Comment by IlBaffo** [comment]
We have this same problem with filtered DropDownLists and, from our tests, using virtualization is possible to resolve the values correctly but there are two major issues that prevented us to adopt this solution.
We found that, if you set the values in initialization (in the options object) those are correctly displayed but, if you set them through the "value" function or the Angular's model, the behaviour is the one you are referring to.

1. we would like to directly set values from code without making any http request (when the widget's value is not primitive)
2. making ajax requests for every value (with primitive values) is highly inefficient
3. valueMapper tries to load the page containing the item by its Index in the datasource and this is impractical for us (in the server side)

I therefore propose to:

1. disable values resolution for non-primitive widgets (either by default or with an option)
2. change or add a new behaviour for the "valueMapper" function to get all the values keys and expect an array of the resolved objects in the same order with "null" for objects not resolved.
3. optionally, when the datasource is ODATA and the schema:id property is set, the widget could resolve the values without needing any "valueMapper" function

Pseudo-code for the point n 2:
```
valuesMapper: function(options) {
  var value = options.values // Values IDs: [1, 2, 3]
  $.ajax({
	url: "/API/Entity?$filter=(ID eq 1) or (ID eq 2) or (ID eq 3)", // Composed with the IDs in options.values
	type: "GET"
  })
	.done(function (data) {
		/* Merge requested values with returned values
		 * If 1 and 3 are resolved, the return array would be:
		 * [ { ID: 1, ... }, null, { ID: 3, ...}]
		 */		
		var resolvedValues = options.values.map(function(id) {
			var resolvedValue = data.filter(function(d) {
				return d.ID === id;				
			})[0];
			return resolvedValue || null;
		});
		options.success(resolvedValues);
	});
}
```

**Comment by IlBaffo** [comment]
For anyone looking for a workaround to this, we have developed a horrible (but working) solution that resolves currently selected codes and appends them to the datasource's result.
This is roughly our solution applied to @valchev 's initial sample code: http://dojo.telerik.com/ICoFI

**Comment by valchev** [comment]
The original issue is invalid. The problem is with the example and the way `valueMapper` function is implemented.

In the original example the `valueMapper` does not return the indexes of the dataItems that correspond to the values hence the widget cannot resolve and display the selected tags.

Here is an update of the original example with modified `valueMapper` where the scenario works as expected: http://dojo.telerik.com/ohoma/6

@IlBaffo we will change the current virtualization logic and provide an option to use it without a `valueMapper`. The corresponding enhancement is scheduled for the next official release: telerik/kendo-ui-core#1659
