### ISSUE TITLE
Formatting numbers on groups gives unexpected output

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-ui-core#1407]
Formatting numbers on groups gives unexpected output as seen in the following demo below:

Add this code in dojo:
console.log(kendo.format("{0:#,##0}", 11111111111111));  

Output using v2016.1.112:
1,1111111111111

Output using v2015.3.1111:
11,111,111,111,111

Reported in ticket: #1004584
Issue is reproducible after this commit: #1015

**Comment by tsvetomir** [comment]
Isn't this the infamous "indian grouping" feature?

**Comment by ggkrustev** [comment]
It seems to be a bug that occur after we implemented the #1015 feature. It definitely should work, if the format is shorter than the number.
