### ISSUE TITLE
RequireJS does not load Kendo scripts when used along with angular

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#1409]
The following setup works with Q3 SP version and does not work with 2015.1.201 version:

require.config({
          paths: {
			"jquery": "http://code.jquery.com/jquery-1.9.1.min",
            "angular": "https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min",
            "kendo": "../require/dist/js/kendo/kendo.all.min"
          },
          shim: {
            "angular": { deps: ["jquery"] },
            "kendo": { deps: ["angular"] }
          }
        });

**Comment by tsvetomir** [comment]
A baseUrl must be set with the new version. See the [updated instructions](http://docs.telerik.com/kendo-ui/third-party/using-kendo-with-requirejs#load-kendo-ui-using-requirejs).

**Comment by KirilNN** [comment]
The the following is obsolete?

http://docs.telerik.com/kendo-ui/third-party/using-kendo-with-requirejs#use-angularjs-and-kendo-ui-with-requirejs

**Comment by IlBaffo** [comment]
With the latest internal Build (2016.1.118) I am using this configuration and it works.
I know that this is not beautiful but I had not enough time to investigate a better solution.

```
{
    baseUrl: "/app",
    waitSeconds: 60,
    paths: {
        "angular": "libs/angular.min",		
        "kendo.core": "libs/kendo/kendo.web.min",
        "kendo.web": "libs/kendo/kendo.web.min",
        "kendo.angular": "libs/kendo/kendo.web.min",
        "kendoCulture": "libs/kendo/cultures/kendo.culture.it-IT.min",
        "kendoMessage": "libs/kendo/messages/kendo.messages.it-IT.min",
        "jquery": "libs/jquery-2.1.4.min"
    },
    map: {
        '*': {
            'kendo': 'kendo.core'
        }
    },
    shim: {
        "kendo.core": { deps: ["jquery"], exports: "kendo" },
        "kendo.angular": { deps: ["kendo.core"], exports: "kendo" },
        "kendoCulture": { deps: ["kendo.core"] },
        "kendoMessage": { deps: ["kendo.core"] },
        "angular": { deps: ["jquery"], exports: "angular" }
    }
}
```

```
define(["angular", "kendo", "kendo.web", "kendoCulture", "kendoMessage"], function (angular, kendo) {
    'use strict';

    kendo.culture('it-IT');	
	
	var app = angular.module('MyApp', ['kendo.directives']);
});
```

**Comment by KirilNN** [comment]
There is an updated example here:

http://docs.telerik.com/kendo-ui/third-party/using-kendo-with-requirejs#use-angularjs-and-kendo-ui-with-requirejs

please refer to it for the correct configuration
