### ISSUE TITLE
upArrowText and downArrowText are not localizable

### ISSUE THREAD

**Issue by IlBaffo** [telerik/kendo-ui-core#1410]
The tooltips of the up and down arrows in the NumericTextBox are always displayed in English, even when kendo.culture is set to another language (with the proper culture and messages files included).

This is a working workaround for version "2016.1.118"  to be put in "kendo.messages.it-IT.js".
```
/* NumericTextBox arrows tooltips */
if (kendo.ui.NumericTextBox) {
    kendo.ui.NumericTextBox.prototype.options =
    $.extend(true, kendo.ui.NumericTextBox.prototype.options, {
        "upArrowText": "Incrementa valore",
        "downArrowText": "Decrementa valore"
    });
}
```
For a proper fix, these options should be nested in a "messages" object like the other widgets, I think.

I hope I didn't report anything wrong as this is my first opened issue, thank you.

**Comment by ggkrustev** [comment]
This seems to be resolved in Q2 2016 SP2:

http://dojo.telerik.com/eleYa
