### ISSUE TITLE
Grid is not rendered correctly on Edge when Material theme is used

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-ui-core#1419]
Grid is not rendered correctly on Edge when Material theme is used - when grouping and scrolling is applied, the "k-group-cell" cells shows small dots as seen below. Possible solution is to change the "text-overflow" CSS property to "clip".

![image](https://cloud.githubusercontent.com/assets/2195951/12841428/7436a9a4-cbf4-11e5-9c22-c0f4ad9b1764.png)

Demo: http://dojo.telerik.com/OMODI
TIcket: #1008047

**Comment by inikolova** [comment]
Fixed. Master commit: 4fdb9979b34c4fbb5
