### ISSUE TITLE
Grid pager showing wrongly

### ISSUE THREAD

**Issue by mfidemraizer** [telerik/kendo-ui-core#1423]
I'm experiencing some issue when using Kendo UI Grid. See the following screenshot:

![Grid](http://i67.tinypic.com/2miahh.png)

I'm including both `kendo.common.core.css` and `kendo.material.css` in my Web app.

Is there any step I can do to fix this or it might be a bug?

Thank you in advance! ;)

**Comment by gyoshev** [comment]
The Kendo UI Grid is not part of kendo-ui-core, and this repository is for issues with core widgets only. Feel free to open a support ticket.
