### ISSUE TITLE
JS error after selected items are cleared through the API

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#1424]
Example: http://dojo.telerik.com/@ben.buhr/owuzi/2

Steps:

1. Filter the multi select to a value that is outside of the initial load. (For example: Ernst)
2. Select the value.
3. Close the multi select list.
4. Click the Clear Orders button.

JS error is thrown.

**Comment by valchev** [comment]
Seems to be fixed in the latest version.

**Comment by harlankoehn** [comment]
@valchev I'm having this problem and wondering where the fix is. Is there a commit or pull request so I can see what's modified? Or any idea when 2016.Q3 will land?
