### ISSUE TITLE
Mask is not obeyed in Win Phone 10 (Edge)

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1427]
Navigate to : [http://demos.telerik.com/kendo-ui/maskedtextbox/index]http://demos.telerik.com/kendo-ui/maskedtextbox/index)

Tap in the "Phone number" field and type some text (NOT numbers)
Result: The text is not rejected - it appears after the end of the control

**Comment by MilenaCh** [comment]
Duplicate item https://github.com/telerik/kendo-ui-core/issues/826
