### ISSUE TITLE
requirejs, knockout-kendo and KendoUI 2016.1.112

### ISSUE THREAD

**Issue by crashnick16** [telerik/kendo-ui-core#1428]
KendoUI  version 2016.1.112 does not seem to work with requirejs and knockout kendo.
Getting "Uncaught TypeError: Cannot read property 'data' of undefined" when running.

I found that the library is referencing jquery as "jquery.min" internally but even after renaming this it still does not seem to work.

Any ideas?

**Comment by underlog** [comment]
This is resolved in #1379
