### ISSUE TITLE
Data Source may be set twice on widgets in Angular

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#1433]
In the following [test snippet](http://dojo.telerik.com/@tsvetomir/UciGA) the "fetching data for bar" message should appear only once.

**Comment by valchev** [comment]
The same issue was reported by client in ticket 1035059

Example: http://dojo.telerik.com/akUHE (use the button to change the Grid's dataSource)

It seems that this is a regression from v2015.1.318 ([working example with 2015.1.318](http://dojo.telerik.com/akUHE/5))

**Comment by 807811b0-1373-11e5-b60b-1697f925ec7b** [comment]
7 months and this issue is still open. I hope this can be fixed by end of year.
