### ISSUE TITLE
draggable container feature does not work as expected in AngularJS

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-ui-core#1435]
http://dojo.telerik.com/UVodU/3

Strange thing that it works as expected with inline styles.

**Comment by zdravkov** [comment]
The issue was caused by the fact that we use jQuery reference when passing the 'dragContainer'. With the new [feature](https://github.com/telerik/kendo-ui-core/issues/3877) the issue is working correctly when passing a string in the following line:
  `$scope.dragContainer = ".demo-section";`
