### ISSUE TITLE
Focus state styles should not be shown on hover

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-ui-core#1437]
Box-shadow styles should not be visible on mouse hover when navigatable:true; property is not set:

![focus-state](https://cloud.githubusercontent.com/assets/1118895/12981095/e70788ac-d0e7-11e5-88f6-5954e134d2c8.jpg)

See this dojo for reference: http://dojo.telerik.com/@yordanov/oqixu

**Comment by inikolova** [comment]
Moved to the private repo.
