### ISSUE TITLE
Native scrolling enforces header <-> footer position switch on Android

### ISSUE THREAD

**Issue by Lanayx** [telerik/kendo-ui-core#1443]
This inversion behavior should be specific to the Android theme only. Please remove it from the base logic and styles or make configurable, so one can disable it on app start while still using native scrolling.

**Comment by underlog** [comment]
I am not sure that I understand that. May you please provide an example of the problem? In addition to that, our documentation provides the means to [override this behavior using CSS](http://docs.telerik.com/kendo-ui/controls/hybrid/application#place-the-tabstrip-at-the-bottom-in-android).

**Comment by Lanayx** [comment]
Yes, I did found this link, which works with disabled native scrolling. If I enable it, flexbox is no longer there and this solution doesn't work, because of
1. this style [here](https://github.com/telerik/kendo-ui-core/blob/master/styles/mobile/common/base.less)

```
.km-native-scrolling .km-android .km-header
{
    top: auto;
    bottom: 0;
}
```

2. this function [here](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.mobile.view.js)
```
 _padIfNativeScrolling: function() {
            if (mobile.appLevelNativeScrolling()) {
                var isAndroid = kendo.support.mobileOS && kendo.support.mobileOS.android,
                    skin = mobile.application.skin() || "",
                    isAndroidForced = mobile.application.os.android || (skin.indexOf("android") > -1),
                    hasPlatformIndependentSkin = skin === "flat" || (skin.indexOf("material") > -1),
                    topContainer = (isAndroid || isAndroidForced) && (!hasPlatformIndependentSkin) ? "footer" : "header",
                    bottomContainer = (isAndroid || isAndroidForced) && (!hasPlatformIndependentSkin) ? "header" : "footer";

                this.content.css({
                    paddingTop: this[topContainer].height(),
                    paddingBottom: this[bottomContainer].height()
                });
            }
        },
```

**Comment by underlog** [comment]
I see what you mean. In general, the Android theme is *meant* to switch headers and footers. If I understand your case correctly you want to:

- use the android theme
- use app level native scrolling
- yet, switch the headers and footers like the "normal" theme

If so, then this is not supported at the moment. Notice that the "classic" android theme is quite dated - we cover the current styling via the material mobile skin. 

In case you are interested in this feature, you may consider submitting a pull request - please check the contribution guide for that.

**Comment by Lanayx** [comment]
No, I don't use android theme (actually I don't use any theme), that's why I asked to remove this functionality from base styles and javascript which shouldn't include android-theme-specific logic.

**Comment by Lanayx** [comment]
Closing as abandoned
