### ISSUE TITLE
Implement setOptions method

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1449]
Configuration properties are not refreshed on setOprions. Can be replicated here:

[http://dojo.telerik.com/ubazO](http://dojo.telerik.com/ubazO)

Reported in Ticket ID: 1010973

setOptions is also not documented under "methods" here:
[http://docs.telerik.com/kendo-ui/api/javascript/ui/slider](http://docs.telerik.com/kendo-ui/api/javascript/ui/slider)

Note: The issue is reproducible for KendoSlider and KendoRangeSlider

min and max methods were also added to the control.

**Comment by KirilNN** [comment]
@naskog this is a feature that is currently not implemented, so maybe we should change this to a feature rather than a bug, and change the severity.

**Comment by naskog** [comment]
@KirilNN Shouldn't there be:
'Uncaught TypeError: rangeSlider.setOptions is not a function'
if the feature is not implemented ?

**Comment by underlog** [comment]
No; `setOptions` is inherited from the base Widget class.

**Comment by KirilNN** [comment]
@naskog you will get the same result with $(...).getKendoSlider(...).foo is not a function
