### ISSUE TITLE
Edge: Not able to perform native scroll

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1450]
Reproducible on: MS Surface

Steps:
Navigate to [http://demos.telerik.com/kendo-ui/m/index](http://demos.telerik.com/kendo-ui/m/index)
Scroll down to the bottom of the demos list

Result: Scrolling is not possible when you are using a finger. The whole page (together with the navigation bar) moves, but not the page content

Note: Scrolling is possible when the device's pen is used

Reported in Ticket ID: 1011635

**Comment by Casimodo72** [comment]
Hi, I'm the person who reported this issue via Telerik's forum. Any progress? Our app is loosing customer acceptance due to this issue. Please note that finger-scrolling is not possible throughout the application, i.e. not only in the list-view. Any scrollable view is transported back into the prehistoric Pocket-PC-with-a-pen era.

**Comment by underlog** [comment]
There is no development here. The mobile app instance is targeting mobile devices exclusively, and we don't consider the surface to be a mobile device, so the mobile app enters will go in "development" mode, forcing javascript based scrolling

We will accept a pull request for configuration option that overrides this.

**Comment by Casimodo72** [comment]
We don't use surface tablets. We use TrekStor SurfTab duo W1 3G tablets with no keyboard attached when the people are out in the field performing unexploded ordnance surveys. Does this could as mobile?
You mentioned a configuration option. Does this mean the problems we have are just related to a configuration option which kicks in javascript scrolling? Please, could you point me to the related piece of code, so I can hard-code the override on our side?

**Comment by underlog** [comment]
That's a feasible approach - you don't even have to modify the source code, actually. You can override this immediately after the kendo script inclusion:

https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.core.js#L1998-L2002
The scroller uses it here:
https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.mobile.scroller.js#L294

Afterwards, all your views should have `use-native-scrolling=true` set.

**Comment by Casimodo72** [comment]
Thanks, that did work.
