### ISSUE TITLE
Add pagination and virtual scroll to Kendo UI TreeList

### ISSUE THREAD

**Issue by kgottumukkala** [telerik/kendo-ui-core#1451]
We have requirement where the flat structure of data would be shown in hierarchical format based on Id and ParentId relations. TreeList seems promising and handling exactly what we are trying to achieve. However we could not continue to use that since we even have a requirement of lazy loading of data, as the data size would be 60000 records. Obviously bringing all 60000 records into UI and implementing hierarchy may not be good since users might be interested only certain records. Currently we had to limit ourself to Kendo Grid and doing some javascript customization to handle expand and collapse of hierarchy. So if we have pagination or lazy loading of data withing treelist that would really work like charm.

**Comment by naskog** [comment]
Hi @kgottumukkala ,
Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (Professional, UI for MVC, PHP, JSP) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI!

**Comment by kgottumukkala** [comment]
Thanks for the response. I will try to post it with Premium Forum.
