### ISSUE TITLE
Compile itemTemplate to the dataSource item

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#1459]
### Description
The widget currently binds the itemTemplate to the result of the `dataItems` method, which is not correct.

This demo should work: http://dojo.telerik.com/@ggkrustev/uMUJa

**Comment by JeroenVinke** [comment]
In [this sample](http://demos.telerik.com/kendo-ui/multiselect/virtualization) `template` is used instead of the `itemTemplate`. `template` isn't in the API documentation of the multiselect either. Should itemTemplate be used, or `template`?

**Comment by ggkrustev** [comment]
We support both `itemTemplate` and `template`:
https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.multiselect.js#L242
It is more correct to use `itemTemplate` though. The change will be visible in the next official release of Kendo UI.

P.S. Please open a separate issue for bug reports that are not related to the specific thread, like is the case here. Thank you in advance
