### ISSUE TITLE
ObservableArray functions are missing support for thisArg

### ISSUE THREAD

**Issue by arntj** [telerik/kendo-ui-core#1465]
This applies to the following functions on ObservableArray:
`forEach, map, filter, find, every, some`

These functions don't support a `thisArg` argument to set the `this` context variable when executing the callback. This should be supported in order to make the functions as predictable and standards-compliant as possible.

See Mozilla docs for these functions:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every

**Comment by matanasov** [comment]
@ag-petrov @Stamo-Gochev @ivanchev 

Could you please take a look at this?

**Comment by ivanchev** [comment]
We will add this in the upcoming R1 release.
