### ISSUE TITLE
Not applied class k-state-default to initially expanded nodes

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#1468]
### Bug report

The item with text "Item 3" is set to expanded (expanded: true), this adds the "k-state-active" class to the li element, however the "k-state-default" class is missing and when the item is collapsed it is not added back. This behavior defers from the one exhibited on manually expanding and collapsing items: the "k-state-active" class is added/removed, while the "k-state-default" class remains. 

### Reproduction of the problem
http://dojo.telerik.com/oGetImAG/2

### Current behavior
"k-state-default" class is missing and when the item is collapsed it is not added back.

### Expected/desired behavior
"k-state-default" class is added when the item is collapsed it is not added back

### Environment

* **Kendo UI version:** 2019.3.917

**Comment by Dimitar-Goshev** [comment]
Reproducible with R2 2017 SP1 (2017.2.621) as well.

**Comment by eyupyusein** [comment]
Doesn't seem to be a valid scenario for the latest version with the new rendering.
