### ISSUE TITLE
transport.submit documentation

### ISSUE THREAD

**Issue by RainerAtSpirit** [telerik/kendo-ui-core#1472]
I'm in the process of adding `$batch` support for a custom Odata kendo datasource.
Based on the source code it seems that the only way to combine CUD requests into one batch request by using a custom `transport.submit` method.

https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.data.js#L2794
```javascript
 if (that.options.batch && that.transport.submit) {
                    promises = that._sendSubmit(created, updated, destroyed);
                } else {
                    promises.push.apply(promises, that._send("create", created));
                    promises.push.apply(promises, that._send("update", updated));
                    promises.push.apply(promises, that._send("destroy", destroyed));
                }
```

However when glancing through the documentation I haven't found documentation for `transport.submit`. Is there a reason why this is not documented or would you consider it safe to be used?

**Comment by tsvetomir** [comment]
This method is now [documented](http://docs.telerik.com/kendo-ui/api/javascript/data/datasource#configuration-transport.submit)
