### ISSUE TITLE
iPad (Safari): Bottom border is not visible in Bootstrap theme

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#1477]
Can be observed on:
[http://demos.telerik.com/kendo-ui/datepicker/index](http://demos.telerik.com/kendo-ui/datepicker/index)
[http://demos.telerik.com/kendo-ui/datetimepicker/index](http://demos.telerik.com/kendo-ui/datetimepicker/index)
[http://demos.telerik.com/kendo-ui/datetimepicker/index](http://demos.telerik.com/kendo-ui/datetimepicker/index)

Result: The bottom border is being cut off.  Other themes such as Default do not have the issue. 

Reported in Ticket ID: 1015689

**Comment by ipeshev** [comment]
Can't reproduce
