### ISSUE TITLE
Grid - Cancel on popup edit dialog resets data

### ISSUE THREAD

**Issue by RaptorCZ** [telerik/kendo-ui-core#1481]
I have this example: http://dojo.telerik.com/IhEdu

There is column CanDelete in data to hide/show "delete" command column. Column is removed in dataBound based on CanDelete value.

Now try to click on "edit" text in grid then "cancel" in popup dialog. And "delete" appears right of "edit". But this column has been deleted on dataBound.

It has something to do with schema, because removing schema fixed this. 
Why? What's wrong with this schema definition?

**Comment by KirilNN** [comment]
Hi @RaptorCZ,

Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (Professional, UI for MVC, PHP, JSP) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI!
