### ISSUE TITLE
Incorrect Feature List Table in ReadMe page

### ISSUE THREAD

**Issue by writeosahon** [telerik/kendo-ui-core#1487]
Hello Telerik.

Please can you take a look at the feature lists table on the Read Me page. The feature list indicator for the Kendo UI Core are inaccurate. 
The Kendo Validator widget has been marked as unavailable for the Kendo UI Core, and this is incorrect.

I also suspect there are other incorrect indicators.

Thank you

**Comment by dmihaylo** [comment]
@writeosahon Many thanks for noticing that! 

We updated the list of available controls in the Core distribution and also changed the documentation correspondingly. It is expected to be live soon.
