### ISSUE TITLE
Make it easy for the latest `kendo-ui-core` package to be found in npm

### ISSUE THREAD

**Issue by dwiyatci** [telerik/kendo-ui-core#1488]
Will there be any efforts of making the latest release to be always pushed to npm? I see the version of [the one in npm is already far outdated](https://www.npmjs.com/package/kendo-ui-core).

I think it'd make life easier for ones who use npm/webpack to manage their frontend dependencies. :grin:

**Comment by underlog** [comment]
Hi,

the currently published package is not owned by our team, but by a person not related to the company. We have contacted NPM on several occasions in order to resolve this, no response so far :(.

**Comment by dwiyatci** [comment]
It's a shame, really, because npm is allegedly the largest (JavaScript) package repository in the world today. :pensive: I do hope Telerik will try harder to win this.

**Comment by underlog** [comment]
There is not much more to try here. NPM does not respond to our emails. You may try contacting them or reporting the module in some way, perhaps this will help.

**Comment by dwiyatci** [comment]
@underlog Your move, mate! :v::yum:  

<img width="1250" alt="screen shot 2016-03-07 at 23 08 48" src="https://cloud.githubusercontent.com/assets/4405796/13585044/b8a95b58-e4b9-11e5-83c9-09fd9816814e.png">

**Comment by underlog** [comment]
Thank you!

**Comment by underlog** [comment]
Hi @dwiyatci ,

We made some progress here. Please check #1666 . Comments are welcome.

**Comment by dwiyatci** [comment]
@underlog Thanks for the effort! I tested it; appears to be working well with my [javascript-webpack](https://github.com/dwiyatci/web-frontend-boilerplate/blob/master/webpack.config.js) pair (ES6+/Babel) 🍻
