### ISSUE TITLE
TreeView AutoScroll doesn't work on iOS

### ISSUE THREAD

**Issue by elenatosheva** [telerik/kendo-ui-core#1497]
See a dojo demonstrating the issue:

http://dojo.telerik.com/ImoMi

Reproducible under iPhone6 - iOS version 9.1, iPad - iOS version 7.1.2 and iOS version 8.3 

Works under Android 4.4.2, desktop browsers - IE,FF, Chrome

**Comment by simonssspirit** [comment]
The same issue on iOS can be observed in the Sortable Grid: http://dojo.telerik.com/IsEhU

**Comment by jivanova** [comment]
Not reproducible. Test with meta tag and latest version:

``` html
<meta name="viewport" content="width=device-width">
```

[http://dojo.telerik.com/ULepaxIg](http://dojo.telerik.com/ULepaxIg)

**Comment by Dimitar-Goshev** [comment]
Not reproducible for Sortable Grid as well - https://dojo.telerik.com/aqIPUCet
