### ISSUE TITLE
Throws an error due to multiple attempts to destroy a widget

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#1501]
### Description
When the widget is nested in another one, like Kendo UI Window, then it will be destroyed by `kendo.destroy(children)` call. The AngularJS binding, however, will also try to destroy it:

- https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.angular.js#L540

The passed `widget` is already destroyed, but as it is used in the scope this is not known yet. The subsequent `destroy` call causes an exception.

Repro demo: http://dojo.telerik.com/@pgresham/uGAti

Reported in TicketID: 1018626

**Comment by mishoo** [comment]
Here's a suggested fix in a previous discussion on this topic: https://github.com/telerik/kendo-ui-core/issues/99#issuecomment-51255854

**Comment by ggkrustev** [comment]
Thanks @mishoo! It seems that the conclusion of the discussion is pretty clear :). I will fix the issue using `kendo.destroy` method.

P.S. @underlog could chime-in here if we should find a more general solution.
