### ISSUE TITLE
Widget does not restrict typed characters on Android/Windows Phone devices

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#154]
To reproduce the issue, open the Kendo UI MaskedTextBox demo in Android/Windows Phone device and try to type something which is not allowed.

**Comment by ggkrustev** [comment]
Reported in TicketID: 1055809. A working open-source widget could be found here - https://github.com/angular-ui/ui-mask

**Comment by ggkrustev** [comment]
I will re-open this issue. We will need to address it, because the widget is not usable in mobile devices.

**Comment by jlchereau** [comment]
I am not 100% certain #2469 is the same problem considering this one designates explicitly Android/Windows Phone and not iOS and #2469 applies to iOS among others.

So when you fix this one, please consider typing suggestions from virtual keyboards.
