### ISSUE TITLE
Collapsible content does not resize correctly on iOS

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#1540]
Example: http://dojo.telerik.com/ARiNa/31

Steps: Expand the first collapsible widget, it will issue Ajax request to update its content. In the `always` Ajax promise callback `resize` method of the Collapsible will be called. At this stage the Collapsible cannot get the actual content height (`_getContentHeight`) although that the content is updated.

Reported in ticket: 1019462

**Comment by nenchef** [comment]
Close due to low activity and replication only under iOS9
