### ISSUE TITLE
Tooltip position incorrect due to box-shadow

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#1543]
When tooltip's position is set to "left", the tooltip cannot be reached with the mouse, due to a "gap" (4 pixels) opening between div.k-callout and the tooltip, caused by 

.box-shadow(0 4px 6px @shadow-color);
from
https://github.com/telerik/kendo-ui-core/commit/d1c98e7977a05f197cff3a223609c5a8059a9b84

Steps to reproduce:

- Open http://dojo.telerik.com/eQiKa/3
- Hover the font awesome icon
- try to hover the tooltip

- uncomment /*box-shadow: 0 4px 2px #C6C6C6;*/ from the styles tag
- repeat steps 1-3

**Comment by yordanov** [comment]
Tooltip should use `autoHide: false` property, if the intention is to keep the Tooltip opened. The position is calculated properly with respect to the box-shadow styles.
