### ISSUE TITLE
child menu navigation on chrome messed up when zoom in

### ISSUE THREAD

**Issue by ColdScream** [telerik/kendo-ui-core#1546]
zoomed in chrome
![image](https://cloud.githubusercontent.com/assets/3462256/13981067/62d13342-f114-11e5-8159-1a39bb9d65a1.png)

for comparison, zoomed in safari
![image](https://cloud.githubusercontent.com/assets/3462256/13981005/0cac885e-f114-11e5-9935-e8f3bca7fa0c.png)

**Comment by Dimitar-Goshev** [comment]
Browser zoom level other than 100% is not officially supported.
