### ISSUE TITLE
Autocomplete with mvvm produces wierd mouse click bugafter `select` event on IE9-11 (win 7)

### ISSUE THREAD

**Issue by bboyz269** [telerik/kendo-ui-core#1547]
I'm using kendo ui mvvm to create a very simple app. 

A list of item to input, at the end of list will be an empty item. After that empty item has been input, it'll be copied to the list and new one is created.

[Here is the fidle.](https://jsfiddle.net/bboyz269/pmg0sLbv/) 

The bug is that when user make a selection from the autocomplete list. Mouse click (left, right, scroll) events is not responding on the newly created empty item. You can't even select the text next to it. But after a while (duration is not consistent) or by clicking on other element, it works fine again.

Note: This only happens on IE9, 10, 11 (win 7), even IE8 works fine, and by making a selection from the autocomplete list only because input value via keyboard is fine also. 

// Sorry for the bad English.

**Comment by ggkrustev** [comment]
Hi @bboyz269,

I tried to replicate the issue using the provided demo, but to no avail. I prepared a Dojo demo as the jsFiddle didn't run locally:

- http://dojo.telerik.com/ITEXa

Here is a screencast of my test:

- http://dojo.telerik.com/ITEXa

Could you elaborate a bit more what exactly does not work?

**Comment by ggkrustev** [comment]
I will close this thread due to inactivity.

If someone can provide a repro demo, it would be very helpful to post it below.
