### ISSUE TITLE
Changing multiselect value after select in virtualization mode throws error

### ISSUE THREAD

**Issue by JeroenVinke** [telerik/kendo-ui-core#1557]
http://dojo.telerik.com/OVaDU

To reproduce:
1. filter the list with `er`
2. select something from the list
3. click the `Set value` button.

The set value button calls `multiselect.value(multiselect.value())` which results in the `Uncaught TypeError: Cannot read property 'item' of undefined` error

Original issue: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/442#issuecomment-203940750

**Comment by JeroenVinke** [comment]
This is also happening with the dropdownlist control, so I assume that this applies to all controls that support virtualization

**Comment by zdravkov** [comment]
Could not replicate it with the latest version - [dojo](http://dojo.telerik.com/@zdravkov/aCAKO).
