### ISSUE TITLE
Destroying the widget triggers a reflow on the whole document

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-ui-core#1560]
Reported in ticket ID 1024443

When unbinding scroll event handlers, the popup [`_scrollableParents` method](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.popup.js#L473-L477) triggers reflow on quite a few elements, because [`kendo.isScrollable` uses `getComputedStyle`](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.core.js#L1805).

A few solutions for that pop to mind:
- attaching an event handler to all parents, no matter if they are scrollable or not. It will attach handlers unnecessarily, but seems to do the trick.
- caching the elements that have an event handler attached. Event handlers now leak if an element changes its `overflow` property via JS after the drop-down is initialized, so this idea is not that bad in any case.

@ggkrustev , what do you think?

**Comment by jivanova** [comment]
Consider caching the scrollableParents collection when initializing the Popup and then further use it for destroy, etc. Currently, if there are hundred dropdownlists(any inheriting popup) the destroy time would be. 

https://dojo.telerik.com/EYoDujIX

Current Performance:
![image](https://user-images.githubusercontent.com/7159157/53722861-2126e580-3e6f-11e9-8fc8-81def6983485.png)

Performance with cached scrollableParents:
![image](https://user-images.githubusercontent.com/7159157/53722915-3dc31d80-3e6f-11e9-8aa9-c133ecfe7037.png)

**Comment by jivanova** [comment]
Reported in:

1130441
1398529
1148720
170066
1364023
