### ISSUE TITLE
Disabled ToolBar SplitButton can be opened with the keyboard

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#1566]
Example: http://dojo.telerik.com/UkUrO

When SplitButton is disabled the following can be observed:

~~**current**: the main button disables but can still receive focus by clicking or by tabbing~~
~~**expected**: the button should not be able to receive focus~~ Focus is expected, as said in the following comment: https://github.com/telerik/kendo-ui-core/issues/1566#issuecomment-358662625

**Current**: the dropdown arrow section remains visibly enabled, reacts to mouseover and clicks
**Expected**: the dropdown arrow section should be visibly disabled and shouldn't react to mouseover and clicks

**Current**: if the button has focus, the ALT-DownArrow keyboard shortcut will show the popup
**Expected**: disabled button should not receive focus and should not be possible to be opened with the keyboard

* **Kendo UI version:** 2016.1.226
* **Browser:** [all]

**Comment by mvgmvg** [comment]
A disabled split button in toolbar should be focusable and the focus state should be styled
