### ISSUE TITLE
Fix less comments for webpack optimization

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#1569]
This (with all the blank lines):

![image](https://cloud.githubusercontent.com/assets/2556751/14411065/eec9374e-ff35-11e5-9510-7e58d6418a0e.png)

First translates into this (less compiling)

![image](https://cloud.githubusercontent.com/assets/2556751/14411041/854230aa-ff35-11e5-8733-329becb92741.png)

then into this (webpack packaging):

![image](https://cloud.githubusercontent.com/assets/2556751/14411027/1e587ffc-ff35-11e5-90dc-ba1553ef1c17.png)

See also https://github.com/webpack/webpack/issues/2311 although I am not sure it can be considered a webpack issue since it refers to an external less compiler.

Please remove all blank lines from your distributions.

**Comment by underlog** [comment]
We need the blank lines as a part of our build/licensing process.
