### ISSUE TITLE
DropDownList and MultiSelect inconsistent ng-model binding behavior in IE and Chrome/FF

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#1574]
When the data is read very fast (e.g. from a local .json file), the DropDownList behaves differently with ng-model binding under IE and Chrome/FireFox

Reported in ticket ID 1024659.

### Reproduction of the problem
Open the following page in Internet Explorer:
[test.zip](https://github.com/telerik/kendo-ui-core/files/3406960/test.zip)

### Current behavior
The dropDownBModelvalue with DS from a local json-file is 0

### Expected/desired behavior
The dropDownBModelvalue with DS from a local json-file is 3

## Notes from the client:

If "throtteling" is enabled (Regular 4G)  in "Google Chrome", the model of the dropdown is than correct, it seems that when the datasource is loaded too "fast", the widget cannot handle this?

Note 2: 
If this script is opened in "Internet Explorer 11.0.9600.17937" the model is correct (because the browser is "slower"?)

**Comment by nenchef** [comment]
Close due to inactivity and complexity (circumstances) of the environment and behavior.
