### ISSUE TITLE
Unable to build a modules dependencies map: some modules are duplicated on many files.

### ISSUE THREAD

**Issue by willywongi** [telerik/kendo-ui-core#1578]
I noticed that a number of modules are duplicated and scattered through all files in kendo distribution. This lead to a big mess to build modules dependencies (eg `util/main` is defined in `kendo.spreadsheet.js`, `kendo.scheduler.js`, `kendo.pdf.js`...), thus spoiling some of the advantages of using a module loader.
I suggest to stick to the rule "one file = one module" and then distribute bundles when you just want to statically load functionalities (eg. when I want a grid, I just include kendo.base and kendo.grid, that are bundles of kendo.base.core, kendo.base.util, kendo.grid.base, kendo.grid.columnsorter...)
Disclaimer: I'm using a loader that batch up module requests, performs a single request to a combo loader that bundles up files on the fly, leading to exaclty just the code you need in every page.
It's a great way to achieve fast pageloads (less bytes, less connections) without a build process.

**Comment by underlog** [comment]
Unfortinately, the current state of affairs is a result of a distribution mechanism we came up with long before the JavaScript modules became popular. The files you refer to were originally designed to be manually picked and assembled by the user. The modules came as an afterthought, and this is visible in various places, like the examples you have provided.  

However, we can't change the format we distribute without breaking everyone that relies on kendo.grid.js.

I think that an "escape hatch" from this would be a new, NPM specific distribution, where we can fix this. A private NPM distribution mechanism is in the works.

**Comment by willywongi** [comment]
I can relate! But I thought you could keep the distribution as-is but as a result of a build process from single module-files AND distributing the collection of these files, resulting in:
1. The whole lot of module/files (plain, commented);
2. The dependencies map and the definition of common bundles (eg. kendo.grid = kendo.grid.base + kendo.grid.feature1 + kendo.grid.feature2)
2. A number (lesser than 1) of plain js files as a result of combining files from 1 with info from 2.
3. The same files, minimized (w/ map files).

I see it's not an easy task to keep everything as-is and rearranging these files. I'll definitely keep an eye on the NPM distribution. Thank you!

**Comment by underlog** [comment]
:) People already complain that our distros are huge, and adding a third version will definitely inflate the archive file size even further. But - yes. We hear you and we are looking into means of improving the module story.

**Comment by willywongi** [comment]
How can I follow your progress on this? We're deciding how to employ KendoUI (static loading, bundles, or dynamic require) and I can use some insight on the matter. 
Thanks!

**Comment by underlog** [comment]
Things won't happen in the public repository, as it is a matter of a company level infrastructure - we will need a private NPM registry to begin with. I am afraid that I can't provide a concrete timeline for the effort, but it won't happen anytime soon, so please, don't rely on that happening in the upcoming weeks.

**Comment by underlog** [comment]
Hi @willywongi,

We published an update of the Kendo UI NPM package, which includes the source files in CommonJS format. Please check #1666 for further details. Feedback is welcome, as usual.
