### ISSUE TITLE
Minifier Problem

### ISSUE THREAD

**Issue by aersamkull** [telerik/kendo-ui-core#1581]
In Kendo 2016.1, in kendo.web.js, there is the following line (95625):
```JavaScript
this._sheet.forEach(this._ref.toRangeRef(), function (_, _, data) {
```
The duplicate _ parameter name is a problem for the Minifier of the WebCompiler (https://github.com/madskristensen/WebCompiler), which results in a syntax error instead of a minified file. Renaming a parameter to _1 or so fixes the problem.

The problem is that two identical parameter names (even if it's _) are not allowed.

**Comment by underlog** [comment]
Hi,

Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (kendo.web.js) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI!
