### ISSUE TITLE
Initial ng-model gets cleared when using data source remote loading on angular versions >1.4.8

### ISSUE THREAD

**Issue by kfreezen** [telerik/kendo-ui-core#1582]
First example has angular 1.4.8 included, and works as intended
[http://dojo.telerik.com/@villagemedia/aBEXO/2](http://dojo.telerik.com/@villagemedia/aBEXO/2)

Second example has angular 1.4.9 included, and shows the broken behaviour
[http://dojo.telerik.com/@villagemedia/exEJe](http://dojo.telerik.com/@villagemedia/exEJe)

Link to the angular 1.4.9 changelog
https://github.com/angular/angular.js/blob/master/CHANGELOG.md#149-implicit-superannuation-2016-01-21

**Comment by ggkrustev** [comment]
This is issue is documented in our Troubleshooting section:
- http://docs.telerik.com/kendo-ui/AngularJS/Troubleshooting/common-issues#widgets-with-ng-model-directives-reflect-no-model-value
