### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by dungdm93** [telerik/kendo-ui-core#1585]
In this [doc](https://github.com/telerik/kendo-ui-core/blob/2d53f448aed7f413023c32cc07fd1242b7e4f6dd/docs/jsp/introduction.md):

> Telerik UI for JSP (JavaScript Pages) is a complete web development framework for building HTML5 applications...

JSP is [**JavaServer Pages**](http://www.oracle.com/technetwork/java/javaee/jsp/index.html), not **JavaScript Pages**

**Comment by KirilNN** [comment]
Hi @dungdm93,

It is fixed now.

Thanks!
