### ISSUE TITLE
Stockchart starting 1/1/1970

### ISSUE THREAD

**Issue by rob123456** [telerik/kendo-ui-core#1587]
When creating a stockchart (with the navigator) setting the frequency to annual. If the dataset starts on 1/1/1970 the chart doesn't display anything. If you show a dataset starting before 1970 (which can include a value on 1/1/1970) the chart displays fine.

I've got a temporarily fix - if the year is 1970 then I set the date to 2/1/1970 so the chart works as it should.

Kendo version: KendoUI-2014.2.1008 (don't judge, IE8)

**Comment by KirilNN** [comment]
Hi @rob123456,

Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (Professional, UI for MVC, PHP, JSP) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI!
