### ISSUE TITLE
TypeScript: Missing footerAttributes in GridColumn

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#1592]
Forwarding this issue from DefinitelyTyped/DefinitelyTyped#9036 on behalf of @	EmirKrkic

**Comment by tsvetomir** [comment]
Same for imageClass, that was updated in DefinitelyTyped/DefinitelyTyped#8683

@rkonstantinov: those seem to be missing from the documentation. Are they considered public API?

**Comment by rkonstantinov** [comment]
Indeed, footerAttributes option should be available. However, the command's imageClass is meant as internal.

**Comment by tsvetomir** [comment]
Keeping this open until we merge it in DefinitelyTyped
