### ISSUE TITLE
Data Source should mark offline items in __create__ state as dirty when they are read from the offline storage in order to correctly sync them when it becomes online

### ISSUE THREAD

**Issue by AntonDobrev** [telerik/kendo-ui-core#1595]
Steps to reproduce:

1.	Add an item in the data source when offline
2.	Refresh the data source instance/browser page
3.	Read the items offline – they are added to the data source 
4.	Switch to online mode 

Expected result: the item created offline should be synced to the remote data source
Actual result: the item is not synced. Items in __update__ state are synced though. 

For full information refer to ticket # 1027788.

**Comment by rkonstantinov** [comment]
test page: http://dojo.telerik.com/oqAVE

**Comment by tsvetomir** [comment]
Will keep it open until release to make sure the changelog doesn't picks this up
