### ISSUE TITLE
Selected items are not cleared in tag mode

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#1606]
http://dojo.telerik.com/@nsk.bars/AfiVI

When backspace is pressed the items the tag is removed, but items are still selected.

**Expected behavior:** backspace should not remove the tag.

**Comment by underlog** [comment]
Can you fix the typo in the title?

**Comment by epikhighs** [comment]
i'm seeing this behavior when using virtualization and filtering the list by typing into the text box.  Please make sure the fix also takes into account filtering.

**Comment by epikhighs** [comment]
when can I expect 2016.Q2.SP.Next milestone to be released (by end of june)?  

Will there be a preview release I can use ahead of the official release that includes this fix?

Thanks.

**Comment by KirilNN** [comment]
Hi @epikhighs,

We are still working on the issue, as soon as the issue is closed the fix will be pushed in the open source repo and you can get it and test it.

Best!

**Comment by ggkrustev** [comment]
The fix will be included in Q3 2016 release as it depends on a **breaking change**. I am afraid that there is not workaround for the moment.

**Comment by epikhighs** [comment]
@ggkrustev Hi, could you clarify what a breaking change means?

**Comment by ggkrustev** [comment]
@epikhighs the change is documented here:
- https://github.com/telerik/kendo-ui-core/blob/master/docs/backwards-compatibility/2016/2016-backward-compatibility.md#breaking-changes
