### ISSUE TITLE
The dropdown popup appears in wrong position on mobile devices

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#1609]
The popup position of the drop-down list is wrong on mobile devices. It seems that the wrong calculation of the position occurs, if the web site is not on most top left scroll position.

Reproducible using Chrome in Device Mode:

1) Open http://runner.telerik.io/fullscreen/iCame

2) Drag a bit so that the widget is partly hidden

3) Open the dropdown

**Comment by underlog** [comment]
Works in iOS. Does not work in Android.
![screen shot 2016-05-05 at 18 38 18](https://cloud.githubusercontent.com/assets/13347/15048095/9844a6a0-12f0-11e6-8066-03e8dc26dab8.png)

**Comment by ipeshev** [comment]
On Mobile, when scrolled dropdown-menu is not aligned to the dropdown-button. Try to open the example in some mobile and rotate the screen.
Not sure if it is an issue it might be a feature in some cases.

**Comment by ggkrustev** [comment]
I updated the demo with the scripts from staging and it seems to work just fine in Android 5 phone. The popup is aligned next to the anchor as it should do.

http://runner.telerik.io/fullscreen/iCame/3

With regards to the popup behavior when the screen is rotated - it is possible to see shifted popup if part of the anchor is not visible horizontally. This behavior is expected and it is due the "fit" collision feature of the popup.

https://github.com/telerik/kendo-ui-core/blob/master/docs/controls/layout/popup/overview.md#control-positioning

I will close the ticket as resolved.

**Comment by pbnttttt** [comment]
I use the [metronic Admin template](http://keenthemes.com/preview/metronic/theme/admin_1_material_design/index.html).

The DropDownList work fine when I using version 2016.2.714, and it broke after I upgraded the version to 2016.3.914.

Image:
![kendoddl](https://cloud.githubusercontent.com/assets/351436/19153415/10d1a514-8c09-11e6-9367-0ebb58bb3f14.png)

Example:
2016.2.714
[http://dojo.telerik.com/onITa](http://dojo.telerik.com/onITa)

2016.3.914
[http://dojo.telerik.com/onITa/2](http://dojo.telerik.com/onITa/2)
