### ISSUE TITLE
why every mobile demo only can render on body

### ISSUE THREAD

**Issue by mrjumpy** [telerik/kendo-ui-core#1614]
Every demo using:
`var app = new kendo.mobile.Application(document.body, { skin: "nova" });`
so I change to
`<div id="app"> </div>`
and script
 `var app = new kendo.mobile.Application(document.getElementById('app'), { skin: "nova" });`
only show blank here.

because I'm trying to use Kendo on react, so I don't want to render on body,
is there anything that i misunderstanding?

here's my sample code
http://dojo.telerik.com/EtewI

**Comment by tsvetomir** [comment]
The `#app` div has no height set. Other than that it shouldn't matter where the Application is initialized.
