### ISSUE TITLE
Toolbar widget doesn't lose focus with "Shift+Tab" when the first item if focused

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#1619]
This is reproducible right on the official demo: http://demos.telerik.com/kendo-ui/toolbar/keyboard-navigation
1. Focus the toolbar widget
2. Repeatedly press Shift+Tab

Expected: Eventually, the focus should leave the toolbar widget
Actual: Focus gets "stuck" on the first item in the toolbar

**Comment by Dimitar-Goshev** [comment]
The issue is no longer reproducible.
