### ISSUE TITLE
Angular aggregate groupFooterTemplate and groupHeaderTemplate not working in Grid

### ISSUE THREAD

**Issue by JeroenVinke** [telerik/kendo-ui-core#1622]
dojo: http://dojo.telerik.com/AcoLa

When using aggregates in a grid, combined with an angular groupFooterTemplate/groupHeaderTemplate, the aggregate can't be bound to:

```
      Count1: {{dataItem.count}}  // doesn't show anything
      Count2: {{dataItem.ProductName.count}} // shows the correct count
```

**Comment by rkonstantinov** [comment]
Indeed, you are correct. The during the construction of the groupHeader/Footer templates (only when they are set as strings) some "syntax sugar" is applied in order aggregated value to be accessed directly by its name. However, same approach cannot be easily applied when angular is used, thus the mentioned syntax will not work and it is required that the value is accessed via its fieldName (as shown in the working part of the above code snippet).

**Comment by JeroenVinke** [comment]
Thanks for the quick response :+1:  Using the fieldnames is fine :)

**Comment by adriatic** [comment]
Wow - this was indeed quick at all "points of connection". I am impressed that @JeroenVinke found this to be KendoUI issue and further @rkonstantinov being able to attribute this to "angular" dialect of KendoUI (our Aurelia-KendoUI bridges is classified as angular I guess, which is another reason to create the next version of that bridge as its own entity :-)
