### ISSUE TITLE
Cannot remove a programatically set value from virtualized widget

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#1631]
### Description
When a value is set with `value` method, it cannot be deleted using the "X" button. The removal behavior works, however, when popup is opened.

Repro demo:  http://dojo.telerik.com/uboCi

Reported in TicketID: 1032519

**Comment by ggkrustev** [comment]
The issue is actually fixed in Q2 2016 (2016.2.607).

**Comment by ipeshev** [comment]
Not sure if it's related, [here](http://kendobuild.telerik.com/dojo-staging/EKIzE)  we have same example with fix applied and it is working - added programaticaly value can be deleted , but it can be added multiple times and then those cannot be deleted.

**Comment by ggkrustev** [comment]
Thanks for reporting this. Indeed, this is a different issue, which was logged as #1976
