### ISSUE TITLE
AllDay event is shown one day shorter in Scheduler Agenda View

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#1632]
(Public issue for notification purposes)

The issue starts to reproduce with Q1 2016 SP1. (Q1 2016 is OK)

1. Go to [http://demos.telerik.com/kendo-ui/scheduler/index](http://demos.telerik.com/kendo-ui/scheduler/index)
2. Create an AllDay appointment from Tue 6/11 to Thu 6/13.
3. Switch to Agenda View.

Expected: The AllDay Appointment is displayed for 11th, 12th and 13th - [http://screencast.com/t/UjxpYYqIQ](http://screencast.com/t/UjxpYYqIQ).
Actual: The AllDay Appointment is displayed for 11th, 12th - [http://screencast.com/t/MCb8qiAIs9Ws](http://screencast.com/t/MCb8qiAIs9Ws).

**Comment by DavidEberhard** [comment]
The bug has not been fixed yet.!!!!!!!
this problem is urgent for our Enterprise!

**Comment by DavidEberhard** [comment]
in the Version v2016.3.1028 is yet fixed!!! THANK YOU!!
