### ISSUE TITLE
Widget performs two requests on cascade when filtering is enabled

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#1642]
### Description
When chose a value from a parent ddl which has filtered enabled, the child will request the same values twice

Repro demo: http://dojo.telerik.com/uRumA

Reported in TicketID: 1034447

**Comment by amariq** [comment]
Seems like it's similar to this one: [telerik/kendo-ui-core/issues/1554](https://github.com/telerik/kendo-ui-core/issues/1554)
No?

**P.S.** TicketID: 1034447 - it's my ticket :3

**Comment by ggkrustev** [comment]
Yep, this is a duplicate one. Thanks for reporting this

Closing as a duplicate to #1554
