### ISSUE TITLE
Multiselect widget icon click issue

### ISSUE THREAD

**Issue by nutangwari** [telerik/kendo-ui-core#1643]
In Multi-Select widget, if you click on the icon then dropdown doesn’t get open. You need to click inside the box to open it. It was working before the Q32015 release. 

What i found is the issue in the code as below:
```javascript
_wrapperMousedown: function(e) {
            ....
            var closeButton = target.hasClass("k-select") || target.hasClass("k-icon");
/* above kendo is checking for the .k-icon class instead it should be searching for the k-i-close class to be more specific.  because any multiselect field containing icon class ".k-icon" would break the functionality.*/
            if (closeButton) {
                closeButton = !target.closest(".k-select").children(".k-i-arrow-s").length;
            }
....
```
could you please confirm if my understanding is correct or am i getting it wrong?

**Comment by ggkrustev** [comment]
Hi @nutangwari,
could you clarify which widget you are referring to? The [MultiSelect](http://demos.telerik.com/kendo-ui/multiselect/index) **doesn't have a button** that toggles the popup.

Do you refer to the [DropDownList](http://demos.telerik.com/kendo-ui/dropdownlist/index) ?

Could you also show us a repro [Dojo](http://dojo.telerik.com) demo? This will help us to observe the erroneous behavior.

**Comment by nutangwari** [comment]
Hi @ggkrustev , 
Its Multiselect widget, and yeah [multiselect](http://demos.telerik.com/kendo-ui/multiselect/index) doesn't have a button, but deep down kendo is adding icon classes to the widget. and visibility is set to hidden. if we change the visibility property we can see those icons coming up on the widget.  check below code.

```CSS
 .k-multiselect .k-loading-hidden {
     visibility:visible;
   }

you can check the same on the DOJO demo here: http://dojo.telerik.com/aLaTI

this will bring the hiding icon, now if i will replace the above icon with my defined icon in the css,
 i can add any icon to the Multiselect widget. But now if you try to click on above icon its not gonna display the dropdown list. on debugging you will get to know the above mentioned js code gets failed due to the presence of k-icon class present in the code. I hope you got my point.

**Comment by ggkrustev** [comment]
Hi @nutangwari,

Indeed, the MultiSelect renders a hidden icon, which however has a dedicated purpose - to show loading indicator when widget fetches data. **This icon is not intended to be changed or modified, neither to interact with it.** That being said, the described behavior is absolutely expected.

If you would like to add toggle button inside the widget, then you will need to done this manually - add the button and wire its click event.

This Github channel should be **used only** for bug reports. Any custom implementations should be discussed in public forums like [StackOverflow.com](http://stackoverflow.com/).

I will close the thread as its topic is not a bug report. Please relay the discussion in a public forum.
