### ISSUE TITLE
"No data" template

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1647]
The contents of the template should be displayed in the widget's drawer when the filter applied does not match any results. 

The template should have access to the filter string.

Related UV request: http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/8429415-allow-adding-additional-buttons-to-combobox-and-dr

**Comment by underlog** [comment]
The feature would greatly benefit from a demo // @yordanov

**Comment by ggkrustev** [comment]
@yordanov and @inikolova should design and style the 'no-data' element.

**Comment by yordanov** [comment]
The message must be short and simple:

"No data found."

It should be placed in the center of the popup. Text color should get the k-state-disabled color. 

Additionally set: 
text-transform: uppercase;
font-size: 0.85em;
font-weight: light;

Nova theme preview:

![nodatafound](https://cloud.githubusercontent.com/assets/1118895/16553356/da1bd0c6-41d0-11e6-98b6-a6c3f35424ce.png)

**Comment by ggkrustev** [comment]
The default `noDataTemplate` text is updated. I will assign the issue to @inikolova to close it once the styling is done.

**Comment by ggkrustev** [comment]
@inikolova, please update the `k-nodata>span` selector to style `k-nodata>div` elements. This is due the refactor done in d4dca17

**Comment by giond** [comment]
Hi, 

Can I somehow localize "NO DATA FOUND." in the kendo-drop-down-list? I suspect it is from noDataTemplate:"No data found." from the kendo.all.min.js

**Comment by kutkovav** [comment]
@giond Try using `<ng-template kendoDropDownListNoDataTemplate>
                    YOUR CUSTOM TEXT
                </ng-template>`
right before closing `</kendo-dropdownlist>`

**Comment by ben-tes** [comment]
Is there any way to hide 'No data' template? I wanted to use multiselect only for custom values.
