### ISSUE TITLE
Example on how to create new record from within combobox

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1648]
Based on #1647. 

The demo should feature a no data template with some copy + button that suggests creating a new item when none is matched. 

The demo code should show how to create a new record in the widget datasource and refresh the widget with the new item selected. 

Perhaps some progress indicators will be necessary. 

cc @yordanov

**Comment by underlog** [comment]
The demo may also utilize the footer template (#1649), or it may be a separate demo.

**Comment by underlog** [comment]
A demo for the multiselect would help, too: http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/4545733-multiselect-new-items

**Comment by ggkrustev** [comment]
Implemented with https://github.com/telerik/kendo/commit/69a30491d848e9b7456744ff65ae5a51fff352e5
