### ISSUE TITLE
Footer template

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1649]
The template should be permanently displayed at the bottom of the drawer. It should be refreshed with the contents of the drawer, and should have access to the dataSource (for example).

Common use case for such feature would be a summary of the records found, something like " 440 items found", or "see all results" link (check facebook search).

**Comment by underlog** [comment]
The feature would greatly benefit from a demo // @yordanov

**Comment by ggkrustev** [comment]
Demos added with https://github.com/telerik/kendo/commit/13d6c45340db69586c8a61543ef3f8c02467c62e
