### ISSUE TITLE
"Clear" button 

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1650]
Similar to the one offered by `<input type="search" />`. 

UV request - http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/4304595-enhance-combobox-to-be-able-to-clear-value-like-i

I am not sure if it makes sense for the DropDownList, though.

**Comment by yordanov** [comment]
Adding a `clear` button will require additional styling of the dropdown button in some themes. In addition, the **x** must be displayed on hover/focus/active states only and should not be visible in normal state.

Here is an example:

![combobox](https://cloud.githubusercontent.com/assets/1118895/15609378/5d55bfae-2428-11e6-97c2-d1998606037f.png)

**Comment by tapopov** [comment]
Added ComboBox and AutoComplete implementation in a feature branch (d1dbf3d858fef5e576f3f80003fc56b6d17180f1). MultiSelect's implementation and styling are coming up next.

**Comment by tapopov** [comment]
Added clear button to MultiSelect as well (0a6be439b666994e308843561fd9de98832fa1c0)

**Comment by joneff** [comment]
Currently, in multiselect and autocomplete when the clear button is visible and there is server loading both icons oevrlarp. This behaviour applies to autocomplete and multiselect only. In combobox the loading icon appears inside the toggle popup button.

As discussed with @tsvetomir and @ggkrustev, the clear icon must be hidden while the loading icon is visible.

**Comment by joneff** [comment]
Note: Please consider using `display` and not `opacity` for hiding the icons.
