### ISSUE TITLE
Flash of unbound value occurs during loading

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1652]
The report is [here](http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/5450525-combobox-add-flag-to-prevent-value-from-being-di), and, based on the votes, sounds like a real one. We can investigate it.

**Comment by ggkrustev** [comment]
Indeed, the current `text` behavior is confusing. Here is a Dojo demo that demonstrates it clearly:
- http://dojo.telerik.com/oGubA

It will be much better to leave the `text` empty until the widget is bound. Once we detect that the value is really *custom*, then we will update the text to match it.

I do not believe that we need a configuration option to enable/disable this behavior. The value can always be retrieved with the `value()` method anyway.
