### ISSUE TITLE
Add an option to Autocomplete to not show all items on length = 0

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1653]
> In order to fix concerns from #241 the Autocomplete now shows a full list of items when the text entered has been deleted. This ignores the MinLength option, and can cause unresponsiveness in the browser (since MinLength is generally there to reduce the amount of results). From #574 this new functionality is intentional (and as such, the thread was closed as won't fix), but in practical terms, this causes issues for a lot of people. If you really don't want to enforce MinLength when 0 results are returned, perhaps adding an extraoption like 'AlwaysEnforceMinLength' would solve this problem.

Copy pasted from here - http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/7177544-add-an-option-to-autocomplete-to-not-show-all-item

**Comment by valchev** [comment]
Closed with 08155174d3e44c680afa6ef6264bfdf16055b7e0

- added `enforceMinLength` configuration option that allows the developer to determine if the list should show all items when the search (filter) input is cleared
- by default `enforceMinLength` is set to `false` which keeps the current behaviour (no breaking changes)
