### ISSUE TITLE
`AutoWidth` configuration option

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1654]
Similar to what the Ajax controls expose:

http://docs.telerik.com/devtools/aspnet-ajax/controls/combobox/functionality/dropdown-autowidth

Not sure how this would work with virtualization, though. I think that we can list it as a limitation for the mode.

**Comment by valchev** [comment]
Similar behaviour is shown in this how-to article:
- http://docs.telerik.com/kendo-ui/controls/editors/dropdownlist/how-to/auto-adjust-the-width

The popup will auto-size if it has `width: auto`:
```javascript
dropdownlist.list.width("auto");
```
The widget header (anchor of the popup) will stay unchanged. This is how the Ajax DDL works.

**Comment by underlog** [comment]
Seems good. How hard would be to promote this to a built-in feature?

**Comment by tapopov** [comment]
Implemented in c1d26add89dae05299fce7550b536e4c1bead05d

**Comment by crazyfx1** [comment]
Should this work with virtualization? The documentation doesn't include a hint that virtualization is not supported for autoWidth. http://docs.telerik.com/kendo-ui/controls/editors/combobox/overview#configuration-Adjustment

Furthermore this feature was released in Kendo UI R3 2016 in September 2016, but the Typescript Definitions on NPM @types/kendo-ui are still missing the autoWidth property (i.e. on ComboBoxOptions).
