### ISSUE TITLE
Expose a boolean query method if the current value has a match from the available ones

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1655]
Requested here:

http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/5012741-check-whether-current-autocomplete-value-is-in-sug

**Comment by valchev** [comment]
This requests can be easily handled using the `dataSource.view()` result. If the view doesn't have length then the current AutoComplete value is not in the suggestions. Basically, the dataSource already has all of the required information to detect whether the value is valid or not.

Here are several use cases that can be easily handled with DataSource API:

- Check if value is valid on AutoComplete change event:
```javascript 
$("#autocomplete").kendoAutoComplete({
...
 change: function() {
    if (this.dataSource.view().length === 0) {
       alert("Current value is not part of the suggestions!");
    }
 }
});
```

- Check if value is valid during typing
```javascript
$("#autocomplete").kendoAutoComplete({
  dataSource: {
    ....
    change: function() {
       if (this.view().length === 0) {
            alert("Current filter (value) is not part of the suggestions!");
       }
    }
  }
});
```

Do we need a method that does those checks? We could add `contains` method that checks in the current `dataSource.data()` result. This, however, will behave inconsistently when remote data is used.

I would vote to ditch this feature for now. @underlog what do you think?

**Comment by underlog** [comment]
I see what you mean here. The examples provided above should be sufficient. I considered the feature trivial, but this does not seem to be the case. Let's close that with won't fix.
