### ISSUE TITLE
Multiple separators

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1656]
UV request:

http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/6151383-add-multiple-separators-to-autocomplete

**Comment by tapopov** [comment]
The Autocomplete's clear button affects the FilterCell widget, which has its own button. What would be the preferred course of action? Make the clear button optional and disabled by default (at least in the FilterCell) or something else? 
![image](https://cloud.githubusercontent.com/assets/5184468/16308003/078ace3a-396c-11e6-93a7-1c4dc0d7a1e8.png)

**Comment by ggkrustev** [comment]
I'd vote to leave that functionality disabled by default, even when the autocomplete is initialized as a standalone widget. 

Personally, I don't like IE style "X" clear button at all, but it could be just me :). @yordanov, what do you think?

**Comment by yordanov** [comment]
I would vote for leaving the clear button optional, but **enabled** by default. It is not visible in normal state, so it won't introduce any unnecessary visual clutter. I tend to think that people will like this enhancement and once they have the new bits they won't need to do anything as it will just be there. If the **x** is hidden by default, there is a big chance they won't even notice that such functionality exist.

Regarding the FilterCell, I would suggest to remove the dedicated **[X]** and use the new clear functionality from now on. It is just the more elegant way to do it - show the **x** only when it might be needed and reduce the number of UI elements in the FilterCell.

![filtercell](https://cloud.githubusercontent.com/assets/1118895/16333557/99cd14ae-3a04-11e6-8129-0ac04cec9590.png)

**Comment by tapopov** [comment]
The Multiple separators feature was added with commit 45bf98da09aa40e04eb99dfe4ec724f928c0e8e5
