### ISSUE TITLE
New preventable add/remove events

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1658]
Requested here:

http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/10204494-prevent-multiselect-from-deleting-items-using-new

http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/5328085-multiselect-add-add-remove-event-or-modify-change

**Comment by ggkrustev** [comment]
As we already have `select` event that is preventable, I would consider adding `unselect` event (following the same naming convention) that also will be preventable. The event will be raised when someone tries to unselect an item or tries to remove a tag.

The `select` and `unselect` events could be used like that:

```
$("#multiselect").kendoMultiSelect({
   ... //DataSource configuration and etc goes here
   select: function(e) {
     //'e' argument will contain:
     //e.item - the selected jQuery LI element
     //e.dataItem - the selected data item
     //e.preventDefault() - will prevent the action
   },
   unselect: function(e) { //the same as select
     //'e' argument will contain:
     //e.item - the selected jQuery LI element
     //e.dataItem - the selected data item
     //e.preventDefault() - will prevent the action
   }
});
```

@underlog, what do you think?

**Comment by ggkrustev** [comment]
After an offline discussion with @underlog, we decided to go with `deselect` and `select` events. This means that we will:

- Introduce `deselect` event with the following arguments:
```
{ item: $(LI), (?)tagItem: $(tag LI), dataItem: ObservableObject }
```
- Add a dataItem argument to `select` event to be consistent
