### ISSUE TITLE
Virtualization support without a value mapper

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1659]
A very thorough suggestion is present here:

http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/9006157-virtualization-without-valuemapper

**Comment by valchev** [comment]
Closed with 3164dd713e4d1b3214c4a51ff2b37c0cdac565e4

The following changes are introduced:

- (all) `valueMapper` is not a must have any more, the widget will not throw exception if the `valueMapper` is not defined
- (combobox, dropdownlist, multiselect) `valueMapper` is required only when the widget has initial value or when the value is being set through the `value` method of the corresponding widget. In that case, if the `valueMapper` is not defined the widget will throw exception with link to the documentation
- (autocomplete) `valueMapper` is never required
- (all) `mapValueTo` configuration was added. By default its value is `index` which does not change the current virtualization process (**no breaking changes** 👍 ).
- (all) the `mapValueTo` can also be set to 'dataItem'. In that case the `valueMapper` will be expected to return dataItem that corresponds to the value, not an index of a dataItem. This greatly simplifies the `valueMapper` implementation. The downside of `mapValueTo: "dataItem"` is that the list will not scroll the list to the selected item. For more detailed description please see the updated [virtualization topic](https://github.com/telerik/kendo-ui-core/blob/master/docs/controls/editors/combobox/virtualization.md#value-mapping)
- corresponding docs & api reference were updated
