### ISSUE TITLE
Support for defaultSelected

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1660]
This item needs some additional research. The concerns expressed in UserVoice sound valid:

http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/6717200-multiselect-control-defaultselected

MDN article:
https://developer.mozilla.org/en/docs/Web/API/HTMLOptionElement

**Comment by valchev** [comment]
I believe that we can resolve this request with an enhancement in the `<option>` elements generation. Now the widgets create an `<option>` tag only with value and text attributes:
- https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.list.js#L1063
We could create Option instances and setting the defaultSelected property with the initial ones. I'm not sure how this will fit the current options replacement though. This should be investigated further.

On a second thought, it will be much better if we just pass the old and new values in the change event callback. What do you think on this idea @underlog? It would be more work, but the benefit is much more tangible.

**Comment by underlog** [comment]
Great idea, but I don't know if we should not spread this to all widget change events. I would explore both, if possible.

**Comment by ggkrustev** [comment]
After a more detailed research, I would stand behind the opinion that the `defaultSelected` will have a very limited impact over the Drop-downs users. 

Basically, only users that initialize Drop-down widget from *pre-populated SELECT element* would use `defaultSelected` prop. On the other hand, support for that OPTION property will require a change in the options generation and how the selected value is being applied. Now, we update selected attribute on every change, which was actually a bug fix in the past.

Based on the little impact of supporting the `defaultSelected` property and the need to change the current behavior (introducing a breaking change), I would vote to **pass <old, new> values to the `change` event handler** of the widgets. Of course, this change should be applied across all Kendo input widgets.

**Comment by ggkrustev** [comment]
On a second review of the support case that precedes the UserVoice discussion, it seems that the requirement here is to provide a support for the 'default value' of the HTML element, which in the context of HTML Select is the `defaultSelected` property. This would help for dirty check scenarios - 3rd party validation libraries, which validates HTML elements directly (they are not aware of the JavaScript widgets that work on top of them).

The '<old, new>' values passed to the `change` event would not be sufficient for such tracking scenarios. That is why we will not discuss the possible implementation in this issue.

Support for the `defaultSelected` property could be easily implemented for a widget that is *bound only once*. When the source is dynamically modified (filtered or paged), the default selected options could be lost, which will break the dirty tracking logic.

Based on the given details, I would suggest to add support the `defaultSelected` attribute only for non-filtering / non-paging scenarios.

I will continue with the lastly suggested implementation. Let me know if any objections arise.
