### ISSUE TITLE
Enhance the search box behavior, so that no data is requested initially

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1661]
The option may be something like `minFilterLength`.

It should act pretty much like the autocomplete does. The behavior is briefly described here:

http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/6453493-dropdownlist-server-filtering-do-not-query-data 

This makes sense for large data sets, and would effectively suffice in scenarios currently using virtualization.

**Comment by valchev** [comment]
Added ComboBox here, as it is similar to the DropDownList. The new `footer` template will improve the UX as we could open the popup showing the user that he/she needs to type something to see suggestion items.

**Comment by valchev** [comment]
Closed with affe76d2bf3134802569bdd9308c61ec23c8829b

- DropDownList and ComboBox does not bind on open if `autoBind: false` and `minLength` is set to higher that 1 (**change in the previous behaviour**).
