### ISSUE TITLE
Removing item from the dataSource breaks selection

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#1668]
### Reproduction of the problem

1. Load the sample http://dojo.telerik.com/AdujOSej/5
1. Select "Something else" immediately after the page is loaded

### Current behavior
The value of the dropdown is removed

### Expected/desired behavior
Dropdown value becomes Apples

* **Kendo UI version:** 2019.2.619

**Comment by nenchef** [comment]
The behavior is expected when manually removing items from the datasource collection. If that's needed, one should set the selection manually as well.
