### ISSUE TITLE
Configuration of allowed file types

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-ui-core#1676]

**Comment by tsvetomir** [comment]
That might be implemented as a `allowedExtensions` array option on the root level.
Here is how it could look like:

```
$("#upload").kendoUpload({
    allowedExtensions: ["jpeg", "png"],
    ...
});
```

**Comment by Raisolution** [comment]
Upload widget now supports validation for allowedExtensions, minFileSize and maxFileSize.

**Comment by ipeshev** [comment]
@dmihaylo It is good to mentiond in the docs that allowedExtensions array recognizes entries with ".type" but not only "type" , also filesizes are measure in bytes.

**Comment by Raisolution** [comment]
We could discuss which entries to support - ".type", "type" or both. @tsvetomir what do you think?

**Comment by tsvetomir** [comment]
We should support both for the added convenience. I can't think of a situation where this would be ambiguous.

**Comment by dmihaylo** [comment]
Added the types of the extensions as agreed: http://kendobuild/kendo-ui/api/javascript/ui/upload#configuration-validation.allowedExtensions. 
The measurement of the file sizes in bytes is already mentioned in the article.
