### ISSUE TITLE
API for accessing the plotArea, panes, series and points

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#1678]
Currently the Chart does not allow access to its internal structure outside the configuration. This makes a lot of customization tasks harder than they should be.

This is a **living specification** of the API members that we'll introduce as part of this story:

* `Chart` - new methods:
 * `plotArea()` - returns a reference to the plot area
 * `findPaneByName(name)`
 * `findPaneByIndex(index)`
 * `findAxisByName(name)` - an alias for the existing `getAxis(name)`
 * `findSeries(predicate)`
 * `findSeriesByName(name)`
 * `findSeriesByIndex(index)`
 * `showTooltip(category | predicate)`
 * `hideTooltip()`

* `ChartSeries` - new class representing a single chart series
 * `toggleVisibility(show, predicate)` - show or hide the entire series or individual points (predicate receives data items)
 * `toggleHighlight(show, predicate|point)` - toggles the highlight of the series points or specific point.
 * `findPoint(predicate)` - finds series point.
 * `points(predicate)` - returns all the series points or the ones matching the predicate, if supplied
 * `data(newData)` - gets or sets the series data

* `ChartAxis` - new members:
  * `value(point)` - returns the axis value corresponding to the coordinates of the point
  * `slot(categoryText)` - the current overload only works for category indicies
  * `options` - reference to the axis options object
 * `valueRange()` - returns the value range of the points associated with the axis

* `Pane` - new class representing a chart pane
  * `visual` - a field referencing the pane visual element (a Group)
  * `chartsVisual` - a fields referencing the group holding the charts.
  * `name` - returns the name of the pane
  * `series()` - returns the series associated with this pane

* `PlotArea` - new public class for the Chart plot area
  * `visual` - a field referencing the plot area visual element (a Group)
  * `backgroundVisual` - a field referencing the plot area background visual element (a Path).

**Comment by danielkaradachki** [comment]
We can also include API for hiding/showing the tooltip similar to the one available currently for the [highlight](http://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart#methods-toggleHighlight).
