### ISSUE TITLE
When selecting item from keyboard in DropDownList with repeated key, It's not selecting the desired item

### ISSUE THREAD

**Issue by Sajan-Kumar-Devarakonda** [telerik/kendo-ui-core#1681]
For example, If we have list of items in dropdownlist like [10,102, 11,12,20,21,22,30,31,32,33]
if we press '10' from keyboard it selecting correct item '10' , but when we enter '11', it is going to select next item of 10 instead of 11, In plugin it's checking with the _last key value and current key value then it selecting the next item of previously selected item, it's desirable but addition to this we need to add extra functionality for selecting items with repeated key values.

**Comment by zdravkov** [comment]
This is the default behavior of the control and the usual way that selection is done in list controls when there is not filter. In your scenario I would rather recommend you using the Combobox control as for example it is done in this [dojo page](https://dojo.telerik.com/oTOTar/2).
