### ISSUE TITLE
Add a remove() method for removing a single file

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-ui-core#1685]

**Comment by tsvetomir** [comment]
This might be implemented as `remove(predicate)` where you decide what to remove based on the information for the file entry.

**Comment by Raisolution** [comment]
@tsvetomir, indeed this will be good way to filter files, when more than one have to be removed.
I think we should also have a way to remove a concrete one by specifying either index, uid or DOM element for example.

**Comment by tsvetomir** [comment]
I'm okay with having a dedicated `removeFileById` method.

Index, DOM element and so on are easier to implement with a matching function.

```
// Removes a file by ID
upload.removeFileById(id);

// Removes all files
upload.removeFile(); 

// Removes all files for which the callback returns true
upload.removeFile(function(entry) {
    // entry has fields like id, name, index, element and so on
    return entry.name === "foo.txt";
});
```

**Comment by tsvetomir** [comment]
We can also add overloads that remove the files only from the UI.

```
// Removes all files without issuing requests to the remove handler
upload.clearAllFiles();

// Removes all files for which the callback returns true
// without issuing requests to the remove handler
upload.clearFile(function(entry) {
    // You can submit a request to the remove handler here, if needed
    // $.ajax({ url: "/remove", data: { name: "foo" } })    

    return entry.name === "foo.txt";
});
```

**Comment by Raisolution** [comment]
I ended implementing 3 pairs of methods:

- removeAllFiles / clearAllFiles
- removeFileByUid / clearFileByUid
- removeFile / clearFile (via callback)

in which the remove methods send a standard remove request to the handler, while the clear methods remove the files only visually from the UI.
