### ISSUE TITLE
Spreadsheet cell ignores the format option when a date value is entered and format it as date. 

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#1686]
Steps to reproduce the issue: 
  1. Open the http://dojo.telerik.com/IXAzO example. 
  2. Set "Number" format for a cell. 
  3. Type "1/30" and then tab.

Even if the format is set to number, the value in the cell is formatted as a Date object.

**Comment by mishoo** [comment]
`1/30` is not a number, so the format is reset.  If you type `=1/30`, then yeah, that's a formula that returns a number and it will be displayed accordingly.

The same happens in Google Sheets.

**Comment by tsvetomir** [comment]
I think its a case where Excel tries to be a bit more clever than it should be and converts `1/30` to a formula because of the set format.

Let's not try to emulate this at least until we can get away with it.
