### ISSUE TITLE
NumericTexbox Min/Max validation scenario

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1690]
It seems like many users find the current min/max behavior confusing:

http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/10779708-change-numeric-textbox-k-min-k-max-validation-beha

I think that this is a matter of documenting and demoing integration with the validator. If time permits, we may also provide one for AngularJS.

**Comment by ggkrustev** [comment]
Document range validation - 0443075

**Comment by ggkrustev** [comment]
Add range validation demo - https://github.com/telerik/kendo/commit/8368bb0889cea2491386bbd7aa75c201c32dec26
