### ISSUE TITLE
Copy maxlength attribute to the visible input element

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#1691]
### Description
The widget copies the input `style` and `class` options to the generated visible input element. The maxlength attribute, however, is not copied. 

#### Implementation
Copy the `maxlength` attribute on init:
```
<input id="combobox" maxlength="10" /> 
```
should be copied to the visible input
```
<input class="k-input" type="text" maxlength="10" role="combobox"/>
```

Related to [this UserVoice item](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/13309716-add-a-maxlength-shortcut-to-kendo-combo-box)

**Comment by tapopov** [comment]
Implemented in d0ea9d15b47dfebc29f89acaa91e2cf1f5246a83
