### ISSUE TITLE
Demo that showcase picking single/multiple items from a dialog from a form

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1695]
There is a certain interest in scenarios that allows the user to select items from a treeview, a grid, or list of checkboxes. Many people attribute this to a feature of the combobox, however, I think that the wide variances here make it more suitable for a demo. 

The basic setup includes a form, a read-only field (may be a text box, or just text), and a button that will open a dialog (#1664) that contains a widget that supports selection in some form and OK  | Cancel buttons. In general, the scenario suggests a lot of items, so filtering of the widget may be enabled. If possible, the filter box should be automatically focused when the dialog is open. 

The widget in the dialog may be a treeview, a grid, or a listview with checkboxes. 

http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/3767009-treeview-in-combobox
http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/3616075-combobox-with-checkboxes
http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/10600184-grid-in-combobox

Once the item is selected, the user closes the dialog, and the form state changes to display the selection. Re-opening the dialog populates the selection state. 

@yordanov  - I think that we will need some wireframes here. Pass this after done.

**Comment by yordanov** [comment]
##### Scenario 1: Dialog + TreeList with CRUD and Checkbox column

![option1-preview](https://cloud.githubusercontent.com/assets/1118895/15545718/021bd8e0-22a6-11e6-841b-0055625e583e.png)


![option1](https://cloud.githubusercontent.com/assets/1118895/15545525/43e2214a-22a5-11e6-860f-b7198f13f4ae.gif)

**Comment by yordanov** [comment]
##### Scenario 2: Dialog + TreeView with Checkboxes and Filtering input


![option2-preview](https://cloud.githubusercontent.com/assets/1118895/15567544/b29eefca-232f-11e6-85d1-915b2a9f83d5.png)

Option 1: [Select All] checkbox is always visible and selects only those items that are currently displayed/filtered
![option2](https://cloud.githubusercontent.com/assets/1118895/15567710/752aff2a-2330-11e6-87c8-8519bd1a0db2.gif)

Option 2: [Select All] checkbox is visible only when there is no filter applied and all TreeView items are visible
![option2a](https://cloud.githubusercontent.com/assets/1118895/15567902/a7593bbe-2331-11e6-9619-496cbee19b74.gif)

Both approaches are valid as we don't want one to select/deselect items that are not displayed in the TreeView.

**Comment by dana-shalev** [comment]
Hi
We are currently evaluating Kendo UI and once of our main requirements is a drop down containing a tree.
The demos i see here look great :)
Will the both single and multi selection be supported in the tree?
Do you have a planned time estimation of when these components will be released?

**Comment by underlog** [comment]
The demos above will be part of our R3 release, due September - you can check assigned milestone.  The dialog contents and the selection logic will be arbitrary - one can put flat lists, grids, trees, etc.

**Comment by asmita2201** [comment]
Hello, Theres no milestone assigned. Is this ready yet?

**Comment by underlog** [comment]
The milestone was removed by mistake.

**Comment by asmita2201** [comment]
Do let us know where can we access this component now? Thanks

**Comment by tsvetomir** [comment]
* [Dialog / TreeView in Dialog](http://demos.telerik.com/kendo-ui/dialog/treeview-integration)
* [Dialog / TreeList in Dialog](http://demos.telerik.com/kendo-ui/dialog/treelist-integration)

**Comment by asmita2201** [comment]
Thank you guys!!! this will be helpful!

**Comment by asmita2201** [comment]
One question, this doesn't select the parent by Defalut. Also I select Andrew fuller – level 1 of a tree can it automatically select Nancy, Janet and Margaret at the same time and visa a versa?

**Comment by underlog** [comment]
This is a demo - you may pick the sample code and use it as a starter implementation for your business requirements. In case you need any further assistance, feel free to contact us through our support system.
