### ISSUE TITLE
Allow setting request headers in data source configuration

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#1696]
A common requirement is to be able to set request headers, e.g. for authorization. The way of doing this right now is awkward at best. It requires disabling the initial request and overriding `beforeSend` on the client.

``` cshtml
@(Html.Kendo().Grid<Kendo.Mvc.Examples.Models.OrderViewModel>()    
    .Name("grid")
    ...
    // Suppress initial binding request
    .AutoBind(false)
    .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(20)
        .Read(read => read.Action("Orders_Read", "Grid"))
     )
)

<script>
    $(function() {
        var grid = $("#grid").data("kendoGrid");

        grid.dataSource.transport.options.read.beforeSend = function (req) {
            req.setRequestHeader('Authorization', 'auth token goes here');
        };

        grid.dataSource.read();
    });
</script>
```

Implementing this [UserVoice item](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/6095996-allow-kendo-mvc-to-use-beforesend) can make this easier, but it still won't signal the intended usage.

What we can do instead is to add a `HttpHeaders` configuration option on the actions:

``` cs
.Read(read => read.Action("Orders_Read", "Grid").HttpHeaders(new { Authorization = "foo" } ))
```

This has the benefit of clearly stating what it does and allows setting the values without scripting.

Thoughts @rkonstantinov @ivanchev @Xizario ?

**Comment by Eneuman** [comment]
Hi!
We really need this quick.
Everyone is moving over to access tokens, and right now it's really messy to get it working with Kendo MVC. Having .read rely on a Identity Token for authorization is not good practice.

**Comment by atlanticstarr1** [comment]
Telerik,
per tsvetomir, it is really awkward to implement this feature. Has an easier solution been implemented on your end ?

**Comment by Xizario** [comment]
@atlanticstarr1, property like HttpHeaders is not yet added.

**Comment by gcedil** [comment]
+1 would also like to see this added two years later...

**Comment by Alex-Bubblemaster** [comment]
Also requested in ticket with ID 1361188

**Comment by Alex-Bubblemaster** [comment]
Also requested in ticket with ID 1381237

**Comment by Alex-Bubblemaster** [comment]
Also requested in ticket with ID 1380949

**Comment by AlekseyKrainev** [comment]
+1, would be useful

**Comment by Alex-Bubblemaster** [comment]
Configuration


mvc/core wrapper

```
@(Html.Kendo().Grid<Kendo.Mvc.Examples.Models.CustomerViewModel>()
	.Name("grid")
	
	.DataSource(dataSource => dataSource
		.Ajax()
		.Read(read => read.Action("Customers_Read", "Grid")
			.Headers(new { header1 = "test1" })
		)
	)
)
```

Tag helper:
```
@{
    var headers = new Dictionary<string, string>();
    headers.Add("header1", "value1");
}

<kendo-datasource name="dataSource1" type="DataSourceTagHelperType.Ajax" server-operation="false">
    <transport>
        <read url="@Url.Action("Products_Read", "DataSource")" headers="@headers"  />
    </transport>
</kendo-datasource>
```

Expected result when a CRUD operation is executed:
![headers](https://user-images.githubusercontent.com/1857705/57527791-3faad080-7339-11e9-9018-99300526cafd.png)
