### ISSUE TITLE
Widget closes popup on scrollbar click in IE11

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#170]
### Information

The widget closes its popup when user tries to scroll down the list.
### Steps to reproduce
1. Click the "arrow" icon exactly.
2. Click the scrollbar of the popup element
### Repro demo

http://trykendoui.telerik.com/@ggkrustev/udIn
### Update (2014-10-06):

The problem appeared again in the latest IEs (10 and 11)
Reported in:
865257
859232

The fix is to remove the patch added for IE9, which is not required any more.

**Comment by solidoussnk** [comment]
Hello, I am part of a team assisting in trouble shooting this issue as well. I have two questions:
1) How can I identify the IE9 Patch?
2) How can I remove the IE9 Patch?

Thanks.

**Comment by ggkrustev** [comment]
Hi @solidoussnk,
I would suggest you review the commits list visible in this issue.
Here are answers to your specific questions:

1. In general, the patch was related to wire "mousedown" event handler to the arrow icon. The function name is `_iconMousedown` and the place where it is used is `_span`. Both functions can be found in "kendo.dropdownlist.js"
2. Remove the "mousedown" event handler of the arrow icon.

I strongly suggest review the applied commits.

**Comment by solidoussnk** [comment]
Hey, Thanks for the quick feedback.

**Comment by R1c3** [comment]
Hi @ggkrustev 

Still able to replace this on latest IE11, opening the drop-down and click anywhere on the scrollbar causes the Close event to fire.

**Comment by ggkrustev** [comment]
Hi @R1c3,

I tried to replicate the issue locally, but to no avail. Here is a screencast of my test:
[http://screencast.com/t/QRmd95B2M7](http://screencast.com/t/QRmd95B2M7)

Could you provide a runnable test demo and/or screencast that replicates the issue ?

**Comment by hbarpitgupta** [comment]
Hey, 

Please provide the kendo.dropdownlistJs update file ASAP....
