### ISSUE TITLE
TabStrip select seems to suffer from regression

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1702]
The example here: http://docs.telerik.com/kendo-ui/api/javascript/ui/tabstrip#methods-select does not work as expected. Commenting the first select call seems to fix the problem.

**Comment by tsvetomir** [comment]
Both select calls seem to work as expected on their own.
Calling them in order unexpectedly leaves the first tab selected (index is zero-based):

    tabStrip.select("li:first");        // Select by jQuery selector
    tabStrip.select(1);                 // Select by index

I don't see different behavior with older versions.

**Comment by KirilNN** [comment]
I am not sure that this is a regression as it is the same behavior since 2014 Q2 release. Actually it might be the intended behavior due to this:

https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.tabstrip.js#L1112

**Comment by underlog** [comment]
Nice catch! Indeed, this is so. I suggest that we fix the documentation, then. Perhaps change the tab with a button?

**Comment by KirilNN** [comment]
Done with https://github.com/telerik/kendo-ui-core/commit/2473bf366dfdc96929aac38e72272da0ac5ad89f!
