### ISSUE TITLE
Deleting list items with the Backspace key results in incorrect content

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-ui-core#1716]
Steps to reproduce:
1. Open an Editor demo (http://demos.telerik.com/kendo-ui/editor/index).
2. Place the cursor before the first word in the first list item and press Backspace.
3. Place the cursor before the first word in the new first list item and press Backspace two times.

Expected:
The list item is successfully removed from the list.

Actual:
The list item is moved to the bottom of the content.

The problem can be reproduced in Chrome and Firefox, but there is an incorrect (although different) behavior in Internet Explorer as well.

Reported in Ticket ID: 1037158

**Comment by Dimitar-Goshev** [comment]
Not reproducible since version 2016.3.1028 - R3 2016 SP1
