### ISSUE TITLE
Improve layout and styling of validation dialog

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-ui-core#1725]
**Current:**
![validation-dialog](https://cloud.githubusercontent.com/assets/1118895/15603181/05d4bbc0-2402-11e6-8cc9-408daa25d846.png)

**Should be:**
![validation-dialog1](https://cloud.githubusercontent.com/assets/1118895/15603295/8c6d3b62-2402-11e6-8eb5-379acb0adae9.png)

**Comment by gyoshev** [comment]
Closed via telerik/kendo@7cf6ab5

**Comment by ipeshev** [comment]
On all themes radiobuttons and checkboxes are not aligned with their labels
![capture 2016-08-03 at 17 55 09](https://cloud.githubusercontent.com/assets/4143177/17935459/18cf220c-6a24-11e6-96bf-7911c8fd9f81.png)

**Comment by inikolova** [comment]
Commits: 2d10124a28f4d12,  ed6c06c5fd113380e33

**Comment by ipeshev** [comment]
the problem with misaligned radiobuttons and checkboxes is moved into another issue #2213
