### ISSUE TITLE
Create color themes that comply with the skins in UI for ASP.NET AJAX

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-ui-core#1737]
- Create additional kendo.[theme].less files with color palettes matching the skins available in the [ASP.NET AJAX suite](http://docs.telerik.com/devtools/aspnet-ajax/controls/grid/appearance-and-styling/skins)
- Document how to run them against the current set of [Kendo UI theme types](http://docs.telerik.com/kendo-ui/styles-and-layout/appearance-styling#common-css-files).

**Comment by Dimitar-Goshev** [comment]
LESS ThemeBuilder is deprecated.
