### ISSUE TITLE
Tabindex not working in numerictextbox

### ISSUE THREAD

**Issue by dfperry** [telerik/kendo-ui-core#1741]
The tabindex property gets cleared in a kendo numerictextbox after rendering when set from the scope/model.

Seen in this example:
http://dojo.telerik.com/UBIGu

**Comment by ggkrustev** [comment]
This is a known behavior well documented here:

http://docs.telerik.com/kendo-ui/AngularJS/Troubleshooting/common-issues#angularjs-templates-are-not-evaluated-before-widget-initialization

Will close this thread

**Comment by dfperry** [comment]
so if the numerictextbox control gets created at compile time, how am I supposed to set the tabindex value when the scope isn't available at that point?
