### ISSUE TITLE
Build on Windows failed

### ISSUE THREAD

**Issue by h2soft-de** [telerik/kendo-ui-core#1745]
Install VM
Windows 10 x64 1511 Update Apr 2016

Install git
https://git-scm.com/
v2.8.3

Install nodejs
https://nodejs.org/en/
v4.4.5

execute
git clone https://github.com/telerik/kendo-ui-core.git

execute
git submodule update --init

execute
npm run build
FAILD! first error: gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

Install python
https://www.python.org/downloads/
v2.7.11

execute
npm run build
still failed!!! not realy an usefull error message.

delete folder nodes_modules ...

execute
npm run build
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23                                                )

A forum entry suggests to install Visual Studio Express 2013 with c++ redist
done

execute
npm run build
Failed with:
C:\_src\kendo-ui-core\node_modules\grunt-debug-task\node_modules\node-inspector\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>if not defined npm_confi                           g_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
C:\_src\kendo-ui-core\node_modules\grunt-debug-task\node_modules\node-inspector\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(4                           09): error C2039: 'ExternalAsciiStringResource' : is not a member of 'v8::String' [C:\_src\kendo-ui-core\node_modules\grunt-debug-task\node_modules\node-inspector\node_modul                           es\socket.io\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
...

Please help.

**Comment by underlog** [comment]
I don't see anything Kendo UI specific in the stack traces you provide - most likely one of the dependencies (socket.io?) fails to compile in your environment. You may request assistance from the respective project maintainers.

**Comment by Xtrem4** [comment]
Hi guys I had slight fix for gyp err and now I'm stuck with npm err. Please assist.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xhlongwane\\AppData\\Roaming\\npm\\node_modules\\npm\\bi
n\\npm-cli.js" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! kendo-ui-core@1.0.0 build: `npm install && ./node_modules/.bin/gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kendo-ui-core@1.0.0 build script 'npm install && ./node_modules/.bin/gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kendo-ui-core package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && ./node_modules/.bin/gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kendo-ui-core
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kendo-ui-core
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xhlongwane\Documents\frameworks\kendo\kendo-ui-core\npm-debug.log
PS C:\Users\xhlongwane\Documents\frameworks\kendo\kendo-ui-core> 0 info it worked if it ends with ok
