### ISSUE TITLE
Spreadsheet displays undefined after number formatting

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#1746]
Spreadsheet displays **undefined** after _number formatting_ on empty cells.
The issue appear after two clicks on **decrease** or **increase** decimal button from the toolbar.

Issue can be reproduce in the following demo: http://demos.telerik.com/kendo-ui/spreadsheet/index

All steps to recreate the issue:

1. Blank one of the numeric cells. Use C3, for this example
2. Select column C
3. Format column C to be 'Number' using the 'Custom Format' dropdown from the toolbar
4. Note that C3 is still blank, as expected.
5. With column C still selected, click 'Decrease Decimal' (on the toolbar) twice to remove the decimal component of the number
6. Note that cells without numbers in them (either originally empty or originally with a number, such as C3) now contain 'Undefined' rather than being blank. Increasing the decimal has no effect on this behavior.
7. Repeat the action from Step 3 (above). Problem disappears until Step 5 is executed.

Reported in TicketID: 1039657.

**Comment by gyoshev** [comment]
I tracked down that an undefined value [is passed](https://github.com/telerik/kendo/blob/master/src/spreadsheet/view.js#L231-L232) to the number formatting function from the view. Do we need this for any formats?

It also occurred to me that `adjustDecimals` [keeps on adding negative formats](http://dojo.telerik.com/oBeGu), which does not seem right. @mishoo should we add the check, or just change the adjustDecimals?

**Comment by mishoo** [comment]
> I tracked down that an undefined value is passed to the number formatting function from the view. Do we need this for any formats?

Nope.  I actually wanted to write `!= null`, but then JSHint would make me feel sad.  In files I mostly wrote myself I always use `eqnull: true`.  Yeah, we should definitely not call the formatting code with `undefined`, I'll fix that.

> It also occurred to me that adjustDecimals keeps on adding negative formats, which does not seem right.

Definitely looks like a bug in `adjustDecimals`, I'll investigate.

**Comment by mishoo** [comment]
Just for the record, after b91c10d1948bb2894173199180fa4f3e3bd7336b there should be no problem calling the formatting code with `undefined`.  I added the check nonetheless.

Fixed.

**Comment by tsvetomir** [comment]
Note that this fix won't make it in the 2016 R2 SP1 release, it will be included in builds versioned 2016.2.607 and later.
