### ISSUE TITLE
Error message not showing when number of rows pasted is greater than Spreadsheet's rows

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#1748]
Reported in Ticket ID: 1039891

To recreate:
[http://dojo.telerik.com/@bubblemaster/oFofu](url)
- Copy the data(1-11 commented block) in the Dojo sample and paste in any cell of the spreadsheet
- New data is not visible for few seconds or until click

Additional observations:
- TypeError: Cannot read property 'value' of undefined - in the browser Console
- Error Message "Cannot paste, because the copy area and the paste area are not the same size and shape." appears eventually after a few repetitions of pasting invalid size of data

**Comment by tapopov** [comment]
Version 2016.3.1028 exhibits even stranger behavior. The data is pasted without any notice that it doesn't actually fit, however the penultimate item is removed. The result is 1,2,3...8,9,11. Any subsequent attempt to paste the same content throws the expected error. I will update this thread as I continue investigating the issue.

**Comment by tapopov** [comment]
Fixed.
