### ISSUE TITLE
Table Wizard dialog

### ISSUE THREAD

**Issue by Jekata** [telerik/kendo-ui-core#1754]
It will be similar to the [Table Wizard](http://docs.telerik.com/devtools/aspnet-ajax/controls/editor/functionality/dialogs/table-wizard) of RadEditor for ASP.NET AJAX and allows table creation, configuration and editing through an easy to use UI. 

UserVoice item: http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/5853229-kendo-ui-editor-table-wizard

**Comment by Jekata** [comment]
Add ability to insert formatted tables like the one in this blog post: http://www.sitefinity.com/blogs/blog-of-barrett-coakley/2016/05/11/how-to-enable-digital-marketing-agility
Similar functionality is already offered by RadEditor Table Wizard.

**Comment by Dimitar-Goshev** [comment]
Table Wizard is added in R3 2016 - https://docs.telerik.com/kendo-ui/controls/editors/editor/table-wizard-dialog
