### ISSUE TITLE
Export Grid Data to CSV/XLSX

### ISSUE THREAD

**Issue by Jekata** [telerik/kendo-ui-core#1757]
You will be able to export the Grid data to the popular CSV and XLSX formats via [the RadSpreadProcessing library](http://docs.telerik.com/devtools/wpf/controls/radspreadprocessing/overview) or the brand new RadSpreadStreamProcessing.

**Comment by Dimitar-Goshev** [comment]
- UI for ASP.NET MVC - Server export to CSV and XLSX is supported since R3 2016 - http://demos.telerik.com/aspnet-mvc/grid/server-export
- UI for ASP.NET Core - Server export to CSV and XLSX is in development for R1 2021.
