### ISSUE TITLE
Export to excel with aggregates / footer templates

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-ui-core#1765]
Footer templates are incorrectly rendered only once, at the end of the widget.

Reported in support thread 906729

**Comment by simonssspirit** [comment]
Reported again in ticket: 1098579

**Comment by simonssspirit** [comment]
Please check the following Dojo demonstrating the issue: http://dojo.telerik.com/ERUPu

**Comment by simonssspirit** [comment]
Reported again in ticket: 1124472

**Comment by MilenaCh** [comment]
Footer for the last cell is not exported in the correct cell in excel
Configuration
http://dojo.telerik.com/ERUPu/8

**Comment by Alex-Bubblemaster** [comment]
#3702
