### ISSUE TITLE
InsertHtml command unnecessarily scrolls page with inline editor

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#1791]
[Reproduction sample](http://dojo.telerik.com/@nikmaslik/INAwA)

Related to: telerik/kendo#5341; [UserVoice#127393](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/14798697-kendo-editor-scolls-to-end-when-pasting-from-clipb);

**Comment by krzyszt0fd** [comment]
I have same issue in version 2016.2.714. Is it possible to obtain a patch through support?

**Comment by KirilNN** [comment]
Hi @krzyszt0fd,

I am afraid that patches for older versions are not possible, as always the supported version is the latest one.
