### ISSUE TITLE
Hiding a column leaves ghost merged cell visible

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1794]
Steps to reproduce:

load the file below in http://demos.telerik.com/kendo-ui/spreadsheet/index 
[hideIssueWorkbook_simplified_1yr_nomonths.xlsx](https://github.com/telerik/kendo-ui-core/files/315628/hideIssueWorkbook_simplified_1yr_nomonths.xlsx)

hide B:F columns. Result here:

![screen shot 2016-06-15 at 10 53 18](https://cloud.githubusercontent.com/assets/13347/16072052/669acf6e-32e7-11e6-8be3-f1309c0241e3.png)

**Comment by mishoo** [comment]
I pushed a rendering fix, but it's not complete yet.  Can be seen in `playground/spreadsheet/merged.html` — the initial rendering is fine.  If you unhide columns B, C, D and then select and hide them again, the bad rendering appears to come back.  The problem now is that the hidden columns remain selected (which Should Not Happen™).  You can move `up` and `down` to see the other hidden cells while they are active.  Once you press `left` or `right` and leave the hidden columns, you can no longer select them until you unhide them.

I suggest the next proper fix would be to move selection to the next (or previous) visible column (or row) after hiding columns/rows. (G.Sheets do the same)

**Comment by mishoo** [comment]
BTW, somewhat funny: one can hide all rows and all columns in a sheet, and then there is no way to unhide :-).  I'd call it a minor issue, should we attempt to fix? (probably add a "unhide all" item in the context menu of the top-left header cell?)

**Comment by underlog** [comment]
All in for the selection change.

**Comment by tsvetomir** [comment]
An "Unhide All" option in the context menu will help. The case is not handled very well in Excel as well - it's possible to end up with all columns hidden and no option to show them :)

**Comment by mishoo** [comment]
Done the selection update.  I don't quite like the code though :-( reviews/critics welcome. :-)

**Comment by tsvetomir** [comment]
The `while(true)` loop makes me cringe a bit, but it's expresses the intent fairly well. I'd leave it as it is.

Thanks!
