### ISSUE TITLE
Inconsistency when disabled dates are manually entered in the picker

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#1795]
Refer to the following dojo example: 
http://dojo.telerik.com/ecILA/2

Steps to reproduce:
1) In empty picker, enter disabled data (6/12/2016) for example
result -> value is cleared
2) Pick or enter valid date and then change it to a disabled date (without clearing the valid date)
result -> value is not cleared

**Comment by KirilNN** [comment]
I would like to see a comment from @ggkrustev, as I am not sure what is the expected behavior here.

**Comment by ggkrustev** [comment]
We'd need to persist the typed text in 1) to be consistent with 2). 

[TL;DR]
Although it sounds strange, the idea behind the widget is to keep the wrong value and allow the developer to validate it with separate validation mechanism.
