### ISSUE TITLE
Cascading not working when filtering is enabled

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#1796]
Having cascading dropdowns, if the dropdown has filtering enabled and you select an item, the next dropdown is not activated.
Browsers: Internet Explorer, Older versions of FireFox (45.0.2).
Bug Introduced in 2016 R2 SP1. 
Demo reproducing the problem: http://dojo.telerik.com/ogaRA/2
Reported in:
Ticket ID: 1042747
Ticket ID: 1053473
Ticket ID: 1056922

**Comment by ggkrustev** [comment]
We will schedule the fix  for Q3 2016 (tentative). If it is not resolved in the next official release, then we will postpone it for first service pack.

**Comment by LorenDorez** [comment]
@ggkrustev   Is there a work around we can apply right now? I have a few systems that are live that use this feature.

**Comment by jmead1** [comment]
Hi LorenDorez - there is a work around. 
You can force the cascade child to reload correct data by resetting its datasource in the change event of the cascade parent.

 In the "parent" cascading drop down's change event, add two lines:

    var childWidget = $("#ChildDropDownId").data("kendoDropDownList");
     childWidget.setDataSource(childWidget.dataSource);

**Comment by LorenDorez** [comment]
@jmead1 

Thanks that appears to get me buy until the new Update Release
