### ISSUE TITLE
Cannot choose from all items when filtering is applied once

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#1797]
_Issue_: Once filtering is **applied**, if the user tries to filter it again the Filter popup editor is not showing all items. Check the expected behaviour in Excel.

_Reason way this is needed_:  "**Add to current selection**" checkbox can only retain the filtered selection and can not extend it.

_Where the issue is reproducible_: http://demos.telerik.com/kendo-ui/spreadsheet/sorting-filtering 

_Admin ticket_: 1043483

**Comment by Dimitar-Goshev** [comment]
Admin ticket: 1081977
