### ISSUE TITLE
Error: kendoDropDownList attribute used but expression in it is not assignable: kendo-drop-down-list

### ISSUE THREAD

**Issue by bryandent** [telerik/kendo-ui-core#1798]
This error appears with literally all the AngularJS directives.  Researched the error and cannot find any details regarding it.  The control functions as expected, so this is a bit troubling that the error appears for so many of the controls, yet still works as expected.  We are considering purchase of the full version, but have doubts when we see these types of errors.  Please advise.
<img width="1003" alt="napkin 06-15-16 12 02 36 pm" src="https://cloud.githubusercontent.com/assets/1007794/16087466/0ebf3f1e-32f1-11e6-9c8c-0045184583f6.png">

**Comment by underlog** [comment]
Hey, 

thank you for your interest in Kendo UI. Given the specifics of your inquiry, I may suggest that you submit a support ticket through the Telerik support system and attach a runnable sample of your case. We should be able to help you further from there.
