### ISSUE TITLE
Copy from empty cell pasts null value

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#1799]
Steps to reproduce:
    
Open kendo spreadsheet demo site (https://demos.telerik.com/kendo-ui/spreadsheet/index)
Press Ctrl + C on a blank cell(for example B:13)
Paste on a random cell(for example C:13)
“null “ is pasted in the cell instead of blank

**Comment by mishoo** [comment]
Fixed in https://github.com/telerik/kendo/commit/e451bd65f4663598ebaba080a69bf18eca463440 (commit log links to the wrong issue).
