### ISSUE TITLE
Deleting a column after another is hidden causes wrong layout

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#1800]
Open kendo spreadsheet demo site (https://demos.telerik.com/kendo-ui/spreadsheet/index)
Hide row with index 4
Delete row with index 3

the column is shrunken instead of being deleted

**Comment by mishoo** [comment]
Duplicate of #1801 (it's fixed by the same [commit](https://github.com/telerik/kendo/commit/0caf3052d737da6fdbae55e802e12a08d8a4d99c)).
