### ISSUE TITLE
Pasting into a disabled cell from an edited cell / plain text leaves the cell blank

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#1802]
Dojo:  http://dojo.telerik.com/aHilE/62

Screenshot: 
![f2cf6ef4-a217-4388-a216-124fe33dce0d_disabledpaste](https://cloud.githubusercontent.com/assets/13347/16109218/5f2a51cc-33b0-11e6-8559-a81d550e693d.jpg)

Additional info from the ticket:

> If you copy the cell and not the actual content, that is not disturbing the disabled cell on pasting but if you copy the content of the cell and then paste on disabled cell, its becoming blank. Same case if you copy content from notepad and paste in disabled cell, its becoming null.

**Comment by ipeshev** [comment]
@mishoo currently it is marking the cell like it does have invalid content, but it is not accepting pasted content in disabled cell. Is it by design to mark call as invalid.

**Comment by ipeshev** [comment]
Currently this behavior can't be observed under IE11.
