### ISSUE TITLE
Editor insertion bug

### ISSUE THREAD

**Issue by stetod11** [telerik/kendo-ui-core#1806]
We have discovered an issue in the Editor around insertion of text using a custom button - it can be seen at http://dojo.telerik.com/EZijI 

If you highlight text that is contained within a `<span>` tag, and use a custom button to insert more text (in this case, replacing the highlighted text with other text), the text gets removed successfully, but the `<span>` gets closed, and the inserted text appears outside the closing `</span>` tag. 

Given that `<span>` tags can be used to format text, you therefore lose the formatting you had applied to the text you removed, and the new text appears unformatted i.e. inheriting formatting from the parent, which is not expected behaviour.

**Comment by underlog** [comment]
thank you!

**Comment by stetod11** [comment]
Is there a reason why this hasn't yet been labelled or assigned a severity, yet stuff that has been logged more recently has? This is a fairly fundamental problem for us - having to hack the HTML defeats the purpose of an editor that non-technical users can use

**Comment by underlog** [comment]
The problem in question seems like a fairly complex one. I assigned the tags in question, but we can't commit to a specific milestone for its resolution.

**Comment by stetod11** [comment]
Any clue as to when this might be addressed..?

**Comment by stetod11** [comment]
This was logged  more than a year ago, and remains an issue for us - any clue as to when it will be addressed?

**Comment by stetod11** [comment]
Hi,

Any chance someone could get around to fixing this for us?

19 months have elapsed, yet no further comments have been added nor timescale for resolution.

**Comment by bergenhem** [comment]
You should already have this answer, but to let everyone else viewing this issue know/doing some house cleaning I'll mention this here and close the issue.

This issue should be solved by using [the paste method](https://docs.telerik.com/kendo-ui/api/javascript/ui/editor#methods-paste) and it's options.split parameter. This is responsible for determining if the surrounding formatting should be split prior to inserting the pasted HTML. Setting this to false should have the desired outcome. [Here's a sample](http://dojo.telerik.com/EZijI/11) that showcases the usage (the command at the end of the snippet specifically).
