### ISSUE TITLE
Wrong positioning of the popup when page is zoomed and scrolled on Chrome for Android

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#1814]
Zooming in Chrome for Android causes the popup of dropdown devices to be offset. The between the input and the popup varies depending on the zoom and the scroll position:

![image](https://cloud.githubusercontent.com/assets/7533599/16148896/58e970be-3495-11e6-965b-625523be601f.png)

To reproduce the problem:
1- Open http://runner.telerik.io/fullscreen/ACIfA/6
2- pinch to zoom in
3- scroll a little on the Y axis, (window.scrollY must not be 0).
4- open the datapicker to see the calendar.

**Comment by ggkrustev** [comment]
Reported already in telerik/kendo-ui-core#1609
