### ISSUE TITLE
The row resize handle does not appear when the first column is hidden

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#1815]
### Bug
If the first row is _hidden_ the column resize icon do not appear on hover and vice versa. Also, if _both_ are hidden neither the row or the column  resize icon will appear.

### Reproduction
The issue is reproducible in every Kendo UI Spreadsheet, for example: http://dojo.telerik.com/AWaGA/3

Ticket: 1043954

### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
After the fix the initial problem is not reproducible. But now resize handles for the first row and column appear, although they are hidden. As a result, content of the hidden row can be shown. The content of the column is not visible, but it also can be expanded to become visible:
![image](https://user-images.githubusercontent.com/6614183/42695116-1154e536-86bd-11e8-86bc-0539f374e0f1.png)
To reproduce the issue, hide column A and row 1, then hover to the left border of column B or to the top border of row 2. As a result, a drag handle is visible and may be dragged.
