### ISSUE TITLE
Explain how the Navigator and its dataSource relates to the Stock Chart and its dataSource

### ISSUE THREAD

**Issue by dimodi** [telerik/kendo-ui-core#1816]
requested in ticket 1043630

**Comment by Stamo-Gochev** [comment]
Also requested in [Ticket ID: 1044592](https://admin.telerik.com/?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1044592&SM=0) and in [Ticket ID: 1031064](https://admin.telerik.com/?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1031064&SM=0)
