### ISSUE TITLE
Context menu cannot undo pasted text

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-ui-core#1817]
Calling undo from the context menu after pasting text does not undo it. Maybe the context menu command does not go through the editor undo/redo stack? Either way, this is confusing for users, as it undoes some text, but not all.

Reported in ticket ID 901851

**Comment by Iankodj** [comment]
Two years later there is still no suitable event to handle the undo command from the context menu. Theoretically, the input event is the one we could use ([InputEvent](https://developer.mozilla.org/en-US/docs/Web/Events/input)). Where the [inputType property](https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/inputType) shows the type of the change occurred. This, however, is available only for Chrome and Opera. 

Another solution is to prevent the native context menu and implement a custom one. If this is what we are after, this should be logged as an enhancement.

**Comment by gyoshev** [comment]
At the time of writing, I was considering detecting `input` events after the `contextmenu` event is triggered. Not sure if this is a viable option implementation-wise, though.

**Comment by Iankodj** [comment]
There are several troubles with that:

1. IE and Edge does not utilize the input event for contenteditabe elements at all. 
2. Firefox, we could possible get the input event, but without the inputType we could not know whether undo or redo is executed from the context menu.

**Comment by Iankodj** [comment]
Closing this issue due to impossibility to be handled in all browsers consistently. If there is further demand, the solution would be to entirely prevent the context menu and show a custom one. This, however, should be processed as a feature request.
