### ISSUE TITLE
Diagram HtmlHelper for MVC Core

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#1835]
The Diagram is the last component that is missing in the Kendo UI for ASP.NET Core MVC suite.

**Comment by justinsweet** [comment]
Is there any updates to when the Diagram component will be in the ASP.NET Core MVC suite?

**Comment by petyosi** [comment]
Hi @justinsweet , the item was shelved in favor of higher priority items. I am afraid that we don't have a concrete timeline for it currently.

**Comment by Alex-Bubblemaster** [comment]
Raising priority - Ticket ID: 1127641 and 1122578

**Comment by AFract** [comment]
Hello, 
As the last update to this ticket seems to go back more than a year and the Diagram feature is still not available in MVC core samples, I wish to renew the question to know if you plan to do something about this to support it ?
Thank you

**Comment by Stamo-Gochev** [comment]
@AFract I cannot share a specific release when the Diagram will be available, so what I can recommend is to share your request in the Feedback Portal, so the item can be prioritized among others for the ASP.NET Core wrappers:
https://feedback.telerik.com/aspnet-core-ui

**Comment by jeffrey-sadler** [comment]
Hi,

As the Diagram feature is still not available in ASP.Net Core can you please recommend another product which does have Diagrams which we could use instead? As the Core implementation looks like its just a wrapper is the product "Telerik UI for ASP.Net AJAX" the best alternative? 

Thanks

**Comment by Stamo-Gochev** [comment]
@jeffrey-sadler 
The diagram is available as a Kendo UI widget and you can use it in your ASP.NET Core project by configuring it as demonstrated in the demos:
https://demos.telerik.com/kendo-ui/diagram/index

The documentation can be found at:
https://docs.telerik.com/kendo-ui/controls/diagrams-and-maps/diagram/overview
