### ISSUE TITLE
Spreadsheet cell content, copied with Cut/Copy toolbar/context menu buttons, is pasted as HTML to cells in Edit mode or to cells in another Spreadsheet

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#1837]
### Bug report
HTML Object is pasted when the cell is in **edit mode**, instead of just the value or directly prevent pasting like the behavior in MS Excel.
The same is reproducible when pasting from one Spreadsheet to another, if cell is copied through context menu or toolbar buttons.

### Reproduction of the problem
1. Go to http://demos.telerik.com/kendo-ui/spreadsheet/index
1. Selected a cell to copy.
1. Click the Cut/Copy toolbar or context menu buttons.
1. Double click on another cell to enter its Edit mode.
1. Paste the copied content with keyboard (Ctrl + V)

[VIDEO](https://www.screencast.com/t/5pCmQVX9)

### Reproduction of the problem for two Spreadsheets
Go to https://dojo.telerik.com/AKUMaTEd
1. Selected a cell to copy from the first Spreadsheet
1. Click the Cut/Copy toolbar or context menu buttons.
1. Click on a cell in the second Spreadsheet (no need to be in Edit mode)
1. Paste the copied content with keyboard (Ctrl + V)

### Current behavior
The html, containing the cell style, format, value etc. is pasted

### Expected/desired behavior
Should paste only the value of the coped cell, as when not in Edit mode.

### Environment
* **Kendo UI version:** 2019.1.220
* **Browser:** [all] 

Reported in Ticket ID: 1045350, 1086909

**Comment by ipeshev** [comment]
On IE ~11  CTRL+V is not working, right click in edit mode + PASTE is not working either. It is working on official demos though.

**Comment by Dimitar-Goshev** [comment]
I updated the issue's title and description and closed the duplicate issue.

**Comment by PekoPPT** [comment]
Reported on ticket 1497933

**Comment by PekoPPT** [comment]
A possible workaround is demonstrated in this Dojo example: https://dojo.telerik.com/OTuxOhAy
