### ISSUE TITLE
Change event is not triggered when a link or style is added to a cell 

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#1839]
Please refer to the http://dojo.telerik.com/aPoyu example and try to bold the cell's text without editing the content itself. 

Reported in thread 1045467

**Comment by mishoo** [comment]
Oops...  Wrong issue ID in commit.  Reopening.  Sorry!

**Comment by ipeshev** [comment]
Currently it is triggering event every odd click on Bold/Italic/etc. buttons.

**Comment by gyoshev** [comment]
I am having second thoughts if this behavior should be attached to the change event (currently documented as ["triggered when a value changes"](http://docs.telerik.com/kendo-ui/api/javascript/ui/spreadsheet#events-change)). @tsvetomir, @rkonstantinov -- do you believe this should be in the `change` event (via a event argument field), or in a different event (and under what name)?

**Comment by tsvetomir** [comment]
After a short offline discussion we decided to stick to a single change event and add information about the changed property.

**Comment by Dimitar-Goshev** [comment]
As the description of the event says, it is meant to be fired only when 'value' is changed. Not firing it on changing style/link for a cell is not a bug.
