### ISSUE TITLE
Editor scolls to end when pasting from clipboard in Inline mode

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#1843]
Reproducible in [Inline Editing](http://demos.telerik.com/kendo-ui/editor/inline-editing) demo. 

1. Insert large amount of text
2. Paste at the beginning

Actual: Scroll is applied
Expected: Scroll is preserved at the caret positon

[UserVoice#127393](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/14798697);

**Comment by mparvanov** [comment]
The issue has been resolved and the fix will be available in the next official release Q3 2016
