### ISSUE TITLE
The Kendo UI Spreadsheet filter dialogue does not appear after scrolling when column headers are frozen

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#1853]
**Issue**: The Kendo UI Spreadsheet filter dialogue does not appear after scrolling when column headers are frozen. The filter will appear again on click if the rows are scrolled to the top.

The issue can be reproduced in _all_ of our demos: http://demos.telerik.com/kendo-ui/spreadsheet/sorting-filtering

**Steps to reproduce the issue:** 
- Apply filter
- Froze all header rows
- Click the filter icon and it is working
- Scroll down until the first data row is not visible
- Click the filter icon and now the filter menu will _not_ appear
- Scroll back to the top and the filter menu will appear again.

**Telerik admin ticket**: 1045658

**Comment by simonssspirit** [comment]
Another report for this issue in ticket: **1065696**.
Priority changed from **low** to **medium**.

**Comment by marclazell** [comment]
Was there a fix for this, or a workaround or is it in development for the next release?
