### ISSUE TITLE
Destroy kendo widgets on $scope.$destroy()

### ISSUE THREAD

**Issue by qbunia** [telerik/kendo-ui-core#1861]
Hello,

Are you planning to support this action in future? Right now If I create my own scope via: $rootScope.$new(), and this scope will contain for example kendoDropdownlist. After $scope is destroyed the DOM of k-list-container still remains, thats why everytime when I destroy my scope I have to call: kendo.destroy(document.body).

**Comment by alexoldenburg** [comment]
any follow up?

**Comment by zdravkov** [comment]
Unfortunately this enhancement has not been planned for implementation yet. In such case we recommend providing at least one [runnable dojo](http://dojo.telerik.com/) so the issue is better illustrated. That could be quite useful when considering its priority.

**Comment by Dimitar-Goshev** [comment]
Starting with R2 2022, the Kendo UI team officially drops the support for AngularJS 1.x through Kendo UI for jQuery
