### ISSUE TITLE
Calendar view duplication.

### ISSUE THREAD

**Issue by iyegoroff** [telerik/kendo-ui-core#1871]
Found buggy calendar behavior in Firefox & Mac OS X
![screen shot 2016-07-04 at 00 12 14](https://cloud.githubusercontent.com/assets/4447438/16547587/6c325068-4184-11e6-8d6b-edd7c084faef.png)
It can be reproduced here - http://dojo.telerik.com/ImuMaJ
- navigate to top view;
- select '2090-2099' -> '2099' -> 'Mar';
- navigate to next month;
- again navigate to top view.

**Comment by ggkrustev** [comment]
Couldn't replicate
