### ISSUE TITLE
Adding multiple lines into a cell using Alt+Enter is not working correctly in Internet Explorer.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#1872]
### Bug report
When Alt+ Enter is used to add a new line in a cell, the last character from the row is being moved into the new row. The issue is observed only in _Internet explorer._

### Reproduction of the problem
1. Open http://demos.telerik.com/kendo-ui/spreadsheet/index
1. Start typing in a cell and adding new rows with Alt+Enter on several rows

### Current behavior
The last character from the row is being moved into the new row.

### Expected/desired behavior
The last character from the row should not be moved like in Chrome

### Environment

* **Kendo UI version:** 2010.3.1023
* **Browser:** IE11
**Telerik admin ticket**: 1047499

**Comment by veselints** [comment]
also reported in Ticket ID: 1382322

**Comment by PekoPPT** [comment]
also reported in Ticket ID: 1452616

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
