### ISSUE TITLE
Enter new line on first formatted paragraph moves the line to the third line and puts cursor to the second one

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#1873]
1. [http://demos.telerik.com/jsp-ui/editor/index](http://demos.telerik.com/jsp-ui/editor/index)
2. Remove all content
3. Insert a paragraph of text
4. Highlight it with the mouse 
5. Apply some formatting (e.g., Bold)
6. Press Enter at the end of the line 

Video: [http://screencast.com/t/h4lziMaLJcT](http://screencast.com/t/h4lziMaLJcT)

Actual: 

```
<p></p>
<p></p>
<p><strong>some text</strong></p>
<p></p>
```

Expected:

```
<p><strong>some text</strong></p>
<p></p>
<p></p>
```

**Comment by fcristini** [comment]
We are facing the same issue here, please let me know if you find a fix.

**Comment by nstoychev** [comment]
Not reproducible with Kendo UI 2017 R1.
