### ISSUE TITLE
Not properly sized resizable columns in Gantt's TreeList view on less than 480px screen width

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#1876]
### Bug report
Reported in ticket: 1047854 
Reproduction video: http://screencast.com/t/AZB3Udw8Y75

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/gantt/column-resizing
1. Make the screen resolution below 480 width.
2. Refresh the screen.
3. Click on the TreeListView button the Gantt

### Current behavior
![image](https://user-images.githubusercontent.com/6614183/42885232-1c5b01d2-8aa9-11e8-846a-1908c208e5ca.png)

### Expected/desired behavior
Columns are wide enough to see their content

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Another issue with columns sizing on less than 480px wide screen: https://github.com/telerik/kendo-ui-core/issues/1915
