### ISSUE TITLE
Hide method does not hide items from the overflow popup

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-ui-core#1879]
Reported in ticket: 1047752. Can be reproduced here: http://dojo.telerik.com/@Iliana/OvUYO

**Comment by veselints** [comment]
Reported also in Ticket ID: 1098007

**Comment by mparvanov** [comment]
Ticket ID: 1125044

**Comment by InciteGmbH** [comment]
This is still open since 2016. This is for us and our customers important. Could you let us know, when this will be solved. Thanks.

**Comment by movedoa** [comment]
This should be a high priority bug.
Users can execute disabled functions when the developer is not aware of this bug witch can lead to a huge amount of problems.

**Comment by mparvanov** [comment]
Raising the issue severity to High. The following workaround could be used temporarily:
http://dojo.telerik.com/uboZA/2
