### ISSUE TITLE
Paste keyboard command (Ctrl +C/V) in Spreadsheet places "null" in the target cell

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#1882]
The problem can be replicated using the online demos:

demos.telerik.com/aspnet-mvc/spreadsheet/index

**Comment by mishoo** [comment]
Duplicate of #1799 (fixed).

**Comment by ipeshev** [comment]
Not sure if it is an issue, but on MS Edge CTRL+C ( from empty cell ) and CTRL+V into some cell (with content ) does nothing, on other browsers ( including IE11) it is clearing cell content.

**Comment by Alex-Bubblemaster** [comment]
Copied blank Excel cell pastes "null" in Spreadsheet. Reported in ticket 1049532. 
(Tested in kendobuild)

**Comment by ipeshev** [comment]
On Chrome it CTRL+C/ is not working but CTRL+INS ( instead CTRL+C ) is working fine. 
It looks like it is something Chrome specific with keyboard shortcuts.
