### ISSUE TITLE
Borders of minorTick slots are incorrectly styled for cells after the first one

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-ui-core#1886]
Borders of minorTick slots are incorrectly styled for cells after the first one. This can be observed in the following demo:
-  [http://dojo.telerik.com/eDese](http://dojo.telerik.com/eDese)

![image](https://cloud.githubusercontent.com/assets/2195951/16615609/8debc6fa-4380-11e6-8284-8be1414679b4.png)

**Comment by Dimitar-Goshev** [comment]
Closing it as duplicate of https://github.com/telerik/kendo-ui-core/issues/2671
