### ISSUE TITLE
PDF export does not work correctly when the Grid has a locked column

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#1887]
**Issue**: If the Grid has locked column/s the PDF export does not work as expected and the exported file is incorrect.

The issue can be **reproduced** in our demos: http://dojo.telerik.com/ITuFE

**Admin ticket**: 1048185

**Comment by mishoo** [comment]
Unfortunately, this cannot be fixed.  There is a note about it in [known limitations](http://docs.telerik.com/kendo-ui/framework/drawing/drawing-dom#configuration-Page), which states:

> If the algorithm decides to move a node to the next page, all the DOM nodes which follow it, will be moved as well, even if there might be potentially room for some of them on the current page.

The locked content being in a separate `<table>` element from the main content, when it's split, the main content moves to the next page entirely.  The explanation in the docs might be a little too technical, but it boils down to “vertically aligned long elements will not be displayed properly across pages”.

**Comment by tsvetomir** [comment]
@simonssspirit we should note that in the grid documentation as well

**Comment by simonssspirit** [comment]
The limitation is added in the Grid documentation.
`9c69cfe`
