### ISSUE TITLE
Dropdown of virtualized DropDownList with popup origin set appears empty in IE/Edge

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#1902]
### Bug report
[popup.origin](https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist/configuration/popup#popup.origin) is set to position the dropdown over the widget when it is opened.
Removing the `popup.origin` property from the configuration resolves the issue.

**NOTE:** the issue is not reproducible with smaller amount of items (testing shows that the issue starts to reproduce when the items are more than 541000).
**NOTE:** clicking on the left side of the Dojo, when the dropdown is expanded, makes the items visible. Also if item's position or box-sizing is toggled in dev tools, the items become visible.

Reported in ticket 1048904

### Reproduction of the problem
https://dojo.telerik.com/UjaYOqIc/5

### Current behavior
![image](https://user-images.githubusercontent.com/6614183/42805781-64cad93c-89b5-11e8-8627-348b48351308.png)

### Expected/desired behavior
![image](https://user-images.githubusercontent.com/6614183/42805844-8a55b14a-89b5-11e8-8db7-5a3744091bc9.png)

### Environment
* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [IE 11, Edge]

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
And Microsoft Edge is now based on Chromium engine and its current version is 108.
