### ISSUE TITLE
Wrong HTML is rendered when Columns.HeaderTemplate is used in Filterable and Sortable Grid

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-ui-core#1907]
Reported in ticket: 1048018. When using Columns.HeaderTemplate in Filterable and Sortable Grid, k-grid-filter is rendered within the k-link element, too. This differs from the JavaScript Grid version (http://dojo.telerik.com/@Iliana/InUROr)

**Comment by Xizario** [comment]
If the given Column and Grid are Sortable then hyperlink with class "**k-link**" must be included into the HeaderTemplate. 
If the "k-link" hyperlink is missing, it will be added automatically for each Sort enabled column, by wrapping the whole cell content.

The correct razor looks like:
```c#
@(Html.Kendo().Grid<CustomerViewModel>()
    .Name("grid")
    .Columns(columns =>
    {
        columns.Bound(c => c.ContactTitle).Sortable(true).HeaderTemplate("<a class='k-link' href='#'> Contact Title </a>");
        columns.Bound(c => c.CompanyName).Sortable(false).HeaderTemplate("Company Name");
    })
    .Filterable()
    .Sortable()
    )
)
```
