### ISSUE TITLE
Tooltip not showing text when showOn option is set to focus and navigate to the target using the keyboard

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#1908]
Use the following snippet:
[http://dojo.telerik.com/@parvanov/UpUke](http://dojo.telerik.com/@parvanov/UpUke)
Navigate to the third input using the keyboard
Expected: The tooltip shows "My tooltip" text
Actual: The tooltip is shown but it's empty
Note: If use your mouse to set focus on the input element with Kendo Tooltip enabled, it will work just fine.

The following workaround could be used:
[http://dojo.telerik.com/@parvanov/ALIZIb](http://dojo.telerik.com/@parvanov/ALIZIb)

**Comment by veselints** [comment]
Also reported in Ticket ID: 1113479

**Comment by Iankodj** [comment]
The fix should include several other improvements regarding the show-on-focus behavior (with keyboard): 

- [ ] Show tooltip content on focus;
- [ ] Reset the target's title attribute on focus;
- [ ] Hide tooltip on focusing out; 
- [ ] Restore the target's title attribute on focus.
