### ISSUE TITLE
CTRL+C does not changes the clipboard state when cell is empy , on MS EDGE

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#1910]
Reproduction steps:
1. Navigate to [http://demos.telerik.com/kendo-ui/spreadsheet/index](http://demos.telerik.com/kendo-ui/spreadsheet/index)
2. CTRL+C on some empty cell
3. CTRL+V on some cell with content
4. The cell's content is not cleared

Related to [https://github.com/telerik/kendo-ui-core/issues/1882](https://github.com/telerik/kendo-ui-core/issues/1882)

**Comment by mparvanov** [comment]
The issue is not reproducible with v. 2019.3.1023.
