### ISSUE TITLE
AngularJS Slider does not update ng-model in IE11

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#1916]
### Bug report
AngularJS Slider does not update ng-model in IE 11.
Similar to the following issue: https://github.com/telerik/kendo-ui-core/issues/1241

### Reproduction of the problem
1. Open [Slider AngularJS demo](http://demos.telerik.com/kendo-ui/slider/angular) in IE 11

### Current behavior
The image is NOT fitting in the container and the image is NOT resized when slider value is changed.

### Expected/desired behavior
The image is fitting in the container and the image is resized when slider value is changed, as in Chrome 75, Firefox 64 and Edge

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** IE 11

**Comment by KirilNN** [comment]
In which IE version can the issue be reproduced?

**Comment by ipeshev** [comment]
Under IE11.

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
