### ISSUE TITLE
Limit ValueAxis only when the output is VML

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-ui-core#1918]
Currently the axis slots are limited to 100000 since it does not seem to be possible to display paths with larger coordinate values in VML. The same is not true when rendering Canvas and SVG so we can skip or increase the limit in this scenario.

**Comment by tsvetomir** [comment]
Note that canvas has [size limitations](http://stackoverflow.com/a/11585939/25449) on its own.
