### ISSUE TITLE
TabStrip dynamically added tab with content is not hidden when other tab is selected. 

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#1923]
To reproduce the issue please check the following http://dojo.telerik.com/usuCI example. When a new tab is added and user selects other tab the content of the dynamically added tab is still shown.

**Comment by vladimirivanoviliev** [comment]
Issue in the demo itself - on each click of the button, new instance of the Tabstrip created over the existing one. After fixing the demo it works as expected. 

-  **[http://dojo.telerik.com/usuCI/2](http://dojo.telerik.com/usuCI/2)**

```
 var tabStrip = $("#tabstrip1").kendoTabStrip().data("kendoTabStrip");
```

**Comment by GerryOnGithub** [comment]
This originates with a bug in the kendo documentation 
https://docs.telerik.com/kendo-ui/controls/navigation/tabstrip/tabs#dynamic-tabs
