### ISSUE TITLE
Demo is not styled properly 

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#1928]
It can be seen [here](http://demos.telerik.com/kendo-ui/grid/angular).
Navigate to "CONTACT INFORMATION" tab.

**Comment by inikolova** [comment]
@yordanov should we add additional styling to the "CONTACT INFORMATION" tab?

**Comment by yordanov** [comment]
Yes, this is how it should look:

![styling](https://cloud.githubusercontent.com/assets/1118895/16913691/f5f94272-4cf4-11e6-868f-85e33c826618.png)
