### ISSUE TITLE
dropdown arrow not visible IE 11

### ISSUE THREAD

**Issue by jmbeach** [telerik/kendo-ui-core#1931]
I can't figure out what's causing it, but the dropdown arrow (class k-i-arrow-s) is not visible in IE 11. 
I am calling `kendoComboBox` on my select and below is the result:
![image](https://cloud.githubusercontent.com/assets/2680142/16812331/320b6724-48f2-11e6-8435-709da6bce199.png)

**Comment by jmbeach** [comment]
Randomly the dropdown arrow will be visible after clicking on the dropdown, but it will disappear again later.
Also, I have tried messing with z-index, but it did not help.

**Comment by ggkrustev** [comment]
@jmbeach could you provide a repro demo that demonstrates the issue? This will help us to investigate the case locally and determine its status.

**Comment by jmbeach** [comment]
Sure thing

**Comment by jmbeach** [comment]
I'd like to close this actually. I found that the problem only occurs for me in Visual Studio and not while the project is live. No idea why.
