### ISSUE TITLE
kendo-ui-core webpack angular directives do nothing

### ISSUE THREAD

**Issue by noherczeg** [telerik/kendo-ui-core#1932]
Greetings!

I've spent numerous hours trying to make the kendo-ui-core - webpack - angular trio to work, but without success. I checked the online docs, but they do not cover this use case at all (or I just failed to find it).

My application entry file:
```
import * as $ from "jquery";
import angular from 'angular';
import 'kendo-ui-core';
import 'kendo-ui-core/js/kendo.angular';
import uiRouter from 'angular-ui-router';
import uiBootstrap from 'angular-ui-bootstrap';
import Common from './common/common';
import Components from './components/components';
import AppComponent from './app.component';

import 'kendo-ui-core/css/web/kendo.common-material.core.css';
import 'kendo-ui-core/css/web/kendo.material.css';

const APP_MODULE = angular
    .module('app', [uiRouter, uiBootstrap, 'kendo.directives', Common, Components])
    .config(($locationProvider) => {
        'ngInject';
        $locationProvider.html5Mode(true).hashPrefix('!');
    })
    .component('app', AppComponent)
    .name;

export default APP_MODULE;
```

The CSS is loaded correctly, but the kendo angular directives do nothing at all. I'm assuming they are not working as intended. I checked the built sources and the contents of `kendo.angular.js` are present so it got loaded, but somehow did not get registered properly(?).

Oh and angular does not complain about the `'kendo.directives'` module dependency definition so it seems as if it loaded it.

Does kendo-ui-core require a special webpack loader/resolver configuration? Am I importing stuff the wrong way?

Any and every help/suggestion is much appreciated!

**Comment by noherczeg** [comment]
Oh and the version I'm using is `2016.2.607` from kendo-ui-core, and `1.5.7` from angular.

**Comment by noherczeg** [comment]
It was my bad, I needed to ensure load order. Although I'd recommend putting this inside the docs, because for beginner webpack users this might not be trivial (like me).

So the solution was to set up the provider plugin for webpack:
```
config.plugins = [
    new webpack.ProvidePlugin({
        'window.jQuery': 'jquery'
    })
];
```

**Comment by underlog** [comment]
Thanks for the suggestion. Webpack may be intimidating to newcomers, indeed.

**Comment by jkarthik08** [comment]
Thanks noherczeg. You saved my time.

**Comment by underlog** [comment]
Just some heads-up — using Kendo UI with webpack is easier if you use the NPM package distribution. This repository shows how to do that: https://github.com/telerik/kendo-ui-npm-example/tree/master/typescript-webpack

**Comment by noherczeg** [comment]
@underlog I don't get your point. The provided example project doesn't even have jquery in it.

**Comment by underlog** [comment]
There is no need to add it — jQuery is listed as a dependency of kendo-ui-core. Of course, you may add it if you need to specify the exact version.

**Comment by noherczeg** [comment]
@underlog Oh yeah, you are right, forgot about that.
