### ISSUE TITLE
Auto-link command does not work with space key in Firefox

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#1933]
Steps: 
1. http://demos.telerik.com/kendo-ui/editor/index
2. Delete all text
3. Type "www.telerik.com"
4. Press spacebar 

Actual: Nothing happens.
Expected: Auto-link to generate "www.telerik.com" to a link.

**Comment by nstoychev** [comment]
Here is a workaround:
`<textarea id="editor" rows="10" cols="30" style="width:100%;height:400px"></textarea>
<script>
    $("#editor").kendoEditor();

    var toolsFromShortcut = kendo.ui.editor.Keyboard.fn.toolsFromShortcut;
    kendo.ui.editor.Keyboard.fn.toolsFromShortcut = function (tools, e) {
        if (kendo.support.browser.mozilla && !e.keyCode && e.charCode) {
            e.keyCode = e.charCode;
        }
        return toolsFromShortcut.call(this, tools, e);
    };
</script>`

**Comment by nstoychev** [comment]
Here is a workaround:
[http://dojo.telerik.com/usaFE/2](http://dojo.telerik.com/usaFE/2)
```
<textarea id="editor" rows="10" cols="30" style="width:100%;height:400px"></textarea>
<script>
    $("#editor").kendoEditor();
    if (kendo.support.browser.mozilla) {
        var toolsFromShortcut = kendo.ui.editor.Keyboard.fn.toolsFromShortcut;
        kendo.ui.editor.Keyboard.fn.toolsFromShortcut = function (tools, e) {
            if (!e.keyCode && e.charCode) {
                e.keyCode = e.charCode;
            }
            return toolsFromShortcut.call(this, tools, e);
        };
    }
</script>
```
