### ISSUE TITLE
Copied table subset is pasted into single column under MS EDGE

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#1936]
It can be seen [here](http://kendobuild/staging-kendo-ui/spreadsheet/index).
Select multiple rows and columns ( sub table ) , select single cell , try to paste into it - it is pasted into single column

**Comment by simonssspirit** [comment]
Additional information related to the same issue reported in another ticket(1082123):

Working as expected:

-  Copy or Cut using context menu.
-  Paste using Ctrl + V works.

Not working as expected:

- Copy or Cut using Ctrl C 
- Use Ctrl +V, does not work.

**Comment by mparvanov** [comment]
The issue is not reproducible with v. 2019.3.1023
