### ISSUE TITLE
Edit mode + scroll results formula flowing above table cells.

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#1942]
Visible on all browsers in [official demos](http://kendobuild/staging-kendo-ui/spreadsheet/index).
Try to put a cell with formula in edit mode, then scroll down. Cell content is standing still above the rows.

**Comment by mishoo** [comment]
I believe this is by design, so you can select with the mouse cells/ranges outside the view while editing a formula.  Please reopen if I'm wrong.
