### ISSUE TITLE
PDF Export JavaScript error when Grid is not pageable

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#1956]
Grid PDF Export throws the following JavaScript error when the PDF Export button is pressed for the second time (or the Grid dataSource.read() is called programmatically after the export is complete):

http://dojo.telerik.com/AGEdO

On the other hand, if the PDF allPages option is removed, the Grid can be exported multiple times, but all pages are stacked on top of each other in the resulting 1-page PDF:

http://dojo.telerik.com/AGEdO/2

Reported in Ticket ID: 1049472

**Comment by mishoo** [comment]
Note: `e.dataSource` is not defined here:

```js
pdfExport: function(e){
  e.promise.then(function(){
    e.dataSource.read();  // ***
  })
},
```

To do that, obtain a reference to the grid, e.g. `$("#grid").getKendoGrid().dataSource.read()` (on the other hand, it is not necessary to call read() on the DS after rendering).
