### ISSUE TITLE
Grid dirty cell indicator is misplaced in RTL mode

### ISSUE THREAD

**Issue by dimodi** [telerik/kendo-ui-core#1960]
reported in ticket: 1050446

test page that reproduces the bug: http://dojo.telerik.com/@DUKEiLL/IVAPu
(edit any existing cell and blur it)

immediate CSS workaround: 

```
.k-rtl span.k-dirty {
  margin: -0.4em 0.5em 0 0;
}
```

**Comment by ipeshev** [comment]
Оn FF, MS Edge and IE11 dirty cell indicator is a bit far from the cell corner.

**Comment by martintabakov** [comment]
Due to the fix, the dirty indicator does not appear in Chrome. https://dojo.telerik.com/@martin.tabakov@progress.com/IQutIguy/5
