### ISSUE TITLE
Cells can't be edited after undo is executed

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#1964]
**Bug report**

**Reproduction of the problem**
It can be seen on every [official demo](http://demos.telerik.com/kendo-ui/spreadsheet/index)
1. Click on cell and type '1'
2. Repeat step 1 several times on different cells
3. Leave the cursor/focus in the last edited cell
4. Undo last change via 'Undo' button
5. Execute step 1 on some free cell - cell content is not changed

**Expected behavior**
Click on cell + some input should change its content

**Environment** 
- **Browser:** All  
- **Language:** All

**Comment by mishoo** [comment]
This too is fixed if we deactivate the editor on blur.  See also https://github.com/telerik/kendo-ui-core/issues/1941#issuecomment-232623166

**Comment by mishoo** [comment]
This is fixed now.
