### ISSUE TITLE
kendo.dropdownlist.js: regression in version 2016.2.714 when using a calculated field for dataTextField

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#1972]
The suggested fix is to wrap lines https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.dropdownlist.js#L1261 to https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.dropdownlist.js#L1263 as follows: 

```
if (this.options.optionLabel) {
    if (dataItem === optionLabelText || this._text(dataItem) === optionLabelText) {
        template = this.optionLabelTemplate;
    }
}
```

To reproduce the exception thrown, use a data model similar to the following - it derives from models.Activity which is a kendo.data.Model but the only important part is the name$ calculated field - to build a data source.

```
models.Score = models.Activity.define({
    fields: {
        test: {
            defaultValue: null
        },
        score: {
            type: NUMBER,
            editable: false
        }
    },
    init: function (data) {
        Model.fn.init.call(this, data);
        this.type = 'score';
    },
    name$ : function () {
        var id = this.get('id');
        if (RX_MONGODB_ID.test(id)) {
            return kendo.format('{0:' + i18n.culture.dateFormat + '} ({1:p0})', this.get('created'), this.get('score') / 100);
        }
    }
});
```

Then bind the data source to a drop down list as follows, which used to work in previous versions of kendo ui, and now throws an exception:

```
var scoresListWidget = scoresList.kendoDropDownList({
    autoBind: false,
    dataTextField: 'name$()',
    dataValueField: 'id',
    dataSource: viewModel.scores
}).data('kendoDropDownList');
```

I also suggest to add this scenario as a new unit test.

**Comment by underlog** [comment]
Hi, 

Can you replicate the problem in a dojo? Alternatively, given the investigation performed, you may also submit a pull request. Any of these files would be suitable for the suggested unit test. 

https://github.com/telerik/kendo-ui-core/tree/master/tests/dropdownlist 

Please re-open the issue afterwards. Thank you in advance.

**Comment by jlchereau** [comment]
HI,

Here is your dojo: http://dojo.telerik.com/UGakU/2.

Kendo UI 2016.2.714 fails. The exception thrown is ```TypeError: d.name$ is not a function``` in all browsers.

Previous versions do not fail.

![image](https://cloud.githubusercontent.com/assets/2556751/17017330/e02d5626-4f2a-11e6-8be9-9ecbdd6e27d5.png)
