### ISSUE TITLE
Fiori theme visual glitches

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#1973]
## Reproduction of the problem
 Bottom borders are missing of some widgets , radiobuttons are not aligned.
![capture 2016-07-03 at 10 11 40](https://cloud.githubusercontent.com/assets/4143177/16978123/ecd66944-4e62-11e6-9408-e30e63643e8b.png)
It can be seen in [themebuilder demo](http://demos.telerik.com/kendo-ui/themebuilder/). althought on other demos those widgets are looking fine.

## Expected Behavior
     The widgets should have visible border.
     Radiobuttons should be aligned with their labels.

## Details on the Environment
**Browser**  All - for unaligned radiobuttons | Chrome - for missing border bottom    
**Language** All

**Comment by inikolova** [comment]
RadioButtons misalignment -> Commit: 0280568c8b9a023

**Comment by ipeshev** [comment]
On all themes there is misalignment between checkbox / radiobutton and it's label it is around 2 pixels but it is visible. Should we move this to new issue ?

**Comment by inikolova** [comment]
@ipeshev , yes please

**Comment by ipeshev** [comment]
The problem with misaligned radiobuttons and checkboxes is refered into another issue #2213
