### ISSUE TITLE
MultiSelect and AutoComplete focused items not visually recognizable in Office365 theme

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#1977]
When arrow keys are used for navigation through the dropdown, the currently focused item is not visually recognizable when the Office365 theme is used. Reproducible in the online demos.

Reported in Ticket ID: 1052079

**Comment by inikolova** [comment]
This issue has been already addressed. Commit: 609c10c65458db15c59c in the private repo
