### ISSUE TITLE
Add Html.Kendo().Culture() helper to the documentation

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#1978]
http://www.telerik.com/forums/wrong-json-date-string-when-in-line-editing-datetime#43yfb9Zq8EitllvA8USKCA

Ticket: 1051924

**Comment by danielkaradachki** [comment]
added to the [globalization documentation](http://docs.telerik.com/kendo-ui/aspnet-mvc/globalization#use-the-culture-helper)
