### ISSUE TITLE
SUGGESTION: add icon only (text hidden) overflow mode in kendo.ui.ToolBar

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#1985]
Sorry guys, I know you do not like suggestions here but I am out of credits on uservoice.

It would be nice to have another overflow mode in the toolbar that automatically hides button text when resizing the toolbar.

This would be particularly effective on mobile devices where icon only buttons would be kept visible instead of crowding the overflow popup. Note that you only have 320px on iPhone 5 in portrait mode, which hardly displays 3 buttons with text which looks unusual as people are used to icon only buttons on mobile phones.

See http://docs.telerik.com/kendo-ui/api/javascript/ui/toolbar#configuration-items.overflow

**Comment by Dimitar-Goshev** [comment]
There are such properties available:
- [items.showIcon](https://docs.telerik.com/kendo-ui/api/javascript/ui/toolbar#configuration-items.showIcon)
- [items.showText](https://docs.telerik.com/kendo-ui/api/javascript/ui/toolbar#configuration-items.showText)
- For buttongroup buttons only - [items.buttons.showIcon](https://docs.telerik.com/kendo-ui/api/javascript/ui/toolbar#configuration-items.buttons.showIcon)
- For buttongroup buttons only - [items.buttons.showText](https://docs.telerik.com/kendo-ui/api/javascript/ui/toolbar#configuration-items.buttons.showText)

**Comment by jlchereau** [comment]
This is not the same feature. My suggestion consists in a 3-step overflow as the toolbar is resized:
- large toolbar: icon + text
- normal toolbar: icon
- small toolbar: overflow 

showIcon and showText have no dependency on the size of the toolbar.
