### ISSUE TITLE
Virtualized MultiSelect does not fire its change event if there are no initially selected values

### ISSUE THREAD

**Issue by harlankoehn** [telerik/kendo-ui-core#1986]
This is a repeat of an issue reported on January 5, 2016 which has since been closed without actually being fixed correctly. The issue is that the change event doesn't fire on a Multiselect that has virtual enabled and begins it's life with no default values. This is basically a Javascript pointer bug having to do with the _old property.

Here's a Telerik dojo showing the problem: http://dojo.telerik.com/@villagemedia/uHaFa/16

Note that all line numbers mentioned are in [kendo.multiselect.js in the GitHub src](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.multiselect.js).

At line 551 you'll see `that._old = value` and it's inside the value function which has an argument of value. Apparently under the right circumstances this ends up setting _old as a pointer / memory reference to the same object as the Value property of the multiselect, which then keeps the two objects "synchronized". This results in the compare function (line 1209) seeing _old and value as the same values (because they are) so no change event gets fired. One actually does get fired (line 666) but at line 670 the `if` resolves to true (because the arrays are identical) so that.trigger(CHANGE) never gets fired.

Here's the fix I implemented and it works. I think there could be a more elegant way of doing this and the first part of my code might be simply unnecessary, but I didn't want to take any chance of _old referencing the value property so I opted to just copy the objects. 

The code I've added:

		if(Array.isArray(value) && value.length > 0) {
			for(i = 0; i < value.length; i++) {
				that._old.push(value[i]);
			}
		} else {
			that._old = [];
		}

And here's the entire function:

	value: function (value) {
		var that = this;
		var listView = that.listView;
		var oldValue = listView.value().slice();
		var maxSelectedItems = that.options.maxSelectedItems;
		var clearFilters = listView.bound() && listView.isFiltered();
		if (value === undefined) {
			return oldValue;
		}
		value = that._normalizeValues(value);
		if (maxSelectedItems !== null && value.length > maxSelectedItems) {
			value = value.slice(0, maxSelectedItems);
		}
		if (clearFilters) {
			listView.bound(false);
			that._filterSource();
		}
		listView.value(value);
		if(Array.isArray(value) && value.length > 0) {
			for(i = 0; i < value.length; i++) {
				that._old.push(value[i]);
			}
		} else {
			that._old = [];
		}
		if (!clearFilters) {
			that._fetchData();
		}
	}

**Comment by ggkrustev** [comment]
Hi @harlankoehn,

Indeed, the widget does not trigger change when `_old` is set to same array instance. The fix is pushed in master branch and the next official release will include it.

**Comment by ipeshev** [comment]
The above example is throwing error under IE ".... Promise is not defined" [here](http://dojo.telerik.com/@ipeshev/oBaqO) is fixed version that can be tested under IE
