### ISSUE TITLE
Add .k-button-bare styles to all themes

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-ui-core#1988]
`.k-button-bare` is usually used with `.k-button-icon` CSS class to style icon buttons without background-color. It should have styles for the following states:
- disabled
- normal
- hover
- focused
- active/selected

**Comment by lkarakoleva** [comment]
.k-button-bare inherit color styles. In cases we need a contrast active/selected color, it could uses the accent color of the theme
![bare_button_state](https://cloud.githubusercontent.com/assets/16577622/17438852/a8c88dfe-5b2d-11e6-86a4-3bb4adf5032d.png)
