### ISSUE TITLE
Grid does not export all pages to PDF when scrolling is disabled and PagerSize is specified

### ISSUE THREAD

**Issue by kostadin-dimitrov** [telerik/kendo-ui-core#1996]
The issue can be replicated in the following MVC [live example](http://demos.telerik.com/aspnet-mvc/grid/pdf-export) when the scrolling is disabled. It export only the current page even though AllPages option is enabled.

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket ID 1091273. Raising priority.
As a workaround, you may hide the scrollbar with CSS rules. 

- Documentation article: [link](http://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance#remove-the-vertical-scrollbar)

- Runnable Dojo [demo](http://dojo.telerik.com/OLIJIw)

**Comment by mishoo** [comment]
This is no longer reproducible: http://dojo.telerik.com/UqOCOnuH
