### ISSUE TITLE
Grid drag and group breaks on the 2nd column

### ISSUE THREAD

**Issue by Vaughnereal** [telerik/kendo-ui-core#1998]
When dragging a column on the Kendo Grid to group by, the first column groups and reloads as expected, but when dragging the second column to group by the grid just hangs and never displays the data.

**Comment by MilenaCh** [comment]
I tested our [demo page](http://demos.telerik.com/kendo-ui/grid/index) and it seems the same scenario works as expected on it. 
Can you provide a sample, where we can observed the problem?

**Comment by Dimitar-Goshev** [comment]
Closing this issue as not reproducible.
