### ISSUE TITLE
Cells extend its height when shrinked in RTL mode

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#2005]
### Bug report
Cells extend its height when shrinked in RTL mode

### Reproduction of the problem
It can be seen [here](http://dojo.telerik.com/@ipeshev/UKARo)
Try to shrink some cell on second row. 

### Expected/desired behavior
Cells height should stay the same, overflowing content should be hidden ,ellipsis should be shown.

### Environment

* **Kendo UI version:** 2016.2.714
* **jQuery version:** All
* **Browser:** [IE 11 | MS Edge ]

**Comment by dimodi** [comment]
Hello,

I investigated the issue and my comments are the following:

- the issue only occurs when the following combination of prerequisites is met: RTL mode, IE/Edge, filtering (or column menu) is enabled, but sorting is disabled.
- a fix would require breaking changes in the HTML markup of the Grid
- an easy workaround exists - wrap the header cell content in any DOM element, e.g. `{ field: "UnitsInStock", headerTemplate: "<span>Units In Stock</span>" }`
- the above combination of prerequisites, existing workaround and required approach for resolution deem the issue to have a pretty low priority, at least in my opinion.

I suggest that we leave it as is for now.
