### ISSUE TITLE
The Grid in ASP.NET Core MVC - RC1 is loading the templates only from Views/Shared/EditorTemplate

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#2007]
### I'm submitting a ...
- Bug report
### Reproduction of the problem

Try to load editor template from different from Views/Shared/EditorTemplate folder
### Current behavior

Templates are loaded only from Views/Shared/EditorTemplate folder
### Expected/desired behavior

You should be able to load the editors from different locations as well (the behavior from the previous ASP.NET MVC versions)

**Comment by ag-petrov** [comment]
Not reproducible with the latest version.
