### ISSUE TITLE
Chart select-zoom functionality causes FireFox and IE11 browsers to hang

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2012]
### Bug report
Zooming a small selected portion of the Chart via the shift+mousewheel repeatedly causes the graph to hang and eventually - distort. This happens only when dashType configuration is not "solid", and in Firefox and IE11 only.

### Reproduction of the problem
The issue occurs when we select a small portion of the graph using mouse by holding the shift key i.e. select-zoom functionality of graph.
When we repeatedly select a small portion of graph, after few selections, the graph starts to hang and eventually distorts.

Dojo:
[http://dojo.telerik.com/OQuZU/2](http://dojo.telerik.com/OQuZU/2)

### Current behavior

The described behavior is observed in the following video:
[http://www.screencast.com/t/rrPf1xNF](http://www.screencast.com/t/rrPf1xNF)

Sometimes the graph inverts after repeated selections.
Please check the video below for this:
[http://www.screencast.com/t/Lyp26ptOM4](http://www.screencast.com/t/Lyp26ptOM4)

### Expected/desired behavior
Zooming functionality to work as expected (like in Google Chrome)

### Environment
* **Operating System - Windows 8.1
* **Browser - Firefox
* **Browser Version - 47.0.1
* **Kendo UI Version - 2016.2 714
* **Mouse – all

Reported in TicketID 1053410

**Comment by shiv-veerashetty** [comment]
What is the status of this defect ? We also need fix for this
