### ISSUE TITLE
Click on a horizontally scrolled diagram resets the x scroll in IE

### ISSUE THREAD

**Issue by nlazarov** [telerik/kendo-ui-core#2014]
Issue can be reproduced in a docs sample - [http://docs.telerik.com/kendo-ui/controls/diagrams-and-maps/diagram/how-to/using-scrollbar](http://docs.telerik.com/kendo-ui/controls/diagrams-and-maps/diagram/how-to/using-scrollbar)
1. scroll horizontally
2. click anywhere

Notice that the horizontal scroll is reset.

Reported in ticket ID 1053688

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
