### ISSUE TITLE
Document how delayed setting of options interacts with k-ng-delay

### ISSUE THREAD

**Issue by dimodi** [telerik/kendo-ui-core#2016]
Ticket 1053642

This is how the new Kendo UI versions work - if there are widget options, which still do not exist in the scope, and k-ng-delay is defined as well, the widgets will ignore k-ng-delay and only wait for the options to be set. In other words, the widget options work in the same way as k-ng-delay.

This change was triggered by changes in Angular itself.

On the other hand, if the widget options are available immediately, then k-ng-delay will not be ignored and the widget will still wait to initialize.

Finally, here is the documentation that shows how options of Kendo UI directives, that are wrapped in custom directives, should be set with a delay:

http://docs.telerik.com/kendo-ui/AngularJS/introduction#delay-widget-initialization

(see the "Set Options in Link Function" section)

**Comment by Dimitar-Goshev** [comment]
Closing this issue - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
