### ISSUE TITLE
Widget is not initialized when min option is undefined.

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#2018]
### Reproduction of the problem
http://dojo.telerik.com/OJulU
### Current behavior
Widget is not initialized when min option is undefined in AngularJS app.
### Expected/desired behavior
Widget to initialize, as in previous versions. It was broken after 2015 Q2

### Environment

* **Kendo UI version:** 2016.2.714
* **jQuery version:** 1.9.1
* **Browser:** [all ]

**Comment by ggkrustev** [comment]
This is a known limitation introduced exactly after Q2 2015 release. More details can be found here:

http://docs.telerik.com/kendo-ui/AngularJS/Troubleshooting/common-issues#widgets-are-not-initialized
