### ISSUE TITLE
Allow filtering using "isnull" and "isnotnull" operators only

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2020]
### Feature request
Allow filtering using "isnull" and "isnotnull" operators only

### Current behavior
Wrong filter result when only "isnull" and "isnotnull" operators are present with "extra : false"

### Expected/desired behavior
Process "or" filter logic when extra is set to false 
[* Private link kendo repo *](https://github.com/telerik/kendo/blob/master/src/kendo.filtermenu.js#L291)

### Reason for Suggesting the Feature
Ticket ID: 1053716

**Comment by SashaPshenychniy** [comment]
I'm not sure how kendo works internally, but processing "OR" instead of "AND" in case there is NO extra filter at all, is equally wrong even if it resolves my particular case. Filter should just skip additional condition in case it's disabled.

**Comment by rkonstantinov** [comment]
Indeed you are correct. The expected result should be to only apply the first filter expression as the second one is not shown to the user.
