### ISSUE TITLE
How to load only combobox files

### ISSUE THREAD

**Issue by vijaykumarcmeseo** [telerik/kendo-ui-core#2021]
I have used [http://demos.telerik.com/kendo-ui/combobox/index](url)  in my blog [http://vmyblogupdates.blogspot.in/](url)   

But it loads all js files like this file [//cdn.kendostatic.com/2016.2.607/js/kendo.all.min.js](url)
loads all js files but i want to apply only combobox files beacuse all.js file takes more time to load how can i solve this problem any help would really appreciable

**Comment by ggkrustev** [comment]
Hi @vijaykumarcmeseo,

I would suggest you check this thread:
http://docs.telerik.com/kendo-ui/intro/installation/what-you-need

In general, the minimum scripts list would be:
```
<script src="http://cdn.kendostatic.com/{version}/js/kendo.core.min.js"></script>
<script src="http://cdn.kendostatic.com/{version}/js/kendo.data.min.js"></script>
<script src="http://cdn.kendostatic.com/{version}/js/kendo.popup.min.js"></script>
<script src="http://cdn.kendostatic.com/{version}/js/kendo.list.min.js"></script>
<script src="http://cdn.kendostatic.com/{version}/js/kendo.combobox.min.js"></script>
```
Please note that this communication channel is intended only for **bugs** and **feature** requests. If you need further assistance on this, please post your question in Stackoverflow thread.
