### ISSUE TITLE
Grid virtual scroll, Hierarchy  detailgrid(expand) not taken into account.

### ISSUE THREAD

**Issue by mikila85** [telerik/kendo-ui-core#2022]
### Bug report

We are evaluating kendo ui to buy it for our new project,

The page has a kendo grid with virtual scroll.
each row can be expanded as Hierarchy with another grid inside.
when opened, the size of the opened Hierarchy is not taken into account  for the scrollbar and half the grid is not scrollable. 
cant reach the buttom!

![image](https://cloud.githubusercontent.com/assets/3965957/17296481/2a551774-580a-11e6-9226-d324ca0080ef.png)
### Recreation

Here is a recreation in Dojo, 
Scroll to bottom and expand the table, you cannot see the end:
[Dojo recreation.](http://dojo.telerik.com/UcoyO)
### Environment

Kendo UI version: 2016.2.714
jQuery version: 1.12.3
Browser: all

**Comment by Stamo-Gochev** [comment]
Virtual scrolling and hierarchy (detail template) are not compatible as changing the height of the grid content results in incorrect calculation of the virtual scrollbar position. This is listed as a limitation in the documentation:

https://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance#limitations-for-virtual-scrolling
