### ISSUE TITLE
Keyboard navigation not working correctly in workWeek view when switching visible range

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#2027]
steps to reproduce:
http://dojo.telerik.com/@zdravkov/EcaQu

- Select some non allday slot on Monday from the first resource
- Press left arrow key

Expected: select the slot with the same hour range from Friday previous week
Current: select some allday slot

**Comment by Dimitar-Goshev** [comment]
This fix also fixes the related issue.
