### ISSUE TITLE
Cell lines invisible in the xlsx document exported with Spreadsheet after copy/pasting content from Excel

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2035]
### Reproduction of the problem

From an .xlsx file copy the content of two or more adjacent (horizontally or vertically) cells. Paste the copied content in the Spreadsheet. Export to .xlsx.  The behavior can be observed in the [following ](https://demos.telerik.com/kendo-ui/spreadsheet/server-side-import-export)demo. 
### Current behavior

In IE and Firefox the cell lines are invisible in the exported document. 
### Expected/desired behavior

The cells lines are visible in the exported document.
### Environment
- **Kendo UI version:** 2016.2.714
- **jQuery version:** x.y
- **Browser:** [ Firefox 47.0.1 | IE 10,11  ]

**Comment by mparvanov** [comment]
The issue is not reproducible with v. 2019.3.1023
