### ISSUE TITLE
Info - Win10 Anniversary Update - different Edge zoom behavior

### ISSUE THREAD

**Issue by Casimodo72** [telerik/kendo-ui-core#2045]
Hi,

this is just an info. This is not a Kendo issue, but could spare you headaches produced by the Windows 10 Anniversary Update related to Edge's different zoom behavior.

Scenario: On Windows 10 tablets with high resolution, but tiny dimensions, you probably have changed Window's zoom settings via System->Display. Our settings are at 200%, not only because our app is mostly used by older folks with crappy eyes, but also because fingers of Homo Sapiens are just not that tiny and it seems that the dimensions of screens are not accessible to the OS - which is a shame or something else is wrong.

Issue: When installing the Windows 10 Anniversary Update there is a change in behavior of Edge's zoom related to Window's zoom.
Before the update: Edge's zoom was modified by Window's zoom.
After the update: Edge's zoom is _not_ modified by Window's zoom.
This means you have to adjust Edge's zoom for your app(s) if you had a Windows zoom other than 100%.
E.g. if you had a Windows zoom of 200%. Then Edge will no longer reflect the +100% of Windows, and thus stuff will be displayed in a -100% tiny fashion.

Regards
Kasimier Buchcik

**Comment by matanasov** [comment]
@Casimodo72 
Thank you for sharing this information.

@hadjieva 
Do you think we should add this in our docs?
