### ISSUE TITLE
Selection is restored to an old position after Ctrl+A under IE11

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2046]
### Bug report
Selection is restored to its previous state after using select-all in text (Ctrl+A). Any changes are not applied to the new selection. 

### Reproduction of the problem

1. Go to http://demos.telerik.com/kendo-ui/editor/index;
1. Put the cursor somewhere in the text;
1. Use Ctrl+A to select all text;
1. Place the cursor elsewhere;
1. Press Enter to insert new line.

### Current behavior
Command is applied on the previous selection.

### Expected/desired behavior
Command to be applied on the newly made selection.

### Environment

* **Kendo UI version:** 2016.2.714
* **jQuery version:** 1.12.3
* **Browser:** [IE 11]

**Comment by ghelyar** [comment]
This is still occurring in 2016.3.1118.
