### ISSUE TITLE
Grid: When adaptive rendering is used ( mobile: true) the popup editor does not render non-editable fields correctly

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#2050]
### Reproduction of the problem

Please refer to the http://dojo.telerik.com/EbUnuZ/3 example and open an item for edit using the edit button. 
### Current behavior

The ProductName label and the ProductName value are displayed over one another.
### Expected/desired behavior

The ProductName value should be displayed next to the "ProductName" label. 
### Environment
- **Kendo UI version:** 2016.2.714
- **jQuery version:** 1.12.3
- **Browser:** Chrome 51

**Comment by PreslavKozovski** [comment]
Workaround:
```
edit: function(e){
  var container = e.container;
  var editFields = container.find(".k-edit-field");
  
  editFields.each(function(i, e){
    if($(e).children().length===0){
      $(e).wrapInner("<div></div>");
    }
  });
}
```

https://dojo.telerik.com/IkIZUxoV

**Comment by MilenaCh** [comment]
The issue does not exist with the latest KendoUI version - 2019.2.514(R2 2019).
