### ISSUE TITLE
Prompting cell / range error message to display in Spreadsheet, forces validation cell list to be wrapped in a _matrix(...)

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2055]
### Bug report

When applying list validation to a Spreadsheet cell / range and the list of accepted values is defined in the following format (H1:H3), every time the validation prompts the error message, the validation list is wrapped within a _matrix(...). The (H1:H3), for example, becomes _matrix(_matrix(_matrix(_matrix(H1:H3)))).
### Reproduction of the problem

Could be observed on [the demos](https://demos.telerik.com/kendo-ui/spreadsheet/index).
[Video, reproducing the problem](http://screencast.com/t/MoOsOpjVHrg).
### Expected/desired behavior

Validation list is expected to remain (H1:H3).
### Environment
- **Kendo UI version:** 2016.R2.714
- **Browser:** all

**Comment by mishoo** [comment]
No longer happens.
