### ISSUE TITLE
Navigator.series.missingValues "gap" does not work

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-ui-core#2058]
### Bug report
Navigator.series.missingValues "gap" does not work. Reported in ticket: 1056062

### Reproduction of the problem
Can be reproduced in this dojo: http://dojo.telerik.com/@Iliana/aKoMA. 

### Current behavior
Setting the missingValues to "gap" clears the navigator.

### Expected/desired behavior
Navigator.series.missingValues "gap" should work like in the main chart.

### Environment
* **Kendo UI version:** 2016.2.714
* **Browser:** [all]

**Comment by tsvetomir** [comment]
The default styling for the navigator is to show line series with hidden markers. When `missingValues` is set to `gap` the line disappears as well. This is as intended.

You can see the markers in the updated snippet:
http://dojo.telerik.com/@tsvetomir/ILiZU

            navigator: {
              series: [{
                type: "line",
                markers: {
                  visible: true
                },
                field: "Close",
                missingValues: "gap"
              }],

              categoryAxis: {
                baseUnit: "years"
              }
            }
