### ISSUE TITLE
Selected item is duplicated when dropdown is opened

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2062]
### Reproduction of the problem
Selected item is duplicated when dropdown is opened. Ticket ID: 1056319
Steps to reproduce: 
1. Select an item
2. Click to open dropdown ![2016-08-12_1312](https://cloud.githubusercontent.com/assets/5161281/17619755/2103006c-6090-11e6-8ee7-73a1380cd578.png)

### Current behavior
Selected item is duplicated

http://screencast.com/t/RTFt22dXcw3y

### Expected/desired behavior
Selected item not to be duplicated

**Comment by dimodi** [comment]
related to https://github.com/telerik/kendo-ui-core/issues/2175

**Comment by ggkrustev** [comment]
This should be fixed too.
