### ISSUE TITLE
Dynamic class cache is generated multiple times for the same request

### ISSUE THREAD

**Issue by dimodi** [telerik/kendo-ui-core#2069]
### Bug report

Dynamic class cache is generated multiple times for the same request. `GetHashCode()` generates unique hash codes even for the same request in `Kendo.Mvc/Infrastructure/Implementation/Grouping/Aggregates/EnumerableAggregateFunctionBase.cs`

### Reproduction of the problem

The issue can be observed when using a Kendo UI MVC Grid with aggregates.

### Current behavior

Memory consumption increases when making multiple identical requests.
The topic is discussed in ticket 1027403 ("Memory leak when using Kendo Grid with aggregates and EntityFramework")

### Expected/desired behavior

Multiple caching for identical requests should not occur.

### Environment

* **Kendo UI version:** 2016.2.714

**Comment by Xizario** [comment]
Closed with https://github.com/telerik/kendo/commit/98c14f373725289af0871d01cb5814d8530a2446
