### ISSUE TITLE
Unexpected behaviour of Kendo Editor, when Enter key is pressed

### ISSUE THREAD

**Issue by spatarinski** [telerik/kendo-ui-core#2074]
### Reproduction of the problem
Sample target - official Kendo Editor Demo: [http://demos.telerik.com/kendo-ui/editor/index](http://demos.telerik.com/kendo-ui/editor/index)

1. set cursor before a word in bulleted list
2. press backspace to delete a bullet
3. press enter
4. press enter again => the cursor moves above the bulleted list
5. write a word and press enter (word "one" in my demo)
6. write a word and press enter (word "two" in my demo) => the cursor moves up
7. write a word and press enter (word "three" in my demo)
8. write a word and press enter (word "four" in my demo) => the cursor moves up, last letter 'e' from word 'three' is moved to new line

### Expected behavior
The cursor should always go to a new line/item after the Enter key is pressed.

### Environment

* **Kendo UI version:** 2016.2.714
* **Browser:** [all]

**Comment by ipeshev** [comment]
Currently this exact behavior is passing, it is perfect candidate for unit test. Please contact me if you need any assistance with it. 
There is something strange though, if you execute steps 1 -> 2 -> 2 you will see how the cursor is going bellow the ordered list. This behavior is present in offical demos so it is not regression. Referred #2214
