### ISSUE TITLE
Workbook should export wrapped cells with correct height

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2076]
### Bug report

Kendo ooxml Workbook wrapped cells are exported with the default row height.

### Reproduction of the problem
[Dojo demo](http://dojo.telerik.com/IMEXE)

### Expected/desired behavior
Workbook should export wrapped cells with correct height

**Comment by mishoo** [comment]
I doubt we can do anything for this case.  OOXML export code would simply produce a XLSX file from the data it gets, but it has no knowledge about fonts/sizes to be able to automatically determine row height; that's the task of the caller (e.g. the Spreadsheet widget).
