### ISSUE TITLE
Excel Export - Multi-line content exported as a single line 

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2077]
### Bug report

Cells with multiple lines are exported as one line.

### Reproduction of the problem
Official [Demo](http://demos.telerik.com/kendo-ui/spreadsheet/index)

- Enter several lines in a single cell
- Export

It seems that the line endings are lost. 
When you click on the cell, the cell preview is correct.

### Expected/desired behavior
Ideally, should be exported as wrapped cells with the correct height. 
Possibly related with #2076

**Comment by mishoo** [comment]
Can't reproduce.  Please reopen with more detail if I'm missing something.

**Comment by mishoo** [comment]
Seems [there is an issue](http://screencast.com/t/1OCFOEYC4) though, reopening.

**Comment by mishoo** [comment]
I don't understand what's going on here.  After [this commit](https://github.com/telerik/kendo/commit/ba77b6d8cc9175978c1a16eadc0b75b8c3db2807), our `xl/sharedStrings.xml` is *identical* to what Excel generates, yet still, it won't show the newline until you edit the cell and press Enter.

I found a couple of links describing the same problem:
- https://github.com/SheetJS/js-xlsx/issues/108
- https://github.com/PHPOffice/PHPExcel/issues/744

**Comment by mishoo** [comment]
Aha, apparently we need to set the "wrap" style attribute. :-(  I'll push an ugly fix.

**Comment by ipeshev** [comment]
Currentl it is separating the rows correctly, but it hides some of the rows under MS Excel , in first attachement it hides one row in other it hides 2 rows which gets visible when cell is focused ( that with scrambled text ). On Libre office it is fine, online also is fine. This is definitely MS bug !!!
@mishoo Please take a decision, how to procede with this one.

**Comment by jmartsch** [comment]
@ipeshev Take a look to this answer here: https://github.com/protobi/js-xlsx/issues/73#issuecomment-308316352
It is not a solution, but you can pay them to get this fixed.
