### ISSUE TITLE
The value circle is not in the correct position when setting the value over a hidden colorpicker

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#2079]
### Reproduction of the problem
The value circle is not in the correct position when setting the value over a hidden flat colorpicker.
[http://dojo.telerik.com/@parvanov/EQuzE/2](http://dojo.telerik.com/@parvanov/EQuzE/2)
Workaround: [http://dojo.telerik.com/@parvanov/AhOMe](http://dojo.telerik.com/@parvanov/AhOMe)

### Current behavior
1) Hide the colorpicker
2) Set a value for the color
3) Show the color picker 

### Expected/desired behavior
The value circle points to the proper color

### Environment

* **Kendo UI version:** 2016.2.714
* **jQuery version:** 1.12.3
* **Browser:** all

**Comment by Iankodj** [comment]
The described behavior is expected. The widget cannot interact with the DOM properly when its wrapper is hidden and has no viewport. Such a scenario cannot be handled with built-in code.

More details and possible solution to handle such situations are documented here (will be live shortly): http://docs.telerik.com/kendo-ui/controls/editors/colorpicker/how-to/fix-selected-value-when-shown.
