### ISSUE TITLE
Collapsed load-on-demand node cannot be expanded after sort

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-ui-core#2081]
[Reproduction sample](http://dojo.telerik.com/ANuxa)
1. Expand Item 3.
2. Collapse Item 3.
3. Click on Sort button.
4. Again expand Item 3. (It does not expands)

Reported in ticket ID 1057208

**Comment by gyoshev** [comment]
Possible workarounds:
- [using loadOnDemand: false](http://dojo.telerik.com/ANuxa/2)
- [resetting the loaded flag after sorting](http://dojo.telerik.com/ANuxa/3)

**Comment by jivanova** [comment]
Not reproducible with latest version: [http://dojo.telerik.com/eRUzAGIF](http://dojo.telerik.com/eRUzAGIF)
