### ISSUE TITLE
Splitter does not resize all of its child panes on window resize

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-ui-core#2083]
### Reproduction of the problem
1. Open https://dojo.telerik.com/ELUxUziZ/3
2. Use the Splitbar to resize  Pane A to ~90% of the Splitter's width
3. Resize the browser window
### Current behavior

The window-resizing of the Splitter is broken when one of the Splitter's panes is resized to less than 20% of the whole Splitter's width before that.
**video:** [http://screencast.com/t/fLR0muTPYSl](**http://screencast.com/t/fLR0muTPYSl**)
### Expected/desired behavior

All panes are resized properly.
### Environment
- **Kendo UI version:** 2023.3.1010

**Comment by movedoa** [comment]
The problem still exists in 2017.1.118

**Comment by pepinho24** [comment]
With version 2024.4.1112 the panes do not make the splitter overflow when the window is resized. 

Another important point is that one of the panes should be without set size, to compensate for the set size of the other panes, to act as a buffer.
