### ISSUE TITLE
Pasted number should be validated against min/max range

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#2088]
### Current behavior
The widget will allow to paste a valid number although it is out of range. This will result in additional adjustment of blur. To avoid the "surprise" effect, the widget should reject values that are out of range.

### Expected/desired behavior
Reject pasted value that is out of range.

### Reason for Suggesting the Feature
Reduce the "surprise" effect of current behavior.

### Environment

* **Kendo UI version:** 2016.2.714
* **jQuery version:** 1.9.3+
* **Browser:** all

**Comment by ggkrustev** [comment]
For those who would like to restrict typing of extremely long numbers (e.g. 1e+47), I would suggest  add maxlength attribute to the widget:
```
<input id="numeric" maxlength="20" />
```

**Comment by MLefebvreICO** [comment]
Regarding extremly long numbers, why not just add a validation on https://github.com/telerik/kendo-ui-core/blob/50683ecaceba5ceb349f8644fdd5c861e15c6777/src/kendo.numerictextbox.js#L272

That does : 
```js
if (isNaN(value)) {
     // Put the old value back
}

**Comment by ggkrustev** [comment]
@MLefebvreICO, the suggestion seems plausible. 
I suppose that you would like to support long numbers without specifying `maxlength` attribute. Is that the case?

**Comment by MLefebvreICO** [comment]
@ggkrustev Exactly !
