### ISSUE TITLE
Upgrade to AngularJS 1.5.*

### ISSUE THREAD

**Issue by qbunia** [telerik/kendo-ui-core#2092]
I heard that its not easy to upgrade to 1.5 as Angular team totally changed NgModel. Can you give at least estimate when you are going to upgrade?

**Comment by ggkrustev** [comment]
We've planned to resolve the `select` issue in the next internal build - https://github.com/telerik/kendo-ui-core/issues/2252

I believe that there wouldn't be any other show stoppers.

I will close this thread. Please follow the corresponding #2252 issue.
