### ISSUE TITLE
Long pasted text with spaces is split on multiple lines when copied from Excel cell.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2094]
### Bug report
Long text with spaces is split into multiple lines when copied from Excel cell. The text is pasted on a single line when copied from a different place like Notepad.

### Reproduction of the problem
The issue is reproducible in all of our demos: https://demos.telerik.com/kendo-ui/spreadsheet/index.
Steps:

1) Write "abc abc abc abc abc abc abs" in a cell in Excel, copy the cell and paste it in the Kendo UI Spreadsheet. The text goes on multiple lines(2).

2) Write "abc abc abc abc abc abc abs" repeat the same using Notepad, not Excel, the pasted text is on a single line.

### Expected/desired behavior
A consistent result when the text is pasted.

### Environment

* **Kendo UI version:** 2016.2.714, the issue is not observable in  2015.3.930 
* **jQuery version:** x.y
* **Browser:** all

**Comment by mishoo** [comment]
Fixed in https://github.com/telerik/kendo/commit/761fb42ce1f66c19732257d7ac3c2e4d23eec424 (sorry, forgot to reference the issue in the log).
