### ISSUE TITLE
Error when using MenuItem->separator

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2095]
### Bug report
[Code location in repository](https://github.com/telerik/kendo/blob/bec019c6b5e6a4a00b9c14f25c6dba3bb5ed39f1/wrappers/php/lib/Kendo/UI/MenuItem.php#L46)

**Incorrect function :**

```
public function separator() {
       return $this->setProperty('separator', $value);
   }
```

**Should be either :**

```
public function separator($value) {
        return $this->setProperty('separator', $value);
    }
```

**or :**

```
public function separator() {
        return $this->setProperty('separator', true);
    }
```

**Comment by ipeshev** [comment]
Why not passing $value parameter to the upper wrap ?
