### ISSUE TITLE
Draggable AutoScroll does not show the top (first) node or show half of the node.

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#2101]
### Bug report

Kendo UI TreeView autoScroll sometimes does not show the top (first) node or show half of the node.
### Reproduction of the problem

The problem can be replicated with http://dojo.telerik.com/uCuZUS/3example. 

1. Drag a child item of the `Storage` node to top

### Current behavior

Sometimes when a child item of the "Storage" is dragged over to the upper part of the scrollable container (in order to scroll and eventually shows the "Furniture" node) it stops without reaching the top part of the scrollable container. The "Furniture" is cut in half or not shown at all.

### Expected/desired behavior

The Furniture node should be shown completely. 

### Environment
- **Kendo UI version:** 2019.1.115
- **jQuery version:** 1.12.3
- **Browser:** all

**Comment by dmanova** [comment]
Seems to be fixed with https://github.com/telerik/kendo-ui-core/issues/3289
