### ISSUE TITLE
Theme builder doesn't export chart's gradients

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/kendo-ui-core#2103]
1) Open theme builder - http://demos.telerik.com/kendo-ui/themebuilder/
2) Select Flat theme.
3) Export the theme and apply it to the chart.
Expected - The JSON should have information about disabling the gradient:
        "seriesDefaults": {  "overlay": {  "gradient": "none"  },  },
Actual - The JSON doesn't have setting about disabling the gradient and the chart series still have gradient because it is enabled by default.

**Comment by mparvanov** [comment]
Closing due to relatively low severity and lack of recent demand by the community.
