### ISSUE TITLE
Restrict characters input in Android OS

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#2109]
### Current behavior

The widget does not restrict the user input when it is loaded in mobile browser (i.e. Chrome) on Android device. 

To see the current behavior:
- load the http://demos.telerik.com/kendo-ui/numerictextbox/index in Android OS v5+
- start typing in the input
- notice how the non-numeric characters are allowed
### Expected/desired behavior

Allow only numeric values
### Reason for Suggesting the Feature

The change of the behavior will allow the usage of the widget in Android OS
### Environment
- **Kendo UI version:** 2016.2.714
- **jQuery version:** 1.9.3+
- **Browser:** Android 5.0+ Web Browser

**Comment by MLefebvreICO** [comment]
Almost one year later, any feedback on this would be great as we're gonna go in production with this and we need to support Android phones.

**Comment by ag-petrov** [comment]
QAs please test the fix in all browser on all devices

**Comment by ag-petrov** [comment]
Related issue - https://github.com/telerik/kendo/issues/6884
