### ISSUE TITLE
TabStrip & PanelBar regression

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#2111]
### Bug report
Those are first results of image comparision tests between 2016.2.714 and current state, false positives are removed , and elso baseline update (evolution)
### Current behavior
- [x] Panelbar/Tabstrip All Themes
![themebuilder_bootstrap_626f647920236578616d706c65202e636f6c756d6e3a66697273742d6368696c64 themebuilder_bootstrap_626f647920236578616d706c65202e636f6c756d6e3a66697273742d6368696c64 1024px diff](https://cloud.githubusercontent.com/assets/4143177/18086897/e7985f5a-6eba-11e6-881f-adae193aa8ef.png)

- [x] RadioButtons/Checkboxes Default those should be more centered
![themebuilder_default_626f647920236578616d706c65202e636f6c756d6e202e7375622d636f6c756d6e themebuilder_default_626f647920236578616d706c65202e636f6c756d6e202e7375622d636f6c756d6e 1024px diff](https://cloud.githubusercontent.com/assets/4143177/18086968/5db4d45c-6ebb-11e6-81aa-d8a0355b0e96.png)

- [x] MultiSelect content padding ( it can be seen mostly in themebuilder )
![themebuilder_nova_body_ example_ column_ k-multiselect themebuilder_nova_body_ example_ column_ k-multiselect 960px baseline](https://cloud.githubusercontent.com/assets/4143177/18133298/a82f9ade-6fa2-11e6-9f1e-5d84c48ba5a7.png)

### Expected/desired behavior
We should maintain difference up to some minimum which will allow us to update baseline

### Environment

* **Kendo UI version:** 2016.2.714
* **jQuery version:** N/A
* **Browser:** [Chrome XX ]

**Comment by inikolova** [comment]
TabStrip padding is OK now
