### ISSUE TITLE
Feature Request: Impliment k-ng-model on Sortable

### ISSUE THREAD

**Issue by sitefinitysteve** [telerik/kendo-ui-core#2112]
### Bug report/Feature request
Feature request

### Reproduction of the problem
http://jsbin.com/soyatet/1/edit?html,console,output

### Current behavior
- DOM is out of sync with the model, requires manual intervention to change array elements, results are inconsistent (doesnt work properly)

### Expected/desired behavior
DOM matches the NG model array

### Reason for Suggesting the Feature
Angular devs use ng-repeat for arrays, I think just about everyone would.  It causes confusion and issues to not support this like other widgets do [Example](https://github.com/bevacqua/angular-dragula#dragula-model).

This really should be mandatory to claim angular support on kendo sortable.

### Environment

* **Kendo UI version:** All
* **jQuery version:** All
* **Browser:** [all]

**Comment by underlog** [comment]
Hi, 

please post this in user voice - we will review the interest in our user base and consider it further. Thank you.

**Comment by sitefinitysteve** [comment]
It's not a feature request, this is a honkin bug on the NG sortable implementation (or lack thereof)... it's been on uservoice for months anyway

**Comment by underlog** [comment]
I assume that this is what you refer to, pasting the link for people who find this issue. http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/14155941-angular-kendo-sortable-work-with-ng-repeat
