### ISSUE TITLE
RecurrenceEditor does not validate nor updates "End recurrence on" date

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2117]
### Bug report
The Recurrence editor does not validate the [End recurrence on date](http://screencast.com/t/i4bLFndgAo). When the date in the EndOn DatePicker is invalid, a javascript error is thrown.

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/scheduler/index
1. Start creating event;
1. Set recurrence to Daily;
1. Select **End: On** option

### Current behavior
- When you set invalid date in the "End recurrence On" date picker, e.g. 60/11/2013, a javascript error is thrown: `"Uncaught TypeError: Cannot read property 'getFullYear' of null";`
- When you try to save the event with the invalid date for "End recurrence On" date picker, the popup is closed as if the event is created successfully, but it is not created or not created correctly;

Here is a video of the issue: http://screencast.com/t/2uBH4dxLyH 

### Expected/desired behavior
The Recurrence date picker should not throw error and should validate as the Start and End DateTime pickers. Similar to this fixed issue: https://github.com/telerik/kendo-ui-core/issues/3846

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
### Workaround

The following [Dojo snippet](http://dojo.telerik.com/@zdravkov/EfePi) provides a workaround for invalid dates entered in the End On DatePicker. If the entered date is not in the min/max boundaries of the DatePicker, then the previous value is retained in the input.

**Comment by Dimitar-Goshev** [comment]
After the fix there is no error thrown and a validation tooltip is shown.
But the tooltip disappears on clicking on another widget, e.g. on another dropdown or on the Save button. Thus, a user may miss the tooltip if hidden too quickly and then it is not obvious what is the reason for not being able to Save the event.
In contrast, the validation tooltip for the End date and time remains visible until the invalid date is fixed. I would expect the same for the On tooltip.
