### ISSUE TITLE
Double borders shown in tabs

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#2131]
### Reproduction of the problem

![capture 2016-09-03 at 13 34 46](https://cloud.githubusercontent.com/assets/4143177/18309061/31818b46-7500-11e6-8512-e96d0d0eac9e.png)

### Expected/desired behavior
To have only single border.

### Reason for Suggesting the Feature
_(feature report only)_
Provide information about what necessitates the implementation of this feature.

### Environment

* **Kendo UI version:** 2016.2.714
* **jQuery version:** all
* **Browser:** all

**Comment by inikolova** [comment]
Cannot be reproduced any more
