### ISSUE TITLE
Valid cells with applied validation display as invalid in Spreadsheet, after its content has been exported to XLSX

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2134]
### Bug report
Valid cells with applied validation display as invalid in Spreadsheet, after its content has been exported to XLSX.

### Reproduction of the problem
Could be reproduced on the following [Dojo demo](http://dojo.telerik.com/axuLE/8)

### Current behavior
Displays valid cells as invalid

### Expected/desired behavior
Should keep the validation status that was correct before export

**Comment by vladimirivanoviliev** [comment]
After some investigation it seems that this behavior is indeed and issue as the validation are reset during the export, but never recalculated after it.
