### ISSUE TITLE
The filter expression is not cleared in the Excel document.

### ISSUE THREAD

**Issue by kostadin-dimitrov** [telerik/kendo-ui-core#2135]
The issue could be replicated in the following [dojo sample](http://dojo.telerik.com/IYiGi/2). The steps to replicate the issue could be found below.

1) Export
2) Filter on Jane
3) Export (see single row)
4) Press clear (see all data)
5) Export (*still* see single row)

**Comment by mishoo** [comment]
Apparently, that's not the proper way to reset the filter, as if I use the "Clear" button from the filter menu then export is fine.

The following code [works](http://dojo.telerik.com/IYiGi/4):

```js
  function clearFilter(){
    var grid = $("#grid").data("kendoGrid");
    grid.thead.find("th").each(function(){
      var filter = $(this).data("kendoFilterMenu");
      filter.clear();
    });
  }
```

(found by digging through the Grid and FilterMenu code; that's probably undocumented/not public API)
