### ISSUE TITLE
Data validation dialog is not persisting cell validation rules

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#2136]
### Reproduction of the problem

Can be observed in official  [demos](http://demos.telerik.com/kendo-ui/spreadsheet/index)
Try to set custom validation rule with invalid formula something like `##44` for some cell, if you open data validation dialog again the settings are gone, it is missing confirmation for validity.
### Expected/desired behavior

Validation settings to be persisted in the dialog.
### Environment
- **Kendo UI version:** 2016.2.714
- **jQuery version:** N/A
- **Browser:** All

**Comment by ipeshev** [comment]
My mistake this will be deleted.

**Comment by ipeshev** [comment]
@gyoshev  It is with updated description, it is minor though.

**Comment by mparvanov** [comment]
Closing due to relatively low severity and lack of recent demand by the community.
