### ISSUE TITLE
Value method does not return correct dataItem after dataSource range is changed

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#2137]
### Reproduction of the problem

Example: http://dojo.telerik.com/@development@enviro-intel.com/OfidU

Steps: move the scrollview forward, after you pass 10th page (dataSource.pageSize = 10) the `value` method starts to return `undefined`.

The issue is caused by the fact that the dataSource range is changed and `dataSource.at(index)` stops working. See [this line](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.mobile.scrollview.js#L794)

The obvious solution `dataSource.at(this.page - this.dataSource.skip())` does not work because dataSource changes its range before end of the current page is reached, e.g. there is a case when the scrollview page is equal to 8 but skip() returns 10.
### Environment
- **Kendo UI version:** 2016.2.714
- **jQuery version:** any
- **Browser:** [all]

**Comment by ag-petrov** [comment]
Related to the mobile suite which is now depricated
