### ISSUE TITLE
Spreadsheet should remove the disabled state of cells before pasting

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2139]
### Bug report

Copying a disabled cell should not copy the disabled state, only the content.

### Reproduction of the problem

[Official disabled cells demo](https://demos.telerik.com/kendo-ui/spreadsheet/disabled-cells)

- Copy a disabled cell
- Paste to any enabled cell
- The changed cell is now disabled as well 

### Expected/desired behavior

Copy only the content, not the state as well. 
Reported in [Forum thread](http://www.telerik.com/forums/copy-paste-of-disabled-cells)

**Comment by tsvetomir** [comment]
Related to #1728
