### ISSUE TITLE
There is no ToDataSourceResult extension for DataTable in ASP.NET Core

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#2140]
### Reproduction of the problem

In the ASP.NET Core assembly there is no ToDataSourceResult extension method for DataTables
### Environment
- Telerik.UI.for.AspNet.Core 2016.2.714

**Comment by ag-petrov** [comment]
This is not a bug. There is no DataTable support for ASP.NET Core.

**Comment by Vasimovic** [comment]
Just FYI in case it makes a difference: ASP.NET Core 2 targeting .NET Standard 2.0 does support DataTables

[.NET Core API Reference version 2.0](https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-2.0)

**Comment by TsvetinaIvanova** [comment]
The ASP.NET Core project has been upgraded to .NET Core 2.0. We should review this item.

**Comment by FunkyMJ** [comment]
I would very much like to see binding to DataTables implemented.  
"Without this, binding a Grid in Razor Pages to a varying number of columns is very hard, if not possible."

**Comment by ag-petrov** [comment]
@TsvetinaIvanova Binding to the model like demonstrated above and in [this](https://demos.telerik.com/aspnet-mvc/grid/serverbinding) demo is possible only for the Grid for MVC and not ASP.NET Core. The reason for this is that with such binding server rendering is used and the Core grid does not have such. However in the next official release you will be able to bind the grid to a DataTable as demonstrated below.

View:
```
@model System.Data.DataTable

@(Html.Kendo().Grid<dynamic>()
    .Name("Grid")
    .Columns(columns =>
    {
        foreach (System.Data.DataColumn column in Model.Columns)
        {
            var c = columns.Bound(column.ColumnName);
        }
    })
    .Pageable()
    .Sortable()
    .Editable(ed => ed.Mode(GridEditMode.PopUp))
    .Filterable()
    .Groupable()
    .DataSource(dataSource => dataSource
        .Ajax()
        .Model(model =>
        {
            foreach (System.Data.DataColumn column in Model.Columns)
            {
                var field = model.Field(column.ColumnName, column.DataType);
            }
        })
        .Read(read => read.Action("Customers_Read", "Grid"))
    )
)
```

Controller:
```
[Demo]
public IActionResult Index()
{
	DataTable products = GetDataTable(500);
	
	return View(products);
}
private static DataTable GetDataTable(int howMany)
{
    var dataSource = new DataTable();
    dataSource.Columns.Add("Field1");
    dataSource.Columns.Add("Field2", typeof(int));
    for (int i = 0; i < howMany; i++)
    {
        dataSource.Rows.Add("value" + i, i);
    }
    return dataSource;
}
public IActionResult Customers_Read([DataSourceRequest] DataSourceRequest request)
{
	return Json(GetDataTable(500).ToDataSourceResult(request));
}
```

**Comment by christophad** [comment]
When the next official release is going to be available? dataSourceResult for DataTables is extremely important.

**Comment by matanasov** [comment]
@christophad 
This issue was resolved in R2 2018 which was released on 16 May and is available for download.
Please read the last comment by @ag-petrov above as it states some important details about the solution.

**Comment by christophad** [comment]
When I update the Kendo.Mvc library via nuget, the latest version that exists is 2016.2.616 and it doesn't include toDatasourceResult for DataTables
