### ISSUE TITLE
IE11 scroll is always visible in range name dropdown

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#2144]
### Reproduction of the problem

![snip](https://cloud.githubusercontent.com/assets/4143177/18385266/3c9537a0-7698-11e6-9a79-8447aa282816.png)
### Expected/desired behavior

On other browsers it is not visible, and the dropdown is taking height as much as needed.
### Environment
- **Kendo UI version:** 2016.2.714
- **jQuery version:** N/A
- **Browser:**  IE 11

**Comment by Dimitar-Goshev** [comment]
The issue is no longer reproducible.
