### ISSUE TITLE
Widget highlights first item incorrectly

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#2146]
### Reproduction of the problem
1. Open this demo - http://dojo.telerik.com/uDIbU/2
2. Start searching for different items
3. (hard to replicate constantly) the first item will be focused although the `highlightFirst: false` config.

The most probable reason for this inconsistent behavior is the explicit focus of the StaticList widget:
https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.list.js#L2228

This should be controlled by an option `highlightFirst` probably, which will eliminate the need of clearing the focused item on second step:
https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.autocomplete.js#L411
### Expected/desired behavior

The widget should not focus the first item when `highlightFirst: false` is defined.
### Environment
- **Kendo UI version:** 2016.2.717
- **jQuery version:** 1.9.3+
- **Browser:** all

**Comment by zdravkov** [comment]
Could not replicate it with the latest version of Kendo.

**Comment by Dimitar-Goshev** [comment]
This issue is still reproducible and logged publicly - https://github.com/telerik/kendo-ui-core/issues/3852 . It is easier for reproduction with connection throttling.
