### ISSUE TITLE
Scheduler changes date on show work hours click in workWeek view

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2147]
### Bug report

Scheduler should not change the date when show work hours is clicked in workWeek/week view.
### Reproduction of the problem

[Official demo](http://demos.telerik.com/kendo-ui/scheduler/index)
1. Date when initialized in our demo is 2013/6/13, selected view - workWeek
2. Click show business hours
3. Check the date - it is now 2013/6/10 (Monday)
### Current behaviour

The date is changed to the startDate of the current view:
[source file](https://github.com/telerik/kendo/blob/master/src/kendo.scheduler.dayview.js#L982-L985)
### Expected/desired behavior

Preserve the current date

**Comment by John-Pendlebury** [comment]
Hi,
I was wondering if there has been any movement on this problem. We're still getting reports on it from our test and support departments with the latest version of the Kendo API.

Kind Regards,
John

**Comment by zdravkov** [comment]
We will do our best to address the issue as soon as possible.
