### ISSUE TITLE
The page cannot be scrolled on touch devices with IE and Edge when the Grid is selectable.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2148]
### Bug report

The grid cannot be scrolled on touch devices with **IE** and **Edge** when the Grid is _selectable_.
### Reproduction of the problem

The issue can be reproduced in the following Dojo and touch devices with IE and Edge browsers:

http://dojo.telerik.com/eFIvI/4
### Current behavior

The page cannot be scrolled.
### Expected/desired behavior

The page to be scrollable.
### Environment
- **jQuery version:** x.y
- **Browser:**  IE and Edge.

**Comment by IT-CASADO** [comment]
Any progress on fixing this?

**Comment by boyandim** [comment]
A fix will be included in our upcoming service pack release (Kendo UI R3 2017 SP1).
