### ISSUE TITLE
Configuring spreadsheet toolbar should configure context menu accordingly

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#2151]
### Bug report: Design issue
Configuring spreadsheet toolbar should configure context menu

### Reproduction of the problem
Configure spreadhseet as in http://dojo.telerik.com/ekUCI where copy, cut paste and merge have been removed from the toolbar.

### Current behavior
copy, cut, paste and merge are still available in the context menu
![image](https://cloud.githubusercontent.com/assets/2556751/18442068/42879efc-7907-11e6-8ead-29025fa105e5.png)

### Expected/desired behavior
Use toolbar configuration to configure context menu

### Environment

* **Kendo UI version:** 2016.2.714
* **jQuery version:** all
* **Browser:** all

**Comment by underlog** [comment]
I would like to ask you to follow the rules of our workflow when it comes to feature requests.These are to be submitted in UserVoice.

**Comment by jlchereau** [comment]
*I will do my best* although I have come to realize we do not have the same definition of a defect vs. feature.

In the company I work for, we would consider that the feature is about configuring the spreadsheet component to prevent certain operations (e.g. merge cells) and we would consider the availability of these operations in context menus despite being removed from the toolbar as a design issue, in other words a defect, not a feature request.

**Comment by underlog** [comment]
Thank you for your consideration; I understand your point—in this case, the spreadsheet is **missing a feature**; certain operations can't be fully disabled from the UI. The underlying feature that will solve this is to implement customization of the context menu. 

Debating if something is a bug or a missing feature, especially when it comes to an incredibly complex component like the spreadsheet won't bring much value to discussion. We may as well consider any missing feature from excel/google docs as a defect, as it prevents the you from implementing a given scenario correctly.
