### ISSUE TITLE
k-ng-model broken if form name not on scope

### ISSUE THREAD

**Issue by 807811b0-1373-11e5-b60b-1697f925ec7b** [telerik/kendo-ui-core#2152]
### Bug report

If you use `k-ng-model` property on an item, it will look for the parent `<form>` element and try to read it off of scope. The problem is that the parent form might not be on scope. This is a regression from the previous release v2016.2.504:

### Reproduction of the problem

Working (v2016.2.504):
http://dojo.telerik.com/eCIVa

Broken (v2016.3.914):
http://dojo.telerik.com/INaXU

### Current behavior

Error in console. Model is not displayed on screen after picking a selection. (http://dojo.telerik.com/efumu)

### Expected/desired behavior

No error in console. Model value is displayed on screen after picking a selection. (http://dojo.telerik.com/eCIVa)

### Environment

* **Kendo UI version:** 2016.3.914
* **jQuery version:** 1.9.1
* **Browser:** all

**Comment by 807811b0-1373-11e5-b60b-1697f925ec7b** [comment]
I wrote a workaround:

```js
// @todo remove this terrible hack
var form = $element.closest('form');
var formName = form.attr('name');
$scope[formName.split('.')[0]] = {};
```

http://dojo.telerik.com/efumu/2

**Comment by rkonstantinov** [comment]
Thanks for the report. The error should be gone in the next internal build.
