### ISSUE TITLE
ThemeBuilder numeric - wrong hover icon

### ISSUE THREAD

**Issue by mkovacheva** [telerik/kendo-ui-core#2153]
### Bug report
ThemeBuilder numeric - wrong hover icon for Increase & Decrease value of the numeric field.

### Reproduction of the problem
_(bug report only)_
![image](https://cloud.githubusercontent.com/assets/11819170/18464515/3464b948-799a-11e6-9955-2391d77ee4b2.png)

**Comment by inikolova** [comment]
This appears to be an issue in the Material theme, not in the ThemeBuilder itself. Scenario: NumericTextbox in PanelBar. Can be observed here: http://dojo.telerik.com/@Iliana/eFogO
