### ISSUE TITLE
KendoUI Grid with NumericTextBox column doesn't work when using KendoSortable

### ISSUE THREAD

**Issue by GabrielTudose** [telerik/kendo-ui-core#2161]
### Bug report
- KendoUI Grid with NumericTextBox column doesn't work when using KendoSortable
### Reproduction of the problem
- When using KendoUI Grid having applied KendoSortable and have a NumericTextBox column, the spinner from that column does not update the value when click on another cell, but when click outside the grid it works well.
- Ex of repro.: click on NumericTextBox cell, spin up or down, click on another cell, value is reverted.
- Dojo: http://dojo.telerik.com/@gabytudose/OSoJa
- The first impression was that using that combination in AngularJS caused the problem, but can be reproduced with any simple example.
### Current behavior

After removing kendoSortable from the grid all works well.
### Expected/desired behavior

NumericTextBox column should update the value when that is changed from spinners when using KendoSortable in KendoUI Grid.
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** 1.12.3
- **Browser:** [all] 
- http://dojo.telerik.com/umiYO

**Comment by gabrieltudose** [comment]
Hi,
Can anyone point me to some workaround or fix?

Thanks

**Comment by Dimitar-Goshev** [comment]
This issue is not reproducible since 2020.1.219 - https://dojo.telerik.com/@Dimitar-Goshev/uhuzunuR
