### ISSUE TITLE
Add DefaultContractResolver JSON options when creating Telerik MVC Core Project from VS

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/kendo-ui-core#2163]
Step 5 (AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver()) from the following article should be included in the Startup.cs file when creating Telerik UI Core Project from Visual Studio - https://docs.telerik.com/aspnet-core/getting-started/getting-started#configuration-Add

For example:
Startup.cs:
```
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddApplicationInsightsTelemetry(Configuration);

        services.AddMvc().AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());

        // Add Kendo UI services to the services container
        services.AddKendo();
    }
```

The omission of this line will break the Ajax binding (i.e., all data source fields will be serialized with lower case).

**Comment by Dimitar-Goshev** [comment]
This configuration is already added to Telerik UI for ASP.NET Core projects, created through Telerik VS Extension.
