### ISSUE TITLE
The Widget base variable does not change the base color in Fiori theme

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-ui-core#2168]
### Reproduction of the problem
1. Open http://demos.telerik.com/kendo-ui/themebuilder/
2. Choose Fiori skin
3. Change the "Widget base" color
### Current behavior

The color set through the Widget Base option does not change the look of the theme (like does in the other themes).
### Expected/desired behavior

The base color of the theme is changed depending on the chosen value.
### Environment
- **Kendo UI version:** 2016.3.914
- **Browser:** all

**Comment by TeyaVes** [comment]
no longer reproducible after latest theme builder commits in master
