### ISSUE TITLE
Unlink and PDF tools icons are missing from Kendo editor's toolbar

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#2169]
### Bug report

Unlink and PDF tools icons are missing in Kendo editor's toolbar

### Reproduction of the problem
The issue could be observed on the following demos:

- [http://demos.telerik.com/kendo-ui/editor/index](http://demos.telerik.com/kendo-ui/editor/index)
Click on any link to show the unlink tool on the toolbar
- [http://demos.telerik.com/kendo-ui/editor/pdf-export](http://demos.telerik.com/kendo-ui/editor/pdf-export) - Switch to material skin

### Current behavior
The tools icons are missing

### Expected/desired behavior
The tools icons are available

### Environment
Kendo UI version: 2016.3.914

**Comment by theOrlin** [comment]
Possible partial workaround is to add the following to the page styles:

        .k-i-unlink {
            background-position: -288px -72px;
        }
        .k-i-pdf {
            background-position: -288px -240px !important;
        }

Works in all themes but does not fix the broken icons in Office365. Needs more research.

**Comment by Jekata** [comment]
A sticky note has been created on the subject: http://www.telerik.com/forums/the-unlink-and-pdf-tools-icons-are-malformed-from-editor's-toolbar-in-r3-2016-(ver-2016-3-914)
