### ISSUE TITLE
Hovering the border of a middle table row causes hiding of the toolbar in inline editing

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-ui-core#2172]
### Bug report

Hovering the border of a middle table row causes hiding of the toolbar in inline editing

### Reproduction of the problem
1. Navigate to http://demos.telerik.com/kendo-ui/editor/inline-editing
2. In the first editor insert a table (5x5)
3. Select some text in order to popup the toolbar
4.  Hover the border between the rows

### Current behavior
The toolbar hides

### Expected/desired behavior
The toolbar should not hide

### Environment

* **Kendo UI version:** 2016.3.914

**Comment by Iankodj** [comment]
The same bug affects situation with a readonly editor: 

```
<textarea id="editor">
    <table>
      <tr>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
      </tr>
    </table>
</textarea>

<script>
    $("#editor").kendoEditor({
        
    });
    var editor = $("#editor").data("kendoEditor");
    $(editor.body).attr("contenteditable", false)
</script>
```

Hovering the table borders will re-enable the editing.
