### ISSUE TITLE
Can`t use kendo-ui-core with webpack. Get the following error

### ISSUE THREAD

**Issue by casufi** [telerik/kendo-ui-core#2174]
### Bug report

Can`t use kendo-ui-core with webpack. Get the following error

Error: The Kendo UI directives require jQuery to be available before AngularJS. Please include jquery before angular in the document.
### Reproduction of the problem

https://github.com/casufi/kendo-webpack-test.git
cd kendo-webpack-test
npm install

check the follwing files 
1) /client/app/app.js
2) /client/app/components/home/home.controller.js
3) /client/app/components/home/home.html

gulp serve
Open http://localhost:3000
- **Kendo UI version:** kendo-ui-core@2016.2.727
- **jQuery version:** jquery@2.2.4
- **Browser:** [all]

**Comment by underlog** [comment]
Did you check this thread - https://github.com/telerik/kendo-ui-core/issues/1932

**Comment by casufi** [comment]
Thank you the error is gone, but there is some problem with CSS. Should I include it separately in index.html ?

**Comment by zdravkov** [comment]
Yes - it should be added separately.
