### ISSUE TITLE
MultiSelect with virtualization behaves improperly after an item has been select and the input field or the item in the input field is clicked

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2175]
### Bug report
When used in virtualization scenario the MultiSelect calls at least 3 times its DataSource read action and in some cases multiple times the ValueMapper action. Clones of the selected items appear in the input field of the widget.

### Reproduction of the problem
Steps to reproduce:
* On the [Virtualization demo](http://demos.telerik.com/kendo-ui/multiselect/virtualization) remove all preselected items;
* Search for an item which is not loaded initially (it is not on the first page of the drop-down);
* Select that item;
* Click on the MultiSelect input field or the selected item in the input field.

Here is an image of the result (which also may deffer from the below):
![multiselectvirtualization](https://cloud.githubusercontent.com/assets/3431388/18589255/794a4f56-7c32-11e6-8d75-6deebe17f56f.png)

**Comment by dimodi** [comment]
related to https://github.com/telerik/kendo-ui-core/issues/2062

**Comment by arracos** [comment]
We've got a client deployment using this functionality at the beginning of November.  They're obviously very concerned that we have a fix a soon as possible.  As soon as we can get a development build for this fix I want to get my hands on it so that I can implement the fix into test and allow my testing team to try using the fix.  Thanks

**Comment by arracos** [comment]
Has there been any progress on this issue?  It's becoming critical for us to have some kind of resolution.  Even a dev build that addresses the issue would be helpful.

**Comment by ggkrustev** [comment]
We are working on this bug. We will try to release a fix for the upcoming service pack.
Please follow the Github issue for more details.

**Comment by arracos** [comment]
Thank you for the feedback.  I'll be looking forward to telling our client that we might have a resolution before we have to go live in the next few weeks.

**Comment by arracos** [comment]
Since the release date for the service pack has slipped to Oct 26, is there any chance we can get some kind of test build before then?  We're supposed to release to our client about a week after that.  I'd like some extra time for our internal testing.

**Comment by ggkrustev** [comment]
Once, we have a fix, most probably we will release it as internal build. I don't see any reason to wait for the service pack to publish the changes. Follow the thread for updates.

**Comment by ggkrustev** [comment]
@arracos We pushed a fix for the issue. It turned out to be more complex. We will test it for several days and most probably will release an internal build in the end of work week. Give it a try once it is out and let us snow whether the issue is still present.

**Comment by arracos** [comment]
@ggkrustev Do you know when a new internal build for Kendo Professional will be dropped?  I could pull down only the core but we're using grids in our client project.  It would be much easier to have a build including everything rather than piece together various bits from released/internal code.

**Comment by ggkrustev** [comment]
@arracos I am afraid that we had technical difficulties with the internal build process. We will release service pack directly instead. It should be live in a couple of days.
