### ISSUE TITLE
Add information for the scrollable Grid in the documentation.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2180]
If the Grid is scrollable it cannot be zoomed because the misalignment will occur.

**Comment by simonssspirit** [comment]
Workaround:
Add the following code on the resize event of the window element:

`$('.k-grid').data('kendoGrid').thead.closest(".k-grid-header").css("padding-right", kendo.support.scrollbar(true))`

**Comment by simonssspirit** [comment]
The workaround is added in the documentation:

http://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance#adjust-grid-layout-on-page-zoom

commit: [4a8d2fd](https://github.com/telerik/kendo-ui-core/commit/4a8d2fde80fa3328c6a337422f41e43e096c30e6)

**Comment by ashutosh-kendurkar** [comment]
> Workaround: Add the following code on the resize event of the window element:
> 
> `$('.k-grid').data('kendoGrid').thead.closest(".k-grid-header").css("padding-right", kendo.support.scrollbar(true))`

It appears that kendo.support.scrollbar(true) considers standard scrollbar width, it fails in case of firefox thin scrollbar, it should return 10px instead of 17px.
