### ISSUE TITLE
The folder icon is missing in Kendo editor File Browser dialog

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#2181]
### Bug report

The folder/file icon is missing in Kendo editor File Browser dialog. The issue has been introduced with the effort on unifying the rendering and class names for icons.

### Reproduction of the problem
The issue could be observed on the following demo:

[http://demos.telerik.com/kendo-ui/editor/imagebrowser](http://demos.telerik.com/kendo-ui/editor/imagebrowser)
Open the File/Image Browser

### Current behavior
The folder/file icon is missing

### Expected/desired behavior
The folder/file icon is available

### Environment

* **Kendo UI version:** 2016.3.914

### Workaround 
Add the following to the page styles:

		.k-filebrowser .k-i-file {
			height: 80px;
			width: 80px;
		}
		.k-filebrowser .k-i-file {
			height: 80px;
			width: 80px;
		}
		.k-i-file {
			background-color: #fff;
			border-color: #d5d5d5;
		}
		.k-i-file {
			border-style: solid;
			border-width: 0 0 1px;
			padding: 0.65em 0.17em 0.65em 1em;
		}
		.k-dropzone, .k-i-file {
			position: relative;
		}
		.k-i-file {
			background-color: #fff;
			border-color: #e8e8e8;
		}  
		.k-i-file {
			background-color: #fff;
			border-color: #e8e8e8;
		}
		.k-i-file {
			border-style: solid;
			border-width: 0 0 1px;
			padding: 0.65em 0.17em 0.65em 1em;
		}
		.k-dropzone, .k-i-file {
			position: relative;
		}
		
		.k-filebrowser .k-i-folder {
			background-position: 0 -200px;
			background-repeat: no-repeat;
			height: 80px;
			width: 80px;
		}
		
		.k-filebrowser .k-folder {
			background-position: 0 -200px;
			background-repeat: no-repeat;
			height: 80px;
			width: 80px;
		}
		:root * > .k-button-group .k-tool-icon, *:root * > .k-icon, *:root * > .k-sprite {
			vertical-align: middle;
		}
		.k-filebrowser .k-folder {
			background-position: 0 -200px;
			background-repeat: no-repeat;
			height: 80px;
			width: 80px;
		}
		:root * > .k-icon, *:root * > .k-sprite, *:root * > .k-tool-icon {
			vertical-align: middle;
		}

**Comment by ericvb** [comment]
This topic is closed, but how to detect in which package it is corrected?
If I check the demo link http://demos.telerik.com/kendo-ui/editor/imagebrowser, the problem is still there.

I've just updated the Telerik UI for ASP.NET MVC to version v2016.3.1118, but don't find the given gitnumber in the release notes. So I conclude from there that the correction is not in this release.
But which release then?
