### ISSUE TITLE
Dialog is blurred Chrome/Chrome OSX, IE, Opera

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2182]
### Bug report

Reported in ticket ID  #1062971
### Reproduction of the problem

Official [Dialog demo](http://demos.telerik.com/kendo-ui/dialog/predefined-dialogs)
### Current behaviour

The widget is blurred along with the content inside, due to the transitions
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** 1.9.1
- **Browser:** [Chrome OSX,Windows - Chrome/IE/Opera ]

**Comment by Dimitar-Goshev** [comment]
The issue used to be as follows:
![image](https://user-images.githubusercontent.com/6614183/35965838-c38f075e-0cc4-11e8-8fc1-971e4de98459.png)

It is no longer reproducible with latest R1 2018, so I am closing it.
