### ISSUE TITLE
Scheduler should trigger change on Surface in Chrome

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2184]
### Current behavior

Scheduler does not trigger change event in **Chrome** on Surface and Dell Vue 11 Pro. 
Firefox, IE, Edge work as expected.
### Research/Enhancement

[Issues with Touch events](https://docs.google.com/document/d/12-HPlSIF7-ISY8TQHtuQ3IqDi-isZVI0Yzv5zwl90VU/edit#)
[Input device capabilities Google article](https://developers.google.com/web/updates/2015/10/inputdevicecapabilities)
[Input device capabilities Draft Community Group Report 02 August 2016](https://wicg.github.io/InputDeviceCapabilities/)
### Environment

Surface
- **Browser:** [Mobile Chrome - Surface]

**Comment by anuragsinghtomar** [comment]
Do we have any update on this. When we expect this change

**Comment by jivanova** [comment]
Currently, we are working on improving the Scheduler functionality under touch devices. We are planning to include a fix in R2 2018.

Fix included in [Issue](https://github.com/telerik/kendo/issues/5653) .
