### ISSUE TITLE
Dialog with zoom:in animation is not centered

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/kendo-ui-core#2191]
Dialog with zoom:in animation is not centered.
Steps to reproduce:
1) Open this dojo - http://dojo.telerik.com/AjIRa
2) Open the dialog by clicking the button.
3) Actual - the dialog is not centered - http://screencast.com/t/ynsO7CCt
4) Remove the animation and reopen the dialog - the dialog is centered

**Comment by nenchef** [comment]
Already fixed with version 2019.1.115
