### ISSUE TITLE
Pie Chart labels may be rendered outside the visible area

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2192]
### Bug report

The SVG group element is larger than the chart element which results in labels being cut off occasionally
### Reproduction of the problem

<img src="http://i66.tinypic.com/invqlh.png" border="0" alt="Image and video hosting by TinyPic">
### Current behavior

Unless the element css is altered, the chart does not resize
Dojo: [link](http://dojo.telerik.com/IripU)
### Expected/desired behavior

The size to be equal

**Comment by tsvetomir** [comment]
A possible workaround for the moment is to set the [labels.distance](http://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart#configuration-series.labels.distance) to a smaller value, e.g. 15

**Comment by danielkaradachki** [comment]
increasing the [padding](http://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart#configuration-series.padding) is also an option.

**Comment by Alex-Bubblemaster** [comment]
Also reported in 1425571. Raising priority.

**Comment by Alex-Bubblemaster** [comment]
Reported in 1451472. Raising priority.

**Comment by tsvetomir** [comment]
Fixed via the new [autoFit](https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart/configuration/series.autofit) option.
