### ISSUE TITLE
Wrong notification error color in BlueOpal theme

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-ui-core#2196]
### Bug report
Notification error color in BlueOpal theme is wrong. Reported in ticket: 1063246.

### Reproduction of the problem
Can be observed here: [http://demos.telerik.com/kendo-ui/notification/index]. Set theme BlueOpal theme and click the first button

### Expected/desired behavior
The text should be readable.

### Environment

* **Kendo UI version:** 2016.3.914/
* **jQuery version:** 2016.3.914/
* **Browser:** [all ]

**Comment by jlchereau** [comment]
Also try Default, Silver, Uniform, ... which are affected by the same disease.
