### ISSUE TITLE
Displaced DropDownList dropdown on Android, when the page is scrolled down

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#2197]
### Bug report
Displaced DropDownList dropdown on Android, when the page is scrolled down.
(Not reproducible on iOS Safari)
Regression since R3 2016 (2016.3.914)

### Reproduction of the problem
1. Use the following Dojo - [http://dojo.telerik.com/oWena/4](http://dojo.telerik.com/oWena/4)
2. Open it in Full screen [http://runner.telerik.io/fullscreen/oWena/4](http://runner.telerik.io/fullscreen/oWena/4) and open that URL with Android Chrome or in Chrome emulator with an emulated Android device, e.g. Nexus 5X.
3. Tap on the DropDownList - its dropdown is rendered right below it.
4. Scroll down the page.
5. Tap on the DropDownList.

### Current behavior
The dropdown is displaced upwards - [screenshot](http://screencast.com/t/QAnM6llAjHrZ)

### Expected/desired behavior
The dropdown is rendered right below the DropDownList - reproducible with earlier versions.

### Environment

* **Kendo UI version:** 2016.3.914
* **Browser:** [Mobile Chrome 52.0.2743.98]

**Comment by nzacca** [comment]
The following commit seems related to/consistent with the behavior described: https://github.com/telerik/kendo-ui-core/commit/0f9af9a0500e2835eab409123aed316297524e81

Removing it fixes the issue I am experiencing.

**Comment by tsvetomir** [comment]
cc @ggkrustev

**Comment by ggkrustev** [comment]
I suppose this issue is similar to this one #2266

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket ID 1069665
