### ISSUE TITLE
JS error "Maximum call stack size exceeded" when trying to import a certain type of file

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#2198]
### Reproduction of the problem
http://demos.telerik.com/kendo-ui/spreadsheet/server-side-import-export 

Upload the file from this [issue](https://github.com/telerik/kendo/issues/6159)

### Current behavior
JS error "Maximum call stack size exceeded" is observed and the file is not imported successfully

### Expected/desired behavior
The file is imported without errors

### Environment

* **Kendo UI version:**"2016.3.914"
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mishoo** [comment]
No reasonable workaround is possible at the moment.  The dependencies between formulas in the linked sheet are just too nested.
