### ISSUE TITLE
Virtualized MultiSelect does not fire a change event on first item selection with jQuery version 3*.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2204]
### Bug report

Virtualized MultiSelect does not fire a change event on first item selection with jQuery version 3*.

### Reproduction of the problem

The issue can be reproduced in the following Dojo: http://dojo.telerik.com/uHeyu.
Select one item and notice that the change event is not fired. Then select second item and notice that the e.sender.value() is returning only the first selected value.

### Environment

* **Browser:** all

**Comment by ggkrustev** [comment]
Fixed with https://github.com/telerik/kendo-ui-core/issues/2250
