### ISSUE TITLE
Scheduler's Export PDF button is not rendered (mobile: phone)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2206]
### Bug report

The Export PDF button is not rendered when the Scheduler's **mobile** property is set to "phone". When mobile is set to "tablet" the button is rendered as expected.  
### Reproduction of the problem

Set: 
toolbar: ["pdf"],
mobile: "phone",

As a workaround a custom button  can be added to the Scheduler's toolbar:

``` JavaScript
$(document).ready(function () {
    var scheduler = $("#scheduler").data("kendoScheduler");

    var button = $("<button id='export' class='k-button k-my-button'>Export PDF</button>");

    $(scheduler.toolbar[0]).prepend(button);

    $("#export").click(function (e) {
        scheduler.saveAsPDF();
    });
});
```
### Current behavior

No Export PDF button is rendered.
### Expected/desired behavior

Export PDF button should be rendered as in mobile: "tablet" mode. 
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** x.y
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Iankodj** [comment]
Layout will be additionally handled: https://github.com/telerik/kendo-ui-core/issues/3579
