### ISSUE TITLE
Wrong typescript definition for kendo.ui.Widget.Upload

### ISSUE THREAD

**Issue by XavierDupessey** [telerik/kendo-ui-core#2208]
kando.all.d.ts contains wrong definitions for kendo.ui.Widget.Upload. For example: `getFiles(): void;`
It should return an array of something...

That generates typescript errors `Type 'void' is not assignable to type ...`

Kendo UI version: 2016.3.914 (pro)

**Comment by tsvetomir** [comment]
@Raisolution the [method declarations](http://docs.telerik.com/kendo-ui/api/javascript/ui/upload#methods-clearFile) in the API reference are missing a return type ([sample](http://docs.telerik.com/kendo-ui/api/javascript/ui/progressbar#methods-value)).

The problem should be solved once we fix this.

**Comment by Raisolution** [comment]
The documentation for [getFiles](http://docs.telerik.com/kendo-ui/api/javascript/ui/upload#methods-getFiles) has been updated, which also fixes the TypeScript definitions.
