### ISSUE TITLE
NumericTextBox title not updating

### ISSUE THREAD

**Issue by MLefebvreICO** [telerik/kendo-ui-core#2209]
### Reproduction of the problem

1. Go on http://dojo.telerik.com/IQEkA
2. Enter `1` in the numericTextBox and leave the field (click elsewhere)
3. MouseOver the input, it will say `$1`
4. Change the value to `2` and leave the field
5. MouseOver the input, it still says `$1`

### Current behavior
The input title is not changed when the `numericTextBox` value is updated

### Expected/desired behavior
The input title should change when the `numericTextBox` value is updated

### Environment

* **Kendo UI version:** 2016.3.914 (pro)
* **jQuery version:** 2.1.4
* **Browser:** all

**Comment by parthsw** [comment]
Has it been fixed because I have been facing similar sort of issue in one of my application ?

**Comment by ag-petrov** [comment]
Indeed the problem was fixed and the issue is closed. If you still experience the same problem I suggest providing a dojo example which illustrates it.
