### ISSUE TITLE
Typo in styles/web/common/notification.less -> no margin for error notification icon

### ISSUE THREAD

**Issue by Rico-K** [telerik/kendo-ui-core#2210]
### Bug report
The following line contains a typo:
https://github.com/telerik/kendo-ui-core/blob/master/styles/web/common/notification.less#L20

The last part of that line should be **k-i-error** instead of **k-i-erorr**.

### Reproduction of the problem
Look at the error notification on any theme on http://demos.telerik.com/kendo-ui/themebuilder/ . The margin between the !-icon and the text of the notification is missing for the error notification.

### Current behavior
No margin between !-icon and error notification text.

### Expected/desired behavior
4px margin between !-icon and error notification text like for the information, success or warning notifications

### Environment

* **Kendo UI version:** 2016.3.914
* **Browser:** [all]

**Comment by inikolova** [comment]
This issue has been already resolved -> https://github.com/telerik/kendo-ui-core/commit/6902ed4d1d4921587ada187db1884817cb38f372
