### ISSUE TITLE
Add Scheduler recurrence editor missing messages in API 

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2211]
- messages.recurrenceEditor.cancel
- messages.recurrenceEditor.update
- messages.recurrenceEditor.endTitle
- messages.recurrenceEditor.repeatTitle
- messages.recurrenceEditor.headerTitle

**Comment by Dimitar-Goshev** [comment]
The messages are added. We may further enhance their description as I mentioned in the PR. Moving it to Done. We should close it once we merge the fixes branch.
