### ISSUE TITLE
k-overlay and k-notification-wrap both have z-index===10002

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#2212]
### Bug report

When our app displays a kendo.ui.Dialog with a background overlay, kendo.ui.Notification are no more visible (displayed below the overlay).
### Reproduction of the problem

![image](https://cloud.githubusercontent.com/assets/2556751/18809837/c9b9e418-827e-11e6-957c-9b1ccafda88f.png)
### Expected/desired behavior

k-overlay and k-notification-wrap both have z-index===10002
k-notification-wrap should have a higher z-index (also higher than windows and dialogs).
### Environment
- **Kendo UI version:** 2016.3.914

**Comment by jlchereau** [comment]
Suggested fix:

Replace at https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.notification.js#L250

```
popup.wrapper.addClass(that._guid).css(extend({margin:0}, that._popupPaddings));
```

with

```
popup.wrapper.addClass(that._guid).css(extend({margin:0,zIndex:10050}, that._popupPaddings));
```

**Result**:

![image](https://cloud.githubusercontent.com/assets/2556751/19000901/eab8ace0-873c-11e6-85e3-a694b244f7f8.png)

**Comment by jlchereau** [comment]
Any chance this one gets a milestone?

**Comment by inikolova** [comment]
I considered the issue and believe there are valid scenarios for both cases:

- _Notification above dialog_ - global notification, which should be visible everywhere in the application;

- _Dialog above notification_ - local notification, visible only in a particular context. 

Therefore I would suggest the following approach: 

- Set some class name to the notification wrapper;

-Set z-index to the notification wrapper via CSS. 

For your convenience I prepared an example: http://dojo.telerik.com/@Iliana/uJaru

**Comment by jlchereau** [comment]
Thank you, but I do not think there is any valid use case for having a notification showing and not being able to read it because it is (partially) covered. In other words, having a local notification triggered when the context is (partially) covered (i.e. context has changed) should not occur and if this is the case, the developer probably did something wrong.

And assuming one would need both, the default should be an always visible notification with the possibility for the developer to implement more complex scenarios through code.

**Comment by gyoshev** [comment]
After discussing this in more detail, we concluded that this problem should be fixed. Local notifications can be achieved via the `appendTo` configuration option of the notification widget, and global notifications should be above the dialog.

In order to fix this properly, we would need to have a stacking order implementation shared between all components. However at the time being it appears that raising the notification z-index is sufficient to handle this scenario. Thank you for your contribution.
