### ISSUE TITLE
Radiobuttons and checkboxes misaligned with their labels in all themes

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#2213]
### Reproduction of the problem
this can be seen on all themes, on all browsers - [here](http://demos.telerik.com/kendo-ui/themebuilder/) please loop over the themes to see it in full. 

### Expected/desired behavior
Radiobuttons and checkboxes should be aligned with their labels.

### Environment

* **Kendo UI version:** 2016.3.914
* **jQuery version:** All
* **Browser:** All

**Comment by inikolova** [comment]
Everything looks OK now
