### ISSUE TITLE
When the selection is in the begging of a non first list item and backspace is clicked, its content should be moved to the the previous one.

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#2214]
### Reproduction of the problem

Sample target - official Kendo Editor Demo: [http://demos.telerik.com/kendo-ui/editor/index](http://demos.telerik.com/kendo-ui/editor/index)
1. set cursor before a word in bulleted list
2. press backspace to delete a bullet
3. press backspace to delete a bullet
### Expected/desired behavior

The cursor should always go to a previous line/item after the backspace key is pressed.
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** All
- **Browser:** All

**Comment by danail-vasilev** [comment]
Two related issues:
1) Open http://demos.telerik.com/kendo-ui/editor/index
2) Select the first bullet item.
3) Click 3 times the back space:
Actual:
   - In IE11 - A JavaScript error is thrown - http://screencast.com/t/AgIeoYk9
   - In Chrome the cursor goes to the end of the page - http://screencast.com/t/hdkxY7P8rho
