### ISSUE TITLE
Hyperlink is not underlined by default

### ISSUE THREAD

**Issue by ivanchev** [telerik/kendo-ui-core#2219]
When inserting a hyperlink into an empty cell, it should be underlined, but it's currently not.

Can be observed here:
http://dojo.telerik.com/EQeKO

* **Kendo UI version:** 2016.3.914
* **Browser:** all

**Comment by yordanov** [comment]
Underline action should be triggered by default:

![underline](https://cloud.githubusercontent.com/assets/1118895/18865100/3327811a-84a2-11e6-8c46-1f6582752228.png)

**Comment by mishoo** [comment]
I'm OK with setting Underline on when a link is added through the dialog, but I don't think we should do that when the spreadsheet is initialized from JSON (which the example does).
