### ISSUE TITLE
Using k-rebind to add new tab to a tab strip 

### ISSUE THREAD

**Issue by jayanthakgjls** [telerik/kendo-ui-core#222]
I'm using k-rebind to add new tab to a kendo tab strip.

`<div kendo-tab-strip="" k-rebind="tabs.length">`

But instead of adding new tab it renders the initial tab two times more.. Seems like desired output since kendo-angular simply recompile the content which already there . But I can't use a Datasource to create tabs because  I need to have a custom template for the tab header.

Here is the [Dojo](http://dojo.telerik.com/EHiR/3)

**Comment by mohsincitiustech** [comment]
Hey can you share your code on jsfiddler?

**Comment by jayanthakgjls** [comment]
I sent them a mail , let's see .

On Fri, Feb 20, 2015 at 6:13 PM, mohsincitiustech <notifications@github.com>
wrote:

> Hey can you share your code on jsfiddler?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telerik/kendo-ui-core/issues/222#issuecomment-75232318>
> .
>



-- 
Thanks & Regards,
Jayantha lal,
Associate Tech Lead  | 99X Technology <http://www.99xtechnology.com/>
Skype: Jayantha.lal
Blog <http://codetuner.blogspot.com/>| LinkedIn
<http://www.linkedin.com/in/jayanthalal>| StackOverflow
<http://stackoverflow.com/users/590278/jayantha>
