### ISSUE TITLE
Widget raises `select` event on blur

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#2220]
### Bug report

Widget triggers `select` event on blur explicitly.
### Reproduction of the problem
1. http://dojo.telerik.com/UJubi
2. Select new item
3. Blur

Notice that the `select` is triggered on blur even though it shouldn't.
### Expected/desired behavior

Trigger the `select` event only when a new item is selected.
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** 1.9.3
- **Browser:** all

**Comment by ggkrustev** [comment]
Reported in TicketID: 1064459

**Comment by boyandim** [comment]
The issue can be reproduced with the following [http://dojo.telerik.com/UqevO](http://dojo.telerik.com/UqevO) example. It is tested against 2016.3.1118 version.
