### ISSUE TITLE
AutoComplete, MultiSelect and ComboBox clearButton option can not be set via setOptions()

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2222]
### Bug report

AutoComplete and ComboBox clearButton option cannot be set via setOptions()
### Reproduction of the problem

[http://dojo.telerik.com/ijUYA](http://dojo.telerik.com/ijUYA)
### Expected/desired behavior

The clearButton option can be modified via setOptions()
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** x.y
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by zdravkov** [comment]
Could not replicate it with the latest version.

**Comment by zdravkov** [comment]
It is also reproduced in MultiSelect - here is the updated [dojo](http://dojo.telerik.com/@zdravkov/EgEHaK).
