### ISSUE TITLE
Dropdown position incorrectly calculated on mobile devices when bootstrap.css is loaded 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2223]
### Bug report

On mobile devices when bootstrap's css is referenced on the page and the page is scrolled down occasionally the dropdown's position is calculated incorrectly on page refresh: 

### Reproduction of the problem

Can be reproduced in Chrome's mobile device emulator: [screencast](http://screencast.com/t/bJ7ACoPKkJ).

Sample [dojo](http://dojo.telerik.com/otOWI/3).

Also reproducible with other widgets that have dropdowns:
AutoComplete
ColorPicker
ComboBox
DatePicker
DateTimePicker
MultiSelect
TimePicker
Grid - the filter popup

### Current behavior
Incorrect dropdown position.

### Expected/desired behavior
Correct dropdown position. 

### Environment

* **Kendo UI version:** 2016.3.914
* **jQuery version:** x.y
* **Browser:** [ Mobile Chrome XX  ]

**Comment by inikolova** [comment]
This issue can be reproduced without Bootstrap, too - [http://dojo.telerik.com/@Iliana/ebUpa](url)

**Comment by Alex-Bubblemaster** [comment]
The issue is reproducible without bootstrap in v2016.3.914.  [Dojo](http://runner.telerik.io/fullscreen/aJIjI)
It must be related to the script updates and #2197 & #2266 as it works as expected with v.2016.2.714
