### ISSUE TITLE
Inconsistent behaviour of the Draggable in different browsers when the autoScroll is active.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2227]
### Bug report

Inconsistent behaviour of the Draggable in different browsers when the **autoScroll** is active. When the element is dragged to the right side of the page, the content of the page is pushed to the left side and disappears. This occurs only in Chrome. 
### Reproduction of the problem

The issue can be reproduced in the following Dojo: http://dojo.telerik.com/oYIqa.
### Environment
- **Kendo UI version:** 2015.3.1111 and newer.
- **Browser:** Chrome

**Comment by dmanova** [comment]
Doesn't seem to be reproducible anymore.
