### ISSUE TITLE
Scheduler view() method's typescript definition returns void 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2228]
### Bug report

In the typescript definitions the view() method returns void: view(type?: string): void;
### Current behavior

returns void
### Expected/desired behavior

should return the view object
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** x.y
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by zdravkov** [comment]
Duplicates this issue #2924
