### ISSUE TITLE
The layout of the last Kendo UI Diagram for ASP.NET MVC on the page overrides the others

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/kendo-ui-core#2231]
The layout of the last Kendo UI Diagram for ASP.NET MVC on the page overrides the others.

Steps to reproduce:
1) Run the code below.
Actual - http://screencast.com/t/VcJeLa0gMJC
Expected - http://screencast.com/t/ObyKaYvxO

CSHTML:
@(Html.Kendo().Diagram()
    .Name("diagram")
    .DataSource(dataSource => dataSource
        .Read(read => read.Action("_DiagramTree", "Diagram")).Model(m => m.Children("Items"))
    )
    //.Events(e=>e.DataBound("onDataBound"))
    .Layout(l => l
        .Type(DiagramLayoutType.Tree)
        .Subtype(DiagramLayoutSubtype.Down)
        .HorizontalSeparation(30)
        .VerticalSeparation(20)
    )
    .ShapeDefaults(sd => sd
        .Width(40)
        .Height(40)
    )
)

@(Html.Kendo().Diagram()
    .Name("diagram2")
    .DataSource(dataSource => dataSource
        .Read(read => read.Action("_DiagramTree", "Diagram")).Model(m => m.Children("Items"))
    )
    .Layout(l => l
        .Type(DiagramLayoutType.Tree)
        .Subtype(DiagramLayoutSubtype.Right)
        .HorizontalSeparation(130)
        .VerticalSeparation(20)
    )
    .ShapeDefaults(sd => sd
        .Width(40)
        .Height(40)
    )
)

Workaround:
Handle the the dataBound event of the previous diagram and reset the layout
    function onDataBound(e) {
        e.sender.layout({
            type: "tree",
            subtype: "down"
        });
    }
Note: The diagram serialization is fine. The issue is not reproducible with the serialized JavaScript in a dojo sample - http://dojo.telerik.com/aRuSE

Issue is caused by this line - https://github.com/telerik/kendo/blob/master/src/dataviz/diagram/dom.js#L3384

**Comment by gyankov** [comment]
No longer replicates in 2021 R2.
