### ISSUE TITLE
TreeView's expand/collapse state is inverted after e.preventDefault() on collapse

### ISSUE THREAD

**Issue by rmorrise** [telerik/kendo-ui-core#2235]
### Reproduction of the problem

http://dojo.telerik.com/Aloza/17
### Current behavior

In the TreeView, when e.preventDefault() is triggered on a 'collapse' event, the following attempt to collapse causes an 'expand' animation, instead.
1. Click "foo" to expand. The tree expands.
2. Click "foo" to collapse. The tree collapse is prevented, as expected, and the console message is shown.
3. Click "foo" to collapse again. The "expand" animation is shown instead of the "collapse" animation, and the tree remains expanded.
### Expected/desired behavior

If the collapse event is not prevented, the tree node should collapse when clicked.
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** jquery-1.9.1
- **Browser:** Chrome 52.0.2743.82 m (64-bit)

**Comment by IvanDanchev** [comment]
after the collapse event is prevented clicking the node's arrow triggers the expand event instead of triggering the collapse event. The node's attributes are also updated even though the collapse event has been prevented: [dojo](https://dojo.telerik.com/ESEhiD) example.
