### ISSUE TITLE
The Grid' Excel export is not working with some jQuery versions when the latest Kendo UI version(2016.3.914) is used.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2239]
### Bug report

The Grid' Excel export is not working with some jQuery versions.

Not working: 1.9.1. , 1.10.1, 2.1.4.

Working: 1.12.1, 2.2.4

### Reproduction of the problem

The issue can be reproduced in our demos: http://docs.telerik.com/kendo-ui/controls/data-management/grid/excel-export

### Environment

* **Kendo UI version:** 2016.3.914
* **jQuery version:** 1.9.1, 2.1.4
* **Browser:** all 
The Grid' Excel export is not working with some jQuery versions when the latest Kendo UI version(2016.3.914) is used.

**Comment by KirilNN** [comment]
It does not work with 2.1.3 as well:


http://dojo.telerik.com/ICEdI

**Comment by Alex-Bubblemaster** [comment]
Not working with 2.1.1 as reported in ticket ID 1069101
http://dojo.telerik.com/uRUPe

**Comment by tsvetomir** [comment]
The issue didn't land in 2016.3.1028 (SP1) due to a technical glitch. It'll be available in builds versioned 2016.3.1102 and later (internal builds).

Apologies for the caused inconvenience.

**Comment by phunik** [comment]
It works with:
Kendo UI version: Kendo UI v2016.2.714
jQuery JavaScript Library v1.12.3
JSZip.min ....
