### ISSUE TITLE
Misaligned PDF icon in Export to PDF button

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-ui-core#2243]
### Reproduction of the problem
`.k-i-pdf` icon has wrong background-position in normal state. The issue can be oserved with all themes in [this demo](http://demos.telerik.com/kendo-ui/grid/pdf-export).

### Environment

* **Kendo UI version:** 2016.3.914
* **Browser:** all

**Comment by inikolova** [comment]
This issue has beel already addressed: https://github.com/telerik/kendo/commit/0a428857603029d67945e7929f731f94c5a1f18c
