### ISSUE TITLE
Remove or fix demos for JSP and PHP wrappers

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2244]
Remove or fix the following demos for the PHP and JSP wrappers. Their source code is missing:

**PHP**:

http://demos.telerik.com/php-ui/spreadsheet/server-side-import-export
http://demos.telerik.com/php-ui/spreadsheet/server-side-pdf-export
http://demos.telerik.com/php-ui/spreadsheet/datasource
http://demos.telerik.com/php-ui/spreadsheet/custom-editors

**JSP**:

http://demos.telerik.com/jsp-ui/spreadsheet/server-side-import-export
http://demos.telerik.com/jsp-ui/spreadsheet/server-side-pdf-export
http://demos.telerik.com/jsp-ui/spreadsheet/datasource
http://demos.telerik.com/jsp-ui/spreadsheet/custom-editors

**Comment by Dimitar-Goshev** [comment]
Demos will be removed.
