### ISSUE TITLE
Incorrect ToolBar keyboard navigation when resizable is set to false 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2248]
### Bug report

When the resizable property is set to "false" navigating through the ToolBar's items with Shift + Tab does not work correctly: the navigation stops unexpectedly and the user is not able to navigate through all of the items.  
### Reproduction of the problem

Sample [dojo](http://dojo.telerik.com/oXuRe). 
1. Focus the first ToolBar and navigate to Button4 by pressing Tab.
2. Navigate backwards by pressing Shift + Tab.
3. Expected: all items up to Button1 are navigated, actual: the navigation stops at Button2
### Current behavior

Shift + Tab does not navigate through all ToolBar items. 
### Expected/desired behavior

All items can be navigated through by pressing Shift + Tab. 
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** x.y
- **Browser:** [all ]

**Comment by richmag** [comment]
Great, thank you @jivanova !
