### ISSUE TITLE
ResponsivePanel does not work in IE 9

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2254]
### Bug report
ResponsivePanel does not work in IE 9

### Reproduction of the problem
Could be observed on the [Demo page](http://demos.telerik.com/kendo-ui/responsive-panel/index)

**Comment by inikolova** [comment]
Kendo UI ResponsivePanel relies on CSS3 media queries, however they are not supported in IE under 9.  This means that Kendo UI ResponsivePanel does not support IE 7 and IE 8.
