### ISSUE TITLE
Add ability to define the minimal column width during resizing

### ISSUE THREAD

**Issue by rkonstantinov** [telerik/kendo-ui-core#2259]

**Comment by IT-CASADO** [comment]
I'm waiting long for this sorely missing feature. Unfortunately this feature is in my opinion incomplete. 
I often have one or more columns with a * width. Then this columns use all additional available space (often text columns with larger text). The negative side of this is, that if the parent container is to small, this columns are invisible. My hope was, that the implementation of a min-width property solves this problem. But it doesn't :(
