### ISSUE TITLE
Not rendered scripts for Deferred widgets inside TabStrip and Splitter

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2261]
### Reproduction of the problem

It is reproduced only in ASP.NET MVC Core. Not reproducible in ASP.NET MVC5.

[Deferred widgets inside splitter does not render scripts anywhere.zip](https://github.com/telerik/kendo-ui-core/files/511421/Deferred.widgets.inside.splitter.does.not.render.scripts.anywhere.zip)

Screenshot of browser: http://screencast.com/t/F0p2kBHMjDds
### Expected/desired behavior

The scripts for the widgets inside the Splitter should be rendered along the scripts for the Splitter.

**Comment by pepinho24** [comment]
The same behavior is observed also in TabStrip and PanelBar

**Comment by twurm** [comment]
Any update on when this will be addressed?  This is preventing us from moving our ASP.net Core app intro production.

**Comment by eeasss** [comment]
We will try to get it addressed for the R1 2017 release (mid January)

**Comment by twurm** [comment]
Is this still something you are planning to address?  Its been 6 months and still nothing.

**Comment by twurm** [comment]
So going on 10.5 months now and no progress, any thoughts on when this will be finally fixed?

**Comment by Dimitar-Goshev** [comment]
The issue is fixed for TabStrip and Splitter. It is still valid for PanelBar and I logged it as a separate issue: https://github.com/telerik/kendo-ui-core/issues/3677
