### ISSUE TITLE
Fix the negative format string in kendo.format() is not properly applied

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/kendo-ui-core#2262]
Fix the negative format string in kendo.format() is not properly applied.
For example: kendo.format('{0:$#,###,##0.00;($#,###,##0.00)}',-1200)
actual - ($1200.00)
expected - ($1,200.00)
The issue is reproducible with this dojo sample - http://dojo.telerik.com/utIMu/13

**Comment by danail-vasilev** [comment]
The issue is related to this one - https://github.com/telerik/kendo-ui-core/issues/1645

**Comment by ggkrustev** [comment]
Related to https://github.com/telerik/kendo-ui-core/issues/2681.
Will close leaving the newest one.
