### ISSUE TITLE
Wrong typescript definition for kendo.ui.UploadFile

### ISSUE THREAD

**Issue by XavierDupessey** [telerik/kendo-ui-core#2265]
Some properties of kendo.ui.UploadFile are missing in kando.all.d.ts:

    interface UploadFile {
        extension?: string;
        name?: string;
        size?: number;
    }

should also have `uid?: string` and `rawFile: File` because they also can  be useful outside kendo...

That generates typescript errors: `Property 'uid' does not exist on type 'UploadFile'` and `Property 'rawFile' does not exist on type 'UploadFile'`.

Kendo UI version: 2016.3.914 (pro)

**Comment by Raisolution** [comment]
The UploadFile interface represents the [files](http://docs.telerik.com/kendo-ui/api/javascript/ui/upload#configuration-files) configuration option i.e. the initially selected files in the widget. An UploadFile[] files array should not be passed as a parameter to the Upload widget event handlers, which is now fixed.
