### ISSUE TITLE
Spreadsheet trows error in IE 11, when value is pasted (Ctrl+V) in an activated cell

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2268]
### Bug report
Spreadsheet trows error in IE 11, when value is pasted (Ctrl+V) in an activated cell. The error reports: "Unable to get property 'getData' of undefined or null reference"

This bug is a **regression**. It cannot be observed in R2 2016 607, but it is present in R2 2016 714 and R3 2016 914

### Reproduction of the problem
Steps to reproduce:
- Open the [Index demo](https://demos.telerik.com/kendo-ui/spreadsheet/index) in IE 11;
- Double click on a cell to activate it;
- Press Ctrl+V to paste value;
- The error can be seen on the console;

### Environment

* **Kendo UI version:** 2016.2.714 and 2016.3.914
* **Browser:** [ IE 11 ]

**Comment by mishoo** [comment]
Seems I introduced it in telerik/kendo@73c6d3bf14b476026a95055ecf9fe5ea393f8733.
