### ISSUE TITLE
DST recurring event is not rendered correctly, when Scheduler and events are in different timezones

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2271]
Settings to reproduce the issue:
Set timezone of scheduler to some zone that doesn't have DST (UTC for example) and the timezone of the events to some zone with DST (or just adjust your local machine timezone)("Europe/Sofia" for example)

1) Create recurring event before Local timezone (e.g. Sofia) DST in Scheduler without timezone set.

"Start": "2015-03-21T03:00:00",
"End": "2015-03-21T04:00:00",
"RecurrenceRule": "FREQ=DAILY",

2) The event is rendered incorrectly after the DST:
Before:
![image](https://cloud.githubusercontent.com/assets/2195951/9543934/7fdfe664-4d85-11e5-9591-97e61f7cc7ec.png)
After:
![image](https://cloud.githubusercontent.com/assets/2195951/9543960/c0ed272a-4d85-11e5-9163-52eb89dfcea5.png)

**Comment by pepinho24** [comment]
Another use case reported in: Ticket ID: 1066828

**Comment by deddu** [comment]
Any update? This is pretty mission critical for us.

**Comment by Dimitar-Goshev** [comment]
When only Scheduler timezone is set, the occurrences should not be shifted, as explained in the following [help article](http://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/timezones#configuration). Thus, if UTC is set for the Scheduler and no timezone is defined for events, every user will see events in UTC time, no matter what the local time of the user is. As a result, there would be no shifting in recurring appointment appearance, as all occurrences would be displayed in UTC.

Recurring events occurrences are expected to be shifted, if the timezone of the Scheduler and the start or end timezone of the event have different DST. When the Scheduler Timezone is Etc/UTC and the events startTimezone is Europe/Sofia, there will be a difference between the timezones offset before and after DST. Before DST for Europe/Sofia occurs, the offset between Etc/UTC and Europe/Sofia is 2 h. This means that events starting at 3 AM Sofia time, would start at 1 AM UTC.
After DST for Europe/Sofia occurs, the offset between Etc/UTC and Europe/Sofia is 3 h. This means that events starting at 3 AM Sofia time, would start at 0 AM UTC.
As the Scheduler is in Etc/UTC timezone, all appointments will be shown according to their equivalent UTC time. Thus all events, which occurred from 1 to 2 AM before DST, would be shifted from 0 AM to 1 AM after DST.

**Comment by Dimitar-Goshev** [comment]
@deddu Could you share what your setup is and what is the expected and actual result you observe?
