### ISSUE TITLE
"k-gantt-treelist" element's width is 0 when the Gantt is nested in TabStrip 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2276]
### Bug report

When the Gantt is loaded in a TabStrip's tab the **listWidth** property value is not respected and the list's width is 0. 
### Reproduction of the problem
1. Run the following [dojo](http://dojo.telerik.com/EmUBO/3). 
2. Click on Tab 1. 
3. The Gantt is loaded and its list's width is 0, even though listWidth is set to 500. 

As a workaround **listWidth** can be set in the TabStrip's onActivate event handler through the setOptions method: gantt.setOptions({ listWidth: 500});
### Current behavior

The lists width is 0. 
### Expected/desired behavior

The listWidth property value is respected. 
### Environment
- **Kendo UI version:** 2020.2.617
- **Browser:** [all]

**Comment by ag-petrov** [comment]
Not reproducible with the latest version
