### ISSUE TITLE
Sheet.batch should recalc by default

### ISSUE THREAD

**Issue by mishoo** [telerik/kendo-ui-core#2287]
If we use `sheet.batch` without passing `{ recalc: true }`, the Sheet remains in a semi-broken state (some formulas are not calculated, and validation will appear broken).  It would be more intuitive if we recalculate by default.

Related ticket: 1067378.

**Comment by tsvetomir** [comment]
@gyoshev any objections? I think it will reduce the ticket count by a good deal.

**Comment by gyoshev** [comment]
It seems a reasonable default, given that `recalc: false` is used primarily for performance.
