### ISSUE TITLE
Animation can't be enabled again

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#2291]
### Reproduction of the problem
It can be seen http://dojo.telerik.com/umUCo
Animations are disabled and then enabled again, 
error is thrown in the console.
Possible other widget also have that problem.
### Expected/desired behavior
It should not throw errors in console.
It should enable animations again, if animation:false transition is reversable"
### Environment

* **Kendo UI version:** 2016.3.914
* **jQuery version:** x.y
* **Browser:** [all  ]

**Comment by gyoshev** [comment]
To enable back the default animation options, they must be passed back to the `setOptions` method, like so:

    $('#calendar').data('kendoCalendar').setOptions({
        animation: kendo.ui.Calendar.fn.options.animation
    })

The `true` value is not parsed to use the defaults -- it is a good idea for the API, but not a bug.
