### ISSUE TITLE
Unordered List(ul) are not correctly exported to PDF

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2292]
### Bug report

Unordered List(ul) are not correctly exported to PDF. The  default options disc, circle and square are exported with different figures or not visible at all.
### Reproduction of the problem

The issue can be produced in the following Dojo, the Dojo is based on our demo example: http://dojo.telerik.com/iMatu.

The disc ul in Dojo:
![dojo](https://cloud.githubusercontent.com/assets/11087921/19307882/92d12794-9085-11e6-8e5b-269f2fa2d00c.PNG)

The disc ul in PDF: 
## ![downloadedpdf](https://cloud.githubusercontent.com/assets/11087921/19307913/b342ec60-9085-11e6-95b7-ee594879ad50.PNG)

The square ul in Dojo:

![dojosquare](https://cloud.githubusercontent.com/assets/11087921/19307928/c2723fec-9085-11e6-83e9-fdea6248552f.PNG)

The square ul in Adobe PDF:

![pdfadobesquare](https://cloud.githubusercontent.com/assets/11087921/19307936/cbeaac26-9085-11e6-8091-e115659e1126.PNG)

The square ul in Edge PDF:

![pdfedgesuqare](https://cloud.githubusercontent.com/assets/11087921/19307958/dd18cc62-9085-11e6-9838-31bacb72c33a.PNG)

---

The circle ul in Dojo:

![dojocircle](https://cloud.githubusercontent.com/assets/11087921/19307976/f34501e0-9085-11e6-951c-8f1f0ca5a123.PNG)

The circle ul in Adobe PDF:

![adobepdfcircle](https://cloud.githubusercontent.com/assets/11087921/19307980/fca300ca-9085-11e6-8401-2fe6cd43f36b.PNG)

The circle ul in Edge PDF:

![edgepdfcircle](https://cloud.githubusercontent.com/assets/11087921/19307985/079d9eb8-9086-11e6-9a56-9676824e85d5.PNG)
### Environment
- **Browser:** all

**Comment by mishoo** [comment]
We use characters from "DejaVu Serif" font to render the bullets.  Normally this won't be a problem; if the CSS file is hosted on the same domain, we can find the font in the `@font-face` rules, but on the Dojo pages we have to declare it: http://dojo.telerik.com/iMatu/2

Leaving this issue open though.  At some point it would be good to either render list bullets with drawing primitives, or attempt to use PDF built-in font [Zapf Dingbats](https://en.wikipedia.org/wiki/Zapf_Dingbats) — any of these would mitigate the need for DejaVu Serif.

**Comment by vikyaiyer** [comment]
I have a alternative fix for this issue, write custom CSS class to display bullets and apply the class list-view to ul tag.

ul.list-view{
      list-style-type: none;
}
ul.list-view li{
      display: flex;
}
ul.list-view li::before{
       content: "";
       width: 3px;
       height: 3px;
       border: 3px solid black !important;
       border-radius: 50%;
       margin: 7px 5px 0 0;
}

**Comment by park-junha** [comment]
> I have a alternative fix for this issue, write custom CSS class to display bullets and apply the class list-view to ul tag.
> 
> ```
> ul.list-view{
>       list-style-type: none;
> }
> ul.list-view li{
>       display: flex;
> }
> ul.list-view li::before{
>        content: "";
>        width: 3px;
>        height: 3px;
>        border: 3px solid black !important;
>        border-radius: 50%;
>        margin: 7px 5px 0 0;
> }
> ```

This doesn't work for nested bulleted lists.

**Comment by NishaJKulal** [comment]
Even i am facing this issue.

**Comment by pclancysc** [comment]
Extended upon @vikyaiyer solution but using pdf 1.4 fonts

```
ul li {
      list-style-type: none;
    }

    ul li {
      display: flex;
      align-items: flex-start;
    }

    ul li::before {
      content: 'm';
      font-family: 'ZapfDingbats';
      margin: 0.75em 1em 0 0;
      font-size: 50%;
    }

    ul[style='list-style-type: disc;'] li::before {
      content: 'l';
    }
}

```
