### ISSUE TITLE
Missing back button icon on android device/4.3 version

### ISSUE THREAD

**Issue by vegeorgi** [telerik/kendo-ui-core#2293]
The icon for the back button, is missing on android device, 4.3 version. 
Chrome version - 50.0.2661.89. 
Kendo UI Professional v2016.3.1007./Kendo Nova theme
jQuery v1.12.3

The button is there, but the icon is missing. 
I was testing a cordova app from Telerik Platform.

![img_20161012_134812](https://cloud.githubusercontent.com/assets/11516912/19308875/883b15a6-908a-11e6-902c-506ce2db6e8a.jpg)

**Comment by inikolova** [comment]
http://www.telerik.com/forums/backbutton-has-icon-for-ios-nothing-for-android#rdjwsS7ndE2qL8aGkeRcjw
