### ISSUE TITLE
Selected font not displaying in dropdown for Kendo Editor (Tablet)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2295]
### Bug report

Selected font not displaying in DropDown for Kendo Editor (Tablet). When a new font is selected and then the user click on the text, the dropdown is showing empty.
### Reproduction of the problem

The issue can be reduced in our demos, for example:  http://demos.telerik.com/kendo-ui/editor/all-tools. The issue was reproduced on Android tablet, also the same behaviour was reported for iPad.

Steps:

1) Mark the content 
2) Change the font from the DropDown
3) Notice that the font is changed but the DropDown shows empty.
### Environment
- **Browser:** all

**Comment by massiek** [comment]
Yeah me too

**Comment by Dimitar-Goshev** [comment]
### Bug report
The FontName tool value is applied to editor content but is not displayed in the UI on Android and iPhone. 
https://www.screencast.com/t/D6QxlY6g9y
Ticket ID: 1123036

### Reproduction of the problem
http://demos.telerik.com/kendo-ui/editor/all-tools
Change the font name through the dropdown

### Environment
* **Kendo UI version:** 2017.2.621
* **Browser:** iPhone Safari and Android Chrome

**Comment by Iankodj** [comment]
For iPad and iPhone there is a limitation: Changing selection in the editing area does not trigger selection events and none of the tools are updated properly.
