### ISSUE TITLE
notification colors theme issue (2016.3.914)

### ISSUE THREAD

**Issue by sebfz1** [telerik/kendo-ui-core#2297]
Hi,

I've just upgraded to `2016.3.914` and I'm noticing that new notification colors choice/change make these almost unreadable (info, success and error).
It is true for most themes, not to say that background color is often inappropriate (from my pov). See 'default' theme in attached screenshot

### Environment

* **Kendo UI version:** 2016.3.914
* **Browser:** [Firefox 49] 

Thanks in advance,
Sebastien.

![kendo-ui-2016 3 914](https://cloud.githubusercontent.com/assets/1717144/19317424/45675e68-90a5-11e6-9828-4a77c626f027.png)

**Comment by inikolova** [comment]
Duplicate issue - [https://github.com/telerik/kendo-ui-core/issues/2196](url)
