### ISSUE TITLE
Missing ClearButton option

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-ui-core#2303]
The ComboBox ASP.NET MVC wrappers are missing the ClearButton configuration option, which is enabled by default. As a result, the option cannot be disabled at this point.

This was reported in ticket 1068316.

**Comment by Jekata** [comment]
The same issue also applies the AutoComplete wrapper. Can you please take a look at it?

**Comment by ggkrustev** [comment]
The required changes for the AutoComplete and MultiSelect are already done (visible in the commits related to this issue).

We just missed to add the labels for the AutoComplete and MultiSelect. We've done that.
Thanks for the reminder.
