### ISSUE TITLE
TreeView unexpected behaviour when the same path is expanded twice in the same function.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2309]
### Bug report

TreeView unexpected behaviour when the same path is expanded twice in the same function.
For example, if in one function the expandPath method is called twice for the same path for adding a class to different HTML elements, the first element will not receive the class.
### Reproduction of the problem

The issue can be reproduced in the following Dojo: http://dojo.telerik.com/IyUHI/2
- Click the expand button.
- Notice that only the second item has the newly added class.
### Environment
- **Browser:** all

**Comment by zdravkov** [comment]
The expandPath method is performing an asynchronous load operations so if we have a case when two expandPath operations should be performed one after another we would rather recommend calling the second one from the callback function as for example in this [dojo](http://dojo.telerik.com/@zdravkov/IhiJIYen).
