### ISSUE TITLE
Changing height after width does not work

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-ui-core#2325]
### Bug report

Trying to change Barcode height after changing the width does not work. Reported in ticket: 1068954
### Reproduction of the problem

Can be observed in this dojo (**Option 2**): http://dojo.telerik.com/@Iliana/aSaHU

Note: using the **redraw** method instead of the **_resize_** one works as expected.
### Expected/desired behavior

The order should not have matter when changing width / height
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** 1.12.3
- **Browser:** [all]

**Comment by danielkaradachki** [comment]
resize is supposed to work with the element dimensions. Not the options. Use redraw if you wish to update the barcode based on the options.
