### ISSUE TITLE
Kendo format string does not put the literal '?' in the correct place

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2326]
### Bug report

Kendo format string does not put the literal '?' in the correct place. This is not observable in every scenario. Escaping or not the literal '?' does not change the result is some scenarios.
### Reproduction of the problem

The issue can be observed in the following Dojo: http://dojo.telerik.com/avUne
### Environment
- **Browser:** all

**Comment by madelson** [comment]
:+1: 

For reference, here's my original question on StackOverflow which prompted this:
http://stackoverflow.com/questions/39977914/kendo-format-string-puts-literal-in-the-wrong-place

**Comment by ag-petrov** [comment]
Using the symbol directly seems to work now.

```
var format = "?$0";
    console.log(kendo.toString(100, format)); 
```
