### ISSUE TITLE
Widget selects focused item on blur unexpectedly

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#2327]
### Bug report

The widget is designed to select the focused item on blur, even though the user didn't want to accept that selection. This stays since the old "always should select an item" behavior. 
### Reproduction of the problem

Run the demo: http://dojo.telerik.com/@bmulhollem/erAWu
### Expected/desired behavior

Leave the widget empty on blur. If the user TABs out or clicks the the item, then the selection will be initiated.
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** 1.9.1
- **Browser:** all

Reported in TicketID: 1069023

**Comment by gyoshev** [comment]
Raising severity since it can be seen in the spreadsheet.

**Comment by simonssspirit** [comment]
An issue related to this one was reported in ticket: 1085310.

In the ticket, there are steps to reproduce and a runnable example.

**Comment by tsvetomir** [comment]
Bumping priority, ideally we'd like to have this shipped with the first SP

**Comment by ggkrustev** [comment]
I'd love to include in the SP, but there will be change in the behavior - https://github.com/telerik/kendo-ui-core/commit/ac7af1ec953d2c1f051838a3b495126d345ca2e2
@tsvetomir, Do you think that it is OK to push the change for the SP?
