### ISSUE TITLE
Unchanged widget triggers 'select' event on TAB

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#2329]
### Bug report

The widget seems to trigger 'select' event on every TAB, even though the value has not changed.
### Reproduction of the problem
1. Open http://demos.telerik.com/kendo-ui/dropdownlist/events
2. Focus and blur the widget using TAB/SHIFT+TAB
### Expected/desired behavior

Trigger 'select' event only when the value has changed.
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** 1.9.1
- **Browser:** all

Reported in TicketID: 1069129

**Comment by IvanDanchev** [comment]
Apart from the event firing unexpectedly on pressing tab, it also fires when the DropDownList loses focus by clicking outside of the widget: http://dojo.telerik.com/IbowO Reproducible in version 2016.3.914 and newer.

**Comment by IvanDanchev** [comment]
Raising the issue's severity. Ticket ID: 1077241
