### ISSUE TITLE
StockChart does not show the last point

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-ui-core#2331]
### Bug report

StockChart does not show the last point. Reported in ticket: 1069032. 
### Reproduction of the problem

Can be observed in this dojo: http://dojo.telerik.com/@Iliana/EJOZe
### Current behavior

The last bar for Oct 2 is not displayed by default, but displaying if navigator duration is changed
### Expected/desired behavior

A bar for Oct 2 is displayed when navigator.select and or / categoryAxis.max are set
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** 1.12.3
- **Browser:** [all ]

**Comment by tsvetomir** [comment]
Adding a [test case](http://dojo.telerik.com/@ghauta@centricminingsystems.com/amITU) for validation.

**Comment by shiv-veerashetty** [comment]
Is there any workaround for this issue ?

**Comment by tsvetomir** [comment]
Not that I know of, but we'll publish an updated internal build tomorrow. Apologies for the caused inconvenience.

**Comment by shiv-veerashetty** [comment]
Can u please tell me the build where this fix is integrated ?

**Comment by tsvetomir** [comment]
The fix should be included in the current release - 2017 R1 (v. 2017.1.118), as well as the latest internal build for 2016 R3 (v 2016.3.1317).
