### ISSUE TITLE
DataSource vs SchedulerDataSource inconsistency

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-ui-core#2337]
### Bug report

from @JeroenVinke

### Reproduction of the problem
A user of our aurelia-kendoui-bridge has noticed inconsistent behavior between the SchedulerDataSource and the DataSource. I made two dojo's: http://dojo.telerik.com/imuxE and http://dojo.telerik.com/iDUZa. The former uses a SchedulerDataSource and the latter uses the DataSource.

The user uses the read callback of the datasource so that he can supply an array of data from his view-model to the datasource It appears that the SchedulerDataSource modifies objects of the original array, setting all properties to undefined. So whenever you tell the scheduler to refresh, appointments would disappear. The DataSource does not modify the objects out of the original array, hence the seemingly inconsistent behavior.

It is easily worked around by cloning the array before passing it to the DataSource's options.success function, but thought I would mention this anyway as it may confuse others.

CC @ggkrustev

**Comment by ggkrustev** [comment]
Indeed, the original data will be modified, but this is expected. The DataSource does not perform a deep clone of the data, before the projections (`from` option) and parsing (`parse` function) transformations are done. This could be see in the regular DataSource too:
- http://dojo.telerik.com/iDUZa/2

What breaks the Scheduler binding in the first example is the `from` projection, which will modify the structure of the objects. I am afraid that the described behavior is expected and the only way to avoid it is to clone the data manually:
- http://dojo.telerik.com/imuxE/2

**Comment by JeroenVinke** [comment]
Thank you for the detailed response 👍
