### ISSUE TITLE
Fix customizing grid filter operators in ASP.NET Core

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/kendo-ui-core#2346]
You cannot customizing grid filter operators in ASP.NET Core - http://screencast.com/t/p4s0rCO2GIk5

The issue is reproducible with this demo - http://demos.telerik.com/aspnet-core/grid/filter-menu-customization

**Comment by masterjs** [comment]
Hello,
Any news on when this could be fixed or any work-around? It's already been a while and your own demo page is showing a broken feature (http://demos.telerik.com/aspnet-core/grid/filter-menu-customization).

thank you,
JS

**Comment by TsvetinaIvanova** [comment]
When fixing this, also ensure that the IsNull operator is shown as expected in DateTime? columns (original issue in https://github.com/telerik/kendo-ui-core/issues/3376 .

**Comment by ag-petrov** [comment]
https://github.com/telerik/kendo/commit/b2917c6ef8f76b69a74f4715ec36338db7a6e18f
