### ISSUE TITLE
Generate ASP.NET Core wrappers for Upload clear event

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#2350]
Generate ASP.NET Core wrappers only (the ASP.NET MVC wrappers should be generated already) for Upload clear event:

https://github.com/telerik/kendo-ui-core/blob/master/docs/api/javascript/ui/upload.md#clear

**Comment by Dimitar-Goshev** [comment]
Use the following setup for testing:
        @(Html.Kendo().Upload()
            .Name("files")
            .Async(a => a
                .Save("Save", "Upload")
                .Remove("Remove", "Upload")
                .AutoUpload(false)
            )
            .Events(events => events
                .Clear("onClear")
            )
        )
