### ISSUE TITLE
kendo.ui.notification is not responsive

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#2351]
### Disclaimer

_Again I appreciate that this is borderline between feature request and defect since the notification widget might not have been designed to be responsive in the first place, but considering Telerik heavily advertises the responsiveness of the Kendo UI framework, I am opting for the latter._
### Bug report

kendo.ui.notification is not responsive.
### Reproduction of the problem

Try http://runner.telerik.io/fullscreen/IxEKon on an iPhone 5.

![image](https://cloud.githubusercontent.com/assets/2556751/19592266/e442b112-9772-11e6-9b2d-4d29e2b9d3b5.png)
### Expected/desired behavior

The notification should wrap on smaller screens.
### Environment
- **Kendo UI version:** 2016.3.914

**Comment by jlchereau** [comment]
FYI, I have also posted a feature request for a different behaviour when used with kendo.mobile.Application:
http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/16755469-add-notifications-to-kendo-mobile-or-adapt-the-be

**Comment by mparvanov** [comment]
Тhanks for your post, and for your interest in Notification responsive behavior! This issues list is for bugs only, not feature requests, so I’m going to close this issue since you have already opened a feature request in our user voice portal.

**Comment by jlchereau** [comment]
When Telerik/Progress marketing shouts loud and clear that Kendo UI is responsive, and developers discover that several widgets are not, do you think that keeping on promises should be qualified as feature request or bug/defect?
