### ISSUE TITLE
Sporadic error in IE8 in leafDatacells function using multi column headers

### ISSUE THREAD

**Issue by rkonstantinov** [telerik/kendo-ui-core#2356]
The error seems to be raised by the [].sort logic.

Here are some findings from the support ticket:

> It turns out to be an unrelieable array.prototype.sort() algorithm in the IE8 JavaScript runtime. Kendo.web.js reuses the a and b parameters in it's sort compareFunc - which IE8 does NOT like and "sometimes" returns an undefined.
> See https://www.zachleat.com/web/array-sort/ for more information and a life demo.

**Comment by jlewis-ebi** [comment]
What is the status of this issue?  My company uses Kendo and we've had to modify the code in the last several releases to get past this to be able to support IE8.  Will this be fixed before the R1 2017 release, which I just read is dropping IE8 support?  Thank you and great product by the way.

**Comment by rkonstantinov** [comment]
I'm afraid that as we will be dropping the IE8 support, addressing such IE8 specific issues is not our current priority.
