### ISSUE TITLE
Keyboard arrow down opens dropdown disregarding the MinLength property

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2357]
### Reproduction of the problem

When filtering is enabled and minLength property is set, the dropdown could be opened with the keyboard arrow down even when the minLength requirement is not met. [Screencast](http://screencast.com/t/nokhZrU2A), [Dojo](http://dojo.telerik.com/icIJa/6)
### Expected/desired behavior

The dropdown should not be opened unless the filter minLength requirement is met.

**Comment by mparvanov** [comment]
The dropdown should be opened using the keyboard down arrow regardless of the filter minLength.
