### ISSUE TITLE
Tables could not be resized when editor is inside Kendo grid custom popup template

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#2358]
### Bug report

Table resizing is not working when editor is inside Kendo grid custom popup template
### Reproduction of the problem

1) Open the custom popup template
2) Insert a table inside editor content
3) Try to resize a row, cell or the whole table
### Current behavior

The rows, cells or the whole table could not be resized
### Expected/desired behavior

The rows, cells or the whole table could be resized
### Environment
- **Kendo UI version: 2016.3.914
- **jQuery version:1.12.3
- **Browser: all

**Comment by ipeshev** [comment]
Is it possible this to be related to telerik/kendo-ui-core#2345 ?

**Comment by mparvanov** [comment]
This issue is reproducible only when editor is inside of Kendo grid custom popup template. It's not related to the case of single editor or editor inside window like this: http://dojo.telerik.com/@parvanov/EDAwU
