### ISSUE TITLE
Widget should re-apply selection when filter is removed

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#2363]
### Bug report

The widget will remove the selection when filtering is applied, which is **intended** behavior. When filtering is removed, however, the item is not re-selected, which will result in not selected item even on blur.
### Reproduction of the problem
1. Open http://demos.telerik.com/kendo-ui/dropdownlist/serverfiltering
2. Open popup and type 'tof'
3. Remove filter
4. Notice that 'Chai' is not selected even on blur and on subsequent popup open
### Expected/desired behavior

Re-select lastly active item when filter is removed.
### Environment
- **Kendo UI version:** 2016.3.914
- **jQuery version:** 1.9.1+
- **Browser:** all

Reported in TicketID: 1070583

**Comment by zdravkov** [comment]
Could not replicate with the latest version.

**Comment by Dimitar-Goshev** [comment]
Fixed since R1 2018 SP1 - 2018.1.221
