### ISSUE TITLE
The virtualized ComboBox is selecting a random item when scrolling with the arrows and then blurred.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2365]
### Bug report
The virtualized ComboBox is selecting a random item when scrolling with the arrows and then blurred.

### Reproduction of the problem
The issue can be reproduced in our demo:
http://demos.telerik.com/kendo-ui/combobox/virtualization

### Environment
- **Kendo UI version:** 2019.3.1023
- **Browser:** [all]

**Comment by IvanDanchev** [comment]
The issue is reproducible even without scrolling. In the virtualization demo enter "Berglunds snabbköp", click on the ComboBox to open it, then click outside to blur it. The first item of the page is selected instead of the item with text "Berglunds snabbköp".
