### ISSUE TITLE
Disabled Spreadsheet cells can be edited through custom cell editors

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#2367]
### Bug report

It is possible to edit disabled cells if they are in a selected range with cells using custom editors. Changing the value of a cell through its custom editor results in changing the disabled cell value.
### Reproduction of the problem
1. Use the following [Dojo](http://dojo.telerik.com/OKEBU)
2. Select a range consisting of a cell from column B and a cell from column C.
3. Change the value of the column B cell through its custom editor.
### Current behavior

The disabled cell in column C changes its value.
### Expected/desired behavior

The disabled cell in column C cannot be edited.
### Environment
- **Kendo UI version:** 2016.3.914
- **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The issue is still reproducible, so I reopen it. If you select a cell with custom editor and a disabled cell in a range, editing the first cell through the custom editor would result in editing the disabled cell as well.

**Comment by mishoo** [comment]
Actually for this case the only thing we can do is to abort entirely.  We have a similar situation in filling — if you drag the autofill handle over some disabled cells, it will abort with a message “Destination range contains disabled cells” (fills no cells at all).  I suggest we do the same in this case, does it sound reasonable?

**Comment by Dimitar-Goshev** [comment]
Yes, it sounds reasonable to me. Thus, we would have a more consistent behavior in these two similar scenarios - trying to edit a disabled cell.

**Comment by veselints** [comment]
The issue is still present for the Spreadsheet MVC HTML helper. It has been fixed for the jQuery Kendo Spreadsheet.

**Comment by veselints** [comment]
Reopened this by mistake.
