### ISSUE TITLE
Clicking outside widget keeps cell editor open

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#2369]
### Bug report

Use case: button outside spreadsheet that sends the spreadsheet data to the server. Clicking it will not have the latest data, as the formula input does not confirm the changes on blur.
### Environment
- **Kendo UI version:** 2016.3.914
- **Browser:** [all]

**Comment by tbjers** [comment]
+1 We are having the same issue.
