### ISSUE TITLE
Dropdown height is incorrect when there is h* element in HeaderTemplate

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2373]
### Reproduction of the problem

When there is an h\* element (e.g. `<h5>`) in HeaderTemplate of a MultiSelect the dropdown's height is not calculated correctly.
[Dojo](http://dojo.telerik.com/eMUlU), [Screenshot](http://screencast.com/t/dur3Zc6lQT)

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket ID: 1081464

The headerTemplate x and y overflow in ComboBox and DropDownList as well.
The dojo below shows all three widgets with both axes overflowing.

[Dojo](http://dojo.telerik.com/@bubblemaster/uFEfi)
[Fulscreen](http://runner.telerik.io/fullscreen/@bubblemaster/uFEfi)
