### ISSUE TITLE
The PivotGrid wrapper serializes cube.dimensions and cube.measures configuration as an array

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2375]
### Bug report

The `cube.dimensions` configuration defined by the PHP wrapper is serialized as an array, where we expect an object.

The current output is something like this:

```
dimensions: [
 { field: "ContactName", value: { caption: "All Contacts" } },
 { field: "CompanyName", value: { caption: "All Companies" } },
 { field: "Country", value: { caption: "All Countries" } },
 { field: "ContactTitle", value: { caption: "All Titles" } }
]
```

This will break the PivotConfigurator binding.

The expected output is:

```
dimensions: {
    ContactName: { caption: "All Contacts" },
    CompanyName: { caption: "All Companies" },
    Country: { caption: "All Countries" },
    ContactTitle: { caption: "All Titles" }
}
```
### Reproduction of the problem

The issue can be observed in our offline PHP demos: http://kendobuild/staging-php/pivotgrid/remote-flat-data-binding.php

Try to drag one of the columns to the main Grid and noticed that an error occurs: Uncaught SyntaxError: Unexpected number
### Environment
- **Browser:** [all]

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket with ID 1340230. Raising priority.

**Comment by Alex-Bubblemaster** [comment]
Reported in ticket with ID: 1443768. Raising priority
