### ISSUE TITLE
fix disabled menu items can be selected in IE11

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/kendo-ui-core#2378]
You can select disabled menu items in IE11 - http://screencast.com/t/Gt5gl7Gq
Steps to reproduce:
1) Open this dojo sample in IE11 - http://dojo.telerik.com/iyUzI/10
2) Click on first item-> sub item 1,2,3
Actual - disabled items are selected. Expected - disabled items should not be selected.

**Comment by simonssspirit** [comment]
Another issue probably connected to this one:

When the disabled items are clicked, the up and down keyboard navigation stop working(IE11).
