### ISSUE TITLE
TreeView MVC checkboxes are not styled when the wrapper is bound to remote data.

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-ui-core#2380]
### Bug report
TreeView MVC checkboxes are not styled when the wrapper is bound to remote data. The issue is not reproducible when a TreeView is bound to local data.

### Desired behavior
Render the same DOM when a TreeView is bound to remote and to local data, which will allow to style check-boxes in the wrapper.

**Comment by Dimitar-Goshev** [comment]
Duplicate of #2379
