### ISSUE TITLE
Custom header for upload 'remove' event

### ISSUE THREAD

**Issue by rmorrise** [telerik/kendo-ui-core#2386]
### Bug report

On Kendo Upload, the XML HTTP request is not provided to the 'remove' event.

This looks like an issue that was reported on the Telerik forum by users back in 2014:
http://www.telerik.com/forums/custom-authorization-header-for-upload

### Reproduction of the problem
_(bug report only)_

When configuring the kendo Upload widget, set a 'remove' event on the upload options:
```
uploadOptions.remove = function(e) {
  var xhr = e.XMLHttpRequest;
  if(xhr) {
    xhr.addEventListener("readystatechange", function() {
      if (xhr.readyState == 1) {
        xhr.setRequestHeader('Authorization', 'Basic 1234');
      }
    });
  }
}
```

### Current behavior
_(optional)_

xhr is null.

//I tested the same code on the 'upload' event and it works normally. Only the 'remove' is missing the xhr.

### Expected/desired behavior

Authorization header should be added to the HTTP DELETE request generated by the upload widget.

Even better: fix the upload widget so that it uses the datasource 'transport' options. Why is this widget different than all other widgets?

### Environment

* **Kendo UI version:** 2016.1.226
* **jQuery version:** 1.8.3
* **Browser:** Chrome 52.0.2743.82 m (64-bit)

**Comment by tjrobinson** [comment]
Documentation: https://docs.telerik.com/kendo-ui/api/javascript/ui/upload/events/remove

For example:

```
e.headers = { "X-XSRF-TOKEN":  xsrfToken };
```
