### ISSUE TITLE
Scheduler does not calculate recurring appointment correctly when kendo.culture is set to other but default

### ISSUE THREAD

**Issue by antonpopov** [telerik/kendo-ui-core#2388]
### Bug report

When a recurring appointment passes December the **first** occurrence in the new year is not calculated correctly when kendo.culture isn't set to default.

### Reproduction of the problem
http://dojo.telerik.com/eTiGU/12 
1) If an appointment is set up on the **18th of November** to reccur every **5 weeks**, next appointment is the **23th of december** - that is right so far - next appointment should be **27th of January**, but instead **it is one week later**, the **3rd** of february. (this behavior occurs when kendo.culture("de-DE"); **is set**)
### Environment

* **Kendo UI version:** 2016.3.1028
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by antonpopov** [comment]
Ticket ID: 1071513

**Comment by tommyTanaka** [comment]
Hi, is there a date when this issue will be fixed?
