### ISSUE TITLE
Show custom binder in the Window and Dialog MVVM demos

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2390]
With the current implementation of these demos ([Dialog](https://demos.telerik.com/kendo-ui/dialog/mvvm) and [Window](https://demos.telerik.com/kendo-ui/window/mvvm)) we show simple property binding to open and close dialog, which is incorrect for the Popup widgets—visible binder interacts only with the CSS display property and does not call the widget's API to show or close. The latter is typically done using [custom binders](http://docs.telerik.com/kendo-ui/framework/mvvm/bindings/custom#custom-widget-binding).

Example [http://dojo.telerik.com/ISaHI](http://dojo.telerik.com/ISaHI): 

```js
kendo.data.binders.widget.dialogOpen = kendo.data.Binder.extend({
      init: function(widget, bindings, options) {
          kendo.data.Binder.fn.init.call(this, widget.element[0], bindings, options);
      },
      refresh: function() {
      	var that = this;
        var value = that.bindings["dialogOpen"].get();
        var dialog = $(that.element).data("kendoDialog");
        
        if(value){
        	dialog.open();
        }else{
          dialog.close();
        }
      }
        
  });
```

**Comment by Dimitar-Goshev** [comment]
The two demos were improved based on this issue and they are live with R2 2019 SP1 release.
