### ISSUE TITLE
Event created on 10/30/2016 is not rendered in DayView

### ISSUE THREAD

**Issue by ivanchev** [telerik/kendo-ui-core#2393]
Can be observed in live demo:
http://demos.telerik.com/kendo-ui/scheduler/index

Create an one hour event on 10/30/2016, from 11PM in week view. 

Switch to day view for 10/30/2016 - event should be rendered, but it's not.

* **Kendo UI version:** 2016.3.1028

**Comment by Dimitar-Goshev** [comment]
The issue is still reproducible.
