### ISSUE TITLE
Fix Kendo UI scaffolder hijacks "Add Controller"

### ISSUE THREAD

**Issue by Jekata** [telerik/kendo-ui-core#2395]
### Bug report
When the developer picks Add | Controller in VS2015 he/she gets the Kendo UI Scaffolder dialog instead of the default VS add new controller dialog. This is a problem because the developer is unable to add a new empty controller.
The issue is reproducible only in Telerik ASP.NET Core projects and not in Telerik ASP.NET MVC ones.

### Reproduction of the problem
Video reproduction in Telerik ASP.NET Core project -> [http://screencast.com/t/iB1e9gPA1iX](http://screencast.com/t/iB1e9gPA1iX)

### Current behavior
It is impossible to add an empty controller

### Expected/desired behavior
It should be possible to add an empty controller 

### Environment

* **UI for ASP.NET MVC Core:** 2016.3.xxx
Visual Studio 2015

**Comment by pbechtelGitHub** [comment]
Any update on this?  Still happening.

**Comment by mparvanov** [comment]
Hi,

I'm raising the severity of the public issue to critical so its priority in our issues backlog will also be increased.

Best Regards

**Comment by Xizario** [comment]
It was false report in the first place. Visual Studio itself don't have "Controller..." into the context menu. So we are not overriding anything. 
Without Scaffolder: 
![originalmenu](https://cloud.githubusercontent.com/assets/9458606/23458533/4b13ee50-fe85-11e6-9293-a86c71a17416.png)
With Scaffolder:
![scaffoldermenu](https://cloud.githubusercontent.com/assets/9458606/23458532/4b1302ba-fe85-11e6-914c-783aefc289b2.png)

**Comment by tsvetomir** [comment]
Nice catch! Perhaps we can register our entry as "Add Kendo UI Controller"?

**Comment by Xizario** [comment]
Looking at the values of [CodeGeneratorInformation](https://msdn.microsoft.com/en-us/library/microsoft.aspnet.scaffolding.codegeneratorinformation(v=vs.118).aspx) it looks as the text in the menu is not something that we can control.

We set the correct `Categories` and `Gestures`, which tells Visual Studio that a `Controller` and/or `View` can be created using our Scaffolder.

If the user have several extensions, he will see this window(which is not ours): 
![image](https://cloud.githubusercontent.com/assets/9458606/23467291/4d0204e2-fea6-11e6-9906-0534deee305a.png)
But if he don't have multiple extensions the studio itself starts the only one available.

**Comment by ethr95awd** [comment]
[http://stackoverflow.com/questions/32901637/add-controller-option-is-missing-in-visual-studio-2015](url)

Here are some discussion about missing the add controller in VS 2015

**Comment by brentkilboy** [comment]
This one just threw me off again. With .net core apps, you need to make sure you have the dependencies in your project.json for the new Controller option to appear in VS. It's some combination of the below:
{
  "dependencies": {
   ...
    "Microsoft.AspNetCore.Mvc": "1.1.1",
    ...
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.1.0-preview4-final",
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.1.0-preview4-final"
  },

  "tools": {
   ...
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
      "imports": [
        "portable-net45+win8+wp8+wpa81"
      ]
      }
    },
    "frameworks": {
      "netcoreapp1.0": {
        "imports": [
          "dotnet5.6",
          "portable-net45+win8+wp8+wpa81"
        ]
      }
    },
After those are there, the menu prompts correctly:
![2017-03-01 09_40_28-add scaffold](https://cloud.githubusercontent.com/assets/14183771/23470192/025788c4-fe63-11e6-8a17-33da9530a84a.png)

**Comment by ethr95awd** [comment]
brentkilboy that did it!

The only catch was that Microsoft.EntityFrameworkCore.Tools needed to be loaded with the console and with the -pre switch. 

[https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Tools/1.1.0-preview4-final](url)
