### ISSUE TITLE
Virtualization does not reset page after value mapping

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2396]
### Reproduction of the problem
[Demo](http://runner.telerik.io/fullscreen/AdAMo)
[Screencast](http://screencast.com/t/gPwhmwBe)

Steps for reproduction: 

1. Click in the MultiSelect
2. Type "hanari" 
3. Select the last result 
4. Lose focus,  e.g. click outside the MultiSelect
5. Click in MultiSelect focus it - the selected values are remapped 
6. Type "hanari" in MultiSelect 

### Current behavior
NO RESULTS for any search, because the "page" and "skip" parameters are not reset

**Comment by arracos** [comment]
Question for you... When using type ahead search of the virtualized multi-select, the text the user typed is not being removed once a selection is made:

1. User  types 123 in the multi-select
2. The drop down presents the list of possible choices
3. User selects a choice
4. The typed text of 123 remains in the field until the field loses focus 

Is that the intended behavior or another bug with virtualized multi-selects?  I'm hoping it's a bug that is either resolved with this fix or can be fixed at the same time as my users are complaining about this bit of "new" functionality.  
[GhostText_1.zip](https://github.com/telerik/kendo-ui-core/files/569483/GhostText_1.zip)

**Comment by ggkrustev** [comment]
@arracos,
When the `autoClose: false` option is used, the widget will persist the typed text until the user blurs the widget. The behavior is intended. The text represents an applied filter that is still present, hence it should stay until the selection completes.

One possible workaround is to clear the filter text on every change:
- http://dojo.telerik.com/UjUKE

P.S. The latest internal build (from yesterday) includes this fix. You can give it a try.
