### ISSUE TITLE
DropDownList with MinFilterLength > 0 does not repopulate the full data list after filter has been triggered and an item has been selected

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2400]
### Bug report
DropDownList with MinFilterLength > 0 does not repopulate the full data list after filter has been triggered and an item has been selected.

Another related problem is the following: After filtering, when no item is selected and the Esc key pressed (to clear filter and close the drop-down), the second attempt to filter with the same string could not be performed.

### Reproduction of the problem
On the following [Dojo sample](http://dojo.telerik.com/uXurU):
- Click to open drop-down;
- Type "la";
- Two items are returned;
- Select one of them;
- The drop-down closes;
- If you now open the drop-down, the filter field is empty, but the list contains only the previously filtered items;

Reproduction of the related problem (on the same sample):
- Click to open drop-down;
- Type "la";
- Two items are returned;
- Press "Esc";
- The filter is cleared and the drop-down closes;
- Open again the drop-down;
- The full list of items is displayed;
- Type "la";
- No filtering occurs;

### Expected/desired behavior
DropDownList should display all items, if there is no filter text.

### Environment

* **Kendo UI version:** 2016.3.914

**Comment by ibwoy** [comment]
Any fix on this?
