### ISSUE TITLE
Fix Delete confirmation cannot be disabled in Kendo UI Grid for ASP.NET MVC

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/kendo-ui-core#2406]
Delete confirmation cannot be disabled in Kendo UI Grid for ASP.NET MVC

Steps to reproduce:
1. Open the offline version (2016.3.1028) of this demo http://demos.telerik.com/aspnet-mvc/grid/editing-inline.
1. Disable the delete confirmation dialog:

```    
.Editable(editable => editable.Mode(GridEditMode.InLine).DisplayDeleteConfirmation(false))
```

Actual - the confirm dialog is still shown. Expected - the confirm should not be shown.

Note: The issue is reproducible only with MVC wrappers.

A possible workaround is to update the options of the grid via the setOptions method.

Example:

```js
@(Html.Kendo().Grid<Kendo.Mvc.Examples.Models.ProductViewModel>()
    .Name("grid")
    .Columns(columns =>
    {
        columns.Bound(p => p.ProductName);
        columns.Bound(p => p.UnitPrice).Width(120);
        columns.Bound(p => p.UnitsInStock).Width(120);
        columns.Bound(p => p.Discontinued).Width(120);
        columns.Command(command => { command.Edit(); command.Destroy(); }).Width(250);
    })
    .ToolBar(toolbar => toolbar.Create())
    .Editable(editable => editable.Mode(GridEditMode.InLine).DisplayDeleteConfirmation(false))
    .Pageable()
    .Sortable()
    .Scrollable()
    .HtmlAttributes(new { style = "height:550px;" })
    .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(20)
        .Events(events => events.Error("error_handler"))
        .Model(model => model.Id(p => p.ProductID))
        .Create(update => update.Action("EditingInline_Create", "Grid"))
        .Read(read => read.Action("EditingInline_Read", "Grid"))
        .Update(update => update.Action("EditingInline_Update", "Grid"))
        .Destroy(update => update.Action("EditingInline_Destroy", "Grid"))
    )
)

<script type="text/javascript">
    $(document).ready(function () {
        $("#grid").data("kendoGrid").setOptions({ "editable": { "confirmation": false } });
    })
    

    function error_handler(e) {    
        if (e.errors) {
            var message = "Errors:\n";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function() {
                        message += this + "\n";
                    });
                }
            });        
            alert(message);
        }
    }
</script>
```

**Comment by chrismikec** [comment]
Is there any forecast for when this will be fixed? It is causing me a major headache.

**Comment by BobBonser** [comment]
I am still having this problem.  I still get the Delete confirmation popup even though I have indicated in the grid that I do not want them.  I have confirmed that I am using the latest internal build according tot he Chrome developers console.

Here is my grid markup:

                @(Html.Kendo().Grid(Model.Locations)
                    .Name("LocationsGrid")
                    .ToolBar(toolbar => { toolbar.Create().Text("Add Location"); })
                    .HtmlAttributes(new { style = "height: 150px;" })
                    .Columns(columns =>
                    {
                        columns.Bound(l => l.LocationData).ClientTemplate("#=LocationData.Name#").Title("Name");
                        columns.Command(cmd => cmd.Destroy().Text("<i class='fa fa-trash-o'></i>")).Width(50);
                    })
                    .Scrollable()
                    .Editable(editable => editable.Mode(GridEditMode.InCell).DisplayDeleteConfirmation(false))
                    .DataSource(ds =>
                        ds.Ajax()
                        .Batch(true)
                        .ServerOperation(false)
                        .Model(model => { model.Id(p => p.Id); model.Field(l => l.LocationData).DefaultValue(ViewBag.DefaultLocation as LocData); })
                            .Create(create => create.Action("AddLocationToProcess", "ProjectConfiguration"))
                            .Destroy(destroy => destroy.Action("RemoveLocationFromProcess", "ProjectConfiguration"))
                        )
                        .Events(events => events.Edit("LocationsGrid_edit"))
                    )

**Comment by slighter** [comment]
Yes, this fix was not included in the current internal build. But we made sure it will be available in the next one.

**Comment by miasavelli** [comment]
How did you find what statement to delete in the Controller side when you call your destroy Action Controller? My row will delete in the kendo grid, but not send the correct sql exec and save.
