### ISSUE TITLE
Angular: Initialization from nested property

### ISSUE THREAD

**Issue by MizardX** [telerik/kendo-ui-core#2408]
### Bug report

When using k-ng-model, the bound expression must be a property directly on the scope. Nested properties result in a blank widget.

I believe this is common for all widgets that use k-ng-model, but I will only demonstrate it for the DatePicker.

### Reproduction of the problem
Use a nested property for k-ng-model with the DatePicker widget.

### Current behavior
The DatePicker is blank.

### Expected/desired behavior
The DatePicker gets initialized the same way as when using a non-nested property.

See a demonstration of this problem here: https://jsfiddle.net/MizardX/3s80e7bz/

The left DatePicker is initalized with a non-nested property, and the right with a nested property.

The problem is probably due to this line: [src/kendo.angular.js#L411](https://github.com/telerik/kendo-ui-core/blob/8aa8f59148ed88584ede592aadbd6853485b2bc8/src/kendo.angular.js#L411)

### Environment

* **Kendo UI version:** 2016.3.1028
* **jQuery version:** 2.2.4
* **Browser:** all

**Comment by ggkrustev** [comment]
Hi @MizardX,
using `k-ng-model` and `ng-model` on the same component is not reliable and could lead to undesired behavior, like the depicted one. Removing the `ng-model` directive fixes the issue:
- https://jsfiddle.net/3s80e7bz/1/

I am afraid that you cannot use the Kendo UI widgets with both directives applied at the same time.  Please use either the `ng-model` or `k-ng-model` directives.

With this comment, I will close the issue as we cannot consider it as a bug.

**Comment by MizardX** [comment]
Ok. Removing `ng-model` does make it work with nested properties in this scenario.

But changing the linked line to use `$parse` would make scenarios easier, where both `ng-model` and `k-ng-model` are required, such as Angular validation when binding to a date.

**Comment by ggkrustev** [comment]
I would suggest you post your request for enhancement in our UserVoice portal. Thus more people could vote for it.

Of course, a pull request, that solves the issue, is always welcomed.
