### ISSUE TITLE
Filtering Merged Rows

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#2416]
### Desired behavior

Ref: [UV Item](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/15662652-spreadsheet-filtering-merged-rows)

The filter and sorting functionality should be extended to support merged cells.

**Comment by mishoo** [comment]
Not sure why filtering was prevented on range with merged cells, it appears to work properly.  I enabled it.

For sorting things are more complicated.  Excel requires that all cells in the range have the same size (i.e. if one is merged, then all should be merged and have the same width/height).  Checking whether is feasible to do the same.
