### ISSUE TITLE
Default Cell Style

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#2417]
### Desired behavior

Ref: [UV Item](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/16042318-spreadsheet-default-cell-format)

The Spreadsheet should expose a `defaultCellStyle` configuration option with the following children properties (see [cells](http://docs.telerik.com/kendo-ui/api/javascript/ui/spreadsheet#configuration-sheets.rows.cells)):
- `background`
- `color`
- `fontFamily`
- `fontSize`
- `italic`
- `bold`
- `underline`
- `wrap`

These styles should be applied as initial style to all cells.

**Comment by vladimirivanoviliev** [comment]
Inserting column / row does not take into account the default styles.

**Comment by ipeshev** [comment]
We should consider how those defaultCellStyle will work, those will be valid for all cell or only for cell without any style ?
