### ISSUE TITLE
Column is not expanded after new data source is set

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#2420]
The issue can be reproduced here:

http://dojo.telerik.com/ONUcA

1. Load the page
2. Collapse CEO
3. Click the button to set new dataSource.
4. Observe the effects.

**Comment by gyoshev** [comment]
Caused when there are locked columns -- the container height is not synchronized after `setDataSource`:

![image](https://cloud.githubusercontent.com/assets/90405/20050879/8430328a-a4d4-11e6-9dc0-e7083a1ca830.png)

**Comment by gyoshev** [comment]
Happens because the component height is not explicitly set, [as documented](http://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance#locked-columns). Specifying its height [resolves the problem](http://dojo.telerik.com/ONUcA/2).
