### ISSUE TITLE
Add noDataTemplate and clear messages for dropdown widgets and enable modifying them via kendo messages files

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2424]
Enhance the AutoComplete, ComboBox, DropDownList, and MultiSelect widgets with the opportunity to take the text for the noDataTemplate option from the messages files for the corresponding current culture, when this configuration option is not explicitly set.

**Comment by veselints** [comment]
PR: https://github.com/telerik/kendo/pull/9895
