### ISSUE TITLE
Error occurs when a name is selected from the names DropDown(imported file).

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2436]
### Bug report

Error occurs when a name is selected from the names DropDown. The issue was reproduced with an imported file.

### Reproduction of the problem

The issue can be reproduced with a file from the following ticket: 1073755.

Import the file and change the names from the DropDown, the error occurs sometimes after two or three changes and the browser locks:

![spreadsheet](https://cloud.githubusercontent.com/assets/11087921/20218553/d9d95ab6-a82d-11e6-854b-5b875c64fb46.PNG)

### Environment

* **Browser:** [all ]

**Comment by mishoo** [comment]
I also pushed some [additional VLOOKUP fixes](https://github.com/telerik/kendo/commit/13ca1384d9f3d8e6f9b1482bbe7d4985bf85524f) that are necessary to properly load the file from the referenced ticket.  They will be available in the next internal build.
