### ISSUE TITLE
Editor does not wrap content correctly on iOS

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2438]
### Bug report

Kendo UI Editor does not wrap words as expected, instead, very long words stick out of the content element:

<a href="http://tinypic.com?ref=2jbsa6c" target="_blank"><img src="http://i66.tinypic.com/2jbsa6c.png" border="0" alt="Image and video hosting by TinyPic"></a>

As a work around you may apply a CSS rule `word-break: break-all;`, however, it will break a word in two if it is too long to fit on the same line:  

```
var editor = $("#editor").kendoEditor().data("kendoEditor"); 
editor.body.style.wordBreak = "break-all";
```

### Reproduction of the problem

Test it on an iOS device, does not reproduce on simulators nor on Android phones.

[Dojo](http://dojo.telerik.com/iYaZi)
[Fullscreen](http://runner.telerik.io/fullscreen/iYaZi)

### Expected/desired behavior

Editor should wrap content/break words

### Environment

* **Kendo UI version:** 2016.3.1028
* **Browser:** [ iOS XX Safari ]

**Comment by Dimitar-Goshev** [comment]
R2 2018 SP1 Editor on iOS Safari breaks to a new line parts of words, which are not fitting on the current line. This behavior is expected and mentioned in the issue's description: 

> As a work around you may apply a CSS rule word-break: break-all;, however, it will break a word in two if it is too long to fit on the same line.

Upon testing the R2 2018 SP1 version, it seems that if word-break is not set at all, the above issue is not reproducible anymore. And the word breaking issue is not reproducible as well.

We should retest the current state without applying word-break.
