### ISSUE TITLE
Render ARIA attributes for Grid command buttons

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#2443]
### Current behavior
Grid command buttons are rendered as simple `<a>` tags with no ARIA attributes. See [Inline Editing](http://demos.telerik.com/kendo-ui/grid/editing-inline) example.

### Expected/desired behavior
The buttons should be marked with `role="button"` as a minimum. See [Using the button role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role).

**Comment by vladimirivanoviliev** [comment]
Suggested change is valid one as the [`button`](https://w3c.github.io/aria-practices/#button) role more precisely describe the Grid commands than the [`link`](https://w3c.github.io/aria-practices/#link) role. 

**Link role:**
A link widget provides an interactive reference to a resource either locally in the application or to an external resource.

**Button role:**
A button is a widget that enables users to trigger an action or event, such as submitting a form, opening a dialog, canceling an action, or performing a delete operation.

**Comment by vladimirivanoviliev** [comment]
Fixed in: 1449be7

**Comment by ipeshev** [comment]
It looks fine, should we consider refactor also those [buttons](http://demos.telerik.com/kendo-ui/grid/filter-row) @tsvetomir , @vladimirivanoviliev ?
