### ISSUE TITLE
Copy and paste does not work if Enter is pressed after a value is set in a blank cell

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2444]
### Bug report

Copy and paste does not work if Enter is pressed after a value is set in a blank cell.

### Reproduction of the problem

The issue can be reproduced in our demos.

Steps:

Enter a number into a blank cell
Hit Enter
Hit Up Arrow to move back into the cell into which you just typed a number
Copy the cell
Paste the cell into a different blank cell
At this point, copy/paste is broken for the entire spreadsheet.

Please refer to the following screencast provided in the ticket:

http://www.screencast.com/t/BqcqnKb4TMqF

### Environment

* **Kendo UI version:** 2016.3.1028 - version 2016.3.914 is working as expected
* **Browser:** [all]

**Comment by tapopov** [comment]
Fixed
