### ISSUE TITLE
After inserting more than 50 rows in the active sheet, the row selections is not working as expected.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2448]
### Bug report

After inserting more than 50 rows(more or less) in the active sheet, the row selection is not working as expected.

### Reproduction of the problem

The issue can be reproduced in the following Dojo example: http://dojo.telerik.com/AYIVI.

1) Click the insert button.
2) Scroll to row 52 and click on it.
3) Notice that it is showing the incorrect row.

The issue is caused by the following commit:  [b59bedb](https://github.com/telerik/kendo/commit/b59bedbba30cd7266acd298ed1ba9f2ca71abd63)

**Comment by ipeshev** [comment]
The bug is still present http://dojo.telerik.com/AYIVI/4 , can you please check
