### ISSUE TITLE
The JSP TreeView's id is rendered in the widget's ul element instead of the div element 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2449]
### Bug report

The JSP TreeView renders its id in the ul element, whereas the jQuery TreeView widget renders it in the div element. 

### Reproduction of the problem
Inspect the widget's HTML elements in the browser's dev tools.

### Current behavior
Inconsistent id attribute rendering in jQuery and JSP.   

### Expected/desired behavior
Consistent id attribute rendering in jQuery and JSP.  

### Environment

* **Kendo UI version:** 2016.3.1028
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by jivanova** [comment]
We've thoroughly researched the issue. So, straight to the point - when a TreeView widget is initialized via **ul** element, the id is set to the **ul** element:: https://demos.telerik.com/kendo-ui/treeview/index

As for the JSP wrapper:

- when the TreeView has defined `<kendo:treeView-items>` - the id will be set to the **ul** element. 
- when the TreeView is bound to `<kendo:dataSource>` - the id will be set to the **div** element.

The issue will be marked as **Won't fix** as this is the expected TreeView behavior.
