### ISSUE TITLE
Resizing doesn't work properly when Window is appended

### ISSUE THREAD

**Issue by vasiliy0** [telerik/kendo-ui-core#245]
How it behaves when appended to such container, just try to resize: http://dojo.telerik.com/@vasiliy0/ecoc/4

**Comment by gyoshev** [comment]
Thank you for reporting this. Reduced sample [available here](http://dojo.telerik.com/@gyoshev/Olodi).

**Comment by cahidaydin** [comment]
in this example if the window container on top resize works as expected.
http://dojo.telerik.com/EkocEP

**Comment by dimodi** [comment]
The initially reported scenario works as expected with the latest Kendo UI version:

http://dojo.telerik.com/egATu

However, two other scenarios still don't work. Here they are:

1. http://dojo.telerik.com/agISU (Window is appended to a static container after some other content. Same scenario, as reported by @cahidaydin )
1. http://dojo.telerik.com/UZoJOK (Window is appended to a positioned container with margins. Will work if the appendTo container is static (i.e. no position:relative style))
