### ISSUE TITLE
Need explanation of these style files

### ISSUE THREAD

**Issue by stanleyxu2005** [telerik/kendo-ui-core#2452]
Regarding the readme, I should include at least `kendo.common.min.css` and `kendo.default.min.css`. 

Actually I'm building a minimal distribution for my own Bootstrap 4 project, which just need the splitter control. What is the minimal style sheets, I need to use? I dont really see the difference, but I'd like to know, if I should include these two? `kendo.bootstrap.min.css` and `kendo.common-bootstrap.core.css`.

Advise is really highly appreciated.

**Comment by MilenaCh** [comment]
Here you can add your feature requests and bug reports, but for consulting purposes I would suggest you to open a support ticket and explain the issue in it. Our support officers will provide the needed information as soon as possible.
