### ISSUE TITLE
Scrollable Grid header and content tables misaligned when tabbing through filter inputs in "row" filtering mode

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2453]
### Bug report

Grid header scroll via tabbing between the AutoComplete inputs in "row" filtering mode causes an offset between the header and content tables when there is a horizontal scrollbar present.

### Reproduction of the problem

[http://dojo.telerik.com/ofuBe/2](http://dojo.telerik.com/ofuBe/2)

### Expected/desired behavior

Header and content tables scrolling to be synced.

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by simonssspirit** [comment]
Issue connected to this behaviour is also reported in ticket: 1110044

The ticket contains an example, screenshot and detailed explanation.

**Comment by ag-petrov** [comment]
https://github.com/telerik/kendo/commit/7e3e851358568b0e00224d1b5aa4741a158e0aaf
