### ISSUE TITLE
Incorrect mobile Grid height in Material and Materia Black after paging

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#2454]
### Bug report
The problem is reported initially [here](http://kendoui-feedback.telerik.com/forums/127393/suggestions/17175671).

### Reproduction of the problem
1. Use the following [Dojo snippet](http://runner.telerik.io/fullscreen/iYesoq/5) with Chrome Simulator.
2. Change Grid's page using the dropdownlist in the middle of the Pager.

### Current behavior
Grid's height is reduced:
![image](https://user-images.githubusercontent.com/6614183/33213932-63bce314-d132-11e7-885c-45775c4b3b12.png)

### Expected/desired behavior
Grid's height should stay the same:
![image](https://user-images.githubusercontent.com/6614183/33213946-6ecf55d4-d132-11e7-848c-0c03cc6d3f23.png)

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** All
* **Browser:** All

**Comment by MilenaCh** [comment]
The issue does not exist with the latest KendoUI version - 2019.2.514(R2 2019).
