### ISSUE TITLE
Expose a NoDataTemplate() method in the widgets' wrappers

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2455]
### Еnhancement

Expose a NoDataTemplate() method in the wrappers of the widgets that support the noDataTemplate configuration option.

### Reproduction of the problem
Currently such methods are not exposed, but the noDataTemplate can still be set through the widget's setOptions method. 

### Environment

* **Kendo UI version:** 2016.3.1028
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by zdravkov** [comment]
It was working correctly with latest version.
