### ISSUE TITLE
The Display attribute is ignored and the property name is used as a title for the Spreadsheet columns

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2457]
### Bug report

The Spreadsheet ignores the Display or DisplayName:  [Display(Name = "Unit price")] attribute and uses the property name, "UnitPrice" for example, as a column title. 

### Reproduction of the problem
The issue can be reproduced in the [DataSource binding](http://demos.telerik.com/aspnet-core/spreadsheet/datasource) demo. 

### Current behavior
The Display attribute is ignored. 

### Expected/desired behavior
The string set in the attribute is used as a column title. 

### Environment

* **Kendo UI version:** 2019.3.1023

**Comment by gyankov** [comment]
The sheets of the Spreadsheet are not generic, thus, during the serialization of the component we are not aware of model the current sheet will bind to. So getting the title specified via data annotations is not possible.

Also, the dataSource bound Spreadsheet generates the header row automatically and custom titles are not supported at this point.

I have logged an enhancement for the Spreadsheet to expose an API for the header row:

- https://github.com/telerik/kendo-ui-core/issues/6414

Once the above enhancement is implemented, users will be able to get the value from the Display attribute with reflection and set it as a title.
