### ISSUE TITLE
Clipboard no longer works in the spreadsheet after pressing SPACE

### ISSUE THREAD

**Issue by mishoo** [telerik/kendo-ui-core#2459]
Select any cell and, without entering edit mode, press SPACE.  After that copy/paste no longer works on this spreadsheet instance.

**Comment by ipeshev** [comment]
The first SPACE and Ctrl+C doesn't work, try to put some string in the clipboard and then load http://dojo.telerik.com/AYIVI/6 try to SPACE and Ctrl+C something and then just paste in some cell it is still initial content of the clipboard.

**Comment by mishoo** [comment]
Can't repro on master. Please reopen if I'm missing anything.
