### ISSUE TITLE
Close open ContextMenu when a different one opens

### ISSUE THREAD

**Issue by jajdoo** [telerik/kendo-ui-core#246]
When multiple context menus exist, opening a new menu without choosing an option on the previous one means +1 open menus.
I would suggest forcing other context menus to close when one opens.

**Comment by wfsm** [comment]
@bundyo The fiddle is still showing two opened ContextMenu now. Do I misunderstand?

**Comment by KirilNN** [comment]
Hi @wfsm,

The fiddle uses an old version where the fix is not present. Please use the latest version for testing.

**Comment by wfsm** [comment]
@bundyo I'm using the latest pro version. My problem is I have to different context menu for a treeview(one for node with children, one for node without children), if I don't click any item on first context menu then show another context menu, the first context menu doesn't remove from the DOM
