### ISSUE TITLE
Time slider in MediaPlayer is not updated upon selection of another video from playlist.

### ISSUE THREAD

**Issue by EduardoSerra** [telerik/kendo-ui-core#2463]
### Bug report

When using the playlist functionality of the Media Player, the time slider will not change upon selecting different videos.

### Reproduction of the problem

1. Go to the [MediaPlayer playlist demo](http://demos.telerik.com/kendo-ui/mediaplayer/playlist) in our website.
2. After the video is playing, select any other video in the playlist to the right.

### Current behavior

The time slider reflects the length of the first video played and goes beyond the limit if the video currently being played is longer than the original one.

### Expected/desired behavior

The time slider should update.

### Environment

* **Kendo UI version:** 2016.3.1118
* **Browser:** all

**Comment by MilenaCh** [comment]
This issue has been resolved in R1 2017.
