### ISSUE TITLE
Progress indicator of TabStrip is not displayed correctly

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#2465]
### Reproduction of the problem
The issue is observed in this [dojo page](http://dojo.telerik.com/@zdravkov/UDexo) where starting from Q3 2016 the progress indicator of the TabStrip is no longer correctly displayed. 

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** x.y
* **Browser:** all

**Comment by KevinMWood1** [comment]
I am disappointed not to see any movement on this issue - it is existing functionality missing from the recent releases and is preventing us from updating to the latest version

**Comment by lenardchristopher** [comment]
I would also like to push for an update on this issue after no progress in over a month.

**Comment by joneff** [comment]
The bug was caused by "leaking" (unscoped) styles in another control. We've fixed it and the fix will make it in the next major release of Kendo, due out later in January.

**Comment by KevinMWood1** [comment]
Thanks

Looking forward to testing it out when the next release is issued.

Regards
Kevin
