### ISSUE TITLE
Hidden rows are not hidden after export to excel file

### ISSUE THREAD

**Issue by ivanchev** [telerik/kendo-ui-core#2466]
This can be reproduced in the online demo at http://demos.telerik.com/kendo-ui/spreadsheet/index
1. Open the demo
2. Select a Row and Right Click-> Hide the Row
3. Export the spreadsheet to Excel
4. Now open the exported file in Excel.   The hidden row is visible (not hidden).

Expected/desired behavior:
The row should be hidden. Hiding the columns works as expected. The issue is only observed when hiding rows.

**Comment by jwbqv** [comment]
Did this perhaps / hopefully actually make it into 2017.1.18?  It says passed QA but the milestone still says 2016.R3.SPnext.     Thank you.

**Comment by ivanchev** [comment]
The fix did make it into the 2017.1.18 release, and I fixed the wrong milestone.
