### ISSUE TITLE
Security trimming does not work when duplicate controllers are used

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#2468]
### Reproduction of the problem

Run the attached test project.

[MvcApplication4.zip](https://github.com/telerik/kendo-ui-core/files/605817/MvcApplication4.zip)

Reported in TicketID: 896351

### Environment

* **Kendo UI version:** 2019.1.115
* **jQuery version:** 1.12.3
* **Browser:** all

**Comment by Iankodj** [comment]
The Security Trimming works with the context provided in MVC and the verification comes from the running the authorization against each controller given. Therefore, if a controller is returned as authorized there is no additional rules we can count on to hide/disable the generated item. 

I suggest to take a look at this option to achieve similar behavior without security trimming and see whether this provides a better solution for the case: https://github.com/telerik/kendo-ui-core/issues/5013#issuecomment-497675361.
