### ISSUE TITLE
kendo.ui.MaskedTextBox: virtual keyboard suggestions on mobile devices bypass mask

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#2469]
### Bug report

Virtual keyboard suggestions on mobile devices bypass mask

### Reproduction of the problem

1. Create a web page with a MaskedTextBox with a mask;
2. Run it on Safari in iOS 10 (iPhone or iPad);
3. Select a keyboard suggestion (at the top of the virtual keyboard on iOS10);
4. It gets copied into the textbox, bypassing the mask rules.

### Environment

* **Kendo UI version:** 2016.3.1028

**Comment by ggkrustev** [comment]
This is a duplicate report to this issue - https://github.com/telerik/kendo-ui-core/issues/154

I will close this one. You can continue the discussion in the related thread.
