### ISSUE TITLE
Spreadsheet exported Excel RowHeight and ColumnWidth does not match to the imported custom ones.

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#2471]
### Reproduction of the problem
Set custom ColumnWidth and RowHeight in an Excel file. Import it in the Spreadsheet. Export the sheet in new Excel file.

### Current behavior
If certain Excel file with custom ColumnWidth or/and RowHeight is imported to the Spreadsheet and after that exported to Excel file - the ColumnWidth and RowHeight are not matching the original values.

### Expected/desired behavior
The ColumnWidth and RowHeight in the exported Excel file should be the same as the imported one

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

Video: [http://www.screencast.com/t/oAvj9ZMjU](http://www.screencast.com/t/oAvj9ZMjU)

**Comment by jwbqv** [comment]
Hello, are there any updates or plans for resolving this issue?  Thank you.
