### ISSUE TITLE
shapeMouseEnter event fires only for the last shape layer defined

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2473]
### Reproduction of the problem
1. Open this dojo: http://dojo.telerik.com/Idewo;
1. Open the console;
1. Hover over the shape in the shape layer - no console.log
1. Hover over the shape in the bubble layer - there is console.log

### Expected/desired behavior
shapeMouseEnter to raise for all shape-based layers.

### Environment

* **Kendo UI version:** 2016.3.1028
* **Browser:** [all ]

**Comment by Stamo-Gochev** [comment]
The events are supposed to be working with a single shape layer only due to the rendering of the layers as different `div.k-layer` elements, which implies that only the last one will trigger events.
