### ISSUE TITLE
When editing cell the next cell is not focused when pressing Tab in Chrome and Firefox

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2475]
### Reproduction of the problem
When you are editing a cell and press Tab, the focus goes to the clipboard instead of the next cell - [screencast](http://screencast.com/t/rqowyvcolvap)

### Current behavior
The next cell is not focused. The focused element is the iframe of the clipboard.

### Expected/desired behavior
The next cell should be focused.

### Environment

* **Kendo UI version:** 2017.1.22
* **Browser:** [ Chrome | Firefox  ]

**Comment by hema7760** [comment]
i have got same error. how to resolve this ? i couldn't find any solution to the problem mentioned above.
