### ISSUE TITLE
The axisCrossingValues property of the Chart is not working as expected

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2479]
### Bug report

The axisCrossingValues property of the Chart is not working as expected.

### Reproduction of the problem

The issue can be observed in the following Dojo example: http://dojo.telerik.com/UbUnE

The issue occurs after this [commit](https://github.com/telerik/kendo/commit/0940b04fde514bca0ad7c001057f2b37b7fe47ab)

### Environment

* **Kendo UI version:** 2016.3.914 and newer
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by tsvetomir** [comment]
Another test case by customer:
http://dojo.telerik.com/@tsvetomir/AlENI
