### ISSUE TITLE
When closing Drawer clears the view style attribute

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-ui-core#2483]
### Bug report
When closing the drawer widget clears the view style attribute

### Reproduction of the problem
Can be observed in this dojo: `http://dojo.telerik.com/OROGAZIT/2`

### Expected/desired behavior
Drawer widget should not clear a view style attribute

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by sspasova** [comment]
Closing this as the mobile suite is now deprecated. You can read more information here: https://docs.telerik.com/kendo-ui/controls/hybrid/introduction
