### ISSUE TITLE
AutoCompleteFor client side validation from DataAnnotations does not work

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2485]
### Reproduction of the problem

In ASP.NET Core The AutoCompleteFor does not respect the [Required] DataAnnotation of the Model.

Use the following files to create a sample form which has DropDownListFor and AutoCompleteFor and only DropDownListFor is validated
[AutoCompleteFor View,Model,Controller.zip](https://github.com/telerik/kendo-ui-core/files/613602/AutoCompleteFor.View.Model.Controller.zip)

**Comment by JoshRefactored** [comment]
Guys, Has this been addressed yet??

**Comment by gusdewa** [comment]
Any updates for this open issue?

**Comment by TsvetinaIvanova** [comment]
Also reported in: 1146268
