### ISSUE TITLE
Excel grid toolbar not i18n

### ISSUE THREAD

**Issue by XavierDupessey** [telerik/kendo-ui-core#2486]
Hello,

The "Export to Excel" label is in english whereas I set the Kendo culture to french.
Other gird labels like filters ones are displayed in french, so I guess this is a bug?

![kendo_grid_excel_label](https://cloud.githubusercontent.com/assets/1449888/20661598/e8ea8f82-b54f-11e6-9752-ccd7ab71260b.PNG)

Kendo UI version: 2016.3.914
jQuery version: 1.12.3
Browser: all

Xavier

**Comment by Dimitar-Goshev** [comment]
Not reproducible with 2023.3.1114 - https://dojo.telerik.com/@Dimitar-Goshev/adArACit
