### ISSUE TITLE
Pager should list page numbers side by side

### ISSUE THREAD

**Issue by hiyelbaz** [telerik/kendo-ui-core#2490]
### Reproduction of the problem
Edit this example http://demos.telerik.com/kendo-ui/listview/editing
change `kendo.common.min.css` to `kendo.common.core.min.css` (core version)

### Current behavior
Page numbers are listed vertically.

### Expected/desired behavior
Page numbers should be listed horizontally.

### Environment
Kendo UI version: 2016.3.1118 core edition
jQuery version: 1.9 / 2.2.4
Browser: all

**Comment by tsvetomir** [comment]
What you're experiencing is expected, the 'core' styles don't include the styles for the Grid. They're include only the [Core](https://github.com/telerik/kendo-ui-core#features-of-kendo-ui-core) widgets.

You need the full stylesheet in this case.

**Comment by hiyelbaz** [comment]
It's a Listview which is included in core widgets.

**Comment by tsvetomir** [comment]
Sorry, my bad - reopening.

**Comment by hiyelbaz** [comment]
Thanks. It would be great if you provide a workaround in the short-term.

**Comment by inikolova** [comment]
Commit: 7d6f955c4a88d712

**Comment by hiyelbaz** [comment]
http://runner.telerik.io/fullscreen/IREMok

This patch will list page numbers horizontally. However, responsive styles are still missing. Dropdown page number widget fails on narrow screens.

**Comment by hiyelbaz** [comment]
The issue is still exists.

**Comment by inikolova** [comment]
Hi, I will investigate the case and provide a fix in a short period of time
