### ISSUE TITLE
IE 11 freezes on initial load and reports "Long-running script" when referencing kendo.common.min.css and kendo.mobile.all.min.css from Kendo CDN service in MVC 5 project

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2491]
### Bug report
IE 11 freezes on initial load and reports "Long-running script" when referencing kendo.common.min.css and kendo.mobile.all.min.css from Kendo CDN service in MVC 5 project.

### Reproduction of the problem
- Create a Telerik ASP.NET MVC Application;
- Include references to the kendo.common.min.css and kendo.mobile.all.min.css from CDN (if not included);
- Run the project in IE 11;
- Try to interact with content - you will notice that browser freezes;
- If you open the F12 Developer tools, reload page and try to click a control on it, it reports "localhost is not responding due to long-running script";
- After a while, it warns "Could not locate https://kendo.cdn.telerik.com/source/mobile/kendo.mobile.all.css specified in source map https://kendo.cdn.telerik.com/2016.3.1028/styles/kendo.mobile.all.min.css.map."

### Environment
* **Kendo UI version:** 2016.2.607 to 2016.3.1118 (tested)
* **Browser:** IE 11

**Comment by tsvetomir** [comment]
Likely related to #2460

**Comment by Dimitar-Goshev** [comment]
Closed due to inactivity.
