### ISSUE TITLE
The Grid Excel export is not working on Safari browser with local data binding.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2496]
### Bug report

The Grid Excel export is not working on Safari browser with local data binding.

The issue is not fixed using the approach suggested in the documentation:

http://docs.telerik.com/kendo-ui/controls/data-management/grid/excel-export#excel-export-is-not-working-in-internet-explorer-and-safari

### Reproduction of the problem

The issue can be reproduced in both Dojo`s: http://dojo.telerik.com/Ecuje and http://dojo.telerik.com/UMuyO

### Environment

* **Browser:** [Safari XX ]

**Comment by silvangithub** [comment]
Looks like it is working now. (fixed on Apple's end!?). Tested using Safari Version 10.1 (12603.1.30.0.34).
Can someone double-confirm?

**Comment by MilenaCh** [comment]
On our end export functionaly works properly on Safari 11.1 on MAC device, however the problem still exist on IPAD and Iphone devices with the same version of Safari(11).

**Comment by ag-petrov** [comment]
Seems to work now. Adding for testing.
