### ISSUE TITLE
Wrong clear icon

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#2497]
### Reproduction of the problem
Clear icon is wrong for all components
![capture 2016-12-04 at 14 00 50](https://cloud.githubusercontent.com/assets/4143177/20793235/b8e08680-b7ce-11e6-9c14-d3c42ff1a16a.png)

### Expected/desired behavior
Clear icon should be something that is expressing "Clear"

### Environment

* **Kendo UI version:** 2016.3.1028
* **jQuery version:** N/A
* **Browser:** All

**Comment by Xizario** [comment]
@MilenaCh, seems this is already fixed, will you close it?

**Comment by Dimitar-Goshev** [comment]
Already fixed: http://demos.telerik.com/kendo-ui/combobox/addnewitem
