### ISSUE TITLE
Wrap cell text on word boundaries

### ISSUE THREAD

**Issue by Jekata** [telerik/kendo-ui-core#2501]
### Description of the improvement
The word wrapping on the spreadsheet when a piece of text is centered doesn't throw the next whole word onto a new line, but will wrap by character.  The latest version of excel does wrap by whole word as opposed to by character.  

When the column is wide enough to accommodate the longest word, but not wide enough to accommodate the entire sentence.

In this situation Excel line breaks at the spaces.

In the Kendo spreadsheet, it line breaks in the middle of words.

See this screenshot how the spreadsheet differs from MS Excel when wrapping and centering the cell contents:
![jquery spreadsheet control example _ kendo ui spreadsheet demos](https://cloud.githubusercontent.com/assets/5063488/20828896/5a4c60ee-b882-11e6-9755-cb8bce9ed4bf.png)

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** any
* **Browser:** [all]
* **Public item:** [https://github.com/telerik/kendo-ui-core/issues/2501](https://github.com/telerik/kendo-ui-core/issues/2501)
* **Ticket:** 1067833

**Comment by jwbqv** [comment]
I see that this was moved into 2418 on Dec 5; and that 2418 is tagged as a milestone for 2017.1.18;  does that mean this is fixed in 2017.1.18?
