### ISSUE TITLE
Unwanted scrollbar repositioning when clicking on a TreeView node's span or li elements (IE) 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2502]
### Bug report

In IE if the TreeView is higher than the visible window area clicking on its node (either the span or the li element) results in a change in the container's scroll position. 

### Reproduction of the problem
Reproducible in the [demos](http://demos.telerik.com/kendo-ui/treeview/odata-binding). 
[Screenscast](http://www.screencast.com/t/AwqKX7Xi4EQe)

### Current behavior
Change of scroll position. 

### Expected/desired behavior
On node click the scroll position remains unchanged. 

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** x.y
* **Browser:** [IE11 ]

**Comment by Renegade1821** [comment]
any news here? I'm facing a similar problem

**Comment by jivanova** [comment]
Duplicated. Use this one for reference: https://github.com/telerik/kendo-ui-core/issues/3059. @Renegade1821  - For the time being, you could use the workaround referenced in the above issue
