### ISSUE TITLE
Recurrence rule for every X days/weeks does not recreate events correctly

### ISSUE THREAD

**Issue by antonpopov** [telerik/kendo-ui-core#2503]
### Reproduction of the problem
Take a look at the sample [dojo](http://dojo.telerik.com/eDUlI) where the problem is reproduced.

### Current behavior
[Screenshot](http://www.screencast.com/t/NFXRABBQ72)

### Expected/desired behavior
[Screenshot](http://www.screencast.com/t/dqRF0V9B0e)

**Comment by antonpopov** [comment]
ticket: 1076939

**Comment by veselints** [comment]
This appears to be Culture dependant. The problem could be observed between the year 2016 and 2017 for Swedish culture (se-SE), but not for the default: [Dojo](http://dojo.telerik.com/eDUlI/10)
