### ISSUE TITLE
Theme builder is not working on Safari.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2504]
### Bug report

Theme builder is not working on Safari.

Error: POST http://demos.telerik.com/kendo-ui/service/export 500 (Internal Server Error)

### Reproduction of the problem

The issue can be reproduced in the Theme builder site: http://demos.telerik.com/kendo-ui/themebuilder/

It may be related to- https://github.com/telerik/kendo-ui-core/issues/2496

### Environment
* **Browser:** [Safari]

**Comment by Dimitar-Goshev** [comment]
The error is no longer reproducible - https://demos.telerik.com/kendo-ui/themebuilder/
