### ISSUE TITLE
Incorrect default font export in Spreadsheet  

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2505]
### Bug report

The default Spreadsheet cell font (Arial) and size (12) are not exported correctly unless the cell's font is first changed to another font and then set back to Arial. 

### Reproduction of the problem
Reproducible in the following [dojo](http://dojo.telerik.com/) example.
- Enter some text in two different cells. Change the second cell's default font and then set it back to Arial and also set its size to 14.  

- Export to Excel. The first cell's font in the xlsx file is Calibri, size is 11. The second one's is Arial, size 14 as expected. 

### Current behavior
The cell's default font and size are not exported correctly. 

### Expected/desired behavior
The cell's default font and size are exported. 

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by mishoo** [comment]
The fix for this depends on https://github.com/telerik/kendo-ui-core/issues/2417, which will only land in the next major release.
