### ISSUE TITLE
Delete button is not present in the Edit pop-up of reoccurring event

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2514]
### Bug report
Inconsistent Delete functionality of reoccurring event:
The Delete button is not present in the Edit pop-up of reoccurring event. However, after editing the above event, saving the changes and opening again the Edit pop-up, the Delete button is present. The user can also delete the occurrence using the X button, rendered on the appointment itself.

### Reproduction of the problem
1. Go to [Basic usage demo](http://demos.telerik.com/kendo-ui/scheduler/index)
1. Create a series of reoccurring events
1. Start editing a single occurrence

### Current behavior
The "Delete" button is not present
NOTE: If the occurrence becomes a recurrence exception, the Delete button will be visible.
1. Change one of the properties of the event (for example its start time);
1. Save changes;
1. Open to edit the same event;
1. The "Delete" button is now present;

### Expected/desired behavior
The "Delete" button should always be present in the Edit form, when editing reoccurring event;

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
Reported in a duplicate issue and in ticket 1445147 . Increasing priority.
