### ISSUE TITLE
Increase Spreadsheet cell left/right-padding

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-ui-core#2515]
Let's update the side padding of Spreadsheet cells to avoid *italic* text overflow.

Current styles: 

```html
.k-spreadsheet .k-spreadsheet-pane .k-spreadsheet-cell {
    padding: 1px;
}
```

Suggestion: 

```html
.k-spreadsheet .k-spreadsheet-pane .k-spreadsheet-cell {
    padding: 1px 3px;
}
```

**Comment by dimodi** [comment]
@mishoo Can you please comment if this padding change is feasible to implement also in the PDF exporting mechanism and if it makes any notable difference in standard use cases (e.g. not too large font-sizes and not too slanted glyphs)? If there is a sensible benefit, we will be able to improve the Spreadsheet appearance and avoid support tickets such as 1076639. Thank you.

**Comment by mishoo** [comment]
I'm not sure an increase of only 2 pixels will be sufficient; the customer exemplified clipping with some really big fonts.

But whatever the amount, I should be able to accomodate it in PDF export, no problem.

**Comment by dimodi** [comment]
This is true, but nevertheless, we could resolve the more common use cases.

Is this the correct change to be made, assuming a new side padding of 3px instead of 1px?

https://github.com/telerik/kendo/blob/master/src/spreadsheet/print.js#L454

        var rect_left   = cell.left   + 4;
        var rect_top    = cell.top    + 2;
        var rect_width  = cell.width  - 8;
        var rect_height = cell.height - 4;

**Comment by mishoo** [comment]
@dimodi yep, for padding `1px 3px` instead of `1px`, that seems correct.

**Comment by dimodi** [comment]
@mishoo Thank you.
