### ISSUE TITLE
The editable Grid does not have all of the needed aria attributes for the edited column.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2516]
### Bug report

The editable Grid does not have aria attributes for the edited column name. This is creating a scenario where the user does not know which is the currently edited column.

### Reproduction of the problem

The issue can be reproduced in our demo using NVDA or JAWS screen readers:

http://demos.telerik.com/kendo-ui/grid/editing-inline

### Environment

* **Browser:** [all]

**Comment by simonssspirit** [comment]
Also, another issue related to the Grid accessibility is that a filterable Kendo Grid header name read by JAWS includes a large amount of whitespace. The issue is reported by the same customer in ticket: 1078193.

**Comment by simonssspirit** [comment]
Another issue with the Grid accessibility reported on the similar subject:

When a Kendo Grid column is filterable, the text inputs in the filter options have no name as read by screen readers.

Ticket: 1078444

![c2952960-33eb-47f7-9719-ad68ff067866_filterinput](https://cloud.githubusercontent.com/assets/11087921/21010070/c8da050a-bd52-11e6-9e43-434f26868ff5.png)

**Comment by tsvetomir** [comment]
@simonssspirit please open separate issues for the related problems in the comments

/cc @vladimirivanoviliev

**Comment by simonssspirit** [comment]
A new issue is created for ticket: 1078444 / issue: https://github.com/telerik/kendo-ui-core/issues/2555
New information is requested from the customer for ticket: 1078193, a new issue will be created when the information is available.

**Comment by boyandim** [comment]
JAWS does not read the column name in edit mode in IE browser. It only reads the cell content.  Please refer to the http://runner.telerik.io/fullscreen/eYaka/3 example.
