### ISSUE TITLE
Stacking UP does not position properly the notifications one over another

### ISSUE THREAD

**Issue by Jekata** [telerik/kendo-ui-core#2517]
### Bug report
The Stacking: "up" setting does not position properly the notifications one over another. This is a regression in the latest version.

### Reproduction of the problem
1. Go to [http://demos.telerik.com/kendo-ui/notification/position-stacking](http://demos.telerik.com/kendo-ui/notification/position-stacking) on Opera, Chrome and Firefox.
2. Choose one of the following themes Nova, Metro, Default
3. Change the Notification stacking combo to Up.
4. Click several times the Show Notification button to see the issue.
5. You'll see that the new notification are not placed exactly over the priors ones as shown in this video:
Video: [http://screencast.com/t/UQgpES8bt](http://screencast.com/t/UQgpES8bt)

### Environment

* **Kendo UI version:** 2016.3.1118
* **Browser:** [Chrome, Firefox and Opera ]

**Comment by weaponready** [comment]
i have the same problem 😢

**Comment by TehWardy** [comment]
I've spent the last 2 hours thinking I screwed something up ... Apparently not!

I got round it by templating the notifs and off-setting in a div inside the kendo generated notif itself but that's an ugly hack and involves overriding a lot of kendo stuff to make it work.
It looks like when you use bottom and right positioning for some reason kendo chooses to pos using top and left so i'm guessing this is some sort of rounding error in the position calculation code.

**Comment by TehWardy** [comment]
@jivanova The deployment of this milestone doesn't appear to have worked.
According to: http://dojo.telerik.com/ the scripts in question are at ...
  http://kendo.cdn.telerik.com/2017.1.117/js/angular.min.js
  http://kendo.cdn.telerik.com/2017.1.117/js/jszip.min.js
  http://kendo.cdn.telerik.com/2017.1.117/js/kendo.all.min.js

These links appear to be broken.
Is there an ETA on this?

**Comment by petyosi** [comment]
@TehWardy we are releasing the R1 milestone right now, the assets should be available by the end of the day.

**Comment by TehWardy** [comment]
Ah thanks @petyosi  hopefully I'll be able to confirm the fix pretty fast as it's an area i'm actively looking at in our UI framework at the moment.

**Comment by tsvetomir** [comment]
Should be fixed now, notice that the version is 2017.1.118

**Comment by TehWardy** [comment]
Fix confirmed with version 2017.1.118 ... thanks guys :)
