### ISSUE TITLE
Inconsistent behavior of the Bold, Italic, Underline commands in IE11

### ISSUE THREAD

**Issue by Jekata** [telerik/kendo-ui-core#2518]
### Bug report
Highlighting text in IE11 and then hitting the format buttons (bold, italic, underline, etc) does not work consistently.  Sometimes you can highlight text and it'll format, other times it won't.  Sometimes we can hit "Enter" and create a new line and the formatting that wasn't previously visible when highlighting is visible on the next line.

We've been able to reproduce this on different machines using the library on our website and we've been able to replicate this same inconsistent behavior on the demos on the Telerik site: http://demos.telerik.com/kendo-ui/editor/index

### Reproduction of the problem
See the attached video: 
[2016-12-06 14-24-30.zip](https://github.com/telerik/kendo-ui-core/files/637244/2016-12-06.14-24-30.zip)

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** x.y
* **Browser:** [IE11, Chrome, Firefox ]

**Comment by nstoychev** [comment]
Reproducible in IE11, on Windows 10 in dojo.

IE version:
Version: 11.0.14393.0
Update Versions: 11.0.33

**Comment by Dimitar-Goshev** [comment]
Not reproducible with latest version 2017.1.223 on IE11. Tested in Dojo from the following [Demo](http://demos.telerik.com/kendo-ui/editor/index)
