### ISSUE TITLE
Bi-weekly recurrence error over New Year

### ISSUE THREAD

**Issue by joli80** [telerik/kendo-ui-core#2519]
### Reproduction of the problem
When a bi-weekly recurrence rule has WKST=MO the recurrence is incorrect after the passing over to a new year.

See example with start date 2016-12-14 and recurrenceRule "FREQ=WEEKLY;INTERVAL=2;BYDAY=WE;WKST=MO"

[Dojo](http://dojo.telerik.com/iWohi/3)

### Current behavior
Event dates are dec 14, dec 28, jan 4, jan 18, feb 1, ...

### Expected/desired behavior
Event dates should be dec 14, dec 28, jan 11, jan 25, feb 08, ....

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 1.12.3
* **Browser:** Chrome 54

**Comment by zdravkov** [comment]
The issue seems to be fixed in the latest version.
