### ISSUE TITLE
MinScreenWidth is not available in the API of Grid for ASP.NET Core

### ISSUE THREAD

**Issue by Jekata** [telerik/kendo-ui-core#2522]
### Bug report

When using ASP.NET MVC Core 1.0 the [MinScreenWidth method](http://docs.telerik.com/aspnet-mvc/api/Kendo.Mvc.UI.Fluent/GridColumnBuilderBase#methods-MinScreenWidth(System.Int32)) is not available:
columns.Bound(p => p.ProductName).MinScreenWidth(200);

### Environment

* **UI for ASP.NET Core:** 2016.3.1118

**Comment by dguinn-oncore** [comment]
Was this closed because it was fixed?  Or not a bug?

**Comment by ag-petrov** [comment]
It was a bug and was closed becaused it was fixed. I apologize for not including the additional details.
