### ISSUE TITLE
Gantt task summary is displayed incorrectly when the rowHeight is set and child task is moved

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-ui-core#2523]
### Reproduction of the problem
[Dojo example](http://dojo.telerik.com/uwawi/3). Also reproduced in [templates demo](http://demos.telerik.com/kendo-ui/gantt/task-template).
[Screencast](http://www.screencast.com/t/FosUHLkDMurO)

![Screenshot](https://cloud.githubusercontent.com/assets/5161281/21014112/55657d44-bd65-11e6-9bfd-6e38ae0e6113.png)

The issue is not reproducible when rowHeight is not set.

Reported in Ticket ID: 1077718

**Comment by Dimitar-Goshev** [comment]
This is another scenario for the following issue - https://github.com/telerik/kendo-ui-core/issues/5704 . Closing this one and adding comment and increasing priority of the other.
