### ISSUE TITLE
Having input in a sub menu item closes the popup on hover

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2526]
### Bug report

The bug is reproducible as of Chrome 55.0.2883.87 m. 

### Reproduction of the problem

http://dojo.telerik.com/usifaM

Run the dojo, open the submenu and hover the input inside. 

Actual: The popup closes immediately.

### Expected/desired behavior
Input to be editable as with other browsers. 

### Environment

* **Kendo UI version:** 2016.3.1028
* **jQuery version:** 1.12.4
* **Browser:** [Chrome 55.0.2883.87 m ]

**Comment by Alex-Bubblemaster** [comment]
Affects all filterable grids with column menus. Reported in ticket with ID 1080004.

**Comment by ErikTheGreat** [comment]
Workaround found here: http://www.telerik.com/forums/issue-with-grid-filter-(on-chrome-55-0-2883-75) dojo sample here: http://dojo.telerik.com/ipihu/16

**Comment by Alex-Bubblemaster** [comment]
@ErikTheGreat thank you for sharing this. The assigned software engineer has provided a fix, we still have some testing to do and you will be able to remove the workaround from your code shortly.

**Comment by lzr900515** [comment]
so how to solve it now without the workaround??? anyone can tell me the detail?

**Comment by Sebazzz** [comment]
I'm also curious, though one could argue this is a Chrome bug, not a Kendo bug.
