### ISSUE TITLE
ASP.NET Core Grid wrapper does not find editor templates if Dynamic View Location is applied

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#2527]
### Bug report

If the [View Location](https://msdn.microsoft.com/en-us/magazine/mt763233.aspx) is changed, the editor templates are not found by the Grid.

### Workaround

Add the full path to the editor, for example:

`
.Editable(e=>e.Mode(GridEditMode.PopUp).TemplateName("~/Areas/Admin/Views/Shared/EditorTemplates/Custom.cshtml"))
`

### Expected/desired behavior

The templates should be loaded correctly with the applied Dynamic View Location

**Comment by Alex-Bubblemaster** [comment]
#3492

**Comment by kdikov82** [comment]
The same problem is observed if the template is placed within the **Area** folder (instead of thew **Views** folder).

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket with ID 1154457. Raising priority.

**Comment by csharperperson** [comment]
Just curious for any updates on this. I have a large project with tons of EditorTemplates, It's getting pretty difficult to manage all of them in the single directory. Thanks guys! :)

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket with ID 1160335. Raising priority.

**Comment by simonssspirit** [comment]
Reported again in 1171498 
The issue was reproduced in a standard scenario:

1) Make a new project from the templates
2) Add editing
3) Add templates - the template is only loaded using the full path

Rising severity.

**Comment by ag-petrov** [comment]
It seems that this might be a framework problem. Already reported to Microsoft - https://github.com/aspnet/Mvc/issues/8526
