### ISSUE TITLE
Spreadsheet pasted in Excel overrides its default border

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-ui-core#2529]
### Bug report
Spreadsheet pasted in Excel overrides its default border

### Reproduction of the problem
1. Navigate to https://demos.telerik.com/kendo-ui/spreadsheet/index
1. Create a new sheet so there is no background previously applied to the cells and enter the the following values:

Test1  Test2
Test3  Test4

1. Copy cells that seemingly have no background color applied:

![image](https://user-images.githubusercontent.com/7202037/68754445-5e9f5d80-060f-11ea-9f1f-3d00e6a54ad9.png)

2. Paste into Excel

### Current behavior
Excel's default border is no longer visible:
![image](https://user-images.githubusercontent.com/7202037/68754495-7e368600-060f-11ea-87b2-15685bc5fdc8.png)

### Expected/desired behavior
The Excel's default border should be maintained

### Environment

* **Kendo UI version:** 2019.3.1023

**Comment by mishoo** [comment]
Looks like we don't do anything wrong here.  Excel just adds a white background to the pasted cells, even though the `<table>` that we put on the clipboard contains no background at all.  I don't think this is fixable.

**Comment by tapopov** [comment]
Adding the following style element to the clipboard HTML content should fix this.
```HTML
<style type="text/css"><!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}--></style>
```
Excel will parse it and the border will appear as expected (neither white nor solid black).

**Comment by ag-petrov** [comment]
Seems to not reproduce with the latest version
