### ISSUE TITLE
Fix axisCrossingValues misalignment in StockChart

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/kendo-ui-core#2530]
Stock chart is misaligned when axisCrossingValues of the categoryAxis is defined.
The issue is reproducible with the Q3 2016 release.
Actual - http://www.screencast.com/t/UX0X9Rl2Q
Dojo sample - http://dojo.telerik.com/UpOKE/2

**Comment by tsvetomir** [comment]
Duplicate of #2479
