### ISSUE TITLE
Native scrolling doesn't work with the latest Android System WebView

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#2533]
### Bug report
Views with native scrolling don't scroll when opened in a Cordova app or a Dojo in Android Chrome after the latest Android System Web View update (version 55.0.2883.91).

### Reproduction of the problem
http://dojo.telerik.com/iDImu - open in Android Chrome after updating both Chrome and the Android System WebView to latest version

### Environment

* **Browser:** Chrome on Android, Android System WebView (55.0.2883.91)

**Comment by tsvetomir** [comment]
The fix will be included in the next internal build. Versions 2016.3.1216 will be uploaded later today.

**Comment by yourdream94** [comment]
@tsvetomir Hi, I am facing same issue. Could you please tell me how to fix this issue?

**Comment by tsvetomir** [comment]
What version of Kendo UI are you using? Try evaluating `kendo.version` in the console.

**Comment by yourdream94** [comment]
I am sorry that I am not using Kendo UI. But I am using Android Webview just for my own app and I am also facing scrollng issue. I don't know where to start for finding out root cause.  I just need your help :) Thank you for your help in advance.

**Comment by tsvetomir** [comment]
The solution for us was to override the future detection for PointerEvents in Chrome _as they're broken_.

**Comment by yourdream94** [comment]
@tsvetomir I appreciate your answer. 
You did commit "https://github.com/telerik/kendo-ui-core/commit/b37076555792da5db2fa55a375f77eca40c23336" that referenced this issue on 16 Dec 2016. But it modified only "touch-action". It was not about "pointer-events".
Could you please tell me where you modified for solution in your source code? (or commit date/ id)

**Comment by tsvetomir** [comment]
This change is actually reverted later, see 57511af8090fe0353a9b7b4b347884fc935fec1f
