### ISSUE TITLE
TreeList MVVM bindings stop working if a column template contains a table

### ISSUE THREAD

**Issue by dimodi** [telerik/kendo-ui-core#2536]
### Bug report

TreeList MVVM bindings stop working if a column template contains a table. Reported in 1074469.

### Reproduction of the problem

http://dojo.telerik.com/ANAgE

### Current behavior

The bindings for the Position column... `<span data-bind="text: Position"></span>`  work only for the first few rows. It matters if there is a full table in the template, or just a table tag.

Doesn't work:

    <table>
      <tr><td>cell</td></tr>
    </table>

Works:

    <table></table>

### Expected/desired behavior
The bindings should work for all rows.

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 1.12.3
* **Browser:** all

**Comment by rusev** [comment]
This might be related to some bug in the virtual DOM implementation.
