### ISSUE TITLE
After a filter selection, clicking in the input removes all previously selected items.

### ISSUE THREAD

**Issue by antonpopov** [telerik/kendo-ui-core#2541]
### Reproduction of the problem

Use the following [dojo ](http://dojo.telerik.com/eSINam) in order to reproduce the issue.
1.) Click in the input and type a letter.
2.) Choose an item and repeat step 1 until the bug is reproduced.

[Video](http://screencast.com/t/5sADjBmWNe).

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 1.12.3

**Comment by antonpopov** [comment]
[Ticket ID: 1080017](https://admin.telerik.com/?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1080017&SM=0)

**Comment by Alex-Bubblemaster** [comment]
The functionality works as expected when the empty valueMapper is removed:

[Dojo](http://dojo.telerik.com/AXIbu)
