### ISSUE TITLE
Drag and drop of Kendo Scheduler events does not work properly on Windows 10 touch devices

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2547]
### Bug report
Drag and drop of Kendo Scheduler events does not work properly on Windows 10 touch devices. Tested in Chrome, Edge and Firefox on Surface Pro 2

### Reproduction of the problem
- On a Windows 10 touch device go to [Scheduler Event move and resize demo](http://demos.telerik.com/kendo-ui/scheduler/move-resize);
- Try to drag any of the events. On Edge and Chrome you will be able to move them only up / down with a single slot. In Firefox you could move them only to left / right, but this should be done without initially holding the event.

**Comment by ZachHardin** [comment]
Please fix this
