### ISSUE TITLE
Update Grid's Editor Templates article with EditorTemplateName property and DataType attribute

### ISSUE THREAD

**Issue by danail-vasilev** [telerik/kendo-ui-core#2548]
Update Step 5 in [Editor Templates](http://docs.telerik.com/aspnet-mvc/helpers/grid/templating/editor-templates) article.
      1) columns.Bound(p => p.MyField).EditorTemplateName("myEditorTemplate");
      2) DataType attribute in the model:
````cs
        [DataType("myEditorTemplate")]
        public int MyField
        {
            get;
            set;
        }
````

**Comment by Alex-Bubblemaster** [comment]
Closing as a duplicate in our private repository exists.
