### ISSUE TITLE
Add documentation and wrappers for series.labels.rotation

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-ui-core#2549]
The `series.labels.rotation` option is supported, but it is not documented:

http://dojo.telerik.com/@stamo/obETa

We should update the wrappers accordingly.

**Comment by gyankov** [comment]
The `series.labels.rotation` configuration seems to be documented and the wrappers are generated:
https://github.com/telerik/kendo/commit/402d0ea6214b65e8ba536d8c0d83489f4bb985ad
https://github.com/telerik/kendo/commit/b5c887d2cc5c1b92fd5b4b522d18683ceb80c68d
