### ISSUE TITLE
The drag is cancelled when the items reach the Grid filter row

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2550]
### Bug report

The drag is cancelled when the items reach the Grid filter row. In our demo for dragging items between Grids, if the Grid has a filter row and the item is dragged over the filter row it will be cancelled.

### Reproduction of the problem

The issue can be reproduced in the following Dojo(Chrome 55):  http://dojo.telerik.com/ERaCE

The issue is probably related to the new pointer events for Chrome.

Check issue: https://github.com/telerik/kendo-ui-core/issues/2526

### Environment

* **Browser:** [Chrome 55 ]

**Comment by tsvetomir** [comment]
Related issue #2584
