### ISSUE TITLE
Kendo drawing does not export correctly JPG images in Firefox

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2551]
### Bug report
Kendo drawing does not export correctly JPG images in Firefox.

### Reproduction of the problem
- Run the following [Dojo](http://dojo.telerik.com/oHENO/2) in firefox;
- When the Open file dialog appears, select the "Open with" radio button and click OK;
- The file that is opened (and exported) is a PNG (calendar.jpg.png), while it should be a JPG (calendar.jpg);

### Environment
* **Browser:** Firefox

**Comment by veselints** [comment]
Update [the following](https://feedback.telerik.com/Project/108/Feedback/Details/208463-radclientexportmanager-does-not-export-correctly-jpg-images-in-firefox) item in the AJAX Feedback portal, when fixed.

**Comment by tsvetomir** [comment]
The [exportmage](http://docs.telerik.com/kendo-ui/api/javascript/drawing#methods-exportImage) will always yield a PNG image.

Saving it with a different extension doesn't change the file itself.
