### ISSUE TITLE
Make FilterMenu ARIA compatible

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2555]
Bug report

When a Kendo UI Grid column is filterable, the text inputs in the filter options have no name as read by screen readers.

More information in the ticket: 1078444

The issue can be reproduced in our demo using NVDA or JAWS screen readers:

http://demos.telerik.com/kendo-ui/grid/remote-data-binding

Environment

Browser: [all]

**Comment by vladimirivanoviliev** [comment]
Implmented with: https://github.com/telerik/kendo/commit/cadf17c8c0f09fc3eff47d938a921c1fbf9986b2

**Comment by tsvetomir** [comment]
This issue seems to be related to telerik/kendo-ui-core#2193
