### ISSUE TITLE
Editing the series of recurring appointment deletes previously made changes to some appointment of the series

### ISSUE THREAD

**Issue by antonpopov** [telerik/kendo-ui-core#2557]
### Reproduction of the problem
1. Open the following sample: [dojo](http://dojo.telerik.com/azeka/19)
2. Double-click to the calender and create a recurrence-event. ([create event](https://admin.telerik.com/ClientsFiles/1b79259a-7bfb-4002-b599-e6dde0d6e249_RecurrenceEvent.PNG))
3. Double-click to one event of the recurrence-event and choose. ([edit occurence](https://admin.telerik.com/ClientsFiles/c6ad8903-e03d-4a17-ac7c-7a93cfdda1a0_EditCurrentOccurrence.PNG))
4. Change the date and the title.
5. Double-click again to one event of the recurrence-event and choose "Edit the series".
6. Change the title to "Event3" and click save.

### Current behavior
**Event3** is applied as title to all events of the series. Previously made changes to some events of the series is deleted. 

### Environment

* **Kendo UI version:** 2016.3.1118

**Comment by antonpopov** [comment]
[Ticket ID: 1079682](https://admin.telerik.com/?Context=Support&Control=~%2fUserControls%2fSupport%2fThreadReply.ascx&ST=1079682&SM=0)

**Comment by antonpopov** [comment]
https://github.com/telerik/kendo-ui-core/issues/2557

**Comment by veselints** [comment]
Also reported in [Ticket ID: 1138860](https://admin.telerik.com/default.aspx?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1138860&SM=0)

**Comment by veselints** [comment]
[Here you could find a workaround of the discussed issue](http://dojo.telerik.com/ofUke/8)

**Comment by veselints** [comment]
Also reported in [Ticket ID: 1144571](https://admin.telerik.com/default.aspx?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1144571&SM=0)

**Comment by veselints** [comment]
Also reported in [Ticket ID: 1145026](https://admin.telerik.com/default.aspx?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1145026&SM=0)

**Comment by nelito987** [comment]
Also reported in [Ticket ID: 1342723](https://admin.telerik.com/default.aspx?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1342723)
