### ISSUE TITLE
Horizontal scrolling in the Grid with virtual scrolling freezes sometimes in Microsoft Edge

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2563]
### Bug report

Horizontal scrolling in the Grid with virtual scrolling freezes sometimes in Microsoft Edge.

### Reproduction of the problem

Steps to reproduce:

- Build a grid with scrollable: { virtual: true}
- Use a large data source so that the vertical scrollbar is visible
- Add enough columns to the grid so that the horizontal scrollbar is visible
- Scroll down and up
- Scroll right and left
- Repeat the last two steps a few times, sometimes scrolling right and left will not work, after scrolling down and up again, scrolling right and left may work again too

Please check the ticket with the video of the issue: 1081007 

The issue can be observed in the following Dojo: http://dojo.telerik.com/uWaMeG

### Environment

* **Browser:** [ MS Edge version 38+  ]

**Comment by simonssspirit** [comment]
The issue is reported again in ticket: 1109273.

Raising the priority from low to medium.

**Comment by hadjieva** [comment]
The issue is reported in ticket: 1112066 as well

**Comment by Stamo-Gochev** [comment]
I cannot reproduce the issue with the latest version from the master branch and Edge v40.

**Comment by matanasov** [comment]
@Stamo-Gochev 
This still replicates with Edge 38 and Edge 40

**Comment by Stamo-Gochev** [comment]
It seems like there is an issue with scrollbar freezing in Edge in general and as we cannot reproduce the problem in any other browser, we won't add any fixes for that:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9706209/
