### ISSUE TITLE
Kendo Mobile TabStrip is triggered when the native menu of an iOS device is invoked 

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#2567]
### Bug report

Reported in 1081289. When a Cordova app with Kendo UI mobile runs on an iOS device and the user swipes up to invoke the native menu, the TabStrip triggers and the view changes.

### Reproduction of the problem
Steps:

1. With AppBuilder, Create a TabStrip Cordova app from a template.
2. Deploy on an iOS device.
3. Swipe up from the bottom of the screen to invoke the native menu.

### Environment

* Kendo UI Professional v2016.3.1216

**Comment by ag-petrov** [comment]
Closing this issue as the mobile suite is now depricated.
