### ISSUE TITLE
Grid with virtual scrolling and locked columns resets scrollLeft() in IE

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2573]
### Bug report

If the "scrollable" part of a Grid with virtual scrolling and locked columns is clicked, the table is scrolled horizontally, and then vertically, scrollLeft() is reset to 0 when a request for new data is performed. Reproducible in IE only.

### Reproduction of the problem

[http://dojo.telerik.com/UHUmI/3](http://dojo.telerik.com/UHUmI/3)
http://dojo.telerik.com/UHUmI

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** x.y
* **Browser:** [IE 11]

**Comment by MilenaCh** [comment]
Steps for reproduce:
1. Click somewhere on the scrollable table
2.Scroll horizontally to the most rigth
3.Scroll vertically to fetch the new view

Result:
The horizontally scrolling will be reset to left.

**Comment by ag-petrov** [comment]
After further research the problem proved to be a browser bahavior. When a new set of items is received and showed we hide the tables, adjust the rows height and display the tables again. In IE this seems to reset the scroll position. I was able to reproduce it without using the grid with only a table in a scrollable container. 

Altering the logic which show/hides the tables may result in wrong recalculation of some styles which is not desirable. That said I am marking the issue as wont fix.
