### ISSUE TITLE
Bar Chart label is positioned under the line Chart when panes.clip is false

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2577]
### Bug report

Bar Chart label is positioned under the line Chart when panes.clip is false. The Line is overlapping with the label.

### Reproduction of the problem

The issue can be observed in the following Dojo example: http://dojo.telerik.com/eMUbo

Notice that the labels are not visible initially, if the panes.clip property is set to true, the labels will be visible.

### Environment

* **Browser:** [all]

**Comment by danielkaradachki** [comment]
fixed with telerik/kendo@fccadb0a82d91dd9aa70f640181abd078d4f0713
