### ISSUE TITLE
Paste is making row height bigger without wrapping the text.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2578]
### Bug report

Paste is making row height bigger without wrapping the text. If the copied text is longer than the cell width, the height of the cell will be increased but the text will not be wrapped.

### Reproduction of the problem

The issue can be reproduced in our demo example: http://demos.telerik.com/kendo-ui/spreadsheet/index

Paste "Spinach and Blue Cheese" in cell H7 and noticed the undesired result.

### Environment

* **Browser:** [all]

**Comment by tapopov** [comment]
Fixed.
