### ISSUE TITLE
Text color in Notification using Nova theme 

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-ui-core#2581]
### Bug report
Notification text color in Nova theme is wrong.

### Reproduction of the problem
See this demo: http://demos.telerik.com/kendo-ui/notification/index

### Current behavior
Text color is #20aec0 

### Expected/desired behavior
Text color should be #00838f

**Comment by melhaer** [comment]
For nova skin it is not possible to get 00838f color with darkening, so we will apply 10% darkening and will get a color that is close enough: #198694
