### ISSUE TITLE
Spreadsheet: column styling or paste poor performance

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2582]
### Bug report

The browser freezes when text wrap, font size change or font type change is applied to a whole column with any more than 500 rows of the Spreadsheet. The same could be observed if all cells are selected and paste is performed.

### Reproduction of the problem

- Select the first column
- Press textWrap button from the Toolbar
or
- Select a new Font size/ Font Family

[Dojo](http://dojo.telerik.com/@bubblemaster/uzidA/2)

### Current behaviour

Progressively declining performance which eventually crashes the browser as the number of rows are increased. 

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by veselints** [comment]
Possible workaround could be to alter the default behavior of the fontSize ComboBox:
````JavaScript
var initial = true;

var onRender = function() { 
  if (initial) {
    initial = false;

    var comboElement = $('span[data-tool="fontSize"] input[data-role="combobox"]');
    var combo = comboElement.getKendoComboBox();
    combo.unbind('change');

    combo.bind('change', function(e) {
      var selectedValue = Number(e.sender.value());
      var spread = $("#spreadsheet").getKendoSpreadsheet();
      var sheet = spread.activeSheet();

      sheet.batch(function() {
        var range = sheet.selection();
        range.fontSize(selectedValue);
      });
    });
  }
};
````

**Comment by mparvanov** [comment]
The issue was not reproduced with v 2019.3.1023
http://dojo.telerik.com/EnuFoLuw/2
