### ISSUE TITLE
Cannot set filter in grid column menu (disappears on hover)

### ISSUE THREAD

**Issue by hanssens** [telerik/kendo-ui-core#2584]
### Reproduction of the problem
Steps to reproduce:

1. Open Google Chrome (latest)
2. Navigate to the **Kendo UI Grid / Column menu demo**:  
  http://demos.telerik.com/kendo-ui/grid/column-menu
2. Try to set a filter on any column, through the column menu's "Filter" dropdown menu

... or watch this 10sec. animated gif demo:

![cannot-set-focus](https://cloud.githubusercontent.com/assets/493382/21646600/15be3496-d297-11e6-94f4-edc4b6f953ae.gif)

You see the **menu disappearing completely**.

### Current behavior
The entire menu disappears before the user can actually enter a value to filter on. Rendering the entire grid column menu useless for filtering. 

### Expected/desired behavior
Expected behaviour is the user can set focus to an entry field - and add a filter.

### Environment

* **Kendo UI version:** Kendo latest, see demo's in url above
* **jQuery version:** Kendo default, see demo's in url above
* **Browser:** Occurs only with Google Chrome (version 55.0.2883.95 64-bit), not with Firefox
* **OS:** macOS 10.12.2

**Comment by hanssens** [comment]
There is a current workaround for this glitch: using the animated example above, when the menu opens select the "contains" criteria (making sure you don't hover over the text field). Next, you can [tab] into the input text field to actually set the filter.

**Comment by mustaqahmed** [comment]
This seems like a bug in handling PointerEvents in Kendo UI. Chrome 55 recently turned on PointerEvents by default which exposed the bug.

More precisely, Kendo UI seems not handling "pointerout" events correctly. For example, when filtering by "Order ID", suppressing "pointerout" events for targets with class "k-numeric-wrap" fixes the problem. Note that the input box for "Order ID" filter has this class.

This, however, doesn't happen in Edge which also support PointerEvents.

Kendo team: please check Chrome-specific codepath in "pointerout" handlers. Could also try the same codepath as Edge.

**Comment by tsvetomir** [comment]
@mustaqahmed on it

We'll likely ignore PointerEvents entirely in Chrome as the implementation seems to be buggy.

**Comment by tsvetomir** [comment]
This is now fixed and will be included in the next internal build tomorrow.

**Comment by hanssens** [comment]
@tsvetomir great news, thanks for the quick follow-up and actions on this.

**Comment by vdh** [comment]
@tsvetomir Because of [this one line](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.menu.js#L42) in `kendo.menu.js`, it's been made impossible to patch this fix in safely without modifying the kendo files. The variable is needlessly cached inside a closure.

**Comment by tsvetomir** [comment]
This pattern is widespread in our codebase and I can't make a commitment to change it everywhere. Still, you can get around this by loading individual scripts. You'll need to overwrite the `kendo.supports.pointers` variable after loading `kendo.core`, but before loading the menu.

**Comment by vdh** [comment]
@tsvetomir That's what I would have done, if the contents and load order of `kendo.all.min.js` had been documented anywhere. Instead I'm stuck with a mystery bundle that probably starts with `kendo.core` but is otherwise full of unknowns.
