### ISSUE TITLE
FilterMenu input is clobbered on datasource change

### ISSUE THREAD

**Issue by watsoncj** [telerik/kendo-ui-core#2590]
### Bug report

Changes to the FilterMenu input are lost whenever the datasource fires a change event. This makes interacting with grid filters problematic with background refreshes are used.

The refresh function of filtermenu.js is explicitly overwriting the form inputs with the filter model values (line 249):

    if (that.form) {
        kendo.bind(that.form.children().first(), that.filterModel);
    }

### Reproduction of the problem

Easy to reproduce by calling read on the datasource in an interval.

http://dojo.telerik.com/OReyI/2

### Current behavior

Any unsaved changes to the filter menu inputs are lost.

![demo](http://g.recordit.co/r1aCdo37ih.gif)

### Expected/desired behavior

User input should not be overridden by the filter model state when the filter menu is open.

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 1.12.3
* **Browser:** all

**Comment by watsoncj** [comment]
Telerik support claims this is "expected behavior" and that the workaround is to reimplement the entire filter menu. 👎

**Comment by Stamo-Gochev** [comment]
The scenario was discussed in the dev team and any updates to the datasource (calling the read method) are expected to trigger refreshing of the connected widgets. If this is not expected, the corresponding events can be prevented or the client state (in this case - the input value) can be cached and restored manually.
