### ISSUE TITLE
MultiSelect does not clear selected value(s) from the list when filtered, and autoClose is false

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2591]
### Bug report

When the filter is used, then a value is selected from the list, and then deleted from the selected values, it is still highlighted as selected in the list of available options. This only happens when **autoClose** is set to **_false_**.

### Reproduction of the problem
[http://dojo.telerik.com/asILi](http://dojo.telerik.com/asILi)

### Current behavior
As described above.

### Expected/desired behavior
When a value is removed from the tag list of selected values, it should also be unmarked (not shown as selected) in the dropdown

**Comment by Dimitar-Goshev** [comment]
https://github.com/telerik/kendo-ui-core/issues/2591
