### ISSUE TITLE
Editor's content area has been scrolled to the bottom on enter key

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-ui-core#2592]
Editor's content area has been scrolled to the bottom on enter key when content is large plain text

Steps to reproduce:
1. Insert enough plain text so the scrollbars appears
2. Set the cursor in the beginning of the content and press enter

Actual result: The content area is scrolled to the bottom
Expected result: The content area should not be scrolled when the cursor is in the view port

Video:
http://www.screencast.com/t/4QveHLjtyyz

**Comment by tijurajan** [comment]
Hi,
Would you be able to provide and ETA for this bug Fix at this point of time? This is critical to the client project UAT sign off. 

Regards, 
Tiju Abraham 
Telerik by Progress

**Comment by nstoychev** [comment]
Hi @tijurajan,

The issue is planed for fixing in the current iteration which ends on 22.01.2017.
