### ISSUE TITLE
The values in the filter menu are displayed in random order.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2594]
### Bug report

The values in the filter menu are displayed in random order. The items(distinct) should be displayed in the same order as they are in the column.

### Reproduction of the problem

1. The issue can be reproduced in our demo: http://demos.telerik.com/kendo-ui/spreadsheet/sorting-filtering
1. Open the filter menu

### Current behavior
The values in the filter menu are displayed in random order.

### Expected/desired behavior
The items(distinct) should be displayed in the same order as they are in the column or sorted alphabetically like in excel.

### Environment

* **Browser:** [all] 
* **Kendo UI version:** 2019.3.917

**Comment by mparvanov** [comment]
Another point of view is to sort the filter items alphabetically as it is implemented in Excel.

**Comment by mishoo** [comment]
The (distinct) values are displayed in the same order as they appear in the column, provided that they are of the same kind (e.g. only dates, or only numbers, or only text).  This can be seen in the demo.

For mixed values they may be reordered, like this: if present, a blank will come first, followed by numbers, dates, and everything else in the original order.

I vote to close this, it's not an issue..

**Comment by sspasova** [comment]
As Mihai noted, the current behavior is intended. There is a Feature request for changing it to sort the items. 
You can easily vote for its implementation here: https://feedback.telerik.com/kendo-jquery-ui/1360172-sort-the-items-of-spreadsheet-filter-by-default
