### ISSUE TITLE
Cancelling Edit on Recurring appointment removes the 'edited' occurence from UI

### ISSUE THREAD

**Issue by antonpopov** [telerik/kendo-ui-core#2595]
### Reproduction of the problem
[dojo](http://dojo.telerik.com/ICENU/4)

1. Double click on an appointment
2. Choose "Edit current occurrence"
3. Check 'All day event' (client reports the same behavior without this step)
4. Click 'Cancel'
[video](http://screencast.com/t/K24j1emlSwbx)

### Current behavior
The 'edited' event is removed from UI

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 1.12.3

**Comment by antonpopov** [comment]
[Ticket ID: 1082807](https://admin.telerik.com/?Context=Support&Control=~%2fUserControls%2fSupport%2fThreadReply.ascx&ST=1082807&SM=0)

**Comment by zdravkov** [comment]
It is related to this issue #2513
