### ISSUE TITLE
Spreadsheet server-side Save method does not export the correct value for cells with custom format

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#2598]
### Bug report

When the Spreadsheet has custom format ("@") for a given cell and the server-side export is implemented, the exported Excel file contains incorrect values.

For example, when "01234" value is set in some cell - the exported excel file should be "01234", while currently it is "1234". 

The issue seems to originate by the **SetCells** method in partial class Workbook, where the values from the Spreadsheet are translated to the exported Excel file. Probably the SetValueAsText method should be used after the SetFormat.

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by pepinho24** [comment]
Reported also in Ticket ID: 1087280

**Comment by dimodi** [comment]
Also in 1092189

**Comment by adrianagurau** [comment]
Can someone give me an example of code that actually works? The leading zeros are still truncated in my case, when they export the grid to Excel and these are postal codes that are missing the leading zeros. The users are having a heck of a time with it. It will make the addresses useless. How can I fix it? Please help. Thanks.

**Comment by nenchef** [comment]
@adrianagurau would you specify which version of our components you are using? Also, if a sample (or dojo) example is available, please submit a support ticket to examine the exact implementation you use.
