### ISSUE TITLE
NumericTextBox helper rendered HTML is culture dependend and breaks when number have decimal separator.

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-ui-core#2600]
This results in empty value in Edge, and wrongly parsed in Chrome or Firefox.
Also the markup does not pass validation.
This happens if the server culture have comma as decimal separator. The rendering should be culture independent. 

Steps to reproduce.
Go to http://demos.telerik.com/aspnet-core/grid/globalization?culture=de-DE
Change culture to de-De.

Then open.
https://validator.w3.org/nu/?doc=http%3A%2F%2Fdemos.telerik.com%2Faspnet-core%2Fnumerictextbox%2Findex
```
<input id="percentage" max="0,9" min="0" name="percentage" step="0,01" type="number" value="0,05" />
```

**Comment by ag-petrov** [comment]
Duplicate issue - https://github.com/telerik/kendo-ui-core/issues/2970
