### ISSUE TITLE
Add a unique class to the clear button

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-ui-core#2601]
Currently the clear button in the AutoComplete, MultiSelect and ComboBox components cannot be styled independently, as it uses the same class as the tag buttons (`k-i-close`). It would be helpful if the clear value button has its own class, which describes what it does. `k-clear-value`, perhaps?

**Comment by KirilNN** [comment]
closed with https://github.com/telerik/kendo-ui-core/commit/c4dd1a0fc141cf058859b1969969ff6012cc59e7

**Comment by KirilNN** [comment]
will go ahead and add the same class for the angular 2 component as well
