### ISSUE TITLE
In the mobile Grid' filter menu, the options AND and OR does not appear as selected(Flat theme).

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2602]
### Bug report

In the mobile Grid' filter menu, the options **AND** and **OR** do not appear as selected. When an option is clicked there is no visual indication that it was selected.

Reported in ticket: 1083062

### Reproduction of the problem

The issue can be reproduced in our demo example using the **Flat** theme: http://demos.telerik.com/kendo-ui/m/index#grid/adaptive

### Environment

* **Browser:** [all]

**Comment by theOrlin** [comment]
In addition, the icons of the NumericTextBox in the filter are not properly positioned.
