### ISSUE TITLE
Event view of the mobile Scheduler with Flat theme has missing icons and misalignments.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2603]
### Bug report

Event view of the mobile Scheduler with the Flat theme has missing icons and misalignments.

Reported in ticket: 1083062

### Reproduction of the problem

The issue can be reproduced on our demo using the **Flat** theme:  http://demos.telerik.com/kendo-ui/m/index#scheduler/adaptive

### Environment

* **Browser:** [all]

**Comment by simonssspirit** [comment]
Current result:
![_schedulerevent](https://user-images.githubusercontent.com/11087921/28918905-dedfffbe-7853-11e7-8d4f-d7edb361d66b.png)

Expected:

![image](https://user-images.githubusercontent.com/11087921/28918890-d65be510-7853-11e7-8b8d-88f80e69cd92.png)

**Comment by Dimitar-Goshev** [comment]
The Timezone label is still covered by the timezone button. But this issue is observed in other themes as well so I will log it as a separate one.
