### ISSUE TITLE
All icons are now font icons

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/kendo-ui-core#2605]
Details: docs.telerik.com/kendo-ui/backwards-compatibility/2017/2017-backward-compatibility#kendo-ui-2017-r1

**Comment by digeomel** [comment]
The link you provided above doesn't seem to work any more, unless I'm doing something wrong.

**Comment by digeomel** [comment]
The correct link seems to be:
http://docs.telerik.com/kendo-ui/backwards-compatibility/2017-backward-compatibility

**Comment by marin-bratanov** [comment]
Thanks for noticing. I had created the link while working on the documentation before it was published and we had changed its URL since. I have now updated the initial post as well.
