### ISSUE TITLE
The Animation configuration for the PopUp Window of the Grid is not applied

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#2610]
### Bug report
Configuring the Animation of the PopUp Window in Grid is not applied and the default animation is used instead

### Reproduction of the problem
Using the following configuration does not apply the animation to the PopUp window
.Editable(editable => editable.Mode(GridEditMode.PopUp).Window(w => w.Title("Standort").Animation(animation => animation
		.Open(open => open.SlideIn(SlideDirection.Left).Duration(500))
		.Close(close => close.SlideIn(SlideDirection.Left).Duration(500).Reverse(true))
	)
)) 

### Environment
Version: 2016.3.1118

**Comment by madrianr** [comment]
when can we expect a fix for this?

**Comment by madrianr** [comment]
some News?

**Comment by madrianr** [comment]
I'm waiting now for months and now fix????

**Comment by madrianr** [comment]
Now it's at the end of 2017 and no fix?
when can we expect a fix for that?
