### ISSUE TITLE
An invalid aria-title attribute set on the NumericTextBox

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2612]
### Bug report

An invalid aria-title attribute set on the NumericTextBox. The aria-title attribute is not a valid attribute based on the official documentation for the available aria attributes:

https://www.w3.org/TR/wai-aria/states_and_properties#state_prop_def

### Reproduction of the problem

The issue can be reproduced in our demos of the NumericTextBox: 

http://demos.telerik.com/kendo-ui/numerictextbox/index

### Environment

* **Browser:** [all]

**Comment by ggkrustev** [comment]
This seems to be fixed, as the NumericTextBox doesn't render aria-title any more.
