### ISSUE TITLE
lockColumn() method not working as expected in multi-column headers scenario

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2616]
### Bug report
The lockColumn() method yields unexpected results in multi-column header scenario.

### Reproduction of the problem
[http://dojo.telerik.com/UCoju/2](http://dojo.telerik.com/UCoju/2)
### Current behavior
Sub columns are mixed up. Multiple further issues if there is a hidden sub-column:
[http://dojo.telerik.com/UCoju/3](http://dojo.telerik.com/UCoju/3)

Only non-locked content sub-columns are misaligned with the headers, if there is a hidden column, and columns are initially locked (not via the lockColumn() method):

[http://dojo.telerik.com/UCoju/4](http://dojo.telerik.com/UCoju/4)

**Comment by MilenaCh** [comment]
The scenarios below still do not work as expected:
http://dojo.telerik.com/uruhOcuy
http://dojo.telerik.com/ujETAmUd
