### ISSUE TITLE
A web page inside the Splitter cannot be scrolled on iOS.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2622]
### Bug report

A web page inside the Splitter cannot be scrolled on iOS.

### Reproduction of the problem

The issue can be reproduced on the following Dojo when opened on iOS device: http://dojo.telerik.com/ewiLO

* **Browser:**  [ iOS Mobile]

**Comment by mparvanov** [comment]
The issue is not reproducible with v. 2019.3.1023
