### ISSUE TITLE
AutoComplete and ComboBox placeholder text is indented too far in MS Edge

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#2623]
### Bug report

Most visible with Bootstrap v3, Fiori, Material, Material Black, Nova and Office 365 themes, combobox placeholder text is indented too far in MS Edge.

### Reproduction of the problem

1. http://dojo.telerik.com/@joneff/uJUya
2. clear the text

### Current behavior

The placeholder text is indented too far, compared to selected value:
![image](https://user-images.githubusercontent.com/6614183/29032621-c00e399e-7b9a-11e7-8a60-923ecfc7fabe.png)

### Expected/desired behavior
Should not be indented as much. Indentation should be as with selected value above.

### Environment

* **Kendo UI version:** 2016.3.1118; reproducible with 2017.2.621 as well
* **Browser:** MS Edge

**Comment by mvgmvg** [comment]
The issue is a logged Edge browser bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4354812/

**Comment by joneff** [comment]
As noted, the issue is MS Edge issue. It appears fixed in Microsoft Edge 42.17134.1.0 and is broken in Microsoft Edge 40.15063.674.0
