### ISSUE TITLE
PdfExport functionality (in particular drawDOM method) removes attributes from the elements in the DOM tree.

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#2625]
### Bug report

PdfExport functionality (in particular drawDOM method) removes attributes from the elements in the DOM tree.

### Reproduction of the problem

Please refer to the http://dojo.telerik.com/AcURu/4 example. In order to replicate the issue: 
   1. Click on the export button. 
   2. Inspect the radio buttons using the browser's developer tools. 
   3. The name attribute of the radio buttons is removed. 

### Expected/desired behavior

The name attribute should not be removed in order radio buttons to behave as expected. 

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 1.12.3
* **Browser:** [all ]

**Comment by mishoo** [comment]
Cannot reproduce this on latest code.  Please reopen if I'm missing something.
