### ISSUE TITLE
Hold event of the Draggable widget is hired when the holdToDrag property is set to false.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2633]
### Bug report

The hold event of the Draggable widget is fired when the holdToDrag property is set to false. In the documentation is stated that the event should be only fired if holdToDrag is set to true.

### Reproduction of the problem

The issue can be observed in the following Dojo: http://dojo.telerik.com/aWOyi

### Environment

* **Browser:** [all ]

**Comment by Juveniel** [comment]
It is not correct for the holdToDrag option to control the execution of the hold event and to cancel it. Its main purpose is to extend the specific DOM element with additional logic that enables activating drag on hold, and as such it should affected the drag behavior.

Taking the above into consideration, I am revering the previous commit. In addition to this, the information in the API Documentation will be updated accordingly.

/cc @ag-petrov
