### ISSUE TITLE
Deleting a list along with its sub-list leaves the bullets

### ISSUE THREAD

**Issue by Jekata** [telerik/kendo-ui-core#2635]
### Bug report
Go to [http://dojo.telerik.com/@RumenJ/EzaxO/2](http://dojo.telerik.com/@RumenJ/EzaxO/2). 
If you select all content via mouse (not ctrl-a) and press delete, the bullets (main and its sub-item bullet) remain in the editor. 

The issue is not reproducible with an editable div.

### Reproduction of the problem
video: [https://www.screencast.com/t/kUXmYxpqOlm](https://www.screencast.com/t/kUXmYxpqOlm)

### Expected/desired behavior
The sub-bullet should be removed as in an editable div element.

### Environment

* **Kendo UI version:** 2018.3.911
* **Browser:** All

**Comment by Dimitar-Goshev** [comment]
Reproducible with 2017.3.913 as well.

**Comment by IvanDanchev** [comment]
This behavior seems to be specific to Chrome. With version 2018.2.620 two bullets remain after selecting the Editor's content (Ctrl + A) and pressing Delete. In the editable div element one bullet remains. All bullets are removed in Firefox and IE11. [Dojo example](http://dojo.telerik.com/okamOqIQ/2).
