### ISSUE TITLE
The edited cell is still shown as edited even after a click outside of the Spreadsheet.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2636]
### Bug report

The edited cell is still shown as edited even after a click outside of the Spreadsheet

### Reproduction of the problem

The issue can be observed in our demos: http://demos.telerik.com/kendo-ui/spreadsheet/index

Please check the screencast showing it: 

https://www.screencast.com/t/kCVaAqbiSz

### Environment

* **Browser:** [all ]

**Comment by mishoo** [comment]
This was fixed some time ago.  I can't repro on the master branch, and neither in the demos — perhaps they were updated.  Please reopen if I'm missing something.
