### ISSUE TITLE
Editing a cell, containing multi-line text, or pasting such in the formula bar distorts the Spreadsheet

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2639]
### Bug report
Pasting multiline text in the formula bar, or opening a cell, containing multiline text for editing, extends the field at the top and visually distorts the whole spreadsheet.

Can be fixed via the following CSS:

`<style>
     .k-spreadsheet .k-spreadsheet-action-bar .k-spreadsheet-formula-input {
      max-height: 1.5em;
    } 
  </style>`
### Reproduction of the problem
[http://dojo.telerik.com/ITiho](http://dojo.telerik.com/ITiho)
Paste multiline text in any of the text fields, and then open it for editing, or directly in the formula bar at the top.
### Expected/desired behavior
Uncomment the CSS in the **style** tag, and perform the steps above again.
### Environment

* **Kendo UI version:** 2016.3.1118, 2017.1.118

**Comment by mishoo** [comment]
This was broken by [this commit](https://github.com/telerik/kendo/commit/87c1e51439bbcccb89a59290db2b63bcf7b871d0), to which I left a note.  Sorry it still slept through :-\

Adding @inikolova

**Comment by inikolova** [comment]
OK, I will investigate the case
