### ISSUE TITLE
Icon missaligned in edin demo section

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-ui-core#2642]
### Reproduction of the problem
It can be seen on every  [demo](http://kendobuild/staging-kendo-ui/slider/index)
![capture 2017-01-04 at 13 52 55](https://cloud.githubusercontent.com/assets/4143177/22105830/9d99bb16-de4e-11e6-802f-caabf638b6fb.png)

### Expected/desired behavior
Icon should be aligned

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** x.y
* **Browser:** [all  ]

**Comment by Dimitar-Goshev** [comment]
Not relevant anymore as the demos are rebranded for R3 2020.
