### ISSUE TITLE
Number precision is lost after paste in from one Spreadsheet to another if a decimal formatting is applied.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2646]
### Bug report

Number precision is lost after paste in from one Spreadsheet to another if a decimal formatting is applied. If the number 10.20 is formatted to show only 10, the value in the other Spreadsheet will be only 10. In the same Spreadsheet, the value will be 10.20 and correctly displayed as 10.

Related to: #4843

### Reproduction of the problem

The issue can be reproduced in the following Dojo: http://dojo.telerik.com/iVUsa

Please check the screencast provided in the ticket: https://www.screencast.com/t/rgNgyWG8

### Environment

* **Browser:** [all]

**Comment by mparvanov** [comment]
The issue is not reproducible with v. 2019.3.1023
http://dojo.telerik.com/oMENILaY/5
