### ISSUE TITLE
npm login automatically for build server

### ISSUE THREAD

**Issue by stefanzvonar** [telerik/kendo-ui-core#2647]
Hi,

Trying to set up the npm login automatically and bypass the interactive mode for username and password.  We are using Kendo UI Professional.

In the build step, we can perform the following:

npm login -registry=https://registry.npm.telerik.com/ --scope=@progress  

However, not too sure how to get past the interactive mode of entering the username and password.   Can we provide the username and password via the command line?

Am currently playing with the addUser parameter to set the registry and setting always-auth to be true, but no luck so far.

Kind regards,

Stefan

**Comment by tsvetomir** [comment]
I've updated the docs to include a section for [authenticating build agents](https://github.com/telerik/kendo-ui-core/blob/984ceee8503565a956ffb33d607cc4e6a0e34a00/docs/intro/installation/npm.md#authenticating-build-agents). Let me know if that helps.

**Comment by stefanzvonar** [comment]
Thanks tsvetomir.

That is very close to how we got it working in the end.  The following is how we ended up performing it for our particular build configuration, so we can generate the npmrc file without having to log onto the build server itself.  These were set up as tasks in the build.

1) Run: npm install -g npm-cli-login
2) Run: npm-cli-login -u <your Telerik username> -p <your Telerik password> -e <your Telerik email address> -r https://registry.npm.telerik.com -s @progress --config-path "./.npmrc"
3) Run: npm install --save @progress/kendo-ui

**Comment by tsvetomir** [comment]
That's fine if you're not worried about storing a password in cleartext.
Using a token is a lot better in terms of information disclosure.

**Comment by stefanzvonar** [comment]
Hmmm, we had set up the username and password as variables with the values hidden in the build tool that we used (not in source control) but yes, I guess just using the npmrc file itself could be much better than generating each time.  Might think about generating the file and using that across the build agents.  Cheers.
