### ISSUE TITLE
.k-icon, .k-sprite, .k-tool-icon missing vertical-align: middle in R1

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2649]
### Bug report

Some Grid icons are vertically mis-aligned, e.g.:

[http://dojo.telerik.com/OnoQi/8](http://dojo.telerik.com/OnoQi/8)

Remove the comment from the first rule in the style tag to see the previous version (and desired) layout:

[http://dojo.telerik.com/OnoQi/9](http://dojo.telerik.com/OnoQi/9)

### Environment

* **Kendo UI version:** 2017.1.118

**Comment by joneff** [comment]
Fixed by 3abcd9dcfbd7e56c384544b0d7048faf0ca56b9e
