### ISSUE TITLE
Inconsistent behavior of the ComboBox and the DropDown when nesting in AngularJS forms.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2657]
### Bug report

Inconsistent behavior of the ComboBox and the DropDown when nesting in AngularJS forms.

The $pristine status is different when ng-model has a null value or any other.

### Reproduction of the problem

The issue can be reproduced in the following two Dojos:

The ComboBox will set $pristine to false on the outer form if ng-model is null: http://dojo.telerik.com/IWejaleR/3

The DropDown will set $pristine to false on the outer form if ng-model is different from null: http://dojo.telerik.com/iXuzuvAL/2

### Expected result

The both innerForm  and outerForm  $pristine becomes  false

### Environment

* **Browser:** [all] 
Kendo version: 2019.2.619

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
