### ISSUE TITLE
Virtualized MultiSelect doesn't add k-state-selected to filtered items

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2661]
### Bug report

Virtualized MultiSelect should add the k-state-selected CSS rule to selected items when filtering 

### Reproduction of the problem

[Official Demo](http://demos.telerik.com/kendo-ui/multiselect/virtualization)
Start typing the name of the preselected items. This only occurs when the MultiSelect has virtualization.

<img src="http://image.prntscr.com/image/97f195cfea9449d7aa5b185fa6eeed42.png">

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12
* **Browser:** [all ]

**Comment by epikhighs** [comment]
Hi, I'm the original filer of this ticket on telerik forum.  In this http://dojo.telerik.com/AtAqI/3 , try the following steps

1. select/click 10249 Toms Spezialitäten, Germany (this is the 2nd item in the list as soon as you open it)
2. now type into the multiselect "tom"
3. notice that 10249 Toms Spezialitäten, Germany is no longer selected from that filtered list
4. now press backspace 3 times to remove the filter "tom"
5. notice that 10249 Toms Spezialitäten, Germany is STILL NOT selected.
6. 10249 Toms Spezialitäten, Germany does show as selected if you close and reopen the list.

**Comment by epikhighs** [comment]
Hi, is there an ETA on this fix?  Thanks.

**Comment by ggkrustev** [comment]
Hi @epikhighs, currently we are addressing issues with higher priority, but I do believe that this will come next soon. I am afraid, however, that I would not be able to provide any specific time frame.

**Comment by perrein** [comment]
Any news about the fix?

**Comment by mparvanov** [comment]
The following workaround could be temporarily used:
https://dojo.telerik.com/UTuFa/22
