### ISSUE TITLE
Add bottom border to the grid last row in all themes

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-ui-core#2664]
### Bug report
Suggested in ticket 1085868

### Reproduction of the problem
Add bottom border to the grid last row in all themes. Can be observed in this dojo: http://dojo.telerik.com/@Iliana/UTIga

### Current behavior
Currently there is no bottom border to the grid last row.

### Expected/desired behavior
There should be bottom border to the grid last row

**Comment by theOrlin** [comment]
Duplicates https://github.com/telerik/kendo-ui-core/issues/2663. Borders have been removed from Material themes as adding a border to the last row would create a double border in cases where the content reaches the bottom border of the Grid container.
