### ISSUE TITLE
JS error in IE when exporting to PDF and using page breaks

### ISSUE THREAD

**Issue by ivanchev** [telerik/kendo-ui-core#2666]
Can be reproduced with the following dojo, when run in IE 11:
http://dojo.telerik.com/EzAPu/3

Not reproduced with Q3 2016

Browser: IE (11)

**Comment by mishoo** [comment]
Can you please paste the error?  I do get an error but just want to make sure it's the same.

**Comment by ivanchev** [comment]
The error was "Invalid calling object":
https://www.screencast.com/t/XlTXxm2dFkI

**Comment by mishoo** [comment]
Right, that's what I saw.  It's fixed now.
