### ISSUE TITLE
Increase the DefaultJavaScriptSerializer.MaxJsonLength property to its maximum value

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2667]
### Bug report

In order to render bug amount of data through Model-binding users should be able to configure the `MaxJsonLength` value for the `DefaultJavaScriptSerializer`. 

Ticket ID: 1085906

### Reproduction of the problem
Having model-binding with more than 4 MB of data.

### Current behavior
A server exception is thrown.

### Expected/desired behavior
The MaxJsonLength to be configured so that binding works as expected.

### Environment

* **Kendo UI version:** all
* **jQuery version:** all
* **Browser:** [all]

**Comment by tsvetomir** [comment]
Are we certain we'd like to change an application configuration setting from an UI component? What would happen if the developer has already set it to the desired value?

**Comment by simonssspirit** [comment]
This is a workaround shared by the community, it may be used is these scenarios:

`publicclassMySerializer
: Kendo.Mvc.Infrastructure.JavaScriptInitializer
{
publicoverrideIJavaScriptSerializer CreateSerializer()
{
varserializer = base.CreateSerializer() asDefaultJavaScriptSerializer;
serializer.MaxJsonLength = serializer.MaxJsonLength * 100;
returnserializer;
}
}
Kendo.Mvc.Infrastructure.DI.Current.Register<Kendo.Mvc.Infrastructure.IJavaScriptInitializer>( () => newMySerializer() );
}
`

**Comment by tsvetomir** [comment]
I see what you mean, thanks! I've missed the "model binding" part initially.

**Comment by Stamo-Gochev** [comment]
As the `MaxJsonLength` property cannot be changed from the `Web.config` in certain cases:
- http://www.telerik.com/forums/ajax-grid-serialization-bug-big-data#sfqhIJKJdUmZT096HAdZNw
- http://stackoverflow.com/questions/1151987/can-i-set-an-unlimited-length-for-maxjsonlength-in-web-config/7207539#7207539

we decided to increase it to its maximum value (`Int32.Max`) by default. 

If you need to make any additional configurations, you can use the [above approach](https://github.com/telerik/kendo-ui-core/issues/2667#issuecomment-284638185) with custom `JavaScriptSerializer`. In addition, the MVC wrappers for ASP.NET Core use the `Json.NET` serializer (which doesn't have such issues), so we can switch to it in the future.

**Comment by atif7** [comment]
@simonssspirit where do you have to include this code (work around)? can you show with example? will be really helpfull. Thanks.

**Comment by simonssspirit** [comment]
@atif7 This code can be added either in the Controller or in an upper base Controller.

**Comment by atif7** [comment]
Yes thanks, I figured it out :)

**Comment by satyambhatt** [comment]
Hl  use this return value 
            return new JsonResult() { Data = documentViewModelList.ToDataSourceResult(request), MaxJsonLength = Int32.MaxValue };
