### ISSUE TITLE
getAxis and findAxisByName method do not work during render event

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2668]
### Bug report

The described behavior is reproducible in this how-to article: http://docs.telerik.com/kendo-ui/controls/charts/how-to/appearance/custom-plot-bands. 

### Reproduction of the problem
http://dojo.telerik.com/UJuWAB

### Current behavior
getAxis and findAxisByName methods return undefined

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment
http://dojo.telerik.com/AkEMo

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12.4 
* **Browser:** [all]

**Comment by tsvetomir** [comment]
The fix will be included in the internal build tomorrow. Look for versions 2017.1.127 and later.
