### ISSUE TITLE
Virtualized ComboBox throws js error in MVVM scenario.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2677]
### Bug report

Virtualized ComboBox throws js error in MVVM scenario. 

If the pageSize is larger then expected a JS error will occur.

If the pageSize is correctly set, the noDataTemplete will be shown under the list of values.

### Reproduction of the problem

The issue can be observed in the following Dojo: http://dojo.telerik.com/UhUki/3

### Current behavior

The JS error occurs after dataBound when the list's items are bound via kendo.binder.

### Environment

* **Kendo UI version:** 2016.3.914 and later
* **Browser:** [all]

**Comment by jamnikr** [comment]
Do you have any plan to fix it? This is very important for us. This bug doesn't allow us to upgrade kendoui to the newest version.

**Comment by zdravkov** [comment]
Could not replicate the issue with the latest version.

**Comment by mparvanov** [comment]
The issue is not reproducible with Kendo R3 2017 SP2:
http://dojo.telerik.com/Ahuna
