### ISSUE TITLE
When TreeView bound to remote DataSource is nested in a PanеlBar in AngularJS scenario, the DataItems of the TreeView return undefined for their fields

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2679]
### Bug report
When bound to remote DataSource TreeView is nested within a PanalBar in AngularJS scenario, the DataItems of the TreeView return undefined for their fields. This problem is a regression, introduced with the R1 2017 release

### Reproduction of the problem
Run the following [Dojo](http://dojo.telerik.com/ESUGa/14)

### Current behavior
dataItem.FullName returns "undefinеd"

### Expected/desired behavior
dataItem.FullName should return the proper field value

### Environment

* **Kendo UI version:** 2017.1.118

**Comment by zdravkov** [comment]
In version 2017.1.118 we have added Template support for Panelbar control in Angular too and that is why when template is defined as in the example provided the templates are misleading. In such case we would rather recommend using setting the template of the treeview programatically as in the this [dojo](http://dojo.telerik.com/@zdravkov/iXAme)
