### ISSUE TITLE
Unable to set border-radius of ProgressBar from LESS ThemeBuilder

### ISSUE THREAD

**Issue by nlazarov** [telerik/kendo-ui-core#2680]
### Bug report

Border-radius style set from the [ThemeBuilder](http://demos.telerik.com/kendo-ui/themebuilder/) with *Bootstrap v3* is not reflected in ProgressBar.

### Reproduction of the problem

1. Open [ThemeBuilder](http://demos.telerik.com/kendo-ui/themebuilder/)
2. Choose *Bootstrap v3* theme
3. Change border radius to `0` or `20`

### Current behavior
ProgressBar edges stay the same - `border-radius: 4px;`

### Expected/desired behavior
ProgressBar edges are square - `border-radius: 0;` or `border-radius: 20;`

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
LESS ThemeBuilder is deprecated.
