### ISSUE TITLE
Copy/Paste range of data should behave like Excel 

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#2685]
### Description
Pasting a single value in a multi-cell range pastes the value only to the first cell in the range.

Suggested in Ticket 1086515
[Public Feedback item](https://feedback.telerik.com/kendo-jquery-ui/1359932-enable-cut-copy-cell-values-and-can-paste-it-in-mutiple-selected-values)

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/spreadsheet/index
1. Click on cell B3 (Calzone) and press CTRL+C
1. Click on cell B4, hold the shift key and arrow down until cells B4-B7 are highlighted
1. Press CTRL+V

### Current behavior
Only cell B4 receives the value of "Calzone".

### Expected/desired behavior
All cells B4-B7 should have the value Calzone".

### Environment
* **Kendo UI version:** 2019.2.619
* **jQuery version:** 1.12.3
* **Browser:** all

**Comment by veselints** [comment]
also requested in: https://supportheroes.telerik.com/ticket/1453633

**Comment by veselints** [comment]
Possible implementation is available here:
https://dojo.telerik.com/udopeJOl

**Comment by mparvanov** [comment]
1. Go to spreadsheet/index
1. Click on cell B3 (Calzone) and press CTRL+C
1. Click on cell B4, hold the shift key and arrow down until cells B4-B7 are highlighted
1. Press CTRL+V -> All cells B4-B7 have the value Calzone"
1. Press CTRL+Z 

### Current behavior
Only cell B4 restores its initial value.

### Expected/desired behavior
All cells B4-B7 restore their initial values

**Comment by mparvanov** [comment]
1. Go to spreadsheet/index
1. Mark cells B3 to B5 and press CTRL+C
1. Click on cell B9 and press CTRL+V -> B9 to B11 values are changed from 5,4,3 to 1,2,1
1. Press CTRL+Z 

### Current behavior
B9 to B11 values are changed from 1,2,1 to 5,4,3 

### Expected/desired behavior
B9 to B11 values are changed from 1,2,1 to 5,2,1

**Comment by mparvanov** [comment]
Cells formatting is not preserved on copy/paste:
1. Select D3 to D5
2. Copy and paste - Ctrl+C and Ctrl +V
Current behavior: the currency $ symbol is not pasted
