### ISSUE TITLE
Cannot focus and type in ComboBoxes added to the toolbar

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2686]
### Bug report

This is a regression bug. As of R2 2017, comboboxes cannot be focused and typed in.

### Reproduction of the problem
http://dojo.telerik.com/ewIri

### Current behavior
Try to put the cursor one of the comboboxes in the toolbar. 

### Expected/desired behavior
http://dojo.telerik.com/AwAQA

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by yegorpetrov** [comment]
The bug is still there for `resizable: true`: http://dojo.telerik.com/oMEcaPeL
