### ISSUE TITLE
Error occurs in Adobe reader when exporting the Grid.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2687]
### Bug report

Error occurs in Adobe reader when exporting the Grid. The Grid is shown with no data. The issue only occurs with Adobe reader, with other PDF viewers it is working as expected.

![pdferror](https://cloud.githubusercontent.com/assets/11087921/22423840/4d1e74fe-e6fc-11e6-8d4d-8fdd03157ae4.PNG)

### Reproduction of the problem

The issue can be reproduced on our demo page: http://demos.telerik.com/kendo-ui/pdf-export/index

I removed the Charts and the styles to isolate the issue: http://dojo.telerik.com/uLIji

### Environment

* **Kendo UI version:** 2017.1.118 - it is working as expected with older versions
* **Adobe reader:** 11.0.12
* **Browser:** [all]

**Comment by mishoo** [comment]
Funny, it works fine with IE (10).
