### ISSUE TITLE
Popup grid editing and Cancel scrolling

### ISSUE THREAD

**Issue by cyrusdowney** [telerik/kendo-ui-core#2689]
### Reproduction of the problem
_(bug report only)_
When ever the grid is navigatable **and** you are using the popup grid editing **and** user hits cancel, the grid scrolls to the bottom of the list.  You can best see the bug when you choose to edit the first record.  Additionally, after clicking cancel, then going to edit the first row again, the scrolling issue doesn't happen.

I've created a dojo to help display the issue: http://dojo.telerik.com/@jhinnen@momentum3.biz/aBUkA

### Expected/desired behavior
I would expect that I should be able to have a navigatable grid and use the popup without having the grid scroll unexpectedly to the bottom of the data.

### Environment

* **Kendo UI version:** 2016.3.1118
* **jQuery version:** 1.12.3
* **Browser:**  Chrome  55.0.2883.87

**Comment by MilenaCh** [comment]
I tried to replicate the unwanted behavior, but to no avail. Here, you can find a [video](https://www.screencast.com/t/V0PEE3uw) recorded during the testing. Please see it and provide exact steps for reproduce.
