### ISSUE TITLE
Update clear-filter icon in filter row

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-ui-core#2690]
Let's have the clear-filter icon `x` replaced with a more meaningful one:

Icon's class should be changed from `k-i-close` to `k-i-filter-clear` available in the [icon font](http://docs.telerik.com/kendo-ui/styles-and-layout/icons-web#actions)
![filter-clear](https://cloud.githubusercontent.com/assets/1118895/22458192/ffb019f4-e7a3-11e6-993b-0fab968b19da.png)

**Comment by MilenaCh** [comment]
'Filter' and 'Clear Filter' icons are not aligned in Firefix:
https://www.screencast.com/t/bejhxKgbbN
Most obvious in Metro theme.
