### ISSUE TITLE
The toolbar is creating a memory leak in Internet explorer 11.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2692]
### Bug report
The toolbar is creating a memory leak in Internet explorer 11. When going between pages with a ToolBar the memory usage can go up to 1 or 2 GB making the page unresponsive.

### Reproduction of the problem
The issue can be reproduced on our demo page: http://demos.telerik.com/kendo-ui/toolbar/index

Switch between examples for a couple of minutes and notice the memory usage.

The video demonstration in available in the ticket: 1085806

### Environment
* **Kendo UI:** 2019.3.1023
* **Browser:** [IE 11]

**Comment by Iankodj** [comment]
With latest version it seems to peek to ~600mb, but drops immediately to ~300mb, which is normal. 

![image](https://user-images.githubusercontent.com/4222379/38314874-eeff7de2-382f-11e8-9b86-ba4dcf4f0ff5.png)
