### ISSUE TITLE
DropDownList can not select the updated item if DataSource is sorted

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#2694]
### Bug report

DropDownList does not allow selecting an item which is updated when DataSource is sorted.

### Reproduction of the problem

Please refer to the http://dojo.telerik.com/iboMIN/3 example and try to replicate the issue: 
   1. Click on update button. 
   2. Open the DropDownList to see that the item position will be changed. 
   3. Try to select this item. The old item is still marked as selected. 
   4. Only select event is fired (change event is not fired). 

Note: Example with DDL v. 2019.2.619: http://dojo.telerik.com/IfOFEgEy

### Expected/desired behavior

The new selected item should be marked as selected and change event should be fired. As a possible workaround the value of the widget can be reset. Please refer to http://dojo.telerik.com/iboMIN/6 example. In order this workaround to work the value of the widget should not be reset when filtering. 

### Environment

* **Kendo UI version:** 2017.1.118
* **Kendo UI version:** 2019.2.619
* **jQuery version:** 1.12.3
* **Browser:** [all ]

**Comment by ag-petrov** [comment]
Seems to not reproduce with the latest version - https://dojo.telerik.com/IfOFEgEy/5
