### ISSUE TITLE
Kendo Grid Grouping problem in RTL mode.

### ISSUE THREAD

**Issue by ysmoradi** [telerik/kendo-ui-core#2695]
### Bug report

When I use kendo grid with grouping on RTL mode, arrows of expanding and collapsing rows are not showing the appropriate direction.

### Reproduction of the problem
Just open http://demos.telerik.com/kendo-ui/grid/right-to-left-support and group one of those fields.

### Expected/desired behavior
Instead of "<" direction, you'll see ">" direction as like as LTR mode.

### Environment

* **Kendo UI version:** "2017.1.118"
* **jQuery version:** "3.1"
* **Browser:** "all"

### Additional info:

Using following CSS classes, I managed to fix the problem temporarily 

```
.k-i-expand:before {
    content: "\e007";
}

.k-i-collapse:before {
    content: "\e002";
}
```

**Comment by ag-petrov** [comment]
Working fine in the latest version
