### ISSUE TITLE
The URL of some images in the custom CSS from the Theme Builder is none/sprite.png.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2696]
### Bug report

The URL of some images in the custom CSS from the Theme Builder is none/sprite.png.

Instead of none, it should be the folder name based on the used base theme.

A sample CSS rule is- background-image: url('none/sprite.png');

### Reproduction of the problem

The issue can be reproduced by downloading a custom theme: http://demos.telerik.com/kendo-ui/themebuilder/

**Comment by simonssspirit** [comment]
Reported again in ticket:  1085105

**Comment by simonssspirit** [comment]
Also, there is an unnecessary CSS rules added which are causing the icons to overlap:
`.k-icon,
.k-tool-icon,
.k-grouping-dropclue,
.k-drop-hint,
.k-column-menu .k-sprite,
.k-grid-mobile .k-resize-handle-inner:before,
.k-grid-mobile .k-resize-handle-inner:after,
.k-pager-numbers .k-current-page .k-link:after,
.k-scheduler-toolbar>ul.k-scheduler-views>li.k-current-view>.k-link:after,
.k-gantt-views>.k-current-view>.k-link:after {
    background-image: url('BlueOpal/sprite.png');
    border-color: transparent;
}`

**Comment by theOrlin** [comment]
Reported in 1113852

**Comment by mvgmvg** [comment]
Reported in 1117746

**Comment by theOrlin** [comment]
Reported in  1118137

**Comment by mvgmvg** [comment]
reported in 1119531

**Comment by theOrlin** [comment]
Also encountered in 1120232

**Comment by theOrlin** [comment]
Also reported in 1127814
