### ISSUE TITLE
Bad icons in Spreadsheet's Export PDF dialog

### ISSUE THREAD

**Issue by mishoo** [telerik/kendo-ui-core#2697]
Firefox:

![firefox](https://cloud.githubusercontent.com/assets/334725/22471529/43f7c8a0-e7db-11e6-9423-7880713e1e21.png)

Chrome:

![chrome](https://cloud.githubusercontent.com/assets/334725/22471533/490cb076-e7db-11e6-8abc-bc9899699a61.png)

**Comment by joneff** [comment]
Fixed by ec1b5b4bb3d40b853b89bc9ffe5e15ecd18cad62

**Comment by Dimitar-Goshev** [comment]
Icons are proper now. The issue needs another iteration of improvement to fix the appearance of this functionality in the dialog:
![image](https://user-images.githubusercontent.com/6614183/28114215-72478c34-6708-11e7-9087-a62461423c10.png)

**Comment by Dimitar-Goshev** [comment]
I added some comments and questions to the pull request.

**Comment by Dimitar-Goshev** [comment]
As a result of the latest improvement https://github.com/telerik/kendo/commit/b4bde3049dc089b5ae35b60aee098acbcf45984f , buttons in button groups lost focus indication in Black, Blue Opal, Default, Fiori, High Contrast, Metro Black, Moonlight, Nova, Office 365, Silver and Uniform themes.
