### ISSUE TITLE
Image Browser can't add new Folder

### ISSUE THREAD

**Issue by ErpBoy** [telerik/kendo-ui-core#2700]
### Bug report

Added New Folder will not show. 

**For Feature Requests - please submit those into [our UserVoice feedback portal](http://kendo.uservoice.com/)**

### Reproduction of the problem

Go to http://demos.telerik.com/kendo-ui/editor/imagebrowser and load the Insert Image or Insert File dialog.
Create a new folder then rename it and click on any images. 

### Current behavior
I can also replicate using 2017.1.11. 

### Expected/desired behavior
The added folder should not disappear when the user rename it or press enter key. 

### Environment

Kendo UI version: 2016.3.11.18
Browser: [all]

**Comment by mparvanov** [comment]
Hi ErpBoy,

Thanks for your report, and for your interest in Kendo UI Core! I was not able to replicate the described issue with Kendo Editor version 2017.1.223.
Please note that bug reports against previous versions will be closed.

Thanks again for the issue report, and for using Kendo UI Core!
