### ISSUE TITLE
JavaScript error thrown when resizing sub-columns in a multi-header columns scenario

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2701]
### Bug report

The following JavaScript error is thrown when an attempt to resize a sub-column group is made:

Uncaught TypeError: Cannot read property 'minResizableWidth' of undefined

### Reproduction of the problem

[http://demos.telerik.com/kendo-ui/grid/multicolumnheaders](http://demos.telerik.com/kendo-ui/grid/multicolumnheaders)

Start resizing the "Location" column or any of its descendants.

### Current behavior

The JavaScript error, described above is thrown.

### Expected/desired behavior
No JavaScript errors should be triggered.

### Environment

* **Kendo UI version:** 2017.1.118

**Comment by dimodi** [comment]
Fixed by https://github.com/telerik/kendo/commit/45f26369329965a8d19d568750223967be99a516
