### ISSUE TITLE
Update third-party dependencies

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#2702]
We currently ship the following libraries as part of Kendo UI.

* jQuery 1.12.3 - the latest version is 1.12.4
* [Pako](https://github.com/nodeca/pako) (pako_deflate) 1.0.1 - can be upgraded to 1.0.4
* JSZip 2.6.0 - can be upgraded to 2.6.1
* Angular 1.4.6 - not sure if we can upgrade to 1.6.x /cc @ggkrustev ?

**Comment by ggkrustev** [comment]
Yeah, the [Angular 1.4.x]() limitation was resolved in Q3 2016 release (if I recall correctly). We will need to update the documentation to reflect the new functionality.

Also it seems that widgets work just fine with angularjs@1.6.1:
- http://dojo.telerik.com/EqUnUL

**Comment by DaleCam** [comment]
Actually @ggkrustev, please note that in your dojo - ng-model is not updated on change of the combo. Pretty major bug. I can replicate this locally using 1.6.1 of angular. Thanks.

**Comment by ggkrustev** [comment]
@DaleCam, you are absolutely right! 

The widget doesn't update the model and it seems that the 'culprit' in this case seems to be the complete rewrite of the select's ngModel functionality. The new select integration built's internal [value maps](https://github.com/angular/angular.js/blob/89f3e3b0af74d6ea2f2741b4d6eced184e1a2b1a/src/ng/directive/select.js#L164), which will not be populated if the select options are added with JavaScript, which we actually do.

We will try to address the issue with several adjustments.
