### ISSUE TITLE
Custom Script Builder does not automatically select all required dependencies

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2704]
### Bug report

If the PanelBar is checked in the [Custom Script Builder](http://www.telerik.com/download/custom-download), then DataSource -> OData should be automatically checked as well, since the widget depends on it. If it is not included, a js exception (Uncaught TypeError: Cannot read property 'create' of undefined at init._dataSource...) is thrown when you use the downloaded script.  

### Reproduction of the problem
Create and load a custom script for the PanelBar without including DataSource -> OData. 

### Current behavior
The Builder does not automatically select the required dependency. 

### Expected/desired behavior
All scripts that a widget depends on are selected automatically. 

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by tsvetomir** [comment]
This is probably due to [the metadata](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.panelbar.js#L10) missing a dependency to ["data.odata"](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.data.js#L15).

**Comment by Dimitar-Goshev** [comment]
To be tested, when the new version is uploaded.
