### ISSUE TITLE
Selected font is not populated to editor fontName dropdown for text inserted programmatically

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#2709]
### Bug report

Selected font is not populated to editor fontName dropdown for text inserted programmatically.
The issue is relevant for Internet Explorer while the fontName dropdown is populated as expected in Chrome and Firefox

### Reproduction of the problem

http://dojo.telerik.com/@parvanov/OxaWU 
Click on the text inside editor content 

### Current behavior
The DropDown shows empty

### Expected/desired behavior
The dropdown is populated with "Arial, Helvetica, sans-serif" fontname

### Environment

* **Kendo UI version:** 2017.1.118
* **Browser:** IE

**Comment by SumitMeh** [comment]
Even i have faced this issue, would be helpful if we can get a solution for this.

**Comment by Iankodj** [comment]
When adding text programmatically, Editor is not focused and its select event is not triggered. Thus, the toolbar's tools are not refreshed with new values. 

To resolve, you can call the focus method after setting up the value and trigger the select event. 

http://dojo.telerik.com/ukeguQeB
