### ISSUE TITLE
Grid buttons display empty box (instead of nothing) when iconClass is set to an empty string

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2715]
### Bug report

Grid buttons icons are no longer hidden (an empty box is displayed instead) when iconClass is set to an empty string.

### Reproduction of the problem
[http://dojo.telerik.com/AKerI/7](http://dojo.telerik.com/AKerI/7)

Desired behavior (observed when previous Kendo UI version is used):

[http://dojo.telerik.com/AKerI/8](http://dojo.telerik.com/AKerI/8)

### Environment

* **Kendo UI version:** 2017.1.118

**Comment by joneff** [comment]
@hadjieva this should be handled within the grid. If the issue us not within the grid, but in the button, then it should be fixed there.

**Comment by ag-petrov** [comment]
Closed with - https://github.com/telerik/kendo/commit/abed8a03625eb35e140b12117ba67987a95bcb76
