### ISSUE TITLE
Improve the documentation and the examples for Kendo UI with webpack and NPM.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2717]
Add examples for JS + Kendo UI core and TS + Kendo UI Pro:

https://github.com/telerik/kendo-ui-npm-example

Refactor the documentation for:

http://docs.telerik.com/kendo-ui/third-party/webpack

http://docs.telerik.com/kendo-ui/intro/installation/npm

**Comment by simonssspirit** [comment]
The example for TypeScript and Kendo UI Pro is added.

The documentation is also updated.

@tsvetomir Please advise if the JavaScript + Core example should be removed as it is currently not working, probably based on a dependency issue. If the issue is on our side, it should be logged.

**Comment by tsvetomir** [comment]
The issue seems to be caused by a missing dependency. There shouldn't be a difference in the packaging of the Core/Pro products.

**Comment by simonssspirit** [comment]
The documentation is updated, the TypeScript example is added and an issue is raised for investigating the dependency in the Core package: https://github.com/telerik/kendo/issues/6736
