### ISSUE TITLE
The destroy method is not working on MediaPlayer widget with YouTube source

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2720]
### Bug report

The destroy method is not working on MediaPlayer widget. A JavaScript error occurs when the destroy method is called:

Uncaught TypeError: Cannot set property 'ontimeupdate' of undefined

### Reproduction of the problem

The issue can be reproduced in the following Dojo: dojo.telerik.com/ILuqo

### Environment
* **Browser:** [all ]

**Comment by marclazell** [comment]
was this ever fixed?

**Comment by Dimitar-Goshev** [comment]
@marclazell  Yes, this issue was fixed and the fix was released in R2 2017 as pointed by the Milestone.

**Comment by marclazell** [comment]
@Dimitar-Goshev my mistake - I missed this, thank you!
