### ISSUE TITLE
Selection problems with touch events in Chrome under Windows 8.1

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2725]
### Bug report

Under Chrome in Windows 8.1, it is difficult to open the dropdown popup using touch events. Even if opened, by typing some text, selecting an item is impossible with touch events. 

### Reproduction of the problem

http://dojo.telerik.com/IQEho

1. Open dojo and try to open dropdown by using the button. 

Actual: Flickering, the virtual keyboard is opened and the popup is not shown.

1. Open dojo
1. Select the input
1. Type 'r'
1. Try to select an item.

Actual: Virtual keyboard is closed but selection is not performed.

### Workaround

Use the following overwrite:
```javscript
kendo.ui.DropDownList.fn._popup=function(){
  kendo.ui.Select.fn._popup.call(this);
  this.popup.one("open", $.proxy(this._popupOpen, this));

  $(this.list).on("touchend.StaticList", "li", $.proxy(this._click, this))
  $(this.list).on("touchend.StaticList",".k-list-optionlabel", $.proxy(this._click, this))
}
```
###
### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12.3
* **Browser:** [ Chrome 56.0.2924.87 ]

**Comment by iAmcDiddy** [comment]
It's also a bug on tablets running Windows 10 and Chrome.
