### ISSUE TITLE
ListView Multiple Selection "_firstSelectee" not tracked when selections are programmatic

### ISSUE THREAD

**Issue by IanAtOcucom** [telerik/kendo-ui-core#2728]
### Bug report

When modifying selections programmatically (to restore selections removed by record-modification), the first selectee cursor is not retained, and all selections start at the first item in the list. Affects `selectable="multiple"` ListViews

### Reproduction of the problem
http://dojo.telerik.com/@ian+telerik@ocucom.com/OlUhO

### Current behavior
Interactive multi-select selections following non-interactive selections always revert to starting from item zero instead of the first or last item in the selection group.

### Expected/desired behavior
When setting a selection in the listview using listView.select(items), and then shift-clicking to expand the selection with the mouse, the "start" of the selection should be at the currently-selected item furthest in the list from the clicked-upon item. 

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12
* **Browser:** all

**Comment by ag-petrov** [comment]
This is not a bug, it is a design decision. The selectable tracks the last user iteraction not api calls. If you select the items using the mouse(perform user iteraction) and later select a larger subset the items will be selected as per the expectations. The select functionality is similar to that in other controls. Here is an example of a grid that behaves in the same exact manner - http://dojo.telerik.com/ahaco/18

If you would like to set a last active element for the selectable when calling the api you can follow the approach demonstrated [here](http://dojo.telerik.com/aZaHev/3).
