### ISSUE TITLE
Kendo UI Sortable does return incorrect indices in the end event in AngularJS application if filtering option is enabled. 

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#2730]
### Bug report

Kendo UI Sortable does return incorrect indices in the end event in AngularJS application if filtering option is enabled. 

### Reproduction of the problem

Please refer to the http://dojo.telerik.com/atocek example. Try to sort the items and check the console output. 

### Expected/desired behavior
It should return correct old and new index. 

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12.3
* **Browser:** [all ]

**Comment by ag-petrov** [comment]
This is not a bug, but rather a wrong configuration. When a custom placeholder is defined it should match the filter criteria. That said the fix for the specific case is to add the sortable class for the placeholder. [Here ](http://dojo.telerik.com/EGOwuSiH)is a dojo illustrating this.
