### ISSUE TITLE
Kendo UI DatePicker and DateTimePicker MVVM initialization ignores data-week-number option

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#2731]
### Bug report

Kendo UI DatePicker and DateTimePicker MVVM initialization ignores data-week-number option. 

### Reproduction of the problem

Please refer to the http://dojo.telerik.com/ODayi example and open the calendar of the DatePicker. 

### Expected/desired behavior

The week number column should be displayed. 

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12.3
* **Browser:** [all ]

**Comment by Xizario** [comment]
https://github.com/telerik/kendo-ui-core/commit/e0f86952231d719052556be57b15902e6500443e
