### ISSUE TITLE
Grid Excel Export with JSZip v. 3+ causes a JavaScript error

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2733]
### Bug report
Using JSZip v.3.0+ causes a JavaScript error in the Grid Excel Export functionality
### Reproduction of the problem

[http://dojo.telerik.com/IrOpE](http://dojo.telerik.com/IrOpE)

### Expected/desired behavior
The  Grid Excel Export functionality to work with the current JSZip version

**Comment by tsvetomir** [comment]
Duplicate of #2316
