### ISSUE TITLE
MVC DropDownList in Grid custom editor cannot be focused and expanded (jQuery 3.0.0 and newer)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2735]
### Bug report
The DropDownList MVC wrapper's dropdown cannot be focused and expanded when the component is nested in a Grid's column editor and jQuery v3.0.0-3.1.1 is referenced. 

### Reproduction of the problem
The issue is reproducible in the [Editing Custom Editor](https://demos.telerik.com/aspnet-mvc/grid/editing-custom) demo (Category column) with the following library loaded: https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js

### Current behavior
On click the row flickers, but the DropDownList's dropdown cannot be expanded.

### Expected/desired behavior
On click the DropDownList is properly focused and can be expanded. 

### Environment

* **Kendo UI version:** 2016.3.1118 and 2017.1.118
* **jQuery version:** 3.0.0-3.1.1
* **Browser:** [Chrome, IE 11]

**Comment by matanasov** [comment]
Doesn't replicate with R3 2018 (2018.3.911)
