### ISSUE TITLE
ComboBox filtering problem

### ISSUE THREAD

**Issue by jeebsorg** [telerik/kendo-ui-core#2738]
Hi Kendo Team,

I took a portion of your ComboBox example, and added an item to fabric one, as can be seen on this jsfiddle: https://jsfiddle.net/t4kz1fpg/

If you type cotton into the input, a close paren character is automatically appended.  So here, I added something like 100% (Cotton), while keeping also the standard Cotton option.  If you type Cotton, you will see the input read "Cotton)".  I would expect the behavior to simply auto-select and read "Cotton".

Thank you,

Jerad

**Comment by Dimitar-Goshev** [comment]
Hi @jeebsorg ,
The reported behavior is expected, when the Combobox [suggest](https://docs.telerik.com/kendo-ui/api/javascript/ui/combobox#configuration-suggest) property is set to true. "If set to **true**, the widget will automatically use the **first** suggestion as its value." As "100% (Cotton)" is the first item matching Cotton in the list of items, it is selected. If the Cotton item is added before "100% (Cotton)", then only Cotton will be selected.
