### ISSUE TITLE
Grid group row header is considered as newly selected row which is unexpected.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2740]
### Bug report

Grid group row header is considered as newly selected row which is unexpected. Also, the field value for the first row under that header is returned from the dataItem method.

### Reproduction of the problem

The issue can be observed in the following Dojo:  http://dojo.telerik.com/UXoQeZ

Steps:

1) Open the log console
2) Click a row. See that it is now selected and that there is a log message containing the row element and the name field value for that row.
3) Click the group header. See that no rows are selected and that there is a log message containing the group header element and the name field value for the first row under that header.

### Environment

* **Browser:** [all]

**Comment by Stamo-Gochev** [comment]
I am not able to reproduce the problem with the latest version in the master branch.
