### ISSUE TITLE
Navigatable grid closes dirty empty cells on click in Edge

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2743]
### Bug report

Navigatable Grid with "incell" edit mode closes **dirty & empty** cells on click in Edge. Reported in ticket ID 1088710.

### Reproduction of the problem

- Open [Dojo](http://dojo.telerik.com/emONo/4) in Edge
- Click on any cell and clear its content
- Press Enter
- Click on the dirty cleared cell - the cell will enter edit mode after many clicks or with a double-click

### Possible Workaround

Add an event listener to the click event of the `<td>` elements and call the [editCell()](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#methods-editCell) method of the Kendo UI Grid. 

[Dojo](http://dojo.telerik.com/aRuqu)

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12
* **Browser:** [Edge ]

**Comment by Stamo-Gochev** [comment]
The issue is not reproducible with the latest version from the master branch.
