### ISSUE TITLE
Incorrect dropdown position when the page is scrolled (IE) and rtl is enabled

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2744]
### Bug report
When the page is scrolled clicking on the widget (DropDownList, ComboBox, MultiSelect, AutoComplete) displays its dropdown at an incorrect position. The behavior is reproduced when the k-rtl class is set to the widget's container. The issue is introduced in version 2016.3.914.

### Reproduction of the problem
[Dojo ](http://dojo.telerik.com/ICaZU/3)example. 
1. Scroll down the page.
2. Click on the widget: its dropdown shows up detached from the component at a unexpected position.

### Current behavior
Incorrect dropdown position

### Expected/desired behavior
Correct dropdown postition.

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** x.y
* **Browser:** [IE ]

**Comment by AlaaFouad** [comment]
Hi,

I made a fix for it in the following 
http://dojo.telerik.com/OviKu/37

Alaa Fouad
