### ISSUE TITLE
The returned ng-model has trimmed empty spaces initially present in the AutoComplete and ComboBox' data source

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2748]
### Bug report
After selecting an item, the text of which contains leading and trailing empty spaces the returned ng-model has the empty spaces (initially present in the AutoComplete and ComboBox' data source) trimmed.

### Reproduction of the problem
[Dojo](http://dojo.telerik.com/EfOWA) example
1. Select the Empty Spaces item.
2. The returned sting does not contain the empty spaces (before and after the actual text) that are present in the data source. 

### Current behavior
Empty spaces are trimmed

### Expected/desired behavior
Empty spaces are preserved, as they are when using a standard select:  [dojo](http://dojo.telerik.com/aKisU).

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by Iankodj** [comment]
The case is related to `ng-model` and `input` elements. The same is discussed here: https://github.com/angular/angular.js/issues/2010. 

The solution is to use `ng-trim='false'`. http://dojo.telerik.com/ajaZEHAw
