### ISSUE TITLE
groupHeaderTemplate is not compiled for angular/aurelia

### ISSUE THREAD

**Issue by JeroenVinke** [telerik/kendo-ui-core#2749]
### Bug report

**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our UserVoice feedback portal](http://kendo.uservoice.com/)**

### Reproduction of the problem
Repro: http://dojo.telerik.com/EyucU
Here you can see that `eventTemplate` is compiled nicely, but `groupHeaderTemplate` is not. 

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** v1.12.3
* **Browser:** all

**Comment by JeroenVinke** [comment]
The `slotTemplate` of the scheduler seems to have the same issue ([repro](http://dojo.telerik.com/ocAkE)).

**Comment by Xenope** [comment]
Hi, 

just to inform you, we have a commercial licence with kendo so i opened an issue on the telerik site as well.
The guys came back to me with this answer : 

> Currently, Scheduler does not support angular template directives for the groupHeaderTemplate. Have a look at this article showing the supported template directives among the widgets:
>
> http://docs.telerik.com/kendo-ui/AngularJS/introduction#template-directives
>
> You could use the groupHeaderTemplate as follows: http://docs.telerik.com/kendo-ui/api/javascript/ui/scheduler#configuration-groupHeaderTemplate or modify the current function:
>
> groupHeaderTemplate: function (e) {
       return e.text + "@@";
},
> 
>Regards,
>Joana 
>Telerik by Progress

With the info provided I managed to do what i wanted. It's up to you if you wanna close this one.

Thanks.

**Comment by JeroenVinke** [comment]
Thanks for keeping us up to date 👍

**Comment by Iankodj** [comment]
The shorts answer is that groupHeaderTemplate supports only MVVM syntax. For this to be included as template directive, you can submit a proper feature request here:  http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback.
