### ISSUE TITLE
DatePicker and CurrencyTextBox stopped working in Chromium 56

### ISSUE THREAD

**Issue by tahaipek** [telerik/kendo-ui-core#2751]
### Bug report
I have a same issue in this post. [http://www.telerik.com/forums/datepicker-and-currencytextbox-stopped-working-in-chrome-56](http://www.telerik.com/forums/datepicker-and-currencytextbox-stopped-working-in-chrome-56)

### Reproduction of the problem
[Dojo](http://dojo.telerik.com/UyIsA/21) example

1. Set current computer Culture in Turkey/Turkish or different from en-US.
2. And set numericTextBox default value 1000000,25 _(1.000.000,25)_

### Current behavior
When I set "1000.02" default value to kendo numericTextBox then it is giving 100002. It is normal for en-US culture. But we are working in tr-TR culture format and value must be shown as "1000,02". To see that result I already added **kendo.culture.tr-TR.min.js** and I have called **kendo.culture("tr-TR")** at head of page. Doing this operations didn't solve my problem and when I set the value as "1000,02" it is giving an error on console. 

The message is : **"The specified value "1000,02" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)? "**. 
This problems were created after Chrome / Chromium based browsers was updated to version 56 

### Expected/desired behavior
We are working in tr-TR culture format and default value must be shown as "1000,02".

### Environment

* **Kendo UI version:** v2014.2.903 | v2017.1.118 
* **jQuery version:** x.y
* **Browser:** [ Chrome 56.X | Opera 56.X | Yandex 56.X] and Chromium Based Browser 

![untitled](https://cloud.githubusercontent.com/assets/5754670/22786931/1e4db628-eee3-11e6-9bd7-ea52a0fc16d9.png)

**Comment by canperk** [comment]
I have same issue and no solution yet. Turkish culture is giving error when I set decimal value to numerictextbox

**Comment by MilenaCh** [comment]
The correct setup in this scenario would be to set the value in widget configuration, but no to html element and remove type="number" from input's markup.
See the modified dojo example [here](http://dojo.telerik.com/UyIsA/33).
