### ISSUE TITLE
PanelBar fires Select event two times when bound with dataSource

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2752]
### Bug report

When items are bound with DataSoucre, the first time you select an item, the select event fire twice.

### Reproduction of the problem
Click on a node and inspect that triggering is logged 2 times in the browser console.

### Current behavior
http://dojo.telerik.com/awiRA

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by ScottKirsten** [comment]
I spent hours thinking I did something wrong in my 2017 migration, thank you for catching this
