### ISSUE TITLE
508 compliance improvements for Grid component.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-ui-core#2756]
**Bug report**

Currently, grid does not pass 508 compliance in some scenarios:

1.Column filter icons need text(http://dojo.telerik.com/aNoxu)
2.In hierarchical grids the expand arrow fails needs text(http://dojo.telerik.com/eLUbE)
3.The input box in the pager needs a label(http://dojo.telerik.com/OqeVO)
4.The select list in the pager needs a label(http://dojo.telerik.com/EbEqOV)

**Reproduction of the problem**

Open the corresponding examples in Full screen mode in Chrome and validate with Wave extension OR load the Full screen mode URL in [WAVE Validator](http://wave.webaim.org/) 

**Current behavior**

Errors appear in these scenarios 

**Expected/desired behavior**

508 compliance validation should pass without errors.

**Environment**

Kendo UI version: 2017.1.118
Browser: [all]

**Comment by MilenaCh** [comment]
The problems below still could be replicated:
3.The input box in the pager needs a label(http://dojo.telerik.com/OqeVO)
4.The select list in the pager needs a label(http://dojo.telerik.com/EbEqOV)

**Comment by Stamo-Gochev** [comment]
@dbalinov @MilenaCh 
I am moving the item back into the current sprint, so we can check it. The milestone can be updated, when all the improvements are applied.

**Comment by Stamo-Gochev** [comment]
@MilenaCh @dbalinov 
The issue is being re-opened as additional changes should be added (we removed the fix from `<td>` to `<th> to pass the compliance check).
