### ISSUE TITLE
Calendar weekNumber does return incorrect week number in some time zones 

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#2758]
### Bug report

Calendar weekNumber does return incorrect week number in some time zones . For example if the local time zone is set to UTC +1, it will start week numbers from 2 instead of 1 for 2017. 

### Reproduction of the problem
It can replicated on http://demos.telerik.com/kendo-ui/calendar/week-column demo if time zone is set to UTC +1. Please navigate to January 2017. 

### Expected/desired behavior
It should start counting the week numbers from 1 instead of 2. 

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12.3
* **Browser:** [all ]

**Comment by simonssspirit** [comment]
Reported also in ticket: 1087383

**Comment by danielkuhlmann** [comment]
There are more issues with the display of the weeknumber in the date time picker.
Move in the example to march and you will see two weeks number 14.
the kendo.date.weekInYear() does return correct week numbers, but some how the display of week numbers is incorrect. 

For me it also unclear how to easily handle different week number calculations:
first week of year starting 1st of january
first full week
first 4 days of year

**Comment by EduardoSerra** [comment]
Also reported in ticket number 1105342.

**Comment by boyandim** [comment]
This problem is fixed with Kendo UI latest official release.
