### ISSUE TITLE
numerictextbox  focusout event triggered before _inputWrapper is initialized

### ISSUE THREAD

**Issue by vascofernandes** [telerik/kendo-ui-core#2759]
### Bug report

I have a Grid with inline row edit.
This Grid is setup using Kendo UI ASP.NET MVC. All great so far.

When clicking on the "Edit" command button, then the following error occurs:

> Uncaught TypeError: Cannot read property 'removeClass' of undefined (kendo.numerictextbox.js:269) 

My analysis of the problem is the following:
The field where it fails is a NumericTextBox where the initialization code emitted server side is:
```javascript
jQuery(function(){jQuery("#Quantity").kendoNumericTextBox({"format":"{0:n3}","spinners":false,"decimals":3});});
```

When the user clicks the Edit command button, the initialization code above will run.

Eventually we get to the [`NumericTextBox.init()`:](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.numerictextbox.js#L47)

[Then a focusout event is bound to the input](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.numerictextbox.js#L55)

[Then the input wrapper is setup](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.numerictextbox.js#L80)

[Inside of `NumericTextBox._wrapper()`, because the element is not yet wrapped, it will try wrapping the input with a span](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.numerictextbox.js#L677)

[and in the next line the **`.wrap()` call will make the focusout event previously bound fire**.](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.numerictextbox.js#L678)
[
This cases the error "Cannot read property 'removeClass' of undefined" in when the `NumericTextBox ._focusout` handler runs.](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.numerictextbox.js#L388)

Problem is that `that._inputWrapper` is still undefined since this line was not run yet:
https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.numerictextbox.js#L688

* **Kendo UI version:** Kendo UI v2017.1.118
* **jQuery version:** 3.1.1
* **Browser:**  Chrome 56 

Full stracktrace from the console:

> Uncaught TypeError: Cannot read property 'removeClass' of undefined (kendo.numerictextbox.js:269) 
>     at init._focusout (kendo.numerictextbox.js:269)
>     at HTMLInputElement.dispatch (jquery-3.1.1.js:5201)
>     at Object.trigger (jquery-3.1.1.js:8171)
>     at Object.simulate (jquery-3.1.1.js:8230)
>     at HTMLDocument.handler (jquery-3.1.1.js:8289)
>     at buildFragment (jquery-3.1.1.js:4829)
>     at domManip (jquery-3.1.1.js:5729)
>     at jQuery.fn.init.wrapAll (jquery-3.1.1.js:9342)
>     at HTMLInputElement.<anonymous> (jquery-3.1.1.js:9372)
>     at Function.each (jquery-3.1.1.js:368)
>

**Comment by vascofernandes** [comment]
I found the root cause of our the issue. Here is the relevant part. 

```javascript
    $(document).ready(function () {

        $('#SomeGridId').data('kendoGrid').cellFocusSelector = 'input:eq(1)';

    });
```
After removing this line everything works as expected.

This snippet programmatically set focus to specific cell when grid is in inline edit mode.
Therefore when the user clicks to edit the line the input will be focused and the _focusout_ event will triggered. 
As per the description in the original post, the `that._inputWrapper` in the _focusout_ handler will not yet be initialized.

Removing the line solves our issue, and this is an acceptable compromise for today, but we would like to see a definitive solution for this.

How could we make sure that all inputs in the row have been initialized ? 
(so the after we can set focus on the specific one we want)


Best Regards

**Comment by Xizario** [comment]
@vascofernandes, the I don't see the cellFocusSelector to be build-in property. So it would depend on how you use it later. I would suggest you to call the focus using a timeout, to be sure the editors are initialized. 

We for sure can add check [here](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.numerictextbox.js#L388), if the wrapper is defined. But I am not convinced this alone will fulfill your requirements, and if the focus will work correct for your case.

If you modify [this dojo](http://dojo.telerik.com/icUkO/2) to replicate the issue, we could discuss the possible resolutions here.

**Comment by vascofernandes** [comment]
You suggestion based on timeout worked.  

After the update to the latest kendo ui/jquery  is seems that some execution order has changed.
Adding timeout around our own focus() operation makes sure the kendo input is fully initialized.

But this is not a good solution.

In general I find that it is very difficult to control when kendo elements are created and ready.
Add setTimeout is a hack.

It would be useful to have events such as "onElementCreated", "onElementDestroy", etc...

Anyway, I have a workaround.

**Comment by vascofernandes** [comment]
Hi,

We have a very similar problem again. I can reproduce it in a Dojo.

We use ASP.NET MVC to generate the grid: 

````csharp
 Html.Kendo().Grid<PosUnitModel>()
    .Name("PosUnitsGrid")
    .Columns(col =>
    {
        col.Bound(x => x.Number);
        col.Command(cmd => cmd.Destroy());
    })
    .DataSource(ds =>
        ds.Ajax()
        .Read(x => x.Action("GetPosUnits", "Configuration", new { storeId = Model.StoreId }))
        .Destroy(x => x.Action("DestroyPosUnits", "Configuration"))
        .Model(m => {
            m.Id(x => x.Id);
        })
    )
```

**Comment by Xizario** [comment]
The later problem happens because of this [change in jquery 3](https://jquery.com/upgrade-guide/3.0/#breaking-change-document-ready-handlers-are-now-asynchronous)
The numeric text box in the tempalte is initialized with delay. Thus if there was not document.ready into the template it would have worked: http://dojo.telerik.com/EvAQu/6

We are aware of this issue and some fix will be provided soon.

**Comment by vascofernandes** [comment]
Thanks for the information.

How soon does "soon" mean ? 
Really have some tight schedule on this.

Best Regards.

**Comment by Xizario** [comment]
It is already fixed, will be part of the upcoming service pack this week.
