### ISSUE TITLE
PanelBar's change event fires twice

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2761]
### Bug report

On PanelBar item selection the widget's change event fires twice.

### Reproduction of the problem
Sample [dojo](http://dojo.telerik.com/EJUhA).

### Current behavior
Change event fires twice on item selection.

### Expected/desired behavior
Change event fires once on item selection as the TreeView's change event does. 

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** x.y
* **Browser:** [Chrome, IE]

**Comment by ScottKirsten** [comment]
My Dashboard uses the PanelBar and it has worked out beautifully.  However, since upgrading to the 2017, I have noticed that the select event indeed fires twice which causes some issues of data loading twice.
