### ISSUE TITLE
The disabled icon in the Grid pager with Metro Theme is not visible on hover

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#2764]
### Bug report
The disabled icon in the Grid pager with Metro Theme is not visible on hover

### Reproduction of the problem
Hover over the Previous or First button in the Grid's page (over the font icon in the button) and its color will be changed to white (will become invisible)
http://dojo.telerik.com/imISO/3

### Expected/desired behavior
The font icon should be visible on hover

### Environment

* **Kendo UI version:** 2017.1.118

Temporary workaround:
`  <style>
    .k-link.k-pager-nav.k-state-disabled:hover{
      border-color: #ddd;
    }
    .k-state-disabled .k-icon{
      color: #555;
    }
  </style>`

**Comment by Dimitar-Goshev** [comment]
The issue in Metro is fixed. But after the fix, disabled buttons in Material, Material Black and Nova have visible border on hover:
![image](https://user-images.githubusercontent.com/6614183/33183921-b243a654-d082-11e7-8440-d64bde9ebe54.png)
