### ISSUE TITLE
Spreadsheet wrapper throws JS error, when placed in Partial view, which is loaded upon action.

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#2765]
### Bug report

When the user interaction to load the partial view (where the spreadsheet is placed) is triggered several times and fast - it reflects as JS error thrown for a SplitButton in the Toolbar of the widget.

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ivanchev** [comment]
Problem is caused by improper disposing of the widget, and is not an issue with the widget itself.
