### ISSUE TITLE
A 'System.NullReferenceException' is thrown in MakeCurrentUrlRelative method when more than 3 optional Url parameters are defined in MapRoute

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#2766]
### Bug report
The issue is reproducible when more than 3 optional Url parameters are defined in route configuration of the MVC project.

### Reproduction of the problem
Define more than 3 optional Url parameters in RouteConfig.cs:
```
public static void RegisterRoutes(RouteCollection routes)
        {
            routes.IgnoreRoute("{resource}.axd/{*pathInfo}");
            routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}/{p1}/{p2}/{p3}/{p4}",
                defaults: new { controller = "Home",
                                action = "Index",
                                p1 = UrlParameter.Optional,
                                p2 = UrlParameter.Optional,
                                p3 = UrlParameter.Optional,
                                p4 = UrlParameter.Optional,
                }
            );
        }

```
Layout view:
```
                    @(Html.Kendo().Menu()
                                .Name("Menu")
                                .Items(items =>
                                {
                                    items.Add().Text("Home").Action("Index", "Home", new { area = "" });
                                    items.Add().Text("About").Action("About", "Home", new { area = "" });
                                    items.Add().Text("Contact").Action("Contact", "Home", new { area = "" });
                                })
                    )
```

Run the project.

### Current behavior
The following error is thrown:
```
 at Kendo.Mvc.Infrastructure.Implementation.InternalHttpRequestBase.MakeCurrentUrlRelative(String appCurrentUrl)
   at Kendo.Mvc.Infrastructure.Implementation.InternalHttpRequestBase.get_AppRelativeCurrentExecutionFilePath()
   at System.Web.Routing.RouteCollection.IsRouteToExistingFile(HttpContextBase httpContext)
   at System.Web.Routing.RouteCollection.GetRouteData(HttpContextBase httpContext)
   at Kendo.Mvc.Infrastructure.Implementation.RouteDataCache.RouteDataFactory(String url)
   at Kendo.Mvc.Infrastructure.Implementation.RouteDataCache.<>c__DisplayClass1.
```

### Environment

* **Kendo UI version:** 2017.R1
* **jQuery version:** v1.12.3

**Comment by nenchef** [comment]
The bug is **not** related to Telerik UI for ASP.NET MVC implementation. 

It's rather a configurational issue. When you need to declare such amount of optional parameters, you should define them in a separate MapRoute:

        public static void RegisterRoutes(RouteCollection routes)
        {
            routes.IgnoreRoute("{resource}.axd/{*pathInfo}");
            routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}",
                defaults: new
                {
                    controller = "Home",
                    action = "Index"
                }
            );
            routes.MapRoute(
               name: "Params",
               url: "{controller}/{action}/{p1}/{p2}/{p3}/{p4}",
               defaults: new
               {
                   controller = "Home",
                   action = "Index",
                   p1 = UrlParameter.Optional,
                   p2 = UrlParameter.Optional,
                   p3 = UrlParameter.Optional,
                   p4 = UrlParameter.Optional,
               }
           );
        }
