### ISSUE TITLE
Editor removes empty row, when there is an empty paragraph element in the html (< p> < /p>) and a Copy command is performed (either with mouse or keyboard)

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#2769]
### Bug report

Editor removes empty row, when there is an empty paragraph element in the html (< p> < /p>) and a Copy command is performed (either with mouse or keyboard). Pasting empty paragraph should insert a bomNode as a child node.

### Reproduction of the problem
use the following dojo example:

http://dojo.telerik.com/aDUVe/6

Select the entire content of the Editor and press Ctrl+C or right mouse button click and select copy

### Current behavior

The empty row, created due to the empty paragraph usage is removed.

### Expected/desired behavior
Should not remove the empty row and persist the initial layout.

### Workaround:
http://dojo.telerik.com/aDUVe/10

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by henkli** [comment]
I am seeing the same behaviour on 2017.2.621.
Any news on when this can get fixed? Very annoying bug.

**Comment by IvanDanchev** [comment]
Priority 1 (ID=1132403)

**Comment by IvanDanchev** [comment]
Priority 2 (ID=1136749)
