### ISSUE TITLE
The Draggable is not auto-scrolled on MS Edge if all of the area is not visible initially and there is a vertical scrollbar on the page.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2771]
### Bug report

The Draggable is not auto-scrolled on MS Edge if all of the area is not visible initially and there is a vertical scrollbar on the page. The container is auto-scrolled on the other browsers as expected.

### Reproduction of the problem

The issue can be observed in the following Dojo example: http://dojo.telerik.com/emuXI

### Expected/desired behavior

The page should be scrolled on MS Edge as on the other browsers.

### Environment

* **Browser:** [MS Edge]

**Comment by zdravkov** [comment]
Could not replicate it with latest version.
