### ISSUE TITLE
Searchbar placeholder is "undefined" in http://docs.telerik.com/

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2779]
### Bug report

The placeholder of the search bar input in docs is "undefined".
 
<img src="http://image.prntscr.com/image/f99a0ce20b794b8bb959f70e05c71785.png"/>

**Comment by gyoshev** [comment]
Seems that it was an isolated issue with the Google Search widget, and has since been resolved.
