### ISSUE TITLE
Second half of two days event is not shown when event end is Never or specific day

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-ui-core#2782]
### Bug report

If a recurrent event that is across two days is created and for event end is selected Never or specific day, the second part of the event is not shown.

### Reproduction of the problem
1. Open this dojo example - http://dojo.telerik.com/UhAfe
2. Create event that is across two days and choose Repeat: Daily and End: Never

### Current behavior
The second part of the event is missing.

### Expected/desired behavior
The second part of the event is shown.

### Environment

* **Kendo UI version:** 2017.1.118
* **Browser:** all

**Comment by nenchef** [comment]
The timeline is intended for singe-day display. If you need to show several days in timeline view, you can use the [timelineWeek] or the customization approach demonstrated in [this article](https://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/how-to/custom-views/timeline-with-dynamic-length)
