### ISSUE TITLE
Browser's dragging of the drag handles is not prevented

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-ui-core#2789]
### Bug report

Drag hint shows when clicking on empty step and dragging immediately without releasing the mouse button.

Dojo sample: http://dojo.telerik.com/eyepo/2
Issue reproduction video - https://www.screencast.com/t/i6T7WTXsY

Workaround: Cancel browser's drag of the slider drag handle.
$(document).on("dragstart", ".k-draghandle", function(e) {
    e.preventDefault();
});
### Environment

* **Kendo UI version: 2017.1.118
* **Browser: Chrome

**Comment by Iankodj** [comment]
Fixed in [rangleslider-link-drag](https://github.com/telerik/kendo/compare/rangleslider-link-drag)
