### ISSUE TITLE
Selected time on DateTimePicker stays selected when a new one is selected(only Windows Phone 8)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2790]
### Bug report

Selected time on DateTimePicker stays selected when a new one is selected(only Windows Phone 8). When the user selects the new time, the old one still appears as selected resulting in multiple selected times(visually).

### Reproduction of the problem

The issue can be observed in the following Dojo on Windows Phone 8: http://dojo.telerik.com/@Lance/isifOq

### Environment

* **Browser:** [Windows Phone]

**Comment by Xizario** [comment]
Browser of windows phone was unsupported from January 12, 2016 with no further updates, and even if this issue is from 2017 I am closing.
