### ISSUE TITLE
Inconsistency in the border-radius of the calendar container in the Calendar widget and the DatePicker popup in Bootstrap theme 

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#2794]
### Bug report
Inconsistency in the border-radius of the calendar container in the Calendar widget and the DatePicker popup in Bootstrap theme 

### Reproduction of the problem
http://dojo.telerik.com/ivEjO/3

### Current behavior
The border-radius of the calendar is not the same in the Calendar and DatePicker popup

### Expected/desired behavior
The border-radius should be consistent and should be applied to all borders, not only to the bottom borders

### Environment

* **Kendo UI version:** 2017.1.118

**Comment by mvgmvg** [comment]
Actually this is an expected behavior: Calendar widget should not have rounded corners. The same widget used in popup of DatePicker should have rounded corners except those that are placed on the side next to the DatePicker input.
