### ISSUE TITLE
Spreadsheet: when filter is applied to a column (some values / rows are hidden) and a value is copied to below / above cells, using the lower right corner handle, the hidden cells in between the visible cells get the dragged value

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2797]
### Bug report
Spreadsheet: when filter is applied to a column (some values / rows are hidden) and a value is copied to below / above cells, using the lower right corner handle, the hidden cells in between the visible cells get the dragged value. The behavior of Excel is different - it does not change the values in the hidden (filtered out) cells.

### Reproduction of the problem
* Go to the [Index demo](https://demos.telerik.com/kendo-ui/spreadsheet/index)
* Add filtering to the Quantity column;
* Filter the above column to leave only those rows, that have value of "1". Rows 3, 5, 6 and 8 should be visible;
* Change the value of the C3 cell to "A";
* Drag that cell value over the other visible cells using the lower right cell corner handler;
* Open the filter menu, uncheck and check the All checkbox. All the rows from 3 to 8 will be displayed and all the C column cells on those rows will have value of "A";

### Expected/desired behavior
The value of the filtered out (hidden) cells should not be changed. This is also how Excel behaves in this scenario.

**Comment by tsvetomir** [comment]
Will merge the fix after the SP1 release tomorrow. Internal builds and the next official releases will include it.
