### ISSUE TITLE
DropDownList with Bootstrap Popover

### ISSUE THREAD

**Issue by RaptorCZ** [telerik/kendo-ui-core#2798]
Is there any way how to use Bootstrap popover with Kendo DropDownList?

I'm using Knockout in my application with custom kendo-knouckouts bindings. But sometimes I need to attach popover to DropDownList, but input field is hidden inside html of generated Kendo control, so popover doesn't work.

I think it must be somehow generated on top span element of Kendo control.

```
<input data-bind="kendoDropDownList: $root.getKendoDropDownListDefinition(), popover: $root.getPopoverDefinition()" />
```

**Comment by Juveniel** [comment]
The Kendo DropDownList can be successfully initialized in a Bootstrap Popover by cloning the already initialized widget markup in the popover as demonstrated in the following Dojo example:
* [https://dojo.telerik.com/IBeRUxAY/2](https://dojo.telerik.com/IBeRUxAY/2)
