### ISSUE TITLE
ValueMapper function gets called unexpectedly when ComboBox has initially selected value and the user changes the selection to one of the next items

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2803]
### Bug report
ValueMapper function gets called unexpectedly when ComboBox has initially selected value and the user changes the selection to one of the next items.

### Reproduction of the problem
* Could be observed on the following [Dojo](http://dojo.telerik.com/aPIqi/2);
* Open the drop-down and select the next item. The valueMapper function will be called and an AJAX call will be initiated;

### Expected/desired behavior
The valueMapper function should not be called when already loaded item is selected;

**Comment by zdravkov** [comment]
Could not replicate it with the latest version.
