### ISSUE TITLE
TimePicker popup misalignment with Nova theme

### ISSUE THREAD

**Issue by nlazarov** [telerik/kendo-ui-core#2804]
### Bug report

The popup of the TimePicker with Nova theme is not aligned to the left edge of the input.

![timepicker_popup](https://cloud.githubusercontent.com/assets/182215/23167223/2e3ea002-f84c-11e6-877c-f325420dbff6.png)

### Reproduction of the problem

1. [http://demos.telerik.com/kendo-ui/timepicker/index](http://demos.telerik.com/kendo-ui/timepicker/index)
2. Select **Nova** theme
3. Open TimePicker's popup

### Current behavior

Popup is offset to the left, missing the left edge of the input.

### Expected/desired behavior

Popup is aligned with the left edge of the input.

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Reproducible with R3 2017 as well. In addition, the icon color in Nova is wrong for all Date and Time Pickers.
