### ISSUE TITLE
Displaced DateTimePicker icons in RTL for Material, Material Black, Fiori and Nova themes

### ISSUE THREAD

**Issue by nlazarov** [telerik/kendo-ui-core#2805]
### Bug report

The appearance of the buttons in the DateTimePicker in an RTL container seems incorrect.

#### Material Black
![datetimepicker_rtl](https://cloud.githubusercontent.com/assets/182215/23169456/780a92c4-f854-11e6-98ff-13d9537890da.png)

#### Nova
![datetimepicker_rtl_nova](https://cloud.githubusercontent.com/assets/182215/23169459/7cdab310-f854-11e6-9370-0f2c51e354a2.png)

### Reproduction of the problem
1. Go to [http://demos.telerik.com/kendo-ui/datetimepicker/right-to-left-support](http://demos.telerik.com/kendo-ui/datetimepicker/right-to-left-support)
2. Change theme to **Material Black** or **Nova**

### Current behavior
The icons are not aligned correctly horizontally and a vertical line appears on hover.

### Expected/desired behavior

Icons are correctly aligned and there is no gap in the buttons.

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Reproducible with 2017.2.621 as well.

**Comment by Dimitar-Goshev** [comment]
The issue is last reproducible with R3 2017 SP2. It is no longer reproducible with R1 2018.
