### ISSUE TITLE
ListView does not work with shared DataSource

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#2810]
### Bug report

When a DataSourceID is passed to the ListView an exception is thrown. 

### Reproduction of the problem

The Code below results in circular reference exception.

`<script type="text/x-kendo-tmpl" id="template">
    <div class="product">
        <img src="@Url.Content("~/content/web/foods/")#:ProductID#.jpg" alt="#:ProductName# image" />
        <h3>#:ProductName#</h3>
        <p>#:kendo.toString(UnitPrice, "c")#</p>
    </div>
</script>

<div class="demo-section k-content wide">
   @(Html.Kendo().DataSource<Kendo.Mvc.Examples.Models.ProductViewModel>()
    .Name("dataSource1")
    .Ajax(dataSource => dataSource
       .Read(read => read.Action("Products_Read", "DataSource"))
    )
)

@(Html.Kendo().ListView<Kendo.Mvc.Examples.Models.ProductViewModel>()
    .Name("listView")
    .TagName("div")
    .AutoBind(false)
    .ClientTemplateId("template")
    .DataSource("dataSource1")
    .Pageable()
)`

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** all
* **Browser:** all

**Comment by okhustad** [comment]
I am trying to share a datasource between Kendo-Grid and Kendo-Listview. Datasource work with Grid, an throws Circular reference exception for listview. 
Listview works if i

```
    @(Html.Kendo().DataSource<ProcessStartedViewModel>()
    .Name("dataSourceProcessStarted")
    .Ajax(dataSource => dataSource
    .ServerOperation(true)
    .PageSize(10)
    .Model(model => model.Id(m => m.Oppdragsnr))
    .Read(read => read.Action("GetStartedProcesses", "Process"))))

    @(Html.Kendo().ListView<ProcessStartedViewModel>()
          .Name("StartedProcess")
          .TagName("div")
          .DataSource("dataSourceProcessStarted")
          .ClientTemplateId("template")
    )
```
Listview works if I declare the same datasource using the lambda expression.

```
 @(Html.Kendo().ListView<ProcessStartedViewModel>()
          .Name("StartedProcess")
          .TagName("div")
          //.Selectable()
          .DataSource(dataSource =>
          {
              dataSource
                  .PageSize(10)
                  .Read(read => read.Action("GetStartedProcesses", "Process"));

          })
          .ClientTemplateId("template")
          .Pageable(pager => pager
              .Input(true)
              .Numeric(false)
              .Info(true)
              .PreviousNext(true)
              .Refresh(true)
              .PageSizes(new int[] { 5, 10, 20, 50 }))
    )

```
Environment

Kendo UI version: 2017.1.118.545
jQuery version: all
Browser: all

**Comment by simonssspirit** [comment]
A similar issue occurs when the shared DataSource is passed to the column.filterable.dataSource property of the Grid.

Argument 1: cannot convert from 'string' to 'System.Action<Kendo.Mvc.UI.Fluent.ReadOnlyDataSourceBuilder>'

**Comment by Xizario** [comment]
https://github.com/telerik/kendo/commit/5a8ea911e72974db5c0d34d7e2dd2fe255f32c08
@VicTachev, @MilenaCh
