### ISSUE TITLE
parseDate ignores timezone sign for minutes offset

### ISSUE THREAD

**Issue by akrassikov** [telerik/kendo-ui-core#2813]
### Bug report

kendo.core.js -- parseExact(value, format, culture){}
// Splits timezone into hours and minutes, but only hours portion has the sign (+|-).

matches = value.substr(valueIdx, 6).match(count > 2 ? longTimeZoneRegExp : shortTimeZoneRegExp);
...
matches = matches[0].split(":");
hoursOffset = matches[0];
minutesOffset = matches[1];
...
hoursOffset = parseInt(hoursOffset, 10);
minutesOffset = parseInt(minutesOffset, 10);
...
if (hoursOffset) {
  hours += -hoursOffset;
}

if (minutesOffset) {
  minutes += -minutesOffset;
}

value = new Date(Date.UTC(year, month, day, hours, minutes, seconds, milliseconds));

Simple fix: add the sign before you call parseInt() on the minutesOffset like so:
minutesOffset = match[0][0] + minutesOffset;

And increase the range for the incorrect minutes from (0, 59) to (-59, 59) like you have hours.
if (isNaN(minutesOffset) || outOfRange(minutesOffset, **-59**, 59)) {
return null;
}

### Reproduction of the problem

kendo.parseDate('2017-02-23T10:00:00-01:00');
// Thu Feb 23 2017 06:00:00 GMT-0500 (Eastern Standard Time) // correct

kendo.parseDate('2017-02-23T10:00:00-00:30');
 // Thu Feb 23 2017 04:30:00 GMT-0500 (Eastern Standard Time) // incorrect

kendo.parseDate('2017-02-23T10:00:00-00:00'); 
// Thu Feb 23 2017 05:00:00 GMT-0500 (Eastern Standard Time) // correct

kendo.parseDate('2017-02-23T10:00:00+00:30');
// Thu Feb 23 2017 04:30:00 GMT-0500 (Eastern Standard Time) // correct

### Expected/desired behavior

kendo.parseDate('2017-02-23T10:00:00-00:30');
// should return: 
// Thu Feb 23 2017 05:30:00 GMT-0500 (Eastern Standard Time)

### Environment

Kendo UI version: 1.408
Browser: all

Tested on an old version, but it looks like your current code is still broken at the time I am writing this message.

**Comment by matanasov** [comment]
@ag-petrov 
Calling those 2 lines return the same result which is not expected:

`kendo.parseDate('2017-02-23T10:00:00-00:30');`
`kendo.parseDate('2017-02-23T10:00:00+00:30');`
