### ISSUE TITLE
Undo scrambles formula cell references when undoing an added row

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#2816]
### Bug report

**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our UserVoice feedback portal](http://kendo.uservoice.com/)**

### Reproduction of the problem
_(bug report only)_
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via http://dojo.telerik.com or similar.

### Current behavior
Use the Kendo Demo Spreadsheet - https://demos.telerik.com/kendo-ui/spreadsheet/index

Insert a row, for example insert a new row 5.    
Remove it with undo button
Double click F7 for example (or any F greater then the added row)
The references of the formulas are not on the same row

### Expected/desired behavior
The references of the formulas should be on the same row

### Environment
Here is a [video](https://www.screencast.com/t/jRJxbcHNOm) of the issue.
* **Kendo UI version:**2017.1.223
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jwbqv** [comment]
This bug is still in 2017.2.504 & is a rather serious bug because it makes the calculations in a spreadsheet wrong without the user knowing they are wrong.  What is the prognosis for a fix?

**Comment by mishoo** [comment]
@jwbqv I agree the issue is serious.  Sorry it fell off the radar.  It's now being worked on and a fix will be available soon.

**Comment by Dimitar-Goshev** [comment]
@jwbqv The issue was fixed in R3 2017 (version 2017.3.913). It is not reproducible since then. It is OK with R2 2018 and R2 2018 SP1 releases.
