### ISSUE TITLE
Broken layout of Editor's File and Image browser dialogs with Default v2 and Bootstrap v4 themes

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#2819]
### Bug report/Reproduction of the problem

Run http://demos.telerik.com/kendo-ui/editor/imagebrowser, select the Default v2 theme and open the file and image browsers.

![image](https://cloud.githubusercontent.com/assets/2556751/23354954/58364008-fccb-11e6-9edc-71a64c6d9775.png)

![image](https://cloud.githubusercontent.com/assets/2556751/23354967/69a04cb2-fccb-11e6-8776-5f0555934cb8.png)

### Environment

* **Kendo UI version:** 2017.1.223 with Default v2 theme (Note the problem does not occur with other themes.)
* **Browser:** All

**Comment by Dimitar-Goshev** [comment]
Overall the layout is not that broken after the fixes. However, there are remaining issues as follows:
- Files and images are not arranged as a grid as in other themes. Instead, they are arranged as list items.
- Uploaded file details remain visible after upload, which forces the Arrange by dropdown to fall on a second line. In other themes, such file details are not visible after upload:
![image](https://user-images.githubusercontent.com/6614183/27090932-4493e06a-5067-11e7-8047-30293560f8f1.png)

- Broken breadcrumbs appearance - create a New folder and then double click on it to navigate to it:
![image](https://user-images.githubusercontent.com/6614183/27091076-c32990aa-5067-11e7-84c1-1d5d53ad9dbe.png)
- Search icon is displaced in Edge browser:
![image](https://user-images.githubusercontent.com/6614183/27091568-36c892d0-5069-11e7-9560-29349d7e53d2.png)
