### ISSUE TITLE
Wrong week number if 53 weeks

### ISSUE THREAD

**Issue by pettersoft** [telerik/kendo-ui-core#2822]
### Bug report
The wrong week number is displayed using the Kendo Datepicker. Assuming it's because that 2016 had 53 weeks. 

### Reproduction of the problem
http://dojo.telerik.com/oniku

### Current behavior
The first week of the current year is 2 if the previous year ends with week 53. This displaces every week of the year. For example now its week 9 according to the ISO8601 standard but the datepicker displays week 10. Locale used 'sv-SE', however, the error exists no matter which locale is used. Tested in .NET MVC and using jQuery.

### Expected/desired behavior
Expected behaviour is for the year to start with week 1 instead of week 2.

### Environment
* **Kendo UI version:** 2017.1.223
* **jQuery version:** 2.2.4
* **Browser:** all

**Comment by boyandim** [comment]
This problem is fixed with Kendo UI latest official release.

**Comment by pettersoft** [comment]
Thank you!

**Comment by tobbin2** [comment]
Is this issue resolved with a new version of kendo.mvc.fluent.ui?

**Comment by pettersoft** [comment]
This was resolved four years ago.

Den ons 24 feb. 2021 kl 11:00 skrev tobbin2 <notifications@github.com>:
