### ISSUE TITLE
Moving an event outside the business hours display the wrong time in timelineview

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#2828]
### Bug report

When moving an event outside of the business hours range using drag and drop, the end time is stuck to the workDayEnd hour in timeline view.
Note: The issue is not reproducible in Day view

### Reproduction of the problem
http://dojo.telerik.com/@parvanov/eZIdu
Drag the Evaluations appointment to earlier or later time

### Current behavior
The end time stays 5:00 PM

### Expected/desired behavior
The label on the appointment displays the new start and end hours

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.11.3

**Comment by nenchef** [comment]
The bug is fixed
