### ISSUE TITLE
NumericTextBox arrows have the wrong offset in docs

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-ui-core#2830]
### Reproduction of the problem
* open http://docs.telerik.com/kendo-ui/api/javascript/ui/numerictextbox#configuration-factor 
* go to preview tab

![image](https://cloud.githubusercontent.com/assets/13347/23403283/20b7c352-fdb8-11e6-9a27-97dc0e4e30c7.png)

The up/down arrows are displaced

### Expected/desired behavior
The arrows should be centered

### Environment

* **Kendo UI version:** 2017.1.233
* **Browser:** Chrome 56, Windows 10, size of text set to 150% (not sure if relevant)

**Comment by ag-petrov** [comment]
Not reproducible with the latest version.
