### ISSUE TITLE
Selected font size and font name are not shown in the toolbar's comboboxes in IE

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-ui-core#2831]
### Bug report

Selected font size and font name are not shown in the toolbar's comboboxes when clicking in an empty paragraph or empty content area in IE only. Reproducible in http://dojo.telerik.com/avERI/9.

### Reproduction of the problem
1. Type something, select it and apply font size
2. Set the cursor at the end of the text and press enter. The correct font-size is shown at the combo.
3. Click on the new created element(paragraph)

### Current behavior
The combo does not show the font size any more.

### Expected/desired behavior
The font size should not be changed.

### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** IE11

**Comment by Iankodj** [comment]
Not reproducible with latest version.
