### ISSUE TITLE
Add templates support for PanelBar in MVVM

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#2832]
Currently PanelBar does not support templates in MVVM scenario. The PanelBar is similar to the TreeView, which supports templates - [Dojo](http://dojo.telerik.com/OhiNe) . If the TreeView is substituted by PanelBar, there will be no checkbox on each PanelBar item.

### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** [all]

**Comment by crb02005** [comment]
Any progress?
