### ISSUE TITLE
Redundant class attributes on DOM elements after Export to PDF, image, SVG

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#2837]
### Bug report
The issue starts to reproduce since 2016 Q1 SP1.

### Reproduction of the problem
1. Use the following [Dojo](http://dojo.telerik.com/eQoki)
2. Inspect the first Grid cell
3. Export to PDF/ image/ SVG
4. Inspect the first Grid cell.

### Current behavior
Empty class attributes remain on Grid elements after export - [screenshot](https://www.screencast.com/t/APlyOFdb8J)

### Expected/desired behavior
No redundant class attributes on Grid elements after export. (Switch Kendo version in the Dojo to 2016 Q1)

### Environment

* **Kendo UI version:** 2016.1.226 to latest R1 2017 SP1)
* **Browser:** [all]

**Comment by mishoo** [comment]
PDF supports JPEG natively, so we optimize images with content-type `image/jpeg` by just dumping the file content directly into the PDF stream ([see the relevant code](https://github.com/telerik/kendo-drawing/blob/6126b41d79dd208cd389ac9f97e3b134a22de0ff/src/pdf/core.js#L432-L449)), as opposed to PNG-s, which we render on a canvas and then retrieve via `canvas.toDataURL` which we then BASE64-decode (a lot of work).

I'm not sure why this image doesn't render properly in a PDF viewer, but I have checked that the content embedded in the PDF stream is exactly the same as the image binary.

One solution that works, however, is to disable this optimization.  But, without even measuring the impact, I'm pretty sure this will slow down considerably exporting JPEG images, along with increasing memory usage, so I'm quite hesitant to do it.

**Comment by mishoo** [comment]
We use [element.classList](https://developer.mozilla.org/en/docs/Web/API/Element/classList)'s add/remove to manipulate the class name.  Seems add(name) followed by remove(name) leaves the empty class attribute in the DOM.  I see no harm in that, therefore won't fix.
