### ISSUE TITLE
Embedded Kendo Menu in TabStrip Tab causes the next tab to not be able to display its content

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2841]
### Bug report
Embedded Kendo Menu in TabStrip Tab causes the next tab to not be able to display its content. The issue is present since R1 2017 release. It is not reproducible with older releases.

### Reproduction of the problem
- Open the following [Dojo](http://dojo.telerik.com/ErOBI/9)
- Click on the first tab -> the content is displayed;
- Click on the second tab -> no content is displayed.

### Environment
* **Kendo UI version:** 2017.1.118

**Comment by lwwells** [comment]
This is crucial for the enterprise application we are building.  This was working prior to my upgrade of Kendo.  if you could put together a fix and release the affected files so I can work it into the current version that would be fantastic. Or, if that's not possible, I would greatly appreciate it if this could be addressed ASAP in the next point release. Any word on when the next release will occur?  Thanks!

**Comment by Dimitar-Goshev** [comment]
The next Kendo UI release is scheduled for [May 17, 2017](https://github.com/telerik/kendo-ui-core/milestone/43)
