### ISSUE TITLE
Images with xmp metadata (from illustrator) are not exported to PDF

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#2845]
### Bug report

Images with xmp metadata (from illustrator) are not exported to PDF

### Reproduction of the problem
[http://dojo.telerik.com/@parvanov/OTUZa/4](http://dojo.telerik.com/@parvanov/OTUZa/4)
Export the 2 images 

### Current behavior
Only the first image is exported

### Expected/desired behavior
Both images are exported

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 1.12.3

**Comment by mishoo** [comment]
PDF supports JPEG natively, so we optimize images with content-type `image/jpeg` by just dumping the file content directly into the PDF stream ([see the relevant code](https://github.com/telerik/kendo-drawing/blob/6126b41d79dd208cd389ac9f97e3b134a22de0ff/src/pdf/core.js#L432-L449)), as opposed to PNG-s, which we render on a canvas and then retrieve via `canvas.toDataURL` which we then BASE64-decode (a lot of work).

I'm not sure why this image doesn't render properly in a PDF viewer, but I have checked that the content embedded in the PDF stream is exactly the same as the image binary.

One solution that works, however, is to disable this optimization.  But, without even measuring the impact, I'm pretty sure this will slow down considerably exporting JPEG images, along with increasing memory usage, so I'm quite hesitant to do it.

**Comment by mishoo** [comment]
Fixed.
