### ISSUE TITLE
Incorrect Spreadsheet filtering with Turkish letters

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#2846]
### Bug report

http://dojo.telerik.com/AsoSiwET

filter "i" or "İ" both shows “KEBİR” and “icra”
filter "ı" or "I" both should show “SATIŞ” and “alınan çekler” but this is not working in spreadsheet component.

http://character-code.com/turkish-html-codes.php
 Steps:
open filter and type or copy/paste “Lowercase i-dotless“ char in the search input
 
In filter area I want to see two world; Word start with KEB… and  Tah…
 
Open filter and type or copy/paste “Capital I-dotted “ char in the search input
 
In filter area I want to see two world; Word start with SAT… and  Al…

### Environment

* **Kendo UI version:** 2019.3.1023

**Comment by mishoo** [comment]
Fixed by taking the current culture into account in filtering.  In order for it to work you need to load and use kendo.culture.tr-TR.js.
