### ISSUE TITLE
Spreadsheet displays no more than 76694 rows in IE

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2854]
### Bug report
Spreadsheet displays no more than 76694 rows in IE

### Reproduction of the problem
[Dojo](http://dojo.telerik.com/Ukute/3)

### Expected/desired behavior
Spreadsheet should display all rows (100,000) as the other browsers do

**Comment by mishoo** [comment]
I suspect there is a hard browser limit here.  See this: http://stackoverflow.com/questions/18708598/ie-fundamental-limit-of-scrolltop-in-a-large-scrollable-div

I wouldn't say this is of “medium” severity.

**Comment by tsvetomir** [comment]
Doesn't look fixable to me.

**Comment by catmanjan** [comment]
If the problem is max element size, why not create a new element once you reach the threshold.

**Comment by mparvanov** [comment]
Closing due to browser limitation.
