### ISSUE TITLE
add kendo.attr to public API

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#2855]
### Environment

* **Kendo UI version:** 2017.1.223

kendo.attr function missing from documentation here http://docs.telerik.com/kendo-ui/api/javascript/kendo
and from TypeScript definitions.
Still it is exposed in kendo object and used not only by kendo internals but you can find that is used by users. E.g.
https://github.com/telerik/kendo-ui-core/issues/2799
http://www.telerik.com/forums/imagebrowser-identifier
https://stackoverflow.com/questions/24982708/kendo-ui-grid-sort-by-descending-before-ascending

For me it looks like this function must be properly documented or if it is not intended to be a part of public API - it should be hidden from kendo object, or prefixed with underscore.

**Comment by jlchereau** [comment]
There is one which is related and which I am using frequently: ```kendo.roleSelector```. I would recommend using them, especially in custom widgets, because of kendo.ns.
