### ISSUE TITLE
Observable.bind signature in typescript definitions must accept event list

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#2856]
### Environment

* **Kendo UI version:** 2017.1.223

```javascript
bind(eventName: string, handler: Function): Observable;
````
but should be
```javascript
bind(eventName: string, handler: Function): Observable;
bind(events: string[], handlers: { [event: string]: Function }): Observable;
````

**Comment by matanasov** [comment]
@ivanchev @hadjieva 
Please comment on this suggestion.

**Comment by ivanchev** [comment]
Approved. With the addition of the following:
bind(events: string[], handler: Function): Observable;

and the same overloads for the `one` and `first` methods, they will be available in R3 2018.
