### ISSUE TITLE
Add support for showing and hiding the widget with ng-show

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#2858]
### Reproduction of the problem
Currently the control is not working correctly when you try to hide and show it with ng-show yet it is working ok if you use jQuery show()/hide()(ticket - 1095485)

### Current behavior
_(optional)_
Provide additional information if the steps for reproducing the faulty behavior are not sufficient to describe the issue.

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment

* **Kendo UI version:2017.1.223
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Dimitar-Goshev** [comment]
Starting with R2 2022, the Kendo UI team officially drops the support for AngularJS 1.x through Kendo UI for jQuery
