### ISSUE TITLE
The Tooltip does not hide on every point if multiple points are shown together.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2860]
### Bug report

The Tooltip does not hide on every point if multiple points are shown together. If the points are close to each other, multiple Tooltips will be shown on hover but only the last one will disappear when the mouse leave the points.

### Reproduction of the problem

The issue can be observed in our demo:  http://demos.telerik.com/kendo-ui/map/remote-markers

Please check the screencast demonstrating the issue:  https://www.screencast.com/t/y3sWUsOMp

### Environment

* **Browser:** [all]

**Comment by ag-petrov** [comment]
Seems to not reproduce anymore

**Comment by matanasov** [comment]
Doesn't replicate with R1 2019 SP1 (2019.1.220)
