### ISSUE TITLE
Change event only trigger the first column, if you select two columns for copy and paste them only on one column

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#2862]
### Bug report

Change event only trigger the first column, if you select two columns for copy and paste them only on one.

### Reproduction of the problem
Select Column A and B. Ctrl+C to copy them. Select column D and paste with Ctrl+V.

### Current behavior
 The range return in the change event is only for the Column D, 

### Expected/desired behavior
The returned range object should contain the range of Column D as well as E

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mparvanov** [comment]
The issue is not reproducible with v. 2019.3.1023
