### ISSUE TITLE
Editor messages configuration does not alter the dropdown tools tooltip

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2864]
### Bug report
Editor messages.insertHtml does not alter the InsertHtml tooltip

### Reproduction of the problem
In the following [Dojo](http://dojo.telerik.com/OCUke/3) the tooltips for the insertImage and insertFile tools are correctly configured to a custom value. The tooltip for the insertHtml tool, however, is not.

### Expected/desired behavior
The tooltip for the insertHtml tool should be configured according to the messages.insertHtml field.

**Comment by mparvanov** [comment]
The issue is relevant for all dropdown tools.

**Comment by abuassar** [comment]
Would you please give this issue some attention. It has been 5 months since it was reported.

**Comment by Iankodj** [comment]
Issue is handled in the internal branch [editor-dropdowns-title](https://github.com/telerik/kendo/tree/editor-dropdowns-title).

**Comment by Dimitar-Goshev** [comment]
The Formatting issue mentioned is related to not working tooltip property, messages works as expected for Formatting. I logged the issue as a separate one - https://github.com/telerik/kendo-ui-core/issues/4281
