### ISSUE TITLE
Error-registry error parsing json

### ISSUE THREAD

**Issue by saurabhschauhan** [telerik/kendo-ui-core#2865]
### Bug report

when I'm installing my node packages I'm facing the following issue after just the simple **npm install** command. please resolve my issue as soon as possible.
![screenshot from 2017-03-07 18 32 09](https://cloud.githubusercontent.com/assets/25522343/23657919/7b83c0a2-0366-11e7-9328-8a86b38edd11.png)

**Comment by tsvetomir** [comment]
You need to have an active license for Kendo UI to access the packages - either a commercial or trial. The error message in the error log is "403 - Forbidden: Access is denied."
