### ISSUE TITLE
MultiSelect: screen readers announce only one of the selected items

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2867]
### Bug report
Multiselect: screen readers announce only one of the selected items. JAWS in IE announces only the last selected item.

The reason for the observed is the fact that the focusable input of the widget always has its *aria-activedescendant* attribute set to the last selected item from the list.

Because of the above, if no items are selected, the announced is the one from the list that is focused.

### Reproduction of the problem
http://dojo.telerik.com/ohaDe/10

**Comment by veselints** [comment]
Also reported in Ticket ID: 1140467

**Comment by jivanova** [comment]
Duplicated: https://github.com/telerik/kendo-ui-core/issues/4020
