### ISSUE TITLE
Keyboard navigation through editor's text skips empty lines in IE and Edge

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#2869]
### Bug report

UP/DOWN navigation through editor text skips empty lines

### Reproduction of the problem

1. Open demo website in IE: http://demos.telerik.com/kendo-ui/editor/index
2. Insert empty paragraphs at the end of the content
3. Press the RETURN key on the keyboard
4. Press Up/Down arrows

### Current behavior
Caret jumps to the beginning of the first line with text when UP/Down key is pressed.

### Expected/desired behavior
Could be observed in other browsers. Navigation should go through the empty lines

### Environment

* **Kendo UI version:** 2017.1.118
* **Browser:** all

Note: the issue starts to reproduce since R2 2016 - 2016.2.504

**Comment by Iankodj** [comment]
Commit that causes the regression is 44f8fd5aba6177a1f5f858d6996e987335b27237
