### ISSUE TITLE
type-THEME_NAME.less files should be splitted into several per-control files

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#2871]
### Environment

* **Kendo UI version:** 2017.1.223

Right now theme less styles stored in a single file which makes it impossible to create CSS file only for used controls. It should be splitted into spearate files like it is done for base styles (common folder).

**Comment by matanasov** [comment]
@joneff 
Please comment on this.

**Comment by joneff** [comment]
We are already doing this, as visible from the files in https://github.com/telerik/kendo-ui-core/tree/master/styles/web/themes.

Still it's a slow process and will take its time.
