### ISSUE TITLE
Not working how-to examples for the Charts after version 2017*

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2874]
Affected examples:

- http://docs.telerik.com/kendo-ui/controls/charts/how-to/appearance/create-left-to-right-gradient-multi-color-values

- http://docs.telerik.com/kendo-ui/controls/charts/how-to/appearance/draw-on-scatter-plots

- http://docs.telerik.com/kendo-ui/controls/charts/how-to/appearance/custom-plot-bands

- http://docs.telerik.com/kendo-ui/controls/charts/how-to/appearance/linear-gradient-bars

All of the examples are working as expected with the latest version of 2016 (2016.3.1118).

**Comment by simonssspirit** [comment]
@tsvetomir @danielkaradachki Please advise if there is a known issue causing these errors, or the examples have to be changed, as all of them are starting from Q1 2017.

**Comment by danielkaradachki** [comment]
Known issues. All examples are working with the latest service pack

**Comment by simonssspirit** [comment]
Ok, so once the version of the How-to example is updated they will work as expected.
