### ISSUE TITLE
Setting the PanelBar's animation expand/collapse duration does not have the expected effect (MVC)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2878]
### Bug report
In the MVC wrapper setting animation expand/collapse duration:
.Animation(a => a.Expand(e => e.Duration(2000)).Collapse(c => c.Duration(2000)))
does not change the default duration. 

### Current behavior
The specified animation duration is not applied and does not change the default one.

### Expected/desired behavior
The animation duration is properly applied when set in the wrapper's configuration. 

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [all ]

needs #2916

**Comment by jivanova** [comment]
Currently, Animation effect should be set to the PanelBar in order to make the **Duration property** work. So, example code will look like:
```
.Animation(animation =>
{
     animation.Expand(config => config.Fade(FadeDirection.In).Duration(400));
     animation.Collapse(config => config.Fade(FadeDirection.Out).Duration(5000));
})
```
