### ISSUE TITLE
TreeList wrapper does not provide filterable.operators option

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#2883]
The option for specifying custom filter options is available in the jQuery widget, but not in the MVC wrapper.

[http://docs.telerik.com/kendo-ui/api/javascript/ui/treelist#configuration-filterable](http://docs.telerik.com/kendo-ui/api/javascript/ui/treelist#configuration-filterable)

### Current behavior

![treelistfilterableoptions](https://cloud.githubusercontent.com/assets/11771009/23797868/9878d5f8-05aa-11e7-8831-bbb81c4057a4.jpg)

### Expected/desired behavior

The option is available in the Grid widget:

![gridfilterableoptions](https://cloud.githubusercontent.com/assets/11771009/23797913/c9f9e612-05aa-11e7-9262-fc675c0feb5c.jpg)

### Workaround

 Overwrite the list of operators in the default FilterMenu configuration before the widget is initialized. 

```
<script>
     kendo.ui.FilterMenu.fn.options.operators.string = {
       contains: "Contains"
     };
</script>
```

### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** [all]

**Comment by Alex-Bubblemaster** [comment]
Also requested in 1407732

**Comment by molequetu** [comment]
What about this? 2 years after the request, the asp.net mvc wrapper does not provide api for operators.

**Comment by Alex-Bubblemaster** [comment]
Also requested in 1453051

**Comment by gdenchevprog** [comment]
Requested in 1518207

**Comment by eyupyusein** [comment]
Requested in 1537008
