### ISSUE TITLE
The swipe event of the Kendo UI Touch is not fired on iOS devices if a video on the page is paused.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2884]
### Bug report

The swipe event of the Kendo UI touch is not fired on iOS devices if a video on the page is paused. In my testing scenarios, the issue occurs after the second pause event.

### Reproduction of the problem

The issue can be reproduced in the following Dojo using an iOS device: http://dojo.telerik.com/exinI

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [Mobile iOS Safari]

**Comment by matanasov** [comment]
Doesn't replicate with R1 2019 SP1 (2019.1.220)
