### ISSUE TITLE
Combobox inside ng-repeat - Initial value is lost

### ISSUE THREAD

**Issue by guilmori** [telerik/kendo-ui-core#2886]
Why are some of my combobox initial values overwritten ?

http://dojo.telerik.com/UNApE/2

**Comment by Dimitar-Goshev** [comment]
Using the `k-ng-model` directive and setting `k-value-primitive` to `true` fixes the issue and the values are displayed as shown in the [modified Dojo snippet](http://dojo.telerik.com/UNApE/10). The issues with the changes to the model field when using ng-model as opposed to using k-ng-model directives are explained in the following [Troubleshooting documentation article](https://docs.telerik.com/kendo-ui/framework/AngularJS/Troubleshooting/common-issues#widgets-with-ng-model-directives-do-not-reflect-a-model-value).
