### ISSUE TITLE
A Kendo UI for ASP.NET Core project created with the template cannot be published in Azure.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#2887]
### Bug report

A Kendo UI for ASP.NET Core project created with the template cannot be published in Azure.

Please find more information and details in the following ticket: 1096915

**Comment by zdravkov** [comment]
I have tested it with the latest version 2017.3.913, VS2017, .NET CORE 2.0 - and it built with no errors. Here is the [hosted test site](http://telerikaspnetcoreapp420171003014527.azurewebsites.net/).
