### ISSUE TITLE
MultiSelect does not allow clearing selected items by using the cross icon in a cascading scenario

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2894]
### Bug report
MultiSelect does not allow clearing selected items by using the cross icon in a cascading scenario. The cross icons on the items and the input of the second (cascaded) MultiSelect do not behave properly.

### Reproduction of the problem
The issue could be observed in our [*Create Cascading MultiSelects*](http://docs.telerik.com/kendo-ui/controls/editors/multiselect/how-to/cascading-multiselects) How-to sample:
* Select some options for the child MultiSelect.
* Select some options for the parent MultiSelect.
* Click the clear button on the child MultiSelect (the clear button won't work).
* Click the individual delete buttons on selected options of the child MultiSelect (they will duplicate themselves)

### Expected/desired behavior
The clear button should clear an item or all entries.

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible anymore with R2 2017 and R3 2017.
https://dojo.telerik.com/ixuyIt
