### ISSUE TITLE
ComboBox/MultiSelect/AutoComplete clear button does not clear the input on Chrome - Windows 10 touch devices

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2897]
### Reproduction of the problem
Reproducible in our [demos](http://demos.telerik.com/kendo-ui/combobox/index). 

### Current behavior
Tapping on the clear button does not clear the input. 

### Expected/desired behavior
Tapping on the clear button should clear the input.

### Environment
Touch devices (Microsoft Surface), Windows 10 

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [Chrome 57.0.2987.98 ]

**Comment by Dimitar-Goshev** [comment]
Similar issue - https://github.com/telerik/kendo-ui-core/issues/2366

**Comment by Dimitar-Goshev** [comment]
The issue is fixed for ComboBox and MultiSelect. It is still reproducible for AutoComplete.
