### ISSUE TITLE
Filter Multi Checkbox menu is not shrinking properly based on the search result in IE.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-ui-core#2898]
### Reproduction of the problem
1.Navigate to:
http://dojo.telerik.com/IzEve

2.Open ProductName filter menu

3.Type "test" in filter menu input

### Current behavior
https://www.screencast.com/t/zXgw8qTiYJ

### Expected/desired behavior
https://www.screencast.com/t/bxMPSm7ud2Ht

### Environment
* **Browser:** InternetExplorer and Edge

**Comment by theOrlin** [comment]
Tried setting a class instead of `display: none` inline but that does not help this behavior.
Closing this as a browser bug. If workaround is needed, add the following to CSS:
```CSS
.k-ie,
.k-edge {
    .k-multicheck-wrap {
        overflow-y: scroll;
    }
}
```

This will set an always-visible scrollbar to the filter container but will prevent it from stretching.
