### ISSUE TITLE
Some culture files are outdated due to differences between Windows 8 and Windows 10 date formats

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#2899]
### Bug report
Kendo UI Culture files have been generated 2 years ago. Since then, Windows 10 has been officially released and there are changes in the format for some cultures, e.g. cs-CZ.

This results in failed client-side validation in MVC apps, where custom format strings are ignored while parsing dates.

### Reproduction of the problem
See the script file generated by `@Html.Kendo().Culture("cs-CZ")` and compare it to the contents of  `kendo.culture.cs-CZ.min.js`. The `"{0:dd.MM.yyyy}"` format is valid in the former and invalid in the latter.

### Environment
* **Kendo UI version:** 2017.1.223 (and all previous versions running on a Windows 10 computer)

**Comment by TsvetinaIvanova** [comment]
A possible work around is to generate the culture scripts on the fly using  @Html.Kendo().Culture("cs-CZ"), as described here:
[Use the Culture Helper](http://docs.telerik.com/aspnet-mvc/getting-started/globalization#use-the-culture-helper)

**Comment by veselints** [comment]
The es-US and es-SV Kendo UI Culture files are also outdated. They state the following for the *groupSize* of the *numberFormat* and *percent*: **[3,0]** while it should be **[3]**

**Comment by veselints** [comment]
Related to [this item](#2421).

**Comment by tsvetomir** [comment]
See #768 and the CLDR-based implementation in [telerik/kendo-intl](https://github.com/telerik/kendo-intl)
