### ISSUE TITLE
Kendo UI Scaffolder should use a new VS 2017 extensibility format

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2900]
### Current behavior

Kendo UI Scaffolder produces the warning below during installation to VS2017:

<img src="http://image.prntscr.com/image/fee8ca3424074204b15b9b7bd96803ac.png"/>

### Expected/desired behavior

Kendo UI Scaffolder for Visual Studio 2017 should be built with the updated VSIX format (VSIXv3). 

[Forum post from VS community regarding VS2017 compatibility](https://developercommunity.visualstudio.com/content/problem/1180/this-extension-is-not-compatible-with-visual-studi-9.html)

***Important***

> Extensions which have been updated with the latest Visual Studio RC version of the VS SDK will not display this error when installed into VS 2017. Our current plans are to disallow installation for extensions which have not been updated in the final version of VS 2017.

**Comment by uurapp** [comment]
I read the forum post where was explained that the incompatibility is caused by changed depencies on the new modular installation of Visual Studio. Is it safe to just install this extension when you have installed the modules that this extension is likely depending on? And if so: how can I get this extension, because it is not showing up in Visual Studio's "Extensions & Updates"

**Comment by veeprox** [comment]
@code54nl did you end up just installing the extension and seeing how it went?

i'll see if it can find a copy and try it out in the meantime

**Comment by code54nl** [comment]
@veeprox no haven't tried it since. Last time I checked, there was no way to install this extension. I still prefer to use it, but I can live without it. Did you have any success?

**Comment by simonssspirit** [comment]
Raising the priority as it is requested(reported) in multiple tickets: 1109303 1109046(only for the last two days).

**Comment by Dimitar-Goshev** [comment]
Requested in ticket 1109421 as well.

**Comment by Xizario** [comment]
Related to: https://github.com/telerik/kendo/issues/6298

How to upgrade: https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017

http://www.visualstudioextensibility.com/2017/01/10/its-time-to-change-the-vsix-manifest-of-your-extension-to-v3-for-visual-studio-2017-compatibility/

It looks that we need to start shipping 2 scaffolds (or drop the VS2010 support):
VSIX v3 is not supported for VS 2010. 
VSIX v1/2 is not longer supported for VS>=2017

**Comment by Xizario** [comment]
@MilenaCh, https://github.com/telerik/kendo/commit/eb1e31445db8c80455462193730bdca23047bd56
