### ISSUE TITLE
Select event is fired twice in mobile Chrome under Windows

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#2902]
### Bug report

[http://dojo.telerik.com/Iceji](http://dojo.telerik.com/Iceji)
[http://dojo.telerik.com/aNoGoDay](http://dojo.telerik.com/aNoGoDay)

### Reproduction of the problem

When filtering: 

"MAC0" - have 6 items and everything works as expected
"MAC01" - have 2 items - select is fired with null item value and then fired once again with the correct item value

### Expected/desired behavior
Select should be fired once.

### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** Mobile Chrome  56.0.2924.87 and later

**Comment by mparvanov** [comment]
The issue is not reproducible with version 2019.2.619 in mobile Chrome 76.
