### ISSUE TITLE
Cannot define tools for the tabs

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2905]
### Bug report

According to the API (http://docs.telerik.com/aspnet-mvc/api/Kendo.Mvc.UI.Fluent/SpreadsheetToolbarSettingsBuilder) Home, Insert and Data methods should be capable to accept array of string for the tools to show in the toolbar. 

Currently, only boolean value is available as an argument. 

### Workaround

```
@(Html.Kendo().Spreadsheet()
    .Name("spreadsheet")
)
 
<script>
    $(document).ready(function () {
        var spreadsheet = $("#spreadsheet").data("kendoSpreadsheet");
        var options = spreadsheet.options;
        spreadsheet.destroy();
        $("#spreadsheet").html("");
        $("#spreadsheet").kendoSpreadsheet($.extend({ toolbar: { home: [['bold', 'italic', 'underline']], insert: false } }), options);
    });
</script>
```

### Environment

* **Kendo UI version:** 2017.1.228
]

**Comment by IvanDanchev** [comment]
Workaround updated to include an array of strings for the tools:  home: [['bold', 'italic', 'underline']]

**Comment by veselints** [comment]
PR here: https://github.com/telerik/kendo/pull/9943
