### ISSUE TITLE
Kendo UI npm install not in kendo folder but in @progress folder

### ISSUE THREAD

**Issue by arvadevy** [telerik/kendo-ui-core#2906]
I use AurliaJS to develop. When I npm install kendo trough command line, the folder is installed in node_modules/@progress/kendo-ui@2017.1.307 and before it was installed in the node_modules/kendo folder.

This is how it used to be declared in my aurelia.json file
```
{
            "name": "kendo",
            "path": "../node_modules/kendo/",
            "resources": [
              "css/web/kendo.common.core.min.css",
              "css/web/kendo.bootstrap.min.css",
              "css/web/kendo.common.min.css",
              "css/web/kendo.rtl.min.css",
              "css/mobile/kendo.mobile.all.min.css",
              "css/web/kendo.material.min.css"
            ]
          },
```

Any ideas?

**Comment by zdravkov** [comment]
Yes indeed - this is the folder where the Kendo UI is installed with its latest version.
