### ISSUE TITLE
Multiple Grid header icons display issues in Material theme

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2908]
### Bug report

Both the sorting and filtering icons are too transparent, and the sorting arrows are hardly visible.

The filtering icon inherits the default anchor color for the page:

[http://dojo.telerik.com/AxODU](http://dojo.telerik.com/AxODU)

### Expected/desired behavior

The icons should be more clearly visible, and the filtering icon should have its own color set, like in previous versions:

[http://dojo.telerik.com/AxODU/2](http://dojo.telerik.com/AxODU/2)

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by lkarakoleva** [comment]
It is better the sorting icon color to use `selected-text-color` primitive. It contrasts to background color and is consistent with grid-pager selected color.

The filtering icon uses `opacity: .45;` that could be increased to 'opacity: .7' so we keep the hover state effect and make icon more visible.

**Comment by MilenaCh** [comment]
The opacity of filter icon is still 0.45(it should be 0.7)

**Comment by lkarakoleva** [comment]
Header filter icon inherits header color: #999
Filter row icon inherits dropdown color: #444
We could change filter icon in header to `opacity: .7` and keep filter row icons `opacity: .45`
