### ISSUE TITLE
Calendar time zone issue in FireFox (all months from March on in the 2012 year view are rendered as March)

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#2913]
### Bug report

All months from March on are rendered as March in the Date(Time)Picker/Calendar year view in FireFox v.52, when Beirut time zone is set:

[https://www.screencast.com/t/pzC54Y3aQs](https://www.screencast.com/t/pzC54Y3aQs)

### Reproduction of the problem

Change the time zone to Beirut, zoom out to year view, and navigate to 2012.

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [Firefox v. 52]

**Comment by ag-petrov** [comment]
The problem is not reproducible with the latest version Kendo and FireFox.
