### ISSUE TITLE
Cannot set a function to modify the imageUrl value of ImageBrowser in MVC wrappers

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-ui-core#2920]
Cannot set a function to modify the imageUrl value of ImageBrowser in MVC wrappers. This can be achieved only in the widget - http://dojo.telerik.com/Ogaha

**Comment by nenchef** [comment]
Requested in Ticket ID: 1098081. 
Additional comment: "The fix should allow for optional encoding. Those using urls with the "/path?image={0}" format will need encoding while the rest will not."

**Comment by Iankodj** [comment]
The syntax to setup a function after this improvement is 

```
.Image(image => image.UrlHandler("fuction_name"))
```

or

```
.Image(image => image.UrlHandler("function (e) {return 'url' + e;}"))
```
