### ISSUE TITLE
Bower semver implementation deems jquery 3.x invalid

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#2921]
### Bug report

Bower interprets `jquery#>=1.9.1 <=3` incorrectly. Bower installs jquery 2.2.4 and does not respond to any update calls including  `--force-latest`

```
bower jquery#>=1.9.1 <=3        cached https://github.com/jquery/jquery-dist.git#2.2.4
bower jquery#>=1.9.1 <=3      validate 2.2.4 against https://github.com/jquery/jquery-dist.git#>=1.9.1 <=3
bower                        ECONFLICT Unable to find suitable version for jquery
```

### Reproduction of the problem

- bower install jquery
- bower install https://bower.telerik.com/bower-kendo-ui.git

### Current behavior

jQuery 3.x is deemed invalid during bower installation

### Expected/desired behavior

jQuery 3.x should be interpreted as a valid version during bower installation

**Comment by tsvetomir** [comment]
Fixed in 2017.1.321
