### ISSUE TITLE
Prevent page scrolling when mousewheel is over the item list

### ISSUE THREAD

**Issue by dimodi** [telerik/kendo-ui-core#2923]
### Feature Request

Allow scrolling of the items list of AutoCompletes, ComboBoxes, DropDownLists and MultiSelects to NOT be propagated to the page, so that when the user reaches the top/bottom end of the list, nothing happens any more. Currently, the page starts scrolling at this point, which a lot of people regard as bad user experience, and also, it is inconsistent with the behavior of the native `<SELECT>` element. From this point of view, the behavior may even be regarded as a bug.

### Current behavior

http://dojo.telerik.com/okenU

Scroll the page a little, then open the DropDownList, scroll down the list with the mouse wheel, and then up. When you reach the top end of the list, the page will scroll and the DropDownList will close. This is not desired.

### Expected/desired behavior

http://dojo.telerik.com/OJugu

When the top/bottom end of the item list is reached, and the mouse wheel is over the list, scrolling the page should be disabled.

### Environment

* **Kendo UI version:** 2017.1.#

**Comment by gramx** [comment]
We are using an onLoad hack for this, I would love for this to be fixed/updated.

`function stopScroll() {
    var activeElement;

    $(document).bind('mousewheel DOMMouseScroll', function (e) {
        var scrollTo = null;

        if (!$(activeElement).closest(".k-popup").length) {            
            return;
        }

        if (e.type == 'mousewheel') {
            scrollTo = (e.originalEvent.wheelDelta * -1);
        }
        else if (e.type == 'DOMMouseScroll') {
            scrollTo = 40 * e.originalEvent.detail;
        }

        if (scrollTo) {
            var element = $(e.target).parent().parent();
            e.preventDefault();
            element.scrollTop(scrollTo + element.scrollTop());
        }
    });

    $(document).on('mouseover', function (e) {
        activeElement = e.target;
    });
}`
