### ISSUE TITLE
Scheduler is scrolled into view, when a time slot/event is focused

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#2930]
### Bug report

Scheduler toolbar is scrolled into view, when a time slot/event is focused.
The issue is reproducible on each selection in IE.
It is reproducible on the first selection in Chrome and Edge. Not noticeable in FF.
The issue is NOT reproducible in Firefox.
### Reproduction of the problem
1. Go to [Scheduler/ Keyboard Navigation demo](http://demos.telerik.com/kendo-ui/scheduler/selection) in IE.
2. Scroll down the page so that the header is not visible.
3. Click on a time slot or event.
### Current behavior

The page is scrolled up to the toolbar. If the Scheduler is high, the page may be scrolled far away from the selected slot/event.
### Expected/desired behavior

The slot/event is selected and the page is not scrolled.
### Environment
- **Kendo UI version:** 2019.1.115
- **Browser:** [IE | Chrome 52 | Edge ]

**Comment by mparvanov** [comment]
This issue appear to be a browser specific behavior where when given element is focused. This action is not preventable and scrolls the page to the top of the focused element. More details and possible workarounds could be found in the Troubleshooting section of Kendo documentation:
http://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/troubleshoot/troubleshooting#navigation

**Comment by jivanova** [comment]
Indeed, it's browser behavior of how scrollIntoView works. However, we could research the behavior if the scenario is handled due to the higher demand. Reopening the issue for further investigation and prioritization.
