### ISSUE TITLE
MVC and Core Spreadsheet exports corrupted xlsx file when text length validation is configured for a cell.

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2939]
### Bug report
MVC and Core Spreadsheet exports corrupted xlsx file when text length validation is configured for a cell. When trying to open the exported file in Excel the following error is observed:

*We found a problem with some content in ...[workbook]. Do you want to try to recover as much as we can?*

The bug is a regression, introduced with R1 2017 release.

### Reproduction of the problem
* Go to the [Validation MVC demo](https://demos.telerik.com/aspnet-mvc/spreadsheet/validation);
* Export the Spreadsheet to an xlsx file;
* Open the file in Excel - the error will be displayed;

### Expected/desired behavior
No error should be present.

### Environment
* **Kendo UI version:** from 2017.1.118 on

**Comment by Dimitar-Goshev** [comment]
https://github.com/telerik/kendo-ui-core/issues/2719

**Comment by Dimitar-Goshev** [comment]
The length syntax is wrong on the demo, which causes errors. It should have < before 200:
from: "AND(LEN(A3)>3, LEN(A3)<200)",

**Comment by veselints** [comment]
Fixed with commit https://github.com/telerik/kendo/commit/7aabde3dec724a0463bfc482e16a4818fa43dfbf
