### ISSUE TITLE
Spreadsheet hidden columns display their values

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2944]
### Bug report
When navigating the cells with the keyboard cell values in hidden columns are displayed. The behavior is related to the columns width option being set. 

### Reproduction of the problem
[Screencast](https://www.screencast.com/t/caIextty2XW). Sample [dojo](http://dojo.telerik.com/ECIGO/2).

### Current behavior
Values in hidden columns are displayed. 

### Expected/desired behavior
Values in hidden columns are not displayed.

Workaround: set the columns width programmatically instead of setting them in the Spreadsheet's declaration:

 var spreadsheet = $("#spreadsheet").data("kendoSpreadsheet");
 var sheet = spreadsheet.activeSheet();
 **sheet.columnWidth(1, 200);
 sheet.columnWidth(2, 150);**

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by mishoo** [comment]
Fixed in https://github.com/telerik/kendo/commit/6faf169260ad6dc437e91259aeccf6afaaf4d996.
