### ISSUE TITLE
Drawing does not properly export counter values

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2945]
### Bug report
Counter values set through the counter-increment CSS property are not correctly exported by Drawing. 

### Reproduction of the problem
[Dojo](http://dojo.telerik.com/IZadUt) example.

### Current behavior
Counter values are exported as zeroes. 

### Expected/desired behavior
The actual counter values are exported.

### Environment
In Chrome all numbers are exported as zeroes, whereas in Firefox and IE11 only the last number is exported as zero (1.1.0 instead of 1.1.1).

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by IvanDanchev** [comment]
The suggested workaround allowed the counter values to be properly exported, however in a multi page export scenario the counter on the second page starts from zero. [Dojo](http://dojo.telerik.com/efeRi).

**Comment by Dimitar-Goshev** [comment]
The original issue is fixed - [Dojo 2019.3.1023](https://dojo.telerik.com/@Dimitar-Goshev/ecoHiluK). If further improvement is needed for scenarios with multiple pages we may open a new issue.
