### ISSUE TITLE
DropDownList / ComboBox/ AutoComplete items filter is not cleared, when certain item was selected (base on search criteria) and minLength options is set

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#2950]
### Bug report

DropDownList filter is not cleared, when item is selected and minLength options is set

### Reproduction of the problem

Use the dojo below, in order to replicate the issue:
http://dojo.telerik.com/@nenchef/AtiyI/2
1. Search for "cha"
2. Select the Chang option.
3. Expand the dropdow

### Current behavior
The result set displayed in the dropdown is corresponding to the cha filter string.

NOTE: If the minLength option is not set - the list is correctly filled after the initial search. 
[Video](https://www.screencast.com/t/4qy7BwNcYMS)

### Expected/desired behavior
All items are displayed in the dropdown, as there is no text typed for filtering.

### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The issue is still reproducible after the fix.
