### ISSUE TITLE
Not fired cascade event, when selection is changed to the already selected item

### ISSUE THREAD

**Issue by daliran** [telerik/kendo-ui-core#2954]
When the list of a ComboBox or a DropDownList (maybe also the AutoComplete and MultiSelect) is opened, the widget does not contain a value and the items are selected (but not confirmed) by keyboard arrows navigation (always with the list opened), the **select** and **cascade** events are fired correctly.

But, if the widget has a selected value, on the same conditions above, the **cascade** events is not fired when selecting (but not confirming) the widget selected value.

For example, if the wiget datasource contains three elements:
```
{ 
   Id: 1,
   Text: 'Item1'
}, {
   Id: 2,
   Text: 'Item3'
}, {
   Id: 2,
   Text: 'Item3'
}
```
When the Item1 is selected on the widget, opening the list and navigating with the keyboard arrows (without confirming the value) will raise the **select** and **cascade** events for the items: 2 and 3 but only the **select** event for item 1.

This may causes inconsistency because if the **cascade** event is handled, selecting the items 2 and 3 in these conditions causes that event to execute code (for example, the update of other widgets), but the selection of item 1 doesn't.

The problem can be easly reproduced by adding to this existing demo example the onCascade event:
http://demos.telerik.com/kendo-ui/dropdownlist/events

I have tested this issue with the kendo ui version 2017 Q1 SP1.

**Comment by jivanova** [comment]
Test in **cascade-event** branch.
