### ISSUE TITLE
In Editor, navigating to a link using the Ctrl + click keeps the cursor position as selected in the Editor, where the click occurred

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2956]
### Bug report
In Editor, that has a link (<a> tag) as its content. Try to navigate to the link page using the Ctrl + click. After closing the newly opened page, in the editor, the cursor position remains as selected position, where the click occurred. This is reproducible in Firefox, Edge and IE.

### Reproduction of the problem
* Go to the [Editor Index demo](http://demos.telerik.com/kendo-ui/editor/index);
* Hold the Ctrl key and click on one of the links in the Editor. The linked page will be opened in a new tab;
* Close the newly opened page;
* Move the mouse without clicking anywhere. You will notice that part of the Editor content gets highlighted (selected);

Video [here](https://www.screencast.com/t/Ky4vvkkWhS3).

### Expected/desired behavior
Editor content should not get selected.

### Environment
* **Browser:** [Firefox | IE | Edge ]

**Comment by Iankodj** [comment]
The described behavior comes from the browser functionality for selection in content editable elements. The same is reproducible here as well: http://dojo.telerik.com/UqeKuTAL.
