### ISSUE TITLE
Start a scroll gesture from event does not scroll content under iOS

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2957]
### Bug report

Touching an event to scroll content does not scroll content. Only scrolling over empty area scrolls it. 

### Reproduction of the problem
https://demos.telerik.com/kendo-ui/m/index#scheduler/adaptive

### Current behavior
Content is not scrolled.

### Expected/desired behavior
To be able to scroll the content.

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 1.12.3
* **Browser:** [ iOS 9.3.5 Safari | iOS 9.3.5 Chrome ]

**Comment by chiznoodle** [comment]
Hello,
As I have currently the same exact problem I just would like to know if you managed to find a solution to this issue please.
Thank you very much.
