### ISSUE TITLE
Scheduler throws n.innerRect is not a function error when creating an event with duration of 24 hours, which spans over the spring daylight saving change

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2958]
### Bug report
Scheduler throws n.innerRect is not a function error when creating an event with duration of 24 hours, which spans over the spring daylight saving change.

Related to #2371

### Reproduction of the problem
* Go to the following [Dojo](http://dojo.telerik.com/uKOjU);
* Create an event that starts on 25 March at 5 pm and ends on 26 March at 5 pm;
* *n.innerRect is not a function* will be thrown;

**Comment by veselints** [comment]
Review [the following forum thread]http://www.telerik.com/forums/daylight-savings-time-and-problem-with-event-rendering() which contains troubleshooting details on this case.

**Comment by tkopecky** [comment]
In my opinion, the main problem is not throwing the exception. It is that the event created in [Dojo](http://dojo.telerik.com/uKOjU) as described is displayed in a bad place. It is at the bottom of the scheduler. Also the other events that were visible (there were events Dance Practice and HR Lecture) are not shown at all.

The state of the scheduler after creating the event is here:
![schedulererror](https://cloud.githubusercontent.com/assets/1950307/24751140/bc5c2cda-1ac8-11e7-934a-ad8f9c7438c1.png)
