### ISSUE TITLE
Mouse cursor automatically moved at the end of the text in the ComboBox input

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2960]
### Bug report
With no filter set if you place the mouse cursor within the text in the input and type the cursor is automatically moved at the end of the text (Chrome, IE). 

### Reproduction of the problem
Reproducible in our [demos](http://demos.telerik.com/kendo-ui/combobox/grouping). [Screencast](https://www.screencast.com/t/Av7UPPgoPT).

### Current behavior
Cursor is moved automatically. 

### Expected/desired behavior
No automatic cursor movement. 

### Workaround
http://dojo.telerik.com/@nstoychev/iNaVO

### Environment
Not reproducible in Firefox.

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [Chrome 57.0.2987.110 | IE 11 ]

**Comment by Dimitar-Goshev** [comment]
Issue after a fix:
Type a, then select some result.
Expected - caret is at the end of the selected item.
Actual - caret is after the first letter of the selected item.
