### ISSUE TITLE
NumericTextBox does not allow currency character to be pasted together with the numeric value

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#2962]
### Bug report

When user pastes $45 in the numeric text box the value is not accepted and the previous value is displayed. Pasting only 45 works fine. 

### Reproduction of the problem

The behavior can be reproduced with our http://demos.telerik.com/kendo-ui/numerictextbox/index demo. 

### Expected/desired behavior

The expected behavior can be observed in versions below 2016.3.914. 

### Environment

* **Kendo UI version:** 2016.3.914
* **jQuery version:** 1.12.3
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by geraldbauer** [comment]
I am experiencing this within the kendo-angular components. Either a $ or a comma within the numeric value, will not allow pasting to the input. Am I using too old of a version?

    "@progress/kendo-angular-buttons": "^2.0.1",
    "@progress/kendo-angular-dialog": "^3.5.0",
    "@progress/kendo-angular-dropdowns": "^1.5.0",
    "@progress/kendo-angular-inputs": "^1.5.0",
    "@progress/kendo-angular-intl": "^1.3.0",
    "@progress/kendo-angular-l10n": "^1.3.0",
    "@progress/kendo-angular-layout": "^1.2.0",
    "@progress/kendo-angular-popup": "^2.0.1",
    "@progress/kendo-angular-ripple": "^0.2.1",
    "@progress/kendo-angular-upload": "^4.2.2",
    "@progress/kendo-theme-bootstrap": "^2.11.0",
    "@progress/kendo-theme-default": "^2.47.0",
    "@progress/kendo-theme-material": "^0.3.0",

**Comment by matanasov** [comment]
The issue is fixed in 2017 R2 SP1 (2017.2.621) version of the Kendo UI for jQuery numeric text box and doesn't affect angular components that use a separate repo:

https://github.com/telerik/kendo-angular

**Comment by geraldbauer** [comment]
Thank you
