### ISSUE TITLE
Stacked series starting axis value changes when other series are deselected.

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-ui-core#2967]
In particular circumstances, the minimum value of the value axis changes unexpectedly when the chart rescales the value axis after a series is deselected in the legend.

http://dojo.telerik.com/AZANe

To reproduce, click on the "Line3" series in the chart legend to deselect it.  Note the value axis starts from 3.4 although the expected scale is 0 to 6.

https://www.screencast.com/t/bJafeenPe7V

**Comment by danielkaradachki** [comment]
This is related to the [narrowRange option](http://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart#configuration-valueAxis.narrowRange). Setting it to false should fix this:

http://dojo.telerik.com/@SiliconSoul/efIwi

**Comment by tsvetomir** [comment]
This is what Excel does as well. The only difference that I can spot is that it is slightly less sensitive and will collapse the axis range only when the second value is 0.8 or lower (5:1 value ratio).

![image](https://user-images.githubusercontent.com/247917/27339872-a1de5c4e-55e1-11e7-8b1a-11c6c7a03cf7.png)

**Comment by tsvetomir** [comment]
No fix is planned for this issue.
