### ISSUE TITLE
seriesHover event fires inconsistently when using a shared tooltip

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#2968]
### Reproduction of the problem
Dojo: [http://dojo.telerik.com/@tsveti/uwoLa/2](http://dojo.telerik.com/@tsveti/uwoLa/2)

Hover the chart plot area.

### Current behavior
When a shared tooltip is enabled, the seriesHover event fires when hovering anywhere in the plot area, behaving more like a category hover event.

### Expected/desired behavior
seriesHover event should only be fired when one of series columns is hovered. This is the behavior when a shared tooltip isn't used.

### Environment

* **Kendo UI version:** 2017.1.223

Apart from making the seriesHover event more consistent, it may be a good idea to add a categoryHover event that can be used to show the tooltip and highlight the series in the same way as they behave now with a shared tootlip configuration.

**Comment by Alex-Bubblemaster** [comment]
Similar inconsistency reported in ticket with ID 1102982

[Dojo](http://dojo.telerik.com/amogA)

### Steps to reproduce

- Hover on series
- Move below the chart area
- Hover on series column(shared tooltip not showing every time)

Repeat a few times to reproduce

**Comment by TsvetinaIvanova** [comment]
Additional problem with the `legendItemHover` event and related behavior was reported in ticket with ID 1126445. Series highlight is not shown on legend item hover and the `legendItemHover` event is not fired when a shared tooltip is used.

Issue can be reproduced here: [http://dojo.telerik.com/@tsveti/iKuken](http://dojo.telerik.com/@tsveti/iKuken).

Try hovering the legend and see that neither a highlight is shown, nor the `legendItemHover` event is fired.

**Comment by TsvetinaIvanova** [comment]
`legendItemHover` issue also reported in ticket with id: 1128514.

**Comment by MilenaCh** [comment]
This issue is partially fixed. The hover will work as expected for the legend for shared tooltip. seriesHover will still be triggered on category hover to avoid breaking change. Instead the users can use the new seriesOver event.
