### ISSUE TITLE
Widget incorrectly set time the calendar min/max value

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#298]
### Description
Widget sets the whole min/max date to the underlying calendar, which breaks the correct value selection afterwards.

Repro demo:
http://dojo.telerik.com/@ggkrustev/aViY (repro steps inside)

Reported in TicketID: 858146

**Comment by KirilNN** [comment]
The following code assigns the min value of the widget to 8/28/2015 12:30AM
``` html 
end.min(new Date(startDate.getTime() + 30*60000));
```
so when selection is made, the min value is actually selected. This is expected behavior.

**Comment by KirilNN** [comment]
The issue can be reproduced here: http://dojo.telerik.com/IWaJa,

the expected behavior will be when a date is selected, the widget should persists the current time value, and do not respect the set min value.
