### ISSUE TITLE
Empty hyperlink is inserted when pressing enter at the beginning of link

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#2980]
### Bug report

[demo](http://demos.telerik.com/kendo-ui/editor/all-tools)

### Reproduction of the problem
1. Clear the content and insert a hyperlink
2. Go at the beginning of the link and press enter

### Current behavior
```
<p><a href="http://telerik.com">&nbsp;</a></p>
<p><a href="http://telerik.com">test</a></p>
```
### Expected/desired behavior
```
<p>&nbsp;</p>
<p><a href="http://telerik.com">test</a></p>
```
### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** all

**Comment by stetod11** [comment]
Hi, we logged this 4 months ago, and no update - any idea when someone will look at it? Placing the cursor within text in the Editor and choosing 'Enter' is a pretty common action - the extraneous HTML it produces is confusing, not to mention adding an overhead in useless HTML content

**Comment by stetod11** [comment]
Hi, any update on this?

We're now at 10 months and counting, but it seems fixes to the Kendo UI Editor are now the poor relation compared to whizzy new functionality elsewhere...and depending on your POV, this is not low severity. Adding unwanted/unnecessary HTML to a WYSIWYG component may not seem important - but if Editor users then have to go and manually amend the HTML, it's hardly WYSIWYG, is it???

Someone at Telerik/Progress has to grasp that these tools are being used in commercial software - we're paying for this stuff, and it really doesn't look good if two releases have come and gone in the time we have had this issue open and open issues are not being fixed.
