### ISSUE TITLE
Spreadsheet duplicates the last column on a second page, when exporting it to portrait PDF and having specific values for the columns widths

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2991]
### Bug report
In some cases, while exporting to PDF, the Spreadsheet duplicates the last column in the sheet and places the duplicated column on a separate page. This happens, when the exported PDF is in portrait mode and all the other options are the default. To reproduce the issue, specific values for the columns widths should be set:

```` JavaScript
"columns":[  
   {  
      "index":0,
      "width":196.0
   },
   {  
      "index":1,
      "width":98.0
   },
   {  
      "index":2,
      "width":98.0
   },
   {  
      "index":3,
      "width":98.0
   },
   {  
      "index":4,
      "width":98.0
   },
   {  
      "index":5,
      "width":252.0
   }
],
````

### Reproduction of the problem
* Go to the following [Dojo];
* Click the export button on the Spreadsheet toolbar and select to export to PDF;
* Select portrait mode and leave the other options to be the default;
* There will be two pages in the exported PDF. The second page will contain only the last configured column in the Spreadsheet. This column will also be available on the first page.

### Expected/desired behavior
No additional page should be exported.

**Comment by mishoo** [comment]
You forgot the Dojo link. ;-)

**Comment by nenchef** [comment]
Hi mishoo,

Please test with the following dojo example:

http://dojo.telerik.com/@nenchef/icIfo/4

Note that you select portrait mode when exporting to PDF

**Comment by jwbqv** [comment]
Are there any updates on this issue?  This is high impact for us due and should not be classified as "Low".  Thank you.

**Comment by mishoo** [comment]
@jwbqv it's now fixed on the development branch and will be available soon.

**Comment by jwbqv** [comment]
Thank you 👍
