### ISSUE TITLE
Incorrect dropdown open behavior of widgets nested in PanelBar

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#2993]
### Bug report
When the page is scrolled close to the bottom and the input of a MultiSelect nested in PanelBar is clicked its dropdown opens and immediately closes automatically. The behavior is difficult to reproduce consistently  and seems to be related to focusing a PanelBar item, prior to clicking the MultiSelect's input.  
 
### Reproduction of the problem
Sample [dojo](http://dojo.telerik.com/eFAfoC). [Screencast](https://www.screencast.com/t/xmYiKYzfo). 

### Current behavior
The dropdown closes automatically. 

### Expected/desired behavior
On click the dropdown should open and should not close automatically unless the widget is blurred. 

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [ Chrome 57  ]

**Comment by zdravkov** [comment]
Could not replicate with the latest version.

**Comment by Dimitar-Goshev** [comment]
I also do not reproduce the issue on my side. It is most probably caused/related to this issue https://github.com/telerik/kendo-ui-core/issues/3516 and its fixing fixed this scenario as well.
