### ISSUE TITLE
kendo.dataviz.* not available on CDN for 2017.1.223

### ISSUE THREAD

**Issue by sebfz1** [telerik/kendo-ui-core#2995]
`kendo.dataviz.*.min.js` are not available on CDN for version `2017.1.117` & `2017.1.223`

http://kendo.cdn.telerik.com/2017.1.223/js/kendo.dataviz.chart.polar.min.js
http://kendo.cdn.telerik.com/2017.1.117/js/kendo.dataviz.chart.polar.min.js

It used to work on `2016.3.1118`
http://kendo.cdn.telerik.com/2016.3.1118/js/kendo.dataviz.chart.polar.min.js

Or script files have changed, in which case the documentation is not up-to-date:
http://docs.telerik.com/kendo-ui/intro/supporting/scripts-dataviz

Btw, a release note on the release tag would be awesome :)
https://github.com/telerik/kendo-ui-core/releases/tag/2017.1.223

**Comment by danielkaradachki** [comment]
Sorry for taking so long to respond. The dataviz.chart.polar and dataviz.chart.funnel contents were included in the dataviz.chart file. We will update the documentation to reflect this.
