### ISSUE TITLE
AutoScroll could not be enabled for a TreeView in AngularJS scenario

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#2997]
### Bug report
AutoScroll could not be enabled for a TreeView in AngularJS scenario. 

### Reproduction of the problem
* Go to the following [Dojo](http://dojo.telerik.com/ApeBI/6);
* Expand all nodes of the TreeView;
* Drag the last node up - the container will not scroll with the dragged node;

### Expected behavior
The container should scroll up / down together with the dragged node;

**Comment by zdravkov** [comment]
It works correctly when adding **overflow:hidden** to the tree view as it is described [here](https://docs.telerik.com/kendo-ui/api/javascript/ui/treeview#configuration-autoScroll)- "_If the scroll container is different than the TreeView container, set overflow: hidden on the TreeView container_."
Here is working [dojo](http://dojo.telerik.com/@zdravkov/efayi).
