### ISSUE TITLE
Gantt scrolls to the selected date on expand / collapse task

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3001]
### Bug report
Gantt scrolls to the selected date on expand / collapse task

### Reproduction of the problem
* Go to the following [Dojo](http://dojo.telerik.com/EyAbOb/4)
* Scroll to another day on the timeline;
* Expand or collapse a task

### Current
 the timeline scroll will move back to the selected date.

### Expected
the timeline does not scroll

### Environment
Kendo UI: 2020.2.617

**Comment by ag-petrov** [comment]
Does not seem to reproduce with the latest version - https://dojo.telerik.com/ofoREsOT
