### ISSUE TITLE
The dates in the Grid Excel export are rounded to plus one day.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3003]
### Bug report

The dates in the Grid Excel export are rounded to plus one day.

### Reproduction of the problem

The issue can be reproduced in the following Dojo: http://dojo.telerik.com/uzOwA

Notice that the date is Wed Nov 10 2010 20:30:00, but is exported to Nov 11 2010.

### Environment

* **Browser:** [all]

**Comment by danielkaradachki** [comment]
At least on my machine the exported value is 11/10/2010 -> 11th month(nov), day 10, year 2010

**Comment by mishoo** [comment]
False alarm, in `new Date` month is zero-based so the output 11/10/2010 is correct (November).
