### ISSUE TITLE
Filtering does not work with Chinese by completing characters with click

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3009]
### Bug report

With Chinese IME typing by using spacebar is possible and items are filtered. With clicking the Chinese characters, filtering does not work.

In iPad, filtering with Chinese is not possible as well.

### Reproduction of the problem

http://dojo.telerik.com/eXotI/2

1. Switch to Chinese (Simplified, China) language input method
2. Focus the filter input;
3. Type 'f' and quickly press spacebar;
4. You will see the items filtered;
5. Reset filter;
6. Type 'f' and quickly click the first character available;
7. The filtered data is filtered with value 'f'

### Expected/desired behavior
The filter to work with Chinese IME.

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 1.12.3
* **Browser:** [all ]

**Comment by mparvanov** [comment]
When completing characters with click, the filtered data is not filtered with the Chinese character, but with the initially entered English character:
http://take.ms/FFHxz

**Comment by Iankodj** [comment]
The case with the click is rather related to the timeout that is used during the keydown event. Thus, when the timeout finishes and filtering is done, changes does not occur furthermore via click because this does not fire the keydown event. 

For this case, you can set up a greater delay for the timeout via the [delay option](https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist/configuration/delay) of the DropDownList.
