### ISSUE TITLE
Filtering closes the keyboard in Android 

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3012]
### Bug report

When filtering is applied the keyboard is closed and user needs to refocus again the filter input to continue typing text.

### Reproduction of the problem

http://dojo.telerik.com/aFUFO

1. Open dropdown;
1. Start typing text;
1. Wait the filtering to proceed;

### Current behavior
Keyboard is closed, but input stays focused. 

### Expected/desired behavior
Keyboard to stay opened or to automatically be reopened.  

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 1.12.3
* **Browser:** [ Android  Chrome 56 ]

**Comment by zdravkov** [comment]
Seems to be working correctly when adding the following metatag that is required for mobile devices:
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

**Comment by mparvanov** [comment]
The issue is no more reproducible with Chrome v58
