### ISSUE TITLE
TreeMap renders tiles for items with value 0

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3017]
### Bug report
Currently the TreeMap renders the tiles of items with value: 0 on top of each other, thus only the last item tile is visible.

### Reproduction of the problem
Sample [dojo](http://dojo.telerik.com/eSoWI/2).
foo, bar and baz tiles are rendered and only baz is visible (it is displayed over the others) 

### Current behavior
Tiles for items with value 0 are rendered.

### Expected/desired behavior
Tiles for items with value 0 are not rendered.

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [all] 

Update: Dojo from the ticket: https://dojo.telerik.com/UbIQOCIm

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket with ID 1178769. I believe the below [`itemCreated`](https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/treemap/events/itemcreated) handler function can be used as a workaround:

```
        itemCreated:function(e){
          var item = this.dataItem(e.element);
          if(!item.value){
            e.element.hide();
          }
        }
```
[Dojo](http://dojo.telerik.com/@bubblemaster/inUzanEv)

### Additonal observations

It seems to make a difference at what position the 0 value items are and how many of them there are. The 0 item value corresponding elements get the `k-inverse` class.
