### ISSUE TITLE
Upload's k-i-warning icon is slightly clipped  

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3019]
### Bug report
The Upload's warning icon occasionally appears slightly clipped (left side). It is reproducible at certain window sizes. 

### Reproduction of the problem
Reproducible in the validation [demo](http://demos.telerik.com/kendo-ui/upload/validation). [Screenshot](https://www.screencast.com/t/EgNUoRsSauHq).
Depending on the window size the behavior might not be exhibited on load, so the window needs to be resized in order for the clipping to occur. 

### Current behavior
Icon is clipped.

### Expected/desired behavior
Icon is displayed correctly. 

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [Chrome XX | IE 11 ]

**Comment by zdravkov** [comment]
Seems fixed after the latest updates on the control.
