### ISSUE TITLE
Browser page crashes on content scroll

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#302]
### Description
Mobile Chrome (37.0.2062.117) optimizes meta tags added with JavaScript and thus they are not applied at the moment of the application initialization:

    <meta content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
Because of this, the window reports incorrect inner height value and the result is a page crash.

Repro demo: http://dojo.telerik.com/@ggkrustev/OQEz
Reported in Ticket ID: 859428

**Comment by naskog** [comment]
Fixed in recent browser versions. Not reproducible in Chrome 40.0.2214
