### ISSUE TITLE
Files with long names selected in the Upload overflow on window resize

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3021]
### Bug report
The file name leaves the boundaries of the Upload on resize.

### Reproduction of the problem
Reproducible in our demos. [Screenshot](https://www.screencast.com/t/hnRKy9nE1tS4).
Select a file and shrink the browser window. 

### Current behavior
The filename overlaps the Upload. 

### Expected/desired behavior
The filename should be cropped and not leave the boundaries of the Upload.

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [Firefox XX | IE 11 | Chrome 62]

**Comment by mvgmvg** [comment]
The correct behavior is cropping text - the entire file name is displayed by title HTML attribute by hovering. There is a workaround for scenarios where wrapping text to the second line would be expected:
`.k-file-name { white-space: normal }`

**Comment by Dimitar-Goshev** [comment]
After the fix, the % complete and Pause/Start buttons overlap the file name. Reproducible on Chunk Upload demo:
![image](https://user-images.githubusercontent.com/6614183/33207656-334b41fa-d117-11e7-873e-40d72d8a3e7f.png)

**Comment by Dimitar-Goshev** [comment]
The issue is still reproducible for LESS themes.
