### ISSUE TITLE
While exporting to Excel, the Grid's groupFooterTemplate does not pass the e.field.group object

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#3024]
### Bug report

While exporting to Excel, the Grid's **groupFooterTemplate** does pass the **e.fieldName.group** object

### Reproduction of the problem
Open the following dojo:
http://dojo.telerik.com/UTAsI

The group values of the grouped field will be logged in the console (e.month.group.value).
Clicking on the Export to Excel button will throw an error, because the group object will not be available

### Environment

* **Kendo UI version:** 2017.1.223

**Comment by simonssspirit** [comment]
Reported again in ticket: 1115756.

@mishoo I can assume that it is connected to this issue: https://github.com/telerik/kendo-ui-core/issues/3095

**Comment by Alex-Bubblemaster** [comment]
The format of the data is inconsistent. Ticket ID 981516

When in the grid, `groupFooterTemplate: "#=data.fieldName.group.field #` exists but in the Excel export it is passed as `data.group.field` which makes a condition in the groupFooterTemplate necessary.

```
groupFooterTemplate: "Count for #=data.ProductName.group ? data.ProductName.group.field : data.group.field #: #=count#"
```

Dojo: [http://dojo.telerik.com/@bubblemaster/EXuYu](http://dojo.telerik.com/@bubblemaster/EXuYu)

**Comment by matanasov** [comment]
@mishoo @Alex-Bubblemaster 
I have logged a new #3897 for this scenario. Closing this one as it is already released.
