### ISSUE TITLE
kendo.drawing.ElementsArray.splice mistakenly turns elements into [elements] and fails

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#3030]
*Note: I would have made a pull request if kendo.drawing was part of kendo-ui-core (which I suggest you change since kendo.drawing is part of the core framework).*

### Bug report

The code for kendo.drawing.ElementsArray.splice is:

```
splice: function (index, howMany) {
    var elements = slice.call(arguments, 2);
    var result = this._splice(index, howMany, elements);
    this._change();
    return result;
},
```
This is wrong because ```slice.call(arguments, 2)``` actually returns [elements], not elements, so you actually need ```slice.call(arguments, 2)[0]```. This does not affect the rest of kendo UI code base because kendo UI always uses the private _splice method, never uses the public splice method.

### Fix

The code for splice should be (change on line 2)

```
splice: function (index, howMany) {
    var elements = slice.call(arguments, 2)[0];
    var result = this._splice(index, howMany, elements);
    this._change();
    return result;
},
```

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** all
* **Browser:** all

**Comment by danielkaradachki** [comment]
What values are you passing to the method? The method is designed to work like the [Array.splice](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) method which it currently does - [example](http://dojo.telerik.com/@SiliconSoul/EYIKUz)

**Comment by jlchereau** [comment]
Currently making long hours. My mistake. Sorry for the trouble.
