### ISSUE TITLE
Incorrect defaults in Chart's majorGridLines documentation

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#3031]
http://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart#configuration-categoryAxis.majorGridLines.visible

```
 categoryAxis.majorGridLines.visible Boolean (default: false)
```

should be
```
 categoryAxis.majorGridLines.visible Boolean (default: true)
```

**Comment by MaceWindu** [comment]
Same problem for other instances of this setting

**Comment by danielkaradachki** [comment]
Thanks for pointing out this issue. I updated the documentation.
