### ISSUE TITLE
Menu hover working on root element with openOnClick: true

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3032]
### Bug report

After clicking on a root menu item you can also open root items subgroups with hover.
This can be related to the following [issue](https://github.com/telerik/kendo-ui-core/issues/2613)

### Reproduction of the problem

* Got to the following [Dojo example](http://dojo.telerik.com/AlIgU/4)
* Click on "Products" root item.
* Hover over "Stores" root item. 

### Expected/desired behavior

Root menu items should only be opened with click.

**Comment by jivanova** [comment]
Fix included in https://github.com/telerik/kendo/commit/e09af21e0f7b5b69207ca9a3325c7015261fce10
