### ISSUE TITLE
kendo.dataviz.themes.js doesn't work in strict mode

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#3035]
### Reproduction of the problem
Add `"use strict"` at the begining of script file that includes code from `kendo.dataviz.themes.js`

### Current behavior
Script fails to initialize

### Expected/desired behavior
Script initialized successfully

### Environment

* **Kendo UI version:** v2017.1.223

Problem is on line 440:
```
        }(this.kendo.dataviz = this.kendo.dataviz || {}));
```
must be replaced with
```
        }(window.kendo.dataviz = window.kendo.dataviz || {}));
```

**Comment by danielkaradachki** [comment]
The problem has been fixed and the fix will be available in the next internal build.
