### ISSUE TITLE
Image is deleted when deleting the last ordered list item using backspace

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#3037]
### Bug report

Image is deleted when deleting the last ordered list item using backspace

### Reproduction of the problem
[https://www.screencast.com/t/sdtK9Ttph](https://www.screencast.com/t/sdtK9Ttph
)

1. Navigate to http://demos.telerik.com/kendo-ui/editor/all-tools
2. Create an ordered list 
3. Place an image in a list item e.g. https://demos.telerik.com/kendo-ui/content/web/editor/kendo-ui-web.png
4. Create few new list items 
5. Delete the last list item using backspace

### Current behavior
The image is deleted

### Expected/desired behavior
Only one list item is deleted

### Environment

Reported in Ticket ID: 1103038

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 1.12.3
* **Browser:** [all ]

**Comment by mparvanov** [comment]
The original scenario is not reproducible any more with R3 2017 (https://www.screencast.com/t/qn8IG4e3) but the following reproduction steps are still applicable : 

1. Open the following sample [http://dojo.telerik.com/ADImA/2](http://dojo.telerik.com/ADImA/2) 
2. Position the cursor at the end of the content
3. Delete the entire last row using backspace

Actual result: The images are deleted
[https://www.screencast.com/t/f3wt9gzjjHqE](https://www.screencast.com/t/f3wt9gzjjHqE)

**Comment by InciteGmbH** [comment]
Dear Colleagues

This is a important issue for our customers, because they are loosing information when they are manipulating text with bullets. Thanks for a quick bugfix.

Kind regards.
Marc

**Comment by InciteGmbH** [comment]
Dear Colleagues

This is still open and not solved in Q1/18.

Thanks.
Marc

**Comment by mparvanov** [comment]
The issue has been resolved and the fix will be available in the next internal build as well as in R2 2018 official release.
