### ISSUE TITLE
Data validation dropdowns from named ranges are not imported with the Spreadsheet's server import 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3041]
### Reproduction of the problem
1. Create an named range in blank Excel workbook.
2. In a different column click a cell and create a validation dropdown with the named range set as Source (Data -> Data Validation -> Allow(List) Source(=myNamedRange)
3. Save the file and import it using server import ([demo](http://demos.telerik.com/aspnet-mvc/spreadsheet/server-side-import-export)). 
4. Expected: the dropdown is present in the Spreadsheet after importing the Excel file. Actual: the dropdown is not imported. 

### Current behavior
Currently the validation dropdown is properly imported through the client-side import ("Open..." button in the Spreadsheet's ToolBar), but is not imported through the server import. 

### Expected/desired behavior
Validation dropdown is imported with the Spreadsheet's server import. 

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by veselints** [comment]
Raising priority as reported in Ticket ID: 1179504

**Comment by mishoo** [comment]
Client-side import works properly.

**Comment by jivanova** [comment]
- Added support for server-side import/export of named ranges
- Added support for server-side validation 


[handled by Telerik.Web.Spreadsheet] Issue in DPL: [DPL bug tracker](http://tfsemea.progress.com:8080/DefaultCollection/WPF_Scrum/_queries?id=404836 )

**Comment by Dimitar-Goshev** [comment]
This seems as a related issue: https://github.com/telerik/kendo-ui-core/issues/1761
