### ISSUE TITLE
Pie chart hangs browser on some values

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#3042]
### Reproduction of the problem
create pie chart with series[].data[].value have only 0 or values from [Number.MIN_VALUE * 1e17, -Number.MIN_VALUE * 1e17] range (approximate, multiplying by 1e18 works).

### Current behavior
If there are only 0 values, pie chart's "pie" is not rendered at all
If there are only numbers from specified range and at least one is not 0 - browser hangs

### Expected/desired behavior
Pie chart should be rendered in both cases.

### Environment

* **Kendo UI version:** v2017.1.223
* **jQuery version:** 3.1.1
* **Browser:** all

**Comment by danielkaradachki** [comment]
The problem with the browser hanging should be fixed.
The rendering of the labels with zero values should also be fixed. Zero values will still not be rendered as segments.
