### ISSUE TITLE
Invalid template error is thrown when editing a field where DispayAttribute is set in cyrillic

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#3049]
### Reproduction of the problem
The FirstName and ShipAddress fields are defined in the Model like this:

`[Required]
[Display(Name = "Име")]
string FirstName
{
	get;
	set;
}`

`[Display(Name = "Адрес")]
public string ShipAddress
{
	get;
	set;
}`

### Current behavior
The problem can be observed in [this video](https://www.screencast.com/t/daEKhgDpz)

### Expected/desired behavior
The editing in the detail Grid should work the same as in the parent.

### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** [all]

**Comment by matanasov** [comment]
Doesn't replicate with 2018.1.221
