### ISSUE TITLE
Typo in kendo.culture.nb-NO.js

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#3052]
### Bug report
There is a type in the `kendo.culture.nb-NO.js` message file.

### Expected/desired behavior
Current:
last: "Sidste side" 

Should be:
last: "Siste side"

### Environment

* **Kendo UI version:** all
* **jQuery version:** all
* **Browser:** all

**Comment by ggkrustev** [comment]
Moved from https://github.com/telerik/kendo-angular/issues/470

**Comment by dbalinov** [comment]
@ggkrustev

No string `"Sidste side"` was found in the kendo.culture.nb-NO.js . 
Do you mean page last message: `"Gå til sidste side"` to be changed?

**Comment by Xizario** [comment]
It is already correct in `nb-NO` messages.
@tomaszgrabowski, please reopen the issue and give us more information if you still think there is problem.
