### ISSUE TITLE
Warnings are displayed in the DatePicker demos for ASP.NET MVC Core (Chrome latest)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3053]
### Bug report

Warnings are displayed in the DatePicker demos for ASP.NET MVC Core (Chrome latest). Still, the values are parsed as expected.

### Reproduction of the problem

The warnings can be observed on our demos: http://demos.telerik.com/aspnet-core/datepicker/index.

* **Browser:** [Chrome Version 57.0.2987.98 (64-bit)  ]

**Comment by Xizario** [comment]
https://github.com/telerik/kendo/commit/e6738e098b64698886664a089752431f6282de90 @MilenaCh
