### ISSUE TITLE
Bootstrap DatePicker is missing the bottom border.

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3054]
### Bug report

The bottom border of the DatePicker with bootstrap integration is missing when accessing from an iOS device.

### Reproduction of the problem

1. Open http://demos.telerik.com/kendo-ui/bootstrap/ on an iOS device.
2. Navigate to the "Birthday" DatePicker.

### Current behavior

The bottom border is missing.

### Expected/desired behavior

The bottom border is present.

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 1.12.3
* **Browser:** [Mobile Chrome | iOS Safari]

**Comment by theOrlin** [comment]
Duplicates https://github.com/telerik/kendo/issues/6260
