### ISSUE TITLE
Scroll to the task when it is clicked on in the treelist area

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#3057]
### Bug report
http://demos.telerik.com/kendo-ui/gantt/keyboard-navigation

### Current behavior
The Timeline is scrolled to the task when its item is focused (navigated to using the arrow keys) in the TreeList. Yet, when you click on the task in the TreeList using the mouse, the Timeline is not scrolled to.

### Expected/desired behavior
The Timeline should be scrolled to the currently selected task, when a task has been clicked on in the TreeList part of the widget.

### Environment
* **Kendo UI version:** 2017.1.223
* **Browser:** [all]

**Comment by abindalSchuco** [comment]
What is the ETA for this Bug?

**Comment by ag-petrov** [comment]
Not reproducible with the latest version
