### ISSUE TITLE
TreeView visual glitch in IE with fixed container height

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3059]
### Bug report

A flickering effect occurs when interacting with the TreeView items, when the container is with fixed height (IE 11 only).

### Reproduction of the problem

* Go to the [following Dojo example](http://dojo.telerik.com/EhEgi/23)
* Scroll to the bottom of the menu
* Click several times on a random item from the list

[Screencast](https://www.screencast.com/t/DJgMIUy1SqgT)

### Expected/desired behavior

There should not be any flickering when clicking on TreeView items.

### Workaround:
A workaround could be achieved by overwriting the focus function:
[http://dojo.telerik.com/acUDEKum ](http://dojo.telerik.com/acUDEKum )

### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** [IE 11]

**Comment by alexandrejobin** [comment]
I also have this problem and the workaround have solved my problem. Thank you!
