### ISSUE TITLE
Pasting plain text from Word into Editor can cause a JavaScript error when msConvertLists option is on

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3060]
### Bug report
Editor throws *Cannot read property 'replace' of undefined* error when *msConvertLists* option is on and a certain type of plain text is pasted from MS Word into the editable area.

The text should not be converted at all as no list is inserted, but a plain text with bullet element.

The above could be observed only in IE and Chrome.

### Reproduction of the problem
* Open the following [Dojo](http://dojo.telerik.com/@NerdBrick/EMuKo) in Chrome;
* Copy the text in the golden-brown rectangular;
* Paste the text into Editor;
* Cannot read property 'replace' of undefined error will be thrown on the console;

The above could be reproduced by Copy>Paste from [the following .docx file](https://admin.telerik.com/ClientsFiles/1564d069-5028-4aaa-b969-f9be8a38be06_KendoEditorBug.zip)

### Environment
* **Browser:** [ Chrome XX | IE XX ] 
* **Version:** 2018.3.911 http://dojo.telerik.com/OPoNOVIQ

**Comment by Iankodj** [comment]
The case with the content from this file will never work ideally. This content fakes a list, but as this only symbol with some plain text it is missing the list attributes needed for the formatting to be parsed. 

Thus, the JS error can be fixed. But the content as plain text will be always included inside a list when msConvertLists is enabled.
