### ISSUE TITLE
Pasting formatted cells from Excel to Spreadsheet changes the content of empty cells from null to empty string

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3066]
### Bug report
Pasting empty formatted cells from Excel to Spreadsheet changes the content of empty cells from *null* to *empty string ("")*.

### Reproduction of the problem
* Open [Dojo](http://dojo.telerik.com/UYoqAb/11);
* Open an excel spreadsheet;
* In the excel spreadsheet leave A1 and B1 blank, but put "Test" in C1;
* Select A1:C1, and change the fill color of the cells to be highlighted;
* Copy cells A1:C1;
* Paste the cells into the provided Dojo;
* Click on cell A1 in the dojo. You can see that the value is " ";
* The same is true for cell B1, but it also causes the validation to fail;

This does not happen when there is no cell formatting coming from excel

### Expected/desired behavior
When pasting formatted cell with no value, the cell in the Spreadsheet should retain its initial value (null).

**Comment by mparvanov** [comment]
Closing due to relatively low severity and lack of recent demand by the community.
