### ISSUE TITLE
Line chart with invisible points fails to render

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#3067]
### Bug report
Line chart rendering fails with `TypeError: targetBox is undefined` with following stack:
```
BoxElement<.reflow
LinePoint<.markerBox
LinePoint<.overlapsBox
ChartContainer<.unclipLabels
ChartContainer<.createVisual
ChartElement<.renderVisual
ChartElement<.renderChildren
ChartElement<.renderVisual
ChartElement<.renderChildren
ChartElement<.renderVisual
ChartElement<.renderChildren
ChartElement<.renderVisual
ChartElement<.renderChildren
ChartElement<.renderVisual
Chart<._redraw
Chart<.init/<
FontLoader.loadFonts
FontLoader.preloadFonts
Chart<.init
Chart<._createChart
Chart<._initChart
Chart<._initDataSource
Chart<.init
.plugin/$.fn[name]/<
.each
jQuery.prototype.each
.plugin/$.fn[name]
```

Debuging shows that `LinePoint.markerBox` pass undefined to reflow method for `this._childBox`.
I've checked when it could skip initialization of this field and found that it is done in `CategoricalChart.reflow` when `valueAxis.getSlot()` returns null and point marked as not visible.

Looks like somewhere in stack above check for point.visible is missing, maybe in `ChartContainer.unclipLabels`'s `if` condition?

### Reproduction of the problem
Point could be marked invisible if it has negative value for logarithmic scale of value axis.

### Current behavior
Rendering fails with TypeError

### Expected/desired behavior
No errors expected

### Environment

* **Kendo UI version:** v2017.1.223
* **jQuery version:** 3.1.1
* **Browser:** all

**Comment by danielkaradachki** [comment]
Thanks, should be fixed for the next internal build
