### ISSUE TITLE
JavaScript error when all panels of a PanelBar are disabled

### ISSUE THREAD

**Issue by tjvantoll** [telerik/kendo-ui-core#307]
Via http://stackoverflow.com/questions/25998209/kendo-panelbar-error

If all panels from a PanelBar are disabled, and you then click within a PanelBar control, you get a JavaScript error. The example [we show in the docs](http://docs.telerik.com/kendo-ui/api/javascript/ui/panelbar#methods-enable) actually has this problem, which I simplified a bit here: http://dojo.telerik.com/@tjvantoll/ehEjA.

**Comment by naskog** [comment]
Steps:
Click within a panel
Click out of the panel

Result: JS Error "TypeError: r[0] is undefined"

Can be reproduced here: http://dojo.telerik.com/@naskog/UfOsU
