### ISSUE TITLE
grid widget extension — drawDOM / pdf.saveAs — headers do not repeat when repeatHeaders true

### ISSUE THREAD

**Issue by KthProg** [telerik/kendo-ui-core#3075]
### Bug report
When calling drawDOM then pdf.saveAs on a kendo grid extension, the headers are not repeated.

### Reproduction of the problem
http://dojo.telerik.com/ojIwi/35
If you change the data-role attribute to grid, then everything works fine.

### Expected/desired behavior
drawDOM / pdf.saveAs should repeat headers for kendo grid extensions when repeatHeaders is true

### Environment

* **Kendo UI version:** 2016.3.914
* **jQuery version:** 1.12.3
* **Browser:** IE 11, Chrome

**Comment by danielkaradachki** [comment]
Should be fixed in telerik/kendo@492d5c872684df4df6e09f6fea9510e33c9a37cd
