### ISSUE TITLE
Search in TreeView filtering demo is stacking items

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3076]
### Bug report

Category search causes items to stack when some of the root nodes are collapsed.

### Reproduction of the problem

* Go to the [TreeView filtering demo](https://demos.telerik.com/kendo-ui/treeview/filter-treeview-in-dialog)
* Collapse all root nodes
* Type "f" in Category search

### Expected/desired behavior

The items should not be stacked when performing a search.

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible anymore with R2 2017 SP1 demos online.
