### ISSUE TITLE
Justified category axis could lead to missing dataItem in point tooltip template

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#3077]
### Bug report
In line chart when categoryAxis.justify is set to true and panning is enabled point tooltip template could receive data without dataItem property when point located at chart's edge.

### Reproduction of the problem
http://dojo.telerik.com/IFaViB/3
If you will pan chart to make point partially hidden by right edge of chart you will notice that first category axis label disappears but point is still visible partially. At this moment if you will look at point template you will see that dataItem property in template model is undefined.

### Current behavior
Point tooltip broken for points near to the chart age if it uses data from dataItem

### Expected/desired behavior
Tooltip has access to dataItem always

### Environment

* **Kendo UI version:** v2017.1.223
* **jQuery version:** 3.1.1
* **Browser:** all

**Comment by danielkaradachki** [comment]
The points are considered out of range and that is why currently they not have dataItem. However, since they can be visible I guess we should include it. We will fix this for the next internal build.
