### ISSUE TITLE
PanelBar's select event fires only once (FF)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3079]
### Bug report

When an item is clicked in Firefox the select event fires only once. On subsequent item selection the event does not fire. 

### Reproduction of the problem
[Dojo](http://dojo.telerik.com/OWIqO) example. 
Consecutively select different PanelBar items.

### Current behavior
The event fires only once. 

### Expected/desired behavior
The event fires every time an item is selected. 

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [ Firefox 52.0.2 and newer  ]

**Comment by zdravkov** [comment]
Could not reproduce it.
