### ISSUE TITLE
Use of jQuery's removeAttr function setting boolean properties

### ISSUE THREAD

**Issue by scottyb86** [telerik/kendo-ui-core#3081]
When the latest version of Kendo 2017.1.223 is used with JQuery 3.1.1, the jQuery Migrate script (https://github.com/jquery/jquery-migrate) reports that in the kendo.web.js file, Jquery's removeAttr function is being used to set boolean properties.

Here is the message I get in the console:

jQuery.fn.removeAttr no longer sets boolean properties

Here is Jquery's description of the problem, as well as their proposed solution:

"Cause: Prior to jQuery 3.0, using .removeAttr() on a boolean attribute such as checked, selected, or readonly would also set the corresponding named property to false. This behavior was required for ancient versions of Internet Explorer but is not correct for modern browsers because the attribute represents the initial value and the property represents the current (dynamic) value.

Solution: It is almost always a mistake to use .removeAttr( "checked" ) on a DOM element. The only time it might be useful is if the DOM is later going to be serialized back to an HTML string. In all other cases, .prop( "checked", false ) should be used instead."

**Comment by Dimitar-Goshev** [comment]
This issue is included in the following broader issue - https://github.com/telerik/kendo-ui-core/issues/5439
