### ISSUE TITLE
MaskedTextBox breaks in IE after using Ctrl-Z command

### ISSUE THREAD

**Issue by EduardoSerra** [telerik/kendo-ui-core#3085]
### Reproduction of the problem

1) Copy to clipboard some random numbers, for example "6416516546541564654564"
2) Open your demo page http://demos.telerik.com/kendo-ui/maskedtextbox/index in Internet Explorer 
3) Focus first masked texbox (phone number) and select all text in it
4) Paste copied text - text gets cropped and fitted correctly - so far everything works as expected
5) Press Ctrl + Z twice

### Current behavior
Masked textbox is broken. See screenshot: ![screenshot](https://cloud.githubusercontent.com/assets/961284/25346786/a29e24d4-28e6-11e7-85be-6f9e04e44a24.png)

### Expected/desired behavior
It goes back to its original value after pressing Ctrl-Z twice

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 1.12.3
* **Browser:** [IE ]

**Comment by Xizario** [comment]
Looks to be resolved in 2017.2.504
