### ISSUE TITLE
Grid k-on-change attribute fails when passing in 'selected' with AngularJS v1.2.24

### ISSUE THREAD

**Issue by durz** [telerik/kendo-ui-core#309]
The [documentation for the grid's AngularJS directive](http://kendo-labs.github.io/angular-kendo/#/grid-widget) suggests that you can access the element of the row selected in a grid by passing in a `selected` variable to the `k-on-change` handler.

This is no longer possible with Angular 1.2.24 as you now get an error stating `Referencing DOM nodes in Angular expressions is disallowed!`

To reproduce:
Dojo: http://dojo.telerik.com/AgILE/3
1. Select a row
2. Observe that an error is thrown in the console
3. Change
`<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.24/angular.js"></script>` to 
`<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.js"></script>`
4. Re-run the dojo
5. Select a row
6. Observe that no error is thrown in the console

**Comment by mishoo** [comment]
I added a note in the documentation about this.  I can't see any possible fix from our side.

I tried to persuade that the restriction is pointless, [here](https://github.com/angular/angular.js/issues/9220) and [here](https://github.com/angular/angular.js/pull/9301), but I could have spoken to a brick wall to the same effect. :-(
