### ISSUE TITLE
The variable data.columName.group is undefined during the Grid Excel export.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3095]
### Bug report

The variable data.columnName.group is undefined during the Grid Excel export. The variable is correctly displayed in the Grid groupFooterTemplate, but it is undefined during the export.

### Reproduction of the problem

The issue can be observed in the following Dojo: http://dojo.telerik.com/Aruwu/3

### Environment

* **Browser:** [all ]

**Comment by mishoo** [comment]
This works fine with the latest code from master.
