### ISSUE TITLE
Telerik.Web.SpreadSheet.Workbook does not preserve leading zeros when saving to stream

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3099]
### Bug report

Leading zeroes in text formatted cells are not being preserved if you try to save the value to stream in ASP.NET MVC. 

In **SetCells()** method (Workbook.ToDocuments.cs) the following if statement does not check for cell formatting:
```` C#
else if (double.TryParse(stringValue, out numericValue))
{
    selection.SetValue(numericValue);
}
````

In this case the **stringValue** is being parsed as a double, so the leading zeros are being removed.

### Reproduction of the problem

* Create workbook from JSON data
* Try to save the workobook ( `workbook.Save(stream, extension);` )

### Expected/desired behavior

Cell formatted as text should be saved with leading zeroes preserved in excel.

**Comment by Juveniel** [comment]
Possible fix suggestion: 
```` C#
else if (double.TryParse(stringValue, out numericValue) && cell.Format != "@")
{
    selection.SetValue(numericValue);
}
````

**Comment by veselints** [comment]
also reported in Ticket ID: 1140601

**Comment by veselints** [comment]
Also reported in [Ticket ID: 1145139](https://admin.telerik.com/default.aspx?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1145139&SM=0)

**Comment by jivanova** [comment]
Duplicated issue with: https://github.com/telerik/kendo-ui-core/issues/2598 which has now highest priority. You could track the progress there.
