### ISSUE TITLE
kendo.drawing.Path.parse returns a MultiPath, not a Path

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#3106]
### Bug report

Doc at http://docs.telerik.com/kendo-ui/api/javascript/drawing/path#parse says parse method returns a drawing.Path. It actually returns a drawing.MultiPath.

### Reproduction of the problem

See http://dojo.telerik.com/oJenU.

### Expected/desired behavior

Either it should return a drawing.Path and a fix is required in the code.

Or it should return a drawing.MultiPath and a fix is required in the docs (note that in this case, it would make sense to move the parse method to drawing.MultiPath).

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** any
* **Browser:** all

**Comment by danielkaradachki** [comment]
Thanks, I updated the documentation.
The result cannot be a Path because input like `M 0,0 L 100,100 M 200,200 L 300,300` cannot be represented with a single drawing Path.
