### ISSUE TITLE
Window does not fire error event when in iframe mode

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3119]
### Bug report
Window does not fire error event when in iframe mode

### Reproduction of the problem
Run the following [Dojo](http://dojo.telerik.com/oKaJUK/10). The *error* event won't be fired. 

### Expected/desired behavior
Window should fire *error* event

**Comment by Iankodj** [comment]
The error handler of the Kendo Window is supposed to be thrown only when AJAX request is utilized: http://docs.telerik.com/kendo-ui/api/javascript/ui/window#events-error. 

With the iframe option enabled, the URL is set to the `src` attribute of the iframe element in the popup.  Hence, there is no AJAX request in that scenario, but a browser request, which does not throw an error event that could be handled. 

A possible solution to handle potential errors for requests made by the browser (like in this case) you can first make an AJAX call (e.g., by using [jQuery.ajax()](http://api.jquery.com/jquery.ajax/)) to the URL and handle the error event from there. If the AJAX request returns a valid response, then set up the Kendo Window with the URL required.
