### ISSUE TITLE
Toolbar's overflow button in RTL mode scrolls page to top under IE

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3121]
### Bug report

In RTL mode, clicking on the overflow button scrolls the page to top. 

### Reproduction of the problem
http://dojo.telerik.com/oJaJAk

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 1.12.3
* **Browser:** [ IE 11 ]

**Comment by Dimitar-Goshev** [comment]
This issue has one and the same or similar cause with the following one: https://github.com/telerik/kendo-ui-core/issues/3134

**Comment by zdravkov** [comment]
Can be tested in this [branch](https://github.com/telerik/kendo-ui-core/tree/dropdown-fixes)
