### ISSUE TITLE
PageSizes dropdown and filter menus auto-closing in Grid with no height set

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#3124]
### Bug report
When a Grid with no height set is last in a page with scrollable content, and the page size is changed via the UI, the dropdown auto-closes immediately when opened again. Same is observed with the filter menus when the menu has greater height than the Grid (e.g. the grid is left empty or with 1 item):

[http://dojo.telerik.com/iMolO/3](http://dojo.telerik.com/iMolO/3)

Steps to reproduce:

1) Scroll to the bottom and either change the page size to a smaller one, or filter the Grid such that few or no items remain
2) Open the dropdown or filter menu - both are immediately closing

Both issues are resolved when the page is scrolled

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by TsvetinaIvanova** [comment]
Also reported in ticket with id 1128946.

**Comment by populationtwo** [comment]
This appears to be resolved on Kendo 2017.3.1102.
