### ISSUE TITLE
compile issue in kendo.core.js

### ISSUE THREAD

**Issue by htta17** [telerik/kendo-ui-core#3133]
### Bug report
Please see at   [Link ]( https://www.screencast.com/t/Nk4a7LNxz )
After comparing to source code, I found that problem in kendo.core.js, template is undefined (compile function)

### Current behavior
_(optional)_
Provide additional information if the steps for reproducing the faulty behavior are not sufficient to describe the issue.

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment

* **Kendo UI version:** 2016 .1.112
* **jQuery version:** Any
* **Browser:** all

**Comment by zdravkov** [comment]
I could not replicate the issue at my side. Would you please share a [dojo ](http://dojo.telerik.com/)where we can observe the issue?

**Comment by zdravkov** [comment]
I have closed the issue because we could not replicate it and there is not enough information about it.
