### ISSUE TITLE
DropDowns Popup appears in wrong position in IE in RTL mode when the page is scrolled

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-ui-core#3134]
### Bug report

The Popup is rendered in wrong position when "k-rtl" class is applied on the body, and the page is scrolled. Reproducible in IE v. 11.0.41:

[http://dojo.telerik.com/iDisA/2](http://dojo.telerik.com/iDisA/2)

Might be related to [https://github.com/telerik/kendo-ui-core/issues/673](https://github.com/telerik/kendo-ui-core/issues/673)

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** x.y
* **Browser:** [ IE 11 ]

**Comment by zdravkov** [comment]
Can be tested in this [branch](https://github.com/telerik/kendo-ui-core/tree/dropdown-fixes).
