### ISSUE TITLE
An excel file with filters in not properly imported into the Spreadsheet - the filters are not applied.

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3137]
### Bug report
If all options for filtering are selected in an Excel file, when the file is imported client side into Spreadsheet, then the filter functionality is not applied at all - no filter for the column.

NOTE: if any of the options for filtering is unchecked in the Excel file, then when imported in Spreadsheet, filtering is properly applied.

### Reproduction of the problem
Use the following Excel file.
[Book1.xlsx](https://github.com/telerik/kendo-ui-core/files/2289974/Book1.xlsx)
When opened in Excel, there is filter for column B:
![image](https://user-images.githubusercontent.com/6614183/44145198-4b4964b6-a093-11e8-88b2-ab2142cf6aa6.png)
But when opened in Spreadsheet, there is no filter for column B.

### Current behavior
The filter are not applied in Spreadsheet.

### Expected/desired behavior
The filters should be applied to column B in Spreadsheet as in Excel.

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by mishoo** [comment]
Is this referring to client-side import, or server-side?  Also, the description is a little contradictory, I read it as “filters are not imported, but however, filters are imported”.

**Comment by Dimitar-Goshev** [comment]
@mishoo I updated the description above with proper reproduction steps.
