### ISSUE TITLE
Large Navigatable and Selectable Grid requires multiple clicks to create a DropDownList editor

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3138]
### Bug report

Custom KendoDropDownList editor not rendering in large selectable and navigatable Grid.

When you click on the DropDown cell, the cell flashes and the dropdown seems to appear briefly, then it closes. The same Grid has ComboBox editor which is working fine.

For example, disabling grouping will fix it, but it reproduces it again with more items.

Disabling the navigatable property will also fix it.

Also, making the Grid pageable will resolve it.

**For Feature Requests - please submit those into [our UserVoice feedback portal](http://kendo.uservoice.com/)**

### Reproduction of the problem

The issue can be observed in the following Dojo: http://dojo.telerik.com/ADEFA

### Environment

* **Browser:** [all ]

**Comment by Alex-Bubblemaster** [comment]
Possibly related with:
https://github.com/telerik/kendo-ui-core/issues/2743
https://github.com/telerik/kendo-ui-core/issues/3270

Ticket ID 1123514 reports this behaviour only on a specific page
Ticket ID 1120003 - Reproducible only in IE, same symptoms [Fiddle](https://jsfiddle.net/nickwest366/fdughebf)
