### ISSUE TITLE
Up arrow click navigates to child grid header instead of the parent header cell when navigable option is enabled

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#3141]
### Bug report

In cases of hierarchy the up arrow click focuses the child grid's header cell instead of the parent grid's header cell. 

### Reproduction of the problem

Please refer to the http://dojo.telerik.com/aviyi/3 example and follow the steps below: 
   1. Click on Nancy cell. 
   2. Click on the up arrow key. 

### Current behavior

The child grid header cell is focused. 

### Expected/desired behavior

The parent grid header cell should be focused. 

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Please test navigation from thead to tbody and from the cell holding the expand/collapse button to the thead.

**Comment by MilenaCh** [comment]
Up arrow key on some data cell from the first item moves focus to the wrong header cell.
