### ISSUE TITLE
ComboBox value not retained with syncValueAndText: false

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3144]
### Bug report

If you initialize a ComboBox with initially set value, text and syncValueAndText: false and try to expand it without selecting any item, the value is not retained. This happens when the ComboBox DataSource does not have an item with value field equal to the value set for the widget.

### Reproduction of the problem

* Got to [the following Dojo example](http://dojo.telerik.com/@Dimitar.K/UTisO/2)
* Alert the value of the ComboBox with the button
* Open the ComboBox and then close it without selecting any value
* Alert the value again

### Expected/desired behavior

The value of the ComboBox should be preserved when no selection change is made.

### Environment

* **Kendo UI version:** 2017.1.223

**Comment by Dimitar-Goshev** [comment]
Another issue with the same property set to false: https://github.com/telerik/kendo-ui-core/issues/3403

**Comment by zdravkov** [comment]
Could not replicate it with the latest version.

**Comment by mparvanov** [comment]
The fix will be available in R1 2018.
