### ISSUE TITLE
23h 59m length scheduler block on 29 Oct 2017 is not rendered due to DST conversion

### ISSUE THREAD

**Issue by timurgaitov** [telerik/kendo-ui-core#3147]
To reproduce:

0. set your computer timezone to UTC+1 Belgrade (which has daylight saving time)
1. go to http://demos.telerik.com/kendo-ui/scheduler/index
2. select 2017 october 29
3. create block from 12:00 AM to 11:59 PM
4. see that the block is not visible and we got error in the console:
`Uncaught TypeError: n.innerWidth is not a function`

I think this happens because the length of the block is bigger than 24 hours. Actually because the time changes on that day, we have length 24h 59m

Try this code (UTC+1 Belgrade should be set on your computer):
`new Date(2017, 9, 29, 23, 59, 0) - new Date(2017, 9, 29, 0, 0, 0)`
and compare to any other date like
`new Date(2017, 9, 30, 23, 59, 0) - new Date(2017, 9,30, 0, 0, 0)`

**Comment by Dimitar-Goshev** [comment]
Hi,
I am testing the fix for this issue. I believe that in the end of the reproduction steps above you mean Oct, not Sept, thus the dates would be as follows:

> Try this code (UTC+1 Belgrade should be set on your computer):
> `new Date(2017, 10, 29, 23, 59, 0) - new Date(2017, 10, 29, 0, 0, 0)`
> and compare to any other date like
> `new Date(2017, 10, 30, 23, 59, 0) - new Date(2017, 10, 30, 0, 0, 0)`
