### ISSUE TITLE
Scheduler custom view problem

### ISSUE THREAD

**Issue by cy6eria** [telerik/kendo-ui-core#3151]
### Bug report

A scheduler with custom view don't mark selected custom view as a selected.

### Reproduction of the problem

The built-in views become orange when selected. The custom ones are not.
http://dojo.telerik.com/IKAJOB

### Current behavior
The selected custom view don't become marked.

### Expected/desired behavior
The selected custom view should become marked.

### Environment

* **Kendo UI version:** 2017.1.223
* **jQuery version:** 1.12.3
* **Browser:** all

**Comment by cy6eria** [comment]
I figured out that the problem related with a custom view title. If you use a one word title then it will work normal. In other hand, the view title goes to the css class and the problem will appear.

I think you should use a view type (this is a one word) everywhere. It appears in a navigate event as a "view" property too.

**Comment by zdravkov** [comment]
The widget expects string for the type of the custom view and then it will be selected correctly. Here is my [sample dojo](http://dojo.telerik.com/@zdravkov/urafU).

**Comment by cy6eria** [comment]
@zdravkov then it should be changed at [documentation](http://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/how-to/custom-views/custom-view).

**Comment by zdravkov** [comment]
I have updated it - thank you for the remark.
