### ISSUE TITLE
Using a ComboBox as a custom editor in a batch editable Grid causes the Grid save event to fire twice

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#3153]
### Bug report
If you use a ComboBox as a custom editor in the MVC Grid, using InCell batch editing, the Grid Save event is fired twice when selecting an item in the ComboBox after a search.

### Reproduction of the problem
1. Open the [custom editor](http://demos.telerik.com/aspnet-mvc/grid/editing-custom) demo locally.
2. Replace the **DropDownListFor** in the custom editor file with **ComboBoxFor**.
3. Handle the Grid Save event.
4. Run the sample and open a cell for editing.
5. Type in some search criteria, e.g. "C" and select one item from the result.

### Current behavior
The Save event is fired twice.

### Expected/desired behavior
The Save event should be fired only once, as it is with the DropDownList editor.

### Environment

* **Kendo UI version:** 2017.1.223

**Comment by ag-petrov** [comment]
This is a limitation in the current implementation. Altering the logic will break scenarios in which the model value is changed in the save event or will break the combobox.
