### ISSUE TITLE
kendo.toString with one argument should not simply return the first argument

### ISSUE THREAD

**Issue by madelson** [telerik/kendo-ui-core#3159]
Referred from http://www.telerik.com/forums/surprising-behavior-of-kendo-tostring-with-one-argument#uIfEHp_GIEaM9RVv3d9Z8A

### Bug report

My use-case is that I am trying to format a numeric value in a culture-aware way using kendo.

In many cases, I can do this via kendo.toString, for example:

`kendo.toString(1.67, "#.##")`

However, in this case rather than specifying a custom format I wanted to use the "natural" format (as many decimal places as the number has). In C#, for example, you can get this by calling ToString() on a value of type double. I thought that `kendo.toString(number)` might have the same behavior, and was surprised when it returned a number back. A workaround for my use-case is to do `kendo.toString(number, "#.############")`, but the current behavior with one argument seems like a bug that might catch others up in the future.

### Reproduction of the problem
`kendo.toString(1.67)`

### Current behavior
Returns the number `1.67`

### Expected/desired behavior
either `"1.67"` (as appropriate given the current kendo culture), or an error indicating that multiple arguments are required

### Environment

* **Kendo UI version:** 2017
* **jQuery version:** 2.1.4
* **Browser:** all

**Comment by ag-petrov** [comment]
As my colleague Tsvetina mentioned in the forum post altering the method in order to meet the above requirements will lead to a breaking change which is not desirable. Moreover the current behavior is not a bug and is by design. Considering the aforementioned I am marking the item as closed.

As a solution I suggest integrating the workaround you have mentioned.

**Comment by madelson** [comment]
@ag-petrov can you explain how this is by design? When would I ever want a method called toString to return something of a non-string type? I understand and applaud the desire for backwards compatibility, but in this case it isn't clear to me that this is documented functionality vs an undocumented corner-case bug.
