### ISSUE TITLE
Editor changes its height when mouse down over the toolbar

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#3163]
### Bug report

Editor should not get resized when mouse is down over the toolbar. Video - [VIDEO](https://www.screencast.com/t/mcm1HUIA)

### Reproduction of the problem

1. [demo](http://demos.telerik.com/kendo-ui/editor/index) Open the demo
2. Mouse down over the toolbar
3. Start moving the mouse

### Current behavior
Editor is resized in the direction in which the mouse is moved

### Expected/desired behavior
Editor keeps its size

### Environment

* **Kendo UI version:** 2017.1.223
* **Browser:** all

**Comment by mparvanov** [comment]
Not reproducible with 2018.3.1017
