### ISSUE TITLE
TabStrip tab content receives incorrect height of 0px after being disable and re-enabled, with custom animation configured.

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3164]
### Bug report
TabStrip tab content receives incorrect height of 0px after being disable and re-enabled, with custom animation configured. The Tab should be selected while disabling it,

### Reproduction of the problem
* Go to the following [Dojo](http://dojo.telerik.com/ezolO/6);
* Select the second tab;
* Click the *Disable second* button;
* The selection will move to the first tab;
* Click the *Enable second* button;
* Select the second tab - its content element will have height of 0px;

### Expected/desired behavior
Tab content should retain its predefined height;

**Comment by Iankodj** [comment]
The layout issue appears due multiple calls of the `kendoTabStrip` method over the same DOM element in the `disable` and `enable` methods. That causes multiple widget initialization and multiplies the animations applied over the DOM, which leads to sporadic behavior. 

The proper way to get widget reference is documented here: http://docs.telerik.com/kendo-ui/intro/widget-basics/events-and-methods#getting-widget-references. 

Here is also a fixed dojo for reference: http://dojo.telerik.com/ezolO/12.
