### ISSUE TITLE
Screen readers NVDA and JAWS do not read the focused menu item

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-ui-core#3166]
### Bug report

When a sub menu popup has been opened, the screen readers do not read first item. The other items are not read as menu and sub menu items like jQuery UI menu ([http://dojo.telerik.com/@nstoychev/ipOhIF](http://dojo.telerik.com/@nstoychev/ipOhIF)).

### Reproduction of the problem
Reproducible in this dojo: (http://dojo.telerik.com/@nstoychev/IcaPOM)
Navigate to "Tables & Chairs" (Products -> Furniture -> Tables & Chairs) using the keyboard arrows.

### Current behavior
The readers do not read "Tables & Chairs".

### Expected/desired behavior
"Tables & Chairs" to be read.

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** Chrome, Firefox

**Comment by richmag** [comment]
Thanks!  Please note JQuery UI menus handle this scenario, and the HTML/DOM is similar.

**Comment by jivanova** [comment]
Fix included in: https://github.com/telerik/kendo/commit/e09af21e0f7b5b69207ca9a3325c7015261fce10

**Comment by mparvanov** [comment]
The first sub item is not read by Jaws and NVDA:
http://dojo.telerik.com/@parvanov/opOpa/2

**Comment by jivanova** [comment]
Use JAWS for IE and NVDA for FireFox

**Comment by Dimitar-Goshev** [comment]
Not reproducible with Kendo UI 2019.1.115 - https://dojo.telerik.com/@Goshev/EPesoxoD
