### ISSUE TITLE
NumericTextBox with a negative value pointer does not go between the clicked numbers

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3168]
### Bug report

When you click on NumericTextBox with a negative value, the pointer does not go between the clicked numbers.

### Reproduction of the problem

http://dojo.telerik.com/UTOSa

### Current behavior

In the above Dojo when you click between "2" and "3", the pointer goes between "1" and "2".

### Expected/desired behavior

The pointer goes between "2" and "3".

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** 1.12
* **Browser:** [all]

**Comment by NikoPenev21** [comment]
#### Regression with fixing this.
Cursor wrongly placed on the focus of the NumericTextBox

#### Reproduction of the problem
* Run the following demo: https://demos.telerik.com/kendo-ui/numerictextbox/index
* Click in the Price NumericTextBox to focus it
* The cursor goes in from of the value

![image](https://user-images.githubusercontent.com/46747298/106615109-c7585a00-6574-11eb-92cc-d0e7b035c30b.png)

#### Expected/desired behavior
The cursor shall be placed after the value.

### Environment
* **Kendo UI version:** 2020.2.513 or above
* **Browser:** [all]
