### ISSUE TITLE
Spreadsheet loses Time, when editing cell with custom Date and Time formatting

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3169]
### Bug report
Spreadsheet loses Time when editing cell with custom Date and Time formatting

### Reproduction of the problem
* Go to the following [Dojo](http://dojo.telerik.com/OlaXo/16)
* Start editing the A1 cell;
* The Time part of the cell disappears;
* Manually type Time greater than 13:00;
* Click another cell to exit editor;
* The A1 cell will have its Time set to 00 00;

### Expected/desired behavior
The editor should retain the cell Time value, should display it and should allow editing. [Here](https://www.screencast.com/t/1n5OdoWyp0IB) could be seen the behavior of Excel in a similar scenario

**Comment by Dimitar-Goshev** [comment]
- Date is presented as a number in the formula bar, when the cell is selected:
![image](https://cloud.githubusercontent.com/assets/6614183/26254166/4665e008-3cbe-11e7-8366-4b12b33f3002.png)

- Date is presented as a number in the cell, when the cell is in edit mode:
![image](https://cloud.githubusercontent.com/assets/6614183/26254196/606b84d0-3cbe-11e7-8475-24ff76d9e3ef.png)
