### ISSUE TITLE
Draggable element is being dragged on scroll in IE8

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#317]
Can be reproduced here:

http://dojo.telerik.com/USIC

**Comment by esinek** [comment]
Issue with IE9 as well.
http://www.telerik.com/forums/ie-drag-thumb-on-scrollbar-in-sortable-item-tries-to-drag-sortable-item

**Comment by underlog** [comment]
The easiest and most reliable way to work around this behavior is to nest a container in the draggable:

http://dojo.telerik.com/@petyosi/uFUXE

Given the complexity it would take to address this case (for instance - the RTL mode), we consider the workaround to be far more reliable.
