### ISSUE TITLE
Cell content in Spreadsheet are automatically underlined on second Save 

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3173]
### Bug report

Cell content in Spreadsheet are automatically underlined on second Save - Telerik.Web.Spreadsheet.Workbook.Save(path)

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Dimitar-Goshev** [comment]
Closing this as a duplicate of the issue referenced above.
