### ISSUE TITLE
Missing Notification icon right margin

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3176]
### Bug report
The "**error**", "**info**" and "**success**" Notification types have no margin-right set for their respective icons. The only type that has **margin-right: 4px** is the "**warning**" Notification. 

### Reproduction of the problem
Sample [dojo](https://dojo.telerik.com/IVeXEGux).

### Current behavior
Right margin is set only to the "warning" Notification:
![image](https://user-images.githubusercontent.com/6614183/48468916-f51b2200-e7f5-11e8-972d-e15b75bc5a41.png)

### Expected/desired behavior
Identical margins across all Notification types, as in SASS themes:
![image](https://user-images.githubusercontent.com/6614183/48468943-03693e00-e7f6-11e8-9880-56f61ce75a50.png)

**Workaround:**

.k-notification-wrap .k-i-error, 
.k-notification-wrap .k-i-success,
.k-notification-wrap .k-i-info {
  margin-right: 4px;
}

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by joneff** [comment]
Fixed by 3e59f4d5901d41c8f55ed9ce7d698fe1424ab22e
