### ISSUE TITLE
TimePicker does not preserve the new value when dateInput is enabled

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#3179]
### Bug report
TimePicker does not preserve the new value when dateInput is enabled

### Reproduction of the problem
Refer to the following dojo example:
[http://dojo.telerik.com/ImAFar/6](http://dojo.telerik.com/ImAFar/6)
Changing the value manually in the input or selecting a value from the picker will set the value in the input, but it will be changed to 12:00AM on blur

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Xizario** [comment]
By default min and max of the TimePicker are the current day midnight. The TimePicker skips the date part. But the DateInput does not skip it, thus performing validation.
It would run if you set "max" different than the default:
http://dojo.telerik.com/ImAFar/9
