### ISSUE TITLE
k-window-content box-sizing changed between 2017 R1 and R2

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#3187]
Which in terms break certain layouts.

In addition, we override any nested 3rd party components with `.k-widget * {box-sizing: content-box}` and that breaks a lot more.

See if we can drop the box-sizing altogether...

TID: 1107379

**Comment by nstoychev** [comment]
This change also affect the window sizing when window is resized vertically: http://demos.telerik.com/kendo-ui/window/index.

**Comment by joneff** [comment]
Fixed by 10dd2beb1e016a3c43e3c26f08e88516cfcf867b
