### ISSUE TITLE
Change event triggered twice on kendo Autocomplete

### ISSUE THREAD

**Issue by mspace** [telerik/kendo-ui-core#3190]
### Current behavior

Running example available on: http://dojo.telerik.com/aWEjU

 ```
If I type input color 'b' and click on the next input, event 'change' is triggered twice
 <br />
 <input id="color" />
 <input />
     <script>
     $(document).ready(function() {
     $("#color").kendoAutoComplete({
       dataTextField: "text",
       dataValueField: "value",
       dataSource:  [
         { text: "Black", value: "1" },
         { text: "Orange", value: "2" },
         { text: "Grey", value: "3" }]
       });

       $("#color").on("change", function() {
         console.log("jQuery change");
       });                 
     });
</script>
```

### Expected/desired behavior

Correct would be that 'change' event is triggered only once, when autocomplete value is selected or not selected.

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** 1.12.3
* **Browser:** Chrome, Firefox

**Comment by zdravkov** [comment]
In such case we recommend using the [change ](http://docs.telerik.com/kendo-ui/api/javascript/ui/autocomplete#events-change) event of the control as for example it is done in this [dojo page](http://dojo.telerik.com/aWEjU/2).
