### ISSUE TITLE
Not preserved columns width during column reordering if there is a hidden column.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3198]
### Bug report

The columns width is not preserved during column reordering if there is a hidden column.

### Reproduction of the problem

The issue can be observed in the following example: http://dojo.telerik.com/iQUNo/5

### Environment

* **Browser:** [all]

**Comment by TsvetinaIvanova** [comment]
Also reported in ticket 1134582 .

**Comment by MilenaCh** [comment]
Columns reordering does not work in IE11 when destination and the column whose position should be changes are hidden.
Ex.: http://dojo.telerik.com/eMEnOxEd/2
