### ISSUE TITLE
Validation attributes are not added to editors for a nested property in UI for ASP.NET Core

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#3201]
### Reproduction of the problem
public class ProductViewModel
    { 
        [UIHint("ClientCategory")]
        public CategoryViewModel Category{get;set;}
...
public class CategoryViewModel
{
    [Required]
    public string CategoryName { get; set; }
}

**And the View:**
@model ProductViewModel

_data-val attributes are missing_ 
@Html.Kendo().TextBoxFor(m=>m.Category.CategoryName)

_data-val attributes correctly are present_
@Html.TextBoxFor(m=>m.Category.CategoryName) 

### Environment

* **Kendo UI version:** 2017.2.504

**Comment by ag-petrov** [comment]
There is a bug in the platform which prevents the rendering of the validation attributes. I have already reported it - https://github.com/aspnet/Mvc/issues/6862 .
