### ISSUE TITLE
DataSource TypeScript group option should accept any parameter

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#3203]
### Bug report

DataSource TypeScript `group` should accept `any` parameter to allow for a single object

### Reproduction of the problem/Current behavior

![image](https://cloud.githubusercontent.com/assets/10980842/26043903/811e719c-3949-11e7-9bcc-5b0711677af7.png)

### Expected/desired behavior

[http://docs.telerik.com/kendo-ui/api/javascript/data/datasource#configuration-group](url)

**Comment by frankieyan** [comment]
Hey Alex, I think it should be `DataSourceGroupItem | DataSourceGroupItem[]` so that type-checking can still take place. Thanks!
