### ISSUE TITLE
Issues, with the keyboard navigation of the MediaPlayer.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3207]
### Bug report

Issues, with the keyboard navigation of the MediaPlayer.

When a toolbar button(star pause) is clicked the space button is not pausing or starting the MediaPlayer.

Also, after a toolbar button is clicked, and the Enter is clicked the full-screen mode is active, but the enter key is now working as space.

Then if the window is minimised from the toolbar, the space button is working as enter.

### Reproduction of the problem

The issue can be observed in our demo: http://demos.telerik.com/kendo-ui/mediaplayer/keyboard-navigation

Also, please check the video demonstrating this: https://www.screencast.com/t/zpVJdD2f9xS

### Environment

* **Browser:** [all]

**Comment by ag-petrov** [comment]
The issues are now resolved, the fix will be included in the upcoming SP.
