### ISSUE TITLE
ng-style directive does not work when used in a grid template

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-ui-core#321]
reproduction here: http://dojo.telerik.com/efUG/2

problem comes from the fact that we pass an observable, which reaches the jQuery `css`  method.

![screen shot 2014-10-03 at 6 07 50 pm](https://cloud.githubusercontent.com/assets/13347/4507820/cbca8b34-4b0f-11e4-81cd-89569ac7a8e4.png)

which in turn calls our `forEach` with unexpected arguments (and maybe context). 

Currently, I don't have any concrete idea on how to fix that. @akorchev , @mishoo, perhaps you can come up with something?

**Comment by ag-petrov** [comment]
Calling toJSON is the way to go. The wrapped object have many properties that can error out.
