### ISSUE TITLE
Dragging a Scheduler event to the AllDaySlot and back changes the event's duration

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3211]
### Bug report
If an event is dragged from its view (Day or Week) timeslot to the AllDaySlot (without dropping it in the AllDaySlot), then back to a timeslot in the view, its duration is changed - the event's start and end time now have the same value. 

### Reproduction of the problem
[Screencast](https://www.screencast.com/t/76cr0RhAgDc).

### Current behavior
Dragging an event through the AllDaySlot (without dropping it) changes its duration.

### Expected/desired behavior
The dragged event's duration is not changed. 

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
After the fix, the dragged event jumps downwards away from the mouse, if the Scheduler timeslots are scrolled up while dragging to All Day row - [Video](https://www.screencast.com/t/LJjoKRR7Pi)
Steps to reproduce:
- Go to http://kendobuild-staging.openstack.progress.com/staging-kendo-ui/scheduler/index
- Scroll down the Scheduler in Work Week view to the bottom of the timeslots.
- Create an event from 9:00 PM to 9:30 PM.
- Drag the event slowly to All Day row - timeslots would scroll up upon dragging.
- Drag the event back away from the All Day row - the event will be away from the mouse downwards as much as the slots were scrolled up in the previous step
