### ISSUE TITLE
ListBox add event data e.items`s type is not Array?

### ISSUE THREAD

**Issue by nason-dev** [telerik/kendo-ui-core#3212]
### Bug report
http://docs.telerik.com/kendo-ui/api/javascript/ui/listbox#events-add
EVENT DATA
e.items Array
The item elements that are to be added.
e.dataItems Array
The data items that are to be added.

I test e.items is Object.
### Reproduction of the problem
_(bug report only)_
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via http://dojo.telerik.com or similar.

### Current behavior
_(optional)_
Provide additional information if the steps for reproducing the faulty behavior are not sufficient to describe the issue.

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by Xizario** [comment]
e.dataItems is array of data items.
e.items is array of html elements.
Both are arrays.
![image](https://user-images.githubusercontent.com/9458606/27023109-ba7cd958-4f59-11e7-8f35-0f2915077249.png)
