### ISSUE TITLE
Extend TypeScript definition of GridColumn command

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#3217]
### Bug report

The Kendo UI Grid column command accepts `string`, `string[]`, `object[]`. The TypeScript definition should reflect that.

[http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-columns.command](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-columns.command)

### Current behavior

![image](https://cloud.githubusercontent.com/assets/10980842/26154910/0546736c-3b1a-11e7-95f5-e0bfa9e310c3.png)

### Expected/desired behavior

```
command?: string | string[] |GridColumnCommandItem |GridColumnCommandItem[];
```
### Fix
[private link](https://github.com/telerik/kendo/blob/master/build/type_script.rb#L60)

**Comment by Stamo-Gochev** [comment]
The `text` property look correct in the latest version:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/kendo-ui/index.d.ts#L3772
