### ISSUE TITLE
ComboBox setOptions applies the new dataTextField and dataValueField, but the widget renders are undefined the fields.

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3218]
### Bug report

ComboBox setOptions applies the new dataTextField and dataValueField, but the widget renders as undefined the fields when a new data source is set.

### Reproduction of the problem

See the dojo example below: http://dojo.telerik.com/@nenchef/oSOFo

### Current behavior

Items in the dropdownlist are undefined. If you select a certain item, however, the correct text is displayed.

### Expected/desired behavior
Items in the dropdownlsit should be rendered with their proper text.

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** ALL

**Comment by Dimitar-Goshev** [comment]
I believe that there is a small mistake in the Dojo sample above. The button click handler should set newName as the new text field:

```
    $(".k-button").click(function(e){
       var combo = $("#combo").getKendoComboBox();
            combo.setOptions({ dataTextField: "newName" });
        	 combo.setDataSource(data1);
    })
```

**Comment by ghynx** [comment]
Changing the button click handler doesn't do the trick . 
Same behaviour when using 
  $(document).ready(function(e){
    $(".k-button").click(function(e){
         var combo = $("#combo").getKendoComboBox();
          combo.setOptions({ dataTextField: "newName" , dataValueField:"newId"});
       	 combo.setDataSource(data1);
    })

Why did you close this ?

**Comment by Dimitar-Goshev** [comment]
@ghynx I just added a comment that there is an error in the Dojo and the handler from the comment should be used for testing. I closed it because there is a fix applied in the source and setting new fields works. It will be released with R3 2017 SP1.

**Comment by ghynx** [comment]
@Dimitar-Goshev  : Ok thank's for the explanation.
