### ISSUE TITLE
ListView drag events could not be detected on Windows device with capactive touch screen in IE and Edge browsers.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-ui-core#3222]
### Bug report
The issue could be observed on the listview used for playlist of MediaPlayer:
http://demos.telerik.com/kendo-ui/mediaplayer/playlist

Load the demo in Windows device with capactive touch screen and try to scroll up/down playlist items using touch screen in IE/Edge.

**Comment by Stamo-Gochev** [comment]
The problem is no longer reproducible. https://github.com/telerik/kendo/commit/3adf5d84d257c15c33857984c87e1b3ce4f25b3e#diff-799e5f66298b307a2d0a2bc90a1daf0c
