### ISSUE TITLE
TreeList column attributes are not applied in edit mode.

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#3224]
### Bug report

[Column attributes](http://docs.telerik.com/kendo-ui/api/javascript/ui/treelist#configuration-columns.attributes) are not applied in edit mode of TreeList

### Reproduction of the problem
Set some column attributes, enable inline editing and open an item for edit. 

### Current behavior
The column attributes are overwritten.

### Expected/desired behavior
The column attributes should get applied to the respective cells.

### Environment

* **Browser:** [all]

**Comment by boyandim** [comment]
https://github.com/telerik/kendo/commit/c5e4ff2a80b2f712d95926989cbdf84da416c6ff

**Comment by boyandim** [comment]
https://github.com/telerik/kendo/commit/c5e4ff2a80b2f712d95926989cbdf84da416c6ff

**Comment by boyandim** [comment]
telerik/kendo#7149

**Comment by dbalinov** [comment]
Merge request: telerik/kendo#7149
