### ISSUE TITLE
kendo.version is incorrect when using NPM packages

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#3225]
### Reproduction of the problem
`console.log(kendo.version)`

### Current behavior
The output is "$KENDO_VERSION"

### Expected/desired behavior
The output should be the actual version, e.g. 2017.1.117

### Environment

* **Kendo UI version:** 2017.2

**Comment by Pavel-Durov** [comment]
Why was this issue closed?

I'm getting the same issue, running Windows & Ubuntu.

kendu version: 2017.3.1116
node: 8.9.1
npm: 5.5.1

**Comment by ivanchev** [comment]
Tested again with the example:
https://github.com/telerik/kendo-ui-npm-example/tree/master/javascript-webpack/pro

Works as expected. 

If you encounter any issues, please open a support ticket where we can investigate your project further

**Comment by Pavel-Durov** [comment]
Well, this example uses outdated webpack + webpack dev-server

When I modify the project to use latest dependencies:

>     "webpack": "^3.10.0",
>     "webpack-dev-server": "^2.10.0"

The Issue reproduces

**Comment by ivanchev** [comment]
I can confirm the issue is indeed fixed, even with the webpack versions you specified. Please keep in mind that since the issue was in the kendo code itself, the 2017.3.1116 version will always be broken. Try using our latest release - 2018.1.117
