### ISSUE TITLE
mapValueTo: "dataItem" option does not apply selection in the list 

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3227]
### Bug report

When using `mapValueOption: "dataItem"` the value is bound, but the same item in the list is not selected.

### Reproduction of the problem

Note that the following dojo only recreates the problem. Data is static and the valueMapper will always return the second item as selected.

http://dojo.telerik.com/IZEceZ

### Expected/desired behavior

The result to be the same as if `mapValueTo: "index"` is used.

http://dojo.telerik.com/EJefus

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** 1.12.3
* **Browser:** [all  ]

**Comment by mparvanov** [comment]
The selection is applied properly now. However, navigating with the keyboard down arrow key is not selecting the correct item but the first one.
