### ISSUE TITLE
InsertHtml inserts content at the top of the Editor content in IE

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#3230]
### Bug report
[DOJO](http://dojo.telerik.com/EqOZo)

### Reproduction of the problem

1. Type several lines in the editor
2. Type something
3. Press the custom tool in the editor

### Current behavior
$ symbol is inserted at the beginning of the content

### Expected/desired behavior
$ is inserted at the cursor position

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** IE

**Comment by mparvanov** [comment]
Raising the priority of this issue since it's reported by more users.

**Comment by IvanDanchev** [comment]
Raising priority to 3.

**Comment by SignASure** [comment]
Hi Ivan, Any updates for the above mentioned issue??

**Comment by IvanDanchev** [comment]
Consider the different behavior when calling the insertHtml method on DropDownList item selection, when the DropDownList's "filter" option is set and when it isn't: [dojo ](https://dojo.telerik.com/egAZIX) example. With filter set the new content is inserted at the beginning of the existing content.

**Comment by Iankodj** [comment]
The case with  the dropdownlist or combobox is that the focus (selection) is stolen from the content area. In IE, the browser does not keep the selection and thus when the editor is focused back on exec, the content area is selected at the beginning of the content. Therefore, the command is applied on this context. 

This can be prevented in the implementation of the custom tool—using getRange to cache the range before being stolen and using selectRange to restore it before calling the exec method. Here you are an example: https://dojo.telerik.com/uhuzusaW. 

As a result of this logged issue, the following article (https://docs.telerik.com/kendo-ui/controls/editors/editor/working-with-selection) will bve updated with the same information.
