### ISSUE TITLE
Focusing a textbox nested in Window does not highlight its text

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3244]
### Bug report

When a textbox nested in a modal Window is focused by pressing Tab its text is not highlighted. (**Regression**).

### Reproduction of the problem
[Dojo ](http://dojo.telerik.com/oJodo) example.

### Current behavior
The focused textbox' text is not highlighted. 

### Expected/desired behavior
The focused textbox' text is highlighted. 

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by wudifeixue** [comment]
Hi there is this problem fixed now? I can still reproduce the same thing with 2017.2.621, it works fine with 2017.1.223.
