### ISSUE TITLE
Resizing cell selection shows unstyled element which breaks the layout

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#3247]
### Reproduction of the problem

1) Go to http://demos.telerik.com/kendo-ui/spreadsheet/index
2) Make a selection
3) Using the right bottom corner resize the selection

At the top left corner of the cell-area, an unstyled element appears and breaks the layout - [VIDEO](https://www.screencast.com/t/BPxC9gB7UJTg)

Source: http://www.telerik.com/forums/display-issue-on-drag-cell(s)-with-right-bottom-anchor-point

**Comment by mvgmvg** [comment]
The issue has been fixed. Tested with the Kendo UI 2017.3.913 version
