### ISSUE TITLE
fix(grid): column reordering not working with @progress/kendo-theme-default

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#3250]
Based on customer report:

> The drag and drop column reordering does not work correctly. If I drag column 2 over column 3, the column reorder operation is not performed. However, the columnReorder event is still fired and indicates the correct old and new column index. The problem only exists when dragging from left to right. It works correctly when dragging from right to left. Also, using the older jQuery based themes, it works correctly either way.
> 
> http://dojo.telerik.com/ozowaG

Could be related to https://github.com/telerik/kendo-theme-default/issues/513
 (TID: 1110535)

**Comment by matanasov** [comment]
Does not replicate in R3 2018 (2018.3.911)
