### ISSUE TITLE
Window resizes incorrectly when its container has margin-top set

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3257]
### Bug report

When resized in vertical direction the Window will initially resize with the value of the container's margin instead of following the mouse cursor. 

### Reproduction of the problem
[Dojo ](http://dojo.telerik.com/ociVeG) example. [Screencast](https://www.screencast.com/t/uYerNOUzjsp).

### Current behavior
Incorrect/unexpected resizing behavior.

### Expected/desired behavior
Resizing behavior is independent of the container's margin value. 

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by nstoychev** [comment]
Not reproducible with the latest version of Kendo UI.
