### ISSUE TITLE
Wrong checkbox appearance in different states (hover/focus/checked/unchecked)

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-ui-core#3259]
### Reproduction of the problem

1. Open the following Dojo samle: http://dojo.telerik.com/acuDo
2. Hover the checked checkbox
For more detailed information, see ticket with ID 1110883.

All states should be reviewed and compared with designed appearance.

### Current behavior
 Checked state of border is replaced by hover state border

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
Still there is difference between expected and actual appearance on hovering a checked checkbox in Default v2 theme:
![image](https://user-images.githubusercontent.com/6614183/28823353-c3d29108-76c5-11e7-8d86-c4d63054c6ac.png)
