### ISSUE TITLE
Broken layout of Editor's Image/File Browser dialog toolbar, if font-size is not 12px in all LESS themes

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3266]
### Bug report
The toolbar of the Image and File Browser dialog has broken layout with different than 12px font-size. 

### Reproduction of the problem

http://dojo.telerik.com/EjOjac

Open the Image Browser dialog.

### Current behavior

http://dojo.telerik.com/EjOjac
![image](https://cloud.githubusercontent.com/assets/4222379/26543015/d6e27ac6-4464-11e7-811f-a61f482980c2.png)

### Expected/desired behavior

![image](https://cloud.githubusercontent.com/assets/4222379/26543028/e5bf7080-4464-11e7-8fbf-f16f8a1816d0.png)

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The issues are reproducible in all LESS themes. After the fix there are several remaining issues:
- Displaced buttons in Nova theme
![image](https://user-images.githubusercontent.com/6614183/28821811-988f66de-76bf-11e7-9706-550279d5450e.png)

- Upload + icon is displaced downwards in all themes (check the image below);
- Search icon in the searchbox is displaced in all themes (check the image below);
- "Arrange by" dropdown width does not change and its content is cut (check the image below);
![image](https://user-images.githubusercontent.com/6614183/28821889-e2516150-76bf-11e7-8305-2d6a010bf74f.png)

- A probable issue in Default v2 - Upload and New folder button do not become bigger, when font size of the toolbar is increased. In contrast, the "Arrange by" dropdown becomes bigger.
![image](https://user-images.githubusercontent.com/6614183/28821967-294250ec-76c0-11e7-8db3-d32fa6e3c85f.png)

**Comment by mvgmvg** [comment]
The issue in Default v2 theme is caused because font-size in the sample is customized only for .k-widget element. The same custom font-size should be set also for .k-button element.
