### ISSUE TITLE
Filtering is not working with Turkish localization

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#3268]
### Bug report

[http://dojo.telerik.com/@jivanova/UZufOF](http://dojo.telerik.com/@jivanova/UZufOF)

The issue is reproducible when uppercase ıtems are set in the combo and try to filter with lowercase.

### Reproduction of the problem

1. Switch to turkish language
2. Type: kız

### Current behavior
NO DATA displayed

### Expected/desired behavior
KIZILTOPRAK displayed.

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** all

**Comment by yasirersoy** [comment]
http://dojo.telerik.com/eVIRUs

**Comment by Dimitar-Goshev** [comment]
This issue will be resolved in R2 2019 release with the introduction of a new DataSource property - **_accentFoldingFiltering_** , which will need to be set for this type of filtering to work properly.
