### ISSUE TITLE
The filter menu of the columnMenu is closed sometimes when an element inside the filterMenu is clicked (Chrome).

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3269]
### Bug report

The filter menu of the columnMenu is closed sometimes when an element inside the filterMenu is clicked (Chrome). From additional tests, it looks like, at some point, the click is registered over a Grid cell instead of the filterMenu.

### Reproduction of the problem

The issue can be reproduced in our demo, but it not occurs on every click, it may take 5 or 50 clicks: demos.telerik.com/kendo-ui/grid/column-menu

Also, the may be connected to the isPopupMouseLeaved function of the kendo.menu.js.

### Environment

* **Browser:** [Chrome ]

**Comment by simonssspirit** [comment]
Additional information for the issue can be found in ticket: 1111350

**Comment by MilenaCh** [comment]
The issue could not be replicated with 2018.1.221 version of KendoUI and the current Chrome version(65.0.3325).
