### ISSUE TITLE
Menu dropdown menus appear off screen on Chrome for Android

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3272]
### Bug report

On Chrome for Android the Menu dropdown menus do not position according to the available space and expands the screen.

Works as expected in the desktop version of Chrome. 

### Reproduction of the problem

The described behavior can be observed in [this Dojo](http://dojo.telerik.com/Unohi)

* Click on the rightmost subitem (user icon)

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** [Mobile Chrome]

**Comment by Iankodj** [comment]
In mobile devices there is a meta tag that should be included in the HTML page for the view port to behave normally and not get stretched by absolutely positioned elements (popups, dialogs and so on). 

```html
<meta name="viewport" content="width=device-width,user-scalable=1,initial-scale=1.0">
```

Adding this meta tag in the head element of the application will resolve the problem. Plus, render the size of the HTML elements properly according to the view port of the device. http://dojo.telerik.com/Unohi/4. 

More information about why using this meta tag is recommended can be found in MDN:  https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag.
