### ISSUE TITLE
Notifications overlaps on Android with specific font customization

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3277]
### Bug report

Notifications overlap when custom font-family is set and font-size less than 16px. Can be reproduced on Chrome for Android native only.

### Reproduction of the problem

* Go to [the following Dojo](http://dojo.telerik.com/ubAVO/18)
* Click on the warning notification button
* Click on the error notification button

You will notice that the notifications are overlapping.

![overlapping_notifications](https://cloud.githubusercontent.com/assets/16972160/26630550/dc30c3be-460f-11e7-8536-451cbb34e33f.png)

### Expected/desired behavior

Setting font-family and font-size should not affect the positioning of the notifications.

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** [Chrome for Android (native)]

**Comment by Dimitar-Goshev** [comment]
On mobile devices, Kendo UI requires the usage of the following meta tag for proper appearance:
`<meta name="viewport" content="width=device-width, initial-scale=1" />`

The issue is not reproducible, when the respective meta tag is used:
http://dojo.telerik.com/OCOXALIV/2
