### ISSUE TITLE
ColorPickers' input is not editable

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3281]
### Bug report

When the Color Picker of the Kendo Editor foreground or background tool is configured with the default HEX palette the input field is not editable. 

### Reproduction of the problem

http://dojo.telerik.com/AduKad

### Workaround

http://dojo.telerik.com/iJUmE

Removing the original open handler of the color pickers and assigning new handlers that does not prevent the mousedown event for the input elements. 

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** 1.12.3
* **Browser:** [all ]

**Comment by dung-np** [comment]
Doesn't work on all versions of IE.

**Comment by mparvanov** [comment]
The issue is reproducible with latest internal scripts in Internet Explorer 11:
http://kendobuild-staging.openstack.progress.com/dojo-staging/EDiwUQUl

**Comment by Iankodj** [comment]
The last commit includes a minor enhancements that enables to store the editor range when clicking inside the input. That way, when changed value is applied, the selection is restored and the formatting is applied to the correct selection.
