### ISSUE TITLE
Multi check filter to work with null values

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-ui-core#3284]
It should add IsNull instead of ==null in the query.
Based on this request:
http://www.telerik.com/forums/multi-filter-with-null-values---they-are-not-visible

**Comment by Xizario** [comment]
Priority changed based on 1123840

**Comment by matanasov** [comment]
@ag-petrov 
Add the same logic for `number` and `date` types.

Please also review this client scenario:
http://dojo.telerik.com/udOjE

**Comment by ag-petrov** [comment]
[Here](http://dojo.telerik.com/udOjE/7) is a working dojo.

**Comment by Xizario** [comment]
@ag-petrov , but now if you clear the filter, it shill show "Null" in the dropdownlist.

**Comment by ag-petrov** [comment]
Indeed I only wanted to illustrate that the values in the dropdowns match after filtering. When stripping the code I have removed the empty item. Later I will post an example with an empty item. Have in mind that the above linked dojo needs additional stripping of the logic.

**Comment by matanasov** [comment]
@ag-petrov  Just a reminder about:
"Later I will post an example with an empty item. Have in mind that the above linked dojo needs additional stripping of the logic."
