### ISSUE TITLE
Unable to navigate out of Spreadsheet view by keyboard

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3285]
### Bug report

The Spreadsheet provides accessibility support and keybord shortcuts for navigation. However, there is no keyboard shortcut to navigate out of the view. 

### Reproduction of the problem

http://demos.telerik.com/aspnet-mvc/spreadsheet/index

1. Focus the spreadsheet ;
1. Try navigating out of the Spreadsheet with the keyboard

### Current behavior
Focus is trapped in the Spreadsheet. The mouse is the only alternative. 

### Expected/desired behavior
Keyboard shortcuts to navigate out of the Spreadsheet.

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by veselints** [comment]
Pressing Shft+Esc is now implemented to navigate outside of the Spreadsheet. It will focus the very next focusable element. Also, when the last cell is focused (the cell on the last row and the last column), pressing Tab will move the focus to the next focusable element on the page. Moreover, if the first cell is focused (the cell on the first row in the first column), pressing Shft+Tab will move the focus to the Formula Input, the second Shft+Tab will move the focus to the Ranges Combo and so on back to the Spreadsheet Toolbar tools.

**Comment by Dimitar-Goshev** [comment]
@veselints There is a JS error on pressing Shift + Tab after loading the Basic usage demo without clicking on any Spreadsheet cell. The same issue is reproducible on creating a new sheet and pressing Shift + Tab .
Uncaught TypeError: Cannot read property 'element' of undefined

**Comment by Dimitar-Goshev** [comment]
The error is resolved.
The logic for Tab and Shift+Tab does not take into account if there is a selected range.

For a range A1:C3 Shift+Tab should move the selected cell inside the range. But when A1 is reached, Shift+Tab does not move the selected cell to the bottom right cell of the range.

Similarly, for a range containing the bottom right cell of a sheet Tab should move the selected cell inside the range to its top left cell. But when the bottom right cell is reached, Tab moves the focus outside the Spreadsheet.
