### ISSUE TITLE
ListBox draggable settings are not serialized correctly  for MVC wrappers

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#3286]
### Bug report

The dragglabe is serialized as dragglable: { "enabled": false } which will intialize the draggable but prevent the drag. 

### Current behavior
By default dragglable: { "enabled": false } is serialized from the server.

### Expected/desired behavior
Nothing should be serialized.

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by theOrlin** [comment]
Reported in ticket 1112400

**Comment by ag-petrov** [comment]
https://github.com/telerik/kendo/commit/643a6395e8f7f8b50b9a2240ccfc8749010b2e09
