### ISSUE TITLE
When autoScroll is enabled hint is not shown above the first item

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#3289]
### Reproduction of the problem
1. Run [this example](http://dojo.telerik.com/ULuso/28).
2. Scroll the list down a bit
3. Try to drag an item to the first place

### Current behavior
Current behavior is shown in [this video](https://www.screencast.com/t/W07hSmYTF).

### Expected/desired behavior
The hint should be displayed before the first item

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** 1.12
* **Browser:** [Chrome ]

**Comment by dmanova** [comment]
The provided example has 2 issues:
1. It is not scrolled when "autoScroll: true" is used.
2. When moving something at the top (above the first item) its hint is not shown the same way as when no scrolling is used. Check the new video to compare:
![SortableShowHintOnTop](https://user-images.githubusercontent.com/52446546/111795824-380ec800-88d0-11eb-8ebd-fe87205f473c.gif)

**Comment by ag-petrov** [comment]
QAs should write a test for this scenario.
