### ISSUE TITLE
When an input element is focused, the Grid will not receive the focus when clicked, and the keyboard navigation is not working.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3291]
### Bug report

When an input element is focused, the Grid will not receive the focus when clicked, and the keyboard navigation is not working.

### Reproduction of the problem

The issue can be reproduced in the following Dojo: http://dojo.telerik.com/aSEcIh/6

### Environment

* **Browser:** [all]

**Comment by simonssspirit** [comment]
Reported again in: 1123433

**Comment by TsvetinaIvanova** [comment]
Similar problem reported in 1123687.
