### ISSUE TITLE
Unclickable Template Checkboxes in TreeView 

### ISSUE THREAD

**Issue by theOrlin** [telerik/kendo-ui-core#3292]
The checkboxes created by a template in the TreeView appear unclickable in the latest version.

See dojo (current version): http://dojo.telerik.com/OyujI/11
Compare with dojo (previous version): http://dojo.telerik.com/OyujI/9

When clicking on the item label, the checkbox gets checked/unchecked as expected. When clicking the checkbox itself, it does not.

Look at the console when clicking on the checkbox. The checkbox input element is clicked twice in the latest version as opposed to once in the previous version.

Suspected culprit: https://github.com/telerik/kendo/blob/master/src/kendo.treeview.js#L295-L297

Reported in ticket 1111976

**Comment by Iankodj** [comment]
There is also a a JS error:  Cannot read property 'click' of null.
