### ISSUE TITLE
Kendo loader does not hide after successfully deleting an image or deleting / creating a new folder in Editor's Insert image dialog

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3293]
### Bug report
The Kendo loader does not hide after successfully deleting an image or creating a new folder in the Insert image dialog.

### Reproduction of the problem
* Go to [File and image browser demo](http://demos.telerik.com/kendo-ui/editor/imagebrowser);
* Click on the Image browser icon to open the Insert image dialog;
* Select an image and click the delete button;
* Confirm that you whant to delete that image;
* The delete request is executed appropriately, but the loader does not hide;
* The same occurs after creating a new folder and hittong enter;

### Expected/desired behavior
The loader should be hidden after successfully executing the above actions.

**Comment by veselints** [comment]
A possible workarownd is to attach an event handler for the jQuery [ajaxSuccess event](http://api.jquery.com/ajaxsuccess/) and manually remove the loader:

````JavaScript
$( document ).ajaxSuccess(function( event, xhr, settings ) {
  // Check for the correct url, that returns success
  if ( settings.url == "http://demos.telerik.com/kendo-ui/service/ImageBrowser/Destroy" ) {
    $('.k-imagebrowser>.k-listview>.k-loading-mask').remove();
  }
});
````

**Comment by veselints** [comment]
Also reported in [Ticket ID: 1114090](https://admin.telerik.com/?Context=Support&Control=~%2fUserControls%2fSupport%2fThreadReply.ascx&ST=1114090&SM=0)

**Comment by veselints** [comment]
Also reported in Ticket ID: 1123954

**Comment by veselints** [comment]
Reopening as it can be reproduced in R3 2018 1017:
* Go to https://demos.telerik.com/kendo-ui/editor/imagebrowser
* Open the File/Image browser window and upload an image.
* Try to create a new folder or delete one of the pre-existing images.
* Loading animation hangs.

**Comment by nisha11shahi** [comment]
I'm working on ASP.NET MVC Project. Where should I attach that event handler?
