### ISSUE TITLE
The cursor is moved from the current position when clicking on a menu item in IE

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#3298]
### Bug report

The cursor is moved from the current position when clicking on a menu item. The issue could be observed when inserting text into the editor component content area through menu item click. In IE, choosing a menu item inserts the text at the start of the content area and not where the cursor is.

### Reproduction of the problem
1. Open the following sample in IE: http://dojo.telerik.com/@parvanov/uZumo
2. Place the cursor somewhere in the editor content area 
3. Click on any menu item E.G. "First Item"

### Current behavior
The text is pasted at the beginning of the content area

### Expected/desired behavior
The text is pasted at the cursor position

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** [Internet Explorer] 

Note: The issue starts to appear after the following commit: 
https://github.com/telerik/kendo-ui-core/commit/791c93a78cecb121f78f858fb786dd3042cc8acc
(https://github.com/telerik/kendo/commit/288d941583684c4be3f788e5bea4e7e6dcddb88b)

**Comment by nstoychev** [comment]
It is expected editor's selection to be changed when clicking outside the editor in Internet Explorer. To resolve it, handle pointerdown event of the menu items or the whole menu if there are not any links and call event.preventDefault() function.
```
<script>
    $("#menu").on("pointerdown", function(e){
        e.preventDefault();
    });
</script>
```
