### ISSUE TITLE
"Maximum call stack size exceeded" error thrown by the HierarchicalDataSource with remote data and client-side filtering

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3300]
### Bug report
"Maximum call stack size exceeded" error thrown by the HierarchicalDataSource when the data source is filtered client-side.

**NOTE:** The bug is regarding a scenario, where the **serverFiltlering** is set to **false** (!the default ServerFiltlering value is false). In case you have the **serverFIltering** set to true and you experience this issue - we already have this issue fixed: [https://github.com/telerik/kendo-ui-core/issues/3208](https://github.com/telerik/kendo-ui-core/issues/3208)

### Reproduction of the problem
http://dojo.telerik.com/awURI

### Current behavior
"Maximum call stack size exceeded"

### Expected/desired behavior
No error

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** [all]

**Comment by veselints** [comment]
Also reported in Ticket ID: 1114715

**Comment by cjlint-hl** [comment]
This bug is very high priority for us, is there any patch or internal build that will fix this issue? We tried applying this commit: https://github.com/telerik/kendo-ui-core/commit/ce145f15eda26555525bf62afc1b18fc5effe818 however it does not fix the issue.

**Comment by zdravkov** [comment]
If you are using **serverFiltering** this is the [commit](https://github.com/telerik/kendo-ui-core/commit/1c25b665a3af2211f861c5594588864dfb99a622#diff-e4227ae6b20f4e387c12827a321f0d08) that is fixing the [issue](https://github.com/telerik/kendo-ui-core/issues/3208).
