### ISSUE TITLE
FontName value disappears once a not common font-family is chosen 

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#3301]
### Bug report

[DOJO](http://dojo.telerik.com/@jivanova/IGEZur/3) - Chrome 58.0.3029.110 Windows 10 machine or under iOS

### Reproduction of the problem

1. Choose "Book Antiqua" at the beginning of the content area

### Current behavior
Font name dropdown is empty

### Expected/desired behavior
Font name dropdown show the corresponding value

### Environment

* **Kendo UI version:** 2017.2.504
* **jQuery version:** ^1.2.1
* **Browser:** Chrome 58.0.3029.110 Windows 10

**Comment by Iankodj** [comment]
Under Chrome latest version this is not reproducible anymore. 

As of iOS, the selected value in the dropdown depends on the value returned by the browser. In this case, changing the value in order to unify the one returned under iOS will fix the problem: 

```js
...
{ text: "Book Antiqua", value: '"Book Antiqua"' },
...
```
