### ISSUE TITLE
JS error thrown on clicking Cut/Copy/Paste buttons of Spreadsheet's toolbar or context menu, when Spreadsheet's content is loaded using .fromJSON() method

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3302]
### Bug report
The Spreadsheet Toolbar and Context menu Cut/Copy/Paste button click throws *"Cannot read property 'clipboard' of undefined"* error, when the content of the Spreadsheet is loaded using .fromJSON() method. In FF the error is reported as *"this._workbook._view is undefined"*.

NOTE: Cut/Copy commands are working as expected with keyboard shortcuts.

### Reproduction of the problem
1. Go to the following [Dojo](https://dojo.telerik.com/OdACoMij);
1. Select a random cell in the Spreadsheet;
1. Click on the *Cut*/*Copy* button on the Spreadsheet toolbar/context menu;

### Current behavior
*Cannot read property 'clipboard' of undefined* error will be reported on the console;

### Expected/desired behavior
No error and content is copied.

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by dasaevc** [comment]
What I made to workaround this was

`kendoSpreadSheetInstance.fromJSON(theJSON);`
`kendoSpreadSheetInstance._workbook._view = kendoSpreadSheetInstance._view;`
