### ISSUE TITLE
Spreadsheet Redo does not behave properly

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3304]
### Bug report
The Spreadsheet Redo command does not behave properly. It retrieves from the clipboard only the last executed action.

### Reproduction of the problem
* Go to the [Spreadsheet Index Demo](http://demos.telerik.com/kendo-ui/spreadsheet/index);
* Select B7 cell and press Ctrl + C to copy it;
* Select the C7 cell and press Ctrl + V to paste the copied cell;
* Select the B8 cell and press Ctrl + C to copy it;
* Select the C8 cell and press Ctrl + V to paste the copied cell;
* Press Ctrl + Z or the Undo button on the Spreadsheet Toolbar three times. This will remove the pasted cells and will keep the focus on the C7 cell;
* Press Ctrl + Y or the Redo button. This will paste the B8 cell (the last copied) on the C7 cell. This, however, is not the correct state, as the pasted content in C7 should be the one from B7;

### Expected/desired behavior
The Redo button (Ctrl + Y) should properly restore the previous state of the Spreadsheet;

**Comment by Dimitar-Goshev** [comment]
Also the issue is reproducible when copy/paste from external source, not only when copying from spreadsheet cells. Make sure to test such scenarios as well, when testing a fix for the issue.

**Comment by Juveniel** [comment]
In addition to the above, when pasting mutiple cells from Excel, pressing Ctrl + Z only undo the first cell only. Reproducible in the [Basic Usage Demo](https://demos.telerik.com/aspnet-mvc/spreadsheet).

**Comment by nenchef** [comment]
Another reproduction of the problem (reported in TicketID: 133308):
1. Enter values in the cells from A1-D1
2. Update each cell value by just changing the Active cell (using Tab) and not removing the range selection. (e.g 1,2,3,4)
3. Click somewhere else in the sheet to bring selection on some other cell.
4. Now press Ctrl+Z 4 times(once for each cell) to undo the changes in the cells we made.
5. Select the range A1-D1 again and change the active cell to be C1 (using Tab)
6. Now press Ctrl+Y 4 times

Result demonstrated in this video: [https://monosnap.com/file/i2iD2wbR1qapwmJ3mjipo8EK2ziB5X](https://monosnap.com/file/i2iD2wbR1qapwmJ3mjipo8EK2ziB5X)
Priority of the bug increased
