### ISSUE TITLE
Spreadsheet server-side import does not hide columns that are hidden in the source file

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3310]
[TestFile.zip](https://github.com/telerik/kendo-ui-core/files/1067429/TestFile.zip)
### Bug report

Related and fixed with #4462

Spreadsheet server-side import does not hide columns that are hidden in the source file. The issue is replicable only with a large file. The issue seems to originate either from the Load method of the namespace Telerik.Web.Spreadsheet or from the workbook.ToJson().

### Reproduction of the problem
The problem is replicable with our online demos:
[https://demos.telerik.com/aspnet-mvc/spreadsheet/server-side-import-export](
https://demos.telerik.com/aspnet-mvc/spreadsheet/server-side-import-export)

Test the problematic behaviour with the attached file above (Telerik Test)

### Current behaviour
The defined columns as hidden from the source file are displayed, once the workbook is loaded into the spreadsheet.

### Expected/desired behavior
The hidden columns should remain hidden.
### Environment

* **Kendo UI version:** 2017.2.504

* **Browser:** ALL

**Comment by Dimitar-Goshev** [comment]
Another scenario to reproduce the issue:

### Bug report
Hidden column is exported to JSON with width 0.0 . But when the same exported JSON is imported to the Spreadsheet, the column is not hidden. If the respective sheet is exported again to JSON, the column, which is expected to be with width 0.0 is missing.

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/spreadsheet/server-side-import-export
2. Hide column B.
3. Export to JSON:
```
            "columns": [
                {
                    "index": 0,
                    "width": 280.0
                },
                {
                    "index": 1,
                    "width": 0.0
                },
                {
                    "index": 2,
                    "width": 120.0
                },
                {
                    "index": 3,
                    "width": 120.0
                }
            ],
```
4. Import the exported JSON - column B is NOT hidden.
5. Export to JSON again - column with index 1 is missing:
```
            "columns": [
                {
                    "index": 0,
                    "width": 280.0
                },
                {
                    "index": 2,
                    "width": 120.0
                },
                {
                    "index": 3,
                    "width": 120.0
                }
            ],
```

### Current behavior
Hidden column is NOT hidden, when imported from JSON.

### Expected/desired behavior
Hidden column IS hidden, when imported from JSON.

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]
