### ISSUE TITLE
The Spreadsheet AGGREGATE function does not ignore hidden values when rows are hidden using filter

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3312]
### Bug report
The Spreadsheet AGGREGATE function does not ignore hidden values when rows are hidden using a filter.

The following function '=AGGREGATE(1, 5, C4:C11)' should result in ignored hidden cell values. The second number (in this case 5) specifies which values should be ignored [DOCS HERE](https://support.office.com/en-us/article/AGGREGATE-function-43b9278e-6aa7-4f17-92b6-e19993fa26df). The result, however, does not ignore values, that are hidden because a filter has been applied to a column.

### Current behavior
The function '=AGGREGATE(1, 5, C4:C11)' should always ignore hidden cell values.

**Comment by mishoo** [comment]
It seems to work fine when rows are hidden manually (i.e. the value changes after you hide rows).  With filtering, the problem is that applying/clearing a filter did not trigger a recalculation.  I fixed that.
