### ISSUE TITLE
Item does not expand when the item is filtered in loadOnDemand="true" scenario

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#3313]
### Bug report

Item does not expand when the item is filtered in **loadOnDemand="true"** scenario

### Reproduction of the problem

1. Go to: http://demos.telerik.com/kendo-ui/treeview/api
2. Click the “Edit this example” blue button at the top right of the page.  A new page will load and is divided into two sections.
3. In the “Choose Library” drop down menu, select Kendo UI 2017 R2*
4. In the section on the left, scroll down and find the declaration of the treeview object.  Change the property loadOnDemand from false to true.
5. Click the blue Run button.
6. In the right section, collapse the Item 1 tree node.
7. Click the “FILTER BY TEXT” button.
8. Item 1 node should be all that is shown in the tree view.  Click Item 1 to expand the node and view the child nodes.  

### Current behavior
You are unable to expand this tree node to view the child nodes for Item 1.

### Expected/desired behavior
You are able to expand this tree node to view the child nodes for Item 1.

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** [all]

**Comment by veselints** [comment]
Also reported in [Ticket ID: 1163561](https://admin.telerik.com/default.aspx?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1163561)
