### ISSUE TITLE
Increase Slider click area in LESS Fiori, Material, Material Black, Nova, Office 365 and SASS Default-v2, Bootstrap-v4 and Material-v2 themes

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-ui-core#3318]
### Bug report
 Slider track is hard to click n LESS Fiori, Material, Material Black, Nova, Office 365 and SASS Default-v2, Bootstrap-v4 and Material-v2 themes

### Reproduction of the problem
Open http://demos.telerik.com/kendo-ui/colorpicker/index with one of the themes listed above and try to change the color by clicking on the slider.

### Current behavior
Slider's track active zone is small and hard to click:
![slider](https://user-images.githubusercontent.com/1118895/27084393-6e955640-5054-11e7-939b-276297327a47.png)

### Expected/desired behavior
The hot area must be larger (at least not less than the height of the drag handle):
![slider-larger](https://user-images.githubusercontent.com/1118895/27084414-84dbc29a-5054-11e7-9bcf-59ca0c093f65.png)

### Environment
* **Kendo UI version:** 2019.2.619
* **jQuery version:** all
* **Browser:** all

**Comment by lkarakoleva** [comment]
The hit zone of the slider track should be increased in the following themes as well:

**LESS**
- Fiori;
- Material Black;
- Nova;
- Office 365

**SASS**
- Default v2;
- Bootstrap v4;

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
If changes in SASS themes are needed, log an issue in [kendo-themes](https://github.com/telerik/kendo-themes/issues)
