### ISSUE TITLE
Keep all values available in the column filter menu, even if filter by value has been already applied

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3319]
Currently, after filtering a column by value, when the filter menu is opened again, the available value options are only those, which have been already selected (checked):
![2017-06-14_1121](https://user-images.githubusercontent.com/3431388/27122595-e199b9de-50f3-11e7-9682-d0998c5f602c.png)

Excel in this case behaves differently and displays all the available values in the column (selected and not):
![excel](https://user-images.githubusercontent.com/3431388/27122612-e9972b9e-50f3-11e7-8ac9-202b3b89e8c5.png)

The suggestion is to keep the Excel behavior in the Kendo Spreadsheet too.

**Comment by jivanova** [comment]
Fix in: https://github.com/telerik/kendo-ui-core/issues/1797
