### ISSUE TITLE
Display all items after removing filtering for the Spreadsheet

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3320]
### Bug report
Currently, Kendo Spreadsheet does not display all available values after the filtering has been removed from the Spreadsheet.

### Reproduction of the problem
* Go to [Sorting and Filtering demo](https://demos.telerik.com/kendo-ui/spreadsheet/sorting-filtering);
* Filter any column from second to last by any condition/value; **(the issue is not reproducible with the first column)**
* Click on the Filter button on the Spreadsheet Toolbar to remove all filters;

### Current behavior
The displayed data will remain filtered;

### Expected/desired behavior
The MS Excel behavior differs in this case. When the filter has been removed, it displays all available items in the Worksheet. In does not keep filtering. The suggestion is to keep the same behavior in the Spreadsheet as the one in Excel.

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by mishoo** [comment]
No longer reproducible.

**Comment by Dimitar-Goshev** [comment]
Reproducible with all columns, except the first one. I updated the issue's description.
