### ISSUE TITLE
fix: do not enforce box-sizing: content-box

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#3325]
The less themes enforce `box-sizing: border-box` to child components and that tends to break bootstrap and similar child components.

TID: 1114098, 1124709

**Comment by Juveniel** [comment]
Also reported in TID with a related issue: 1123999

Kendo UI for MVC scaffolder generates the box-sizing-fixes.css above the Kendo UI styles, although in the [documentation](http://docs.telerik.com/kendo-ui/third-party/using-kendo-with-twitter-bootstrap) is stated that the fix should be referenced after Bootstrap and Kendo UI styles.

![image](https://user-images.githubusercontent.com/16972160/29119397-a769642a-7d0e-11e7-91e7-5a9b0d07acb9.png)

**Comment by nelito987** [comment]
Reported in ticket ID: 1485831
