### ISSUE TITLE
Grid Metro theme pager buttons icons disappear on hover 

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3327]
### Bug report

Grid Metro theme pager buttons( "Go to the first page" or "Go to the previous page") icons disappear on hover.

### Reproduction of the problem

1. http://demos.telerik.com/kendo-ui/grid/index
2. Change Theme -> Metro
3. Hover "Go to the first page" or "Go to the previous page" buttons

### Current behavior

Icons disappear.

### Expected/desired behavior

Icons are visible.

### Environment

* **Kendo UI version:** 2017.2 504
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by TeyaVes** [comment]
The following bug has been fixed by the following commit from a year ago: https://github.com/telerik/kendo/commit/157765b424127096f5888fa6454f050e0f77a284 and is no longer reproducible
