### ISSUE TITLE
Editor PDF export to a new window not working 

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3332]
### Bug report

Editor exports PDF in new browser tab with forced proxy and proxyTarget: "_blank". However, if the he "Content-Disposition" header is set to inline; filename="<fileName.pdf>", the file is not being opened in a new window.

### Reproduction of the problem

The behavior can be reproduced with the following solution: 
[TelerikMvcAppEditorExport.zip](https://github.com/telerik/kendo-ui-core/files/2383825/TelerikMvcAppEditorExport.zip)

### Expected/desired behavior

Editor configured with proxyTarget: "_blank" should export the document in a new window if the "Content-Disposition" header is set to inline; filename="<fileName.pdf>".
### Environment

* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by mparvanov** [comment]
The issue is not reproducible with R1 2019.
