### ISSUE TITLE
Allow the Spreadsheet Copy - Paste of only values (no formatting) from Excel

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3336]
Allow the Spreadsheet Copy - Paste only values (no formatting) from Excel. Currently only Copy - Paste of both values and formatting is supported.

Related to #4091

**Comment by veselints** [comment]
The suggestion could be implemented with a configuration property and change in the 'parse()' method:
```JavaScript
parse: function () {
	var state = newState();
	if (this._isInternal()) {
		state = this._internalContent;
	} else {
		var data = this._externalContent;
                // Here could be the check of the new property (pasteClearFormatting)
		if (!this.isExternal() && !this.pasteClearFormatting && data.html) {
			var doc = this.iframe.contentWindow.document;
			doc.open();
			doc.write(data.html);
			doc.close();
			var table = $(doc).find('table:first');
			if (table.length) {
				state = parseHTML(table);
			} else {
				state = parseTSV(data.plain);
			}
		} else {
			state = parseTSV(data.plain);
		}
		this.origin = state.origRef;
	}
	this._content = state;
}
````

**Comment by veselints** [comment]
Related to #3361

**Comment by Dimitar-Goshev** [comment]
Currently pasting values only is available in Chrome by pasting using Ctrl + Shift + V keyboard shortcut.

**Comment by veselints** [comment]
A possible workaround for this issue would be to override the `Clipboard.paste` method:
````JavaScript
kendo.spreadsheet.Clipboard.prototype.paste = function() {
  var sheet = this.workbook.activeSheet();
  var pasteRef = this.pasteRef();
  var content = this._content;
  
  content.data = stripData(content.data);
  sheet.range(pasteRef).setState(content, this);
  sheet.triggerChange({ recalc: true, ref: pasteRef });
}
````

**Comment by Juveniel** [comment]
The previously provided workaround does not work with the latest version (2018.3.1017). A temporary solution with the specified version could be found on the following Dojo:

[http://dojo.telerik.com/eVuzIdEs/6](http://dojo.telerik.com/eVuzIdEs/6)

**Comment by veselints** [comment]
The newly exposed `paste` event handler allows you to manipulate the pasted content and populate only the respective values in the Spreadsheet. Here you could find an article on how to do that: https://docs.telerik.com/kendo-ui/knowledge-base/spreadsheet-paste-only-values
