### ISSUE TITLE
Spreadsheet is missing an indication icon when columns are being resized

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3340]
### Bug report

When resizing columns in the spreadsheet, the dragging indication icon is missing (Sass themes only).

### Reproduction of the problem

The behavior can be observed in [the following Plunker](https://plnkr.co/edit/g09PsITM6jJKdvdc9JC9).

### Expected/desired behavior

An indication icon should appear when resizing(dragging) the spreadsheet columns.

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** [all]

**Comment by mparvanov** [comment]
The issue is not reproducible with v 2019.3.917.
