### ISSUE TITLE
Virtualized ComboBox' last portion of items not visible when itemHeight is over 33px and items count over 100k (in IE11 only)

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3343]
[sample.zip](https://github.com/telerik/kendo-ui-core/files/1097971/sample.zip)
### Bug report

Virtualized ComboBox' last portion of items not visible when itemHeight is over 33px and items count over 100k

### Reproduction of the problem

Use the attached project. When the ComboBox loads, scroll to the bottom of the list.
If you initially scroll the scrollbar a bit and load some portions of the items - the last portion will be visible.

### Current behavior
The last portion of items is not visible

### Expected/desired behavior
The last portion of items should be visible.
### Environment

* **Kendo UI version:** 2017.2.504

* **Browser:** IE11

**Comment by mparvanov** [comment]
Closing due to relatively low severity and lack of recent demand by the community.
