### ISSUE TITLE
IconClass property of command columns has to be documented and added to MVC server wrappers

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#3347]
### Bug report

The `iconClass` property used in fix for [#2715](https://github.com/telerik/kendo-ui-core/issues/2715) is not documented in the API reference and there isn't a corresponding method for it in the Fluent API. This leads to breaking changes for customers, who wrote code targeting the `span` element dependent on this property setting.

Also, [this example](http://docs.telerik.com/kendo-ui/controls/data-management/grid/how-to/Layout/font-awesome-icons-in-custom-grid-command-buttons) has to be fixed to accommodate the changes in the custom command buttons rendering (and the changes icon classes in the Grid).
### Environment

* **Kendo UI version:** 2017.2.621

Ticket ID: 1116130

**Comment by ag-petrov** [comment]
https://github.com/telerik/kendo/commit/4365d89e27c969e3943ee569968f84db69fd9986

**Comment by PreslavKozovski** [comment]
Additionally, fix this example:
http://docs.telerik.com/aspnet-mvc/helpers/grid/faq#how-to-add-kendo-ui-icons-to-custom-command-buttons

**Comment by PreslavKozovski** [comment]
https://github.com/telerik/kendo/commit/02b6ca541b12f5bb76b11c773436bed83eaec155

**Comment by PreslavKozovski** [comment]
https://github.com/telerik/kendo/commit/e5a438eb360a6b0eec7041f369d024de74a0b627
