### ISSUE TITLE
DropDown in a navigatable Grid is losing focus when up or down arrow is pressed.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3348]
### Bug report

DropDown in a navigatable Grid is losing focus when up or down arrow is pressed. 

### Reproduction of the problem

The issue can be observed in the following video: https://www.screencast.com/t/1lqzDIZ0Ir

### Environment

* **Browser:** [all ]

**Comment by danielkaradachki** [comment]
Can't see the code from the video but assuming that you have copied the custom editor demo, this will occur because of the autoSync option and the behavior is expected.

**Comment by ag-petrov** [comment]
Indeed the custom editor demo seems to be the case. I am marking this as closed unless another case which is valid is pointed.
