### ISSUE TITLE
PanelBar "expanded: true" not working on load with content and contentUrl

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#3349]
### Bug report

PanelBar "expanded: true" does not work properly on load with content and contentUrl. It works properly only with child items, as visible in the following docs example - [Working Dojo](https://dojo.telerik.com/uYEPu)

### Reproduction of the problem
http://dojo.telerik.com/@zdravkov/EMoxIM

Extended Dojo with contentUrl and 2017.2.621: http://dojo.telerik.com/atATe

### Current behavior
The items with expanded true are NOT expanded.

### Expected/desired behavior
The items with expanded true are expanded.

### Environment

* **Kendo UI version:2017.2.621
* **Browser:** [all]

**Comment by ariolaaltus** [comment]
Hi,

Can you please give us an update with regards to this issue and when will the fix be available?

Thank you

**Comment by zdravkov** [comment]
It should be available in the upcoming R3 release that is expected next week.

**Comment by kimiakh** [comment]
Hi
Is there any progress on this task?
