### ISSUE TITLE
The empty spaces at the begging are trimmed when export to excel.

### ISSUE THREAD

**Issue by OMTI-Hee** [telerik/kendo-ui-core#3351]
### Bug report
The empty spaces at the begging in real data are trimmed when export to excel.

### Current behavior
The empty spaces at the begging are trimmed when export to excel.
ex) When I export the "           Hee's Company" text on grid to excel using Kendo API, it is trimmed when opened in excel like "Hee's Company".

### Expected/desired behavior
It should keeps starting empty spaces because it is real data too.

### Environment
* **Kendo UI version:** 2016.R3.SP2
* **jQuery version:1.12.3
* **Browser:** [all | Chrome 59.0.3071.115 | Firefox 54.0 | IE 10 ]

**Comment by ag-petrov** [comment]
This does not seem to reproduce with the latest version - http://dojo.telerik.com/aDebeDEk/2
