### ISSUE TITLE
Focusing the ComboBox with the keyboard and filtering it applies "k-state-focused" class to the wrong item 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3356]
### Bug report

After filtering is performed the "k-state-focused" class is applied inconsistently depending on the way the ComboBox has been focused. Focusing it by clicking on it, then filtering, correctly focuses the first item matching the user input. Whereas if it is focused by pressing Tab, after filtering the focused item is different (it is dependent on the **index** or **value** configuration options). 

### Reproduction of the problem
[Screencast](https://www.screencast.com/t/ycNcplodtl).  [Dojo ](http://dojo.telerik.com/iFeru) example.

1. With index or value set click somewhere on the page. 
2. Press Tab. 
3. Press "d" 
4. Expected: the first of the returned items is focused. Actual: the focused item is based on the value of the "index" or "value" options. 

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by zdravkov** [comment]
Could not replicate it with the latest version.

**Comment by mparvanov** [comment]
The issue is still reproducible:
1) Open http://kendobuild-staging.openstack.progress.com/dojo-staging/eKeveD
2) Press "d" in Combobox input
Expected: Arnold is focused
Actual: donald is focused

**Comment by zdravkov** [comment]
Currently the functionality should work this way:

- if filter is "none" - when the dropdown is opened the first item is not focused and the first item that matches the string in the input is selected
- if filter is **not** "none" - the first item is focused when the highlightFirst is true, if highlightFirst is false nothing is focused.
