### ISSUE TITLE
Kendo ObservableObject Doesn't Support Prototype Methods from TypeScript

### ISSUE THREAD

**Issue by ijabit** [telerik/kendo-ui-core#3358]
https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.data.js -> line 457 you are looping through each property on an object and wrapping it as an observable. However your for...in loop doesn't loop over prototype properties and methods and so once my object gets wrapped the wrapped object is missing all prototype methods.

This is a huge problem when compiling JS classes in TypeScript, since the methods of a class are transpiled down to JS as prototypes. For example, here is my object before you wrap in ObservableObject:
 
![image](https://user-images.githubusercontent.com/557752/27663403-2e85aa90-5c30-11e7-8994-48472f8f3db4.png)

And here it is after:
![image](https://user-images.githubusercontent.com/557752/27663449-5f1a9f08-5c30-11e7-9c3a-c7befd580201.png)

You can see that all prototype methods are dropped!

This happens for any TypeScript compiled class but, for reference, here is the specific class from the screenshots:
```
import IFacilityRepository from "repositories/IFacilityRepository";
import SearchParams from "search/FacilitySearchParameters";
import Facility from "dto/Facility";

export default class FacilityRepository implements IFacilityRepository {
    public authToken = "";

    public constructor(public serviceUrl: string) {}

    private async authorize(ajaxRequest: JQueryAjaxSettings) {
        if (this.authToken === null || this.authToken === "") {
            this.authToken = await $.get(Globals.siteBaseUrl + "api/Authorization/OrderManagementApi");
        }

        ajaxRequest.beforeSend = (jqXHR) => {
            jqXHR.setRequestHeader("Authorization", "Bearer " + this.authToken);
        }

        return ajaxRequest;
    }

    public async getFacility(facilityId: string): Promise<Facility> {
        let settings = await this.authorize(<JQueryAjaxSettings>{
            url: `${this.serviceUrl}api/Facility/${facilityId}`,
            type: "GET",
            dataType: "json",
            contentType: "application/json"
        });

        try {
            return $.ajax(settings);
        } catch (ex) {
            if (ex.status && ex.status === 401) {
                this.authToken = "";
                await this.authorize(settings);

                return $.ajax(settings);
            }
        }
    }

    public async searchFacilities(params: SearchParams): Promise<Facility[]> {
        let settings = await this.authorize(<JQueryAjaxSettings>{
            url: `${this.serviceUrl}api/Facility`,
            type: "GET",
            dataType: "json",
            data: { searchQuery: params.searchQuery },
            contentType: "application/json"
        });

        try {
            return $.ajax(settings);
        } catch (ex) {
            if (ex.status && ex.status === 401) {
                this.authToken = "";
                await this.authorize(settings);

                return $.ajax(settings);
            }
        }
    }

    public async getFacilitySearchResultSuggestions(): Promise<Facility[]> {
        return Promise.resolve([]);
    }
}
```

**Comment by ijabit** [comment]
Anyone reading these?

**Comment by ijabit** [comment]
Will someone at least respond?

**Comment by zdravkov** [comment]
The issue seems like a bug indeed - in such cases in order to be easily reproduced and fixed we need the exact steps to replicate it and a simple dummy code that will show both the current and the desired behavior. If may also submit a feature request of a possible fix if you have an idea about it.

**Comment by ijabit** [comment]
I gave the code to reproduce the issue. It's not hard. I have no idea what the fix would be.

**Comment by ijabit** [comment]
Is anyone going to fix this? Is this toolset still supported?

**Comment by Stamo-Gochev** [comment]
Hello @ijabit,

The main idea of an ObservableObject is to "wrap" a plain JS object with additional abstractions that are used by other Kendo UI entities, such as the DataSource. This is why the properties of the wrapped object are copied to it and its prototype is intact (it is the same as defined in the source code).

On the other hand, what I suppose you are trying to do requires inheritance (extending the ObservableObject "class"), which will result in combining the "FacilityRepository.prototype" with the "ObservableObject.prototype", which is the same as the standard JavaScript prototypal "inheritance". 

This seems like a different use-case than the one that the ObservableObject is intended for and thus it cannot be achieved by it.

**Comment by ijabit** [comment]
@Stamo-Gochev your answer is disappointing. Prototype properties have nothing to do with inheritance and there is no reason why we shouldn't be able to wrap prototype properties just the same as regular properties. Instead you are burying the issue saying it's a different use case and closing the issue.

This is not a different use case, but either a glaring oversight or Kendo showing it's age. JavaScript standards are moving towards the use of classes and the only way to run that new code in existing browsers is by transpiling the properties of the class into prototype properties. So what you're really saying is that Kendo doesn't support, and never will support ES6 classes and therefore is effectively a dead technology.

**Comment by Stamo-Gochev** [comment]
Hello @ijabit, 

In my previous answer, I tried to explain the main concept behind the `ObservableObject` abstraction in the suite and how it is used and still the described requirement does not fit with this concept. This is why I suggested a possible approach for extending the functionality to satisfy these additional requirements as they are not currently supported.

**Comment by ijabit** [comment]
Okay, I know how ObservableObject works and was even able to pinpoint the exact spot in the code where the bug is. The object could easily be extended to work with prototype properties so I don't buy your comment about it fundamentally not fitting my scenario.

As for your "possible approach for extending the functionality to satisfy these additional requirements", I'm already inheriting from ObservableObject and it makes no difference. If you actually read the line of code that I pointed to you'd see why that will never work.

**Comment by stljeff1** [comment]
I concur with @ijabit . Can Kendo comment on the issue at hand? Basically, we are wanting to construct an ObservableObject using an instance of a custom class?

Lets say we have a form for new users. Then, lets say we want to create a class that represents the data of that form. Ie:

`
     class MyFormObject {
             constructor() {
                    this.username = '';
                    this.email = '';
                   ...
            }
            submitForm() {
                    // do stuff
            }
      }
`

Why is it not possible to bind an instance of that class to an html element, ie:

` 
     kendo.bind($('#myForm'), new MyFormObject());
`

**Comment by Stamo-Gochev** [comment]
@stljeff1 As explained in the documentation, `kendo.bind` works by passing an element and an observable, but the result from `new MyFormObject()` is not an observable and thus this cannot work out of the box:

https://docs.telerik.com/kendo-ui/framework/mvvm/overview#create-the-view-model

One way to do it is to inherit from [kendo.data.ObservableObject](https://github.com/telerik/kendo-ui-core/blob/516139db4ce1bc7d17f8057da22c1cb09293c5cf/src/kendo.data.js#L74). Consider the following Dojo example, which is an extended version of the example from the docs:

https://dojo.telerik.com/IMURoNet

The `displayGreeting` method should now work as expected with instances of `MyFormObject`.

Please send us a support ticket in case you need more assistance regarding your specific case, so we can help.

**Comment by jvalkeejarvi** [comment]
When using babel one workaround is to use [babel-plugin-transform-es2015-classes](https://www.npmjs.com/package/babel-plugin-transform-es2015-classes) with option `loose: true`.

That causes babel to transform ES6 classes so that class methods are found from objects prototype.

**In my opinion kendo should support ES6 classes even though a workaround exists. I really hope that this gets fixed.** Making every class in project extend `kendo.data.ObservableObject` as @Stamo-Gochev  suggested is not an option.

**Comment by piresashwin** [comment]
> @stljeff1 As explained in the documentation, `kendo.bind` works by passing an element and an observable, but the result from `new MyFormObject()` is not an observable and thus this doesn't work out of the box:
> 
> https://docs.telerik.com/kendo-ui/framework/mvvm/overview#create-the-view-model
> 
> One way to do it is to inherit from [kendo.data.ObservableObject](https://github.com/telerik/kendo-ui-core/blob/516139db4ce1bc7d17f8057da22c1cb09293c5cf/src/kendo.data.js#L74). Consider the following Dojo example, which is an extended version of the example from the docs:
> 
> https://dojo.telerik.com/IMURoNet
> 
> The `displayGreeting` method should now work as expected with instances of `MyFormObject`.
> 
> Please send us a support ticket in case you need more assistance regarding your specific case, so we can help.

Any arrays inside of MyFormObject Class does not support two way binding. How to solve this problem?

Also, if the array is converted to ObservableArray then its items cannot access the class methods.
