### ISSUE TITLE
Placing ListBox in PopUp editor template in MVC Grid throws error

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#3363]
### Bug report

When a ListBox is placed within a PopUp template, when an item is opened for editing a "_e.value is not a function_" error is thrown. 

### Reproduction of the problem
You can replicate the problem by placing a simple ListBox in the PopUp `template:
````
@(Html.Kendo().ListBox()
            .Name("selected")
            .AutoBind(false)
            .BindTo(new List<string>())
        )
````

### Environment

* **Kendo UI version:** 2017.2.621

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket ID 1116890

**Comment by ag-petrov** [comment]
https://github.com/telerik/kendo/commit/971c0b06f7f7c42fb66a9ba0f57b82820d058fbc
