### ISSUE TITLE
Initializing ListBox in PopUp template in Kendo UI Grid throws error on closing the popup

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#3364]
### Bug report

When a ListBox is placed within a PopUp template of Kendo UI Grid, an "_Uncaught TypeError: Cannot read property 'removeData' of null_" error is thrown when the popup is closed.

### Reproduction of the problem
Refer to the following dojo example:
[http://dojo.telerik.com/Iviru/2](http://dojo.telerik.com/Iviru/2)

### Environment

* **Kendo UI version:** 2017.2.621

**Comment by jthope** [comment]
Is there a workaround to this issue?

**Comment by ag-petrov** [comment]
The workaround would require to override some of the JavaScript. We have already referenced the problem and the fix will be available in the upcoming service-pack.
