### ISSUE TITLE
Splitter does not display bidirectional cursor when resizing panes on Mac

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3366]
### Bug report

One-directional icon is displayed when resizing Splitter panes on Mac.

### Reproduction of the problem

The problem can be reproduced with [the following Dojo](http://dojo.telerik.com/IMUKUwuw)

### Expected/desired behavior

Bidirectional icon should be displayed when resizing the Splitter paned on Mac.

### Environment

* **Kendo UI version:** 2019.3.1023
* **Browser:** [all]

**Comment by pepinho24** [comment]
This is not reproducible with the 2024.4.1112 version.
