### ISSUE TITLE
Pinned Kendo Windows do not re-position correctly using keyboard navigation.

### ISSUE THREAD

**Issue by zakmac** [telerik/kendo-ui-core#3370]
### Bug report
A Kendo Window with the following options will not re-position correctly.
```javascript
{
  draggable: true,
  pinned: true
}
```

Opening a k-window with the options above and attempting to use the keyboard arrows to re-position the window will result in unexpected behavior.

### Reproduction of the problem
Create a k-widow with _at minimum_ the following options set:
```javascript
{
  draggable: true,
  pinned: true
}
```

1. Scroll down the page containing the k-window at least `100px`.
1. Launch the k-window and use keyboard arrow keys to re-position the window on screen. 

### Current behavior

[jsBin demonstrating behavior](http://jsbin.com/nerideqega/edit?output) - Kendo version is outdated but the bug still exists in newer releases

When an arrow key is pressed, a call is made to `kendo.getOffset` which does not make accommodations for a pinned window vs. a statically positioned window. Instead of moving `10px` or another desired increment, the window will move `10px + the current number of pixels the scrollbar is from the top of the page`.

### Expected/desired behavior

When an arrow key is pressed a call is made to `kendo.getoffSet()` and accommodations are made for a pinned window vs. a statically positioned window, resulting in a movement of _only_ `10px` or another specified amount.

### Environment

* **Kendo UI version:** 2017.3.***
* **jQuery version:** N/A
* **Browser:** Chrome 59, Firefox 54, IE 11 (possibly others, not tested)

**Comment by Iankodj** [comment]
Closed due to https://github.com/telerik/kendo-ui-core/pull/3371#issuecomment-321158803

If, however, there are additional concerns that address the latest version of Kendo UI please open a new issue that addresses the most recent version of the suite.
