### ISSUE TITLE
Aggregations on "complex" data sources results in ever increasing values after redraw(refresh)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3373]
### Bug report

Aggregations on "complex" data sources result in ever increasing values after redraw(refresh).

### Reproduction of the problem

The issue can be observed in the following example: 

http://dojo.telerik.com/iBofI/4

Notice how the sum aggregate is increased after the Chart is refreshed even if the data is not changed.

### Environment

* **Browser:** [all]

**Comment by danielkaradachki** [comment]
We discussed the case and while we agree that this is a bug we decided not to fix it at least for now.
Fixing the problem will require to deep clone the original data item which may lead to significant performance issues for a case which can be easily workaround via projection:
http://dojo.telerik.com/@SiliconSoul/aWeCE

Will document it as limitation.
