### ISSUE TITLE
Grid "selectable" column does not remove the selected state from the unlocked columns table

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#3374]
### Bug report

When the selection in the Grid is handled through the "selectable" column and there are locked columns, deselecting records does not remove the selected state from the unlocked columns table

### Reproduction of the problem
Select and deselect item in the following dojo example:
[http://dojo.telerik.com/Itixo/2](http://dojo.telerik.com/Itixo/2)

### Environment

* **Kendo UI version:** 2017.2.621

**Comment by ag-petrov** [comment]
https://github.com/telerik/kendo/commit/560356bb5baca1d9bc75e4609a7bf1e2179da1f5

**Comment by Krish007na** [comment]
I'm facing the same issue. we are using kendo-jquery version - 2017.2.621 (same version as mentioned above)

**Comment by ag-petrov** [comment]
@Krish007na the fix was integrated on 13th of July 2017 which is after the release of version 2017.2.621. Please upgrade to the latest version and check the sample again. If not desirable upgrading to R3 2017 should work as well.
