### ISSUE TITLE
Overlapping buttons in RTL Editor with resizable toolbar

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#3375]
From customer report: with inline editing and RTL the buttons of the toolbar are stacking on top each other.

![image](https://user-images.githubusercontent.com/8048/27826218-f3a6dcd4-60ba-11e7-8dd8-73c5ad4ac844.png)

TID: 1116749

* **Kendo UI version:** 2017.2.621 : http://dojo.telerik.com/opuMIX
* **Kendo UI version:** 2018.3.911 : http://dojo.telerik.com/UBiDAqAf

**Comment by Dimitar-Goshev** [comment]
The issue is reproducible in classic mode as well - [Dojo](http://dojo.telerik.com/Onoqi)

**Comment by Dimitar-Goshev** [comment]
The following issue also concerns the overflow button - https://github.com/telerik/kendo-ui-core/issues/3978
