### ISSUE TITLE
Span element is rendered instead of anchor in a tab configured to use .Action() method

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3377]
### Bug report
If a tab is configured with the .Action() method instead of an anchor element a span element is rendered in the tab's HTML, as a result on selecting the tab the controller is not called. 

### Reproduction of the problem

@(Html.Kendo().TabStrip()
    .Name("tabstrip")
    .Items(items =>
    {
        items.Add().Text("One").Action("About", "Home");
        items.Add().Text("Two").Action("Contact", "Home");
    })
)

### Current behavior
No anchor element is rendered in the tab and selecting it does not call the controller.

### Expected/desired behavior
An anchor element is rendered in the tab and on selecting it the specified action is called. 

### Environment
The behavior is not reproducible with version 2017.2.504 and could be related to the following issue: #3113

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by Iankodj** [comment]
This is indeed a regression from #3113. It should be tested for other possible situation where navigation might fail.
