### ISSUE TITLE
Validation tooltip visible with correct data in the Grid

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3385]
### Bug report

In an input, if you change the value so the validation does not pass, a tooltip appears. If you bring back the old value, the tooltip does not hide due to the fact that the data item is not updated.

### Reproduction of the problem

1. http://demos.telerik.com/kendo-ui/grid/editing-custom-validation
2. Chai -> Edit
3. Chai = chai
4. tab
5. chai = Chai

The validation tooltip is still visible. 

### Current behavior

The tooltip is visible.

### Expected/desired behavior

The tooltip is not visible.

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by Iankodj** [comment]
Tooltip is not involved in the problematic scenario. The same, isolated only with Kendo Binder, works properly: http://dojo.telerik.com/uyaCu. 

After some debugging, it is the ProductName field that does not get the dirty flag when changing from `chai` to `Chai` and thus, there is not change event triggered to call the validate method. If you change it to any other valid value, the validation error will hide. https://www.screencast.com/t/J64GhS2cQV

**Comment by simonssspirit** [comment]
Similar issue is reported on ticket: 1141395 

Scenario:

1) Edit field with value 10,
2) Delete value(null) validation is shown.
3) Enter 10 again, and the validation message is still shown.

Rising priority and severity.
