### ISSUE TITLE
Export to excel doesn't work if there's a merged cell in row 10+

### ISSUE THREAD

**Issue by andreluizbellon** [telerik/kendo-ui-core#3389]
### Reproduction of the problem
Open the spreadsheet's [demo](http://demos.telerik.com/kendo-ui/spreadsheet/index) and do the following:

* Unmerge the header
* Merge A11:B11
* Try to export to excel

### Current behavior
It is throwing the following error in the console:
`Uncaught TypeError: Cannot read property '2' of null`

### Expected/desired behavior
It should have exported the sheet to .xlsx
 
### Environment

* **Kendo UI version:** 2017.2.621

**Comment by lwwells** [comment]
Hi, can I get an update on this issue?  I have run into it in an enterprise app I am building using Kendo.  Thanks!

**Comment by lwwells** [comment]
FYI, I'm on 2017.2.261.

**Comment by lwwells** [comment]
Hi, any update?

**Comment by lwwells** [comment]
Found it, I think...looks like you guys fixed this in 2017.3. I wasn't originally sure if the comment above about adding this to the 2017.R3 milestone meant it was fixed or not.  I did find it in the release notes though.  Thanks.

**Comment by Dimitar-Goshev** [comment]
@lwwells Thank you for the update. The issue is mentioned in [Kendo UI R3 2017 Release notes](https://www.telerik.com/support/whats-new/kendo-ui/release-history/kendo-ui-r3-2017):
![image](https://user-images.githubusercontent.com/6614183/53945490-67c44c00-40ca-11e9-908c-05093d7260b9.png)
