### ISSUE TITLE
Undesired view navigation on editing a task in the Gantt's treelist when navigatable is set to true

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3397]
### Reproduction of the problem
Reproducible in [this](http://demos.telerik.com/kendo-ui/gantt/keyboard-navigation) demo. [Screencast](https://www.screencast.com/t/7UDpAezRj).

1. Double click a task to edit it.
2. Select the text with mouse and then delete it with backspace/delete button or start typing directly.
**NOTE:** The issue is not reproducible, if the text is deleted with backspace without selecting it.
3. Type 1, 2 or 3. This causes the respective view to be auto-selected.

### Current behavior
Unwanted navigation occurs when entering numbers while editing a task.

### Expected/desired behavior
No automatic navigation while a task is edited. 

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by abindalSchuco** [comment]
This is a major issue, Need Hot Fix.
