### ISSUE TITLE
Cursor glitch in Editor after tapping outside of the content area on iPad and iPhone

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3400]
### Bug report

A large cursor appears on the sides of the Editor after tapping outside of the content area. The mobile keyboard is also not responding(hiding) when tapping outside of the Editor.

### Reproduction of the problem

The behavior can be reproduced on iPad and iPhone with iOS 9 and 10 with [the following Dojo](http://dojo.telerik.com/EXUzuJus)

Steps:

* Focus the editor
* Tap outside of the content area

You will notice that the cursor is not placed correctly, no text can be typed and the mobile keyboard is not hiding when you tap outside of the content area of the Editor.

### Current behavior

![2017-07-11_1754](https://user-images.githubusercontent.com/16972160/28075076-0996b084-6663-11e7-9532-13e6c4470aa8.png)

### Expected/desired behavior

Should be able to focus the Editor content area and the mobile keyboard must hide when you tap outside of the Editor content area.

### Environment

* **Kendo UI version:** 2019.1.115
* **Browser:** [ Mobile Chrome | iOS 9 Safari |  iOS 10 Safari  ]

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible with iOS 12 Safari on the Dojo above. It is not reproducible with Kendo UI 2022.1.412 as well - [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/ayIlofUW).
