### ISSUE TITLE
TableWizard, createTable command and Paste table from Word / Excel should append an empty focusable space after table

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3405]
### Bug report

So that when table is created users can navigate after the table by clicking on the empty space and type text.

### Reproduction of the problem
http://demos.telerik.com/kendo-ui/editor/index

### Expected/desired behavior
Example: http://dojo.telerik.com/OHoNU. This only demonstrates a possible option. 

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by veselints** [comment]
Before fixing, review Ticket ID: 1119134 for details

**Comment by Iankodj** [comment]
Another case to be considered: 

Table bug: 
 
1.	Focus at the end of the table
2.	Enter new line
3.	Press backspace to move the cursor at the beginning of the table
4.	Press enter again
Result: <p>&#65279;</p> is entered in the table tag

https://www.screencast.com/t/kUgNs82P7
