### ISSUE TITLE
Grid placed inside PanelBar does not show export progress

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#3408]
### Bug report

When a Grid is placed in a PanelBar, its export progress bar stays empty all the time until the file is exported. This happens because the background applied to completed chunks is overwritten by the PanelBar styles (see [image](https://www.screencast.com/t/I1XDjaycX)).

### Reproduction of the problem
Open this Dojo and run a PDF export:
http://dojo.telerik.com/@tsveti/OxuRE/2

### Current behavior
Progress bar chunks are never filled with the highlight color.

### Expected/desired behavior
Expected behavior is shown in this Dojo, where the PanelBar styles are overwritten with a custom style:
http://dojo.telerik.com/@tsveti/UyUgiK

### Environment

* **Kendo UI version:** 2017.2.604

**Comment by eyupyusein** [comment]
Cannot be reproduced since 2021.3.1109 onward.
