### ISSUE TITLE
Editor adds new lines within comment blocks after viewing the HTML and clicking Update

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3412]
### Bug report
Editor adds new lines within comment blocks after viewing the HTML and clicking Update

### Reproduction of the problem
* [Open the following Dojo](http://dojo.telerik.com/OFUPU/10);
* Click the View HTML button to view the mark-up;
* Click Update;
* Click again View HTML - 4 new lines will be added in each comment;

### Expected/desired behavior
No new lines should be added

### Workaround
To workaround this issue, you could implement the following custom serialization of the HTML:
````JavaScript
serialization: {
    custom: function(html) {
      	var edited = html.replace(/>\s+</g, "><");
        return edited;
    }
}
````

[Here you will find a simple Dojo implementing the above](http://dojo.telerik.com/OFUPU/9).

**Comment by stetod11** [comment]
Hi,

Any sign of this being resolved?

While the workaround looks good on the face of it, it would also remove spaces that users had intentionally added - and we can't allow that to happen.

**Comment by Iankodj** [comment]
The fix that is implemented will not follow the workaround logic. 

With this fix the comments will entirely remain intact as they are not HTML code that should be processed as string. I.e., no new lines will be added or stripped during viewing the source code and applying it back.
