### ISSUE TITLE
 kendo multiselect when filtering item the already selected items should show in blue color.

### ISSUE THREAD

**Issue by VaidNivrutti** [telerik/kendo-ui-core#3413]
kendo multiselect when filtering item the already selected items should show in blue color.
Example 
1 - Before Filtering(Open Multiselect). WhenOPen.png & WhenOpen1.png
2 - When Filtering (When Type or Search In MultiSelect).

on that time we didn't track item is selected already and we select same item deselect event is not occured. 

![whenfiltering](https://user-images.githubusercontent.com/28671993/28261666-cb804568-6afd-11e7-9fe2-a6ab2647e9d5.png)
![whenfiltering1](https://user-images.githubusercontent.com/28671993/28261667-cb80c722-6afd-11e7-887c-01f6229c3105.png)
![whenopen](https://user-images.githubusercontent.com/28671993/28261665-cb7e8eda-6afd-11e7-881c-8da0bedbbefa.png)
![wnenopen1](https://user-images.githubusercontent.com/28671993/28261668-cb8852da-6afd-11e7-8da3-1af7f0786d0a.png)

**Comment by Dimitar-Goshev** [comment]
The issue is fixed and not reproducible since R2 2018 (2018.2.516) - [Dojo snippet](http://dojo.telerik.com/eHOyEqeL)
