### ISSUE TITLE
Wrong content editing, when custom font-size is applied in Editor

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#3414]
### Bug report
When custom font-size is applied to a word, content editing has unexpected behavior:

- Enter key erases content, adds multiples lines, adds lines on top instead of bottom.
- Pressing bold, italic or underline adds empty tags at the beginning instead of at the current selection.
- Changing the color of anything only changes one of the few empty bold tags at the beginning.

### Reproduction of the problem
Reproduction video: https://www.screencast.com/t/5JhLl5vG

1. Go to http://demos.telerik.com/kendo-ui/editor/all-tools
2. Select all Editor's content (ctrl + a), press backspace.
3. Enter one word, e.g. "Available".
4. Press enter.
5. Enter a few word, e.g. "in all stores".
6. Select the first word "in" (Double click on it).
7. Change it's font to something else (Arial).
8. Select the value of the font-size dropdown and change it to 30px without opening the dropdown and press enter.
9. Select all and make it bold.

### Current behavior
Although the whole content appears selected, Editor's behavior is as only the "in" word is selected. Thus, only "in" becomes bold and selected, after the bold button is clicked.
[Content editing video after the above steps](https://www.screencast.com/t/lfJwrPtc)

### Expected/desired behavior
All content becomes bold. Pressing enter after that should insert a new line after the caret position. 

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** [Chrome 59 | Firefox 54.0.1]

**Comment by Iankodj** [comment]
By design, the fontSize and fontName tools should act as DropDown tools and therefore no custom values to be entered. 

Also there is inconsistency with IE, whether those tools are rendered as DropDowns, which is the expected behavior. 

With that said, the proper fix is to make sure that the tools are rendered as expected in Chrome and Firefox, and custom values cannot be entered.
