### ISSUE TITLE
Editor tools icons color is not consistent in all themes

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3415]
### Bug report

Not all themes make use of the "k-tool" class when setting the color of the tools' anchor element. As a result in certain skins (Fiori, Silver, Default, etc.) the color can be easily overridden with:
```html
<style>
a {
    color: #0487c4;
}
</style>
```

### Reproduction of the problem
Reproducible in the basic usage [demo](http://demos.telerik.com/kendo-ui/editor/index), in which the CSS rule posted above comes from examples.css and changes the default tool icon color based on the selected theme. 

Workaround: some of the themes (e.g. Nova), which are not affected by this issue, apply the following CSS rule:
```html
<style>
.k-editor .k-tool {
    color: inherit;
}
</style>
```

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by joneff** [comment]
Fixed by https://github.com/telerik/kendo/commit/7a22dc76908e7bdab8324021b8b9e93b8d1fa550
