### ISSUE TITLE
Editor defaultTools["insertLineBreak"].options.shift = false; causes unbolding to remove new lines

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3420]
### Bug report
Editor defaultTools["insertLineBreak"].options.shift = false; causes unbolding to remove new lines.

### Reproduction of the problem
* Go to the following [Dojo](http://dojo.telerik.com/EREgu/4);
* Type text;
* Bold it using the Bold tool (B icon);
* Hit enter and type a new text;
* Mark the second line and un-bold the text by clicking to the Bold tol;
* This will remove bolding, but it will also move the second line text on the first line

**Comment by IvanDanchev** [comment]
Also reproducible in the demos by pressing Shift + Enter to go to a new line ([screencast](https://www.screencast.com/t/lN9BvEkq)).

**Comment by Iankodj** [comment]
Related to https://github.com/telerik/kendo-ui-core/issues/3354. And fixed in R2 2018.
