### ISSUE TITLE
Spreadsheet throws Cannot read property '2' of null error on xlsx export, when specific mergedCells are set

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3423]
### Bug report
Spreadsheet throws Cannot read property '2' of null error on xlsx export, when defaultCellStyle and specific mergedCells are set.

### Reproduction of the problem
The issue could be observed on [the following Dojo sample](http://dojo.telerik.com/eTADAn)

**Comment by veselints** [comment]
The same could be observed without a *defaultCellStyle* set, but with a single cell with a value. [Dojo here](http://dojo.telerik.com/AYiGa/47)

**Comment by mishoo** [comment]
Both examples work with latest code from `master`.
