### ISSUE TITLE
Grid pageSize(All) not persisting after adding a new record

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3424]
### Bug report

Change to pageSize to All in a Grid. Add a new record. The same behavior is observed when deleting a row.

### Reproduction of the problem

1. https://dojo.telerik.com/IjuzoV
2. Open in Dojo
3. pageable: {    pageSizes: true    },
4. Set the page size to all.
5. Click Add new record.

https://www.screencast.com/t/JgL3RytOb1z5

### Current behavior

The page size is not changed.

### Expected/desired behavior

The page size changes to the new dataSource.data().length value.

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by PreslavKozovski** [comment]
Workaround: http://dojo.telerik.com/uCaWor

**Comment by simonssspirit** [comment]
Reported on ticket 1146878. It is reproducible also when filtering the Grid as well.

Rising the priority.

**Comment by simonssspirit** [comment]
Workaround for the filter issue: http://dojo.telerik.com/uCaWor/3

**Comment by PreslavKozovski** [comment]
Additional scenario for testing:

1. Run the dojo.

2. Filter the product column with a value which is not present in the data, so that grid view doesnot show any record(eg. filter --> product name == 'asdasda')

3. Grid view will not have any records now.

4. Change the page size to 'All'

5. Now clear the filter in product name column.

6. Now the grid view is not populated with the data.
