### ISSUE TITLE
DropDownList with virtualization enabled and pageSize set throws js exception (MVVM binding)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3426]
### Reproduction of the problem
[Dojo ](http://dojo.telerik.com/OkOtiQ) example.

### Environment

* **Kendo UI version:** 2017.2621
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by jivanova** [comment]
The exception is fixed. However, the pageSize gets overridden by the automatically calculated size based on height and itemHeight. Have a look at this article: [http://docs.telerik.com/kendo-ui/controls/editors/combobox/virtualization#data-and-ui-combined](http://docs.telerik.com/kendo-ui/controls/editors/combobox/virtualization#data-and-ui-combined)
