### ISSUE TITLE
When using Grid custom editor, the Kendo Editable adds data-binding for the value for both the hidden and the visible inputs of the ComboBox.

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3427]
### Bug report
When using Grid custom editor, the Kendo Editable adds data-binding for the value for both the hidden and the visible inputs of the ComboBox. This results in a field named *[propertyName]_input* to appear in the item model after it has been edited.

### Reproduction of the problem
* Go to the following [Dojo sample];
* Start editing the ProductName of the first item - a ComboBox will appear;
* Type free text, without select a value;
* Click outside of the editor - the value won't be updated. Also, if you look at the Item, it will have a *ProductName_input* field, that has been added, while editing;

### Current behavior
No new field should be added to the Item data and the field, that has been edited should be updated accordingly.

**Comment by wangwanlin** [comment]
HI， I also come to this problem. I was trying to validate cell if it is required dynamically by other cell, and it appears that [input_name]_input is required. I cannot solve it, can you help me out?

**Comment by martintabakov** [comment]
This bug reproduces with the latest version - https://dojo.telerik.com/OfiCoyog/2

**Comment by Dimitar-Goshev** [comment]
Note: When a ComboBox is used as a custom Grid editor, it is important to set the [syncValueAndText](https://docs.telerik.com/kendo-ui/api/javascript/ui/combobox/configuration/syncvalueandtext) property of the ComboBox to false, as custom combobox values are not valid options for the edited field.

```
function categoryDropDownEditor(container, options) {
            $('<input required name="' + options.field + '"/>')
                .appendTo(container)
                .kendoComboBox({              			
                    autoBind: false,
                    syncValueAndText: false, // prevent using custom values for editing Grid field 
                    dataTextField: "CategoryName",
                    dataValueField: "CategoryID",
                    dataSource: {
                        type: "odata",
                        transport: {
                            read: "https://demos.telerik.com/kendo-ui/service/Northwind.svc/Categories"
                        }
                    }
                });
        }
```
