### ISSUE TITLE
Validator Basic usage demo has unneeded code

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3431]
### Bug report

The **else** block in the **submit** event handler of the **form** will never be executed.

### Reproduction of the problem

http://demos.telerik.com/kendo-ui/validator/index

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The issue will be addressed in the following broader issue - https://github.com/telerik/kendo-ui-core/issues/5742
