### ISSUE TITLE
Stacked bar series don't grow from the valueAxis when it has been moved

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-ui-core#3433]
### Bug report
Stacked bar series don't grow from the valueAxis when it has been moved

### Reproduction of the problem
Can be observed in this example: http://dojo.telerik.com/@Iliana/UmAMUY

Note: when the stacking option is removed, series are rendered as expected

### Current behavior
Stacked bar series always grow from left go right

### Expected/desired behavior
Stacked bar series should grow from the valueAxis position

### Environment

* **Kendo UI version:** v1.12.3 
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by danielkaradachki** [comment]
The behavior is expected for stacked series since they represent sum and always start from zero. Otherwise, the second value from the stack will be drawn on top of the previous value.
