### ISSUE TITLE
kendo angular ui doesnot show up with typescript and webpack

### ISSUE THREAD

**Issue by BhaskaranR** [telerik/kendo-ui-core#3434]
I am facing an issue with importing  kendo with typescript and webpack.  We are using Telerik as a multi portlet app inside life. So we are bootstrapping each portlet as an angular app separately.  The kendo controls does not show up at all.  And it does not throw any errors.  However it works if we bootstrap the application to the document instead of the element.

this this how we bootstrap our app with ng-metadata

    <div class="container-fluid">
          <div id="order-queue-app" class="container-fluid">
        <div>
            <order-queue>
                Loading...
            </order-queue>
        </div>
    </div>
    </div>

```
import {angular, jQuery} from '@mercury/portal';
import { platformBrowserDynamic } from 'ng-metadata/platform-browser-dynamic';
import { enableProdMode } from 'ng-metadata/core';
import { AppModule } from '../app/app.module';
import { OrderQueueModule, OrderQueueModuleName } from '../app/containers/order-queue/order-queue.module';
import { AppSharedModule } from '../app/app.shared.module';
import "kendo-ui-core";
import 'kendo-ui-core/js/kendo.angular';

if ( process.env.NODE_ENV === 'production' ) {
  enableProdMode();
}

// platformBrowserDynamic().bootstrapModule( OrderQueueModule );

angular.bootstrap( document.getElementById('order-queue-app') , [OrderQueueModuleName], {strictDi: true} )

```

appreciate any help

### Environment

* **Kendo UI version:** 2017.1.16
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by BhaskaranR** [comment]
hi, can somebody help me here? stuck with this

thanks,
Bhaskar

**Comment by zdravkov** [comment]
This repository is for Kendo UI for jQuery. For Angular(4+) scenarios we recommend using [Kendo UI for Angular](http://www.telerik.com/kendo-angular-ui/components/). If you observe any bugs you can submit them in this [kendo-angular reposititory](https://github.com/telerik/kendo-angular). In case of other questions you can submit a support ticket.
