### ISSUE TITLE
Cannot read property 'model' of undefined

### ISSUE THREAD

**Issue by texirv0203** [telerik/kendo-ui-core#3437]
- I am new to angular 2 and kendo UI.
- I am trying to add the grid inside my pop up.
- I was able to show the pop-up.
- but when I add the grid kendo-grid-template  ><..I am seeing the below error...
- can you guys tell me how to fix it?
- i am trying to display the grid using the kendo ui.  http://demos.telerik.com/kendo-ui/grid/index
- sample working code http://jsfiddle.net/XY7HT/53/

- providing related code below and complete code in the fiddle since no space to paste it below https://jsfiddle.net/9bwdk6xk/9/

    <div id="win1" style="display:none">
        <p>First Window</p>
        <button type="button" id="open2">Open second Window</button>
            <input type="file" name="batchFile" id="batchFile" title="Select file" />

    </div>
    
    <div id="kgrid" >
        <kendo-grid-template  ></kendo-grid-template>
    </div>

    

>EXCEPTION: Error in app/components/sports/sport caused by: Cannot read property 'model' of undefined
    ErrorHandler.handleError @ core.umd.js:3462
    next @ core.umd.js:6924
    schedulerFn @ core.umd.js:6172
    SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238
    SafeSubscriber.next @ Subscriber.ts:190
    Subscriber._next @ Subscriber.ts:135
    Subscriber.next @ Subscriber.ts:95
    Subject.next @ Subject.ts:61
    EventEmitter.emit @ core.umd.js:6164
    onError @ core.umd.js:6388
    onHandleError @ core.umd.js:6263
    ZoneDelegate.handleError @ zone.js:207
    Zone.runTask @ zone.js:139
    ZoneTask.invoke @ zone.js:304
    core.umd.js:3464 ORIGINAL EXCEPTION: Cannot read property 'model' of undefined
    ErrorHandler.handleError @ core.umd.js:3464
    next @ core.umd.js:6924
    schedulerFn @ core.umd.js:6172
    SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238
    SafeSubscriber.next @ Subscriber.ts:190
    Subscriber._next @ Subscriber.ts:135
    Subscriber.next @ Subscriber.ts:95
    Subject.next @ Subject.ts:61
    EventEmitter.emit @ core.umd.js:6164
    onError @ core.umd.js:6388
    onHandleError @ core.umd.js:6263
    ZoneDelegate.handleError @ zone.js:207
    Zone.runTask @ zone.js:139
    ZoneTask.invoke @ zone.js:304

**Comment by zdravkov** [comment]
From the code provided it seems like AngularJS is used. If you  want to use Angular(4+) I would recommend you to refer to our demos [here](http://www.telerik.com/kendo-angular-ui/components/). If you prefer to use AngularJS and Kendo UI for jQuery you can submit your question in our [forums](http://www.telerik.com/forums/kendo-ui).
