### ISSUE TITLE
Delete confirmation cannot be set as a function when editable.mode is defined

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-ui-core#3438]
### Reproduction of the problem
Dojo example: http://dojo.telerik.com/eXuwi
Sample code:
```
<div id="grid"></div>
<script>
    $("#grid").kendoGrid({
        columns: [
          { field: "name" },
          { field: "age" },
          { command: "destroy" }
        ],
        dataSource: [
          { name: "Jane Doe", age: 30 },
          { name: "John Doe", age: 33 }
        ],
        editable: {
            confirmation: function() {
                return "Are you sure?"
            },
            mode: "popup"
        }
    });
</script>
```

### Current behavior
When `editable.mode` option is set and `editable.confirmation` is used as a function, it gets overriden by `messages.editable.confirmation`, so the function is not being called.

### Expected/desired behavior
The `editable.confirmation` option of the grid should override the `messages.editable.confirmation` setting.

A temporary workaround is to set the desired confirmation function using the `messages.editable.confirmation` option:

http://dojo.telerik.com/iJuRu

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** 1.9
* **Browser:** all

**Comment by simonssspirit** [comment]
reported in ticket: 1120573

Related issue with suggested fix: https://github.com/telerik/kendo-ui-core/issues/3439

**Comment by Stamo-Gochev** [comment]
Closed in https://github.com/telerik/kendo-ui-core/issues/3439
