### ISSUE TITLE
Events within the TreeView Template are not properly bound for the dynamically added nodes

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3440]
### Bug report
Events within the TreeView Template are not properly bound to the respective methods from the ViewModel for the dynamically added nodes.

### Reproduction of the problem
1. Run the following [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/eLoKEbAP)
1. Click one of the arrow symbols to add a new sibling to the TreeView
1. Click the arrow on the newly added item

### Current behavior
No action will be performed

### Expected/desired behavior
The Event bindings should be valid for the newly added items in the TreeView

### Environment
-  ** Kendo UI:** 2019.3.1023
- **Browser:** all

**Comment by veselints** [comment]
The issue could be worked around by re-setting the DataSource of the TreeView:
````JavaScript
treeview.setDataSource(this.get('treeData'));
````

**Comment by PekoPPT** [comment]
Reported in Ticket ID: 1408029

**Comment by sspasova** [comment]
The issue is fixed. Tested with Kendo UI version 2023.3.1010. I am linking a working Dojo example - https://dojo.telerik.com/ucEyUsAt .
