### ISSUE TITLE
k-ng-model not set correctly with cascading ComboBoxes

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3446]
### Bug report

The cascading functionality of the ComboBox widgets breaks k-ng-model and does not set the correct value for the cascading ComboBox model.

### Reproduction of the problem

The described behavior can be observed on [the following Dojo](http://dojo.telerik.com/AtOXA).

In order to reproduce the issue follow these steps:

* Click the "Switch" button - value changes in both widgets.
* Click the "Switch" button a second time - $scope.c2 is null (logged in the browser console), thus no value is being selected in the second ComboBox.

### Environment

* **Kendo UI version:** 2016.1.112 and UP
* **Browser:** [all]

**Comment by jivanova** [comment]
Fix included in: https://github.com/telerik/kendo/commit/795b771a52c9a2b8f5d0d6b34583c1ed5898153c
