### ISSUE TITLE
The columns order in the Grid column menu is not changed after reordering only for the reordered column.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3449]
### Bug report

The columns order in the Grid column menu is not changed after reordering only for the reordered column.

### Reproduction of the problem

The issue can be observed in the following Dojo: http://dojo.telerik.com/oNoDi

Steps: 

1. Grid with column reorder and column menu
2. On a column open the column menu to show/hide columns
3. Reorder the grid columns
4. Open the column menu for the same column => the columns in menu are in the initial state (before reorder)
5. Open column menu for any other column => the columns menu is in the correct state (after reorder)

### Environment

* **Browser:** [all]

**Comment by Stamo-Gochev** [comment]
The problem is also reproducible with the mobile column menu.
