### ISSUE TITLE
Progress bar not displayed during upload in Edge

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3451]
### Bug report

No progress bar is being displayed in the Kendo UI Upload widget while uploading files with the latest version of Edge.

### Reproduction of the problem

The described issue can be observed on [the following demo](http://demos.telerik.com/kendo-ui/upload/async) with Edge 40 (works ok with Edge 38).

[Screencast](https://www.screencast.com/t/JygGIPaaGJX)

### Expected/desired behavior

A progress bar should be displayed to indicate the upload progress.

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** [ Edge 40 ]

**Comment by mparvanov** [comment]
Not reproducible with Edge 44.17763.1.0 and Kendo 2019.3.1023
