### ISSUE TITLE
Wrong values for Scheduler event resources when multiple resources are filtered and selected

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#3455]
### Bug report
There are two issues as a result of filtering multiple event resources and selecting a filtered value:
- Problem 1 - Newly created events do not appear for the resource selected with filtering;
- Problem 2 - After filtering is used, Scheduler's Create event form is populated with wrong values for resources and the event placeholder does not appear on the timeslot selected for creating it.

#### Problem 1:
[Reproduction Video](https://www.screencast.com/t/CEALFIuR)
1. Go to the demo-site for the timeline view of the scheduler: http://demos.telerik.com/kendo-ui/scheduler/timeline
2. Double-click on an empty timeslot to open create form, e.g. Meeting Room 101 -> Alex -> 7-7:30 AM.
3. Click in the „Attendees“ field and type „Bo“  -> the editor suggests „Bob“
4. Select „Bob“ and click „save“.

**Expected:** the created event appears for Alex and Bob, as they were selected as resources.
**Actual:** The created event appears only for Alex. Refreshing the Browser with F5 shows the display with the correct events.

**NOTE:** The bug does NOT appear if you just click in the „Attendees“ field without typing anything and select „Bob“ directly with the mouse (without using the multiselect filtering functionality.

#### Problem 2:
[Reproduction Video](https://www.screencast.com/t/YaNq7VrZj)
After following all steps from Problem 1 above, if a timeslot is double-clicked for creating a new event, the resources shown in the form are incorrect. Also the placeholder for the new event appears in a wrong timeslot, not in the one, which is double-clicked.

**NOTE:** **workaround** for the time being could be to either **not use multiple resources selection**, or to **disable typing in the multiselect** (prevent filtering option) by setting readonly attribute to its input element in Scheduler edit event - [Dojo](http://dojo.telerik.com/ENUfox) 

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** [all]

**Comment by zdravkov** [comment]
The issue is caused by a bug in multiselect widget that the filter is not removed after the widget is blurred:
`    
           $("#button").kendoButton();
            var button = $("#button").data("kendoButton");
            button.bind("click", function (e) {
                console.log($("#multiselect").data("kendoMultiSelect").dataSource._filter)
            });
            $("#multiselect").kendoMultiSelect({
                dataSource: [
                    { Name: "Parent1", Id: 1 },
                    { Name: "Parent2", Id: 2 }
                ],
                dataTextField: "Name",
                dataValueField: "Id"
            });
