### ISSUE TITLE
The registerTheme method does not work for setting the colors of the TreeMap.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3458]
### Bug report

The registerTheme method does not work for setting the colors of the TreeMap.

### Reproduction of the problem

The issue can be reproduced in the following Dojo: http://dojo.telerik.com/ODaWi

### Environment

* **Browser:** [all]

**Comment by danielkaradachki** [comment]
If I am not mistaken, this is not a public method. At least I couldn't find anything in the docs.
Also, the issue is not for the chart as it is labeled.
The problem is in the treemap which currently works only with lowercase letters for the name:
http://dojo.telerik.com/@SiliconSoul/EBArIt

**Comment by simonssspirit** [comment]
Closed based on the provided information from @danielkaradachki 

The colors can be set if the theme name is with lower case letters.
