### ISSUE TITLE
.NET Core NumericTextBox tag helper does not apply properly formatting configuration

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3466]
### Bug report
.NET Core NumericTextBox tag helper does not apply properly formatting configuration. This occurs when the strongly typed version of the helper is used. The percent formatting results in 0.00 format:
````C#
 <kendo-numerictextbox format="p0" for="[Model property name]"/>
````

### Expected/desired behavior
The strongly typed version of the tag helper should properly set the formatting of the widget as the not-strongly typed version does:
````C#
<kendo-numerictextbox format="p0" name="simpleTag" value="0.7"/>
````

**Comment by Allann** [comment]
It should be noted that the format string also does not use the standard {0:p0} syntax nearly every other control does.  For example using the standard asp tag helper attributes:
                    <input asp-for="MaximumGrainPercent" asp-format="{0:p0}" class="form-control" autocomplete="off" />

**Comment by Allann** [comment]
Any news on this?  It's been a year and it still appears to be an issue.

**Comment by Allann** [comment]
In the latest version 411 (i think) the restrict-decimals="true" and decimals="0" attributes are also ignored.
