### ISSUE TITLE
New features for Core and Professional version

### ISSUE THREAD

**Issue by RaptorCZ** [telerik/kendo-ui-core#3468]
I created a new operator for kendo.data (UI Core) and created custom modification for kendo.filtercell (Professional). Is there any way how to try propose this new thing to Kendo Professional build? I can create pull request only for UI Core code, but FilterCell is not open sourced. We have sources based on our license so I'm able to modify everything.

**Comment by zdravkov** [comment]
You can submit the feature request with the changes in our core project in this repository. As for the changes in the professional version I would recommend you to open a support ticket and submit the changes and their description so we could inspect it and create an internal feature request based on it.
