### ISSUE TITLE
Chart treats a \n string in the data as a new line character

### ISSUE THREAD

**Issue by dimodi** [telerik/kendo-ui-core#3469]
### Bug report

The Kendo UI Chart treats a \n string in the data as a new line character. Reported in ticket **1122855**.

### Reproduction of the problem

https://jsfiddle.net/jx7r5q8n/

The above test page contains the workaround as well. Remove the label template to see the issue in action.

### Current behavior

Labels containing "\n" will be split to two lines.

### Expected/desired behavior

Labels containing "\n" should be displayed on a single line.

### Environment

* **Kendo UI version:** 2017.2.621

**Comment by danielkaradachki** [comment]
The behavior is by design and is described in the documentation:

http://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart#configuration-categoryAxis.labels.template

**Comment by dimodi** [comment]
@tsvetomir Can you please take a look and confirm that we are all on the same page and discussing the same use case? I got the impression that the problematic scenario involved a "\n" string that was escaped and should not be treated as a new line character. Thanks.
