### ISSUE TITLE
Kendo editor FontName tool doesn't show selected value on mobile device

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#3470]
### Bug report
The FontName tool value is applied to editor content but is not displayed in the UI on Android and iPhone. 
https://www.screencast.com/t/D6QxlY6g9y
Ticket ID: 1123036

### Reproduction of the problem
http://demos.telerik.com/kendo-ui/editor/all-tools
Change the font name through the dropdown

### Environment
* **Kendo UI version:** 2017.2.621
* **Browser:** iPhone Safari and Android Chrome

**Comment by Dimitar-Goshev** [comment]
Closing it as Duplicate of: https://github.com/telerik/kendo-ui-core/issues/2295
The issue description is copied as a comment to the original item.
