### ISSUE TITLE
Hiding the first unlocked column in a grid with Frozen columns leads to a thick line between the locked and unlocked tables

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3472]
### Bug report

Hiding the first unlocked column in a grid with Frozen columns leads to a thick line between the locked and unlocked tables.

.k-filter-row>th:first-child, .k-grid tbody td:first-child, .k-grid tfoot td:first-child, .k-grid-header th.k-header:first-child {
    border-left-width: 0;
}

https://www.screencast.com/t/NWUkqvbj1P

### Reproduction of the problem

1. http://dojo.telerik.com/Okota
2. Hide the age column.

### Current behavior

A thick line appears as a border(two borders).

### Expected/desired behavior

A normal border appears(a single border).

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by PreslavKozovski** [comment]
Workaround: http://dojo.telerik.com/Okota/3

**Comment by theOrlin** [comment]
This can be worked around by switching the direction of the border but that introduces an unwanted border if the last column is hidden, causing an inconsistency in the appearance of the Grid:
![grid_last_column_unwanted_border](https://user-images.githubusercontent.com/5155721/33216009-b9c8d814-d13a-11e7-90fe-02ff37073919.png)

One way to work around this is to have a marker for first and last visible column but this will require a rewriting in the rendering of the Grid which requires further discussion.

**Comment by theOrlin** [comment]
Upon further consideration, fixing this in the Grid's code would be too involved for such an issue, and potentially cause undesired side effects.

The border is expected as we have border to the right of the frozen columns container (to mark the end of the frozen columns), and border to the left of the visible unlocked columns. Upon hiding the leftmost one, it is natural to have a double border where the two meet. If a workaround is needed, use the one suggested above (dojo: http://dojo.telerik.com/Okota/3).

For the time being this is a won't fix.
