### ISSUE TITLE
Editor formats pasted content as list which is not formatted as list in the source Word document.

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3474]
### Bug report

Editor formats pasted content as list, while this content is not formatted as list in the source Word document.

### Reproduction of the problem
Use the attached word document content and paste it in the BasicUsage online demo:
[http://demos.telerik.com/kendo-ui/editor/index](http://demos.telerik.com/kendo-ui/editor/index)

### Current behavior
The first row is generated as list

### Expected/desired behavior
The content should not be formatted as list

### Environment

* **Kendo UI version:** 2019.1.115
* **Browser:** [all ] 
[bug_rep.zip](https://github.com/telerik/kendo-ui-core/files/1194136/bug_rep.zip)

**Comment by Iankodj** [comment]
The convert-to-list mechanism depends on the specific list-formatting of Word. Shortly, Word never actually provides content that is formatted as a list. The list is detected by class name and/or characters that outline a list formatting (like the one in the attached document). Therefore, paragraphs that have list characters in from of the text are considered as list formatting. Plus, visually, they are lists and there are actually reports for such content not being converted to list.

If we are to remove that text reading we would produce a lot of breaking changes with complex paragraph and list nesting copied from Word into the Editor.
