### ISSUE TITLE
Kendo UI Grid MVC does not render a guid value as an id attribute for the th element, which matches the aria-describedby value of the cells in that column

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#3475]
### Bug report

Kendo UI Grid MVC does not render a guid value as an id attribute for the th element, which matches the aria-describedby value of the cells in that column. This causes JAWS not to read the column name together with the cell value while navigating between the cells of the grid. 

### Reproduction of the problem

It can be inspected on any Kendo UI Grid for ASP.NET MVC demo and compare the rendering of the th element with a demo of Kendo UI Grid for JavaScript. 

### Expected/desired behavior
The id value of the th element should match the aria-describedby value of all cells in the column. 

### Environment

* **Kendo UI version:** all
* **jQuery version:** all
* **Browser:** [IE]

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket with ID1123610

**Comment by VicTachev** [comment]
Reported again in ticket 1138616

**Comment by MilenaCh** [comment]
https://github.com/telerik/kendo/issues/6930
