### ISSUE TITLE
When pasting the following string (Mar 2017 randomText) in a Spreadsheet cell, the widget converts it to "3/20/2017"

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3476]
### Bug report
When pasting the following string ("Mar 2017 randomText") in a Spreadsheet cell, the widget converts it to "3/20/2017".

### Reproduction of the problem
Here you will find a short video:

[2017-08-03_0939.zip](https://github.com/telerik/kendo-ui-core/files/1196283/2017-08-03_0939.zip)

### Expected behaviour
The pasted text should remain the same in the Spreadsheet

**Comment by mishoo** [comment]
This is how kendo.parseDate works.  I thought an acceptable fix would be to make it fail (return null) if any text remains after parsing the format.  This could be achieved by adding [on this line](https://github.com/telerik/kendo-ui-core/blob/a6e371b0a4f5fbe2639239e3851216a81da0fc39/src/kendo.core.js#L1429):

```js
        // if more characters follow, assume wrong format
        // https://github.com/telerik/kendo-ui-core/issues/3476
        if (!/^\s*$/.test(value.substr(valueIdx))) {
            return null;
        }
```

However, this makes a bunch of tests fail, [for example](https://github.com/telerik/kendo-ui-core/blob/a6e371b0a4f5fbe2639239e3851216a81da0fc39/tests/core/dateparsing.js#L80-L81).  CC @ggkrustev — any thoughts about this?  Fixing it my way seems to be a breaking change…

**Comment by ggkrustev** [comment]
Making the `parseDate` to fail in such circumstances will be quite big breaking change. Although, I absolutely agree that `parseDate` method should return `null` when input doesn't match exactly the format. I'm afraid, though, it is a bit late to just release the change.

Would it be possible to split the logic and introduce a new method, `kendo.parseExactDate` ? Thus we will be able to incrementally and not too obtrusively replace `parseDate` with new `parseExactDate`, fixing all related bugs.

@mishoo, do you think that this is a feasible solution?

**Comment by mishoo** [comment]
@ggkrustev, that would work.  Although, funny, the function where I proposed the change above is called `parseExact`. ☺ (but fortunately that's not public)

I'll add `kendo.parseExactDate` which will return null when text remains after the format.

**Comment by ggkrustev** [comment]
@mishoo, yeah... I feel the shame on me, as an author of this poor-named function :). At least we fixed it in `kendo-intl` package :)
Oh well... http://devopsreactions.tumblr.com/post/150811199010/reaction-of-a-senior-engineer-having-seen-it-all
