### ISSUE TITLE
Immutable elements cannot be deleted via Backspace with collapsed selection

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#3480]
### Bug report

[http://demos.telerik.com/kendo-ui/editor/immutable-elements](http://demos.telerik.com/kendo-ui/editor/immutable-elements)

### Reproduction of the problem
1. Set the cursor as follows: Dear Your Name, **|** 
2. Start pressing backspace

### Current behavior
"Dear" immutable element cannot be deleted.

### Expected/desired behavior
The whole immutable element is deleted once Backspace is pressed at its end.

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** 3
* **Browser:** Internet Explorer 11

**Comment by Iankodj** [comment]
Duplicated: https://github.com/telerik/kendo-ui-core/issues/3062
