### ISSUE TITLE
Checkboxes in Scheduler edit form in Mobile mode are displayed as arrows, instead of ticks

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3485]
### Bug report
Checkboxes in Scheduler edit form in Mobile mode are displayed as triangle, instead of tick.
In addition, if the all day checkbox is not checked, it is not visible at all.
This is a regression introduced with the R1 2017 release.

### Reproduction of the problem
* Open the Edit form in the following [Dojo](http://dojo.telerik.com/eDInO/2);
* Click on the *All Day* line to check the checkbox;
* A triangle will be displayed to the far right, instead of tick;

### Current behavior
- https://www.screencast.com/t/ZkABEaDQ6

- Checkboxes in Repeat event view:
![image](https://user-images.githubusercontent.com/6614183/29064088-97eee26a-7c30-11e7-8942-54dd49e56c6b.png)

### Expected/desired behavior
https://www.screencast.com/t/do3TE1crj

### Environment
* **Kendo UI version:** from 2017.1.118 on

**Comment by Dimitar-Goshev** [comment]
Duplicate: https://github.com/telerik/kendo/issues/6682

**Comment by Dimitar-Goshev** [comment]
As of R2 2019 this issue is no longer valid. The improved Scheduler adaptive rendering uses a switch for the All day true/false editor. The checkboxes no longer show triangles.
