### ISSUE TITLE
feat: Change to FilterCell in Professional version

### ISSUE THREAD

**Issue by RaptorCZ** [telerik/kendo-ui-core#3488]
I would like to include changes to FilterCell component in Professional version.

In pull request https://github.com/telerik/kendo-ui-core/pull/3487 is implementation of new operators for string values - IsNullOrEmpty and IsNotNullOrEmpty. Reason why I need it is included in description of pull request.

Only needed edit action for FilterCell component is add those operators to configuration.

file: **kendo.filtercell.js**
```
nonValueOperators = [
                'isnull',
                'isnotnull',
                'isempty',
                'isnotempty',
                'isnullorempty',
                'isnotnullorempty'
            ];
```
```
string: {
    eq: EQ,
    neq: NEQ,
    startswith: 'Starts with',
    contains: 'Contains',
    doesnotcontain: 'Does not contain',
    endswith: 'Ends with',
    isnull: 'Is null',
    isnotnull: 'Is not null',
    isempty: 'Is empty',
    isnotempty: 'Is not empty',
    isnullorempty: 'Has no value',
    isnotnullorempty: 'Has value'
}
```

Attached changed file is modified from 
**telerik.kendoui.professional.2017.2.621.commercial-source**

[kendo.filtercell.zip](https://github.com/telerik/kendo-ui-core/files/1210467/kendo.filtercell.zip)

**Comment by matanasov** [comment]
@ag-petrov @Stamo-Gochev
Please update this issue once the related PR is resolved.

**Comment by ag-petrov** [comment]
Implemented and merged.
