### ISSUE TITLE
The editor templates used from the Grid are not found if they are placed in the view folder(MVC Core).

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3492]
### Bug report

The editor templates used from the Grid are not found if they are placed in the view folder(MVC Core). The standard EditorFor will successfully find the templates, but the Grid will not.
In the same scenario, the MVC 5 Grid will successfully find the templates as well.

### Reproduction of the problem

The issue can be reproduced in our demos if а custom popup editor template is placed under the view folder: Views/EditorTemplates/TemplateName.cshtml

### Environment

* **Browser:** [all]

**Comment by boyandim** [comment]
Duplicated issue with #2007 and it is not reproducible with latest version.
