### ISSUE TITLE
Empty tags remain after deleting the Editor's content

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3493]
### Bug report

When all of the Editor's content is deleted either by highlighting it with the mouse and pressing Del or by pressing Ctrl + A then Del keys, some empty tags remain, for instance:
```html
<h4 style="font-family:'Times New Roman';font-size:medium;"></h4>
```

In Chrome both ways of deleting the content (highlight + Del and Ctrl + A + Del) result in empty tags being left, whereas in FF and IE11 only the former way leaves tags. 

### Reproduction of the problem
[Dojo](http://dojo.telerik.com/OWENEW/2) example. 

### Current behavior
Empty tags remain after deleting the Editor's content.

### Expected/desired behavior
No tags remain after deleting the Editor's content.

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Iankodj** [comment]
Fixed in [editor-fix-handleselection](https://github.com/telerik/kendo/tree/editor-fix-handleselection)
