### ISSUE TITLE
autoWidth works only when filter: "contains" is set

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3498]
### Bug report

The AutoComplete autoWidth only works when the filter property is set and its value is "contains" (Does not work with "startswith").

### Reproduction of the problem

The described behavior can be observed on [the following Dojo example](http://dojo.telerik.com/eZEfE).

Steps to reproduce the issue:

* Focus the AutoComplete and type "a"
* Clear the input to show all items

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** [all ]

**Comment by mparvanov** [comment]
Unexpected horizontal scrollbar appears in the popup in IE, Edge and Firefox.
