### ISSUE TITLE
kendoGrid toolbar & command buttons: imageClass not supported anymore

### ISSUE THREAD

**Issue by sebfz1** [telerik/kendo-ui-core#3499]
Hi,

It seems that `imageClass` [1] is not supported by kendoGrid's toolbar anymore

2017.2.621 (not working):
http://dojo.telerik.com/@sebfz1/AzUzI

2017.2.504 (working):
http://dojo.telerik.com/@sebfz1/AQAxA

This is also affecting command buttons.

I didn't read any mention of this in the release note so I suppose it was not intended.
http://www.telerik.com/support/whats-new/kendo-ui/release-history/kendo-ui-r2-2017-sp1

[1] http://www.telerik.com/forums/toolbar-configuration

Thanks & best regards,
Sebastien

**Comment by sebfz1** [comment]
`iconClass` can be used instead [1]. IMO, it should to be documented in http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-columns.command

[1] http://docs.telerik.com/kendo-ui/controls/data-management/grid/how-to/Layout/font-awesome-icons-in-custom-grid-command-buttons

**Comment by matanasov** [comment]
@sebfz1 
These are now documented [here](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-toolbar.iconClass) and [here](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-columns.command.iconClass).

**Comment by sebfz1** [comment]
Great, thanks @matanasov ! :+1:
