### ISSUE TITLE
Timeline view events overlap when columnWidth and eventMinWidth are set

### ISSUE THREAD

**Issue by ivanchev** [telerik/kendo-ui-core#3501]
### Bug report
Timeline view events overlap when columnWidth and eventMinWidth are set

### Reproduction of the problem
1. https://dojo.telerik.com/OBaHoYUy

### Current behavior
Events are on one row and overlap:
![image](https://user-images.githubusercontent.com/6614183/51121761-e31f2500-1820-11e9-8964-a08eb68fac95.png)

### Expected/desired behavior
Events are on different rows:
![image](https://user-images.githubusercontent.com/6614183/51121744-d8649000-1820-11e9-8d95-caff12495349.png)
This is reproducible, when eventMinWidth is commented in the above dojo setup.

### Environment
* **Kendo UI version:** 2019.1.116
* **Browser:** [all]

**Comment by zdravkov** [comment]
Both properties expect number yet in the example we pass string and that is breaking the functionality.
Here is a working example after we define both properties as numbers - https://dojo.telerik.com/@zdravkov/isoHIsAW.

columnWidth is documented [here](https://docs.telerik.com/kendo-ui/api/javascript/ui/scheduler/configuration/views.columnwidth)  .
eventMinWidth is not documented yet after checking it in the source code it is expecting only number too. I have logged an issue to document it properly.
