### ISSUE TITLE
text-transform: uppercase is ignored on PDF export

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3502]
### Bug report
Currently, text-transform: uppercase is ignored on PDF export. Research the case and confirm whether it is a limitation or a bug.

### Reproduction of the problem
Could be observed on the following [Dojo](http://dojo.telerik.com/IXAnu/48)

**Comment by HymedGh** [comment]
Hey Guys ! The kendo DOJO above seems to demonstrate that stylesheet upper-casing is a limitation of kendo PDF.
Can you please confirm that ? or is there any solution to take this particular styling into consideration ?
