### ISSUE TITLE
MultiSelect's clear button does not clear all selected items in single tag mode

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3506]
### Bug report
Currently clicking the clear button removes the last selected item in a MultiSelect in single tag mode. This behavior has been introduced in R2 2017. 

### Reproduction of the problem
Reproducible in [this](http://demos.telerik.com/kendo-ui/multiselect/tag-mode) demo. 

### Current behavior
The clear button removes the last selected item. 

### Expected/desired behavior
The clear button removes all selected items. 

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by melfahn** [comment]
this item should not be closed, it is currently an issue in v2021

**Comment by Dimitar-Goshev** [comment]
@melfahn The issue is not reproducible on my side with the reproduction steps from the description. The online demos use R1 2021 - 2021.1.119. Could you provide steps to reproduce, if the issue is reproducible on your side on the online demos? Or if a certain different setup is needed, could you provide it as a Dojo snippet for example and steps to reproduce it.

**Comment by brunoviveiros-dev** [comment]
I'm using 2022.1.119 version and facing the same reported issue with single tag mode.

Component code:
`<kendo-multiselect name="CollectorMultiSelect"
                   datatextfield="Text"
                   datavaluefield="Value"
                   placeholder="Collectors..."
                   tag-mode="@MultiSelectTagMode.Single"
                   down-arrow="true"
                   auto-close="false"
                   clear-button="true"
                   item-template="<input type='checkbox'/> #:data.Text#"
                   on-change="onMultiSelectChange"
                   on-data-bound="onMultiSelectDataBound"
                   style="width:100%;">
    <datasource type="DataSourceTagHelperType.Custom" server-filtering="true">
        <transport>
            <read url="@Url.Action("GetCollectorsMultiSelect", "CollectorInstances", new { Area = "Dashboards" } )"/>
        </transport>
    </datasource>
</kendo-multiselect>`

![MultiSelect_SingleTagMode](https://github.com/telerik/kendo-ui-core/assets/81095417/ccf40a45-5f87-48f5-9ea5-1996e5ab92e1)

If I change from `tag-mode="@MultiSelectTagMode.Single"` to `tag-mode="@MultiSelectTagMode.Multiple"`, the same behavior happens, but if I remove `tag-mode="@MultiSelectTagMode.Single"`, it works correctly.

![MultiSelect_MultipleTagMode](https://github.com/telerik/kendo-ui-core/assets/81095417/e079d9f8-a1d0-4215-9af0-218321fe391e)

I also tested without item-template and javascript to control the checkbox and the same thing happened.

Using Progress Telerik Repl for ASP.NET Core the code snippet works fine: [https://netcorerepl.telerik.com/GIOPFhvB23H3Pijj46](url)
