### ISSUE TITLE
Kendo UI Grid Column menu stays visible after the Grid is hidden.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3507]
### Bug report

Kendo UI Grid Column menu stays visible after the Grid is hidden.

### Reproduction of the problem
Check the following Dojo: http://dojo.telerik.com/EKIYAtod

Steps to reproduce:

- Click on Item 1
- Click on the column menu chevron icon in "Product Name" (or any column header)
- Press shift-tab on keyboard once to move focus back, onto Item 1 (NB shift-tab twice in FF)
- Press enter on keyboard to activate Item 1 in PanelBar

### Current behaviour

Panel bar collapses and the Grid is hidden, but column menu remains visible/orphaned.

### Expected/desired behavior

Panel bar collapses and column menu disappears along with grid

Workaround: http://dojo.telerik.com/umaCE/5

### Environment
* **Kendo version:** 2019.3.917
* **Browser:** [all]

**Comment by ag-petrov** [comment]
This is a behavior of the popup. Currently mouse iteractions only will hide it. I am adding a Kendo2 label for revision.

**Comment by ag-petrov** [comment]
This should be handled with custom logic. Integrating show/hide detection would not bring any additional value
