### ISSUE TITLE
Underline and BackColor Editor tools remove tags, although custom classes set to tags should prevent removal

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3508]
Some of the Editor's tools modify the widget's content when used and remove tags or merge elements into one element. 
[Dojo ](https://dojo.telerik.com/UbegUl) example.

1. Highlight the "HTML" word in the first line. 
2. Click "underline". Click "underline" again. The **span** tags are removed and "HTML" is now part or the **p** element's text.

1. Highlight "Test1Test2".
2. Repeat 2. from the previous example. The tags of the two span elements are removed. 

1. Highlight "Test1Test2".
2. Select a color from the backColor tool and apply it. "Test1" and "Test2" are merged into a single span. 

Compare this behavior to that of the "bold" tool, which does not remove or merge tags.
 
### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by IvanDanchev** [comment]
After further discussion of the three issues (steps: 1-2, 3-4 and 5-6) the team came to the following conclusions: 

* The removal of the span in this case is expected since by default the Underline tool wraps the highlighted word in a span and applies to it **text-decoration: underline**. Removing the underline is done by removing the added span element. This can be observed by highlighting the word "familiar", which is not declared in a separate span element, and clicking the Underline tool. The Editor wraps it in a span with the mentioned styles applied. Clicking the tool again removes the added span. The Bold tool works similarly only it adds a **strong** element instead of span. In the case described in 1-2 the word "HTML" already is wrapped in a span element, so on clicking Underline only the mentioned style is applied to it, but on clicking it again the span is removed as described in the example with the "familiar" word following the default procedure of removing underline. To workaround this behavior a custom class could be set to the declared span element. This way the Editor can tell it appart from a span elements that it automatically adds when using the Underline tool: dojo example.  
* Issue 3-4 needs further investigation since the previously suggested workaround (setting custom classes to the elements):
```html
 <span class="test1">Test1</span><span class="test2">Test2</span>
```

does not prevent them from being merged on applying Underline. 
* The behavior on applying the BackColor is similar to the previous one (3-4) in that even if custom classes are set to the elements they are merged into a single span element.

**Comment by Iankodj** [comment]
As consolidation of same tags is part of the Editor's logic and it is implemented on purpose this issue targets to fix only consolidation of tags with different class names, i.e., to prevent such consolidation. 

Fix is available in [editor-inline-consolidate](https://github.com/telerik/kendo/tree/editor-inline-consolidate).
