### ISSUE TITLE
ContextMenu close event fires multiple times

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3509]
### Bug report
The close event fires multiple times based on how many times the ContextMenu has been closed previously. For example, if it is open for the first time and closed the event fires once. Opening and then closing it again will cause the event to fire twice and so on. 

This behavior has been introduced in R2 2016 SP2 (2016.2.714).

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/eJUDU) example.

1. Open the ContextMenu.
2. Close it. 
3. Repeat 1. and 2.

### Current behavior
The close event fires multiple times.

### Expected/desired behavior
The close event fires a single time. 

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by zdravkov** [comment]
Fix in [this branch](https://github.com/telerik/kendo/tree/menu-close-event)
