### ISSUE TITLE
Chrome scrolls when Grid is focused.

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#3511]
### Bug report

Use the cofiguration below to replicate the problem:
http://dojo.telerik.com/IviQib

Steps to reproduce:
1.Click a cell to enter edit mode
2.Press Tab key

Result: Page scrolls down.

Video:
https://www.screencast.com/t/O8HqLf02q

**Comment by DarynHolmes** [comment]
When I test the link above I do not see the error, however I can see the error in this link: https://runner.telerik.io/fullscreen/@daryn/uCEHU

As explained on the Kendo forum,  I start seeing the jumping at anything higher than a height of 645.

This is on Google Chrome Version 60.0.3112.101 (Official Build) (64-bit)
Tit is not "jumping" on Microsoft Edge 40.15063.0.0

FYI: Original thread - http://www.telerik.com/forums/grid-selection---screen-jumps-scrolls

**Comment by DarynHolmes** [comment]
Shouldn't this be labelled as a bug?

**Comment by Abhishek311290** [comment]
so is there any fix suggested or setting the height is the only fix for this issue?
