### ISSUE TITLE
Focus order is reset when tabbing fast after the DropDownList pop-up is opened

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3512]
### Bug report
Focus order is reset when tabbing fast after the DropDownList pop-up is opened. The focus goes to the beginning of the page, instead of the next focusable element.

### Reproduction of the problem
1. Open the following Dojo: http://dojo.telerik.com/uMaDO/25
1. Open the DropDownList pop-up and tab out really fast. 

### Current result
The focus will be moved to the beginning of the page.

### Expected result
The focus will be moved to the next input

[Video here](https://www.screencast.com/t/ExDAFB8k)

**Comment by sspasova** [comment]
Closing this as the issue is no longer reproducible using Kendo 2023.3.1010 - https://dojo.telerik.com/UNUROTAb/2
