### ISSUE TITLE
Separators are added to tools in the Spreadsheet toolbar

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3513]
### Bug report
Even if the tools are not part of a group a separator is added to the left side of each tool. 

### Reproduction of the problem
Default tools: [example](https://dojo.telerik.com/EzikAC). 
Custom tools: [example](https://dojo.telerik.com/iYOtux).

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by mparvanov** [comment]
The tools which are part of a tool group are defined as an array.
https://docs.telerik.com/kendo-ui/api/javascript/ui/spreadsheet/configuration/toolbar

https://dojo.telerik.com/ISepaquG/2
