### ISSUE TITLE
Editor throws "TypeError: e is null" when third-party add-ons are enabled in Firefox 55+

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3515]
### Bug report

Third-party add-ons such as AutoFill Forms interfere with the iframe of the Editor and a "TypeError: e is null" exception is being thrown. The bug can be observed only in Firefox 55+ and cannot be reproduced with a simple editable content in iframe. 

### Reproduction of the problem

The issue can be observed [on the following Dojo example](http://dojo.telerik.com/@Dimitar.K/owAMo)

List of known add-ons that can trigger the error:

* Tampermonkey
* AutoFill Forms 0.3.2
* Privacy badger
* [Google Analytics Opt-out Add-on](https://tools.google.com/dlpage/gaoptout?hl=en)

### Current behavior

[Screencast](https://www.screencast.com/t/xfWcSJPmVqhj)

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** [Firefox 55]

**Comment by GaloisGirl** [comment]
Also triggered by [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)

Reproduction is as simple as opening the Editor's official demo page at http://demos.telerik.com/kendo-ui/editor/index . The editor doesn't show at all.

<img width="959" alt="kendouieditorff55ublock" src="https://user-images.githubusercontent.com/3268958/30165076-05d21e44-93df-11e7-8d10-cfeec2cbdc91.png">

**Comment by mparvanov** [comment]
@GaloisGirl Thanks for reporting another add-on that reproduce the issue with editor widget. We have already resolved the problem and the fix will be available in the next official release R3 2017 scheduled for the mid of September.
