### ISSUE TITLE
Widget's dropdown auto-closes in Chrome when a preceding element's height is reduced

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3516]
### Bug report
Reproducible in Chrome when the DropDownList (or any other dropdown widget) is placed at the bottom of a scrollable page and an element above it has its height reduced. 

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/oRESi) example. 
1. Scroll down. 
2. Click the button above the DropDownList.
3. Click the DropDownList: its dropdown opens and immediately auto-closes. 

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [Chrome 60 ]

**Comment by MarcoZama** [comment]
Can you help me to fix the problem?
Thank you!

**Comment by Dimitar-Goshev** [comment]
@MarcoZama The issue is not reproducible on my side with latest Kendo UI - 2018.1.117. I used the following [Dojo ](http://dojo.telerik.com/ESuqOV) for testing. Is the issue reproducible on your side with latest Kendo UI?

**Comment by byberkan** [comment]
I had similar issue and it was because of the min-height. Make sure you give some min-height based on your layout.
