### ISSUE TITLE
Wrong number rounding when cell format is applied to a formula

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3520]
### Bug report

When cell formatting is applied to a formula, the result rounding is incorrect (inconsistent with Excel).

![image](https://user-images.githubusercontent.com/16972160/29527208-db841250-86a0-11e7-821c-74037202bb21.png)

### Reproduction of the problem

The described behavior can be observed on [the following Dojo](http://dojo.telerik.com/AYija/9)

### Current behavior

Numbers are rounded correctly when formatting is applied on simple numbers, but incorrect when used on a formula.

### Expected/desired behavior

Should produce similar behavior to Excel.

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** [all]

**Comment by Juveniel** [comment]
There is still an issue with cell formatting for certain formulas. The issue can be observed in [this Dojo example](http://dojo.telerik.com/AYija/33), where the following inconsistencies with Excel can be observed:

* (-(86.4+18.23+4.47))*0.045 with 3 decimal places results in -4.09 in Kendo Spreadsheet / -4.10 in Excel
* 43.65*0.05 with 20 decimal places results in 2.18250000000000010658 in Kendo Spreadsheet / 2.18250000000000000000 in Excel

**Comment by Dimitar-Goshev** [comment]
The issue is still reproducible in certain cases, e.g. when the following formula is applied to a cell:
="aa"&2.53

Steps:
1. Go to http://demos.telerik.com/kendo-ui/spreadsheet/index
2. Click on an empty cell and paste the above formula.

**Expected:** aa2.53
**Actual:** aa2.5300000000000002

**Comment by Dimitar-Goshev** [comment]
After the latest fix, the above issues seem fixed, but there is a new issue when pasting formulas:
1. Use the Basic usage demo and click in an empty cell.
2. Type = , then paste the following numbers 43.65*0.05 and press Enter.

**Expected:** 2.1825 is calculated.
**Actual:** = is displayed in the cell, and '= is displayed in the formula bar, no calculation is performed.

**Comment by mishoo** [comment]
@Dimitar-Goshev seems like a different issue.  Any case, fix pushed.

**Comment by nenchef** [comment]
The bug seems to be reproducible again when using Round function:

https://www.screencast.com/t/ltefvUHBrj6K
