### ISSUE TITLE
Spreadsheet does not export content to PDF, when the browser window is too low and the page has been scrolled down on export

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3525]
### Bug
Spreadsheet does not export content to PDF, when the browser window is too low and the page has been scrolled down on export

### Reproduction of the problem
Video here (second part of the video):
![spreadsheetexportpdfscrolling](https://user-images.githubusercontent.com/3431388/29614427-c3cf20fa-8812-11e7-9e8a-546e79d827b8.gif)

Steps:
* Go to our [Spreadsheet Index demo](https://demos.telerik.com/kendo-ui/spreadsheet/index);
* Make the browser window below 300px;
* Click the Export.. button;
* From the drop-down select PDF;
* Scroll down and click "Save";
* The exported PDF will contain only cell styling with no values;

**Comment by marin-bratanov** [comment]
Manifests again in all browsers. Setting to critical and high priority because it does not allow exporting of content in many cases, and because it is a regression at this point. Reported in 1401736.
