### ISSUE TITLE
Floated tabs in TabStrip are moved to a new line on tab resize, scrolling is not triggered 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3529]
### Bug report
 The last 3 tabs are floated to the right. When tab4 size increases they are moved to a new line. Scrolling is triggered only if the tabs up to tab4 (including) do not fit the TabStrip's width. The floated do not affect the appearance of scroll buttons.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/IhajALaD) example. 
- Click "Grow Tab4" button

### Current behavior
Floated tabs are moved to a new line and their width is not taken into account by the scrollable tabs functionality. 

### Expected/desired behavior
Floated tabs are not moved to a new line and the scrollable functionality triggers when all tabs' combined width exceeds that of the TabStrip. 

### Environment

* **Kendo UI version:** 2019.3.1023

**Comment by sspasova** [comment]
The issue is fixed. Tested with Kendo UI version 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/IhajALaD/2
