### ISSUE TITLE
Spreadsheet opens only 200 rows from previously exported document

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#3530]
### Bug report

When opening a previously exported large spreadsheet, only 200 rows are displayed

1. Create an excel file with more the 200 row e.g. 600
2. Open [Spreadsheet demos](http://demos.telerik.com/kendo-ui/spreadsheet/server-side-import-export)
3. Click "open" in Spreadsheet toolbar button and select the excel file
4. Click "export" and save the file as excel file 
5. Click "open" and the file that you just saved.
6. Roll down to check if all rows is available

### Current behavior
Only 200 rows are displayed in spreadsheet while 600 rows are displayed if the document is opened in excel

### Expected/desired behavior
The rows number in spreadsheet matches the rows number of the initial spreadsheet - 600

Workaround: 
Set the rows to a grater value (the default is 200)
http://dojo.telerik.com/UnUFO/2

### Environment
* **Kendo UI version:** 2017.2.621

**Comment by veselints** [comment]
Also reported in Ticket ID: 1386378
