### ISSUE TITLE
Filtering is not working with Chinese and Japanese input in Firefox

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3531]
### Bug report

When trying to filter the data in the ComboBox, DropDownList or MultiSelect with Chinese and Japanese input, the filter does not trigger. This is reproducible only in Firefox.

### Reproduction of the problem

The issue can be observed on [the following Dojo example](http://dojo.telerik.com/@Dimitar.K/adaGa) in Firefox (Japanese input).

### Current behavior

[Screencast](https://www.screencast.com/t/hUqbBrF4n)

### Expected/desired behavior

If the input value is available in the widget DataSource, the dropdown list of the widget should be filtered accordingly.

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** [Firefox 55]

**Comment by zdravkov** [comment]
Worked correctly in FF 57 at my side.

**Comment by mparvanov** [comment]
The issue is not reproducible in 2017.621 with FireFox 57
https://www.screencast.com/t/4MBPxDWVM

**Comment by haifzhan** [comment]
It is not working on my side. If I replace Chinese with English, everything works fine.
