### ISSUE TITLE
Angular1 Grid with checkbox selection does not provide the data for all selected rows in the change event

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3532]
### Bug report

Angular1 Grid with checkbox selection does not provide the data for all selected rows in the change event.

### Reproduction of the problem

https://dojo.telerik.com/irUBoR

### Expected/desired behavior

Change event handler has the data for all the rows.
https://dojo.telerik.com/OTIza

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Xizario** [comment]
Isn't this by design? With checkbox selection the items should be available thru the selectedKeyNames property.
