### ISSUE TITLE
Filterable operators at grid level are ignored ASP.NET Core

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#3537]
### Bug report

Reported in ticket 1127125.

### Reproduction of the problem

Reproduces in the [official demos](http://demos.telerik.com/aspnet-core/grid/filter-menu-customization).

```
.Filterable(filterable => filterable
        .Extra(false) // extra works as expected
        .Operators(operators => operators // a full list of operators are still seen
            .ForString(str => str.Clear()
                .StartsWith("Starts with")
                .IsEqualTo("Is equal to")
                .IsNotEqualTo("Is not equal to")
            ))
        )   
```
### Current behaviour

Despite configuring only three operators, all operators are available in the FilterMenu

### Expected/desired behavior

Only the declared operators should be shown

### Workaround

Add the root configuration in a script tag before the grid initialization as demonstrated in the [documentation](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-filterable.operators) or declare them at column level
```
<script>
     kendo.ui.FilterMenu.fn.options.operators.string = {
       eq: "Equal to",
       neq: "Not equal to"
     };
</script>
```

### Environment

* **Kendo UI version:** 2017.2.621

**Comment by ag-petrov** [comment]
Duplicate item - https://github.com/telerik/kendo-ui-core/issues/2346
