### ISSUE TITLE
A JavaScript error occurs when changing the Chart examples on Edge(v40.*).

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3538]
### Bug report

A JavaScript error occurs when changing the Chart examples on Edge(v40.*).

**Unable to get property 'handleEvent' of undefined or null reference**

### Reproduction of the problem

The issue can be observed in our demos by changing the examples: http://demos.telerik.com/kendo-ui/area-charts/index'

More details and a video is available on the ticket: 1126972

### Environment

* **Browser:** [Edge v40.* ]

**Comment by MilenaCh** [comment]
Issue could not be replicated with: Microsoft Edge 40.15063.0.0 version.
