### ISSUE TITLE
KendoChart "pane.chartsVisual.insert"ed  Element vanishes on Zoom.

### ISSUE THREAD

**Issue by noc2spam** [telerik/kendo-ui-core#3539]
### Reproduction of the problem
**Documentation link:** http://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart
**derived from demo:** https://dojo.telerik.com/UwiTA

in this dojo, try zooming into the chart.
### Current behavior
the circle vanishes

### Expected/desired behavior
the circle should stay in the chart where it belonged.

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** 1.10.2
* **Browser:** all

**Comment by tsvetomir** [comment]
The pane visual will be re-rendered and any custom overlays will be reset. You can render them on `zoomEnd` to restore them, see [dojo](https://dojo.telerik.com/odoCo/3). There's a noticeable flicker, as the operation is async. We'll try to figure out a way to improve this in future versions.

The alternative would be to render the overlay on the chart visual, see [dojo](https://dojo.telerik.com/uguMif). This way it will survive repaints, but it overlays the series.

**Comment by noc2spam** [comment]
Makes sense, allthough I would love to see the improvement. As for now, the first dojo works for my client's needs so I will stick to that.

**Comment by matanasov** [comment]
@danielkaradachki @Stamo-Gochev @tsvetomir 
Do we plan "_We'll try to figure out a way to improve this in future versions._" or we can close this as won't fix?

**Comment by danielkaradachki** [comment]
We plan to add a paneRender event with which it will be possible to avoid the flicker and generally be used for rendering additional elements inside the updated elements.

**Comment by MilenaCh** [comment]
paneRender event was implemented for the scenario described in this issue.
