### ISSUE TITLE
Kendo Dashboard template project hangs in IE

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#3542]
### Bug report

Kendo Dashboard template project hangs in IE

### Reproduction of the problem
1. Create New Project in Visual Studio 2017 Kendo UI ASP.NET MVC 5 Application
2. Select DASHBOARD template
3. Run project in Internet Explorer

### Current behavior
The browser hangs when loading the index view.

Reported in ticket: 1127414

**Comment by kdikov82** [comment]
https://github.com/telerik/kendo-vsx-templates/commit/381a63e32f6eb7ae4fcd7956dfea1692000fe3fe
