### ISSUE TITLE
The initial value is not applied to Combobox when autoBind is set to false

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#3544]
### Bug report

The initial value of combobox set through the value property is not applied in case autoBind is set to false

### Reproduction of the problem
[https://dojo.telerik.com/aHufO/2
](https://dojo.telerik.com/aHufO/2
)
### Current behavior
The Combobox is empty. Once start typing or it is opened the value is applied.

### Expected/desired behavior
The combobox value Item1 is applied initially. Once start typing the custom input text remains in combobox.

Workaround: Set the initial value to the HTML element: http://dojo.telerik.com/@parvanov/UbEfEJ/3

### Environment

* **Kendo UI version:** The issue is regression since 2016.3.914

**Comment by zdravkov** [comment]
This seems to be the expected behavior of the widget. It is described and changed in[ this issue](https://github.com/telerik/kendo-ui-core/issues/1652). In case anybody whats to achieve similar behavior  the value method can be used and for example in [this dojo](https://dojo.telerik.com/aHufO/3).
