### ISSUE TITLE
Attributes could not be set for Custom tools in the Spreadsheet ToolBar

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3545]
### Bug report
Attributes cannot be set for Custom tools in the Spreadsheet ToolBar.
According to [the API reference](http://docs.telerik.com/kendo-ui/api/javascript/ui/spreadsheet#configuration-toolbar.home), *for all available options, see the toolbar items configuration: [http://docs.telerik.com/kendo-ui/api/javascript/ui/toolbar#configuration-items](http://docs.telerik.com/kendo-ui/api/javascript/ui/toolbar#configuration-items)*.
One of the configurable options is the *[items.attributes](http://docs.telerik.com/kendo-ui/api/javascript/ui/toolbar#configuration-items.attributes)*.
But setting attributes for a custom tool in the Spreadsheet causes *Maximum call stack size exceeded* error.

### Reproduction of the problem
Run the following [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/OcIBiTuX)

### Current behavior
JS error: `Maximum call stack size exceeded`

### Expected/desired behavior
No error and custom tool has title attribute applied

### Environment
* **Kendo UI version:** 2019.3.917
* **jQuery version:** not depending on specific jQuery version. Tested with 1.12.4, 3.4.1
* **Browser:** all

**Comment by veselints** [comment]
The *id* option and the *render* event could be used to workaround this issue:
````JavaScript
<div id="spreadsheet"></div>
<script>
  $("#spreadsheet").kendoSpreadsheet({
    render: function(e) {
    	$('#test').attr("title", "configuration");
    },
    toolbar: {
      home: [
        {
          type: "button",
          text: "Custom",
          spriteCssClass: "k-icon k-font-icon k-i-cog",
          click: function() {
            window.alert("custom tool");
          },
          id: "test"
        }
      ]
    }
  });
</script>
````

**Comment by eramella** [comment]
Would really need this to be fixed. Any chances to it can be done any time soon?

**Comment by Dimitar-Goshev** [comment]
Reported also in ticket 1432815.

@eramella We prioritize bugs based on their severity and priority and there is no ETA for fixing this issue. I increased the issues Priority based on your comment and another report and I also reassessed its severity.
