### ISSUE TITLE
fixedGroupTemplate not displayed in AutoComplete with virtualization enabled

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3548]
### Reproduction of the problem
[Dojo](http://dojo.telerik.com/uCEFas) example based on the virtualization demo with grouping and fixedGroupTemplate enabled. 

### Current behavior
Template is not displayed. 

### Expected/desired behavior
Template is displayed. 

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all  ]

**Comment by Dimitar-Goshev** [comment]
After a fix, the fixedGroupTemplate is initially applied, but if records are retrieved by scrolling down the dropdown, then the template is not applied anymore.

**Comment by Dimitar-Goshev** [comment]
The issue is fixed.
