### ISSUE TITLE
Box-sizing issue in window on mobile

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#3552]
Box sizing is not propagating correctly inside window on mobile devices:

![image](https://user-images.githubusercontent.com/8048/30013305-7f5935ec-914e-11e7-83cd-871496cd1360.png)

The issue in particular is due to pickers having height. Either remove height / change how height is set, or change the box sizing:

* original: http://dojo.telerik.com/@joneff/Umexo
* with fix: http://dojo.telerik.com/@joneff/Umexo/2

// TID 1127831

**Comment by mvgmvg** [comment]
related https://github.com/telerik/kendo/issues/7734
