### ISSUE TITLE
Chunk Upload throws error, when autoUpload is set to false and a file from the selected files is removed

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3553]
### Bug report
Chunk Upload throws error, when autoUpload is set to false and a file from the selected files is removed

### Reproduction of the problem
* Go to the following [Dojo](http://dojo.telerik.com/uXIxo/4);
* Select multiple files in the widget;
* Remove one of the files (not the last);
* Two calls to the *chunkSave* endpoint are made, *Cannot read property 'totalChunks' of undefined* is thrown on the console and the Upload will not upload the file, that follows the removed;

### Expected/desired behavior
The *chunkSave* endpoint should not be called. No errors should be observed and the file should be simply removed from the list.

**Comment by charettedavid** [comment]
Hi, any update on this issue? I currently experience the same problem. Thank you.

**Comment by IvanDanchev** [comment]
The same exception is thrown when removing all files by clicking on the Clear button
