### ISSUE TITLE
Spreadsheet does not export empty spaces added before existing cell content (xlsx client export)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3554]
### Reproduction of the problem
Reproducible in the [demos](http://demos.telerik.com/kendo-ui/spreadsheet/index). [Screencas](https://www.screencast.com/t/23Tyh7f0DVib)t.
1. Double-click a cell that has content. 
2. Add spaces before the existing content. 
3. Click the Spreadsheet's "Export..." button. Click "Save". 
4. Expected: the added spaces are exported in the generated file, actual: the spaces are missing in the exported file. 

The issue is reproducible when using the Spreadsheet's client export. The [server export](http://demos.telerik.com/kendo-ui/spreadsheet/server-side-import-export) exports the added spaces as expected.

### Current behavior
Spaces are not exported.

### Expected/desired behavior
Spaces are exported.

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by mishoo** [comment]
Works for me.  Am I missing something?

**Comment by IvanDanchev** [comment]
Screencast showing the behavior in question added to first post.

**Comment by jwbqv** [comment]
Hello, we urgently need this fixed in 2017 R3 SP1.     Thank you.
