### ISSUE TITLE
Kendo UI Custom Download missing dependencies

### ISSUE THREAD

**Issue by sssalib42** [telerik/kendo-ui-core#3555]
To reproduce: Create a Kendo UI Custom Download bundle, and choose UI grid with all it's subd-dependencies, including sortable!

The first major problem I faced is that the downloaded file doesn't contain a definition for kendo.all.min, or even kendo.custom.min like in the full kendo.min.all file. How are we expected to import kendo as a module, if the file doesn't export/define it?! I attempted to manually define it, except that I was faced with the following and second problem.

The bundle file does not include all the dependencies. For example, the kendo.sortable.min isn't defined in the file, even though it's listed in the list of dependencies of kendo.grid.min.

The full library is about 3 MB. The packages/sub-modules I need, result in a file of size 1MB, which is why I'm trying to use the custom download bundle.

The Kendo UI Custom Download is a very useful feature, but it seems like it was not properly tested. Please, please fix it.

Thank you.

**Comment by zdravkov** [comment]
Yes indeed, such combined file is not designed to export objects but rather define the window.kendo and only the desired functions and objects in it. This way you can import the script and then use the kendo instance from the window.
As for the sortable script - it is a bug indeed and we will do our best fix it soon
