### ISSUE TITLE
The ResponsivePanel closes immediately on mobile devices after it is opened in Chrome due to passive event listener

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3556]
### Bug report
The ResponsivePanel closes immediately after it is opened in Chrome due to a passive event listener.

"[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive"
https://www.chromestatus.com/features/5093566007214080

### Reproduction of the problem
The issue can be reproduced from our examples when tested in Chrome mobile mode:
http://docs.telerik.com/kendo-ui/api/javascript/ui/responsivepanel#configuration-breakpoint
1. Here is the respective sample in a [Dojo](https://dojo.telerik.com/aYiDIqaw)
1. Use a an Android mobile device or emulate it in Chrome.
1. Tap on the toggle button

### Current behavior
Responsive panel opens and closes immediately

### Expected behavior
Responsive panel opens and remains open

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [Chrome 70+]

Note:
Duplicate of [the following Kendo private issue](https://github.com/telerik/kendo/issues/7752)
Duplicate of the following Core issue: #3634

**Comment by InciteGmbH** [comment]
For us this is very important. When will it be fixed? Thanks a lot. Marc Huber

**Comment by veselints** [comment]
Raised priority as reported in Ticket ID: 1017840

**Comment by veselints** [comment]
The following issue represents a discussion on the topic - how jQuery should handle passive events: https://github.com/jquery/jquery/issues/2871.

**Comment by Ecarbone70** [comment]
I opened a ticket for this issue about 2 years ago and I received a workaround fas,t nothing to say. Now that I'm in the middle of a restyling of the web application and I upgrade to the last version i found that this issue is still there and so I have to apply the fix in every page. We use responsive panel for the global menu and to show particular filters for each page.

**Comment by smileytechguy** [comment]
@Ecarbone70 what was the workaround?

**Comment by Dimitar-Goshev** [comment]
@smileytechguy 
Excuse me for the late reply. The workaround is visible in the duplicated issues - [Workaround Dojo](https://dojo.telerik.com/azEcaLIG). The issue could be avoided by applying the following handler:
```JavaScript
$(".k-rpanel-toggle").on("touchend", function(e) { 
  e.preventDefault();
});
```
