### ISSUE TITLE
All day checkbox is not focused in  default edit form

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#3557]
### Bug report
http://demos.telerik.com/kendo-ui/scheduler/index 
(or the staging demo)

### Reproduction of the problem
1. Try to add event.
2. Press tab after the edit form is opened.
3. Try to navigate with Tab to all day checkbox.

### Current behavior

It is not possible to navigate to all day checkbox.

### Expected/desired behavior
It should be possible to navigate to all day checkbox.

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

**Comment by jivanova** [comment]
Fixed with Scheduler KeyBoard navigation enhancement.
