### ISSUE TITLE
Kendo CheckBox is not bound to field in Grid for .NET Core

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#3559]
### Reproduction of the problem
The issue can be replicated in our online examples where CheckBox is used for editing:

- [Inline Editing](http://demos.telerik.com/aspnet-core/grid/editing-inline)
- [Popup Editing](http://demos.telerik.com/aspnet-core/grid/editing-popup)

Video showing the problem - [https://www.screencast.com/t/CqIrDn96](https://www.screencast.com/t/CqIrDn96)

### Current behavior
The value in the CheckBox does not replicate the value in the field. The field in the dataSource cannot be edited.

### Expected/desired behavior
CheckBox should be bound to the boolean field in the DataSource

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by Alex-Bubblemaster** [comment]
Also reported in 1128849. Raising priority.
