### ISSUE TITLE
Filtering is not triggered when a selection is made from the QuickType keyboard on iOS

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3562]
### Bug report

When a choice is selected from [the QuickType keyboard](https://www.apple.com/my/ios/whats-new/quicktype/) on iOS, the ComboBox/DropDownList suggestions lsit is not being filtered.

### Reproduction of the problem

The described behavior can be observed on [the following Dojo](http://dojo.telerik.com/iSeBi/36)

Steps to reproduce:

* Select the ComboBox and type "ob"
* Select "obsessed" from the QuickType suggestions list

### Current behavior

No filtering occurs after a selection is made from the QuickType keyboard.

### Expected/desired behavior

Should filter the widget suggestions list if the selected item is available in the dataSource.

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** [iOS all]

**Comment by zdravkov** [comment]
Could not replicate it with the latest version.
