### ISSUE TITLE
Lost focus from Inline Editor's content area when using dropdown tools

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3564]
### Reproduction of the problem
Reproducible in this [demo](http://demos.telerik.com/kendo-ui/editor/inline-editing). 
1. Click somewhere within the content area of the upper Editor.
2. Click on the **Color** or **Background color** tools 
3. Expected: focus is not lost from the content area, actual: focus is lost. 

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
After the fix, the focus remains in the content area after the first time a color picker tool is applied. But if a color picker is expanded a second time, the focus is moved in the beginning of the content **in IE**. [Video](https://www.screencast.com/t/4S1p35gLt) Use the Inline editing demo for reproduction.
