### ISSUE TITLE
Kendo Menu should implement the aria-haspopup attribute 

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3566]
### Bug report
The `aria-haspopup` indicates that the item has a popup and helps with keyboartd navigation when using screen readers. 

### Current behavior
http://demos.telerik.com/kendo-ui/menu/keyboard-navigation

### Expected/desired behavior
This dojo example can be used as  a temporary workaround as well: http://dojo.telerik.com/ehUgu. 

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** all
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
The attribute is added to parent items on initial load. But if an item becomes a parent by adding child items to it through API or if its child items are removed, the attribute is not update. This could be tested on the Menu API demo.

Another issue related to aria attributes is that the **aria-disabled** attribute is not added initially to disabled items in MVC and Core wrappers. Inspect the last item News - http://demos.telerik.com/aspnet-mvc/menu , with the same item in the Kendo demo - http://demos.telerik.com/kendo-ui/menu/index . The good news is that the attribute is properly updated through API in both Kendo and the wrappers.

**Comment by Iankodj** [comment]
The case with  the aria-disabled is handled in different item as it will impact on other components as well. https://github.com/telerik/kendo-ui-core/issues/3646
