### ISSUE TITLE
SVG-rendered Chart stops responding after continuosly panning it on iOS

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#3567]
### Bug report

After continuously panning and zooming the Chart for some time on iOS, it stops responding to any gestures (pan, zoom). This happens to the SVG-rendered Chart only.

### Reproduction of the problem

Open [this Dojo](http://dojo.telerik.com/UkiHi/2) and quickly swipe left and right multiple times, lifting your finger off the screen between swipes. The chart will eventually freeze and stop responding to touch gestures.

### Environment

* **Kendo UI version:** 2017.2.621
* **Browser:** iOS Safari
Ticket id: 1129220

**Comment by tsvetomir** [comment]
The Chart will re-render its SVG elements on pan, thus breaking the touch event sequence. The only workaround is to use a Canvas - in this case, the element is not re-created.

Recommendation is to close as "Won't fix" and note in documentation.

**Comment by TsvetinaIvanova** [comment]
Issue documented in the following KB:
http://docs.telerik.com/kendo-ui/knowledge-base/chart-cannot-pan-and-zoom-continuously-on-mobile
