### ISSUE TITLE
Styling issues with Mobile Switch widget and others

### ISSUE THREAD

**Issue by cjpearson** [telerik/kendo-ui-core#3568]
### Bug report
Styling issues with Mobile Switch widget and others

Copied issues from the related issue, which is closed as duplicate:
There are a few issues in the Switch widget styles in recent versions, probably because of [this commit](https://github.com/telerik/kendo-ui-core/commit/b34ba55997038df682e0a6ceaec08ee2193b2d37).

* Switches show an unneeded border: [Dojo](http://dojo.telerik.com/odOfO/2)
* When using switches in a dark theme like Material, they show a light background:  [Dojo](http://dojo.telerik.com/odOfO).

* Web version of styles shows incorrect styles. This Dojo (opened from a demo) shows switches styles wth Nova styles showing the layout of the Flat theme with only the Nova color scheme: [Dojo](http://dojo.telerik.com/okOdE).

### Reproduction of the problem
The change [here](https://github.com/telerik/kendo-ui-core/commit/b34ba55997038df682e0a6ceaec08ee2193b2d37) adds additional k- prefixes to some mobile widgets and causes several styling issues. For example an unwanted border appears around the switch widget and can be seen in the [demo](http://demos.telerik.com/kendo-ui/m/index#switch/mobile).

This also breaks the box-sizing [flat](https://github.com/telerik/kendo-ui-core/blob/19e14edf3116950b3cbaae959ce8bd973fea3269/styles/mobile/flat/base.less#L31), [material](https://github.com/telerik/kendo-ui-core/blob/19e14edf3116950b3cbaae959ce8bd973fea3269/styles/mobile/material/base.less#L31), [nova](https://github.com/telerik/kendo-ui-core/blob/19e14edf3116950b3cbaae959ce8bd973fea3269/styles/mobile/nova/base.less#L75), and [ios7](https://github.com/telerik/kendo-ui-core/blob/19e14edf3116950b3cbaae959ce8bd973fea3269/styles/mobile/ios7/base.less#L50) themes which use the k- prefix to identify web widgets.

Is it possible to revert this change or make it optional so mobile applications will not receive the incorrect styles?

### Current behavior
Mobile switch widget is treated as a web widget by the mobile themes.

### Expected/desired behavior
Mobile switch widget is treated as a mobile widget by the mobile themes.

### Environment

* **Kendo UI version:** 2017.1.118, 2017.2.621
* **jQuery version:** 2.1.4
* **Browser:** All

**Comment by joneff** [comment]
We have mostly overhauled the switch for the current release. As a result, it appears that the issues are fixed with latest official version:
* nova http://dojo.telerik.com/@joneff/UXIJoSEH
* material http://dojo.telerik.com/@joneff/OQOJAJEK

One more thing, even with the older versions it's quite easy to "fix" the issues. You just need to load the files for the theme, and not the default ones: both nova and material themes require a different common file, so when you mix default common and material (nova) common it's not unexpected to have issues.
