### ISSUE TITLE
The width of a Multiheader column is changed after reordering if the first column in the group is hidden.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3572]
### Bug report

The width of a Multiheader column is changed after reordering if the first column in the group is hidden.

### Reproduction of the problem

The issue can be observed in the following Dojo: http://dojo.telerik.com/ehoxO.

Notice how after the Multeheader column is reordered, its widht is changed. Then if the Contact Name column is not hidded, the width will remain the same after reordering.

### Environment
* **Browser:** [all]

**Comment by simonssspirit** [comment]
Additional information provided in the ticket:
Kendo.all.js Line 48866 value of colSourceIndex is -1 when first column in Multi-Column header is hidden.  This causes the column width(s) in the grid to get scrambled.

            _reorderContent: function (sources, destination, before) {
                var that = this;
                var lockedRows = $();
                var source = sources[0];
                var visibleSources = visibleColumns(sources);
                var sourceIndex = inArray(source, leafColumns(that.columns));
                var destIndex = inArray(destination, leafColumns(that.columns));
                var colSourceIndex = inArray(source, visibleLeafColumns(that.columns));
                var colDest = inArray(destination, visibleLeafColumns(that.columns));
                var lockedCount = lockedColumns(that.columns).length;
                var isLocked = !!destination.locked;
                var footer = that.footer || that.wrapper.find('.k-grid-footer');
                var headerCol, footerCol;
                headerCol = footerCol = colDest;

**Comment by TsvetinaIvanova** [comment]
Additionally, if you lock the first column and drag the multi-column header to the locked area, depending on the position, one of the following happens:
1) The first locked column disappears.
2) The second column from the multi-column header group disappears.

Dojo: [http://dojo.telerik.com/@tsveti/ObIjob/9](http://dojo.telerik.com/@tsveti/ObIjob/9)
