### ISSUE TITLE
Wrong horizontal scrolling in a navigatable RTL Grid 

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3574]
### Bug report

Wrong horizontal scrolling in a navigatable RTL Grid 

https://www.screencast.com/t/mmJhcm6UAHuP

### Reproduction of the problem

http://dojo.telerik.com/ifuVu

### Expected/desired behavior

The grid scrolls to the selected/navigated cell.

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ag-petrov** [comment]
Not reproducible with the latest version - http://dojo.telerik.com/ifuVu/4
