### ISSUE TITLE
TreeList multiple selection selects collapsed child rows

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#3578]
### Bug report

If you collapse a parent row and do Shift-selection between it and its following sibling, all children of the collapsed parent get selected.

### Reproduction of the problem
See Dojo: [http://dojo.telerik.com/UzaKA](http://dojo.telerik.com/UzaKA)
-Minimize the row for Guy Wooten
-Select that row so it is highlighted
-Holding SHIFT select the row for Priscilla Frank
-At this point all the children of Guy are incorrectly selected (This can be shown by right clicking the expand arrow of Guy's row. A left click will both expand Guy's row and force selection to just it)

### Current behavior
All hidden children rows between the two parent rows are selected as well

### Expected/desired behavior
Only the visible higher level rows should be selected

### Environment

* **Kendo UI version:** 2017.2.621

Reported in ticket: 1129921

**Comment by ag-petrov** [comment]
This is not a bug and is the design behavior. If selecting the child records is not desirable I suggest logging a feature request so we could add an option that would enable such selection conditionally.
