### ISSUE TITLE
Refactor toolbar phone layout

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3579]
### Bug report

With the PDF button added in the toolbar (https://github.com/telerik/kendo-ui-core/issues/2206) the view dropdown overlays other buttons.

![image](https://user-images.githubusercontent.com/4222379/30419222-41f5abfc-993e-11e7-919b-f91eab3f49d4.png)

Playground: /playground/mobile/adaptive-scheduler.html

### Environment

* **Kendo UI version:** 2017.913
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by joneff** [comment]
Fixed by telerik/kendo@a53bca2

**Comment by joneff** [comment]
To reproduce, use `mobile: "phone"` in the widget configuration. As a positive side effect, when viewing the said scheduler, the view switcher is not squashed.

**Comment by Dimitar-Goshev** [comment]
After the fix, there are issues reproducible with smaller themes, such as LESS Default, on iPhone 5 viewport size, or with larger themes, such as Material, on iPhone 6.

- timelineWeek and timelineWorkWeek views are on two rows:
![image](https://user-images.githubusercontent.com/6614183/33376230-91323326-d515-11e7-828e-cc345726c176.png)

- timelineWorkWeek view is on two rows in the views dropdown:
![image](https://user-images.githubusercontent.com/6614183/33376252-aab88174-d515-11e7-9d49-c8965f12f711.png)

- When timelineWorkWeek view is present, the dropdown moves to the left on expanding:
![image](https://user-images.githubusercontent.com/6614183/33375264-09c8576a-d512-11e7-875e-8bdfa5b8ffd6.png)

**Comment by Dimitar-Goshev** [comment]
As of R2 2019 this issue is no longer valid. The improved Scheduler adaptive rendering changes the Export to PDF button to a small icon only button, thus there is no overlap:
![image](https://user-images.githubusercontent.com/6614183/60806280-444e0280-a18b-11e9-8e33-891d9696dafe.png)
