### ISSUE TITLE
Disabled Treeview Node gets checked/unchecked when checking/unchecking parent

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-ui-core#3581]
### Reproduction of the problem
[http://dojo.telerik.com/OqULi](http://dojo.telerik.com/OqULi)
The node has been set as disabled by setting `enabled: false` in the array. But when the parent node is checked/unchecked, the disabled node is also checked/unchecked.

### Expected/desired behavior
The checked state of the disabled node should stay the same unless the node is enabled again.

### Environment

* **Kendo UI version:** 2017.3.913
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
After a fix, it is not possible to uncheck child nodes' checkboxes through their parent's checkbox in **IE and Edge**, if one of the child nodes is disabled.
