### ISSUE TITLE
Pressing Space closes DropDownList popup when filtering is enabled

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#3583]
### Bug report

[http://demos.telerik.com/kendo-ui/dropdownlist/serverfiltering](http://demos.telerik.com/kendo-ui/dropdownlist/serverfiltering)

[DOJO](http://dojo.telerik.com/@jivanova/IBAZe )- workaround provided here

### Reproduction of the problem
1. Expand the DropDownList
2. Press SpaceBar

### Current behavior
DropDownList popup closes

### Expected/desired behavior
DropDownList popup remains opened and filter is applied

### Environment

* **Kendo UI version:** 2017.3.913
* **Browser:** all

**Comment by jfreal** [comment]
The work around is not relevant to the dropdown space at all.

Maybe the wrong workaround link was added?

**Comment by jfreal** [comment]
Here is the correct work around if anyone else lands here: 

```
<script>
  var keyDown = kendo.ui.DropDownList.prototype._keydown;
  kendo.ui.DropDownList.prototype._keydown = function (e) {
    if (e.keyCode === kendo.keys.SPACEBAR && this.filterInput[0] === document.activeElement) {
      return;
    }
    keyDown.call(this, e);
  }
</script>
```
