### ISSUE TITLE
How to resolve kendovalidator is undefined in after html data in form ?

### ISSUE THREAD

**Issue by Sathiyamm** [telerik/kendo-ui-core#3584]
# **file1.cshtml**

<form id="driver" name="Customer" method="post">
    <div>
        <p>@Html.TextBoxFor(m => m.Email, new { required = "required", placeholder = "Email", id = "cust-email", maxlength = 255 })</p>
        <label id="lbl-cust-email-error" class="error error-label-style">@Html.ValidationMessageFor(m => m.Email)</label>
        <small class="field-tip">Use your real email address. We don't spam.</small>
    </div>
<div>
            <input id="submit-cust" type="submit" value="Join"/>
        </div></form>

# **file2.cshtml**

<div id="Customeridentity" hidden="hidden" class="registration_form_element">
                                    @Html.Partial("_file1")
                                </div>
 <script>
$("body").on("click", "#submit-cust", function () {
var formValidator = $("form#driver").data('kendoValidator');
if(formValidator.validate()){
$.ajax({
                            type: 'POST',
                            url: '@Url.Action("IsCustomerModelStateValid", "Account")',
                            data: form.serialize(),
                            success: function (data) {
                                isClickedJoinFreightRover = false;
                                if (data.IsValid) {
                                    $(".field-validation-error").hide();
                                    var registerUrl = '@Url.Action("RegisterCustomer", "Account")',
                                }
                                else {
                                    $('#Customeridentity').html(data);
}
}
});
}
});
</script>

> 

first time click with wrong data kendo validator is working.
After $('#Customeridentity').html(data) append and next again submit the kendo validator is undefined error show.The data is coming same form and with error value.

What I have tried:

I have tried almost all possibility
![file1](https://user-images.githubusercontent.com/30838274/30430677-9744deee-9979-11e7-81e5-8c0bda672abb.png)
![file2](https://user-images.githubusercontent.com/30838274/30430684-9ea25306-9979-11e7-9968-9b2062a6831d.png)

![kendoval](https://user-images.githubusercontent.com/30838274/30430294-6651a8e0-9978-11e7-824d-51aca2e5e56e.png)

**Comment by matanasov** [comment]
For support related issues consider Kendo UI support [main page](http://www.telerik.com/support/kendo-ui)
