### ISSUE TITLE
In the MVC Grid, if the refresh button is clicked with middle click, the data from the read action will be shown in new window.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3585]
### Bug report

In the MVC Grid, if the refresh button is clicked with middle click, the data from the read action will be shown in a new window.

### Reproduction of the problem

It can be observed in our demos: http://demos.telerik.com/aspnet-mvc/grid
In the demo, a server error will be thrown as this type of GET requests are not allowed.

As a workaround the href attribute of the page-refresh button can be replaced:

```
$(document).ready(function () {
            $(".k-pager-refresh").attr("href", "#")
});
```

**Comment by ag-petrov** [comment]
By design the refresh button renders the read url as a href. Altering it may cause a breaking change which is not desirable. If the described behavior is not desired I suggest integrating the above workaround.
