### ISSUE TITLE
flat theme is no more flat (has background-image: url(textures/highlight.png);)

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#3586]
### Bug report

Flat theme has 3D texture:

![image](https://user-images.githubusercontent.com/2556751/30443012-0153a49a-9976-11e7-8c2c-0d90badae532.png)

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by joneff** [comment]
The problem resides in the theme. We'll fix the theme and it will be applied in the Less Themebuilder with the next update.

**Comment by joneff** [comment]
Gradient can be disabled by choosing "flat" from Texture dropdown

**Comment by Dimitar-Goshev** [comment]
Not reproducible with R3 2019 SP1.
