### ISSUE TITLE
Spreadsheet PDF export adds extra column to the exported area, when right border is set for the last active column

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3587]
### Bug report
Spreadsheet PDF export adds extra column to the exported area, when right border is set for the last active column. This bug is a regression, introduced with the R2 2017 release

### Reproduction of the problem
Can be reproduced on the [Index demo](https://demos.telerik.com/kendo-ui/spreadsheet/index);
Video [here](https://www.screencast.com/t/3G93kPKmUzq)

### Environment
* **Kendo UI version:** - from 2017.2.504 on

**Comment by jwbqv** [comment]
Thank you 👍    We are blocking from upgraded due to this bug so it's really critical for our project to have a fix in the SP.
