### ISSUE TITLE
Adaptive grid cuts off last records and pager with scrollable:false

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#3595]
### Bug report

As reported in Ticket ID: 1129332 

### Reproduction of the problem

Try [Dojo](http://runner.telerik.io/fullscreen/aqoTO) on a mobile device.

### Current behaviour

It is impossible to scroll to the bottom of the grid.

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** 1.12.3
* **Browser:** tested with [Chrome iOS | IE | Safari ]

**Comment by theOrlin** [comment]
This is not a bug. The adaptive rendering of the grid places it in a pane which does not auto stretch past the height of the screen thus preventing scrolling. There are two options for the pane of the mobile grid, either with set height or in an auto stretch mobile application. It is all described in the documentation: http://docs.telerik.com/kendo-ui/controls/data-management/grid/adaptive#pane-configuration
