### ISSUE TITLE
Inconsistent margin-left values of the Menu's dropdown arrows 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3601]
### Bug report

Dropdown arrows of the MVC Menu's root items and submenu items have inconsistent margin-left values, which causes the arrow to be displayed too close to the item's text in most of the themes (except Default v2, Bootstrap v4, Fiori and Office365). 

Workaround: 
```
<style> 
.k-i-arrow-s, .k-i-arrow-e {
  margin-left: 5px !important;
}
</style>
```

### Reproduction of the problem
Reproducible in our [demos](http://demos.telerik.com/aspnet-mvc/menu/orientation). 

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by mvgmvg** [comment]
Forwarded for retesting.
