### ISSUE TITLE
Incorrect AutoComplete popup position

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#3602]
### Bug report

A certain combination of settings (popup origin and position and animation open) breaks the layout of autocomplete. It's either a bug or invalid combination of settings.

### Reproduction of the problem

1) Open https://dojo.telerik.com/@joneff/iZOrU
2) Enter "a" in autocomplete
3) delete

### Current behavior

The popup is positioned on top of autocomplete

### Expected/desired behavior

The popup should be positioned properly.

### Environment

* **Kendo UI version:** 2015.3.930 - 2017.3.913
* **Browser:** All

**Comment by zdravkov** [comment]
Related with this issue - #1568
