### ISSUE TITLE
Values list is separated from the widget after scrolling with jQuery 2.2.0 and Chrome 61

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3604]
### Bug report

If the DropDownList is opened after scrolling down the page, the values list appears separated from its parent. 

### Reproduction of the problem

The issue can be observed on [the following Dojo example](http://dojo.telerik.com/ENobEQ/4).

### Current behavior

[Screencast](https://www.screencast.com/t/zj04IcQr).

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** 2.2.0
* **Browser:** [ Chrome 61 ]

**Comment by IvanDanchev** [comment]
Reproducible in IE11 and Firefox as well.

**Comment by joneff** [comment]
The issue seems to be related to jQuery 2. Does not happen if we use jQuery 1.12.3

**Comment by joneff** [comment]
From a customer report: it seems that the issue is not present in jQuery 2.2.4.

**Comment by zdravkov** [comment]
The issue seems to be caused by a bug in the 2.2.0 version of jQuery and is fixes with 2.2.1 version.
