### ISSUE TITLE
MVVM Grid missing schema.model.id 

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3605]
### Bug report

MVVM Grid missing schema.model.id. PersistSelection functionality depends on this.

### Reproduction of the problem

http://dojo.telerik.com/ACUBo

### Expected/desired behavior

The Grid takes the model ID from the definition and persistSelection works as expected.

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by TsvetinaIvanova** [comment]
Also encountered by another customer. Ticket id: 1132572.
