### ISSUE TITLE
new function kendo.parseExactDate is not documented and missing from TypeScript definitions

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#3608]
### Reproduction of the problem
Latest release added function for exact date parsing, but it wasn't added to documentation (http://docs.telerik.com/kendo-ui/api/javascript/kendo) or TypeScript definitions.

### Current behavior
function is not documented

### Expected/desired behavior
Function documented and exposed to TypeScript users

### Environment

* **Kendo UI version:** 2017.3.913

**Comment by Xizario** [comment]
related to, https://github.com/telerik/kendo-ui-core/issues/3476
