### ISSUE TITLE
KendoPager is not responsive on Internet Explorer 10

### ISSUE THREAD

**Issue by SuperPat45** [telerik/kendo-ui-core#3610]
### Bug report
I noticed that the KendoPager component is not responsive on IE10 while it support an older version of the flexbox specifications.

The responsive KendoPager use these two properties:
```
            display: inline-flex;
            flex-direction: column-reverse;
```
The support could be provided under IE10 by adding these two properties:
```
            display: -ms-inline-flexbox;
            -ms-flex-direction: column-reverse;
```

### Current behavior
KendoPager is not responsive on IE 10

### Expected/desired behavior
KendoPager should be responsive on IE 10

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** 3.2.1
* **Browser:** IE 10

**Comment by joneff** [comment]
Fixed by 09690566ec3a73ccce77e3d6e15a4e74f6854948 and https://github.com/telerik/kendo/commit/ef4a9754e13d902bcbf97b07b99fb48191060df0
