### ISSUE TITLE
Inconsistent AutoComplete and ComboBox height within ToolBar template in IE 

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#3613]
### Bug report
**Regression since R3 2017.**
When AutoComplete and ComboBox are used within ToolBar template, in IE they are not as high as when used outside the ToolBar.

The issue is caused by height set as follows
`.k-ie .k-toolbar .k-input { height: 1.65em }`

A workaround for the issue is to set greater height as follows - [Dojo](http://dojo.telerik.com/etEJIM):
```
  <style>
    body {font-family: sans-serif; font-size: 14px; }
    .k-ie .k-toolbar .k-autocomplete .k-input { height: 2em }
    .k-ie .k-toolbar .k-combobox .k-input { height: 2em }
  </style>
```

Note: the issue is not reproducible with DropDownList or NumericTextBox

related https://github.com/telerik/kendo/issues/7734

### Reproduction of the problem
Use the following [Dojo](http://dojo.telerik.com/aDUri)

### Current behavior
AutoComplete and ComboBox are NOT as high as when used outside the ToolBar:
![image](https://user-images.githubusercontent.com/6614183/30742435-ab61c95e-9fa1-11e7-95b9-e241a38f79f8.png)

### Expected/desired behavior
AutoComplete and ComboBox are as high as when used outside the ToolBar - **OK with 2017.2.621**

### Environment

* **Kendo UI version:** 2017.3.913
* **Browser:** [IE]

**Comment by mvgmvg** [comment]
fixed by the following pull request: https://github.com/telerik/kendo/pull/7742
