### ISSUE TITLE
If the NumericTextBox has a invalid value, it will not change the $valid status of the AngularJS form

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3614]
### Bug report

If the NumericTextBox has an invalid value, it will not change the $valid status of the AngularJS form.

### Reproduction of the problem

It can be observed in the following Dojo: http://dojo.telerik.com/EcurE

The invalid number can be "."

A workaround could be to programmatically set the input as invalid: http://dojo.telerik.com/ISewUY

### Environment

* **Browser:** [all]

**Comment by Xizario** [comment]
Another workaround:
replace `minlength="1"` with `pattern="/\d+/"`

**Comment by JonathanCRUL** [comment]
Neither solution work in IE. The Save button remains disabled in IE.

**Comment by JonathanCRUL** [comment]
Is there a way to setup a keypress for the NumericTextBox in the dojo example.

**Comment by Xizario** [comment]
@JonathanCRUL you can use the keypress event of the input element:
[http://dojo.telerik.com/AJoNI](http://dojo.telerik.com/AJoNI)
But keep in mind that the NumericTextBox also handles these events:
https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.numerictextbox.js#L184-L188
If suitable, it would be better to use the change event of the widget:
http://docs.telerik.com/kendo-ui/api/javascript/ui/numerictextbox#events-change

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
