### ISSUE TITLE
Spreadsheet validation pop-up appears twice

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3615]
### Bug report
Spreadsheet validation pop-up appears twice.

This is regression introduced in with the R3 2017.3.913 release

### Reproduction of the problem
The issue could be observed on the [Validation Demo](https://demos.telerik.com/kendo-ui/spreadsheet/validation)

### Environment
* **Kendo UI version:** from 2017.3.913

**Comment by adrobyazko-softheme** [comment]
Hello @veselints , @mparvanov 
It seems - it not fixed completelly - it still reprodusable for Kendo UI version: 2017.3.1026
Here is reported issue https://github.com/telerik/kendo-ui-core/issues/3850.
Could you please provide solution?

**Comment by Dimitar-Goshev** [comment]
@adrobyazko-softheme 
The issue is no longer reproducible with R3 2018 SP1 (2018.3.1017)
