### ISSUE TITLE
Changing font size in spreadsheet is slow

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#3626]
Based on customer feedback

> I'm on a spreadsheet, i select all the rows and columns in the spreadsheet and then i change the font size from 11 to 12 or 14, it takes me around 20 seconds or more to update the style

![5af99fee-c31b-4bb5-a7e0-91fb1d11558f_ox-sheet](https://user-images.githubusercontent.com/8048/30908224-a00bbf8c-a385-11e7-961a-26a0a47482fb.gif)

TID: 1131732

**Comment by mishoo** [comment]
Closing as duplicate of #2582.
