### ISSUE TITLE
Input in Pager is higher than dropdown in Fiori theme

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#3628]
### Bug report

The pager layout is wrong with Fiori theme: : page selector drop down and number of pages dropdown are not aligned and have different heights. Also the first misses the dropdown icon.

### Reproduction of the problem

Run https://dojo.telerik.com/ejARad/8 + resize browser

![2017-10-02_1644](https://user-images.githubusercontent.com/4389590/31080336-135623a6-a791-11e7-92aa-b8a17b4c3dbb.png)

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jlchereau** [comment]
Note that type-fiori.less is missing in https://github.com/telerik/kendo-ui-core/tree/master/styles/web, but this can be fixed as follows (which matches type-office365.less)

Anyway at Line 2796, change

```
 .k-pager-wrap
{
    // min-height: 3.8em;
    min-height: 2.2em;
}
```

At line 2809, change

```
.k-pager-numbers,
.k-grid .k-pager-numbers {
        position: absolute;
        left: 5em;
        display: inline-flex;
        flex-direction: column-reverse;
        // margin-top: 6px;
        overflow: visible;
        height: auto;
        transform: translatey(-100%);
}
```

And at line 2859, change:

```
.k-pager-wrap .k-pager-numbers .k-current-page .k-link {
    width: 3.8em;
    line-height: 1.429em;
    // padding: 0.643em .429em 0.643em 0.8em;
    padding: 0.3em .429em 0.3em 0.8em;
    border-radius: @border-radius;
    .composite-background(@widget-gradient);
    background-position: 50% 50%;
    background-color: @drop-down-background;
    border: 1px solid @widget-border-color;
}
```

**Comment by mvgmvg** [comment]
Updated Dojo sample (and screenshot) to use kendo.common-fiori.min.css instead of kendo.common.min.css
