### ISSUE TITLE
Material theme: kendo.ui.Pager does not display well

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#3629]
### Bug report

The pager layout is wrong with Material themes: page selector drop down and number of pages dropdown are not aligned and have different heights. Also the first misses the dropdown icon.

See also (for a fix): https://github.com/telerik/kendo-ui-core/issues/3628

### Reproduction of the problem

Run https://dojo.telerik.com/ejARad and resize.

![image](https://user-images.githubusercontent.com/2556751/30914598-28ab3fb0-a38c-11e7-8a29-347ef6561096.png)

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jlchereau** [comment]
Ti fix this (except the missing dropdown icon) In type-material.less, remove line 3393

```
.k-pager-numbers .k-current-page .k-link {
    width: 3.8em;
    // line-height: 2.564em;
    padding: 0 .429em 0 0.8em;
    border-radius: @border-radius;
    .composite-background(@widget-gradient);
    background-position: 50% 50%;
    background-color: @drop-down-background;
    border: 1px solid transparent;
    border-top: 0;
    .box-shadow(0 2px 2px 0 @drop-down-background);
}
```

**Comment by mvgmvg** [comment]
Regarding to [this ](http://docs.telerik.com/kendo-ui/styles-and-layout/appearance-styling#common-css-files)article, Material theme should use kendo.common-material.css instead of kendo.common.css
