### ISSUE TITLE
Automatic  pdf.defineFont does not work in MacOS

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#3633]
### Bug report

The automatic  pdf.defineFont is not working correctly on Chrome MacOS.

### Reproduction of the problem
dojo - [http://dojo.telerik.com/OhAge/6](http://dojo.telerik.com/OhAge/6)
The underline is not correct on the exported file

ticket - 1131114

workaround - trigger the pdf.defineFont manually [dojo](http://dojo.telerik.com/OhAge/25)

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** x.y
* **Browser:** [Chrome MacOS ]

**Comment by Iankodj** [comment]
Not reproducible
