### ISSUE TITLE
toJSON does not return the correct columns count

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#3637]
### Bug report

[import - export demo](https://demos.telerik.com/kendo-ui/spreadsheet/server-side-import-export)

### Reproduction of the problem
In the demo there are 5 columns initially
1. Fill several cells in the sheet next to the initial ones (ex: 2)
2. Press Save As JSON

### Current behavior
The columns in the JSON remains 5 regardless of the newly added cells values.

### Expected/desired behavior
The columns in the JSON should be updated to 7

### Environment

* **Kendo UI version:** 2013.3.913
* **Browser:** all

**Comment by mishoo** [comment]
That happens because columns E, F, etc. have the default width, while A, B, C and D have custom widths in that demo.  If you resize column E, for instance, then an entry for it will be present in the JSON `columns` property.

Not a bug, but feature! ☺
