### ISSUE TITLE
Escape calc() functions that use variables in less themes to prevent wrong compiling

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-ui-core#3638]
### Bug report
Calc() function that uses variables are wrongly compiled by some compiler. To prevent the issue, the function should be escaped.

Reported in ticket 1132257.

/cc @joneff

**Comment by crazyfx1** [comment]
I had the same issue. As a workaround you can use the "--strict-math=on" parameter on your less compiler.
