### ISSUE TITLE
Editor's serializer reorders attributes of the inserted tags in an alphabetical order.

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3639]
### Bug report

The execution of the insertHtml command reorders the attributes of the inserted link. 

### Reproduction of the problem
[http://dojo.telerik.com/@nenchef/eGOzA/5](http://dojo.telerik.com/@nenchef/eGOzA/5)
The above dojo example exhibits the issue

### Current behavior
The attributes of the inserted link are alphabetically reordered.

### Expected/desired behavior
The order of the attributes should remain as the initially inserted ones.

### Environment

* **Kendo UI version:** 2017.3.913
* **Browser:** [all]

**Comment by Iankodj** [comment]
If someone's logic depends on the attributes to be ordered alphabetically, a [serialization.custom](http://docs.telerik.com/kendo-ui/api/javascript/ui/editor#configuration-serialization.custom) function can be implemented after this fix for that to bring back the old behavior. 

http://dojo.telerik.com/aGUGUF
