### ISSUE TITLE
Target .NETStandard 2.0 for Telerik.UI.for.AspNet.Core

### ISSUE THREAD

**Issue by NikolayIT** [telerik/kendo-ui-core#3640]
### Current behavior

Currently the NuGet package `Telerik.UI.for.AspNet.Core` targets `.NET Framework 4.5.1` as well as `.NET Standard 1.6` but this is causing msbuild compiler warnings when referencing kendo core wrappers from projects that target .NET Standard 2.0:

```Warning	MSB3277	Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.```

### Expected/desired behavior

Kendo to be able to be referenced without warnings in .NET Standard 2.0 projects.

**Comment by zdravkov** [comment]
Hi Niki, 

I have tested the issue by creating different TelerikAspNetCore applications, but could not replicate the issue. It seems like the warning is observed only when some specific libraries are referenced. Would you please elaborate which references should be added to observe the issue or try to isolate the issue in some sample application?

**Comment by NikolayIT** [comment]
Sure, this is my project file `********.Web.Infrastructure.csproj` that causes the warning:

	<Project Sdk="Microsoft.NET.Sdk">

	  <PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
	  </PropertyGroup>

	  <PropertyGroup>
		<CodeAnalysisRuleSet>..\..\Rules.ruleset</CodeAnalysisRuleSet>
	  </PropertyGroup>
	  <ItemGroup>
		<AdditionalFiles Include="..\..\stylecop.json" />
	  </ItemGroup>

	  <ItemGroup>
		<PackageReference Include="AutoMapper" Version="6.1.1" />
		<PackageReference Include="CsvHelper" Version="3.0.0-RC04" />
		<PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta004" />
		<PackageReference Include="Telerik.UI.for.AspNet.Core" Version="2017.3.913" />
	  </ItemGroup>

	  <ItemGroup>
		<ProjectReference Include="..\..\********.Common\********.Common.csproj" />
		<ProjectReference Include="..\..\Services\********.Services.Common\********.Services.Common.csproj" />
	  </ItemGroup>

	</Project>

`********.Services.Common.csproj` looks like:

	<Project Sdk="Microsoft.NET.Sdk">

	  <PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
	  </PropertyGroup>

	  <PropertyGroup>
		<CodeAnalysisRuleSet>..\Rules.ruleset</CodeAnalysisRuleSet>
	  </PropertyGroup>
	  <ItemGroup>
		<AdditionalFiles Include="..\stylecop.json" />
	  </ItemGroup>

	  <ItemGroup>
		<PackageReference Include="AutoMapper" Version="6.1.1" />
		<PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta004" />
	  </ItemGroup>

	</Project>

and `********.Common.csproj` looks like:

	<Project Sdk="Microsoft.NET.Sdk">

	  <PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
	  </PropertyGroup>

	  <PropertyGroup>
		<CodeAnalysisRuleSet>..\..\Rules.ruleset</CodeAnalysisRuleSet>
	  </PropertyGroup>
	  <ItemGroup>
		<AdditionalFiles Include="..\..\stylecop.json" />
	  </ItemGroup>

	  <ItemGroup>
		<PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta004" />
	  </ItemGroup>

	</Project>

**Comment by zdravkov** [comment]
I have tested once again the issue, with the additional references that you provided, but unfortunately still could not observe it at my side. In such cases in order be more helpful we recommend opening a support ticket and continuing the research there.
