### ISSUE TITLE
Pressing the arrow keys during editing navigates to neighboring cells

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#3644]
### Description

In Excel, you can start typing directly in the focused cell. In this mode, the user can finish editing using arrow keys. This behavior works also when cell is dbclicked.
Steps:
1. Focus cell
2. Start typing directly
3. Press LEFT arrow

Note that when cell is put in edit mode using F2, this behavior should not work.

**Comment by Dimitar-Goshev** [comment]
https://github.com/telerik/kendo/issues/4920

**Comment by Dimitar-Goshev** [comment]
When tested with Excel 2016, editing behavior is as follows:
- If an **empty or non-empty cell** is focused with **single click**, pressing Arrow keys moves the focus to another cell.
- If an **empty cell** is focused with **double click**, pressing Arrow keys moves the focus to another cell.
- If a **non-empty cell** is focused with **double click**, pressing Arrow keys moves the caret inside the currently edited cell.

In the context of Kendo UI Spreadsheet, **double click** on a **non-empty cell** should work as pressing F2 - arrow keys should move the caret inside the cell, not navigating to another cell.

**Comment by Dimitar-Goshev** [comment]
After the fix, testing editing and navigation in Spreasheet works as described above for Excel.
But in IE, if a single character is entered in a cell, it is not applied to that cell and its content becomes empty.
Steps to reproduce:
1. Go to Spreasheet / Basic usage demo.
2. Focus a cell either by clicking/double-clicking or moving the focus with arrow/Tab keys.
3. Type **a** in the cell.
4. Confirm the entry by pressing Enter/Arrow key/Tab.

**Expected** - the cell contains **a** as an entry.
**Actual** - the cell is empty.

**Comment by mishoo** [comment]
@Dimitar-Goshev fixed that, though I have no idea what could have caused the issue.
