### ISSUE TITLE
DropDownList does not return any results when filter is cleared

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3651]
### Bug report

No results are being returned after the filter input is completely cleared.

### Reproduction of the problem

The issue can be reproduced with [this DropDownList Virtualization Demo](http://demos.telerik.com/aspnet-mvc/dropdownlist/virtualization) and is only reproducible with the Kendo UI for ASP.NET MVC Wrappers (works fine in ASP.NET Core).

### Current behavior

[Screencast](https://www.screencast.com/t/GbNASOwUprVL)

### Expected/desired behavior

When the filter is cleared, all of the available items in the DataSource of the widget should be displayed.

### Environment

* **Kendo UI version:** 2017.3.913
* **Browser:** [all]

**Comment by mparvanov** [comment]
The fix has been reverted with the following commit:
https://github.com/telerik/kendo/commit/dbaf10f077cf34cb3be6b1e1df75982870a5d668

**Comment by Juveniel** [comment]
Potential workaround:

```cs
public ActionResult Virtualization_Read([DataSourceRequest] DataSourceRequest request)
{
  if (request.Filters.Count > 0 && (request.Filters[0] as FilterDescriptor).Value.ToString() == "")
  {
    request.Filters.Remove(request.Filters[0]);
  }
  
  return Json(GetOrders().ToDataSourceResult(request));
}
```
