### ISSUE TITLE
Model property name causes an exception, when accessing that property. 

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3659]
### Bug report

Exception is raised in kendo#getter/kendo#setter as result of invalid expression, returned by kendo#expr.

### Reproduction of the problem

Use the following dojo example:

[http://dojo.telerik.com/@nenchef/atACi/2](http://dojo.telerik.com/@nenchef/atACi/2)
The dojo example contains a workaround, which is why you need to set the  var ENABLE_FIX to false

Reported in ticketID: 1133731

### Current behavior

JS exception is thrown in kendo#getter/kendo#setter as result of invalid expression, returned by kendo#expr

### Expected/desired behavior
No exception should be thrown

### Environment

* **Kendo UI version:**2017.3.913
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Work as expected with the latest version - https://dojo.telerik.com/ocUXiwOH
