### ISSUE TITLE
Overlay distorts over disabled widgets in Chrome

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3661]
### Bug report

Overlay (.k-overlay) distorts when there are disabled elements on the page. This behavior can only be reproduced in Chrome.

### Reproduction of the problem

[Dojo example](http://runner.telerik.io/fullscreen/EGuziB). 

Steps to reproduce:

* Disable the Upload widget
* Open the modal Window
* Drag the window over the Upload container

### Environment

* **Kendo UI version:** 2017.3.913
* **Browser:** [ Chrome ]

**Comment by Juveniel** [comment]
The issue can be resolved by adding backface-visibility to .k-overlay:

```CSS
.k-overlay {
  -webkit-backface-visibility: hidden;
} 
```

**Comment by mvgmvg** [comment]
The issue is caused by overlapping two elements with opacity.

**Comment by valcs007** [comment]
We ran into the same distorted issue. Can you please let me know when can we expect a new patch fr this issue?
