### ISSUE TITLE
DatePicker (DateInput?) changed event is not reliably triggered when clearing contents

### ISSUE THREAD

**Issue by jaxidian** [telerik/kendo-ui-core#3665]
## Reproduction of the problem
A simple repro of the bug can be found here with all repro steps in the example. https://dojo.telerik.com/EcaWi

*Redundant info:*
1. Run this Dojo: https://dojo.telerik.com/EcaWi
2. Immediately after page loads, without doing anything else, select text in the DateInput field with your mouse.
3. Hit your backspace key
4. Click on the white background to make the field lose focus
5. Observe that no alert window pops up. This is the bug!
6. Expected behavior: alert('changed'); should have ran.
7. If you go use the calendar control to select a date, you'll get an alert.
8. If you then highlight the text again, delete it, and click away, you'll get the alert again.

### Environment

* **Browser:** I have tested on updated Chrome, Edge, and Android Chrome. I stopped testing browsers at that point.

**Comment by matanasov** [comment]
@jaxidian 
Although you see the date set in the picker, it is actually empty because setting it to a string value is not valid. Note that the [`value`](https://docs.telerik.com/kendo-ui/api/javascript/ui/datepicker/configuration/value) property requires a `date` object.
