### ISSUE TITLE
Grid Filter not cleared on filter click

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3669]
### Bug report

When you use a filter and you successfully filter a column, if you open the filter again, remove the filtering text and click the filter button - nothing happens.

Same behavior as 
https://github.com/telerik/kendo-ui-core/issues/3263

### Reproduction of the problem

1. http://dojo.telerik.com/aMipi
2. name -> filter -> starts with -> "Jan" -> filter button
3. name -> filter ->"empty string" -> filter button

### Current behavior

The filter event does not fire.

### Expected/desired behavior

When the filter string is empty and the "Filter" button is clicked, the filtering is cleared.

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by PreslavKozovski** [comment]
workaround: https://dojo.telerik.com/oKoPE

**Comment by MilenaCh** [comment]
The problem still exists.
