### ISSUE TITLE
Incorrect events' top position calculation when an all day event is present in the same timeslot of a vertically grouped Scheduler in Timeline Month View

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#3671]
### Bug report
The top position of events is calculated wrong when an all day event is present in the same timeslot. This is reproducible only for vertically grouped Scheduler in Timeline Month View. As a result a resource may occupy may rows on the Scheduler, instead of only two.

### Reproduction of the problem
1. [Dojo](https://runner.telerik.io/fullscreen/@Dimitar-Goshev/aVimuKoT)
1. In Timeline Month View create several events on June 06 for Room 201 / Charlie resources
2. Create an all day event on June 06 for Room 201 / Charlie resources

### Current behavior
In Timeline Month View - The non-all day events fall on separate rows as if they are all day events as well.
![image](https://user-images.githubusercontent.com/6614183/61138262-d3328600-a4cf-11e9-9e81-333d7793cf28.png)
NOTE: If the all day event is deleted, then the non-all day events are on one row.

### Expected/desired behavior
In Timeline Month View - The non-all day event are on ONE row below the all day event, as in Timeline Week View for example.
![image](https://user-images.githubusercontent.com/6614183/61138566-75eb0480-a4d0-11e9-9ae5-16bf417a0b91.png)

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** all

**Comment by tylerorchestratellc** [comment]
I was wondering if there was any timeline as when this bug may get addressed. Thank you for any information you can provide.

**Comment by Dimitar-Goshev** [comment]
@tylerorchestratellc The issue is still reproducible with 2019.2.619. I cannot provide a timeframe for fixing it as we are fixing issues based on their priority and severity. Currently we are working on higher priority issues.

**Comment by ag-petrov** [comment]
Seems to be working fine in the latest version - https://runner.telerik.io/fullscreen/OmiFeVuy
