### ISSUE TITLE
Draggable. AutoScroll: true brakes scrolling in Chrome 61 and Edge

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3678]
### Bug report
Kendo Draggable: **autoScroll: true** brakes scrolling in Chrome 61 and Edge

### Reproduction of the problem
* Run the following [Dojo](https://dojo.telerik.com/AWiLe/5);
* Drag one of the items to the bottom of the visible container and hold it there;
* The item will start to jump up and down. Even the container has a scrollbar, the element won't scroll.

[Video here](https://www.screencast.com/t/JfqHocD05i7)

### Environment
* **Browser:** [ Chrome 61 | Edge ]

**Comment by zdravkov** [comment]
Could not replicate it with the latest version.
