### ISSUE TITLE
DropDownList scroll position is not reset if optionLabel is set

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3679]
### Bug report
If an item is selected in DropDownList, on opening its dropdown it is scrolled to the selected item, which is expected.
If no item is selected at all, which is achieved by setting optionLabel, the scroll position of the dropdown should be reset back to top, if the DropDownList is blurred between closing it and consecutive reopening

**NOTE:** regression since 2015.1.318
Its previous behavior can be seen on this [Dojo ](http://dojo.telerik.com/IPUqoD)- 2014.3.1411

### Reproduction of the problem
1. Go to https://dojo.telerik.com/edAvE
2. Expand the first DropDownList - it has optionLabel.
3. Scroll down to bottom.
4. Blur the dropdown by clickin on Products heading above it.
5. Expand the dropdown again

### Current behavior
Dropdown is scrolled to bottom.

### Expected/desired behavior
Dropdown is scrolled back to top, as there is no selected item.

**NOTE:** Also reproducible in a [Cascading DropDownList scenario](http://demos.telerik.com/kendo-ui/dropdownlist/cascadingdropdownlist). 
1. Select "Beverages" in the first DDL. 
2. Click the second DDL scroll to the last item and select it. 
3. Click the first DDL and select "Condiments"
4. Click the second DDL.
**Expected:** since there is no selected item the scroll position should be reset.
**Actual:** the list is scrolled to the bottom (the scroll position is not reset)

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by rahmanpdvl** [comment]
Any updates on this issue?

**Comment by Dimitar-Goshev** [comment]
@rahmanpdvl The issue is still not fixed, as its status shows. I updated its description and tracked it down to version 2015.1.318 , when it started to reproduce.

**Comment by rahmanpdvl** [comment]
Any update on this issue? If we remove the optionlabel scroll position is getting reset.But our requirement is should have the optionLabel.

**Comment by Dimitar-Goshev** [comment]
@rahmanpdvl There are no updates on this issue.
