### ISSUE TITLE
Update the kendo.timezones.js to respect recent changes

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3680]
### Bug report
A change for the Asia/Omsk and Asia/Novosibirsk timezones has been introduced. [Here you could find further information about the change](https://support.microsoft.com/en-us/help/3182203/september-2016-time-zone-change-for-novosibirsk).

The information about America/Santiago is also wrong. The daylight saving changes for 2018 are set to be on 2018-04-29 and 2018-09-02, while in fact they are on 2018-05-13 and 2018-08-12.

Review for any other timezone changes.

Update the kendo.timezones.js to respect all recent changes.

**Comment by bronhee** [comment]
The data from [npm package tzdata](https://github.com/rogierschouten/tzdata-generate/blob/master/dist/tzdata/timezone-data.json) is close to kendo's zones and rules format from kendo.timezones.js.

The difference is that tzdata stores unnecessary null values in some zone arrays.
See [kendo.core.js#L3692](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.core.js#L3692)

```
var until = zoneRules[idx][3];

if (until && utcTime > until) {
```

Variable `until` can be _undefined_ when use kendo zones and can be _null_ when use tzdata zones.

This replacement to tzdata zones and rules fixes my issue with timezone 'Asia/Novosibirsk':
Before `kendo.timezone.offset(new Date(), 'Asia/Novosibirsk'); // = -360`
After `kendo.timezone.offset(new Date(), 'Asia/Novosibirsk');  // = -420`

**Comment by bronhee** [comment]
Time zones that present in tzdata and not present in kendo:
- America/Fort_Nelson
- America/Punta_Arenas
- Asia/Atyrau
- Asia/Barnaul
- Asia/Famagusta
- Asia/Tomsk
- Asia/Yangon
- Europe/Astrakhan
- Europe/Kirov
- Europe/Saratov
- Europe/Ulyanovsk
- Factory
- Pacific/Bougainville


Time zones with different offset in tzdata and kendo:

time zone|kendo|tzdata
--- | --- | ---
America/Caracas|270|240
America/Montevideo|120|180
Antarctica/Casey|-480|-660
Asia/Baku|-300|-240
Asia/Chita|-480|-540
Asia/Gaza|-120|-180
Asia/Hebron|-120|-180
Asia/Magadan|-600|-660
Asia/Novosibirsk|-360|-420
Asia/Pyongyang|-540|-510
Asia/Sakhalin|-600|-660
Pacific/Norfolk|-690|-660



https://dojo.telerik.com/uWipa/6

**Comment by veselints** [comment]
Timezone definitions for Brazil are also out-of-date, as they have skipped daylight saving change in November 2019.
Reported in Ticket ID: 1441659

**Comment by veselints** [comment]
Europe/Istanbul is also outdated. Since September 2016 they no longer change the clock and stay only in the daylight saving zone EEST which becomes TRT:
https://www.timeanddate.com/time/zone/turkey/istanbul
