### ISSUE TITLE
Disabled ToolBar button in a buttonGroup is hidden

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3684]
### Bug report

Disabled button (enable: false) as part of a buttonGroup are hidden instead of being displayed as disabled. This behavior has been introduced in R3 2017.

Workaround:
```
    <style>  
        .k-button-group .k-state-disabled {
          display: inline-flex;
        }
    </style>
```

### Reproduction of the problem
[Dojo](http://dojo.telerik.com/eLUmu) example.

### Current behavior
Disabled buttons are hidden.

### Expected/desired behavior
Disabled buttons are displayed.

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
After the implemented fix, it is possible to click the disabled button (its styles are changed on click).

**Comment by Dimitar-Goshev** [comment]
It is still possible to click the disabled button (its styles are changed on click), when they are inside the overflow dropdown. Test the following button group inside and outside the overflow:

```
{
    type: "buttonGroup",
    buttons: [
        { icon: "align-left", text: "Left", togglable: true, group: "text-align", enable: false },
        { icon: "align-center", text: "Center", togglable: true, group: "text-align" },
        { icon: "align-left", text: "Left", togglable: false, group: "text-align", enable: false },
        { icon: "align-center", text: "Center", togglable: true, group: "text-align" },
        { text: "Right", togglable: true, group: "text-align", enable: false },
        { text: "Right", togglable: true, group: "text-align" },
        { text: "Right", togglable: false, group: "text-align", enable: false },
        { text: "Right", togglable: false, group: "text-align" },
    ]
},
```
