### ISSUE TITLE
Recurrence events are not shown with ShowBusinessHours or startTime set

### ISSUE THREAD

**Issue by ivanchev** [telerik/kendo-ui-core#3685]
Steps to reproduce

1) go to http://demos.telerik.com/aspnet-core/scheduler/index
2) click on "SHOW BUSINESS HOURS" on the scheduler, to display only the business hours range
3) double-click on the 4:00pm hours on Tuesday (for example), to add a new appointment; the dialogs open
4) set up repeat "weekly"
5) Save the appointment.

If you use the same approach to create a single event, it will be shown.

**Comment by veselints** [comment]
Also reported in Ticket ID: 1137282

**Comment by folia2001** [comment]
Hi, we are experiencing the same exact issue with the recurrence rule.  We have a previous version (2017.3.1026).  Is there any chance of getting a FIX for this without having to renew the entire product?

Any ideas? 

Thank you in advance.

**Comment by Dimitar-Goshev** [comment]
@folia2001 I am afraid that patching bugs for older Kendo UI versions is not supported.
