### ISSUE TITLE
RTL-Support for PivotGrid

### ISSUE THREAD

**Issue by iPazooki** [telerik/kendo-ui-core#3686]
Hello,
I am using Kendo UI, recently I have been trying to  test **PivotGrid**. due to my research I didn’t find any resources showing RTL-Support for PivotGrid.
Does pivotGrid support RTL? Does it work fine with Arabic and Persian?
if so would you please show me a documentation, guide or sample to set it up?
Thank you in forward

**Comment by matanasov** [comment]
@theOrlin 
Can you verify whether PivotGrid widget has support for RTL? Some of its features share RTL styles with Grid, Menu and other widgets, but I couldn't find dedicated RTL styles for the PivotGrid widget.

**Comment by theOrlin** [comment]
The PivotGrid does not support RTL at this time. Please submit a feature request at the [Feedback portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback).
