### ISSUE TITLE
The columns container in the Grid ColumnMenu is not scrollable with the mousewheel.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3687]
### Bug report

The columns container in the Grid ColumnMenu is not scrollable with the mousewheel.

The issue is introduced in the current version 2017.2.504.

### Reproduction of the problem

The issue can be observed in the following Dojo:  http://dojo.telerik.com/iBOca

1) Open the columnMenu
2) Open the Columns section
3) Try to scroll with the mousewheel.

__The same issue is observed for the ForeignKey column filtering, where the DropDownList could not be scrolled with the mouse wheel__:
[http://dojo.telerik.com/EpErI](http://dojo.telerik.com/EpErI)

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** [all]

**Comment by simonssspirit** [comment]
A similar issue can be observed in the filter container in the following how-to example:

https://docs.telerik.com/kendo-ui/controls/data-management/grid/how-to/filtering/checkbox-filter-menu.html

Reported in ticket: 1136311

Rising the priority.

**Comment by simonssspirit** [comment]
The issue is also reported in ticket:  1138895

More details, it only occurs on the filterable column, not on all.

Rising the severity.

**Comment by Stamo-Gochev** [comment]
The issue seems to be introduced after the fix in https://github.com/telerik/kendo-ui-core/issues/2923

**Comment by mparvanov** [comment]
The issue is still reproducible:
http://kendobuild-staging.openstack.progress.com/dojo-staging/IFuma/2
