### ISSUE TITLE
kendo.parseDate method does not parse correctly abbreviated ja-JP months

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#369]
### Description

The abbreviated month names in `ko-KR`, `ja-JP` and `vi-VN` are digits, which breaks the current logic.

Repro demo: http://dojo.telerik.com/@ggkrustev/AKAKe/2

Reported in TicketID: 874722

**Comment by ivanchev** [comment]
Issue is no longer reproduced, both with the version it's logged with, and with the latest version. Closing.
