### ISSUE TITLE
Improved array formulas support in Spreadsheet

### ISSUE THREAD

**Issue by mishoo** [telerik/kendo-ui-core#3691]
Currently the formula engine supports [array formulas](https://support.office.com/en-us/article/Guidelines-and-examples-of-array-formulas-7d94a64e-3ff3-4686-9372-ecfd5caa57c7), but does so unconditionally, which can create [confusion](https://github.com/telerik/kendo-ui-core/issues/3606) when it happens by accident.  To implement proper support we would need the following:

- [x] formulas should fill a single cell by default, even if the returned value is a matrix.

- [x] when F2 is pressed, the editor should allow creating an “array formula” when Ctrl-Shift-Enter is pressed.  The selection range must be stored in the formula object (will be the formula's affected range).

- [x] when saving an array formula, original data in the affected range should be saved for undo purposes.

- [x] array formulas should fill cells in the affected range only.

- [x] JSON support (should persist/restore the affected range) - initialization from JSON and serialization to JSON.

- [x] XLSX support (Excel does this: `<f t="array" ref="D1:D11">B1:B27/A1:A27</f>`) - proper client-side importing and exporting of array formulas from/to Excel.

- [x] it should not be possible to edit cells in a formula's “affected range”.

- [x] update [documentation](https://docs.telerik.com/kendo-ui/controls/data-management/spreadsheet/end-user/list-of-formulas#array-formulas)

**Comment by Dimitar-Goshev** [comment]
I am closing this issue. Its currently known problems are logged here - https://github.com/telerik/kendo/issues/7873
