### ISSUE TITLE
Groupable grid with locked columns gets misaligned (out of sync) 

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#3694]
### Bug report

Similar behaviour reported in thread 1134480. 
![image](https://user-images.githubusercontent.com/10980842/31709748-9aa522aa-b3fb-11e7-970b-bc9ebf0f1e34.png)

### Reproduction of the problem

- Add a locked column in a groupable grid
- Group by two fields
- Remove one of the groups
[Dojo](http://dojo.telerik.com/EfEQEG)

### Current behaviour

The locked and unlocked tables are out of sync 

### Expected/desired behavior

The locked and unlocked grouping rows should be resynced. Uncomment the dataBound handler to see the fix as suggested in [this forum thread](https://www.telerik.com/forums/kendo-grid-locked-column-and-grouping#q3Opr55VC0qLJ4IMGSLbrw):

```
dataBound: function(e){
  this._applyLockedContainersWidth();
  this._syncLockedContentHeight();
  this._syncLockedHeaderHeight();
}
```
### Environment

* **Kendo UI version:** 2017.3.913

**Comment by MilenaCh** [comment]
The issue still could be replicated in some scenarios:
Example:
http://kendobuild-staging.openstack.progress.com/dojo-staging/oJOfE
1.Group by UnitsOnOrder
2.Group by ProductName
3.Remove UnitsOnOrder

Video:
https://www.screencast.com/t/XXBFmJ9r7y2S

**Comment by MilenaCh** [comment]
The commit has been reverted, because the test(added in the commit) was failing in FireFox.
https://github.com/telerik/kendo/commit/4a06a3f1379ee4da5970ee4236730eabab0d6c41#diff-f810c335b76ea2e4d78327457f230a46
