### ISSUE TITLE
Update toolbar overflow button icon from arrow to the three-points vertical one

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-ui-core#3703]
Overflow button icon of toolbar should be replaced by three-points vertical icon.

**Comment by mparvanov** [comment]
The overflow button icon is missing for hybrid widget:
http://kendobuild-windows.openstack.progress.com/kendo-ui/m/index#navbar/adaptive-toolbar 
Live:
http://demos.telerik.com/kendo-ui/m/index#navbar/adaptive-toolbar
