### ISSUE TITLE
Using Vue components in the templates of the Vue wrappers

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3704]
Research and implement a native way to have Vue templates for the widgets' templates and use Vue components inside them.

**Comment by zdravkov** [comment]
Related to this [issue](https://github.com/telerik/kendo-vue-wrappers/issues/182).

**Comment by cjpearson** [comment]
@zdravkov, I can't see the linked issue. Is there a public place to follow this work?

**Comment by zdravkov** [comment]
We have added this functionality and it will be available from the upcoming R1 2018 that is expected next week.

**Comment by cjpearson** [comment]
Cool, thanks!

**Comment by badams2527** [comment]
I'm trying to use some custom components inside the column templates of the Grid.  Is there any documentation on how to use this? Or is this issue not covering that kind of functionality?

**Comment by mchikhaoui** [comment]
is there any sample for that ? thanks!

**Comment by zdravkov** [comment]
Here is how you can use native Vue templates with Kendo Vue UI:

1. Include and register the component:

```
import Template from './Template.vue'
var itemTemplate = Vue.component(Template.name, Template)
```

2. Define the template as function that returns object:

```
itemTemplate: function (e) {
      return {
        template: itemTemplate,
        templateArgs: e
      }
    }
```

3. If the item arguments are needed in the template they should be registered in the data object as for example in this sample template:
```
<template>
   <div>
      <button @click="buttonClick">{{templateArgs.text}}</button>
  </div>
</template>

<script>

export default {
  name: 'template1',
  methods: {
    buttonClick: function (e) {
      alert(1)
    }
  },
  data () {
    return {
      templateArgs: {},
      itemText: 'template'
    }
  }
}
</script>
```
I am also attaching a sample project here:
[my-project-test.zip](https://github.com/telerik/kendo-ui-core/files/1715821/my-project-test.zip)


We will do our best to add nice documentation about this feature as soon as possible.

**Comment by mchikhaoui** [comment]
@zdravkov thank you 👍

**Comment by mchikhaoui** [comment]
@zdravkov , it's works fine with wrapper, but not when try using it in script block like that : 
```
columns:[{field:"name", title:"Name", width:"250", template: e => {
          return {
            template: itemTemplate,
            templateArgs: e
          }
        }
        }]
```

**Comment by zdravkov** [comment]
Yes - currently only passing the template function as a prop is supported for this scenario.

**Comment by mchikhaoui** [comment]
thank you for this quick answer.

**Comment by Etheryte** [comment]
@zdravkov Why are only props supported at the moment? The data binding logic should be very similar. Also, why is data passed to the template by what is literally a hack, manually setting the internal data? The correct way would be to use props for this.

**Comment by zdravkov** [comment]
Hi all, 

Straight to the questions:
@mikecole :  First of all, please excuse me for not reaching out earlier - [headerTemplate](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/columns.headertemplate) in the grid column does not pass any parameter to the function and that is why with the current implementation we can't send meaningful data with the Vue wrapper either. In such case you will have to define the columns one by one. You could also submit a feature request with the useful data that could be passes in the parameter for possible implementation in the future.

@Etheryte :  yes indeed, this is how the templates are implemented in Kendo Vue wrappers at the moment. We have tested and thought about different ways of adding support for native Vue templates and this was the one that worked best against all our tests with Kendo widgets. If you have some concrete idea for improvements or you meet some scenario that is not working correctly please submit a new issue with detailed information about it so we could be able to inspect it deeper and provide appropriate answer.

If you are Vue and Kendo fans you could also vote and share thoughts [on this issue](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/33871774-vue-native) and what would you expect from such native Vue components.

Greetings

**Comment by ivanchev** [comment]
@blueTeddy Please use the [forum](https://www.telerik.com/forums/kendo-ui-vue/general-discussions) or the support channel.

**Comment by uoc1691** [comment]
When I use this approach for kendo treeview, template component uses the args passed last.  So last item is duplicated for all nodes on the same level. Didn't do anything special. Similar code as the example.

**Comment by zdravkov** [comment]
Hey, @uoc1691 ,

Thank you for reaching out - for such questions we recommend using our [forums](https://www.telerik.com/forums/kendo-ui-vue/general-discussions). It will also be more helpful if you share the exact code that you are using or isolate the issue in a plunker or sample project so it could be easily replicated.

**Comment by uoc1691** [comment]
@zdravkov We've already created a support ticket for this. Here's a sample
[kendo-with-vuex-bug-template-duplicate-nodes.zip](https://github.com/telerik/kendo-ui-core/files/2227126/kendo-with-vuex-bug-template-duplicate-nodes.zip)
