### ISSUE TITLE
Grid columnMenu filtering throws an exception when a column is filtered two times and the field contains a dot

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3714]
### Bug report

Grid columnMenu filtering throws an exception when a column is filtered two times and the field contains a dot.

This behavior is replicable **only** with the latest Kendo UI version(2017.3.1018)

### Reproduction of the problem

1. http://dojo.telerik.com/aKuRaR
2. Click on the ColumnMenu -> filter -> 1
3. Click on the ColumnMenu

### Expected/desired behavior
No errors should be thrown.

### Environment

* **Kendo UI version:** 2017.3.1018
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ag-petrov** [comment]
Again reported in ticket  - 1136339

**Comment by hadjieva** [comment]
Reported in ticket: 1137224 as well
