### ISSUE TITLE
Virtually scrollable and navigatable grid jumps up and down and rebinds too many times 

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#3715]
### Bug report

Reported in ticket with ID 1136677
Comment from ticket 1136938:
```
The scrollbar jumps up and down. I guess it is caused because the grid tries to keep the focused row within the visible area (or something like that).

Scroll a few pages down and try to get row at the end of the grid where only the upper part (50%) is visible. If you click it, you'll see that the grid is scrolling very fast up and down.
```
### Reproduction of the problem

[Dojo with 2017.3.1018](http://runner.telerik.io/fullscreen/IJOTI) rebinds profusely after the first request on mouse wheel
[Dojo with 2017.2.621](http://runner.telerik.io/fullscreen/eNUCe) works correctly

http://dojo.telerik.com/IJOTI
http://dojo.telerik.com/eNUCe

### Current behavior

Numerous rebinds occur since our R3 release with the virtually scrollable and navigatable Kendo UI Grid. This behaviour occurs only with a mouse wheel, the scrollbar behaves as expected. 

### Expected/desired behavior

As in R2

### Environment

* **Kendo UI version:** from 2017.3.913

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket 1136938

**Comment by MilenaCh** [comment]
It is not possible to scroll to the bottom if click on some cell and start scrolling using mouse wheel.
