### ISSUE TITLE
Kendo.Mvc.Examples utilizing wrong System.Web.Mvc version for MVC5 solution

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3716]
### Bug report

Mismatch in the System.Web.Mvc version referenced in Views/Web.config in the Kendo.Mvc.Examples solution for VS2013/VS2015/VS2017. This leads to an error "HtmlHelper does not contain a definition for Kendo" in the application views, thus no intellisense.

### Current behavior

![image](https://user-images.githubusercontent.com/16972160/31996522-821d7fca-b991-11e7-9220-a6aeb42a68f7.png)

### Expected/desired behavior

Proper version of System.Web.Mvc should be referenced in Views/Web.config

```razor
 <host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc, Version=5.0.0.0" />
```

**Comment by haithemaraissia** [comment]
Any updates?

**Comment by Dimitar-Goshev** [comment]
@haithemaraissia The issue is still reproducible.

**Comment by Dimitar-Goshev** [comment]
This issue is not reproducible anymore.
