### ISSUE TITLE
Menu sub-menu does not open on hover in IE and Edge with jQuery 1.10.2

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3717]
### Bug report
Menu sub-menu does not open on hover in Firefox, IE and Edge with jQuery 1.10.2 and jQuery 2.0.0 to 2.1.0 included.

This is a regression introduced with Kendo UI version R2 2017.2.504

### Reproduction of the problem
1. Go to [Dojo](http://dojo.telerik.com/OzINO)
1. Hover over a root menu item with sub-items

### Current behavior
Sub-menu items are NOT expanded.

### Expected behavior
Sub-menu items are expanded.

### Environment

* **Kendo UI version:** from 2017.2.504 on
* **jQuery version:** jQuery 1.10.2, jQuery 2.0.0 to 2.1.0
* **Browser:** [ IE, Edge, Firefox 62.0.0]

**NOTE: The issue is not reproducible in Firefox with Kendo UI version 2018.2.516+**

**Comment by IvanDanchev** [comment]
Firefox 59.0.2 added to the list of browsers

**Comment by mgunko** [comment]
Any updates on when this issue will be resolved?

**Comment by jivanova** [comment]
@mgunko The issue is scheduled for our next SP (R3 SP 2018). Item will be updated accordingly once it passes our testing procedures.
