### ISSUE TITLE
When a ListBox is initialized in a page after a Calendar widget, it breaks the Calendar selection

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#3719]
### Bug report
When you initialize a ListBox after a Calendar, the Calendar selection no longer works
[Dojo](http://dojo.telerik.com/@tsveti/eCorO)

### Reproduction of the problem
Open the Dojo and try to do selection in the Calendar. If you move the `kendoCalendar` call after the `kendoListBox` call, the issue is no longer there.
### Environment

* **Kendo UI version:** 2017.3.1026
Reported in: 1137173

**Comment by zdravkov** [comment]
It seems to be connected with the selectable: "multiple" property of Calendar because when it is removed it works correctly.
