### ISSUE TITLE
Unexpected Tooltip hiding on hovering its content

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3721]
### Bug report
Regression since 2017.3.913 (R3 2017).
When you try to hover the content of a Tooltip, it is automatically being hidden. 

### Reproduction of the problem
[Dojo example](http://demos.telerik.com/kendo-ui/tooltip/index)

### Current behavior
Tooltip hides when its content is hovered.

### Expected/desired behavior
Tooltip should be visible when hovering over its content.

### Environment
* **Kendo UI version:** 2018.3.911
* **Browser:** [all]

**Comment by joneff** [comment]
I've traced the issue to a commit last year by @dtopalov 22a63dcce1cbbeb402ea5e7867a256712e6d4a0b.

**Comment by ariolaaltus** [comment]
Hi

Any idea when the fix for this issue will be rolled out?

Thank you

**Comment by joneff** [comment]
Just a quick update on what exactly is happening: when the tooltip is shown either here, or in the related example, the mouse enters the tooltip element and leaves the anchor element. That causes the tooltip to hide. But then, the mouse is on the anchor element again and we get into this vicious circle.

What needs to be done is the following:

* we need to add offset property to the popup that allows the popup to be positioned slightly off from the given coordinates
* the tooltip should use the said offset property to compensate for the callout, when it's present
* most importantly, when when leaving the anchor, we should take into consideration if the mouse has entered the tooltip

**Comment by Juveniel** [comment]
A fix for the issue will be included in the next Latest Internal Build and with 2019 R2 release. The fix includes two new properties for the Tooltip:

* offset - specifies the offset in pixels between the Tooltip and the anchor. 
* hideAfter - specifies the delay in milliseconds before the Tooltip is hidden
