### ISSUE TITLE
Token with string empty for dataTextField are not displayed correctly in MultiSelect

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#3723]
### Bug report

If dataTextField is empty string, the item is not rendered correctly In the MultiSelect input field. The item is rendered very tiny and the close button is not visible. 

### Reproduction of the problem
[Dojo example](https://dojo.telerik.com/oHiLA)

### Current behavior
Items with empty string for dataTextField are not displayed correctly.

### Expected/desired behavior
The item with string empty for dataTextFiled should be with the same height as the rest of the items and the close button should be visible.

### Environment

* **Kendo UI version:** 2017.3.1018
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
- After a fix is applied, tokens are higher than expected in Fiori, Material, Material Black and Nova themes.
- When a token is chosen, the MultiSelect becomes higher than an empty MultiSelect. Note that this issue is reproducible for Material and Material Black even before the fix - http://demos.telerik.com/kendo-ui/multiselect/index - delete the tokens and the MultiSelects will become shorter.

**Comment by mparvanov** [comment]
Token with string empty have proper height after the fix.
The height of inputs needs to be revised so they match the design and be consistent with buttons height in the following skins:
- Black
- Material
- Material Black
- Bootstrap v3
- Fiori
- Office 365

**Comment by Dimitar-Goshev** [comment]
Another possible issue related to MultiSelect:
- Only in Chrome on Virtualization demo the live demo fits the two tokens on one row, while the staging demo has the tokens on separate rows. Is it a bug or something expected?
![image](https://user-images.githubusercontent.com/6614183/34560869-52b42b66-f150-11e7-8344-dd6cbf9d6d78.png)

**Comment by mvgmvg** [comment]
There is fixed (increased) right padding, so the current behavior is correct.
