### ISSUE TITLE
Allow the selection zoom marquee to be appended to a specific element

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-ui-core#3724]
Source: [Ticket ID: 1137325](https://admin.telerik.com/default.aspx?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1137325&SM=0)

When the chart is inside an element that has transformations applied, the marquee selection can be displayed "outside" of the chart:

http://dojo.telerik.com/oZogA/2

We discussed with @tsvetomir that implementing a new option for appending the marquee to an element different from the `<body>` can help us handle such cases.

**Comment by danielkaradachki** [comment]
Appending the selection to the transformed element will not be sufficient to fix the scenario. Any coordinates that we work with will have to be transformed based on the combined transformation applied to all parents. This will lead to unnecessary overhead for the majority of cases. Therefore I will mark the issue as won't fix for now. If this becomes a common problem we may consider providing a method to set the current transformation applied to the element.
