### ISSUE TITLE
JAWS 2018 announces the previous element upon focusing DropDownList in AngularJS application

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3725]
### Bug report
JAWS 2018 announces the previous element upon focusing DropDownList in AngularJS application. The issue is only present in some cases, while in the most, the drop-down is announced properly. 

### Reproduction of the problem
* Run the following [Dojo](http://dojo.telerik.com/oVUma/2);
* Click on the "Test" button;
* Move the cursor out and then back on the button;
* Hit Tab to focus the DropDwonList - in some cases "Test button" will be anounced;

### Environment
* **Browser:** [ IE 11 ]

**Comment by Dimitar-Goshev** [comment]
The issue is very difficult to replicate. It seems as a JAWS issue, as the setup is one and the same, but the issue is reproducible inconsistently. Tested with [2019.3.1023 Dojo](http://runner.telerik.io/fullscreen/OYIcIYEX). Closing it due to inactivity.
