### ISSUE TITLE
Add support for ASP .NET Core SignalR

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#3726]
Add support to ASP .NET Core SignalR for its official realease. It is currently at Alpha 2 version. Here is the official [roadmap](https://github.com/aspnet/Home/wiki/Roadmap).

**Comment by Stamo-Gochev** [comment]
The functionality is tested with the latest (as of this writing) [1.0.0-rc1](https://github.com/aspnet/SignalR/releases/tag/1.0.0-rc1-final) release of SignalR with a sample service at https://github.com/telerik/kendo-ui-demos-service/tree/master/signalr-hubs

As with the old SignalR integration, the DataSource requires both the [hub](https://docs.telerik.com/kendo-ui/api/javascript/data/datasource/configuration/transport.signalr#transport.signalr.hub) and [promise](https://docs.telerik.com/kendo-ui/api/javascript/data/datasource/configuration/transport.signalr#transport.signalr.promise) options to be specified:

```javascript
$(document).ready(function() {
    var hubUrl = "url to a service";
    var hub = new signalR.HubConnectionBuilder()
        .withUrl(hubUrl, {
            transport: signalR.HttpTransportType.LongPolling
        }).build();

    var promise = hub.start();

    createGrid(hub, promise);
});

function createGrid(hub, promise) {
    $("#grid").kendoGrid({
        dataSource: {
            type: "signalr",
            transport: {
                signalr: {
                    promise: promise,
                    hub: hub,
                    server: {
                        read: "read",
                        update: "update",
                        destroy: "destroy",
                        create: "create"
                    },
                    client: {
                        read: "read",
                        update: "update",
                        destroy: "destroy",
                        create: "create"
                    }
                }
            }
            ...
        }
        ...
    });
}
```
More information regarding SignalR can be found in the official docs: https://docs.microsoft.com/en-us/aspnet/core/signalr/?view=aspnetcore-2.1
