### ISSUE TITLE
Reordering multi-column-header unlocked column to locked, causes wrong column order

### ISSUE THREAD

**Issue by david-gal-sdi** [telerik/kendo-ui-core#3728]
### Reproduction of the problem
http://dojo.telerik.com/AtAta
* Move any none locked column group (group-2, group-3) from the unlocked section to the locked section
* Move the same column group back to the unlocked section

### Current behavior
After moving a nested columns via main column from/to locked section, the columns are not ordered as they are configured.

### Expected/desired behavior
When moving nested columns via main column from/to locked section, keep configured column order.

**Comment by matanasov** [comment]
@david-gal-sdi 
If you use multi-column headers, it is possible to lock a column at the topmost level only. More information about locked columns features and limitations is available [here](https://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance#locked-columns)
