### ISSUE TITLE
Incorrect Tooltip position if its content wraps and the widget's width is not set

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3733]
### Bug report
Tooltip shows over its target when the widget has no specific width set and its text wraps.
If the Tooltip's width is set (for example **width: 750**) it is positioned correctly above its target and does not overlap it.
**Regression since version 2017.1.118.**

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/UtExEnUs) example. 
1. Hover the div. 
2. The Tooltip overlaps its target. 

### Current behavior
When "width" is not set and the text wraps the Tooltip overlaps the target. 

### Expected/desired behavior
Tooltip position is correctly calculated when its text wraps.

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
[The following issue](https://github.com/telerik/kendo-ui-core/issues/3879) shows another scenario, where the tooltip is incorrectly positioned - click on Delhi, Mumbay or Jakarta.
