### ISSUE TITLE
Wrong Localization in Turkish

### ISSUE THREAD

**Issue by kaansengul** [telerik/kendo-ui-core#3735]
The word "Tamalandı" should be "**Tamamlandı**":

https://github.com/telerik/kendo-ui-core/blob/83126312221cd226362d0ebee75c46cdc8f352d1/src/messages/kendo.messages.tr-TR.js#L367

Regards,
Kaan

**Comment by matanasov** [comment]
@ivanchev 
I have verified this and indeed @kaansengul is correct about this typo.

**Comment by ivanchev** [comment]
The upkeep of the different localization files (except the default one) is community driven, so feel free to fix such issues in this repository, and create a pull-request, rather than creating an issue. For this occurrence I will fix this directly in code.
