### ISSUE TITLE
Grid scrollable endless ignores page size, displayed counter goes out of sync

### ISSUE THREAD

**Issue by GaloisGirl** [telerik/kendo-ui-core#3736]
### Reproduction of the problem

1. Run the sample at http://dojo.telerik.com/@GaloisGirl/OsowI
1. Increase page size from 2 to 10
1. Scroll down once

### Current behavior

1. 2 additional items are loaded
1. Displayed item count is 4, while the grid has 12 visible rows

<img width="466" alt="kendogridscrollendlessignorespagesize" src="https://user-images.githubusercontent.com/3268958/32385566-e61c76d2-c0be-11e7-9d43-49ea06a4283b.png">

### Expected/desired behavior

1. 10 items should be loaded
1. The displayed item count should match the number of visible rows

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

**Comment by matanasov** [comment]
@GaloisGirl 
The endless scrolling feature used in the DoJo have [limitations ](https://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance#limitations-for-virtual-scrolling)similar to those of virtual scrolling. As virtual scrolling is designed and intended to be used as an alternative to standard paging, both features (paging and virtual/endless scrolling) should not be used at the same time.
