### ISSUE TITLE
Grid: with scrollable endless, reducing the page size shows more rows, not less

### ISSUE THREAD

**Issue by GaloisGirl** [telerik/kendo-ui-core#3737]
Possibly related to #3736

### Reproduction of the problem

1. Run the sample at http://dojo.telerik.com/@GaloisGirl/AhUjA
1. Note page size is 20
1. Scroll down once (or twice)
1. Decrease page size from 40 (or 60 respectively) to 10

### Current behavior

1. 20 additional items are loaded, for a total of 60 (or 80 respectively)

### Expected/desired behavior

1. Only 10 rows should be visible

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

**Comment by matanasov** [comment]
@GaloisGirl 
The endless scrolling feature used in the DoJo have [limitations ](https://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance#limitations-for-virtual-scrolling)similar to those of virtual scrolling. As virtual scrolling is designed and intended to be used as an alternative to standard paging, both features (paging and virtual/endless scrolling) should not be used at the same time.
