### ISSUE TITLE
meego.less references meego-sprite.png which is missing

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#3738]
### Bug report

meego.less references meego-sprite.png which is missing

https://github.com/telerik/kendo-ui-core/blob/master/styles/mobile/meego.less#L642

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** all
* **Browser:** all

**Comment by matanasov** [comment]
@joneff 
Please take a look at this.

**Comment by joneff** [comment]
Going all the way back, it appears that there never was a meego-sprite... Looking at the code, it's only used for checkboxes.

Unfortunately, I can't find the design neither. Still, we could try to improvise and create e checkbox sprite... After all MeeGo "inherited" Nokia's / Qt design language and there should be some guidelines somewhere in the web.

@matanasov @jlchereau what's your thought on that?

**Comment by jlchereau** [comment]
Anything works for me as long as it does not break webpack bundling. Thx.

**Comment by magdalenaan** [comment]
The Kendo UI Mobile LESS themes was officially deprecated with R1 2022.
