### ISSUE TITLE
The Points(markers) from GeoJSON are not hidden when the hide method of the Map layer is used.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3740]
### Bug report

The Points(markers) from GeoJSON are not hidden when the hide method of the Map layer is used. Only the Polygons are hidden.

### Reproduction of the problem

The issue can be observed in the following Dojo: http://dojo.telerik.com/esEWi

### Expected/desired behavior

The markers should be hidden as well.

### Environment

* **Browser:** [all]

**Comment by ag-petrov** [comment]
Generally the markers have their own layer and can be shown/hidden as demonstrated in this dojo - https://dojo.telerik.com/UToriLeB/3
