### ISSUE TITLE
autoScroll does not work if the container is the body Chrome and Edge

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#3741]
### Bug report

As reported in ticket with ID 1138214 

### Reproduction of the problem

Dojo [http://dojo.telerik.com/@bubblemaster/IwoJIp](http://dojo.telerik.com/@bubblemaster/IwoJIp)

### Expected/desired behavior

The body should auto scroll when the dragged element reaches the bottom as it does in Firefox and Internet Explorer 

### Additional Information

[Old issue for IE and FF](https://github.com/telerik/kendo-ui-core/issues/1145)

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** 1.12
* **Browser:** [ Chrome 61.0.3163.100 | Edge 38.14393.1066.0 ]

**Comment by zdravkov** [comment]
Could not replicate it with latest version.

**Comment by alexandrejobin** [comment]
You're right. With the version 2018.2.516, everything seems OK for Chrome. I didnt tested with Edge.
