### ISSUE TITLE
Inline Editor text highlighting is removed on expanding fontName and fontSize tools dropdowns

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3742]
### Bug report

Clicking on the fontName or fontSize tools dropdown arrows expands the dropdown and removes text highlighting. 

### Reproduction of the problem
[Dojo ](http://dojo.telerik.com/EZAzutog) example. 
1. Double-click a word from the Editor's content. The word is highlighted.
2. Click on the fontName or fontSize tool's dropdown arrow.
3. The dropdown expands and the word is no longer highlighted. 

### Current behavior
Clicking on fontName or fontSize tools removes text highlighting.

### Expected/desired behavior
Clicking on fontName or fontSize tools does not remove text highlighting, similarly to clicking other dropdowns like foreColor or backColor tools for instance. 

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** x.y
* **Browser:** [ Chrome, Firefox ]

**Comment by Iankodj** [comment]
The described behavior is not a bug. With inline editor the selection of text is part of the same document where the fontSize and fontName tools are created. Thus, when the input of these tools is focused the highlighted text in the content area is removed, but later, on selecting (or typing) a value, the value is applied on the same selection that is originally selected. 

In this case, typing a custom value in these tools is a crucial feature for the Editor and it cannot be sacrificed for the visual appearance of the highlight.
