### ISSUE TITLE
Tooltip does not show on each item when there is a filter applied and autohide is set to false

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#3744]
### Bug report

Tooltip is not showing on every item.

### Reproduction of the problem
[Dojo example](http://dojo.telerik.com/emAJI/8) Tooltip shows once on every two elements. If  element is hovered and the Tooltip appears, on hovering the next element the Tooltip will not appear.

### Current behavior
Тoоlltip is not showing on hover of every element.

### Expected/desired behavior
Tooltip should always show, when an element is hovered

### Environment
Works as expected with jQuery version 2.2.4

* **Kendo UI version:** 2017.3.1026
* **jQuery version: 3.x.x
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
Not reproducible with R3 2018 SP1 - 2018.3.1017 - http://dojo.telerik.com/OLIROWuc (jQuery 3.1.1 and also 3.3.1 tested)
