### ISSUE TITLE
Tabbing through events not working properly when there are more than two events scheduled in the same time

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3748]
### Bug report

When the [selectable option](https://docs.telerik.com/kendo-ui/api/javascript/ui/scheduler#configuration-selectable) of the widget is set to true and there are more than two events with the same start and end time, tabbing between events gets stuck.

### Reproduction of the problem

The issue can be observed [on the following Dojo](https://dojo.telerik.com/oCiri/10) by selecting the first event and then pressing tab until the focus is stuck.

### Current behavior

[Screencast](https://www.screencast.com/t/HAD3KlE2W)

### Expected/desired behavior

Tabbing through events should not be affected by events with identical start and end time.

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
After the fix, tabbing through more than 2 events works in FF, Chrome and Edge, but in IE there is a JavaScript error, when trying to move from one event to another with Tab:
Object doesn't support property or method 'findIndex'
