### ISSUE TITLE
Scheduler events with hourly recurrence should be repeated correctly in

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#3751]
### Enhancement
An event created with hourly recurrence is not repeated all day long (day and night). 
[Dojo example](https://dojo.telerik.com/ONifI)

### Current behavior
When an event is created with hourly recurrence, in Day view, it is repeated on every hour for the current day. But for the next days, it starts every day on the same time. The event is repeated on every hour, all day long in the Week view, but in the Day view it does not repeat after 00am.

**Comment by nelito987** [comment]
Might be related to [#4006](https://github.com/telerik/kendo-ui-core/issues/4006)

**Comment by Dimitar-Goshev** [comment]
This issue is identical with the related one. I will update its description to have the current scenario in mind as well. I am closing this issue as duplicate.
