### ISSUE TITLE
A non-breaking space is set to Kendo editor when the textarea is initially empty in IE and Edge

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#3754]
### Bug report

When the textarea element of editor is defined as empty initially, a non-breaking space is applied in IE and Edge, which is causing a validation issue,

### Reproduction of the problem
http://dojo.telerik.com/efaZU/2

### Current behavior
Editor passes the validation even with no content entered

### Expected/desired behavior
Editor does not pass validation if content is not entered

Workaround: Set empty value to editor component in case there is a single "\&nbsp;" initially.

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [IE 11 | Edge ]

**Comment by madcamp** [comment]
Is there any planned date to release this fix?

**Comment by nenchef** [comment]
@madcamp  I am afraid that we cannot provide you with an exact timeframe for the fix. 

The issue is reported again in  TIcket ID: 1172581. Hence, Priority increased by 1.

**Comment by Iankodj** [comment]
For the time being you can workaround that by setting up the value option to zero-width space entity: 

````js
$("#editor").kendoEditor({
    value: '\ufeff'
});
````
http://dojo.telerik.com/OpanEwUD
