### ISSUE TITLE
Kendo Grid data not refresh after Menu Filter clear 

### ISSUE THREAD

**Issue by kothiyalkailash** [telerik/kendo-ui-core#3756]
### Current behavior
Kendo Grid data not refresh after press clear button on Menu Filter 
 Steps:
Go to given link below
http://dojo.telerik.com/EZevo/6

press run
then

Click on filter icon for order date
enter valid date 
press Filter
Scroll down towards the paging drop-down and change the row count to "All"
Click again on filter icon for period begins 
Press Clear
### Expected/desired behavior
All data should return after pressing Clear below search Box

**Comment by matanasov** [comment]
@kothiyalkailash 
This seems to be a bug in the grid widget.

**Comment by Stamo-Gochev** [comment]
No longer reproducible in the master branch.
