### ISSUE TITLE
TreeView disabled nodes can be checked/unchecked

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3758]
### Bug report

Introduced in R3 2017 SP1. 

### Reproduction of the problem
[Dojo](http://dojo.telerik.com/OqULi/4) example. 
1. Click the disabled node's checkbox. 

**Workaround:**
```html
<script>
$(document).ready(function() {
  $(".k-treeview .k-checkbox-wrapper .k-checkbox").change(function(e) {
    if(e.target.disabled) {
    	e.target.checked = !e.target.checked;
    }
  });
});
</script>
```

### Current behavior
A disabled node can be checked/unchecked.

### Expected/desired behavior
A disabled node's checked status cannot be changed. 

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
This issue is related to the following issues: https://github.com/telerik/kendo-ui-core/issues/3581

**Comment by Dimitar-Goshev** [comment]
Another issue concerning wrong behavior of disabled node: https://github.com/telerik/kendo-ui-core/issues/3406
