### ISSUE TITLE
Overflowing cell followed by an empty cell is merged after paste in Spreadsheet

### ISSUE THREAD

**Issue by ivanchev** [telerik/kendo-ui-core#3760]
### Bug report

1. Open the attached excel file
[Book1.xlsx](https://github.com/telerik/kendo-ui-core/files/3695906/Book1.xlsx)
1. Mark and Copy A1 through C1 cells 
1. Paste them in https://demos.telerik.com/kendo-ui/spreadsheet/index

Below you can find how the issue is reproduced:
https://www.screencast.com/t/pZjOQeE7nA

### Current behavior
The overflowing cell followed by an empty cell is merged

### Expected/desired behavior
The three cells are pasted separately

### Environment

* **Kendo UI version:** 2019.3.917
* **Browser:** [IE11]

**Comment by Dimitar-Goshev** [comment]
After a fix, the issue is still reproducible only in IE.
