### ISSUE TITLE
Unable to delete selected MultiSelect items when autoClose is true and filtering is applied

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#3761]
### Bug report
It is not possible to delete selected MultiSelect items when **autoClose** is **true** (by default) and some text is entered in the input to filter.

### Reproduction of the problem
1. Use the following [Dojo](http://dojo.telerik.com/iZuhOS/2).
2. Click on the MultiSelect - the dropdown is expanded
3. Type n and press Enter - the focused item "Nancy King" is selected and the dropdown is closed.
4. Type m and press Enter - the focused item "Michael Leverling" is selected and the dropdown is closed.
5. Type a - items starting with a are filtered. 
6. Press Backspace - all items are shown and the first item "Steven White" is focused.
7. Press Backspace again.

### Current behavior
"Steven White" is selected. Subsequent Backspace pressing toggles "Steven White" selection.
If Esc is pressed, a javascript error is thrown - _"Uncaught TypeError: a.select(...).done is not a function"_

### Expected/desired behavior
"Michael Leverling" is deleted. Pressing Backspace again deletes "Nancy King" as well.
NOTE: the issue is not reproducible with R3 2017 - 2017.3.913 - [Dojo](http://dojo.telerik.com/Ohilu)

### Environment

* **Kendo UI version:** 2017.3.1018
* **Browser:** [all]

**Comment by zdravkov** [comment]
It was introduced by this [issue](https://github.com/telerik/kendo/issues/7688) so it will have to be retested too.

**Comment by epikhighs** [comment]
hi - is there a fix for this?  why was this issue closed?

**Comment by zdravkov** [comment]
Yes the issue is fixed and it will be available in the R1 2018 that is expected in January.
