### ISSUE TITLE
The numeric buttons in the pager of the Adaptive grid are not rendered correctly for some Less themes

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-ui-core#3766]
### Bug report

The numeric buttons in the pager of the Adaptive grid are not rendered correctly for some Less themes

### Reproduction of the problem

Use grid adaptive [demo ](http://demos.telerik.com/kendo-ui/m/index#grid/adaptive)and change the skin locally.

### Current behavior
Buttons are not rendered correctly - some of their borders are missing for these themes:
Fiori, Office365

### Expected/desired behavior
Buttons must render all their borders.

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** x.y
* **Browser:** [Desktop -> Chrome | Firefox | IE 11 | Edge] 

Sample image of one of the affected skins:
![32784923-d5b02ada-c958-11e7-849e-47b778b9c617](https://user-images.githubusercontent.com/5861835/32784994-0be98006-c959-11e7-8461-32a7c2e9ae65.jpeg)

**Comment by theOrlin** [comment]
These themes do not have a border around the whole number, just a line above the number itself. Cannot see any problems currently.

**Comment by matanasov** [comment]
@theOrlin 
The issue is valid for other skins - I have updated the description.
