### ISSUE TITLE
Cell validation button focuses next available cell when there are exactly 2 columns following it

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3769]
### Bug report

When cell validation is defined with a button ([cells.validation.showButton](https://docs.telerik.com/kendo-ui/api/javascript/ui/spreadsheet#configuration-sheets.rows.cells.validation.showButton)) and there are exactly 2 empty columns following it, the click of the button changes the focus to the next available cell and does not open the list of items for the validated cell. 

### Reproduction of the problem

Steps to reproduce with [the following Dojo example](http://dojo.telerik.com/AqEvIw/2):

* Select cell B1, B2 or B3
* Click on the editor button

### Current behavior

[Screencast](https://www.screencast.com/t/2TcRTWQWIswT)

### Expected/desired behavior

When the validation button is clicked, the corresponding cell list/custom editor should be opened.

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

**Comment by rshell** [comment]
Would actually put this a show big problem in using the date validators on imported data. Create a start and end date next to a row and have them work. Looks like have some problem in order of events or area of the screen the control.

**Comment by mishoo** [comment]
Seems to be a Chrome-only issue (works in FF).

**Comment by Dimitar-Goshev** [comment]
Reproducible in FF, IE and Edge on my side with the reproduction Dojo.
