### ISSUE TITLE
Touch events not properly triggered in Win10 devices, with keyboard and touch ability.

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3773]
### Bug report

Due to the late touch event trigger, if the form has some sort of validation - it is triggered, even if there is an item selected. 

### Reproduction of the problem

Use the following simple implementation and perform a selection in the DropDown with touch event.
```html
<form id="myForm">
    @(Html.Kendo().DropDownList()
              .Name("SpouseOneGender")
              .DataTextField("Text")
              .DataValueField("Value")
              //.Events(ev => ev.Select("onSelect"))
              .OptionLabel("Select Gender")
              .BindTo(new List<SelectListItem>() {
                  new SelectListItem() {
                      Text = "Male",
                      Value = "M"
                  },
                  new SelectListItem() {
                      Text = "Female",
                      Value = "F"
                  },
              })
              .HtmlAttributes(new { required = "required", validationmessage = "Select Gender" })
    )

    <button class="k-button k-primary" type="submit">Submit</button>
</form>
<script>
    $(document).ready(function () {
        var validator = $("#myForm").kendoValidator().data("kendoValidator")
    })
</script>

```

Tested on Yoga and HP EliteOne 800 G2 23-inch Touch  Aio

### Current behavior
The validation is triggered when you select an item. The second time you select an item - the validation correctly passes.

### Expected/desired behavior
The validation should not bi triggered, when you select an item from the DropDown.

### Workaround

Use the following overwrite, which will successfully hook the touchend event needed for the proper behavior:

```javascript
    kendo.ui.DropDownList.fn._popup = function () {
        kendo.ui.Select.fn._popup.call(this);
        this.popup.one("open", $.proxy(this._popupOpen, this));

        $(this.list).on("touchend.StaticList", "li", $.proxy(this._click, this))
        $(this.list).on("touchend", ".k-list-optionlabel", $.proxy(this._click, this))
    }

```

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [Chrome]

**Comment by kdnguye3** [comment]
I think there's also an issue with MultiSelect and touch events on the Win10 devices. I can't clear a selection by directly touching on the "x". I have to touch slightly under it.

**Comment by nenchef** [comment]
@kdnguye3 , your observations are absolutely correct and indeed the touch event does not get triggered in this scenario as well. This is will be taken into consideration when the issue is about to be fixed

**Comment by jivanova** [comment]
Could be observed in jquery scenario too: http://dojo.telerik.com/@jivanova/AhOmIbaG
