### ISSUE TITLE
The selectDates model binder for the MVVM Calendar is missing.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3775]
### Bug report

The selectDates model binder for the MVVM Calendar is missing. This creates a scenario where the selectDates values cannot be set initially from the viewModel.

### Reproduction of the problem

The issue can be observed at the following Dojo: http://dojo.telerik.com/ipAnE/3

### Environment

* **Browser:** [all]

**Comment by simonssspirit** [comment]
As the selected days can be passed through the property,  having a specific value binder is not required.

We made an example of how to make a custom model binder for that property if the desired approach is to used the value binder.

https://docs.telerik.com/kendo-ui/knowledge-base/calendar-how-to-set-multiple-dates-in-the-calendar-with-mvvm

**Comment by CSerX** [comment]
I am use this:
    kendo.data.binders.widget.selectDates = kendo.data.Binder.extend({
        init: function(widget, bindings, options) {
            //call the base constructor
            kendo.data.Binder.fn.init.call(this, widget.element[0], bindings, options);

            var that = this;
            //listen for the change event of the element
            widget.bind('change',function() {
                that.change(); //call the change function
            });
        },
        refresh: function() {
            var value = this.bindings["selectDates"].get();
            var calendar = $(this.element).data('kendoCalendar');
            calendar.selectDates(value);
        },
        change: function() {
            var calendar = $(this.element).data('kendoCalendar');
            var value = calendar.selectDates();
            this.bindings["selectDates"].set(value); //update the View-Model
        }
    });
