### ISSUE TITLE
Application navigation redirects to the initial instead of the previous view

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3778]
### Bug report
When navigation is performed to an external view (in external HTML file), the browser back button on the third visited view will redirect to the initial view of the Application, instead of the second (the previously visited) view.

### Reproduction of the problem
Available in the following [sample](https://admin.telerik.com/ClientsFiles/13b47079-7e2a-4e92-b763-f806f3d109f5_appnavigation.zip).

### Expected/desired behavior
The browser back button should always navigate to the previously visited view.

**Comment by sabgkang** [comment]
I am having the same problem, any workaround for this bug?

**Comment by ag-petrov** [comment]
The issue on hand is logged for the mobile widgets that are now depricated. Closing this issue.
