### ISSUE TITLE
The horizontal scroll  goes out of sync with Virtualized Grid with locked columns after scroll and click on the scroll arrow

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3779]
### Bug report

The horizontal scroll goes out of sync with Virtualized Grid with locked columns after scroll and click on the scroll arrow. Only IE11

Please check the following video: https://www.screencast.com/t/t7eezjXtH

### Reproduction of the problem

The Dojo used in the video: http://dojo.telerik.com/uBomi/6

### Environment

* **Browser:** [IE11] 
* **Kendo UI version:** 2017.2.621

**Comment by Stamo-Gochev** [comment]
Might be an IE 11 feature regarding the scroll event not being fired starting from version IE 11.0.9600.18861 (works in IE 9, 10 and 11 until 11.0.9600.18860 including). I ran the following tests:

| IE version  | Platform | Result |
| ------------- | ------------- | ------------- |
| 11.0.9600.18860  | Windows 7  | working  |
| 11.0.9600.18860  | Windows Server 2008 R2  | working  |
| 11.0.9600.18861  | Windows Server 2012 R2  | not working  |
| 11.0.9600.18894  | Windows 8  | not working  |
