### ISSUE TITLE
Kendo Window fires close event twice on Esc keydown 

### ISSUE THREAD

**Issue by GaloisGirl** [telerik/kendo-ui-core#3780]
### Reproduction 

1. Run sample at https://dojo.telerik.com/@GaloisGirl/ElAFo/2
2. Click on the dialog
3. Press Esc

### Current behavior

"Close" event handler is executed twice. ("Window closed" is logged twice. )

If dialog is closed by click on close button, the event handler is only executed once.

### Expected/desired behavior

Whether window is closed by button click or pressing Esc, the event handler should be executed once.

Possibly related to #3152.

### Environment

* **Kendo UI version:** 2017.3.1026 (works as expected on 2017.1.223)
* **Browser:** [all]

**Comment by zdravkov** [comment]
Introduced in this [commit](https://github.com/telerik/kendo/commit/1457a2aca7682b94f3065fc534fc84a29826ca2b#diff-e541ce9b63819df5053be61d3e34e00a)
