### ISSUE TITLE
columns.selectable not working with multiple grids on the same page

### ISSUE THREAD

**Issue by bhcoder** [telerik/kendo-ui-core#3783]
### Reproduction of the problem
1. Run sample at https://dojo.telerik.com/IWasEJ
2. Click on the "select all" checkbox on the second grid

### Current behavior
All rows of the first grid are selected

### Expected/desired behavior
All rows of the second grid have to be selected

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

**Comment by simonssspirit** [comment]
The issue is also reproduced in detailed Grids: 1142064.

A workaround will be to set custom select all checkbox in the header: http://dojo.telerik.com/orEhu/15 

Raising the severity and the priority.

**Comment by TsvetinaIvanova** [comment]
Reported by another customer in 1142518.
