### ISSUE TITLE
DatePicker validation is not triggered under mobile devices

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3785]
### Bug report
DatePicker validation is not triggered under mobile devices

### Steps to reproduce
1. Open https://demos.telerik.com/kendo-ui/validator/custom-validation
2. Click on save to trigger validation
3. After error messages are shown, select a date from the datepicker using touch actions
4. Click outside of the datepicker.

### Current behavior
_(optional)_
The validation for the datepickers is not triggered under mobile devices

### Expected/desired behavior
The validation for the datepickers should be triggered under mobile devices

### Workaround

In order to overcome the issue, you should manually trigger the validation, using the validateInput method of the kendoValidator and pass the input of the picker. This could be achieved in the change event of the widget:

```javascript
function pickerChange(e) {
    var validator = form.kendoValidator().data("kendoValidator");    //get reference to kendoValidator on the page    
    validator.validateInput(e.sender.element); // validate the input of the kendoDatePicker widget
}
```

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

**Comment by Stamo-Gochev** [comment]
The issue is caused by a difference in focusing the datepicker's input in touch devices and fixing this will result in a breaking change. If a way to fix this is found without introducing a breaking change, the item will be updated in the future.
