### ISSUE TITLE
Server aggregates are not calculated properly when data is grouped by more than one column in php scenario

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#3787]
### Bug report

The values for the first subgroup subgroup are not calculated properly when server operations (server aggregates) are enabled. The problem should exist in the DataSourceResult.php file. 

### Reproduction of the problem

To replicate the problem you can extend our [http://demos.telerik.com/php-ui/grid/aggregates](http://demos.telerik.com/php-ui/grid/aggregates) demo to group the Kendo UI Grid by 2 groups. Include the Count sum for the ProductName field. 

### Current behavior

The Count value for the first subgroup is not calculated correctly. It takes the count value as if it was grouped only by this column (single column grouping). 

### Expected/desired behavior

The count value should be equal to the items in the parent group. 

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by dimodi** [comment]
Please update the customer in 1140745 when the fix is implemented.

**Comment by martintabakov** [comment]
Closed due to deprecation of the PHP library.
