### ISSUE TITLE
MultiSelect value cannot be cleared programmatically if an item is selected after filtering the data

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3788]
### Reproduction of the problem
[Dojo](http://dojo.telerik.com/ACIkoT) example. 
1. Focus the MultiSelect and type "four". 
2. The item with text "Four" is returned as a match. 
3. Select item "Four". 
4. Click the Clear button above the MultiSelect. 

**Expected:** the MultiSelect's input is cleared. 

**Actual:** the selected item's tag remains in the MultiSelect's input and can no longer be removed by clicking its own clear button or the MultiSelect's clear button. Clicking these two clear buttons after having called value([]) throws a js exception: `"Uncaught TypeError: a.select(...).done is not a function"`
related #3761
This behavior has been introduced in R3 2017 SP1.

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by tgoric** [comment]
I found a similar bug that isn't related to clearing the MultiSelect programmatically, and just want to make sure that the fix to this bug fixes both. This occurs with Single tag mode only and does not throw any JavaScript errors.

Steps, using the Single tag mode sample [here](http://demos.telerik.com/kendo-ui/multiselect/tag-mode):

1. Clear the Single tag mode control
2. Type 'la' or anything else to filter the list down
3. Click anywhere off the control to make the dropdown lose focus and close
4. Click the 'x' to clear the selected item.

The item is not cleared from the MultiSelect.
