### ISSUE TITLE
NoRecords message is not rendered in MVC Grid with server binding

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#3791]
### Bug report

Using server binding does not render the NoRecords message for the Grid

### Reproduction of the problem

		@(Html.Kendo().Grid(new List<Product>())    
			.Name("Grid")
			.Columns(columns => {
				columns.Bound(p => p.ProductID).Groupable(false);
				columns.Bound(p => p.ProductName);
				columns.Bound(p => p.UnitPrice);
				columns.Bound(p => p.UnitsInStock);
			})
			.NoRecords("No records found.")
			
			.Pageable()
			.Sortable()
			.Scrollable() 
			.DataSource(d=>d.Server())
			.Filterable()
			.Groupable()
		)

### Workarond
A possible workaround is to use local binding by setting the AJAX binding in the DataSource, but keep the initial server binding:

		@(Html.Kendo().Grid(new List<Product>())    
			.Name("Grid")
			.Columns(columns => {
				columns.Bound(p => p.ProductID).Groupable(false);
				columns.Bound(p => p.ProductName);
				columns.Bound(p => p.UnitPrice);
				columns.Bound(p => p.UnitsInStock);
			})
			.NoRecords("No records found.")
			
			.Pageable()
			.Sortable()
			.Scrollable() 
			.DataSource(d=>d.Ajax().ServerOperation(false))
			.Filterable()
			.Groupable()
		)

### Environment

* **Kendo UI version:** 2017.3.1026

**Comment by junkmanuk** [comment]
The workaround works, but causes issues with template detail.  Any update on when this will be fixed?

**Comment by dgirardin** [comment]
This solution don't work with 'Custom command'
----
Custom command routes is available only for server binding.

**Comment by Alex-Bubblemaster** [comment]
Raising priority, also reported in ticket with ID 1441187

**Comment by web-jeromejose** [comment]
Any update on this for tag helper?
