### ISSUE TITLE
Gulp custom build fails for a single component without trailing comma

### ISSUE THREAD

**Issue by Proper-Job** [telerik/kendo-ui-core#3794]
### Reproduction of the problem
with the environment setup below run this command:

```bash
gulp custom -c datepicker
```

### Current behavior
produces no output

### Expected/desired behavior
custom build is written to dist folder

### Workaround
Add a **trailing comma** to the command and the output is written to the dist folder:
```bash
gulp custom -c datepicker,
```

### Environment

node: 4.7.0
npm: 4.5.0
gulp: 3.9.1
gulp-cli: 3.9.1
git tag: 2017.3.1026

**Comment by matanasov** [comment]
@ivanchev 
I am replicating the reported behavior. Can you please take a look into it?
