### ISSUE TITLE
The month is changed always to January, if a date is entered manually

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#3797]
### Bug report

After changing a date manually, the displayed month is always January, if the date format is set to 'm/dd/yyyy' or 'mm/dd/yyyy'

### Reproduction of the problem
1. Open the Dojo - [http://dojo.telerik.com/ekazEF](http://dojo.telerik.com/ekazEF)
2. Enter manually a date in column C

### Current behavior
The month after changing a date is always January

### Expected/desired behavior
The month should be the same as the entered one.

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by mishoo** [comment]
The bug is in `kendo.parseDate`:

```js
kendo.parseDate("4/5/1987", "m/dd/yyyy") → "Mon Jan 05 1987 00:04:00 GMT+0200 (EET)"
```

/cc @ggkrustev

**Comment by rishi01k** [comment]
Hi,

While facing this issue, I have tried changing the format from 'mm/dd/yyyy' to 'MM/dd/yyyy' and it worked for me.

Thanks

**Comment by mishoo** [comment]
Fixed in https://github.com/telerik/kendo/pull/8669/commits/6b4660846e8d917819673f7b6d8dc7c4cf0621a4
