### ISSUE TITLE
Pdf file exported with the Scheduler's PdfExport cannot be opened in Acrobat Reader

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3803]
### Reproduction of the problem
[Dojo](http://dojo.telerik.com/eBELiw) example (reproducible also in the Scheduler's PDF Export demo). 
1. Press the "Export to PDF" button (triggering the export with the saveAsPDF method leads to the same behavior)
2. The exported content is displayed as expected in Chrome. 
3. Save the file locally and open it with Adobe Acrobat Reader. An exception is thrown ([screenshot](https://www.screencast.com/t/7HZwZbcu)). 

The issue is reproducible since R2 2017. 

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** x.y
* **Browser:** [ Chrome 62 ]

**Comment by veselints** [comment]
The same could be observed on the [PDF export demo](https://demos.telerik.com/kendo-ui/scheduler/pdf-export). The issue is present when opening the PDF with Adobe Acrobat Reader DC. It could not be observed with some older versions of the Reader (e.g. v XI).

**Comment by Dimitar-Goshev** [comment]
The issue is reproducible on my side with Adobe Reader XI (v 11.0.12), Chrome 65 and Kendo UI 2018.1.221.
