### ISSUE TITLE
kendo.drawing.drawDOM duplicates content from textarea in IE

### ISSUE THREAD

**Issue by DmitryKiselyov96** [telerik/kendo-ui-core#3805]
### Reproduction of the problem

kendo.drawing.drawDOM (**with paperSize setting**) duplicates content from textarea after saving to pdf in IE 11 and Edge.  Also reproduced with other settings (for example forcePageBreak).
Dojo example: http://dojo.telerik.com/iqiyi/4
After exporting to pdf in IE content of textarea (text1) will be duplicated. But in Chrome everything is fine.

### Expected behavior
kendo.drawing.drawDOM (**with paperSize setting**) doesn't duplicates content from textarea like in Google Chrome.

### Environment
* **Kendo UI version:** 2017.3.1026
* **jQuery version:** 2017.3.1026
* **Browser:** [ IE 11 | Edge ]

**Comment by DmitryKiselyov96** [comment]
Workaround works.

**Comment by DmitryKiselyov96** [comment]
The workaround does not work correctly if you add more html elements.
The output file becomes dependent on the screen resolution. I tested export on monitors with 1920x1080 and 1280x1024 resolution and they produce different pdf-files (even in Google Chrome).
[1920x1080.pdf](https://github.com/telerik/kendo-ui-core/files/2083821/1920x1080.pdf)
[1280x1024.pdf](https://github.com/telerik/kendo-ui-core/files/2083822/1280x1024.pdf)

Your solution with more elements - http://dojo.telerik.com/ElOxoVOr/9
Expected behavior with more elements - http://dojo.telerik.com/ozeMUNIJ/2

**Comment by jmj101** [comment]
The workaround does not work, forcePageBreak only work on kendo.drawing.drawDOM method but not on kendo.drawing.exportPDF.

**Comment by pepinho24** [comment]
Reported also in Ticket ID: 1389151 for ClientExportManager for ASP.NET AJAX when PageBreakSelector is set (which internally sets the forcePageBreak property)

**Comment by vamshi586** [comment]
I have the same issue.. is this issue resolved??

kendo.drawing
                .drawDOM("#printSection",
                    {
                        forcePageBreak: ".page-break",
                        toolbar: ["pdf"],
                        paperSize: "Letter",
                        margin: {
                            top: "1cm",
                            left: "1cm",
                            right: "1cm",
                            bottom: "1cm"
                        },
                        template: $("#page-template").html(),
                        scale: 0.55,
                        pdf: {
                            author: "WUSTL",
                            date: new Date(),
                            fileName: "",
                            keywords: "WUSTL, ImmunityForm, HealthHistory",
                            allPages: true,
                            avoidLinks: true,
                            paperSize: "Letter",
                            margin: {
                                top: "2cm",
                                left: "1cm",
                                right: "1cm",
                                bottom: "1cm"
                            },
                            landscape: false,
                            repeatHeaders: true,
                            pageable: true
                        }
                    })

i have the above code and the mutliline text box draws duplicate content i.e twice the content

**Comment by Juveniel** [comment]
Fixed with the 2020.2.513 release. 

Can be tested with latest version [here](http://dojo.telerik.com/iWeqIdUf/2).
