### ISSUE TITLE
On the autumn daylight saving date, in Scheduler with UTC timezone, when changing end time to be between 1 and 3 AM the scheduler adds 1 hour to the date

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3810]
### Bug report
On the autumn daylight saving date, in Scheduler, when the timezone is set to UTC, if changing the end time of an event to be between 1 and 3 AM the scheduler adds 1 hour to the date.

This could be related to #3282

### Reproduction of the problem
1. Go to the following [Demo](https://dojo.telerik.com/@Dimitar-Goshev/eWaSenIh);
1. Create an event starting at 12 AM on 29 Oct 2017;
1. Resize the end of the event to 1:30 AM;

### Current behavior
The event will be automatically resized to 2:30 AM;
The above will occur in the browser timezone is Europe/Sofia UTC + hours. If another client timezone is tested (UTC -5 US Eastern time for example), one hour will be removed instead (for example 3 AM will be converted to 2 AM).

What happen in this case is: 
* When setting the date it is being created in browser as JavaScript object (always local time):
Sun Oct 29 2017 01:30:00 GMT+0300 (Eastern Europe Daylight Time)
* Then, as the Scheduler is configured to be `timezone: "Etc/UTC"`, three hours are added before being sent to the server:
Sun Oct 29 2017 04:30:00 GMT+0200 (Eastern Europe Standard Time)
* On the server, the date is saved, but as the 4:30 is already after DST change (occurring at 3:00), whet it is returned to the client only two hours are compensated instead of three. The date is displayed as:
Sun Oct 29 2017 02:30:00 GMT+0200 (Eastern Europe Standard Time)

### Expected behavior
The event is resized to 1:30 AM

### Environment
- **Kendo UI: ** 2019.2.619
- **Browser:** all

**Comment by racquelar** [comment]
I think the severity should be bumped up to at least a Medium

**Comment by racquelar** [comment]
Is there any kind of timeline for when this bug will be fixed?  Daylight savings time is coming around again on November 4, 2018. A year later there is still no milestone assigned to this issue.  With no workaround, in my opinion this is a real issue to have to deal with every year.
