### ISSUE TITLE
Inconsistent items selection when ComboBox suggest property is true and filtering is applied

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#3811]
### Bug report 1
ComboBox does not always select item when suggest is set to 'true' and filtering is used.  

### Reproduction of the problem
1. Open the [Dojo](https://dojo.telerik.com/eSISuB)
2. Open the console to see the text of the selected item.
3. Type 'd' and press Tab key. The select event is fired.
4. Delete the text in the ComboBox input, type 'd' and press Tab key again. The select event is fired, but  e.item is null.

Regression introduced in **R2 2017 - version 2017.2.504**

### Current behavior
On the first search the e.item in the select event is the selected item. On the second search e.item is null.

### Expected/desired behavior
The items should be selected correctly every time, by pressing the Tab key. 

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

### Bug report 2
ComboBox does not always select item when suggest is set to 'true' and filtering is used.  

### Reproduction of the problem
1. Go to [ComboBox Basic usage demo](https://demos.telerik.com/kendo-ui/combobox/index)
2. Select the text of the first ComboBox input and type c.
3. Click outside the ComboBox to blur it - **c**otton is selected - this is a custom item with **value cotton**.
4. Select the text of the first ComboBox input and type c.
5. Click outside the ComboBox to blur it - **C**otton is selected - this is the item from the datasource with **value 1**.

Regression introduced in **R2 2017 - version 2017.2.504**

### Current behavior
On one blur the existing item from the datasource is selected. On the next blur a custom item is selected.

### Expected/desired behavior
As **suggest** is set to **true** and **c** is auto-completed to **cotton**, on blur the **matching item** from the datasource **Cotton** is always selected. A custom item may be selected only if the entered text in the input is cotton+something.

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
This issue is caused by the following item: https://github.com/telerik/kendo-ui-core/issues/1962
