### ISSUE TITLE
Incorrect selected state applied to multiple items of vitrualized ComboBox/DropDownList, when navigating to last item with press and holding Down Arrow key

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#3812]
### Bug report
Video: https://www.screencast.com/t/PMObDZihumY
Regression since R3 2017 - 2017.3.913.

### Reproduction of the problem
1. Go to http://demos.telerik.com/kendo-ui/dropdownlist/virtualization
2. Click on the DropDownList/ComboBox arrow to expand the dropdown.
3. Press and hold Down Arrow key until the last item at the bottom is reached

### Current behavior
Multiple items have selected class applied. If Up arrow is pressed, selected state is added to other item to the top as well.
![image](https://user-images.githubusercontent.com/6614183/33427550-548b6cd0-d5ce-11e7-9d7e-f3d54cb8ece4.png)

### Expected/desired behavior
There is only one selected item at a time.

### Environment

* **Kendo UI version:** 2017.3.913+
* **Browser:** [all]

**Comment by zdravkov** [comment]
The issue was introduced by [this issue](https://github.com/telerik/kendo/issues/7218) so it should be retested too.
