### ISSUE TITLE
Memory Leak in IE11 with kendoWindow, when the widget is opened and closed multiple times

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3815]
### Bug report

As described in the title, the memory leak occurs in IE11 when the window gets opened and closed multiple times.

### Reproduction of the problem
The following dojo demonstrates the issue:
[http://dojo.telerik.com/@nenchef/AgEHax/23](http://dojo.telerik.com/@nenchef/AgEHax/23)

Open the example and click the button once.

### Current behavior
Consumed memory in IE11 grows each time the window is opened.

### Expected/desired behavior
The memory usage should now grow

### Workaround

You can manually dismiss the focus event of the document window, which is not properly disconnected. This could be achieved at the deactivate event of the Window:

```javascript
               deactivate: function (e) {                 
                  this.destroy();
                 $(window).off("focus")                 
               }
```

the modified dojo with the workaround:

[http://dojo.telerik.com/@nenchef/AgEHax/23](http://dojo.telerik.com/@nenchef/AgEHax/23)

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [IE11 ]

**Comment by riccardomerlin** [comment]
FYI there is also `blur` event that needs to be removed. 
```javascript
deactivate: function() {
    this.destroy();
    $(window).off('focus').off('blur');
}
```

**Comment by mparvanov** [comment]
Consider removing also `blur` event handler.
