### ISSUE TITLE
Unexpected TreeView node check/uncheck behavior when nodes or their checkboxes are disabled

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3816]
### Bug report

Consider the following 4 scenarios: 

**Scenario1**: [dojo](https://dojo.telerik.com/enEJU) example

1. Node "child1" can be checked on every third click of its checkbox.

**Expected**: The expected behavior should be "child1" to not change its state, since it contains a single node ("baz"), which is disabled and unchecked. "baz" is disabled so its state ("unchecked") cannot be changed unless it is first enabled. Therefore its parent's state should remain unchecked as well. 

**Scenario2**: [dojo](https://dojo.telerik.com/enEJU) example

1. Click "Parent1"'s checkbox. 
2. Its state changes to indeterminate, but cannot be changed to unchecked on subsequent clicking. 

**Expected**: The expected behavior should be switching from indeterminate to unchecked state (since only "child3" should be checked/unchecked on clicking "Parent1"'s checkbox).

**Scenario3** [dojo](https://dojo.telerik.com/anUtO) example 

In this scenario а checkbox template is set. Based on a field in the dataSource ("available") the checkbox of some nodes is disabled. The nodes themselves are not disabled. 
The behavior is similar to Scenario1. 
**Expected**: Since "baz" cannot be checked by checking its parent after the fix of issue #3581 the expected behavior should be as in Scenario1: the unchecked state of "child1" should persist and should not be possible to change. 

**Scenario4** [dojo](https://dojo.telerik.com/anUtO) example 
1. Clicking "Parent1"'s checkbox consecutively cycles through all 3 possible states. 

**Expected**: The expected behavior should be as in Scenario2: "Parent1" should switch between indeterminate state (only "child3" is checked) and unchecked ("child3" is unchecked). The state of the other nodes does not change. 
 
The behavior in these scenarios is different up to R3 2017 SP1, the current one is related to #3581

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by ivanchev** [comment]
Helpful testing setup:
http://dojo.telerik.com/IgAwU

**Comment by ivanchev** [comment]
Scenario 2 is expected - When the Checkbox is indeterminate, clicking on it should try to check the checkbox. Since it cannot, nothing should happen. Reverting to unchecked is not consistent with the logic.
