### ISSUE TITLE
Dialog content is trimmed, if it exceeds dialog dimensions

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3817]
### Bug report

Setting the Dialog's height or maxHeight options lead to "overflow: hidden" style to be applied to the widget's content wrapping element (with class ".k-dialog-content")

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/EVaROz) example. 
Inspect the content wrapping element.

Workaround: 

```htm
<style>  
  .k-dialog-content {
    overflow-y: visible !important;
  }
</style>
```

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
The issue is also reproducible with dialog width as well, so I renamed it:
Use the following [Dojo](https://dojo.telerik.com/ERiRO/7)
