### ISSUE TITLE
Review kendo.mobile.Application status bar scenarios for iPhone X

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#3818]
### Bug report

The following two articles extensively describe the defect and solution. As far as Kendo UI is concerned, the height of the status bar is not 20px on iPhone X. 

Review https://docs.telerik.com/kendo-ui/controls/hybrid/application#common-scenarios considering:

- http://stephenradford.me/removing-the-white-bars-in-safari-on-iphone-x/
- https://stackoverflow.com/questions/46232812/cordova-app-not-displaying-correctly-on-iphone-x-simulator

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** 3.2.1
* **Browser:** iOS 11 UIWebView on iPhone X

**Comment by Dimitar-Goshev** [comment]
Kendo Mobile is deprecated.
