### ISSUE TITLE
MultiSelect throws an error if an item is select while filtering

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#3821]
### Bug report

If an item is selected in MultiSelect while filtering, an exception occur.

### Reproduction of the problem
1. Use the following Demo [http://demos.telerik.com/aspnet-mvc/multiselect/virtualization](http://demos.telerik.com/aspnet-mvc/multiselect/virtualization)

2. Slow the filtering by adding Thread.Sleep in the controller
```htm 
public ActionResult Virtualization_Read([DataSourceRequest] DataSourceRequest request)
        {
            Thread.Sleep(3000);
            return Json(GetOrders().ToDataSourceResult(request));
            
        }
```
3. Type a value in MultiSelect to start filtering.
4. Before the response from the server is received click (or press Enter) an item to select it.
5. A js exception is thrown.

### Current behavior
js exception is thrown: "Cannot read property 'OrderId' of undefined".

### Expected/desired behavior
No exception is thrown when item is selected while filtering.

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all ]

**Comment by barrakuda099** [comment]
Could you please fix it in short time as possible?
Thank you in advance!

**Comment by barrakuda099** [comment]
Could you tell us when will you fix it?

**Comment by Dimitar-Goshev** [comment]
@barrakuda099 There is no time estimate for fixing the issue. As you are following the issue, you will be notified on its progress. I am increasing its priority, as it is reported by another customer as well.

**Comment by jivanova** [comment]
Fix included in https://github.com/telerik/kendo/issues/8364.
