### ISSUE TITLE
Fonts are not pasted correctly from document to Editor

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#3825]
### Bug report

When text is pasted to the Editor from a document (docx, rtf) the font name and the font size are not pasted correctly. The behavior is different in different browsers.

### Reproduction of the problem
1. Open an Editor Demo, for example - [http://demos.telerik.com/kendo-ui/editor/all-tools](http://demos.telerik.com/kendo-ui/editor/all-tools)
2. Copy a text from a word document.
    2.1. For example text with font- Times New Roman 12px. 
    2.2 Text with font Courier New 11px
3. Paste the text in the Editor
4. Copy the Editor's content, Paste back to the word document and check the font name and size
### Current behavior
2.1 
- IE11/Chrome -  the font name and the font size are not recognized and are not displayed in the 'Font name' and 'Font Size' tools. The pasted text is with size 9px, the font is Verdana. 
screencast [https://www.screencast.com/t/02m5ARqUW7N4](https://www.screencast.com/t/02m5ARqUW7N4)
- Firefox - the font name and the font size are correct, but are not recognized and are not displayed in the 'Font name' and 'Font Size' tools.

2.2
- IE - Font name and font size are not recognized. The pasted font is correct, but the size is 9px
- Firefox/Chorme - Font is recognized and is correct, but the size is 9px. 
screencast - [https://www.screencast.com/t/0HZtfwmzGm](https://www.screencast.com/t/0HZtfwmzGm)

### Expected/desired behavior
The behavior should be consistent. The text should be pasted with its initial font name and font size. 
### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all  ]

**Comment by Iankodj** [comment]
The font name and font size styles are processed only by the browser during pasting and copying. Most of the reported issues can be also reproduced with a simple contenteditable element, like the one here: http://dojo.telerik.com/UmAnIWiZ. 

In IE, the output values of these properties are not shown because the tools are dropdowns and do not allow showing custom values (values that are not listed in the tool).
