### ISSUE TITLE
Setting the Dialog's actions text with the setOptions method does not work correctly 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3827]
### Bug report
If the actions text is changed with the setOptions method the actions are rendered with their initial text.

### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/OniyuZ) example. 
1. The Dialog is initialized with 2 actions with text "OK" and "Cancel"
2. On "show dialog" button click different text is set to the Dialog's actions. 

**Expected**: The newly set actions.text ("test1" and "test2") is displayed as actions text. 

**Actual**: The initially set actions.text ("OK" and "Cancel") is displayed as actions text. 

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by jivanova** [comment]
Added setOptions method that handles content, modality, title, actions, width/height.

**Comment by Dimitar-Goshev** [comment]
After the fixes, setOptions does not work as expected, if width and height are initially set, or set with setOptions. Uncomment width/height and the dialog will appear empty on re-opening:

```
<div id="dialog"></div>
<input type="button" value="show dialog" onclick="showDialog()" />
<script>
    $("#dialog").kendoDialog({
        visible: true,
        //width: 300,
        //height: 200,
        actions: [{
            text: "OK",
            action: function (e) {
                return false;
            },
            primary: true
        }, {
            text: "Cancel"
        }]
    });

    function showDialog() {
        var dialog = $("#dialog").data("kendoDialog");
        dialog.setOptions({
            closable: false,
            //width: 300,
            //height: 200,
            actions: [
          { text: 'test1', primary: true },
          { text: 'test2' }
            ]
        });

        dialog.open();
        console.log(dialog.options.actions)
    }
</script>
```
![image](https://user-images.githubusercontent.com/6614183/36264452-7971a152-1275-11e8-91c9-7f055ff74c2b.png)
