### ISSUE TITLE
The DateTimePicker with DateInput corrects the entered value if it is set out of range (min or max)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3828]
### Bug report

The DateInput setting enabled in Date/Time/Picker corrects the entered value if it is set out of range (min or max)

### Reproduction of the problem

The issue could be reproduced in the following Dojo by setting a value lower than the min one and logging the results: http://dojo.telerik.com/OmEfOv

### Environment

* **Browser:** [all]

**Comment by simonssspirit** [comment]
reported again in ticket: 1154602,
raising the priority and the severity

**Comment by VicTachev** [comment]
Changing the behavior would cause breaking change in either the DateInput or Date(Time)Picker components and this is something we strive to avoid. 

We can clear the value in the picker when an out-of-range date is entered and leave the default month/date/year placeholder. However, this will again be a big change in the way the picker components work.

**Comment by Taygair** [comment]
Just returned to check how this bug correction is going on. I'm fine with the behaviour that the min date/time will be set automatically if the date is older than the min date (as it works now). I just realized you can't catch any such changes. The close event of the widget seems to fire BEFORE the corrected date is set, so then still returning null. 
By which KendoUI version should this bug be fixed?

**Comment by Taygair** [comment]
Just realize that this bug is closed. Why? The problem still exists in the latest KendoUI version. What is the correction if there is one?

**Comment by VicTachev** [comment]
The current behavior is observed because the DateInput corrects the entered value if it is out of range. However, if the user enters an invalid value the Date(Time)Picker does not accept it. What we can suggest for applying the value displayed in the DateInput to the DatePicker is the approach shown in the dojo below:

[http://dojo.telerik.com/oPuKIxez/3](http://dojo.telerik.com/oPuKIxez/3)
