### ISSUE TITLE
LinkCommand deletes formatting when an a tag wraps original formatting

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3830]
### Bug report

If you have selection, format it and apply a link, the a tag will wrap all formatting. Next, changing the text of the link will remove the original formatting and leave only the a tag. 

### Reproduction of the problem
http://demos.telerik.com/kendo-ui/editor/index

1. Select a word (e.g., Editor);
1. Format with Bold, Italic and apply a link (do not remove selection);
1. Clear selection and re-select the word;
1. Open the link dialog and change the link text.

https://www.screencast.com/t/mPrc5fWYTxe

### Current behavior
Original formatting is removed. And there a JS error: 

    The given range isn't in document. kendo.all.js:63683 

### Expected/desired behavior
Either link to always be applied as a child of all previous formatting. Or LinkCommand to extract the original formatting before changing the innerHTML of the a tag.

### Environment

* **Kendo UI version:** 2018.2.620
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by nikistefanov** [comment]
Also when you have formatted word and change the formatting for some characters of that word and create a link, the result is multiple link elements.
See [video](https://www.screencast.com/t/ibUqalTKz) for better picture.

**Comment by Iankodj** [comment]
@nikistefanov The described behavior is expected as the inline formatting cannot be consolidated in such a scenario. The formatting applied is on different level for each node. In order to consolidate such output a much more complex traverse mechanism would be required. 

Plus, this output does not result to any functional difference in regards to the created link/s or results to concerns regarding the DOM generated.

**Comment by mparvanov** [comment]
A JS error is thrown in FireFox with the following scenario:

1. Open the internal build http://kendobuild-windows.openstack.progress.com/kendo-ui/editor/index
1. Select a word (e.g., Editor)
1. Format with Bold, Italic and apply a link (do not remove selection)
1. Clear selection and re-select part of the word
1. Open the link dialog and change the link text

### Current behavior
TypeError: t is undefined[Learn More]
