### ISSUE TITLE
Wrong position of clear button on AutoComplete, ComboBox and MultiSelect in RTL in IE 

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#3832]
### Bug report
The clear button is on the right in the input and covers the selected value.

### Reproduction of the problem
http://demos.telerik.com/kendo-ui/autocomplete/right-to-left-support
http://demos.telerik.com/kendo-ui/combobox/right-to-left-support
http://demos.telerik.com/kendo-ui/multiselect/right-to-left-support
Use a LESS theme, type something in the input so that the clear button is visible and select a value.

### Current behavior
![image](https://user-images.githubusercontent.com/6614183/29059238-41d94374-7c1d-11e7-826d-ec987a5312b4.png)
![image](https://user-images.githubusercontent.com/6614183/29059265-669a563a-7c1d-11e7-9648-789a10737f1f.png)
![image](https://user-images.githubusercontent.com/6614183/29059342-c8efa63c-7c1d-11e7-9671-744e64287ccb.png)

### Expected/desired behavior
The clear button is on the left, as in SASS themes
![image](https://user-images.githubusercontent.com/6614183/29059401-0e0eca4a-7c1e-11e7-838b-3efff2b4706a.png)

### Environment

* **Kendo UI version:** 2017.2.621+
* **Browser:** [IE9+]

**Comment by mparvanov** [comment]
The issue is still reproducible in Internet explorer for Combobox, E.G. Default theme
