### ISSUE TITLE
It is not possible to change checkbox value in batch editing on devices with Touch and Mouse.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3836]
### Bug report

It is not possible to change checkbox value in batch editing on devices with touch and mouse.

### Reproduction of the problem

This could be observed in our online demo:  http://demos.telerik.com/kendo-ui/grid/editing

### Environment

* **jQuery version:** x.y
* **Browser:** [Chrome XX | Firefox XX  ]

**Comment by ag-petrov** [comment]
Related to https://github.com/telerik/kendo-ui-core/issues/2724

**Comment by Alex-Bubblemaster** [comment]
Raising priority, also reported in ticket with ID 1148726

**Comment by Alex-Bubblemaster** [comment]
As a temporary workaround, before we can offer a fix, check if the device is touch enabled. If it is, use native checkboxes, if it is not, render the styled Kendo UI checkboxes. Example:

[kendo.support](https://docs.telerik.com/kendo-ui/api/javascript/kendo#fields-support)
```
 columns: [
   { field: "Discontinued", width: 120, editor: customBoolEditor }
]

function customBoolEditor(container, options) {
  var guid = kendo.guid();
  if(!kendo.support.touch){                    
    $('<input class="k-checkbox" id="' + guid + '" type="checkbox" name="Discontinued" data-type="boolean" data-bind="checked:Discontinued">').appendTo(container);
    $('<label class="k-checkbox-label" for="' + guid + '">​</label>').appendTo(container);
    } else {
    $('<input id="' + guid + '" type="checkbox" name="Discontinued" data-type="boolean" data-bind="checked:Discontinued">').appendTo(container);
    }
}
```
