### ISSUE TITLE
Menu, ComboBox and DropDownList are not closing correctly with jQuery 3.x.x

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#3840]
### Bug report
Menu, ComboBox, DropDownList are closing upward, above the parent element.

### Reproduction of the problem
1. Open the Dojo - [http://dojo.telerik.com/unIPi](http://dojo.telerik.com/unIPi)
2. Hover fast over the Menu elements or double click fast on the ComboBox or DropDownList

### Current behavior
[screencast](https://www.screencast.com/t/igPzE0hDGXSx)
The list with the items is closing upward above the widget.

### Expected/desired behavior
The list with the items has to close below the widget.

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** 3.x.x
* **Browser:** [all ]

**Comment by nenchef** [comment]
Reported in TicketID: 1145456
