### ISSUE TITLE
JavaScript error thrown on saving Scheduler event with invalid date format entered in Start/End inputs

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#3846]
### Bug report
Invalid dates entered in Create/Edit event Start/End inputs are not validated (rejected as invalid) and a JavaScript error is thrown on saving the event.

![image](https://cloud.githubusercontent.com/assets/961037/13144426/3686e736-d653-11e5-94f9-fa33501e0231.png)

### Reproduction of the problem
1. Go to http://demos.telerik.com/kendo-ui/scheduler/index
2. Double click on a time slot to open the popup for creating an event.
3. Several scenarios for entering invalid date for Start/End:
- Case 1 - write some random text instead of AM/PM
- Case 2 - delete the space between the minutes and AM/PM - "6/10/2013 8:00AM" (no space between 8 AM)
- Case 3 - fill for start : "2015/8/26 08:00 AM" and End: "2015/8/29 12:00 AM" (**Note**: kendo.parseDate("2015/8/26 08:00 AM") works, but the DatePicker expects "8/26/2015" format only)

4. Click "Save" button.

### Current behavior
Uncaught TypeError: Cannot read property 'getTimezoneOffset' of null

### Expected/desired behavior
Date format is validated, e.g. rejected on blurring the input - The previous valid date is entered.
OR
Date format is validated, e.g. rejected on blurring the input - a validation message appears, showing that the entered date does not match the valid format.

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

### Workarounds for avoiding invalid dates entering
- The following [Dojo snippet](http://dojo.telerik.com/idomoB) shows how to make pickers' inputs readonly, thus only valid dates could be selected through the picker buttons.
- The following [Dojo snippet](http://dojo.telerik.com/ASosI) shows how to reject the invalid value entered in Start/End picker and keep its previous valid date.

**Comment by zdravkov** [comment]
Also mentioned in ticket 1177399
