### ISSUE TITLE
Grid can throw an exception in _page timer callback if grid was destroyed

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#3848]
### Bug report

Grid._page method contains following code:
```js
that._timeout = setTimeout(function () {
                        if (!that._scrolling) {
                            if (delayLoading) {
                                kendo.ui.progress(that.wrapper.parent(), true);
                            }
                            dataSource.range(skip, take, function () {
                                kendo.ui.progress(that.wrapper.parent(), false); // fails here
                                callback();
                                that.trigger(PAGE);
                            });
                        }
                    }, 100);
```
which fails, when grid were destroyed between setTimeout call and timer callback call with error like this:
```
TypeError: Cannot read property 'parent' of null
```
because callback doesn't check if grid still alive or not.

### Environment

* **Kendo UI version:** 2017.3.1026

**Comment by matanasov** [comment]
@ag-petrov @Stamo-Gochev 
Please advice!

**Comment by Stamo-Gochev** [comment]
@MaceWindu Indeed, this can happen, but the default setting for the virtual scrolling is not to use a timeout (this is done in the virtual scrollable internally), so can you send a runable example, which demonstrates how the problem can be reproduced?

**Comment by MaceWindu** [comment]
I'm trying to reproduce it but without success yet. We observed this error only once and I don't think we will see it again soon, as we already deployed fix where we patched kendo grid  to perform a check in this callback. I will add more details if I will be able to reproduce it.

**Comment by MaceWindu** [comment]
Btw, maybe this stack trace will help you:

repored stack for minified script:
```js
TypeError: Cannot read property 'parent' of null
    at <script_file>
    at init.range (<script_file>)
    at <script_file>
    at Object.success (<script_file>)
    at <script_file>
    at u (<script_file>)
    at Object.fireWith [as resolveWith] (<script_file>)
    at Object.a.(anonymous function) [as resolve] (<script_file>)
    at Object.200 (<script_file>)
    at u (<script_file>)
```
stack, restored from sourcemaps
```js
Restored Stack: 
	_page(...) at kendo.grid.js (529, 64)
	range(...) at kendo.data.js (3052, 25)
	range(...) at kendo.data.js (3061, 42)
	_prefetchSuccessHandler(...) at kendo.data.js (3182, 29)
	read(...) at [transport.read in our custom grid wrapper]
	fire(...) at jquery.js (3317, 31)
	fireWith(...) at jquery.js (3447, 7)
	Unresolved frame: NoMatchingMapingInSourceMap
	requestData.200(...) at [success callback in our ajax helper] (104, 29)
	fire(...) at jquery.js (3317, 31)

```

**Comment by MaceWindu** [comment]
I don't see anything in our wrapper that could make it different, except having transport.read function, that calls our own fetch code and pass results to options.success callback, when data is ready.

**Comment by Stamo-Gochev** [comment]
@MaceWindu In order for us to confirm whether this is a bug or not, a runable Dojo example is required. Please right back to us when such an example can be provided and the steps to reproduce the problem.
