### ISSUE TITLE
Spreadsheet validation hint displays twice

### ISSUE THREAD

**Issue by adrobyazko-softheme** [telerik/kendo-ui-core#3850]
### Reproduction of the problem
Steps for reproducing:
1. Go to https://demos.telerik.com/kendo-ui/spreadsheet/index
2. Setup Data Validation to the cell
![image](https://user-images.githubusercontent.com/3669463/33983772-0d12f4e0-e0be-11e7-926d-6e9935b792aa.png)
3. Input "incorrect" value
![image](https://user-images.githubusercontent.com/3669463/33983815-2eebfdaa-e0be-11e7-928f-a92a354761ef.png)
4. Close validation popup by 'Close' button
![image](https://user-images.githubusercontent.com/3669463/33983842-49657076-e0be-11e7-8ad3-c9cf9b5ecb40.png)

### Current behavior
First popup closed. Second validation popup displayed.
![image](https://user-images.githubusercontent.com/3669463/33983872-5a34d78e-e0be-11e7-9909-e2e2b039dead.png)

### Expected/desired behavior
Spreadsheet validation hint displays once.

### Environment https://demos.telerik.com/kendo-ui/spreadsheet/index
* **Kendo UI version:** 2017.3.1026
* **jQuery version:** 1.12.3
* **Browser:** [Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by Juveniel** [comment]
The issue can also be reproduced whith invalid formula:
`={{'';;}}`

**Comment by Dimitar-Goshev** [comment]
The issue is no longer reproducible with R3 2018 SP1 (2018.3.1017)
