### ISSUE TITLE
Wrong position of Tooltip placed in iframe in IE and Edge

### ISSUE THREAD

**Issue by magdalenaan** [telerik/kendo-ui-core#3851]
### Bug report
Position of the tooltip on the first and second opening is different.
The issue is reported in the ticket with ID 1144672.

### Reproduction of the problem
1. Open the following [Dojo sample](http://dojo.telerik.com/@geeforceone/eSUTA) in IE11/Edge
2. Hover the top right element to open the tooltip.
3. Close the tooltip.
4. Hover the element again.

### Current behavior
On second and consecutive openings, the tooltip is displaced to the left.
![2017-12-14_1135_001](https://user-images.githubusercontent.com/4389590/33985384-1c066a22-e0c3-11e7-963a-31c6106a4c7a.png)

### Expected/desired behavior
![2017-12-14_1135](https://user-images.githubusercontent.com/4389590/33985392-22801d12-e0c3-11e7-813e-9b51d4747446.png)

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** IE 11, Edge 40

**Comment by mvgmvg** [comment]
When the same sample is opened in IE without using iframe (by a local project), there appear scrollbars after the second tooltip opening.


![2017-12-18_1536](https://user-images.githubusercontent.com/4389590/34108570-43155102-e409-11e7-9d6e-22ade0055a72.png)

**Comment by magdalenaan** [comment]
The issue is not reproducible in Microsoft Edge v107.0.1418.26.
