### ISSUE TITLE
Unexpected focus of AutoComplete's first search result item with slow filter requests and highlightFirst false

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3852]
### Bug report
The AutoComplete first option is focused incorrectly, when filter requests to the server are slow, although [highlightFirst](https://docs.telerik.com/kendo-ui/api/javascript/ui/autocomplete/configuration/highlightfirst) is set to false. Note that its default value is also false.

### Reproduction of the problem
[Reproduction video](https://user-images.githubusercontent.com/77701769/120377762-39279100-c326-11eb-911c-f58575846598.gif)
1. Run the following [Dojo example](https://dojo.telerik.com/iGInEwUB) or the [Server Filtering demo](https://demos.telerik.com/kendo-ui/autocomplete/serverfiltering)
2. Click on the AutoComplete and type `gran` - Grandma's Boysenberry Spread is filtered
3. Blur the AutoComplete
4. Set browser throttling (3G Slow) to simulate slow connection speed, which makes reproduction easier. Keep dev tools on Network tab to observe the filter requests.
5. Click on the AutoComplete after `gran` and type `d` - this triggers a filter request.
6. While the above filter request is still in progress, immediately after typing `d` press `backspace` to delete d - this triggers another filter request.

### Current behavior
When the first filter request completes, Grandma's Boysenberry Spread is filtered in the search results.
And then when the second filter request completes, Grandma's Boysenberry Spread becomes focused, although highlightFirst is false.

Note that when the item is highlighted, pressing Tab to blur the component selects the item in the AutoComplete.

[Screencast](https://www.screencast.com/t/ss1d9fLUp)

### Expected/desired behavior
The first option of the list should not be focused when highlightFirst option is set to false.

### Environment
* **Kendo UI version:** 2021.2.511
* **Browser:** all

**Comment by jhdalal** [comment]
I think this matches with the issue #4428 that I filed. Please see **Workaround** section for a possible fix.

**Comment by Dimitar-Goshev** [comment]
Increasing priority - reported in https://github.com/telerik/kendo-ui-core/issues/4428 and https://github.com/telerik/kendo-ui-core/issues/6443 . When addressing the issue, check the related issues for additional scenarios, if needed.

**Comment by nelito987** [comment]
Reported in ticket id: 1567327
