### ISSUE TITLE
kendo-ui-grids-vue-wrapper 无法下载

### ISSUE THREAD

**Issue by corala** [telerik/kendo-ui-core#3854]

**Comment by corala** [comment]
### Bug report
An unexpected error occurred: "http://r.cnpmjs.org/@progress%2fkendo-grids-vue-wrapper: not_found"

**Comment by matanasov** [comment]
There is a typo in the address. This one works:
http://r.cnpmjs.org/@progress%2fkendo-grid-vue-wrapper
