### ISSUE TITLE
AngularJS ListBox template cannot access the functions inside the scope

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#3860]
### Enhancement

AngularJS ListBox template cannot access the functions inside the scope

### Reproduction of the problem

http://dojo.telerik.com/OwoFEL/3

### Expected/desired behavior

The function should be invoked. For example:
http://dojo.telerik.com/OwoFEL/6

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
