### ISSUE TITLE
e.matches error with PDF Export 

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#3861]
### Bug report

Js error : e.matches error with PDF Export is thrown when exporting a page

### Current behavior
error is observed

### Expected/desired behavior
page is exported correctly

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by zdravkov** [comment]
Is there a way to catch such errors so that they can be logged? ([ticket](https://admin.telerik.com/default.aspx?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1144715&SM=0))

**Comment by mishoo** [comment]
@zdravkov seems not, as the error occurs in asynchronous code (e.g. your try/catch block finishes by the time the error is thrown).  I will investigate shortly.

**Comment by mishoo** [comment]
@zdravkov I pushed a fix.

**Comment by abhijitchoudhary** [comment]
I apologize for missing this earlier but is the Dojo example public? The sample HTML I had submitted contains a lot of private user information. I will need you to take this down immediately if it’s public.

Thanks!
Abhijit

**Comment by zdravkov** [comment]
I  would like to appoligize for this mistake. I have removed the dojo from this issue and it will be down as soon as possible.
