### ISSUE TITLE
Spreadsheet custom editor button is not visible in frozen columns scenario

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-ui-core#3862]
### Bug report
Spreadsheet custom editor button is not visible when the cell that has the custom editor belongs to the last frozen column.

Related https://github.com/telerik/kendo-ui-core/issues/3254

Related to: #3105 and #5097

### Reproduction of the problem
1. Open the following Dojo: https://dojo.telerik.com/IhaKa/3
2. Select the K2 cell
3. The editor button will not be displayed.

### Current behavior
https://www.screencast.com/t/ckMV69DfH

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** all

**Comment by veselints** [comment]
Also reported in Ticket ID: 1364441

**Comment by Juveniel** [comment]
This issue can also be reproduced if the last column is hidden - [Dojo example](https://dojo.telerik.com/oxiqIweq/3).

* Click on S1 or S2 and notice that the editor is not visible.
