### ISSUE TITLE
DropDownList autoWidth option cannot be set through data attribute

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3863]
### Reproduction of the problem
[Dojo](http://dojo.telerik.com/olUlIZ) example.

### Current behavior
autoWidth cannot be enabled with data attribute: **data-auto-width="true"**

### Expected/desired behavior
**data-auto-width="true"** enables the widget's autoWidth functionality.

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by andreasandreou** [comment]
Is this closed because it is fixed? In which version?
