### ISSUE TITLE
Kendo UI grid for AngularJS detail row automatically collapse after do a dataSource.read();

### ISSUE THREAD

**Issue by ranjan49** [telerik/kendo-ui-core#3868]
I have a Kendo UI grid with child grid in AngularJS. I want to retain the expanded rows after do a datasource.read(). Right now its getting collapsed after editing any rows and save.

any help will be appreciated.

**Comment by matanasov** [comment]
**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !
