### ISSUE TITLE
Pasting text in Spreadsheet formula bar does not change the selected cell's value

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3869]
### Bug report
In Chrome and Firefox manually entering text in the Spreadsheet's formula bar changes the selected cell's value as expected, but pasting text from the clipboard does not, unless the user continues typing text after pasting.  

### Reproduction of the problem
Reproducible in the demos. [Screencast](https://www.screencast.com/t/N4I0hTMY).

### Current behavior
The selected cell's value does not change on pasting text in the formula bar. 

### Expected/desired behavior
The selected cell's value reflects the pasted text. 

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** x.y
* **Browser:** [Firefox 57, Chrome 63]

**Comment by mishoo** [comment]
No longer reproducible.
