### ISSUE TITLE
Detail template container is not removed when k-detail-template is used with AngularJS

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#387]
Can be reproduced here:

http://dojo.telerik.com/ECItu

**Comment by mikila85** [comment]
problem happening again.

**Comment by underlog** [comment]
The dojo above seems to work when updated here - http://dojo.telerik.com/@petyosi/OmuyU

**Comment by mikila85** [comment]
its back in appgyver supersonic steroids (phonegap wrapper on ipad 7.1.2 ios)
dunno why but ur element.remove doesnt work there and the template shows :(

**Comment by mikila85** [comment]
New info i was able to extract from the page:

View	Time	Level	Message
http://localhost/index.html#/kendo	11:07:56.683	info	
"TypeError: 'undefined' is not an object (evaluating 'e.targetTouches[0]') - undefined:undefined"
http://localhost/index.html#/kendo	11:07:56.700	info	
"TypeError: 'undefined' is not an object (evaluating 'e.targetTouches[0]') - undefined:undefined"
http://localhost/index.html#/kendo	11:07:55.865	info	
"TypeError: 'undefined' is not an object (evaluating 'e.targetTouches[0]') - undefined:undefined"
http://localhost/index.html#/kendo	11:07:55.453	info	
"TypeError: 'undefined' is not an object (evaluating 'e.targetTouches[0]') - undefined:undefined"

**Comment by underlog** [comment]
Hi, 

The problem you experience seems to be specific to your environment/setup; the error you have posted does not seem related to the issue at hand, too. 

At this point, we can't help any further. You may consider contacting the appgyver support channel, in case you have a concrete test case which works in the browser but fails in their environment.
