### ISSUE TITLE
Change and Deselect events should be triggered once when the Clear button of the MultiSelect is clicked and t here are multiple items selected.

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3872]
### Bug report

Change and Deselect events should be triggered once when the Clear button of the MultiSelect is clicked and there are multiple items selected.

### Reproduction of the problem
use the following code, demonstrating how the change/deselect event console is logged for each removed item through the X button

```html
<select id="multiselect" multiple="multiple">
    <option>Item1</option>
    <option>Item2</option>
</select>
<script>
var multi = $("#multiselect").kendoMultiSelect({
  change: function(e) { 
    console.log(e)  
  }
}).data("kendoMultiSelect");  
</script>
```
### Current behavior
The change/deselect event is triggered for each deleted item, for the Clear Button click event.

### Expected/desired behavior
The change/deselect event is triggered only once, for the Clear Button click event.

### Workaround:

1. Stop the immediate propagation of the Click event on the clear button
1. Set an empty value to the MultiSelect through its **.value()** method of the multiselect
1. Manually trigger the change event with the **.trigger()** method of the multiselect

```html
<select id="multiselect" multiple="multiple">
    <option>Item1</option>
    <option>Item2</option>
</select>
<script>
var multi = $("#multiselect").kendoMultiSelect({
  change: function(e) { 
    console.log(e)  
  }
}).data("kendoMultiSelect");
  
  $(document).ready(function(){

    $(".k-clear-value").mousedown(function(e){
      debugger;
      e.preventDefault();
      e.stopImmediatePropagation()
      multi.value("")
      multi.trigger("change")    
    })  
  })
  
</script>
```

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

**Comment by jivanova** [comment]
Fixed change event. However, deselect event should be fired per every item that is to be removed: https://docs.telerik.com/kendo-ui/api/javascript/ui/multiselect#events-deselect
