### ISSUE TITLE
### Need DateTimePicker in Kendo SpreadSheet

### ISSUE THREAD

**Issue by bilal0106** [telerik/kendo-ui-core#3875]
i want to display datetime picker for specific coulums but the datetime picker do not appear like this example but i need a time https://demos.telerik.com/kendo-ui/spreadsheet/validation

**Comment by matanasov** [comment]
**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !
