### ISSUE TITLE
one js/css file for all components 

### ISSUE THREAD

**Issue by devjaw** [telerik/kendo-ui-core#3884]
hello 
i just downloaded the latest version of kendo ui core but i didn't find the following files : 
- kendo.common.min.css
- kendo.default.min.css
- kendo.ui.core.min.js

also, i don't want to use CDN because the files in CDN is old and it is created in 2014.

**Comment by matanasov** [comment]
@devjaw 
If you build the resources (gulp build) you should be able to find them in:
```
  \dist\styles\web\kendo.common.core.min.css
  \dist\styles\web\kendo.default.min.css
  \dist\js\kendo.ui.core.min.js
```
The CDN provides all kendo-ui-core releases. Just change the version in the script reference - for example:
```
<script src="http://kendo.cdn.telerik.com/2017.3.1026/js/kendo.ui.core.min.js"></script>
```
