### ISSUE TITLE
Popup closes in IE10

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-ui-core#389]
Steps to reproduce:
1. Initialize a MultiSelect with autoBind = false
2. Click on the widget
3. Wait for the popup to open
4. Popup shows for a moment, then closes. Happens only on the first expand and if enough items are present

[Example](http://trykendoui.telerik.com/aQuR/3)

**Comment by ggkrustev** [comment]
The issue is related to the large data set that is shown in the popup. This forces the IE to close.
We will further investigate the case, but probably the best solution is to use `virtualization`

**Comment by tapopov** [comment]
It is still unclear what triggers the unexpected focusout event in IE10. This issue however, occurs only when huge amount of items are rendered, in which case virtualization is preferred for performance reasons.
