### ISSUE TITLE
deepEqual is not a function - React

### ISSUE THREAD

**Issue by laura-rodriguez** [telerik/kendo-ui-core#3893]
Hi,
I am having this issue using the grid from the React wrapper.
I have installed the deep-equal dependency but without success.

Here the details of the error:

main.js:193120 Uncaught TypeError: deepEqual is not a function
at reconcileConfiguration (main.js:193120)
at Grid.componentWillReceiveProps (main.js:193053)
at main.js:288153
at measureLifeCyclePerf (main.js:287618)
at ReactCompositeComponentWrapper.updateComponent (main.js:288152)
at ReactCompositeComponentWrapper.receiveComponent (main.js:288089)
at Object.receiveComponent (main.js:46769)
at ReactCompositeComponentWrapper._updateRenderedComponent (main.js:288296)
at ReactCompositeComponentWrapper._performComponentUpdate (main.js:288266)
at ReactCompositeComponentWrapper.updateComponent (main.js:288187)

Any clues?

Thanks!

Laura.

**Comment by matanasov** [comment]
**Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**Comment by cbastos** [comment]
I have the same problem!

**Comment by cbastos** [comment]
I have seen that the error is in the code 
`
var reconcileConfiguration = function (oldConfiguration, newConfiguration, widget) {
    if (!deepEqual(oldConfiguration, newConfiguration, { strict: true })) {
        widget.setOptions(newConfiguration);
    }
};
`
the "deepEqual" is not a function, it's an object with a "default" property that is a function. Seems that has an error with the module import.

I've tried to install other version of this dependency but fails.

Can you fix it?

**Comment by cbastos** [comment]
I've fixed with a workaround in webpack config: include a custom transformation with:
`
module.exports = function transform(content) {
    return content.replace(
        'if (!deepEqual(oldConfiguration, newConfiguration, { strict: true })) {',
        'if (!deepEqual.default(oldConfiguration, newConfiguration, { strict: true })) {'
    );
};
`

referenced in config:

`
  module: {
    loaders: [
      {
        test: /\.(js)$/,
        loader: './npm-scripts/build/deepEqual'
      },
`

**Comment by GrooyaO** [comment]
Any other way of solving this? 
Getting it in  "@progress/kendo-grid-react-wrapper": "2021.3.1112"
