### ISSUE TITLE
The columns and the footer are misaligned when the setOptions method is called after one of the column was resized manually.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#3895]
### Bug report

The columns and the footer are misaligned when the setOptions method is called after one of the columns was resized manually.

### Reproduction of the problem

The issue can be observed at the following Dojo: http://dojo.telerik.com/uHUpa/2

### Environment

* **Browser:** [all]

**Comment by VicTachev** [comment]
If the sum of column widths is less than that for the Grid the specified widths are ignored and the columns are resized automatically by the browser. We recommend to set width for all column when their sum exceeds the width of the Grid and the goal is to achieve horizontal scrolling.

https://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance#column-widths
