### ISSUE TITLE
Tooltip opens and closes in a loop when hovering Grid td elements

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3896]
### Bug report
Regression since 2017.3.913 (R3 2017).

### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/inUVE) example. [Screencast](https://www.screencast.com/t/UnmANFNsdh3G).

### Expected 
https://dojo.telerik.com/EtexaSaJ/4
Hover over the tooltip

### Environment
* **Kendo UI version:** 2018.3.911
* **jQuery version:** x.y
* **Browser:** [Chrome 63, Firefox 57]

**Comment by nelito987** [comment]
Another case - [https://dojo.telerik.com/@NeliKondova/AkeXO](https://dojo.telerik.com/@NeliKondova/AkeXO)

**Comment by Iankodj** [comment]
Related to: https://github.com/telerik/kendo-ui-core/issues/3721

**Comment by Jekata** [comment]
The problem also affects the tooltip of the RadMap for UI for ASP.NET AJAX wrapper.

**Comment by mparvanov** [comment]
Reopening the issue since hovering over the tooltip still closes it,
