### ISSUE TITLE
In Spreadsheet deleted formula cells are shifted up, when exported from xlsx file

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3899]
### Bug report
In Spreadsheet deleted formula cells are shifted up, when exported from xlsx file.

### Reproduction of the problem
* In Excel, create the following table
| 1 | 2 |
| 1 | 2 |
| 1 | 2 |
| 1 | 2 |
* Type the folloing formula in cell C1: `=A1+B1`
* Drag-copy the formula to the below cells;
* Select cells C2 and C3;
* Press delete to delete their contents. The final table will look like:
| 1 | 2 | 3 |
| 1 | 2 |
| 1 | 2 |
| 1 | 2 | 3 |
* Save the file and import it in Kendo Spreadsheet. The imported table will look like:
| 1 | 2 | 3 |
| 1 | 2 | 3 |
| 1 | 2 | 0 |
| 1 | 2 | 0 |
Moreover, the C3 and C4 cells will hold formula references as the following: `=A5+B5` and `=A6+B6`

**Comment by mishoo** [comment]
This was fixed IIRC, but it would be good to be re-tested.

**Comment by Dimitar-Goshev** [comment]
This was fixed in R2 2018 - 2018.2.516
