### ISSUE TITLE
Gantt does not blur inline edited tasks, when the reordering is disabled

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#3901]
### Bug report

Gantt does not blur inline edited tasks, when the reordering is disabled only when you attempt to click on the TreeList view of the Gantt.

### Reproduction of the problem
Use the following dojo example, where the reordering is disabled as follows:
..editable: {reorder: false},
1. Edit the title of some of the tasks.
2. Click on some other task in the TreeList view, in order to apply the currently updated value

video on the repro:
[https://monosnap.com/file/AXEhZwy1xKthpwq9iv0qbtCfZjkLN6](https://monosnap.com/file/AXEhZwy1xKthpwq9iv0qbtCfZjkLN6)

### Current behavior
The currently edited cell cannot get blurred, hence, the update of the field cannot be performed. 

### Expected/desired behavior
The cell should be able to get blurred, when you click whenever on the TreeList view.

### Workaround
Handle the click event of the treelist view Gantt, in order to manually trigger the blur event on the currently edited cell ():

```js
<script>    
    $(document).ready(function (e) {
        $(".k-grid-content").on('click', function (e) {
            var gantt = $("#gantt").getKendoGantt(); //use Name of your Gantt
                var editable = gantt.list.editable;
                if ($(e.target).is(".k-input") || $(e.target).closest(".k-datepicker").length) {
                    return;
                }
                if (editable && editable.end()) {
                    gantt.list._closeCell();
                }
            });     
    })   
</script>
```
### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all ]

**Comment by veselints** [comment]
Also reported in Ticket ID: 1382688

**Comment by veselints** [comment]
Also repported in 1521271
