### ISSUE TITLE
Scheduler events width not properly calculated in RTL scenarios when a scrollbar is displayed

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3909]
### Reproduction of the problem
[Dojo ](http://dojo.telerik.com/OQoYe) example. [Screenshot](https://www.screencast.com/t/fAXusASskl). 

### Expected/desired behavior
Events are aligned correctly within the timeslots, based on their start and end time. 

### Environment

* **Kendo UI version:** 2017.3.1026
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by kepeter** [comment]
It is a year long issue and seems no one touched it!

**Comment by IvanDanchev** [comment]
We apologize for the delay in fixing this bug. Every release contains a number of issues fixed (see the [Release History notes](https://www.telerik.com/support/whats-new/kendo-ui/release-history)). Unfortunately, this specific issue did not make it into any of the releases in between R1 2018 and R1 2019.  We will do our best to fix it in one of the upcoming releases.
