### ISSUE TITLE
values are not selected with virtualization and autoBind: "false"

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3911]
### Bug report

Selected items that are set with the values option are not being selected upon opening the MultiSelect dropdown.

The behavior can only be reproduced with subsequent version of Kendo UI 2017 R3. 

The commit that affected the above behavior - https://github.com/telerik/kendo/commit/b3e94a6037e9f9b06c290a895d90a9d157db84b3

### Reproduction of the problem

The problem can be reproduced with [the following Dojo example](http://dojo.telerik.com/eCUxOY).

Steps to reproduce:
* Open the MultiSelect

### Current behavior

Initial values are not being selected in the TagList after opening the MultiSelect dropdown.

### Expected/desired behavior

Initial values should be selected in the TagList on opening the MultiSelect.

### Environment

* **Kendo UI version:** 2017.3.1026
* **Browser:** [all]

**Comment by InciteGmbH** [comment]
Dear Colleagues

Could you set a higher priority please. This is an important feature for us.

Thanks a lot.
Incite GmbH, Marc Huber

**Comment by ivanchev** [comment]
The priority has already been increased and we will fix the issue for the upcoming R1 2018 release.
