### ISSUE TITLE
Where is the source for kendoGrid?

### ISSUE THREAD

**Issue by dumptruckman** [telerik/kendo-ui-core#3916]
Forgive me if I'm not looking in the right place, but I'm trying to find the source for this `kendoGrid` function that I found [here](https://demos.telerik.com/kendo-ui/grid/keyboard-navigation). Thanks in advance!

**Comment by matanasov** [comment]
**Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**Comment by dumptruckman** [comment]
Is this really a support request? I'm looking into contributing but I can't even find the code I'm looking to modify.
