### ISSUE TITLE
Ship the Kendo.Mvc.Export assembly with the installation package

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3920]
Currently, the Kendo.Mvc.Export.dll file is available only by downloading and extracting the Kendo UI for MVC archive package.

Installing via the MSI installer or the Telerik Control Panel does not include that assembly. 

It would be easier to be used if it is shipped via these sources as well. 

Related to Ticket 1148621.

**Comment by Dyanko** [comment]
http://teampulse.telerik.com:9896/Project/27/Feedback/Details/348960-update-kendo-ui-mvc-installers-to-include-kendo-mvc-export-folder

**Comment by Iankodj** [comment]
With the next official release the **Kendo.Mvc.Export** assembly will be shipped with the installation package and will be available in the installation folder under the **export/binaries** folder.
