### ISSUE TITLE
Disabled Button in Toolbar should have focus stylization

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#3923]
Related to: https://github.com/telerik/kendo-ui-core/issues/1566

https://dojo.telerik.com/emALIz

1. Click on the last enabled button
2. Use Tab key to navigate to teh disabled splitbutton

Actual: The spitbutton is highlighted as it is enabled. 

Expected: The decoration of the splitbutton to not show it as focused.

**Comment by Dimitar-Goshev** [comment]
Remaining issues after a fix is applied:
- Flat - different colors of the two button parts and unexpected rounded corners:
![image](https://user-images.githubusercontent.com/6614183/35328686-d95ffa22-0105-11e8-8d33-dc82e562521f.png)

- Fiori - different colors of the two button parts:
![image](https://user-images.githubusercontent.com/6614183/35328802-41e394d2-0106-11e8-8d2f-04e644da3ff3.png)

- All  LESS themes, except Fiori, Material, MaterialBlack, Nova and Office 365 - difference between the border of the two button parts:
![image](https://user-images.githubusercontent.com/6614183/35329076-29e5a4d2-0107-11e8-864f-9a114696cf5b.png)

![image](https://user-images.githubusercontent.com/6614183/35328934-b171768e-0106-11e8-8124-599f6b725658.png)
