### ISSUE TITLE
ComboBox Change Event doesn't trigger with the Kendo UI 2018 R1 release

### ISSUE THREAD

**Issue by 06b** [telerik/kendo-ui-core#3926]
### Bug report

ComboBox Change Event doesn't trigger with the Kendo UI 2018 R1 release
### Reproduction of the problem
https://demos.telerik.com/kendo-ui/combobox/events

1. Click into the combobox field
2. Start typing 'ite'
3. Use the arrow keys on the keyboard to highlight an item
4. Click the enter key
5. Change Event does not fire

### Current behavior
Clicking into the combobox field and using the arrow keys will trigger the change event however that is different than when attempting to search within a combo or when using the steps to reproduce and using the mouse to select an item.

### Expected/desired behavior
This worked in previously in Kendo UI 2017 R3 SP2 and can be tested by Editing the example above and changing the library to that version.

### Environment

* **Kendo UI version:** 2018.1.117
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by samudrak** [comment]
Is this really fix . we are using v2018.1.221 but we can see still bug exists .

Steps 
Open the Combobox.
Select an item with the mouse: First change event is fired.
Click outside of the Combobox: Second change event is fired.

**Comment by jivanova** [comment]
Hi all, the issue should be fixed in our 2018.1.221 version. 

@samudrak  Could you please test on our demo site?

https://demos.telerik.com/kendo-ui/combobox/events 

If the issue in not reproducible there could you verify the version of your project and the exact setup of the ComboBox and if certain scenario is still not handled?

**Comment by samudrak** [comment]
Try this one on EDGE  it does not work.

[](http://dojo.telerik.com/oLAxeBuW)

Dom Structure on Edge. 

![edge](https://user-images.githubusercontent.com/2469444/39899413-5b3ec61e-54d9-11e8-8c39-7adb528fa0f0.JPG)

Dom Structure on Crome
![crome](https://user-images.githubusercontent.com/2469444/39899502-efe17c3a-54d9-11e8-9dd6-0012d13ada5a.JPG)

on edge wrapper div with k-animation-container class is missing .  There for Menu Items are rendered but not displaying .
