### ISSUE TITLE
Custom action click event not triggered

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3927]
### Bug report

Custom action click event is not triggered due to pointer-events. 

The issue can be reproduced only with the Kendo UI LESS Themes, where pointer-events are set to none for the .k-icon class. 

### Reproduction of the problem

The issue can be reproduced [on the following Dojo example](http://dojo.telerik.com/OVoVOq)

### Current behavior

Click event handler is not working when attached to the .k-icon-x element.

### Expected/desired behavior

Click event should work when attached to the .k-icon-x element.

### Workaround

Set pointer events to auto:

```css
<style>
  .k-icon {
    pointer-events:auto !important;
  }
</style>
```

### Environment

* **Kendo UI version:** 2018.1.117
* **Browser:** [all]

**Comment by mvgmvg** [comment]
This is expected behavior. Events should be attached to buttons or other icon's parent instead to the icon itself. Events are disabled advisedly, as icon element should have only decorated role.
