### ISSUE TITLE
Enhance the Tooltip's autoHide option or implement a new one (hideOn)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3933]
Since R3 2017 (related issue: #1908) setting **showOn** to "focus" changes the Tooltip's hide behavior. It no longer hides on mouseleave as specified in the **autoHide** [documentation](https://docs.telerik.com/kendo-ui/api/javascript/ui/tooltip#configuration-autoHide). 
[Dojo ](https://dojo.telerik.com/UkapEF)example.

An enhancement of the auto-hide behavior could include an option that would allow to specify the event that will trigger the Tooltip's hiding. For example a **hideOn** option that accepts: "mouseleave", "focusout" or "click" value. The **autoHide** option could be used only to enable/disable the widget's auto-hide behavior.

**Comment by Dimitar-Goshev** [comment]
The scenario above is logged as a regression bug: https://github.com/telerik/kendo-ui-core/issues/4553
This Enhancement item is proposing a way to resolve the bug, but it is a duplicate item on the same topic, so I will add a reference to it in the bug with a proper comment. I am closing this item to avoid duplication.
