### ISSUE TITLE
kendo issue with category/values axis position when more than one value axis are present

### ISSUE THREAD

**Issue by sorb999** [telerik/kendo-ui-core#3934]
### Bug report
kendo issue with category/values axis position when more than one value axis are present

### Reproduction of the problem
http://plnkr.co/edit/AbG4TtufLI6Ax1EkimbF?p=preview

### Current behavior
Category axis values at the middle of the charts for negative values

### Expected/desired behavior
Category axis values must be at the bottom of the charts for negative values

### Environment
All

**Comment by Stamo-Gochev** [comment]
@sorb999 The behavior is expected as the default position of the labels is not determined by the displayed values, but by default margin/alignment settings. This is why displaying negative values might require changing the position of the axis.

I will also reply to the support ticket on the same topic. If you have any additional questions, please post them in the ticket.
