### ISSUE TITLE
Headers inner column change the location between parent columns after reordering

### ISSUE THREAD

**Issue by alexeyburlo** [telerik/kendo-ui-core#3936]
### Bug report

Inner columns change the location between parent columns after reordering.

### Reproduction of the problem

The issue can be observed in the following Dojo: https://dojo.telerik.com/ijOBA

1. Move column "Header3" after column "Header2".

Headers inner column "Header2" moved into column "Header3"

### Environment

* **Browser:** [all]

**Comment by matanasov** [comment]
@ag-petrov 
The reported case is fixed. However, now the problem can be observed with a slightly different case:
   1.  Move column "Header2" before column "Header3".

**Comment by matanasov** [comment]
@ag-petrov
Still doesn't work for some scenarios:

Scen1:
1. Move column "Header3" before column "Header2" - all is fine.
2. Now move back column "Header3" after column "Header1" or after column "Header4" - not fine.

Scen2:
1. Move column "Header2" after column "Header3" - all is fine.
2. Now move back column "Header2" before column "Header1" or before column "Header4" - not fine.
