### ISSUE TITLE
Disabled anchor in Window prevents Tab navigation to other focusable elements (IE)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3938]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/UMOFe/3) example.
1. Focus the Window or the first input. 
2. Press Tab consecutively.

### Current behavior
After reaching the anchor the next focusable element cannot be focused by pressing Tab.

### Expected/desired behavior
All focusable elements can be focused. 

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** x.y
* **Browser:** [ IE11 ]

**Comment by Dimitar-Goshev** [comment]
Disabled links, buttons, inputs are expected to not be focusable in Window and Dialog. So they are skipped in the focus sequence and it is possible to focus all focusable elements.
