### ISSUE TITLE
Widget scrolls popup content over filter input in mobile device

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#394]
### Repro steps
1. Open [Server filtering demo](http://demos.telerik.com/kendo-ui/dropdownlist/serverfiltering)
2. Place the phone in "landscape" mode
3. Open the popup and filter with "ch"
4. Scroll the filtered result

Result:
![repro](https://cloud.githubusercontent.com/assets/495188/5066790/b7c0ffaa-6e42-11e4-8589-506d37bcb383.png)

**Comment by naskog** [comment]
On Android device when you perform 1-3 and open the DropDown again just the top of it is visible (the box in which you type). It is confusing for the user.

**Comment by naskog** [comment]
![dsc_0606](https://cloud.githubusercontent.com/assets/961037/7314588/806996b8-ea6e-11e4-9a57-cb2c9c526e40.jpg)

**Comment by valchev** [comment]
There is a regression in DropDownList rendering when Filter/FixedGroupHeader are present:

http://screencast.com/t/jvCqW6Nnxy
