### ISSUE TITLE
NumericTextBox does not reflect changes applied through setOptions

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#3945]
### Bug report

When using `setOptions` method to change NumericTextBox options, the new options are not applied if they require a visual change in the widget.

[Example](http://dojo.telerik.com/@tsveti/acesU)

Also applies to other properties that require visual changes like the `spinners` one.

### Environment

* **Kendo UI version:** 2018.1.117

Reported in: 1150526

**Comment by matanasov** [comment]
@ag-petrov 
The fix doesn't work for the `spinners` property as described by @TsvetinaIvanova
