### ISSUE TITLE
Group headers are not set correctly when group field is null or empty

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3947]
### Bug report

When DropDownList is configured with Virtualization and Grouping and the group field is an empty string or null, the respective item is displayed first in the dropdown. However, the subsequent group header is not being displayed.

### Reproduction of the problem

[Dojo example](https://dojo.telerik.com/UJOBah)

* Run the example and open the DropDownList
* Notice the second items 

### Current behavior

Group header is not set for subsequent items if there is an empty group field.

### Expected/desired behavior

Group header should be set if group fields is not empty.

### Environment

* **Kendo UI version:** 2018.1.117
* **Browser:** [all]

**Comment by zdravkov** [comment]
The widget is rendering correctly the data that is returned from the dataSource.view() - that is the way the items are sorted when the value of the grouped filed is empty string as it is seen in this [dojo](https://dojo.telerik.com/@zdravkov/APOJoxuq).

**Comment by Xenope** [comment]
I don't know why this one is closed, still the same behaviour as the one described in the first place :+1: 
https://dojo.telerik.com/orIzeSAn

We should have "Austria" set in the grouping on the sconde line, it's not here.

**Comment by Xenope** [comment]
Guys?

Any chance that this one has been fixed, see you fixed some other issues regarding the grouping (ie: [#4969](https://github.com/telerik/kendo-ui-core/issues/4969)) ? 

Still don't know why it was closed.

**Comment by zdravkov** [comment]
Hi @Xenope ,

I just saw the comments - somehow missed them earlier - please excuse me for this.
It seems that we have closed the issue by mistake - I have reopened it, proposed a fix for it and it is currently in a testing. Hope that it will be fixed soon.

Thank you for your concern with Kendo.

Greetings,
Plamen
