### ISSUE TITLE
Label HTML helper in the Scheduler Edit template does not render special characters

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3949]
### Bug report
Label HTML helper in the Scheduler Edit template does not render special characters. Instead, it displays their code number.

This is a regression bug introduced with R1 2018 release.

### Reproduction of the problem
Insert the following helper on the Scheduler Edit template view:
`@(Html.LabelFor(model => model.Title, "Probe durchgeführt"))`

When opening the edit form the above will be displayed as:
`<label for="Title">Probe durchgef&amp;\#252;hrt</label>`

In the Scheduler Editor template it will be generated as:
`\u003clabel for=\"Title\"\u003eProbe durchgef\u0026\\\\\\#252;hrt\u003c/label\u003e`

### Environment
* **Kendo UI version:** 2018.1.117

**Comment by veselints** [comment]
A workarownd would be to use the `<label>` element, instead of the HTML helper:
`<label for="Title">Probe durchgeführt</label>`

**Comment by zdravkov** [comment]
The issue was introduced by this [one ](https://github.com/telerik/kendo-ui-core/issues/3316)so it needs to be retested too.
