### ISSUE TITLE
Spreadsheet does not calculate properly the height of a cell with wrapped text.

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#3956]
### Bug report
Spreadsheet does not calculate properly the height of a cell with wrapped text. This happens, when the wrapped text should be placed on three or more lines.

### Reproduction of the problem
[Dojo here](https://dojo.telerik.com/uPiSa/4)

**Comment by Dimitar-Goshev** [comment]
The commit seems to fix the issue, but it changes the way we used to break words to a new row.
- Before the fix, Spreadsheet did what Excel does - if there is not enough space to fit a word on the same row, then that word starts on next row. And then if it does not fit, it is transferred to a new row:
Spreadsheet: 
![image](https://user-images.githubusercontent.com/6614183/42985034-4b9bb090-8bf8-11e8-8b47-ce8f6711a7f3.png)
Excel:
![image](https://user-images.githubusercontent.com/6614183/42985044-5200e64e-8bf8-11e8-966d-a8ddd7fd385c.png)

- After the fix, if there is some space on the same row, we put the next word there, although it does not fit and would be transferred to the next row. This leads to the strange situation where we place only one letter of a two letter word at the end of the row and transfer the other letter to a new row, e.g. "My":
![image](https://user-images.githubusercontent.com/6614183/42985061-69c47566-8bf8-11e8-9c9f-6acfa7947689.png)

**Comment by Dimitar-Goshev** [comment]
@mishoo After the latest fix word wrapping is OK. But there is wrong height in SASS themes (the first row with "My" is cut:
![image](https://user-images.githubusercontent.com/6614183/44024861-25894900-9ef7-11e8-89cf-169b513e2294.png)
