### ISSUE TITLE
Cells are not populated when fast typing

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3959]
### Bug report

SpreadSheet cells are not populated with values upon fast typing and navigating with the arrow keys, tab or enter. 

The issue seems related to the changes made for [the following item](https://github.com/telerik/kendo-ui-core/issues/3644).

### Reproduction of the problem

The issue can be reproduced on a relatively slow machine with [the following Dojo example](https://dojo.telerik.com/iQurO/2).

* Click on the first cell and type 1
* Press down arrow and type 1 (repeat multiple times)

### Current behavior

[Screencast](https://www.screencast.com/t/94ncCJu5Iw)

### Expected/desired behavior

Cells should be populated with values when fast typing.

### Environment

* **Kendo UI version:** 2018.1.117
* **Browser:** [all]

**Comment by mparvanov** [comment]
Was not able to replicate on a few machines with Kendo UI version 2019.2.619.
