### ISSUE TITLE
Virtual scrolling in MultiSelect. A user's selection is lost when the valueMapper function is not implemented.

### ISSUE THREAD

**Issue by DmitriiGaidukov** [telerik/kendo-ui-core#3963]
Hi, guys!  I’ve been trying to implement virtual scrolling for kendo-multi-select (in AngularJS) without valueMapper function. I thought it would be possible because I have no need for setting an initial value. Here it says:
> As of the Kendo UI R3 2016 release, the implementation of the valueMapper function is optional. It is required only if the widget contains an initial value or if the value method is used.
> https://docs.telerik.com/kendo-ui/controls/editors/combobox/virtualization?_ga=2.249157445.317358105.1517593638-1087625096.1516044431

It all seemed to be good until I noticed a problem: When I type something for filtering and select an item from the filtered list then this item is added up without a problem. But if I reopen the item list after that all the currently selected items will be lost. 
Having made an experiment with valueMapper I found out that implementation of the function solves my problem.   Actually the function's handler even gets called at the exact same moment when I was losing all selected items before. It looks like selecting an item through the filtering causes the need for valueMapper's call in the next opening of the drop down list.

Please tell me if it is really necessary to implement valueMapper function at this point or 
have I simply missed something? Thanks!

I use Kendo UI v2018.1.117.

Html:
```
<select kendo-multi-select k-options="statusListFilterOptions"
                                    k-ng-model="statusListIds"
                                    style="width:350px;" 
                                    class="form-control" 
                                    id="statusFilter" />
```

AngularJS controller:

       ```
        $scope.statusListIds = [];

        $scope.statusListFilterDataSource = new kendo.data.DataSource({
            sort: [{ field: "Name", dir: "asc" }],
            serverSorting: true,
            serverFiltering: true,
            serverPaging: true,
            pageSize: 80,
            type: "odata",
            transport: {
                read: function (options) {
                    stateEntityService.Query(options);
                }
            }
        });

        $scope.statusListFilterOptions = {
            placeholder: "Select statuses...",
            dataTextField: "Name",
            dataValueField: "id", 
            valuePrimitive: true, 
            dataSource: $scope.statusListFilterDataSource,
            height: 520,
            virtual: {
                itemHeight: 26
                //...the implementation of the valueMapper function solves the problem
            }
        }
```

**Comment by zdravkov** [comment]
I have tested the scenario in one test dojo but could not replicate the described issue. Would you please try to isolate it in some runnable dojo or project and point the exact steps to replicate it?

**Comment by DmitriiGaidukov** [comment]
@zdravkov  Ready https://dojo.telerik.com/ofOKU    
I took it from the demo https://demos.telerik.com/kendo-ui/multiselect/virtualization  
I've just commented out declaration of valueMapper function and setting the inital value. 

How to reproduce:
1. Perfom a filtration by typing some text and select any item from a filtered set. 
2. Open the list again at this precice moment the previous selection will disappear.

**Comment by zdravkov** [comment]
Thank you for elaborating the issue - it is a bug indeed and we will do our best to fix it as soon as possible.

**Comment by jivanova** [comment]
https://github.com/telerik/kendo/commit/1180586d72fdb8eabfabb3e62a5e180b5aa70264

**Comment by mparvanov** [comment]
The issue is reproducible with the current development version and the setup from the dojo example above.
Steps to reproduce:
1. Click on the multiselect input
2. Type 'Han'
3. Select one of the filtered items, e.g. the third one
4. Click again on the multiselect input
https://www.screencast.com/t/kJkfR1Dj2

**Comment by mparvanov** [comment]
The following issue is observed with the dojo example above after telerik/kendo-ui-core#3963
http://kendobuild-staging.openstack.progress.com/dojo-staging/uHuLolap 
1. Click on the multiselect input
2. Type 'Han'
3. Select one of the filtered items, e.g. the third one
4. Type 'Han'
5. Select one of the filtered items again
6. Click on the multiselect input
7. Press Backspace

An error is thrown: Uncaught TypeError: l.select(...).done is not a function

**Comment by zdravkov** [comment]
Hi @RavikantJagdale ,

I have tested the scenario once again with the latest version and it seems to work ok at my side. Would you please specify the case that you are observing by sharing a simple dojo and exact steps to replicate the issue?

Greetings,
Plamen
