### ISSUE TITLE
Spreadsheet Format dialog is opened twice

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#3966]
### Bug report

Spreadsheet Format dialog is opened twice when opened from formats dropdown tool

### Reproduction of the problem
1. Navigate to https://demos.telerik.com/kendo-ui/spreadsheet/index
2. Open the "Custom format" dropdown
3. Click "More formats" item

### Current behavior
2 dialogs are opened at the same time

### Expected/desired behavior
Only one dialog is opened

### Environment

* **Kendo UI version:** 2018.1.117

**Comment by Dimitar-Goshev** [comment]
This seems as a regression of https://github.com/telerik/kendo-ui-core/issues/2279
