### ISSUE TITLE
Editor overflow button overlap on resizing when Editor is nested in Window

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#3978]
### Bug report
When Editor is nested in Kendo Window and Editor`s toolbar is resizable, the overflow button overlaps the rest of the buttons in the toolbar on resizing the Window. 

### Reproduction of the problem
1. Open the Dojo [https://dojo.telerik.com/@NeliKondova/aZaHA](https://dojo.telerik.com/@NeliKondova/aZaHA)
2. Resize the Window

### Current behavior
The Editor`s toolbar overflow button overlaps the other buttons in the toolbar. 

### Expected/desired behavior
The Editor`s toolbar overflow button should not overlap the other buttons in the toolbar. 

### Environment

* **Kendo UI version:** 2018.1.117
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
Related issue: https://github.com/telerik/kendo-ui-core/issues/3324
