### ISSUE TITLE
Using the ComboBox, DropDownList or MultISelect Tag Helpers in a ViewComponent throws an error

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#3982]
### Bug report

When using the the ComboBox, DropDownList or MultISelect TagHelpers in a ViewComponent, an error is being thrown. 

### Reproduction of the problem

[TagHelpersIssue.zip](https://github.com/telerik/kendo-ui-core/files/1723997/TagHelpersIssue.zip)

### Current behavior

An error is thrown for the respective Tag Helper (Kendo.Mvc.TagHelpers.MultiSelectTagHelper)  - NullReferenceException: Object reference not set to an instance of an object.

### Expected/desired behavior

No error should be thrown when using the ComboBox, MultiSelect or DropDownList Tag Helpers to initialize the widgets inside a ViewComponent.

### Environment

* **Kendo UI version:** 2018.1.117
* **Browser:** [all]

**Comment by BobBonser** [comment]
It would appear this same problem is happening with the Window tag helper as well.

**Comment by BobBonser** [comment]
Are you ever going to work on this and fix it?  It is getting quite annoying.

**Comment by mparvanov** [comment]
Tested DropDownList, AutoComple, MutiSelect, ComboBox and Window.
