### ISSUE TITLE
Window does not open immediately after closing (jQuery 3.1.1)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#3985]
### Bug report
Not reproducible with jQuery v2.2.4 and 1.12.4.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/IlOkA) example.
1. Click the Close/Reopen button. 

### Current behavior
The Window closes and does not reopen. 

### Expected/desired behavior
The Window reopens after closing. 

**Workaround:**

Either disable the Window's close animation:
```
animation: {
  close: false
}
```
or reopen it with after a slight delay (e.g. 500ms timeout)

### Environment

* **Kendo UI version:** 2018.1.117
* **jQuery version:** 3.1.1
* **Browser:** [all] 
Related to https://github.com/telerik/kendo/issues/8395

**Comment by Vasimovic** [comment]
FYI: I just tried it in Chrome, Edge, and Firefox and it works as expected

**Comment by mparvanov** [comment]
Not reproducible with latest source and jQuery 3.1.1 and 3.3.1
