### ISSUE TITLE
Date/TimePicker popup auto-closes in Chrome when a preceding element's height is reduced

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#3986]
### Bug report

Reproducible in Chrome when the DatePicker (or any other picker widget) is placed at the bottom of a scrollable page and an element above it has its height reduced.

### Reproduction of the problem

1. Open [http://dojo.telerik.com/@tsveti/EHivux](http://dojo.telerik.com/@tsveti/EHivux)
1. Scroll down to bottom of page.
1. Click button to decrease element height.
1. Try to open the picker Calendar. The popup immediately closes.

### Environment

* **Kendo UI version:** 2018.1.117

Reported in:
1153319
1117310

Related to #3516

**Comment by TsvetinaIvanova** [comment]
Also reported in 1157772.

**Comment by matanasov** [comment]
@VicTachev 
This replicates with latest source code from master.
