### ISSUE TITLE
Missing localization for de-?? cultures

### ISSUE THREAD

**Issue by bdongus** [telerik/kendo-ui-core#3987]
### Current behavior
Using the color picker with a german culture all messages are in English. See also:
[https://www.telerik.com/forums/missing-localization-in-colorpicker](url)
### Expected/desired behavior
I would expect the four messages to be translated.

### Environment

* **Kendo UI version:** 2018.1.118

**Comment by Dimitar-Goshev** [comment]
@bdongus , as your [pull request](https://github.com/telerik/kendo-ui-core/pull/3988) for de-AT, de-CH, de-DE and de-LI cultures is still not processed, note that this item only fixes the messages for de-DE culture. The rest of the messages would be available for R2 2018 release.
