### ISSUE TITLE
Incorrect style is applied in Calendar for March 1st in non-leap years

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#3990]
### Reproduction of the problem
Run the dojo below: 

http://dojo.telerik.com/ogUBoB/5

### Current behavior
March 1st is not decorated with **k-other-month** CSS class.

### Expected/desired behavior
**k-other-month** should be applied to the date

### Environment

* **Kendo UI version:** 2017.3.913 and newer
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by VicTachev** [comment]
https://github.com/telerik/kendo/pull/8280

**Comment by EduardoSerra** [comment]
A customer reported this behavior in Ticket number 1156920.
