### ISSUE TITLE
Calendar multiple selection on Mac OS

### ISSUE THREAD

**Issue by vanagnostos** [telerik/kendo-ui-core#3991]
### Bug report

Multiple dates selection using Ctrl key is not possible on Mac OS. Only range selection works. Ctrl + mouse click opens browser context menu. 

### Reproduction of the problem

https://demos.telerik.com/kendo-ui/calendar/selection (use any browser on mac os). 

### Expected/desired behavior

Widget should use Cmd + mouse click on mac,  multiple date selection should work. 

### Environment

* **Kendo UI version:** 2018.1.117
* **jQuery version:** 1.12.4
* **Browser:** All / Mac OS

**Comment by matanasov** [comment]
@boyandim 
I confirm this is doesn't work as expected. Can you please take a look into it?
