### ISSUE TITLE
Calendar navigation on Mac OS

### ISSUE THREAD

**Issue by vanagnostos** [telerik/kendo-ui-core#3993]
### Bug report

According to documentation:

    - ctrl left arrow navigates to previous month
    - ctrl right arrow navigates to next month
    - ctrl up arrow navigates to previous view
    - ctrl down arrow navigates to next view 

However this does not work on Mac OS: 

    - ctrl + left / right arrow does nothing. 
    - ctrl + up / down shows opened application or desktop. 

### Reproduction of the problem

https://demos.telerik.com/kendo-ui/calendar/keyboard-navigation (use any browser on mac os).

### Expected/desired behavior

I would expect this functionality to work in the same way as on Windows but using Cmd key instead of Ctrl. 

### Environment

* **Kendo UI version:** 2018.1.117
* **jQuery version:** 1.12.4
* **Browser:** All / Mac OS

**Comment by matanasov** [comment]
@ag-petrov @boyandim 
I confirm this doesn't work as expected. Can you please take a look into it?
