### ISSUE TITLE
Widget with filtering does not close popup on scroll

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#400]
### Description
Widget does not close popup element on window scroll. Instead it is detached from the anchor moves with the page.

Can be reproduced in ["Server filtering" demo](http://demos.telerik.com/kendo-ui/dropdownlist/serverfiltering)

Reported in TicketID: 879886 

Can be reproduced in Grid filter demo too:
http://demos.telerik.com/kendo-ui/grid/filter-menu-customization

**Comment by solidoussnk** [comment]
I'm new to github, and are posting to see if the drop down issue was resolved? I'm working with Kendo UI and noticed this issue affects the combo box as well.
