### ISSUE TITLE
Setting "editable: false" for a field in the schema.model of the TreeList does not prevent editor creation

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4001]
### Enhancement

Setting editable: false for a field in the schema.model of the TreeList does not prevent editor creation

### Reproduction of the problem

https://dojo.telerik.com/IkOWE

### Expected/desired behavior

The same as in the Grid - an editor is not created.
https://dojo.telerik.com/EWeban

### Environment

* **Kendo UI version:** 2018.1.117
* **Browser:** [all]

**Comment by VicTachev** [comment]
The HireDate field is specified two times in the schema.model.fields configuration. When the second definition is removed the editable option is respected.

https://dojo.telerik.com/IZoxAMOL

**Comment by beast195** [comment]
Must be the including kendo.grid script instead of kendo.all
