### ISSUE TITLE
Input in submenu keeps the submenu popup open 

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#4004]
### Bug report

Reported in ticket with ID 1152982

### Reproduction of the problem

The behaviour of the menu has changed since R3 2017. Currently, if the input is focused, the popup of the submenu with the input remains open on other items hover which causes the popups to overlap:

![image](https://user-images.githubusercontent.com/10980842/36422093-874c1056-1643-11e8-89b8-6ee2f7836dab.png)

- Open [Dojo](http://dojo.telerik.com/@bubblemaster/OfoTu)
- Click to focus input in item 1 submenu
- Hover to Item 2 - > both popups are visible

If you do the same test with versions before R3 2017, there is only one popup when following the steps above -> [Dojo](http://dojo.telerik.com/@bubblemaster/Osaca)

### Current behavior

When a submenu has a focused input, the popup remains open.

### Expected/desired behavior

Only one submenu should be visible

### Additional remarks

Possible related to public issue [2526](https://github.com/telerik/kendo-ui-core/issues/2526) , private issue [6417](https://github.com/telerik/kendo/issues/6417) and [2584](https://github.com/telerik/kendo-ui-core/issues/2584)

### Environment

* **Kendo UI version:** 2018.1.118

**Comment by Iankodj** [comment]
The following issues are connected and should be also considered during testing: https://github.com/telerik/kendo-ui-core/issues/519 https://github.com/telerik/kendo-ui-core/issues/519
