### ISSUE TITLE
Cell values formatted as percent are incorrect for certain values

### ISSUE THREAD

**Issue by ivanchev** [telerik/kendo-ui-core#4005]
After entering certain values as percent, the value is changed to an incorrect one. 

Can be reproduced on the demo:
https://demos.telerik.com/kendo-ui/spreadsheet/index

1. Pick an empty cell
2. Type in 1.092%
3. Press enter

Expected result:
Cell shows 1.09%, Formula bar shows 1.092%

Actual result:
Cell shows 1.92%, Formula bar shows 1.0919999999999999%

**Comment by davidbacisin** [comment]
After stepping through with the debugger, it looks like the leading zeros of the decimal part are being dropped within the **runtime.toFixed** function. Because we still would want to round the decimal part, I propose adding the following 3 lines to the **spreadsheet/numformat** module:
```
while (decpart.length < 14) {
    decpart = '0' + decpart; // add leading zeros to replace any lost when converting to a number
}
```
And shown in context:
```
toFixed: function toFixed(value, decimals) {
        var str = String(value);
        var pos = str.indexOf('.');
        if (pos >= 0) {
            var intpart = str.substr(0, pos) || 0;
            var decpart = str.substr(pos + 1);
            if (decpart.length > 14) {
                decpart = String(Math.round(decpart / Math.pow(10, decpart.length - 14)));
                while (decpart.length < 14) {
                    decpart = '0' + decpart;
                }
            }
            if (decpart.length < decimals) {
                while (decpart.length < decimals) {
                    decpart += '0';
                }
                return intpart + '.' + decpart;
            }
            value = parseFloat(intpart + '.' + decpart);
        }
        return value.toFixed(decimals);
    }
```

**Comment by Dimitar-Goshev** [comment]
@mishoo The cell now shows 1.092% as expected. But still the formula bar shows 1.0919999999999999%, instead of 1.092%
