### ISSUE TITLE
Missing recurring Scheduler events in the beginning of a view

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4006]
### Bug report
Recurring Scheduler events are not rendered in the beginning of a view. There are several scenarios for reproducing the issue. It is reproducible with daily, hourly, weekly recurrence, probably other rules as well. 

### Reproduction of the problem - DAILY recurrence:
1. Open the following [Dojo](http://dojo.telerik.com/ELIGEPEL)
2. Go through each view and press Prev/Next arrows to switch dates.

### Current behavior
- Day view: 
![image](https://user-images.githubusercontent.com/6614183/43955103-7d29fde6-9ca7-11e8-8bc1-378bdde93cbe.png)

- Week view:
![image](https://user-images.githubusercontent.com/6614183/43955196-c7cdd714-9ca7-11e8-8eb6-8d931ccbbd32.png)

- Timeline view:
![image](https://user-images.githubusercontent.com/6614183/43955249-f08fb460-9ca7-11e8-84b6-4245b8ca7549.png)

- Moth view - **Make sure to go to the next month, e.g. March, so that there is an event starting from the previous month**:
![image](https://user-images.githubusercontent.com/6614183/43955299-1ef8f46a-9ca8-11e8-94e6-2eff31839bc4.png)

- Agenda view:
![image](https://user-images.githubusercontent.com/6614183/43955355-6946cf7e-9ca8-11e8-91aa-38ccb26a032c.png)

### Reproduction of the problem - HOURLY recurrence:
1. Open the following [Dojo](http://dojo.telerik.com/ACukERAL)
2. Go through each view and press Prev/Next arrows to switch dates.

### Current behavior
- Day view: 
![image](https://user-images.githubusercontent.com/6614183/43955478-1653080e-9ca9-11e8-8384-985d66fb668b.png)

- Week view - missing events in the beginning of the week:
![image](https://user-images.githubusercontent.com/6614183/43955561-689977ba-9ca9-11e8-8a9c-43fc665b1f82.png)

- Timeline view - same as in DAILY scenario above

- Agenda view - events start from 8:00 AM, instead of 12:00 AM for each first event:
![image](https://user-images.githubusercontent.com/6614183/43955634-bf898b64-9ca9-11e8-81c5-2bd2af728a2e.png)

### Expected/desired behavior
The entire event, which started from the previous day/week/month accordingly, should be rendered.

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by serhiy-koza** [comment]
Definitely Your Team will want to make changes in .ts files, but as long as they are unfortunately not delivered, I think its not a problem to find an appropriate section by using following:
in the kendo.all.js , row 95057, please change:
from this: useEventStart = freqName === 'yearly' || freqName === 'monthly' || freqName === 'weekly';
to this: useEventStart = freqName === 'yearly' || freqName === 'monthly' || freqName === 'weekly' || freqName === 'daily';

Kind regards,

Serhiy 
CollabFlex Software
