### ISSUE TITLE
Grid with aggregates throws error after deployment - ASP.NET Core 2

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#4007]
### Bug report

Ticket ID: 1152972 

### Reproduction of the problem

The ticket contains an ASP.NET Core 2 project which grid which errs after deployment in Azure when there are Aggregates. The error is:

> Exception: Unable to build typeDynamicClass1
> Kendo.Mvc.Infrastructure.Implementation.ClassFactory.EmitType(string typeName, CSharpCompilation compilation) in ClassFactory.cs, line 108
> 

[Full stack trace](http://runner.telerik.io/fullscreen/iZeJa)

### Current behavior

The error occurs only with ASP.NET Core 2

### Temporary workarounds

- Downgrade Core to a 1.x.x version
- Use client side operations `ServerOperation(false)`

### Environment

* **Kendo UI version:** 2018.1.131

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket with ID 1155297. Raising priority.

**Comment by fglebel** [comment]
I have the same issue. Working on dev and not after IIS publishing.

**Comment by Stamo-Gochev** [comment]
The problem can be tested by publishing the ASP.NET Core project to IIS locally.

**Comment by Stamo-Gochev** [comment]
@nihirrshah Yes, the problem is resolved and include in the R2 2018 (version2018.2.516) and later.
