### ISSUE TITLE
 The second column of a resizable Grid will disappear if the first one is autoFit by clicking the resize handler.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#4008]
### Bug report

The second column of a resizable Grid will disappear if the first one is autoFit by clicking the resize handler.

### Reproduction of the problem

The issue can be observed here:  http://dojo.telerik.com/arepUd

### Environment

* **Kendo UI version:** 2018.1.117
* **Browser:** [all]

**Comment by VicTachev** [comment]
The behavior is expected - in a scrollable Grid columns without defined width can shrink to a zero width. 

https://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance#column-widths
