### ISSUE TITLE
Change event fires on ComboBox/DropDownList blur 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4009]
### Bug report

After selecting an item and removing the focus from the widget, by clicking elsewhere on the page or pressing Tab key, the change event is fired even though there is no change to the value. This behavior is exhibited if the ComboBox dataSource contains an array of strings (dataTextField/dataValueField options are not set). 

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/uMECi) example.
1. Click the ComboBox.
2. Select an item. 
3. Click elsewhere on the page or press Tab key.

### Current behavior
Change event fires on blurring the ComboBox.

### Expected/desired behavior
Change event does not fire. 

### Environment

* **Kendo UI version:** 2018.1.117
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by jivanova** [comment]
Changes required in the kendo.list.js to fix the behavior:
[https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.list.js#L638](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.list.js#L638)

[https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.list.js#L1205](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.list.js#L1205)

**Comment by menasheh** [comment]
Why was this closed? Still causing headache in 2021. How can I check what triggered the change event, in order to not run if it was a blur? It's automatically resetting the dropdownlist value to something arbitrary and incorrect.

**Comment by IvanDanchev** [comment]
The issue was logged, because the "change" event fired when there was no actual change in the value. This was fixed and the issue was closed. Compare the behavior before the fix:

[https://dojo.telerik.com/uMECi](https://dojo.telerik.com/uMECi)

and after the fix:

[https://dojo.telerik.com/IKAHuWoK](https://dojo.telerik.com/IKAHuWoK)

Before the fix the "change" event fires twice, once on selecting a value and another time on blurring the ComboBox. After the fix, the event does not fire a second time on blur, only on selecting a value.
