### ISSUE TITLE
Value is deselected on initial load

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#4022]
### Bug report

[DOJO](https://dojo.telerik.com/AXepo) : If empty value array is set and autoBind is false, once item is selected, it will get unselected

### Reproduction of the problem
1.  Select a value
2. Open the multiselect

### Current behavior
Value is deselected

### Expected/desired behavior
Value remains selected

### Environment

* **Kendo UI version:** 2018.2.221
* **Browser:** all

**Comment by mparvanov** [comment]
The following problematic scenario is reproduced:
1. Use the following setup:
<select id="multiselect"></select>
<script>
            $(document).ready(function() {
                var dataSource = new kendo.data.DataSource(
                    {
                        type: "odata",
                        serverFiltering: true,
                        transport: {
                            read: {
                                url: "https://demos.telerik.com/kendo-ui/service/Northwind.svc/Products",
                            }
                        }
                    }
                );
                $("#multiselect").kendoMultiSelect({
                    placeholder: "Select products...",
                    dataTextField: "ProductName",
                    dataValueField: "ProductID",
                    autoBind: false,
                    dataSource: dataSource,
                    value: [
                    ]
                });
            });
        </script>

2. Enter text in the multiselect input that doesn't match an item text, e.g. "test"
3. Press Enter

The following JS error is thrown:
Cannot read property 'hasClass' of null

**Comment by jivanova** [comment]
Issues are not related. Fix included in https://github.com/telerik/kendo/issues/8300
