### ISSUE TITLE
Enhance Kendo DLL to avoid warnings when latest System.Web.Mvc is referenced

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4023]
### Enhancement

Currently, Kendo dll is referencing System.Web.Mvc Version 5.2.3.0. In projects where the version of System.Web.Mvc is 5.2.4.0 the following warning might occur:

_Assuming assembly reference 'System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' used by 'Kendo.Mvc' matches identity 'System.Web.Mvc, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' of 'System.Web.Mvc', you may need to supply runtime policy_

### Expected/Desired behavior
The warning should not appear in case System.Web.Mvc 5.2.4.0 is referenced in a project. 

* **Kendo UI version:** 2018.1.117
* **Browser:** [all ]

**Comment by DaleyKD** [comment]
Yes, please!

**Comment by RaNa2009** [comment]
Yes, please.

**Comment by mbarmettler** [comment]
yes, would be great.

**Comment by abhinav1985** [comment]
Is there any targeted date by when we can expect a solution for this issue ?

**Comment by kdubious** [comment]
It is still an issue in:
Kendo UI version: 2018.1.221

**Comment by Peymman** [comment]
It is the same with us. We use Kendo.Mvc version 2018.1.221.545 with System.Web.Mvc version 5.2.4.0 which gives warnings/errors.

**Comment by mobius7777** [comment]
System.Web.Mvc 5.2.6 NuGet package just came out. Will this be a problem for that too? Will this constantly be a problem every time Microsoft updates System.Web.Mvc?

**Comment by zdravkov** [comment]
Yes - it will be an issue indeed - we will research the possibility for a constant solution - if such is not found we will do our best to provide an updated version as soon as possible.

**Comment by dfarrNTST** [comment]
Why was this issue closed?  It is still occurring!

**Comment by wazahuis** [comment]
I added Telerik Reporting view to a MVC project and it started getting all these warnings.    I am finding it frustrating.

**Comment by mmunchandersen** [comment]
I upgraded to kendoui.for.jquery.2018.2.613 and kendoui.for.jquery.2018.2.613.commercial and the warnings went away

**Comment by DoomerDGR8** [comment]
The issue is back with _Telerik UI for MVC v2019.1.115.545_ and _System.Web.Mvc to 5.2.7.0_. Here is the warning I'm getting:

`CS1702: Assuming assembly reference 'System.Web.Mvc, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' used by 'Kendo.Mvc' matches identity 'System.Web.Mvc, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' of 'System.Web.Mvc', you may need to supply runtime policy`

**web.config @ site root**
```
<dependentAssembly>
	<assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
	<bindingRedirect oldVersion="0.0.0.0-5.2.7.0" newVersion="5.2.7.0" />
</dependentAssembly>
```

**web.config @ Views**
```
<configuration>
	<configSections>
		<sectionGroup name="system.web.webPages.razor" type="System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35">
			<section name="host" type="System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" requirePermission="false" />
			<section name="pages" type="System.Web.WebPages.Razor.Configuration.RazorPagesSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" requirePermission="false" />
		</sectionGroup>
	</configSections>

	<system.web.webPages.razor>
		<host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
		<pages pageBaseType="System.Web.Mvc.WebViewPage">
			<namespaces>
				<add namespace="System.Web.Mvc" />
				<add namespace="System.Web.Mvc.Ajax" />
				<add namespace="System.Web.Mvc.Html" />
				<add namespace="System.Web.Optimization"/>
				<add namespace="System.Web.Routing" />
				<add namespace="DA.Services.CarPark.Presentation.Web" />
				<add namespace="DA.Services.CarPark.Presentation.Web.Common" />
				<add namespace="Kendo.Mvc.UI" />
			</namespaces>
		</pages>
	</system.web.webPages.razor>

	<appSettings>
		<add key="webpages:Enabled" value="false" />
	</appSettings>

	<system.webServer>
		<handlers>
			<remove name="BlockViewHandler"/>
			<add name="BlockViewHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.HttpNotFoundHandler" />
		</handlers>
	</system.webServer>

	<system.web>
		<compilation>
			<assemblies>
				<add assembly="System.Web.Mvc, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
			</assemblies>
		</compilation>
	</system.web>
</configuration>
```

**Comment by mobius7777** [comment]
I have it again too, but it was because I updated to System.Web.Mvc 5.2.7. Telerik UI for MVC appears to be compiled for System.Web.Mvc 5.2.6. I think this will always happen when there is a mismatch. It's really just a warning, but very annoying. I wish there was away to make the warning "go away". Our application still seems to work fine.

**Comment by DoomerDGR8** [comment]
Well, if you are using **Microsoft.CodeDom** then you can add a _1702_ to the ignore list afte the c# line::

```
    <system.codedom>
        <compilers>
            <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=2.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:default /nowarn:1659;1699;1701;1702" />
            <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=2.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:default /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />
        </compilers>
    </system.codedom>
```

This will hide all the errors.
