### ISSUE TITLE
Custom group sorting

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4024]
### Enhancement

Grouping a column with a sortable.compare function should sort the groups in the implemented order.

Reported in 1154779 , 1170865, 1178938, 1339436

### Reproduction of the problem

https://dojo.telerik.com/eQOxU/4
group by **item** field

### Current behavior

The groups are sorted regularly.

### Expected/desired behavior

The groups are sorted based on the sortable.compare function.

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all ]

**Comment by Stamo-Gochev** [comment]
As sorting the groups is different from sorting the items inside the groups (these are the flat view items without any grouping), it was decided to expose additional options in order to do that instead of using `sortable.compare`.

The following code snippet demonstrates how it will be possible to sort the groups based on the total number of the items in ascending order:
```javascript
$("#grid").kendoGrid({
    ...
    groupable: {
        sort: {
            dir: "asc",
            compare: function compareByTotal(a, b) {
                if (a.items.length === b.items.length) {
                    return 0;
                } else if (a.items.length > b.items.length) {
                    return 1;
                } else {
                    return -1;
                }
            }
        }
    }
}
```

**Comment by PrashanthSubramanianMS** [comment]
`group: {
                        field: "category",
                   dir: "desc",
            compare: function(a, b) {
                if (a.items.length === b.items.length) {
                    return 0;
                } else if (a.items.length > b.items.length) {
                    return 1;
                } else {
                    return -1;
                }
            }
          }
        }`
