### ISSUE TITLE
kendo.all.d.ts (2018.1.221) lost all jQuery plugin associations

### ISSUE THREAD

**Issue by DaleyKD** [telerik/kendo-ui-core#4025]
### Reproduction of the problem
Comparing kendo.all.d.ts with the previous versoin (2018.1.117), a huge chunk of lines are missing from the bottom of the file which attach the kendo jQuery plugin to jQuery.fn.  This prevents my .ts files from finding `$('select').kendoDropDownList()`, etc.

### Environment
* **Kendo UI version:** 2018.1.221

**Comment by matanasov** [comment]
@DaleyKD 
This is indeed an issue in the 2018.1.221 version. 
It is already resolved in the latest internal build (2018.1.226) that you can download from your account or kendo-ui npm package.
