### ISSUE TITLE
k-ng-model does not update $dirty and $pristine when ng-form directive is used

### ISSUE THREAD

**Issue by mlhDevelopment** [telerik/kendo-ui-core#4026]
### Bug report

Similar to [issue 398](https://github.com/telerik/kendo-ui-core/issues/398) but triggered when ng-form is used instead of a form tag.

### Reproduction of the problem
See http://dojo.telerik.com/OLATOM/2

Might be as easy as starting with [b2e63f99cb0a71ba0e0e2041f4f76ef3113abd8f](https://github.com/telerik/kendo-ui-core/commit/b2e63f99cb0a71ba0e0e2041f4f76ef3113abd8f) and selecting a parent form or ng-form.

### Environment
* **Kendo UI version:** 2018.1.221
* **jQuery version:** 1.12
* **Browser:** all

**Comment by matanasov** [comment]
@ag-petrov @boyandim 
Could you please take a look at this?

**Comment by DanielHirschTpg** [comment]
Is there an update on this? I'm having the same issue when using the ng-form directive since I can't use the form element.

**Comment by ag-petrov** [comment]
This seems like something we can fix. We are currently working on the matter.
