### ISSUE TITLE
Kendo UI Sales Hub sample project is throwing error due to blocked mixed active content resources

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#4027]
### Bug report

The sample demo is hosted on https but loads CDN resources from http. This results in blocked mixed active content resources errors:

### Reproduction of the problem
Open https://demos.telerik.com/kendo-ui/saleshub 

### Current behavior
An error is thrown for blocked mixed active content resources:
Mixed Content: The page was loaded over HTTPS, but requested an insecure script . This request has been blocked; the content must be served over HTTPS.

### Expected/desired behavior
No error occurs

**Comment by Dimitar-Goshev** [comment]
The issue is currently not reproducible. Although in source repo the following resources are with http:// , the uploaded version uses https:// .
