### ISSUE TITLE
kendo.all.d.ts: kendo.data.transports has no index signature

### ISSUE THREAD

**Issue by DaleyKD** [telerik/kendo-ui-core#4031]
Currently, kendo.all.d.ts shows the following for `kendo.data.transports`:
```
declare namespace kendo.data.transports {
    var odata: DataSourceTransport;
}
```
When trying to use the following code snippet:
```
type: (() => {
    if (kendo.data.transports['aspnetmvc-ajax']) {
        return 'aspnetmvc-ajax';
    } else {
        throw new Error('The kendo.aspnetmvc.min.js script is not included.');
    }
})(),
```

TypeScript tells me: 

> Element implicitly has an 'any' type because type 'typeof transports' has no index signature.

Kendo UI for jQuery version 2018.1.221.

**Comment by matanasov** [comment]
@Stamo-Gochev @ag-petrov 
Can you please take a look at this?

**Comment by matanasov** [comment]
@DaleyKD 
Could you please provide more details about this issue? We couldn't hit it locally so far.

**Comment by DaleyKD** [comment]
I can try.

I'm in Visual Studio 2017, using TypeScript 2.7.2.

Fresh project. Only has **all.ts** and **kendo.all.d.ts**.  This is my **all.ts**:
```
/// <reference path="kendo.all.d.ts" />

function kendoTest() {
    if (kendo.data.transports['aspnetmvc-ajax']) {
        return 'aspnetmvc-ajax';
    } else {
        throw new Error('The kendo.aspnetmvc.min.js script is not included.');
    }
}
```

This is the error in my Error List:

> TS7017	(TS) Element implicitly has an 'any' type because type 'typeof transports' has no index signature.

Try setting `noImplicitAny` to `true`.  I think this is the cause.

**Comment by matanasov** [comment]
@DaleyKD 
Thanks - indeed it is `noImplicitAny` causing the error.
Our developers will take a look at it and get back to you with the details.

**Comment by DaleyKD** [comment]
Any update on this?  It'd be nice to fix the index.d.ts so that you can use a proper indexer.

**Comment by ag-petrov** [comment]
@DaleyKD This seems to be a general Typescript behavior. Could you please elaborate on how would you expect the declaration to be included in our typescript files?

**Comment by DaleyKD** [comment]
I am no expert at TypeScript by any means, but looking at the way you guys extend `kendo.data.transports` like this:
![image](https://user-images.githubusercontent.com/7206282/77672533-0716e400-6f57-11ea-9edd-72380ecf748e.png)

...makes me think that there's a couple ways to do it.  The simplest for today seems to be remove the `declare namespace kendo.data.transports` and instead moving it to be an interface under `kendo.data`:
```
declare namespace kendo.data {
    interface transports {
        odata: DataSourceTransport;
        [transportType: string]: DataSourceTransport;
    }
...
```

And that's not an exact type matching, since you also have `RemoteTransport`, `LocalTransport` and `XmlaTransport` (but you don't give us types for those).

I _hope_ this gives some explanation as to where my mind is.

**Comment by DaleyKD** [comment]
Well, that's not exactly right... that wouldn't work... but I hope it gives you a direction?

**Comment by DaleyKD** [comment]
I guess after some deeper research, is it even possible to do this?  Since you guys are saying it's a "namespace," but are using it more like some kind of static class.

https://github.com/microsoft/TypeScript/issues/6480

I guess we can close this.  I don't know if there's a solution other than to:

```
if ((kendo.data.transports as any)['aspnetmvc-ajax']) {
    return 'aspnetmvc-ajax';
} else {
    throw new Error('The kendo.aspnetmvc.min.js script is not included.');
}
```

I hate converting things to any. :(

**Comment by zdravkov** [comment]
Closing this for the moment because of the linked[ typescript issue ](https://github.com/microsoft/TypeScript/issues/6480)that is still not addressed.
