### ISSUE TITLE
MultiSelect clear button is not rendered when items are selected programmatically 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4034]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/abIYOqav/3) example. 
1. Click the clear button to remove the selected items. 
2. Press the "Select items" button.
3. No clear button is rendered. 

Triggering the change event after calling the value method does not change anything. 

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by jivanova** [comment]
Fix included in https://github.com/telerik/kendo-ui-core/issues/4192.
