### ISSUE TITLE
Error is thrown when using JSDO batch operations

### ISSUE THREAD

**Issue by dimodi** [telerik/kendo-ui-core#4037]
### Bug report

The following error is thrown when trying batch saves with a JSDO transport: "A newer version of Kendo UI is expected for batching support."

More information and explanations here: https://community.progress.com/products/f/86/t/37422

> The message "A newer version of Kendo UI is expected for batching support." indicates that the Grid is trying to perform batch editing without using a submit operation. The submit operation provides support for Transactional Submit where multiple edits/updates (create, update, and delete) can be sent to the server as a single request.
> Calling the individual entry points in the JSDO transport does not provide that functionality and the decision was check fhat submit was used.
> ...
> Please contact the Kendo UI team and mention about call to the submit method in the transport.

### Reproduction of the problem

http://dojo.telerik.com/ibIjohIK/3

Make an edit and click on the Save changes button.

### Current behavior

A JavaScript alert pops and no request is made. An error is logged in the browser console.

### Expected/desired behavior

No errors during batch CRUD operations. Here is a working example with R3 2017 SP2: http://dojo.telerik.com/ibIjohIK/2

### Environment

* **Kendo UI version:** 2018.1.#

**Comment by Rayka** [comment]
Hi Dimo, I have some questions regarding Kendo UI for React, can I somehow ask them personally? I can be very concrete. if you have two minutes :)
