### ISSUE TITLE
kendo-grid-column with inline bound prop causes redundant read requests on data changes 

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#4038]
Similar to https://github.com/telerik/kendo-ui-core/issues/3952, but by using `kendo-grid-column`.

```html
<kendo-grid id="projects_grid"
            :data-source-ref="'datasource1'"
            :resizable='true'
            :filterable='true'
            :sortable='true'
            :pageable='{ refresh: true, pageSize: 100, pageSizes: true, buttonCount: 5 }'>
<kendo-grid-column
  :command="[ { name: 'open', text: 'Open', iconClass: 'k-icon k-i-edit' }, { name: 'delete', text: 'Delete', iconClass: 'k-icon k-i-delete' } ]"
  title=" " width="220px">
</kendo-grid-column>
</kendo-grid>
```
will rebind the widget at each change of any reactive property present in the Vue app:
```html
<input v-model="new_proj_name" type="text" />
```
```JavaScript
export default {
  name: 'grid',
  data: function () {
    return {
      new_proj_name: ''
    }
  },
...
```

**Comment by besmiralia** [comment]
Hi lankodj
I noticed that when i put any of the server-side parameters in the grid datasource it causes double requests if I change any other bound property.
Check this https://plnkr.co/edit/HyePYzdtlkBr1sdwRSIe?p=preview
Open the console (switch the frame from top to plunkerPreviewTarget) and try changing DATA.GH=700 

Now try to change the datasource by adding any of the following properties and repeat the last step above. You will see that it causes 2 requests

:server-sorting="true"
:server-paging="true"
:server-filtering="true"
:sort="[]"


Let me know if this is not clear enough.

**Comment by Iankodj** [comment]
Hi @besmiralia, the results you see are normal and expected. By enabling the server operation it is expected that this will happen. Generally, changing the height will submit a change to the component and the widget, which will influence the rows that can be fitted, thus the grid makes another request to get the items from the server and fill the space with the more rows according to the new height.

**Comment by besmiralia** [comment]
Hi @lankodj.
Thanks for the explanation, my concern is that it sends double requests. Also is there any way that can prevent this behavior, prevent requests because of height change

**Comment by Iankodj** [comment]
@besmiralia, you can try changing the CSS of the DOM element instead of using the prop.
