### ISSUE TITLE
Reload method doesn't update tabs via AJAX 

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#4048]
### Bug report

The reload method should reload the TabStrip tabs via AJAX:
https://docs.telerik.com/kendo-ui/api/javascript/ui/tabstrip/methods/reload#reload

### Reproduction of the problem
https://dojo.telerik.com/AxIpaFEV

### Current behavior
The tabstrip tabs are not updated via AJAX

### Expected/desired behavior
The tabstrip tabs are updated via AJAX

### Environment
* **Kendo UI version:** 2018.1.221

**Comment by Dimitar-Goshev** [comment]
The reproduction Dojo above is missing dataContentUrlField: "contentUrl" setting and that is why reload does not work in this scenario. When dataContentUrlField: "contentUrl" is added, reload works as expected - [Fixed Dojo](https://dojo.telerik.com/AYoyExUZ). It also works with contentUrl without dataSource - [Dojo](https://runner.telerik.io/fullscreen/omEZaVuc). The first tab gets updated (visible in dev tools Network tab) with the following script:
```
var tabstrip = $('#tabstrip').getKendoTabStrip();
tabstrip.reload("li:first");
```
