### ISSUE TITLE
Missing TypeScript definition for binders in kendo.data.binders

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4049]
### Bug report
Add typescript definition for binders in kendo.data.binders:

### Current behavior
Error: "Property 'widget' does not exist of typeof 'binders'"

kendo.data.binders.widget.highlightFirst = ...1

### Expected/desired behavior
no error 
ticket: 656882 
ticket: 1176334

### Environment
* **Kendo UI version:** 2018.2.620

**Comment by simon-sharp** [comment]
I went with kendo.data['binders'].widget.highlightFirst to prevent the error. As a workaround

**Comment by GaloisGirl** [comment]
Still missing as of version "@types/kendo-ui": "2019.3.0" .
