### ISSUE TITLE
Cannot set the culture for clear button title and loading message in AutoComplete, ComboBox and MultiSelect

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4052]
### Bug report

Cannot set the culture for clear button title and loading message in ComboBox

### Current behavior
Cannot set the culture for clear button title and loading message in ComboBox

### Expected/desired behavior
The clear button tooltip and loading messages (in virtialization mode) should be automatically translated base on the set culture e.g.   kendo.culture("es-ES");

### Environment

* **Kendo UI version:** 2018.3.911
* **Browser:** [all]

**Comment by Iankodj** [comment]
The clear title can be set using messages.clear option. https://dojo.telerik.com/oFicuDaT

The option, however, is not populated to the API of the list components.

**Comment by MirAlbertioni** [comment]
Doesnt say whether it is javascript, react or anything else..

**Comment by ag-petrov** [comment]
The autocomplete messages are not present in the localization files but if added will be localized correctly. There is not problem in the component itself. Closing this one as the localization files are driven by the community.
