### ISSUE TITLE
Enabling Navigatable in Grid prevents SHIFT+Arrow Keys selection in editors

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#4061]
### Bug report
Due to the SHIFT+ARROW KEYS selection of the Navigatable functionality of the Grid, using SHIFT+ARROW KEYS in editors does not select the content. If possible, we should exclude the preventing of the events in the navigatable logic if the event fires from input elements.

### Reproduction of the problem
Open row for editing in the following dojo example and try to select the text in the first editor with SHIFT+ARROW KEYS:
[https://dojo.telerik.com/OWeCEquy](https://dojo.telerik.com/OWeCEquy)

### Environment

* **Kendo UI version:** 2018.1.221

**Comment by MilenaCh** [comment]
SHIFT + UP/DOWN arrow do not select/unselect the text in Firefox.

**Comment by VicTachev** [comment]
This looks like the default Firefox behavior with inputs. It can be observed with regular input elements - http://dojo.telerik.com/eLOWEcoG.
