### ISSUE TITLE
Checkbox column does not work in hierarchical grid in MVC.

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#4063]
### Bug report

In MVC the grid header is rendered on the server which causes the problem since it is reused for the detail grids. The header checkboxes in this scenario have the same ids which breaks the selection when clicked.

### Current behavior
Selects the wrong subset of items if multiple levels are expanded and a header checkbox in the child levels is clicked.

### Expected/desired behavior
Selects the correct subset of items.

**Comment by manprit-sahota** [comment]
Please let me know the fixed version when it is released so that I can update my library to get things working.

**Comment by manprit-sahota** [comment]
I am not able to find  2018.R2 version in progress control panel. Can you please provide release details?

**Comment by manprit-sahota** [comment]
Is there any update on this?
