### ISSUE TITLE
Spreadsheet does not properly format decimal numbers with more signs after the decimal point

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4064]
### Bug report
Spreadsheet does not properly format decimal numbers with more signs after the decimal point. This bug is a regression introduced with the R1 2018.1.117 release

### Reproduction of the problem
On the following [Dojo](https://dojo.telerik.com/oGURiHan/2), check the value and the displayed number in the A1 cell. The value is **-0.00040000000001328** and it is displayed as **0.40**

### Environment
* **Kendo UI version:** from 2017.1.117 on

**Comment by veselints** [comment]
Priority set to 5 as it is a regression Bug.

**Comment by Iankodj** [comment]
Fixed with https://github.com/telerik/kendo/commit/a81f8aae419ea10405c3610f47777f521ffe8216#diff-ffe636911e5638d7b9d31b0b66f383a6, related to https://github.com/telerik/kendo-ui-core/issues/4005.
