### ISSUE TITLE
ComboBox with paging displays incorrect value if an item that is not on the first page is selected

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4065]
### Bug report
If an item that is not on the first page is selected in ComboBox with paging and then the ComboBox is expanded, the widget displays in the input field, the dataValue of the item instead of its text. 

### Reproduction of the problem
1. Open the Dojo [https://dojo.telerik.com/ODokEGOy](https://dojo.telerik.com/ODokEGOy)
2. Search for 'Tofu' and select it. 
3. Expand the ComboBox

### Current behavior
In the input field the 'ProductID' (dataValueField) of the item is displayed, instead of the 'ProductName' (dataTextField).

### Expected/desired behavior
The widget should display the dataTextField value. 

### Environment

* **Kendo UI version:** 2018.1.117
* **Browser:** [all ]

**Comment by veselints** [comment]
The same could be reproduce with a ComboBox with Virtualization and *mapValueTo* set to *dataItem*

**Comment by 06b** [comment]
Following up from Ticket: 1156827

I noticed that this issue was closed but it doesn't seem to have a milestone assigned to it, so I'm assuming that it's been fixed. 

I see that there is a 2018.R1.SP.next & a 2018.R2 milestone - which milestone should I expect this fix to included in?
