### ISSUE TITLE
Scrollable Menu is not resizing correctly on mobile browser after changing device orientation

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4067]
### Bug report
When the orientation of scrollable Menu is changed on mobile devise, the Menu is not resized correctly.

### Reproduction of the problem
1. Open the Demo [https://demos.telerik.com/kendo-ui/menu/scrollable](https://demos.telerik.com/kendo-ui/menu/scrollable) on mobile device.
2. Turn the device in order to change the orientation to horizontal
3. Turn it back to change the orientation to vertical. 

### Current behavior
The Menu is not rendered correctly. It exceeds the width of the container. (screencast - [https://www.screencast.com/t/g85sqXF5y7y](https://www.screencast.com/t/g85sqXF5y7y))

### Expected/desired behavior
The Menu should be rendered within the container after changing the orientation. 

### Environment
* **Kendo UI version:** 2019.1.115
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible on desktop Chrome device emulator or on iPad Safari. But it is still reproducible on a real Android device Chrome.
