### ISSUE TITLE
Regression - pageSize "all" does not work correctly with the grid's Excel export

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#4069]
### Bug report

Ticket ID 1155619 

### Reproduction of the problem

[Instructions in the Dojo](https://dojo.telerik.com/@bubblemaster/EvopOPaL)

### Current behavior

Since 2018 SP1 when pageSize is "all" or equal to the total of the dataSource, the excel export contains the original pageSize, instead of the total which results in an unexpected Excel export.  This is a regression from the fix of the pager [here.](https://github.com/telerik/kendo-ui-core/issues/3424).

### Observations

The issue arises because we are setting the pageSize to undefined. During the Excel export, the grid's data source is extended with the current view and passed to the excel exporter. Since the pageSize is no longer defined(it used to be `dataSource.pageSize(dataSource.total() ? dataSource.total() : MAX_VALUE);`, $.extend takes the initial grid dataSource pageSize. 

### Workaround

Add a handler to the data source [`change`](https://docs.telerik.com/kendo-ui/api/javascript/data/datasource/events/change) event and if the internal property _pageSize is `undefined`, set it as the total of the data source:

```
 change: function(e){      
     if(!e.sender._pageSize){
       e.sender._pageSize = e.sender.total();
     }
    }
```

### Expected/desired behavior

When the grid pager is changed to "All", all records should be exported as it is in 2018 R1 and before.

### Environment

* **Kendo UI version:** 2018.1.221

**Comment by patrickjlee** [comment]
Has this problem now been fixed in the latest release (Q2 2018)? Thanks

**Comment by patrickjlee** [comment]
The issue has not yet been fixed.  From Preslav at Progress Telerik in a support ticket reply to me: "For the time being, this bug is not yet fixed. Our dev team is still working on it. "

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket with ID 1342082

**Comment by MilenaCh** [comment]
Yes, we have provided a fix for this issue and it will be part of R3 2018 SP1 release. The fix will be also included in our next internal build.  

Generally speaking, when an issue is closed and there is a milestone set to it, this means that it is done and will be included in the corresponding release. In case we reject an item, it will be marked as 'Won't fix' and our dev team will add a comment with the exact reason about that.

**Comment by Alex-Bubblemaster** [comment]
Thank you very much for your feedback. I will communicate the suggestion to also include a text comment when processing the issues with the management and let you know the outcome in the ticket with ID 1155619.
