### ISSUE TITLE
Cascading DropDownList restores previous selection

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4070]
### Bug report

Cascading DropDownList restores previous selection of select method is used to select optionLabel

Related to:
https://github.com/telerik/kendo/issues/8417
https://github.com/telerik/kendo-ui-core/issues/3446

#### First case
Use the following dojo to replicate the problem:
[https://dojo.telerik.com/EKibagiF/12](https://dojo.telerik.com/EKibagiF/12)

Steps:
1. Click button Set.
2. Click button Reset.
3. Select Category "Black" manually.

#### Second case
Use the following dojo to replicate the problem:
[https://dojo.telerik.com/EKibagiF/22](https://dojo.telerik.com/EKibagiF/24)

Steps:
1. Click button Set;
2. In the `categories` DDL select the option label (Select category...) manually;
3. Select Category "Black" manually;
4. "Obsidan" will be populated in the `products` DDL.

The same will not occur if the initial values are selected manually. The `products` DDL will remain empty (displaying its option label).

### Current behavior
The second DropDownList restores its previous selection.

This won't happen if value() method is used to reset the selection - **.value(0)**

### Expected/desired behavior
The second DropDownList  should maintain optionalLabel selected, once the _**Black**_ item is selected

### Environment
* **Kendo UI version:** 2018.1.117
* **Browser:** [all]

**Comment by veselints** [comment]
PR here: https://github.com/telerik/kendo/pull/10243

**Comment by veselints** [comment]
Please, make sure that the following two scenarios also work appropriately:
https://github.com/telerik/kendo/issues/8417
https://github.com/telerik/kendo-ui-core/issues/3446
