### ISSUE TITLE
Tooltip doesn't work as expected for Dropdown with filter

### ISSUE THREAD

**Issue by RaptorCZ** [telerik/kendo-ui-core#4071]
When dropdown has enabled 'filter' option and attached tooltip with 'focus' activator, then it doesn't work as expected. Problem seems to be focused 'search' field, because wrapper lost focus.

How to keep tooltip visible even if search field is focused?

Sample:
https://codepen.io/raptor/pen/jzEOQM

**Comment by veselints** [comment]
Hi,
I would recommend you to open a [support ticket](https://www.telerik.com/account/support-tickets) on the discussed topic, where we will be able to provide you with further assistance on this matter. I will  close now this issue as the described behaviour of the Tooltip is expected in the described scenario.

**Comment by RaptorCZ** [comment]
I still think it is bug, because it is unexpected behaviour for me.

Only users with active license can send support ticket, right? I have no active license. And dropdown is part of Kendo UI Core - so no need to purchase anything. So how can I send support ticked in this case?
