### ISSUE TITLE
Filter Field Settings menu "Include Fields" in PivotGrid local binding applies wrong filters

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#4072]
### Bug report

Reported in ticket with ID 1156870. Probably related with [this issue.](https://github.com/telerik/kendo-ui-core/issues/2054)

### Reproduction of the problem

[https://demos.telerik.com/kendo-ui/pivotgrid/local-flat-data-binding](https://demos.telerik.com/kendo-ui/pivotgrid/local-flat-data-binding)

1. Toggle column menu for column category (click three verical dots)
2. Click "Include fields"
3. Expand "All categories" and make some subset selection, confirm selection
4. Again click "Include fields" -> note that the checkbox should show intermediary state but it is blank
5. Click on "All categories", click "OK" -> no records are shown as if we filtered "Include fields - none"

* if the node "All Categories" is expanded, the intermediary state gets updated correctly and clicking ok does not result in the error above

### Current behavior

No records are shown if the "Include Fields" => "All Categories" is selected without expanding it.

### Expected/desired behavior

The correct filter should be applied instead of no fields included.

### Environment

* **Kendo UI version:** 2018.1.221

**Comment by ag-petrov** [comment]
Seems to be fixed for the lcoal data-binding - https://demos.telerik.com/kendo-ui/pivotgrid/local-flat-data-binding
