### ISSUE TITLE
Kendo Window fires close event twice on Esc keydown when using preventDefault

### ISSUE THREAD

**Issue by movedoa** [telerik/kendo-ui-core#4073]
Basically the same bug as #3780.
The bug still happens in 2018 R1 SP1 when you use e.preventDefault(). in the close event to prevent the windows from closing.

Example: https://dojo.telerik.com/uGeliWil

**Comment by movedoa** [comment]
Will this get fixed in R2 2018?
This bug is a majo headache for my program and i can only use some really nasty workarounds.

**Comment by Iankodj** [comment]
Hi @movedoa,

Yes, the fix most probably will be released with  the next official release.
