### ISSUE TITLE
Scroller not able to scroll content all the way to the top if it is in a div element (contenteditable=true)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4075]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/awoyevAn) example. [Screencast](https://www.screencast.com/t/ZlULlfpyHy76).
1. Manually enter text on new lines in the div element so that the content can be scrolled. 
2. Try scrolling to the top. 

The topmost part of the content remains hidden and cannot be scrolled into view neither manually (by holding down the mouse button and dragging, by using the mousewheel, or by swiping on mobile devices) nor programmatically - by calling the scrollTo method. 
If the content is added to the div in the HTML and not manually, it can be scrolled to the top as expected.  

### Environment

* **Kendo UI version:** 2018.1.226
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Reported in ticket ID 1432969
