### ISSUE TITLE
Dragging unlocked column over a locked one causes flicker when browser is zoomed

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#4083]
### Reproduction of the problem
1. Run this dojo - https://dojo.telerik.com/ekawumAm/12
2. Zoom the page
3. Drag unlocked column over the locked one

The behavior is observed in Chrome and Edge browsers the first time a column is dragged.

### Current behavior
Video showing the problem - https://www.screencast.com/t/MehBGn9FY

### Expected/desired behavior
There should be no flicker.

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** 1.12
* **Browser:** [Chrome | Edge]

**Comment by VicTachev** [comment]
Workaround:
`$("#grid").getKendoGrid()._draggableInstance.options.autoScroll = false;`

https://dojo.telerik.com/ekawumAm/14

**Comment by ag-petrov** [comment]
Seems to not reproduce with the latest version
