### ISSUE TITLE
Long title overflows the Window

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4084]
### Bug report
A change to positioning of the **.k-window-titlebar** element in R1 2018 SP1 caused the Window's title to overflow when long text that does not fit the Window's width is set as title. 

### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/AteCOGuY) example.

Workaround:
```
.k-window-titlebar {display: flex } 
```

### Environment
* **Kendo UI version:** 2018.2.620
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by joneff** [comment]
Targeted by https://github.com/telerik/kendo/pull/8844
