### ISSUE TITLE
Don't set iframe.src to a script uri in editor _createContentElement when it is not required

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#4085]
### Reproduction of the problem
Add editor to a page with CSP directive blocking inline scripts.

### Current behavior
CSP violation error generated because `iframe.src` will allways set to javascript uri, even when `document.domain` change is not required.

### Expected/desired behavior
If `document.domain` change is not required (which I exect a case for most of users), use `'about:blank'` for src instead `'javascript:""`

### Environment

* **Kendo UI version:** 2018.1.117
* **jQuery version:** 3.2.1
* **Browser:** Chrome 67

**Comment by Iankodj** [comment]
Addressed in https://github.com/telerik/kendo-ui-core/issues/4086
