### ISSUE TITLE
PageSize is set to total when number of records is less than the page size

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#4092]
### Bug report

When the Grid has autoBind set to false and the number or returned items is less than the specified page size the Pager sets the total as pageSize.

### Reproduction of the problem
Run this dojo - https://dojo.telerik.com/UlOdASiv/7
Click Read button

### Current behavior
The page size is set to the total number of items

### Expected/desired behavior
The page size should be persisted

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** 1.12
* **Browser:** [all]

**Comment by VicTachev** [comment]
Reported in tickets 1157998, 1156965, 1157741

**Comment by digeomel** [comment]
Please, is there a workaround for this? Instead of upgrading to the latest version? We are paying customers.

**Comment by keyofj** [comment]
I have a similar problem and using a workaround in an older bug: [work around](https://github.com/telerik/kendo-ui-core/issues/3424)

In my case, it is when the record total is less and you have set the paging selection to "All". It does not persist correctly. Here is a modification I use that may help you: in databound event

```
var dropdown = $(e.sender.element).find('.k-pager-sizes').find('[data-role="dropdownlist"]').data('kendoDropDownList');
            var dropDownValue = dropdown.text();
            var pageSizes = this.options.pageable.pageSizes;

            if (dropDownValue !== "All") {  // grid sets the value to camelcase
                // check if the value is not one of our options
                if (pageSizes.indexOf(parseInt(dropDownValue)) === -1) {
                    // set it to ALL
                    isAllSelected = true;
                } else {
                    isAllSelected = false;
                }
            } else {
                isAllSelected = true;
            }

            setTimeout(function (e) {
                if (isAllSelected) {
                    dropdown.value("all");  // keep lowercase
                    dropdown.trigger('change');
                }
            });
```
I am on version 2018.1.117 (upgrade to latest if you can and this may go away)
