### ISSUE TITLE
Tables background color copied from word file is not pasted into Editor

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4094]
### Bug report
Tables background color copied from word file is not pasted into Editor

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/editor/all-tools , select all Editor content and delete it.
1. Open [TablesBackground.docx](https://github.com/telerik/kendo-ui-core/files/2702627/TablesBackground.docx) word document and copy a table from it.
1. Paste the table in the Editor.

### Current behavior
The color is not pasted as background to the table. If the pasteCleanup none option is set to true - the color will be pasted.
![image](https://user-images.githubusercontent.com/6614183/50341320-0f4bcc80-0527-11e9-9e30-276315878cb8.png)

### Expected/desired behavior
The background color should be pasted as well.
![image](https://user-images.githubusercontent.com/6614183/50341304-f93e0c00-0526-11e9-8f18-c016d7f51a3d.png)

### Environment
* **Kendo UI version:** 2018.3.1017
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by Iankodj** [comment]
Linked with https://feedback.telerik.com/kendo-jquery-ui/1557058-paste-tables-from-word-and-keep-the-format-styles

**Comment by Iankodj** [comment]
Raising priority due to high demand.
