### ISSUE TITLE
Work hours slots selected styles are not properly applied on the current day in Scheduler day view

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4097]
### Bug report
Work hours slots selected styles are not properly applied on the current day in Scheduler day view.

This is a regression introduced with R1 2018.1.221

### Reproduction of the problem
* Run the following [Dojo](http://dojo.telerik.com/iXEHozus/4);
* Try to select one of the available slots after 8 AM.

### Environment
* **Kendo UI version:**  R1 2018.1.221

**Comment by joneff** [comment]
The regression is a result from #3663 so after finishing this item, we should test the related as well.
