### ISSUE TITLE
The Grid select method is selecting wrong cells with locked columns.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#4102]
### Bug report

The Grid select method is selecting wrong cells with locked columns. It selects 3 instead of 1 cell. Also, the additional two cell cannot be deselected even if a single selection mode is used.

### Reproduction of the problem

The issue can be observed in the following Dojo:  https://dojo.telerik.com/IbAqUJeN

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all  ]

**Comment by simonssspirit** [comment]
More details and a possible fix are in ticket: 1158425

**Comment by MilenaCh** [comment]
The issue still exist if selectable mode is set to 'multiple, cell':

https://dojo.telerik.com/@milena/iVeCUjaz/2
Result: 5 selected cells

**Comment by boyandim** [comment]
We will add a comment in the select method api section for 'multiple, cell' case.
