### ISSUE TITLE
TreeView template not rendered correctly with special characters

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4104]
### Bug report

When specific special characters are set in the TreeView node text, the template is not being rendered correctly:

### Reproduction of the problem

Issue is reproduced [on the following Dojo example.](http://dojo.telerik.com/OwEWeruM/4)

### Current behavior

Node template is broken:
![image](https://user-images.githubusercontent.com/16972160/37759231-ad40dee2-2dbb-11e8-9610-07a88b7cecef.png)

### Expected/desired behavior

Special characters should be rendered correctly within the node template.

### Environment

* **Kendo UI version:** 2017.2.504
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
After a fix, the above scenario is fixed. After testing with other special characters, I found an issue that \ is skipped:
```
<div id="treeview"></div>
<script>
  $("#treeview").kendoTreeView({
    checkboxes: true,
    dataTextField: "text",
    dataSource: [
      { text: 't\e/st"1<2#3@>45!6', expanded: true, items: [
        { text: "-'f+o\o, ;:" },
        { text: "$%^&*`~T[e]s(t)?|{}" }
      ] }
    ]
  });
</script>
```
