### ISSUE TITLE
Item text in dropdown cut off in virtualization + rtl scenario

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4106]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/UmUToZij ) example. [Screenshot](https://www.screencast.com/t/DteE0A7Yk4l).

Workaround:

```
.k-virtual-list .k-virtual-item {
     padding-right: 8px !important;
     margin-right: 8px !important;
}
```

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** x.y
* **Browser:** [Chrome 65 ]

**Comment by mparvanov** [comment]
Not reproducible with Chrome 75.
