### ISSUE TITLE
MultiSelect losing values after editing in a grid template

### ISSUE THREAD

**Issue by sajeetharan** [telerik/kendo-ui-core#4108]
### Bug report
 MultiSelect losing values after editing in a grid template

### Reproduction of the problem

Here is the issue reproduced,

- Run the dojo
- Edit the first record in the Contracts grid
- Add a zip code such as 22250
- Click Save
- Then click Edit on the first row again
- Only zip code 22250 is displayed in the editor

 http://dojo.telerik.com/IREVAXar/2

### Current behavior
 It does not retain values.

### Expected/desired behavior
 It should retain values

### Environment

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

**NOTE** :  It works when you change k-min-length="3" to k-min-length="1", then the issue goes away. But in the scenario I'm working on, it needs to be 3.

**Comment by matanasov** [comment]
@sajeetharan 

This issue is fixed in 2017 R3 SP1 release (2017.3.1018). You can verify it by using this updated dojo example:
http://dojo.telerik.com/IREVAXar/3
