### ISSUE TITLE
The popup edit form is not closed on the first update click if there was a invalid value before entering a valid one(SASS themes).

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#4109]
### Bug report

The popup edit form is not closed on the first update click if there was an invalid value before entering a valid one(SASS themes).

### Reproduction of the problem

The issue can be observed in our demo: 

https://demos.telerik.com/kendo-ui/grid/editing-popup

I made a video showcasing the issue:  https://www.screencast.com/t/FiR6zWhPp

### Environment

* **Kendo UI version:** 2018.2.221
* **Browser:** [all ]

**Comment by ag-petrov** [comment]
Seems to work fine in the current version, user just needs to make sure that the button is clicked. When blurring an input the validation label is being hidden and the window gets a slight resize meaning that if the click was done at the lower part of the button ot may not occur there as first comes the blur.
