### ISSUE TITLE
JS error thrown in Scheduler Week View on updating events whose eventTemplate contains a table element

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4112]
### Bug report
If a Scheduler widget has an `eventTemplate `defined and that template contains a `<table>` element, moving an event within the Scheduler will result in *Cannot read property 'setAttribute' of undefined* error.

### Reproduction of the problem
1. Run the following [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/udixEKER);
1. In Week View drag one of the events to a new slot

### Current behavior
*Cannot read property 'setAttribute' of undefined* error

### Expected/desired behavior
No error thrown and the dragged event is updated.

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** all

**Comment by Avinapster** [comment]
I am also encountering same issue
