### ISSUE TITLE
Allow ToolBar items of type ButtonGroup and template items to be hidden

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4115]
Currently only items of type "button" and "splitButton" can be hidden through setting their **hidden: "true"** option ([dojo ](https://dojo.telerik.com/enEJICiB) example).

**Comment by Dimitar-Goshev** [comment]
Closing it as duplicate of https://github.com/telerik/kendo-ui-core/issues/2289
