### ISSUE TITLE
Scheduler does not remove recurrence exceptions when a recurring event is transformed to a non recurring

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4117]
### Bug report
Scheduler does not remove recurrence exceptions when a recurring event is transformed to a non recurring.

### Reproduction of the problem
* Go to the [Scheduler Index demo](https://demos.telerik.com/kendo-ui/scheduler/index);
* Create a daily recurring event;
* Edit one of the occurrences (not the first one);
* Edit another occurrence;
* Edit the entire series and make the event non recurring (Repeat = Never);

### Current behavior
The recurrence exceptions will remain in the Scheduler;

### Expected/desired behavior
All occurrences including the recurrence exceptions should be removed from the Scheduler.
Only the initial event should remain after converting it from recurring to non recurring. 

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** all

**Comment by IvanDanchev** [comment]
Priority raised and severity set to High due to inability to remove the remaining recurrence exception event. When trying to delete it a js exception is thrown. To reproduce it follow the steps from the issue description and at the end try to delete the recurrence exception, either through "Delete the current occurrence" or  "Delete the series".

**Comment by Dimitar-Goshev** [comment]
@veselints After the fix there is a JS error thrown `Cannot read property 'recurrenceId' of undefined`
### Reproduction of the problem
1. Go to the [Scheduler Index demo](https://demos.telerik.com/kendo-ui/scheduler/index);
1. Create a daily recurring event;
1. Edit the second occurrence;
1. Edit the third occurrence - **having a second recurring exception is vital to reproduce the error**
1. Edit the entire series and make the event non recurring (Repeat = Never);

### Current behavior
 `Cannot read property 'recurrenceId' of undefined`
```
                if(!model.isOccurrence() && !!model.recurrenceException && !model.recurrenceRule) {
                    dataSource.data().forEach(function(event){
                        if(event.recurrenceId === model.id) {
                            dataSource.remove(event);
                        }
                    });
```
