### ISSUE TITLE
ComboBox in dialog is not rendered correcty while filtering on iOS touch devices

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4130]
### Bug report
When ComboBox is rendered in dialog (Kendo Dialog or bootstrap modal) and the user is trying to filter the results, the results dropdown is rendered on wrong position. On every entered character in the input, the results dropdown is changing its position. 

### Reproduction of the problem
1. Open the following dojo on iPhone or iPad. - [http://dojo.telerik.com/asuxoHOc/9](http://dojo.telerik.com/asuxoHOc/9)
2. Try to filter the results

### Current behavior
The results dropdown appear on wrong position. [(screencast)](https://www.screencast.com/t/9C5oSijFJ0)

### Expected/desired behavior
The results should be rendered below or above the input filed of the ComboBox. 

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [iOS all ]

**Comment by Dimitar-Goshev** [comment]
Not reproducible with R3 2019 SP1 (2019.3.1023) - [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/utiJovuq)
