### ISSUE TITLE
Editor InsertImage button causes browser freeze.

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4131]
### Bug report

When an image is pasted in the kendo Editor, selected and then the **Insert Image** button is clicked - the browser freezes, because the web address evaluated so too long

### Reproduction of the problem
Use the following declaration of kendo Editor ([dojo](http://dojo.telerik.com/IRiMErAk/2));
```javascript
  <div id="example">
    <textarea id="editor" rows="10" cols="30" style="height:440px" aria-label="editor">                   
    </textarea>
  </div>
  <script>
    $(document).ready(function() {                 
      $("#editor").kendoEditor({ resizable: {                      
      }});
    });
  </script>
```
Steps
1. Paste certain image
1. Select the pasted image
1. Click on the **InsertImage** button

Test Image: 
![hay](https://user-images.githubusercontent.com/7202037/47836800-4a950f00-ddb2-11e8-94f1-adf1eae8350d.jpg)

video on the repro:

[https://monosnap.com/file/KeK0rDJ53L90tCy5ZivkmsI8IwWl7Y](https://monosnap.com/file/KeK0rDJ53L90tCy5ZivkmsI8IwWl7Y)

### Current behavior
Browser freezes when the pasted image is selected and the InsertImage button is clicked

### Expected/desired behavior
The browser should not get frozen. 

### Environment

* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by eyupyusein** [comment]
I wasn't able to reproduce it. Perhaps newer version of browsers handle this scenario better.
