### ISSUE TITLE
Grid pager items per page not displayed in Firefox

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4136]
### Bug report

Grid pager items per page not displayed in Firefox for the following themes:

1. Fiori
1. Material Black
1. Nova
1. Bootstrap v3
1. Material

The same behavior is observed for some of the themes in other browsers when there are 3 digits. For example:
https://dojo.telerik.com/eKiyiKer

### Reproduction of the problem

Open the Basic usage demo in Firefox:
https://demos.telerik.com/kendo-ui/grid/index

### Expected/desired behavior

The items per page numbers are displayed. For example the Default theme.

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [Firefox 59.0.2]

**Comment by jonaspal** [comment]
This is still happening in 2018.2.516.
Workaround:
html.k-ff .k-dropdown-wrap .k-input::before{
    content: none;
}
