### ISSUE TITLE
Datepicker have choice for navigation bar with month instead of fullyear name for the first month

### ISSUE THREAD

**Issue by obcdnico** [telerik/kendo-ui-core#4139]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
![image](https://user-images.githubusercontent.com/1224004/38421380-3830aeb4-39a7-11e8-976e-b49377f343a1.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/1224004/38421402-48dca736-39a7-11e8-9df6-a5e73daa8f8a.png)

can we have a boolean to do that ?

to do that go in file  : "node_modules\@progress\kendo-angular-dateinputs\dist\es\calendar\services\month-view.service.js"

-> line 96, function "navigationTitle()" we can have a boolean to say: ' i want to display month name instead of fullYear name for the first month'

i can be possible with perhaps an exposed variable in kendo template like this :
<kendo-datepicker [navigation]="true" [navigationMonthView]="true"></kendo-datepicker>

thx lot

( i have a ready pr it can be merged to kendo-angular-dateinputs, how i can submit it ? )

**Comment by matanasov** [comment]
@obcdnico 
I am closing this issue as this is not an angular-components related repository.
Please open a new issue in https://github.com/telerik/kendo-angular/issues
