### ISSUE TITLE
ScrollView does not work with remote transport and client size paging

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#414]
There is a problem when the ScrollView uses client side paging.

If the developer specifies the pageSize, the buffer uses the length of the current view() not the length of the whole data. See [here](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.data.js#L4432)

If the developer does no specify the pageSize, the buffer is not aware when to stop requesting new entries.

Example:

    <div id="home" data-role="view">
        <div id="scrollview-container">  
            <div data-role="scrollview" data-template="scrollview-template" data-source="datasource" data-content-height="300px"></div>
        </div>
    </div>
    <div id="test" data-role="layout" data-id="default">
        <header data-role="header">
            <div class="titlbar">
                Listview Demo
            </div>
        </header>
        <footer data-role="footer">
            <div data-role="tabstrip">
                <a data-icon="home" href="#home">Home</a>
            </div>
        </footer>
    </div>
    <script id="scrollview-template" type="text/x-kendo-template">
        <div data-role="page" style="width:300px; height:300px;">#: name #</div>
    </script>
    <script type="text/javascript">
        var app = new kendo.mobile.Application(document.body, { layout: "default" });

        var datasource = new kendo.data.DataSource({
            transport: {
                read: function (options) {
                    // make AJAX request to the remote service
                    $.ajax({
                        type: "get",
                        url: "banner3.json",
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: function (data) {
                            options.success(data);
                        }
                    });
                },

            },
            schema: {
                data: "banners",
                total: "count",
                fields: { 
                    name: { type: "string" },
                    image: { type: "string" },
                    title: { type: "string" }
                }
            }
        });
    </script>

Ticket: 879708

**Comment by underlog** [comment]
Fixed with this - 6e323cd0dad8aff27b1abff93d05a1ce90398c1e . No need to specify page size.
