### ISSUE TITLE
Drop zone not working it saveUrl: is not set. 

### ISSUE THREAD

**Issue by OoonaNet** [telerik/kendo-ui-core#4142]
Hi Team 
I'm using Kendo upload to select a file to upload to S3 I added a dropzone and it didn't work. 
After further research, it turned out that if "saveUrl:" is not set the dropzone functionality is not active!? 
once I set any value in it, it worked as expected. 

[Code.zip](https://github.com/telerik/kendo-ui-core/files/1887180/Code.zip)

**Comment by zdravkov** [comment]
Hi, 

Yes indeed this is expected - the drop zone is working only if the saveUrl is defined in the async options of the Upload widget. Drop functionality is only supported when async form module is used and it is only loaded if the saveUrl is defined.  We will need to document this behavior better.

**Comment by veselints** [comment]
Description available in the [Documentation](https://docs.telerik.com/kendo-ui/controls/editors/upload/drag-and-drop)

**Comment by sanjogs** [comment]
I don't see it documented in the linked article
