### ISSUE TITLE
Pager not refreshed correctly after selecting "All" page size

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4144]
### Bug report

Pager not refreshed correctly after selecting "All" page size on a page different from the first one.

This bug is introduced in 2018.1.221. I cannot replicate it in <= 2018.1.117.

### Reproduction of the problem

1. Open: https://dojo.telerik.com/ElEyumuW
2. Go to the second page.
3. From the drop-down, select "All" page size.

### Current behavior

https://www.screencast.com/t/9uYUthlfMaT

### Expected/desired behavior

https://www.screencast.com/t/24iowt2OwRdt

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all]

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket with ID 1178635. Raising priority.
