### ISSUE TITLE
Change event fires on pasting text in the Editor in IE

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4146]
### Bug report
In IE the Editor's change event fires immediately after pasting text in the widget, whereas in Chrome and Firefox it fires after blurring the Editor. This behavior has been introduced in version 2016.3.914.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/ASivaHuv/3) example.
1. Open the example in IE11.
2. Focus the Editor and paste text from the clipboard.

### Current behavior
In IE the change event fires after pasting text.  

### Expected/desired behavior
The change event fires on blurring the Editor. 

### Environment

* **Kendo UI version:** 2018.3.911
* **jQuery version:** x.y
* **Browser:** [ IE ]

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
