### ISSUE TITLE
Disabled checkboxes appear disabled only on hover (Edge)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4157]
### Bug report
After disabling programmatically a Kendo checkbox (element with class k-checkbox or a checkbox initialized with the wrapper: @(Html.Kendo().CheckBox()... ) it does not appear disabled in Edge until it is  hovered. 

### Reproduction of the problem
[Dojo example](https://dojo.telerik.com/ijiQACaG/9). 
1. Click the button => the checkbox does not appear disabled 
2. If the checkbox is hovered it is properly styled and appears disabled. 

### Environment

* **Kendo UI version:** 2019.3.1023
* **Browser:** [Edge]

**Comment by eyupyusein** [comment]
I wasn't able to reproduce this. Perhaps, the issue was in the old Edge.

**Comment by IvanDanchev** [comment]
Yes, the issue was in the old Edge (Spartan)
