### ISSUE TITLE
Wrong page sizes in the PDF Export / Page Layout demo

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-ui-core#4159]
### Bug report
When Page size should be divided by 1.33 as described[ the documentation](https://docs.telerik.com/kendo-ui/framework/drawing/drawing-dom#dimensions-and-css-units).
Reported in the ticket with ID 1161632.

### Reproduction of the problem
1. Open the following demo: https://demos.telerik.com/kendo-ui/pdf-export/page-layout.
2. Export the demo to PDF with set page size to A4.
3. The exported PDF will not be with A4 dimensions.

### Current behavior
For example, the page size A4 has dimensions "_**size-a4 { width: 8.3in; height: 11.7in; }**_" in the code of the demo;

### Expected/desired behavior
Dimensions should be divided by 1.33, so they will be width: 6.2in; height: 8.8in; Other page sizes dimensions should be corrected as well.

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
After a fix, demo layout is broken as follows:
- A 4:
  - Material, Material Black, Fiori, Nova, Office 365:
![image](https://user-images.githubusercontent.com/6614183/39116236-93b56ca0-46ec-11e8-8bc6-1f9339dcd129.png)


- Letter:
  - Material, Material Black, Fiori, Nova, Office 365:
![image](https://user-images.githubusercontent.com/6614183/39116269-b038c976-46ec-11e8-8c05-65afef265127.png)

  - Bootstrap v4 - https://www.screencast.com/t/CxsPckaZUJOa

- Executive:
  - Bootstrap v4 - https://www.screencast.com/t/dBZDX4hpuVJ
