### ISSUE TITLE
Toolbar throws js error when the number is as big as it makes the items to break on second line

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4161]
### Bug report

"Cannot read property 'find' of undefined" error is thrown when toolbar items break on a second line

### Reproduction of the problem
Run the following dojo example and open the browser console.
http://dojo.telerik.com/@nenchef/UlUNuBUF

### Current behavior
"Cannot read property 'find' of undefined" error is thrown

### Expected/desired behavior
No errors should be thrown

### Workaround

Setting _overflow: "never"_ to the separator items will fix the js error:
``` javscript
 { type: "separator", overflow: "never"  },
```
### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all]

**Comment by Iankodj** [comment]
Fixed with https://github.com/telerik/kendo-ui-core/issues/4101. Commit: https://github.com/telerik/kendo/commit/d10cd0c996bcc7696e39f67bf22a831b14c7305f
