### ISSUE TITLE
MultiSelect value is sorted on filtering from the input in AngularJS scenario

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4165]
### Bug report
Related to #4188

### Reproduction of the problem
1. Go to http://dojo.telerik.com/oMIxeLUF/10
1. Click on the MultiSelect and type x in its input.

### Current behavior
The value is sorted and again returned to the previous state. No items are filtered.

### Expected/desired behavior
The value should not be changed on filtering. Items should be filtered.

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
