### ISSUE TITLE
hasChanges method return false after an item is added

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4166]
### Bug report
HierarchicalDataSource hasChanges method returns **false** after an item has been added to the dataSource.

### Reproduction of the problem
- Run the following [Dojo](https://dojo.telerik.com/OzepEseW) and check that false is returned by the method after adding an item.

Another reproduction with TreeView
1. Open the [Dojo example](https://dojo.telerik.com/EhaMUHiQ)
2. Click the 'Add value' button and check the console.

### Current behavior
The hasChanges method returned 'false' although the data has been changed. 

### Expected/desired behavior
hasChanges() method should return 'true'

### Workaround
The hasChanges() method returns correct value when the id field of the newly added item (in this case "valeurId") starts with lowerCase letter. 

### Environment
* **Kendo UI version:** 2023.3.1114
* **Browser:** all

**Comment by gdenchevprog** [comment]
The hasChanges method searches for dirty and newly added items in the collection. The way the dataSource determines if an item is new, is based on the default id. If the id of the item that has just been added is the same as the defaultValue then the model would be considered "new" and hasChanges will return "true".

The default value for the id field is `""`, if the item is added with value `1` then it won't be considered as new.

The correct way to use the `dataSource.add()` method is to either add the item without specifying the id:
```javascript
hierarchicalDataSource.add({"Nom":"NewValue", "IsActif":false, "ValeursEnfants":[]});
```
Or to specify a default value for the id field:
```javascript
                  schema: {
                    model: {
                      id: "valeurId",
                      children: "ValeursEnfants",
                      fields: {
                        valeurId: {defaultValue: 1}
                      }
                    }
                  }

hierarchicalDataSource.add({"valeurId":1, "Nom":"NewValue", "IsActif":false, "ValeursEnfants":[]});
```
