### ISSUE TITLE
'Invalid-meta The "main" field cannot contain minified files' error is thrown when installing Kendo-UI Bower package

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#4167]
### Bug report

When installing Kendo UI using the Bower package that is hosted on  the Private Git repository the following error is observed:

_bower bower-kendo-ui#2018.1.221+SP1     invalid-meta for:C:\Users\parvanov\AppData\Local\Temp\PROGRESS-parvanov\bower\d86d0a71b49c762e899774fef446d55f-10092-ftcYFB\bower.json
bower bower-kendo-ui#2018.1.221+SP1     invalid-meta The "main" field cannot contain minified files_

### Reproduction of the problem
Execute: bower install https://bower.telerik.com/bower-kendo-ui.git#2018.1.221+SP1

### Current behavior
'Invalid-meta The "main" field cannot contain minified files' error is thrown and the scripts/styles are available

### Expected/desired behavior
No errors occur and the scripts/styles are available 

### Environment

* **Kendo UI version:** 2018.1.221

**Comment by ivanchev** [comment]
Same fix apllied to public repo as well:
https://github.com/kendo-labs/bower-kendo-ui
