### ISSUE TITLE
Incorrect parsing of recurring events start time, when displayed in Agenda view eventTimeTemplate and the events are loaded with AngularJS $resource

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4168]
### Bug report
Scheduler does not properly parse event `start` time of **recurring events** when it is being displayed in the **eventTimeTemplate** of **Agenda view**. This happens when the events are loaded with [AngularJS $resource](https://docs.angularjs.org/api/ngResource/service/$resource). The `start` time is always rendered as a number.

### Reproduction of the problem
Run the following [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/ABozUdiD);

### Current behavior
![image](https://user-images.githubusercontent.com/6614183/61447927-998fce00-a95a-11e9-9829-5a921b76f910.png)

### Expected/desired behavior
Start time of recurring events is displayed properly as start time of non-recurring events.

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** all

**Comment by veselints** [comment]
The workarownd would be to use a custom `eventTimeTemplate` wich properly converts the integer to date:
```html
<script id="event-time-template" type="text/x-kendo-template">
  # if (isAllDay) { #
     All day
  # } else { #
     #= kendo.toString(new Date(start + (new Date(start).getTimezoneOffset() * 60000)), "t") # - #= kendo.toString(end, "t") #
  # }  #
</script>
```

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
