### ISSUE TITLE
Unexpected single bullet  and left alignment applied to multiple lines in Editor

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#4176]
### Reproduction of the problem
1. Use the following [Dojo](https://dojo.telerik.com/erUSunOp)
2. Type A in Editor.
3. Click on "Align text right" button.
4. Press Enter.
5. Type B in Editor and press Enter.
6. Type C in Editor and press Enter.
7. Select B and C and click on "Align text left" button - B and C are aligned left.
8. Click on unordered or ordered bullets button.

### Current behavior
A, B and C rows become left aligned and A has a bullet in front:
![image](https://user-images.githubusercontent.com/6614183/39050846-94b60a18-44af-11e8-91b6-65ad97c77bd6.png)

### Expected/desired behavior
A remains right aligned, while B and C remain left aligned and with bullets in front.

### Note
This happens when there is no content at all in the Editor, thus the formatting dropdown says "Format". In such a case when "Align text right" is applied, the text is wrapped in a `<div>` element. A workaround could be to add an empty paragraph in Editor's content, which will make the formatting as "Paragraph" - [Dojo sample](http://dojo.telerik.com/AWEKejer). In this scenario each row will be a separate `paragraph `not wrapped in a common `div`, thus formatting will be as expected:
![image](https://user-images.githubusercontent.com/6614183/39050934-da120850-44af-11e8-848f-c56caf43e648.png)

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all]

**Comment by Iankodj** [comment]
The incorrect behavior stems from the justify tools. There is no paragraph initially the justify tool adds a div tag, which later is considered as a single block element and transformed into a single list item. 

The behavior that is correct is to create a paragraph. And thus, when the last two lines are converted to list items-two list items to be generated and tha first line to remain with the correct alignment. 

```html
<p style="text-align: right;">a</p>
<ul>
  <li>b</li>
  <li>c﻿</li>
</ul>
```

**Comment by Dimitar-Goshev** [comment]
https://github.com/telerik/kendo-ui-core/issues/4175
