### ISSUE TITLE
Scheduler does not parse properly the start and end dates in the eventTemplate when Date grouping is used in Month view

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4178]
### Bug report
Scheduler does not parse properly the start and end dates in the eventTemplate when Date grouping is used in Month view

### Reproduction of the problem
Run the following [Dojo](https://dojo.telerik.com/uyEcuhUS/2). You will notice 2 things:
- The date is passed to the template as integer;
- Even parsed as Date, that integer represents the start of each day (00:00).  The time part of the date is omitted;

**Comment by veselints** [comment]
To workaround this issue, placeholders for the dates could be put in the template and the DataBound event could be handled:
```html
"{start} - {end}"
```
and:
```JavaScript
    function onDataBound(e) {
        var events = $('.k-event');
        var scheduler = e.sender;

        for (var i = 0; i < events.length; i += 1) {
            var currentEvent = $(events[i]);
            var initialText = currentEvent.text();
            var uid = currentEvent .data('uid');
            var eventItem = scheduler.occurrenceByUid(uid);

            modifiedHtml = initialText.replace(/{start}/g, kendo.toString(eventItem.start, 'HH:mm'));
            modifiedHtml = modifiedHtml.replace(/{end}/g, kendo.toString(eventItem.end, 'HH:mm'));
            currentEvent.html(modifiedHtml);
        }
    }
```

**Comment by zdravkov** [comment]
fix in [this branch](https://github.com/telerik/kendo/tree/scheduler-monthview-fix) .
