### ISSUE TITLE
TimePicker doesn't show value when re selecting after deleting.

### ISSUE THREAD

**Issue by EduardoSerra** [telerik/kendo-ui-core#4179]
### Bug report

After selecting a value and deleting it manually, it won't be displayed again when reselecting it

### Reproduction of the problem

1. Go to the [events demo in the demos section](https://demos.telerik.com/kendo-ui/timepicker/events)
2. Click on the time picker icon and pick 12:00 AM.
3. Now delete the content from the input box manually.
4. Without loosing focus from the input box, click on the time picker icon and select 12:00 AM again.

### Current behavior

The input box will not show 12:00 AM.

### Expected/desired behavior

The input box should show 12:00 AM.

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** 1.12.4
* **Browser:** All

**Comment by EduardoSerra** [comment]
Reported on ticket #1163497

**Comment by matanasov** [comment]
@EduardoSerra 
I think this is expected because the value changes on blur and in this scenario the input is never blurred. Hence the value remains 12:00 AM although the user doesn't see it.
I am notifying our devs about this and they can confirm if it is expected or issue.

**Comment by rkokal** [comment]
This used to work earlier as expected. Also this scenario works currently for Date picker and DateTime picker controls, but for Time picker, its an issue.

If the changes are reverted back to the earlier code for the _update method in Time picker control, then the scenario works fine. Below is the reverted code:

```
_update: function (value)
{
	// Below fix is for the Time Picker control issue
	// Select a value via picker, clear it in the input box, and selecting the previous value via picker
	// without losing focus from the control
	var that = this, options = that.options, timeView = that.timeView, date = timeView._parse(value);
	if (!isInRange(date, options.min, options.max))
	{
		date = null;
	}
	that._value = date;
	that.element.val(kendo.toString(date || value, options.format, options.culture));
	timeView.value(date);
	return date;
}
```
