### ISSUE TITLE
Column / Row resize handler appears in the wrong position for frozen columns / rows after scrolling to the right / down

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4180]
### Bug report
Having a Spreadsheet with frozen columns. After scrolling the Sheet to the right, the column resize handler on the frozen columns remains on the initial fixed position. The same applies for the frozen rows.

### Reproduction of the problem
* Run the following [Dojo](https://dojo.telerik.com/OSoBeMiB/2);
* Move the spreadsheet horizontal scroll bar a bit to the right;
* Try to adjust the width of the productName column.

Screenshot here:
![spread](https://user-images.githubusercontent.com/3431388/39169754-b038ce84-47a1-11e8-9241-d3f25f9f5390.png)

**Comment by mishoo** [comment]
Possibly related to #1815.

**Comment by Dimitar-Goshev** [comment]
I am putting this issue back in progress as it was fixed together with the related issue, which is not fixed completely. This one appears fixed, but it would be good to be retested, when the related issue is fixed.
