### ISSUE TITLE
Classes in the Vue autocomplete wrapper are added wrongly

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-ui-core#4181]
### Bug report
1. A custom static CSS class is added to both elements - "k-widget" and "k-input". The class should be added only to the widget wrapper (k-widget).

2. Dynamically added custom CSS class is applied to the "k-input" element instead of to its parent - k-widget..com/)**

### Reproduction of the problem
1. Run the following demo: http://dojo.telerik.com/AxIvUTAt.
2. After loading the page, the static "form-control" class name is added to both elements.
![2018-04-24_1136](https://user-images.githubusercontent.com/4389590/39175829-fafa7d70-47b3-11e8-980d-5b7be51187d6.png)
3. Focus and clear the AutocompleteBox.
4. The dynamically added class is applied to the "k-input" element instead of to the widget wrapper.

### Expected/desired behavior
All custom classes - static and dynamically added, should be added to a widget wrapper only.

**Comment by Iankodj** [comment]
The problem I see here is that the k-input class is removed from the element and thus, it is not decorated properly anymore. That is related to the :class behavior explained here: https://github.com/vuejs/vue/issues/3975. 

The proper behavior would be to have both static and dynamically bound classes on both element and wrapper, and preserve the ones added dynamically by the Kendo Widget.

**Comment by Iankodj** [comment]
With this improvement, any class that is added to the component through the `class` attribute or the `:class` prop will be added to the element and the wrapper of the widget. Plus, any kendo classes that are added dynamically after initialization will be stashed and appended during $attrs change of the component.
