### ISSUE TITLE
[Grid]: Existing filters get cleared when invalid date value provided for 'Date' column filter

### ISSUE THREAD

**Issue by jigneshhdalal** [telerik/kendo-ui-core#4183]
Demo: https://demos.telerik.com/kendo-ui/grid/remote-data-binding

Repro Steps:
1) Go to demo link [here](https://demos.telerik.com/kendo-ui/grid/remote-data-binding).
2) Apply a "Contains" filter with "carnes" value on "Ship Name" column.
3) Apply a "Is greater than" filter with "50" value on "Frieght" column.
4) Now, for "Order Date" column provide "asdfdfdsf" (invalid date) value and apply the filter. Observe that existing filters (point 2 and 3) are cleared and all the data is being shown.

**Comment by MilenaCh** [comment]
The problem could not be reproduced with the latest version.
