### ISSUE TITLE
MultiSelect, DropDownList, ComboBox dropdown should not be rendered outside the viewport

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4187]
### Bug report
When the height of the items dropdown exceeds the height of the viewport the end of the items list is rendered outside the viewport. Thus when the user try to scroll to the end, the dropdown closes.

### Reproduction of the problem
1. Open the Dojo - [https://dojo.telerik.com/IFuxaFes](https://dojo.telerik.com/IFuxaFes)
2. Scroll to the end of the items

### Current behavior
The list with the items will close.

### Expected/desired behavior
The height of the list with items should be limited to the visible part of the viewport.

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all ]

**Comment by zdravkov** [comment]
The behavior is expected because we set the height to 800 and the popup is getting the correct height. In case we need another height we should set it according to the needs.
