### ISSUE TITLE
MultiSelect does not behave properly, when in AngularJS scenario, its DataSource is sorted and the select element initially has its 'multiple' attribute set

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4188]
### Bug report
MultiSelect does not behave properly, when in AngularJS scenario, its DataSource is sorted and the `<select>` element initially has its 'multiple' attribute set.

Related to #4165 - the issues seem very similar, but the other one does not need multiple attribute set to select element to be reproducible.

### Reproduction of the problem
Run [the following Dojo](https://dojo.telerik.com/IzENIYiJ/24) and follow the steps, which are written in the Dojo.

### Current behavior
The filter typed is cleared and MultiSelect items are not filtered.

### Expected/desired behavior
The filter is not cleared and MultiSelect items are filtered based on it.
NOTE: this behavior is achieved, if the multiple attribute is removed from the select element.

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
