### ISSUE TITLE
Scheduler view() not available in parameterMap with jQuery 3.1.1

### ISSUE THREAD

**Issue by msmolka** [telerik/kendo-ui-core#4191]
### Reproduction of the problem
Official documentation stays that Kendo UI is compatible with JQuery 3.1.1. However on scheduler there are still issues with that, see example:

https://dojo.telerik.com/AmeGiHAV

server filtering is not working when using JQuery 3.1.1.The view is not available because of `Deferred` changes in JQuery.  

### Current behavior
the `view()` is not available in `parameterMap` for server filtering.

### Expected/desired behavior
as documentation states, and JQuery 1.* and 2.* works the `view()` should be available in `parameterMap`.

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** 3.1.1+
* **Browser:** [all]

**Comment by veselints** [comment]
[Here is a modified sample](https://dojo.telerik.com/AmeGiHAV/6), which enables the *serverFiltering* option for the Scheduler DataSource. The View, the Start and End dates are properly retrived.

**Comment by msmolka** [comment]
In my scenario I cannot use `autoBind:true`. I need create scheduler first, then read data. So this is not working for me.
