### ISSUE TITLE
Clear button is displayed when no item is selected

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4192]
### Bug report
If the ComboBox value is cleared programmatically either with the select(-1) or value("") method on hovering the widget its clear button is displayed. 

### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/OruBOjOR) example.
1. Click the "clear value" button.
2. Hover the widget = > the clear button is displayed.

### Current behavior
Clear button is displayed.

### Expected/desired behavior
Clear button is not displayed when there is no item selected.

As a workaround the widget's refresh method can be called after clearing the value:
```
$("#ComboBox").data("kendoComboBox").refresh();
```

Possibly related to #3645 

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by jivanova** [comment]
Added enhancement to hide the clear button after being pressed.
