### ISSUE TITLE
Primary button in widgets' dialogs is not visible in Nova theme

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4196]
### Bug report
**Regression since 2018.1.221**
Update button is not visible in Grid Add New Item popup, in Nova theme.
NOTE: the issue is not limited to Grid. It is also reproducible in Editor Table wizard and Spreadsheet Data validation editor.

### Reproduction of the problem
Use the kendo demo below:
https://demos.telerik.com/kendo-ui/grid/editing-popup

Click on Add New Record button  - the Update button has the same color as the bottom bar, hence it is not visible.

### Current behavior
Update button is not visible 

### Expected/desired behavior
Update button should be visible 

### Workaround
Change the background color of the _k-edit-buttons_ to _transparent_

```css
.k-edit-buttons {
      background: transparent;
}
```

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all]

**Comment by joneff** [comment]
Fixed by https://github.com/telerik/kendo/pull/8736
