### ISSUE TITLE
An anchor in custom ToolBar item does not navigate on pressing Enter key

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4197]
### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/OxedAmat) example. 
1. Focus the anchor in the ToolBar. 
2. Press Enter => no navigation occurs. 

### Current behavior
Anchor navigation with keyboard is prevented when the anchor is placed in a custom ToolBar item.

### Expected/desired behavior
Navigation to the specified url occurs on click and on pressing Enter key. 

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by IvanDanchev** [comment]
A different scenario that does not involve a "template" item, but a "button" type item shows similar behavior when the click handler is set through the onclick attribute. Clicking the button fires the click event, whereas pressing Enter while the button is focused prevents the event: [dojo example](https://dojo.telerik.com/acErOmaX).

**Comment by Dimitar-Goshev** [comment]
After a fix is applied, in IE 9 the button scenario still does not work. Pressing Enter does not trigger click, while clicking on the button triggers it. The anchor scenario works as expected. Both scenarios work as expected in all other browsers.

**Comment by Dimitar-Goshev** [comment]
I am reopening this as a regression appeared. It is not possible to check group toggle buttons with Enter, when they are togglable by themselves, like Bold, Italic and Underline group:
https://demos.telerik.com/kendo-ui/toolbar/index (Test this scenario on staging)
```
{
    type: "buttonGroup",
    buttons: [
        { icon: "bold", text: "Bold", togglable: true },
        { icon: "italic", text: "Italic", togglable: true },
        { icon: "underline", text: "Underline", togglable: true }
    ]
},
```
Toggling with Enter works OK for a group where only one button can be selected, like Left, Center and Right.

**Comment by Dimitar-Goshev** [comment]
Click event is not fired anymore for SplitButton, when pressing Enter while it is focused
