### ISSUE TITLE
RTL Scheduler displays the wrong arrows in Timeline views for events that span outside the business hours

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4202]
### Bug report
When the Scheduler is used in RTL and business hours are shown in its view (`showWorkHours: true`), the arrows pointing that the event spans outside of the visible time range are wrong. The left arrow points to the right and vice versa.

### Reproduction of the problem
Run the following [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/UsaSuMeY)

### Current behavior
![image](https://user-images.githubusercontent.com/6614183/64178640-7ff30900-ce6a-11e9-8957-124b1ac43473.png)
![image](https://user-images.githubusercontent.com/6614183/64178717-ab75f380-ce6a-11e9-973e-7a8be96ba522.png)

### Expected behavior
Arrows point that the event continues beyond the visible timeslots.

### Environment
- **Kendo UI:** 2019.2.619
- **Browser:** all

**Comment by magdalenaan** [comment]
The issue cannot be reproducible with v2022.3.913
