### ISSUE TITLE
Grid is missing column menu active style when using Metro skin

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#4204]
### Bug report
If you enable the column menu in a Grid using the Metro skin, the column menu button is not highlighted when a filter is applied to the column:
[https://dojo.telerik.com/oYaboTOz](https://dojo.telerik.com/oYaboTOz)

If you replace the skin with "Default", for example, you will see an active style applied to the column menu button in the OrderID column.

### Environment

* **Kendo UI version:** 2018.1.221

**Comment by matanasov** [comment]
@TsvetinaIvanova 
As far as I can see - it is applied correctly. Here is an image of the dojo example with the grid filtered by OrderID. What am I missing?

![style](https://user-images.githubusercontent.com/5861835/39745389-c5b1c39c-52af-11e8-93ac-adcb73b43f0f.png)
