### ISSUE TITLE
Change event triggered twice on paste

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4205]
### Bug report

Change event is triggered twice when pasting content in the Spreadsheet.

### Reproduction of the problem

The issue can be reproduced [on the following Dojo](https://dojo.telerik.com/OGugobeT/2). Just paste content in any cell/s.

### Current behavior

Change event is executed twice.

### Expected/desired behavior

Change event should be executed only once.

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [all]

**Comment by veselints** [comment]
Also reported in Ticket ID: 1176287
