### ISSUE TITLE
null reference error under Firefox when the widget is in a hidden iframe

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/kendo-ui-core#4206]
### Bug report

Due to a browser bug [https://bugzilla.mozilla.org/show_bug.cgi?id=548397](https://bugzilla.mozilla.org/show_bug.cgi?id=548397), the `window.getComputedStyle()` call returns `null` when the Kendo widget is in an iframe that is not rendered. This error breaks the widget rendering and can also break other scripts.

Report in Ticket ID 1164195 

### Reproduction of the problem

A sample is attached
[ff-hidden-frame-bug.zip](https://github.com/telerik/kendo-ui-core/files/1982622/ff-hidden-frame-bug.zip)

### Current behavior

The error is thrown in `elementStyles` in `drawing.js` when the `styles` are accessed in the loop.

The exact error message may vary between versions due to the minification process assigning different function and variable names. Here is an example:

```
TypeError: r is null[Learn More]
kendo.all.js:14380:28
w
kendo.all.js:14380:28
init
kendo.all.js:18225:58
create
kendo.all.js:17426:27
gi.create
kendo.all.js:17561:19
init
kendo.all.js:23202:25
n.create
kendo.all.js:23307:6
_initSurface
kendo.all.js:161806:35
init
kendo.all.js:161640:16
_createChart
kendo.all.js:163328:20
_initChart
kendo.all.js:163322:39
_initDataSource
kendo.all.js:163345:21
init
kendo.all.js:163133:22
plugin/e.fn[c]/<
kendo.all.js:2440:35
each
https://kendo.cdn.telerik.com/2018.1.221/js/jquery.min.js:2:2879
each
https://kendo.cdn.telerik.com/2018.1.221/js/jquery.min.js:2:844
plugin/e.fn[c]
kendo.all.js:2439:24
createChart
http://localhost:55251/ff-hidden-frame-bug/chart.html:28:13
i
https://kendo.cdn.telerik.com/2018.1.221/js/jquery.min.js:2:27444
fireWith
https://kendo.cdn.telerik.com/2018.1.221/js/jquery.min.js:2:28213
ready
https://kendo.cdn.telerik.com/2018.1.221/js/jquery.min.js:2:30004
K
https://kendo.cdn.telerik.com/2018.1.221/js/jquery.min.js:2:30366
```

### Expected/desired behavior

No error is thrown. The chart must be redrawn after the iframe is shown, however, as with any other hidden parent element.

### Environment

* **Kendo UI version:** any
* **jQuery version:** any
* **Browser:** Firefox

**Comment by nenchef** [comment]
Increased priority due to another report in Ticket ID - 1154954

**Comment by tylerorchestratellc** [comment]
Is there any update on this issue? I just ran into this in the kendo.all.js file in Firefox when I have a form hidden in an iframe a user can open later.
