### ISSUE TITLE
Kendo LESS themes icons blocked with CSP

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4208]
### Bug report

Kendo UI Icons not loaded with LESS themes due to [the following Content Security Policy](https://support.microsoft.com/en-us/help/3053676/windows-10-technical-preview-adds-a-feature-that-blocks-untrusted-font).

### Current behavior

Icons are not loaded.

### Expected/desired behavior

Icons should be loaded regardless of the described CSP. 
A possible approach to workaround the issue is to embed the font icons in the LESS themes.

### Possible Workaround

Reference the following font file after the Kendo UI Less theme references ([font.zip](https://github.com/telerik/kendo-ui-core/files/1991470/font.zip)).

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** [ IE11 | Edge ]

**Comment by dvdobrovolskiy** [comment]
+1

**Comment by crawy** [comment]
Thank you the workaround it worked for us. We have added the the font.css after kendo css.  Just a sidenote we only had issues using https with certificate. Everything worked properly using http.

**Comment by joneff** [comment]
@crawy I am glad the workarounds work.

**Comment by joneff** [comment]
Considering the workarounds provided and that the policy has been swiftly re-evaluated after introduction, we are closing the issue.
