### ISSUE TITLE
Navigatable incell editable grid loses changes if TAB is pressed in Edge HTML17

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#4209]
### Bug report

Reported in ticket with ID 1165670 - After upgrading to the Windows April 2018 Update (1803) 

The changes are lost when you <kbd>TAB</kbd> out of a dirty cell if that cell is a `string`. If the user clicks, the changes are ***not*** lost, only when tabbing out.

The `number` and `boolean` fields work as expected and trigger the `save` event with <kbd>TAB</kbd>. 

### Reproduction of the problem

 ✋  Check the ticket note for access to a machine with Edge with HTML 17

[https://demos.telerik.com/kendo-ui/grid/editing](https://demos.telerik.com/kendo-ui/grid/editing)

1. Open the demo in Edge
1. Edit the `ProductName` column
2. Press <kbd>TAB</kbd>

### Current behavior

Changes are lost when you tab out of a string type dirty cell.

### Environment

* **Kendo UI version:** 2018.1.221
* **jQuery version:** 1.12
* **Browser:** [Edge HTML 17]

**Comment by Alex-Bubblemaster** [comment]
Raised priority as reported in ticket with ID 1171821. If this is a show stopper, we may look into providing a workaround for our clients while Microsoft fixes this issue. They assigned it to a developer on 28 May.

**Comment by PreslavKozovski** [comment]
Reported again in 1172122

**Comment by Alex-Bubblemaster** [comment]
Reported in 1172548

**Comment by VicTachev** [comment]
Also reported in 1172806  and 1172811

**Comment by PreslavKozovski** [comment]
Reported again in 1176641

**Comment by PreslavKozovski** [comment]
Temporary workaround while Microsoft fixes this issue:
https://dojo.telerik.com/OkACIwOH

**Comment by Alex-Bubblemaster** [comment]
Reported in forum with ID 1179155

**Comment by Alex-Bubblemaster** [comment]
Reported in ticket with ID: 1340470

**Comment by Alex-Bubblemaster** [comment]
Microsoft have fixed the issue in Edge, they should release it in the next Windows update.
