### ISSUE TITLE
KendoMenu are  KendoGrid columnMenu are not working properly sub menu items are hidden on Edge and Firefox.  

### ISSUE THREAD

**Issue by samudrak** [telerik/kendo-ui-core#4211]
KendoMenu are  KendoGrid columnMenu are not working properly on Edge and Firefox. Sub menu items are hidden.  It works properly on chrome 
 
Try this one on EDGE  it does not work.

http://dojo.telerik.com/oLAxeBuW

Note : 

1. It works with JQerry version 1.12.4 
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/kendo.all.min.js"></script>

2. But not works with 2.0 of JQuery 
    <script src="https://code.jquery.com/jquery-2.0.0.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/kendo.all.min.js"></script>

Dom Structure on Edge. 

![edge](https://user-images.githubusercontent.com/2469444/39899413-5b3ec61e-54d9-11e8-8c39-7adb528fa0f0.JPG)

Dom Structure on Crome
![crome](https://user-images.githubusercontent.com/2469444/39899502-efe17c3a-54d9-11e8-9dd6-0012d13ada5a.JPG)

on edge wrapper div with k-animation-container class is missing .  There for Menu Items are rendered but not displaying .

Reference to old issue 
https://github.com/telerik/kendo-ui-core/issues/3717

**Comment by PrasathHari** [comment]
Hi,
I am also experiencing the same problem. In IE 11 the wrapper div is not getting coming. I am using telerik UI MVC v2017.3. Please let me know the solution. I am having a hard time finding a solution for this issue.

**Comment by mgunko** [comment]
Any updates on when this issue will be resolved?

**Comment by Dimitar-Goshev** [comment]
@PrasathHari @mgunko As noted in the related issue, both are fixed and the fix will be included in R3 2018 SP1
