### ISSUE TITLE
JavaScript error is thrown on paste in Internet Explorer

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#4212]
### Bug report

The issue is thrown when pasting from Word document that contains lists.
[https://demos.telerik.com/kendo-ui/editor/index](https://demos.telerik.com/kendo-ui/editor/index)

### Reproduction of the problem

[Richtextbox issue.docx](https://github.com/telerik/kendo-ui-core/files/1994151/Richtextbox.issue.docx)

1.  Paste the content from the above document

### Current behavior
Object doesn't support property or method 'append'. 

### Expected/desired behavior
Content to be pasted correctly. Workaround:
[https://dojo.telerik.com/oYoJopun](https://dojo.telerik.com/oYoJopun)
Make sure that the append method is called to a jquery object.

### Environment

* **Kendo UI version:** 2018.1.221
* **Browser:** IE

**Comment by IvanDanchev** [comment]
The fix causes an unexpected effect in certain scenarios: list numbers are converted to Roman numbers. Use the exemplary content from the file attached in the first post in ticket id: 1171895.

**Comment by jivanova** [comment]
The errors are reproducible after https://github.com/telerik/kendo-ui-core/issues/2498 . Fixing the JavaScript error revealed the actual issue with pasting lists in IE.
