### ISSUE TITLE
While creating a formula, cannot navigate through already present tokens

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#4217]
### Bug report

Creating a formula with keyboard navigation restricts users to not go through already selected cells in the formula. 

### Reproduction of the problem
https://demos.telerik.com/kendo-ui/spreadsheet/index

1. Double click on F7
2. Delete the current formula (leave the = sign)
3. Navigate to D7 and press +
4. Navigate to E7 and press +
5. Try to navigate to C7 with left arrow

### Current behavior
Cursor is stuck in F7 cell.

### Expected/desired behavior
Should be able to pass through already selected cells.

### Workaround
https://dojo.telerik.com/EDUpotif

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** all
* **Browser:** [all]

**Comment by mishoo** [comment]
The commit above references the wrong issue.  It fixes #4219 instead.  Sorry about that..
