### ISSUE TITLE
Update TypeScript definitions and documentation for calendar footer.

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4218]
### Bug report

Update TypeScript definitions and documentation for calendar footer.

https://docs.telerik.com/kendo-ui/api/javascript/ui/calendar/configuration/footer

It should look like:

footer String | Function | Boolean

**Comment by wildough57** [comment]
Still wrong in 2018.3.911.  At least when you install via npm as I do.

**Comment by Dimitar-Goshev** [comment]
@wildough57 Indeed the fix is not in the version distributed with the nmp. I am reopening the issue and we will address it for R3 2018 SP.next

**Comment by ivanchev** [comment]
The npm installation relies on the DefinitelyTyped project, where we're still waiting for approval on our pull request. 

The issue itself has been fixed, as can be seen here:
https://github.com/telerik/kendo-ui-core/blob/master/typescript/kendo.all.d.ts#L1908
