### ISSUE TITLE
An error is thrown when serialize tojson and then reading it back with fromjson a workbook and pressing enter over the active cell

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#4219]
### Bug report
An error is thrown when serialize tojson and then reading it back with fromjson a workbook and pressing enter over the active cell

### Reproduction of the problem
1. Open the following demo http://dojo.telerik.com/UNUfawem/3
2. Double click to edit B1 cell
3. Press Enter

### Current behavior
An error is thrown and the UI hangs

### Expected/desired behavior
No errors occur and the cell could be edited successfully

Note: Suggested workaround in Ticket ID: 1167532

### Environment

* **Kendo UI version:** 2018.1.221

**Comment by mishoo** [comment]
Fixed in https://github.com/telerik/kendo/commit/1e5a47023df2e378ffdd934ec6b2660c5740b83b
