### ISSUE TITLE
Provide backwards compatibility for old font icons in LESS themes

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4220]
Add backwards compatibility for old font icon classes [that were changed in the 2017 R1 release](https://docs.telerik.com/kendo-ui/backwards-compatibility/2017-backward-compatibility#changes-from-2016-r3-sp2) in the LESS Themes (already implemented in SASS based themes).

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
