### ISSUE TITLE
Window cannot be resized over an iframe

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4221]
### Bug report
The Window widget cannot be resized when opened over an iframe. After trying to expand the Window, the events are not being properly attached/detached, thus causing the widget to shrink/expand only by moving the mouse.

### Reproduction of the problem
1. Run the following [Dojo](https://dojo.telerik.com/ENIpiRoP).
1. Try to increase Window's width or height by moving the mouse outwards of window's borders.

### Current behavior
Window size cannot be increased. Also there are [visual glitches when moving the Window over the iframe](https://github.com/telerik/kendo-ui-core/issues/4336).
[Screencast](https://www.screencast.com/t/QMcwXqH7XX1h).

### Expected/desired behavior
Window resize functionality should be working correctly regardless of the underlying element.

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** all

**Comment by doalg** [comment]
Hi.
I've looked at your code and I see that the resizing happens after dragging, and for long time is a know issue, because I found this post:
https://www.telerik.com/forums/drag-stops-when-mouse-hovers-over-iframe---suggested-fix-

Have you fixed the dragging issue during ? If yes, it's a base for the resizing issue.

**Comment by Dimitar-Goshev** [comment]
Hi, the dragging issue is logged separately here: https://github.com/telerik/kendo-ui-core/issues/4336
Both issues are still open.

**Comment by PekoPPT** [comment]
Reported in ticket #1474115

**Comment by Juveniel** [comment]
The iframe events interfere with the Window drag and resize events, thus leading to the observed behavior. To workaround the issue, there are two possible approaches:

* Utilize [the Window modal option](https://docs.telerik.com/kendo-ui/api/javascript/ui/window/configuration/modal) when we know there are iframes on the page. This will add an overlay behind the Window when it is opened, thus preventing the issues with resizing and dragging. 

* Utilize [the Window resize/drag events](https://docs.telerik.com/kendo-ui/api/javascript/ui/window#events) to find every iframe on the page and programmatically add an overlay above the iframes to prevent their events from triggering, thus eliminating the issue. Refer to [the following Knowledge Base article](https://docs.telerik.com/kendo-ui/knowledge-base/window-drag-resize-over-iframe) that demonstrates this approach.

Taking the above into consideration, the recommended approach is to utilize the modal option. However, in case you need to drag/resize a non-modal Window over iframes on the page, then the second approach demonstrated in the above-linked Knowledge Base article can be used.

Closing the issue.
