### ISSUE TITLE
Scroll bar is not displayed on entering a new line in br tag mode (Chrome)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4222]
### Bug report

In \<br> tag [new line mode](https://docs.telerik.com/kendo-ui/controls/editors/editor/how-to/customize/change-p-to-br-tag) when the cursor is at the bottom of the Editor and a new line is entered the Editor does not display a scrollbar and the its content is not scrolled. The cursor position remains hidden from view. 

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/UqOxOdep) example.

1. Focus the Editor and press Enter until the cursor goes past the Editor's bottom border. 

### Environment

* **Kendo UI version:** 2018.2.516
* **jQuery version:** x.y
* **Browser:** [Chrome 66 ]

**Comment by asifbts** [comment]
Is this issue being addressed?
