### ISSUE TITLE
Unmerging cells sets the value to each of the previously merged cells

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4227]
### Bug report
The root cause of the issue is the fact that internally, we are populating all merged cells (not only the first one) with the same typed value. As a result, when the first three cells on the first row are merged, the `=COUNTA(A1:C1)` function will return 3, while in Excel it will return 1.

### Reproduction of the problem
Reproducible in the demos. [Screencast](https://www.screencast.com/t/Tf2utl3uw).
1. Select several cells and merge them. 
2. Enter a value in the new cell. 
3. Unmerge the cells.

### Current behavior
The value is set to all previously merged cells. 

### Expected/desired behavior
The value is set only to the first cell in the range of merged cells. 

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by veselints** [comment]
Also reported in Ticket ID: 1405609

**Comment by PekoPPT** [comment]
This issue could be also observed with COUNTBLANK, SUBTOTAL, and COUNT (range operations). 
Ticket ID: 1406172
