### ISSUE TITLE
DropDownTree value on change event is not empty, when the event is triggered by clear button or Esc key

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4228]
### Reproduction of the problem
https://dojo.telerik.com/UNIdEjEH
select an item 
click clear button to clear the item

### Current behavior
value is still there

### Expected/desired behavior
no value in the clear change event

### Environment
* **Kendo UI version:** 2018.2.516
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
- [ ] http://kendobuild-staging.openstack.progress.com/kendo-ui/api/javascript/ui/dropdowntree/events/clear - Description does not clearly state that the event is fired only when clear button is clicked or when Esc key is pressed.

- [ ] http://kendobuild-staging.openstack.progress.com/kendo-ui/api/javascript/ui/dropdowntree/events/clear "Example - subscribe to the "**change**" event after initialization"
- [ ] Add clear event to all Events demos

**Comment by zdravkov** [comment]
We have inspected the issue and decided that we will fix the bug with the value in the change event and not add clear event at this time to keep the persistence how other widgets work.
