### ISSUE TITLE
Grid height changes in IE9 after column resize and row click

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4229]
### Bug report

Grid height changes in IE9 after column resize and row click.
More information in 1167641.

### Reproduction of the problem

http://dojo.telerik.com/iNEbIcOq in IE9

### Environment

* **Kendo UI version:** 2018.2.516
* **Browser:** [IE 9]

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
