### ISSUE TITLE
The images for the Tile Layer are sometimes requested with wrong URL

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#4231]
### Bug report
In the following dojo example, the URL for the tile layer is with "http", but when you zoom fast to the maximum zoom level, wrong requests are send with "https" and no images are displayed. Panning or zooming in and out resolves the issue (sometimes).

### Reproduction of the problem
Try zooming to the last zoom level and you will notice failed requests in the console.
https://dojo.telerik.com/ejilAxuq/6

### Environment

* **Kendo UI version:** 2018.2.516
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Stamo-Gochev** [comment]
The problem seems to be caused by the service itself as the map is not changing the URL. The issue cannot be reproduced in the[ Bing tile layer demo](https://demos.telerik.com/kendo-ui/map/bing) (which uses a different service).
