### ISSUE TITLE
Expose old range in the change event

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4232]
Currently, in the Spreadsheet change event only the new range object is available in the event data. Improving the change event to include old range object would greatly benefit users in scenarios, where both the old and new values of a cell need to be compared.

Currently, comparing range data can only be achieved by utilizing both select and change events to store data in the global scope.

**Comment by Juveniel** [comment]
A temporary workaround for such scenarios can be achieved by subscribing to the Spreadsheet's editor change event:

```js
<script>
  var controller = spreadsheet._controller;
  controller.editor.unbind("change");
  controller.editor.bind("change", function (e) {
    console.log(e.range.value());
    console.log(e.value);
       
    // Execute custom change logic
         
    this.onEditorChange();
  }.bind(controller));
</script>
```

**Comment by veselints** [comment]
The new Spreadsheet `changing` event provides the new values before they are populated in the widget cells. It is preventable, so it allows the developer to stop the change if the new values do not meet her requirements: https://docs.telerik.com/kendo-ui/api/javascript/ui/spreadsheet/events/changing
