### ISSUE TITLE
Add typescript definitions for Vue modules

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4235]
### Bug report

Kendo UI wrappers for Vue are missing typescript definition files. Therefore, modules cannot be properly loaded.

### Reproduction of the problem

The issue can be reproduced by creating a starter template with ASP.NET Core by running the `dotnet new vue` command from the CLI (dotnet new --install Microsoft.AspNetCore.SpaTemplates::*).

### Current behavior

A warning is displayed when importing the Kendo modules.

### Expected/desired behavior

Definition files should be available in order to use the Vue wrappers with typescript.

### Workaround

1) Install a package e.g kendo-dateinputs-vue-wrapper

2) Create an `index.d.ts` file in `node_modules/kendo-dateinputs-vue-wrapper/dist/npm` folder

3) Export the required modules:
```ts
export function Calendar(): any
export function KendoDateinputsInstaller(): any
...
```
4) Specify the `typings` option in the package.json file (`node_modules/kendo-dateinputs-vue-wrapper`)
```
  "typings": "./dist/npm/index.d.ts",
```
5) Add alias for vue in webpack.config.js 
```js
resolve: {
  extensions: [ '.js', '.ts' ],
  alias: {
    vue: 'vue/dist/vue.js'
  }
}
```

### Environment

* **Kendo UI version:** 2018.2.504
* **Browser:** [all]

**Comment by Iankodj** [comment]
The d.ts files are published through the dev channel.
