### ISSUE TITLE
Active element is not blurred on Tab key pressed in IE

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4239]
### Bug report

In MVVM scenario when disabling a button on a change of a ViewModel field the keepInTrap functionality allows the button to be focused. This behavior is only reproducible in IE 11.

### Reproduction of the problem

[The issue can be reproduced on the following Dojo](https://dojo.telerik.com/iNUTejOr/5):

* Focus the first input and type a letter in IE
* Press "Tab"

### Current behavior

The disabled element is focused.

### Expected/desired behavior

The correct behavior is to blur the active one, thus allowing the collection of the focusableElements within a popup to be updated.

### Environment

* **Kendo UI version:** 2018.2.504
* **Browser:** [IE 11]

**Comment by Juveniel** [comment]
Currently, this can be bypassed by overriding the _keepInTrap() method as follows:
```js
<script>
  kendo.ui.Popup.TabKeyTrap.fn._keepInTrap = function (e) {
    if (e.which !== 9 || !this.shouldTrap() || e.isDefaultPrevented()) {
      return;
    }
    document.activeElement.blur();
    var elements = this._focusableElements();
    var sortedElements = this._sortFocusableElements(elements);
    var next = this._nextFocusable(e, sortedElements);
    this._focus(next);
    e.preventDefault();
  }
</script>
```

**Comment by zdravkov** [comment]
The provided workaround has bags described in the ticket - 1168335

**Comment by Iankodj** [comment]
Using the above workaround is indeed inappropriate. The main reason for the behavior described is not related to the Popup's logic, but to the way Kendo MVVM is handling the value binder. 

Generally, the value binder depends on the change event, which is fired on bluring the input. Thus, the enabled state of the button is changed after is being focused (under any browser). 

The solution here would be to have the value binder depend on the input event, which will fire change to  the observable during input event (which is triggered before change). That way the button will be disabled before input is blurred. 

This solution, however, will lead to a breaking change for current usages of the value binder (which is used by almost all editing templates in the Kendo widgets). Thus, I am not sure that such a change is reasonable enough. 

That said, in my opinion, in such cases it would be a much better option to have a [custom binder](https://docs.telerik.com/kendo-ui/framework/mvvm/bindings/custom) that would satisfy all demands. 

Here you are a dojo example as well: https://dojo.telerik.com/iNUTejOr/15

And the code of the custom binder that is used for the case: 

```
        kendo.data.binders.syncValue = kendo.data.Binder.extend({
          init: function(element, bindings, options) {
            kendo.data.Binder.fn.init.call(this, element, bindings, options);

            var that = this;

            $(that.element).on("input", function() {
              that.change();
            });
          },
          refresh: function() {
            var that = this,
                value = that.bindings["syncValue"].get();

            $(that.element).val(value);
          },
          change: function() {
            var value = this.element.value;
            this.bindings["syncValue"].set(value);

          }
        });
```
