### ISSUE TITLE
Radio button 'checked' binding do not work if you set value to null.

### ISSUE THREAD

**Issue by mkurayan** [telerik/kendo-ui-core#4240]
### Bug report

Radio button 'checked' binding do not work if you set value to null.

This row will not affect radio button "checked" state
` this.set("group", null);`

This row will affect radio button "checked" state
` this.set("group", "");`

I cannot save snippet in dojo.telerik.com, so here is file with full code.
[Kendo UI Snippet.zip](https://github.com/telerik/kendo-ui-core/files/2026575/Kendo.UI.Snippet.zip)

Dojo example: https://dojo.telerik.com/ACEHUquY

**Comment by Stamo-Gochev** [comment]
@mkurayan After the fix, setting null value will reset the checked state to "false" as it is done with the checkbox/select elements.
