### ISSUE TITLE
Allow updating of the initial files with setOptions method or a public method

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4241]
Allow the update of the initial files property with setOptions method or some public method.

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Juveniel** [comment]
Fixed with https://github.com/telerik/kendo-ui-core/issues/5746
