### ISSUE TITLE
Aria-Label is not evaluated on the wrapper in AngularJS scenario

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4253]
### Bug report
https://dojo.telerik.com/eJehIfAv/2
### Reproduction of the problem
Inspect the rendering of the wrapper element

### Current behavior
aria-label={{label}}

### Expected/desired behavior
aria-label=test

ticket: 1168531 
### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all ] 

Workaround:
    $scope.$on("kendoRendered", function (e) {
               if ($scope.dropdown) {
                 $scope.dropdown.wrapper.attr("aria-label", $scope.dropdown.element.attr("aria-label"));
               }
           })

**Comment by nenchef** [comment]
As with the end of life of AngluarJS, we plan no further enhancements or fixes in the suite:
https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c
