### ISSUE TITLE
Vue Grid Export to Excel is not working

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4259]
### Bug report

https://plnkr.co/edit/LB0dIr4btYSKblk9DL3X?p=preview

### Reproduction of the problem
Click the excel export button

### Current behavior
nothing is exported

### Expected/desired behavior
Exported file is expected

### Environment

* **Kendo UI version:** 2018.2.516
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by zdravkov** [comment]
We need to add the 'jszip' script in order to have the export working correctly:

>     <script src="https://kendo.cdn.telerik.com/2018.2.516/js/jszip.min.js"></script>

Here is working plunk - https://plnkr.co/edit/LB0dIr4btYSKblk9DL3X?p=preview

**Comment by kamaldeepb** [comment]
I am using the jszip.min.js script, yet the export file is not getting created using kendo ui Vue grid. can you help further?

**Comment by kamaldeepb** [comment]
despite of using the js file you mentioned, grid is still not generating export file. I can see data in "excelExport" method, but no file is created
Kendo grid configuration is:
 <kendo-grid :height="300"
                  :data-source-ref="'ds'"
                  :toolbar="['create','excel']"
                  :excel-filterable="true"
                  :excel-all-pages="true"
                  :excel-export="excelExport"
                  :column-menu="true"
                  :pageable='true'
                  :editable="'inline'"
                  :selectable="true"
                  :sortable-mode="'multiple'"
                  :sortable-allow-unsort="true"
                  :resizable="true"
                  :filterable="true"
                  :dataBinding="onDataBinding"
                  :dataBound="onDataBound">

 methods: {
      excelExport: function (e) {
        console.log('excelExport')
        console.log(e.data);
      },
      requestStart: function (e) {
        console.log('RequestStart: ' + e.type)
      },
      requestEnd: function (e) {
        console.log('RequestEnd: ' + e.type)

      }
}

**Comment by zdravkov** [comment]
Would you please elaborate a little bit by sharing a plunker or update working the one from my previous reply so we could investigate the issue deeper?

**Comment by blueTeddy** [comment]
**in main.js:**
// Kendo Grid Export support
import 'jszip/dist/jszip.js'


**Grid configuration is below:**
<kendo-grid ref="grid"
                  :height="300"
                  :data-source-ref="'ds'"
                  :toolbar="['create','excel']"
                  :excel-filterable="true"
                  :excel-all-pages="true"
                  :excel-export="excelExport"
                  :column-menu="true"
                  :pageable='true'
                  :editable="'inline'"
                  :selectable="true"
                  :sortable-mode="'multiple'"
                  :sortable-allow-unsort="true"
                  :resizable="true"
                  :filterable="true"
                  :dataBinding="onDataBinding"
                  :dataBound="onDataBound">
        <kendo-grid-column :command="['edit','destroy']" title="&nbsp;" width="250px"></kendo-grid-column>
        <kendo-grid-column field="focode" title="FOCode" :menu="false" :filterable-multi="true" :filterable-search="true"></kendo-grid-column>
        <kendo-grid-column field="foname" title="FOName" :filterable-multi="true" :filterable-search="true"></kendo-grid-column>
        <kendo-grid-column field="description" title="Description" :filterable-multi="true" :filterable-search="true"></kendo-grid-column>
        <kendo-grid-column field="border" title="Border" :filterable-multi="true" :filterable-search="true"></kendo-grid-column>
        <kendo-grid-column field="borderBit" title="BorderBit" :filterable-multi="true" :filterable-search="true"></kendo-grid-column>
        <kendo-grid-column field="active" title="Active" :width="120" :editor="customBoolEditor1" :filterable-multi="true" :filterable-search="true"></kendo-grid-column>
      </kendo-grid>

**The methods:**
excelExport: function (e) {
        console.log('excelExport')
        console.log(e.data);
      }

"excelExport" shows me the data on console, but export file is not being created.

**Comment by blueTeddy** [comment]
I also used 'https://demos.telerik.com/kendo-ui/service/Products'" to confirm if there is a problem with the datasource I was using, but using this example datasource, is also not generating export. 

**in main.js:**
// Kendo Grid Export support
import 'jszip/dist/jszip.js'

**in .Vue**
<template>
  <div id="vueapp">
    <div class="vue-app">
    <kendo-datasource ref="remoteDataSource"
                      :transport-read-url="'https://demos.telerik.com/kendo-ui/service/Products'"
                      :transport-read-data-type="'jsonp'"
                      :transport-read-type="'GET'"
                      :transport-update-url="'https://demos.telerik.com/kendo-ui/service/Products/Update'"
                      :transport-update-data-type="'jsonp'"
                      :transport-update-type="'GET'"
                      :schema-model-id="'ProductID'"
                      :schema-model-fields="schemaModelFields"
                      :page-size='20'>
    </kendo-datasource>

    <kendo-grid :height="600"
                :data-source-ref="'remoteDataSource'"
                :pageable='true'
                :editable="'inline'"
                  :toolbar="['create','excel']"
                  :excel-filterable="true"
                  :excel-all-pages="true"
                  :excel-export="excelExport">
      <kendo-grid-column field="ProductName"></kendo-grid-column>
      <kendo-grid-column field="UnitPrice" title="Unit Price" :width="120" :format="'{0:c}'"></kendo-grid-column>
      <kendo-grid-column field="UnitsInStock" title="Units In Stock" :width="120"></kendo-grid-column>
      <kendo-grid-column :command="['edit']" title="&nbsp;" width="250px"></kendo-grid-column>
    </kendo-grid>
  </div>
 </div>
</template>

<script>
export default {

    data: function () {
      return {
 schemaModelFields: { // For sample code from kendo site
          ProductID: { editable: false, nullable: true },
          ProductName: { validation: { required: true } },
          UnitPrice: { editable: true, type: 'number', validation: { required: true, min: 1 } },
          UnitsInStock: { type: 'number', validation: { min: 0, required: true } }
        }
}}
,
    methods: {
      excelExport: function (e) {
        console.log('excelExport')
        console.log(e.data);
      }
}
}
</script>

**Comment by zdravkov** [comment]
Hi @blueTeddy , 

In case you are loading the jszip from npm you can follow these steps:
1: npm i jszip
2: import JSZip from 'jszip'
3: window.JSZip = JSZip ( this can be done in 'created' Vue hook for example)

Hope this information will be helpful.
Regards,
Plamen

**Comment by blueTeddy** [comment]
I installed jszip using npm. 

**main.js has** 
// Kendo Grid Export support
import JSZip from 'jszip/dist/jszip.js'

**Created function updated per your suggestion, yet no change in the result.**
 created() {
      console.log('In Created')
      window.JSZip = JSZip
      //this.getFieldOffices() // Used for b-table
    }

**Comment by zdravkov** [comment]
I am attaching a sample project that worked correctly at my side here.
[test-grid-export.zip](https://github.com/telerik/kendo-ui-core/files/2179067/test-grid-export.zip)

**Comment by blueTeddy** [comment]
Thank you so much!! The trick was to import JSZIP in .vue rather than main.js.

**Comment by blueTeddy** [comment]
How do I translate this kendo template from jquery to vue.js?

 <script type="text/x-kendo-template" id="gridHeaderServerExportTemplate">

      <div class="grid-export-excel-button">

        <a href="\\#" class="k-button k-button-icontext k-grid-excel" title="Export to Excel" onclick="$dashboard.reports.ExportToExcelServer(reportType)"><span class="k-icon k-i-file-excel"></span>Export to Excel</a>

      </div>

      <div class="grid-reset-filter-button">

        <a href="\\#" class="k-button k-button-icontext filter-clear"title="Clear Filters"><span class="k-icon k-i-filter-clear"></span>Clear Filters</a>

      </div>

    </script>



I need to create 'onclick' for each of these buttons. For 'Clear Filter', I need to pass in the grid whose data filter needs to be cleared out. How do I do that?

Thanks!

________________________________
