### ISSUE TITLE
Links keep their initial order, when column in Spreadsheet it sorted

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4261]
### Bug report

Links keep their initial order when a column in Spreadsheet it sorted

### Reproduction of the problem

repro dojo:
[http://dojo.telerik.com/exavUZEy](http://dojo.telerik.com/exavUZEy)

Sort the Priority column A-Z

### Current behavior
Links keep their initial order when a column in Spreadsheet is sorted

### Expected/desired behavior
Linked-value, should be correctly sorted along with its text

### Environment

* **Kendo UI version:** 2018.2.516
* **Browser:** [all]

**Comment by mparvanov** [comment]
The issue is still reproducible:

http://take.ms/IWWwR

**Comment by mparvanov** [comment]
The issue appears to be fixed with the latest source, closing it as resolved.
