### ISSUE TITLE
Spreadsheet throws an error, when attempting to load a sheet that contains file with cell that has background color set from excel

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4263]
[testcolors.xlsx](https://github.com/telerik/kendo-ui-core/files/2047734/testcolors.xlsx)
### Bug report

Spreadsheet throws an error when attempting to load a sheet that contains a file with a cell that has a background colour set from excel:

Uncaught Error: Cannot parse color: #18e618e618e6

Reason for the bug: 
Hexadecimal value is not properly converted to RGBA. 

### Reproduction of the problem
Use the attached file for replication.

### Current behavior
A js error is thrown, when attempting to convert the background color format

### Expected/desired behavior
no js error should be thrown

### Environment

* **Kendo UI version:** 2018.2.516
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible with R3 2018 (2018.3.911) and R3 2018 SP1 (2018.3.1017).
The background color is loaded as expected.
