### ISSUE TITLE
Hidden columns are displayed after setting the options with minScreenWidth in the Grid

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4265]
### Bug report

Hidden columns are displayed after setting the options with minScreenWidth in the Grid.

May have common grounds with #3612 and #3972

Reported in: 1166018

### Reproduction of the problem

http://dojo.telerik.com/OpAHANEH

1. hide a column
1. Save State
1. Load State

### Expected/desired behavior

The hidden columns are not displayed after setting the options.

### Environment

* **Kendo UI version:** 2018.2.516
* **Browser:** [all]

**Comment by Stamo-Gochev** [comment]
The current behavior is due to how `minScreenWidth` is implemented, which is described in the documentation:

https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/columns.minscreenwidth

**Comment by PreslavKozovski** [comment]
To overcome this behavior, use the approach from the following KB article:

https://docs.telerik.com/kendo-ui/knowledge-base/grid-setoptions-hide-columns
