### ISSUE TITLE
Input text is not visible in Combobox in Flat theme

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4266]
### Bug report
When Flat theme is used for ComboBox, the text in the input field is not visible.

### Reproduction of the problem
1. Open the [Demo](https://demos.telerik.com/kendo-ui/combobox/index)
2. Try to select an item

### Current behavior
The item is selected correctly, but the text is not visible as the background color and the text color are the same. 

### Expected/desired behavior
The text in  combobox should be visible

### Workaround
Add color to the text in the ComboBox input
`<style>
    .k-combobox .k-input{      
      color: #10c4b2;
    }
  </style>`

### Environment

* **Kendo UI version:** 2018.2.516
* **Browser:** [all ]

**Comment by joneff** [comment]
Artifact from https://github.com/telerik/kendo/issues/8433
