### ISSUE TITLE
Footer data row is not visible if the page is loaded in horizontal orientation IPhone 7

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4271]
### Bug report

https://runner.telerik.io/fullscreen/IqiseTiK

### Reproduction of the problem
1:Open in fullscreen
2: hard refresh page

### Current behavior
the footer is not visible 

### Expected/desired behavior
the footer should be visible

### Environment

* **Kendo UI version: 2019.2.619
* **jQuery version:** x.y
* **Browser:** [Safari XX |  iOS XX WKWebView ] 

[footer-bug-image.zip](https://github.com/telerik/kendo-ui-core/files/2047506/footer-bug-image.zip)

**Comment by magdalenaan** [comment]
The Kendo UI Mobile LESS themes are[ officially deprecated ](https://www.telerik.com/blogs/future-plans-telerik-kendo-ui-less-themes)with R1 2022.
