### ISSUE TITLE
column filterable prop throws a warning when object is passed as a parameter

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4273]
### Bug report

Gird's column filterable prop generates a warning when an object is passed as a parameter.

### Reproduction of the problem
```html
<kendo-grid-column :filterable="{ cell: {enabled: false}}" field="ContactTitle" title="Contact Title"></kendo-grid-column>
```

### Current behavior

![image](https://user-images.githubusercontent.com/16972160/40662077-fe649e3a-635d-11e8-89f0-acb0c6013ac3.png)

### Expected/desired behavior

The filterable prop should accept both boolean and Object parameters.

### Environment

* **Kendo UI version:** 2018.2.516
* **Browser:** [all]

**Comment by aakashbashyal21** [comment]
I am getting the same warning on Kendo UI version: 2018.2.516. Is there any solution for the same warning?
