### ISSUE TITLE
footer typescript definition causes an error with boolean parameter

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4275]
### Bug report

According to [the official documentation](https://docs.telerik.com/kendo-ui/api/javascript/ui/calendar/configuration/footer), if false is set, the footer will not be rendered. However, due to wrong generation of the typescript definitions an error is being thrown ('Type boolean is not assignable to type String | Function').

### Reproduction of the problem

```ts
let cal = $("#calendar").kendoCalendar({
    footer: false
});
```

### Current behavior

![image](https://user-images.githubusercontent.com/16972160/40707102-5b0ee33a-63f8-11e8-8f29-f8f7c34f1091.png)

### Expected behavior

Boolean parameter should be assignable to the footer option of the Calendar.

### Environment

* **Kendo UI version:** 2018.2.516
* **Browser:** [all]

**Comment by ivanchev** [comment]
Duplicate to [4218](https://github.com/telerik/kendo-ui-core/issues/4218)
