### ISSUE TITLE
Tooltip property does not change title of Editor's Format tool

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#4281]
### Bug report
Tooltip property does not change title of Editor's Format tool.
It works for all other tools.

Workaround: set the tooltip through messages property
```
messages: {
    formatting: "Format the selected text"
}
```

### Reproduction of the problem
1. http://dojo.telerik.com/IRumURiq

### Current behavior
Hovering Format tool shows "Format" tooltip.

### Expected/desired behavior
Hovering Format tool shows "Format the selected text" tooltip.

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by veselints** [comment]
PR here: https://github.com/telerik/kendo/pull/10099
