### ISSUE TITLE
columns.hidden not hiding header in a Grid initialized from a table

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4283]
### Bug report

columns.hidden not hiding header in a Grid initialized from a table.

Reported in 1169716

### Reproduction of the problem

http://dojo.telerik.com/AqeRuqap

### Expected/desired behavior

https://dojo.telerik.com/IkabElAC/4

### Environment

* **Kendo UI version:** 2018.2.516
* **Browser:** [all]

**Comment by PreslavKozovski** [comment]
workaround: 
Add - style="display: none;" - to the th element of the desired columns.
https://dojo.telerik.com/IkabElAC/4

**Comment by matanasov** [comment]
The DoJo example provided in **Expected/desired behavior** is broken after the fix
