### ISSUE TITLE
Font name and font style are incorect after using backspace in IE

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#4287]
### Bug report

When using backspace to remove a line, the selection is not inside the applied inline styles. Thus, addition content added is not properly decorated. 

Ticket: 1170057

### Reproduction of the problem
https://demos.telerik.com/kendo-ui/editor/all-tools

1. Remove all content
1. Select a different font
1. Type some text
1. Add two empty paragraphs (Enter key twice)
1. Press backspace to remove the last line (see the font name is "inherited font")
1. Type some more text 

### Current behavior
Text is  not with the proper font name and size

### Expected/desired behavior
The font name and size to retain as defined

### Environment

* **Kendo UI version:** all
* **jQuery version:** all
* **Browser:** [ IE ]

**Comment by mparvanov** [comment]
The following internal regression scenario has been detected in non-IE browsers after the fix:
http://kendobuild-windows.openstack.progress.com/kendo-ui/editor/all-tools/
1. Remove all content
1. Select a different font
1. Type "test"
1. Add two empty paragraphs (Enter key twice)
1. Press backspace twice
1. type "test"

Expected HTML:
```
<p><span style="font-family: Georgia, serif;">﻿test</span></p><p><span style="font-family: Georgia, serif;">test﻿</span></p>
```
Actual HTML:
```
<p><span style="font-family: Georgia, serif;">﻿test</span></p><font face="Georgia, serif">test</font>
```
