### ISSUE TITLE
Fix demo and documentation for Upload Async 

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4288]
The current implementation in demos and documentation regarding the Upload Async doesn’t work
https://demos.telerik.com/aspnet-core/upload/async
https://docs.telerik.com/aspnet-core/helpers/html-helpers/upload

**Comment by mparvanov** [comment]
- [ ] The files should not be actually saved through the demo in order to avoid free space issues on the live server
- [ ] The commits need to be cherry picked into production so they will go live with the R2 2018 SP1
