### ISSUE TITLE
Allow Gantt TaskTemplate to be defined as directive in AngularJS scenario, similarly as the EventTemplate for the Scheduler could be defined

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4289]
Allow Gantt TaskTemplate to be defined as directive in AngularJS scenario, similarly as the EventTemplate for the Scheduler could be defined:
```JavaScript
<div kendo-gantt k-options="ganttOptions">
  <span k-task-template class='custom-task'>{{dataItem.title}}</span>
  <button ng-click="testClick()">click</button>
</div>
```

Pass the controller scope to the template, so the click handler is properly attached to the button using the *ng-click* directive.

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
