### ISSUE TITLE
Unexpected multiple selected nodes in single selection DropDownTree with filtering

### ISSUE THREAD

**Issue by lampo1024** [telerik/kendo-ui-core#4293]
### Bug report
I do the demo at this page: https://demos.telerik.com/kendo-ui/dropdowntree/client-filtering

When I set the filter equals true of DropDownTree widget。At the very beginning, I select one node(eg. Tables & Chairs), and then enter some text in the filter input box(eg. "so"), the filter result node of the DropDownTree only left "Sofas", I select it, "Sofas" was selected. 

Finally, I remove the filter text(here is "so"), the problem comes out. "Tables & Chairs" and "Sofas" nodes were both selected and couldn't be click any more.

**Expected:** Only "Sofas" node appears as selected.
**Actual:** Both "Tables & Chairs" and "Sofas" nodes appear as selected.
![image](https://user-images.githubusercontent.com/6614183/41024467-01a783d0-6978-11e8-97f3-ed8065ca4a95.png)

### Environment:
Kendo UI version: 2018.2.516
Browser: All

**Comment by Dimitar-Goshev** [comment]
@zdravkov The described scenario is now fixed, but there is another one, which is not addressed:
1. https://demos.telerik.com/kendo-ui/dropdowntree/client-filtering
2. Expand dropdown and select Tables and Chairs.
3. Expand and type s in the filter input.
4. Select Sofas.
5. Clear Sofas through the clear button.
6. Expand dropdown and delete s in the filter input.

**Expected:** no nodes selected.
**Actual:** Tables and Chairs is selected.
