### ISSUE TITLE
Pasting long text in the MultiSelect's input displays a horizontal scroll bar

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4294]
### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/Eruwuhuc/3)example. [Screencast](https://www.screencast.com/t/RGyr27Js). 

1. Copy some text in the clipboard
2. Focus the MutliSelect, press Ctrl + V and hold the keys pressed until a horizontal scroll bar appears. 

Workaround:
```
.k-multiselect>span {
  overflow-x: hidden !important;
}
```

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by eyupyusein** [comment]
Not reproducible.
