### ISSUE TITLE
Kendo Drawing does not properly draw Bar Chart with long category labels in Firefox

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4299]
### Bug report

Kendo Drawing does not properly draw Bar Chart with long category labels in Firefox. The labels of the axis overlap the Chart plot area.

### Reproduction of the problem
Run [the following Dojo](https://dojo.telerik.com/APiVoMeH/7) and export the Chart by clicking the button.

### Current behavior
![test](https://user-images.githubusercontent.com/3431388/41083849-f1c079ea-6a3a-11e8-8d02-96ca448033d8.png)

### Expected/desired behavior
Labels should not overlap

### Environment

* **Kendo UI version:** 2018.2.516
* **Browser:** [ Firefox 60 ]

**Comment by MilenaCh** [comment]
Works properly with Firefox version 64.0
