### ISSUE TITLE
ImageBrowser Thumbnail implementation throws "InvalidOperationException"

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4302]
### Bug report

The current implementation of the ImageBrowser's Thumbnail option throws the following exception:

### Reproduction of the problem

The issue can be reproduced with [the File and ImageBrowser Demo for ASP.NET Core](https://demos.telerik.com/aspnet-core/editor/imagebrowser) by configuring the Thumbnail option( .Thumbnail("Thumbnail", "ImageBrowser")).

### Current behavior

![image](https://user-images.githubusercontent.com/16972160/41156166-693adc74-6b29-11e8-937f-2dc3cf84f9c2.png)

### Expected/desired behavior

The Thumbnail should correctly return the image path.

### Environment

* **Kendo UI version:**2019.1.115
* **Browser:** [all]

**Comment by Juveniel** [comment]
Further investigating the issue shows that the described error is being thrown as the default Thumbnail implementation of the ImageBrowserController for ASP.NET Core returns null. This is the case, as the System.Drawing library that was previously used in Telerik UI for ASP.NET MVC is not currently available in ASP.NET Core. Thus in order to generate a preview for the uploaded images, a third-party library should be used. Additional information can be found in the following article:

* [https://devblogs.microsoft.com/dotnet/porting-to-net-core/](https://devblogs.microsoft.com/dotnet/porting-to-net-core/)

When the .Thumbnail() option is configured, a request is being sent to the remote end-point that contains the image path in the request header. The service is expected to respond with an image file for the thumbnail. Thus, to provide an implementation for the Thumbnail end-point, the Thumbnail method should be overrided as follows:
```cs
public override IActionResult Thumbnail(string path)
{
  ...
  return File(thumbnail, mimeType);
}
```

We will also add a note in [the ImageBrowser Documentation for ASP.NET Core ](https://docs.telerik.com/aspnet-core/html-helpers/editors/editor/image-browser#image-browser)  regarding this limitation.

Taking the above into consideration, I am closing the issue.

**Comment by cyroul82** [comment]
Hello,

I had the same issue, and I overrided the Thumbnail method  as follow :
`
public override IActionResult Thumbnail(string path) {
      const string contentType = "image/png";
      var physicalPath = Path.Combine(_appConfig.AbsoluteUserFilesPath, "Images", path);
      Image image = Image.FromFile(physicalPath);
      Image thumb = image.GetThumbnailImage(80, 80, () => false, IntPtr.Zero);
      using(var ms = new MemoryStream()) {
        thumb.Save(ms, ImageFormat.Png);
        return File(ms.ToArray(), contentType);
      }
    }
`
It worked, it might help someone 
.

**Comment by ngoctruy87** [comment]
thank @cyroul82 it looks great!
