### ISSUE TITLE
Expose SplitButton in public API

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4305]
### Description

Expose the SplitButton as a separate widget and describe its options and methods in the public API.

* Improve adding/removing items from the menuButtons list.

**Comment by cas4** [comment]
This is a must.  I'm not sure why there is not an exposed way to manipulate toolbar buttons (not just a SplitButton) after it has been rendered.  For example, changing the URL on the fly does not appear doable without using some internal methods.

**Comment by Dimitar-Goshev** [comment]
@cas4 This scenario is logged as a separate issue here: https://github.com/telerik/kendo-ui-core/issues/4538

**Comment by Iankodj** [comment]
Closing in favour of: https://github.com/telerik/kendo/issues/15156.
