### ISSUE TITLE
Pointer cursor is displayed when hovering over disabled ComboBox button

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4311]
### Bug report
When ComboBox is disabled and we hover over the open button, a pointer cursor is displayed.
It is possible to click and focus the button of a disabled ComboBox.
It is not possible to click the disabled arrow icon, but the rest of the button is not styled properly.

### Reproduction of the problem
[Dojo example](https://dojo.telerik.com/OBUdasET/3)
1. Hover the ComboBox button away from its center - the cursor will become pointer.
In addition click the button.

### Current behavior
The cursor becomes pointer and the button is be focused on clicking. The focusing is visible in Chrome, where the button gets blue border:
![image](https://user-images.githubusercontent.com/6614183/31549448-e70c78dc-b036-11e7-8557-fad9b8bea075.png)

### Expected/desired behavior
The cursor should not become pointer and the button should not be focused on clicking.

Workaround - [Dojo](https://dojo.telerik.com/OBUdasET/2)
```
  <style>
    .k-combobox .k-state-disabled .k-select {
      cursor: default;   
    }
  </style>
```

### Environment

* **Kendo UI version:** 2018.2.516
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
This issue is fixed in [R1 2019 (2019.1.115)](https://dojo.telerik.com/@Dimitar-Goshev/ABiSuxuj) and newer versions.
