### ISSUE TITLE
Create scenario with DropDownTree in Grid editor template when it is with checkboxes

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4314]
It will be similar to the one created for multiselect - https://docs.telerik.com/kendo-ui/controls/data-management/grid/how-to/Editing/use-multiselect-as-custom-editor

The scenario should be similar to this one - http://dojo.telerik.com/@zdravkov/UZOlAdAk

**Comment by Dimitar-Goshev** [comment]
The scenario from the [following snippet](http://dojo.telerik.com/UsilAhiq) will work as expected with R2 2018 SP1.
