### ISSUE TITLE
kendo-ui-core#^2016.1.322 bower to npm migration

### ISSUE THREAD

**Issue by uMtMu** [telerik/kendo-ui-core#4319]
Hi, i am trying to migrate from bower to npm but 
- bower install kendo-ui-core#2016.1.322
- npm install kendo-ui-core#2016.1.322 not working because of diffrent repositories. File structure is different. 

How can i migrate to npm from bower?

**Comment by matanasov** [comment]
@uMtMu 

**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !
