### ISSUE TITLE
Reordering/locking multi-column headers are not changing the header/table data

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4320]
### Bug report

Reordering/locking multi-column headers are not changing the header/table data

### Reproduction of the problem

1. http://dojo.telerik.com/ijeTAcuq
2. Check the "Location" column after the timeout

### Expected/desired behavior

Reordering/locking multi-column headers are working as expected.

### Environment

* **Kendo UI version:** 2018.2.516
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Duplicate item - https://github.com/telerik/kendo-ui-core/issues/2616
