### ISSUE TITLE
Row not Removed from Grid on Cancel when Server Grouping is enabled

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#4323]
### Bug report

Reported in ticket 1171782 

### Reproduction of the problem

Project in ticket. The behaviour can be reproduced with the following options enabled:

- editable grid
- add a group to the data sourece
- create a record
- click `cancel`
- item remains in the DOM

### Current behavior

The newly created item is not removed from the DOM

### Expected/desired behavior

The newly created item should be removed from the DOM

### Workaround

Attach an event handler to the [`cancel`](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/events/cancel) event of the grid and use the dataSource [`cancelChanges()`](https://docs.telerik.com/kendo-ui/api/javascript/data/datasource/methods/cancelchanges) method to cancel the item which is not removed:

```
@(Html.Kendo().Grid<TestModel>()
     .Name("ModelGrid")
     .Events(ev=>ev.Cancel("onCancel"))
)
<script>
    function onCancel(e) {
       e.sender.dataSource.cancelChanges();
    }
</script>
```

### Environment

* **Kendo UI version:** 2018.2.516

**Comment by matanasov** [comment]
The scenario from the ticket still does not work - one item is still added on Cancel. 
Subsequent items are not added though:

![untitled](https://user-images.githubusercontent.com/5861835/46147700-e17c2200-c26e-11e8-8739-cb81bdb541c6.png)

**Comment by danigrosu** [comment]
I can confirm the scenario, I'm using 2019.3.917 version.
