### ISSUE TITLE
Checkbox alignment change might need revision

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4324]
### Bug report

A change in the **k-checkbox-label** vertical-alignment (current value is **top**) might need revision, because the previous value (**text-top**) is more suitable in certain scenarios  
 The change is introduced in version 2018.1.221 ([commit](https://github.com/telerik/kendo/commit/9836c90e2cfbf72edd23b09dd9e1f47d073d7643#diff-764164880047d632727199507e2d4206)). 

### Current behavior
https://dojo.telerik.com/oXUPiLuX/4

### Expected/desired behavior
https://dojo.telerik.com/oXUPiLuX/2

* **Kendo UI version:** 2019.3.1023

**Comment by Juveniel** [comment]
Not reproducible with latest release [https://dojo.telerik.com/oXUPiLuX/8](https://dojo.telerik.com/oXUPiLuX/8)
