### ISSUE TITLE
Revise Tooltip callout position calculation change

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4328]
### Bug report
Tooltip callout Js position calculation removed in version 2018.2.516 ([commit](https://github.com/telerik/kendo/commit/67938183ee0b0e18d2619de2926f6dd462403554#diff-6be8732e187b204f16cc5f1c684f063b)). 

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/uTOBATiL) example.

### Current behavior
The callout is positioned in the middle of the Tooltip. 

### Expected/desired behavior
The callout is positioned according to the position of the element the Tooltip is shown for. 

### Environment

* **Kendo UI version:** 2018.2.516
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by IvanDanchev** [comment]
Another scenario the issue is exhibited in:  https://dojo.telerik.com/OyOJAbuj/2
When Tooltip position is set to top and there is not enough space for it, it is displayed below the target but its callout is also displayed at the bottom of the Tooltip instead of at the top.

**Comment by Jekata** [comment]
The problem also affects the tooltip of the RadMap for UI for ASP.NET AJAX wrapper.
