### ISSUE TITLE
Add support for multiple column headers with the kendo-grid-column component

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4331]
### Enhancement

Allow nesting of kendo-grid-column components in order to be able to specify multi-column headers for the Grid (similar to [the following Grid Demo](https://demos.telerik.com/kendo-ui/grid/multicolumnheaders) with jQuery.)

**Comment by zdravkov** [comment]
The described behavior is currently supported with our Native Vue Grid - https://www.telerik.com/kendo-vue-ui/components/grid/columns/headers/ and we recommend using it when such scenarios are needed.
