### ISSUE TITLE
Scrollable detection is off by one pixel

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4335]
### Bug report

Scrollable detection is off by one pixel and is not triggered when tabs are overflowing by 1 pixel.

### Reproduction of the problem

The issue can be observed on [the following Dojo example](http://dojo.telerik.com/uBipuxEk/2).

You will notice that the last tab is displayed on a new line and the scrollable functionality is not working. If we decrease the TabStrip container width by one pixel, the functionality will be working as expected (.fixedContent { width: 394px; })

### Current behavior

The scrollable functionality of the TabStrip is not activated.

### Expected/desired behavior

The scrollable functionality should be triggered when tabs cannot fit in the TabStrip width.

### Environment

* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by Juveniel** [comment]
Reported in TicketID: 1167565

**Comment by mparvanov** [comment]
Not reproducible with 2019.3.1023.
