### ISSUE TITLE
Unable to drag Window over an iframe, e.g. over Editor widget 

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4336]
### Bug report
When there is Window and iframe on the same page (Window and Editor as Editor uses iframe), Window dragging is not working properly. While dragging, the Window freezes. Sometimes the Window continue to be draggable, although left mouse button is released.

### Reproduction of the problem
1. Open the [Dojo example](https://dojo.telerik.com/upIleBoW)
2. Open the Window from the button on the top
3. Click on Window's title bar close to its outer borders and start to drag the Window, moving the mouse out of the window borders.

NOTE: the same behavior is observed, when using a simple iframe, not an Editor - [DOJO](https://dojo.telerik.com/ENIpiRoP)

### Current behavior
When the mouse goes over the Editor's iframe, the Window freezes. It still can be moved although the left mouse button is released. ([screencast](https://www.screencast.com/t/pMRe7pe3q))

### Expected/desired behavior
The Window should not freeze. The behavior should be the same, no matter if there is iframe (Editor) on the page. 

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** all

**Comment by Juveniel** [comment]
The iframe events interfere with the Window drag and resize events, thus leading to the observed behavior. To workaround the issue, there are two possible approaches:

* Utilize [the Window modal option](https://docs.telerik.com/kendo-ui/api/javascript/ui/window/configuration/modal) when we know there are iframes on the page. This will add an overlay behind the Window when it is opened, thus preventing the issues with resizing and dragging. 

* Utilize [the Window resize/drag events](https://docs.telerik.com/kendo-ui/api/javascript/ui/window#events) to find every iframe on the page and programmatically add an overlay above the iframes to prevent their events from triggering, thus eliminating the issue. Refer to [the following Knowledge Base article](https://docs.telerik.com/kendo-ui/knowledge-base/window-drag-resize-over-iframe) that demonstrates this approach.

Taking the above into consideration, the recommended approach is to utilize the modal option. However, in case you need to drag/resize a non-modal Window over iframes on the page, then the second approach demonstrated in the above-linked Knowledge Base article can be used.

Closing the issue.
