### ISSUE TITLE
Adjust the Excel Export to work with the new Chrome 67 Date standard

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#4338]
### Bug report

Reported in Tickets with IDs: 1172569, 1172775, 1171951 

### Reproduction of the problem

- Using Chrome 67, dates are exported with seconds offset which is different dependent on the timezone even though they have the correct time in the workbook 
-  [Dojo](http://dojo.telerik.com/@bubblemaster/aWixOvUF)

### Current behavior

[https://stackoverflow.com/questions/50814643/chrome-67-date-vs-chrome-66-date](https://stackoverflow.com/questions/50814643/chrome-67-date-vs-chrome-66-date)
[https://stackoverflow.com/a/50841568](https://stackoverflow.com/a/50841568)
[https://stackoverflow.com/a/50610030](https://stackoverflow.com/a/50610030)

### Expected/desired behavior

The dates should not be modified when exporting in Chrome 67

### Environment

* **Kendo UI version:** 2018.2.620
* **Browser:** Chrome 67

**Comment by yamilelias** [comment]
@matanasov, you closed this issue with no other attachments. Right now, we are experiencing this issue using the Excel export function. Which was the resolution to this issue?

**Comment by hassan369** [comment]
@matanasov could you please provide an update on the resolution of the issue related to the Excel export in Chrome? Where can we find the solution?"
