### ISSUE TITLE
Tapping an option does not select it with disabled animation option on Windows touch devices

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4340]
### Bug report

When animation is disabled (close animation in particular), the DropDownList can be opened/closed, but no selection could be made by tapping an option. 

The issue is reproducible on Microsoft Surface devices with the Chrome browser.

### Reproduction of the problem

The issue can be reproduced with [the following Dojo example](http://dojo.telerik.com/UwOYEtUc/16)

### Current behavior

When the DropDownList is opened and an item is tapped, it is not being selected. 

### Expected/desired behavior

The tapped item should be selectable.

### Environment

* **Kendo UI version:** 2018.2.620
* **jQuery version:** 3.1.1
* **Browser:** [Chrome | Mobile Chrome XX]

**Comment by mparvanov** [comment]
Not reroducible with notebook Lenovo touch.

**Comment by Dimitar-Goshev** [comment]
Not reproducible on Surface with Chrome 77. Tested with the reported Dojo, as well as with [Dojo with jQuery 3.1.1](https://dojo.telerik.com/@Dimitar-Goshev/uKasaWaq) and [Dojo with jQuery 3.1.1 + Kendo UI 2019.3.1023](https://dojo.telerik.com/@Dimitar-Goshev/eHuYOkUV)
