### ISSUE TITLE
Gantt treelist and timeline rows misaligned (IE)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4345]
### Reproduction of the problem
[Screencast](https://monosnap.com/file/hsF4tRWmcm8dRwf1pgB767znQUaJh8). Reproducible in the [demos](https://demos.telerik.com/kendo-ui/gantt/index). 
1. Scroll down the Gantt view and select a one of the last tasks in the widget's timeline.

### Current behavior
Treelist and timeline get misaligned.

### Expected/desired behavior
Treelist and timeline alignment is not affected by task selection.  

### Environment
* **Kendo UI version:** 2020.2.617
* **Browser:** IE11

**Comment by Juveniel** [comment]
The misalignment issue can also be reproduced with small font-size and without the need to select a task: [Dojo example](https://dojo.telerik.com/UkujIQeP).
