### ISSUE TITLE
Expanding results in incorrect cell content formatting

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-ui-core#4353]
### Bug report

Expanding items results in incorrect formatting of data - the number fields are formatted as currency and vice versa.

Reported in [Ticket ID: 1174421](https://admin.telerik.com/default.aspx?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=1174421)

A similar problem has been reported in [Ticket ID: 917709](https://admin.telerik.com/?Context=Support&Control=~/UserControls/Support/ThreadReply.ascx&ST=917709)
and fixed in https://github.com/telerik/kendo/issues/4292

### Reproduction of the problem
Dojo example: https://dojo.telerik.com/IbIcafoD

1. Expand "All Geographies"
2. On the line with "Alhambra" expand "All Products"
3. Expand "All Products" below "[DATE].[CALENDAR]".

### Current behavior

"Reseller Freight Cost" cell is not formatted as a number (should be as currency).
"Customer Count" cells are formatted as a currency (should be as a number).

### Expected/desired behavior
"Reseller Freight Cost" cell is formatted as a currency.
"Customer Count" cells are formatted as a number.

### Environment

* **Kendo UI version:** 2018.2.62
* **jQuery version:** 1.9.1
* **Browser:** [all |

**Comment by sspasova** [comment]
The issue is fixed. Tested with Kendo UI version 2023.3.1114. I am linking a working Dojo example -> https://dojo.telerik.com/IbIcafoD/4
