### ISSUE TITLE
Pasting Table from MS Word with column width set in percentage results in invalid col style

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4354]
### Bug report
Pasting Table from MS Word with column width set in percentage results in invalid col style. The col style width will be invalid in the following format: `<col style="width:25%px;" />`. Note that both the percent sign (`%`) and the text `px` are present.

### Reproduction of the problem
* Create a Table in MS Word;
* Configure at least one of its columns to be set in percentage;
* Select the table and copy it;
* Go to the [Editor index demo](https://demos.telerik.com/kendo-ui/editor/index) and paste the copied Table in the Editor;
* If you inspect the HTML in the Editor you will notice that the Table `<colgroup>` will contain improper configuration for its `<col>`s: `<col style="width:80%;">`

### Expected/desired behavior
The `width` should be present in percentage only (`%`).

### Environment
* **Kendo UI version:** 2018.2.620
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by veselints** [comment]
To workaround this issue you could implement a custom `pasteCleanup`:

```JavaScript
$("#editor").kendoEditor({
    pasteCleanup: {
        custom: function(html) {
    	    return html.replace(/%px/g, '%');
        }
     }
});
```

**Comment by Dimitar-Goshev** [comment]
Closing the issue due to inactivity.
