### ISSUE TITLE
Setting a custom filter widget for a boolean column does not work

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#4359]
### Bug report
Setting a custom filter widget for a boolean column does not work.

### Reproduction of the problem
1. Open the[ dojo ](http://dojo.telerik.com/oGowUDix).
3. Open the filter menu.

### Current behavior
Although a the filter of the column is configured to use custom widget the default template is displayed.

### Expected/desired behavior
The custom widget should be rendered in the filter menu.

### Environment

* **Kendo UI version:** 2018.2.620
* **Browser:** [all ]

**Comment by Xizario** [comment]
https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/columns.filterable.ui#columns.filterable.ui

**Comment by matanasov** [comment]
@gyankov 
This works well if the boolean values are set as strings - e.g. `value="false"`. However if the value is set like `value=false`, the negative text `No` can't be set.
Use this [dojo](http://dojo.telerik.com/@martinpz/UbeQIRoG)
