### ISSUE TITLE
Additional tools for adding rows/columns are shown on selecting the table in IE

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4361]
### Bug report
When a table cell in the Editor is focused additional tools, which allow adding rows/columns, appear in the widget's toolbar. Only in IE11 these tools appear on selecting a table even if a cell is not focused. 

### Reproduction of the problem
[Screencast](https://www.screencast.com/t/68qGxALxq9Yd). The issue is reproducible in the [demos](https://demos.telerik.com/kendo-ui/editor/index).
1. Create a table in the Editor.
2. Select the table without focusing a cell.
3. The additional tools appear. Clicking them throws a js exception. 

### Current behavior
Additional tools appear without focusing a cell.

### Expected/desired behavior
Additional tools appear only when a cell is focused. 

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** x.y
* **Browser:** [IE ]

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
