### ISSUE TITLE
List numbering is restarted on paste from Word in Internet Explorer

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#4368]
### Bug report

List numbering is restarted to 1 when pasting multi level lists from Word in Internet explorer to Kendo Editor.

The issue originates from the following issue: https://github.com/telerik/kendo-ui-core/issues/4212
Reported in Ticket ID: 1171895

### Reproduction of the problem
[Lists.docx](https://github.com/telerik/kendo-ui-core/files/2188720/Lists.docx)
Paste the content of the document to Kendo editor

### Expected/desired behavior
The numbering is kept
```
1.	Xxxxxxxx xxxxxxxx xxxxxxxxxxxx (Xxxxxxxx xxxxx) – Xxxxx xxxxw xxxxx – Xx yxx xxxxx wx xxvx xxy xxxxx xxxxxxxx xxxxxxxxxx xxxxxxxxxxxx?
•	Xxxxxx Xxxxx				
•	Xxxxxx xxxxx xxxxy xxxxx				
•	Xxxxxxxx Xxxxxxx Xxxxxxx				
2.	Xxxxxxxx Xxxxxxxx xxxxxxxxxxxx (Xxxxxxxxx) – Xxxxx xxxxw xxxxx – Xxx xx xxxw xx xxyxxxxx xxxx xxxxx xx xx xxxxx
•	Xzxxx Xxxxx Xxxvxxxx				
•	XXX Xxxvxx 2016				
XXX		

```

### Current behavior
The numbering is reset to 1
```
1.	Xxxxxxxx xxxxxxxx xxxxxxxxxxxx (Xxxxxxxx xxxxx) – Xxxxx xxxxw xxxxx – Xx yxx xxxxx wx xxvx xxy xxxxx xxxxxxxx xxxxxxxxxx xxxxxxxxxxxx?
•	Xxxxxx Xxxxx				
•	Xxxxxx xxxxx xxxxy xxxxx				
•	Xxxxxxxx Xxxxxxx Xxxxxxx				
1.	Xxxxxxxx Xxxxxxxx xxxxxxxxxxxx (Xxxxxxxxx) – Xxxxx xxxxw xxxxx – Xxx xx xxxw xx xxyxxxxx xxxx xxxxx xx xx xxxxx
•	Xzxxx Xxxxx Xxxvxxxx				
•	XXX Xxxvxx 2016				
XXX	                 
```
### Environment

* **Kendo UI version:** 2018.2.620
* **Browser:**  IE 11

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
