### ISSUE TITLE
Templates for components with reactive data throw "[Vue warn]: Cannot find element ..."

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4374]
### Bug report
Templates for components with reactive data trow "[Vue warn]: Cannot find element ...". The warning is caused by [the following `$nextTick` handler](https://github.com/telerik/kendo-vue-wrappers/blob/develop/packages/kendo-base-components-vue-wrapper/src/kendo-base-component/index.js#L129)

### Reproduction of the problem
Run [the following demo sample](https://codesandbox.io/s/727mn053k0). The warnings will be observed on the console after the data has been loaded in the Grid.

Or test this project:
[test-templates.zip](https://github.com/telerik/kendo-ui-core/files/2192891/test-templates.zip)

### Expected/desired behavior
No warnings should be thrown

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by veselints** [comment]
A possible fix could be;
```JavaScript
that.$nextTick(function () {
  if(document.getElementById(kendoguid)) {
    vueObject.$mount('#' + kendoguid);
    that.$_nativeTemplates.push(vueObject);
   }
});
```

**Comment by veselints** [comment]
Something that might be possibly related: The template for each row (item) gets evaluated twice.

**Comment by tritrancs** [comment]
I also got this issue.

**Comment by ashupp** [comment]
I have also this issue when using Templates with reactive data.
