### ISSUE TITLE
Grid resize method doesn't work in a flexbox

### ISSUE THREAD

**Issue by kakone** [telerik/kendo-ui-core#4375]
### Reproduction of the problem
I have a datagrid in a flexbox with flex-grow: 1. In this case, the resize method of the grid doesn't work : see https://dojo.telerik.com/@kakone/AKIQUtIG
### Current behavior
The resize method of the grid doesn't work
### Expected/desired behavior
Grid height must be updated correctly when we call the Resize method of the grid
### Environment
- **Kendo UI version :** 2018.2.620

**Comment by PreslavKozovski** [comment]
Hi @kakone, 

I checked the provided page, and it seems that the Grid is okay. Could you please elaborate on what are your expectations for the resize method?

**Comment by kakone** [comment]
The grid should expand to 100% height, the footers should be at the bottom of the screen, it is not the case with the resize method.
If I use an older method to resize the grid (the commented lines in the provided sample), it works, but not with the resize method.

**Comment by kakone** [comment]
![image](https://user-images.githubusercontent.com/1640329/42845178-69da7792-8a15-11e8-83e1-bbd96c893f1f.png)

**Comment by sparklellama** [comment]
I use a workaround for this. However, Kendo grid should really do this by default.  Would be much nicer if Kendo generally worked with modern CSS better (flex) across the board

```
kendo.ui.Grid.prototype.matchContainerHeight = function(this: kendo.ui.Grid)
{
	if (this.element && this.element.parent())
	{
		let height = $(this.element.parent()).outerHeight()
		if (height !== 0)
		{
			$(this.element).css("height", height)
			this.resize()
		}
	}
}
```

**Comment by PreslavKozovski** [comment]
The make the Grid 100% height of its parent, as explained [here](https://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance#set-100-height-and-auto-resize), use a parent container that is part of the flex layout.

Please check the modified CSS in this Dojo: https://dojo.telerik.com/UpEXexuS

Please, let me know if this is the desired behavior?

**Comment by kakone** [comment]
Yes, that was the desired behavior, I'm going to add a parent container, thanks.
