### ISSUE TITLE
Stock Chart shows wrong data in the info box for the candlestick

### ISSUE THREAD

**Issue by fayhand** [telerik/kendo-ui-core#4378]
## I'm submitting a...
* Bug report 

## Current behavior
I go to https://demos.telerik.com/kendo-ui/financial/index
Scroll down and click the "Edit this example" button
Here I run the example with developer tools open, so I can see the boing-stock.json file
I zoom in and select the date interval 1-jan 2000 to 1-feb 2000.
I can now see candlesticks for 3-jan, 5-jan, 7-jan and so on.

Mouseover/clicking a candlestick while show an info box with OCHL values.
I looks like each box covers data from 2 days. The day in the title of the info box plus the day after.
For example the info box says 3-jan. The data is for 3-jan and 4-jan.

But the info box for 5-jan shows something strange. 
It shows Open, Close, High, Low values all from the 6-jan.

## Expected behavior
In this example I would expect the the Open value to be from 5-jan.

And actually, I would expect these boxes to show values from days before and up to including the date in the title. So the 5-jan box I would expect to show values from 4-jan to 5-jan, not 5-jan to 6-jan. Maybe I am wrong here. 

## Environment
Browser:
- Chrome (desktop) version 67.0.3396.99
System:
- Platform:  Windows

**Comment by matanasov** [comment]
@fayhand 
This is how it looks on my side and is expected. Let me know if I am missing something:

![chart](https://user-images.githubusercontent.com/5861835/43063768-7d149eec-8e65-11e8-9fca-6527abad074b.png)

**Comment by matanasov** [comment]
@fayhand 
Indeed the chart can aggregate values as described in this article:

https://docs.telerik.com/kendo-ui/controls/charts/date-series#date-grouping

Note that the default aggregate is max and is applied for all data values (OHLC)
In case the you can't achieve the desired behavior using the aggregates, please consider opening a support ticket.

**Comment by fayhand** [comment]
I thought this was a support ticket...
But yes I think these aggregates are not usable for OHLC data sets.
Each value needs a different aggregate. 
It looks at the wrong dates too in my opinion.
And last, it looks like it did not use the "max" aggregate for the "low"-value in the 5-jan-box.

**Comment by matanasov** [comment]
@fayhand 
My bad - as you have discovered the default aggregate for Low values is Min.

@Stamo-Gochev 
Could you please take a look at this:

> I would expect the boxes to show the following:
> 3-jan-box: the values from 3-jan, because there are the only ones we have at this date.
> 5-jan-box: "open"-value from 4-jan. "close"-value from 5-jan. Highest "high"-value from 4-jan and 5-jan. Lowest "low"-value from 4-jan and 5-jan.
> 
> I can not see what rules the chart uses now. And it looks like it takes values from the future and not past. (3-jan-box takes values from 3-jan and 4-jan).

**Comment by Stamo-Gochev** [comment]
@fayhand
The official support channel for communication can be accessed from your account (assuming there is a valid license). The following blog post provides additional information on how to do this:

https://www.telerik.com/blogs/how-to-submit-a-support-ticket

The candlestick and OHLC series use the following aggregates by default:
```
{ open: MAX, high: MAX, low: MIN, close: MAX }
```
Data points are automatically aggregated when they belong to the same category according to the above. If this needs to be changed, you can use the [series.aggregates](https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart/configuration/series.aggregate) option as in the following Dojo example (use the "first" value):

https://dojo.telerik.com/ISizEBIx/2

As there are additional questions that should be clarified, please open a support ticket, so the support team can provide further assistance and suggestions regarding the scenario.
