### ISSUE TITLE
Typing Korean/Chinese does not set Spreadsheet cell in edit mode

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#4379]
### Bug report
Typing Korean does not set Spreadsheet cell in edit mode. Typing is possible, when edit mode is entered with one of the following options:
- double click on a cell;
- press F2, when a cell is focused;
- type a Latin letter or a number;

### Reproduction of the problem
1. Add Korean language to your input languages.
1. Go to https://demos.telerik.com/kendo-ui/spreadsheet/index
1. Switch to Korean. If an A is visible next to some Korean text, click on the A to toggle it to Korean characters.
1. Click on a Spreadsheet cell to focus it.
1. Type any characters by pressing any letter keys.

### Current behavior
No typing starts as the cell does not enter edit mode.
If the cell is in edit mode, e.g. by double clicking on it, then typing is possible.

### Expected/desired behavior
The focused cell enters edit mode and characters are entered in it.

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by somsne** [comment]
I meet the same bug when I input chinese word.

 Environment:
 - Kendo UI version:2018.2.620
 - Browser:[all]

 Used typewriting:
 - Microsoft Pinyin(Windows 10 built-in chinese typewriting)
 - Sougou(https://pinyin.sogou.com/)

**Comment by Dimitar-Goshev** [comment]
@somsne Thank you for the update, I added Chinese to the issue as well.

**Comment by somsne** [comment]
@Dimitar-Goshev 
Thank you for your response!
I try to solve this problem myself.

```
// Start at kendo-ui/js/spreadsheet/eventlistener.js line 104.
var isAlphaNum = function(keyCode) {
    if ((keyCode > 47 && keyCode < 58)   || // number keys
        (keyCode > 64 && keyCode < 91)   || // letter keys
        (keyCode > 95 && keyCode < 112)  || // numpad keys
        (keyCode > 185 && keyCode < 193) || // ;=,-./` (in order)
        (keyCode > 218 && keyCode < 223) || // [\]' (in order)
        (keyCode === 229)) {  // Chinese support
        return true;
    }
    return false;
};
```

When use the Input Method Editors(IME),user press the keyboard will fire the keydown event correctly.But the event's keyCode property always was `229`.The KeyCode filter did not consider this situation.So I edit this code to make user who use IME can pass check and enter cell edit mode correctly.

I had test Microsoft Pinyin and Sougou in this code.It's worked.I passed the test in IE11(11.285.17134.0),Edge(42.17134.1.0),chrome(69.0.3497.100 X86),firefox(62.0 X64).My test platform is Windows 10 X64.

**Comment by mishoo** [comment]
I tested the fix suggested by @somsne with Korean input on Windows 10.  The outcome is that the cell does enter edit mode, but you have to press the key a second time to get a character in the field (which is different from pressing F2 first, then the key, which inserts it immediately).  I'm not sure how to workaround this, but it's still better than nothing so I committed this fix.

Thanks!
