### ISSUE TITLE
Widget "century" view does not support dates less then 200 year

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#438]
Repro demo:
http://dojo.telerik.com/@ggkrustev/iFaMu

Reported in TicketID: 885363 

See also: #439

**Comment by meziantou** [comment]
Hello,
Is there any news about this issue?

**Comment by ggkrustev** [comment]
Hi @meziantou,
The issue is still not scheduled for fix. I am afraid that I cannot provide a specific time-frame when it will be fixed.

As a side note, we are accepting pull-requests for this issue too. If someone is willing to help, we will be very grateful.
