### ISSUE TITLE
Incorrect virtual DropDownList value, if a filtered item is selected by pressing Enter - jQuery 3.3.1

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#4380]
### Bug report
The issue is reproducible with jQuery 3.3.1, while 1.12.4 works as expected.
Note:
- If there is no valueMapper, pressing Enter fires **change** event without DropDownList value.
- If there is valueMapper, pressing Enter fires **change** event with the value of the previously selected dropdown item. The text shown in the collapsed DropDownList is of the dropdown item, which appeared as focused, on pressing Enter.
In both cases above, pressing Enter again or blurring the widget fires **change** again with correct value.

### Reproduction of the problem
1. Use the following [Dojo](http://dojo.telerik.com/OWeQaPOS)
1. Click on the DropDownList to expand it.
1. Type Tom to filter the results - 10249 Tom is highlighted
1. Press Enter to select it.

### Current behavior
In the change event e.sender.value() is 10248, which is the value of the initially selected item, instead of being 10249 - the value of the focused item, whose text is chosen in the DropDownList.

### Expected/desired behavior
In the change event e.sender.value() is 10249. This works as expected, when jQuery 1.12.4 is used - [Dojo](http://dojo.telerik.com/Afaquqom)

### Environment
* **Kendo UI version:** 2018.3.911
* **jQuery version:** 3.3.1
* **Browser:** [all]

**Comment by jivanova** [comment]
Same incorrect triggerring of change event is reproducible for clearing the value in ComboBox and MultiSelect : https://dojo.telerik.com/ihIvOyiR/2 .

**Comment by frank1russo** [comment]
Here is the problem as I see it. There is an exception being thrown in the _removeTag method at line 41783 of kendo.all.js. The issue is the call to listView.select(listView.select()[position[0]) returns an empty array. There is no done function defined for that object. 

Here is the section:
if (customIndex === undefined) {
   that.persistTagList = false;
   listView.select(listView.select()[position]).done(done); // THIS IS LINE 41783. 
}

The stacktrace is:
Uncaught TypeError: listView.select(...).done is not a function
    at init._removeTag (kendo.all.js:41783)
    at init._tagListClick (kendo.all.js:41795)
    at HTMLSpanElement.proxy (jquery.js:10268)
    at HTMLUListElement.dispatch (jquery.js:5183)
    at HTMLUListElement.elemData.handle (jquery.js:4991)

**Comment by jivanova** [comment]
@frank1russo Thank you for digging into the issue. It turned out that the multiselect issue is not related to this one and I logged a new one for it:

 https://github.com/telerik/kendo-ui-core/issues/4760
