### ISSUE TITLE
Ng directives cannot be used with k-date-header-template

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4385]
### Bug report
`k-date-header-template` is not correctly compiled against the AngularJS `$scope`. 

### Reproduction of the problem
The issue can be observed on [the following Dojo example](https://dojo.telerik.com/owocElUB/10).

```js
<span k-date-header-template class='dh' ng-hide="true">            
  <div ng-if="false">
    <span class='k-link k-nav-day circle'>#=kendo.toString(date, 'dd/M')#</span>
  </div>
</span>
```

### Current behavior
ng directives cannot be used with the `k-date-header-template`.

### Expected/desired behavior
ng directives should be usable with the `k-date-header-template` similar to the rest of the Scheduler template directives (`k-all-day-event-template`, `k-event-template`, etc.).

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
