### ISSUE TITLE
There is recursive variable definition in bootstrap-mapper.less

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#4387]
### Bug report

bootstrap-mapper.less: 55

### Current behavior
When using less-loader in WebPack this recursive definition causes error. 

Ticket ID: 1176256

**Comment by Juveniel** [comment]
Тhe bootstrap-mapper is responsible for mapping the Bootstrap Less variables from bootstrap-variables.less to the Kendo UI Less variables. However, the name of the @input-bg variable that is used in the bootstrap-mapper is the same as in Bootstrap. Thus, commenting out the definition as no explicit mapping is needed.
