### ISSUE TITLE
Not defined Scheduler recurrence messages property deleteSeriesConfirmation

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#4396]
### Bug report
deleteSeriesConfirmation property is not set in any messages file, e.g. [en-US](https://github.com/telerik/kendo-ui-core/blob/master/src/messages/kendo.messages.en-US.js), thus the hardcoded default message in English is used:
```
DELETESERIESCONFIRM = "Are you sure you want to delete the whole series?"
...
text = recurrenceMessages.deleteSeriesConfirmation ? recurrenceMessages.deleteSeriesConfirmation : DELETESERIESCONFIRM;
```
Workaround:
Define the deleteSeriesConfirmation message:
`kendo.ui.Scheduler.prototype.options.messages.recurrenceMessages.deleteSeriesConfirmation = "Custom deleteSeriesConfirmation message";`

### Reproduction of the problem
1. https://dojo.telerik.com/IhohAheY
1. Scroll down Scheduler timeslots to show Dance Practice recurring events.
1. Double click on a Dance Practice event to edit it.
1. Click on "Serie bearbeiten" button.
1. Click on "Löschen" button to delete.

### Current behavior
Dialog text says "Are you sure you want to delete the whole series?"

### Expected/desired behavior
deleteSeriesConfirmation message for German is used (when it is added to de-DE messages and translated to German).

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by zdravkov** [comment]
Add localizations for deleteSeriesConfirmation and deleteRecurringConfirmation in en-US file.
