### ISSUE TITLE
Detail template is cleared when new page with Endless scrolling is rendered

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#4400]
### Bug report
Expanding any record and scrolling down for requesting another page with enabled Endless scrolling clears the content of the detail template. This is working correctly with versions up to R1 2018.

#### Steps to reproduce
1) Open the dojo example:
[https://dojo.telerik.com/OPUDehaS/2](https://dojo.telerik.com/OPUDehaS/2)
2) Expand the first record
3) Scroll down until the new page is rendered
4) Go back to the first record
Result -> the detail template content is cleared

### Environment
* **Kendo UI version:** 2018.2.620

**Comment by Alex-Bubblemaster** [comment]
Reported in ticket ID 1176772, also another client in these three tickets with the same content 1177308,1177309,1177315
