### ISSUE TITLE
Navigating to a MobileView which contains data-rel="external" causes redirect to that link 

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4405]
### Bug report

When we navigate to a view that contains a data-rel="external" link, the page is automatically redirected to the link instead of the view. The issue seems to be caused by a double click that is being triggered.

### Reproduction of the problem

The issue can be observed on [the following Dojo example](http://dojo.telerik.com/EPEyakuf).

Steps to reproduce:

* Turn on browser mobile emulator.
* Click on "To View2" button.

You will notice that the page is being redirected to the external link instead of the View.

### Current behavior

Double click occurs when an anchor tag with data-rel="external" is present on the view to which we are navigating. 

### Expected/desired behavior

The external link should not be clicked when navigating to the view that contains is.

### Environment

* **Kendo UI version:** 2018.2.620
* **Browser:** [Mobile Chrome]

**Comment by robvandijk** [comment]
Can this issue please be scheduled with higher priority? The only workaround currently available is passing 'transition: "slide:left"' to 'new kendo.mobile.Application' and this has a noticable negative impact on our users.

**Comment by ag-petrov** [comment]
Closing this issue as the mobile suite is now depricated.
