### ISSUE TITLE
Why should we stop using CSP (unsafe-inline) if we want to use saveAsExcel from the Grid?

### ISSUE THREAD

**Issue by masterjs** [telerik/kendo-ui-core#4409]
Hello,
We have security at heart and we're using your product for the UI. But recently we realized that using the `saveAsExcel` function from the KendoUI grid forces us to allow "unsafe-inline" in our strict CSP rules, which is very similar to simply disable it. Is there any way around this? So far it's been to only feature we saw with this limitation... but it really scared us that we could find new limitations like this. 

Any known work-around or just where do you guys stand on this topic just to set our expectations?
thank you,
JS

### Environment

* **Kendo UI version:** v2017.3.1018
* **Browser:** [Chrome 67]

**Comment by zdravkov** [comment]
Hi JS,

First of all please excuse me for the delayed answer for this question.

I have tested a scenario with Kendo grid and saveAsExcel and it worked without issues at my side - it didn't forced me to allow "unsafe-inline". I am attaching my code. Please review it and let me know if your scenario is somehow different.

Greetings,
Plamen
[CSP.zip](https://github.com/telerik/kendo-ui-core/files/2382168/CSP.zip)

**Comment by masterjs** [comment]
Hello @zdravkov !
Thank you for your sample, it helped me see my true issue and that your way was working fine! This resolve the issue and I'm really happy! ;o)

If anyone sees this issue and wounder what I did wrong:
`
<button class="btn btn-success btn-sm" onclick="exportToExcel('grid')"><span class="fa fa-file-excel-o"></span> Export to Excel</button>
`
This is not acceptable when using CSP (having a onclick in the html). The way around this is to run in a trusted script something like this instead:
`
$("#exportExcel").click(function (e) {
		exportToExcel('grid');
	});
`
and changed my html to:
`
<button id="exportExcel" class="btn btn-success btn-sm"><span class="fa fa-file-excel-o"></span> Export to Excel</button>
`

thank you,
JS
