### ISSUE TITLE
"TypeError: Cannot read property 'kendoWidget' of undefined" in vuejs

### ISSUE THREAD

**Issue by jeyandale** [telerik/kendo-ui-core#4412]
This instance occurred when you have kendo window in two different pages. 

Let say we have: 
   Page 1 with kendo window A and 
   Page 2 with kendo window B.

Now when you open the kendo window A in page 1 and navigate to page 2 then open kendo window B, this works fine but when you go back to page 1 and open kendo window A again this error will occur:

**[Vue warn]: Error in event handler for "openWindowA": "TypeError: Cannot read property 'kendoWidget' of undefined"**

for reference:
**Kendo window A code:**

`<template>`
 ` <kendo-window ref="openWindowA"`
                `  :width="'300px'"`
                 ` :title="'Window title A'"`
                `  style="display:none">`
       ` <h4>Window content A</h4>`
  `  </kendo-window>`
`</template>`

`<script>`
 ` import {EventBus} from '../../eventbus.js'`
 ` export default{`
 `   name: 'kendoWindowA',`
`    methods: {`
`        openWindowA (e) {`
 `           var window = this.$refs.openWindowA.kendoWidget();`
`            window.center().open();`
`        }`
`    },    created(){`
`     EventBus.$on('openWindowA', () => {`
 `     this.openWindowA()`
`     })`
`    }`
`  }`
`</script>`

**Kendo window B code:**

`<template>`
  `<kendo-window ref="openWindowB"`
               `   :width="'300px'"`
               `  :title="'Window title B'"`
               `   style="display:none">`
      `  <h4>Window content B</h4>`
   ` </kendo-window>`
`</template>`

`<script>`
 ` import {EventBus} from '../eventbus.js'`
  `export default{`
`    name: 'kendoWindowB',`
`    methods: {`
   `     openWindowB(e) {`
     `     var window = this.$refs.openWindowB.kendoWidget();`
  `          window.center().open();`
`        }`
 `   },`
 `   created(){`
`     EventBus.$on('openWindowB', () => {`
`      this.openWindowB()`
  `   })`
 `   }`
 ` }`
`</script>`

Thus anyone know why this is happening? or is there something wrong when my implementation?

**Comment by zdravkov** [comment]
It worked correctly at my side with the latest version - https://stackblitz.com/edit/d61zmq-y36ghl?file=src/main.vue
