### ISSUE TITLE
Update docs and typescript definitions with window.content configuration

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#4416]
https://docs.telerik.com/kendo-ui/api/javascript/ui/window/configuration/content

We should update the content setting to display all of its options:

``` javascript
<script>
$("#dialog").kendoWindow({
  content: {
    url: "/userDetails",
    dataType: "json",
    iframe: false,
    template: "User name: #= data.username #"
  }
});
</script>
```

Update the typescript definitions too.

**Comment by simon-sharp** [comment]
+1

**Comment by DaleyKD** [comment]
Consider this my upvote.  TS is giving me an error.
