### ISSUE TITLE
Tooltip opens only once on iOS, when showOn is mouseenter (default setting)

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4422]
### Bug report
Tooltip opens only the first time on iOS touch devices.
Note: showOn: "click" works as expected on iOS.

### Reproduction of the problem
1. Open the [Dojo example ](http://dojo.telerik.com/aVaTArAj) on iPhone or iPad.
1. Tap on "Tap on this text" to open the Tooltip.
1. Tap above the text to close the tooltip
1. Tap on "Tap on this text" to open the Tooltip again.

### Current behavior
Tooltip is displayed only the first time. Once it is closed it will not show up again.

### Expected/desired behavior
Tooltip should opens every time.

### Workaround
` showOn: kendo.support.touch ? "click" : "mouseenter",`

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [ iOS Safari and Chrome]

**Comment by Juveniel** [comment]
This issue is not reproducible with the development version of Kendo.

**Comment by Dimitar-Goshev** [comment]
@Juveniel The issue is not reproducible due to the changes made for addressing this issue:
https://github.com/telerik/kendo-ui-core/issues/5356
