### ISSUE TITLE
Displaced event indicators in adaptive Scheduler Month view

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4427]
### Bug report
**Regression since R1 2018 - 2018.1.117**

When adaptive rendering for the Scheduler is enabled, the events are displayed as boxes in MonthView one day prior to their actual start date, although the Scheduler has timezone: "Etc/UTC" set. When timezone is set, events should be rendered on one and the same timeslots, regardless of the client timezone - [documentation](https://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/timezones#configuration): "On the other hand, setting the Scheduler timezone will force the widget to show the same start and end times regardless of the user's timezone." This rule seems not observed by mobile month view events indicators.

### Reproduction of the problem
1. Set PC timezone to Eastern Time (UTC -5)
1. Run the following [Dojo](http://dojo.telerik.com/iMUQaTef), which is based on [Adaptive Scheduler demo](https://demos.telerik.com/kendo-ui/m/index#scheduler/adaptive).

### Current behavior
Event indicators are incorrectly positioned for the previous day, e.g. 10th, instead of 11th:
![image](https://user-images.githubusercontent.com/6614183/43957866-6246408c-9c77-11e8-952b-6c1fed7dda23.png)

### Expected/desired behavior
**NOTE: The issue is not reproducible in Firefox.**
Event boxes should be positioned correctly according to the timezone:
![image](https://user-images.githubusercontent.com/6614183/43957921-936d9e26-9c77-11e8-9f93-ca9542127779.png)

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [Chrome, IE, Edge]

**Comment by Dimitar-Goshev** [comment]
@zdravkov The current issue is most probably caused by the last fix for the following issue: https://github.com/telerik/kendo-ui-core/issues/3232
