### ISSUE TITLE
Incorrect selection with Ctrl + Shift + Arrow key keyboard shortcut

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4429]
### Bug report
The Ctrl + Shift + Arrow key keyboard shortcut should select a range in the row/column starting with the active cell and ending with the first cell in the row/column that has a value: [list of shortcuts](https://docs.telerik.com/kendo-ui/controls/data-management/spreadsheet/end-user/list-of-shortcuts) used by the Spreadsheet. It works similarly in Excel. 

### Reproduction of the problem
1. https://dojo.telerik.com/oVoJoRAs
1. Click on A3
1. Press Ctrl+Shift+Down Arrow

### Current behavior
The selection does not end at the first cell that has a value, it ends with the last cell of the row/column.  

### Expected/desired behavior
The expected behavior should be as described in the documentation: "Extends the selection of cells to the last nonblank cell in the same row or column as the active cell."

### Environment

* **Kendo UI version:** 2019.3.917
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by rvicoqbi** [comment]
Very interested on this issue 😄
