### ISSUE TITLE
grunt fails when extra comma is added

### ISSUE THREAD

**Issue by dotnetwise** [telerik/kendo-ui-core#443]
```batch
t:\kendo\src>grunt custom:grid,notification,
Running "custom:grid,notification," (custom) task
Warning: Can't find Kendo file: kendo..js Use --force to continue.
```

Due to the extra `,` at the end the build fails.

Empty ,, commas should be stripped out

**Comment by underlog** [comment]
Thank you for your input. At this point, we won't don't consider the error handling necessary (or, for that matter, appropriate). @mishoo outlined the reasons in his previous reply.
