### ISSUE TITLE
[Support] How to setup kendoImageBrowser like ImageManager in RadEditor???

### ISSUE THREAD

**Issue by vndevil** [telerik/kendo-ui-core#4439]
Hi,

I have a question: How to config kendoImageBrowser same with ImageManager in RadEditor???
On the demo:
https://demos.telerik.com/aspnet-ajax/editor/examples/overview/defaultcs.aspx

**Comment by zdravkov** [comment]
This repository is about Kendo Widgets. In case you have questions about RadControls I will recommend you to submit it in [this forum](https://www.telerik.com/forums/aspnet-ajax/editor).
