### ISSUE TITLE
Sass Material theme status

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-ui-core#4444]
As the Sass Material theme is already working for [some ](https://dojo.telerik.com/arUDONAc)of the widgets, and not for [others](https://dojo.telerik.com/iboZOPoZ). We would like to have a list with the supported components. I know it is not officially released, but since it is out there it is like public beta and can be helpful for testing and bug reports on time before the official release.

**Comment by Dimitar-Goshev** [comment]
@Xizario There is a list of implemented SASS Material theme per widget in the kendo-themes repository: https://github.com/telerik/kendo-themes/issues/235

**Comment by Xizario** [comment]
@Dimitar-Goshev , thank you
