### ISSUE TITLE
data-auto-bind does not work in Scheduler MVVM

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4446]
### Bug report
`data-auto-bind` attribute does not work in Scheduler MVVM. The option could not be set to *false*.

This is a regression introduced with the R1 2018 SP1 release (2018.1.221)

### Reproduction of the problem
* Run the following [Dojo](https://dojo.telerik.com/ADaroJeW/5)
* You will notice that the *Read* function will be called;

### Expected/desired behavior
The *Read* should not be triggered when `data-auto-bind` is set to *false*.

### Environment
* **Kendo UI version:** form 2018.1.221 on
* **Browser:** [all]

**Comment by jivanova** [comment]
Reproducible after https://github.com/telerik/kendo/commit/cae0c16ece0d3675eeb824cc3162e67707f491ea#diff-e6faa471102e96f01e4850c5797767ea
