### ISSUE TITLE
Invalid animation value in kendo.common-material.css

### ISSUE THREAD

**Issue by Ristaaf** [telerik/kendo-ui-core#4450]
### Bug report

Not sure how deep I need to dive into this, but when building a prod build with angular-cli using  Kendo, I get warnings for Invalid animation value. I have narrowed it down to the kendo.common-material.css file which have transition values that are duplicates and also are delimited by " which is not correct css.

Note though that this is not dependent on usage within Angular and Angular CLI, it is just a place where we saw effects of the problem, the problem is much simpler than that, invalid CSS, it can be tested here: https://jigsaw.w3.org/css-validator/validator, pasting the kendo.common-material.css file there shows exactly this bug and a few others.

### Reproduction of the problem

Create a new project with angular-cli, add kendo-ui to it and add kendo.common-material.css to the styles part in the angular.json file. Do a prod build and there will be a number of WARNINGS, not telling where it comes from though. By editing the code in the package that throws this warning you can see what the invalid values are though. And they stem from kendo.common-material.css

### Current behavior
Errors in CSS files (possibly this is in other css files too)
Example:
line 1275-1278
```
-webkit-transition: width 200ms linear;
transition: width 200ms linear;
-webkit-transition: "width 200ms linear";
transition: "width 200ms linear";
```

Where the two last lines have bad css and also are some kind of duplicates of the first two.

There are at least three such places in the file:
line 4228-4235
```
.k-numeric-wrap {
  -webkit-transition: -webkit-box-shadow .15s ease-out;
  transition: -webkit-box-shadow .15s ease-out;
  transition: box-shadow .15s ease-out;
  transition: box-shadow .15s ease-out, -webkit-box-shadow .15s ease-out;
  -webkit-transition: "box-shadow .15s ease-out";
  transition: "box-shadow .15s ease-out";
}
```
and line 9066-9069
```
-webkit-transition: opacity 0.3s linear;
  transition: opacity 0.3s linear;
  -webkit-transition: "opacity 0.3s linear";
  transition: "opacity 0.3s linear";
```

### Expected/desired behavior
css without errors

### Environment

* **Kendo UI version:** 2018.2.806
* **Angular CLI version:** 6.1.3

**Comment by dmanova** [comment]
[W3C CSS Validator ](https://jigsaw.w3.org/css-validator) (CSS level 3 + SVG) gives few more errors for kendo.common-material.css : 

row | css | **error**
264 | .k-header-column-menu | **Value Error :  color  _inhert_ is not a _color_ value : _inhert_**
1931 | .k-menu-scroll-wrapper .k-item div, .k-popups-wrapper .k-item div, .k-menu .k-item div | **_default_ is not a _user-select_ value : _default_**
2588 | .k-grouping-row .k-group-cell, .k-grouping-row + tr .k-group-cell | **_none_ is not a _text-overflow_ value : _none_**
8722 | .k-scheduler-mobile  .k-scheduler-times .k-scheduler-group-cell .k-scheduler-group-text,  .k-scheduler-mobile .k-scheduler-agenda .k-scheduler-group-cell  .k-scheduler-group-text, .k-scheduler-mobile .k-scheduler-times  .k-scheduler-groupcolumn .k-scheduler-group-text, .k-scheduler-mobile  .k-scheduler-agenda .k-scheduler-groupcolumn .k-scheduler-group-text | 
**_tb_ is not a _writing-mode_ value : _tb_** 
14018 | .k-drawer-wrapper | **Property _scrollbar-width_ doesn't exist : _thin_** 
14229 | .k-timeline-card .k-card .k-card-body | **Property _scrollbar-width_ doesn't exist : _thin_**

The last two are with limited support on some browser, and that may cause them appear in the list (check https://caniuse.com/#feat=css-scrollbar).

**Comment by PreslavKozovski** [comment]
The styles from the last two errors are by design, and we are not going to remove/change them.
