### ISSUE TITLE
In some themes, the Page Size dropdown in the Grid shows ellipsis instead of a page size in FireFox 

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#4453]
### Bug report

When a Grid with a Page Sizes dropdown is opened in Firefox using one of the themes having own common styles file (Bootstrap, Material, Fiori, Nova, etc.), the dropdown shows "**...**" instead of the selected number.

### Reproduction of the problem
The issue can be reproduced in the [Basic Usage Demo](https://demos.telerik.com/kendo-ui/grid/index). Open it in Firefox and select the Material theme, for example.

If this may be related to the problem, I reproduced it on a 15.6" monitor with 1920x1280 resolution.

### Environment

* **Kendo UI version:** 2018.2.620
* **Browser:** Firefox

Reported in: 1338170

**Comment by ZishanAnsari** [comment]
Pls provide fix on this issue as I hv also reprodced it

**Comment by TeyaVes** [comment]
Should be fixed by https://github.com/telerik/kendo/pull/8742
