### ISSUE TITLE
Telerik.web.Spreadsheet.Workbook.Load() throws an error on loading a document with gradient cells' background

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4456]
### Bug report
Telerik.web.Spreadsheet.Workbook.Load() throws an error when the loaded document contains gradient backgrounds for some of its cells.

### Reproduction of the problem
Load an xlsx file containing gradients with the above method:
```cs
var filePath = Server.MapPath("/App_Data/Copy of MTO Workbook.xlsx");

using (FileStream file = new FileStream(filePath, FileMode.Open))
{
    XlsxFormatProvider formatProvider = new XlsxFormatProvider();
    Workbook workbook = formatProvider.Import(file);

    Telerik.Web.Spreadsheet.Workbook telerikWorkbook = Telerik.Web.Spreadsheet.Workbook.FromDocument(workbook);
}
```

### Current behavior
Error:
Unable to cast object of type 'Telerik.Windows.Documents.Spreadsheet.Model.GradientFill' to type 'Telerik.Windows.Documents.Spreadsheet.Model.PatternFill'.

### Expected/desired behavior
No error should be observed. The workbook should be loaded and the gradient should be disregarded

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by IvanDanchev** [comment]
Also reported in: Ticket ID: 1432481
