### ISSUE TITLE
TreeView expand event fires multiple times if a node is appended in its handler

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4458]
### Bug report
If a node is appended in the expand event handler the event fires in a loop and a "Maximum call stack size exceeded exception is thrown". Regression reproducible since version 2018.2.516. 

### Reproduction of the problem
[Dojo example](https://dojo.telerik.com/upaSAHOR). 
1. Open the browser dev tools' console.
2. Expand the root node. 

### Current behavior
The expand event fires multiple times.

### Expected/desired behavior
The expand event fires once. 

### Environment

* **Kendo UI version:** 2018.2.620
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Iankodj** [comment]
The fix targets the append method, which should not fire the expand event.
