### ISSUE TITLE
Hidden rows in Excel are visible in Kendo Spreadsheet, once the file is imported server side

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4462]
### Bug report

Related and fixed with #3310

Hidden row, either by row height set to 0 or if the Hide option from the context menu of Excel is selected, is visible once it is loaded in the Spreadsheet

The reciprocal bug is fixed (exported hidden row is not hidden in the excel file):
[https://github.com/telerik/kendo-ui-core/issues/2466](https://github.com/telerik/kendo-ui-core/issues/2466)

### Reproduction of the problem
[Reproduction steps video](https://monosnap.com/file/3c6tEYRIRPY7fWuHN1VnOw9xf86QPm)

### Current behavior
The hidden row is visible in the Spreadsheet loaded file.

### Expected/desired behavior
The state of the row should be identical with the source file.

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by mishoo** [comment]
That video uses the server-side import, which I cannot handle.  I checked the client-side import (click "open" button in the toolbar) and it works fine.
