### ISSUE TITLE
AutoFill increments seconds in DateTime format

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#4466]
### Bug report

When you copy and paste a date like this one `12/30/2017 20:00:00` and apply AutoFill from this cell the seconds will be incremented. 

### Reproduction of the problem
https://demos.telerik.com/kendo-ui/spreadsheet/index

1. Paste `12/30/2017 20:00:00` into an empty cell
2. Apply autofill 

### Current behavior

12/30/2017 20:00:00
12/30/2017 20:00:1
12/30/2017 20:00:2

### Expected/desired behavior
12/30/2017 20:00:00
12/30/2017 20:00:00
12/30/2017 20:00:00

### Environment

* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by mishoo** [comment]
The real bug here is the inability to parse this date+time format.  `12/30/2017 20:00:00` is interpreted as plain text instead of timestamp, as if you typed `'12/30/2017 20:00:00` (notice the apostrophe, which prevents parsing).  When filling a text column, if the text ends with a number that number is incremented.

**Comment by mishoo** [comment]
Fixed in https://github.com/telerik/kendo/commit/da8c8758140658b4d09bba5b7d320e218993a63f (sorry, forgot to reference issue in the commit log).

**Comment by marekdano** [comment]
@mishoo 
> When filling a text column, if the text ends with a number that number is incremented.

What is the current behaviour? Will the text ended with a number be copied with incremented number at the end of the text? If it's then it won't be a fix for us. We'll need to have the same text ('12/30/2017 20:00:00) copied to other cells.
