### ISSUE TITLE
Horizontal scroll bar is displayed in the dropdown even if autoWidth is enabled

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4467]
### Bug report
Reproducible in IE11, Edge, Firefox. In Chrome a scroll bar without a slider is displayed and when an item in the dropdown is hovered the scroll bar disappears. 

### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/ubOHigok/2) example.

### Current behavior
Horizontal scroll bar is displayed in the dropdown.

### Expected/desired behavior
No horizontal scroll bar is displayed.

### Environment

* **Kendo UI version:** 2018.3.911
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Reported in Ticket ID: 1349674

**Comment by judef** [comment]
This bug still exists in IE11

**Comment by Dimitar-Goshev** [comment]
@judef The issue is still open. You may track this issue for updates on its progress.
