### ISSUE TITLE
Click on associated Label with ComboBox, Multiselect and MultiColumnComboBox does not focus the input

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4472]
### Bug report

The label for="[widgetid]" does not trigger the open event of the popup element of the ComboBox, Multiselect and NumericTextBox widgets. The reason is that the **focusin** event is not implemented, like for the DropDownList.

### Reproduction of the problem
Use the following demos the test:

DropDownList, where the functionality works correctly: https://demos.telerik.com/kendo-ui/dropdownlist/index (click on the CAP COLOR label)

ComboBox, where the functionality does not work correctly: https://demos.telerik.com/kendo-ui/combobox/index (click on the T-SHIRT FABRIC label)

### Environment

* **Kendo UI version:** 2018.3.911
* **Browser:** [all]

**Comment by nenchef** [comment]
Reported in ticket 1399640. Raised priority

**Comment by veselints** [comment]
PR here: https://github.com/telerik/kendo/pull/10097
