### ISSUE TITLE
autoFitColumn() does not calculate column width correctly when populate grid on a hidden <div>

### ISSUE THREAD

**Issue by wctiger** [telerik/kendo-ui-core#4474]
### Bug report

When populating a kendoGrid on a hidden `<div>`, autoFitColumn() function is either collapsing the columns or make them wider than desired.

### Reproduction of the problem

Create a hidden div, bind data, then call autoFitColumn() on the grid object. Make the div to show.
Here is a dojo demo of reproduction:
https://dojo.telerik.com/oxoFIFUp

### Current behavior
Column width in the hidden div looks not right.
![capture](https://user-images.githubusercontent.com/7061370/44872877-acc37d80-ac64-11e8-9f74-1736c5033559.PNG)

### Expected/desired behavior
Column width in the hidden div should be calculated same as non-hidden div.

### Environment

* **Kendo UI version:** 2018.2.822
* **jQuery version:** 3.3.1
* **Browser:** [ Chrome 68.0.3440 | Firefox 61.0.2 | IE 11 ]

**Comment by matanasov** [comment]
@wctiger 
The grid must be visible so that it can correctly calculate the auto-fit column width. Modified dojo:
[https://dojo.telerik.com/oxoFIFUp/5](https://dojo.telerik.com/oxoFIFUp/5)
