### ISSUE TITLE
DropDownTree's dropdown remains opened on blurring the widget with Tab

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4482]
### Bug report
When tabbing away from a DropDownTree with opened dropdown, the dropdown is not closed.

### Current behavior
1. Run the following [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/EhILIduZ)
1. Focus the first DropDownTree
2. Open the Popup
3. Tab once to focus the wrapper and twice to go to the next focusable element

### Current behavior
The Popup stays open

### Expected/desired behavior
The Popup should close

### Environment
* **Kendo UI version:**2019.3.1023
* **Browser:** all

Workaround - https://dojo.telerik.com/@zdravkov/erevicOv

**Comment by veselints** [comment]
Also reported in: Ticket ID: 1458376

**Comment by Dimitar-Goshev** [comment]
The reported scenario is fixed. There are two other scenarios still not fixed. They are reproducible when autoClose is set to false
- [ ] DropDownTree with checkboxes and `autoClose: false`
  - Go to [Checkboxes demo](https://demos.telerik.com/kendo-ui/dropdowntree/checkboxes) on staging
  - Click on DDTree to expand the dropdown
  - Click on Check all to select nodes
  - Click on the clear button of DDTree or on the delete button of a selected item
  - Press Tab to blur the DDTree
**Current** - dropdown remains open
**Expected** - dropdown is closed

- [ ] DropDownTree with filtering and `autoClose: false`
  - Use the setup from [Events demo](https://demos.telerik.com/kendo-ui/dropdowntree/events) and add `autoClose: false,` to it
  - Expand the dropdown and select a node, e.g. Furniture
  - Click on the filter input and type 'test'
  - Click on DDTree clear button
  - Press Tab to blur the DDTree
**Current** - dropdown remains open
**Expected** - dropdown is closed
