### ISSUE TITLE
l.select(...).done is not a function error is thrown when delete the second selected item after filtering.

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4483]
### Bug report
l.select(...).done is not a function error is thrown when delete the second selected item after filtering. This occurs when no *valueMapper* function is defined.

### Reproduction of the problem
http://dojo.telerik.com/aPEyOPel 

1. Click on the multiselect input
2. Type 'Han'
3. Select one of the filtered items, e.g. the third one
4. Type 'Han'
5. Select one of the filtered items again
6. Click outside of the widget to blur it
7. Click on the multiselect input, or directly delete an item using the `x` button
8. Press Backspace

### Current behavior
An error is thrown: Uncaught TypeError: l.select(...).done is not a function

### Expected/desired behavior
No errors occur

### Environment
* **Kendo UI version:** from 2017.3.1018 on

**Comment by dinutzy** [comment]
Hello! Can you please check again this bug? I've updated kendo recently to 2018.3.1017 and the error is still trowing...

**Comment by sonikdesign** [comment]
Hello! I also ask for an update on this bug. Thank you.

**Comment by jivanova** [comment]
Hey @dinutzy. @sonikdesign , could you please elaborate what is the exact scenario to replicate the issue?

**Comment by sonikdesign** [comment]
Hi @jivanova, I've this problem with a kendoMultiSelect widget.

1. Selection of an item from the dropdown menu
2. Blur of kendoDropDownList widget
3. Click to delete a value from the widget
4. JS error: l.select(...).done is not a function. It is impossible to remove the values ​​already entered.

**Comment by jivanova** [comment]
@sonikdesign Could you please provide a sample dojo? Do you replicate the issue with the following demo:

[https://demos.telerik.com/kendo-ui/multiselect/virtualization](https://demos.telerik.com/kendo-ui/multiselect/virtualization) or
[http://dojo.telerik.com/upOrotoT](http://dojo.telerik.com/upOrotoT)

**Comment by ronamelissa** [comment]
encountered the same error. is there a fix to this?
