### ISSUE TITLE
Menu popup opening animation appears slower just before it finishes

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4488]
### Bug report
There is a difference in how the popup opening animation looks like when it starts and when it finishes. It appears a little bit slower at the end: [screencast](https://www.screencast.com/t/TfXw5Nb35). It is barely noticeable in the screencast and more noticeable when tested in the browser. It is easier to spot when using the Material or Nova themes. The issue is exhibited only on initial sub menu opening. On subsequent opening of the same menu item the animation looks consistent from start to finish.

### Reproduction of the problem
1. Open the [demo ](https://demos.telerik.com/kendo-ui/menu/direction) and choose Material theme. 
2. Hover a Menu item for the first time to expand it. 

### Current behavior
The space below the last item text appears cut just before the animation completes and then appears not cut when the animation ends. Thus the lower end of the popup appears jumping/flickering.

### Expected/desired behavior
The space below the last item text does not appear cut just before the animation completes. This is reproducible after the submenu items are expanded initially. 

### Environment
* **Kendo UI version:** 2019.1.115
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
R1 2023 is the last official release of Kendo jQuery, where Less Themes are supported and shipped with the product.
