### ISSUE TITLE
Exporting a virtual Grid with all its columns widths set to a scaled down PDF results in column headers shift to the right

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4489]
### Bug report
Exporting a virtual Grid with all its columns widths set to a scaled down PDF results in column headers shift to the right.

### Reproduction of the problem
* Run the following [Dojo](https://dojo.telerik.com/ACOwujas/2);
* Export the Grid data to PDF by clicking the toolbar button;
* The exported PDF will have the headers of the Grid columns shifted to the right;

### Expected/desired behavior
The headers should not be shifted

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Seems to work fine with the latest version, adding QAs to check

**Comment by dmanova** [comment]
Works after v. 2019.3.917
