### ISSUE TITLE
Grid noRecords output inconsistent

### ISSUE THREAD

**Issue by aronduby** [telerik/kendo-ui-core#4495]
### Reproduction of the problem
Set grid's noRecords property to true and compare the rendered out to setting it to an object with a string template. The rendered html shouldn't change so drastically, it makes having proper styling problematic.

https://dojo.telerik.com/AWAkUXOn

### Current behavior
Setting noRecords property to object with template removes the `div.k-grid-norecords-template` element that is used when it is set to true

### Expected/desired behavior
Boolean and template object should have the same structure. Maybe add ability to supply a class with the object.

### Environment
* **Kendo UI version:** 2018.2.620
* **jQuery version:1.12.4
* **Browser:** all

**Comment by matanasov** [comment]
@aronduby 
The described behavior seems expected to me - after all templates provide full control of what you want rendered. You can easily achieve the same look by just adding the same HTML to the template string:

https://dojo.telerik.com/AWAkUXOn/2

**Comment by aronduby** [comment]
If I supply a template from a grid cell it doesn't wipe out it's container.
I don't see this pattern used anywhere else within kendo, or any other
library I've worked with.

You should at least document this behavior.

**Comment by matanasov** [comment]
@aronduby 
I understand your concern and add some of our dev guys here.
@ag-petrov @Stamo-Gochev please share your thoughts about this behavior.

**Comment by ag-petrov** [comment]
@aronduby Thank you for bringing this to question. Now when setting the **noRecords** property to true the below content is actually the entire template. In other words both the wrapper **div** with class **k-grid-norecords** and the inner **div** with class **k-grid-norecords-template** are the default template. 

```<div class="k-grid-norecords"><div class="k-grid-norecords-template" style="margin:0 auto;position:static;">No records available.</div></div>```

That said the actual container is the **div** with the **k-grid-content class**. When defining a custom one it is expected that he replaces the one we render by defautl. As for the default one's format it is such so it can be styled properly. Altering it is not possible as it will cause a breaking change.
