### ISSUE TITLE
ComboBox change event fires twice on entering text and tabbing out

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4496]
### Bug report
Introduced in version 2018.2.620 ([commit](https://github.com/telerik/kendo/commit/beaeb598ee5c2aa0fe2c44eab5b10ee36ef308dd#diff-9ca009eed95e4be66581342a3f910f7d)).

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/eZUcoNiX/2) example. 
1. Click the ComboBox input area. 
2. Enter arbitrary text
3. Press "Tab" key.

### Current behavior
The change event fires twice.

### Expected/desired behavior
The change event fires once.

### Environment

* **Kendo UI version:** 2018.2.620
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by Juveniel** [comment]
The issue can be reproduced on [the following Dojo](http://dojo.telerik.com/uZAbIdoV/3) with the 2019 R1 (2019.1.115):

* Enter text in the ComboBox input
* Press Tab
* Enter more text in the ComboBox input
* Press Tab

The issue can also be reproduced if  'Enter' is clicked after entering text and then tabbing out.
