### ISSUE TITLE
TypeScript definition for ButtonGroup is missing 'selectedIndices'

### ISSUE THREAD

**Issue by wildough57** [telerik/kendo-ui-core#4498]
Bug report

Update TypeScript definitions and documentation for ButtonGroup.

No definition included for 'selectedIndices"

It should look like:

`class ButtonGroup extends kendo.ui.Widget {
        static fn: ButtonGroup;
        options: ButtonGroupOptions;
        element: JQuery;
        wrapper: JQuery;
        static extend(proto: Object): ButtonGroup;
        constructor(element: Element, options?: ButtonGroupOptions);
        badge(button: string, value: string): string;
        badge(button: string, value: boolean): string;
        badge(button: number, value: string): string;
        badge(button: number, value: boolean): string;
        current(): JQuery;
        destroy(): void;
        enable(enable: boolean): void;
        select(li: JQuery): void;
        select(li: number): void;
        selectedIndices?: Array<number>;
    }`

**Comment by nenchef** [comment]
Hi Will,
Thank you for your submit. We will be very grateful if you could directly submit a Pull Request with the needed changes to the typescrpit file in the repo.
Thanks in advance!

**Comment by wildough57** [comment]
nenchef: Sorry but I'm not GitHub savvy enough to do that.  Also, I'm a customer with a commercial license and I don't really think that I should need to go beyond diagnosing the problem and pointing you guys to the fix.
