### ISSUE TITLE
Grid DropDown Editors throw errors when there are "\r\n" new lines in text

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#4500]
### Bug report

Reported in ticket with ID 1340899.

### Reproduction of the problem

Add "\r\n" in the text and use the BindTo() method to assign the data, e.g. the GridForeignKey.cshtml

```
  var employees = Enumerable.Range(1, 10).Select(i => new Employee
 {

    Name = "Employee\r\n Name " + i,
    EmployeeID = i
 });

 ViewData["employees"] = employees;

.Columns(columns =>
{
        columns.ForeignKey(p => p.EmployeeID, (System.Collections.IEnumerable)ViewData["employees"], "EmployeeID", "Name");
})
```

### Current behavior

The error is a JavaScript error thrown by the jQuery append method in which it uses eval() to evaluate the serialized code for the Foreign Key Editor. This occurs with all editors which use BindTo()

![image](https://user-images.githubusercontent.com/10980842/45540332-cf34c980-b814-11e8-9a25-2fc4ecc1ed48.png)

### Expected/desired behavior

The serialized data should not be escaped and this will cause no troubles at all then. Just like it doesn't in jQuery.

[jQuery Grid correct/desired behaviour](https://dojo.telerik.com/@bubblemaster/OYiFojUW)

Reason for the error:

![image](https://user-images.githubusercontent.com/10980842/45540359-e378c680-b814-11e8-86e0-2571d6547cd6.png)

How jQuery grid handles it:

![image](https://user-images.githubusercontent.com/10980842/45540380-f390a600-b814-11e8-9b2b-d80a256a7584.png)

### Environment

* **Kendo UI version:** 2018.2.620
* **jQuery version:** 1.12

**Comment by rpanjwani** [comment]
Why was this issue closed? This still happens.
