### ISSUE TITLE
Grid with locked / frozen columns has a double white mask with jQuery 3.3.1

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#4504]
### Bug report

Tickets with ID 1342204; 1112787;

### Reproduction of the problem

[Dojo](https://dojo.telerik.com/@bubblemaster/EHIsUPoW)

### Current behavior

![image](https://user-images.githubusercontent.com/10980842/45559044-1f7a4e80-b84a-11e8-9b5f-afc7bcb0d025.png)

### Expected/desired behavior

![image](https://user-images.githubusercontent.com/10980842/45559083-3325b500-b84a-11e8-9ffb-e754992b2c03.png)

### Workaround

Force the widget to resize on data bound (uncomment the line in the `dataBound` handler to see it in action in the Dojo above):

```
dataBound: function(e){
    e.sender.resize(true)
 }
```

### Environment

* **Kendo UI version:** 2018.3.911
* **jQuery version:** 3.3.1

**Comment by VicTachev** [comment]
reported again in ticket 1361930
