### ISSUE TITLE
Parent is not hidden if children are inaccessible and a child separator item is present

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#4514]
### Bug report
[Security Trimming docs](https://docs.telerik.com/aspnet-mvc/helpers/navigation/menu/security-trimming)

Whole project: # 1341026

```csharp
@(Html.Kendo().Menu()
   .Name("Menu")
   .SecurityTrimming(s => s.HideParent(true))
   .Items(items =>
   {
       items.Add()
       .Text("Transferências de Arquivos")
       .Items(children =>
       {
           children.Add().Text("Test1").Action("Index", "Upload");
           children.Add().Separator(true);
           children.Add().Text("Test2").Encoded(false).Action("DataFile", "Upload");
       });
   })
)
```
### Reproduction
1. Menu Items that point to action, which is not authorized without login, should not be accessible.

### Current behavior
Separator prevents the menu item from being hidden. All child items are hidden, except a 2px item, rendered for the separator.
![Unexpected visible parent item](https://user-images.githubusercontent.com/6614183/68848283-b81f8f00-06d8-11ea-808e-7991175cad66.png)

### Expected/desired behavior
Menu item is hidden as its child items are not accessible.

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
@Iankodj After the fix PanelBar and TreeView nodes have no rendered child items.
Check Basic usage demos.
