### ISSUE TITLE
Item is re-selected in ComboBox when clearing with backspace

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4516]
### Bug report

When dataTextField and dataValueField are not set and the value in ComboBox is cleared by using the backspace, the item is selected again.

### Reproduction of the problem
1. Open the [Dojo ](https://dojo.telerik.com/IGuBaHOw)
2. Select an item.
3. Clear it with backspace.

### Current behavior
The item is selected again.

### Expected/desired behavior
The value should be cleared.

### Environment

* **Kendo UI version:** 2018.3.911
* **Browser:** [all ]

**Comment by nelito987** [comment]
Related: #4254

**Comment by zdravkov** [comment]
Introduced after fixing - https://github.com/telerik/kendo/issues/8733
