### ISSUE TITLE
Content resizing is not working properly when Editor is in Dialog

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#4526]
### Bug report

When Editor is placed in Kendo Dialog. Its resize functionality does not expand the body to the corresponding height. 

### Reproduction of the problem
http://dojo.telerik.com/oDoMAJaH/3

1, Resize the Editor in the dialog to see that the editable area is not expanding.

2. Close and resize the editor outside the dialog to see the expected behavior. 

### Environment

* **Kendo UI version:** 2019.1.115

**Comment by sspasova** [comment]
The issue is fixed. Tested with Kendo UI version 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/oDoMAJaH/6
