### ISSUE TITLE
Unable to preserve edited Gantt task name on pressing Enter or clicking on treelist in Edge 42

### ISSUE THREAD

**Issue by matsakyan** [telerik/kendo-ui-core#4529]
### Bug report
Changes to edited task name are not preserved pressing Enter or clicking on treelist in Edge 42. Works as expected on Edge 40, Chrome, Firefox, IE.

NOTE: clicking outside of the table after the edit, saves the changes.

### Reproduction of the problem
Kendo Gantt Chart
Can't change task name in Edge browser, even in kendo [example](https://dojo.telerik.com/APIketos)

1. Edit a cell of the Title column inside the table on the left.
2. Press Enter or click on the table to apply the changes.

### Current behavior
Changes are lost.

### Exepected behavior
Changes are saved.

### Environment
* **Kendo UI version:** 2018.3.911
* **jQuery version:** 1.12.3
* **Browser:** [Edge 42.17134.1.0]

**Comment by matanasov** [comment]
@matsakyan 
I was able to successfully change a task name as shown in the image below. All I did was double-click on a task, change its name in opened popup window and click Save to apply the changes. Is there anything else I miss in this case?

![edge](https://user-images.githubusercontent.com/5861835/45999907-c0210780-c0af-11e8-9989-7685280410c7.png)

**Comment by matsakyan** [comment]
I think you tried in another example because in mentioned one there are no any popup or save button.

**Comment by matanasov** [comment]
@matsakyan 
I don't think so - take a look at the url in the screenshot and compare it with the one from the example you quoted - they are the same. I just use the full screen mode in DoJo.

**Comment by matsakyan** [comment]
![2018-09-26_15-13-13](https://user-images.githubusercontent.com/24270766/46076836-d0b0ab00-c19f-11e8-89cf-80bae2218d33.gif)
The provided gif shows the case which I mentioned. It's very interesting because it works in chrome and older edge, but not in edge 42.

**Comment by matanasov** [comment]
@matsakyan 
I was able to replicate this only on Edge 42 and only when I clicked on the table after editing it. If you edit a cell in the table and then click outside of it (say in the diagram), then it will update as expected. 
In all other browsers (including Edge 40) it worked as expected.

**Comment by matsakyan** [comment]
it's also not working with 'enter' button

**Comment by matanasov** [comment]
I noticed that and noted it in the initial post

**Comment by veselints** [comment]
Check whether it could be reproduced with 2020.3.915
