### ISSUE TITLE
Bug with tooltip

### ISSUE THREAD

**Issue by AnatolyLevchenko** [telerik/kendo-ui-core#4534]
### Reproduction of the problem
1.Open https://docs.telerik.com/kendo-ui/controls/layout/tooltip/how-to/show-on-length-condition
2.Press View

### Current behavior
First time ( on mouse over) row going to flickering

### Expected/desired behavior
Row should not flicker

### Environment

Chrome latest

**Comment by Dimitar-Goshev** [comment]
@AnatolyLevchenko This is a known issue - https://github.com/telerik/kendo-ui-core/issues/3896 . Please follow its progress, I am closing this one as duplicate.
