### ISSUE TITLE
Programmatically deselecting Scheduler does not persist in Chrome

### ISSUE THREAD

**Issue by austinw-fineart** [telerik/kendo-ui-core#4535]
### Bug report
Clearing the selection of a Scheduler programmatically does not persist if the Scheduler updates.

### Reproduction of the problem
* Create scheduler with selectable: true
* Select any slot
* Call scheduler.select(null)
* Navigate scheduler or change view
* First slot will be selected automatically

### Current behavior
After clearing scheduler selection but before navigating, scheduler.select() returns empty array. After navigating, scheduler.select() returns selection of first slot. The change event is also triggered.

### Expected/desired behavior
The Scheduler should behave as if nothing were selected. This behavior is inconsistent, as the Scheduler does not automatically select the first slot if it was never selected upon its creation.

### Environment
* **Kendo UI version:** 2019.2.619
* **jQuery version:** 3.2
* **Browser:** Chrome 76

**Comment by ag-petrov** [comment]
Not reproducible with the latest version
