### ISSUE TITLE
Not visible Spreadsheet cell bottom border in Edit mode

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#4539]
### Bug report
When editing a cell in a Kendo UI Spreadsheet, the bottom border is disappears. The issue starts to reproduce since R1 2018 - 2018.1.117. Reproducible with all LESS and SASS themes.

reported again in 1405318 

### Reproduction of the problem
1. Go to [Spreadsheet Live Demos.](https://demos.telerik.com/kendo-ui/spreadsheet/sorting-filtering).
1. Double click on a cell to enter edit mode.

### Current behavior
The line height is increased when entering edit mode.  This causes the bottom border to be not shown.

### Expected/desired behavior
The [bottom border should be shown with the accurate line height.](https://dojo.telerik.com/@PMcDonou/oHozUvoT)

### Environment
* **Kendo UI version:** 2018.3.911
* **jQuery version:** 1.12.4
* **Browser:** all

**Comment by magdalenaan** [comment]
The issue can be fixed by correcting of the `.k-spreadsheet-cell-editor` height calculation.
