### ISSUE TITLE
It is not possible to set Margin for Donut series in ASP.NET Core Chart

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#4541]
### Bug report

The Series.Margin property in the ASP.NET Core Chart tag helper does not work as expected. It should allow passing a single numeric value (instead of setting separate Top, Right, Bottom, Left values) and apply it to the underlying `series.margin` property. 
The problem seems to come from the JS API, which incorrectly lists the four options:
* `series.margin.top`
* `series.margin.bottom`
* `series.margin.right`
* `series.margin.left`

These properties do not have a meaning for any of the Chart series.

### Environment

* **Kendo UI version:** 2018.3.911

Reported in: 1343651

**Comment by MilenaCh** [comment]
CI-Wrappers-Generation build should be fixed
