### ISSUE TITLE
ToolBar click event for splitButton's menuButtons does not fire when the splitButton is in overflow

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4542]
### Bug report
The splitButton's own click event does not fire for its menuButtons, when the splitButton is displayed under the ToolBar's overflow button.

### Reproduction of the problem
1. Open the Toolbar Events demo - https://demos.telerik.com/kendo-ui/toolbar/events
1. Resize the window so that the splitButton is moved under the overflow button.
1. Open the overflow popup.
1. Click on the Action 1 button.

### Current behavior
The splitButton click event does not fire.

NOTE: if the main button of the splitButton is clicked, the event is fired.

### Expected/desired behavior
The splitButton click event fires regardless of the splitButton being in overflow or in main toolbar. 

### Environment
* **Kendo UI version:** 2024.2.519
* **Browser:** all

**Comment by veselints** [comment]
Also reported in Ticket ID: 1426013

**Comment by GaloisGirl** [comment]
It works fine if the splitButton items have their own click handlers defined. 

I think a more accurate description would be:
1. when not overflown, the children without their own handler properly inherit the click handler from the parent
2. when overflown, such children don't inherit the handler.

**Comment by IvanDanchev** [comment]
Also reported in Ticket ID: 1463102

**Comment by icesasoftcorp** [comment]
the problem is when it is for a mobile phone and the buttons overflow the menubuttons click does not work.
use the @GaloisGirl example and it is emulated on a mobile, and the click does not work

**Comment by GaloisGirl** [comment]
Revisiting this today I noticed that per the documentation, the children don't have their own click handlers: https://docs.telerik.com/kendo-ui/api/javascript/ui/toolbar/configuration/items.menubuttons 

However, you can declare such handlers, and they work. 

I'd really prefer for them to have their own click handlers: if I'm using different buttons, it's for doing different things.

**Comment by Dimitar-Goshev** [comment]
@GaloisGirl  @icesasoftcorp We have logged a [Feature Request](https://feedback.telerik.com/kendo-jquery-ui/1546592-toolbar-subitem-clickhandlers-do-not-work-when-overflown) for adding official support for separate subitem click handler and you may vote for it.

**Comment by martintabakov** [comment]
[In the Toolbar events demo](https://demos.telerik.com/kendo-ui/toolbar/events), the splitButtonClickHandler set for the SplitButton items is not thrown when in overflow.
