### ISSUE TITLE
MaskedTextBox has no border on focus out in Vue wrappers

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4543]
### Bug report
When v-model is used in Kendo UI MaskedTextBox for Vue and the input is focused out, the border disappear.

### Reproduction of the problem
1. Open the [Basic Usage Demo](https://www.telerik.com/kendo-vue-ui/components/inputs/maskedtextbox/#toc-basic-usage)
2. Enter value in the MaskedTextBox
3. Press 'Tab' key.

The issue is also reproducible when using v-model in AutoComplete

### Current behavior
The border disappears. There is additional 'k-textbox' class to the 'span.k-widget.k-maskedtextbox' element.

### Expected/desired behavior
The appearance of the MaskedTextBox should be consistent. 

### Environment
* **Kendo UI version:** 2018.3.911

**Comment by TeyaVes** [comment]
Happening due to the following fix: https://github.com/telerik/kendo-ui-core/issues/4181
Similar to: https://github.com/telerik/kendo/issues/8902
