### ISSUE TITLE
Items cannot be selected on mobile devices if the AutoComplete uses templates

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4548]
### Bug report
On mobile devices an item cannot be selected in the AutoComplete if it has templates configured.

### Reproduction of the problem
Reproducible in the [templates demo](https://demos.telerik.com/kendo-ui/autocomplete/template) and in the following [dojo](https://dojo.telerik.com/eCeYiCIm) example.
1. Tap on the AutoComplete input area. 
2. Enter "a".
3. Tap on an item => the dropdown closes and item selection does not occur. 

### Current behavior
Items cannot be selected.

### Expected/desired behavior
Items can be selected.

### Environment

* **Kendo UI version:** 2018.3.911
* **jQuery version:** x.y
* **Browser:** [Mobile Chrome XX (Android; emulator)]

**Comment by jivanova** [comment]
Duplicated with #4564. Fix has been included and use #4564 to track the progress.
