### ISSUE TITLE
Tooltip doesn't hide on mouseleave when showOn is set to "focus mouseenter"

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#4553]
### Bug report
If I set the showOn attribute to "focus mouseenter", the tooltip content will show on mouse over, but will not disappear on mouse leave. The user has to click somewhere else to close the tooltip.

Regression since R3 2017, caused by fixing the[ following issue](https://github.com/telerik/kendo-ui-core/issues/1908). Before fixing it, the tooltip did not show text, but was closing as expected in the scenario below.

### Reproduction of the problem
http://dojo.telerik.com/aHIzeYuz
Hover the second input and leave it.

### Current behavior
The tooltip doesn't hide

### Expected/desired behavior
The tooltip hides on mouse leave, as with [R2 2017 SP1 (2017.2.621)](http://dojo.telerik.com/ELUJuBOG)

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browsers:** all

**Workaround:**
http://dojo.telerik.com/edAHOCUQ

**Comment by Dimitar-Goshev** [comment]
The [Enhancement item ](https://github.com/telerik/kendo-ui-core/issues/3933)I referenced above is proposing a setting to resolve this issue. I closed it to avoid duplication. The issue should be discussed and resolved in this issue.
