### ISSUE TITLE
Column resize handle is incorrectly displayed with multi-column headers

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-ui-core#4555]
### Bug report

Column resize handle is shown when hovering a multi header column. A side effect is that its position is not calculated correctly and the horizontal scrollbar is updated.

Reported in Ticket ID: 1344058

### Reproduction of the problem
1. Open the Dojo example: http://dojo.telerik.com/AMENowuT/4
2. Hover the "Electricity" column (also happens with "Natural Gas").

### Current behavior
Column resize handle is shown when hovering a multi header column. A side effect is that its position is not calculated correctly and the horizontal scrollbar is updated.

### Expected/desired behavior
Column resize handle should not be shown. Resizing multi column headers is not supported. The side effect of changing the horizontal scrollbar of the grid table should not occur.

### Environment

* **Kendo UI version:** 2018.3.911
* **jQuery version:** 1.9
* **Browser:** all

**Comment by devineloper** [comment]
This seems to still be an issue in the latest release 2019.2.514
Updated example:
http://dojo.telerik.com/AMENowuT/12

**Comment by Stamo-Gochev** [comment]
@devineloper 
Can you clarify which column you are hovering and what is the result? I am not able to reproduce the concrete behavior as explained in the bug report. In addition, I am not able to resize any of the columns from your Dojo example - http://dojo.telerik.com/AMENowuT/12
