### ISSUE TITLE
MultiColumnComboBox item selection does not work on mobile devices

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4556]
### Reproduction of the problem
Reproducible in the [demos](https://demos.telerik.com/kendo-ui/multicolumncombobox/index).
1. Tap on the dropdown arrow to open the dropdown
2. Tab on an item in the dropdown.

### Current behavior
The dropdown closes and the tapped item is not selected.

### Expected/desired behavior
The dropdown closes and the tapped item is selected. 

### Environment

* **Kendo UI version:** 2018.3.911
* **jQuery version:** x.y
* **Browser:** [Mobile Chrome XX (Android; emulator)]

**Comment by zdravkov** [comment]
Fixing [commit](https://github.com/telerik/kendo/commit/8400eeb9008c993b5f9bb0dcdb8f19e50a391f79)

**Comment by jivanova** [comment]
Fixed with: https://github.com/telerik/kendo-ui-core/issues/4564. Resolved issue with **templates** as well as the default MultiColumnComboBox rendering.
