### ISSUE TITLE
Menu popup is not shown on hover with Chrome and Firefox on touch devices

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#4559]
### Bug report

When hovering menu item using the mouse, the popup doesn't show. The issue is observable in FireFox and Chrome on touch capable screen devices. Not reproducible in IE and Edge. The menu popup could be opened on mouse click.

### Reproduction of the problem
http://dojo.telerik.com/ibiPIcaT
Hover the menu using the mouse

### Current behavior
The menu popup shows

### Expected/desired behavior
The menu popup doesn't show

Note: The issue is introduced with version 2018.3.911

### Environment

* **Kendo UI version:** 2018.3.911
* **jQuery version:** jquery-1.12.4
* **Browser:** Chrome/Firefox Lenovo IdeaPad Yoga 13 and DELL

**Comment by jivanova** [comment]
Retest: https://github.com/telerik/kendo-ui-core/issues/495
