### ISSUE TITLE
The ToolTip is not automatically hidden on mouseleave when the ToolTip is initialized for a Button

### ISSUE THREAD

**Issue by JoseGoncalves** [telerik/kendo-ui-core#456]
Test case: http://dojo.telerik.com/@jmpg/ePAN/2

**Comment by JoseGoncalves** [comment]
Are you planning to address this issue soon?

**Comment by KirilNN** [comment]
Hi @JoseGoncalves,

I am afraid that at the moment this issue cannot be fixed, you can use the workaround provided in the other GitHub issue here:

https://github.com/telerik/kendo-ui-core/issues/284

**Comment by JoseGoncalves** [comment]
Hi @KirilNN,

A workaround, by definition, is something that provides the functionality specified using a different (non standard) implementation. What you called a workaround is, as I indicated in my comment in #284, not functional, so I disagree that you close this issue, because this is, in my understanding, a bug in the Tooltip widget.

Is'nt possible to add the fix bb19bce240a75ced53b3452144a2e3412b0ee3f3 conditionally, i.e., activated by some configuration option? In this way it would solve my test scenario issue (activating that config) and would not break other test scenarios.

**Comment by KirilNN** [comment]
@JoseGoncalves 

Currently we do not plan on adding this conditional statement to the code. You can fork the repository and add it by yourself, if you believe that this will be fix for the issue.
