### ISSUE TITLE
Item can not be selected when using span or div element in template in ComboBox, AutoComplete and DropDownList

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4564]
### Bug report

When 'span' or 'div' element is used in template in ComboBox, DropDownList and AutoComplete, items can not be selected on mobile. 

### Reproduction of the problem
1. Open[ the Dojo example](https://dojo.telerik.com/UwUpItEq) on mobile device.
2. Enter text (for example 'A') and try to select an item

### Current behavior
No item is selected and only the entered text is in the input.

### Expected/desired behavior
Item should be selected correctly.

### Environment

* **Kendo UI version:** 2018.3.911

**Comment by mcamauryasatish** [comment]
How to fix that issue? No solution till now?
