### ISSUE TITLE
Allow setting initial files from the model in Upload taghelper

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4569]
### Bug report

Currently it is not possible to set the initial files from the model.

Expected 
Should be able to set the initial files from the model - one possible solution is to allow the following markup:
```
<kendo-upload drop-zone="drop-zone1" name="files">     

            <async save-url="asd" />

            <validation allowed-extensions="@Model.Extensions" />

            <files>
                @foreach (var item in @Model.Extensions)
                {
                    <file name="somename" extension="some"></file>
                }
            </files>

        </kendo-upload>
```

### Environment

* **Kendo UI version:** 2018.3.911

**Comment by tsafadi** [comment]
Has this been solved? It doesn't seem to work in the latest version...
