### ISSUE TITLE
dataSource transport connection option is missing in the API reference 

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4574]
### Bug report

The dataSource transport.connection option is currently not documented in the API reference. Thus, the option is not correctly generated for the wrappers.

### Reproduction of the problem

The issue could be reproduce when trying to configure the :transport-connection prop with the Vue wrappers for example.

### Expected/desired behavior

The transport.connection option should be documented and also added/generated for all of the wrappers.

### Environment

* **Kendo UI version:** 2018.3.911
* **Browser:** [all]

**Comment by zdravkov** [comment]
The property seems to be already documented [here](https://docs.telerik.com/kendo-ui/api/javascript/data/pivotdatasource/configuration/transport#transportconnection). In Vue wrapper its settings are [available ](https://www.telerik.com/kendo-vue-ui/components/datasource/api/pivotdatasource/TransportProps/)through the transport-connection-cube and transport-connection-catalog properties.
