### ISSUE TITLE
Incorrect mobile dropdown position on scrolling the page (mobile devices)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4577]
### Bug report
The issue is reproducible with the Mobile Application's **useNativeScrolling** option set to **true**.

### Reproduction of the problem
[Dojo ](http://dojo.telerik.com/ijIvogEn/8) example.
1. Run the example on a mobile device or in Chrome's emulator.
2. Scroll down the page so that the second dropdown is closer to the top edge of the screen. 
3. Click the dropdown => the list of options is not visible

Workaround - set fixed position to the ".km-popup" element:

```
.k-animation-container.km-popup {
    position: fixed !important; top: auto !important; bottom: 0 !important;
}
```

### Current behavior
the list of options is not visible

### Expected/desired behavior
the list of options is visible

### Environment

* **Kendo UI version:** 2019.3.619
* **jQuery version:** x.y
* **Browser:** [Mobile Chrome XX (Android, IOS7)]

**Comment by ag-petrov** [comment]
Closing this as the mobile suite is now depricated
