### ISSUE TITLE
Not triggered change event when a selected item is deleted through MultiSelect's clear button and then selected again

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#4583]
### Bug report
When a selected item is deleted through MultiSelect's clear button and then the same item is selected again, change event is not fired.

The issue starts to reproduce since R1 2018 and seems related to fixing the following [change event issue](https://github.com/telerik/kendo-ui-core/issues/3872).

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/multiselect/events
1. Click on MultiSelect - dropdown expands
1. Click on Africa to select it - change event is fired
1. Click on MultiSelect's clear button - Africa is deleted and change event is fired
1. Click on MultiSelect - dropdown expands
1. Click on Africa to select it

### Current behavior
Change event is NOT fired. Only select event is fired for Africa.

### Expected/desired behavior
Change event is fired. Also select event is fired for Africa.

### Environment
* **Kendo UI version:** 2018.3.911
* **Browser:** [all]

**Comment by zdravkov** [comment]
fixed with this [commit].(https://github.com/telerik/kendo/commit/944f52897b62f0b1190765683ded7c1d17d4ac7f)
