### ISSUE TITLE
TextBox wrapper Format method does not set the format 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4590]
### Bug report
The TextBox wrapper has a Format method similar to that of the NumericTextBox, but it does not actually set the format. 

### Reproduction of the problem

```
@Html.Kendo().TextBoxFor(model => model.ProductID).Format("c3")
```

### Environment

* **Kendo UI version:** 2018.3.911
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by boyandim** [comment]
The format option that expects the TextBox wrapper is actually [C# String format ](https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=netframework-4.7.2). For example the format will work as expected with the following code: 

`@Html.Kendo().TextBoxFor(model => model.ProductID).Format("{0:C3}")`

**Comment by dtthom09** [comment]
When I use this formatting and try to update my datamodel for my razor page like `$('#DataModel').val(value).change()` it does not display the updated value. It only shows the updated value with the correct formatting if I click the field.. I know this is a few years old but could I get some help? Thanks
