### ISSUE TITLE
Pasted text in MutliSelect input is not aligned properly

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#4592]
### Bug report
When a text of an item is pasted in MultiSelect, the pasted text is not properly aligned.

### Reproduction of the problem
1. Open the [basic Demo](https://demos.telerik.com/kendo-ui/multiselect/index) or [this dojo](https://dojo.telerik.com/aGOsezIP).
2. Paste 'Steven white'

### Current behavior
Only the end of the text is visible. ([screencast](https://www.screencast.com/t/6Z2bOILetyJA))
The result when 'Attendees' is pasted:
![image](https://user-images.githubusercontent.com/14364791/143584275-1bd85e59-3210-49a1-a876-770135a2d6f4.png)

### Expected/desired behavior
The entire pasted text should be visible.

### Environment

* **Kendo UI version:** 2019.2.619
* **Browser:** [ All  ]

**Comment by Zkriya** [comment]
Same problem on macOS

**Comment by nelito987** [comment]
The issue is reported in ticket ID: 1544201
The issue can be replicated in all browsers, not only on touch devices when the content is pasted through using the mouse right-click (not Ctrl + V)

**Comment by eyupyusein** [comment]
The issue can no longer be reproduced in newer versions.
