### ISSUE TITLE
MultiSelect clear all items button is not visible in Bootstrap 3 theme, when the input is hovered

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4601]
## Bug report
MultiSelect clear all items button is not visible in Bootstrap 3 theme, when the input is hovered (while icon on white background).

Related to https://github.com/telerik/kendo/issues/8725
related to https://github.com/telerik/kendo/issues/9051

## Reproduction of the problem
Could be observed on the [MultiSelect Index demo](https://demos.telerik.com/kendo-ui/multiselect/index)

## Environment
Kendo UI version: 2018.3.1017
Browser: [all]

**Comment by veselints** [comment]
The following CSS rule will apply color to the icon:

```css
.k-multiselect>.k-multiselect-wrap>.k-i-close {
  color: #357ebd;
}
```

**Comment by Dimitar-Goshev** [comment]
Closing this as a duplicate of https://github.com/telerik/kendo-ui-core/issues/4602
Duplicated due to GitHub outage.
