### ISSUE TITLE
MultiSelect clear all items button is not visible on hover in Bootstrap 3

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#4602]
### Bug report
MultiSelect clear all items button is not visible in Bootstrap 3 theme (while icon on white background).
Related to https://github.com/telerik/kendo/issues/8725 and https://github.com/telerik/kendo/issues/9051

### Reproduction of the problem
1. Go to [MultiSelect Index demo](https://demos.telerik.com/kendo-ui/multiselect/index) and choose Bootstrap 3 theme
1. Hover over the first MultiSelect input - clear all button should be visible at the right side of the widget.
1. Hover over the right side of the MultiSelect - cursor becomes pointer and the tooltip of the clear icon is visible.

NOTE: if the first MultiSelect is focused and the mouse is not over it, then the clear button is visible.

### Current behavior
![image](https://user-images.githubusercontent.com/6614183/47283072-5e8a8500-d5ea-11e8-83fc-5d7040040b7d.png)

### Expected/desired behavior
Clear button is visible on MultiSelect hover and MultiSelect clear button hover.

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by veselints** [comment]
The following CSS rule will apply color to the icon:

```css
.k-multiselect>.k-multiselect-wrap>.k-i-close {
  color: #357ebd;
}
```
