### ISSUE TITLE
Combobox Inview Alignment

### ISSUE THREAD

**Issue by alpkarli** [telerik/kendo-ui-core#4603]
### Bug report

Kendo Combobox is not showing correct item if I use service to get value. (Probably it is not related with only service) It acts inconsistent. It doesn't focus fisrt search letter many times and also when I press backspace it doesn't focus correct one either. Align problem is not limited by text length.

### Reproduction of the problem

https://stackblitz.com/edit/angular-yyafdd-6cvlj7

### Current behavior

Popup doesn't focus and align correct search.

![selected1](https://user-images.githubusercontent.com/28437603/47284818-6568c600-d5f1-11e8-85a3-866443a3db51.png)

### Expected/desired behavior

Popup auto scroll to focused item.

![selected2](https://user-images.githubusercontent.com/28437603/47284825-6dc10100-d5f1-11e8-980a-377eaf15fa98.png)

### Environment

* **Browser:** [all]

**Comment by tsvetomir** [comment]
Seems to be working correctly in the latest version, [see snippet](https://stackblitz.com/edit/angular-yyafdd-vyvxnj?file=app/symbol-list.ts).

If the issue is still present, I'd like to ask you to open a bug report in https://github.com/telerik/kendo-angular/issues

**Comment by alpkarli** [comment]
Hi,

It occurs if I use backspace to clear search string and write again. I opened an issue on this address: https://github.com/telerik/kendo-angular/issues/2110
