### ISSUE TITLE
Unable to remove MultiSelect's single tag, although there are no selected items

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#4611]
### Bug report
NOTE: Regression since R2 2018 (2018.2.516).

If a single tag MultiSelect is blurred on filtering and then on refocusing it backspace is pressed, MultiSelect's value is cleared, but the single tag remains and states that there are selected items.

### Reproduction of the problem
1. Run https://dojo.telerik.com/uhuvUwIw
1. Open browser console and check that MultiSelect's value is logged every 2 seconds - initial value is ["Andrew Callahan", "Andrew Fuller"]
1. Click on MultiSelect input and type a
1. Click outside the MultiSelect to blur it - filter is removed.
1. Click on MultiSelect input and press Backspace.

### Current behavior
MultiSelect value is cleared (value is logged as [ ]). But the single tag remains visible and states that there are two selected items. It is not possible to delete the single tag. If **Esc** key is pressed, a JavaScript error is thrown:
Uncaught TypeError: l.select(...).done is not a function

### Expected/desired behavior
MultiSelect value is cleared (value is logged as [ ]). The single tag is removed. Reproducible with the following [R1 2018 SP1 Dojo](http://dojo.telerik.com/iruWuKOz).

### Workaround
Handle MultiSelect's change event as follows:
```
            function onChange(e) {
              if(!e.sender.value().length){
                e.sender.element.closest(".k-multiselect").find(".k-button").remove();
              }
            }
```

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

Reported in ticket ID: 1347717

**Comment by zdravkov** [comment]
related to this one #3963

**Comment by jivanova** [comment]
Related to: https://github.com/telerik/kendo/commit/b3e94a6037e9f9b06c290a895d90a9d157db84b3
