### ISSUE TITLE
TreeList column classes are not persisted after editing a cell

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4615]
### Bug report

TreeList column classes are not persisted after editing a cell.

### Reproduction of the problem

1. https://dojo.telerik.com/OFireGAl
1. edit a cell from the "position" column

### Expected/desired behavior

The custom classes are persisted. Similar to the Grid:
https://dojo.telerik.com/AZiCazaQ

### Environment

* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by pKrav75** [comment]
Hello any chance to know when this is going to be corrected (next coming version, later...)???

**Comment by Stamo-Gochev** [comment]
@pKrav75 A fix has been pushed. After testing, the corresponding milestone will be set (targeting R1 2019) and it will be available in the internal builds before that.
