### ISSUE TITLE
Q3 code throws error for scrollView with 1 data item (but not Q2 code)

### ISSUE THREAD

**Issue by codylindley** [telerik/kendo-ui-core#462]
I've been working on an mobile application [https://github.com/codylindley/whatsername](https://github.com/codylindley/whatsername)

When I moved from Q2 to Q3 code my scrollView widget broke. Which breaks the entire app. I've reduced the issue to a  datasource bug.

The following code breaks (throws JS error) with Q3 Kendo UI code, but not with Q2.

http://dojo.telerik.com/@codylindley/UwEWU/6

I've explained issue here in a video: http://screencast.com/t/lJsCbC7U3z

**Comment by codylindley** [comment]
Was this fix included in the 3.1204 code? When I'm still getting this error in Q3 code, but am not clear when this fix will be in bower.

**Comment by underlog** [comment]
The fix can't be in the 1204, since it was introduced after that - you can check the date of the commit and do the math. 

We will publish the upcoming SP in Bower.

**Comment by codylindley** [comment]
Doh. forgive my poorly asked question. Next beer on me.
