### ISSUE TITLE
Wrong horizontal scrolling in a navigatable RTL Grid in Edge browser

### ISSUE THREAD

**Issue by Sh3R** [telerik/kendo-ui-core#4620]
### Bug report

Wrong horizontal scrolling in a navigatable RTL Grid in Edge browser

### Reproduction of the problem
http://dojo.telerik.com/eYipaPEl

### Expected/desired behavior
The grid scrolls to the selected/navigated cell.

### Environment

* **Kendo UI version:** 2018.3.911
* **jQuery version:** x.y
* **Browser:** [Edge browser]

**Comment by sspasova** [comment]
The issue is fixed. Tested with Kendo UI version 2023.3.1114 on Edge browser. I am linking a working Dojo - https://dojo.telerik.com/eYipaPEl/6
