### ISSUE TITLE
Missing styles for groups in Bootstrap Sass theme

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#4621]
[https://demos.telerik.com/kendo-ui/dropdownlist/grouping](https://demos.telerik.com/kendo-ui/dropdownlist/grouping)

All Kendo UI select elements (except for MultiColumnComboBox) have missing styles for grouping functionality:

![grouping_bootstrap](https://user-images.githubusercontent.com/7159157/47645784-a83f1680-db7a-11e8-8a45-823d7f28ba16.png)

**Comment by Dimitar-Goshev** [comment]
Duplicate of https://github.com/telerik/kendo-themes/issues/138
