### ISSUE TITLE
Virtualized widget does not properly select its value when the remote ValueMapper call is delayed

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4634]
### Bug report
Virtualized widget does not properly select its value when the remote ValueMapper call is delayed

### Reproduction of the problem
* Run the below project
[TelerikAspNetCoreMultiSelect.zip](https://github.com/telerik/kendo-ui-core/files/2534515/TelerikAspNetCoreMultiSelect.zip)
* Select an item from the first page of the MultiSelect;
* Type 100 and select fast the first suggested item;
* Open fast the drop-down, scroll several times and select other values;
* Some of the values will be duplicated;

### Expected/desired behavior
No duplicated values should be present

### Environment
* **Kendo UI version:** 2018.3.911
* **Browser:** [all]

**Comment by mparvanov** [comment]
Not reproducible with 2019.2.619
