### ISSUE TITLE
events don't work

### ISSUE THREAD

**Issue by Okkkks** [telerik/kendo-ui-core#4637]
### Bug report
Hi, guys.

I use kendo-charts-vue-wrapper, but all chart's events don't work... 
I use it by documentation, but example in documentation also don't work(see attached video)...

Could you check it and reply me, please.

Thank you.

### Environment

* **Kendo UI version:** 2018.3.1017-dev.1023
* **Browser:** [all] 

[01-Nov-18 12-21-33 PM.zip](https://github.com/telerik/kendo-ui-core/files/2538004/01-Nov-18.12-21-33.PM.zip)

**Comment by Okkkks** [comment]
Thank you for reply.
Now it work ( example from documentation with  @seriesClick="onAxisLabelClick").
But it isn't work in my code... =(
I updated  kendo-charts-vue-wrapper to last version(2018.3.1025) today,
but it didn't help...
Could you help me, please.
What am I doing wrong?

![image](https://user-images.githubusercontent.com/23074189/47907036-8952c400-de9b-11e8-8745-b723cd6f26c6.png) and small video
[02-Nov-18 12-37-34 PM.zip](https://github.com/telerik/kendo-ui-core/files/2541888/02-Nov-18.12-37-34.PM.zip)

**Comment by Dimitar-Goshev** [comment]
@Okkkks 
The proper event casing is seriesclick (no caps). In a Vue app, the props are case sensitive, thus seriesClick does not work. It works in StackBlitz, because it uses HTML and it is not case insensitive.
