### ISSUE TITLE
Scheduler changes event duration when drag and dropped

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4639]
### Bug report
When creating an "All Day" event that spans multiple days it changes to the wrong number of days when landing on a daylight savings time change date.

### Reproduction of the problem
Make sure you've changed the timezone to your machine (e.g. to Central America)
1. Open [https://dojo.telerik.com/UletiPaC](https://dojo.telerik.com/UletiPaC)
2. Create an all-day event that spans three days.
3. Drag that event to start on Nov 2nd or Nov 3rd (2013 calendar from the dojo demo)
4. See the span change to span just two days.

### Current behavior
Scheduler changes event duration when drag and dropped.

### Expected/desired behavior
The scheduler should not change event duration when drag and dropped.

### Environment

* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible with R3 2019 SP1 (2019.3.1023) - https://dojo.telerik.com/@Dimitar-Goshev/IJAZIyoR
