### ISSUE TITLE
Kendo.Mvc.Export.dll SetCellValue method should handle null values

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#4640]
### Bug report

Ticket ID: 1349014

### Reproduction of the problem

Create a template project with the VSX and pass null for `OrderDate` property. Use the same server side logic as in the official demo:

[Server-export](https://demos.telerik.com/aspnet-mvc/grid/server-export)

### Current behavior

![image](https://user-images.githubusercontent.com/10980842/47858356-8d77d680-ddf4-11e8-8992-ef4a44ad0e05.png)

If the columns with null values are removed the method does not throw.

### Expected/desired behavior

Same as the client-side export - leave an empty cell.

### Environment

* **Kendo UI version:** 2018.3.1017

**Comment by Alex-Bubblemaster** [comment]
Workaround: 

- go to ~\telerik.ui.for.aspnetmvc.VERSION.commercial-source\src\Kendo.Mvc.Export\Kendo.Mvc.Export and add a value for nulls in the Export.cs file 

```
 private static void SetCellValue(ICellExporter cell, object value)
        {
            if (value == null) {
                value = string.Empty;
            }

            switch (Type.GetTypeCode(value.GetType()))
            {
                case TypeCode.Byte:
                case TypeCode.Char:
                case TypeCode.Decimal:
                case TypeCode.Double:
                case TypeCode.Int16:
                case TypeCode.Int32:
                case TypeCode.Int64:
                case TypeCode.SByte:
                case TypeCode.Single:
                case TypeCode.UInt16:
                case TypeCode.UInt32:
                case TypeCode.UInt64: cell.SetValue(Convert.ToDouble(value)); break;
                case TypeCode.DateTime: cell.SetValue((DateTime)value); break;
                case TypeCode.Boolean: cell.SetValue((bool)value); break;
                default: cell.SetValue(value.ToString()); break;
            }
        }
```
- build the project 
- use the Kendo.Mvc.Export.dll and Telerik.SpreadStreamProcessing.dll from the \bin folder

**Comment by TsvetinaIvanova** [comment]
Also reported in 1388564.

**Comment by PMcDonough11** [comment]
Also reported in 1401160

**Comment by Alex-Bubblemaster** [comment]
Also reported in 1404000. Raising priority.
