### ISSUE TITLE
Multiselect clear button does not clear values in tagmode single when using angular.js bindings

### ISSUE THREAD

**Issue by k290** [telerik/kendo-ui-core#4646]
### Bug report

This works correctly in 2018.2.822, but broke in 2018.3.x

### Reproduction of the problem
This has been reproduced here:.  https://dojo.telerik.com/ASArONOG
Note that the paragraph tag that displays the selected items does not change when the select is cleared with the 'x' button.

### Expected/desired behavior
Clicking the clear button should clear the values and update the bindings, in the same way it did in 2018.2.x
[https://dojo.telerik.com/opaCUReF](https://dojo.telerik.com/opaCUReF)

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** 3.3.1
* **Browser:** [all] 
* **Angular version:** 1.7.2 or 1.7.3

**Comment by mparvanov** [comment]
Releated to:

[Unable to remove MultiSelect's single tag, although there are no selected items #4611](https://github.com/telerik/kendo-ui-core/issues/4611)

**Comment by zdravkov** [comment]
also connected with this one - #3872

**Comment by k290** [comment]
Seems fixed in 2018.3.1114
