### ISSUE TITLE
Clearing multiSelect selected items with tagmode set to single does not fire change event

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#4649]
### Bug report

When the MultiSelect's tagMode is set to single, and the user attempts to clear the items using the clear button, [the change event](https://docs.telerik.com/kendo-ui/api/javascript/ui/multiselect/events/change) does not fire as it does using tagMode set to multiple.

### Reproduction of the problem
The issue can [be observed in the following Dojo.](https://dojo.telerik.com/@PMcDonou/AgOdOqeF)

Steps to reproduce:
1.  Add a couple of items into the MultiSelect
2.  Click the clear button

The change event does not fire.

### Expected/desired behavior
The change event should fire when the clear button is clicked.  This [dojo shows the expected behavior using version 2018.3.911.](https://dojo.telerik.com/@PMcDonou/aFULitoN)

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** 1.12
* **Browser:** [all]

**Comment by mparvanov** [comment]
Related to: #4646

**Comment by zdravkov** [comment]
also connected with this one - #3872
