### ISSUE TITLE
Kendo Window Title - Not showing html encoded characters

### ISSUE THREAD

**Issue by mspace** [telerik/kendo-ui-core#4653]
### Reproduction of the problem

Working example on: https://dojo.telerik.com/iqoxiNIy

      <div id="bla"></div>     
      <script>
        $("#bla").kendoWindow({
          visible: false,
          draggable: true,
          resizable: true,
          modal: true,
          animation: false,
          title: {
            encoded: false
          }
      });
        var a = $("#bla").data("kendoWindow");
        a.title("U<b>ż</b>ytkownik &#225;"); // kendo title should display: >U<b>ż</b>ytkownik á
        a.open();
      </script>

### Expected/desired behavior

Kendo title should respect html encoded characters and displayed them encoded, not as they are.
-> U<b>ż</b>ytkownik á

### Environment

* Kendo UI version:2018.3.1017 
* jQuery version:jquery-1.12.3
* Browser: [all]

**Comment by Juveniel** [comment]
[The title() method](https://docs.telerik.com/kendo-ui/api/javascript/ui/window/methods/title) supports an Object parameter that allows the encoded option to be configured. Taking this into consideration, you should be able to set the non encoded value as follows:
```js
a.title({ encoded: false, text: "U<b>ż</b>ytkownik &#225;" })
```

I have also updated [the Dojo example](https://dojo.telerik.com/iqoxiNIy/11) for your reference.

**Comment by mspace** [comment]
Thank you for the solution. It would be very helpful (also for other Kendo users) if this usage would be added in the official Kendo Window API title documentation.

**Comment by mspace** [comment]
It turns out this doesn't work when Kendo 2017.3.1026 is used. This was fixed in later releases (2018 and on).

**Comment by mspace** [comment]
Just found out that this feature was added only in kendo 2018+, and we are using 2017.3.1026 version
