### ISSUE TITLE
JS exception under IE when exporting to PDF with images with empty src

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/kendo-ui-core#4658]
### Bug report

Under IE when paper size is letter, there are forced page breaks and images with empty src attribute in a table, the PDF export may not work or will result in JS errors (`Unable to get property 'removeChild' of undefined or null reference`) and extra blank pages. May also be related the the CORS images in the content.

### Reproduction of the problem

Behaves differently in a dojo, perhaps because of the iframe, the errors are not reported in the console and it often appears as if nothing is happening, or a PDF is not generated.

Here is a local repro from the [original sample](https://dojo.telerik.com/OWowIJIt/3):

* [repro-ie-blank-image-export-issue.zip](https://github.com/telerik/kendo-ui-core/files/2562196/repro-ie-blank-image-export-issue.zip)

Most of the `<img src="">` were commented out, only one is left. Removing the pdf settings (or some combinations of them, like changing the paper size to A4, or removing page breaks) alleviates the issue.

To reproduce, click the "PDF Export multiple Images" button. You can compare the behavior with the other buttons as they export less content.

### Environment

* **Kendo UI version:** 2018.3.1027
* **jQuery version:** 1.12.4
* **Browser:** IE 11

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
