### ISSUE TITLE
Column width is not respected in Virtualized MultiColumnComboBox 

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#4663]
### Bug report
Column width is not respected in Virtualized MultiColumnComboBox.

### Reproduction of the problem
1. http://dojo.telerik.com/uSiWelex/2
1. Expand the dropdown

### Current behavior
Although all columns have set width as required per [documentation](https://docs.telerik.com/kendo-ui/controls/editors/multicolumncombobox/virtualization), the width is not applied to the columns and they are as wide as needed to fit all their text.
![image](https://user-images.githubusercontent.com/6614183/48399328-013aad00-e72c-11e8-9308-85ce68bbbb2a.png)

### Expected/desired behavior
Columns obey the width set and overflowing text is trimmed with ellipsis:
![image](https://user-images.githubusercontent.com/6614183/48399470-64c4da80-e72c-11e8-9f6f-4dde5b658b3f.png)

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by TsvetinaIvanova** [comment]
Also reported in 1357217.
