### ISSUE TITLE
Resolve compatibility warnings for kendo.all.min.js reported by jQuery Migrate 3.0.1

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#4665]
### Bug report

The following compatibility warnings for kendo.all.min.js are reported by jQuery Migrate 3.0.1
[https://dojo.telerik.com/ADAYuqom
](https://dojo.telerik.com/ADAYuqom
)

- [x] jquery-migrate-3.0.1.js:76 JQMIGRATE: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudosmigrateWarn @ jquery-migrate-3.0.1.js:76
get @ jquery-migrate-3.0.1.js:89
- [x] jquery-migrate-3.0.1.js:76 JQMIGRATE: jQuery.expr.filters is deprecated; use jQuery.expr.pseudos
migrateWarn @ jquery-migrate-3.0.1.js:76
get @ jquery-migrate-3.0.1.js:89
- [x] jquery-migrate-3.0.1.js:76 JQMIGRATE: jQuery.event.props.concat() is deprecated and removed
migrateWarn @ jquery-migrate-3.0.1.js:76
get @ jquery-migrate-3.0.1.js:89
- [x] jquery-migrate-3.0.1.js:76 JQMIGRATE: jQuery.fn.click() event shorthand is deprecated
migrateWarn @ jquery-migrate-3.0.1.js:76
jQuery.fn.(anonymous function) @ jquery-migrate-3.0.1.js:476

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** 3.3.1
* **jQuery Migrsate version:** 3.0.1
* **Browser:** [all ]

**Comment by shibaev** [comment]
Note that you will get even more warnings from specific components. For example, datepicker:
https://dojo.telerik.com/uMosEGix

On page load 2 additional warnings are generated:
- [ ] JQMIGRATE: jQuery.fn.removeAttr no longer sets boolean properties: disabled
- [ ] JQMIGRATE: jQuery.fn.removeAttr no longer sets boolean properties: readonly

And when you open first datepicker more warnings occur:
- [ ] JQMIGRATE: jQuery.fn.unbind() is deprecated
- [ ] JQMIGRATE: jQuery.fn.bind() is deprecated
- [ ] JQMIGRATE: jQuery.unique is deprecated; use jQuery.uniqueSort
- [ ] JQMIGRATE: jQuery.fn.focus() event shorthand is deprecated

**Comment by matanasov** [comment]
It seems like some issues were introduced with the fix.
We will investigate some more time for more in-depth testing
