### ISSUE TITLE
Kendo Scheduler - Impossible to scroll up/down in an event on mobile (touch)

### ISSUE THREAD

**Issue by chiznoodle** [telerik/kendo-ui-core#4672]
### Bug report

On a mobile device, with the Scheduler set on mobile version (mobile: "phone") it is impossible to scroll up or down in an event.

### Reproduction of the problem
http://runner.telerik.io/fullscreen/ozUXIzej

### Current behavior
Please, on the link above try to add an event by clicking anywhere on the scheduler. Then on the new screen try to scroll up or down. It works if you start to scroll with the cursor/finger on the top "Event" bar, but it does not work if you start with your cursor/finger elsewhere on the table(from the first line "Title" to the last line "Attendees").

### Expected/desired behavior
To be able to scroll up/down from anywhere.

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible with [Kendo UI 2019.3.917 - Dojo](https://runner.telerik.io/fullscreen/@Dimitar-Goshev/EjoLUcUc). Scheduler's Adaptive rendering was improved in R2 2019 and it differs from the one with version 2014.2.903 used in the issue description.
