### ISSUE TITLE
Deprecated document.registerElement() method throws a warning 

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4675]
### Bug report

The document.registerElement feature has been removed from the Web standards in favor of cusomElements.define(). More information is [available on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement).

### Current behavior

![image](https://user-images.githubusercontent.com/16972160/48712815-63594d80-ec17-11e8-8351-45c581c5b6d3.png)

### Expected/desired behavior

Usage of document.registerElement() should be migrated to customElements.define().

### Environment

* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by peterilis** [comment]
Hi,

Is this being actively worked on? It seems critical to get a fix for this out ASAP so that everyone has time to upgrade their systems before March when Chrome deprecates the required function. 

Can you please update us on how to proceed or what we can expect in terms of when the fix will be out?

Cheers,
Peter

**Comment by Juveniel** [comment]
Hi peterilis ,

The thrown warning is related to using the experimental kendo.webcomponents.js. Starting from the Kendo UI 2017.R1 release, the webcomponents script is not loaded by default from kendo.all.min.js. Therefore, if you are using the latest version of Kendo UI in your project and you have not explicitly referenced kendo.webcomponents.js, the warning will not be displayed and should not cause any issues with the Kendo UI widgets.

**Comment by oleg-shturbabin** [comment]
Hi @Juveniel,

I've noticed that there is no more kendo.webcomponents.js file in sources. It was deleted in:
[6847af7056453e7bbe1b86a6e3d121cf2a94e32b](https://github.com/telerik/kendo-ui-core/commit/6847af7056453e7bbe1b86a6e3d121cf2a94e32b?_pjax=%23js-repo-pjax-container#diff-c897cf43020be2e56564a33f874b7b0e)
CDN link to this file returns 404 now:
http://kendo.cdn.telerik.com/2018.3.1017/js/kendo.webcomponents.min.js
We're depend on this file and it's included in our generated kendo.custom.min.js using [](https://www.telerik.com/download/custom-download)
Obviously, in case kendo.webcomponents.js won't be referenced, the warning will not appear. Is there any plans to replace deprecated registerElement method with new function in the next release?

**Comment by Juveniel** [comment]
Hi @oleg-shturbabin ,

The webcomponents.js was an experimental integration that was implemented a while back. Since 2017 R1 we have made the first steps towards deprecating it due to low demand, by removing the related documentation and excluding it from bundles. 

Currently, as of the new 2019 R1 release, all development of the webcomponents.js will stop and it will be excluded from official distributions. 

Regarding the custom-download builder - with the new R1 release the tool will not bundle the webcomponents.js. In case you are depending on the implementation, the only option to include it is to either manually reference the version from the old release or use [the CDN from the 2018 R3 release](https://kendo.cdn.telerik.com/2018.3.1017/js/kendo.webcomponents.js).

**Comment by donphelix** [comment]
I am also experiencing the same problem now in 2020 I have never found a clear solution to this. I am trying to download a document with kendo 2016 since the 2019 one does not work find/home/don/Pictures/Screenshot from 2020-03-05 11-50-24.png

**Comment by Juveniel** [comment]
@donphelix  

In case there are no web components in the application you are working on, you do not need to do anything special. Just download the latest version of Kendo UI and the warning should be gone.

**Comment by donphelix** [comment]
@Juveniel  This one saved my day thanks.

**Comment by Jogendra1234** [comment]
Hi,
I'm getting the below error:

chromium: [INFO:CONSOLE(67)] "document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.", source: file:///data/data/com.acroxrm.AcroTrac3/files/app/www/kendo.all.min.js (67)

**Comment by Juveniel** [comment]
@Jogendra1234 

I assume that you are using a version of Kendo UI older than 2019 R1 (2019.1.115), thus the warning is displayed. If that is indeed the case  and there are no web components used across the application, the recommended approach is to upgrade to the latest version of Kendo UI.
