### ISSUE TITLE
Spreadsheet DOLLAR() function does not accept zero or negative parameters as second argument

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4678]
### Bug report
Spreadsheet DOLLAR() function does not accept zero or negative parameters as second argument. The function will return `"#NUM!"` in the cell.

### Reproduction of the problem
Run [the following Dojo](https://dojo.telerik.com/ArOSIJod) and check out the value in the B1 cell.

### Expected/desired behavior
According to [the Excel DOLLAR description](https://support.office.com/en-us/article/dollar-function-a6cd05d9-9740-4ad3-a469-8109d18ff611) "If this is negative [or zero], the number is rounded to the left of the decimal point."

### Environment
* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by veselints** [comment]
To fix this issue [the DOLLAR function](https://github.com/telerik/kendo/blob/master/src/spreadsheet/runtime.functions.js#L2124) should be allowed to accept negative and 0 values as second parameter.

**Comment by veselints** [comment]
Fix implemented with https://github.com/telerik/kendo/commit/972ad58efd957256b9956a02b69fec27819837c2

**Comment by Dimitar-Goshev** [comment]
- [ ] Define constants.
- [ ] After the fix negative or zero second argument do not result in "#NUM!" error. But according to the [DOLLAR function examples](https://support.office.com/en-us/article/dollar-function-a6cd05d9-9740-4ad3-a469-8109d18ff611), negative number argument should round to the left of the decimal point:

1234.567 | =DOLLAR(A5, -2) | $1,200
-- | -- | --
1275.567 | =DOLLAR(A6, -2) | $1,300

I am attaching an Excel file with examples for reference.
[SpreadsheetDollarFunction.xlsx](https://github.com/telerik/kendo-ui-core/files/2628014/SpreadsheetDollarFunction.xlsx)

**Comment by veselints** [comment]
Fixed the negative logic. Did not introduced constants.
