### ISSUE TITLE
Incorrect MultiSelect input width

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4692]
### Bug report

The width of the MultiSelect's input is not calculated based on the selected items. Thus, when typing some text followed by several spaces, the text is displaced to the left and is not visible. 

### Reproduction of the problem

The issue can be reproduced on [the following Dojo](https://dojo.telerik.com/IjoPuQaR/6).

Steps to reproduce:

1. Type some text in the MultiSelect input e.g "Steven".
2. Press space several times until the text ("Steven") starts to move left.

### Current behavior

The MultiSelect input width is not calculated correctly.

### Expected/desired behavior

The input width should be calculated based on the tag list width and the wrapper width(taking into consideration the clear all icon).

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** 3.1
* **Browser:** [all]

**Comment by eyupyusein** [comment]
This seems to be fixed with the new rendering in the latest version.

**Comment by dtopuzov** [comment]
Yep, looks ok with `2022.1.11`.
