### ISSUE TITLE
The Kendo Validator React wrapper does not block the onSubmit prop from executing after failed validation

### ISSUE THREAD

**Issue by k290** [telerik/kendo-ui-core#4699]
### Reproduction of the problem
1. Open demo here: https://stackblitz.com/edit/react-27hyxf?file=app%2Fmain.js
2. Do not fill in required field
3.. Click the submit button
4.. Alert message indicating that onSubmit was executed is displayed

Compare this to the native Kendo React validation which blocks onSubmit if validation fails:
1. https://stackblitz.com/edit/react-ebmmmv-pha3za?file=app/main.js

### Expected/desired behavior
Do not trigger the onSubmit prop's event when validation fails, for applications that require custom logic for form submission

### Environment
* **Kendo UI version:** "2018.3.1129"
* **jQuery version:** 3.3.1
* **Browser:** [Chrome 70]

**Comment by Xizario** [comment]
@k290, the react wrappers of the jQuery widgets are following jQuery practices at first. And in the widget the preventing logic is part of the app, not the widget itself.

We don't have plans to improve the wrappers further. As we already have new react components that follows best practices in react.
