### ISSUE TITLE
Kendo TextBox bound to Model in Razor Pages scenario does not render data attributes

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4704]
### Bug report

[Feedback Portal item](https://feedback.telerik.com/aspnet-core-ui/1364109-kendo-textbox-bound-to-model-in-razor-pages-scenario-does-not-render-data-attributes).

### Reproduction of the problem

View:
```
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
 
<form class="form-horizontal" method="post">
    <h4>Standard textbox:</h4>
    @Html.TextBoxFor(m => m.Candidate.CandidateId)
 
    <h4>Kendo textbox:</h4>
    @Html.Kendo().TextBoxFor(model => model.Candidate.FirstName)
    <div class="form-group">
        <div>
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>
</form>

```

Back end:
```

public class IndexModel : PageModel
{
    [BindProperty]
    public CandidateViewModel Candidate { get; set; }
 
    public void OnGet()
    {
 
    }
 
    public void OnPost()
    {
        ViewData["firstname"] = $"{Candidate.FirstName}";
        ViewData["candidateid"] = $"{Candidate.CandidateId}";
    }
}
```

Model:
```

public class CandidateViewModel
{
    [Key]
    [Display(Name = "Candidate ID")]
    public int CandidateId { get; set; }
 
    [Required]
    [Display(Name = "First Name")]
    public string FirstName { get; set; }
}
```

Inspect the TextBox and Kendo TextBox helpers in the browser. The latter does not render **data-val** and **data-val-required** attributes.

### Current behavior
data attributes are not rendered

### Expected/desired behavior
data attributes are rendered

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by kdikov82** [comment]
Reported in Ticket ID: 1399837 for StringLength Data Annotation as well:

	[Required]
	[StringLength(100, MinimumLength = 4, ErrorMessage = "Error message!")]
	[Display(Name = "Product name")]
	public string ProductName
	{
		get;
		set;
	}

**Comment by mparvanov** [comment]
Not reproducible with 2019.3.1023: https://take.ms/hvn1F
