### ISSUE TITLE
Rows are misaligned with multi-level grouping and locked columns

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#4705]
Feedback item - [https://feedback.telerik.com/kendo-jquery-ui/1364257-rows-are-misaligned-with-multi-level-grouping-and-locked-columns](https://feedback.telerik.com/kendo-jquery-ui/1364257-rows-are-misaligned-with-multi-level-grouping-and-locked-columns)

### Reproduction of the problem
1. Run [this dojo](https://dojo.telerik.com/IDEDUCIq)
1. Collapse one or more of the subCategory groups
1. Collapse the category Group
1. Expand Category

### Current behavior
The aggregate rows are missing and the locked and unlocked content is misaligned

### Expected/desired behavior
Rows should be aligned

### Environment

* **Kendo UI version:** 2018.3.1017

**Comment by Sheing** [comment]
Having this problem in my company's app affecting a few big clients, any temporary fix to prevent this?
