### ISSUE TITLE
Vue DatePicker component incorrectly adds k-input class to its wrapper

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4706]
### Bug report

When a date is selected, the .k-input class is added to the wrapper of the component. Thus, the styling rules are being overwritten. 

### Reproduction of the problem

The issue can be reproduced on [the following StackBlitz example](https://stackblitz.com/edit/vqphdu).

Steps to reproduce:

* Open the widget and select a date.
* Inspect the weapper element and notice that the .k-input class is added.

### Current behavior

The .k-input class is being incorrectly added to the wrapper of the widget after a date is selected. 

### Expected/desired behavior

The k.-input class should not be applied on the wrapper element after selecting a date.

### Environment

* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
With 2023.3.1114 rendering the presence of k-input class on the wrapper element is expected.
