### ISSUE TITLE
PivotGrid throws error on specific Columns/Rows configuration on drag&drop

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#4708]
### Bug report 
(Ticket ID: 1364183)

PivotGrid throws error (_Uncaught TypeError: Cannot read property 'measure' of undefined_) on some scenario when there are multiple rows and no column and one of the rows is dragged to the Columns.

### Steps to reproduce
1) Open: [https://demos.telerik.com/kendo-ui/pivotgrid/index](https://demos.telerik.com/kendo-ui/pivotgrid/index)
2) Clear all measures, rows and columns
3) Drag Account to Columns
4) Drag Customer and Department to Rows
5) Drag Account from columns to Rows
6) Drag Account back to columns
7) The error is thrown

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ag-petrov** [comment]
Seems to work fine with the latest version.
