### ISSUE TITLE
Grid autoFitColumn does not work in mobile Grid's columnShow-event on iPad

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-ui-core#4710]
Can be reproduced in [this Dojo](https://dojo.telerik.com/@martinpz/oPehEJeb/4) 

1. Hide some columns from the column menu.
2. Show the columns from the column menu - no data is shown

Logged in the [feedback portal](https://feedback.telerik.com/kendo-jquery-ui/1364721-autofitcolumn-does-not-work-in-mobile-grid-columnshow-event)

**Comment by ag-petrov** [comment]
This seems to work now. Additionally due to the animations the resizing of the columns should be used with a slight timeout. [Here ](https://dojo.telerik.com/AdiTataK/2)is a modified dojo.
