### ISSUE TITLE
Map markers are not positioned correctly on a zoomed out Bing map

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4711]
### Bug report

The markers are not correctly positioned on a "Bing" map when the map is zoomed out.

Reported in: 1364765

### Reproduction of the problem

Compare these:

https://binged.it/2EcKGvK
https://dojo.telerik.com/upirEqiR

The same behavior is not observed with other map types. For example - "tile":
https://dojo.telerik.com/oTicUDUS

### Expected/desired behavior

The markers are positioned as expected.

### Environment

* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by PreslavKozovski** [comment]
The problem is related to the wrong height of the `span` of the pin in the `LESS` themes.

Additionally, as an enhancement, we can remove the margins and use a `transform: translate(...)` for `LESS` and `SASS` themes. 

During testing, make sure that these changes are working okay in old IE versions.

**Comment by Alex-Bubblemaster** [comment]
Also affects scenarios like this one when adding markers in the exact spot is important: 1425100.
