### ISSUE TITLE
AngularJS TreeList with InCell editing and keyboard navigation resets the focused cell after edit

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#4712]
### Bug report

When adding a TreeList to an AngularJS application, if the widget has in-cell editing combined with keyboard navigation, the focused cell is reset after editing and trying to navigate to the next cell.

### Reproduction of the problem
[https://dojo.telerik.com/AnoKUnAv/4](https://dojo.telerik.com/AnoKUnAv/4)

Follow these steps:

1. Open a cell for editing.
1. Press Tab or Enter key.

### Current behavior
The focus goes back to the first cell in the Grid.

### Expected/desired behavior
The cell next to the edited cell should be focused.

### Environment

* **Kendo UI version:** 2018.3.1017

Reported in: 1364246

**Comment by MilenaCh** [comment]
The issue still exists: https://www.screencast.com/t/cDSdanaiM
