### ISSUE TITLE
Scroll of list view in KendoUI-mobile fails after press tab in last visible element

### ISSUE THREAD

**Issue by jcfiorenzano** [telerik/kendo-ui-core#4717]
### Bug report
In a kendo list view if the user press tab in the last visible element of the list kendo load a bunch of elements from the datasource instead of one at a time, after this is not possible to scroll-ups to the beginning of the list. This issue happens with the endless property set true or false.

### Reproduction of the problem
you can try an example here:
https://jsfiddle.net/jw7pr6z9/

`   
<!DOCTYPE html>
          <html>
              <head>
                  <meta charset="utf-8"/>
                  <title>Kendo UI Snippet</title>
                  <link rel="stylesheet"  href="https://kendo.cdn.telerik.com/2017.3.1026/styles/kendo.common.min.css"/>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.3.1026/styles/kendo.rtl.min.css"/>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.3.1026/styles/kendo.silver.min.css"/>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.3.1026/styles/kendo.mobile.all.min.css"/>

    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.3.1026/js/kendo.all.min.js"></script>
              </head>
             <body>
                   <div data-role="view">
                         <ul data-role="listview" data-source="foo" data-endless-scroll="true" data-template="foo-template" data-item-change="itemChange">
                        </ul>
                   </div>

                   <script type="text/x-kendo-template" id="foo-template">
                             #: name # - #: modified #
                            <input type="text" placeholder="press tab "/>
                   </script>
                  <script>
                        var i = 0, pageSize = 100;
                        // datasource below is customized for demo purposes.
                       var foo = new kendo.data.DataSource({
                                 transport: {
                                          read: function(options) {
                                                       var max = i + pageSize;
                                                       var data = [];
                                                       for (; i < max; i ++) {
                                                               data.push({ name: "record" + i, modified: +new Date() });
                                                      }

                                                   options.success(data);
                                          }
                                    },
                                    pageSize: pageSize,
                                    serverPaging: true,
                                    schema: {
                                            total: function() { return 500; }
                                     }
                         });

                         function itemChange(e) {
                            console.log(e);
                        }

                       new kendo.mobile.Application();
                 </script>
              </body>
            </html>
  `
<img width="1058" alt="screen shot 2018-12-14 at 12 11 30 am" src="https://user-images.githubusercontent.com/5582507/49992269-673b6f80-ff38-11e8-9524-ec292a3fa65b.png">

**Comment by ag-petrov** [comment]
Closing this issue as the mobile suite is now depricated.
