### ISSUE TITLE
Grid column resizing doesn't work as expected with jQuery 3.3.1 is some scenarios

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-ui-core#4719]
Reported again in 1362568 

Can be reproduced in [this Dojo](https://dojo.telerik.com/IkigawaX)

1. Try to resize a column - the resize handle doesn't show or shows up at unexpected location.

![img_6239](https://user-images.githubusercontent.com/5861835/49997773-20329600-ff9b-11e8-94af-f0cbfde4c5c6.JPG)

Logged in the [feedback portal](https://feedback.telerik.com/kendo-jquery-ui/1365238-grid-and-resizable-option-set-to-true-not-working-with-jquery-3-3-1)

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** 3.3.1
* **Browser:** [all]

**Comment by PreslavKozovski** [comment]
Simplified example:
https://dojo.telerik.com/idiQeruc

Note: The Grid should not be scrollable.
