### ISSUE TITLE
Editor bound to Model in Core and MVC does not render data attributes

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4729]
### Bug report

When a model property is decorated with data annotation attributes, the Editor HtmlHelper does not properly render the data-val and data-val-required attributes on the <textarea> element.

### Reproduction of the problem

[TelerikAspNetCoreAppEditor.zip](https://github.com/telerik/kendo-ui-core/files/3742533/TelerikAspNetCoreAppEditor.zip)

### Current behavior

Data attributes are not rendered on the <textarea> element.

### Expected/desired behavior

Data attributes should be successfully rendered on the Editor's <textarea>element.

### Environment

* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]

**Comment by jack0fshad0ws** [comment]
Same applies to TextBoxFor e.g. ```@(Html.Kendo().TextBoxFor(m => m.Customer.FirstName)``` no data attributes like required are rendered

**Comment by mparvanov** [comment]
In MVC5 Wrappers the data-val-required attribute is rendered even before the change - v. 2019.3.1023
