### ISSUE TITLE
Sort groups themselves by a field other than the group field property

### ISSUE THREAD

**Issue by ravi-ku** [telerik/kendo-ui-core#4732]
### Current behavior
_(optional)_
![image](https://user-images.githubusercontent.com/11146609/50444563-1d3a8c80-092f-11e9-88aa-62b4c0996db7.png)

### Expected/desired behavior
![image](https://user-images.githubusercontent.com/11146609/50444641-a651c380-092f-11e9-8a81-5bec534d2d7a.png)

### Environment

* **Kendo UI version:** 2017.r.ddd
* **jQuery version:** 3.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by boyandim** [comment]
We are planning to have such functionality (custom sort of the groups) in our upcoming release R1 2019. Still [here ](https://github.com/telerik/kendo-ui-core/issues/4024)is a link to the public issue where you can find more information about the option and how can be used.
