### ISSUE TITLE
Resizing RTL Grid with filter row throws JavaScript error

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#4737]
### Reproduction of the problem
1. Run dojo - https://dojo.telerik.com/UyOroxin
2. Try to resize a column using the handler in the filter row.

### Current behavior
JavaScript error is shown. https://www.screencast.com/t/D60Ndpgss9pT

### Expected/desired behavior
Resizing should work the same as in non-rtl mode. 

### Environment

* **Kendo UI version:** 2018.3.1017

**Comment by alirezameftahi71** [comment]
Same problem.
Any workaround?
'Cause we can't wait 'till the next update.
