### ISSUE TITLE
DropDownTree select event not fired in MVVM scenarios

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/kendo-ui-core#4740]
### Bug report
The [Select](https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdowntree/events/select) event of a DropDownTree does not fire in an MVVM scenario.

Reported in [https://www.telerik.com/forums/unable-to-bind-to-select-event-using-mvvm](https://www.telerik.com/forums/unable-to-bind-to-select-event-using-mvvm)

### Reproduction of the problem
1. [Sample for MVVM issue](https://dojo.telerik.com/@bratanov/ulaQuNUH) (checkboxes were removed in case this is expected behavior, and merely needs to be documented)
1. Expand the dropdown
1. Click on a node

### Current behavior
Select event is not fired

### Expected/desired behavior
Select event is fired

### Environment
* **Kendo UI version:** 2018.3.1017
* **jQuery version:** 1.12.4
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
@marin-bratanov `Select` event is fired when a node is being selected. If a DropDownTree node is selected, clicking on it once again, does not select it again, thus `select` event is not fired again. In `checkboxes: true` scenario `select` event usage is not recommended and we will add a note about it in its documentation. DropDownTree's value with checkboxes is changed on checking node's checkbox, not on selecting a node. Thus, preventing `select` event does not prevent changing DropDownTree's value with `checkboxes: true`. I updated the issue's description to address the MVVM problem only.

**Comment by marin-bratanov** [comment]
raised priority because of a second report in Ticket ID 1400700
