### ISSUE TITLE
PanelBar fires onSelect twice if you click on a label element inside its template

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/kendo-ui-core#4741]
### Bug report

When you place a `<label>` inside the template of a panelbar, and click on that label, the select event fires twice instead of the expected once.

Note: works as expected on collapsible items, only items without children exhibit the problem.

Reported in Ticket ID: 1381775

May be related to [#2761](https://github.com/telerik/kendo-ui-core/issues/2761) and [#2752](https://github.com/telerik/kendo-ui-core/issues/2752)

### Reproduction of the problem

reproducible: [https://dojo.telerik.com/OXazIKUq](https://dojo.telerik.com/OXazIKUq)

### Expected/desired behavior

the event keeps firing only once as if you clicked on any place in the item outside of the label.

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** 1.12.4
* **Browser:** all

**Comment by marin-bratanov** [comment]
One possible workaround [https://dojo.telerik.com/@bratanov/otIVuNag](https://dojo.telerik.com/@bratanov/otIVuNag)

**Comment by marin-bratanov** [comment]
Feedback Portal link for visibility: [https://feedback.telerik.com/kendo-jquery-ui/1381918-panelbar-fires-onselect-twice-if-you-click-on-a-label-inside-its-template](https://feedback.telerik.com/kendo-jquery-ui/1381918-panelbar-fires-onselect-twice-if-you-click-on-a-label-inside-its-template)

**Comment by Dimitar-Goshev** [comment]
@Juveniel After the fix expanding clicking on a PanelBar item with contentUrl navigates to that URL. Also it is not possible anymore to expand such an item with keyboard Enter/Space key.
To reproduce the issue, use panelbar/ajax demo (all items)  or panelbar/events demo (Ajax Item and Error Item)

**Comment by Dimitar-Goshev** [comment]
@Juveniel After the second fix, it is not possible to expand PanelBar item with contentUrl at all (clicking on it or through keyboard). Use kendo-ui/panelbar/ajax demo for reproduction.

**Comment by Dimitar-Goshev** [comment]
@Juveniel Clicking on the expand arrow icon of a PanelBar item with contentUrl navigates to that URL.
