### ISSUE TITLE
Revisit toolbar dimensions in less themes

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#4742]
Origin of discussion is #4107 -- after some tweaking, the height of the toolbar is tad smaller (4px to be precise). The thing is, it looks good with space between buttons and toolbar being the same, like in the less themes.

Here are some screenshots

**Prior changes** -- 6px top and bottom
![image](https://user-images.githubusercontent.com/8048/50765316-3243e380-127e-11e9-846b-56990e953663.png)

**With changes** -- 4px top and bottom (left and right is a tad smaller)
![image](https://user-images.githubusercontent.com/8048/50765388-67e8cc80-127e-11e9-9230-a16d87b806c7.png)

**Bootstrap v4** -- equal space on all sides
![image](https://user-images.githubusercontent.com/8048/50765447-99fa2e80-127e-11e9-9472-4db72a061661.png)

@lkarakoleva how should the size of the toolbar be: like before (top and bottom 6px) or like now (top and bottom 4px)? Also, should we make the padding on all sides equal, like in bootstrap (and sass themes in general)?

**Comment by lkarakoleva** [comment]
It is better all the padding to be equal: top, bottom and the padding between tools.
