### ISSUE TITLE
DropDownList option label is not evaluated in AngularJS scenario

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4745]
### Bug report
This is a regression introduced in R3 2018. 

### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/umuqaFaT) example.

1. The option label is bound to the scope: 
```<option>{{::foo}}</option>```

```$scope.foo = "BAR";```

But its value is not properly evaluated and is displayed as `{{::foo}}` instead of `BAR`.

### Current behavior
Option label value is not properly evaluated.

### Expected/desired behavior
Option label value is properly evaluated.

[Feedback Portal item](https://feedback.telerik.com/kendo-jquery-ui/1381825-dropdownlist-controller-binding-for-option-labels-does-not-work-in-latest-version).

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by jivanova** [comment]
Reproducible since: https://github.com/telerik/kendo/commit/2fdadc75c45d7902a780d00e3ebe6c5f3cf6a141#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by jivanova** [comment]
This behavior stems from intended change to escape the template expressions in AngularJS.  We proceeded with this change because of security vulnerability in the AngularJS that affected our components.

I will mark the issue as Won't fix. However, if you need to use such expression, I would advice to open a support thread in order to further assist you with the matter.

**Comment by dlwhiteman5** [comment]
Hi Joana, Ivan gave me the following workaround that will allow us to continue using our previous approach:

    var ampRegExp = /&/g,
                ltRegExp = /</g,
                quoteRegExp = /"/g,
                aposRegExp = /'/g,
                gtRegExp = />/g;
    kendo.htmlEncode = function (value) {
                return ("" + value).replace(ampRegExp, "&amp;").replace(ltRegExp, "&lt;").
                    replace(gtRegExp, "&gt;").replace(quoteRegExp, "&quot;").
                    replace(aposRegExp, "&#39;");
     }

Should we be concerned with using the workaround?  Would using this approach expose our application to security vulnerabilities?  If so, do you have a link to an article or something that explains the vulnerability in more detail?
