### ISSUE TITLE
Offline storage __state__ property not removed after successful create or update

### ISSUE THREAD

**Issue by beard7** [telerik/kendo-ui-core#4747]
### Bug report
The `__state__` property of items in offline storage is not removed after posting create or update requests to the server and receiving a success response. This is resulting in the same create/update request being posted to the server multiple times if the dataSource switches between online/offline modes.

I've tried returning the same data as a confirmation of the successful save operation, and I've also tried returning an empty response (as suggested in the documents).

https://runner.telerik.io/fullscreen/arUpoxIP/6

### Reproduction of the problem
1. Create dataSource configured with offlineStorage set to use localstorage.
2. Set dataSource online using `dataSource.online(true);`
3. Read existing data using `dataSource.read();` -- server returns empty array
4. Set dataSource offline using `dataSouce.online(false);`
5. Add a new model and sync: `dataSource.add(model);`   `dataSource.sync();`
6. `__state__` property set to `create` on item in localstorage
7. Set dataSource online using `dataSource.online(true);`
8. Post request is made to url defined in dataSource transport and JSON is returned from server with new `id`
9. Item in localstorage still has `__state__: "create"` property
10. dataSource set offline then online again
11. Another Post request is made, resulting in duplicate record

### Expected/desired behavior
After successfully sending create or update requests to server and receiving success response, `__state__` property should be removed from items in offline storage (localstorage)

### Environment

* **Kendo UI version:** 2018.3.1017
* **jQuery version:** 1.12.3
* **Browser:**Android 6.0.1 Phonegap App Webview

**Comment by ag-petrov** [comment]
Not reproducible with latest version
