### ISSUE TITLE
binding does not work in scrollview when multiple items are passed to the template

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-ui-core#476]
http://dojo.telerik.com/@xmanalex/UvUDe

Reported in 888392

**Comment by burrowj** [comment]
I'm try to find a workaround for this issue.  Please could you give a sample
Thanks

**Comment by petyosi** [comment]
I am afraid that there is no known workaround for the problem, and we will need to introduce some breaking changes to support the scenario. The MVVM binding relies on a single root DOM element to map to the data item.

**Comment by sspasova** [comment]
Closing this as the mobile suite is now deprecated. You can read more information here: https://docs.telerik.com/kendo-ui/controls/hybrid/introduction
