### ISSUE TITLE
Removing MultiSelect tag does not trigger change event with jQuery 3.3.1

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#4760]
### Bug report
Clearing the value in ComboBox and MultiSelect: https://dojo.telerik.com/ihIvOyiR/2 

### Reproduction of the problem
1. Use the following [Dojo](https://dojo.telerik.com/@Goshev/oBUtutEZ)
1. Remove "One" tag from the taglist by clicking its clear button/pressing backspace / pressing Esc twice

### Current behavior
No change event is fired with jQuery 3.3.1

### Expected/desired behavior
Change event is fired as with jQuery 1.12.4 - [Dojo](https://dojo.telerik.com/@Goshev/UrAHAsuy)

### Environment
* **Kendo UI version:** 2019.1.115
* **jQuery version:** 3.3.1
* **Browser:** all

**Comment by zdravkov** [comment]
I could not replicate it with the latest version 2019.2.514 - https://github.com/telerik/kendo-ui-core/issues/4760
