### ISSUE TITLE
proxyUrl options cannot be set in the Spreadsheet vue wrapper

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4761]
### Bug report
Setting the values of the **excel-proxy-URL** and **pdf-proxy-URL** props does not set the respective proxyURL options. 

### Reproduction of the problem
[Stackblitz](https://stackblitz.com/edit/fnf4jk?file=index.html) example.
1. The Spreadsheet options are logged in the console in the **mounted** function. Note that **pdf.proxyURL** and **excel.proxyURL** have no values. 

### Current behavior
proxyUrl options are not set

### Expected/desired behavior
proxyUrl options are set

[Feedback Portal item](https://feedback.telerik.com/kendo-vue-ui/1383101-proxyurl-options-cannot-be-set-in-the-spreadsheet-vue-wrapper).

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by zdravkov** [comment]
Due to the capital letters the correct props are  ":excel-proxy-u-r-l" and "pdf-proxy-u-r-l" - here is the stacklitz that worked at my side - https://stackblitz.com/edit/fnf4jk-r9n7qk?file=index.html

We will update our API documentation as soon as possible.
