### ISSUE TITLE
LESS Themebuilder throws js exception on customizing any of the theme styles

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4765]
### Reproduction of the problem
1. Customize any of the default theme styles.
2. A js exception is thrown: [screenshot](https://www.screencast.com/t/G6nwAXlb) and the widgets appearance does not reflect the changes made.

### Environment

* **Kendo UI version:** 2019.1.115
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
LESS ThemeBuilder is fixed now - https://demos.telerik.com/kendo-ui/themebuilder/
