### ISSUE TITLE
Hovered class (and styling) is applied to the inner hovered element instead to the entire custom drop-zone of the Upload

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4766]
### Bug report
Hovered class (and styling) is applied to the inner hovered element instead to the entire custom drop-zone of the Upload.

### Reproduction of the problem
* Run the [Custom drop-zone demo](https://demos.telerik.com/kendo-ui/upload/customdropzone);
* Drag a file over the text '+Add image' - that text DOM element will be highlighted. Instead, the entire drop-zone should be highlighted

### Current behavior
Only the hovered DOM element inside the drop-zone is highlighted.

### Expected/desired behavior
The entire drop-zone should be highlighted instead.

### Environment

* **Kendo UI version:** 2019.3.1023
* **Browser:** [all]

**Comment by Juveniel** [comment]
Resolved with https://github.com/telerik/kendo/commit/f19dd2e1fac11ff04b7f7aa3f73f8596e4ebbd77. As a result, the `.k-drop-zone-hovered` class is now also added to the drop zone element, while also preserving the previous logic where the class is added to the hovered target element.
