### ISSUE TITLE
Restoring Grid settings adds multiple display:none to hidden columns

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#4773]
### Reproduction of the problem
1. Run the [Persist state demo](https://demos.telerik.com/aspnet-mvc/grid/persist-state)
1. Hide a column
1. Click Save state
1. Click Load State

### Current behavior

The _style_ attribute for the hidden column has _display:none;_ two times;

### Expected/desired behavior

The _display:none;_ setting should be added only once.

### Environment

* **Kendo UI version:** 2019.1.115

**Comment by boyandim** [comment]
also related to #4777
