### ISSUE TITLE
DropDownTree popup auto-closes, when its height is bigger than the window's height, in Chrome and IE

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4776]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/ohIPAKeC) example.
1. Resize the browser window so that its height is smaller than the DropDownTree's popup height. 
2. Click the DropDownTree to open its popup.
3. The popup opens and then auto-closes 

### Current behavior
The popup auto-closes.

### Expected/desired behavior
The popup remains open.

[Feedback Portal item.](https://feedback.telerik.com/kendo-jquery-ui/1383942-dropdowntree-popup-auto-closes-when-its-height-is-bigger-than-the-window-s-height)

### Environment

* **Kendo UI version:** 2019.1.115
* **jQuery version:** x.y
* **Browser:** [Chrome XX | IE11]

**Comment by martintabakov** [comment]
Also reported in ticket #1432221
