### ISSUE TITLE
Ng-model does not update switch value

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#4779]
### Bug report

[https://dojo.telerik.com/uwEkEfEy](https://dojo.telerik.com/uwEkEfEy)

### Reproduction of the problem

1. Click the Switch

### Current behavior
Unchecked switch is reverted.

### Expected/desired behavior
Unchecked should be analogical to the ng-model.

### Environment

* **Kendo UI version:** 2019.1.115
* **Browser:** all

**Comment by kjartanvalur** [comment]
+1
