### ISSUE TITLE
Selecting the first date in the range closes the popup

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#4780]
### Reproduction of the problem
1. Open the [online example](https://demos.telerik.com/aspnet-core/daterangepicker/index)
1. Select range (e.g 10 Jan -15 Jan)
1. Click in one of the inputs
1. Select the first date of the range (10 Jan) 

### Current behavior
The popup is closed
video - https://www.screencast.com/t/DutwW3ER6

### Expected/desired behavior
The popup should remain open

### Environment

* **Kendo UI version:** 2019.1.115

**Comment by MilenaCh** [comment]
Issue:
1. Open MultiViewCalendar  and select some range
2.Open MultiViewCalendar again and click on the end date

Result: The picker will be closed, however it should stay opened in order to select a new range.
