### ISSUE TITLE
DropDownList Filter Not Filtering

### ISSUE THREAD

**Issue by tareknaj** [telerik/kendo-ui-core#479]
I type in the filter "chef", the filter is applied and I select any item. I re-opened the dropdown and typed the same filter again "chef" no request is made. Am I missing something ? (the same issue happen with client filtering)

Tested on: http://demos.telerik.com/kendo-ui/dropdownlist/serverfiltering

**Comment by tareknaj** [comment]
Still reproducible

**Comment by KirilNN** [comment]
@tareknaj The issue is still opened, which means that we are investigating the problem. As soon as the issue is resolved, we will make sure to update the status of the issue to closed.

Thanks again for bringing this up!

**Comment by ggkrustev** [comment]
Related to #662.

**Comment by RodryVazquez** [comment]
I had the same problem.
