### ISSUE TITLE
setOptions is not updating the rendering of DateRangePicker correctly

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#4793]
### Bug report

https://dojo.telerik.com/@zdravkov/EXEnoGAH

### Reproduction of the problem
1. click the button 'setOptions' several times

### Current behavior
wrong rendering is observed

### Expected/desired behavior
widget should render correctly

### Environment

* **Kendo UI version:2019.1.115

**Comment by matanasov** [comment]
The issue seems fixed, but now error is thrown when:

1. Use the same DoJo example
2. Click `SetOptions` and open the calendar.
3. Click `SetOptions` and open the calendar.
4. Hover any date - you get this in the console:

```
kendo.all.js:34992 Uncaught TypeError: Cannot read property 'start' of null
    at init._mouseEnter (kendo.all.js:34992)
    at HTMLTableCellElement.d (jquery-1.12.4.min.js:2)
    at HTMLTableCellElement.handle (jquery-1.12.4.min.js:3)
    at HTMLDivElement.dispatch (jquery-1.12.4.min.js:3)
    at HTMLDivElement.r.handle (jquery-1.12.4.min.js:3)
```
