### ISSUE TITLE
Unable to set strings for Width, Height and Position properties,  of Dialog and Window MVC/Core wrappers

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/kendo-ui-core#4794]
### Bug report
To make a responsive Kendo UI Dialog/Window, [width](https://docs.telerik.com/kendo-ui/api/javascript/ui/dialog/configuration/width) and [height](https://docs.telerik.com/kendo-ui/api/javascript/ui/window/configuration/height) may be set in percentages, e.g. `width: "80%" height: "80%"`. The `Width()` and `Height()` methods of the MVC/Core wrapper, however, can only take an `int` or `double`.

[Update Kendo UI 2019.3.1023]
The same issue is reproducible if we want to set an exact position for the Window component. The Top and Left values of the Position method accept **int** values only and thus a percentage value cannot be set.

### Reproduction of the problem
Try to set Width("50%")

[Update Kendo UI 2019.3.1023]
Try to set Position(p=>p.Top(10).Left("10%"))

### Current behavior
Error not able to convert string to int/double

[Update Kendo UI 2019.3.1023]
Error: Cannot convert from "string" to "int"

### Expected/desired behavior
String is accepted and dialog width is 50% of its parent width as in Kendo UI.

### Workaround
Set width and height after Dialog/Window is initialized, using the **setOptions()** method:
Note: [Known issue when Dialog height is set in percentages](https://github.com/telerik/kendo-ui-core/issues/4029)
```
<script>
    $(document).ready(function () {
        var dialog = $("#dialog").data("kendoWindow");
        dialog.setOptions({
            width: "50%",
            height: "50%"
        })
    });
</script>
```
[Update Kendo UI 2019.3.1023]
```
<script>
 var dialog = $("#window").data("kendoWindow");
        dialog.setOptions({
            position: {
                top: 100, // or "100px"
                left: "10%"
            }
        })
</script>
```

### Environment
* **Kendo UI version:** 2019.1.115
* **jQuery version:** 1.12.4
* **Browser:** all

**Comment by aleksandarevangelatov** [comment]
Also reported in support thread 1456343

**Comment by Dimitar-Goshev** [comment]
Reported in thread 1458953

**Comment by mparvanov** [comment]
- [ ] Window min/max width and height properties are missing from MVC5 wrappers

**Comment by veselints** [comment]
`min-` and `max-` are settings of the Window Resizable configuration. That is why I have implemented them in the `WindowResizingSettingsBuilder.cs`:
```
.Resizable(resize => resize.Enabled((bool)ViewBag.resizable))
```
