### ISSUE TITLE
DropDownList selects the first item if the same field is used as dataTextField and dataValueField 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4797]
### Bug report
In AngularJS scenario when ng-model (or k-ng-model) is null and the same field is used as dataTextField and dataValueField the first item is selected. This behavior is introduced in R1 2017.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/obAQOpUV) example.
1. The same field ("name") is set as dataTextField and dataValueField.
2.  "data" is commented: //$scope.data=0;

If you set the dataValueField to "id" the widget behaves as expected. 

### Current behavior
The first item is selected.

### Expected/desired behavior
No item is selected.

[Feedback Portal item](https://feedback.telerik.com/kendo-jquery-ui/1384609-drop-down-widget-is-showing-the-value-even-though-ng-model-is-undefined-when-we-bind-same-value-to-k-data-value-field-and-k-data-text-field)

### Environment

* **Kendo UI version:** 2019.1.115
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
