### ISSUE TITLE
The ToDataSourceResult() method should support aggregates with DataTables for ASP.NET Core

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#4798]
### Enhancement

Ticket ID: 1384643  

### Reproduction of the problem

Create a grid using [DataTables](https://github.com/telerik/kendo-ui-core/issues/2140#issuecomment-384630376). Add agggregates to the data source:

```
           .Aggregates(aggregates =>
           {
               foreach (System.Data.DataColumn column in Model.Columns)
               {
                   if (column.DataType == typeof(int))
                   {
                       aggregates.Add(column.ColumnName, typeof(int)).Sum();
                   }
                   if (column.DataType == typeof(string))
                   {
                       aggregates.Add(column.ColumnName, typeof(int)).Count();
                   }
               }
           })
```
An error is thrown:

[Stack trace](https://runner.telerik.io/fullscreen/@bubblemaster/UHEjaPiC)

### Expected/desired behavior

The aggregates should be calculated correctly

### Workaround

- add a `System.Data.DataSetExtensions.dll` and use the [`.AsEnumerable()`](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatableextensions.asenumerable?view=netframework-4.7.2#remarks) method

- specify the fields and object types. While this takes away from the dynamic definition, it is a way to use the grid at present with aggregates

```
        public IActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            var res = GetDataTable(500).AsEnumerable().Select(x=> new {                
                Field1 = x.Field<string>("Field1"),
                Field2 = x.Field<int>("Field2")
            });
            return Json(res.ToDataSourceResult(request));
        }
```

### Environment

* **Kendo UI version:** 2019.1.115

**Comment by VicTachev** [comment]
Reported again in ticket 1404416

**Comment by marin-bratanov** [comment]
Also requested in 1413810. Raising priority

**Comment by tynorton** [comment]
Can we increase the priority here? Blocking out move to .NET Core.

**Comment by Alex-Bubblemaster** [comment]
Also reported in 1445669, raising priority

**Comment by tynorton** [comment]
Any updates here?

**Comment by gyankov** [comment]
Requested again in 1473929, raising priority.
