### ISSUE TITLE
Scheduler event with certain timezone jumps when being edited

### ISSUE THREAD

**Issue by austinw-fineart** [telerik/kendo-ui-core#4799]
### Bug report
A scheduler event with the timezone "Europe/Belgrade" will jump to a different time when double clicked on in the scheduler. The time jump will depend on the scheduler's timezone, ie. if the scheduler is UTC then the event will jump backwards by 1 hour, or 2 hours if DST is in effect.

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/scheduler/index
1. Create an event from 3:00 PM to 3:30 PM with start and/or end timezone as "(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Praque" and save:
![image](https://user-images.githubusercontent.com/6614183/52270411-90c9b380-2949-11e9-9206-91b5ced377cd.png)
1. The event is shown from 1:00 PM to 1:30 PM, as the Scheduler has Timezone set to UTC on the demo.
1. Edit the Test event - the event will jump from "1:00 PM-1:30 PM" (Scheduler's UTC timezone) to "3:00 PM-3:30 PM" (Start and End pickers timezone inside event Edit dialog):
![image](https://user-images.githubusercontent.com/6614183/52276364-ae534900-295a-11e9-8982-29ab1c228a22.png)
1. Close the Edit dialog without saving - click on Cancel or close button

### Current behavior
The event will stay in its jumped position "3:00 PM-3:30 PM", if the dialog is closed without saving.
Note: the event will jump back to its correct position if Save is called

### Expected/desired behavior
The event will jump back to its correct position "1:00 PM-1:30 PM", as the Scheduler has UTC Timezone

### Environment
* **Kendo UI version:** 2019.2.619
* **jQuery version:** 1.12.3, 3.2
* **Browser:** all

**Comment by zdravkov** [comment]
Hi @austinw-fineart ,

I couldn't see a link where we can replicate the issue.
I have tested the issue on our demo site [here ](https://demos.telerik.com/kendo-ui/scheduler/index) but could not replicate it there. 

Would you please elaborate the issue by sharing a [dojo ](https://dojo.telerik.com/)or other sample project where it could be replicated?

Greetings,
Plamen

**Comment by Dimitar-Goshev** [comment]
@austinw-fineart @zdravkov I managed to reproduce the issue and I updated the reproduction steps.

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible with R3 2019 SP1 (2019.3.1023)
