### ISSUE TITLE
The field with name "id" is always set to the value of the model.id field

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/kendo-ui-core#4800]
### Bug report

The data source always sets the `.id` field in the data row to the value of the field denoted in the `schema.id` configuration. This happens both when the `schema.id` field is present in the supplied data, and when it is not. In some cases this change may lead to issues and data corruption if the `schema.id` field is not called `id`.

Reported in Ticket ID: 1384602

In case this behavior is expected, we must document it in the Schema section of the CRUD operations article: [https://docs.telerik.com/kendo-ui/framework/datasource/crud#schema](https://docs.telerik.com/kendo-ui/framework/datasource/crud#schema). I already added the explanations that the `schema.id` field must be present in the data, and we may expand on this behavior and its reasons as well.

### Reproduction of the problem

[https://dojo.telerik.com/@bratanov/AwiHOhaJ](https://dojo.telerik.com/@bratanov/AwiHOhaJ)

```
    $(document).ready(function(){
      var a = new kendo.data.DataSource({schema:{model:{id: "nonExistingField"}}});
      a.data([{id: "lorem ipsum"}]);
      console.log("expected: \"lorem ipsum\", actual: " + a.data()[0].id);//empty string
      console.log("expected: \"undefined\", actual: " + a.data()[0].nonExistingField);

      console.log("-----");
      
      var b = new kendo.data.DataSource({schema:{model:{id: "nonExistingField"}}});
      b.data([{name: "lorem ipsum", nonExistingField: "foo"}]);
      console.log("expected: \"undefined\", actual: " + b.data()[0].id);
      console.log("expected: \"foo\", actual: " + b.data()[0].nonExistingField);

      console.log("-----");
      console.log("this seems the only correct case when the id field is called \"id\"");
      
      var c = new kendo.data.DataSource({schema:{model:{id: "id"}}});
      c.data([{id: "lorem ipsum", someOtherField: "test"}]);
      console.log("expected: \"lorem ipsum\", actual: " + c.data()[0].id);
      console.log("expected: \"test\", actual: " + c.data()[0].someOtherField);
      
    });
```

### Expected/desired behavior

Only the field set in `schema.id` must be modified with the values for the id, there must be no hardcoded changes to a named field.

### Environment

* **Kendo UI version:** 2019.1.115 (probably in all versions)
* **jQuery version:** 1.12.4 (probably in all versions)
* **Browser:** all

**Comment by boyandim** [comment]
Indeed this behavior is expected. The "id" is reserved field in the model and it is populated with the value defined in the schema.model.id field. I agree that we should document this in the Schema section of the CRUD operations article.
