### ISSUE TITLE
Anchor Button (Custom Button) with icon in TreeList

### ISSUE THREAD

**Issue by ravi-ku** [telerik/kendo-ui-core#4808]
Is it possible to have Anchor Button (as custom button) with icon in TreeList?

![image](https://user-images.githubusercontent.com/11146609/52034258-fa168480-254d-11e9-9153-cb8288151679.png)

### Bug report

**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our UserVoice feedback portal](http://kendo.uservoice.com/)**

### Reproduction of the problem
_(bug report only)_
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via http://dojo.telerik.com or similar.

### Current behavior
_(optional)_
Provide additional information if the steps for reproducing the faulty behavior are not sufficient to describe the issue.

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment

* **Kendo UI version:** 2015.r.ddd
* **jQuery version:1.9.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Dimitar-Goshev** [comment]
As it is written in the issue template please do not submit support request here, instead use the Kendo UI [Premium Forums](https://www.telerik.com/forums/kendo-ui) or [our support system](https://www.telerik.com/support) at Telerik.com .
