### ISSUE TITLE
Add a table in the Documentation for matching Kendo releases and Sass themes version

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4811]
We should add a table in the Documentation for matching Kendo releases and Sass themes version. This will help the customers downloading the correct theme version from NPM and match it with our scripts

**Comment by Dimitar-Goshev** [comment]
Also asked for it in ticket 1409137

**Comment by alexandrejobin** [comment]
In the meantime, how can I know which version I should use with a specific version of KendoUI?

**Comment by TeyaVes** [comment]
While this part of the documentation is still pending, you can follow the suggested approach below to match the version of Kendo UI with the Sass-themes release:

1. Check the date of the latest official release or the latest internal build of Kendo UI in your telerik.com Account, under Downloads > Progress Kendo UI. Take a look at the following screenshot for a reference. 

![latestKendoUI](https://user-images.githubusercontent.com/45764088/59439017-2e078d80-8dfd-11e9-95d1-431995065cd0.png)

2. Check the Sass-themes release dates in our GitHub repository:

https://github.com/telerik/kendo-themes/releases

3. From there, you can see which version of the desired theme has been released right before the Kendo UI release.

**Comment by alexandrejobin** [comment]
Thank you for this little guide. Obviously, when you will release a table to know exactly which version is used with Kendo, it will be better for everyone!

**Comment by Juveniel** [comment]
Also reported in Ticket ID:1425379

**Comment by nenchef** [comment]
Done. The article can be found here:
https://docs.telerik.com/kendo-ui/styles-and-layout/sass-version-compatibility

**Comment by foxontherock** [comment]
Hi, can you update the table on each version release? 
Actually, which version of the UI should we use with kendo-ui 2022.1.119 ? 
I suppose we use the latest, that is actually 5.1.1 ?
Thank you.
