### ISSUE TITLE
Unable to post Form with kendoValidator and unchecked Switch

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#4813]
### Bug report

Reported in 1384612

### Reproduction of the problem

Project available in the ticket.

1. Post the form

### Current behavior
Switch prevents the form from posting when unchecked. The behavior should be analogical to the Checkbox.

### Expected/desired behavior
The form is submitted with unchecked switch.

### Environment

* **Kendo UI version:** 2019.1.115
* **Browser:** all

**Comment by YS871** [comment]
Same issue with ASP.Net MVC
