### ISSUE TITLE
Flickering custom cell editor for Spreadsheet column with configured filtering / sorting and SASS themes in Chrome and FF

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4815]
### Bug report
Flickering custom cell editor for Spreadsheet column with configured filtering / sorting and SASS themes used.

### Reproduction of the problem
* Run the following [Dojo](https://dojo.telerik.com/OFoTimOm/3);
* Click on B4 or B5 cell to display the custom cell editor button;
* Click on custom cell editor button;

### Current behavior
The custom cell editor pop-up will flicker and disappear - [video](https://www.screencast.com/t/AMncVXcZX0w)

### Expected/desired behavior
The pop-up should stay opened

### Environment
* **Kendo UI version:** 2019.1.115
* **Browser:** Chrome 71 and FF 64

**Comment by veselints** [comment]
To workaround the above, I would suggest you to define your own custom date cell editor. Here you could find a small sample implementing such scenario:
https://dojo.telerik.com/OFoTimOm/11

**Comment by veselints** [comment]
Reported also in Ticket ID: 1385909

**Comment by martintabakov** [comment]
Also reported in Ticket ID: 1427843
