### ISSUE TITLE
Spreadsheet disabled cell with link does not navigate to its URL

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4824]
### Bug report
Spreadsheet disabled cell with link does not navigate to its URL. 

The above is a regression introduced with R1 2019.1.115

### Reproduction of the problem
* Run the following [Dojo](https://dojo.telerik.com/EmApufin/5);
* Click on the cell text - nothing will happen;

### Current behavior
Nothing happens on link text click.

### Expected/desired behavior
Upon click, the browser should navigate to the link URL.

### Environment

* **Kendo UI version:** 2019.1.115
* **Browser:** all

**Comment by mishoo** [comment]
[This commit](https://github.com/telerik/kendo/commit/dc73f9668470a56a29c78bd363d29be7fa25786d#diff-764164880047d632727199507e2d4206R175) seems to have caused the issue.  A disabled cell gets the `k-state-disabled` class, to which the linked commit deactivates pointer events.

**Comment by veselints** [comment]
Fixed in Kendo with: https://github.com/telerik/kendo/pull/9364/commits/eaa09d9347a1f7285c5a3214ff0e90da75c77593
