### ISSUE TITLE
VuejS - DOM is not updated when using v-if/v-else

### ISSUE THREAD

**Issue by occirol** [telerik/kendo-ui-core#4825]
## Bug report

When a MaskedTextBox is use within a v-if/v-else, DOM is not updated accordingly.
Maybe related to: #4671 

### Reproduction of the problem
[stackblitz fiddle](https://stackblitz.com/edit/vue-9jzqyx)

1. Click on switch button

### Current behavior
When _if_ condition is changing, component in the v-if is not destroyed properly.

**Before condition change**
```
<span class="k-widget k-maskedtextbox" style="">
  <input data-role="maskedtextbox" style="width: 100%;" class="k-textbox" autocomplete="off">
  <span class="k-icon k-i-warning"></span>
</span>
<small>kendo-maskedtextbox</small>
```
**After condition change**
```
<span class="k-widget k-maskedtextbox" style="">
  <span class="k-icon k-i-warning"></span>
</span>
<small>kendo-dateinput</small>
```
### Expected/desired behavior
The component isinde the v-else should be displayed.

**Before condition change**
```
<span class="k-widget k-maskedtextbox" style="">
  <input data-role="maskedtextbox" style="width: 100%;" class="k-textbox" autocomplete="off">
  <span class="k-icon k-i-warning"></span>
</span>
<small>kendo-maskedtextbox</small>
```
**After condition change**
```
<span class="k-widget k-dateinput k-state-default" style="">
  <input data-role="dateinput" style="width: 100%;" class="k-textbox" autocomplete="off" type="text">
  <span class="k-icon k-i-warning"></span>
</span>
<small>kendo-dateinput</small>
```

### Environment

* **Kendo UI version:** 2019.1.206
* **Browser:** [Chromium 71 | Firefox 60.5.0esr | Firefox 65 | Edge 44.17763.1.0]

**Comment by occirol** [comment]
#4671

**Comment by zdravkov** [comment]
It seems that in this case the input element of the components is considered the same for both components and is removed in beforeDestroy just after it have been created by the other component. In such case we would rather recommend to set keys to both container so that the elements are considered different. Here is an updated example - https://stackblitz.com/edit/vue-dn58xd?file=index.html
