### ISSUE TITLE
Chat incorrect message bubble background color in the Bootstrap theme

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4829]
### Bug report
Bubbles in Bootsrap v3 appear transparent.

### Reproduction of the problem
Reproducible in the [demos](https://demos.telerik.com/kendo-ui/chat/travel).
1. Select Bootstrap v3 in the theme chooser.
2. Inspect the messages of the "Travel agent" 

### Current behavior
The background-color of the message bubble  is #fff (it is applied to the **k-bubble** class)

### Expected/desired behavior
According to the design the background-color of the message bubble should be #eaeaea

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** [all]

**Comment by magdalenaan** [comment]
The issue cannot be reproduced with the 2022.3.913 version.
