### ISSUE TITLE
Incorrect background-color applied to the k-state-selected class in BlueOpal theme

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4831]
### Bug report
Regression introduced in R1 2019. It affects the dropdown widgets selected item background color and the background color of the current page in the Grid's pager. The respective elements use the **k-state-selected** class and the background-color applied to this class has been changed in R1 2019. 

### Reproduction of the problem
Reproducible in the DropDownList, ComboBox, MultiSelect demos:
1. Select blueopal in the theme chooser.
2. Inspect the selected item in the list.

 Grid's pager - inspect the current page in the pager (the span with class "k-state-selected"): [demo](https://demos.telerik.com/kendo-ui/grid/index)

### Current behavior
The background color is #7bd2f6

### Expected/desired behavior
The background color is #13688c

[Feedback Portal item](https://feedback.telerik.com/aspnet-mvc/1386575-styling-for-blue-opal-theme-has-changed-in-latest-release)

### Environment

* **Kendo UI version:** 2019.1.115
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
Related to https://github.com/telerik/kendo-ui-core/issues/4828
