### ISSUE TITLE
SecurityTrimming's HideParent should hide the topmost item that appears empty after trimming items

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#4833]
### Bug report

HideParent hides the first-level parent that fails authentication, but there are cases that the topmost parent should be hidden as well. 

### Reproduction of the problem

Check out the attached project: 
[Menu-Autorization-Areas.zip](https://github.com/telerik/kendo/files/1193143/Menu-Autorization-Areas.zip)

Without logging, the Areas item is available, although it is empty and it should be hidden.

### Environment

* **Kendo UI version:** 2017.2.621
* **jQuery version:** 1.12.3
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
Reported in ticket ID 1386950

**Comment by jivanova** [comment]
Reported in ticked ID 1398360
