### ISSUE TITLE
SecurityTrimming should hide non-area actions from area actions

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#4834]
### Bug report

Implementing MVC Areas and authentication rights with SecurityTrimming of the Menu, it is expected when logged in an Area, the non-area autentication to fail and thus hide non-area actions from the Menu items

### Reproduction of the problem
Run the new version attached project:
Newer version project - [Menu-Authorization-Areas.zip - 2019.2.619](https://github.com/telerik/kendo-ui-core/files/3534406/Menu-Autorization-Areas-R22019SP1.zip)

Originally logged with version - [Menu-Autorization-Areas.zip - 2017.2.621](https://github.com/telerik/kendo/files/1193114/Menu-Autorization-Areas.zip)

1. Log with the test@test.com user (not an admin), available in the Login page;
1. See that only Home, About and AreaOne/First are available;
1. Go to AreaOne/First

### Current behavior
Home, About, **Content** and AreaOne/First are available. But **Contact** fails authentication and should be trimmed:
```
        [Authorize(Roles="Admin")]
        public ActionResult Contact()
```

### Expected/desired behavior
Home, About and AreaOne/First to be available. **Contact** should be trimmed.

### Environment
* **Kendo UI version:** 2019.3.619
* **jQuery version:** 1.12.3
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
Reported in ticket ID 1386950
