### ISSUE TITLE
Editor does not preserve empty lines, when bold text is Copy Pasted

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4835]
### Bug report
Editor does not preserve empty lines, when bold text is Copy Pasted. A `<p>` element is created for the empty line, but it contains an empty `<strong>` element. It should instead contain `<strong>﻿&#65279;</strong>`.

### Reproduction of the problem
* Go to the [Index Editor demo](https://demos.telerik.com/kendo-ui/editor/index);
* Clear all Editor content;
* Enter any text inside a kendo editor eg. "Test" and make it bold;
* Copy the above entered text;
* Press Enter twice to create two new lines;
* Paste;
* Now copy the entire content;
* Paste;
* Observe the new content pasted does not contain the new line.

![editor-paste-issue](https://user-images.githubusercontent.com/3431388/52551180-0a4b2100-2de4-11e9-81a2-33ef74077902.gif)

### Current behavior
The new line element remains empty.

### Expected/desired behavior
The new line element should instead contain `<strong>﻿&#65279;</strong>`.

### Environment
* **Kendo UI version:** 2019.1.115
* **Browser:** [all]

**Comment by sspasova** [comment]
The issue is fixed. Tested with Kendo UI version 2023.3.1114.
