### ISSUE TITLE
Router change event fires even though back event is prevented 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4838]
### Bug report
Reproducible with pushState enabled in the Router's configuration.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/uQekUjoP) example. 
1. Open the dojo in fullscreen, to observe the changes to the url
2. Open the browser's console. 
3. Click on "Go to view 2" 
4. Click on the browser's back button. 

The Router's back event is prevented, but the change event still fires. 

### Current behavior
Change event fires

### Expected/desired behavior
Change event does not fire

### Environment

* **Kendo UI version:** 2019.1.115
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Not reproducible with the latest version
