### ISSUE TITLE
Caret in MaskedTextBox

### ISSUE THREAD

**Issue by RaptorCZ** [telerik/kendo-ui-core#4839]
I know there is old closed issue for this
https://github.com/telerik/kendo-ui-core/issues/91

But it starts to be a real problem. Customers are sending issues because of this behavior. Moving caret to begin of text is unexpected and annoying.

Let's say you are writing text in TextBox, then alt tabbing out of page, returning back to continue and you are just overwriting text instead of continue. This IS bug, not feature.

Could someone please think about it again an provide fix or workaround?

**Comment by RaptorCZ** [comment]
so? This gets really critical for us on projects.

**Comment by ag-petrov** [comment]
As mentioned in the related issue, this was the initial design behavior. Currently we can suggest detaching the focus handler and moving its logic outside of the component. In this process the initial highlight logic should also be removed. [Here ](https://dojo.telerik.com/AcokaLAH)is a dojo illustrating this approach.

**Comment by RaptorCZ** [comment]
Is there any way how to do the same for NumericTextBox? How to detach focus and keep caret position?
