### ISSUE TITLE
Is "Telerik UI for ASP.NET Core 2019.1.115" support .net Core 3 preview & Visual Studio 2019 preview? 

### ISSUE THREAD

**Issue by OptivolveRodanAlSaleh** [telerik/kendo-ui-core#4840]
I am trying to use "Telerik UI for ASP.NET Core 2019.1.115" with .net core 3 preview version using Visual studio 2019 preview,
Is this version of telerik "2019.1.115" support .net core 3 preview?

**Comment by Stamo-Gochev** [comment]
.NET Core 3 preview version is not currently supported. When the code is updated to support it, we will update the official information channels regarding this as it is a major update.
