### ISSUE TITLE
Add functionality to disable the responsive Pager

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4841]
### Feature Request

Add functionality to disable the responsive Pager.

**Comment by PreslavKozovski** [comment]
Feedback portal item:
https://feedback.telerik.com/kendo-jquery-ui/1387726-add-functionality-to-disable-the-responsive-pager

**Comment by PreslavKozovski** [comment]
Move this to `Ready for Test` when https://github.com/telerik/kendo/commits/adaptive-grid is merged into `master`

**Comment by MilenaCh** [comment]
Pager's layout is broken in MVC wrappers with less themes:
https://www.screencast.com/t/bFyGx9t0l
