### ISSUE TITLE
Date time pickers with dateinput option date parts can not be translated

### ISSUE THREAD

**Issue by SuperPat45** [telerik/kendo-ui-core#4847]
### Bug report

For the three date and time pickers components, when using the dateinput option, date parts (day/month/year ...) can not be translated because these components does not have a messages option: 
```
    messages:{
        "year": "year",
        "month": "month",
        "day": "day",
        "weekday": "day of the week",
        "hour": "hours",
        "minute": "minutes",
        "second": "seconds",
        "dayperiod": "AM/PM"
    }
```

**Comment by matanasov** [comment]
Indeed there is no dedicated properties for configuring the messages when date input is used in the picker. However, you can still access the date input component and set its own messages as demonstrated in this DoJo:
https://dojo.telerik.com/UMezat

**Comment by Alex-Bubblemaster** [comment]
@SuperPat45 Can you vote for this functionality to be available feature [here](https://feedback.telerik.com/kendo-jquery-ui/1408324-kendo-ui-datepicker-dateinput-should-accept-an-options-object) ? Alternatively, it could be that the language you are using does not have the messages translated yet. So you could send us a pull request in the repository or submit a ticket with the changes. Example: 

```
if (kendo.ui.DateInput) {
  kendo.ui.DateInput.prototype.options.messages =
    $.extend(true, kendo.ui.DateInput.prototype.options.messages, {
      "year": "година",
      "month": "месец",
      "day": "ден",
      "weekday": "ден от седмицата",
      "hour": "часа",
      "minute": "минути",
      "second": "секунди",
      "dayperiod": "AM/PM"
    });
}
```

**Comment by SuperPat45** [comment]
@Alex-Bubblemaster  Done
