### ISSUE TITLE
Setting the same value for Min and Max should allow selection only that value

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#4849]
### Reproduction of the problem
Run [this dojo](https://dojo.telerik.com/oYiQufut)
Open the time popup 

### Current behavior
Multiple time options are shown

### Expected/desired behavior
Only the time specified in Min and Max should be available for selection

### Environment

* **Kendo UI version:** 2019.1.115
* **Browser:** [all]

**Comment by VicTachev** [comment]
As a workaround the interval can be set to 24 hours:

https://dojo.telerik.com/ahuZAjAj

**Comment by boyandim** [comment]
The fix for [this issue](https://github.com/telerik/kendo-ui-core/issues/1552) resolves the problem described here.
