### ISSUE TITLE
ComboBox in Grid column loses its value if the Grid's cells are clicked fast

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4850]
### Bug report
Regression introduced in 2019.1.115. Reproducible in IE11. Not reproducible with a DropDownList.

### Reproduction of the problem
1. Setup: virtualized ComboBox in a Grid column EditorTemplate.
2. Click fast on the SEGMENT1 column cells

[Screencast](https://www.screencast.com/t/UKqaUwyk). For more details and a sample project see ticket id: 1385320

### Current behavior
ComboBox loses its value.

### Expected/desired behavior
ComboBox does not lose its value.

### Environment

* **Kendo UI version:** 2019.1.115
* **jQuery version:** x.y
* **Browser:** [IE11]

**Comment by zdravkov** [comment]
The issue starts appearing after this commit - https://github.com/telerik/kendo/commit/56708f8ff96bc946954f8c346a0a0eb62b4a4097 part of this issue https://github.com/telerik/kendo-ui-core/issues/3707.

**Comment by ag-petrov** [comment]
QAs please double check issue #3707 , more precisely keyboard navigation works after checkbox is clicked.
