### ISSUE TITLE
Focus on table filters are very difficult to distinguish from non-selected options

### ISSUE THREAD

**Issue by sryeluri** [telerik/kendo-ui-core#4854]
OS: Windows 1809

Browser: Chrome 70.0.3538.77
Assistive Technology: NVDA 2018.2.1

Steps:
1. Navigate to Application URL
2. Press tab to navigate to the table filters.
3. Observe that focus is challenging to distinguish between the currently focused option and the other filters.

Actual Results: 
Users will have difficulty determining which element has focus.

Expected Results:
The element with focus should be apparent.

**Comment by matanasov** [comment]
The reported Kendo version (2015.2.805) is quite old. Many accessibility improvements were implemented in later versions and I would suggest that you re-verify the problem with latest version (2019.1.220).
