### ISSUE TITLE
Form elements must have labels (.grid-dropdown)

### ISSUE THREAD

**Issue by sryeluri** [telerik/kendo-ui-core#4855]
below is an accessibility issue that needs investigation.

Issue Details
Form elements must have labels

Expected Fix : 
- aria-label attribute does not exist or is empty
- aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
- Form element does not have an implicit (wrapped) <label>
- Form element does not have an explicit <label>
- Element has no title attribute or the title attribute is empty

Environment
Chrome version 70.0.3538.77

**Comment by matanasov** [comment]
The reported Kendo version (2015.2.805) is quite old. Many accessibility improvements were implemented in later versions and I would suggest that you re-verify the problem with latest version (2019.1.220).
