### ISSUE TITLE
Company select table uses non standard controls

### ISSUE THREAD

**Issue by sryeluri** [telerik/kendo-ui-core#4856]
OS: Windows 1809

Browser: Chrome 70.0.3538.77
Assistive Technology: NA

Tools: NA

Steps:
1. Navigate to Application
2. Press tab until focus is given to the table.
3. Observe the following:
Pressing tab provides focus to the "XXX" elements but attempting to use arrow navigation activates these elements.
Users are unable to exit the combo box options without completely leaving the table.
Unable to select XXX with the enter key.

Actual Results: 
Users expecting to use arrow keys will not be able to navigate the page once focus is given to the combo boxes.

Expected Results:
Users should be able to freely navigate the table/grid.

**Comment by matanasov** [comment]
The reported Kendo version (2015.2.805) is quite old. Many accessibility improvements were implemented in later versions and I would suggest that you re-verify the problem with latest version (2019.1.220).

**Comment by kraay** [comment]
@matanasov Thanks for the suggestion. Are there any known accessibility issues with the latest version? We want to make sure that the changes are backward compatible and upgrading will not create new accessibility issues.

**Comment by MilenaCh** [comment]
Currently, we are not aware of **regression** accessibility issues. However, you can check our [public repo](https://github.com/telerik/kendo-ui-core/issues) for other known accessibility issues and enhancements. 
 
In regard of the current issue, I would recommend you to enable [nevaigatable ](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/navigatable)functionality and use the built-in keyboard navigation of Grid. Thus, the user will be able to navigate between the cells with arrow keys and then 'Select' component will be activated only if enter key is pressed. You can also exit from edit mode of 'Select' element with 'Esc' key. You can see how it works [here](https://dojo.telerik.com/@milena/opILOXoW).
