### ISSUE TITLE
Grid does not resize correctly inside window

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#4858]
### Bug report

The grid does not resize correctly.

### Reproduction of the problem

* open https://dojo.telerik.com/@joneff/ihAkIWaj
* resize the window verticaly to increase height
* resize the window horizontally to decrease height

### Current behavior

the grid does not resize down correctly, causing an extra scrollbar to appear

### Expected/desired behavior

The grid should resize down correctly

### Environment

* **Kendo UI version:** 2019.1.115
* **Browser:** All that support flexbox

Reported in 1177186

**Comment by jagjitraja** [comment]
**Also, this issue causes the scrollable content ot be displayed over the grid when the page loads and autoBind is set to true with not page size set in the datasource with endless scrolling.**

.Sortable(true)
.AutoBind(true)
.Scrollable(scroll => scroll.Endless(true))
.NoRecords(true)
 .HtmlAttributes(new { style = "width:100%;height:450px;" })
.DataSource(dataSource => dataSource
                              .Ajax()
                              .Read(read =>
                                  read.Action("GetItems", "Items", new
                                  {
                                      incidentId = Model,
                                      itemType = "item"
                                  }))
                              .ServerOperation(false)
                              .Model(model => model.Id(c => c.Id))))

![image](https://user-images.githubusercontent.com/22244462/53444908-38278c80-39c4-11e9-84e7-34204b7d0033.png)

**Comment by TeyaVes** [comment]
@joneff , @jagjitraja , I do not think this is a bug in the grid, but rather in the flexbox behavior. If we add "min-height: 0" to the container wrapping the grid with "flex: 1 1 auto", the grid will be resized correctly. Please, check the updated Dojo:

[https://dojo.telerik.com/aGeZoLuk/2](https://dojo.telerik.com/aGeZoLuk/2)
