### ISSUE TITLE
Grid Filter links do not have accessible texts

### ISSUE THREAD

**Issue by kraay** [telerik/kendo-ui-core#4860]
### Bug report

The filter links used in Kendo grid (AngularJS v1.7) do not have an accessible text and shows the following errors on running Automated Checks on Keros for Web - 

Issue Details
Links must have discernible text

Expected Fix :
Element does not have text that is visible to screen readers
aria-label attribute does not exist or is empty
aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
Element's default semantics were not overridden with role="presentation"
Element's default semantics were not overridden with role="none"

### Reproduction of the problem

Mock application  - https://runner.telerik.io/fullscreen/oXokIKeS
Code - https://dojo.telerik.com/oXokIKeS

### Current behavior
On running Automated Checks on the Keros for Web (now Accessibility Insights for Web) extension on Google Chrome, the filter links are showing the error - "Links must have discernible text".

### Expected/desired behavior
Links must have aria labels associated

### Environment

* **Kendo UI version:** 2015.2.805
* **Browser:** Google Chrome

**Comment by matanasov** [comment]
The reported Kendo version (2015.2.805) is quite old. Many accessibility improvements were implemented in later versions and I would suggest that you re-verify the problem with latest version (2019.1.220).
Here is a modified DoJo:
https://dojo.telerik.com/@martinpz/EVAwAHEs
