### ISSUE TITLE
TreeList pager does not refresh when All pageSize is selected

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#4868]
### Bug report

Reported in ticket with ID 1389358 

### Reproduction of the problem

- page the TreeList next page/any page
- select "All" from the pageSizes dropdown

[Dojo](https://dojo.telerik.com/@bubblemaster/UNOgAzuz)

### Current behavior

![image](https://user-images.githubusercontent.com/10980842/53335846-4498e000-3905-11e9-9d65-c717ed924916.png)

Possibly related with #4144

### Expected/desired behavior

Pager input and current page should show 1.

### Workaround

[Dojo](https://dojo.telerik.com/@bubblemaster/eQogAcIb)

```
var treelist = $("#treelist").data("kendoTreeList");
treelist.one("dataBound", function(e){
  var pager = e.sender.pager;
   pager.dataSource.bind("change", function(ev){
     // All pages selected         
     if(ev.items.length === ev.sender.data().length){
      $("[title='More pages']").click();
     }
   });
 });
```

### Environment

* **Kendo UI version:** 2019.1.220

**Comment by gyankov** [comment]
The issue does not reproduce in 2019 R2 version.
