### ISSUE TITLE
DatePicker value is not reset to Min/Max when entering out of range date

### ISSUE THREAD

**Issue by CecoMilchev** [telerik/kendo-ui-core#4871]
### Bug report

The issue is reproducible when the DatePicker with DateInput is used as an editor in Kendo Grid for ASP.NET MVC with "InCell" edit mode. 

When a value which is less than the Min value or more than the Max value is typed in, the DatePicker is left blank rather than applying the Min/Max value. 

### Reproduction of the problem

1. Create a grid and set the "InCell" edit mode.
2. Create a DatePickerFor() editor and enable the DateInput(true) property.
3. Input value which is before 1/1/1900 or after 12/31/2099. E.g 1/1/1111
4. Value is left blank instead of the Min value being applied. (Same goes for Max value)

### Current behavior

When value before 1/1/1900 or after 12/31/2099 is typed in, the cell is left blank instead of the Min/Max value being applied.

### Expected/desired behavior

Apply Min/Max value to the model, instead of null.

### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by CecoMilchev** [comment]
As a workaround, the following can be applied:

1. Subscribe to the cellClose event of the grid:
`.Events(ev => ev.CellClose("cellClose"))`

2. Set the model's value in the event handler as follows:

```
function cellClose(e) {
    var orderDate = e.container.find("input[data-role='datepicker']").data().kendoDatePicker._dateInput.value();
    e.model.set("OrderDate", orderDate);
}
```

**Comment by ag-petrov** [comment]
The behavior is due to [this](https://github.com/telerik/kendo-ui-core/issues/3828) limitation. Generally speaking in order to correct this we need to make a breaking change which is not desired. That said I suggest either using the workaround which @CecoMilchev provided. Or using only a DateInput control as an editor for this case which will autocorrect the values.
