### ISSUE TITLE
Spreadsheet incorrect formatting and rounding for the number 1000000000000000

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4873]
### Bug report
When formatted with two symbols after the decimal stop, the Spreadsheet displays the number 1,000,000,000,000,000 as 999,999,999,999,999.90. 

This is a regression introduced with the R1 2019.1.115 release.

Possibly related to: #4700 

### Reproduction of the problem
Run the following Dojo: https://dojo.telerik.com/uNOPaSeM/14

### Expected/desired behavior
The number should be displayed as: 1,000,000,000,000,000.00

### Environment
* **Kendo UI version:** from 2019.1.115
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
After the fix, if cell format is Automatic ( format(null) ) cells display wrong decimal part:
- value 123.79 is displayed as 123.79000000000001 - Reproducible on DataSource demo - Cell C30
- value 999.79 is displayed as 999.78999999999996 - Reproducible on all demos when entering 999.79 and then setting cell format to Automatic
