### ISSUE TITLE
Scheduler editable window settings are not serialized

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4875]
### Bug report

When certain options of the editable Window are set through configuration, they are not being serialized correctly:

* MinWidth
* MinHeight
* Events (Open, Close, etc.)

### Reproduction of the problem
```cs
@(Html.Kendo().Scheduler<TelerikAspNetCoreAppScheduler.Models.TaskViewModel>()
   .Editable(e => e.Window(w => 
      w.MinHeight(1000)
        .MinWidth(1000)
        .Events(we => we.Open('onOpen'))))
)
```

### Current behavior

Options are not serialized correctly, thus not applied to the active Window instance.

### Expected/desired behavior

The options should be serialized.

### Environment

* **Kendo UI version:** 2019.1.220
* **Browser:** [all]

**Comment by Juveniel** [comment]
Feedback portal item: [#1398231](https://feedback.telerik.com/aspnet-core-ui/1398231-scheduler-editable-window-settings-are-not-serialized)

**Comment by zdravkov** [comment]
We need to set these options through the Resizeble method of the Window as it is shown below:
` .Editable(e => e.Window(w => w.Resizable(r=>r.MinHeight(1000).MinWidth(1000))))`

**Comment by nenchef** [comment]
Item in Kendo Sprint https://github.com/telerik/kendo/issues/11781
