### ISSUE TITLE
DropDownTree cannot load its data after binding to no data

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#4877]
### Bug report

https://dojo.telerik.com/UlefOZeK/2

The issue is only reproducible with `autoBind: false` and after binding the DropDownTree to no data and then back with data. Not reproducible neither with [treeview standalone](https://dojo.telerik.com/IFofimIn), nor multiselect.

### Reproduction of the problem
1. Open the DropDownTree
2. Select `two` option from the DropDownList
3. Open the DropDownTree
4. Select `one` option from the DropDownList

### Current behavior
DropDownTree cannot fetch its data changes

### Expected/desired behavior
DropDownTree fetches its data

### Environment

* **Kendo UI version:** 2019.1.220
* **Browser:** all

**Comment by sspasova** [comment]
The issue is no longer reproducible with Kendo UI version 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/ecipeSAc
