### ISSUE TITLE
LESS ThemeBuilder is not setting the Selected background color to Calendar

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#4885]
### Bug report

LESS ThemeBuilder is not setting the Selected background color to Calendar:

https://www.screencast.com/t/c2f5f5YhH

**Comment by Juveniel** [comment]
Also reported in TicketID: 1429510

**Comment by Juveniel** [comment]
Also reported in TickerID:1450275

**Comment by IvanDanchev** [comment]
Also reported in Ticket ID: 1476597
