### ISSUE TITLE
Scheduler : Series Events Cannot Be Deleted

### ISSUE THREAD

**Issue by zubair1103** [telerik/kendo-ui-core#4893]
### Bug report
Scheduler widget is throwing error when delete event from series.
### Reproduction of the problem
Create an event and define repeat rule
Save the event
Delete 1st occuerence
Choose Delete the series
### Current behavior

- choose **Delete the series**; following error occurs
`Uncaught TypeError: Cannot read property 'recurrenceException' of undefined`
- choose **Delete current occurrence**; following error occurs
`Uncaught TypeError: Cannot read property 'startTimezone' of undefined`
### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** 1.12.4

**Comment by zubair1103** [comment]
It happens in all previous versions of kendo ui.

**Comment by zdravkov** [comment]
Such error is observed when the configuration of the SchedulerDataSource is without "dataSource.schema" definition. Please note that adding "dataSource.schema.model" option with all fields described is required for correct operation of the Scheduler when editing events is enabled or you need to render recurring events. [Scheduler: kendo.data.SchedulerEvent](https://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/overview#kendodataschedulerevent)

**Comment by zubair1103** [comment]
I just checked again by defining `dataSource.schema` and still observed the error.
My observation is that it occurs when `dataSource.transport` is not defined.

If `dataSource.transport` is defined then it works fine even `dataSource.schema` is not defined.

**Comment by zdravkov** [comment]
Thank you for providing this information - yes the` dataSource.transport` should also be defined correctly.

**Comment by ripal-patel0** [comment]
I am getting same error as [zubair1103](https://github.com/zubair1103) mentioned with Kendo UI v2022.2.802. dataSource.schema and dataSource.transport set correctly still getting error on deleting recurring events.
