### ISSUE TITLE
TreeList "No records to display" is displayed below pager.

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-ui-core#4897]
With filtering and paging enabled, TreeList shows `No records to display` bellow its pager.

Steps to repro:

1. Use this demo:
https://demos.telerik.com/kendo-ui/treelist/index

2. Filter the TreeList so that no items are returned.
3. Note the `No records to display` is displayed below the pager, but should be above it:

![pager](https://user-images.githubusercontent.com/5861835/54025991-fc02e180-41a4-11e9-802c-10bd6dd09122.png)

**Comment by ag-petrov** [comment]
I have changed the no records template rendering to be consistent with that of the grid.
