### ISSUE TITLE
MultiSelect deselected items remain highlighted in the list

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4902]
### Bug report
Regression introduced in R1 2018. Since this release the **k-state-selected** class is no longer removed from the respective li element when an item is removed by pressing Backspace key. 

### Reproduction of the problem
[Dojo example](https://dojo.telerik.com/EhuseWuH/2)

The widget's autoClose option is set to **false**.
1. Click the MultiSelect and select several items. 
2. Deselect the items by pressing Backspace key.

### Current behavior
The items are removed from the input area, but remain highlighted in the list.

### Expected/desired behavior
The items are removed from the input area and are no longer highlighted in the list.

[Feedback Portal item](https://feedback.telerik.com/kendo-jquery-ui/1399601-multiselect-highlights-items-in-the-list-after-they-are-deselected)

### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
After the fix, there is a js error thrown in the following scenario:
- select 3 items (with mouse or keyboard)
- select the 2nd item's token in the multiselect with keyboard left arrow key
- press Backspace/Delete to delete the 2nd item
- press Backspace to delete the last item

`listView.select(...).done is not a function`

```
            if (customIndex === undefined) {
                that.persistTagList = false;
                listView.select(listView.select()[position]).done(done);
            } else {
```
