### ISSUE TITLE
Cannot read property 'firstSlot' of undefined thrown when remote resources with grouping and autoBind: false are used

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/kendo-ui-core#4905]
### Reproduction of the problem

The scheduler does not know what slot table to render when its resources are remote, and with autoBind: false, when the events arrive there is no table and `"Cannot read property 'firstSlot' of undefined` is thrown.

Repro dojo: [http://dojo.telerik.com/IqoNIboc](http://dojo.telerik.com/IqoNIboc)

### Expected/desired behavior

No error and events are bound and rendered as if the resources were local, or data binding was not deferred.

### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** 1.12.3
* **Browser:** all

**Comment by marin-bratanov** [comment]
Reported in Ticket ID: 1399408

**Comment by mparvanov** [comment]
The following sample represents how to fetch the resources: 
[https://dojo.telerik.com/UTIhUQuR/3
](https://dojo.telerik.com/UTIhUQuR/3
) 
This is working properly after the fix.
