### ISSUE TITLE
Grid - exporting to PDF with nested TABLE elements in cells breaks the layout

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#4927]
### Bug report

When the PDF export **paperSize** is set, when there are nested TABLE elements in the Grid cells, the layout breaks on export.

### Reproduction of the problem
[https://dojo.telerik.com/UzafiBed/2](https://dojo.telerik.com/UzafiBed/2)
The exported file will have broken structure for the cells

### Environment

* **Kendo UI version:** 2019.1.220

**Comment by sspasova** [comment]
The issue is fixed with Kendo UI version 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/uNaQafOY
