### ISSUE TITLE
Unable to bind MultiSelect with selected values to model after form submitting

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#4930]
### Bug report
MultiSelect with AutoBind false and selected items does not show the selected values after form submitting

### Reproduction of the problem
1. Run the attached project
[MultiSelectFor.zip](https://github.com/telerik/kendo-ui-core/files/2989192/MultiSelectFor.zip)
1. Click on Submit button to submit the form

### Current behavior
If there are any selected items in the MultiSelect on submit, then after submitting the form the MultiSelect has no items and does not display any items.

NOTE: If there are no selected items in the MultiSelect on submit, then after submitting the form the MultiSelect has items.

### Expected/desired behavior
After submitting the form, the MultiSelect has selected items.

### Environment
* **Kendo UI version:** 2019.1.220
* **Browser:** [all]

**Comment by Chris-FLD** [comment]
I believe 2019.R2.SP1 has been released now yet this bug hasn't been fixed. Is there any update on this?

**Comment by Dimitar-Goshev** [comment]
@Chris-FLD The issue is fixed in 2019.R2 release. But the project attached to the issue is also not configured properly. The model of the submit method is expecting objects and yet the values of the MultiSelect are sending strings - that is the expected behavior for MultiSelect component.

Kendo MultiSelect component is rendering a select element under the hood and the submitted values are taken from this select element. That is why when using MultiSelect we can only submit primitive values that could be taken from the selected values of a simple `<select>` element and sent to the server. In our case, we are having a model that only uses objects(AvailableFeatures) and that is why after submit it can never get the desired selected values.

In such cases in order to have a correct behavior with a native form submitting, we recommend adding a new field in the model with primitive type (for example a list of  AvailableFeatureIds). Then we can use this model field to submit the selected ids and then on the server extract the AvailableFeatures that are corresponding to these selected AvailableFeatureIds and return them to the View so that the MultiSelect is populated correctly.

So the needed corrections in the project are:

1. Add `public List<string> AvailableFeatureIds { get; set; }` to AvailableFeature class.
1. Bind the MultiSelect to AvailableFeatureIds - `@(Html.Kendo().MultiSelectFor(m => m.AvailableFeatureIds)`
1. Extract the AvailableFeatures using AvailableFeatureIds:
```
        [HttpPost]
        public IActionResult SubmitForm(AvailableFeature model)
        {
            if (ModelState.IsValid)
            {
            }

            model.AvailableFeatures = GetItems().FindAll(f => model.AvailableFeatureIds.Contains(f.FeatureId.ToString()));

            return View("Index", model);
        }
```
I am attaching the fixed project:
[MultiSelectFor-fixed.zip](https://github.com/telerik/kendo-ui-core/files/3421011/MultiSelectFor-fixed.zip)
