### ISSUE TITLE
Editor placed in Dialog cannot be focused (AngularJS)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#4936]
### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/IdEpePib/3) example. 
1. The Editor's content area cannot be focused. 

The issue is not reproducible if instead in a Dialog the Editor is initialized in a Window.  

### Current behavior
The Editor cannot be focused.

### Expected/desired behavior
The Editor can be focused.

[Feedback Portal item](https://feedback.telerik.com/kendo-jquery-ui/1401794-kendo-editor-is-not-editable-inside-kendo-dialog)

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
