### ISSUE TITLE
Chart Vue wrapper throws a warning when using category-axis-min/max

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4937]
### Bug report
When using `category-axis-min` or `category-axis-max` props with integer or string parameters, the Vue component throws a type warning.

Note: similar to this issue: https://github.com/telerik/kendo-ui-core/issues/4932

### Reproduction of the problem
[https://stackblitz.com/edit/wcratf-9wsxxj](https://stackblitz.com/edit/wcratf-9wsxxj)

### Current behavior
A type warning is thrown.

### Expected/desired behavior
The proper types for the parameters should be specified to prevent the warning.

### Environment
* **Kendo UI version:** 2019.1.220
* **Browser:** all

**Comment by zdravkov** [comment]
It seems to be fixed in the latest version - https://stackblitz.com/edit/o7epcy?file=src/main.vue
