### ISSUE TITLE
Window doesn't size properly when set on 100% width

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#4940]
### Bug report

When sized to 100% Window doesn't fit 100% to the screen but is a little bit wider causing the appearance of a horizontal scrollbar.

### Reproduction of the problem

[The issue can be reproduced in this Dojo](https://dojo.telerik.com/OriWayOv) just by running it. 

![1](https://user-images.githubusercontent.com/41293735/54980920-b53c2680-4faf-11e9-9151-d183ffbe6f29.png)

### Expected/desired behavior

The window should fit page's boundaries without causing the appearance of a horizontal scrollbar

Feedback portal link: https://feedback.telerik.com/kendo-jquery-ui/1401908-wrong-popup-size-using-bootstrap-theme 
### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Another scenario with horizontal page scrollbar: https://github.com/telerik/kendo-ui-core/issues/3700
