### ISSUE TITLE
DropDownTree doesn't display the right text when value is set to 0.

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#4941]
### Bug Report

When one of the items in the DropDownTree has a value of 0 and that item is selected initially, its text value is not displayed on the widget.

### Reproduction of the problem

https://dojo.telerik.com/ilifEZiS

### Current behavior

There is no text in the DropDownTree field when value 0 is set.

### Expected/desired behavior

Should display Item0.

### Environment

* **Kendo UI version:** 2019.1.220
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
@zdravkov After the fix the change event starts firing for changing value from code, which is not expected, as highlighted in [change event documentation](https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdowntree/events/change). In addition, the value logged is 0, although setting value 2 for example.
