### ISSUE TITLE
Scheduler in SignalR scenario does not fully update its UI

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4942]
### Issues present

Currently, there are two scenarios in which a Scheduler with SIgnalR binding does not update properly its UI. To test the scenario use the [Scheduler - Binding to SignalR demo](https://demos.telerik.com/kendo-ui/scheduler/signalr)

1. **Upon event create:**

- UserA opens a create new task window on Scheduler, fill out all the info. UserB open a new (or update) task window on the scheduler, fill out all the info.

- UserA clicks on the Save button. New info is saved in the database and also sent to UserB side. However the edit pop-up opened by UserB earlier disappears, and new task info by UserB is shown on the UserB's Scheduler (present only client-side).

2. **Upon event update:**

- UserA opens an existing task A and makes changes on task title, UserB opens an existing task B and make changes;

- UserA clicks on Save button. New info pushes to UserB side (notified but the title of task A is not refreshed) while pop-up still remains open on UserB side. The new info is present when double-clicking on task A on UserB side.

3. When several Scheduler instances are edited simultaneously (events are created or updated) - the first save/update on one instance causes the other edit event dialogs to get closed. 

4.  **Upon recurring event update:**

When the 'Edit current occurance' button is used to update a recurring event:
-  The edit window of UserA is not being closed and the Scheduler event is not being updated with the new data after the 'Update' button is clicked.
-  The corresponding event is being incorrectly removed on UserB side.

**Comment by veselints** [comment]
The current approach to resolve the above issues is to call `dataSource.cancelChanges();` in the Scheduler `push` event handler. That will always end in closing the edit pop-up and updating the UI according to the remote changes. That, however, is not a very good approach from UX perspective, as pop-up will be closed out of nowhere. We may have to reconsider the behavior in the above scenario.

Here is a DOJO, which implements the `dataSource.cancelChanges();` workaround: https://dojo.telerik.com/epefUqap

**Comment by Juveniel** [comment]
Also reported in TID: 1407269

**Comment by Iankodj** [comment]
The problem with the recurrence editing is related to the service we use for the Demo site. It is logged here as a different task. https://github.com/telerik/kendo-ui-core/issues/5106

If the service used properly utilizes int types instead of GUID everything works fine.

**Comment by Iankodj** [comment]
With fixing the closing editor issues there might be an issue with editing the same event simultaneously on two instances. Generally, in this scenario, the one that saves the event last will loose all the edits. 

That can be handled by implementing locking of events. You can follow this example here:  https://github.com/telerik/ui-for-aspnet-mvc-examples/tree/master/scheduler/scheduler-signalr-local-hub-locking-events. 

Built-in option to handle locking of events can be a subject of a feature request so that we can track the demand for such an addition.
