### ISSUE TITLE
Submit DropDownTree values automatically when checkboxes are enabled

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4943]
### Enhancement

Currently, when checkboxes are enabled, the selected items cannot be sent to a remote end-point via form submit.  Research possible workarounds for the senario - rendering an additional input elements, parsing or other suitable approach that allows submitting the value of the widget.

**Comment by GraemeSMiller** [comment]
To me the current functionality seems like a half baked implementation of an input control. It should just work as a part of the from - having to hook into the on-submit event to get values of a from element isn't something I'd consider a working control compared to the rest of your input elements.

I could write code that creates hidden inputs if I had to. Alternatively underlying item generated is a multi-select I'm pretty sure we can populate options and mark as selected and the form would submit them. This would seem to the same way your multi-select works.

**Comment by trailmax** [comment]
@Dimitar-Goshev Closed as in "fixed, will be available in version 2019.R2"?

**Comment by zdravkov** [comment]
Yes, the issue is with 2019.R2 milestone so it will be available in the 2019 R2 release.

**Comment by trailmax** [comment]
@zdravkov Excellent. Many thanks for getting this fixed so quickly! Appreciate the effort.

**Comment by davidhuggett** [comment]
Do you have a sample of this working, please? I can't see any way to get the selected items in a form submission.
