### ISSUE TITLE
Nested DropDown editors in detail Grid throw errors when there are "\r\n" new lines in text

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#4945]
The issue is similar to [this one](https://github.com/telerik/kendo-ui-core/issues/4500), however, the error is thrown when the ForeignKey column is in a detail Grid. 

We should investigate if it is possible to safely escape the "\r\n" characters in an n-level hierarchy. 

### Environment

* **Kendo UI version:** 2019.1.220

**Comment by MilenaCh** [comment]
The problem still occurs for popup and inline edit mode:

[grid-foreign-key-combo-box-column - Copy.zip](https://github.com/telerik/kendo-ui-core/files/3261378/grid-foreign-key-combo-box-column.-.Copy.zip)
