### ISSUE TITLE
Remove window.escape() / window.unescape() calls from the source

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4946]
### Remove window.escape() / window.unescape() calls from the source

The ECMA-262 standard recommends that 'Programmers should not use or assume the existence of these features and behaviours [`escape()` and `unescape()` methods] when writing new ECMAScript code.'

In our implementation we have `window.unescape()` calls, which can be replaced with [`decodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent). We should carefully review for any potential side effects as the above does not fully replicate the behavior of `unescape()`.

**Comment by veselints** [comment]
Setting Priority to 1 as reported in one more thread.

**Comment by mparvanov** [comment]
In certain cases when the template contains Unicode characters the following error is thrown:
 _URIError: URI malformed_
Steps to reproduce:
https://dojo.telerik.com/iceVEfIx 
Open the edit window which contains an unicode character inside:

```
<div class="k-edit-label"><label for="title">My %u0107 Title</label></div>
``
