### ISSUE TITLE
In filterable Grid clear filter button is not hidden after programatically clearing the filter

### ISSUE THREAD

**Issue by CecoMilchev** [telerik/kendo-ui-core#4950]
### Bug report

When the filtering mode of the grid is set to "row" and the filter is programmatically cleared, the "Clear filter" button does not hide. 

### Reproduction of the problem

1. Set filterable: {mode: "row"}.
2. Filter for instance "Is null" or "Is not null".
3. Clear the filter - $("#grid").getKendoGrid().dataSource.filter({});
4. The "Clear filter" button is not hidden

sample Dojo: 

https://dojo.telerik.com/AVOqifeK

If there is text in the filter's input, the button is hidden.

### Expected/desired behavior
Hide the "Clear filter" button, irrespectively whether the filter has been cleared programmatically or via the UI.

### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by ag-petrov** [comment]
This is not a bug. The datasource does not know that is is placed inside a grid and the chain of components can not update the filtercell component inside the filter row. The correcty way to clear the filter is to do this via the filtercell clearFilter method. [Here](https://dojo.telerik.com/AVOqifeK/5) is a dojo.
