### ISSUE TITLE
Spreadsheet loses data of sheet's first two rows if "Add row below" is used, when a cell on the last two rows is focused

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#4954]
### Bug report
If a cell on sheet's last two rows is currently focused, adding a row through Insert tab -> "Add row below" button deletes data from the first two rows of the sheet.

### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/@Dimitar-Goshev/UsalaZAD) and run it.
1. Go to row 19 or 20 and select a random cell of one of the rows, e. g. click on B19
1. Click on Insert tab in Spreadsheet's tools.
1. Click on "Add row below"  button
1. Scroll back to the beginning of the Spreadsheet.

### Current behavior
In rows 1 and 2 there is data only in column A. 

Initial Spreadsheet state:
![initialState](https://user-images.githubusercontent.com/41293735/55323682-706d2f80-5488-11e9-9b02-53fe69221e31.png)

Spreadsheet state after new row insertion at the end of the Spreadsheet : 
![stateAfterInsertion](https://user-images.githubusercontent.com/41293735/55323992-68fa5600-5489-11e9-8711-67e9a2153bca.png)
 
### Expected/desired behavior
There shouldn't be data loss at "Add row below" action or the user should be notified that the execution of the given instruction could lead to data loss.

### Environment
* **Kendo UI version:** 2019.1.220
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
I noticed that if there is content on the last but one row, adding row below would move that data to the first row, shifted one column to the right.
1. Run the following [DOJO](https://dojo.telerik.com/@Dimitar-Goshev/axAzUlUb)
1. Click on B15
1. Insert -> Add row below
Result:
![image](https://user-images.githubusercontent.com/6614183/61641914-a7ba5300-aca8-11e9-812e-21d93a66ffd2.png)

**Comment by Dimitar-Goshev** [comment]
The issue is fixed.
Adding rows below bottom row will alert not supported.
Adding columns to the right of the last column will alert not supported.
