### ISSUE TITLE
ContextMenu appears outside screen boundary upon initial opening

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#4961]
### Bug report

Upon initially opening a Kendo UI ContextMenu, it appears to disregard the screen's boundary, and opens outside of it.

### Reproduction of the problem
1.  [Open this dojo and run it.](https://dojo.telerik.com/iFOvEcOW)
2.  Right click on the target to open the ContextMenu.
3.  Notice it displays outside the screen.
4.  If you click on it again, it will work as expected.

[Here is a screencast of the behavior.](https://www.screencast.com/t/3wBXVGBg9)

### Expected/desired behavior
The ContextMenu should appear [within the bounds of the screen as in the 2019.1.115 version.](https://dojo.telerik.com/OvICuyuy)

### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** 1.12.x
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
Reported in ticket ID 1406613
