### ISSUE TITLE
Decimal values are not displayed when negative percentage value is filled in a cell

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#4970]
### Bug report

Decimal values are not displayed when negative percentage value is filled in a cell

Related to #2963

### Reproduction of the problem
Use the Kendo Spreadsheet to fill "-0.046%" and set its format to %. Sample here: [https://dojo.telerik.com/ACAGeTEL/2](https://dojo.telerik.com/ACAGeTEL/2)

### Current behavior
-.05% is displayed

### Expected/desired behavior
-0.05% should be displayed

### Environment

* **Kendo UI version:** 2019.1.220
* **Browser:** [all]

**Comment by VicTachev** [comment]
Reported also in ticket 1404683

**Comment by stanleygomes** [comment]
Reported also in ticket 1404683
