### ISSUE TITLE
Incorrect focused state of radio buttons in Material theme

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-ui-core#4971]
### Bug report

The focused state of the radio buttons in the material theme is not following the material design guidelines:

https://material.io/design/components/selection-controls.html#radio-buttons

### Reproduction of the problem
1. Go to: https://demos.telerik.com/kendo-ui/styling/radios
2. Select Material LESS theme
3. Click on radio buttons

### Current behavior

![2019-04-08_1501](https://user-images.githubusercontent.com/45764088/55722604-6bbbf480-5a0f-11e9-9fbb-3f42caf8ec1a.png)

### Expected/desired behavior

![2019-04-08_1501_001](https://user-images.githubusercontent.com/45764088/55722620-72e30280-5a0f-11e9-906c-eb7bc3e1800c.png)

**Comment by Dimitar-Goshev** [comment]
LESS Material theme does not follow newest Material design guidelines. In 2019.3.1023 focused radio buttons appear as follows.
![focused radio button](https://user-images.githubusercontent.com/6614183/69548751-978cea00-0fa0-11ea-88f6-c3566f1ec384.png)
