### ISSUE TITLE
Links (anchor tags) in Menu lose color since v. 2019.1.220

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-ui-core#4984]
### Bug report
The links added in the Menu lose their color since v. 2019.1.220

### Reproduction of the problem
The issue can be reproduced in the following [Dojo](https://dojo.telerik.com/uCUKEniB/7)
Although Blog, Company, and Events are anchor elements, their color is black

### Expected/desired behavior
They should be styled as the rest of the links as they were in v [2018.3.911 Dojo](https://dojo.telerik.com/uCUKEniB/6)

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** all

**Comment by Juveniel** [comment]
In previous version of the Less-based themes the links in the Menu were indeed styled with different color. This styling, however, was not correct. All menu items should be styled identically in each Kendo Less-based themes, similar to how links are styles in the Default theme. 

For example, if we examine [a Menu demo](https://dojo.telerik.com/uCUKEniB/7) with the Kendo Less Bootstrap theme, which is designed to provide a similar look and feel to Bootstrap 3, we can observe that the links are currently styled consistently similar to [the Bootstrap Navbar](https://getbootstrap.com/docs/3.4/components/#navbar). This is the expected styling for the Kendo Bootstrap theme.

Taking the above into consideration,  the changes from 2019 R1 are an enhancement that resolves the styling mismatch for all Less-based themes.

A workaround for achieving different color for the links can still be accomplished through the following style ([Dojo example](https://dojo.telerik.com/UnIWaQUN)):
```css
<style>
  .k-menu > .k-item a.k-link {
    color: #428bca;
  }
</style>
```

Closing the issue.
