### ISSUE TITLE
Too hard to set CSS for tree nodes

### ISSUE THREAD

**Issue by dandv** [telerik/kendo-ui-core#499]
Had to [ask a question about this on SO](http://stackoverflow.com/questions/27795390/custom-styling-kendo-treeview-node-text-in-trees-loaded-from-javascript), as there was no documentation on styling the Treeview.

In Webix, it's as simply as setting [`node.$css`](http://docs.webix.com/datatree__styling.html#stylingspecificnodes).

**Comment by naskog** [comment]
@dandv , the TreeView widget is not part of Kendo UI core project.
Please log issue in Kendo UI documentation repo (https://github.com/telerik/kendo-docs)
