### ISSUE TITLE
Unexpected scrollbar appears when setting content through editor value() method in IE

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#4994]
### Bug report

When setting content to Editor by using its value method, a redundant scrollbar appears in the content area.

### Reproduction of the problem
https://dojo.telerik.com/AsuNiPuh/7 

The issue is regression since R2 2016.

### Environment

* **Kendo UI version:** 2019.1.220
* **Browser:** [ IE 11 ] 

[Feedback Portal Item](https://feedback.telerik.com/kendo-jquery-ui/1405353-editor-renders-vertical-scrollbar-in-ie)

**Comment by Iankodj** [comment]
Related to: #4222, telerik/kendo#5444 and telerik/kendo#671
