### ISSUE TITLE
l.select(...).done is not a function error is thrown when delete the selected item after filtering.

### ISSUE THREAD

**Issue by brnowakowski** [telerik/kendo-ui-core#4995]
### Bug report

l.select(...).done is not a function error is thrown when delete the selected item after filtering. 

### Reproduction of the problem

https://dojo.telerik.com/EjaCODIs/2

Bug does not occures always so reproduction is little tricky. Following instructions describes the most reliable method of reproduction we have found. Demo contains intentionally slowed down datasource to imitate slow remote data.

1. Type 'ee' to find item that is not included in first page
2. Select item
3. Blur multiselect control
3. While datasource is fetching data without filtering, click multiple times on multiselect control - dropdown will open and close
4. After data without filter is fetched click somewere on page to blur multiselect
5. Selected item cannot be deleted and "l.select(...).done is not a function" is logged in console

When bug occurs, the item is selected but before datasource is done, dropdown shows selected item like it has not been selected.
![image](https://user-images.githubusercontent.com/40244073/56278619-d8697a00-6106-11e9-93d4-1ea71aac3b41.png)

### Current behavior
An error is thrown: Uncaught TypeError: l.select(...).done is not a function

### Expected/desired behavior
No errors occur, selected item can be deleted
### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** 1.12.3
* **Browser:** all

**Comment by tomaszoida** [comment]
I have the same issue. What are the chances for a fix?

**Comment by sumajay** [comment]
I am having this Issue still, and I'm using Kendo.MVC version 2020.3.915.440. Is the issue fixed?
