### ISSUE TITLE
Tooltip disappears when the page is scrolled and the container has overflow: auto 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5003]
### Bug report

Tooltip disappears when the browser window is not full screen, the container element has **overflow: auto** or **scroll** set and the page is scrolled down. 
Regression introduced in 2017.3.913. 
Reproducible in Chrome and Firefox.

### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/ipIDaMUY )example. [Screencast](https://www.screencast.com/t/dsuE6oymfRq).
1. Check the screencast, which shows how the browser window needs to be set up. 
2. The browser window must be just high enough so that the container element bottom end is closer to the edge of the window.
3. Scroll down the content and hover some of the bottom elements. 

### Current behavior
The Tooltip hides.

### Expected/desired behavior
The Tooltip remains visible.

### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** x.y
* **Browser:** [ Chrome XX | Firefox XX ]

**Comment by achrysanthakopoulou** [comment]
Hello,
Is there a draft estimation about the fix of the problem?
I must decide if I am going to wait for a fix or temporarily use another plugin for tooltip due to this problem..
Thank you!

**Comment by IvanDanchev** [comment]
Hi, 

The bug fix is currently awaiting testing. If it successfully passes the internal testing procedure it will be included in the next release (R2 2019 SP1).

**Comment by achrysanthakopoulou** [comment]
Great, thanks!
