### ISSUE TITLE
Using MultiColumnComboBox with enabled Virtualization as editor in the Grid loses focus in some scenarios 

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-ui-core#5005]
### Bug report

When the Grid is with enabled keyboard navigation (_Navigatable(true)_) and a MultiColumnComboBox with enabled Virtualization is used, working with the editor is some specific cases "loses the focus" in the popup and prevents the user to navigate through the items with the arrow keys.

### Reproduction of the problem
1. [https://dojo.telerik.com/UPoCeyur/4](https://dojo.telerik.com/UPoCeyur/4)
1. Press the 'Add New Record" button
1. Enter "Product Name"
1. Press Tab
1. On Category column, mark the selection, enter 'ss ', wait until the data list shown.
1. Press backspace to delete 'ss ', wait until the data list shown.
1. Continuously press <Arrow Down> key

### Current behavior
 it will lose focus from the multicolumncombobox at some point,

### Expected behavior 
The focus is not lost

Refer to the attached project in ticket Ticket ID: 1405131 for additional details.

### Environment

* **Kendo UI version:** 2019.1.220

**Comment by mparvanov** [comment]
Not reproducible with Kendo v.2019.2.619
https://dojo.telerik.com/UPoCeyur/14

**Comment by hychoo** [comment]
> Not reproducible with Kendo v.2019.2.619
> https://dojo.telerik.com/UPoCeyur/14

Please refer to Telerik support ticket below:
https://www.telerik.com/account/support-tickets/view-ticket/1405131

Use the ticket attachment multicolumncomboboxvirtualization.zip project to run with v.2019.2.619, issue still exist
