### ISSUE TITLE
TreeList Excel export doesn't work with multi-column headers

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#5006]
### Bug report

When there are multi-column headers in the TreeList, exporting the widget to Excel results in a corrupted xlsx file.

Dojo: [https://dojo.telerik.com/ACowudAg](https://dojo.telerik.com/ACowudAg)

### Reproduction of the problem

Open the Dojo and export the TreeList to Excel.

### Current behavior

When you open the file, you will get a message saying that there are problems with the format of the document. If you proceed to load the document, the headers are misplaced.

### Environment

* **Kendo UI version:** 2019.1.220

[Feedback Portal Item](https://feedback.telerik.com/kendo-jquery-ui/1405391-treelist-multi-column-headers-excel-export-bug)

**Comment by TsvetinaIvanova** [comment]
Also reported in 1410291.

**Comment by ag-petrov** [comment]
Works with the latest version https://dojo.telerik.com/ACowudAg/4
