### ISSUE TITLE
Error when moving across (tab) widgets (inLine) editing Grid

### ISSUE THREAD

**Issue by Mesihas** [telerik/kendo-ui-core#5011]
### Bug report

Error when pressing tab to move across fields when edit in line on a Grid.

kendo.all.min.js:formatted:18743 Uncaught TypeError: Cannot read property 'val' of undefined
    at init._move (kendo.all.min.js:formatted:18743)
    at init._keydown (kendo.all.min.js:formatted:20980)
    at HTMLSpanElement.proxy (jquery-2.2.2.js:497)
    at HTMLSpanElement.dispatch (jquery-2.2.2.js:4737)
    at HTMLSpanElement.elemData.handle (jquery-2.2.2.js:4549)

### Expected/desired behavior
To tab across dropdowns without console errors

### Environment
Kendo UI v2015.1.408 
jQuery v2.2.2 
Chrome Version 73.0.3683.103 (Official Build) (64-bit)

![2019-04-24 14_21_21-DevTools - localhost_14740_Scheduler_ResourceBooking_cdf8f5ba](https://user-images.githubusercontent.com/15827329/56632657-2994e300-669e-11e9-96e3-32a9bde5758b.png)

**Comment by MLefebvreICO** [comment]
You are using a really old version if you are using 2015.1.408 ...
They probably fixed this a long time ago ..

You should consider upgrading your Kendo UI version.

**Comment by MLefebvreICO** [comment]
@Mesihas You are using a really old version if you are using 2015.1.408 ...
They probably fixed this a long time ago ..

You should consider upgrading your Kendo UI version.

**Comment by matanasov** [comment]
@Mesihas 
Could you please provide a DoJo example demonstrating the issue?
