### ISSUE TITLE
DropDownList disabled cursor

### ISSUE THREAD

**Issue by MLefebvreICO** [telerik/kendo-ui-core#5017]
### Bug report

The DropDownList does not have the right `cursor` style on hover when disabled.

Note: Since the dropdown currently has `k-state-disabled` on `k-dropdown-wrap` instead of on `k-dropdown`, the only current workaround is to use the following selector to reset the cursor, which is not great : `.k-dropdown[aria-disabled='true']`.

### Reproduction of the problem
1. Open the [dojo](https://dojo.telerik.com/IRONUgOT)
2. Run it
3. Mouse over the `Cap size`'s dropdown

### Current behavior
The disabled DropDownList has the `pointer` cursor.

### Expected/desired behavior
The disabled DropDownList has the `default` cursor.

### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** 2.2.4
* **Browser:** all

**Comment by tgfactor** [comment]
I second this...cursor: no-drop is crossed out for multi-select...doesn't matter which tag I put the style in, it doesn't work.

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible since R1 2022 (2022.1.119) - [Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/ESuXobIB)
