### ISSUE TITLE
RadioButtonFor bound to Model in Core does not render data-val attributes

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#5020]
### Bug report
When a model property is decorated with data annotation attributes, the RadioButton HtmlHelper does not properly render the `data-val` and `data-val-required` attributes on the `<input>` element.

### Reproduction of the problem
[TelerikAspNetCoreAppRadioButtonValidate.zip](https://github.com/telerik/kendo-ui-core/files/3121244/TelerikAspNetCoreAppRadioButtonValidate.zip)

### Current behavior
Data attributes are not rendered on the `<input>` element.

### Expected/desired behavior
Data attributes should be successfully rendered on the `<input>` element.

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by veselints** [comment]
PR here: https://github.com/telerik/kendo/pull/10561
