### ISSUE TITLE
TreeList resizes incorrect column

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#5025]
### Bug report

Ticket ID: 1406478

### Reproduction of the problem

[Dojo](https://runner.telerik.io/fullscreen/@bubblemaster/IrEwagAb)

Steps:

- Hover over the column you want to resize
- Move the mouse to the right to the resize handle
- Move a bit move to be in the next column

![image](https://media.giphy.com/media/h2ZuG59FAyp9GZUQ1L/giphy.gif)

### Expected/desired behavior

TreeList should always resize the intended column.

### Environment

* **Kendo UI version:** 2019.1.220

**Comment by ag-petrov** [comment]
I am not able to reproduce this with the latest scripts

**Comment by bdely** [comment]
Hello @ag-petrov i have been able to reproduce this issue with the latest [2019.2.514]
![treelist-column-resizing-issue](https://user-images.githubusercontent.com/2165209/59443602-3eeadb80-8dca-11e9-85d8-32a92c4a4836.gif)

**Comment by ag-petrov** [comment]
The fix was not applied in the mentioned version. It will be included in the upcoming service-pack.

**Comment by bdely** [comment]
Thank you, I will get that when it is available
