### ISSUE TITLE
Add separate .js for only file upload functionality in src folder.

### ISSUE THREAD

**Issue by tejasmhade** [telerik/kendo-ui-core#5026]
Add separate .js for only file upload functionality in src folder.

**Comment by zdravkov** [comment]
Kendo Upload is part of [Kendo Professional suite ](https://www.telerik.com/kendo-ui) and is not included in Kendo UI Core is a free and open-source subset of Kendo UI as it is described [here](https://github.com/telerik/kendo-ui-core/blob/master/README.md).
