### ISSUE TITLE
StockChart with persistSeriesVisibility throws an error with dynamic series

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#5029]
### Bug report

TicketID: 1405400 

### Reproduction of the problem

Steps in the [Dojo](https://dojo.telerik.com/@bubblemaster/eyALuHEG/3)

### Current behavior

The `series.index`  becomes `undefined` after `setOptions()` is used and this line throws an error:

```
if (this.options.persistSeriesVisibility) {
   this.options.series[series.index].visible = series.visible;
} 
```

![image](https://user-images.githubusercontent.com/10980842/56948802-ede49800-6b39-11e9-93f8-339389b5ec64.png)

### Expected/desired behavior

No errors should be thrown.

### Workaround

Pass an ***index*** in the series configuration when the `setOptions()` method is called:

```
chart.setOptions({
    series: [{
       // other settings
       index: 0
     },{
      // other settings
      index: 1
     }]
});      
```

### Environment

* **Kendo UI version:** 2019.1.220

**Comment by ag-petrov** [comment]
Does not seem to reproduce with the latest version
