### ISSUE TITLE
Large items in MobileListView with endless scrolling disappear on a scroll

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#5030]
### Bug report

Large items in MobileListView with endless scrolling disappear on a scroll.

https://screencast-o-matic.com/watch/cqfv6YZpF0

### Reproduction of the problem

1. https://dojo.telerik.com/ucAFePOV
1. Run and scroll the ListView

### Current behavior

The first item disappears. 

### Expected/desired behavior

The first item does not disappear. 

### Environment

* **Kendo UI version:** 2019.1.220
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Closing this issue as the mobile suite is now depricated.
