### ISSUE TITLE
Empty context menu appears on Tooltip activation in Edge 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5035]
### Bug report
When activating a Tooltip, an empty context menu appears with it.  

### Reproduction of the problem

1. Open [this Dojo](https://dojo.telerik.com/IwUZAZoT) and run it in Edge 44.17763.1.0
2. Move the mouse cursor over a random yellow point on the map 
3. A small gray square appears above the tooltip area. 
4. Don't move the cursor and press the right mouse button. An expected context menu appears and the unexpected one disappears. 

### Current behavior
Mouse cursor over a yellow point - the unexpected context menu is presented:
![tooltip1](https://user-images.githubusercontent.com/41293735/57143836-71b3b400-6dc8-11e9-983e-69253e98d3aa.png)

Right mouse click while the cursor is over a yellow point - the unexpected context menu is missing:
![tooltip2](https://user-images.githubusercontent.com/41293735/57143899-8ee88280-6dc8-11e9-8af6-45c176403b28.png)

### Expected/desired behavior
An additional empty context menu should not appear when a Tooltip is being activated

### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** x.y
* **Browser:** [Microsoft Edge 44.17763.1.0]

**Comment by PekoPPT** [comment]
Also reported in ticket #1467620

**Comment by joneff** [comment]
The issue is related to the fact that we leave an empty title attribute, which Edge shows. If we remove the attribute and then re-add it, the issue will not appear in edge

**Comment by nelito987** [comment]
Also reported in ticket #1468850. In the Dojo example below the Tooltip is used for Stepper steps.
[https://dojo.telerik.com/@NeliKondova/oYuliREM/2](https://dojo.telerik.com/@NeliKondova/oYuliREM/2) The Tooltip is displayed correctly, but also an empty box appears in Edge

**Comment by veselints** [comment]
The issue could no longer be reproduced with Chromium Edge.
