### ISSUE TITLE
DropDownTree is not showing objects when k-ng-model is used and value primitive false (AngularJS)

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#5037]
### Bug report
DropDownTree is not showing objects when k-ng-model is used and value primitive false (AngularJS) - [Dojo](https://dojo.telerik.com/@zdravkov/oHUGADaw)
When the same code is used with MultiSelect the selectedIds are shown as array of objects.

### Reproduction steps
https://dojo.telerik.com/@zdravkov/oHUGADaw
Check several items

### Current behavior
selectedIds are shown as primitives

### Expected/desired behavior
selectedIds should be shown as objects

### Environment
* **Kendo UI version**: 2019.1.220

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
