### ISSUE TITLE
Grid with large pageSize loses cell values  

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5044]
### Reproduction of the problem
Setup:
Grid PageSize is set to 100 or more (e.g. 200)
Column with virtualized ComboBox editor

Clicking on the cells consecutively causes some of the cells to lose their value. [Screencast](https://www.screencast.com/t/CxUnIFZsc).

A sample project, in which the issue can be observed can be found in ticket: 1408425.
NOTE: it is easier to reproduce the issue, if connection is slow. This may be simulated in Chrome devtool's Network tab.

### Current behavior
Cells lose value

### Expected/desired behavior
Cells do not lose value

### Environment
* **Kendo UI version:** 2019.1.220
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Reported in ticket 1406575

**Comment by gyankov** [comment]
A possible workaround would be to initially remove the focusout event within the edit event handler of the grid and then when the combobox is bound restore attach the focusout event.

`
    function onEdit(e) {
        var ns = ".kendoComboBox";
        var nsFocusEvent = ns + "FocusEvent";
        var combo = e.container.find('[data-role="combobox"]').data('kendoComboBox');
        combo.input.off(nsFocusEvent);
        combo.one('dataBound', function () {
            combo.input.on("focusout" + nsFocusEvent, proxy(combo._inputFocusout, combo));
        })
     ...
    }
`
