### ISSUE TITLE
Pasting data from Excel file results in image but not in data values 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5048]
### Bug report
When pasting data from Excel, the data is being pasted as an image instead of values

### Reproduction of the problem
1. Open [https://dojo.telerik.com/UKAFAkEn](https://dojo.telerik.com/UKAFAkEn)
2. Open new Excel file on your system in MS Excel application
3. Enter data 1, 2, 3, 4, 5 in A1 to A5 in sheet1
4. Copy data from A1 to A5 from the local file
5. Paste data in C3 of Spreadsheet opened in step 1
6. The pasted result is an image instead of values

### Current behavior
Pasting from Excel results in an image
![spreadsheet_paste](https://user-images.githubusercontent.com/41293735/57785867-2f309680-773b-11e9-872e-bc18556f091e.png)

### Expected/desired behavior
Pasting from Excel should result in correctly filled data cells
![spreadsheet_paste1](https://user-images.githubusercontent.com/41293735/57786074-86366b80-773b-11e9-8931-f1349b77a082.png)

### Environment

* **Kendo UI version:** 2019.2.514
* **jQuery version:** x.y
* **Browser:** [Chrome 74.0.3729.131 | Firefox 66.0.5 | Edge 42.17134.1.0 ]

**Comment by mishoo** [comment]
Fixed in https://github.com/telerik/kendo/commit/eb112fa520caa3f635684ee66cf2149a5799d9e6
