### ISSUE TITLE
Cannot set multiselect value with item that is not present in the first page 

### ISSUE THREAD

**Issue by brnowakowski** [telerik/kendo-ui-core#5050]
### Bug report

Setting multiselect value with item that is not on first page of dataSource does not work

### Reproduction of the problem

https://dojo.telerik.com/oPENOwuR
To reproduce problem just run script. 
Multiselect control does have initial value and autoBind set to false.

After initalizing multiselect, item I want to set as value is added to dataSource, bacause it is not present in current dataset.

After value is set, it is present in multiselect for a moment but dataSource.transport.read is executed and value disappears after read is done. 

### Current behavior
Setting value causes to execute transport.read what results in clearing control value.

### Expected/desired behavior
Value should not disappear after it is set.

### Environment

* **Kendo UI version:** 2019.2.514
* **jQuery version:** 1.12.3
* **Browser:** all

**Comment by zdravkov** [comment]
The described paging scenario is supported by the widget only when the virtualization is anabled - _Enabling the paging and setting the pageSize of the MultiSelect is efficient only when these features are used with virtualization._- as it is described in this documentation article - https://docs.telerik.com/kendo-ui/controls/editors/multiselect/virtualization.
