### ISSUE TITLE
Using Custom Build with PDFViewer checked throws an error

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5056]
### Bug report

An error occurs on components' initialization when using a custom Kendo UI build which includes PDFviewer

### Reproduction of the problem
1. Go to [Kendo UI Custom Download](https://www.telerik.com/download/custom-download) page
2. In the "WEB" section select random components including the Grid and PDFviewer
3. Download the custom build(kendo.custom.min.js file) and put it in the same folder with an HTML file with the following structure.
```html
<!DOCTYPE html>
<html>

<head>
    <style>
        html {
            font-size: 14px;
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>
    <title></title>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2019.2.514/styles/kendo.default-v2.min.css" />

    <script src="https://kendo.cdn.telerik.com/2019.2.514/js/jquery.min.js"></script>
    <script src="./kendo.custom.min.js"></script>
</head>

<body>
    <div id="example">
        <div id="grid"></div>
        <script>
            $(document).ready(function () {
                $("#grid").kendoGrid({
                    dataSource: {
                        type: "odata",
                        transport: {
                            read: "https://demos.telerik.com/kendo-ui/service/Northwind.svc/Customers"
                        },
                        pageSize: 20
                    },
                    height: 550,
                    groupable: true,
                    sortable: true,
                    pageable: {
                        refresh: true,
                        pageSizes: true,
                        buttonCount: 5
                    },
                    columns: [{
                        template: "<div class='customer-name'>#: ContactName #</div>",
                        field: "ContactName",
                        title: "Contact Name",
                        width: 240
                    }, {
                        field: "ContactTitle",
                        title: "Contact Title"
                    }, {
                        field: "CompanyName",
                        title: "Company Name"
                    }, {
                        field: "Country",
                        width: 150
                    }]
                });
            });
        </script>
    </div>
</body>
</html>
```
4. The following error appears: 
Uncaught TypeError: Cannot read property 'Toolbar' of undefined

### Current behavior
![grid_pdf](https://user-images.githubusercontent.com/41293735/57859855-6a46ce80-77fc-11e9-9cdf-36b335e94332.png)

### Expected/desired behavior
A Grid should be initialized properly and without errors if a custom build is including the PDFviewer

### Environment

* **Kendo UI version:** 2019.2.514
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by jivanova** [comment]
Same applied for Chat.

**Comment by Dimitar-Goshev** [comment]
The issue is still reproducible.

**Comment by Dimitar-Goshev** [comment]
After the fix still an error is thrown with custom script, when ExportAs button is clicked:
`n.observable is not a function`
```
})).kendoWindow(options).getKendoWindow();
                that.viewModel = kendo.observable({
                    title: dialogMessages.exportAsDialog.title,
```

**Comment by Dimitar-Goshev** [comment]
The error caused by PDFViewer scripts is fixed.
The Grid configuration pasted in the issue description needs checking Grid checkbox and its Grouping and Paging optional checkboxes to be checked, as well as checking DropDownList. If these checkboxes are not set, there will be Grid related errors thrown, which is expected.
