### ISSUE TITLE
Column resize handle is displayed at incorrect position

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-ui-core#5058]
### Bug report
Column resize handle is not correctly positioned. 

Reported in Ticket ID: 1344058

### Reproduction of the problem
1. Open the Dojo example: http://dojo.telerik.com/AMENowuT/12
2. Hover the "2017-12" column

### Current behavior
Column resize handle is displayed but is cut out from the page. Its position is not calculated correctly and the horizontal scrollbar is updated.

### Expected/desired behavior
The resize handle is not shown as the hovered column is a multi header column.

### Environment

* **Kendo UI version:** 2019.2.514
* **jQuery version:** 1.9
* **Browser:** all

**Comment by MilenaCh** [comment]
Issue:
Js error is thrown when try to resize using the provided dojo.
'Uncaught TypeError: Cannot read property 'minResizableWidth' of undefined'
