### ISSUE TITLE
@progress/kendo-react-pdf Can not export pdf file in IE

### ISSUE THREAD

**Issue by yellowjian** [telerik/kendo-ui-core#5061]
### Bug report

can  not export pdf file in IE, save unsuccessful.

### Environment

  Nodejs  React
  "@progress/kendo-drawing": "^1.5.12",
  "@progress/kendo-react-pdf": "^2.11.0", 
  IE 11

**Comment by zdravkov** [comment]
Issues for Kendo React should be logged in https://github.com/telerik/kendo-react/ repository.
