### ISSUE TITLE
Scroll go all the way down when pasting long text in Editor in Safari

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5064]
### Bug report
Scroll go all the way down when pasting long text in Editor in Safari.

### Reproduction of the problem
1. Use Safari browser
2. Go to https://demos.telerik.com/kendo-ui/editor/index
3. Copy a long text over 25 characters
4. Paste the copied text in the Editor
5. Notice that the scroll takes you to the bottom of the page, The same is not noticed in any other browser.

### Current behavior
The window scrolls down

### Expected/desired behavior
The window should not be scrolled down

### Environment
* **Kendo UI version:** 2019.2.514
* **Browser:** [ MacOS Safari ]

**Comment by rjpedrosa** [comment]
Same with images

**Comment by martintabakov** [comment]
Also reported in ticket #1580795

**Comment by Iankodj** [comment]
Not reproducible with latest version.
