### ISSUE TITLE
Resource fetching doesn't re-render Scheduler view when autobind=false

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#5069]
### Bug report

With autobind=false, scheduler view need to be re-rendered explicitly when fetching the resources datasource.

### Reproduction of the problem
1. Open the following sample: https://dojo.telerik.com/UTIhUQuR/3
2. Press the "Fetch Resources Datasource" button

### Current behavior
The scheduler view is not re-rendered with the data-source.

### Expected/desired behavior
The scheduler view is re-rendered with the data-source.

Current Solution: Rerender the scheduler view: [https://dojo.telerik.com/OkOQoGOM](https://dojo.telerik.com/OkOQoGOM)

### Environment
* **Kendo UI version:** 2019.2.514

**Comment by marin-bratanov** [comment]
may be related to #4905
