### ISSUE TITLE
Deferred widget initialization does not work in Content tags

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#5074]
### Bug report

Putting a component inside a Content method or tag will not resolve the deferred script. 

### Reproduction of the problem

```razor
@(Html.Kendo().TabStrip()
    .Name("tabstrip")
    .Items(items =>
    {
        items.Add().Text("Tab")
            .Content(@<text>
                @(Html.Kendo().Editor()
                        .Name("editor")
                        .Deferred()
                )
            </text>);
    })
)

@Html.Kendo().DeferredScripts()
```
Loading the snippet above will not load the script for the Kendo Editor.

The same applies for the Tag Helpers as well. 

### Current behavior
Script is not rendered

### Expected/desired behavior
The deferred script to be rendered.

### Environment
- **Kendo UI:** 2019.3.1023

**Comment by Dimitar-Goshev** [comment]
This setup works as expected, when wrapping the widget in a non-rendering code block `@{}` and using the `.Render()` helper method, as suggested in [Rendering of Forms help article](https://docs.telerik.com/aspnet-mvc/getting-started/helper-basics/fundamentals#rendering-of-forms). The following snippet initializes Editor in TabStrip as expected:

```
    @{Html.Kendo().TabStrip()
       .Name("tabstrip")
       .Items(items =>
       {
       items.Add().Text("Tab")
          .Content(@<text>
            @(Html.Kendo().Editor()
              .Name("editor")
              .Deferred()
              )
           </text>);
       }).Render();
    }

    @Html.Kendo().DeferredScripts()
```
