### ISSUE TITLE
Show event of the View fires twice

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5075]
### Bug report
When using the `layout.showIn()` call, the `show` event of the View fires twice. 

This is regression introduced in R2 2019

### Reproduction of the problem
Run the following Dojo: https://dojo.telerik.com/AkOwiMAZ/8

### Current behavior
Show event of the View fires twice

### Expected/desired behavior
Show event of the View should fire only once.

### Environment
* **Kendo UI version:** 2019.2.514
* **Browser:** [all]

**Comment by crazyfx1** [comment]
This is not fixed! 
Check the updated sample with the new kendo version 2019.2.619
https://dojo.telerik.com/AkOwiMAZ/12

**Comment by PreslavKozovski** [comment]
@crazyfx1 
Please excuse me for not including the new bits of code in the "release" branch. 

I already added them to the branch that would be used for our next internal build. If everything goes as expected, the internal build will be out next Wednesday. You can download the source files from here:
https://www.telerik.com/account/product-download?product=KENDOUICOMPLETE
