### ISSUE TITLE
Select column checkbox has to be clicked twice to change state in IE

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5077]
### Reproduction of the problem
1. Run the [Checkbox selection demo](https://demos.telerik.com/kendo-ui/grid/checkbox-selection) in IE 11.706.17134
2. Try clicking a checkbox

### Current behavior
Two clicks are required to change the state of the checkbox.

### Expected/desired behavior
Checkbox should be checked/unchecked with a single click

### Environment

* **Kendo UI version:** 2019.2.514
* **Browser:** [ IE 11.706.17134 ]

**Comment by gyankov** [comment]
The behavior can be reproduced in a standard input of type checkbox outside any of our components. Thus, it is a browser bug.

The issue can be replicated in the following dojo:

https://dojo.telerik.com/EfACuFAk/3

I have logged the bug to IE:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/23304671/
