### ISSUE TITLE
Grid Tag Helper should support setting header template as a function

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#5081]
### Bug report

Currently, the Grid tag helper supports setting the column header template to a static string only. It should also support using a function, as shown in the [columns.headerTemplate](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/columns.headertemplate) article.

### Environment

* **Kendo UI version:** 2019.2.514

Reported in: 1410906

**Comment by aleksandarevangelatov** [comment]
implemented with https://github.com/telerik/kendo/commit/ab91cb41f4425787217d2aa24fc739547ee456b4
