### ISSUE TITLE
Destroying & removing Spreadsheet doesn't remove all DOM elements added on initialization 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5090]
### Bug report
When destroying a SpreadSheet and removing its corresponding DOM element, there are some DOM nodes added on SpreadSheet's initialization which are not removed after the execution of .destroy() and .remove(). 

[Internal info] Possible fix provided in Ticket: 1411323.
### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/OzUlIsuN/4) and run it. 
2. Open browser's console and see the output in it. The initial number of the children nodes in the **body** is 2 and the children nodes after adding and removing a SpreadSheet are 4.  
![Nodes_count](https://user-images.githubusercontent.com/41293735/58703937-05ba7080-83b3-11e9-979d-94a5bdec9b77.png)
3. Right-click the blank page in right and inspect it. Navigate to the body in the iframe and see the additional nodes in it
![Nodes_count_body](https://user-images.githubusercontent.com/41293735/58705584-508ab700-83b8-11e9-9ae2-15a4f2183aba.png)

### Current behavior
Not all DOM elements added on SpreadSheet initialization are being removed when destroying it and removing its corresponding DOM element.

### Expected/desired behavior
After destroying a SpreadSheet and removing its corresponding DOM element, no DOM nodes added on component's initialization should be presented in the DOM tree. 

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Not reproducible with latest version
