### ISSUE TITLE
Updating popup from editable grid crashes browser

### ISSUE THREAD

**Issue by JarLowrey** [telerik/kendo-ui-core#5091]
### Reproduction of the problem

Below is the code causing an issue

	@(Html.Kendo().Grid<ProjectReviewDocument>()
		.Name("fgrid")
		.Columns(columns =>
		{
			columns.Bound(c => c.ProjectReviewDocumentID).Visible(false);
				columns.Bound(e => e.DocumentNumber).Width("20%")
					.ClientTemplate("<a href='" +
					Url.Action("DownloadFile", "ProjectReviewDocuments", new { fileId = "#=ProjectReviewDocumentID#" }) +
					"' target='_blank'>#=DocumentNumber #</a> ");

			
			
			columns.Bound(c => c.DocumentTitle);
			columns.Bound(c => c.DocumentStatus).Hidden(true);
			columns.Bound(c => c.Verified).Hidden(true);
			columns.Bound(c => c.DocumentNotes).Hidden(true).Encoded(false);
			columns.Bound(c => c.FileName).Hidden(true);
			columns.Bound(c => c.UploadedBy).Hidden(true);
			columns.Bound(c => c.UploadedOn).Hidden(true);
			columns.Bound(c => c.LastModifiedOn).Hidden(true);
			columns.Bound(c => c.IsDepricated).Hidden(true);
			columns.Bound(p => p.ProjectReviewDocumentID)
				.ClientTemplate("# if (ProjectReviewDocumentID != 0) { # <a href=\"javascript:void(0);\" onclick=\"showAuditRecordHistory('#=ProjectReviewDocumentID#', 'ProjectReviewDocument')\"><img src=\""
					+ Url.Content("~/Content/images/info-black.png")
					+ "\" /> </a> # } #")
				.Title("")
				.Width(25)
				.HtmlAttributes(new { @class = "text-center" })
				.Sortable(false)
				.Filterable(false)
				.Hidden(false);
			columns.Command(command =>
			{
				command.Edit().UpdateText("Save").CancelText("Cancel").Text("Edit");
			}).Width(UIConstants.ButtonWidthForDelete);
		})

		.ColumnMenu()
		.Sortable()
		.Filterable()
		.Pageable(pageable => pageable
			.PageSizes(new[] { 5, 10, 25 })
			.ButtonCount(5))

		.Editable(editable => editable.Mode(GridEditMode.PopUp).Window(w => w.Width(450)).TemplateName("ProjectReviewDocumentID"))

		.DataSource(dataSource => dataSource
			.Ajax()
			.Events(events => events.Error("handleGridError")) //_site.js
			.Model(model =>
			{
				model.Id(p => p.ProjectReviewDocumentID);
			})
			.Update(update => update.Action("Edit", "ProjectReviewDocuments"))
			.Read(read => read.Action("Read", "ProjectReviewDocuments").Data("returnXPath"))
			.PageSize(5)
		))

### Current behavior

1. Open the Editable popup
2. Click "Save"/"Update" - it closes successfully, no actions called
3. Open it again, this time change the DocumentTitle
4. Hit save. Chrome CPU will spike to >40%, RAM to >1gig. Becomes unresponsive, requires task manager interference
5. Redo in IE11. Same will occur but browser recovers before freezing forever. Params never sent to controller action

### Expected/desired behavior

Pass the updated info to controller action and close the popup successfully. No infinite loops or crashes.

### Environment

* **Kendo UI version:** 2015.1.429
* **jQuery version:** 2.1.3
* **Browser:** [Chrome, IE11]

**Comment by matanasov** [comment]
The version reported in this issue (2015.1.429) is more than 5 years old. It is very likely that the erroneous behavior has been fixed in later versions. 
Could you please test the same scenario with the latest Kendo version?

**Comment by JarLowrey** [comment]
I could not update due to the amount of regression testing that would be required. Instead I created a new partial for the form popup, and got it to display when the grid button is clicked using jQuery.
