### ISSUE TITLE
grid resize handler appear in wrong position

### ISSUE THREAD

**Issue by pouyapoosh** [telerik/kendo-ui-core#5103]
hi i have a kendo ui grid in attached file which is dynamic and deppend on data that u pass to it ,it will genrate a grid 
and its problem is when i resize a column for the first time , the resize handler wont move as like as column width and appear in wrong place and it stock there.
i think its a bug

[grid sample.txt](https://github.com/telerik/kendo-ui-core/files/3269305/grid.sample.txt)

**Comment by matanasov** [comment]
If you consider the current behavior is a bug please provide a minimal demo of the problem via http://dojo.telerik.com or similar.
