### ISSUE TITLE
Missing Button shadow in normal state with LESS Material theme

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5104]
### Bug report
Default and primary buttons have no shadow in normal state in the LESS Material theme. 

### Reproduction of the problem
[Demo](https://demos.telerik.com/kendo-ui/button/index).

### Environment

* **Kendo UI version:** 2019.2.514
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
After the initial fix there is unexpected shadow of Chat toolbar buttons:
![image](https://user-images.githubusercontent.com/6614183/59346558-3e473c00-8d1b-11e9-8caf-25ae7721f9d5.png)
