### ISSUE TITLE
Dates and Numbers are not serialized correctly with WebApi

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#5107]
When using a specific culture the values are not formatted according to the culture which leads to wrong parsing. More information about this problem alongside with samples can be found in ticket - 1411504.

It seems that the change is caused by [this ](https://github.com/telerik/kendo/issues/3263)fix.

**Comment by Alex-Bubblemaster** [comment]
Also reported in 1419411, 1384571 and 1419392. Raising priority.
