### ISSUE TITLE
Scheduler's select() method selects only the last event when multiple ones are passed

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5119]
### Bug report
When using Scheduler's select() method, according to the documentation and the examples given in the [official API](https://docs.telerik.com/kendo-ui/api/javascript/ui/scheduler/methods/select), we should be able to select multiple items when passing their IDs in an array.

### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/@Dimitar-Goshev/EMuxUNOS).
2. See that when calling the select() method, we are passing the IDs of all events listed in the dataSource.
3. Run the Dojo and see that only the event which ID is last in the array is being selected.

### Current behavior
Currently, the select() event is selecting only the last element when an array of event IDs are passed to it

### Expected/desired behavior
When passing event IDs to Scheduler's select method, the events which IDs have been passed should be selected when the method is called

### Environment
* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
Also mentioned in thread #1454317

**Comment by aleksandarevangelatov** [comment]
Reported in #1471189

**Comment by martintabakov** [comment]
Also reported in #1493153
