### ISSUE TITLE
Editor overflow dropdown does not close after clicking a tool in it

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5127]
### Reproduction of the problem
Reproducible in the [demos](https://demos.telerik.com/kendo-ui/editor/index).
1. Shrink the browser window so that some of the Editor tools go under the overflow button. 
2. Click the overflow button and then click a tool in the dropdown that opens a dialog ("Insert Image" or "Insert hyperlink"). 

### Current behavior
A new dialog opens, but the overflow dropdown does not close and remains visible below the newly opened dialog. 

In the inline Editor the overflow dropdown is shown above the newly opened dialog.

### Expected/desired behavior
The overflow dropdown closes.

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by IvanDanchev** [comment]
Because the overflow dropdown does not close it is possible to open 2 tool dialogs at the same time. When both "Create a table" and "Insert Image" tools are in overflow, if you click on "Create table" and then on "Insert Image" their new dialogs will be visible at the same time.

**Comment by Dimitar-Goshev** [comment]
Not reproducible with version 2023.3.1114 - https://demos.telerik.com/kendo-ui/editor/basic-usage
