### ISSUE TITLE
Comments in the Spreadsheet are not properly displayed in frozen columns scenario

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5128]
### Bug report
Comments in the Spreadsheet are not properly positioned in frozen columns scenario.

Related to: #5097

### Reproduction of the problem
Run the following Dojo: https://dojo.telerik.com/uhEWEsAf/5 and hover the A1 cell.

### Current behavior
The comment element will be truncated within the pane, which contains the frozen columns.

### Expected/desired behavior
The comment should not be truncated

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by veselints** [comment]
also reported in: Ticket ID: 1453794

**Comment by IvanDanchev** [comment]
The comment does not appear even without using frozen columns, if the comment is in the last column. Ticket ID: 1479799

**Comment by mishoo** [comment]
> The comment does not appear even without using frozen columns, if the comment is in the last column. Ticket ID: 1479799

This should be fixed as well, if the comment doesn't fit to the right of the cell (more exactly, if there are less than 200 pixels on the right), it'll be displayed on the left side.  A `max-width: 200px` style has been added for this on comment tooltips.
