### ISSUE TITLE
Editor removes wrong element when backspace is hit and immutables is set to true

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#5135]
### Bug report

Editor removes wrong element when backspace is hit and immutables is set to true

### Reproduction of the problem
Open the dojo: https://dojo.telerik.com/@sspasova/ODIgaLOm

1. Put the cursor at the end
2. Hit backspace

### Current behavior

Strong tag disappears but it shouldn't.

### Expected/desired behavior

The strong tag should not disappear.

### Environment

* **Kendo UI version:** 2023.3.1114
* **Browser:** [all ]

**Comment by gdenchevprog** [comment]
Duplicate of - https://github.com/telerik/kendo-ui-core/issues/7070

The issue has been fixed.
