### ISSUE TITLE
Cannot resize columns in a scrolled grid

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/kendo-ui-core#5137]
### Bug report

When you resize a column so the grid has a scrollbar, and scroll to the right, you can no longer resize columns because the handle disappears. Did not manifest in 2019.2.514. May be related to #5058

### Reproduction of the problem

See the video of the unexpected behavior where after the grid is scrolled, column resizing is erratic or impossible: [https://www.screencast.com/t/AEedzjdWI](https://www.screencast.com/t/AEedzjdWI)

You can test it in this dojo:
[https://dojo.telerik.com/@bratanov/oFoDUQit](https://dojo.telerik.com/@bratanov/oFoDUQit)

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** tested with 1.12.4 only

From Ticket ID: 1414322

**Comment by Alex-Bubblemaster** [comment]
Also reported in 1416757

**Comment by marin-bratanov** [comment]
Also reported in 1417972, with another reproducible: [https://dojo.telerik.com/@techadmin@titancloud.com/ExOLuvIV](https://dojo.telerik.com/@techadmin@titancloud.com/ExOLuvIV)

**Comment by marin-bratanov** [comment]
Also reported in 1418635

**Comment by marin-bratanov** [comment]
A fix is available in the [2019.2.718 internal build](https://www.telerik.com/support/whats-new/aspnet-mvc/release-history/ui-for-asp-net-mvc-2019-2-718-internal-build), in case you are still in development (internal builds are not suitable for production). 

Our next official release (planned for mid-September) will also contain this fix so you can upgrade to it when it becomes available.

If you need a site live with this, the option is to revert back to the R2 2019 (2019.2.514) release.
