### ISSUE TITLE
DefaultValue should be applied when it is declared

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#5139]
### Bug report

Ticket ID: 1415663

### Reproduction of the problem

```
 .Model(model =>
 {
         model.Id(p => p.OrderID);
         model.Field(p => p.Status).DefaultValue("A");
})
```
The string fields are serialized as `nullable:true` since #5055 . However, currently when a field is nullable, the [defaultValue](https://docs.telerik.com/kendo-ui/api/javascript/data/model/methods/define) is ignored.

![image](https://user-images.githubusercontent.com/10980842/60183684-74aeac00-982f-11e9-85e2-9173f96384f6.png) 

### Current behavior

The default value is ignored and string fields are created with `null` value for the field.

### Expected/desired behavior

When a DefaultValue() is defined, it should take precedence over the nullable nature for its type.

### Workaround

Add a ***BeforeEdit()*** event handler and assign the desired default value:

```
.Events(e=>e.BeforeEdit("onBeforeEdit"))
<script>
    function onBeforeEdit(e) {
      if(e.model.isNew()){
        e.model.Status = "A";
      }
    }
</script>
```

### Environment

* **Kendo UI version:** 2019.2.619

**Comment by boyandim** [comment]
A regression for not applying the default values for certain fields was introduced with commit related to the [https://github.com/telerik/kendo-ui-core/issues/5055](https://github.com/telerik/kendo-ui-core/issues/5055) issue. As a result default values for some fields were not applied even when they are set in the configuration. 
A new fix was included in the latest internal build (2019.2.718) and now the default values should be applied as expected. The [Release notes section](https://www.telerik.com/support/whats-new/aspnet-mvc/release-history/ui-for-asp-net-mvc-2019-2-718-internal-build) is a great place to find information about all fixes that are included in the current LIB or official release.
