### ISSUE TITLE
Selection does not work correctly in IE 11 in Timeline View with vertical grouping and eventHeight set to odd number

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#5141]
### Bug report
When the Scheduler is grouped, selecting a cell from the last row does not mark it as selected in IE 11 in TimelineView. This behavior is only reproducible if the eventHeight option is set to an **odd** number (35, 37, etc.)

### Reproduction of the problem
1. Open https://dojo.telerik.com/UxetITah/3 in IE 11.
1. Click on any of the cells in the last row('Charlie').

### Current behavior
The same cell in the previous row is marked as selected - Selection does not mark the correct cell as selected in TimeLine View with grouping and the specified eventHeight.

### Expected/desired behavior
Selection should mark the correct cell as selected in TimeLine View with grouping and the specified eventHeight.

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** IE11

**Comment by IvanDanchev** [comment]
Also reported in Ticket ID: 1521928 for the timelineWeek view. 

Priority raised.

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
