### ISSUE TITLE
Encode column titles before displaying them

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#5144]
### Bug report

Currently column titles are not html escaped in header templates, group header templates and column menus.

### Reproduction of the problem

Create a title which contains html.

### Current behavior

The title is not escaped.

### Expected/desired behavior

The title should be escaped.

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by TeyaVes** [comment]
Similar issue reported in ticket #1457818

If HTML is set as a column title in a Grid with grouping enabled, the column title is broken:

[https://dojo.telerik.com/oLoJAHOw/7](https://dojo.telerik.com/oLoJAHOw/7)
