### ISSUE TITLE
Kendo UI jQuery checkbox CSS work, but after that, cannot check/uncheck on checkbox

### ISSUE THREAD

**Issue by donhuvy** [telerik/kendo-ui-core#5161]
### Bug report

**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our feedback portal](https://www.telerik.com/support/feedback)**

### Reproduction of the problem
_(bug report only)_
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via http://dojo.telerik.com or similar.

### Current behavior
```html
<input type="checkbox" th:field="*{isVendor}" th:checked="*{isVendor}" class="k-checkbox">
<label th:for="isVendor" class="k-checkbox-label">Khách hàng hàng cũng là nhà cung cấp?</label>
```
![image](https://user-images.githubusercontent.com/1328316/60754205-0d9baf00-a008-11e9-9619-a82e25400fe0.png)

Cannot check / uncheck the checkbox
      

### Expected/desired behavior
Explain what the expected behavior of the functionality is
Check / Uncheck the checkbox normally.

### Environment

* **Kendo UI version:** 2019.2.514 theme Office 365
```html
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2019.2.514/styles/kendo.common-office365.min.css"/>
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2019.2.514/styles/kendo.office365.min.css"/>
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2019.2.514/styles/kendo.office365.mobile.min.css"/>
```

* **jQuery version:** x.y
* **Browser:** Google Chrome Version 75.0.3770.100 (Official Build) (64-bit) Windows 10 pro x64

**Comment by dmanova** [comment]
Hello! 
Try to specify **id** attribute in the **input** tag. If it doesn't solve the issue, could you please provide a runnable example (DoJo) that demonstrates the problem you need fixed?

**Comment by donhuvy** [comment]
Thank you,
In my web-app, I try to specify id in input tag --> checkbox not work.
I make a dojo at here https://dojo.telerik.com/@donhuvy/aLOMEZik , it work, but put it in web-app, it still doesn't work.

**Comment by donhuvy** [comment]
It is my error. In Thymeleaf, I must use `th:checked=*{foo}` , not `th:field=*{foo}` . Thank you very much. 

(P/S: Please consider merge this pull https://github.com/telerik/kendo-ui-core/pull/5102 )

**Comment by dmanova** [comment]
Thank you. We'll consider the merge.
