### ISSUE TITLE
ComboBoxFor helper with Name set does not throw exception when used as Grid editor

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5165]
### Bug report
In Core when the ComboBoxFor helper is used as an editor in a Grid (Shared/EditorTemplates) and its Name is set, the Grid does not render and no exception is displayed, to indicate that the Name option should not be set. 
 
### Reproduction of the problem
Reproducible in the **Editing custom editor** Grid demo. 

1. Set the ComboBox' Name in the ClientCategory.cshtml template
```
@(Html.Kendo().ComboBoxFor(m => m)
    .Name("CategoryID")
    .DataValueField("CategoryID")
    .DataTextField("CategoryName")
    .BindTo((System.Collections.IEnumerable)ViewData["categories"])
)
```

### Current behavior
We throw an exception when the Name is set (e.g. if the ComboBox is used outside of a Grid), but in this scenario it is not displayed. 

### Expected/desired behavior
An exception is thrown and its message is displayed. 

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by gyankov** [comment]
Exception is not thrown as the Render method of the view is executed within a try block:

- https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.ViewFeatures/src/ViewExecutor.cs#L243

I will log a feature request to ASP.Net Core to conditionally allow the exception to propagate.

**Comment by gyankov** [comment]
Feature request in .Net Core:

- https://github.com/dotnet/aspnetcore/issues/33065

**Comment by gyankov** [comment]
Apparently there is no way to display the developer exception page in this scenario although the exception is thrown.
