### ISSUE TITLE
Unable to change scrolling direction rapidly with mouse wheel when page top/bottom is reached

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#5168]
### Bug report
Unable to change scrolling direction rapidly with mouse wheel when page top/bottom is reached.
When the top or bottom of the page is reached, there is bouncing effect. If you try to change the scrolling direction during this effect, scrolling will not be applied.

### Reproduction of the problem
[VIDEO](https://www.screencast.com/t/4fnbbXzzeF)
1. Run the following [Dojo](https://dojo.telerik.com/IhEzICux)
1. Scroll to the bottom of the div with mouse wheel
1. Continue scrolling down with mouse wheel (make rapid turns)
1. As you are scrolling down (the vertical scrollbar being visible), immediately start scrolling up with mouse wheel.

### Current behavior
It is not possible to start scrolling to top, unless you stop scrolling and wait for the scrollbar to disappear.

### Expected/desired behavior
Scrolling to top should happen immediately. 

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
Reported in ticket ID 1432969
