### ISSUE TITLE
Cannot select PM time in DateTimePicker parseFormats API demo

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#5169]
### Bug report
Cannot select PM time in DateTimePicker parseFormats API demo.

Reported in 1417934

### Reproduction of the problem

1. https://docs.telerik.com/kendo-ui/api/javascript/ui/datetimepicker/configuration/parseformats
1. select a "PM" time from the dropdown

### Expected/desired behavior
"PM" time is shown in the input.

### Environment
* **Kendo UI version:** 2023.3.1114
* **Browser:** [all]

**Comment by nelito987** [comment]
https://github.com/telerik/kendo/pull/19066
