### ISSUE TITLE
Generated pdf document cannot be saved using saveAs

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#517]
When the generated document is opened with Acrobat Reader and you try to use the save as option from the file menu an error is thrown.

"The document could not be saved. There was a problem reading(23)"

**Comment by dtopalov** [comment]
Added in the Kendo UI Documentation as a known limitation of the Kendo UI Drawing API:

[LINK](http://docs.telerik.com/kendo-ui/framework/drawing/drawing-dom#known-limitations)
