### ISSUE TITLE
DateRangePicker is not bound initially when using ControllerAs syntax

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5177]
### Reproduction of the problem
1. Run this dojo - https://dojo.telerik.com/ihOyAzIG/3

### Current behavior
The DateRangePicker does not have initial values applied.

### Expected/desired behavior
Values for the picker should be applied

### Environment

* **Kendo UI version:** 2019.2.619

**Comment by gilm0079** [comment]
Thanks for entering this Viktor. I was the one that submitted the bug. I'm watching the issue here as well. Message me if there are further questions about the issue. I'll work on a jquery workaround for the time being. Looking forward to a fix in a future build. It's a nice control.

**Comment by Dimitar-Goshev** [comment]
Starting with R2 2022, the Kendo UI team officially drops the support for AngularJS 1.x through Kendo UI for jQuery
