### ISSUE TITLE
Angular mobile split view cannot set to `horizontal`

### ISSUE THREAD

**Issue by shengoo** [telerik/kendo-ui-core#518]
Hi, 

I upgrade to version `2014.3.1316` today
but found that the mobile splitview directive is vertically and cannot set to horizontal
check out from http://dojo.telerik.com/ihEwA

Thanks.

**Comment by underlog** [comment]
Our demo - http://demos.telerik.com/kendo-ui/splitview/angular is broken too. Strange thing, it affects only the angular version. We will look into it as soon as possible.
