### ISSUE TITLE
Add a selection section to the asp.net core -> tag-helpers -> data managment -> grid section of the documentation

### ISSUE THREAD

**Issue by cOborski** [telerik/kendo-ui-core#5186]
I would like to copy the selection section of the html helper section of the asp.net core documentation and create an analogous section for the tag helper section of the documentation.

**Comment by cOborski** [comment]
I've forked the repository and created the [branch iss5186](https://github.com/cOborski/kendo-ui-core/tree/iss5186).

**Comment by dmanova** [comment]
Thank you for the contribution.
When you are ready you may submit a pull request. For more information and guidance, you may follow these links:
https://github.com/telerik/kendo-ui-core/tree/master/docs#contributing
https://docs.telerik.com/aspnet-core/tag-helpers/datasource/overview
https://docs.telerik.com/aspnet-core/api/Kendo.Mvc.UI.Fluent/GridBuilder#selectable

**Comment by dmanova** [comment]
As a token of gratitude for the contribution we have updated your [Telerik points](https://www.telerik.com/community/telerik-points).
