### ISSUE TITLE
Map markers initially show on top of map controls in Internet Explorer

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-ui-core#5187]
### Bug report
In IE the markers of kendoMap initially show on top on the map controls. Once you start panning the controls correctly show on top of the markers.

Ticket ID 1421688

### Current behavior
https://dojo.telerik.com/ULeWIVeV
https://dojo.telerik.com/aqONIfig

1. Load kendoMap with markers in IE.
2. Make sure a marker is positioned at the top left corner, at the same place as the map controls. 
If not you may try to resize the browser or change the marker's location.
3. Check that the marker is in front of the map controls.
4. Drag/ Pan the map and position the marker again at the same place as the map controls - now it is fine, behind the map controls. 

### Expected/desired behavior
The markers of kendoMap initially show behind the map controls. 

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** [IE]

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
