### ISSUE TITLE
hoverDelay does not work as expected when switching between items

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-ui-core#519]
Explanation here: http://www.telerik.com/forums/hoverdelay-setting-behavior

**Comment by bundyo** [comment]
I think that hoverDelay can never be a silver bullet for this behavior. However, there is a better approach, used by Apple before and now by Amazon - check this thorough article about it:
http://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown

**Comment by alexsar** [comment]
Thanks for the link - very interesting idea! 
Yes, you are right hoverDelay will not be a silver bullet, but I still think its behavior should be consistent - the amazon's approach is just a very neat alternative solution :)
