### ISSUE TITLE
Transition CSS Effect 'cubic-bezier' applied to Grid rows (tr) causes Infinite 1px height inline-style increment

### ISSUE THREAD

**Issue by Doodely** [telerik/kendo-ui-core#5191]
### Bug report
I provided a .webm to display the current issue being presented. I am unsure of if this relates to the rendering-engine, but it seems that post-compile (scss) CSS for transitions, specifically cubic-bezier, is causing unexpected behavior with row heights in Webkit-based browsers.

When applying a transition effect to the { kendo-grid <tr> } element, on render, it is auto-incrementing an inline-style for the height attribute, based on fps (1px or more per second).

The Grid has a Custom-Toolbar component and two locked columns. (This might have no bearing, or it could be a bug with flexbox and how it contains elements)

### Reproduction of the problem
1. **CSS Selector:** kendo-grid.k-grid table tbody tr
2. **Effect:** transition: .4s cubic-bezier(.25,.8,.25,1);
3. **Load a grid**

### Current behavior
![CSS Transition Height Bug](https://user-images.githubusercontent.com/7016889/61968784-dd13b900-afa6-11e9-881c-0d2a0a449bff.png)

### Expected/desired behavior
Non incrementing inline-style height on row element.

### Temporary Solutions
Remove the transition effect.
Add a max-height css / inline-style to the row.

### Environment

* **Kendo UI version:** Latest
* **Angular:** 8
* **Browser:** [Webkit-based | Chrome: Version 75.0.3770.142 (Official Build) (64-bit)] 

[Transition Effects on Grid Rendering Bug.zip](https://github.com/telerik/kendo-ui-core/files/3436728/Transition.Effects.on.Grid.Rendering.Bug.zip)

**Comment by Doodely** [comment]
If needed, grid markup could be provided!

**Comment by dmanova** [comment]
Could you please provide a runnable example (DoJo) that demonstrates the problem?
