### ISSUE TITLE
ArcGauge should allow setting of its HtmlAttributes()

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#5192]
### Enhancement

Ticket ID 1418725

### Current behavior

Currently it is not possible to pass HtmlAttributes() to the ArcGauge wrapper. The other gauges have this method, the ArcGauge should be no different.

### Expected/desired behavior

The HtmlAttributes() should be set to the widget's element.

### Environment

* **Kendo UI version:** 2019.2.619

**Comment by marin-bratanov** [comment]
The goal is that the gauge can fill up its container, so this should result in a big gauge:

```
<style>
/* this rule for the gauge size should be unnecessary if the HtmlAttributes worked, Important: The surface rule must not be needed either */
/*
     [data-role="arcgauge"],
     [data-role="arcgauge"] [data-role='surface'] {
		/* set the size of gauges to fill their containers. You may want to make the selectors more specific */
		width: 100% !important;
		height: 100% !important;
	}
*/

	.gauge-container {
		width: 600px;
		height: 400px;
	}
</style>

<div class="gauge-container">
	@(Html.Kendo().ArcGauge()
		.Name("gauge4")
		.Value(65)
		.HtmlAttributes(new { style="width: 100%; height:100%;" })
	)
</div>
```
