### ISSUE TITLE
Grid editing in InCell edit mode does not accept new values on mobile devices

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#5193]
### Bug report

Grid editing in InCell edit mode does not accept new values on Mobile devices. 

### Reproduction of the problem

1. Open https://demos.telerik.com/kendo-ui/grid/editing on a mobile device(or Chrome dev tools)
1. Edit a cell and click on another cell - https://screencast-o-matic.com/watch/cqiUoEOkwE

### Environment

* **Kendo UI version:** 2019.2.619
* **Browser:** [Mobile]

**Comment by dmanova** [comment]
Also fix issue described in Ticked 1431575.
