### ISSUE TITLE
Grid VUE Wrapper - Cannot add new rows at Grid's bottom using editable-create-at="bottom"

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5198]
### Bug report

In Grid(Wrapper) in UI for Vue, the **editable-create-at** is not changing Grid's "add new row" behavior when it is set to "bottom".

### Reproduction of the problem
1. Open [this Stackblitz](https://stackblitz.com/edit/kl2dxx?file=index.html) and run it
2. Press the "Add new record" button and see that the new record is being added to at the top of the Grid

A workaround that could be applied is to use ` :editable="{createAt:'bottom'}"` instead of `:editable-create-at="bottom"`

### Current behavior
The new rows are not being added to the bottom of the Grid with ` :editable-create-at="bottom"` configuration applied. 

### Expected/desired behavior
When `:editable-create-at="bottom"`  is applied the new records in the Grid should be added to its bottom

### Environment

* **Kendo UI version:** 2019.2.621
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by martintabakov** [comment]
Also reported in thread #1428273.

**Comment by zdravkov** [comment]
The correct definition of the property is with :editable-create-at="'bottom'" - here is an example where the configuration is set correctly - https://stackblitz.com/edit/kl2dxx-azqhkt?file=index.html
