### ISSUE TITLE
StockChart clips the last point

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#5200]
### Bug report

Reported in ticket 1363584 

### Reproduction of the problem

[Dojo](https://dojo.telerik.com/aqEMErIP)

### Current behavior

This seems to have worked in 2018 R2 and 2018 SP1 but since 2018 R3, the stock chart clips the last point. Possibly related with #2331 

### Expected/desired behavior

The StockChart should display the points available when navigator.select and or / categoryAxis.max are set

### Workaround

Setting `baseUnit: "days"` helps show the last point with a `to` setting in the navigator select that is after the last data point.

[Dojo](https://dojo.telerik.com/@bubblemaster/EHavIlUD)

### Environment

* **Kendo UI version:** 2019.2.619

**Comment by gdenchevprog** [comment]
This issue has also been reported in ticket 1493124

**Comment by dimodi** [comment]
Also in 1597959

**Comment by tsvetomir** [comment]
Working on a fix. In the meantime, set `navigator.categoryAxis.justified` to false as a workaround: [dojo](https://dojo.telerik.com/UsitOYAb).
