### ISSUE TITLE
Date pickers have undocumented widget options for popup

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#5203]
### Bug report

Date pickers utilize the Kendo Popup widget, which is configurable through the popup option. However, this is not documented in the API and thus, wrapper components are not generated with that options. 

Reported in ticket 1416858

### Reproduction of the problem

https://dojo.telerik.com/oYuDEcUF

### Current behavior

All server wrappers are missing the popup configuration option.

### Expected/desired behavior

The popup option to be documented in the API and generated in the wrappers 

### Environment

* **Kendo UI version:** 2019.2.619

**Comment by matanasov** [comment]
All the links are now generated but the MVC ones are broken. Check them here:
http://kendobuild-staging.openstack.progress.com/aspnet-mvc/api/datepicker
