### ISSUE TITLE
Less Themebuilder does not take into account widget styles in component/_theme.less and component/_layout.less 

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-ui-core#5205]
With the new structure of components styles in our LESS theme, we have divided the styles into theme.less and layout.less files. However, when creating the CSS file, the LESS ThemeBuilder is not taking into account these files, but rather uses the styles only from the type-theme.less file, thus, there are missing styles in the compiled CSS.

**Comment by Juveniel** [comment]
Also reported in TickerID: 1450275

**Comment by IvanDanchev** [comment]
Also reported in Ticket ID: 1485653

**Comment by Juveniel** [comment]
related to: https://github.com/telerik/kendo-ui-core/issues/5205
