### ISSUE TITLE
Some items are not translated in the rich-text editor (with Spanish locale for example)

### ISSUE THREAD

**Issue by BBiliyanavishanova** [telerik/kendo-ui-core#5213]
### Reproduction of the problem
When the rich-text editor is used with Spanish locale, the following items are not translated to Spanish and remain in English:
1) Tool-tip for the icon "Clean formatting"
2) In the modal for the "Upload image" option:
2.1. Button "UPLOAD"
2.2. Help text "Search"
2.3 Drop-down "Arrange by" with options "Name" and "Size"

### Expected/desired behavior
The mentioned items to be translated to Spanish

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** 3.4.1

* **Browser:** [all | Chrome 75 ] 

![image](https://user-images.githubusercontent.com/54026543/62861951-a7dcca00-bd0d-11e9-862a-8a7b389a64b0.png)
![image](https://user-images.githubusercontent.com/54026543/62862391-5b45be80-bd0e-11e9-947b-12337bf155d7.png)

**Comment by dmanova** [comment]
Currently, translations are not available for every language and some of the localization files may be incomplete. You are welcome to contribute to the translations. Here is a link with more information on that matter: [Localization Contribution](https://docs.telerik.com/kendo-ui/globalization/localization#contribution )
