### ISSUE TITLE
Text "0 items selected" in the filter drop-down to be translated to Spanish

### ISSUE THREAD

**Issue by BBiliyanavishanova** [telerik/kendo-ui-core#5214]
### Reproduction of the problem
Text "0 items selected" in the filter drop-down to be translated to Spanish for Spanish locale - see attached screenshot

### Expected/desired behavior
Text to be in Spanish for Spanish locale

### Environment

* **Kendo UI version:** 2019.2.611
* **jQuery version:** 3.4
* **Browser:** [all | Chrome 75]

![image](https://user-images.githubusercontent.com/54026543/62872680-a66bcb80-bd26-11e9-9c4e-6bf1daee67ad.png)

**Comment by dmanova** [comment]
Currently, translations are not available for every language and some of the localization files may be incomplete. You are welcome to contribute to the translations. Here is a link with more information on that matter: [Localization Contribution](https://docs.telerik.com/kendo-ui/globalization/localization#contribution )
If you decide to contribute I would suggest using [kendo.messages.en-US.js](https://github.com/telerik/kendo-ui-core/blob/master/src/messages/kendo.messages.en-US.js) as reference for the complete set of messages.
