### ISSUE TITLE
JavaScript exception on using multiple filters in the native Vue Grid 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5216]
### Reproduction of the problem
Reproducible in the [Basic Usage](https://www.telerik.com/kendo-vue-ui/components/grid-native/columns/column-menu/#toc-basic-usage) demo. [Screencast](https://www.screencast.com/t/ZfcFEXf0hx4q). 
1. Filter the Name column by specifying two alternative filters (by selecting "Or")

### Current behavior
A js exception is thrown.

### Expected/desired behavior
The Grid is filtered.

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by zdravkov** [comment]
Should be fixed in the latest 0.3.5 version
