### ISSUE TITLE
Wrong end date in Scheduler Agenda view of events ending on autumn daylight saving date

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#5217]
### Bug report
On the autumn daylight saving date, in agenda view the events will be created for the next day as well if they are created past 11 pm.

Could be related to #3810 and #3381.

### Reproduction of the problem
1. Go to this [Dojo](https://dojo.telerik.com/enAXoCuK/2)
2. Create new Event on the 10/27/2019 with End Time 11:15 pm.
3. Go to Agenda View.

### Current behavior
The event is created on the 10/28 as well.
![image](https://user-images.githubusercontent.com/6614183/63014050-4bf17d00-be96-11e9-86d9-4924fb320752.png)

### Expected/desired behavior
The event should be created only on the 10/27.

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by veselints** [comment]
Not related to https://github.com/telerik/kendo-ui-core/issues/3810
