### ISSUE TITLE
Mobile view title is not rendered

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5221]
### Bug report
Regression introduced in version 2019.2.514.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/itAvoxON/3) example.
1. Run the example with version 2019.2.514 or newer

### Current behavior
The MobileView title is not rendered. 

### Expected/desired behavior
The title is rendered.

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Seems to be fixed in the latest release.
