### ISSUE TITLE
Extending the prototype for array breaks kendo no matter how you extend it

### ISSUE THREAD

**Issue by TehWardy** [telerik/kendo-ui-core#5224]
It's been nearly 2 years so I figured i'd repost this here ...

https://stackoverflow.com/questions/47157045/why-does-kendo-ui-break-when-extending-array-prototype

... this happens on treeviews, grids, listviews, ect as I think it must be breaking the datasource functionality or something.
It's frustrating as I wanted to have my own framework add some "basic helper methods" like an implementation of LINQ in JS on to the array prototype to assist with clean client coding and the only way i can do this is to have a jquery like implementation where I do something like this ...

```
var anArray = new Array();
var query = LINQ(anArray).Where(...);
var filteredSet = query.ToArray();
```

I would much rather just do ...

`var filteredSet = anArray.Where(...);`

... but kendo UI breaks.

**Comment by matanasov** [comment]
Could you provide a runnable example demonstrating you setup and the error you get? Please also provide the Kendo version you are using.

**Comment by TehWardy** [comment]
This is a nearly 2 year old issue to my knowledge the information here hasn't changed.
Literally any kendo grid I tried to setup with having an array prototype extension on the page triggered the kendo code to fail.

If you can't reproduce it i'll happily look in to it but right now i'm the middle of a huge cloud infrastructure project so there might be a delay before I can sit down with this.

**Comment by matanasov** [comment]
Yes, runnable example is suggested and once you are ready with it, please share it here. 
Our developers will take a look at it and update the item accordingly.

**Comment by dmanova** [comment]
Hello @TehWardy,
Could you provide a runnable sample?
You could use our interactive environment at https://dojo.telerik.com/ , if you find it easier, and send us the URL address of the sample.

**Comment by dmanova** [comment]
This doesn't seem to be a Kendo related issue.  
The Array() is an object in JavaScript and is expected to start with capital letter.
I've checked the documentation for `Array` at https://www.w3schools.com/jsref/jsref_obj_array.asp  and changing the first capital letter to a small cause the JS code not to work in the example here: https://www.w3schools.com/jsref/jsref_prototype_array.asp

So I'm closing this issue, as not in the Kendo UI code.
