### ISSUE TITLE
TreeView template leaks memory on changes in the observable

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5226]
### Bug report

[HtmlPage1.zip](https://github.com/telerik/kendo-ui-core/files/3519331/HtmlPage1.zip)

### Reproduction of the problem
1. Run the attached page in the browser.
2. Take a 20 sec long heap snapshot. During these 20 sec click the "change" button to make changes to a specific node's data in the observable.

### Current behavior
Increasing number of detached span elements: [screenshot](https://www.screencast.com/t/drEMriZU8IRj)
Memory consumption increases with every change: [screenshot](https://www.screencast.com/t/kxcxBEkg)

There are no detached span elements if the span within the template does not have a data attribute set.
from:
```
<span data-bind="text: treetext"></span>
```
to:
```
<span>#=item.treetext#</span>
```
### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by PekoPPT** [comment]
Similar scenario reproduced in ticket #1427782 -  Repopulating the DataSource causes memory leaks
