### ISSUE TITLE
MultiColumnComboBox with enabled Virtualization as editor in the Grid loses selection in some scenarios

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5227]
### Reproduction of the problem
1. Run dojo - https://dojo.telerik.com/oHUNovix/2
1. Focus the combo and press Ctrl+Space to open items list
1. Press down arrow and keep it depressed until the second page is reached

### Current behavior
Selection is lost and arrow keys cannot be used for further navigation

Video - https://www.screencast.com/t/bmy6GAaR

### Expected/desired behavior
Selection should be persisted and arrow keys should be usable

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Not reproducible with latest version
