### ISSUE TITLE
kendo.ooxml.Workbook does not properly calculate autoWidth of columns

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5238]
### Reproduction of the problem
1. Run this dojo - https://dojo.telerik.com/ixIbuVeM/6

### Current behavior
The first column is not resized correctly to fit the entire text:

![image](https://user-images.githubusercontent.com/11771009/63839147-6132d500-c987-11e9-92f7-2082dd27b803.png)

### Expected/desired behavior
The cell should be resized to fit the text

### Environment

* **Kendo UI version:** 2019.3.1023
* **Browser:** [all] 

Related to #4750 #4089

**Comment by ag-petrov** [comment]
Does not seem to be reproducible anymore
