### ISSUE TITLE
Mobile material theme does not contain CSS rules with ".km-primary" selector

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5242]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/adUfUXUl) example.

### Current behavior
The mobile material theme does not apply specific styles to a button that has the "km-primary" class. Compare to the Nova mobile theme, which does have specific rules that use ".km-primary" selector.

### Expected/desired behavior
CSS rules that use the ".km-primary" selector should be added to the theme. 

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by magdalenaan** [comment]
The Kendo UI Mobile LESS themes are [officially deprecated](https://www.telerik.com/blogs/future-plans-telerik-kendo-ui-less-themes#what-about-the-kendo-ui-mobile-less-themes) with R1 2022.
