### ISSUE TITLE
MultiSelect Dropdown unresponsive on adding filter: "contains" property

### ISSUE THREAD

**Issue by tanmaykk9** [telerik/kendo-ui-core#5245]
### Bug report

**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our feedback portal](https://www.telerik.com/support/feedback)**

### Reproduction of the problem
_(bug report only)_
I have extended the Dropdown widget to make it Mutliselect dropdown in my application. I am loading the data through a remote dataSource. On adding the property filter: contains in the dropdown. On selecting all the values in the dropdown multiple times the browser becomes unresponsive and then crashes. 

### Current behavior
_(optional)_
On selecting all the values from the dropdown multiple times the browser becomes unresponsive. It happened when added filter: 'contains' property in Dropdown method

### Environment

* **Kendo UI version:** 2018
* **jQuery version:** 3.4.1
* **Browser:** Chrome || Firefox || Safari || Internet Explorer || IE Edge

**Comment by Dimitar-Goshev** [comment]
Closing it due to inactivity.
