### ISSUE TITLE
Empty window.kendo.data 

### ISSUE THREAD

**Issue by szymonworld** [telerik/kendo-ui-core#5249]
### Bug report

I have to update jQuery from 2.1.1 to 3.4.1 and I am getting empty window.kendo.data. It's generate error in knockout-kendo library.

### Expected/desired behavior

It should be works like in 2015.3.1214 build with jquery 2.1.1 which return existing ObservableArray.

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** 3.4.1
* **Browser:** all

**Comment by dmanova** [comment]
Could you give us a runnable sample? 
You may use https://dojo.telerik.com/ and selecting the different Kendo UI versions from the dropdown list "Choose Library". Also could replace the jQuery version in the <head> tag.
