### ISSUE TITLE
Spreadsheet does not alert the user when trying to sort Range with merged cells

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5250]
### Bug report
The Spreadsheet does not alert the user when trying to sort Range with merged cells.

### Reproduction of the problem
* Ren the Filter/Sort Demo: https://demos.telerik.com/kendo-ui/spreadsheet/sorting-filtering
* Merge two cells with data
* Try to sort the range for any column
* Nothing will happen

### Expected/desired behavior
The user should be notified for the reason why the Sort was not performed

### Environment
* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by veselints** [comment]
To workaround the issue apply the following override:
```js
kendo.spreadsheet.Range.fn.isSortable = function() {
    return this.cantSort();
};
```

**Comment by veselints** [comment]
PR here: https://github.com/telerik/kendo/pull/10032

**Comment by Dimitar-Goshev** [comment]
@veselints After the fix the dialog is visible, alerting the user that sorting is not performed.
But if you try to sort the same column again, there are two dialogs now. Every next try to sort the same column adds another dialog.
