### ISSUE TITLE
Using Ctrl + x to cut in the Spreadsheet works only once (IE11)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5251]
### Bug report
Reproducible in IE11.

### Reproduction of the problem
Reproducible in the demos.
1. Select a cell
2. Press Ctrl + x 
3. Paste the content (Ctrl + V)
4. Try cutting another cell's content (Ctrl + x)

### Current behavior
The Copying and pasting dialog pops up and prevents further cutting.

### Expected/desired behavior
Cutting works consistently.

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** [IE11]

**Comment by mishoo** [comment]
Relevant commit: https://github.com/telerik/kendo/commit/24e65d7cb5664d45a6920f36ac600b892c94ee4f
