### ISSUE TITLE
HtmlAttributes method does not add passed class to the Dialog widget instance

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5255]
### Bug report

When initializing a Dialog the specified class within the HtmlAttributes is not added to the instance. 

### Reproduction of the problem

Initialize a Diolog:

```
@(Html.Kendo().Dialog()
    .Name("myDialog")
    .Title("My Dialog")
    .Content("Content")
    .Modal(true)
    .Closable(false)
    .Visible(true)
    .Width(600)
    .HtmlAttributes(new { @class = "myTestClass"})
    .Actions(act =>
    {
        act.Add().Text("Continue").Primary(true);
        act.Add().Text("Cancel Change");
    })
)
```

### Current behavior

The class _myTestClass_ is not added to the Dialog instance

### Expected/desired behavior

The class _myTestClass_ should be added to the Dialog instance

### Environment

* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
[Item in Core Portal](https://feedback.telerik.com/aspnet-core-ui/1443142-dialog-add-htmlattributes) - Make sure to close it manually when this is resolved. The [MVC item](https://feedback.telerik.com/aspnet-mvc/1428390-htmlattributes-method-is-not-assigning-the-class) should be closed automatically.
