### ISSUE TITLE
Edit popup doesn't work with two grids in one page

### ISSUE THREAD

**Issue by MxoSibeko-QuickPic** [telerik/kendo-ui-core#5256]
I have two unrelated grids in one view (asp.net core). the grids work fine until they both use 'Editable(editable => editable.Mode(GridEditMode.PopUp))' .

They both work also when one is using an edit mode that's different to the other.

I need to use PopUp edit for both grids but only one works if i set them both, the other does not render at all. 

How do i fix this ?

**Comment by dmanova** [comment]
I couldn't reproduce the use case you describe. I've modified a demo sample shown at https://demos.telerik.com/aspnet-core/grid/editing-popup. 
I add another grid on the same page (view) and both works. You could find a video here: https://www.screencast.com/t/dJAOlpD8

Could you provide runnable sample and more information on the matter?

**Comment by MxoSibeko-QuickPic** [comment]
I decided to use pop up for one and in-line editing for the other grid
