### ISSUE TITLE
Unable to build a formula in IE when using the Spreadsheet scrollbar

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5259]
### Bug report
When we want to add a formula in a given cell in the **Spreadsheet**, we double-click it and enter the "=" in it as an identifier that a formula definition will follow. If we want to include in the formula a cell that is not inside the visible range of the **Spreadsheet**, we scroll to that cell and select it. In **Internet Explorer**, if we scroll to a given cell using the arrows of the **Spreadsheet**'s scrollbar the "double-clicked" cell becomes just a selected one and the "=" sign is converted to a string value.

### Reproduction of the problem
1. Open [this Dojo example](https://dojo.telerik.com/ekuQuMuS) in **Internet Explorer 11**
2. Select the **A1** cell and enter "=" in it. 
3. Press the "down" direction arrow of the **Spreadsheet** trying to reach cell **A50**. 
4. With the first click on the arrow, the **A1** cell is no more "double-clicked" and the "=" inside it is converted to a string

### Current behavior
When building a formula in a given cell and trying to navigate to a cell using the scrollbar, this usage stops the formula building and converts the "=" into a string. 

### Expected/desired behavior
When a user creates a formula for a given cell, they should be able to navigate through the **Spreadsheet** using its scrollbars. 

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** x.y
* **Browser:** IE 11.950.17134.0

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
