### ISSUE TITLE
Grid resize handle is not positioned correctly

### ISSUE THREAD

**Issue by larshoeppner** [telerik/kendo-ui-core#5261]
### Bug report

A grid with endless scrolling and resizable columns enabled does not position the resize handle correctly when the grid is scrolled to the right.

### Reproduction of the problem

see demo, scroll to right (you will need to make the result pane sufficiently narrow so the scroll bar appears), hover where the resize handle should be, and observe the red rectangle which is the resize handle

https://dojo.telerik.com/@lhoeppner/iMOHAvuP

### Environment

* **Kendo UI version:** 2019.2.619
* **jQuery version:** all
* **Browser:** all

**Comment by dmanova** [comment]
Thank you for your report. This a know issue and it is fixed in [Kendo R3-2019 release.](https://www.telerik.com/support/whats-new/kendo-ui/release-history/kendo-ui-r3-2019)
