### ISSUE TITLE
Edge case for kendo grid

### ISSUE THREAD

**Issue by janjindracek** [telerik/kendo-ui-core#5263]
### Bug report

Hi everyone, I´m sorry if this is the wrong repo or something, but I´d like to report a bug in kendo grid generated by C# asp net core. 

When a grid is loading data from its datasource, the user can still see the loading refresh button. If the user clicks on the button during the loading time, the page breaks thusly:

### Reproduction of the problem
Have the user click on grid reload button during loading (the icon changes a bit too during)

### Current behavior
Chrome: The page displays request response
IE: The page downloads request response

### Expected/desired behavior
Preferably, the button should do absolutely nothing during loading time

### Environment

* **Kendo UI version:** 2019.1.220
* **jQuery version:** 2.14
* **Browser:** [all]

**Comment by dmanova** [comment]
Hello.
I did not manage to reproduce the issue. 
I try to reproduce it on [this demo page](https://demos.telerik.com/aspnet-core/grid/pdf-export) as it looks similar to your grid.
Is it possible for you to provide working example (dojo)?
Or could you share additional information about your configurations?
- datasource type
- other configurations that may affect
