### ISSUE TITLE
Cannot select text inside Splitter pane

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5264]
### Bug report

After upgrade from Kendo UI version v2019.1.220 to 2019.2.619 the text inside Splitter panes cannot be selected. 

### Reproduction of the problem

[Dojo example for unselectable text](https://dojo.telerik.com/@AleksandarEvangelatov/agOWOFuc)
[Dojo example for selectable text](https://dojo.telerik.com/@AleksandarEvangelatov/UriFIDOt/3)

### Current behavior

When using Kendo UI 2019.2.619 the text inside Splitter panes cannot be selected. 

### Expected/desired behavior

Text inside Splitter panes should be selectable.

### Environment

* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by PreslavKozovski** [comment]
related to: https://github.com/telerik/kendo-themes/issues/721

**Comment by PreslavKozovski** [comment]
The issue is fixed in our Master branch. The fix will be out with our R3 release.
