### ISSUE TITLE
Editor adds an empty paragraph on pasting text in nested table

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5272]
### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/oheLAzId)example. 
1. Copy a word
2. Click in the Editor after "Location" or "Date" 
3. Press Enter
4. Press Ctrl + V to pasted the copied text.

### Current behavior
The Editor adds an extra <p> element after the nested table:

```
<p>&nbsp;</p>
```

### Expected/desired behavior
No empty paragraph is added on pasting content.

### Environment

* **Kendo UI version:** 2019.3.917
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by IvanDanchev** [comment]
Issue re-opened due to a newly discovered scenario causing the same problematic behavior: [https://dojo.telerik.com/eRUdugew/2](https://dojo.telerik.com/eRUdugew/2) 

1. Focus a cell with an image in it. 
2. Click on the custom button in the Toolbar.

The paste method is executed and a unwanted empty paragraph is added after the first table.

**Comment by Juveniel** [comment]
@IvanDanchev when content is pasted in a table through the paste() methdo, the Editor ensures that the content below the table is selectable by inserting an empty paragraph immediately after the table. There are some exceptions where the paragraph is not being inserted - when the focused table is nested in another table and when the last sibling is not the focused table.

Taking the above into consideration, in the referred Dojo both tables are placed in different DOM elements, thus the Editor is not able to determine if the empty papragraph should be added or not:

Curent:
```
<div>
  <table></table>
</div>
<div>
   <table></table>
</div>
```
Instead, if we do not want the paragraph to be added, the recommended approach is for the tables to be placed in the same DOM element:
```
<div>
  <table></table>
  <table></table>
</div>
```

Closing the issue.
