### ISSUE TITLE
Scheduler moveStart event does not trigger on mobile devices

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5274]
### Bug report
Regression introduced in R2 2018.

### Reproduction of the problem
The mobile mode of the Scheduler must be turned off. 
Reproducible in the [demos](https://demos.telerik.com/kendo-ui/scheduler/events). 
1. Tap, hold and try to move an event

### Current behavior
The moveStart event does not fire and the event cannot be moved. 

### Expected/desired behavior
The moveStart event fires and the event can be moved.

### Environment

* **Kendo UI version:** 2019.3.917
* **jQuery version:** x.y
* **Browser:** [Android]

**Comment by Juveniel** [comment]
The issue with dragging events on mobile devices is related to the incorrect behavior of the holdToDrag option of the Draggable introduced with #2633 . The related fix is reverted in order to ensure the correct work of the Draggable, which is also used in the Scheduler.
