### ISSUE TITLE
Mobile ListView it does not scroll in  iOS13

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#5276]
### Bug report

Mobile ListView it does not scroll in  iOS13

### Reproduction of the problem
https://demos.telerik.com/kendo-ui/m/index
### Current behavior
the page can't be scrolled

### Expected/desired behavior
scroll shoulkd be possible

### Environment

* **Kendo UI version:2019.3.917
* **Browser:** [ iOS13 ]

**Comment by tiltsoftware** [comment]
I am experiencing this issue in a Cordova app. It actually scrolls ok when using UIWebview in Cordova but not when using WKWebview.

Unfortunately UIWebview has some other issues and is being depricated so that's not a good fix for us.

Thought this info might be useful in some way for trouble shooting

**Comment by johansec** [comment]
Are there any updates as to a fix for this yet?

**Comment by dbb95393** [comment]
I am experiencing this as well with many of our Kendo grids.  Has anyone found a potential workaround to get this working on IOS 13?

**Comment by boyandim** [comment]
Indeed there is a workaround shown in the following [https://dojo.telerik.com/UfoQiluV](https://dojo.telerik.com/UfoQiluV) example.

**Comment by johansec** [comment]
When I try to run this Dojo example in full screen on my iPhone X with iOS 13.1 it does not scroll either.
:(

**Comment by johansec** [comment]
Adding this bit of script resolved the issue for us.

<script>
    if(kendo.support.browser.safari) {
        kendo.support.pointers = false;
    }
</script>

**Comment by dmanova** [comment]
Fixed and verified internally with iPhone iOS 13.1 and 13.2 in Safari, Chrome and Firefox browsers.
