### ISSUE TITLE
Mobile Application with nativeScrolling does not scroll on device with iOS 13.1

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#5289]
### Reproduction of the problem
Open [this Dojo example](http://dojo.telerik.com/aXUtIFus/5) on a device using iOS 13.1, or in the Google Chrome Emulator. Try to scroll through the div. Reproduced when native scrolling is enabled. 

### Current behavior
Scrolling does not work when you try to scroll the div.

### Expected/desired behavior
Scrolling through the div should work.

### Environment

* **Kendo UI version:** 2019.3.917

* **Browser:** [all] iOS 13.1

**Comment by martintabakov** [comment]
Please review ticket #1431385. The client's developer team has done some research and provided information which might prove useful.

**Comment by djamirooo** [comment]
would you please leave a link for the ticket?

**Comment by dmanova** [comment]
Fixed and verified internally with iPhone iOS 13.1 and 13.2 in Safari, Chrome and Firefox browsers.
