### ISSUE TITLE
TreeList rows lose CSS class assigned in dataBound after incell editing

### ISSUE THREAD

**Issue by GaloisGirl** [telerik/kendo-ui-core#5294]
### Bug report
TreeList rows lose CSS class assigned in dataBound after incell editing

### Reproduction of the problem
1. Open dojo at https://dojo.telerik.com/@GaloisGirl/IQaROyEZ
2. Notice how in the dataBound hadler, each tr gets assigned the self-descriptive "italic" CSS class (and an AliceBlue background)
3. Edit any item and exit edition

### Current behavior
After editing, some rows have lost the "italic" CSS class. However, the background style set via CSS remains. 
The bug doesn't occur in Grid, nor in TreeList with inline edit mode, as you can easily check by slightly modifying the linked dojo.

### Expected/desired behavior
After editing, the CSS class I assigned to the tr element in the dataBound hadler should be kept. 
The dataBound event is an important mechanism in customizing TreeList appearance and behaviour, many solutions in the Telerik forums point to it as the place to implement custom features.

### Environment

* **Kendo UI version:** 2019.3.917
* **jQuery version:** 1.12.4
* **Browser:** all

**Comment by ag-petrov** [comment]
This is not a bug, the classes are not included into the internal collection of stylings that are to be applied. The row gets re-rendered and looses the classes.
