### ISSUE TITLE
ComboBox select event data contains info about a previously selected item 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5295]
### Bug report
ComboBox and MultiColumnComboBox

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/uqeyoHUX/2) example. Open the browser console and follow the steps below:

1. Select an item
2. The "select" event fires and, as expected, **e.item** and **e.dataItem** contain info about the selected item.
3. Press Backspace key to delete a character from the text in the input
4. Blur the widget
5. "select" fires: e.item and e.dataItem do not return data (expected)
6. Focus the widget and delete another character.
7. Blur the widget

### Current behavior
After 7. e.item and e.dataItem contain data about an old selection - the item selected in 1.

### Expected/desired behavior
e.item and e.dataItem should not contain data, because a custom value is set in the ComboBox and no item in the dataSource is selected. 

### Environment

* **Kendo UI version:** 2019.3.917
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by IvanDanchev** [comment]
Another similar scenario, in which e.dataItem returns data unexpectedly is:
1. Focus the component
2. Type in text that will return some matches (e.g., "i")
3. Blur the component. 

The data of the first suggested matching item will be returned in the event data.

**Comment by IvanDanchev** [comment]
Priority raised: Ticket ID: 1507178

**Comment by ag-petrov** [comment]
Seems to not reproduce anymore.
