### ISSUE TITLE
Broken URL for the AeroViewr Demo

### ISSUE THREAD

**Issue by dday9** [telerik/kendo-ui-core#5296]
### Reproduction of the problem
The URL for the AeroViewr Demo located on the [Build Single-Page app with Kendo UI Web Framework | Kendo UI Demos](https://demos.telerik.com/kendo-ui/spa/index) is broken.

### Current behavior

1. Go to the URL above.
2. Click on the Launch AeroViewr button
3. You are then redirected to https://demos.telerik.com/kendo-ui/

### Expected/desired behavior
This should presumably bring you to a demo SPA website like [Sushi](https://demos.telerik.com/kendo-ui/websushi/)

### Environment
* **Browser:** all

**Comment by dmanova** [comment]
Thank you for bringing our attention to this. It seems the application is unavailable due to the deprectaion of the 500px API. Please use the Sushi SPA demo instead.

**Comment by dday9** [comment]
I'm going to close this since the AeroViewr section has since been removed from the website.
