### ISSUE TITLE
QRCode appears squashed when drawn as canvas

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5298]
### Reproduction of the problem
Run this dojo - https://dojo.telerik.com/ikoYUCuy

### Current behavior
QR code is squashed

### Expected/desired behavior
QR code should be square

### Environment

* **Kendo UI version:** 2019.3.917
* **Browser:** [all]

**Comment by VicTachev** [comment]
Workaround:
[https://dojo.telerik.com/uFivIMab](https://dojo.telerik.com/uFivIMab)

**Comment by dmanova** [comment]
Also the default size according to [documentation](https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/qrcode/configuration/size) should be 200px.
