### ISSUE TITLE
Databound Spreadsheet loses data on inserting a header row

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5301]
### Bug report
Following the KB [Create Header and Footer Rows for a Spreadsheet with DataSource](https://docs.telerik.com/kendo-ui/knowledge-base/spreadsheet-with-datasource-insert-header-and-footer) results in data loss on creating the custom header row. Upon inserting a row the data in cell A1 is removed.

### Reproduction of the problem
Open [this Dojo](https://dojo.telerik.com/@AleksandarEvangelatov/AsEhANeK) and run it.

### Current behavior
Spreadsheet DataSource is loaded correctly, but after the 2 sec timeout on inserting a new row, the data in cell A1 (A2 after row insertion) is removed.

### Expected/desired behavior
New row should be inserted without data loss in cell A1.

### Environment
* **Kendo UI version:** 2019.3.917
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
In R3 2019 SP1 this issue will be resolved with the introduction of a second parameter to the insertRow method:

#### skipDataSourceInsert `Boolean` *optional*
If passed `true`, the method does not delete item from the DataSource.

Thus, in databound scenarios when inserting rows outside the databound rows, insertRow()'s parameter skipDataSourceInsert should be set to true to avoid the issue from the KB.
`sheet.insertRow(0, true); // the second parameter skips the update of the dataSource`

We will update the documentation and KB article once R3 2019 SP1 is released.
