### ISSUE TITLE
Spreadsheet cannot be scrolled in iOS 13

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#5303]
### Bug report

Spreadsheet cannot be scrolled in iOS 13

### Reproduction of the problem

The issue can be reproduced with [the Basic Usage Demo](https://demos.telerik.com/kendo-ui/spreadsheet/index).

### Current behavior

Spreadsheet cannot be scrolled.

### Expected/desired behavior

Spreadsheet should be scrollable.

### Environment

* **Kendo UI version:** 2019.3.917
* **Browser:** [iOS]

**Comment by mishoo** [comment]
Please use branch [`spreadsheet-ios`](https://github.com/telerik/kendo/tree/spreadsheet-ios) for testing.

**Comment by Dimitar-Goshev** [comment]
@mishoo The fix results in inability to scroll Spreadsheet content in Android and Surface.

**Comment by Dimitar-Goshev** [comment]
@mishoo Selecting and scrolling does not work in Safari in Desktop mode on iOS 13 iPad - the first commit does not resolve the issue.
The fix results in inability to scroll Spreadsheet content in Android and Surface. And I am afraid that the second commit does not resolve scrolling as well.

**Comment by mobitar** [comment]
Any idea when this will be merged in?

**Comment by mishoo** [comment]
It's merged to master.

**Comment by mobitar** [comment]
Do you know when a new release will be created with this? The last release is "2020.2.617".

**Comment by Dimitar-Goshev** [comment]
R3 2020 is expected in mid September.
