### ISSUE TITLE
Grid scroll position jumps when navigating to edited cell in RTL

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5309]
### Reproduction of the problem
1. Run this dojo - [https://dojo.telerik.com/EVIrEGuS/2](https://dojo.telerik.com/EVIrEGuS/2)
1. Change the value in one of the cells.
1. Press Enter
1. Focus another cell using the arrow keys 
1. Focus the edited cell using the arrow keys

### Current behavior
The scroll position jumps left and the focused cell is outside the viewport

### Expected/desired behavior
The scrolling should not move 

### Environment

* **Kendo UI version:** 2019.3.917
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by ahmedqasid** [comment]
Would please provide an expected date for this bug?
It's very annoying and our customers are complaining a lot about it
It's making the grid almost unusable in RTL mode.

**Comment by dmanova** [comment]
Similar behavior is observed also in the Treelist.
