### ISSUE TITLE
Multiple unexpected k-overlay div elements added to Window with iframe true

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#5311]
### Bug report
Multiple unexpected k-overlay div elements added to iframe Windows on the background on using [toFront()](https://docs.telerik.com/kendo-ui/api/javascript/ui/window/methods/tofront) method of another Window or clicking on Window title bar. As a result, multiple unexpected and unnecessary elements are added to Windows on the background.

Ticket ID: 1431891

### Reproduction of the problem - toFront method
1. Run the following [Dojo snippet](https://dojo.telerik.com/AJAMARom)
1. Inspect the div with id="window1" by using the dev tools picker for elements to avoid clicking with right mouse button on a window.
The div has 1 iframe child element followed by 1 element `<div class="k-overlay"</div>`
![image](https://user-images.githubusercontent.com/6614183/66186067-f2355400-e689-11e9-8da6-8507fda322d7.png)

1. Click on "Bring Window 2 to front." button 3 times, which calls toFront() method of Window 2.

### Current behavior
Element `<div class="k-overlay"</div>` is added to id="window1" div on each call of toFront().
Now there are total of 4 divs:
![image](https://user-images.githubusercontent.com/6614183/66186222-65d76100-e68a-11e9-8039-774a1215e4c2.png)

### Expected/desired behavior
The window with id="window1" has only 1 element `<div class="k-overlay"</div>`

### Reproduction of the problem - clicking on Window title bar
1. Run the following [Dojo snippet](https://dojo.telerik.com/AJAMARom)
1. Inspect the div with id="window1" by using the dev tools picker for elements to avoid clicking with right mouse button on a window.
The div has 1 iframe child element followed by 1 element `<div class="k-overlay"</div>`
![image](https://user-images.githubusercontent.com/6614183/66186067-f2355400-e689-11e9-8da6-8507fda322d7.png)

1. Click on Window 2 title bar.

### Current behavior
Each click on Window 2 title bar adds 2 `<div class="k-overlay"</div>` elements to id="window1" 
Now there are total of 3 divs.

### Expected/desired behavior
The window with id="window1" has only 1 element `<div class="k-overlay"</div>`

### Environment
* **Kendo UI version:** 2020.2.513
* **Browser:** all

**Comment by M-Rostock** [comment]
What is the status of this issue?

**Comment by Dimitar-Goshev** [comment]
@M-Rostock The issue is reproducible with our latest version 2020.2.513 as well. I updated its priority label as you are experiencing it as well. Keep track on this issue's status to be informed about its progress.
