### ISSUE TITLE
Mobile App with skin: Office 365 flickers when changing views

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#5312]
### Bug report
The header and footer in a Mobile App using office365 skin flickers when changing views.
### Reproduction of the problem
Open this [Dojo example.](https://dojo.telerik.com/@Dimitar-Goshev/AtAMegop) Switch through the views from the footer.

### Current behavior
The header and footer clicker after navigating through the views

### Expected/desired behavior
The header and footer should not flicker.

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** [all]

**Comment by magdalenaan** [comment]
The Kendo UI Mobile LESS themes are [officially deprecated](https://www.telerik.com/blogs/future-plans-telerik-kendo-ui-less-themes#what-about-the-kendo-ui-mobile-less-themes) with R1 2022.
