### ISSUE TITLE
Grouping Spreadsheet toolbar buttons breaks functionality

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5315]
### Bug report
Upon grouping of buttons in Spreadsheet toolbar the buttons stop working as expected. For example, grouping BackgroundColor and TextColor buttons breaks their functionality.

### Reproduction of the problem
Open this [dojo](https://dojo.telerik.com/@Dimitar-Goshev/UZopOkAR)
Widget is initialized with BackgroundColor and TextColor buttons as a group.

### Current behavior
Click on BackgroundColor and TextColor buttons - drop downs are not shown and color cannot be changed.

### Expected/desired behavior
Clicking on BackgroundColor and TextColor buttons should show drop downs and allow for color to be changed, like in this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/uKomEquk).

### Environment
* **Kendo UI version:** 2022.3.913
* **Browser:** [all]

**Comment by veselints** [comment]
Background and Text color tools of the Spreadsheet Toolbar are not Buttons. Those are PopupTools. As such, they could not be placed within a ButtonGroup that may contain only Buttons.
