### ISSUE TITLE
Missing properties in DropDownTreeItem TagHelper

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#5316]
### Bug
There are properties of the DropDownTreeItemModel (used for DropDownTree with HTML Helpers), which are missing in the DropDownTreeItemBase and then in DropDownTreeItemTagHelper (used with TagHelpers).

As a side note, DropDownTreeItemBase has IconClass and ContentUrl which are used nowhere and seem unnecessary.

### Current behavior
- TagHelper dropdowntree-item properties:
checked=""
enabled=""
expanded=""
id=""
image-url=""
selected=""
sprite-css-class=""
text=""
url=""
value=""

- HtmlHelper DropDownTreeItem properties:
.Checked()
.Enabled()
**.Encoded()**
.Expanded()
**.HasChildren()**
**.HtmlAttributes()**
.Id()
**.ImageHtmlAttributes()**
.ImageUrl()
**.LinkHtmlAttributes()**
 .Selected()
.SpriteCssClasses()
.Text()
.Url()
.Value()

### Expected/desired behavior
TagHelper should also have Encoded, HasChildren, HtmlAttributes, ImageHtmlAttributes and LinkHtmlAttributes properties

### Environment
- **Kendo UI:** 2019.3.1023

**Comment by zdravkov** [comment]
Added .Encoded, .HasChildren and .HtmlAttributes - the other ones are inherited and are not used by the TreeView node.
