### ISSUE TITLE
MultiSelect with virtualization enabled and mapValueTo: "dataItem" option set returns incorrect item

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5317]
### Bug report

When data for the MultiSelect widget is virtualized and mapValueTo: "dataItem" option is set, the widget returns incorrect dataItem on subsequent selection.

### Reproduction of the problem

[DataVirtualization.zip](https://github.com/telerik/kendo-ui-core/files/3697723/DataVirtualization.zip)

1. Select Order 3 and submit selection. Alert displays the selected Id 3
2. Clear selection and submit. Alert displays no data.
3. Select Order 131313 and submit selection. Alert displays the selected Id 131313 
4. Clear selection and submit. Alert displays no data.
5. Select Order 24242 and submit selection. Alert displays the selected Id 131313

### Current behavior

[Screencast](https://www.screencast.com/t/dNwY5Hmh3Cf0)

### Expected/desired behavior

The result to be the same as if mapValueTo: "index" is used.

### Environment

* **Kendo UI version:** 2019.3.1023
* **Browser:** [all]

**Comment by madd0** [comment]
I'm experiencing this bug too in version 2019.3.1023.
I applied the workaround suggested in #4279. Is this the only solution available at the moment? Is this bug scheduled to be fixed?

**Comment by nelito987** [comment]
The issue is also reproducible in AngularJS scenario -[https://dojo.telerik.com/@NeliKondova/osorUxIy]( https://dojo.telerik.com/@NeliKondova/osorUxIy)
Reported in ticket #1478261

**Comment by Iankodj** [comment]
Related to: https://github.com/telerik/kendo-ui-core/issues/4279
