### ISSUE TITLE
Separator is not added before a SplitButton in Spreadsheet toolbar

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5318]
### Bug report

When adding a SplitButton to Spreadsheet toolbar a Separator is not added before the button, like for the other type of buttons.

### Reproduction of the problem

Run the following [dojo]https://dojo.telerik.com/@AleksandarEvangelatov/aLEsaLEW)

### Current behavior
A Separator is not added before the SplitButton

### Expected/desired behavior
A Separator should be added before the SplitButton, like for the other buttons

### Environment

* **Kendo UI version:** 2019.3.917
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible with 2022.2.510 - https://dojo.telerik.com/@Dimitar-Goshev/oTUGocED
