### ISSUE TITLE
"change" event is triggered twice

### ISSUE THREAD

**Issue by mishoo** [telerik/kendo-ui-core#532]
When you manually edit an input element (DatePicker, NumericTextBox, AutoComplete) and press ENTER, a "change" event will be triggered twice on the DOM element.

http://dojo.telerik.com/@mishoo/EDAji/2

**Comment by ggkrustev** [comment]
This is logged in the private repository under the#2741 issue. It is still under consideration, as it will require to detect whether the value will be triggered by the Html element and whether it won't.

I will forward the issue for further internal discussions.

**Comment by bhaidar** [comment]
Any updates on the above? I am facing same problem. If I change value of an input "k-textbox" the event is fired twice in the MVVM viewmodel. Thanks
