### ISSUE TITLE
Missing bottom and vertical borders of MultiColumnComboBox rows with background color for alternate/selected/focused rows in LESS themes in Firefox

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5323]
### Bug report
MultiColumnComboBox is missing bottom and vertical borders for its alternate rows. That applies to all LESS themes and in Firefox

### Reproduction of the problem
Run [the MultiColumnComboBox Index demo](https://demos.telerik.com/kendo-ui/multicolumncombobox/index) in Firefox. Make sure one of the LESS themes is selected.

### Current behavior
![Missing borders in FF](https://user-images.githubusercontent.com/6614183/66474771-a5db8100-ea9a-11e9-8131-ac8ceba0429c.png)

### Expected/desired behavior
Borders should be properly rendered as in Chrome:
![Borders in Chrome](https://user-images.githubusercontent.com/6614183/66474873-d4f1f280-ea9a-11e9-80a2-b94e9dad0b3d.png)

### Environment
* **Kendo UI version:** 2019.3.917
* **Browser:** [Firefox 69.0.2]

**Comment by magdalenaan** [comment]
The issue is caused by Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=688556
