### ISSUE TITLE
DatePicker is cut off at the bottom if font-size is set to 11px or 13px in Chrome

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-ui-core#5324]
### Bug report

The DatePicker is cut off at the bottom if the font-size is 11 or 13px in Chrome

![40e875bd-2954-4926-89c1-2e59b2c900ca_capture40e875bd2954492689c12e59b2c900ca](https://user-images.githubusercontent.com/45764088/66548349-c878a300-eb49-11e9-816f-8a03ff021bb4.jpg)

### Reproduction of the problem

[https://dojo.telerik.com/aLuvEtIp](https://dojo.telerik.com/aLuvEtIp)

### Expected/desired behavior
The Calendar should not be cut

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** Chrome

**Comment by magdalenaan** [comment]
The issue cannot be not reproduced.
