### ISSUE TITLE
Pinch zoom over a Chart does not work on iOS 13

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#5326]
### Bug report

The default pinch zoom in or zoom out can not be performed on a iOS mobile device with the latest iOS version(13).  Ticket - # 1433562

### Reproduction of the problem
Open the official demos of the chart on a mobile device and try to pinch zoom in.

### Current behavior
Zoom in and zoom out do not work
### Expected/desired behavior
Zoom in and zoom out should work.

**Comment by sspasova** [comment]
I am closing this because it cannot be reproduced using Kendo UI 2023.3.1114. Tested with iOS/Safari 17.2.1.
