### ISSUE TITLE
Whitespace causes Editable binder to miss input

### ISSUE THREAD

**Issue by jquense** [telerik/kendo-ui-core#533]
Hey ya'll,

There is a fairly brutal gotcha in the Editable code, that causes really annoying side effects.

[this line here](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.editable.js#L217): attempts to locate the input mapped to the value that just changed in order to validate it and prevent `set()` from continuing if the field is invalid. The issue is that the filter catches this:

`data-bind="value:MyField"` 

but does **not** catch

 `data-bind="value: MyField"`. 

Note the whitespace between `value:` and `MyField`. The whitespace doesn't affect the actual binding, but since the Editable fails to locate the input, the value is set on the model, valid or not.

**Comment by KirilNN** [comment]
Hi @jquense.

Thanks for reporting this. In order for this issue to be fixed a lot of checks need to be implemented that can cause noticeable delay in the widget. This is why we consider this approach as unsupported, and we have added clarification in the corresponding [documentation article](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-columns.editor)

**Comment by jquense** [comment]
that's a reasonable answer thank you @KirilNN, but right now its doesn't even error. It just fails really subtly and in difficult to debug ways. Since the actual binding works just fine with whitespace the issue is just the Editable. 

The development ergonomics are really bad here and a not-so-clear sort of warning on the doc page is not particularly helpful. especially since I would have never seen that b/c my bindings weren't failing so why would I check there? This expressed itself as a grid row not resetting the value on hitting ESC, there were no other signs that something was wrong.

I could be missing some of the nuance or complexity here but It seems like a sufficient check would definitely be performant compared to what it is now. We are talking about updates in Editables, where there are at most 10's of fields to look through? You are already doing a query, I don't think the added filter would add that much overhead but i completely admit that i have not tested it.

```js
var rField = new RegExp("value: *" + fieldName + "|checked: *" + fieldName,"g");

input = $(':input[data-bind*="value:"],:input[data-bind*="checked:"]', that.element).filter(function(){
  return this.getAttribute('data-bind').match(rField)
})
```

**Comment by KirilNN** [comment]
Hi @jquense,

The regex match is a viable solution, however when you have a lot of editors in the editor template it will be a significant performance hit. And we consider the scenario with a lot of editors in the editor template to be more common that having a space in the value binding. And this is why we are withholding ourselves from implementing such check.

**Comment by jquense** [comment]
I can understand the concern for performance, but it seems a bit misguided here, this is code that runs in response user input, there is no need for it to need tens of thousand ops/sec. (a quick js perf is still above 6000 ops/sec compared to the original 10,000 still well above a human even noticing).

 In the current behavior passes the grid cell to the validator which is clearly not correct. if no input is found it should not try to run a validation check. 

The fact that I had to step through source code for an hour trying to track this down, b/c I missed an unclear ("whitespace sensitive", instead of an example?) documentation note should be an indication of poor...something. In any case thanks for listening, I realize it can be difficult to balance perf with user experience. In the future it would be nice to see builds with optional debug messages to help catch this.
