### ISSUE TITLE
DropDownTree closes and forces page to scroll down upon opening on Mac

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#5334]
### Bug report
On Mac Device with Safari v.13.0.2, the DropDownTree forces the page to scroll and then closes. The page must have vertical scrollbar. 

### Reproduction of the problem

Open [this Dojo](https://runner.telerik.io/fullscreen/uwoBEKiT/2) example on Mac with Safari v.13.0.2. Shrink the browser window so that a vertical scroll appears and the popup would appear above the input field. Try to open the DropDownTree. 

A video demonstrating the issue can be found on [this link.](https://app.crossbrowsertesting.com/public/ibf89f93472d4fae/livetests/29940489/bfb80309)

### Current behavior
The DropDownTree scrolls down the page as if there is not enough space for it to open. The popup then closes.

### Expected/desired behavior
The DropDownTree popup should appear above the input field and there should be no scrolling.
### Environment

* **Kendo UI version:** 2019.3.917
* **Browser:** [Safari 13.0.2] 
* **MacOS:** 10.13 High Sierra

**Comment by clevrdavid** [comment]
I also have come across this issue. I have tried adapting a workaround for the DropDownList but so far have not found a solution. 

`var widget = $("#GroupTree").data("kendoDropDownTree");

        widget.tree.parent().on("wheel", function (e) {

            var container = this;

            if ((container.scrollTop == 0 && e.originalEvent.deltaY < 0) ||
                (container.scrollTop == container.scrollHeight - container.offsetHeight &&
                    e.originalEvent.deltaY > 0)) {

                e.preventDefault();

                e.stopPropagation();
            }

        });`

**Comment by Iankodj** [comment]
Not reproducible with latest version: https://dojo.telerik.com/uwoBEKiT/6
