### ISSUE TITLE
MultiSelect selected tags cannot be removed in Safari with iOS 13

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#5342]
### Bug report
Selected tags in MultiSelect cannot be removed in Safari on device with iOS 13.

### Reproduction of the problem
Open the [MultiSelect Basic Usage Demo](https://demos.telerik.com/kendo-ui/multiselect/index) in Safari on iPad with iOS 13. Try to remove one of the two selected tags.
### Current behavior
The tag is not removed upon pressing X.

### Expected/desired behavior
The tag should be removed from the input field when X is pressed.

### Environment

* **Kendo UI version:** 2019.3.917
* **Browser:** [Safari] 
* **iOS:** 13.1.2

**Comment by Dimitar-Goshev** [comment]
After the fix tags can be deleted in iOS 13.
But in Android Chrome deleting a tag through the X button of the tag expands the dropdown.

**Comment by Dimitar-Goshev** [comment]
The issue is fixed.
