### ISSUE TITLE
Incorrect Window height in percentage is set through options with sass-based themes

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#5343]
### Bug report

With the sass-based themes, the height of the window is calculated incorrect by also taking into consideration the top padding.

### Reproduction of the problem

[https://dojo.telerik.com/EDOhEMoj/8](https://dojo.telerik.com/EDOhEMoj/8)

### Current behavior

Incorrect height calculated for the wrapper of the Window. 

### Expected/desired behavior

Height of the Window should be set to 20%.

### Environment

* **Kendo UI version:** 2019.3.917
* **Browser:** [all]

**Comment by martintabakov** [comment]
Also reported in thread #1446476.

**Comment by PreslavKozovski** [comment]
Also reported in 1498117

**Comment by mparvanov** [comment]
Windows tools become aligned incorrectly with less themes:
https://www.screencast.com/t/j84L9Cf7rIrg
