### ISSUE TITLE
Scheduler with multiple grouped resources and CurrentTimeMarker becomes unresponsive

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5346]
### Bug report
If the CurrentTimeMarker is enabled (it is by default), the resources are grouped, and events with different resource values (about 70) are loaded for the current day, a significant performance deterioration is observed. 
With the CurrentTimeMaker disabled or the events loaded for a date different than today (past or future) the performance issue is not exhibited. 

### Reproduction of the problem
[MVCSchedulerCurrentTimeMarker.zip](https://github.com/telerik/kendo-ui-core/files/3752895/MVCSchedulerCurrentTimeMarker.zip)

1. Run the attached sample project. 

### Current behavior
No exceptions are thrown, but the Scheduler becomes unresponsive. 

### Expected/desired behavior
There should be no performance hit, regardless of CurrentTimeMarker being enabled/disabled.

### Environment

* **Kendo UI version:** 2019.3.917
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Iankodj** [comment]
Although, the major performance issue is now fixed. With so many vertically positioned groups it is recommended to have a greater update interval: https://docs.telerik.com/kendo-ui/api/javascript/ui/scheduler/configuration/currenttimemarker#currenttimemarkerupdateinterval.

**Comment by Dimitar-Goshev** [comment]
Having current time markers for 70 vertical groups is now optimized, but sill having so many markers, calculating and updating their position slows down performance. Further optimization would require changing the current time marker implementation.
