### ISSUE TITLE
Pager displays drop down when AlwaysVisible is set to false in MVC

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#5350]
### Bug report

Pager displays drop down when AlwaysVisible is set to false even when there is enough space to render the buttons (more than 1024px) in MVC.

### Reproduction of the problem
Issue can be reproduced in the following demo:
https://demos.telerik.com/aspnet-mvc/grid/pager-visibility

### Current behavior
Pager displays a drop down.

### Expected/desired behavior
Pager should display the buttons

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by msereda** [comment]
Hi - Any chance of getting this item bumped up the priority list?  Toggling 'alwaysvisible' on or off did not work, the only workaround we've been able to find has been to turn off 'Responsive' for the grid pager, so we're stuck with either annoying our desktop users (responsive on), or annoying our mobile users (responsive off).

**Comment by NikoPenev21** [comment]
Reported also in 1475294
