### ISSUE TITLE
Expose the method Data(string handler) for Telerik UI for ASP.NET MVC version for the Editor ImageBrowser

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5352]
### Bug report

Telerik UI for ASP.NET MVC version for the Editor's ImageBrowser CRUD methods does not support the method Data(string handler) in order to send additional parameters. This is supported for Kendo UI for JQuery:
[https://docs.telerik.com/kendo-ui/api/javascript/ui/editor/configuration/imagebrowser](https://docs.telerik.com/kendo-ui/api/javascript/ui/editor/configuration/imagebrowser)

### Reproduction of the problem
Currently, it is not possible to pass additional data when using the Telerik UI for ASP.NET MVC HTML helpers.

### Current behavior
It is not possible to pass additional data when using the Telerik UI for ASP.NET MVC HTML helpers.

### Expected/desired behavior
It should be possible to pass additional data when using the Telerik UI for ASP.NET MVC HTML helpers.

### Environment

* **Kendo UI version:** 2019.3.917
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
Also mentioned in thread #1458305

**Comment by Iankodj** [comment]
Also mentioned in thread #1510452
