### ISSUE TITLE
Tapping outside the Grid does not close edited cell in Safari on iOS

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5363]
### Reproduction of the problem
1. Run this dojo - https://runner.telerik.io/fullscreen/ALAYibEl/18
1. open in Safari on iOS or in Chrome device simulation mode
1. edit a cell in the Grid
1. tap/click outside the Grid

### Current behavior
The cell is not closed.
Video - https://www.screencast.com/t/M4ItFjSurju

### Expected/desired behavior
The cell should close and the value should be changed

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.12.3
* **Browser:** [iOS XX Safari]

**Comment by ag-petrov** [comment]
There seems to be a problem only in the dojo. With the latest version with the same grid configuration all works as expected. The client that reported the problem initially also stated that after upgrading things started working. Ticket ID - 1435572
