### ISSUE TITLE
When the text of a Drawer item contains multiple words the Drawer content is not displayed

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5369]
### Bug report

When the text of a drawer item contains multiple words, the `hidden` class is not removed.

### Reproduction of the problem
 * Open and run [this dojo](https://dojo.telerik.com/@AleksandarEvangelatov/EZUDecic/2)
 * Notice the second item text is "My Notifications".
 * Click on the second item
 * Drawer content is not displayed

### Current behavior
On click of an item with multiple words, the drawer content is not displayed

### Expected/desired behavior
On click of an item with multiple words, the drawer content should be displayed. 
A possible solution could be the removal of spaces:
`e.sender.drawerContainer.find("#drawer-content").find("#" + e.item.find(".k-item-text").text().replace(" ","")).removeClass("hidden");`

### Environment

* **Kendo UI version:** 2019.3.1023
* **Browser:** [all]

**Comment by boyandim** [comment]
The problem is rather related to the custom logic for finding and accessing a DOM element with specific id based on the text of clicked item. The provided solution solves the problem and will be helpful for anyone who faces the same problem.
