### ISSUE TITLE
Widget does not remove tags when "X" is pressed in mobile devices

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#537]
### Description
Currently, widget does not allow to delete tags on "X" button touch.

Reported in TicketID: 903585, 854232

**Comment by ggkrustev** [comment]
After further investigation, we found out that the problem with the tags deletion is related to the size of the delete icon ("x") and not to the current widget implementation.

We will further investigate the case, but for now we cannot modify the rendering in order to make the deletion easier.

**Comment by yordanov** [comment]
We should add an html element around the icon to make the action area larger covering the whole visual area of the token.

From:

```html
<li class="k-button" unselectable="on">
    <span unselectable="on">Anne King</span>
    <span unselectable="on" class="k-icon k-delete">delete</span>
</li>
```
to:

```html
<li class="k-button" unselectable="on">
    <span unselectable="on">Anne King</span>
    <span unselectable="on" class="k-select" > <!-- or something like that -->
        <span class="k-icon k-delete">delete</span>
    </span>
</li>
```
