### ISSUE TITLE
(HighContrast theme)DropDownTree has background color applied in its rounded corners  

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5372]
### Bug report

The DropDownTree in Highcontrast theme has border-radius applied but behind each of its corners there is a background color applied 

### Reproduction of the problem
1. Open [this Dojo project](https://dojo.telerik.com/ELacAviX) and run it
2. See the corners around the DropDownTree component

### Current behavior
There is a dark background applied behind the rounded corners of the DropDownTree
![image](https://user-images.githubusercontent.com/41293735/67872245-60125580-fb3a-11e9-9cb5-df06e1042f8e.png)

### Expected/desired behavior
The background behind the rounded corners of the DropDownTree should be transparent

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by magdalenaan** [comment]
The issue is not reproducible with the 2022.3.913v.

**Comment by Dimitar-Goshev** [comment]
https://dojo.telerik.com/@Dimitar-Goshev/EyABuFIZ
