### ISSUE TITLE
TreeList expand/collapse not working when browser is in Desktop mode iOS13

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#5377]
### Bug report

Ticket ID 1435806.

### Reproduction of the problem

Reproducible in the [official demos](https://demos.telerik.com/kendo-ui/treelist/remote-data-binding) on iPhone and iPad when using the site in Desktop mode.

### Current behavior

It is not possible to expand/collapse the nodes in Desktop mode.

### Expected/desired behavior

The nodes should expand/collapse in Desktop mode.

### Environment

* **Kendo UI version:** 2019.3.1023
* **Browser:** [ Mobile Chrome | iOS 13.2.2 Safari ]

**Comment by dmanova** [comment]
Raising priority because of Ticket ID1445532

**Comment by dmanova** [comment]
A possible workaround is to use treeList methods [collapse ](https://docs.telerik.com/kendo-ui/api/javascript/ui/treelist/methods/collapse) and [expand  ](https://docs.telerik.com/kendo-ui/api/javascript/ui/treelist/methods/expand)as shown in this DoJo sample:
https://dojo.telerik.com/EwAFiVof
