### ISSUE TITLE
Drawer closing click propagates to the view

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#538]
Can be reproduced [here](http://dojo.telerik.com/@Kiril/amoKA). Using Android 4.2.2 on Samsung device.

**Comment by underlog** [comment]
Yes it does, like all onclick events. No reliable means around that.

On Feb 6, 2015, at 8:38 PM, Kiril Nikolov <notifications@github.com<mailto:notifications@github.com>> wrote:


Can be reproduced here<http://dojo.telerik.com/@Kiril/amoKA>. Using Android 4.2.2 on Samsung device.
