### ISSUE TITLE
Links in PDF file are not clickable when file is opened in PDFViewer

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5383]
### Bug report

Open a pdf file with links in PDF Viewer. Links are not clickable.

### Reproduction of the problem

 * Open the demo for the [PDF Viewer](https://demos.telerik.com/kendo-ui/pdfviewer/index)
 * Open a file, containing links
 Example file: [editor_content.pdf](https://github.com/telerik/kendo-ui-core/files/3804561/editor_content.pdf)
* Click on a link

### Current behavior
Clicking on a link does not redirect to the page

### Expected/desired behavior
Clicking on a link should redirect to the link.

### Environment

* **Kendo UI version:** 2019.3.1023

* **Browser:** [all]

**Comment by martintabakov** [comment]
After further discussion, the above is rather a feature requested on this link - https://feedback.telerik.com/kendo-jquery-ui/1432795-add-annotations-layer-to-the-pdfviewer.
