### ISSUE TITLE
Datepicker v-model changes Date to string

### ISSUE THREAD

**Issue by SaphuA** [telerik/kendo-ui-core#5388]
### Reproduction of the problem

https://npc8yw.run.stackblitz.io

Change the value and use the Vue Dev Tools to see that the value changed to a string instead of Date object.

### Current behavior

Binding a Datepicker to a Date field and selecting a date changes the type of the field to a string. This is unexpected and does not play well with TypeScript.

### Expected/desired behavior

The Datepicker should respect the type of the bound field.

### Environment

* **Using Vue wrappers**
* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 3.4
* **Browser:** [Firefox latest]

**Comment by zdravkov** [comment]
A temporary workaround - https://stackblitz.com/edit/4hsp5x-stbtwa?file=index.js
