### ISSUE TITLE
Blurred text on PDFViewer printing with scale less than 200%

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#5394]
### Bug report
Currently the result of PDFViewer printing is affected by PDFViewer scale option. When scale is less than 200%, the letters in the printed PDF appear blurred.

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/pdfviewer/index
1. Set scale option to 100%
1. Print to PDF using "Microsoft Print to PDF" printer. (The final result is the same compared to actual printing to a physical printer)
1. For consistency set the following print options, e.g. in Chrome:
- Paper size: A4
- Pages per sheet: 1
- Margins: None
- Scale: Default

### Current behavior
Text in printed PDF file is blurred

![400% to 100%](https://user-images.githubusercontent.com/6614183/68391920-480d8800-0171-11ea-8f14-0d223b755aea.png)

### Expected/desired behavior
Text in printed PDF file is clear.
NOTE: Clear text may be achieved if PDFViewer scale option is set to 400% on the demo before printing.

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** all

**Comment by PekoPPT** [comment]
The issue is also valid when printing a PDF file directly on paper. See ticket: #1444086

**Comment by Dimitar-Goshev** [comment]
After the fix there are no images in the printed PDF in IE11
