### ISSUE TITLE
ComboBox doesn't reset its default state on content deletion

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5400]
### Bug report

The ComboBox doesn't reset its default state when removing the selected items with Ctrl+A && pressing the Delete/Backspace button.

This bug is a regression from the 2018 R3 version.

### Reproduction of the problem
1. Open [this Dojo project](https://dojo.telerik.com/avIWOQAt)
2. Select the ComboBox and enter "Hanari Carnes", then select the first element
3. Clear the value of a field in one step (press Ctrl+A then Delete/Backspace button). The dropdown of the ComboBox will open.
4. Select the first element in the list - "Vins et alcools Chevalier".
5. The dropdown closes and no item is selected

### Current behavior
When selecting the first element in the list, the Combobox closes without adding a value to the ComboBox input.

### Expected/desired behavior
When the "Vins et alcools Chevalier" value is selected , the value should be added in the ComboBox input and the dropdown should close. 
[Here is a Dojo demonstrating the correct behavior.](https://dojo.telerik.com/EGevAKIP)

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
@Iankodj @mparvanov The fix leads to a critical issue in IE - when the ComboBox value is cleared and the widget is blurred, the focus is automatically returned back to the ComboBox.
