### ISSUE TITLE
Editor table wizard cell styling adds additional columns when multiple cells were selected

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5401]
### Bug report
In Firefox selecting multiple cells in a table and applying a style (e.g. Background Color) through the table wizard results in two extra columns being added.

### Reproduction of the problem
Reproducible in the demos.

1. Add a Table with 2 rows and 2 columns
2. Select multiple cells by clicking on the first cell and then dragging to the right
3. Click on the table wizard icon to open the table wizard
4. Select the Cell tab
5. Change the Background Color to something like red
6. Press the Ok Button
7. Now the first cell has a red background color and 2 columns are added after the first cell

### Current behavior
Columns are added to the table.

### Expected/desired behavior
No columns are added to the table. 

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** x.y
* **Browser:** [Firefox 69]

**Comment by aleksandarevangelatov** [comment]
Also mentioned in thread #1464933

**Comment by Juveniel** [comment]
Also reported in TicketID: 1471629

**Comment by veselints** [comment]
Closing the original issue as it is no longer reproducible with the R2 20202 release. As per the additional reports, those have been extracted in the following issue: https://github.com/telerik/kendo-ui-core/issues/5896
