### ISSUE TITLE
ColorPicker, DropDownTree, Rating and Switch cannot be reset by form reset

### ISSUE THREAD

**Issue by IKKI2000** [telerik/kendo-ui-core#5409]
### Bug report
ColorPicker, DropDownTree multiple or single selection mode, Rating and Switch widgets are not reset by form resetting.
Note: input type="text" and Kendo DropDownList are reset.

### Reproduction of the problem
1. Run the following [Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/OquQAZAN)
1. Select values for all widgets.
1. Click Reset button to reset the form

### Current behavior
ColorPicker, DropDownTree, Rating and Switch widgets are not reset 

### Expected/desired behavior
All widgets are reset similar to DropDownList

### Environment
* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.12.4
* **Browser:** all

**Comment by Juveniel** [comment]
The specified editor widgets require to utilize their value() methods to correctly reset their value. That being said, one possible approach to handle this is through a custom click handler that iterates over the form inputs and checks if the input is part of a widget through [the widgetInstance() method](https://docs.telerik.com/kendo-ui/api/javascript/kendo/methods/widgetinstance). If that is the case, then utilize the respective widget's value() method to change the value.

Resetting the specified editors is also possible with the Form widget which has a built-in clear button:
* [https://demos.telerik.com/kendo-ui/form/index](https://demos.telerik.com/kendo-ui/form/index)
