### ISSUE TITLE
TreeList with toolbar and columns locked right scroll bar overflow

### ISSUE THREAD

**Issue by IKKI2000** [telerik/kendo-ui-core#5410]
### Bug report
TreeList with toolbar and columns locked right scroll bar overflow

### Reproduction of the problem
Please run [https://dojo.telerik.com/iruwoTEx/2](https://dojo.telerik.com/iruwoTEx/2)
DO NOT USE FULL SCREEN
MUST BE Horizontal Scroll Bar Appear

### Current behavior
1. If pagesize less than 11 no overflow~ Greater than or equal to 12 scroll bar overflow
2. This problem only occurs when there is a horizontal scroll bar

### Expected/desired behavior
TreeList with toolbar and columns locked right scroll bar no overflow

### Environment
* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by dmanova** [comment]
Hello. Do you reproduce this issue anywhere outside Dojo environment? Could you give a sample?

**Comment by IKKI2000** [comment]
@dmanova OK~ Please see: https://ikki2000.github.io/KendoUI-Admin-Site/admin/#/data/treelist

**Comment by magdalenaan** [comment]
Hi, is the issue still reproducible? I have opened the first example, but only Kendo Chart is initialized. The second example cannot be opened. Could you provide us with an actual example and a screen shot/video that would describe the issue in more detailed way?

**Comment by ag-petrov** [comment]
Sample to reproduce this is not present so I am closing the issue.
