### ISSUE TITLE
ColorPicker's popup and FlatColorPicker do not support RTL

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#5420]
### Bug report
ColorPicker and FlatColorPicker do not support RTL properly:
- color preview is not on the right
- clear button falls on a new row
- sliders for color selection and opacity are not inverted, thus the selection shown on them does not correspond to the actual value
- when opacity is used, the value is shown as rgba and the closing bracket is on the left, instead of on the right - (`rgba(81, 19, 225, 1`

### Reproduction of the problem
Run the following [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/uFiyILuS)

### Current behavior
![RTL ColorPicker](https://user-images.githubusercontent.com/6614183/68763503-459fa800-0621-11ea-9e85-5c819a2eceea.png)

### Expected/desired behavior
Flipped positions compared to LTR ColorPickers - [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/UNUMoVeD)
Similar to the following flipped image of LTR:
![Flipped LTR](https://user-images.githubusercontent.com/6614183/68764267-0b370a80-0623-11ea-979c-cf47a0893181.png)

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** all

**Comment by Juveniel** [comment]
https://github.com/telerik/kendo/issues/8022

**Comment by Dimitar-Goshev** [comment]
After the fix ColorPicker and FlatColorPicker now appear as expected in RTL.
A few issues remaining in the following themes:
- [ ] Fiori - unexpected border overlapping color preview
![ColorPicker RTL Fiori](https://user-images.githubusercontent.com/6614183/70896222-05a15b80-1ff9-11ea-8330-c7aca5a789d2.png)

- [ ] Office 365 - unexpected border
![ColorPicker RTL - Office](https://user-images.githubusercontent.com/6614183/70896400-4e591480-1ff9-11ea-80ec-3a610a1fd688.png)

- [ ] Fiori and Office 365 - opacity drag handle is bigger than expected as visible on the screenshots above (reproducible in LTR as well - [demo](https://demos.telerik.com/kendo-ui/colorpicker/angular))

**Comment by Dimitar-Goshev** [comment]
The issues from my comment above are fixed and this issue may be closed after merging the respective PR.
