### ISSUE TITLE
When ColorPicker's value is null or empty string, it should display "no color" upon opening its pop-up

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5426]
### Bug report
ColorPicker: when its value is set to `null` or `empty string` upon opening its pop-up it should display `no color`. Currently, it displays a color value.

### Reproduction of the problem
* Run the following Dojo: https://dojo.telerik.com/aSaxIyIZ/3
* Note that the value of the widget is set to `null`;
* Open its pop-up: the red color appears selected and the hex for red is displayed;
* Click the Clear color button: `no color` will be displayed. That should also be the initial state of the widget (as its value is `null`);

### Expected/desired behavior
When its value is set to `null`, the pop-up should also display `no color` and no color in the color box.

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** All

**Comment by menasheh** [comment]
Any plans to fix this?

**Comment by veselints** [comment]
We have not yet scheduled the above for fixing. Nevertheless, based on your question, I have bumped its priority, which will move it sooner in our priority queue.

**Comment by Iankodj** [comment]
The "no color" value will be not used anymore with major updates in the ColorPicker that will be shipped with 2021 R3 SP1.

Null value will be identified from the preview of the color. Here you are a screenshot: 

![image](https://user-images.githubusercontent.com/4222379/140319608-330c71d7-0ac7-47b4-882c-0e9acbf9236c.png)

The "no color" cannot be considered as a proper value for a color input as it cannot be translated either to null or valid color. This is why it will be deprecated as a concept.
