### ISSUE TITLE
Inconsistent responsiveness of the Drawer button located in the NavBar

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#543]
Example: http://dojo.telerik.com/@Kiril/AsARE

The issue occurs even if a larger button with text is used and UserEvents threshold is increased.
It seems that the touchstart and touchend event fire but sometimes (on iOS) the drawer does not open.

Reported in ticket 904518

**Comment by cdahl** [comment]
I'm also seeing this issue. The buttons are unresponsive a lot of the time, sometimes requiring 4-10 taps in order to work (or not at all).

**Comment by xelatek** [comment]
I have the same exact issue.  The issue is not only limited to the "drawer" button, but any buttons.  The issue for me seems to be worse in iOS 8 using the "drawer" and "back" buttons.

**Comment by underlog** [comment]
The threshold is not set correctly. Please check this comment: http://www.telerik.com/forums/click-event-does-not-fire-reliably#JzzYDDZBCkCItzP17Yw5PA
