### ISSUE TITLE
Window destroy affects the behavior of other widgets on the page

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5438]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/utihiyOf/2) example.
1. Drag the page splitter to resize the screen and see the Grid's pager correctly switch between the different responsive styles (expected)
2. Click the "Open Modal" button, which opens a Kendo Window with another Grid in it
3. Drag the page splitter and/or resizing the Window to see each of the Grid's paging styles changing accordingly (expected)
4. Close the Window (destroy is called in the deactivate event handler)
5. Try again to drag the page splitter to resize the screen.  This time, the Grid's pager is no longer responsive

### Current behavior
Responsiveness of the pager of a Grid declared outside the Window is affected by the Window's **destroy** method. 
### Expected/desired behavior
Calling the **destroy** method has no unexpected effect on components that are not nested in the Window. 

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by ag-petrov** [comment]
Seems to be working fine with the latest version
