### ISSUE TITLE
Cannot `Unhide` hidden columns in imported excel file in Kendo Spreadsheet, where the first row is frozen

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#5441]
[test.xlsx](https://github.com/telerik/kendo-ui-core/files/3886061/test.xlsx)
### Bug report

[issue introduced after **R2 2019 SP1** ]
When attempting to use the context menu to unhide the hidden columns - the option is not available. This only happens, when the original excel file (check attached file) that is imported (using the built-in client-side import of the Spreadsheet) has its first row frozen (besides the hidden columns). 

### Reproduction of the problem
1. Load any demo on the demos site, e.g **Basic Usage** https://demos.telerik.com/kendo-ui/spreadsheet/index
2. Use the attached file to load in the Spreadsheet
3. Select Columns B and E by dragging the selection. (columns C,D are hidden).
4. Right-click on the selected column

### Current behavior
There's no "Unhide" option in the context menu, which should be available in this scenario

### Expected/desired behavior
There should be an "Unhide" option in the context menu

### Possible change that caused the issue:

```js
 startSelection: function (ref, mode, addToExisting, shiftKey, view) {
                if (mode == 'autofill') {
                    this._sheet.startAutoFill();
                } else if (shiftKey && mode == 'range') {
                    var range = new RangeRef(this._sheet.activeCell().first(), ref);
                    this._sheet.select(range, false, false);                   
                    this._sheet.startSelection(); //old version, when it worked

                    this._sheet.startSelection(view); //current version
                } else {
                    this._sheet.startSelection();

                   this._sheet.startSelection(view);

                    this.select(ref, mode, addToExisting);
                }
            }
```

### Environment

* **Kendo UI version:** 2019.3.1023
* **Browser:** [all]

**Comment by nenchef** [comment]
Client comments from public item: "Please also fix the Unhide option for rows when first column is frozen."

**Comment by mparvanov** [comment]
Both cases are handled.
- `Unhide` hidden columns when the first row is frozen 
- `Unhide` hidden rows when the first column is frozen
