### ISSUE TITLE
drawing.drawDOM() and drawing.exportPDF() exports regular text as italic bold in Edge

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5442]
### Bug report
drawing.drawDOM() and drawing.exportPDF() exports regular text as italic bold in Edge
Reported in ticket 1442829

### Reproduction of the problem
In Edge, run the following Dojo and click the button to export it to PDF: https://dojo.telerik.com/ovifIyIS/6

### Current behavior
The regular test gets exported as a bold italic in the PDF

### Expected/desired behavior
The regular text should not be exported as bold italic

### Environment

* **Kendo UI version:** 2019.3.1023
* **Browser:** Edge version 42.17134.1.0;
NOTE: version 44.17763.1.0 works properly with the Dojo above, but fails as well, when common.min.css is loaded locally in an MVC project as shown in [this Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/izuFohEN) (not runnable), which loads Content/kendo/2019.3.1023/fonts/DejaVu/DejaVuSerif-BoldItalic.ttf
![Support1442829 - Microsoft Visual Studio 2019-11-28 13 48 00](https://user-images.githubusercontent.com/6614183/69803781-b9c37980-11e5-11ea-9427-d8a390b26c04.png)

**Comment by ag-petrov** [comment]
Seems to be working fine in the test dojo now, the common.min file is now depricated. Closing this one.
