### ISSUE TITLE
Item in locked content disappears when item is collapsed

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5453]
### Reproduction of the problem
1. Run this dojo - https://dojo.telerik.com/ARobUsUN/2
1. Scroll the TreeList
1. Collapse an item

### Current behavior
The item in the locked column dissappears and rows are misaligned.
Video - https://www.screencast.com/t/LK103dmun9a

### Expected/desired behavior
Item should be collapsed without moving to bottom.

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.12
* **Browser:** [all]

**Comment by dmanova** [comment]
Note from internal testing: The issue is partially fixed. The last collapsible item still moves to the bottom.

**Comment by ag-petrov** [comment]
The described behavior is expected. Generally the problems was that the scrolltop of the frozen container was not equal to the scrolltop of the non-frozen. When you scroll to the bottom and hide a number of items it is expected to get a slight adjustment as there are no more items below the collapsed one.
