### ISSUE TITLE
ComboBox: Select event is fired upon custom text typing and blurring the widget

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5457]
### Bug report
Select event is fired upon custom text typing and blurring the widget.

### Current behavior
* Run the ComboBox events demo: https://demos.telerik.com/kendo-ui/combobox/events
* Type some custom text in the ComboBox input;
* Click outside the combo - the `select` event will be triggered;

### Expected/desired behavior
The `select` event should be triggered only when an item from the ComboBox pop-up list has been selected.

### Environment

* **Kendo UI version:** 2023.3.1114
* **Browser:** [all]

**Comment by alestoya** [comment]
Reported in 1591568

**Comment by martintabakov** [comment]
Also reported in ticket 1593603 for the MultiColumnComboBox
