### ISSUE TITLE
Change ListView role when selection is not enabled

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#5458]
Currently the ListView has a role [listbox ](https://www.w3.org/TR/wai-aria-1.1/#listbox)which requires selection. However selection may not always be enabled and in such cases the role of [list ](https://www.w3.org/TR/wai-aria-1.1/#list)seems like a more appropriate one. We should further research what is the best role for the non-selectable ListView.

Reported in ticket - # 1443696

**Comment by dmanova** [comment]
After the change, we have a contradiction between the role="listitem" and the "aria-selected" check: 
https://www.w3.org/TR/wai-aria-1.2/#listitem
As the "listitem" role has no required states and properties, we may consider removing "aria-selected", when the ListView is not configured as selectable.
