### ISSUE TITLE
MultiSelect, WAI-ARIA: aria-autocomplete attribute is not allowed on a widget with a role "listbox" (the widget input element)

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5459]
### Bug report
MultiSelect.
As per the WAI-ARIA guidance, `aria-autocomplete` attribute is not allowed on a widget with a role `listbox`. That is the MultiSelect `input` element. Here are listed all allowed attributes on `listbox`:
https://www.w3.org/WAI/PF/aria/roles#listbox

### Reproduction of the problem
* Run the MultiSelect index demo: https://demos.telerik.com/kendo-ui/multiselect/index
* Inspect the MultiSelect `<input>` element - it has an `aria-autocomplete` attribute, but that is not allowed;

### Expected/desired behavior
The `<input>` element should not use the `aria-autocomplete` attribute, or we should consider changing the `role` of the `<input>` to `combobox` or `textbox`, for example.

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** [all]

**Comment by Iankodj** [comment]
Related to #5460
