### ISSUE TITLE
Scheduler automatically selects a slot on tapping the "Show business hours" button (iOS)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5466]
### Bug report
Reproduced on iPad (iOS12 and 13). Mobile Chrome and Safari.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/UTuLITaW) example.
1. Tap the "Show business hours" / "Show full day" button at the bottom left side of the Scheduler. 

The issue does not occur if tapping specifically on the button's clock icon.

### Current behavior
A slot is automatically selected and change event fires.

### Expected/desired behavior
No slot selection, thus the change event should not fire. 

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** x.y
* **Browser:** iOS Safari and Chrome

**Comment by sspasova** [comment]
The issue is no longer reproducible using Kendo UI 2023.3.1114. Tested on iPad Safari/Chrome with iOS 17.1.1.
