### ISSUE TITLE
Kendo UI DateTimePicker does not work with custom format setting/removing value without calendar

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#5468]
### Bug report

The Kendo UI DateTimePicker throws an error when custom format is set and user tries to set and remove a value in the input. 

### Reproduction of the problem

It will be reproduced in case that the calendar is not opened at all. 

Dojo example: https://dojo.telerik.com/AdOPaTiw

Steps to reproduce:

- Open the dojo example;
- Open a debug console;
- Type a valid date and time value in the picker;
- Remove focus from this picker;
- Delete the value in the picker;
- Remove focus again.

### Current behavior

The widget throws an error. 

### Expected/desired behavior

There is no need to explcitly open the calendar in order to set and remove a value from the Kendo UI DateTimePicker. 

### Environment

* **Kendo UI version:** 2019.3.113
* **jQuery version:** 1.12
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Does not seem to reproduce with the latest version
