### ISSUE TITLE
Grid cell is getting edited immediately after touch

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-ui-core#5472]
### Bug report
When touching a grid cell in incell editing mode it gets edited immediately. This way it is hard to scroll the grid in touch devices and the keyboard appears all the time.
Versions before  2019.2.619 need a longer tap to make the cell editable. So scrolling the grid was easier.

### Reproduction of the problem
https://dojo.telerik.com/oSoMOmAN

### Current behavior
Going in edit mode immediately.

### Expected/desired behavior
Scroll the grid without going in edit mode immediately.
https://dojo.telerik.com/apuVIviQ

### Environment

* **Kendo UI version:** 2019.2.619 - 2019.3.1023
* **jQuery version:** 1.12.3
* **Browser:** [ Mobile Chrome | Android  Web Browser | iOS Safari ]

**Comment by ag-petrov** [comment]
Please test the InCell edit mode on all types of devices with all browsers
