### ISSUE TITLE
ColorPicker, MultiSelect, Radio, Checkbox have no invalid border color

### ISSUE THREAD

**Issue by IKKI2000** [telerik/kendo-ui-core#5475]
### Bug report
ColorPicker, MultiSelect, Radio, Checkbox have no invalid border color

### Reproduction of the problem
1. Run the following [Dojo snippet](https://dojo.telerik.com/oSugolAX)
2. Click button to submit the form

### Current behavior
ColorPicker, MultiSelect, Radio, Checkbox have no invalid border color 

### Expected/desired behavior
All widgets have invalid border color similar to DropDownList

### Environment
* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.12.4
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
@IKKI2000 The Checkbox issue is resolved with the latest dev version of default v2 theme - [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/ilUbOdUw).

For SASS themes related issue, please log issues in [Kendo Themes](https://github.com/telerik/kendo-themes/issues) repository.

**Comment by IKKI2000** [comment]
@Dimitar-Goshev MultiSelect wrap ‘k-valid’ class is missing~ The same as ColorPicker~ This is not the SASS themes issue~ This is the JS issue~
Checkbox invalid border color in your Dojo is wrong color~ It must be error color not the accent color~
