### ISSUE TITLE
AutoComplete widget has troubles if multiple items have the same label

### ISSUE THREAD

**Issue by reckart** [telerik/kendo-ui-core#5476]
### Bug report

It seems that the Kendo AutoComplete ~~AutoSelect~~ widget has issues when multiple items in the auto-suggest box have the same label. 

I am using the AutoComplete ~~AutoSelect~~ widget in the following scenario:

* user starts entering a term
* term is looked up in a database (e.g. Wikidata)
* matching items from the database are shown in the dropdown

If the user for example enters `Chicago`, many different items with that label are proposed.

### Reproduction of the problem

* construct an auto-complete field which upon the input of `Chicago` offers multiple items in the dropdown, all with the label `Chicago`
* provide the list that fills the dropdown using a set of JSON objects consisting of a label and an identifier
* configure the auto-complete field to use the label field from the JSON as the `dataTextField`.
* enter `Chicago` into the field and select the second item from the dropdown
* press the *cursor down* key to open the dropdown again
* note that all items in the dropdown appear pre-selected and not only the first one (cf. `_values` field in the listbox widget)
* select the first item now
* note that no `change` event is triggered when selecting the first item now since it has the same label as the previously selected item (cf. `_oldText` field in the widget).

### Expected/desired behavior
When a concrete data item has been selected, only that item should be used for the pre-selection when the dropdown is opened a second time. Basing the pre-selection on the item label leads to problems.

The `change` event should be triggered if a new item is selected, even if it has the same label as the previously selected item.

The introduction of a `dataIdField` to configure a unique identifier field in the JSON items may be sensible.

### Environment

* **Kendo UI version:** 2019.2.619
* **Browser:** tested on Safari 13.0.4 and Chrome 78.0.3904.108

**Comment by Dimitar-Goshev** [comment]
@reckart Thank you for the detailed issue report. We need some clarifications about it as the described behavior does not match Kendo AutoComplete behavior (you mentioned AutoSelect widget, but there is no such widget and the closest one is AutoComplete). What bothers me in the described scenario is the step "press the cursor down key to open the dropdown again" - Kendo AutoComplete does not open a dropdown on pressing down key. This may be tested on [Basic Usage demo](https://demos.telerik.com/kendo-ui/autocomplete/index).

I would be best if you edit the following [Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/ENisADUz) with the required configuration for issue reproduction and provide the link to it.

**Comment by reckart** [comment]
Thanks for the hints. 

I have tried reproducing the issue in this Dojo: https://dojo.telerik.com/egemILIj/2

Wrt. "all items matching label appear pre-selected when opening the dropdown": I have not been able to reproduce this. When I debugged this before, `_isFiltering()` had returned `false` to me, but I cannot say why. So this cannot be reproduced.

Wrt "no change event triggered when selecting another item with the same label": that one can be reproduced using the Dojo

**Comment by reckart** [comment]
Mind that you can also test the "dropdown opens on cursor down" in this dojo. It is part of the test steps explained in the dojo itself.

**Comment by Dimitar-Goshev** [comment]
@reckart Kendo UI AutoComplete does not support dataValueField. It works only with the selected text. The change event is fired when the value of the AutoComplete is changed by the user. In the given scenario the text in both cases is "Chicago" - that's why the change event does not fire the second time. I am closing this issue as this is the expected supported behavior.

The following [forum thread](https://www.telerik.com/forums/datavaluefield-does-exist#HP9RFXBY9kykmulaUvjxQg) comments the above and in the following reply there is a custom approach for figuring out if other than the text of the item has changed. This updated [Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/IWiLUcar) uses the suggested approach. I hope it helps.
