### ISSUE TITLE
Content is not export to PDF as expected with page break applied.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#5477]
### Bug report

Content is not export to PDF as expected with page break applied. It occurs with nested elements.

### Reproduction of the problem

Dojo: https://dojo.telerik.com/UZuloFUm/2

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mishoo** [comment]
Here's an updated Dojo that seems to work fine: https://dojo.telerik.com/uROSIqOr

I made the following changes:

1. you call drawDOM on `.page`, but in your example that element contains very little text; I moved the class on the upper element, I presumed that's what you wanted.

2. I added `defineFont` declarations, as in other PDF examples; without proper TTF files neither line breaking nor page breaking is expected to work correctly.

3. the elements you use to insert manual page breaks (e.g. the `.page-break` elements) are expected to be empty.  I just removed content from them, and inserted it after them.

Closing it, but please reopen if you feel there's something to be fixed here.
