### ISSUE TITLE
The position of the validator in dropdown Grid editor is not correct

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-ui-core#5478]
### Bug report

The position of the validator in dropdown Grid editor is not correct:
![2019-12-13_1615](https://user-images.githubusercontent.com/45764088/70806368-d524ac00-1dc3-11ea-8d91-d827adf2f519.png)

Reported in ticket 1446004

### Reproduction of the problem
1. Go to the following Dojo:
https://dojo.telerik.com/IpADOmur/2

2. Add a new product and add an empty category from the dropdown

3. The validation message will show up in a misplaced manner

### Expected/desired behavior
The validation tooltip should be displayed underneath the dropdown:
![2019-12-13_1619](https://user-images.githubusercontent.com/45764088/70806590-5aa85c00-1dc4-11ea-8cbb-6be8f5746407.png)

### Suggestion for a fix
The rendering of the tooltip is not correct. Currently, it is added after the input element, inside the k-dropdown element, but it should be after the k-widget k-dropdown element as it is with the rest of the widgets.

**Comment by ag-petrov** [comment]
https://github.com/telerik/kendo-ui-core/issues/5108 seems like a related issue

**Comment by joneff** [comment]
comparing against the latest changes, this appears to have been fixed

**Comment by dmanova** [comment]
The issue seems to have been fixed with Kendo UI R2 2020 (2020.2.513).
