### ISSUE TITLE
Datepicker- Dateinput label is not in German translated.

### ISSUE THREAD

**Issue by daltgenug** [telerik/kendo-ui-core#5479]
When I used a Datepicker, the datepinput appears with wrong format Day.Mont.Year and not  with Tag, Monat, YYYY when i call the culture and message file.
We checked with your team the problem and they give me a temproraryy solution to solve it..
Solution:
<script type="text/javascript">
    kendo.ui.DateInput.fn.options.messages.day = "Tag" 
    kendo.ui.DateInput.fn.options.messages.month = "Monat" 
    kendo.ui.DateInput.fn.options.messages.year = "Jahr"
    kendo.culture("de-DE");
</script>

Best regards Diego.

### Bug report

**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our feedback portal](https://www.telerik.com/support/feedback)**

### Reproduction of the problem
_(bug report only)_
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via http://dojo.telerik.com or similar.

### Current behavior
_(optional)_
Provide additional information if the steps for reproducing the faulty behavior are not sufficient to describe the issue.

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by dmanova** [comment]
The localization files are community-driven. So to have the translation available it needs to be added or updated by someone in the community, that could be you of course. More information in the procedure could be found here:  
https://docs.telerik.com/kendo-ui/globalization/localization#contribution

In your particular case what needs to be done is:
1. Fork the repository.
2. Apply the respective changes - in file [kendo.messages.de-DE.js](https://github.com/telerik/kendo-ui-core/blob/master/src/messages/kendo.messages.de-DE.js) add and translate the section for the Date Input component (that could be found in kendo.messages.en-US.js):

> /* DateInput */
if (kendo.ui.DateInput) {
  kendo.ui.DateInput.prototype.options.messages =
    $.extend(true, kendo.ui.DateInput.prototype.options.messages, {
      "year": "year",
      "month": "month",
      "day": "day",
      "weekday": "day of the week",
      "hour": "hours",
      "minute": "minutes",
      "second": "seconds",
      "dayperiod": "AM/PM"
    });
}

3. Submit a pull request.

Then we are going to review the changes and after approved they will be available in the next release.
