### ISSUE TITLE
Workbook export generates corrupted excel file if the sheet name contains a possible cell, e.g. A1

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5480]
### Bug report
The workbook exporting to Excel generates a corrupted file when the name of some of its sheets contains a "cell-related" value - for example, "A1", "G5", "F45", etc.   

### Reproduction of the problem
1. Open [this Dojo project](https://dojo.telerik.com/@Dimitar-Goshev/AsUFufeb) and run it
2. Save the exported Excel file and open it. 

### Current behavior
When the saved file is opened in Excel, a "corrupted file" warning appears on the screen. 

### Expected/desired behavior
There shouldn't be any warnings when opening a saved workbook
 
### Environment
* **Kendo UI version:** 2022.3.913
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by NikoPenev21** [comment]
a new report in 1446339

**Comment by mishoo** [comment]
I can't reproduce the error, the file opens just fine. I checked `xl/workbook.xml` in the generated XLSX file and the name is properly quoted. If there's still a way to reproduce, please reopen and update the example.
