### ISSUE TITLE
DateRangePicker change event fires three times on every input change.

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#5482]
### Bug report

The change event of the DateRangePicker fires three times every time you change an input field.

This is a regression in Kendo v2019.2.514

### Reproduction of the problem
1. Open [this Dojo example](https://dojo.telerik.com/ArEWInIP).
1. Select Start and End date.

### Current behavior
The change event fires three times on every input change, for a total of six.

### Expected/desired behavior
The change event should only fire once when a date is selected.

### Environment

* **Kendo UI version:** 2019.2.514
* **Browser:** [all]

**Comment by vishal079** [comment]
it's also not working with 
**Kendo UI version 2019.3.1023**
