### ISSUE TITLE
When using SASS theme and programmatically updating the model the dirty field indicator is misplaced

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5486]
**Describe the bug**
When using a SASS theme and programmatically update a model field the dirty indicator is misplaced.

**To reproduce**
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/odefORUf)
2. Click on the third entry ProductName field
3. The "Discontinued" field is programmatically set to `true`
4. The dirty indicator is misplaced to the top-left corner of the Grid

**Expected behavior**
The dirty indicator should be placed over the edited cell

**Screenshots**
Before change: 
![dirty_indicator_1](https://user-images.githubusercontent.com/46348689/70701834-ba740980-1cd5-11ea-9370-a69c1880ebcf.png)

After change:
![dirty_indicator_2](https://user-images.githubusercontent.com/46348689/70701854-c364db00-1cd5-11ea-9bf3-b6e7b8b9df26.png)

**Affected package (please provide)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please provide)**
* Kendo UI for jQuery

**Affected browsers (please provide)**
 * All Browsers

**Comment by TeyaVes** [comment]
Transfering the issue from kendo-themes to kendo repo. The problem is not in the SASS theme styles but rather the rendering- the cell that contains the dirty cell indicator needs a **k-dirty-cell** class, which in the current case is not being added.

**Comment by PreslavKozovski** [comment]
Follow the discussion in this issue - https://github.com/telerik/kendo-themes/issues/1275
