### ISSUE TITLE
Chat does not display the avatar image when using templates

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5487]
### Bug report
Chat does not display the avatar image when using templates.

**That is a regression introduced with R3 2018 release.**

### Reproduction of the problem
Run the following Dojo: https://dojo.telerik.com/ovUcAqAm/5

### Current behavior
No avatar image will be present

### Expected/desired behavior
The image should be rendered. For reference run the same with R2 SP1 2018:
https://dojo.telerik.com/ovUcAqAm/2

### Environment
* **Kendo UI version:** from 2018.3.911 on
* **Browser:** [all]

**Comment by Juveniel** [comment]
https://github.com/telerik/kendo-ux-private/issues/88

**Comment by PekoPPT** [comment]
Also reported in ticket: #1491987

**Comment by Iankodj** [comment]
Currently, only the renderMessage method can render a template with an avatar. Example: https://dojo.telerik.com/uxiPayuS

**Comment by Iankodj** [comment]
Closing this issue as the above solution (https://github.com/telerik/kendo-ui-core/issues/5487#issuecomment-758681841) accomplishes the requirements (render template and avatar). If an avatar is considered for attachments we should consider it as an optional element. And it should come with API, rendering and decoration improvements.
