### ISSUE TITLE
Update Popup editor template classes

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-ui-core#5488]
### Bug report

Reported in Ticket with ID : 1446954

### Reproduction of the problem

Visible in our online grid popup editing demos

- [Core](https://demos.telerik.com/aspnet-core/grid/editing-popup)
- [Mvc](https://demos.telerik.com/aspnet-mvc/grid/editing-popup)

### Current behavior

The editor uses the old rendering and classes:

![image](https://user-images.githubusercontent.com/10980842/71277694-433a1780-235e-11ea-90d8-1dabb33e8467.png)

### Expected/desired behavior

The form should feature the `k-edit-field` and `k-edit-label` classes instead

![image](https://user-images.githubusercontent.com/10980842/71277750-6fee2f00-235e-11ea-9407-498dc2bc8c10.png)

### Environment

* **Kendo UI version:** 2019.3.1024

**Comment by dmanova** [comment]
The fix should be applied to TreeList also.
