### ISSUE TITLE
Column Resize is not working properly in latest version when we have horizontal scroll bar

### ISSUE THREAD

**Issue by purush3** [telerik/kendo-ui-core#5489]
### Bug report

**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our feedback portal](https://www.telerik.com/support/feedback)**

### Reproduction of the problem
1. Create Grid with more columns and horizontal scroll bar.
2. try to resize columns randomly, multiple times
3. you will see column resize does not respond , and you can see the below console error in developer window
 - Uncaught TypeError: Cannot read property 'closest' of undefined
 - Uncaught TypeError: Cannot read property 'attr' of undefined

### Current behavior
_(optional)_
Provide additional information if the steps for reproducing the faulty behavior are not sufficient to describe the issue.

### Expected/desired behavior
Column resize should happen without any issue.

### Environment

* **Kendo UI version:2019.3.1023
* **jQuery version:1.12.4
* **Browser:** All

**Comment by dmanova** [comment]
I try to reproduce the behavior on this Dojo sample https://dojo.telerik.com/OgeRIDAj but I couldn't. 

Could you give us exact steps to reproduce it on this example or another runnable example where the issue is reproduced?

**Comment by ParamesCiena** [comment]
Hi,

I am also receiving the same errors randomly with the column resizing of Kendo Grid in the asp.net MVC Page 

**Uncaught TypeError: Cannot read property 'closest' of undefined
Cannot read property 'attr' of undefined**

Additional Information:
I have locked the first 2 columns as fixe and make the other columns as scrollable
I am using the latest Kendo version (2020) and Jquery Version (3.5.1)

Please help to solve this issue.

**Comment by dmanova** [comment]
Hi @ParamesCiena and @purush3. Thank you for your feedback. 

I'm still struggling in reproducing the issue. Could you send us all the configurations of the grids where you experience the issue? Or a runnable example?  Whatever is more convenient for you.
Also information about the color theme or if you are using RTL, could also help.

**Comment by ParamesCiena** [comment]
Hi ,

This issue is occcuring randomly may be when we try to resize the column might be after double the fixed column to fit to its contents.

Please find the screenshot of the error attached herewith.

![Grid-Resize-Error](https://user-images.githubusercontent.com/62257930/112693342-798e0d00-8ea6-11eb-9cbe-70ed77f81fbd.PNG)

**Comment by ParamesCiena** [comment]
Hi @dmanova,

Did you get a chance to look at the above issue? 

We are still getting this script often when we are trying to resize the column of the grid.

Please help us to  find the cause and solve this issue

**Comment by dmanova** [comment]
Hi @ParamesCiena ,

I've tried to make a sample closer to the grid in your screenshot - https://dojo.telerik.com/AWOnAQUs 
But it seems I'm still missing something, as the issue is not reproducible in this sample either. 

Could you update the sample to be as close as possible to your application? Or post the configuration of the grid, as well as some additional styles you use and maybe JavaScript functions that could be related to the grid header and its resize? 

If your project is ASP.NET it also is useful to have that information so we could reproduce it within ASP.NET MVC/ Core sample.

P.S. Please proceed according to your terms and policy with any information you consider as confidential or similar. Such data could be replaced by dummy data and I don't think it is essential for the issue replication.

**Comment by ParamesCiena** [comment]
Hi @dmanova,

Thanks for your effort in creating the sample to reproduce this issue. 
I am trying to update the sample with the additional function scripts/styles,  grid options (filter, grouping) to reproduce the same issue. 
FYI: We are using both MVC and JQuery kendo grids on different pages and facing the same issue with resizing.

**Comment by ParamesCiena** [comment]
Hi @dmanova,

I have updated the sample with additional options, it is working fine in the sample, https://runner.telerik.io/fullscreen/AWOnAQUs 

but we are getting the script error randomly in our application, when we try to resize the column might be after double click the fixed column to fit its contents.

are we missing any other configurations?

**Comment by ahmedali273** [comment]
Hi @dmanova , @ParamesCiena , @purush3 
I am having the same issue , could you please tell me if any found the root cause or solution for that.

**Comment by dkmung** [comment]
Hi, 

Does any one found the solution on this? We have the same issue happening randomly when resizing the kendo grid column. Throwing error

Environment
   kendo.version: 2020.1.219
   jquery : 3.4.1
   angular.version 1.4.6 (Angular JS)

_vendor.js:177687 ERROR TypeError: Cannot read properties of undefined (reading 'closest')
    at init.start (kendo?ver=22.2.21364.1:1:1071299)
    at init.trigger (kendo?ver=22.2.21364.1:1:7954)
    at init._start (kendo?ver=22.2.21364.1:1:426024)
    at init.i (jquery.min.js:2:87485)
    at init.trigger (kendo?ver=22.2.21364.1:1:7954)
    at init._trigger (kendo?ver=22.2.21364.1:1:403126)
    at init._start (kendo?ver=22.2.21364.1:1:400885)
    at init.i (jquery.min.js:2:87485)
    at init.trigger (kendo?ver=22.2.21364.1:1:7954)
    at init.notify (kendo?ver=22.2.21364.1:1:389188)_

ERROR TypeError: Cannot read properties of undefined (reading 'closest')
    at init.resize (kendo?ver=22.2.21364.1:1:1072372)
    at init.trigger (kendo?ver=22.2.21364.1:1:7954)
    at init._resize (kendo?ver=22.2.21364.1:1:426445)
    at init.i (jquery.min.js:2:87485)
    at init.trigger (kendo?ver=22.2.21364.1:1:7954)
    at init._trigger (kendo?ver=22.2.21364.1:1:403126)
    at init._processMovement (kendo?ver=22.2.21364.1:1:401996)
    at init._drag (kendo?ver=22.2.21364.1:1:401278)
    at init.i (jquery.min.js:2:87485)
    at init.trigger (kendo?ver=22.2.21364.1:1:7954)

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible on my side with the provided Dojo snippet - https://runner.telerik.io/fullscreen/AWOnAQUs 
Also it is not reproducible with the latest version - https://dojo.telerik.com/gAdQqIKA
