### ISSUE TITLE
Loading Popup with Silver Skin

### ISSUE THREAD

**Issue by tareknaj** [telerik/kendo-ui-core#549]
Mixing these 2 demos :
http://demos.telerik.com/kendo-ui/application/loadingpopup
http://docs.telerik.com/kendo-ui/mobile/regular-usage

Into this scenario :
http://dojo.telerik.com/iGIba

Loading Popup not looking as expected

**Comment by underlog** [comment]
The silver skin and the rest of the web compatibility skins are not meant to be used with a mobile application instance.

**Comment by tareknaj** [comment]
@underlog are web widgets supported with mobile application instance ? I know the grid and the scheduler have adaptive capability but what about the core widgets ?

**Comment by underlog** [comment]
yes they are - it is documented and featured in our demos. In case you need further assistance, please open a support ticket in the Telerik help system.
