### ISSUE TITLE
Listbox Compatibility

### ISSUE THREAD

**Issue by dday9** [telerik/kendo-ui-core#5494]
### Reproduction of the problem
Dojo: https://dojo.telerik.com/etuHABUC
In the dojo link above, I have the CDN for jQuery 1.12.4 commented out. If you run it as it is and try to transfer any items between the Listbox widgets you'll get an error. However if you take out the comment brackets for that CDN and move them to the CDN for jQuery 1.9.1 you'll find that the error is resolved.

### Current behavior
The transfer to/from does not work using jQuery 1.9.1.

### Expected/desired behavior
According to the documentation:

> Kendo UI Core depends on the following libraries:
> jQuery v1.9.1+

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.9.1
* **Browser:** all

**Comment by dmanova** [comment]
We release ListBox in [Kendo UI R2 2017](https://www.telerik.com/support/whats-new/kendo-ui/release-history/kendo-ui-r2-2017) . This Kendo UI version is tested against jQuery 1.12.3 and also compatible with 1.10.x, 2.2.x and 3.1.1 as documented [here](https://docs.telerik.com/kendo-ui/intro/supporting/jquery-support). 

Please refer to the latest link for details about the compatibility between Kendo UI and jQuery versions.

**Comment by dday9** [comment]
Then perhaps the documentation should be updated here: https://github.com/telerik/kendo-ui-core#compatibility-and-requirements

**Comment by dmanova** [comment]
Thank you for pointing this out. Will change accordingly.
