### ISSUE TITLE
Vue Grid wrapper column  template with router-link does not work correctly

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#5499]
### Bug report
Vue Grid wrapper column  template with router-link does not work correctly

### Reproduction of the problem
https://codesandbox.io/s/vue-dynamic-components-t54dq

### Current behavior
js errors

### Expected/desired behavior
the router links work correctly

**Comment by 01willtx** [comment]
what ever happened with this? I see it was closed but no resolution?
