### ISSUE TITLE
Spreadsheet formula does not reference properly value from a merged range

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5500]
### Bug report
Spreadsheet formula does not reference properly value from a merged range.

### Reproduction of the problem
* Run the Spreadsheet Index demo: https://demos.telerik.com/kendo-ui/spreadsheet/index
* Change the value in the merged range (A1:G1) to some numeric;
* Select cell L1 and type "=" and then select the merged range;
* Hit Enter;
* The L1 cell will display "#VALUE!", while it should display the same value as the merged range;
* The actual content of the L1 cell is "=A1:G1", while it should be "=A1";

### Current behavior
The full range will be referenced in the formula, while only its first cell should be used;

### Expected/desired behavior
Review the same scenario in Excel. The cell with the reference will contain "=A1" and will display the same value as the merged range;

### Environment
* **Kendo UI version:** 2019.3.1023
* **Browser:** all

**Comment by mishoo** [comment]
Fixed in telerik/kendo#13871
