### ISSUE TITLE
Issue with kendo-diagram-vue-wrapper type file

### ISSUE THREAD

**Issue by aaf-ww** [telerik/kendo-ui-core#5502]
## I'm submitting a...
* Bug report 

## Current behavior
After installing kendo-diagram-vue-wrapper and kendo-all-vue-wrapper, I get an error about the first package exporting some of the Barcode components which are already being exported by the appropriate package.

## Expected behavior
No errors.

## Minimal reproduction of the problem with instructions
Install the aforementioned packages. When you import something out of the kendo-all-vue-wrapper package, you should get an error about several of the Barcode components being re-exported.

## What is the motivation or use case for changing the behavior?
So that I don't have to manually edit a type file.

## Environment

Package versions:

```
2019.3.1023
```

Browser:

- Chrome (desktop) version XX

System:
- TypeScript version: 3.6.4
- Node version: 10.13
- Platform:  Windows

**Comment by zdravkov** [comment]
We have inspected the issue deeper and decided to keep the 'kendo-all-vue-wrapper' package only for a CDN cases and recommend installing separate packages when npm is used.
