### ISSUE TITLE
Include field to aria-label attribute of a.k-grid-filter element

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5505]
Currently the aria-label attribute is showing only "Filter". That does not give enough information to the screen readers about what fields can be filtered.

![image](https://user-images.githubusercontent.com/11771009/71819614-0fb4f800-3095-11ea-8f33-e7ffe11847f9.png)

We should include the relevant field name to aria-label so screen readers would read out what fields can be filtered.

### Environment

* **Kendo UI version:** 2019.3.1023
* **Browser:** [all]

**Comment by GaloisGirl** [comment]
Duplicate of #3388 .
