### ISSUE TITLE
Imported in the Spreadsheet Excel file that contains a Shape cannot be exported to xlsx

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5517]
### Bug report
If an Excel file that contains Shapes is imported in the Spreadsheet, the imported content cannot be exported back to '.xlsx' file. Saving the imported content to Excel throws an error in the console. 

### Reproduction of the problem
1. Open [this demo](https://demos.telerik.com/kendo-ui/spreadsheet/index)
2. Import the attached "Download Issue.xlsx" file that has one shape and one Image in the Sheet1.
3. The file import will be successfully executed. The shape from the file is not visible in the Spreadsheet(this is expected behavior as the Spreadsheet component does not support Shapes, so they are ignored during the import process)
4. Export(save) the Spreadsheet content as Excel file

### Current behavior
Exporting the Spreadsheet content throws an error in the console: 
![image](https://user-images.githubusercontent.com/41293735/72320164-c7579480-36a9-11ea-917d-28a223c51810.png)

### Expected/desired behavior
The Spreadsheet content should be exported to Excel file that doesn't contain the shapes from the imported file

### Environment

* **Kendo UI version:** 2019.3.1023
* **jQuery version:** x.y
* **Browser:** [all] 

[download-issue.zip](https://github.com/telerik/kendo-ui-core/files/4057777/download-issue.zip)

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1556020

**Comment by mishoo** [comment]
Can't reproduce.
