### ISSUE TITLE
MultiSelect selected items on top

### ISSUE THREAD

**Issue by aaa1902** [telerik/kendo-ui-core#5519]
Is there an out of the box way to sort the selected items on top of the list?

**Comment by zdravkov** [comment]
Currently such behavior that is built in the widget. If you have other similar questions I would recommend you to use [Kendo forums ](https://www.telerik.com/forums/kendo-ui)of support tickets as we keep this repository for the bugs in the component. 
You could also submit feature requests in our portal [here](https://feedback.telerik.com/kendo-jquery-ui?_ga=2.257416653.731489224.1579501181-290485417.1536731675).

Regards,
Plamen
