### ISSUE TITLE
Extend PDFViewer PDF.js options to include cMap configuration for the file

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5521]
### Extend PDFViewer PDF.js options to include cMap configuration for the file
- [x] Extend the API reference:
- [x] Extend all wrappers.
For further info: https://github.com/mozilla/pdf.js/issues/11214#issuecomment-538932555

Further info in the following thread:
https://supportheroes.telerik.com/ticket/1448614

**Comment by veselints** [comment]
PR here: https://github.com/telerik/kendo/pull/11098

**Comment by mparvanov** [comment]
- [ ] MVC5 wrappers "File Not Found" error is thrown when setting Url together with CMap properties:"
```
@(Html.Kendo().PDFViewer().Name("pdfviewer1")
       .PdfjsProcessing(pdf => pdf.File(Url.Content("~/Content/web/pdfViewer/sample.pdf")))
       .Height(1200)
    )

    @(Html.Kendo().PDFViewer().Name("pdfviewer2")
        .PdfjsProcessing(pdf => pdf
            .File(c => c
                .CMapUrl("")
                .CMapPacked(true)
                .Url("~/Content/web/pdfViewer/sample.pdf")
        ))
        .Height(1200)
    )

Actual:  
https://monosnap.com/file/PyPUUh6eIuxYkJUMzpKh0PKRByLlBq
Expected:
https://monosnap.com/file/VeDXhRsp64AosjiqleQ5PXKCGXl9UL
```

**Comment by veselints** [comment]
The correct way to define the PDF viewer using the fluent API instead of a string for the `File()` method is:
```
@(Html.Kendo().PDFViewer().Name("extended")
    .PdfjsProcessing(pdf => pdf
        .File(c => c
            .CMapUrl("")
            .CMapPacked(true)
            .Url(Url.Content("~/Content/web/pdfViewer/sample.pdf"))
        )
    )
    .Height(1200)
)
```

Note how the string is passed to the `Url()` method: `.Url(Url.Content("~/Content/web/pdfViewer/sample.pdf"))`. It should follow the same pattern as when used directly in the `File()` method: `.File(Url.Content("~/Content/web/pdfViewer/sample.pdf"))`
