### ISSUE TITLE
"Paste" option not available in the browser contextmenu on right click in the Editor

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5526]
### Bug report
Regression introduced in v2019.2.619. 

### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/EYofAbaJ) example.
1. Copy some text in the clipboard.
2. Right-click the content area of the Editor.

### Current behavior
The "Paste" option is missing from the contextmenu. The only way to make it appear is to right-click the top left corner of the Editor's content area. 

### Expected/desired behavior
The "Paste" option is present in the contextmenu, regardless of where exactly in the Editor's content area the right-click is performed. 

### Environment

* **Kendo UI version:** 2020.1.114
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by jaandric** [comment]
In which version was this fixed?

**Comment by IvanDanchev** [comment]
> In which version was this fixed?

Version 2020.1.219
