### ISSUE TITLE
FileManager's ContextMenu and ToolBar events cannot be handled

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#5530]
### Bug report
ContextMenu open event cannot be handled

### Reproduction of the problem
```js
contextMenu: {
  open: function(){
     console.log("nothing happens!");
  }
}

```
### Current behavior
The console.log is not called

### Expected/desired behavior
The event to be fired

### Workaround

Add the following line of code before initializing the FileManager: 

```js
kendo.ui.filemanager.ContextMenu.fn.events.push("open");
```

**Comment by Dimitar-Goshev** [comment]
The events can be handled in Kendo UI for jQuery. Expose them in wrappers as well.

**Comment by Iankodj** [comment]
Adding those events is not so straightforward in the wrappers and we won't be able to deliver them for the SP release. I am logging this as an enhancement for the R2 - https://github.com/telerik/kendo-ui-core/issues/5598

**Comment by Dimitar-Goshev** [comment]
@Iankodj Thank you for the update. Closing this issue now.
