### ISSUE TITLE
PDFViewer scroll beyond the start/end of the PDF causes browser to be unable to scroll in the other direction for a moment

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5534]
### Bug report
PDFViewer scroll beyond the start/end of the PDF causes the browser to be unable to scroll in the other direction for a moment. Whereby the "hop" effect that triggers when scrolling beyond the topmost or bottommost bound of the document stops the user from scrolling in the other direction when that animation is playing out.  In other words, if I scroll to the bottom of the document, that effect starts, and when I attempt to scroll up while it’s happening, that doesn’t work at all.

It could be reproduced easily in IE, but in other browsers too.

### Reproduction of the problem
Review the issue on the Index demo: https://demos.telerik.com/kendo-ui/pdfviewer/index

### Expected/desired behavior
Scroll in the other direction should not be stopped.

### Environment
* **Kendo UI version:** 2020.1.114
* **Browser:** [all]

**Comment by veselints** [comment]
Rising priority as reported by the AJAX team.

**Comment by eyupyusein** [comment]
An acceptable fix can be to change SNAPBACK_DURATION to 200 (line 28 from this code):
[https://github.com/telerik/kendo/blob/6f8bce70e14631e65601195e97a4c914c7f2c545/src/kendo.mobile.scroller.js ](https://github.com/telerik/kendo/blob/6f8bce70e14631e65601195e97a4c914c7f2c545/src/kendo.mobile.scroller.js )

**Comment by Dimitar-Goshev** [comment]
This issue is fixed by https://github.com/telerik/kendo-ui-core/issues/5168
