### ISSUE TITLE
Dialog Tag Helper does not render actions

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5535]
### Bug report
Dialog Tag Helper does not render actions

### Reproduction of the problem
Run the Tag Helper Dialog demo: https://demos.telerik.com/aspnet-core/dialog/tag-helper

### Expected/desired behavior
When configured action buttons should be present in the Dialog

### Environment
* **Kendo UI version:** 2020.1.114
* **Browser:** [all]

**Comment by Iankodj** [comment]
The issue is a result of a missing closing p tag in the content tag of the Dialog. It is not a bug in the source code.
