### ISSUE TITLE
Navigation does not work on clicking a PanelBar item with url set

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5537]
### Bug report
Regression introduced in R1 2020. Related to #4741

### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/EHiVUTag) example.
1. Click on **Item1** or on **SubItem2**

### Current behavior
The page does not navigate to the url set in the item's data.

### Expected/desired behavior
The page navigates to the url set in the item's data.
[Dojo 2019.3.1023](https://dojo.telerik.com/@Dimitar-Goshev/UtUzIQaS)

### Environment
* **Kendo UI version:** 2020.1.114
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
@Juveniel After the fix, the scenario from the related issue no longer works [Dojo Snippet 2020.1.114](https://dojo.telerik.com/@Dimitar-Goshev/UbaCEhix) - it is not possible to toggle checkbox state.
