### ISSUE TITLE
Expose click handler for FileManager Toolbar and ContextMenu commands

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5539]
### Bug report
Expose click handler for FileManager Toolbar and ContextMenu commands. Currently, the click could not be handled. That would be an easy way to execute some action when a custom button is placed on the Toolbar / ContextMenu.

**Comment by Iankodj** [comment]
Simple custom tool example to test out the click handler in MVC and Core wrappers: 

```csharp
items.Add().Type("button").Text("Custom").Click("clickHandler");
```

```js
    function clickHandler() {
    }
```

**Comment by Dimitar-Goshev** [comment]
For the ContextMenu we will expose its events by https://github.com/telerik/kendo-ui-core/issues/5530 . Then ContextMenu's `select` event should be used to handle the click of custom menu items.
