### ISSUE TITLE
FileManager service fails to add new file / rename an item on root level in MVC

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5540]
### Bug report
FileManager service fails to add new file/rename an item on root level in MVC

### Reproduction of the problem
* Run a FileManager MVC demo: https://demos.telerik.com/aspnet-mvc/filemanager/events
* Try to upload a file at root level- the upload will fail
* Try to rename the folder present on the root level - that would result in a server error;

### Expected/desired behavior
Rename and Upload should be executed properly

### Environment
* **Kendo UI version:** 2020.1.114
* **Browser:** [all]

**Comment by veselints** [comment]
The issue should be caused by the `ContentProviderController.VirtualizePath` implementation:
```cs
protected FileManagerEntry VirtualizePath(FileManagerEntry entry)
{
	entry.Path = entry.Path.Replace(Server.MapPath(ContentPath), "").Replace(@"\", "/");
	return entry;
}
```

**Comment by mparvanov** [comment]
The proper access permissions has been granted to the root level folder
