### ISSUE TITLE
Enabling cell close not working in Grid Inline Editing 

### ISSUE THREAD

**Issue by Ram-97** [telerik/kendo-ui-core#5543]
According to [Documentation](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/methods/closecell), close cell method was not available for inline edit mode.
Is there a way to close the cell for particular columns in grid inline editing mode.

Thanks in advance.

**Comment by dmanova** [comment]
In some use cases, closeCell could be used with inline edit mode the same way as in incell mode.
You may also try jQuery blur or focus events.

**Comment by Ram-97** [comment]
Thanks @dmanova.
If possible please share the runnable demo

**Comment by dmanova** [comment]
The example on the page you refer works the same for inline and incell edit mode.
