### ISSUE TITLE
Could not scroll Mobile List View in Android 10 but tap event is fired

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-ui-core#5548]
### Bug report
Tap event on kendoMobileListView is triggered faster in Android 10 mobile devices than it was in previous Android versions. This makes scrolling almost impossible.

Reported in ticket: 1449940

### Reproduction of the problem
The problem could be reproduced in this dojo:
https://dojo.telerik.com/EfOJOMuT

### Current behavior
List View is tapped when touching for a while and this fires the tap event, but it should be able to scroll it for a short touch and tap for a long one (long time).

### Expected/desired behavior
List View is scrolled when touching it for a while.

### Environment

* **Kendo UI version:** 2015.2.624
* **jQuery version:** 1.9.1
* **Browser:** [Mobile Chrome 79,  Android 10 ]

**Comment by michele-matriciani** [comment]
Hi @dmanova, using a newer Kendo version should solve the problem.

**Comment by dmanova** [comment]
Yes indeed. This is not reproducible with the latest version (2020.3.1118), so closing the issue.
