### ISSUE TITLE
JS error on clear and blur DatePicker input 

### ISSUE THREAD

**Issue by NikoPenev21** [telerik/kendo-ui-core#5550]
### Reproduction of the problem

DatePicker throws JS error "Cannot read property '_focus' of undefined" in the following scenario:

1. Focus element

2. Select all text inside

3  Press Backspace or Delete

4. Remove focus from the element by clicking outside

Dojo to reproduce: https://dojo.telerik.com/uZAhiHuC

Reported in #1450532

**Comment by dmanova** [comment]
Raising priority, after reported in ticket 1451312.

**Comment by Bjego** [comment]
We are facing the same issue. 
Is there any preview package with a fix? 

As a workadound, I just rolled back to 2019.3.1114.
