### ISSUE TITLE
ContextMenu in Scheduler does not open under Safari in Desktop of Ipad 13.3

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#5552]
### Bug report

ContextMenu in Scheduler does not open under Safari in Desktop of Ipad 13.3

### Reproduction of the problem
Open the following dojo with Ipad under Safari in Desktop mode: https://dojo.telerik.com/@nenchef/uVatuzaf/5 
1. Try open the ContextMenu on a certain slot.

### Current behavior
The Context Menu does not open

### Expected/desired behavior
The Context Menu should get opened.

### Environment

* **Kendo UI version:** 2019.3.1023
* **Browser:** [Safari]

**Comment by martintabakov** [comment]
Also reported in ticket #1512508.

**Comment by yawaweb** [comment]
I had the same problem

**Comment by veselints** [comment]
While testing this, could you also test the following scenario:
https://github.com/telerik/kendo-ui-core/issues/5300

I believe the fix would provide a global solution for iPad 13+ problems.

**Comment by Dimitar-Goshev** [comment]
The Spreadsheet issue is not fixed with this fix.
The Context menu issue is fixed. A small change in the snippet from the demo is required to properly identify the target and display "Copy" menu item on a Scheduler event - e.event.target should be used - `var text = $(e.event.target).hasClass("k-event") ? "Copy" : "Paste";`

```
    $("#contextMenu").kendoContextMenu({
        filter: ".k-event, .k-scheduler-table td",
        target: "#scheduler",
        open: function(e) {
          contextMenuIsOpen = true;
          var menu = e.sender;
          var text = $(e.event.target).hasClass("k-event") ? "Copy" : "Paste";

          menu.remove(".myClass");
          menu.append([{text: text, cssClass: "myClass" }]);
        },
      	close: function(e) {
          contextMenuIsOpen = false;
        }
    });
```

**Comment by aabhishek1** [comment]
Hi, could anyone tell me what is the code fix for this issue

**Comment by Dimitar-Goshev** [comment]
@aabhishek1 The fix was adding [the following lines to kendo.core.js](https://github.com/telerik/kendo-ui-core/blob/e00b3a4c868277477613b429d8c4cf0e1cbb02a5/src/kendo.core.js#L2253-L2260).
