### ISSUE TITLE
Removing items from a listview tied to pager / datasource leaves empty page and incorrect range

### ISSUE THREAD

**Issue by codylindley** [telerik/kendo-ui-core#556]
When removing data from a datasource tied to a kendo ui pager, the page you're on will not change when all list items are removed. 

For example, if you go to http://demos.telerik.com/kendo-ui/listview/editing (or, ) and go to the last page and start removing items until the page has no more items. The page, while removed from pager, does not change in the list view. I.e. You just see a blank page, instead of jumping to the last page that actually has items.

Here is a video of this bug: http://recordit.co/e67VXSZ64P

Notice the items XX – XX is wrong as well. Everything is ok once you click on the last page, but shouldn't it do this by default?

**Comment by vladimirivanoviliev** [comment]
Current behavior is expected:
http://www.telerik.com/forums/deleting-last-remaining-row-on-kendo-grid-on-the-last-page-does-not-go-to-the-previous-page#rRNV6--g1E2eePmukZQ2gw
