### ISSUE TITLE
When more than one records in Bar Chart have the same category name only the first one is shown 

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-ui-core#5562]
### Bug report
When more than one records in Bar Chart have the same category name only the first one is shown and it may get the wrong value of the next one.

Refer to ticket ID 1451312 for a similar issue.

### Reproduction of the problem
Check the "Mon" category in this dojo:
https://dojo.telerik.com/UweRIDiP

### Current behavior
When more than one category with the same name the next one is not shown and the first one gets the highest value.

### Expected/desired behavior
All categories are shown and have the proper value.

### Environment

* **Kendo UI version:** 2020.1.114
* **jQuery version:** 1.12.3
* **Browser:** [all  ]

**Comment by danielkaradachki** [comment]
Points with the same category are aggregated. You are seeing the second point value because the default aggregate is max:

https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart/configuration/series.aggregate
