### ISSUE TITLE
Grid's layout breaks when "scrollable: false" and columns' width exceed 960px

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5566]
### Bug report

Grid's layout breaks when having columns with defined widths which sum exceeds 960px and the scrollable property is set to false.

Regression introduced in 2020.1.114

### Reproduction of the problem
[Open this Dojo](https://dojo.telerik.com/UxIVOXId) in fullscreen and see Grid's layout.

If you change the Kendo UI version to **2019.3.1023**, Grid's toolbar is correct

### Current behavior
Grid's layout is breaking
![image](https://user-images.githubusercontent.com/41293735/73448970-c8a3e500-436a-11ea-9eec-4373d6e77523.png)

### Expected/desired behavior
Grid's layout shouldn't break. 
![image](https://user-images.githubusercontent.com/41293735/73449328-93e45d80-436b-11ea-8877-9d48d54d9ed1.png)

### Environment

* **Kendo UI version:** 2020.1.114
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by ag-petrov** [comment]
This is not a bug. The correct behavior is to overflow the grid and is mentioned in the documentation - https://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance/width . If it was working in prior versions it was by chance. Generally setting width for the container and widths for the columns which to overflow the container is a configuration issue.
