### ISSUE TITLE
Grid with virtual columns scroll gives JS error when columns width is in "em"

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-ui-core#5568]
### Bug report
Grid with virtual columns scroll is hiding data and gives JS error when the width of the columns is in "em". 

Reported in ticket 1451456.

### Reproduction of the problem
Scroll horizontally multiple times the grid in this sample:

http://dojo.telerik.com/odiKaZEB

### Current behavior
Data values in the columns are hidden. There is an error:

```
kendo.all.js:66607 Uncaught TypeError: Cannot set property 'colSpan' of undefined
    at init._virtualCols (kendo.all.js:66607)
    at init._templates (kendo.all.js:66616)
    at init.refresh (kendo.all.js:67866)
    at HTMLDivElement.<anonymous> (kendo.all.js:65533)
    at HTMLDivElement.dispatch (jquery-1.12.3.min.js:3)
    at HTMLDivElement.r.handle (jquery-1.12.3.min.js:3)
```

### Expected/desired behavior
Data is visible and no errors appears.

### Environment

* **Kendo UI version:** 2020.1.114
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by ag-petrov** [comment]
This is not a bug. Currently the width of the columns can be set only in pixels when virtual columns are used. Setting it in percents will not work in all scenarios. We may integrate a solution to dynamically extract the width from the headers but this would require jumping every time in the DOM to check the widths which might cause a performance panalty.
