### ISSUE TITLE
Custom editor resets initial value

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#5582]
### Bug report

The main problem is that the value is preserved and passed through the `context.range.value()` method so that it can be validated against the custom logic.

### Reproduction of the problem
https://dojo.telerik.com/iJOjivIN

1. Type some value in the color cell
2. Open editor

### Current behavior
`context.range.value()` return null

### Expected/desired behavior
`context.range.value()` to return the initial value

### Environment

* **Kendo UI version:** all

**Comment by martintabakov** [comment]
The bug doesn't reproduce with the latest version - https://dojo.telerik.com/iJOjivIN/4. Closing this bug for now until further information is provided.
