### ISSUE TITLE
While editing a Gantt task name navigating in the input field with mouse click is not possible

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5583]
### Bug report
While editing a Gantt task name navigating in the input field with a mouse click does not work. Double-clicking on a cell enters edit mode and positions the cursor at the end of the text. Moving the cursor using the mouse does not work while navigating in the input field with the keyboard works.

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/iJUSESIb)
1. Double-click the title of the first task
1. Try to click elsewhere in the input field to move the cursor.

### Current behavior
Clicking in the input field does not move the cursor to the selected position

### Expected/desired behavior
Clicking in the input should move the cursor to the selected position

### Environment

* **Kendo UI version:** 2019.2.619
* **Browser:** [all]

**Comment by Iankodj** [comment]
Related to: https://github.com/telerik/kendo/commit/903aa55142590c9eed449344e23bede10e949949?w=1
