### ISSUE TITLE
ListView MVVM endless scrolling doesn't work 

### ISSUE THREAD

**Issue by metoule** [telerik/kendo-ui-core#5585]
### Reproduction of the problem
I'm trying to set up an MVVM `ListView` with endless scrolling. I'm setting up the DOM element with the `data-scrollable="endless"` attribute, but it seems to be ignored (`data-scrollable="scroll"` also seems to be ignored):

    <div id="listView-mvvm" 
            data-role="listview" 
            data-bind="source: products" 
            data-template="template" 
            data-scrollable="endless">
    </div>

Complete example: https://jsfiddle.net/Metoule/obqs9na5/

Comparison MVVM vs non MVVM: https://jsfiddle.net/Metoule/72z3oq0b/

### Current behavior
The `ListView` ignores the `scrollable` property, and no scrollbar is set up. Endless scrolling doesn't work. 

### Expected/desired behavior
The `ListView` should be set up the same way via MVVM or via direct call to `.kendoListView`

### Environment

* **Kendo UI version:** 2020.1.114
* **jQuery version:** 2020.1.114 (via telerik cdn)
* **Browser:** Tested with Chrome 79 and Firefox 72

**Comment by dmanova** [comment]
Please consider that after the fix additional styles should be applied to have the endless scrolling work. The content should exceed the listview height value and "display: flex" should be specified. In the current example, adding the following code should make the endless scrolling available:
`style="height: 180px; display: flex;"`

**Comment by diegobarriosdev** [comment]
Hi @dmanova . I'm trying this with this fix with version 2020.3.1118 of Kendo without success. Could you please, confirm to me from which version is the bugfix available? CC @metoule

**Comment by diegobarriosdev** [comment]
@dmanova. Here you can find an example: https://dojo.telerik.com/@diegobarriosdev/oBecelIk

![image](https://user-images.githubusercontent.com/10930914/229036830-3a0eceab-052d-4852-8187-e0f386289827.png)

**Comment by diegobarriosdev** [comment]
Hi @dmanova. This looks working with 2023.1.314 - but not works with 2020.3.1118. Could you confirm which version this start to work, please? [It's possible to find an example here](https://dojo.telerik.com/@diegobarriosdev/oBecelIk)

**Comment by dmanova** [comment]
Hi @diegobarriosdev. As it seems you should specify also the height of the ListView either by inline styles, e.g.:
`style="height: 500px; overflow: auto"`

or after Kendo UI 2021 R1 SP1 version (2021.1.224) you could use:
`data-scrollable="endless" data-height="500px"`

It seems the fix is effective after Kendo UI 2021 R1 SP1 version (2021.1.224), but with 2020 R3 SP1 just a part of it has been fixed.
