### ISSUE TITLE
Dropdown not styled correctly in AngularJS mobile application

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#559]
Can be reproduced [here](http://dojo.telerik.com/@Kiril/elAPO)

Reported in ticket ID 907349

**Comment by KirilNN** [comment]
In order to work correctly the application needs to be initialized on the `<body>` element. Here is the working scenario:

http://dojo.telerik.com/eKUro

**Comment by bundyo** [comment]
And to have all tags closed ;)
