### ISSUE TITLE
Popup is not closed when selecting new range included in the previous one

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5592]
1. Run this example: https://demos.telerik.com/kendo-ui/daterangepicker/index
1. Select a range - e.g. 03 Feb - 15 Feb
1. Open the picker popup 
1. Select a new range within the previous one - e.g. 08 Feb - 13 Feb

The popup is not closed.

We should provide an option to close the popup in this scenario.

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible with 2024.3.806
