### ISSUE TITLE
With column virtualization having attributes on a column applies the styles to previous column

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5593]
### Reproduction of the problem
1. Run this dojo - https://dojo.telerik.com/OdIfezab
1. Scroll to the last column

### Current behavior
Styles are applied to the next to last column

### Expected/desired behavior
Style should be applied to the last column.

### Environment

* **Kendo UI version:** 2020.1.114

**Comment by ag-petrov** [comment]
Fixed in the latest version.
