### ISSUE TITLE
FileManager - renaming a folder does not update the folder name in the breadcrumb

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5594]
### Reproduction of the problem
Reproducible in the [demos](https://demos.telerik.com/kendo-ui/filemanager/index). 
1. Select the Images folder in the treeview
2. Right click the Images folder and rename it

### Current behavior
The breadcrumb does not update with the new folder name. Note that if you select another folder (e.g. Documents) after renaming Images and navigate back to the renamed folder the breadcrumb properly displays its new name. 

### Expected/desired behavior
The change in the folder name is reflected in the breadcrumb. 

### Environment

* **Kendo UI version:** 2020.1.114
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Iankodj** [comment]
With recent updates, renaming the selected folder navigates to its parent. That way the folder in the breadcrumb is in sync with the new name when selected again.
