### ISSUE TITLE
Menu - submenu does not close on item selection, if navigation is triggered programmatically

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5596]
### Bug report
Reproducible in Chrome and Firefox. Not reproducible in IE11. 

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/elUvIDEd/2) example.
There are two Menus. In the first one navigation is triggered from the function passed to the "Sub Item 2" item's **url** option. In the second Menu navigation is triggered in the Menu's select event handler. 

1. Hover "Item 2" and click "Sub Item 2"
The wiki page will open in a new tab.
2. Check the Menu in the original tab with the dojo.

### Current behavior
Doing this in the first Menu, results in the submenu remaining open.

### Expected/desired behavior
The submenu should close in both scenarios, since **closeOnClick** is enabled by default and the select event fires before triggering the navigation.

### Environment

* **Kendo UI version:** 2020.1.114
* **jQuery version:** x.y
* **Browser:** [Chrome XX | Firefox XX]

**Comment by martintabakov** [comment]
The behaviour appears to be expected. The API of the [clickOnClose](https://docs.telerik.com/kendo-ui/api/javascript/ui/menu/configuration/closeonclick) states in brackets "provided they won't navigate".
