### ISSUE TITLE
Selecting a new range with the same end date as previous sets it as a start date

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5597]
### Reproduction of the problem
1. Run [this dojo](https://dojo.telerik.com/oRAMALAf) or [DateRangePicker demo](https://demos.telerik.com/kendo-ui/daterangepicker/index)
1. Select a range - e.g. 3 Feb - 10 Feb
1. Select a new range  - e.g. 7 Feb - 10 Feb

### Current behavior
Feb 10 is set as start date

### Expected/desired behavior
The new range should be applied and Feb 10 should be end date.

### Environment

* **Kendo UI version:** 2020.1.114
* **jQuery version:** all
* **Browser:** [all]

**Comment by ag-petrov** [comment]
This was a design decision when implementing the widget. If you start form 3-10 and select 4 the new range will be 4-10, later you can decrease the range if you select a number between 4-10 for example 9, which will select 4-9 as a range. I do not consider this a bug, if we want another type of selection behavior it should be thoroughly documented, explained and approved by the UX. @ivelina-penkova or @nedevp can provide us guidance in this matter.
