### ISSUE TITLE
Editor: Pasting from Word in IE forces the next typing to a new paragraph

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5606]
### Bug report
Editor: Pasting from Word in IE forces the next typing to a new paragraph

### Reproduction of the problem
* In Word a few lines of text and apply some custom styling
* Select the full text and copy it
* Run the Editor Index demo: https://demos.telerik.com/kendo-ui/editor/all-tools in IE
* Clear the Editor content
* Paste the copied content in the Editor
* Spart typing. The cursor will automatically move to the next line and will use the default styles, and not the styles as per the pasted content

### Expected/desired behavior
Typing after pasting should retain the same line and styles as the pasted content (see how behaves Chrome).

### Environment
* **Kendo UI version:** 2020.1.114
* **Browser:** [IE]

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
