### ISSUE TITLE
Cannot set the value of the Badge to 0

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5613]
### Bug report

When trying to set the value of the Kendo Badge to 0 the value is not changed.

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/IPOJeXoX)
1. The initial value of 7 is not changed after calling the value(0) method.

### Current behavior
The value of the Kendo Badge is not set to 0 when calling the value(0) method.

### Expected/desired behavior
The value of the Kendo Badge should be set to 0 when calling the value(0) method.

### Environment

* **Kendo UI version:** 2020.1.114
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
A workaround for the issue is to set the value of the Badge as a string - value("0").

**Comment by PreslavKozovski** [comment]
Should be fixed by https://github.com/telerik/kendo/pull/10845
