### ISSUE TITLE
Current page number is not visible in Bootstrap v3 theme

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5621]
### Reproduction of the problem
1. Open any demo with pager.
1. Select Bootstrap v3 theme

https://demos.telerik.com/kendo-ui/grid/index

### Current behavior
The current page number is not visigle:
![image](https://user-images.githubusercontent.com/11771009/75026728-1f05ce80-54a6-11ea-8570-decad6bd7d91.png)

### Expected/desired behavior
Current page number should be visible

### Environment

* **Kendo UI version:** 2020.1.219
* **Browser:** [all]

**Comment by PreslavKozovski** [comment]
No longer replicable, probably fixed by -  https://github.com/telerik/kendo/commit/0685194b4fcf214a90b4794dc1f53fabfbfb2e03
