### ISSUE TITLE
The Editor Toolbar configuration option Clear() in ASP.NET Core does not clear the Toolbar

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5624]
### Bug report

When configuring the Editor's Toolbar using `.Tools(tools => tools.Clear())` in ASP.NET Core application the default Toolbar is rendered. In ASP.NET MVC applications the `.Tools(tools => tools.Clear())` configuration renders an Editor with an empty toolbar.

### Reproduction of the problem
[TelerikAspNetCoreApp24.zip](https://github.com/telerik/kendo-ui-core/files/4244166/TelerikAspNetCoreApp24.zip)

### Current behavior
When configuring the Editor's Toolbar using `.Tools(tools => tools.Clear())` in ASP.NET Core application the default Toolbar is rendered.

### Expected/desired behavior
When configuring the Editor's Toolbar using `.Tools(tools => tools.Clear())` in ASP.NET Core application an emplty Toolbar should be rendered.

### Environment

* **Kendo UI version:** 2020.2.219
* **Browser:** [all]

**Comment by magicxor** [comment]
This issue is still present in the latest version of Telerik.UI.for.AspNet.Core (2021.1.224).
