### ISSUE TITLE
Validation attributes not rendered on Kendo editors if ViewData contains model property name

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#5641]
### Bug report

Validation attributes are not rendered on Kendo editors if ViewData contains same key as the model.

### Reproduction of the problem
```cs
@{
  ViewData["Title"] = "Home Page"; 
}

@using (Html.BeginForm())
{
  @Html.Kendo().TextBoxFor(model => model.Title)
}

<script>
  $(function () {
    $("form").kendoValidator();
  });
</script>
```
### Current behavior

Validation attributes are not rendered.

### Expected/desired behavior

Validation attributes should be rendered on the input element.

### Environment

* **Kendo UI version:** 2020.1.219
* **Browser:** [all]

**Comment by gh5692** [comment]
I just ran into this in version 2021.2.511, when a grid field would not validate. Mentioning it on the demo page and in the documentation (as this issue is over a year old) might save people a lot of time and frustration.

**Comment by alestoya** [comment]
Reported in 1608512
