### ISSUE TITLE
Spelling correction leads to DOM change and incompatibility with the fontname tool

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#5644]
### Bug report

Correcting a misspelled word with some fontname decoration results to Chrome changing the DOM element to font tag and style to face attribute. 

This leads to the font tool not recognizing the font name and shows inaccurate value. 

### Reproduction of the problem
https://demos.telerik.com/kendo-ui/editor/all-tools

1. Delete all content
2. Type 'Heloo' and change its font name
3. Correct the misspelled word. 

### Current behavior
Dom is changed to font tag with face attribute. And the font tool not showing the font name.

### Expected/desired behavior
Either the Editor to retain or bring back the proper tag and style. Or update the font name to recognize the font from font tag and face attribute

### Environment

* **Browser:** [ Chrome 80.0.3987.122 ]

**Comment by PekoPPT** [comment]
Also reported in ticket: 1472259

**Comment by alana1** [comment]
I would like to know the status of this issue? Is this something that is planned to be fixed?
