### ISSUE TITLE
Change event in ComboBox not triggered, when the same value is cleared in the previously triggered change event

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#5646]
### Bug report
Change event not triggered, when the same value is cleared in the previously triggered change event. The scenario is covered in this documentation article:
https://docs.telerik.com/kendo-ui/controls/editors/combobox/how-to/customize/prevent-custom-values
Reported in TID: 1456211

Repliclable with 2019 R1 SP1

### Reproduction of the problem
Use the example ai the doc article and follow these steps:
1. type 'asd' in the input of the widget
1. blur the input (at this point the value will be cleared)
1. focus the input and tyle 'asd' again
1. blur the widget

### Current behavior
The Change event is not triggered a second time for the same value

### Expected/desired behavior
The Change event should be triggered regardless of the value 

### Environment
* **Kendo UI version:** 2020.1.219
* **Browser:** all

**Comment by mparvanov** [comment]
- [ ] No change event is triggered in IE after blurring the Combobox input

**Comment by Iankodj** [comment]
This is a regression due to this change: https://github.com/telerik/kendo/commit/7031eeaee961341d9784cef64be9f23038b9a4e9
