### ISSUE TITLE
Editor table resize handler doesn't check if table is still alive

### ISSUE THREAD

**Issue by MaceWindu** [telerik/kendo-ui-core#5650]
Error:
```js
"Uncaught TypeError: Cannot read property 'style' of undefined"

_getMaxDimensionValue(...) at kendo.js (33872, 1)
	_resizeWidth(...) at kendo.js (33786, 1)
	resize(...) at kendo.js (33776, 1)
	_onResizeHandleDrag(...) at kendo.js (34004, 1)
	proxy(...) at jquery.js (10268, 1)
	trigger(...) at kendo.js (140, 1)
	_onDrag(...) at kendo.js (33380, 1)
	proxy(...) at jquery.js (10268, 1)
	trigger(...) at kendo.js (140, 1)
	_trigger(...) at kendo.js (13379, 1)
```

See how-to reproduce demo video. E.g. here I select editor content with `Ctrl+A` removing using `Del` while dragging resize handle.

![Table-resize](https://user-images.githubusercontent.com/1099238/76003113-e505e500-5f07-11ea-89dc-d3bc141ab986.gif)

* **Kendo UI version:** up to  2020.1.219

**Comment by martintabakov** [comment]
The issue is not reproduceable with the latest version - https://dojo.telerik.com/aXuFAfot/2. Closing the item until further information is provided.
