### ISSUE TITLE
TypeScript definition for Grid/GridOptions does not have "search"

### ISSUE THREAD

**Issue by DaleyKD** [telerik/kendo-ui-core#5652]
### Current behavior
Unable to use the "search" property on `kendo.ui.GridOptions` in TypeScript.
```
    interface GridOptions {
        name?: string;
        allowCopy?: boolean | GridAllowCopy;
        altRowTemplate?: string|Function;
        autoBind?: boolean;
        columnResizeHandleWidth?: number;
        columns?: GridColumn[];
        columnMenu?: boolean | GridColumnMenu;
        dataSource?: any|any|kendo.data.DataSource;
        detailTemplate?: string|Function;
        editable?: boolean | "inline" | "incell" | "popup" | GridEditable;
        excel?: GridExcel;
        filterable?: boolean | GridFilterable;
        groupable?: boolean | GridGroupable;
        height?: number|string;
        messages?: GridMessages;
        mobile?: boolean|string;
        navigatable?: boolean;
        noRecords?: boolean | GridNoRecords;
        pageable?: boolean | GridPageable;
        pdf?: GridPdf;
        persistSelection?: boolean;
        reorderable?: boolean;
        resizable?: boolean;
        rowTemplate?: string|Function;
        scrollable?: boolean | GridScrollable;
        selectable?: boolean|string;
        sortable?: boolean | GridSortable;
        toolbar?: string | Function | (string | GridToolbarItem)[];
```

### Expected/desired behavior
Let me set `search` without TS throwing an error.

### Environment

* **Kendo UI version:** 2020.1.219
* **@types/kendo-ui:** 2020.1.0
* **jQuery version:** 3.4.1
* **Browser:** all

**Comment by DaleyKD** [comment]
And may I also request that the `interface GridOptions` be made exported so that I can use it as a strong type?

**Comment by dmanova** [comment]
Hi @DaleyKD the search option for the grid is part of the toolbar -> GridToolbarItem. You could use it like this:
`        toolbar: [
            { name: "search" }
        ],`

**Comment by DaleyKD** [comment]
@dmanova : I appreciate the reply.  However, I'm purposefully not using the toolbar.  This refers to the `search` parameter directly off the grid.  Please refer to your own API documentation at: https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/search
