### ISSUE TITLE
Excel file doesn't load correctly in Spreadsheet when its dimension tag is a single cell value

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5659]
### Bug report
The Spreadsheet doesn't' load correctly Excel files which definition of the <dimenson> tag is a single cell, instead of a cell range. 

Test files: [test-2.zip](https://github.com/telerik/kendo-ui-core/files/4311480/test-2.zip)

### Reproduction of the problem
1. Download the test-2.zip file and load the "test.xlsx" file in the Spreadsheet[ here](https://demos.telerik.com/kendo-ui/spreadsheet/index).
2.  The file has data in the “AZ” and “BA” columns and once it is imported in the Spreadsheet the data from the “BA” column is imported in the “AX” column and the values in the AZ column are missing. 

* If the above file is saved in Excel it is correctly loading in the Spreadsheet. In the attached archive there is the “test-copy.xlsx” file which is the saved and correctly working one. Below is the structure of the two files. The one in red is from the "test.xlsx" file and the code in green is from the "test-copy.xlsx" file.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/41293735/76299793-5953d600-62c4-11ea-9fff-6134d69e96fa.png)

### Current behavior
The The "test.xlsx" file is not loading correctly in the Spreadsheet and loses data 

### Expected/desired behavior
The "test.xlsx" file should load correctly in the Spreadsheet without losing data

### Environment

* **Kendo UI version:** 2020.1.219
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by martintabakov** [comment]
The issue doesn't reproduce on the [Spreadsheet Overview demo](https://demos.telerik.com/kendo-ui/spreadsheet/index). The AZ and BA data are correctly positioned as in Excel.
