### ISSUE TITLE
Toolbar - images in overflow buttons are not properly aligned

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5662]
### Reproduction of the problem
[Dojo ](https://dojo.telerik.com/UVowOfiF) example. 

1. Click the overflow button
2. The second button uses an image instead of a font icon and it does not have "middle" vertical alignment

**Workaround**:

```
  .k-overflow-container a>img {
   vertical-align: middle; 
   display: inline-block;
  }
```

### Current behavior
Images are not properly aligned

### Expected/desired behavior
Images are properly aligned

### Environment

* **Kendo UI version:** 2019.1.219
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Juveniel** [comment]
Issue is resolved with 2020 R3 - [https://dojo.telerik.com/UVowOfiF/3](https://dojo.telerik.com/UVowOfiF/3).

Closing the issue.
