### ISSUE TITLE
Window draggable containment option prepends element instead of appending

### ISSUE THREAD

**Issue by austinw-fineart** [telerik/kendo-ui-core#5673]
### Bug report
When using Window with the draggable containment option, the window is prepended to the element instead of appended to. However, the documentation here states that the window is supposed to be appended to this element:
https://docs.telerik.com/kendo-ui/api/javascript/ui/window/configuration/draggable.containment

### Reproduction of the problem
1. https://dojo.telerik.com/imURIgUq
2. Inspect the container and note how the Window element appears before all others

### Expected/desired behavior
Either the current behavior is wrong, or the documentation is.

### Environment

* **Kendo UI version:** 2020.1.219
* **jQuery version:** 3.4.1
* **Browser:** all

**Comment by Juveniel** [comment]
@austinw-fineart when the containment option is used, the Window is inserted in the specified element. Indeed, the wrapper is placed before other elements(prepended). However, this should not be an issue, as the Window has absolute positioning, thus should not cause any issues with other elements in the same container.

In terms of the API documentation - I have updated the wording of the containment option description to prevent confusion in the future.
