### ISSUE TITLE
Selected item in Grid Pager is not visible in LESS Bootstrap theme

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-ui-core#5677]
### Bug report

The selected item in Grid Pager is not visible in LESS Bootstrap theme. The text color is white on white background

### Reproduction of the problem

1.  Go to the following demo: https://demos.telerik.com/kendo-ui/listview/remote-data-binding
1. Select Less Boostrap v3 theme
1. Check the selected page in the pager

### Current behavior
The text color is white on white background

### Expected/desired behavior
The selected page should be visible

### Environment

* **Kendo UI version:** 2019.1.115

**Comment by dmanova** [comment]
Closing as duplicate of #5621
