### ISSUE TITLE
ToCamelCase method doesn't return correct camel-cased result

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5679]
### Bug report

The StringExtensions -> ToCamelCase method(part of  Kendo.Mvc.Extenstions) doesn't return the expected Camel case result.  

* More details in ticket # 1458202

### Reproduction of the problem
Include the  Kendo.Mvc.Extenstions namespace. Define the following in a controller: 
```
        public IActionResult Index()
        {
            string test = "RANDOMStatusId";
            test = test.ToCamelCase();

            return View();
        }
```
Set a debugger and see the value of the "test" variable.

### Current behavior
The returned from the ToCamelCase() method value is "rANDOMStatusId"
![image](https://user-images.githubusercontent.com/41293735/77150277-34b5e600-6a9c-11ea-8bf3-3e43de99b8d8.png)

### Expected/desired behavior
The expected result returned from the ToCamelCase() method value is "randomStatusId"

### Environment

* **Kendo UI version:** 2020.1.219
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by zdravkov** [comment]
There are different implementations of ToCamelCase logic, yet one of the most common ones is to only lower the first letter as we did in out method. If another operations are needed we would rather recommend applying custom logic.

**Comment by failwyn** [comment]
Microsoft, Google, Newtonsoft, Humanizer, et al, all implement this convention consistently, why not kendo?
