### ISSUE TITLE
DropDownTree is not getting model values when it is bound with DataSource

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#5684]
### Reproduction of the problem
When we use DropDownTreeFor and bind the DropDownTree with DataSource the values are not applied

project available in ticket: 1458580

### Environment

* **Kendo UI version:**2020.1.219

**Comment by IvanDanchev** [comment]
In addition to the DataSource remote binding scenario, the model is not properly updated when  server binding is used:

```
@(Html.Kendo().DropDownTreeFor(m => m.ListOfRoles)
    .Checkboxes(c => c.Name("checkedItems"))
    .CheckAll(false)
    .AutoClose(false)
    .BindTo((IEnumerable<ServerCheckboxes.Models.ItemViewModel>)ViewBag.dropdowntreeData, (NavigationBindingFactory<DropDownTreeItem> mappings) =>
    {
        mappings.For<ServerCheckboxes.Models.ItemViewModel>(binding => binding.ItemDataBound((item, category) =>
        {
            item.Text = category.Role;
            item.Value = category.RoleID;
        })
        );
    })
    .Events(e => e.DataBound("onDataBound"))
)
```

A sample project can be found in Ticket ID: 1465800

**Comment by IvanDanchev** [comment]
Update (Ticket ID: 1465800): using a primitive value in the DDT:
```
.ValuePrimitive(true)
```
resolves the issue related to updating the model. So the behavior should be investigated in regards to not using primitive value.

**Comment by mihaela-lukanova** [comment]
Reported in 1564121

**Comment by yanisslav** [comment]
Reported in 1564199
