### ISSUE TITLE
How should pauses be implemented in relation to uploads for Vue ?

### ISSUE THREAD

**Issue by ljlm0402** [telerik/kendo-ui-core#5688]
## I'm submitting a...

* Documentation issue or request

## Current behavior

How should pauses be implemented in relation to uploads for Vue ? 
If you use chunk, the backend (nodejs) asks how to implement it.

Thank you.

**Comment by zdravkov** [comment]
It is rather an back-end question than a bug in the component. 

We don't have an example with Node.js server yet at [our demo here](https://demos.telerik.com/kendo-ui/upload/chunkupload) we have provided an example in the "Sample service" tab with the C# code where is shown sample code of what have to be requested and responded from the server.

In general each request sends a separate file blob and additional string metadata to the server. This metadata is in a stringified JSON format and contains the 'chunkIndex', 'contentType', 'totalFileSize', 'totalChunks', and 'uploadUid' properties. These properties enable the validation and combination of the files on the server. The response also returns a JSON object with the "uploaded" and "fileUid" properties which notify the client what the next chunk is.

If you have furhter question I would recommend you to use either support or forum Kendo channels.
