### ISSUE TITLE
Splitter's collapsed pane should expand after the panes in the component are resized

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5696]
[This Dojo](https://dojo.telerik.com/acUsALoR) has 3 panes which width is defined on the component's initialization and the right pane is collapsed by default. On Splitter's initialization, the right pane can be expanded/collapsed as expected. If after initialization we move the horizontal line between the left and central panes the widths of the panes are reset. This is expected behavior as after a Splitter pane is resized, the assumption is that the user wants the size to be exactly as specified and the panes no longer resize proportionately. 

The described design feature reflects on the functionality of the collapsed pane(the one on right in our example). If after moving the line between the "left" and "central" panes one tries to expand the right pane, it is expanded to "0px". 

Although the behavior of the collapsed pane is expected behavior, we can think about how a pane expanding in a scenario like the described above can result in a visible of the user "expand". 

### Scenario without pane resize
1. Open [the Dojo](https://dojo.telerik.com/acUsALoR)
2. Try to expand the right pane
**Result:** The pane is expanded/collapsed correctly

### Scenario with pane resize
1. Open[ the Dojo](https://dojo.telerik.com/acUsALoR)
2. Move the vertical line between the left and central panes
3. Try to expand the right pane
**Result:** The pane is not expanded on the first try.

**Comment by pepinho24** [comment]
The Resizable panes should have one pane with fluid size (the middle one for example), in order to act as a buffer. With 2024.4.1112, the splitter has a better behavior in regards to expanding the collapsed pane.
