### ISSUE TITLE
dataValueField not present in Autocomplete

### ISSUE THREAD

**Issue by neeldeep** [telerik/kendo-ui-core#570]
This is more like a feature request.
Dropdown has both dataTextField & dataValueField but Autocomplete has only dataTextField.

Can someone please let us know if this will be implemented or any work around for this?

**Comment by underlog** [comment]
Hi, 

Please review the [following search results](https://www.google.com/search?rls=en&q=kendo+ui+autocomplete+datavaluefield). The Telerik forums contain plenty of topics where the subject is discussed and several workarounds are suggested.
