### ISSUE TITLE
Milestone in Gantt is not correctly position in the timeline view, only in Less themes

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#5703]
### Bug report
Milestone in Gantt is not correctly position in the timeline view, only in Less themes
- ~~issue does not exist in Firefox~~ - it is reproducible in Firefox as well

### Reproduction of the problem
Use the following dojo: https://dojo.telerik.com/unoBixak

### Current behavior
![Untitled _ Kendo UI Dojo - Mozilla Firefox 2020-09-08 15 59 53](https://user-images.githubusercontent.com/6614183/92479551-5b074380-f1ec-11ea-85c9-8d50b2008807.png)

### Expected/desired behavior
The milestone should be aligned at 9 a.m precisely. 

### Environment
* **Kendo UI version:** 2020.1.406
* **Browser:** [Chrome 85, FF]

**Comment by Dimitar-Goshev** [comment]
The issue is still reproducible in RTL
