### ISSUE TITLE
.Net Core Radio button renders wrong value

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#5705]
### Bug report

When submitting a form which contains multiple radio buttons and validation fails, the radio buttons in the returned form no longer have correct values. More information and a sample can be found in ticket with ID 1460832.

Related to: https://github.com/telerik/kendo-ui-core/issues/5020

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by veselints** [comment]
A project to be added to the Kendo.Mvc solution and to test with:
[TestRadio.zip](https://github.com/telerik/kendo-ui-core/files/4551159/TestRadio.zip)

**Comment by mparvanov** [comment]
The same issue is observed with MVC Radio Button

**Comment by mparvanov** [comment]
Here is the MVC sample project:

[TelerikMvcApp1.zip](https://github.com/telerik/kendo-ui-core/files/4557066/TelerikMvcApp1.zip)

**Comment by mparvanov** [comment]
In MVC the correct form configuration is:
<form id="formId" action="/Home/Index" method="post">
That way the action method is called properly and the value is passed back properly.
