### ISSUE TITLE
FileManager Destroy method sends multiple delete requests

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#5713]
### Bug report

when selecting multiple folders and deleting them it sends the same delete request multiple times. The more folders are tried to be deleted the more requests it sends.

### Reproduction of the problem
https://demos.telerik.com/aspnet-mvc/filemanager
Select multiple folders and delete them

### Current behavior
Destroy method sends multiple delete requests

### Expected/desired behavior
Only one destroy request per file is sent

### Environment

* **Kendo UI version:** 2020.1.406

Ticket: 1461928
https://feedback.telerik.com/kendo-jquery-ui/1461928-context-method-destroy-sends-multiple-delete-requests

**Comment by aleksandarevangelatov** [comment]
Also reported in Ticker: 1462815

**Comment by jonakirke94** [comment]
Why is this not prioritized higher? It renders the whole component pretty useless when the core delete functionality doesn't work properly and no workaround is provided

**Comment by Iankodj** [comment]
Dojo examples with the DataSource only: https://dojo.telerik.com/oPOdItUJ.
