### ISSUE TITLE
Gantt draggable items in the TreeList are invisible when the width of the TreeList is small

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5714]
### Bug report
When the tasks in the Gantt's TreeList are moved/dragged an item appears over them. When the visible size of the TreeList is small, dragging tasks inside it results in unavailability to understand which task is currently being dragged because the draggable item is partially hidden.

### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/UPOpOqIM)
2. Move the Splitter in the Gantt component to the left, in a way at least half of the initially visible TreeView is hidden.
3. Select Task 2 and drag it.

### Current behavior
The draggable item is initialized with a negative "left" CSS style. The task name is partially visible or not visible at all.
![image](https://user-images.githubusercontent.com/41293735/79482818-02a38f80-801a-11ea-9ef1-fde0ab0173e0.png)

### Expected/desired behavior
The draggable item should be visible. The task name should be visible. 

### Environment

* **Kendo UI version:** 2020.1.406
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Not reproducible with 2023.3.1114 - https://dojo.telerik.com/@Dimitar-Goshev/UbatoJoN
