### ISSUE TITLE
Kendo TreevView Is v-model not supported ?

### ISSUE THREAD

**Issue by ljlm0402** [telerik/kendo-ui-core#5720]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Current behavior

It implements the checkbox to get the checked DataSource through @check, but when moving to another tab, there is a phenomenon that it is initialized, so I wonder if it is possible to bind with v-model.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by zdravkov** [comment]
yes, v-model is currently not supported by the Kendo UI for Vue TreeView wrapper component - one possible approach to achieve similar behavior is to handle the watch of the property, loop through the nodes and check them manually if needed.
