### ISSUE TITLE
Kendo Grid Virtualization Export Excel data-source maximum ?

### ISSUE THREAD

**Issue by ljlm0402** [telerik/kendo-ui-core#5723]
### Bug report

**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our feedback portal](https://www.telerik.com/support/feedback)**

### Reproduction of the problem
_(bug report only)_
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via http://dojo.telerik.com or similar.

### Current behavior
I use saveAsExcel with grid virtualization. However, if the data exceeds 10000, the browser freezes. Is there a solution? If you ever need to communicate with the server, I'm wondering how to split the data fetched through pagesize.

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by dmanova** [comment]
Export to Excel does have its limitations that depend on the browser and hardware specifications when exporting huge amounts of data. For such cases, I would recommend the usage of [RadSpreadStreamProcessing](https://docs.telerik.com/devtools/document-processing/libraries/radspreadstreamprocessing/overview).

Or if you just need to export the data of the current page you could set up [excel.allPages](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/excel.allpages) option to false.
