### ISSUE TITLE
Cannot define OrderID in the DataSource model of the Gantt using the ASP.NET Core wrappers

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5724]
### Bug report
The OrderId field for the Gantt tasks cannot be defined in its datasource using the UI for ASP.NET Core wrappers.

*for more details, please refer to ticket #1461758

### Reproduction of the problem
Create a UI for ASP.NET Core project and try to initialize the Gantt component with a datasource configured similar to the following:

![image](https://user-images.githubusercontent.com/41293735/79840309-6b925b00-83be-11ea-86f5-abfc98039ed9.png)

### Current behavior
The marked "OrderID" definition is not a valid one in UI for ASP.NET Core 

### Expected/desired behavior
The datasource configuration provided above(or similar) should be valid for the Gantt component. The OrderID should be configurable using the ASP.NET Core wrappers.

### Environment

* **Kendo UI version:** 2020.1.406
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by StoyanGoranov** [comment]
Also reported in ticket #1521150
