### ISSUE TITLE
Gantt - no Dependency Type configuration option in the Core wrapper

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5725]
### Bug report
The Core wrapper does not have a "Type" option:

```
.DependenciesDataSource(d => d
	.Model(m =>
	{
		m.Id(f => f.DependencyID);
		m.PredecessorId(f => f.PredecessorID);
		m.SuccessorId(f => f.SuccessorID);
		**m.Type(f => f.Type);**
	})
	.Read("Read_Dependencies", "Gantt")
	.Create("Create_Dependency", "Gantt")
	.Destroy("Destroy_Dependency", "Gantt")
)
```

Both the MVC wrapper and the jQuery widget allow to specify a field in the data that will be used as "type". Currently the Core wrapper does not allow specifying a field, and dependencies will work  only if the data contains a field named "Type". 

### Environment

* **Kendo UI version:** 2020.1.406
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by StoyanGoranov** [comment]
Also reported in ticket #1521150
