### ISSUE TITLE
NoRecords message is visible, while the Grid is fetching its data

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#5730]
### Bug report

While the grid is fetching its data, the component displays hte NoRecords message (if it is set)

### Reproduction of the problem
1. Set a NoRecords message for the Gird
2. Implement a small thread.sleep if needed, in order to push the component to load a bit slowly.
![no-records-message](https://user-images.githubusercontent.com/3043283/80096651-958c7e80-8572-11ea-8cc9-cb6862006de4.png)
### Current behavior
NoRecords message is displayed

### Expected/desired behavior
NoRecords message should not be displayed

### Environment

* **Kendo UI version:** 2020.1.406
* **Browser:** [all]

**Comment by ag-petrov** [comment]
QAs please test the grid with both server and ajax binding and check whether the norecords functionality works correctly
