### ISSUE TITLE
Can not insert row below the penultimate row

### ISSUE THREAD

**Issue by PavelLazhbanau** [telerik/kendo-ui-core#5732]
### Reproduction of the problem
Use the following [demo](https://demos.telerik.com/kendo-ui/spreadsheet/index) , to reproduce the issue.

- Set cursor into the penultimate row (199)
- Press "Insert Row above" button
- Same behavior if a user is trying to insert a row above the last one

### Current behavior
Nor row inserted or warning message appears

### Expected/desired behavior
A new row inserted below the selected one

### Environment

Kendo UI version: 2020.1.406
jQuery version: x.y
Browser: [all]

**Comment by Dimitar-Goshev** [comment]
This functionality was implemented in R1 2022 SP2 - v 2022.1.412 https://www.telerik.com/support/whats-new/kendo-ui/release-history/kendo-ui-r1-2022-sp2-(version-2022-1-412)
