### ISSUE TITLE
RatingFor does not work for editor templates

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#5733]
### Bug report

Rating is not rendered correctly with RatingFor when part of an editor template.

### Reproduction of the problem

1. Setup a Grid column that binds to an int.

2. Create a custom editor with the Rating

```cs
@model int

@(Html.Kendo().RatingFor(m => m)
    .Min(1)
    .Max(6)
)
```

### Current behavior

Rating is not rendered correctly.

### Expected/desired behavior

Rating should be able to successfully render with RatingFor.

### Environment

* **Kendo UI version:** 2020.1.406
* **Browser:** [all]

**Comment by mparvanov** [comment]
Here is the test project: 
[TelerikMvcApp2.zip](https://github.com/telerik/kendo-ui-core/files/4715993/TelerikMvcApp2.zip)
