### ISSUE TITLE
TreeView and JQuery 3.5x Invalid HTML

### ISSUE THREAD

**Issue by leniency** [telerik/kendo-ui-core#5735]
The internal template for the TreeView (and probably a number of other widgets) do not play nice with JQuery 3.5

A number of the internal templates use self-closing `<span />`'s and JQuery 3.5 doesn't appear to play nice with this. The element immediately following the `<span /` will get enclosed in it, rather than be a sibling.

It appears a common pattern in the internal templates is to self-close the icon tags: `<span class="k-icon" />`

This tends to instead result in stuff like:

```html
<span class="k-icon">
  <span class="checkbox-wrapper">...</span>
</span>

Example:
https://dojo.telerik.com/uFadanOm

Reading the JQuery 3.5 notes, the security changes to the html prefilter changed this:
https://jquery.com/upgrade-guide/3.5/

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** 3.5
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Dimitar-Goshev** [comment]
@leniency Thank you for this feedback. We have addressed this issue and we will provide jQuery 3.5 support in R2 2020.
