### ISSUE TITLE
Grid filter with datetimepicker omits timezone specifier

### ISSUE THREAD

**Issue by omfgicbf** [telerik/kendo-ui-core#5737]
When using the `datetimepicker` UI option for a column filter, the date/time sent to the data source lacks a timezone specifier.

### Reproduction of the problem
https://dojo.telerik.com/aQuSAfoK/2

### Current behavior
For example, when the filter range is set to 28th April 2020 01:00 to 28th April 2020 02:00 the following form data is sent in the bind request:-

```
$callback: jQuery112305357434797644376_1588052870171
$inlinecount: allpages
$format: json
$top: 20
$filter: (OrderDate ge datetime'2020-04-28T01:00:00' and OrderDate lt datetime'2020-04-28T02:00:00')
```

As the values lack timezone specifiers, the data source interprets the date/time as server local, which, if different from the client, results in an incorrect date/time.

### Expected/desired behavior
That date/time filter values include timezone specifiers.

### Environment

* **Kendo UI version:** UI for ASP.NET Core 2020.1.406
* **jQuery version:** ^3.3.1
* **Browser:** Chrome 81.0.4044.113

**Comment by dmanova** [comment]
Duplicate : #5306

**Comment by omfgicbf** [comment]
@dmanova this is not a duplicate. The other ticket is marked as a feature request to have the option to send as UTC. This ticket is about the bug where the time sent omits the timezone specifier.

**Comment by bobingham** [comment]
Why the hell is this closed?  I have exactly the same problem in the Angular grid.

**Comment by omfgicbf** [comment]
@bobingham yeah... not really sure. I tried to point out that the related ticket seems to be the same but this actually refers to a broader issue and is not related to converting date/times to UTC.

It's hard to tell because the ticket they closed this for has no context, no reproduction, no environment details and no example of the issue, nor is there any actual commentary on the issue and the only other reference is to a ticket number in some other system that is not identified (which is ironic, because the ticket was raised by their bot but doesn't follow their submission guidelines).

All I can tell is that it is low priority, considered an enhancement rather than a bug (as most things seem to be) and has probably been forgotten about.
