### ISSUE TITLE
TypeScript definition for kendo.ui.SchedulerView doesn't distinguish between configuration and return type

### ISSUE THREAD

**Issue by austinw-fineart** [telerik/kendo-ui-core#5740]
### Bug report
The TypeScript definition for kendo.ui.SchedulerView has `endTime`/`startTime` as Date when set as part of SchedulerOptions but it becomes a function that returns Date when returned from scheduler `view()`.

### Environment
* **@progress/kendo-ui:** 2020.1.406
* **@types/kendo-ui:** 2020.1.0

**Comment by Iankodj** [comment]
The view method of the Scheduler properly is defined as SchedulerView (https://github.com/telerik/kendo-ui-core/blob/master/typescript/kendo.all.d.ts#L7641). Where you can get the startTime and endTime fields as Date. 

![image](https://user-images.githubusercontent.com/4222379/95724324-ea39c800-0c7e-11eb-93a7-764df33a067b.png)

**Comment by austinw-fineart** [comment]
In your example, `startTime` is defined as `Date` when it should be `() => Date`. That is what this issue concerns.

**Comment by Iankodj** [comment]
Thanks for the clarification. I added the startDate definition to the view.

**Comment by austinw-fineart** [comment]
You only added startDate? That was only one of the missing properties for this issue. The main issue is that everything is defined in the `SchedulerView` type, even when the `view` property and `view()` method return distinctly different sets of properties. That is why I specifically state that it doesn't distinguish between a configuration and return type in the title. This wouldn't be such a problem if there was, for example, a `SchedulerViewOptions` type specifically for the `view` property. Then you could separate the two instead of mixing them together. I should also note that even the documentation is missing this distinction, including missing properties returned by `view()`, so you shouldn't rely on it. I suggest looking directly at what is returned by `view()` instead so you can see this for yourself.

**Comment by Iankodj** [comment]
The view() is expected to return the SchedulerView  instance with its options. It has never meant to return the options of the view. To get the latter you should use the instance's options field.

We cannot change what the view() method returns as this will result to a breaking change for many developer used this method to get the view instance.

**Comment by austinw-fineart** [comment]
You misunderstand.
This is `views`: https://docs.telerik.com/kendo-ui/api/javascript/ui/scheduler/configuration/views
This is `view()`: https://docs.telerik.com/kendo-ui/api/javascript/ui/scheduler/methods/view
Notice that the documentation says `view()` returns `kendo.ui.SchedulerView`, but that's what `views` is supposed to be.
Here is an example of the **actual** properties returned by `view()` for the month view:
- columnLevels
- content
- datesHeader
- element
- groupedResources
- groups
- rowLevels
- table
- times
- timesHeader
- title
- dayTemplate()
- eventTemplate()
- groupHeaderTemplate()

And proto properties:
- events
- name
- options (same as `views`)
- addDaySlot()
- dateForTitle()
- destroy()
- endDate()
- mobileDateForTitle()
- nextDate()
- previousDate()
- render()
- selectionByElement()
- shortDateForTitle()
- startDate() `<- This is what you added to kendo.ui.SchedulerView`

`kendo.ui.SchedulerView` is used for both `views` and `view()`. This is wrong.

**Comment by Iankodj** [comment]
The startDate method is added to the interface regarding https://github.com/telerik/kendo-ui-core/issues/5740#issuecomment-706982296. And it seems that using startDate is the appropriate method to use for the case. 

Indeed the same interface is being used for the options and the instance, but this is a topic regarding the entire TypeScript definitions file in the Kendo UI. Currently, we cannot introduce the changes for the View as this will make a huge impact over all developers using these definitions as we will need to introduce a new type and force a major change.

**Comment by austinw-fineart** [comment]
What are you talking about? `views` and `view()` already return different types. This just isn't stated in the documentation. I am trying to explain to you that the TypeScript definitions are wrong, not the component itself. `view()` does not have any properties in common with `views` yet they return the same type. Why?

**Comment by Iankodj** [comment]
Yes, I agree with you. I am referring to the TypeScript definitions as well. If we are to change for example the options of the view from SchedulerView to SchedulerViewOptions everyone who uses the SchedulerView will be forced to change the type to SchedulerViewOptions.

As the original issue reported can be solved by including the missing startDate method, it would be best not to introduce such a big change that will probably force changing the type to already implemented solutions.

**Comment by austinw-fineart** [comment]
Okay, but why only add startDate and nothing else? There are 27 other missing properties on `view()` for just the month view alone.

**Comment by Iankodj** [comment]
The methods and properties in the definitions are the ones from the base view. In order to facilitate the extended views (day, month, etc.) different types should be used - e.g., SchedulerMonthView. 

We could revise the demand for such an option and include it as an enhancement.

**Comment by austinw-fineart** [comment]
Yes I'd rather have that over adding startDate to `kendo.ui.SchedulerView`. Because based off what you just told me you're going to end up polluting it with unrelated properties if you add them all, so you might as well not have added to `kendo.ui.SchedulerView` in the first place.

**Comment by Iankodj** [comment]
I have related a task regarding extracting other View classes for all the views we have.

**Comment by Iankodj** [comment]
@austinw-fineart Can you please open a proper feedback portal (https://feedback.telerik.com/kendo-jquery-ui) so that I can relate the newly created item. That is the proper way for the PM to estimate the task.

**Comment by austinw-fineart** [comment]
Here you go:
https://feedback.telerik.com/kendo-jquery-ui/1491934-add-ts-definitions-for-all-specific-views-with-methods-and-properties

**Comment by Iankodj** [comment]
Thank you!
