### ISSUE TITLE
Read request is triggered twice, when navigation to a folder in the FileManager

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#5741]
### Bug report

Read request is triggered twice when navigation to a folder in the FileManager
Update: The problem occurs in TreeView, Grid, and ListView as well.

### Reproduction of the problem
1. Load on online demos here: https://demos.telerik.com/kendo-ui/filemanager/index
1. Click on the first item in the TreeView section of the FileManager. The issue will occur if you click the item in the active view as well.

### Current behavior
Two Read requests are triggered, in order to acquire the content

### Expected/desired behavior
There should only be one request.

### Environment

* **Kendo UI version:** 2020.1.406
* **Browser:** [all]

**Comment by PekoPPT** [comment]
Reported in ticket 1463594

**Comment by veselints** [comment]
also reported in: https://supportheroes.telerik.com/ticket/1466099

**Comment by Dimitar-Goshev** [comment]
Two other cases to consider:
1. Go to https://demos.telerik.com/kendo-ui/filemanager/index
1. Click on Images folder in the ListView
1. Press F2 and Rename Images to ImagesTest
1. Press Enter
 
The result is Update is triggered, followed by a failing Read request.

1. Go to https://demos.telerik.com/kendo-ui/filemanager/index
1. Click on Images folder in the ListView
1. Press F2 and Rename Images to ImagesTest
1. Press Enter
1. Click on ImagesTest folder in the ListView
1. Press F2 and Rename ImagesTest back to Images
1. Press Enter

The result is the ListView enters into the folder, but its name is shown as ImagesTest in the TreeView and Breadcrumb
