### ISSUE TITLE
Grid cells font size incorrectly exported to Excel

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5745]
### Bug report
The following article shows how to set the cells font size to 30: [https://docs.telerik.com/kendo-ui/knowledge-base/grid-excel-export-custom-font](https://docs.telerik.com/kendo-ui/knowledge-base/grid-excel-export-custom-font). Up to R1 2019 the font size was properly exported. Since R1 2019 the font size in the generated Excel file has a wrong value. 

### Reproduction of the problem
1. Export the Grid
2. Open the generated Excel file. 

### Current behavior
Font size is 22.5

### Expected/desired behavior
Font size is 30

### Environment

* **Kendo UI version:** 2020.1.406
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by gyankov** [comment]
The behavior is introduced after switching the font size from pixels to points. For more information, refer to the following issue:

- https://github.com/telerik/kendo/issues/9154

A possible workaround to revert to the previous behavior is to invert the points to pixels conversion as shown below:

```
     sheet.rows[i].cells[ci].fontSize = 30/(3/4);
```
@VicTachev we might consider updating the referenced article.
