### ISSUE TITLE
FileManager throws a 500  error when trying to edit file name.

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#5749]
### Bug report

When you rename a folder in the TreeView section of the FileManager and then immediately click on some if its contained files, in an attempt to edit its name - an error is thrown

### Reproduction of the problem
hit https://demos.telerik.com/aspnet-mvc/filemanager
1. Rename Images folder
2. Rename a file in the Images folder

### Current behavior
an exception in thrown

### Expected/desired behavior
the edit operation should be performed with no errors.

###Workaround
setting the HasDirectories attribute to true on every folder.

### Environment

* **Kendo UI version:** 2020.1.406
* **Browser:** [all ]

**Comment by Juveniel** [comment]
Not reproducible with version 2020.3.1118.
