### ISSUE TITLE
Column menu does not work correctly after column reorder

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#5750]
### Bug report

Column menu does not work correctly after column reorder. More information including a sample and a video can be found in ticket with id 1460511.

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ag-petrov** [comment]
Related issue - https://github.com/telerik/kendo-ui-core/issues/5700
