### ISSUE TITLE
Rating with precision:half does not render correctly in template

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5751]
### Bug report
When adding a Rating with `precision:"half"` in a Gantt tooltip template the half item is not rendered. Using Rating with `precision:"item"` works as expected.

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/EdaRezeS)
1. Hover over the Task

### Current behavior
Rating is set to 2.5, but the half item is not rendered.

### Expected/desired behavior
Rating configured with precision:"half" should render the half item.

### Environment

* **Kendo UI version:** 2020.1.406
* **Browser:** [all]

**Comment by Juveniel** [comment]
Fixed an issue where the Rating with half precision initialized in Scheduler/Gantt custom edit template does not render the half start.

As for the Dojo in this issue where the Rating start is not rendered correctly in the Gantt tooltip template - this is the case as the Gantt utilizes custom Tooltips for rendering the tasks that are evaluated too early. In this case, Rating with half precision can be rendered successfully as demonstrated in [the following Dojo example](https://dojo.telerik.com/ESuTejIN/2).
