### ISSUE TITLE
Context Menu is not displayed when FileManager is initialized with local data source

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5752]
### Bug report
When the FileManager is initialized with a local data source the Context Menu is not displayed.

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/IPeBArAK)
1. Right-click on a folder of a file

### Current behavior
The context menu is not displayed. The Context menu is not expected to be displayed for the built-in rename and delete commands, but a context menu is not displayed when custom commands are implemented.

### Expected/desired behavior
A context menu should be displayed when local data source is used.

### Environment

* **Kendo UI version:** 2020.1.406
* **Browser:** [all]

**Comment by martintabakov** [comment]
Also in #1482893
