### ISSUE TITLE
Rating component's functionality breaks when the "de-DE" culture is set

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5754]
### Bug report

The rating component layout/functionality breaks when its **precision** configuration is set to "half" and the defined Kendo culture is "de-DE". 

* The issue is related to the defined in the de-DE culture decimal separator
If the below definition
> numberFormat: {
>                pattern: ["-n"],
>                decimals: 2,
>                ",": ".",
>                ".": ",",

is changed to this:
> numberFormat: {
>                pattern: ["-n"],
>                decimals: 2,
>                ",": "'",
>                ".": ",",

The issue is no more reproducing 

### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/ARiloDeb) and run it
1. See the second rating component

### Current behavior
The layout of the rating component with "half" precision doesn't visualize the "half" precision and the value of the current rating is displayed without a decimal point
![image](https://user-images.githubusercontent.com/41293735/81415285-e85c5d80-9150-11ea-9c40-3cea01642fc8.png)

### Expected/desired behavior
The expected behavior can be observed in [this Dojo example](https://dojo.telerik.com/EbOQAVeq)
![image](https://user-images.githubusercontent.com/41293735/81415438-1fcb0a00-9151-11ea-9d05-b98c18ce7fd4.png)

### Environment

* **Kendo UI version:** 2020.1.406
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
Also reported in thread#1468726 and affects the ASP.NET Core wrappers. Also when the Rating value is posted to a remote endpoint, it is posted with a point as a decimal separator e.g. "2.5". The decimal separator defined by the culture applied is not respected.
