### ISSUE TITLE
[Chrome, Firefox]: Kendo Popup displayed over the Sheet pane does not close when Spreadsheet is initialized in modal Window

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5757]
### Bug report
[Chrome, Firefox]: Kendo Popup displayed over the Sheet pane does not close when Spreadsheet is initialized in modal Window:
- Cell context menu does not close when clicking on a cell;
- Cell list validation popup does not close when clicking on a cell;

### Reproduction of the problem
- Run the following Dojo: https://dojo.telerik.com/aleLotep
- Right-click on a cell to open the ContextMenu;
- Left-click somewhere on the Sheet - the ContextMenu will remain open.

### Expected/desired behavior
The ContextMenu should close upon left-click.

### Environment
* **Kendo UI version:** 2024.1.130
* **Browser:** [Chrome XX | Firefox XX]

**Comment by veselints** [comment]
Workaround:
```js
$("#spreadsheet").kendoSpreadsheet({
	select: function() {
  	var menu = $('.k-spreadsheet-cell-context-menu').getKendoContextMenu();
    if(menu) {
    	menu.close();
    }
  }
})
`

**Comment by pepinho24** [comment]
Not reproducible with 2024.4.1112
