### ISSUE TITLE
Form throws error when compiling script with WebPack

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#5766]
### Bug report

Form throws error when compiling script with WebPack

### Reproduction of the problem

The form throws an error when the form script is compiled with WebPack.

### Current behavior

kendo.form.js:189 Uncaught TypeError: Cannot read property '_errorTemplate' of undefined

### Expected/desired behavior

No error should be thrown.

### Environment

* **Kendo UI version:** 2020.2.513
* **Browser:** [all]

**Comment by ceisele-r** [comment]
We can confirm this happens when updating from `2020.1.406` to `2020.2.513`.

**Comment by ceisele-r** [comment]
@Juveniel is there any update/workaround for this issue? This is blocking us from updating to `2020.2.513`.

**Comment by Juveniel** [comment]
Hello @ceisele-r,

Could you test with the latest dev version on npm and verify if the issue is resolved ?

[https://www.npmjs.com/package/@progress/kendo-ui/v/2020.2.528-internal](https://www.npmjs.com/package/@progress/kendo-ui/v/2020.2.528-internal)

**Comment by ceisele-r** [comment]
Hi @Juveniel ,

Thanks, I can confirm that v2020.2.528-internal fixes the issue.
