### ISSUE TITLE
MultiSelect remove its custom tags when item is deselected

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5780]
### Bug report
Currently the MultiSelect allows a custom tag (one that does not correspond to items in its dataSource) to be displayed as selected. For this to work the MultiSelect must have autoBind disabled and the dataValueField option must be set. Once the widget is bound to data it behaves inconsistently, depending on whether there are other pre-selected items and what their index in the dataSource is.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/uZazOHUN/2) example.
1. Focus the MultiSelect

### Current behavior
The widget is loaded with data, but the custom tag remains. This leads to the following unexpected behavior: after step 1. deselect "Product1". The item is deselected, the "custom" tag is removed from the input area but the "Product1" tag remains. The behavior is different, if initially "custom" and "Product2" are pre-selected.

### Expected/desired behavior
Once the widget is bound any custom tags should be removed. The MultiSelect should display only tags for items that are in its dataSource. For a new item to be displayed as selected, it must be added to the dataSource. 

### Environment

* **Kendo UI version:** 2020.2.513
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by zdravkov** [comment]
After researching the issue deeper we have decided to keep the current behavior and keep the custom item when the widget is dataBound - yet we fixed the unusual behavior that was observed when deselecting an item. The custom item persists only when the values are objects and dataTextField and dataValueField are declared. When the values are primitive they are removed when the data is bound.
