### ISSUE TITLE
Missing localization setting for the Upload's pause and resume buttons

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5784]
### Bug report
There are no configuration options dedicated to localizing the text in the arial-label attribute of these buttons. We localize other buttons, such as the "remove" and "cancel" buttons.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/eYOWIyUM/3) example.
1. Select a bigger file, which will allow the "pause" and "resume" buttons to appear.

### Current behavior
The aria-label value is in English.

### Expected/desired behavior
The aria-label value is localized.

### Environment

* **Kendo UI version:** 2020.2.513
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by IvanDanchev** [comment]
Additionally, when the upload of a file is paused we display text "Paused" in the strong element with class *k-upload-status-total*. It should be possible to localize this message as well.

**Comment by Juveniel** [comment]
The `pause` and `resume` aria-label can already be customized through [the localization option](https://docs.telerik.com/kendo-ui/api/javascript/ui/upload/configuration/localization) as follows:
```js
<script>            
    $("#files").kendoUpload({
        async: {
          chunkSize: 11000,
          saveUrl: "chunkSave",
          removeUrl: "remove",
          autoUpload: true,
          withCredentials: false
      },
      localization: {
          resume: "resume custom",
          pause: "pause custom"
      }
});
</script>
```

In terms of the "Paused" message in the header - this option was indeed not documented and available for the wrappers. Thus, I have added it as part of this issue. Thus, with the next major release, the paused text will be available to localize as follows:
```
localization: {
    headerStatusPaused: "Paused message"          
}
```

Also, in terms of built-in available translations in localization files(e.g kendo.messages.de-DE.min.js), we encourage native-speaking users to submit pull requests regarding the exact translations in the Kendo UI Core repository. Refer to [the Contribution guide](https://docs.telerik.com/kendo-ui/globalization/localization#contribution) for additional details.
