### ISSUE TITLE
Spreadsheet: Incorrect server-side import of Excel file with frozen panes

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5785]
### Bug report
An Excel file that has frozen panes is incorrectly imported in the Spreadsheet when a server-side import is executed. 

The bug is reproduced only when the Excel file is scrolled down. 

More details about the issue and possible workaround can be found on this link: https://feedback.telerik.com/aspnet-mvc/1462684-incorrect-server-side-import-of-frozen-panes-when-the-sheet-is-scrolled-before-saving

### Reproduction of the problem
1. Open [this Demo](https://demos.telerik.com/aspnet-mvc/spreadsheet/server-side-import-export) 
2. Click on the Upload component above the Spreadsheet - "Select file to import..." 
3. Select this [simple.xlsx](https://github.com/telerik/kendo-ui-core/files/4657546/simple.xlsx) file from your local storage

### Current behavior
The the Excel file is loaded in the Spreadsheet but the horizontal frozen pane is not defined on the same rows as in the imported file. With the current behavior, when vertical scrolling is done, the third row with values 5 and 6 is not scrolled.  

### Expected/desired behavior
After the simple.xlsx file is imported server-side in the Spreadsheet the frozen panes inside the component should be the same as these defined in the imported file. As a result, when scrolling the imported file vertically, the third row should be scrolled.

### Environment

* **Kendo UI version:** 2020.2.513
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by veselints** [comment]
PR here:
https://github.com/telerik/kendo/pull/10894
