### ISSUE TITLE
Breadcrumb in FileManager does not respect custom id in Schema

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5798]
### Bug report
Breadcrumb in FileManager does not respect custom id in Schema

### Reproduction of the problem
* Run the following Dojo: https://dojo.telerik.com/ORImIvaC/13
* Click on "Folder" in the treeview
* Click on "SubFolder" in the treeview
* Click on "Folder" in the breadcrumb - an error will be thrown. The FileManager tries to navigate to "/Folder", while it should navigate to "1".

### Expected/desired behavior
FileManager should navigate to the proper folder. No error should be thrown.

### Environment
* **Kendo UI version:** 2020.2.513
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The fix introduces an issue in the following scenario:
1. Go to https://demos.telerik.com/kendo-ui/filemanager/index
2. Click on Images in the TreeView and create a New Folder as a child of Images folder
3. Click on New Folder in the TreeView and create another New Folder as a child of New Folder
4. Click on the innermost New Folder in the TreeView - Breadcrumb is Home > Images > New Folder > New Folder
5. Click on Home > Images > New Folder in the Breadcrumb

Expected - navigation to Home > Images > New Folder
Current - navigation to Home

The following [Dojo](https://dojo.telerik.com/@Dimitar-Goshev/ePosaFeL) provides setup for reproducing the issue with local data as well.

**Comment by Dimitar-Goshev** [comment]
The new fix fixes the initial issue and the one from the comment above. But it creates a new issue - nested folders with the same name are not taken into account and Breadcrumb navigation goes to the outermost folder.
1. Go to the local instance of https://demos.telerik.com/kendo-ui/filemanager/index
1. Click on Images in the TreeView and create a New Folder as a child of Images folder
1. Click on New Folder in the TreeView and create another New Folder as a child of New Folder
1. Repeat the above step until you have the following path - Home > Images > New Folder > New Folder > New Folder > New Folder > New Folder
1. Click on the innermost New Folder in the TreeView - Breadcrumb is Home > Images > New Folder > New Folder > New Folder > New Folder > New Folder
1. Click on Home > Images > New Folder > New Folder > New Folder > New Folder in the Breadcrumb (one folder up from the innermost New Folder)

Expected - navigation to Home > Images > New Folder > New Folder > New Folder > New Folder
Current - navigation to Home > Images > New Folder
