### ISSUE TITLE
Server side exception when serializing FixedDocument

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5802]
### Bug report
A server side exception:
**System.OverflowException: 'Value was either too large or too small for a Double.'**
is thrown on attempting to serialize an existing .pdf file converted to FixedDocument.

### Reproduction of the problem
1. Use the **DPL Processing demo** of the PDFViewer in the MVC demos project.
2. Instead of the default **sample.pdf** load the **Development Plan.pdf** file provided in Ticket ID: 1467984

```
public ActionResult GetInitialPdf(int? pageNumber)
{
    //exception with Development plan.pdf file:
    string filePath = Path.Combine(Server.MapPath("~/Content/web/pdfViewer"), "Development Plan.pdf");
    //it works with the sample.pdf file:
    //string filePath = Path.Combine(Server.MapPath("~/App_Data"), "sample.pdf");
    FileStream stream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
    JsonResult jsonResult;
    FixedDocument doc = FixedDocument.Load(stream);

    if (pageNumber == null)
    {
        jsonResult = Json(doc.ToJson(), JsonRequestBehavior.AllowGet);
    }
    else
    {
        jsonResult = Json(doc.GetPage((int)pageNumber), JsonRequestBehavior.AllowGet);
    }

    jsonResult.MaxJsonLength = int.MaxValue;
    return jsonResult;
}
```

### Current behavior
The exception is thrown during the FixedDocument JSON serialization:
```
doc.ToJson()
```
at the following place: **ConvertToList** method in **ArrayExtension** class (**Telerik.Web.PDF** namespace)

### Expected/desired behavior
No exceptions are thrown during serialization.

### Environment

* **Kendo UI version:** 2020.2.513
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by PekoPPT** [comment]
Also reported in ticket 1470065
