### ISSUE TITLE
Cannot read property 'firstChild' of undefined error thrown for Scheduler with remote dataSource, grouping and autoBind set to false

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5806]
### Bug report
The Scheduler configured with remote dataSource, vertical grouping and with autoBind: false, throws an error "Cannot read property 'firstChild' of undefined" and the Scheduler layout is not rendered. The behavior is a regression introduced with Kendo UI v 2020.1.114

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/AfowEbUc)

### Expected/desired behavior
No error should be thrown with the above configuration.

### Environment

* **Kendo UI version:** 2020.2.513
* **Browser:** [all]

**Comment by mparvanov** [comment]
Currently with autoBind:false neither the events nor the resources are bound initially when the scheduler is loaded. When navigate away from the default view to another, for example from Month to Day view the scheduler rebinds the events but doesn't rebind the resources. We need to make sure both events and resources are bound on navigation.
