### ISSUE TITLE
Editor placed in a Window forces a request to undefined endpoint

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5809]
### Bug report
In an MVC project, Editor placed in a Window forces a request to undefined endpoint.
The issue has been introduced with R2 2020.2.513.

### Reproduction of the problem
To reproduce it in Kendo jQuery:
```html
  <div id="MyWindow">
    <textarea id="editor"></textarea>
  </div>
  <script>
      $("#editor").kendoEditor(); 
      $("#MyWindow").kendoWindow();
  </script>
```
To reproduce it in MVC:
- Run the attached project:
[custom-popup-editor.zip](https://github.com/telerik/kendo-ui-core/files/4693714/custom-popup-editor.zip)
- Click the edit button to edit an item;
- The remote request will be made;

The issue is also reproducible outside the Grid's editor window, when the Editor is nested in a standalone Window. For example:
```
@(Html.Kendo().Window()
	.Name("MyWindow")
	.Title("Test")
	.Content(@<Text>
		@(Html.Kendo().Editor()
			.Name("editor")
		)
	</Text>)
)
```

### Expected/desired behavior
No remote requests should be made. That was the behavior before the R2 2020.2.513 release.

### Environment
* **Kendo UI version:** 2020.2.513
* **Browser:** [all]

**Comment by Pokey1** [comment]
Upvote.  Please fix in next release.
