### ISSUE TITLE
In RazorPages solution the Form is not rendered if the FormData configuration is not provided

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5813]
### Bug report
Initializing a Form in a Razor Pages web project without providing the FormData configuration is not possible and Model attributes are not applied to form fields :
```
@(Html.Kendo().Form<OrderViewModel>()
    .Name("formExample")
    .FormData(Model.Order)
    .Items(items =>
    {
        items.Add()
            .Field(f => f.ShipName)
            .Label(l => l.Text("ShipName"));
    })
)
```

### Reproduction of the problem
A Form cannot be initialized in a RazorPage solution using the above definition without providing the FormData() configuration:
```
.FormData(Model.Order)
```
Any attributes applied to the Model properties are also not applied to the Form:
```
[Required]
public string ShipName {get;set;}
```

### Expected/desired behavior
The Form should be initialized without specifying FormData configuration and attributes applied.

### Environment

* **Kendo UI version:** 2020.2.513
* **Browser:** [all]

**Comment by Juveniel** [comment]
Test project: 
[WebApplication1.zip](https://github.com/telerik/kendo-ui-core/files/4721413/WebApplication1.zip)

**Comment by mparvanov** [comment]
The fix resolves the validation issue. Steps:
1. Run the attached project
1. Clear the textbox value 
1. Submit the form

Expected: The validation should be triggered.

**Comment by IvanDanchev** [comment]
The fix specifically targets the Form validation issue related to using nested models. The Form still needs FormData to be set, when a complex model is used, which is the case with the attached example - OrderViewModel is nested within IndexModel.
