### ISSUE TITLE
Scheduler event with timezone jumps when moved or resized

### ISSUE THREAD

**Issue by austinw-fineart** [telerik/kendo-ui-core#5815]
### Bug report
When using scheduler with the current system timezone (timezone and schema.timezone options are not set), moving or resizing the event inside the scheduler will cause it to jump away from its final position.

### Reproduction of the problem
1. Go to https://dojo.telerik.com/umEduFir
2. Create an event with a timezone that's different than the current system timezone
3. Move or resize the event

### Current behavior
The event will constantly be shifted by the difference between the current system timezone and the event timezone each time it is moved or resized.

### Environment
* **Kendo UI version:** 2020.2.513
* **jQuery version:** 3.5.1
* **Browser:** all

**Comment by mahoganymuhoo** [comment]
Any solution???

**Comment by jrmcdona** [comment]
@dmanova @tsvetomir   this seems to happen to me?  It makes the scheduler not usable.  I am using asp.net core.

Looks like this issues has existed for two years.

Thanks

**Comment by Dimitar-Goshev** [comment]
Hello,
The reported behavior is expected in remote binding scenario and no Scheduler timezone specified. When Scheduler uses remote binding, the timezone option should always be specified, as highlighted on [Scheduler Timezones help article](https://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/timezones):

> - When you use **remote binding**, the Scheduler expects to **receive UTC dates**. Respectively, it will **send them back to the server in UTC**. The **service in use is responsible for keeping the dates in UTC, without offsetting them against its local time**.
> - When you **bind the Scheduler to a remote service**, keep the **timezone option always set** to, for example, "**Etc/UTC**".
> - When the **timezone option of the Scheduler is not set**, the **current system timezone offset** is used.

And the last bullet above explains why events jumping is observed when no timezone is set - the current system timezone offset is applied.

**Comment by austinw-fineart** [comment]
I'm not understanding your point. In the provided reproduction Dojo the remote binding uses https://demos.telerik.com/
Are you implying that your own demo server is implemented incorrectly? How should the remote service behave when the timezone on the frontend is the current system timezone? Should the frontend not try to account for this difference? The UI bugging out is certainly not a good indicator for this.

**Comment by Dimitar-Goshev** [comment]
@austinw-fineart The reproduction Dojo https://dojo.telerik.com/umEduFir has Scheduler without timezone property and remote binding. This setup is incorrect and results in the logged issue. There is no way to avoid the issue with the provided setup. The correct setup is to set timezone to Scheduler as on our [Basic usage demo](https://demos.telerik.com/kendo-ui/scheduler/basic-usage), which seems used for creating the reproduction Dojo. When `timezone: "Etc/UTC",` is added to the reproduction Dojo setup - [updated Dojo](https://dojo.telerik.com/@Dimitar-Goshev/OfUfIhUF), the Scheduler behaves correctly and events do not jump on move/edit after being created.
Note that when timezone: "Etc/UTC", is set, [all events are displayed in Etc/UTC](https://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/timezones#schedulers-with-a-timezone-option-set) and if a timezone other than UTC is specified for start and end of an event, when creating it, it will be with an offset to UTC.

**Comment by austinw-fineart** [comment]
Got it, so if I manually set the timezone to match the current system timezone then all is well. In this case I can use the resolved options from Intl.DateTimeFormat to do so.
