### ISSUE TITLE
Pasted table gets incorrect layout after formatting

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#5818]
### Bug report

Pasting <table> HTML via the viewHtml tool and formatting a sentence with an inline tool causes broken layout. 

### Reproduction of the problem
https://dojo.telerik.com/@Dimitar-Goshev/AVAqAXaN

1. Copy the following HTML:

```html
<table>
    <tbody>
        <tr style="height:50%;">
            <td style="width:50%;">Spain﻿</td>
            <td style="width:50%;">Bulgaria</td>
        </tr>
        <tr style="height:50%;">
            <td style="width:50%;">United States</td>
            <td style="width:50%;">UK</td>
        </tr>
    </tbody>
</table>
```

2. Use the View HTML tool to insert it to the editor
3. Select United States by using triple click
4. Bold the selection (Ctrl+B)

### Current behavior
![image](https://user-images.githubusercontent.com/4222379/83492385-df467e00-a4bb-11ea-8202-5b8e8de931d2.png)

### Expected/desired behavior
The layout of the table to remain the same.

### Workaround 
Using a custom deserialization oprion: 

https://dojo.telerik.com/opOpItIL

### Environment

* **Kendo UI version:** all
* **Browser:** [all ]

**Comment by stefankoserkov** [comment]
This bug can still be reproduced if the in editor's config is set `immutables: true`
