### ISSUE TITLE
Endless scrolling of ListView does not correctly in AngularJS

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#5819]
When loading the new batch of items a blank item is rendered. More information can be found in ticket - 1469304. 

Possible workaround can be found in [this ](https://dojo.telerik.com/EHozaKag/5)dojo.

**Comment by gyankov** [comment]
Possible duplicate of https://github.com/telerik/kendo-ui-core/issues/5515.

**Comment by ag-petrov** [comment]
Related issue - https://github.com/telerik/kendo-ui-core/issues/5999

**Comment by dmanova** [comment]
> Possible duplicate of 5515.
5515 doesn't seem to be fixed with the current issue. While 5999 does.

**Comment by dmanova** [comment]
Duplicate of #5999

**Comment by ag-petrov** [comment]
#5515 is not related, it is a separate issue
