### ISSUE TITLE
Unable to add a new row to a sheet exported to Excel and imported back in Spreadsheet

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-ui-core#5826]
### Reproduction of the problem

https://demos.telerik.com/kendo-ui/spreadsheet/index - Steps:
 
1 - Export the file
2 - Import the file that we just exported
3 - Try to add a new row
4 - Error appears - Cannot insert cells due to data loss possibility. Select another insert location or delete the data from the end of your worksheet.

### Current behavior

Error is shown.

### Expected/desired behavior

A new row is added.

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by mishoo** [comment]
Fixed in https://github.com/telerik/kendo/commit/ea1c56f1a8fb0db57aad12970294e60ab1bf35b0
