### ISSUE TITLE
Datepicker should have a setting to disable user typing

### ISSUE THREAD

**Issue by arrudadev** [telerik/kendo-ui-core#5828]
### Enhancement

I had a problem in which I need to disable the user's typing so that the user can only insert the date in the datepicker using the calendar button, because when the user is on a mobile device, with a small screen, the focus on the input ends up opening the keyboard of the device itself, making it difficult to view the calendar component. Using Jquery there is the possibility to disable the input using the readonly attribute, as shown in the following example:

https://docs.telerik.com/kendo-ui/controls/editors/datepicker/how-to/readonly-input?_ga=2.119241801.1179940960.1591299502-154148922.1520272064

However, when angularJs (1.x) is being used, there is no easy way to disable user typing.

### Current behavior
The datepicker component has a function to leave the entry disabled. However, this function also disables the calendar button.

### Expected/desired behavior
There is a property in the construction of the datepicker to disable user typing by default and keep the calendar button working.

#### Jquery Example
```bash
// create DatePicker from input HTML element
$("#datepicker").kendoDatePicker({
     inputReadOnly: true // Disables user typing
});
```
#### AngularJs (1.x) Example
```bash
<input id="datepicker" 
       kendo-date-picker
       ng-model="fromDateString"
       k-ng-model="fromDateObject"
       k-max = "maxDate"
       k-rebind="maxDate"
       k-on-change="fromDateChanged()"
       k-input-read-only="true" />
//k-input-read-only="true" - Disables user typing
```

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
