### ISSUE TITLE
Regular Expression DoS vulnerabilities in tests/dropdownlist/knockout-min.js

### ISSUE THREAD

**Issue by linci8210** [telerik/kendo-ui-core#5829]
### Bug report
We are working on the [ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) problem and detected a vulnerable regex from your code.
`/^[\_$a-z][\_$a-z0-9]*(\[.*?\])*(\.[\_$a-z][\_$a-z0-9]*(\[.*?\])*)*$/`
in [link](https://github.com/telerik/kendo-ui-core/blob/master/tests/dropdownlist/knockout-min.js) takes forever to match the string
`"_[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]\b"`

We didn’t create a pull request because we're not sure if these cases are possible to take place in your program, we also do not understand the functionality of these regexes as you do. Thank you for your understanding.

### Reproduction of the problem
Please try the following:
`var pattern = /^[\_$a-z][\_$a-z0-9]*(\[.*?\])*(\.[\_$a-z][\_$a-z0-9]*(\[.*?\])*)*$/i;
var input = "_[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]\b";`
`var re = new RegExp(pattern);`
`var matched = input.match(re);`

**Comment by Juveniel** [comment]
The related file is part of tests related to an integration with the knockout.js library. As the integration between the two libraries requires additional [kendo-knockout library](https://github.com/kendo-labs/knockout-kendo) which is archived, I think that we could remove the knockout script and related tests.

/cc @zdravkov
