### ISSUE TITLE
Exporting to Excel after setting a custom validation using range.validation method generates corrupted Excel file

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5830]
### Bug report
When exporting to Excel after setting a custom validation using range.validation method generates corrupted Excel file. 

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/UvUpeneb)
1. Export Excel file and open in Excel

### Current behavior
Excel indicates the exported file is corrupted. Removing the validation set via the range.validation method exports a valid file with custom validations.

### Expected/desired behavior
A valid file should be exported

### Environment

* **Kendo UI version:** 2020.2.513
* **Browser:** [all]

**Comment by mishoo** [comment]
Seems Excel does not support a real array for list validation, thus `{"", "X"}` won't work.  It must be a string, with values separated by comma (which also implies you cannot have a blank value there), like this: `"X,Y"` ([see dojo](https://dojo.telerik.com/enuJeTuB/2)).

While Excel thinks the resulted XLSX is "corrupted", it works fine in other apps such as LibreOffice.  Perhaps this should be documented as a limitation of Excel and if one needs the output to be Excel-compatible, one should not use such validations, but as far as I'm concerned it's not an issue in our spreadsheet, thus "won't fix".

**Comment by veselints** [comment]
Fixed with: https://github.com/telerik/kendo-ui-core/issues/6019
