### ISSUE TITLE
DropDownTree can not bind data when using remote datasource as grid editor

### ISSUE THREAD

**Issue by IKKI2000** [telerik/kendo-ui-core#5834]
### Reproduction of the problem
Since version 2020.1.114, DropDownTree can't bind data when using remote datasource. Previous versions didn't have this problem.

### Expected/desired behavior
DropDownTree can bind data whatever using remote or local datasource.

### Environment

* **Kendo UI version:** 2020.1.114, 2020.1.219, 2020.1.406, 2020.2.513
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by dmanova** [comment]
@IKKI2000 could you give a runnable sample ([dojo](https://dojo.telerik.com/)) where this is replicated. I couldn't reproduce it using this demo page - https://demos.telerik.com/kendo-ui/dropdowntree/remote-data-binding

**Comment by IKKI2000** [comment]
@dmanova OK, I'll show you three different pieces of demo to replicated this bug.
* The first demo is to use the remote data source of this year version 2020.2.513. [dojo](https://dojo.telerik.com/uFUhaWiH) In this demo, you can click the edit button to see binding failed.
* The second demo is to use the remote data source of last year version 2019.3.1023. [dojo](https://dojo.telerik.com/AnIdenIt) In this demo, you can see that I have just replaced the KendoUI version, and the rest of the code is exactly the same. But binding succeed.
* The third demo is to use the local data source of this year version 2020.2.513. [dojo](https://dojo.telerik.com/aNefAkag) In this demo, you can click the edit button to see binding succeed.

**Comment by dmanova** [comment]
Thank you for the examples. Indeed now it is reproducible. 
It seems that even the old version shows the same issue from time to time - on the last row. I'm processing it for further investigation and planning.

**Comment by IKKI2000** [comment]
@dmanova You're welcome~ I'm glad to help you~

**Comment by IKKI2000** [comment]
@dmanova Oh, it not only in grid editor but also in MVVM~

**Comment by veselints** [comment]
Reported also in: 1503161

**Comment by Juveniel** [comment]
The issue is related to concurrent DataSource read requests triggered by the DropDownTree value() method.

**Comment by gdenchevprog** [comment]
Reported in 1536256.
