### ISSUE TITLE
Scheduler with vertical grouping - events overlap the next group in Timeline view

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5836]
### Reproduction of the problem
Reproducible in the [Vertical Grouping](https://demos.telerik.com/aspnet-core/scheduler/resources-grouping-vertical) demo. 
1. Select the Timeline view.
2. Add multiple (more than 11) events to a single time slot: [screenshot](https://www.screencast.com/t/VXymD6cual0).
3. The slot resizes in height each time a new event is added, however, the more events are added the closer to the slot's bottom border they are pushed.

### Current behavior
After adding 11 or more events, the last event starts overlapping the next resource group slot.

### Expected/desired behavior
The slot should resize accordingly, based on the number of events shown in it. Events should not be displayed outside of the slot they belong to. 

### Environment

* **Kendo UI version:** 2020.2.513
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by nelito987** [comment]
Reported also in the ticket: 1485683

**Comment by aleksandarevangelatov** [comment]
Reported also in the ticket: 1485916 
The issue can also be replicated without grouping applied, but by only adding multiple events in the same timeslot: [dojo example](https://dojo.telerik.com/@AleksandarEvangelatov/IPolOwUC)

**Comment by PekoPPT** [comment]
Reported in ticket: 1503267. 
Check the ticket. The client shares which part of the code should be edited according to him.
