### ISSUE TITLE
TreeView parent node checkbox state is not properly updated (Core)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5850]
### Reproduction of the problem
1. Run the attached sample project:
[TelerikAspNetCoreApp100.zip](https://github.com/telerik/kendo-ui-core/files/4771062/TelerikAspNetCoreApp100.zip)
2. A child node is returned as checked from the server. 
3. Note the difference between the state of the parent node checkbox in the Core TreeView (incorrect) and in the Kendo UI TreeView (correct).

### Current behavior
The parent node's state remains "unchecked".

### Expected/desired behavior
The parent node's state should be "indeterminate".

**Workaround:**

Attach a DataBound event handler to the TreeView:
```
<kendo-treeview name="DataRestrictionTree" load-on-demand="false" datatextfield="Name" on-data-bound="onDataBound" >
```
In the handler call the TreeView's **updateIndeterminate** API method:
```
function onDataBound(e) {
	var treeview = $("#DataRestrictionTree").data("kendoTreeView");
	treeview.updateIndeterminate();
}
```

### Environment

* **Kendo UI version:** 2020.2.513
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by zdravkov** [comment]
The  issue is caused by the loadOnDemand=false property that is set to the wrapper component and not set in  the jQuery widget - in such cases when loadOnDemand is set to 'false' currently the default behavior of the TreeView is to skip the update of the intermediates.
