### ISSUE TITLE
Editing TimePicker "modern" component type shows NaN

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-ui-core#5865]
### Bug report

When select value between 12:00AM and 12:59AM and then open the Time view for edit it shows 1AM for the clock value.
And if you try to select a few times the same value between 12:00AM and 12:59AM a "NaN" shows.

![TimePicker-FirstSelect12AM](https://user-images.githubusercontent.com/52446546/85287965-b18e9c80-b49d-11ea-9c5a-772b432f63fb.PNG)

![TimePicker-OpenSelected12AM](https://user-images.githubusercontent.com/52446546/85287993-b81d1400-b49d-11ea-869c-db75a876dfc4.PNG)

![TimePicker-AfterSecondSelect12AM](https://user-images.githubusercontent.com/52446546/85288005-bc493180-b49d-11ea-91a8-abc6cbe04dc1.PNG)

### Reproduction of the problem
Could be reproduced on https://demos.telerik.com/kendo-ui/timepicker/component-type

### Expected/desired behavior
Explain what the expected behavior of the functionality is
When select value between 12:00AM and 12:59AM and then open the Time view for edit it shows the already selected value.

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** jquery-1.12.3.min.js
* **Browser:** [all ]

**Comment by gyankov** [comment]
@CecoMilchev  was able to replicate the issue even after the fix. Reopening the issue to further investigate the case.

**Comment by dmanova** [comment]
This is still reproducible from time to time. It seems that it is a pixel ratio related. As it is reproducible when:

- Display Scale setting is different than 100%, e.g. 125%,

- Browser zoom level is different than 100%, e.g. 125%

- Another possible configuration that need to test is with HiDPI displays

**Comment by ag-petrov** [comment]
@dmanova please check the scenario from ticket - 1485988 . It is related to the logic currently being improved, however it seems that the case from there does not work correctly. In my test case the newly selected hour was not selected.
