### ISSUE TITLE
Spreadsheet duplicates headers on filtering 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5867]
### Reproduction of the problem
1. Download the excel file attached in Ticket ID: 1469596
2. Open it in the [Spreadsheet](https://demos.telerik.com/kendo-ui/spreadsheet/server-side-import-export).
3. Filter a column, for example the "Anatomy" column, deselect all and leave only "Abdo".
4. Filter another column, for example Timepoint Name. Deselect all and select only V31. Note that this value does not match any "Abdo" row. Because of that, in Excel "V31" is not even available in the filter, once the "Anatomy" column is filtered by "Abdo". In the Spreadsheet the second column can be filtered by "V31". 

### Current behavior
No data is displayed after filtering the second column (expected), but the header is duplicated. 

Additional notes: the file has been tested against the Open XML SDK tool and it reports 4 issues related to Fonts, however, the duplication occurs even after modifying the original file and applying an arbitrary font and font-size to the whole document, so that it passes the tool's verification successfully.

### Expected/desired behavior
No data is displayed and there is no header duplication.

### Environment

* **Kendo UI version:** 2020.2.607
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by martintabakov** [comment]
Also reported in 1479790

**Comment by veselints** [comment]
The issue will be present only when the initial number of rows in the Spreadsheet is smaller than the number of rows present on the imported XLSX Sheet that is about to be filtered. In order to avoid that issue, set the initial number of rows in the Spreadsheet to a greater value:
```js
$("#spreadsheet").kendoSpreadsheet({
  rows: 5000
});
```

Here is a Dojo sample implementing the above suggestion:
https://dojo.telerik.com/iBEjEREG/2
