### ISSUE TITLE
ColumnMenu in grid hides wrong columns and JS error appears when column without title is placed first

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#5870]
### Bug report
ColumnMenu in Grid does not hide/unhide the correct column when command column is placed first

### Reproduction of the problem
1. Open the [Dojo](https://dojo.telerik.com/ipeqEpUV)
2. Open the columnMenu for one of the columns
3. Try to select a column, for example "Unit in Stock"

### Current behavior
Currently, the previous column is checked/unchecked and respectively hidden ("Unit Price")

### Expected/desired behavior
The column that is selected in the columnMenu should be hidden or displayed and checked/unchecked in the columnMenu

### Environment

* **Kendo UI version:** 2020.2.617
* **Browser:** [all ]

**Comment by IvanDanchev** [comment]
The issue is reproducible with columns that have no title and are not placed last in the columns configuration.

**Comment by IvanDanchev** [comment]
Another scenario the issue is reproducible in: [https://dojo.telerik.com/ENuMAvoX/4](https://dojo.telerik.com/ENuMAvoX/4)

All columns have **title** set, but the first column's **menu** option is disabled.

**Comment by CecoMilchev** [comment]
Also reported in ticket ID: 1475235

**Comment by Anton-Mironovv** [comment]
Also reported in ticket ID: 1473046 (a Dojo example is provided)

**Comment by M2xAy** [comment]
Also reported in ticket-Id: 1475693

**Comment by Alex-Bubblemaster** [comment]
Also reported in ticket 1477559.  Same scenario as mentioned by @IvanDanchev.

**Comment by PekoPPT** [comment]
Also reported in ticket #1477678

**Comment by nelito987** [comment]
Also reported in ticket #1478303
