### ISSUE TITLE
FileManager Renaming nested folders throws 404 error

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5873]
### Bug report

When using the FileManager initialized using the TagHelper and renaming nested folders a 404 error is thrown.

### Reproduction of the problem
 1. Run the [FileManager TagHelper Demo](https://demos.telerik.com/aspnet-core/filemanager/tag-helper)
 1. Create several nested folders
 1. Rename a parent folder
 1. Rename child folders of the renamed parent folder
 1. Rename the same parent folder

[Issue reproduction screencast](https://www.screencast.com/t/GunjZIOmZ)
### Current behavior
A 404 - File or directory not found is returned

### Expected/desired behavior
The folder should be renamed

### Environment

* **Kendo UI version:** 2020.2.617
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible on the demo with version 2023.3.1114
