### ISSUE TITLE
Javascript exception on loading a file in the Spreadsheet

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5878]
### Reproduction of the problem
Use the file attached in Ticket ID: 1472882. It has been tested for validity in Open XML SDK, and the tool does not show any issues in the file.

### Current behavior
A javascript exception is thrown on loading the file:
*Uncaught TypeError: e.name is not a function*

### Expected/desired behavior
No exception on loading the file

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by veselints** [comment]
The bug on our end has been fixed. There are a number of external references in the XLSX file, however, which are not supported by the Spreadsheet widget.
