### ISSUE TITLE
Calling filter() for empty ListBox duplicates the items

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5882]
### Reproduction of the problem
1. Run this sample - https://dojo.telerik.com/aMaHABUz/11
2. Move all items to the right ListBox
3. Click the button

### Current behavior
Items in the left ListBox are duplicated

### Expected/desired behavior
Items should not be duplicated

### Environment

* **Kendo UI version:** 2020.2.617
* **Browser:** [all ]

**Comment by gyankov** [comment]
The described behavior is expected as when there is no data within the dataSource and an operation is executed, the dataSource will fetch the data before executing the operation. To avoid the current behavior you could either sync the server whenever an item is removed from the listbox, this way when the request is sent, the server will return no items and the issue will not occur. Another solution would be to check if the dataSource contains any items before executing the operation.

e.g.

```
            if (listBox.dataSource._data.length) {
              listBox.dataSource.filter({});
            }
```
