### ISSUE TITLE
Editor Image Browser does not recognize the file path when a folder is created in ASP.NET Core 3.1

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#5885]
### Bug report

When the user creates a folder and tries to add a file to the Editor an error occurs that the file is not found. This behavior is observed only if the application is Core 3.1. 

### Reproduction of the problem
1. Open [Image and File Browser Demo](https://demos.telerik.com/aspnet-core/editor/imagebrowser)
2. In the ImageBrowser create a folder.
3. Upload an image and try to add it to the Editor

### Current behavior
Currently, in the console, an error 404 occurs that the resource is not found.

### Expected/desired behavior
The image should be added to the Editor without errors.

### Environment

* **Kendo UI version:** 2010.2.617
* **Browser:** [all ]

**Comment by gyankov** [comment]
Issue no longer replicates:

![image-editor](https://user-images.githubusercontent.com/16634965/173349179-ef1d693c-1143-40da-af1a-77516cd6cecb.gif)
