### ISSUE TITLE
Add support for selecting item when value field is of boolean type

### ISSUE THREAD

**Issue by rusev** [telerik/kendo-ui-core#589]
The [value](http://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist#methods-value) method is documented to support only `string` type parameters.

However you can set the widget value even if you provide `numeric` value as a key. Demonstrated [here](http://dojo.telerik.com/@rusev/ARoSe). But this doesn't work for `boolean` as in the following [example](http://dojo.telerik.com/@rusev/UkEPI).

**Comment by ggkrustev** [comment]
Related to #475

**Comment by naskog** [comment]
Corresponding automated test: SelectBooleanType_589.html
