### ISSUE TITLE
FileManager's DataSource read doesn't contain data about the targeted for opening folder when defined as function

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#5890]
### Bug report
When the "dataSource -> transport ->read" configuration of the FileManager is defined as a function, the parameters available in this function doesn't contain any data about the targeted for opening folder.

### Reproduction of the problem
1. [Open this Dojo example](https://dojo.telerik.com/ErOGeWaW) and run it
2. See the logged value of the "options" variable in the browser's console. 

### Current behavior
The options.data property inside the "read" function of the dataSource doesn't have a value.

### Expected/desired behavior
The options.data property inside the "read" function should contain information about the folder that the user has navigated to.

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** x.y
* **Browser:** [all] 

Feedback Item: https://feedback.telerik.com/kendo-jquery-ui/1473893-filemanager-no-path-passed-to-datasource-read-method

**Comment by nelito987** [comment]
Reported also in ticketId: 1475084

**Comment by PekoPPT** [comment]
The workaround suggested by the client who reported the issue: https://dojo.telerik.com/@GaloisGirl/OJUPoYOY/2

**Comment by GaloisGirl** [comment]
Here's a nicer version: https://dojo.telerik.com/@GaloisGirl/OJUPoYOY/3

**Comment by mparvanov** [comment]
No path passed to dataSource create method as well (Reported in ticket: 1497019):
**Steps to Replicate:**

1. Run the sample https://dojo.telerik.com/@GaloisGirl/OJUPoYOY/8
2. Navigate to "folder1"
3. Click "New Folder"
4. Check JavaScript log

**Actual result**: the call to "create" has no information that the new folder should be created in "folder 1"
**Expected result**: the call to "create" should contain information about the path, for my back-end to create an entry in the correct place

**Comment by Iankodj** [comment]
The target parameter is not included in the data in the transport operations when declared as functions because the DataSource doesn't call the [parameterMap method](https://docs.telerik.com/kendo-ui/api/javascript/data/datasource/configuration/transport.parametermap) declared. 

That said, it is possible to include it by calling it in the function declared. This will be updated in the API documentation of the FileManager as well: 

```js
<div id="fileManager"></div>
    <script>
        var baseUrl = "https://demos.telerik.com/kendo-ui/service/filemanager/";

        $("#fileManager").kendoFileManager({
            dataSource: {
                transport: {
                    read: function(options) {
                        var that = this;

                        $.ajax({
                            url: baseUrl + "Read",
                            dataType: "json", 
                            method: "POST",
                            data: that.parameterMap ? that.parameterMap(options.data, "read") : options.data,
                            success: function(result) {
                                options.success(result);
                            }
                        });
                    },
                    update: function(options) {
                        var that = this;

                        $.ajax({
                            url: baseUrl + "Update",
                            dataType: "json", 
                            method: "POST",
                            data: that.parameterMap ? that.parameterMap(options.data, "read") : options.data,
                            success: function(result) {
                                options.success(result);
                            }
                        });
                    },
                    create: function(options) {
                        var that = this;

                        $.ajax({
                            url: baseUrl + "Update",
                            dataType: "json", 
                            method: "POST",
                            data: that.parameterMap ? that.parameterMap(options.data, "read") : options.data,
                            success: function(result) {
                                options.success(result);
                            }
                        });
                    },
                    destroy: function(options) {
                        var that = this;

                        $.ajax({
                            url: baseUrl + "Destroy",
                            dataType: "json", 
                            method: "POST",
                            data: that.parameterMap ? that.parameterMap(options.data, "read") : options.data,
                            success: function(result) {
                                options.success(result);
                            }
                        });
                    }
                }
            }
        });
    </script>
```
