### ISSUE TITLE
Upload placeholder is hidden if drag and drop action is not completed

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5891]
### Bug report

The Upload placeholder is hidden if drag and drop action is not completed.

### Reproduction of the problem
1. Run the [Async Upload demo](https://demos.telerik.com/kendo-ui/upload/async)
1. Drag a file over the drop zone, but do not release the file
1. Cancel the drag and drop

### Current behavior
The placeholder disappears after canceling the drag and drop event. The placeholder will once again become visible after dragging a file over the dropzone. See the screencast attached.
[Upload_placeholder.zip](https://github.com/telerik/kendo-ui-core/files/4878668/Upload_placeholder.zip)

### Expected/desired behavior
The placeholder should always be visible.

### Environment

* **Kendo UI version:** 2020.2.617
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible with 2023.3.1114 - the placeholder does not hide on dragging a file over the Upload.
