### ISSUE TITLE
[Duplicate] Grid column menu hides wrong columns

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#5893]
### Bug report

In the attached project, a wrong column will be hidden if you try to use the column menu feature. Also, an error will be thrown for the first two fields. 

### Reproduction of the problem
1. Download and run the attached project.
2. Open the column menu and try to hide "Display Name" column. The DueDate column will be hidden instead.
3. Try to hide one of the first two column. An error will be thrown

[webapplication1.zip](https://github.com/telerik/kendo-ui-core/files/4883137/webapplication1.zip)

### Expected/desired behavior
The correct columns should be hidden and no errors should be thrown.

### Environment

* **Kendo UI version:** 2020.2.617
* **Browser:** [all]

**Comment by dmanova** [comment]
Seems similar to https://github.com/telerik/kendo-ui-core/issues/5870
