### ISSUE TITLE
Grid pager number contains incorrect control type

### ISSUE THREAD

**Issue by ylux587** [telerik/kendo-ui-core#5903]
### Bug report
Grid pager number contains incorrect control type

### Reproduction of the problem
Render grid with pagination enabled. When there are multiple pages, page number shows in footer bar. Open AI4D and verify Control type is incorrect for page number "1"  control and no name property exist.

### Current behavior
Issue 1: Control type is incorrect for page number "1"  control.
Given control type for "page number "1" control is "list" which is incorrect.

Issue 2: Name property does not exist for page number "1" control

![image](https://user-images.githubusercontent.com/10621694/86947422-9d36da80-c100-11ea-88aa-3569bd23d2b9.png)
![image](https://user-images.githubusercontent.com/10621694/86947464-aa53c980-c100-11ea-894a-061f4d3629ca.png)

### Expected/desired behavior
Issue 1: Correct control type should be given for page number "1" control.

Issue 2: Name property should exist for page number "1" control

### Environment

* **Kendo UI version:** Kendo UI version: 2019.3.1114
* **jQuery version:** 3.3.28
* **Browser:**Chromium Edge Version: 84.0.488.1 (Official build) dev (64-bit)
* **AI4D Version:** 1.1.1152.1

**Comment by GaloisGirl** [comment]
Isn't it a list of page numbers?

**Comment by ylux587** [comment]
> Isn't it a list of page numbers?

Yes, this is what we are referring to.

**Comment by ag-petrov** [comment]
I did examine the markup in [this ](https://demos.telerik.com/kendo-ui/grid/index)demo which has enabled paging but did not observer any control type assignments? Can you please modify the demo so it illustrates the case?

Additionally can you please elaborate on why should the control contain a name? Is there some accessibility rule that needs to be applied? Bear in mind that the pager is not accessible via keyboard thus normally the screen readers will not be able to get a hold of it to read its data.

**Comment by ylux587** [comment]
Hi, Petrov,

It is regarding the accessibility. We have an internal tool to value it. I think the pager needs to be keyboard or screen reader accessible to make it fully accessibility compatible. The Name property is for the screen reader I think

**Comment by ylux587** [comment]
Or anyway we can workaround it?
