### ISSUE TITLE
Combobox does not render correct control type

### ISSUE THREAD

**Issue by ylux587** [telerik/kendo-ui-core#5906]
### Bug report

Combobox does not render correct control type

### Reproduction of the problem
render a combobox and then open AI4D to check control type. 

### Current behavior
Issue 1:
Name property does not exist for the combo box.

Issue 2:
Control type is incorrect for combo box.

![image](https://user-images.githubusercontent.com/10621694/86948501-13880c80-c102-11ea-9ca3-63d57d90d4f0.png)

### Expected/desired behavior
Issue 1:
Name property should be provided for the combo box.

Issue 2:
The correct control type should be provided for the combo box.

### Environment

* **Kendo UI version:** Kendo UI version: 2020.2.513
* **jQuery version:** 3.5.1
* **Browser:**Chromium Edge Version: 84.0.488.1 (Official build) dev (64-bit)
* **AI4D Version:** 1.1.1152.1

**Comment by veselints** [comment]
The developer can specify the input name attribute. As per the control type, the reported issue does not demonstrate a WCAG or WAI-ARIA violation. Hence, closing it.

**Comment by fsteffi** [comment]
@veselints we have discussed with SME and this issue should be fixed specifically regarding the role. Having a correct role is required by WCAG standards.

**Comment by veselints** [comment]
@fsteffi may I ask you to clarify which is the correct role for the ComboBox widget according to [WCAG](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.1)? Could you, please, explain why the current role (`role="combobox"`) is not appropriate for the ComboBox widget?

**Comment by Shivamd1** [comment]
@veselints The provided role is "listbox" for the "Owning Team" . The expected is "combo box"

**Comment by veselints** [comment]
@Shivamd1 I am not quite sure what do you mean by `The provided role is "listbox" for the "Owning Team" .`. If you refer to the element that the `aria-owns` property points to, `combobox` would not be a valid value. Here is the WAI-ARIA specification section on the `combobox` role:
`A composite widget containing a single-line textbox and another element, such as a listbox or grid, that can dynamically pop up to help the user set the value of the textbox.`

Hence, the `input` (textbox) points to its `listbox` pop-up.

Here is the full WAI-ARIA specification on the `combobox` role:
https://www.w3.org/TR/wai-aria-1.1/#combobox

**Comment by Shivamd1** [comment]
@veselints Here as per the discussion with SME the role property should be as combobox at https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html when checking with dev tools->inspect->accessibility.

**Comment by veselints** [comment]
@Shivamd1 I do not know what do you mean by "SME". Nevertheless, the `role` of the ComboBox focusable element (its `<input>`) is `combobox`.

As per the role `listbox` on the list of pop-up elements, that is preset on the `<ul>` containing the drop-down options:
```
<ul unselectable="on" class="k-list k-reset" tabindex="-1" aria-hidden="true" id="size_listbox" aria-live="off" data-role="staticlist" role="listbox">
```

For reference, inspect the following demo:
https://demos.telerik.com/kendo-ui/combobox/index

Is there anything else I am missing?

**Comment by Shivamd1** [comment]
As per the bug logged "Combo box does not render correct control type" here the control type given is "listbox" instead of combobox. Also as per: https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html  the control type should be combo box for the lists containing the dropdown options. You can check the attached screenshot 
SME is our subject matter experts.

![image](https://user-images.githubusercontent.com/60880975/106103871-9b4d6b00-6167-11eb-8a69-6aa0ec1fa36e.png)
