### ISSUE TITLE
DateTimePicker shows NaN in some cases when componentType set to "modern"

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#5912]
### Reproduction of the problem
1. Open the[ Component Type example](https://demos.telerik.com/kendo-ui/datetimepicker/component-type)
1. Click icon, go to time and set it to 12:59 AM
1. Click icon again and set time to 1:59 PM

Video: https://screencast-o-matic.com/watch/cYiQ2P5GMx

### Current behavior
The picker shows NaN/NaN/0NaN 12:NaN PM

### Expected/desired behavior
The picker should display the selected time and date

### Environment

* **Kendo UI version:** 2020.1.617

**Comment by gyankov** [comment]
This has already been reported and fixed. https://github.com/telerik/kendo-ui-core/issues/5865
