### ISSUE TITLE
TreeView control render <li> element with role "treeitem"

### ISSUE THREAD

**Issue by ylux587** [telerik/kendo-ui-core#5913]
### Bug report

TreeView control render <li> element with role "treeitem"

### Reproduction of the problem
Initiate a treeview control, observe the rendered html

### Current behavior
<li> element rendered as role="treeitem".

### Expected/desired behavior
treeitem is not an allowed role

### Environment

* **Kendo UI version:** Kendo UI version: 2019.3.1114
* **jQuery version:** 3.3.28
* **Browser:**Chromium Edge Version: 84.0.488.1 (Official build) dev (64-bit)

**Comment by Dimitar-Goshev** [comment]
@ylux587 According to W3C treeitem is a role, which is set to li or a element and identifies it as a treeitem. References:
- https://www.w3.org/TR/wai-aria-practices/#tree_roles_states_props 
- https://www.w3.org/TR/wai-aria-practices/examples/treeview/treeview-2/treeview-2a.html
