### ISSUE TITLE
Kendo upload control select files button has unaligned Name property value

### ISSUE THREAD

**Issue by ylux587** [telerik/kendo-ui-core#5917]
### Bug report

Kendo upload control select files button has unaligned Name property value

### Reproduction of the problem
Build a dialog with kendo upload control. Check accessibility and check the Select files... button's name property

### Current behavior
The value of Name property is Choose a file
![image](https://user-images.githubusercontent.com/10621694/87214878-74bc0580-c2e5-11ea-8a42-cb1862d38145.png)

### Expected/desired behavior
It should be aligned with label, which is Select files...

### Environment

* **Kendo UI version:** Kendo UI version: 2019.3.1114
* **jQuery version:** 3.3.28
* **Browser:**Chromium Edge Version: 84.0.488.1 (Official build) dev (64-bit)
* **AI4D Version:** 1.1.1152.1

**Comment by dmanova** [comment]
The value of the Name property is configurable and developers could give it a value they want.
