### ISSUE TITLE
resource value in Scheduler not set correctly when validation fails one time

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#5925]
### Bug report
resource value in Scheduler not set correctly when validation fails one time

### Reproduction of the problem
https://dojo.telerik.com/@zdravkov/ahevozEw/2

### Current behavior
1: double click some slot to create new appointment
2: select Room resource to be Meeting room 1
3: save

the event don't have any selected resource 

### Expected/desired behavior
the event have selected resource Meeting room 1

### Environment

* **Kendo UI version:2020.2.617
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
Not reproducible with 2023.3.1114 - https://dojo.telerik.com/@Dimitar-Goshev/EkISAhAb
