### ISSUE TITLE
A rule with undefined selector is generated in a custom theme created with the LESS Themebuilder

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5926]
### Reproduction of the problem
1. Go to the [Themebuilder page](https://demos.telerik.com/kendo-ui/themebuilder/)
2. Select BlueOpal theme
3. Modify the "Error" color. 
4. Download the custom theme

### Current behavior
The generated kendo.custom.css file contains the following rule: 

```
undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined .k-text-error {
  color: #7030a0;
}
```

### Expected/desired behavior
The rule should have correct selector, or if it is redundant it should not be included in the file. 

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
LESS ThemeBuilder is deprecated.
