### ISSUE TITLE
FileManager's messages.toolbar.uploadDialog does not update toolbar's upload button text

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#5927]
### Bug report

The option for the toolbar's upload button message is incorrect. It should be `messages.toolbar.upload`. 

### Reproduction of the problem
https://dojo.telerik.com/UyOcafAt

### Current behavior
`uploadDialog` does not update the message. As a result, the generated wrappers also lack of possibility to set a message for the Upload tool

### Expected/desired behavior
https://dojo.telerik.com/eBIjafaB

**Comment by Dimitar-Goshev** [comment]
Error in TagHelper messages -> toolbar:
![Untitled - Paint 2020-10-28 16 35 25](https://user-images.githubusercontent.com/6614183/97450787-c42d4c80-193b-11eb-9522-7fd2104a9ab2.png)
