### ISSUE TITLE
numerictextbox focuses on the wrong input on iPad

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#593]
Description from ticket 913781:

> When tapping an input element on the iPad, the browser scrolls that element to the center of the screen. However, the tap event seems to be firing again after the scroll is completed and targeting whatever us under the initial tap location after the scroll. You can reproduce with your Grid / Popup editing demo:

> Using iOS 7 on an iPad (I was on 4th generation iPad)
> Change orientation to landscape
> Browse here: http://demos.telerik.com/kendo-ui/grid/editing-popup
> Tap the Edit button on the first row (Chai)
> Tap the Unit Price input to bring up keyboard.
> Tap Units in Stock (browser scrolls to bring that input to vertical center)
> Tap Unit Price again
> Note that Product Name gets the focus after the scroll, even though you tapped unit price

**Comment by valchev** [comment]
I was not able to reproduce the issue with the latest Kendo UI release.
