### ISSUE TITLE
Upload events are not exposed

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#5933]
### Bug report

Relevant Upload events can be triggered through the FileManager widget directly (like [upload](https://docs.telerik.com/kendo-ui/api/javascript/ui/upload/events/upload)). 

### Reproduction of the problem
Upload events are missing from the wrapper components.

### Workaround
Handling the events with client-side code: 

```
@(Html.Kendo().FileManager().Name("filemanager")
    ...
)

<script>
    $(document).ready(function () {
        var filemanager = $("#filemanager").getKendoFileManager();

        filemanager.upload.bind("upload", function (e) {
             e.data = {
                additionalInfo: "additionalInfo"
            };
        })
    })
</script>

```

**Comment by Dimitar-Goshev** [comment]
Duplicate of #5841
