### ISSUE TITLE
Persist selection does not work with group paging

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#5936]
### Bug report

Persist selection does not work with group paging

### Reproduction of the problem
Enable group paging and persist selection in a grid. Then group the grid.

### Current behavior
A JS error is thrown.

### Expected/desired behavior
Should work as expected.

### Environment

* **Kendo UI version:** 201x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by dmanova** [comment]
Notes from Internal Testing:
The JS error is not appearing anymore, but the selection is not persistent. The rows get unselected when the data is refreshed, fetched, e.g. between pages. This looks like a probable limitation.
