### ISSUE TITLE
The Editor ImageBrowser sends only up to 25 requests for thumbnails

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#5939]
### Bug report

When opening the Editor ImageBrowser if more than 25 images are available only up to 25 requests for thumbnails are sent. The bug is a regression introduced with v2020.2.513

### Reproduction of the problem
1. For an Editor configured as in the [ImageBrowser Demo](https://demos.telerik.com/aspnet-mvc/editor/imagebrowser) containing more than 25 images
1. Open the ImageBrowser and scroll down 

### Current behavior
Thumbnail requests are not sent for all images

### Expected/desired behavior
Thumbnail requests should be sent for all images

### Environment

* **Kendo UI version:** 2020.2.513
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
Also mentioned in ticket# 1484937

**Comment by Juveniel** [comment]
This issue is no reproducible with the latest version 2020.3.915.

/cc @Dimitar-Goshev
