### ISSUE TITLE
kendoForm is not a function

### ISSUE THREAD

**Issue by dday9** [telerik/kendo-ui-core#5940]
### Reproduction of the problem
Call the kendoForm function on a DOM element.
Dojo fiddle: https://dojo.telerik.com/acaXaceX

### Expected/desired behavior
The kendoForm function should be supported? Not sure, it isn't specified in the README.

### Environment
* **Kendo UI version:** 2020.2.617
* **jQuery version:** 1.12.4
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
@dday9 kendoForm is not part of the open-source kendo-ui-core - it is not included in the [src folder](https://github.com/telerik/kendo-ui-core/tree/master/src). I will note that in the README as well.
