### ISSUE TITLE
Spreadsheet throws "Maximum call stack size exceeded" when loading formula with more that 60 IF() statements

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5942]
### Bug report
Spreadsheet trows "Maximum call stack size exceeded" when loading a formula with more that 60 IF() statements

### Reproduction of the problem
Run the following Dojo:
https://dojo.telerik.com/@sspasova/aJAkUREw

### Expected/desired behavior
The widget should not throw an error and the formula should be properly calculated.

### Environment
* **Kendo UI version:** 2023.3.1114
* **Browser:** [all]

**Comment by mishoo** [comment]
Not reproducible with the provided sample, but I'm not closing it yet — it is possible that a deeply nested formula will blow the stack...

**Comment by sspasova** [comment]
> Not reproducible with the provided sample, but I'm not closing it yet — it is possible that a deeply nested formula will blow the stack...

@mishoo I was able to reproduce the issue with the provided [Dojo](https://dojo.telerik.com/@sspasova/aJAkUREw) and Kendo UI  2023.3.1114. Can you retest please?

**Comment by pepinho24** [comment]
Not reproducible with version 2024.4.1112
