### ISSUE TITLE
Wizard.insertAt() uses the default buttons set, while removeAt() keeps the current state for the already present Steps that need to be updated

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5943]
### Enhancement
Wizard.insertAt() uses the default buttons set, while removeAt() keeps the current state for the already present Steps that need to be updated. We should review the case and ensure consistency across those methods.

**Comment by Dimitar-Goshev** [comment]
Inserting a new step after a step with defined custom buttons resets those buttons to default ones:
1. Keyboard navigation demo setup
1. Execute the following script:
```
    var wizard = $("#wizard").getKendoWizard();
    wizard.insertAt(4, {
                            title: "Next Btn only-4",
                            buttons: ["next"]
                        });
```
1. Although the inserted step is the last one, it has only Next button, as specified in its definition - expected.
1. Execute the following script to insert a new step after the previously inserted one:
```
    wizard.insertAt(5, {
                            title: "Next Btn only-5",
                            buttons: ["next"]
                        });
```
1. Next Btn only-4 has its buttons reset to default ones, not taking into account its specified Next button only - not expected.

Note: inserting a step before the previously inserted one does not reset its buttons to default ones:
```
    var wizard = $("#wizard").getKendoWizard();
    wizard.insertAt(4, {
                            title: "Next Btn only-4",
                            buttons: ["next"]
                        });
	wizard.insertAt(4, { title: "Step before" });
```

**Comment by Dimitar-Goshev** [comment]
Removing the last step after a step with defined custom buttons resets those buttons to default ones:
1. Keyboard navigation demo setup
2. Execute the following script:					
```
var wizard = $("#wizard").getKendoWizard();
    wizard.insertAt(4, {
                            title: "Next Btn only-6", // 6
                            buttons: ["next"]
                        });
    wizard.insertAt(4, {
                            title: "Next Btn only-5", // 5
                            buttons: ["next"]
                        });

    wizard.insertAt(4, {
                            title: "Next Btn only-4", // 4
                            buttons: ["next"]
                        });	
```	
				
3. Removing a step, which is not the last one does not reset buttons to steps around it - 6 and 4.
`wizard.removeAt(5)`

But if instead of step 5, we remove the last step, this resets the buttons of the step, which becomes last.
`wizard.removeAt(6)`
