### ISSUE TITLE
Grid misalignment on column resize in RTL with scrollbar 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5952]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/iReweciC/11) example.

1. Make several columns wider and then shrink one of them (See the attached video). 
[Recording31.zip](https://github.com/telerik/kendo-ui-core/files/5016110/Recording31.zip)

### Current behavior
Columns and headers are misaligned.

### Expected/desired behavior
Columns and headers are properly aligned.

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** x.y
* **Browser:** [Chrome XX]

**Comment by hamedhossani** [comment]
Hello,
I founded the reason for it
class ```k-grid-header-wrap``` has ```position:relative```  

Created for this reason.
