### ISSUE TITLE
kendo-ui-core build fails on Windows

### ISSUE THREAD

**Issue by yongzhao1** [telerik/kendo-ui-core#5953]
### Bug report

**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our feedback portal](https://www.telerik.com/support/feedback)**

### Reproduction of the problem
_(bug report only)_

1. clone the kendo-ui-core repository
2. open project folder in VS Code (windows 10, 64bit)
3. `
npm run build
`  

### Current behavior
_(optional)_
build fails with the following error:

> npm WARN bootstrap@4.5.0 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.
npm ERR! code EEXIST
npm ERR! path C:\Users\XXX\Source\Repos\Norfolk-Southern\kendo-ui-core\node_modules\acorn\bin\acorn
npm ERR! dest C:\Users\XXX\Source\Repos\Norfolk-Southern\kendo-ui-core\acorn.cmd
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\XXX\Source\Repos\Norfolk-Southern\kendo-ui-core\node_modules\acorn\bin\acorn' -> 'C:\Users\XXX\Source\Repos\Norfolk-Southern\kendo-ui-core\acorn.cmd'
npm ERR! File exists: C:\Users\XXX\Source\Repos\Norfolk-Southern\kendo-ui-core\acorn.cmd
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXX\AppData\Roaming\npm-cache\_logs\2020-08-03T23_23_00_202Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kendo-ui-core@1.0.0 build: `npm install && gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kendo-ui-core@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXX\AppData\Roaming\npm-cache\_logs\2020-08-03T23_23_00_384Z-debug.log

### Expected/desired behavior
build succeeds

### Environment

* **Windows:** 10.0.17134
* **nodejs:** 14.6

**Comment by dmanova** [comment]
@yongzhao1 it seems the issue you are experience is due to incompatibility between the node version and the kendo build script. Please, until this is solved, use nodejs version older than v. 11.15.0

If you need to manage multiple installations of node.js consider [NVM](https://github.com/nvm-sh/nvm)
