### ISSUE TITLE
Backspace jumps back and deletes unexpected content when &nbsp; in the content

### ISSUE THREAD

**Issue by a-d-atanasov** [telerik/kendo-ui-core#5957]
### Bug report

When there are `&nbsp;` in the content of the editor the backspace sometimes jumps back and deletes unexpected content.

### Reproduction of the problem
Content to reproduce with:

```html
<p>Hello</p>
<p><a href="https://google.com" target="_blank">Link</a>&nbsp; Some more text,&nbsp;</p>
<p>Regards</p>
```

Video: [link](https://www.screencast.com/t/pR95pokrq)

### Current behavior
The link at the start of the row is removed.

### Expected/desired behavior
The character before the cursor to be removed.

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Not reproducible with 2023.3.1114 - https://dojo.telerik.com/@Dimitar-Goshev/oManaGOS
