### ISSUE TITLE
RTL navigation arrows: wrong direction in Material theme

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#597]
Happens when the arrow is not hovered.
Can be replicated on:
http://demos.telerik.com/kendo-ui/calendar/right-to-left-support
http://demos.telerik.com/kendo-ui/datepicker/right-to-left-support

![image](https://cloud.githubusercontent.com/assets/961037/6574361/83aea0ee-c72c-11e4-89a3-d81e33679b3b.png)

**Comment by inikolova** [comment]
Commit: ea45834c047096
