### ISSUE TITLE
Kendo Observable is missing properties in TypeScript 3.9

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5973]
### Bug report
Due to the following change in TypeScript (https://github.com/microsoft/TypeScript/pull/32264#issuecomment-636226201), in some scenarios, the Kendo observable is missing properties in TypeScript 3.9.

### Reproduction of the problem
Steps to reproduce the issue are present in Support thread 1480700

### Expected/desired behavior
Observable creation logic should not rely on the enumeration of property definitions.

### Environment
* **Kendo UI version:** 2020.2.617

**Comment by benpetermorris** [comment]
This is a significant problem for everyone using TypeScript + Kendo; without a workaround, upgrading to TypeScript 3.9 is impossible. Please reconsider the low severity assigned to this issue.

**Comment by Iankodj** [comment]
This will be part of a bigger effort about upgrading the TS version in Kendo. This is logged internally only: https://github.com/telerik/kendo/issues/11548

**Comment by mparvanov** [comment]
The following setup could be used for testing:
```
/// <reference path="jquery.d.ts" />
/// <reference path="kendo.all.d.ts" />

  
  $(function () {
 
    class EncounterClass {
      registration: any;
      constructor () {
        this._mrn = "initial value";
      }
          _mrn: string;
          public get mrn(): string {
              if (this.registration) {
                  return this.registration.mrn;
              }
              return this._mrn;
          }
          public set mrn(value: string) {
              this._mrn= value;
          }
    }
    
    var array =new kendo.data.ObservableArray([new EncounterClass(), new EncounterClass()])
    console.log(array);
    
    
      $("#grid2").kendoGrid({
      columns: [
       
        { field: "mrn", template: (encounter) => {
            return `<span id="area${encounter.mrn}" >${encounter.mrn}</span>`;
        } }
      ],
      dataSource: array,
    });
   
  });
  
  
```
