### ISSUE TITLE
Tabstrip InsertBefore and InsertAfter examples incorrect

### ISSUE THREAD

**Issue by dustbort** [telerik/kendo-ui-core#598]
In the [documentation](http://docs.telerik.com/kendo-ui/api/javascript/ui/tabstrip#methods-insertBefore),  the `referenceTab` argument is shown to be obtained by `tabStrip.tabGroup.eq(0)`.  However, this doesn't work (click the "Edit this example" button and see).  From testing, I found that a correct expression is `tabStrip.tabGroup.children().eq(0)`.

Also, why is a numerical index argument for `referenceTab` not supported (like for `select()`)? A numerical argument gives us an abstraction and keeps us out of the DOM.

**Comment by KirilNN** [comment]
Hi @dustbort,

Thanks for pointing out this issue in the `insertBefore` example, I have added the correct statement with the following commit:

https://github.com/telerik/kendo-docs/commit/267491895c65f08fbb5d2cdce6141647c4de799a

As for the numerical index - I will forward this feedback to the team (thanks again for that)
