### ISSUE TITLE
VB: Wizard HTML helper throws "'Form' is ambiguous because multiple kinds of members with this name exist in class 'Kendo.Mvc.UI.Fluent.WizardStepBuilder'." when Form is atempted to be configured on one of its Steps

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5986]
### Bug report
VB: Wizard HTML helper throws "'Form' is ambiguous because multiple kinds of members with this name exist in class 'Kendo.Mvc.UI.Fluent.WizardStepBuilder'." when Form is atempted to be configured on one of its Steps

### Reproduction of the problem
Run the following project (do not forget to add the Kendo.Mvc.dll in the appropriate folder):
[VbAddIssue.zip](https://github.com/telerik/kendo-ui-core/files/5118343/VbAddIssue.zip)

### Expected/desired behavior
The VB HTML helper should not throw an error.

### Environment
* **Kendo UI version:** 2020.2.607
* **Browser:** [all]

**Comment by ovreiuvictor** [comment]
Hello,

The problem can be solved by installing Microsoft.CodeDom.Providers.DotNetCompilerPlatform package from NuGet, witch comes with Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll and a configuration for system.codedom compilers added in web.confing

See repository below for example:
https://github.com/ovreiuvictor/VbWizzardHtmlIssue.git

**Comment by gyankov** [comment]
Cannot replicate with 2021 R2 version.
