### ISSUE TITLE
MultiSelect with Virtualization loses value of its select element after selecting a filtered item, which belongs to the first page of its DataSource

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#5987]
### Bug report
MultiSelect with Virtualization loses value of its select element after selecting a filtered item, which belongs to the first page of its DataSource.

### Reproduction of the problem
- Run the below project
[EmailNotPosted.zip](https://github.com/telerik/kendo-ui-core/files/5123334/EmailNotPosted.zip)

- Open browser console - note that the value() of the widget and the val() of its select are logged on the console;
- In the MultiSelect input area type "22";
- Select the item "22" - note that the selected item is logged for both the value() and the val();
- Click outside of the widget to blur it - the val() will no longer return value. It logs an empty array;

### Expected/desired behavior
MultiSelect should not lose the values in its `<select>` element.

### Environment
* **Kendo UI version:** 2020.2.617
* **Browser:** [all]

**Comment by veselints** [comment]
As a workarownd you should:
- Disable animation;
- Implement the following handler for the MultiSelect close event:
```js
function onClose(e) {
	setTimeout(function () {
		e.sender.value(e.sender.value())
	});
}
```

**Comment by aleksandarevangelatov** [comment]
Closing as no longer reproducible with `v2024.2.514`.
