### ISSUE TITLE
Excel file created with Workbook toDataURL method is corrupted

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5988]
### Bug report
Excel file is corrupted when it is created with the kendo.ooxml.Workbook toDataURL method, using stringified sheet data:

```
let dataURL = new kendo.ooxml.Workbook(JSON.stringify(data)).toDataURL();
```

If the data is passed to the Workbook without stringifying it, this causes a circular reference error (check the console).

```
let dataURL = new kendo.ooxml.Workbook(data).toDataURL();
```

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/oQAWIgUS) example.
1. Click the "To Json" button above the Spreadsheet. 
2. Try to open the generated file in Excel.

### Current behavior
The generated Excel file is corrupted

### Expected/desired behavior
The generated Excel file is not corrupted

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by veselints** [comment]
This is not a bug in the Workbook initialization functionality. It is an improper way of initializing the class. The proper way to do so would be:
```js
let dataURL = new kendo.ooxml.Workbook(JSON.parse(JSON.stringify(data))).toDataURL();
```
Note that the Workbook init would expect a JS object and not a string.

Here is a fully working Dojo sample:
https://dojo.telerik.com/oQAWIgUS/4
