### ISSUE TITLE
Editor table resize handles duplicated on making changes to the table then undoing them

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#5996]
### Reproduction of the problem
Reproducible in the [demos](https://demos.telerik.com/aspnet-core/editor/index).
1. Click inside a cell in the table
2. Click the "Delete row" button in the toolbar.
3. Use a keyboard shortcut to "Undo" the delete action.
4. Focus the table
5. Resize the table.
6. Observe two sets of resize handles.

### Current behavior
Resize handles duplication

### Expected/desired behavior
No duplication of the resize handles

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** x.y
* **Browser:** [Chrome 85]

**Comment by Dimitar-Goshev** [comment]
The fix throws an error in IE:
Object doesn't support property or method 'forEach'
