### ISSUE TITLE
ToolBar captures move and up cancel events on document level

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#6002]
### Bug report
ToolBar captures move and up cancel events on document level. This prevents other dropdowns to open as expected on mobile browsers in desktop mode.

Note: reported in ticket 1482568 and 1454790

### Reproduction of the problem
1. Open the following [Dojo](https://dojo.telerik.com/OTukIKoG) on real device browser in desktop mode - Android Chrome 85 in Desktop mode; iOS 13 Safari in Desktop mode;
1. Tap on the select2 dropdown

### Current behavior
The dropdown is not opened as the [ToolBar](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.toolbar.js#L977) captures document ["move" and "up cancel"](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.userevents.js#L362-L363) events

### Expected/desired behavior
The dropdown is opened.

### Environment
* **Kendo UI version:** 2020.2.617
* **jQuery version:** x.y
* **Browser:** Android Chrome 85 in Desktop mode; iOS 13 Safari in Desktop mode;

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket #1483686
