### ISSUE TITLE
When using a ComboBox as a From editor with ServerFiltering enabled the text parameter is not passed to the defined action method

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6003]
### Bug report

When using a ComboBox as a From editor and ServerFiltering is enabled the `text` parameter is not passed to the defined action method. The same behavior is observed with the DropDownList, DropDownTree, and MultiSelect widgets when used as editors in the Form.

### Reproduction of the problem
The below configuration passes only the filters, but not the text parameter as in the [ComboBox server filtering demo](https://demos.telerik.com/aspnet-core/combobox/serverfiltering)
```
.Editor(e =>
    {
    e.ComboBox()
        .HtmlAttributes(new { })
        .Placeholder("Select...")
        .DataTextField("ProductName")
        .DataValueField("ProductID")
        .HtmlAttributes(new { style = "width:100%" })
        .Height(520)
        .DataSource(source => {
             source.Read(read => {
                 read.Action("Items_GetProducts", "Form");
               })
            .ServerFiltering(true);
        });
  });
```

### Expected/desired behavior
When using a ComboBox as a From editor and ServerFiltering is enabled the `text` parameter should be passed to the defined action method.

### Environment

* **Kendo UI version:** 2020.2.617
* **Browser:** [all]

**Comment by nelito987** [comment]
Reported also in ticket:  1483935

**Comment by veselints** [comment]
The ComboBox snippet above is missing the `Filter()` configuration method, which is essential to make filtering work in the widget:
```
.Filter(FilterType.Contains)
```
That should be the first step in the process of "fixing" the above.

Apart from that, the `text` member being sent to the ComboBox Read endpoint in a stand-alone scenario is an implementation sugar added on top of the default server filtering behavior of the widget. It automatically adds the following `data` function to the widget:
```
"data": function() { 
    return kendo.ui.ComboBox.requestData(jQuery("#products")); 
}
```
Such a function, however, would not be added in the form, as it uses the `IFormEditor` interface to initialize its editors. Having that said, the approach that should be followed in the above case is either:

1. define the above `data` function manually:
```
read.Action("Items_GetProducts", "Home").Data("onData");
```
and:
```
function onData(e) {
	return kendo.ui.ComboBox.requestData(jQuery("#Test")); // use here the name of the property in the Form model
}
```

or:
2. Configure the DataSource to send an AJAX request containing `DataSourceRequest` data and use that request on the server:
```
.DataSource(source =>
{
	source.Custom()
		.Type("aspnetmvc-ajax")
		.Transport(t => t
			.Read(read =>
			{
				read.Action("Items_GetProducts", "Home").Type(HttpVerbs.Post);
			})
		)
		.ServerFiltering(true);
});
```
and:
```
public ActionResult Items_GetProducts([DataSourceRequest]DataSourceRequest request)
{
    var result = //Get the full list of items for the ComboBox

    return Json(result.ToDataSourceResult(request).Data);
}
```
