### ISSUE TITLE
RTL Grid header vanishes in Chrome 85+

### ISSUE THREAD

**Issue by behnam7171** [telerik/kendo-ui-core#6004]
### Bug report
unexpected vanish of kendo grid header. more accurately, the wrong position of the header when resize handler appended.

### Reproduction of the problem

https://dojo.telerik.com/oLuToGek
In the link above just move the horizontal scroll of the grid to the end, then hover any column header. then the header vanishes.
this happens when resizable is true and parent element has 'k-rtl' class.

### Expected/desired behavior
the resize handler of the grid work properly to find the correct position of the resize handler.

debug:
in method _createResizeHandle, where you check for WebKit, the scrollLeft method returns the wrong value only in chrome. which in my opinion is not your bug, it is chrome's bug.
Hope you can provide a workaround for it.

### Environment

any kendo version
jquery: 3.2.1
**browser: only latest chrome (Version 85.0.4183.83 (Official Build) (64-bit)), other browsers are fine.**

**Comment by behnam7171** [comment]
@NikoPenev21 do you have any idea about this?

**Comment by behnam7171** [comment]
@NikoPenev21 I believe the bug you mentioned is different.
The bug I reported happens on hover and to calculate resize Handler, not the position of the column after resizing,
Please take a look at the dojo I sent and try to reproduce.

Best regards.

**Comment by hamedhossani** [comment]
I have this problem too.

**Comment by Dimitar-Goshev** [comment]
@behnam7171 Thank you for reporting this scenario.
The issue is related to a change introduced with Chromium 85 via the CSSOM View Scroll Coordinates flag in the browser. Chromium no longer uses that flag from 86 on. The follow the new logic without any possibility for a fallback. Further details on that could be found here:
https://bugs.chromium.org/p/chromium/issues/detail?id=721759

**Comment by behnam7171** [comment]
Thank you for resolving the bug.
Just wanted to say that chrome version 86 and also edge chromium version 86 both have same issue.
