### ISSUE TITLE
Tabstrip InsertAfter example incorrect

### ISSUE THREAD

**Issue by dustbort** [telerik/kendo-ui-core#601]
As identified in case #598, both the InsertBefore and InsertAfter examples are broken, but only the InsertBefore example was fixed.  Please fix the [InsertAfter example](http://docs.telerik.com/kendo-ui/api/javascript/ui/tabstrip#methods-insertAfter), too.

**Comment by KirilNN** [comment]
Hi @dustbort,

This commit fixes the insertAfter example as well: https://github.com/telerik/kendo-docs/commit/33c6635e294c9dde7d0312b5783d670be4e65294

Please log all documentation issues in the kendo-docs repo - https://github.com/telerik/kendo-docs

Thanks.
