### ISSUE TITLE
Form: Cannot set Max Property on NumericTextBox in ASP.Net Core and MVC Wrappers.

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6023]
### Bug report

Cannot set Max Property on NumericTextBox in ASP.Net Core and MVC Wrappers.

### Reproduction of the problem
1. Create a project with a Form.
2. Define a NumericTextBox Editor as below:
```
i.Add()
    .Field(f => f.NumericTextBox)
    .Label(l => l.Text("NumericTextBox:"))

    .Editor(e =>
    {
        e.NumericTextBox()
        .Spinners(false)
        .Format("n0")
        .Max(10);                           
    })
```

### Current behavior
The max property is not being applied.

### Expected/desired behavior
The max property should be set.

### Environment

* **Kendo UI version:** 2020.2.619
* **Browser:** [all]

**Comment by IvanDanchev** [comment]
Also reported in Ticket ID: 1486857.

The issue affects other options as well: **Min**, **Step**

```
.Editor(e =>
{
    e.NumericTextBox().Max(1000).Min(0).Format("n0").Decimals(0).Step(10);
});
```
