### ISSUE TITLE
Wizard tag helper used in an editor template causes a js exception

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6026]
### Reproduction of the problem
1. Adding a Wizard tag helper to a Grid's editor template throws an "Invalid or unexpected token" exception. No exception is thrown when using the Html helper.

```
<kendo-wizard name="wizard" on-done="onDone">
	<wizard-steps>
		<wizard-step title="Start">
			<wizard-step-buttons>
				<wizard-step-button name="next" text="Next"></wizard-step-button>
			</wizard-step-buttons>
			<wizard-step-content>
			</wizard-step-content>
		</wizard-step>
		<wizard-step title="User details">
			<wizard-step-buttons>
				<wizard-step-button name="previous" text="Previous"></wizard-step-button>
				<wizard-step-button name="done" text="Register"></wizard-step-button>
			</wizard-step-buttons>
			<wizard-step-content>
			</wizard-step-content>
		</wizard-step>
	</wizard-steps>
</kendo-wizard>
```

2. For a sample project see Ticket ID: 1484465

### Current behavior
js exception on using the Wizard tag helper in an editor template

### Expected/desired behavior
no js exceptions on using the tag helper in an editor template

### Environment

* **Kendo UI version:** 2020.2.617
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by veselints** [comment]
Sample to test with:
[Uploading TelerikAspNetCoreApp148_Mod1.zip…]()
