### ISSUE TITLE
Invalid CSS in the base file of the Bootstrap LESS theme

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6032]
### Reproduction of the problem
The kendo.common-bootstrap.min.css file contains the following rule:
```
.k-time-container{padding-right:100px;padding-left:100px;margin-left:-100px;margin-right:-100px;margin-"left":-117px}
```
that sets margin-left incorrectly: **margin-"left"**

### Environment

* **Kendo UI version:** 2020.3.915
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by joneff** [comment]
There was some invalid string interpolation, hence the issue. Fixed
