### ISSUE TITLE
There is unnecessary border in Grid Filter menu in Sass themes

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6041]
### Reproduction of the problem
1. Open the [following Demo](https://demos.telerik.com/kendo-ui/grid/filter-multi-checkboxes) with one of the SASS themes.
2. Open the filter menu for the ProductName column 

### Current behavior
There is an additional border around the search input. The border appears when Sass is used.

### Expected/desired behavior
The additional border should be removed.

### Environment

* **Kendo UI version:** 2020.3.915
* **Browser:** [all]

**Comment by nelito987** [comment]
Reported also in ticket ID: 1503903

**Comment by PreslavKozovski** [comment]
Related to: https://github.com/telerik/kendo-themes/issues/2119
