### ISSUE TITLE
Rotate Feature for Asp.net Core Image-Editor

### ISSUE THREAD

**Issue by M2xAy** [telerik/kendo-ui-core#6051]
Hi Telerik Team

Please add rotate function to the asp.net core Image Editor.

Thank you very much and best regards

Murat

**Comment by Dimitar-Goshev** [comment]
@M2xAy 
Thank you for your feedback. As the new issue template suggests, please submit a feature request at [our feedback portal](https://www.telerik.com/support/feedback). As ASP.NET Core are server-side wrappers of Kendo UI, please submit it at https://feedback.telerik.com/kendo-jquery-ui

> **For Feature Requests - please submit those into [our feedback portal](https://www.telerik.com/support/feedback)**
