### ISSUE TITLE
DatePicker popup in Spreadsheet is not rendered properly when multiple cells are merged vertically

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6076]
### Bug report

When multiple cells are merged in the Spreadsheet the DatePicker is not always rendered at the correct position. 

### Reproduction of the problem
1. Open the [Demo](https://demos.telerik.com/kendo-ui/spreadsheet/validation)
2. Merge the cells vertically for rows 6-20.
3. Reduce the browser size to set the scrollbars, so the Spreadsheet scrollbar to not be at its top position.
4. Open the DatePicker. 
 
### Current behavior
The DatePicker is not always entirely visible ([screencast](https://www.screencast.com/t/4RKgazyb))

### Expected/desired behavior
DatePicker should be visible

### Environment

* **Kendo UI version:** 2020.3.915
* **Browser:** [all ]

**Comment by Iankodj** [comment]
Not reproducible with the latest version.

**Comment by mparvanov** [comment]
With the current implementation the date picker is shown on the top in case there is sufficient space for the popup  from the top right corner of the selected cell. Otherwise the date picker is shown on the bottom of the selected cell from the bottom right corner of the selected cell.
