### ISSUE TITLE
ComboBox selection is not displayed after page is restored from the Back-Forward Cache in Firefox

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6079]
### Bug report

When making a selection, navigating to another page, and going back to the initial page, which is restored from the Back-Forward Cache in Firefox, the selection of the ComboBox is not displayed.

### Reproduction of the problem
1. Go to the [ComboBox demo](https://demos.telerik.com/kendo-ui/combobox/index)
1. Make a selection in the ComboBoxes
1. Click on any other demo link in the navigation pane to the left (e.g. “Server Filtering”)
1. Press the "Back" browser button

### Current behavior
The selections made are not displayed when the page is restored from the Back-Forward Cache 
### Expected/desired behavior
The selections made should be displayed when the page is restored from the Back-Forward Cache 

### Environment

* **Kendo UI version:** 2020.3.915
* **Browser:** [Firefox 81.0.2]

**Comment by zdravkov** [comment]
We have inspected the issue and it seems like there is not much to be done. Here is a [dojo example ](https://dojo.telerik.com/@zdravkov/ocIrIviF) and if you open it in FireFox and in Full Screen from the button in the upper right corner we can observe that after selecting a new item, clicking navigate to Telerik link and going back with Back button the console.logs in the script tag on the page are not executed.
The only workaround for the moment is adding window.onunload = function () { }; on application level as it is done in this [dojo](https://dojo.telerik.com/@zdravkov/UNeCOYof).

If anybody have idea how it could be fixed - we will be glad to reopen the issue and review them.
