### ISSUE TITLE
Cannot resize columns in a scrolled grid

### ISSUE THREAD

**Issue by amir3321** [telerik/kendo-ui-core#6081]
### Cannot resize columns in a scrolled grid

when use grid with scroll can not resize column .when column qty and width equal grid width show icon resize but after resize not show icon or qty and width gte grid width not show icon resize .
i use grid in tabstrip.

### Environment

* **Kendo UI version:** 2020.r2.513(Asp.net core)
* **jQuery version: v1.12.4 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by veselints** [comment]
@amir3321 is the observed issue present when the Grid is in RTL in Chrome? If yes, the problem has been solved within the following issue:
https://feedback.telerik.com/kendo-jquery-ui/1487148-chrome-rtl-horizontal-scroll-grid-bugs
The SP where the fix will be resent is scheduled for next week.

**Comment by amir3321** [comment]
Thank you very much
