### ISSUE TITLE
Drag & drop

### ISSUE THREAD

**Issue by AlexNoodl** [telerik/kendo-ui-core#6089]
Hello. I have a problem with drag & drop grid rows. In my project i need to add line-through style to row on which applied double click event.  If i have rows with line-through styles and use drag & drop on one of these rows or other rows, all styles are reset. How can i save styles when use drag & drop event?

**Comment by dmanova** [comment]
Hi @AlexNoodl I would suggest taking a look at Grid option [persistSelection](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/persistselection). Maybe you could reuse some of Kendo UI options to achieve what you need. I make a Dojo sample similar to what you describe, but with a single click selection:
https://dojo.telerik.com/IPEBEpOj

If this doesn't help you solve your problem you may proceed with one of the following:

**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our feedback portal](https://www.telerik.com/support/feedback)**

**Comment by AlexNoodl** [comment]
Thank you. I was able to solve my question on my own)) Issue can be closed.
