### ISSUE TITLE
On Android devices a click-through occurs when selecting an item from the AutoComplete popup list

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#6092]
### Bug report

When using the AutoComplete on Android devices and an element is present below the popup list of options, selecting an item that is located over the said element, triggers a click event of the element.

### Reproduction of the problem

1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/OvUDOgaJ) on an Android device 
1. Type "a"
1. Select "Andorra"

### Current behavior
The AutoComplete makes the selection, however, the underlying button's click event is also triggered.

### Expected/desired behavior
The underlying button's click event should not be triggered

### Environment

* **Kendo UI version:** 2020.3.1021
* **Browser:** [all]

**Comment by Iankodj** [comment]
Adding the viewport meta tag in the document solves the case: https://dojo.telerik.com/UJANidOz.

The tag is required for web applications dedicated that are opened in mobile devices: https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag. https://assets.grammarly.com/emoji/v1/1f610.svg

**Comment by poyker** [comment]
> Adding the viewport meta tag in the document solves the case: https://dojo.telerik.com/UJANidOz.

Unfortunately, we can still reproduce it on your Dojo above.

As explained in the initial bug report, you need an extra step to reproduce it when using Kendo.all.min.js (easier to reproduce using only the individual components - https://dojo.telerik.com/azAFINIz/13 )

1. Type "a"
2. Click on "Andorra". Works fine this time (the button is not clicked) and "Andorra" is added in the input with the countries.
3. Delete "Andorra" using the backspace button on your phone (not using the "x" at the end of the input). 
4. Type "a" again and click on "Andorra". This time the button below is also clicked.

Hope the steps above will help you to reproduce it!

**Comment by Iankodj** [comment]
In order to have the AutoComplete working properly in mobile, you need to also enable the mobile scroller as well. 
![image](https://user-images.githubusercontent.com/4222379/97688892-81868400-1aa3-11eb-9fc4-e6a693d45d36.png)

https://dojo.telerik.com/azAFINIz/14

**Comment by poyker** [comment]
> In order to have the AutoComplete working properly in mobile, you need to also enable the mobile scroller as well.
> ![image](https://user-images.githubusercontent.com/4222379/97688892-81868400-1aa3-11eb-9fc4-e6a693d45d36.png)
> 
> https://dojo.telerik.com/azAFINIz/14

Thanks @Iankodj 

I tried your Dojo example on my phone but I am still able to replicate the issue.
I recorded a [video ](https://photos.app.goo.gl/8gWocCaa24DnYivLA) on my phone. 

Many thanks for your help! It is much appreciated!
