### ISSUE TITLE
Duplicate TextBox border 

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#6099]
### Bug report
Duplicate TextBox border when parent font size is 12px

### Reproduction of the problem
1. Run the following[ Dojo snippet](https://dojo.telerik.com/ICItaman/5)

### Current behavior
![Untitled _ Kendo UI Dojo - Mozilla Firefox 2020-10-27 18 01 54](https://user-images.githubusercontent.com/6614183/97328282-8a4a4080-187e-11eb-85b9-c56289678bfa.png)

### Expected/desired behavior
[Dojo 2020.1.406](https://dojo.telerik.com/iteKOBIn)
![Untitled _ Kendo UI Dojo - Mozilla Firefox 2020-10-27 18 02 26](https://user-images.githubusercontent.com/6614183/97328335-9930f300-187e-11eb-93cf-78f5bab72c1a.png)

### Environment
* **Kendo UI version:** 2020.3.1021
* **Browser:** all

**Comment by martintabakov** [comment]
Also reported in ticket #1492935

**Comment by Juveniel** [comment]
Also reported in TicketID: #1493790

**Comment by NikoPenev21** [comment]
Also reported in #1495118

**Comment by NikoPenev21** [comment]
Reported in #1499555
