### ISSUE TITLE
TreeView does not render items after a failed read of the data source

### ISSUE THREAD

**Issue by darrenedale** [telerik/kendo-ui-core#6100]
### Bug report

When a TreeView is initialised using data attributes, successful reads of the data source that happen after a failed read of the data source cause the TreeView to fail to render the retrieved data. A tree view configured similarly using javascript initialisation (rather than data attributes) does not exhibit this behaviour, and renders the retrieved data correctly under these circumstances.

Two dojo snippets demonstrate the issue:

1. The issue is present, using data-attribute initialisation, [here - http://dojo.telerik.com/@dedale/iloDiSam/3](http://dojo.telerik.com/@dedale/iloDiSam/3)
2. The issue is **not** present, using JS code initialisation, [here - http://dojo.telerik.com/@dedale/OkomoCEr](http://dojo.telerik.com/@dedale/OkomoCEr)

### Reproduction of the problem
1. Open the snippet referenced in 1 above.
2. **Run** the snippet.
3. The data source read will fail and the TreeView will display the default "data fetch error" message.
4. Click the **Retry** button.
5. The data source read will succeed.
6. The tree view will not have its items rendered, and will continue to display the "data fetch error" message.

### Current behavior
Currently, when initialised with data attributes, the tree view will not render the items on a successful data fetch if there has previously been a failed data fetch.

### Expected/desired behavior
When initialised using data attributes, the TreeView should behave the same as it does when initialised using JS code. Repeat the _Steps to Reproduce_ with dojo snippet 2 referenced above to see the expected behaviour.

### Environment

* **Kendo UI version:** 2019.3.1023, 2020.3.1021
* **jQuery version:** 1.12.3
* **Browser:** Chrome 85.0.4183.121

**Comment by mparvanov** [comment]
The issue is happening also without using data attributes when using setDataSource :
https://dojo.telerik.com/irulacAy
When setting       var doFail = false; initially the Treeview items are rendered properly:
 https://dojo.telerik.com/IBOzuvoC

**Comment by darrenedale** [comment]
For anyone who needs a (horrific) workaround for this and can't wait for the fix, you can work around the issue in a **very** hacky way by storing a reference to the main `<ul>` from the TreeView after it has been initialised, then clearing and re-inserting the `<ul>` into the tree view in a `requestEnd` handler on the data source, if the tree view doesn't already have it (i.e. after a previous failed data fetch). **BE WARNED THAT THIS IS A VERY BAD IDEA BECAUSE IT MESSES WITH PRIVATE IMPLEMENTATION DETAILS OF THE TREEVIEW WIDGET. ONLY USE IT IF YOU'RE _REALLY_ VERY DESPERATE. AND EVEN THEN, YOU SHOULD SERIOUSLY THINK ABOUT WHETHER IT'S WORTH IT BECAUSE IT COULD VERY EASILY HAVE CATASTROPHIC SIDE-EFFECTS.** You have been warned.

See code snippets below.

### Store reference to main UL
    var treeViewUlElement = treeView.element.find(">ul");

### Clear and resinsert
    if (treeViewUlElement && 0 === treeView.element.find(">ul").length) {
        $(treeViewUlElement).empty();
        treeView.element.empty();
        treeView.element.append(treeViewUlElement);
    }

YMMV. It works for me, for now, in the one place where I really can't be without it, and the code is very heavily commented for removal once the fix is released.

Mods, feel free to delete this comment if you're unhappy with it. I'm well aware how stupid this code is.

**Comment by mparvanov** [comment]
The issue has been ficed with #5781 and will be available with the internal build next week.
