### ISSUE TITLE
Horizontal and vertical lines appear in merged Spreadsheet cells that are disabled

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#6107]
### Bug report

Horizontal and vertical lines appear in the merged Spreadsheet cells when they are disabled. 

** Possible workaround could be to apply the following CSS:
```
      #spreadsheet > div.k-spreadsheet-view > div.k-spreadsheet-fixed-container > div.k-spreadsheet-pane > div.k-spreadsheet-data > div.k-state-disabled {
        opacity: 1;
        color: #a3a3a3;
      }
```

### Reproduction of the problem
1. [Open this Dojo](https://dojo.telerik.com/AlufiLum) and run it
2. There are is a horizontal line above the cell with text "Merged DISABLED cell and there is a horizontal line above". There is a vertical line inside the cell with text "Two cells are merged horizontally and the result cell is disabled. There is a vertical line that should not appear"

### Current behavior
When Spreadsheet cells are merged and the result cell is disabled, there are horizontal or vertical lines that appear inside the merged cell.  
![image](https://user-images.githubusercontent.com/41293735/97589304-0622c500-1a06-11eb-8a63-9f874012eb1c.png)

### Expected/desired behavior
No lines should appear inside the merged cells, no matter if they are enabled or disabled. 

### Environment

* **Kendo UI version:** 2020.3.1021
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by veselints** [comment]
I have tried the following two approaches, with no success:
- Setting `opacity: 1` on the `.k-spreadsheet-cell.k-state-disabled` and setting `opacity: 0.6` on the inner text container. That would not result in opacity being applied to the background of the cell;
- Using a pseudo :after element to overlay the `.k-spreadsheet-cell.k-state-disabled`

**Comment by martintabakov** [comment]
Also reported in #1557769

**Comment by veselints** [comment]
The fix is yet not scheduled for implementation. I have just raised the priority of this item, so that it moves sooner in our implementation queue.
