### ISSUE TITLE
Broken preview appearance and server errors on theme download due to slow themes build process

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#6108]
### Bug report
When creating a theme through ThemeBuilder, there is a themecompiler request, whose response takes more than two minutes. Waiting so long for a response is not acceptable and also it is a regressions since this behavior was not reproducible before R3 2020. Also there is no loading indicator showing that we are waiting for something to happen.

There are several scenarios to reproduce an issue caused by slow build process.
 
### Reproduction of the problem 1
1. Go to https://demos.telerik.com/kendo-ui/grid/index
1. Expand Edit dropdown and select "Edit in Theme Builder"

### Current behavior
ThemeBuilder preview loads with no content. After several minutes the preview appears without styles.

### Expected/desired behavior
The Preview shows a Grid for editing.

### Reproduction of the problem 2
1. Go to https://themebuilder.telerik.com/kendo-ui
1. Select Start Theming
1. Click Create
1. After the preview loads, expand the dropdown, deselect Menu and collapse the dropdown
1. Click Download, type theme name and click OK

### Current behavior
Server error:
```
iisnode encountered an error when processing the request.

HRESULT: 0x6d
HTTP status: 500
HTTP subStatus: 1013
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.
```

### Expected/desired behavior
No error, custom theme is downloaded

### Reproduction of the problem 3
1. Go to https://themebuilder.telerik.com/kendo-ui
1. Select Start Theming
1. Unselect Breadcrumb and Tabstrip (or something else, e.g. Menu)
1. Click Create
1. After swatches load, immediately select Download, type theme name and click OK

NOTE: When there are deselected widgets, it may take 4 minutes to load the preview. Even then, the widgets are severely corrupt.
However, if we leave Tabstrip and Breadcrumb selected, this doesn't seem to happen.

### Current behavior
Server error:
```
iisnode encountered an error when processing the request.

HRESULT: 0x6d
HTTP status: 500
HTTP subStatus: 1013
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.
```

### Expected/desired behavior
No error, custom theme is downloaded

### Environment
* **Kendo UI version:** 2020.3.915
* **Browser:** all

**Comment by Gardens18** [comment]
Any update on this issue ?

**Comment by Dimitar-Goshev** [comment]
@Gardens18 We are currently working on fixing the issue. We will update its status, once done.

**Comment by StoyanGoranov** [comment]
Reopened after a report in 1507626

**Comment by StoyanGoranov** [comment]
Steps for reproduction of the issue provided by client:
1. Go to Themebuilder (https://themebuilder.telerik.com/)
2. Select Kendo UI
3. Import Theme
4. Upload file attached to ticket (scss)
5. Click Download

I haven't been able to reproduce this issue.

**Comment by Dimitar-Goshev** [comment]
Closing it due to not reproducing the issue.
