### ISSUE TITLE
One month only in daterangepicker

### ISSUE THREAD

**Issue by castilloedwin** [telerik/kendo-ui-core#6116]
Hello everyone, what I'm gonna say it's not a bug. I just want to know how can I display one calendar only in daterangepicker. Thanks a lot.

**Comment by dmanova** [comment]
Hi @castilloedwin there isn't such an option in the Kendo DateRangePicker out of the box. You could enter a feature request in our feedback portal:
https://feedback.telerik.com/kendo-jquery-ui?listMode=Recent&categoryId=1947

Or try to configure the MultiViewCalendar that is used inside the  DateRangePicker like in this Dojo sample:
https://dojo.telerik.com/oPOsIjOt

**Comment by dmanova** [comment]
If you still have questions you may proceed with one of the following:

**For Support request - Please do not submit support request here, instead see the** [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our feedback portal](https://www.telerik.com/support/feedback)**
