### ISSUE TITLE
A PDF file shows upside down in dpl case

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#6117]
### Bug report

A specific PDF file (example can be found in ticket : 1493640) shows upside down in DPL case
### Reproduction of the problem
Run the DPL processing demo locally and replace the file with the one provided in the ticket

### Current behavior
The file is shown upside down
### Expected/desired behavior
The file should not be rendered upside down

### Environment

* **Kendo UI version:** 2020.3.1021

**Comment by SyntaxEvg** [comment]
Have you been able to fix this problem?
![image](https://user-images.githubusercontent.com/94603687/184470749-235b4d82-ac30-405f-8007-0a02da10e944.png)

**Comment by aleksandarevangelatov** [comment]
The issue in the sample pdf file provided in ticket 1493640 seems to be related to an edge case - there is a negative horizontal scale, negative font size and negative position applied to the TextFragments in the PDF file. However, the horizontal scale is not exposed in the TextRenderingContext and therefore not serialized, resulting in an incorrect text rendering matrix. 

An internal issue is logged, to expose the HorizontalScale property and once implemented the report will be revisited.
