### ISSUE TITLE
The caret is printed when the Editor's "print" tool is used

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6123]
### Reproduction of the problem
Reproducible in [demos ](https://demos.telerik.com/aspnet-mvc/editor/all-tools) in Chrome.
1. Click on the "Print" tool in the toolbar. 

### Current behavior
The Editor's content is focused and the caret is printed. 

### Expected/desired behavior
The caret is not printed.

### Environment

* **Kendo UI version:** 2020.3.1021
* **jQuery version:** x.y
* **Browser:** [Chrome 86]

**Comment by IvanDanchev** [comment]
Priority raised: Ticket ID: 1493840

**Comment by sspasova** [comment]
I am closing this issue as no longer reproducible in jQuery demos using Chrome and Kendo UI 2023.3.1114.
