### ISSUE TITLE
Error is thrown if an event is created/update by double click/tap in Scheduler

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6129]
### Bug report

When the **_mobile_** option of the Scheduler is set to **_true_** and the user double click/double-tap the Edit dialog is opened, but when saving the event, the following error is thrown in the console:

'_Cannot read property 'isOccurrence' of undefined_'

### Reproduction of the problem
1. Open the [Dojo example](http://dojo.telerik.com/@NeliKondova/aCaloVux) in the emulator.
2. Double click fast to edit or create an event
3. Try to save the event

### Current behavior
An error is thrown in the console ([screencast](https://www.screencast.com/t/ZN5OWtxFY9))

### Expected/desired behavior
There should be no error in the console 

### Environment

* **Kendo UI version:** 2020.3.1021
* **Browser:** [all  ]

**Comment by veselints** [comment]
Entering edit mode on mobile devices is implemented to work on SINGLE tap. Double-tapping to edit/create is not among the supported scenarios for the Scheduler. Hence, I am lowering the severity.
