### ISSUE TITLE
Tooltip close button misaligned after R2 2020 

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#6132]
### Bug report

After R2 2020 when the Tooltip has "autoHide:false" and the width is explicitly configured the close button is not aligned to the right, but is placed right after the Tooltip content.

### Reproduction of the problem

1. Run this [dojo](https://dojo.telerik.com/@Stoyan/AGALoYIN)
1. Hover over the Tooltip target and note the position of the close button

v2020.2.513 and later:
![image](https://user-images.githubusercontent.com/46348689/98917519-26a65100-24d5-11eb-8fa2-d056057738a5.png)
v2020.1.406:
![image](https://user-images.githubusercontent.com/46348689/98917603-476ea680-24d5-11eb-9ad6-60efea96f578.png)

### Expected/desired behavior
The close button should be aligned to the right

### Environment

* **Kendo UI version:** 2020.2.513 and later
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
The following CSS can be used as a workaround:
```
.k-tooltip-content{
    flex: auto;
}
```
