### ISSUE TITLE
The TextArea doesn't display the model value passed from a controller 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#6135]
### Bug report
When a TextArea is submitted in a form, the entered data is correctly passed to the controller. If we return this data back from the controller to the View, the model field value is not loaded by the TextArea.  

*When the controller data is returned to the View, a "value" attribute appears in the TextArea. This value attribute holds the model field value sent by the controller. 

### Reproduction of the problem
1. Open this project - [TextBoxIssues.zip](https://github.com/telerik/kendo-ui-core/files/5524848/TextBoxIssues.zip) and run it. 
1. Click on the "Text Area Test" link
1. Enter random data in the two fields that will load and submit the form. The data entered in the TextBox and TextArea is submitted to the controller and returned back to the view. 

### Current behavior
After the data is returned from the controller, the "Name" input keeps the data entered before the form submit but the "Reason" TextArea is empty. 

### Expected/desired behavior
After the form is submitted and the data from the controller is returned to the View, both the "Name" input and the "Reason" textarea should contain the values entered before submission.
 

### Environment

* **Kendo UI version:** 2020.3.1021
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by gyankov** [comment]
Fixed with https://github.com/telerik/kendo/commit/4d0cd9130e0be91042431051c3b2c65b96ee6ccb.

**Comment by thad-determinism2** [comment]
https://stackdev.space/questions/access-the-textarea-element-through-code-behind After a long search for a solution, I discovered the answer
