### ISSUE TITLE
Workbook data is exported incorrectly when it contains merged cells in a column

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6141]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/iSisOkaN) example.

### Current behavior
Data is exported incorrectly.

### Expected/desired behavior
Data is exported correctly (see the Spreadsheet export)

### Environment

* **Kendo UI version:** 2020.3.1021
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by IvanDanchev** [comment]
After further investigation we came to the conclusion that this is the expected behavior when the cells don't have index specified. The following example shows how to properly export the data by setting the cells index: [https://dojo.telerik.com/aBUBuGab/2](https://dojo.telerik.com/aBUBuGab/2)

**Comment by aldenpoole** [comment]
How can I get the named range of the cells I want to merge from their index? Is named range the only way to use the mergedCells property?
