### ISSUE TITLE
Tooltip inconsistent positioning when large content is loaded 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6148]
### Bug report

[WebSite12.zip](https://github.com/telerik/kendo-ui-core/files/5561698/WebSite12.zip)

### Reproduction of the problem
A sample WebSite is attached.
1. Run the Test page. 
2. Click on the "Click me" text.
3. The Tooltip shows up (note its position).
4. Close the Tooltip.
5. Click on the text again.

### Current behavior
Initially the Tooltip shows up positioned in such way that most of its content not visible. If you close the Tooltip and click the "Click me" text to show it again, it is shown over the whole page. 

### Expected/desired behavior
The positioning on first opening is incorrect. The Tooltip should be positioned identically in both cases (when opened for the first time, and on subsequent opening).

### Environment

* **Kendo UI version:** 2020.3.1021
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by joneff** [comment]
If the issue is related to kendo-jquery, can you make a strip down dojo out of it?

**Comment by IvanDanchev** [comment]
@joneff
The attached website basically contains two Html pages, one with the Tooltip and the other is the content loaded in the Tooltip. So the scenario is isolated as much as possible. The issue is not reproducible in the dojo, because in that case the content will have to be loaded from another domain and this makes the Tooltip render it in an iframe. The issue is not exhibited when an iframe is rendered, i.e. the content must be loaded from the same domain, to avoid it being placed in an iframe, thus I've attached a website with a test page and a content page.
