### ISSUE TITLE
Unable to install Telerik.UI.for.AspNet.Core 2020.3.1118 NuGet package

### ISSUE THREAD

**Issue by dsteinweg** [telerik/kendo-ui-core#6149]
### Bug report

I am unable to install the Telerik.UI.for.AspNet.Core NuGet package (version 2020.3.1118) into a project that has a PackageReference to `Microsoft.VisualStudio.Web.CodeGeneration.Design` version 5.0.0 installed.  I get the following error message in Visual Studio (Error Code NU1107):

```
Version conflict detected for Microsoft.CodeAnalysis.CSharp.Workspaces. Install/reference Microsoft.CodeAnalysis.CSharp.Workspaces 3.7.0 directly to project TelerikRepro to resolve this issue. 
 net5 -> Microsoft.VisualStudio.Web.CodeGeneration.Design 5.0.0 -> Microsoft.VisualStudio.Web.CodeGenerators.Mvc 5.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration 5.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore 5.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration.Core 5.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration.Templating 5.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration.Utils 5.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces (>= 3.7.0) 
 net5 -> Telerik.UI.for.AspNet.Core 2020.3.1118 -> Microsoft.CodeAnalysis 3.3.1 -> Microsoft.CodeAnalysis.CSharp.Workspaces (= 3.3.1).
```

`Microsoft.VisualStudio.Web.CodeGeneration.Design` is used for scaffolding certain items (controllers, Razor pages) in Visual Studio.  If this package is removed, the Telerik package _does_ install successfully.  Or, if you have 3.x.x version of `Microsoft.VisualStudio.Web.CodeGeneration.Design` installed, like 3.1.4, the Telerik package also installs fine.

The crux of the issue seems to stem from `Telerik.UI.for.AspNet.Core` having a dependency on a specific version of `Microsoft.CodeAnalysis`, version 3.3.1, and NuGet must not jump major versions from 3.x to 5.x.

If you follow the instructions in that error message and directly install `Microsoft.CodeAnalysis.CSharp.Workspaces` version 3.7.0 into the project, you get another similar error, this time with package `Microsoft.CodeAnalysis.Common`.  If you continue down this path, you can eventually get the Telerik package to install, but VS still shows version mismatch warnings in the Error List.

I am attempting to install the Telerik .nupkg from my on-premise Azure DevOps package source, but I imagine the result would be the same when using Telerik's package repository at https://nuget.telerik.com.

### Reproduction of the problem
Create a .NET 5.0 .csproj with the following contents:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.0" />
  </ItemGroup>
</Project>
```
Then try to install `Telerik.UI.for.AspNet.Core` version 2020.3.1118 from a NuGet package source -- either Telerik's or a custom location, and you should get this error.

It also happens with prior versions of `Telerik.UI.for.AspNet.Core` and `Microsoft.VisualStudio.Web.CodeGeneration.Design` version 5.0.0, though I don't know which ones exactly.

### Current behavior
N/A

### Expected/desired behavior
Expected that the Telerik package installs successfully.

### Workaround
Don't upgrade `Microsoft.VisualStudio.Web.CodeGeneration.Design` to version 5.0.0 -- leave it on a 3.x.x version.  Alternatively, remove this package from the project if it's not needed (since it's only a design-time package used for scaffolding items in Visual Studio).

### Environment
* **Visual Studio version:** 16.8.1
* **Kendo UI version:** 2020.3.1118
* **jQuery version:** N/A
* **Browser:** N/A

**Comment by Dimitar-Goshev** [comment]
Hi @dsteinweg ,

Thank you for explaining the observed behavior in details. We have a troubleshooting article related to it - [Upgrading to .NET 5](https://docs.telerik.com/aspnet-core/troubleshoot/troubleshooting-net5).

`Telerik.UI.for.AspNet.Core 2020.3.1118` requires 3.3.1 or higher version of the following packages, as its dependencies show - [NuGet package version references](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges).

```
    <PackageReference Include="Microsoft.CodeAnalysis" Version="3.3.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.3.1" />
```

Based on the version ranges table it is not clear to me why NuGet considers the reference as exact version, instead of minimum version.

Automatic dependencies resolution is not achieved by updating the `Microsoft.VisualStudio.Web.CodeGeneration.Design` reference to 5.0.0 and trying to restore packages. Note that in this case the update of the dependency is from 3.3.1 to 3.7.0 - no major version update is required. And currently the highest version of the package is 3.8.0 - no new major version available.

As the error suggests, installing package `Microsoft.CodeAnalysis.CSharp.Workspaces` 3.7.0 directly to project resolves that issue.

Then a second conflict is shown, which concerns `Microsoft.CodeAnalysis.Common` package, but it is noted in the package description, that this package should not be installed manually:
![Nuget aren't compatible with  net 5 0 version of Microsoft AspNetCore Mvc Razor RuntimeCompilation - Mozilla Firefox 2020-11-19 09 01 38](https://user-images.githubusercontent.com/6614183/99632439-e3ecf780-2a45-11eb-8b61-391c86e72c8a.png)

It should be installed by installing the all-in-one package `Microsoft.CodeAnalysis`. As this package also includes the package from the first conflict - `Microsoft.CodeAnalysis.CSharp.Workspaces`, installing just `Microsoft.CodeAnalysis` version 3.7.0 resolves both errors and the project should be able to build successfully. And on my side I see no version mismatch warnings in Visual Studio.

**Comment by dsteinweg** [comment]
Hi @Dimitar-Goshev,

Thank you for your response!  I can confirm that your workaround _does_ work for me:  installing `Microsoft.CodeAnalysis` version 3.8.0 allows me to install `Telerik.UI.for.AspNet.Core` version 2020.3.1118, while also having `Microsoft.VisualStudio.Web.CodeGeneration.Design` version 5.0.0 installed.

As I read your response, I wondered:  why is there no version of `Microsoft.CodeAnalysis` version 5.0.0 available? Microsoft released version 5.0.0 of most other NuGet packages, so why not these code analysis packages?  After searching, I found [this doc](https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019), which has the following text:  `Starting in .NET 5.0, code style analyzers are included with the .NET SDK and can be strictly enforced as build warnings or errors.` and also `Code quality analyzers are now included with the .NET 5 SDK and enabled by default.`  Does this mean the analyzers are no longer shipped as NuGet packages, since they come out of the box with the SDK?

I don't know how the Telerik project uses Microsoft's code analysis packages (if at all), but perhaps for .NET 5.0, the project needn't reference those NuGet packages if they're provided by the SDK.

**Comment by Dimitar-Goshev** [comment]
Hi @dsteinweg,
Thank you for confirming that the workaround works on your side and thank you for sharing your research. Indeed these packages should not be referenced by us as packages in .NET 5 projects. We will further research and address this in future releases.

**Comment by Dimitar-Goshev** [comment]
Hi @dsteinweg ,
After further researching the topic, this [article](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview#latest-updates) specifies that the analyzer that comes with .NET 5 SDK is not the whole Microsoft.CodeAnalysis package. We should still have a reference to Microsoft.CodeAnalysis NuGet package for our distribution.

**Comment by dsteinweg** [comment]
Thanks for continuing to investigate, but the article you linked only describes "locking" or "pinning" the version of the analyzers to use.  Installing a specific version of the NuGet package is one way, the other is to edit the project file and add `<AnalysisLevel />`.

In looking at [the GitHub repository for the analyzers](https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysisnetanalyzers), I see this mentioned again:
> You do not need to manually install this NuGet package to your project if you are using .NET5 SDK or later. These analyzers are enabled by default for projects targeting .NET5 or later.

**Comment by kinetiq** [comment]
Thanks for the workaround. 

Like many devs, we are using Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation, and 5.0.1 conflicts with the suggested workaround. I've found that leaving this dependency on 3.1.10 is functional for the purpose of runtime compilation, and avoids the conflict. Hopefully that helps some people.

I am wondering if there is an ETA for fixing this so I can keep my dependencies moving forward? Thanks.

**Comment by Dimitar-Goshev** [comment]
@kinetiq With R1 2021 in a month this conflict should be resolved.

**Comment by imranbaloch** [comment]
I am upgrading to .NET 8 n now and I am getting,

```
Error	NU1107	Version conflict detected for Microsoft.CodeAnalysis.CSharp.Workspaces. Install/reference Microsoft.CodeAnalysis.CSharp.Workspaces 4.8.0-3.final directly to project MyProject to resolve this issue.
 
 MyProject -> Microsoft.VisualStudio.Web.CodeGeneration.Design 8.0.0 -> Microsoft.VisualStudio.Web.CodeGenerators.Mvc 8.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration 8.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore 8.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration.Core 8.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration.Templating 8.0.0 -> Microsoft.VisualStudio.Web.CodeGeneration.Utils 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces (>= 4.8.0-3.final) 
 MyProject -> Telerik.UI.for.AspNet.Core 2022.1.119 -> Microsoft.CodeAnalysis 4.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces (= 4.0.0).	MyProject	C:\MyProject\MyProject.csproj	1	
```
