### ISSUE TITLE
The signature of the pdf file in dpl case is not visible 

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#6151]
Bug report
A specific PDF file (example can be found in ticket : 1493640) shows upside down in DPL case

Reproduction of the problem
Run the[ DPL processing demo](https://demos.telerik.com/aspnet-core/pdfviewer/dpl-processing) locally and replace the file with the one provided in the ticket

Current behavior
The signature is not shown 

Expected/desired behavior
The signature should be shown

Environment
Kendo UI version: 2020.3.1021

**Comment by aleksandarevangelatov** [comment]
The images in the provided sample file are encoded using FlateDecode filter. We do have a [note in the documentation section](https://docs.telerik.com/aspnet-core/html-helpers/pdf/pdfviewer/dpl-processing#dpl-processing) concerning the use of encoded images and that *SVG or encoded images in other formats might not render correctly.* 

Ensure that when using the PDFViewer and the DPL processing functionality, the document loaded contains images that are not encoded. This way they will be rendered as expected on the client.
