### ISSUE TITLE
Bottom offset is inconsistent in Timeline view

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#6160]
### Bug report

The bottom gap is thinner in every group when different number of events are added for each group.
However, switching to the TimelineEx view (that sets BottomRowOffset to 0), the problem is more obvious.

### Reproduction of the problem
https://dojo.telerik.com/IjIminuv
Observe the bottom offset for each group

### Current behavior
The offset is the same for each group becomes smaller for each group.

### Expected/desired behavior
The offset is the same for each group

### Environment

* **Kendo UI version:** 2020.3.1118

Feedback item: https://feedback.telerik.com/kendo-jquery-ui/1496550-bottom-gap-in-timeline-view

**Comment by kepeter** [comment]
It seems the 'Current' and 'Expected' are switched...

**Comment by Juveniel** [comment]
Fixed with: https://github.com/telerik/kendo/pull/12143
