### ISSUE TITLE
odata-v4 parameterMap 'destroy' params undefined error.

### ISSUE THREAD

**Issue by kkembel** [telerik/kendo-ui-core#6162]
### Bug report

When executing a 'destroy' operation using 'odata-v4' there is an error cannot read property $filter of undefined. This appears to be due to the fact that kendo.data.transports.odata.parameterMap will return 'params' uninitialized in the case of a 'destroy' operation.  With the result 'params' undefined, the kendo.data.transports["odata-v4"].parameterMap then tests results.$filter and throws an exception.  Need to test the results for undefined first or make the property check safer.

### Reproduction of the problem
Execute a 'destroy' operation using an 'odata-v4' data source that calls kendo.data.transports["odata-v4"].parameterMap.

### Expected/desired behavior
The results need to be tested for undefined params first, and if not undefined then check the properties. I'd suggest something like:
                // Existing code...
                var result = kendo.data.transports.odata.parameterMap(options, type, !0);
                // This is the bug fix, test if result is defined first
                if (!result) return result;
               // Continue...

### Environment

* **Kendo UI version:** 2020.3.1118

**Comment by dmanova** [comment]
Hi @kkembel .  The `parameterMap` function takes 2 parameters as described in our documentation here:
https://docs.telerik.com/kendo-ui/api/javascript/data/datasource/configuration/transport.parametermap

It is also written that the `parameterMap ` function is designed to transform the request payload, not to add new parameters to it.  
So adding additional parameters is more likely not handled as you expect.

If you need additional functionality, please write Feature Requests into [our feedback portal](https://www.telerik.com/support/feedback).

Or if you need some help on a particular use case, you could submit a support request to [support system](http://www.telerik.com/support) or check [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui).

**Comment by kkembel** [comment]
Sorry, just a misunderstanding, wasn't asking for additional parameters or different use case. Simply that the 'odata-v4' parameterMap function in the core library is throwing an error on a 'destroy' operation because the current codebase tries to access params.$filter when in a 'destroy' action params is undefined. I believe this is a new bug in 2020.3.1118

I wrote my own kendo.data.transports['odata-v4'].parameterMap for now using the code I posted above to avoid the params is undefined error.  Maybe this wasn't posted in the right place, but I figured this was a good place to share a bug found in the code.

**Comment by dmanova** [comment]
Hi @kkembel . Could you share a runnable sample where this issue is reproducible? I have tried to reproduce it, but in the sample, I have created the error is thrown when the third, additional parameter is used.

Here is the sample:
http://dojo.telerik.com/@dmanova/eHaReGUT
Feel free to edit it if it is easier for you to replicate the behavior.

**Comment by kkembel** [comment]
Hi - I can point you at the logic real quick since it's a simple sequence... when you create a data source of type 'odata-v4' it uses the parameterMap of:
kendo.data.transports['odata-v4'].parameterMap(options, type) 
which is defined on line 486 here: /src/kendo.data.odata.js

If you follow the logic for a 'destroy' type, you will see that your 3-parameter method is called internally line 487:
var result = kendo.data.transports.odata.parameterMap(options, type, true);

Follow that logic into kendo.data.transports.odata.parameterMap(options, type, useVersionFour) on line 385:
This method executes and returns params. But, in the case of 'destroy' you will see that params returned as undefined.

So now the undefined params is returned to 'result' back on line 487...
var result = kendo.data.transports.odata.parameterMap(options, type, true);

Only a few lines below that, on 493 is:
if (result.$filter) { ... }
which throws a: cannot read property $filter of undefined.

I hope this helps, it's only a few lines of code in sequence that seems to have a logic flaw on what params are returned in an odata 'destroy' and then tested.

**Comment by kkembel** [comment]
I modified your sample:
http://dojo.telerik.com/IjudOJuN 

You don't need to define your own parameterMap, it uses the one with the bug by default when you use 'odata-v4'. And if you set the autoSync to true then it'll trigger it when you click the 'delete' button on a row.  It's honestly a pretty simple and basic use case, doesn't require much code to trigger the error.

**Comment by kkembel** [comment]
Here's the datasource used:

                dataSource: {
                    batch: false,
                    type: "odata-v4",
                    transport: {
                        read:"https://demos.telerik.com/kendo-ui/service-v4/odata/Products",
			 									destroy: "https://demos.telerik.com/kendo-ui/service-v4/odata/Products"
                    },
                    schema: {
                      data: function (data) { return data.value; },
                      model: {
                            id: "ProductID",
                            fields: {
                                ProductID: { editable: false },
                                ProductName: { validation: { required: true } },
                                UnitPrice: { type: "number", validation: { required: true, min: 1 } },
                                Discontinued: { type: "boolean" },
                                UnitsInStock: { type: "number", validation: { min: 0, required: true } }
                            }
                        }
                    },
                    pageSize: 5,
                    autoSync: true
                }

**Comment by kkembel** [comment]
Not sure I'd agree with the SEV:low since this bug means that any delete operation on an odata v4 endpoint is broken.

**Comment by gdenchevprog** [comment]
Problem also reported in ticket 1502307

**Comment by Juveniel** [comment]
Fixed with https://github.com/telerik/kendo-ui-core/pull/6224
