### ISSUE TITLE
Spreadsheet does not calculate correctly SUM on merged cells

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6163]
### Bug report

Related To: https://github.com/telerik/kendo-ui-core/issues/5500

When there are merged cells and the SUM formula is used for the merged cells the result is wrong (it depends on the count of the merged cells)

### Reproduction of the problem
1. Open the [Dojo](https://dojo.telerik.com/@NeliKondova/uVifOKob)
2. Enter for example 5 in the merged cells (A1:B2)

### Current behavior
The result in the D1 cell is 20. ( value of cell * count of cells in merged range)

### Expected/desired behavior
The result should be 5. In the same scenario, the result in Excel will be 5.

### Environment

* **Kendo UI version:** 2020.3.1118
* **Browser:** [all  ]

**Comment by veselints** [comment]
Closing as duplicate of: #5500

**Comment by Dimitar-Goshev** [comment]
This issue was fixed in 2021.1.224 - [Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/OwAMifaf)
