### ISSUE TITLE
Editor - "undo" key combination (Ctrl + Z) needs to be pressed twice to work when keydown is handled

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6167]
### Bug report
Reproducible with inline and classic Editor.

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/@sspasova/uDIyuSAc) example.
1. Type in some text in the Editor.
2. Press Ctrl + A keys.
3. Press Backspace key.
4. Press Ctrl + Z keys.

### Current behavior
Undo does not work the first time Ctrl + Z keys are pressed. It works, if you press them a second time. 
If the **keydown** event handler is not attached, it works as expected.

### Expected/desired behavior
Undo works on the first press of Ctrl + Z keys. 

### Environment

* **Kendo UI version:** 2023.3.1114
* **jQuery version:** 3.4.1
* **Browser:** [all]

**Comment by Iankodj** [comment]
Reported in ticket 1511801.

**Comment by Iankodj** [comment]
Reported in ticket 1579812.
