### ISSUE TITLE
Keyboard navigating Virtual List to not yet loaded items leaves different focused and selected items

### ISSUE THREAD

**Issue by bundyo** [telerik/kendo-ui-core#617]
Steps to reproduce (in a Virtualization demo):
1. Open drop down.
2. Press down arrow key and keep pressed until loading... items fill the list and new ones are loaded.
3. Release the key.

Result: the selected and focused states are on different items - the focused state is on the correct item. KB navigating up/down produces 2 selected items. Might be a bit tricky to reproduce.

**Comment by ggkrustev** [comment]
Fixed with #700 and 3f7c17f45712861b0dfdf2f07bc56eb3239f8ce8
