### ISSUE TITLE
Unexpected ComboBox dropdown opening on Capslock button press

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#6171]
### Bug report

Pressing the Capslock button when the ComboBox is focused triggers the opening of its dropdown list. The dropdown list opens one time when the Capslock is pressed. 

* The reported behavior was reproduced on Google Chrome and Firefox.  On IE, the issue is not replicable.

### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/ERuNIVOy) and run it
1. Select the first ComboBox with a mouse click or the "Tab" button
1. Press the Capslock button.

### Current behavior
The dropdown list of the ComboBox opens when the Capslock is pressed

### Expected/desired behavior
The dropdown list of the ComboBox should not open when the Campslock button is pressed

### Environment

* **Kendo UI version:** 2020.3.1118
* **jQuery version:** x.y
* **Browser:** [Chrome 87.0.4280.88 | Firefox 78.5.0esr ]

**Comment by mparvanov** [comment]
1. Open the page
2. Press "Tab" button
3. Press the Capslock button.
The dropdown list of the ComboBox opens when the Capslock is pressed
