### ISSUE TITLE
Paste in a list with a block element splits the list instead of inserting in the list item

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#6173]
### Bug report

Executing a paste method or insertHtml command with a block element in a list item selected splits the list.

### Reproduction of the problem
https://dojo.telerik.com/oWIkiYEh/2

1. Create a bullet list
2. Use the custom tool to insert the HTML a list item

### Current behavior
The list item is removed and the list is split in two lists. 

### Expected/desired behavior
The block element to be inserted inside the list item

### Environment

* **Kendo UI version:** 2020.3.1118

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1544803
