### ISSUE TITLE
PDFViewer does not open system dialog for printing in Chrome and Edge

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6176]
### Bug report

When trying to print a file from the PDF Viewer, if the user wants to use the system print dialog, the printing dialog gets closed, but the system dialog does not appear. 

### Reproduction of the problem
1. Open the [Pdf Viewer Demo](https://demos.telerik.com/kendo-ui/pdfviewer/index)
2. Click print
3. Then scroll and select "Print using system dialog"

### Current behavior
The printing dialog gets closed and the system dialog does not appear. ([screencast](https://www.screencast.com/t/OX8a9vSMdW))

### Expected/desired behavior
The system printing dialog should appear

### Environment

* **Kendo UI version:** 2020.3.1118
* **Browser:** [Chrome | Edge ] 

.

**Comment by veselints** [comment]
I could not reproduce the issue with Chromium Edge.

**Comment by meetshujah** [comment]
This issue still exist of ipad ios 13 so on please fixed it ASAP we have also reported on telerik portal
