### ISSUE TITLE
The toolbar of the Inline Editor hides on a click over it or a click on a disabled button

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#6185]
### Bug report
The toolbar of the inline Editor hides when the user click on a disabled button inside it or on the toolbar itself

* This is a regression introduced with R3 2020 SP1 - 2020.3.1021

### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/oCaZodaY)
1. Open the toolbar and click on the disabled "Unlink" button or on the right part of the toolbar where there are no buttons

### Current behavior
The toolbar hides after the user click on it.
![090873e5-5386-409c-a2fa-4fd501bf53e7_editor-toolbar-issue](https://user-images.githubusercontent.com/41293735/101872490-00380c00-3b8e-11eb-9896-b3406b5ba8df.gif)

### Expected/desired behavior
The toolbar should stay visible after the user click it 

### Environment

* **Kendo UI version:** 2020.3.1118
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by joneff** [comment]
Just to clarify: clicking on disabled button has no effect: the disabled buttons are "transparent" to clicks i.e. you click trough them. meaning that it's the same as if clicking on the toolbar.

In other words the issue is not that clicking on disabled buttons closes the toolbar. it's that clicking on the toolbar closes the toolbar.

**Comment by mparvanov** [comment]
1. Mark a word inside editor content
2. Apply Bold by using the mouse
3. Press Tab 4 times -> Underline tool is focused
4. Click inside editor content

Expected: The toolbar is displayed 
Actual: The toolbar is not displayed any more on clicking inside editor content
