### ISSUE TITLE
Undesired border line in first entry of a Context Menu

### ISSUE THREAD

**Issue by JoseGoncalves** [telerik/kendo-ui-core#619]
I've noticed that a line has appeared below the first entry of a Context Menu.
This can be seen in the [Menu / AngularJS - ContextMenu Demo](http://demos.telerik.com/kendo-ui/menu/context-menu-angular).
Is this intended or is it a bug?

**Comment by KirilNN** [comment]
Hi @JoseGoncalves,

The `k-first` class is applied on the first item of the popup by mistake. It will be fixed with an upcoming build.

Thanks for reporting it.

**Comment by dimodi** [comment]
Fixed

**Comment by JoseGoncalves** [comment]
Which commit fixed the issue?

**Comment by dimodi** [comment]
https://github.com/telerik/kendo-ui-core/commit/30380a79f2e8f2ab4d1d41ff1188094452f0c551
