### ISSUE TITLE
ComponentType Modern by default sets to Today

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#6191]
### Bug report

If the user opens the Kendo UI DateTimePicker with a componentType of "modern", then selects set without any modifications, it will select today instead of what is in the input.

### Reproduction of the problem

1. Go to [this Progress Kendo UI Dojo.](https://dojo.telerik.com/@PMcDonou/anAfIboc)
2. Open the DateTimePicker and select set.

### Expected/desired behavior
The value in the input should remain set as the Kendo UI DateTimePicker's value.

### Environment

* **Kendo UI version:** 2020.3.1118
* **Browser:** All

**Comment by dmanova** [comment]
I reproduce the issue only when combining 24-hour time format and time between 12:00 AM and 12:59 AM, then it is set wrong to 1 AM. Seems related to https://github.com/telerik/kendo-ui-core/issues/5865
Are there any other use cases that set the wrong date or time?
