### ISSUE TITLE
Open event is not fired in "modern" componentType

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#6192]
### Bug report

The Open Event will not fire with the "modern" componentType.  The Popup's open event does work, but not the Kendo UI DateTimePicker's.

### Reproduction of the problem

1.  Go to [this Progress Kendo UI Dojo.](https://dojo.telerik.com/@PMcDonou/ICAJImeQ)
1.  Open the DateTimePicker.  

### Expected/desired behavior
The Open event should fire. 

### Environment

* **Kendo UI version:** 2020.3.1118
* **Browser:** all

**Comment by Alex-Bubblemaster** [comment]
Also required in ticket 1501802, raising priority
