### ISSUE TITLE
Toolbar appearance in Spreadsheet is not correct on smaller screen sizes

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6194]
### Bug report

On screens with smaller sizes not all tools in the Spreadsheet Toolbar are visible. The tools overlap the overflow button and thus cannot be selected.

### Reproduction of the problem

1. Run the following [demo](https://demos.telerik.com/kendo-ui/spreadsheet/index) and reduce the window width
### Current behavior
On wider screens all tools are visible:
![image](https://user-images.githubusercontent.com/46348689/102359422-6cb17180-3fb9-11eb-9252-0fa4fafaab95.png)
On narrower screens only some tools are visible and the overflow button is overlapped:
![image](https://user-images.githubusercontent.com/46348689/102359556-9cf91000-3fb9-11eb-86e6-57240e5a35a2.png)
or completely hidden:
![image](https://user-images.githubusercontent.com/46348689/102359623-b26e3a00-3fb9-11eb-8d11-70465933d987.png)

### Expected/desired behavior
The overflow button should be visible so all Spreadsheet tools are accessible.

### Environment

* **Kendo UI version:** 2020.3.118
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
This issue was addressed with https://github.com/telerik/kendo-ui-core/issues/6860
