### ISSUE TITLE
Spreadsheet column resize handles overlap

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6198]
### Reproduction of the problem
Reproducible in the demos. The attached video demonstrates the issue. 
[Recording49.zip](https://github.com/telerik/kendo-ui-core/files/5710847/Recording49.zip)

1. Reduce to minimum the width of several adjacent columns
2. Increase the width of one of them

### Current behavior
As shown in the video, the F column completely disappears. The column letter remains visible within the next column (G). F column's resize handle remains hidden, and it cannot be made visible.

### Expected/desired behavior
There should be a minimum column width that should be respected on resizing. Its value should always allow the column to be resized. No column overlapping should occur. 

### Environment

* **Kendo UI version:** 2024.1.130
* **jQuery version:** x.y
* **Browser:** [Chrome 87 ]

**Comment by martintabakov** [comment]
The behaviour from the recording cannot be reproduced on the online demos - https://demos.telerik.com/kendo-ui/spreadsheet/index. Closing the item until further information is provided.
