### ISSUE TITLE
MultiSelect filter is cleared after selecting an item and clicking in the input area

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6218]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/OsOyeSOW) example.
1. Focus the MultiSelect and type in "c". The data is filtered and "Canada" is displayed in the list. 
2. Select "Canada".
3. Click in the MultiSelect's input area. 

### Current behavior
The filter is cleared and all the items in the dataSource are listed, even though "c" remains in the input area. 
If step 2 is omitted, the filter is not cleared.

### Expected/desired behavior
The filter should not be cleared. After step 3 the MultiSelect should still show only "Canada" in the list of items.

### Environment

* **Kendo UI version:** 2020.3.1118
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by veselints** [comment]
This is a good candidate for a functional test. I was not able to define a proper unit test for it.
