### ISSUE TITLE
kendo grid can't display data if has 'data' property

### ISSUE THREAD

**Issue by lancelothuxi** [telerik/kendo-ui-core#622]
Hello, I recently found a strange issue when I use kendo grid with angular,  if the returned json data
has property of 'data' ,then the row data can not shown , like {
  "datas":[{
    "companyId":"X",
    "data":{}----------------------------this data attribute will cause issue
  },
    {
      "companyId":"Y",
      "data":{}
    }

  ],
  "total":1
}

**Comment by underlog** [comment]
Hi,

Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (Professional, UI for MVC, PHP, JSP) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI!
