### ISSUE TITLE
search textbox can't be localized in scheduler

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-ui-core#6228]
### Bug report

search textbox can't be localized in scheduler

### Reproduction of the problem
https://dojo.telerik.com/@zdravkov/OHOfaHAb

### Current behavior
search textbox placeholder and title are not localized

### Expected/desired behavior
search textbox placeholder and title should be localized

We should also improve the localization settings on the server side as suggested in ticket: 1501795
### Environment

* **Kendo UI version: 2020.3.1118

**Comment by mparvanov** [comment]
The option need to be applied also for MVC wrappers

**Comment by mparvanov** [comment]
"null" is displayed for search message in MVC5: https://www.screencast.com/t/2rl97hTaAUyJ
