### ISSUE TITLE
Diagram popup toolbar needs class k-diagram-toolbar

### ISSUE THREAD

**Issue by GeorgeGindev** [telerik/kendo-ui-core#6229]
### Reproduction of the problem
The Diagram component is missing class for the toolbar inside the popup, and it cannot be targeted to be styled.
https://supportheroes.telerik.com/ticket/1501571

### Expected/desired behavior
The toolbar in the Diagram component should have class k-diagram-toolbar.

**Comment by ag-petrov** [comment]
This is not a bug, the rendering is ok. Moreover we have updatde the widgets to use the toolbar widget which is also updated. Closing this one
