### ISSUE TITLE
Filterable option does not work correctly in the grid view of the FileManager

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6230]
### Bug report

When the views.grid option of the FileManager is used and the filterable option is enabled, the filter menu is empty. Also the 'Date Created' column is empy.

### Reproduction of the problem
1. Open the [Dojo example](https://dojo.telerik.com/@NeliKondova/iRItezIq)
2. Go to the 'Grid View'

### Current behavior
Currenlty, the filter menu of the Grid in the 'Grid View' is empty. The 'Date Created' column does not show  the dates. 

![file-manager-filterable-bug](https://user-images.githubusercontent.com/14364791/104442617-fe52d580-559d-11eb-9a63-fd47369e977a.jpg)

### Expected/desired behavior
The filter menu in the 'Grid View' and the 'Date Created' column of the FileManager should be not be empty. 

![file-manager-expected](https://user-images.githubusercontent.com/14364791/104443198-c7c98a80-559e-11eb-887e-b795f1c39318.jpg)

#### Workaround
As a temporary workaround, the fields of the model could be defined with lowercase. [Here is a Dojo example](https://dojo.telerik.com/@NeliKondova/AsutIPiq) where the workaround is applied.

### Environment

* **Kendo UI version:** 2020.3.1118
* **Browser:** [all ]

**Comment by Iankodj** [comment]
The dojo provided will not show value in the Date Created column as the created field is missing from the data. Here you are a corrected dojo example: https://dojo.telerik.com/OtOrIwOw/2.
