### ISSUE TITLE
Export Multiple Grids to Excel - Not exporting latest grid data

### ISSUE THREAD

**Issue by gopinathbecse** [telerik/kendo-ui-core#6239]
### Bug report

https://docs.telerik.com/kendo-ui/knowledge-base/multiple-grid-export
When exporting multiple grids to excel using promises as mentioned in sample code, the generated excel sheet has rows only from the data while grid initialized. The latest records from grid are not in the exported workbook. Only old data there.

### Reproduction of the problem
_(bug report only)_
Try to use dynamic records for grid results while refresh (we have a search filter/form which refresh grid data based on search text entering)

### Expected/desired behavior
Exported excel sheet should have updated grid results/data.

### Environment

* **Kendo UI version:** 202x.r.ddd
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ag-petrov** [comment]
This bug is logged for a KB and not product related. In order to verify it as such we need a runnable sample that clearly indicates a problem in the internal working mechanisms.
