### ISSUE TITLE
Long text in grid cell overlaps when exported as PDF in Safari

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-ui-core#6240]
### Bug report

In Safari v13/v14 when a few line content of grid cell is exported to PDF the generated text is not wrapped, but overlaps.

Reported in ticket: 1503041

### Reproduction of the problem
https://dojo.telerik.com/exOdozEj

### Current behavior
[ExportOverlap.pdf](https://github.com/telerik/kendo-ui-core/files/5844351/ExportOverlap.pdf)

### Expected/desired behavior
[ExportFine.pdf](https://github.com/telerik/kendo-ui-core/files/5844353/ExportFine.pdf)

### Environment

* **Kendo UI version:** 2021.1.119
* **jQuery version:** 1.12.4
* **Browser:** [Safari 13 | Safari 14 ]

**Comment by gsuarez-setworks** [comment]
I have experience this issue using kendo react as well, and not limited to grids, but also in a pre tag with line breaks.

**Comment by louisptremblay** [comment]
The bug is caused by this line in:
@progress/kendo-drawing/dist/es/html/core.js

```
if (microsoft || browser.chrome) {
```

Basically Safari skips a block of code that it should be using. Removing the if fixes the problem

**Comment by akash880** [comment]
why is this open for so long

**Comment by cherukuri-bindu-kalpana** [comment]
I am experiencing the same issue by using kendo-react-pdf in MAC safari. Is there solution to fix this?

**Comment by mariagarciaflores** [comment]
I have the same issue, is there a workaround? or something?

**Comment by louisptremblay** [comment]
Since it doesn't seem like they will merge this, you can use 
https://www.npmjs.com/package/patch-package
to modify the code manually. 

yarn install patch-package
Edit the file node_modules/@progress/kendo-drawing/dist/es/html/core.js to remove `if (microsoft || browser.chrome)` condition. 
yarn patch-package @progress/kendo-drawing

**Comment by Iankodj** [comment]
Not reproducible with latest version (2024.1.130) https://dojo.telerik.com/exOdozEj/12
