### ISSUE TITLE
Error when using sticky/frozen columns

### ISSUE THREAD

**Issue by GeorgeGindev** [telerik/kendo-ui-core#6242]
### Reproduction of the problem
https://supportheroes.telerik.com/ticket/1502118

### Current behavior
I  have applied Frozen and Sticky columns following the documentation and the example from the demo, and now I have the following error:

![image](https://user-images.githubusercontent.com/72436523/105339316-3634cb00-5be5-11eb-988e-090132cb1bdb.png)

If I remove Frozen and Sticky options, then the error is gone.  This error also affects the functionality of my toggle buttons.

### Expected/desired behavior
No error when using sticky/frozen column.

**Comment by PreslavKozovski** [comment]
not replicable.
