### ISSUE TITLE
The text of the columns is overlapping when scrolling Grid with sticky columns

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6243]
### Bug report

When there are sticky columns in Grid and the horizontal scrollbar is visible, the text of the columns is overlapping while scrolling.

### Reproduction of the problem
1. Open the [Dojo ](https://runner.telerik.io/fullscreen/@NeliKondova/uVEdeVec)in fullscreen
2. Resize the browser in order for the horizontal scrollbar to be visible and scroll

### Current behavior
The text of the columns is overlapping

### Expected/desired behavior
The text of the columns in Grid should not overlap whiles scrolling

### Workaround
  
`  window.addEventListener('resize', function(){
  		$("#grid").data().kendoGrid._updateStickyColumns(false);  
  });`

[Dojo](http://dojo.telerik.com/@NeliKondova/OCaxuWIc)

### Environment

* **Kendo UI version:** 2021.1.119
* **Browser:** [all ]

**Comment by dmanova** [comment]
Sticky columns will be considered in the [kendo.resize](https://docs.telerik.com/kendo-ui/api/javascript/kendo/methods/resize) method.
Then if the width of the Grid changes through JavaScript or resizing the page after the Grid is created, will need to call the resize method to recalculate the sticky styles, e.g. `$(window).on("resize", function() { kendo.resize($("#grid")); });`
