### ISSUE TITLE
Gantt - parent task's percentComplete is not updated when the child's percentComplete is changed in the treelist

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6245]
### Bug report
A regression introduced in R3 2020. The issue is reproducible when editing a child task in the treelist. It works as expected when the percentComplete value is set in the timeline. 

### Reproduction of the problem
Reproducible in the [demo](https://demos.telerik.com/kendo-ui/gantt/index).
1. In the treelist, modify the % Complete value of a child task (e.g., Design UI)

### Current behavior
The % Complete value of the parent task is not updated.

### Expected/desired behavior
The % Complete value of the parent task is updated. 

### Environment

* **Kendo UI version:** 2021.1.119
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by IvanDanchev** [comment]
In addition to the percentComplete value, the Start and End date values of the parent task are not updated, when the child task's Start or End date are modified.

**Comment by veselints** [comment]
One more bug: when altering Parent task Start, the Start and End of its children are not updated accordingly.
