### ISSUE TITLE
Using a DropDown editor inside an incell editor template Grid with autoSync DataSource of a PopUp editor of the main Grid causes the next cell edit to automatically close the cell

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-ui-core#6248]
### Bug report

Using a DropDown editor inside an incell editor template Grid with autoSync DataSource of a PopUp editor of the main Grid causes the next cell edit to automatically close the cell.

reported in 1503597

### Reproduction of the problem

1. Open https://dojo.telerik.com/IqUmOSev
1. Click `Add new record`.
1. In the Popup, click `Add new record`.
1. Select a value from the DropDown
1. Click on the `Product Name` cell.

Note; If the user clicks anywhere outside of the second Grid - the issue is not replicated.

### Current behavior

The cell closes the first time the user clicks on it.

### Expected/desired behavior

The cell is not closed.

### Environment

* **Kendo UI version:** 2021.1.119
* **Browser:** [all]

**Comment by PreslavKozovski** [comment]
Possible workaround:

Manually editing the `cell` of the same row during the `save` event of the Grid.

```
              save: function(e) {
                var grid = e.sender;
                var uid = e.model.uid;
                var nextCellId = grid.cellIndex(e.container) + 1;
                
                setTimeout(function() {
                	grid.editCell($("[data-uid='" + uid + "'] td:eq(" + nextCellId + ")"));
                }, 100);
              }
```

For a runnable example - https://dojo.telerik.com/ULUQOTiH

**Comment by Iankodj** [comment]
Fixed in [https://github.com/telerik/kendo/tree/fix-window-dropdowns-open](https://github.com/telerik/kendo/tree/fix-window-dropdowns-open)
