### ISSUE TITLE
Grid server grouping and endless scrolling mismatches groups in muligrouping

### ISSUE THREAD

**Issue by Anton-Mironovv** [telerik/kendo-ui-core#6256]
### Reproduction of the problem
Set a Kendo UI Grid with server grouping and endless scrolling. Make multilevel grouping.

## Code
```
@(Html.Kendo().Grid<Kendo.Mvc.Examples.Models.OrderViewModel>()
    .Name("grid")
    .Columns(columns => {
        columns.Bound(p => p.OrderID).Filterable(false).Width(100);
        columns.Bound(p => p.Freight).Width(100);
        columns.Bound(p => p.OrderDate).Format("{0:MM/dd/yyyy}").Width(140);
        columns.Bound(p => p.ShipName); columns.Bound(p => p.ShipCity).Width(150);
    })
    .Pageable()
    .Sortable()
    .Scrollable(s => s.Endless(true))
    .Groupable()
    .Filterable()
    .Height(500)
    .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(20)
        .Group(g => {
            g.Add(t => t.ShipCountry);
            g.Add(t => t.ShipCity);
        })
        .Read(read => read.Action("Orders_Read", "Grid"))
    )
)
```

### Current behavior
Groups are duplicating and mismatched.

### Expected/desired behavior
Groups should be rendered as unique.

### Environment

* **Kendo UI version:** 2021.1.119
* **Browser:** [all |

**Comment by ag-petrov** [comment]
@dmanova please test with single level of grouping as well

**Comment by dmanova** [comment]
_Notes from internal testing:_
Seems to work up to two levels, but when adding third level grouping (e.g. g.Add(t => t.ShipName);) the groups are not correct.

**Comment by ag-petrov** [comment]
Note:  the above linked group paging issue is not related to the current bug
