### ISSUE TITLE
kendo-dialog default closed

### ISSUE THREAD

**Issue by mesteves** [telerik/kendo-ui-core#6265]
```
<kendo-dialog name="dialog" title="Software Update" width="400" modal="false" on-close="onClose" on-open="onOpen" on-init-open="onInit">

(omited)

</kendo-dialog>
```

On the documentation does not explain how to set the dialog to a default closed state when page loads.

I've tried with both tag helper and razor.

How can it be achieved ?

Best regards,
Manuel

**Comment by Dimitar-Goshev** [comment]
@mesteves To get the Dialog initially not shown, use its [visible](https://docs.telerik.com/aspnet-core/api/Kendo.Mvc.UI.Fluent/DialogBuilder#visiblesystemboolean) property.
As a side note, please open support tickets or forum threads for configuration questions. Use this repository for reporting issues or feature requests only.

**Comment by mesteves** [comment]
Thank you @Dimitar-Goshev for the feedback and sorry for asking on the wrong place.

Was good however I got my question answered :) 

Best regards,
Manuel
