### ISSUE TITLE
AngularJS Date-Range-Picker k-ng-model doesn't work with model defined property.

### ISSUE THREAD

**Issue by bloodlanser** [telerik/kendo-ui-core#6268]
### Reproduction of the problem
Navigate to the following dojo: https://dojo.telerik.com/elayoMOk and Run it. 

### Current behavior
Start/End value binding doesn't work and doesn't show any value in the date inputs.

### Expected/desired behavior
Value binding should work with model prefixes.

### Environment

* **Kendo UI version:** 2021.1.127
* **jQuery version:** latest
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
