### ISSUE TITLE
Column/row lines and values disappear and re-appear on scrolling the Spreadsheet

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6272]
### Reproduction of the problem
[Dojo](https://dojo.telerik.com/ECEMoXac/4) example.
1. Hide the second row.
2. Slowly scroll the Spreadsheet horizontally (left and right).

[Scenario 2](https://dojo.telerik.com/@martin.tabakov@progress.com/iKaZIxIH/2): 
1. Hide the second and the third row.
2. Update the cell L4. 
3. Notice how several empty cells appear on the 4th row. A video of the behavior is available [on this link](http://somup.com/crnhQNoWYJ).

### Current behavior
Column lines disappear and row lines appear (columns G, M, N, O). In Chrome values disappear as well, observe the value in column F. The configuration options required for reproducing the behavior are **mergedCells** and **frozenRows**.

### Expected/desired behavior
No changes to the column/row lines and no disappearing values on scrolling.

### Environment

* **Kendo UI version:** 2021.1.119
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by mishoo** [comment]
Export to PDF is broken too, for example in the first scenario — if you try "export to PDF" after hiding the first row it'll throw an exception (a `NaN` comes up from somewhere).  I suspect it's related, since the same algorithm is used for both screen and PDF layout.

**Comment by mishoo** [comment]
Fixed on branch `spreadsheet-rendering-glitches`
