### ISSUE TITLE
AngularJS ListView Grouping doesn't work.

### ISSUE THREAD

**Issue by bloodlanser** [telerik/kendo-ui-core#6280]
### Reproduction of the problem
Navigate to https://dojo.telerik.com/aQuRAFix and Run It. 

### Current behavior
AngularJS k-template doesn't work when ListView DataSource has Group(s).

### Expected/desired behavior
ListView should show the applicable group value / items when DataSource has Group(s).

### Environment

* **Kendo UI version:** 2021.1.127
* **jQuery version:** all
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
