### ISSUE TITLE
For DatePicker with component type:"modern" the "Today" text link is not disabled if today's date is disabled

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6284]
### Bug report
For DatePicker with component type:"modern" the "Today" text link is not disabled if today's date is disabled

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/AdIkAhuT)
1. Open the DatePicker

### Current behavior
Note the "Today" link is not disabled, while the current date is disabled
![image](https://user-images.githubusercontent.com/46348689/107384176-61328080-6afa-11eb-9673-05eb69789d99.png)

### Expected/desired behavior
 The "Today" link should be disabled, similar to the classic view

### Environment

* **Kendo UI version:** 2021.1.119
* **Browser:** [all]

**Comment by dmanova** [comment]
_Notes from internal testing:_
The "Today" links with buttons in LESS themes go on 3 lines:
![image](https://user-images.githubusercontent.com/52446546/108327786-7a12f400-71d4-11eb-939a-bb94e42e2fba.png)
