### ISSUE TITLE
data-menu is returning a string instead of a boolean

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#6296]
### Bug report

When a Kendo UI Grid has been initialized via a table, If the user sets the th element with [data-menu="false"](https://docs.telerik.com/kendo-ui/controls/data-management/grid/overview#using-an-html-table), the menu attribute is read as a string instead of a boolean.  

### Reproduction of the problem

1.  Go to [this Progress Kendo UI Dojo.](https://dojo.telerik.com/@PMcDonou/IJOrezUx)
2.  The make and model have data-menu="false".  But the column menu contains both columns.

### Expected/desired behavior
The data-menu configuration should be parsed to a boolean.

### Environment

* **Kendo UI version:** 2021.1.119

**Comment by PMcDonough11** [comment]
Workaround can be found in the [Kendo UI Feedback Portal Bug Report.](https://feedback.telerik.com/kendo-jquery-ui/1507772-data-menu-is-returning-a-string-instead-of-a-boolean)

**Comment by fabidev1993** [comment]
I had this issue on our project and it tooks me a lot of time to write code to reach this desired behavior , please fix this bug
