### ISSUE TITLE
ComboBox sends two requests to the "read" end point when its input is cleared

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6299]
### Bug report
Regression introduced in R1 2020 SP1. Related to #5400

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/avIREdaR/2) example.
1. Open the browser's dev tools Network tab.
2. Run the example.
3. Type in "s" in the ComboBox. A request is sent and the popup displays matching items (expected).
4. Press Backspace key to clear the ComboBox input.

### Current behavior
2 requests are sent to the "read" end point.

### Expected/desired behavior
1 request is sent to the "read" end point. Note that if the input is cleared with the "clear" button, it works as expected and only 1 request is sent. 

### Environment

* **Kendo UI version:** 2021.1.119
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Iankodj** [comment]
PR: https://github.com/telerik/kendo/pull/12266
