### ISSUE TITLE
Document the precise CSS files for a hosting given theme

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#630]
I'm trying to include the mimimum CSS files required for the Material Design theme. At http://docs.telerik.com/kendo-ui/install/onsite, the instructions for doing so only mention

    <link href="styles/kendo.default.min.css" rel="stylesheet" />
But in the download ZIP, there are at least three non-mobile Material CSS files:

kendo.common-material.core.min.css
kendo.common-material.min.css
kendo.material.min.css
What are the differences among these files, and which need to be included for a desktop configuration?

I assume kendo.common-material.core.min.css includes only the Kendo UI core components plus the common CSS, kendo.common-material.min.css adds the Professional widgets, and kendo.material.min.css is only the Material theme, without the common CSS. This is an educated guess, but it might be wrong - kendo.common-material.min.css is 20kb larger than kendo.common.min.css + kendo.material.min.css (so what's extra in there?).

Documenting the file naming conventions would be great.

**Comment by yordanov** [comment]
Themes and theme files are documented at http://docs.telerik.com/kendo-ui/web/appearance-styling.
