### ISSUE TITLE
Events longer than 24h cannot be dragged over a specific timeslot in Scheduler timeline view

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6304]
### Bug report
Regression introduced in R3 2020 SP2. Possibly related to #6034

### Reproduction of the problem
[Dojo](https://dojo.telerik.com/EPIkagan) example. 
1. Attempt to drag first event to a slot before the one it starts in.

### Current behavior
The event cannot be dragged/dropped over the desired slot. It is automatically placed over the first slot of the day it starts in.

### Expected/desired behavior
The event can be dropped over the desired time slot. 

### Environment

* **Kendo UI version:** 2021.1.224
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by mparvanov** [comment]
https://github.com/telerik/kendo-ui-core/issues/6034 becomes reproducible again after the fix.
1. Open scheduler/timeline demo
2. Make the evaluations event an All day event
3. Drag it to other resource
4.  Open the edit form
Actual: The allday checkbox is NOT checked
