### ISSUE TITLE
kendo.guid() is generating Guids with illegal characters

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#6305]
### Reproduction of the problem
```
for (var i = 0; i < 100; i++) {
    console.log(kendo.guid());
}
```
### Current behavior
Letters outside of Hexadecimal scope are generated e.g.:
**p**d1b6243-0d58-48d9-a6dc-4636f3a4a8ab

### Expected/desired behavior
Hexadecimal characters only are generated
### Environment

* **Kendo UI version:** 2021.1.224

**Comment by dmanova** [comment]
Duplicate of #6261
