### ISSUE TITLE
Grid - GroupPaging with local data in AngularJS 

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#6306]
### Bug report

When applying GroupPaging with local data using a Kendo UI Grid with AngularJS, the error message **Uncaught TypeError: Cannot read property 'hasSubgroups' of undefined**' appears upon expanding a parent row.

### Reproduction of the problem

1.  Go to[ this Progress Kendo UI Dojo.](https://dojo.telerik.com/@PMcDonou/elESeqiy)
2.  Attempt to expand the row.

### Current behavior
Currently, the UID for the group is not matching the group row's UID, and the error message appears.

### Environment

* **Kendo UI version:** 2021.1.224

**Comment by dmanova** [comment]
Last working Kendo UI version: 2020.1.406

**Comment by NikoPenev21** [comment]
Also reported in ticket #1565159

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.
