### ISSUE TITLE
Missing toString method passing an object as kendo.Observable

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6308]
### Bug report

If an object has an overridden toString method and is passed as a kendo.Observable the toString method of the object is not passed. This is a regression introduced with v2020.3.1023.

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/OJEceHan)
2. The overriden toString method is not available

### Expected/desired behavior
The custom toString method should be passed, as in v2020.3.915: [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/ayUFUsix)

### Environment

* **Kendo UI version:** 2021.1.224
* **Browser:** [all]

**Comment by martintabakov** [comment]
The issue persist when using prototype to override the toString method. Refer to this example - https://dojo.telerik.com/EpemoliS

**Comment by veselints** [comment]
Related to: https://github.com/telerik/kendo-ui-core/issues/5973

**Comment by veselints** [comment]
A similar issue is also present when assigning a jQuery object to a field in the observable. Here is a Dojo demonstrating the result:
https://dojo.telerik.com/eyeHosEQ/3

**Comment by Iankodj** [comment]
Dojo to test https://github.com/telerik/kendo-ui-core/issues/5973: https://dojo.telerik.com/@iankodj/EBIguToM
