### ISSUE TITLE
When resizing a Gantt summary task the scroll position is not set correctly

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6315]
### Bug report
When resizing a Gantt summary task by increasing the duration of the task and then decreasing the duration of the task the scroll position is not set correctly.

### Reproduction of the problem
1. Run the [Gantt overview demo](https://demos.telerik.com/kendo-ui/gantt/index?autoRun=true&theme=default-v2)
2. Resize the top summary task to 7/12 or 7/13, for example
3. Resize back to 7/10 and notice the scroll position. 
[Screencast of the behavior](https://www.screencast.com/t/bA23szxmqER)

### Current behavior
The scroll position does not remain at the end of the tasks

### Expected/desired behavior
The scroll position should remain at the end of the task

### Environment

* **Kendo UI version:** 2021.1.224
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Not reproducible with 2023.3.1114
