### ISSUE TITLE
Grid throws a js exception on programmatically selecting a row when "selectable" is disabled

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6316]
### Bug report
A js exception is thrown on selecting a row with the **select** method, when the Grid's **scrollable** option is disabled. The exception started appearing since R3 2020 SP1.

### Reproduction of the problem
1. Go to: [https://dojo.telerik.com/adExIfAp/6](https://dojo.telerik.com/adExIfAp/6)
2. Run the example

### Current behavior
A js exception is thrown on calling the **select** method.

### Expected/desired behavior
No exception is thrown.

### Environment

* **Kendo UI version:** 2021.1.224
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by ag-petrov** [comment]
This is not a bug, the select method should not be called when the grid is not selectable. We have other functionality tied to the selection such as persist selection and it is not clear how the grid should behave in such mixed setup. If one wants to select the row without enabling selection he can do so by adding the **.k-state-selected** class as shown in [this ](https://dojo.telerik.com/adExIfAp/10)dojo.
