### ISSUE TITLE
The Editor's aria-label attribute is not read by screen readers

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6317]
Research possible approaches for setting the aria-label of the Editor in a way that makes it possible for the screen readers to read it.
[https://dojo.telerik.com/EKOqayuH/3](
https://dojo.telerik.com/EKOqayuH/3)

**Comment by veselints** [comment]
rising priority due to: https://github.com/telerik/kendo-ui-core/issues/6776
