### ISSUE TITLE
Pasting a table from Word into the Editor throws a js exception (IE11)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6322]
### Bug report
Regression introduced in R1 2021 SP1. Related to: #6169

### Reproduction of the problem
Reproducible in the demos in IE11.
1. Create a table in a Word document.
2. Copy the table and paste it in the Editor.

### Current behavior
A js exception is thrown.

### Expected/desired behavior
No exceptions on pasting the table.

### Environment

* **Kendo UI version:** 2021.1.224
* **jQuery version:** x.y
* **Browser:** [IE11 ]

**Comment by veselints** [comment]
PR here: https://github.com/telerik/kendo/pull/12305
