### ISSUE TITLE
Not allowed ARIA attribute "aria-expanded" set to Splitter's separator with role="separator"

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#6323]
### Bug report
Splitter's separator with [role="separator"](https://www.w3.org/TR/wai-aria/#separator) has not allowed ARIA attribute "aria-expanded"

### Reproduction of the problem
1. Run [Splitter demo](https://demos.telerik.com/kendo-ui/splitter/index) and inspect a separator element

### Current behavior
`<div tabindex="0" class="k-splitbar k-state-default k-splitbar-horizontal k-splitbar-draggable-horizontal" data-marker="i3db7968" role="separator" aria-expanded="true" style="height: 169px; left: 414px;"></div>`

### Expected/desired behavior
` aria-expanded` is not set
`<div tabindex="0" class="k-splitbar k-state-default k-splitbar-horizontal k-splitbar-draggable-horizontal" data-marker="i3db7968" role="separator" style="height: 169px; left: 414px;"></div>`

### Environment
* **Kendo UI version:** 2021.1.224

**Comment by veselints** [comment]
Also reported in: Ticket ID: 1524571
