### ISSUE TITLE
Text Selection tool in PDF Viewer cannot be enabled from the toolbar

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-ui-core#6324]
### Bug report

Text Selection tool in PDF Viewer cannot be enabled from the toolbar

### Reproduction of the problem
Open our online demos: https://demos.telerik.com/kendo-ui/pdfviewer/index and try enabling the Text selection tool

### Current behavior
Text Selection tool in PDF Viewer cannot be enabled from the toolbar

### Expected/desired behavior
Should be able to enable the Text Selection tool in PDF Viewer
### Environment

Issue replicable as of R1 SP1 2021
* **Kendo UI version:** 2021.1.224
* **Browser:** [all]

**Comment by khalidminhas** [comment]
Is it available in web?
