### ISSUE TITLE
Grid renders incorrect popup template when using dynamic columns

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#6335]
### Bug report

The MVC and Core wrapper renders incorrect popup template when using dynamic columns. More information can be found in ticket - 1511419. 

### Reproduction of the problem
Alter the edit mode to popup on [this sample](https://github.com/telerik/ui-for-aspnet-core-examples/blob/master/Telerik.Examples.Mvc/Telerik.Examples.Mvc/Views/Grid/Dynamic.cshtml).

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket#1522079

**Comment by VicTachev** [comment]
This appears to be a configuration issue in the example. We will add a new example showing how to implement PopUp Editing with dynamic columns. 
https://github.com/telerik/ui-for-aspnet-core-examples/issues/44
