### ISSUE TITLE
2021.1.225 not available on CDN or marked as latest release on github 

### ISSUE THREAD

**Issue by frederikdekegel** [telerik/kendo-ui-core#6338]
### Bug report

The latest release on NPM for Kendo UI jQuery is 2021.1.225. However the version 2021.1.225 is unavailable on the CDN and is nowhere to be found telerik / kendo-ui-core

### Reproduction of the problem
Available: https://kendo.cdn.telerik.com/2021.1.224/js/kendo.all.min.js 
Not available: https://kendo.cdn.telerik.com/2021.1.225/js/kendo.all.min.js 

### Expected/desired behavior
To be able to download version 2021.1.225 from https://kendo.cdn.telerik.com/2021.1.225.

### Environment

* **Kendo UI version:** 2021.1.225

**Comment by dmanova** [comment]
The correct version is 2021.1.224. Please use/install it.
The one 2021.1.225 seems to be added by mistake to NPM. We'll review possible solutions of the issue (remove the version from NPM or add to CDN).

**Comment by dmanova** [comment]
Indeed, the published package version in NPM (2021.1.225) is already used by many users, so we couldn't unpublished it and change it.

We have taken procedural measures to avoid similar cases in the future.

You can use versions of NPM 2021.1.225 with CDN 2021.1.224, and this will not have a negative impact, as the code in them is in synch, despite the difference in version numbers.
You can also download the latest package (e.g. 2021.1.330) in which the versions in NPM and CDN correspond.
