### ISSUE TITLE
Format not applied to column bound to nested property

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#6353]
### Reproduction of the problem
Grid columns setup: 
```
.Columns(columns => {
        
        columns.Bound(p => p.ProductName);
        columns.Bound(p => p.LastSupply).Format("{0:MM/dd/yyyy}");
        columns.Bound(p => p.Category.TestDate).Format("{0:MM/dd/yyyy}");
    })
```

Model:

```
new ProductViewModel
{
	ProductID = 1,
	ProductName = "name",
	LastSupply = DateTime.Now,
	Category = new CategoryViewModel {
		CategoryID = 123,
		CategoryName="test",
		TestDate = DateTime.Now
	}

});
```

### Current behavior
The Grid looks like this:
![image](https://user-images.githubusercontent.com/11771009/112661586-5b50ee80-8e5f-11eb-8a0f-040cb0f4a252.png)

### Expected/desired behavior
The date should be parsed and the specified format should be applied for the TestDate column

### Environment

* **Kendo UI version:** 2021.1.224
* **Browser:** [all]

**Comment by gyankov** [comment]
The Format setting of the column is serialized correctly. However, the DataSource supports value parsing only for flat data. Thus, all properties of complex fields are treated as strings and formatting strings as dates/numbers is not possible.

The very [same behavior can be observed with the jQuery component](https://dojo.telerik.com/UMekeKuf), so its not server wrappers specific either.

The suggest approach in this case is to format the value using a client template.

e.g.

```
columns.Bound(p => p.Category.TestDate).ClientTemplate("#=kendo.toString(kendo.parseDate(Category.TestDate),'MM/dd/yyyy')#");
```
