### ISSUE TITLE
Scaffolder extension for UI for ASP.NET MVC does not work in Visual Studio 2019 version 16.9.0+

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6356]
### Reproduction of the problem
1. Visual Studio 2019 version 16.8.3 (or another version the extension works with)
2. Install the Scaffolder extension. 
3. In a sample Terlerik ASP.NET MVC Application verify that the Kendo Scaffolder and its configuration panel work as expected.
4. Update Visual Studio to version 16.9.2.

### Current behavior
The Kendo Scaffolder is no longer available in the **Add New Scaffolded Item** dialog.

### Expected/desired behavior
The Kendo Scaffolder works as intended. 

### Environment

* **Kendo UI version:** 2021.1.224
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Reported in ticket 1514369

**Comment by nelito987** [comment]
Reported in ticket 1515028

**Comment by Dimitar-Goshev** [comment]
Reported in ticket 1516639

**Comment by gyankov** [comment]
Issue appears to be on Visual Studio's side:

- https://developercommunity.visualstudio.com/t/visual-studio-2019-version-1691-resulted-in-custom/1371519

**Comment by mparvanov** [comment]
Possible solution in https://developercommunity.visualstudio.com/t/visual-studio-2019-version-1691-resulted-in-custom/1371519#T-N1479791

**Comment by eyupyusein** [comment]
Reported in Ticket ID: 1532884

**Comment by mparvanov** [comment]
Kendo UI Scaffolder is available in VS2019 latest version and but not available in VS2022

**Comment by gyankov** [comment]
I've opened a new feedback item in the VS portal:

https://developercommunity.visualstudio.com/t/Custom-scaffolder-not-working-in-VS-2022/10025016?viewtype=all&space=8&entry=suggestion

**Comment by IvanDanchev** [comment]
Closing this issue as no longer relevant, since we implemented our own Scaffolder: https://github.com/telerik/kendo/issues/17919
