### ISSUE TITLE
MultiSelect configured for server filtering sends duplicated read request on blur and open

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6361]
### Bug report

MultiSelect configured for server-filtering="true" sends an empty request on focusout
```
     <kendo-multiselect for="SelectedOrderIds" style="width:100%"
                       placeholder="Select addresses..."
                       datatextfield="ShipName"
                       datavaluefield="OrderID"
                       filter="FilterType.Contains"
                       value="Model.SelectedOrders.Select(x=>x.OrderID)">
        <datasource type="DataSourceTagHelperType.Ajax" server-filtering="true">
            <transport>
                <read url="@Url.Page("Index", "Read")" data="forgeryToken" />
            </transport>
            <schema data="Data">
                <model id="OrderID">
                    <fields>
                        <field name="ShipName" type="string"></field>
                    </fields>
                </model>              
            </schema>
        </datasource>
    </kendo-multiselect>
```

### Reproduction of the problem
[TelerikAspNetCoreApp197.zip](https://github.com/telerik/kendo-ui-core/files/6249043/TelerikAspNetCoreApp197.zip)

1. Run the attached application
2. Enter 34, for example, and select the returned item
3. Click outside of the MultiSelect

### Current behavior
An empty request is sent, fetching all data.

### Expected/desired behavior
A request should not be sent.

### Environment

* **Kendo UI version:** 2021.1.330
* **Browser:** [all]

**Comment by gyankov** [comment]
Same behavior replicates in the [jquery server filtering demo](https://demos.telerik.com/kendo-ui/multiselect/serverfiltering). It is not related with the server wrappers.

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1554693

**Comment by Iankodj** [comment]
Reported in 1534530

**Comment by mihaela-lukanova** [comment]
Reported in 1608079.

**Comment by nelito987** [comment]
Reported in ticket ID:  **1610895**

**Comment by nelito987** [comment]
Reported in ticket: 1482318
