### ISSUE TITLE
Declarative Initialization of numerictextbox  with kendo.init crashes !!!

### ISSUE THREAD

**Issue by pda-code** [telerik/kendo-ui-core#6372]
A very simple scenario
The case is that I want to input a 5 digit integer with leading zeroes.

### Scenario 1
![image](https://user-images.githubusercontent.com/10973438/114085153-a801e400-98b9-11eb-8349-de7128d845f1.png)

### Result 1
![rNcUtX4VPH](https://user-images.githubusercontent.com/10973438/114086036-cd432200-98ba-11eb-8169-3000e929f7f8.gif)

### Scenario 2
![image](https://user-images.githubusercontent.com/10973438/114085511-252d5900-98ba-11eb-92c9-c6a675a57afb.png)

### Result 2
![AS0eliy3Yk](https://user-images.githubusercontent.com/10973438/114086056-d46a3000-98ba-11eb-8ca8-76126addd126.gif)

**Comment by dmanova** [comment]
Indeed it is not working as expected with` data-format="00000"`, but as a workaround it seems to give the desired format when is specified like` data-format="0000#" `
