### ISSUE TITLE
The zoom tool in the PDFViewer's toolbar is disabled when it is in the overflow menu

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6377]
### Reproduction of the problem
Reproducible in the demos: [https://demos.telerik.com/kendo-ui/pdfviewer/index](https://demos.telerik.com/kendo-ui/pdfviewer/index)
1. Shrink the browser window so that the zoom tool goes into the overflow menu.
2. Click on the overflow button to open the menu.

### Current behavior
The zoom tool is disabled.

### Expected/desired behavior
The zoom tool is enabled. 

### Environment

* **Kendo UI version:** 2021.1.330
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1569578
