### ISSUE TITLE
MultiSelect doesn't focus the first suggested item of the popup

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#6385]
### Bug report

MultiSelect doesn't focus the first suggested item of the popup

### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/@Stoyan/agEHEJoL)
2. Make sure it has at least 2 values set on initialization
4. Write some text until the popup opens with some suggestions

### Current behavior
Starting from version 2020.3.1118 the first suggestion of the popup is not focused as expected.

### Expected/desired behavior
The first suggestion should be focused. This behavior can be observed in version 2020.3.1021 and earlier. Review in [this Dojo](https://dojo.telerik.com/@Stoyan/oLoCociZ)

### Environment

* **Kendo UI version:** 2020.3.1118 or later
* **Browser:** [all]

**Comment by veselints** [comment]
Might be related to: https://github.com/telerik/kendo-ui-core/issues/5889
