### ISSUE TITLE
DateRangePicker does not work with depth different than month

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#6400]
### Bug report
Value not selectable when start and depth are configured
Currently, due to the filter of the RangeSelectable, it is not possible to select a date with a depth set to anything but "month".

### Reproduction of the problem
https://dojo.telerik.com/@sspasova/APUfiHiM
Or
1. open this Dojo - https://dojo.telerik.com/@Dimitar-Goshev/ilOwIsAP
2. try to select a range 

### Current behavior
It is not possible to select a date.

### Expected/desired behavior
It should be possible to select a date as it is currently in DatePicker.
Dojo: https://dojo.telerik.com/@sspasova/OWEwubOD

### Suggested fix

```
                that.rangeSelectable = new RangeSelectable(that.wrapper, {
                    filter: "table.k-" + that.options.depth + " " + CELLSELECTORVALID,
                    change: proxy(that._rangeSelection, that)
                });
```

### Environment
* **Kendo UI version:** 2024.3.806
* **jQuery version:** 3.4.1
* **Browser:** all

**Comment by gdenchevprog** [comment]
Reported again 1517569

**Comment by iordanGrancharov** [comment]
The DateRangePicker's selections intentionally work only with `depth: "month"`, because with other `depth` options, the starting and ending dates cannot be determined correctly.
