### ISSUE TITLE
The cursor is misplaced when filtering the DropDownList with Korean language in Internet Explorer

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6413]
### Bug report

The input cursor is positioned incorrectly when filtering the DropDownList in IE with Korean language.

### Reproduction of the problem
1. Open this Dojo - https://dojo.telerik.com/eHUBOtOW/2
2. Make sure to select Korean as language.
3. Filter the widget.

A small video that demonstrates the issue - http://somup.com/crhXInFdp7

### Current behavior
The cursor position is changed to the left in the input field

### Expected/desired behavior
The cursor should remain after the last typed character.

### Environment

* **Kendo UI version:** 2021.1.330
* **Browser:** [Internet Explorer 11]

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
