### ISSUE TITLE
drawDOM and exportPDF do not export properly some non ASCII fonts

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#6415]
### Bug report
drawDOM and exportPDF do not export properly some non ASCII fonts. Tested with Gujarati and Chinese simplified.

### Reproduction of the problem
* Run the following sample and click the button to generate PDF: 
[NonAsciiFonts.zip](https://github.com/telerik/kendo-ui-core/files/6465125/NonAsciiFonts.zip)
* Note the missing characters in the exported PDF

### Expected/desired behavior
All characters should be properly exported.

### Environment
* **Kendo UI version:** 2024.1.130
* **Browser:** [all]

**Comment by martintabakov** [comment]
If you change the Kendo version in the project to 2024.1.130, all the characters are property exported. Closing the issue until further information to reproduce is provided.
