### ISSUE TITLE
TextBox has incorrect height in LESS-based themes

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-ui-core#6428]
### Reproduction of the problem

The height of the TextBox is too small when using a LESS theme

### Current behavior
Open the [TextBox demo](https://demos.telerik.com/kendo-ui/textbox/index?autoRun=true&theme=default) and use the Default LESS theme
The height of the widget is too small:
![image](https://user-images.githubusercontent.com/11771009/119457869-d1c97a00-bd44-11eb-9b8c-3bec7b223b29.png)

### Expected/desired behavior
The height should be the same as the one used in the SASS themes.

### Environment

* **Kendo UI version:** 2021.2.511
* **Browser:** [all]

**Comment by laborZH** [comment]
We can confirm the Bug. We have also this problem

we corrected with css ->> line-height: 1.8em;

Best regards
Murat / laborZh
