### ISSUE TITLE
DateTimePicker cleared incorrectly

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#6429]
### Bug report

When a DateTimePicker with a DateInput is used the mask is cleared if the value is null

### Reproduction of the problem
Run this dojo and check the DateTimePicker - https://dojo.telerik.com/OcaVaWoX/3

### Current behavior
Mask is cleared

### Expected/desired behavior
Mask should be visible

**Comment by MilenaCh** [comment]
When datetimepicker has initially set date, .value() does not work.

Steps:
Execute the code below from datetimepicker-clear branch:
https://dojo.telerik.com/IciXUCom
Actual Result: DateTimePicker is populated with value(2011, 0, 1)
Expected result: DateTimePicker should be empty
