### ISSUE TITLE
Wrong cell value is displayed in the Spreadsheet formula input when the copied value is 0.

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6433]
### Bug report

When you copy a formatted cell with value "0", pasting the content in the Spreadsheet results in an incorrect value in the formula input.

### Reproduction of the problem
1. Open the attached file [in the Spreadsheet](https://demos.telerik.com/kendo-ui/spreadsheet/index).
[CopyPaste-CellFormatIssue.xlsx](https://github.com/telerik/kendo-ui-core/files/6545007/CopyPaste-CellFormatIssue.xlsx)
2. Open the attached file in Excel.
3. Copy the content from C3 to C5 and paste it in the Spreadsheet. 

### Current behavior

The value of the cells containing "-" are incorrectly changed to "-" in the formula bar.

### Expected/desired behavior

The value of the cells containing "-" should remain "0" in the formula bar.

### Environment

* **Kendo UI version:** 2021.2.511
* **Browser:** [all]

**Comment by mishoo** [comment]
Not fixable for Excel — it does not provide the raw cell values anywhere in the clipboard data. I linked a commit, though, that fixes a bunch of issues when pasting from Google Sheets or LibreOffice, as they both provide raw values and custom number format. Google Sheets provides formulas as well, so it's best supported at the moment.
