### ISSUE TITLE
Editor value() returns empty string when replacing an element with contenteditable="false"

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6434]
### Bug report

In the Editor with non-editable content, if you delete the content of the <span contenteditable=false> element and type new value, the new value cannot be obtained.

Note: currently, a `<span class='k-break'>` is rendered before the non-editable content. Before the regression, it was a `<br class="k-br">` element.
 
Regression introduced in Kendo 2020.1.114

### Reproduction of the problem
1. Open the Dojo - https://dojo.telerik.com/@martin.tabakov@progress.com/EgaKIGOQ/3.
2. Place the cursor after the text in the Editor and type new value.
4. Click the test button.

### Current behavior

The value method returns empty value, instead of returning the newly typed value.

### Expected/desired behavior

The value method should return the newly typed content.

### Environment

* **Kendo UI version:** 2021.2.511
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The scenario described above is fixed. But there is another issue related to the same change and we should address it as well.
1. Open the Dojo - https://dojo.telerik.com/@martin.tabakov@progress.com/EgaKIGOQ/3.
1. Place the cursor after the text in the Editor and press Enter - a JS error is thrown - `Cannot read property 'parentNode' of null`

**Comment by Dimitar-Goshev** [comment]
The two issues from my previous comment are fixed. There is still one issue:
1. Use the setup from https://dojo.telerik.com/@martin.tabakov@progress.com/EgaKIGOQ/3
2. Click after New content and press Shift + Enter
3. Type a - The br will be removed and a will be moved after New content

**Comment by Dimitar-Goshev** [comment]
The new fix fixes the br removal, but in FF a new issue appears from it:
1. In FF use the setup from https://dojo.telerik.com/@martin.tabakov@progress.com/EgaKIGOQ/3
1. Click after New content and press Shift + Enter - there is no visible caret in the Editor
1. Type a - a is added before New content
