### ISSUE TITLE
MultiSelect filter accepts only string as value

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6435]
### Bug report

The dataSource filter configuration only accepts string as value.

### Reproduction of the problem
1. Open the Dojo example - https://dojo.telerik.com/OSOjOYOs/2
2. Open the MultiSelect.

Regression introduced with Kendo 2021.1.330

### Current behavior

An error is thrown and the MultiSelect does not open.

### Expected/desired behavior
There should be no error and the MultiSelect should open.

### Environment

* **Kendo UI version:** 2021.2.511
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
The issue is still present when the filter configuration is defined the following way:
```
"filter": [{	
              "logic": "and",	
              "filters": [{	
                "field": "Discontinued",	
                "operator": "eq",	
                "value": false	
              }]	
            }],
```

Reported in ticket 1549179.
