### ISSUE TITLE
PHP Wrapper for PivotGrid doesn't have the correct schema structure.

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-ui-core#6439]
### Bug report

The PHP Wrappers for the PivotGrid do not work with flat data binding.

### Reproduction of the problem

The problem can be reproduced in the Local PHP Demos - Remote Binding. The measures and columns can be pre-added to the dataSource, however if you attempt to add them through the configurator, errors are thrown in the console.

![image](https://user-images.githubusercontent.com/70957719/120172537-d4781380-c20b-11eb-819f-93e625d7755c.png)

This is how the schema's dimensions and measures look in a working PivotGrid:
![image](https://user-images.githubusercontent.com/70957719/120171947-3be19380-c20b-11eb-8814-a8b26e7473af.png)

And this is how they look with the PHP Wrappers:
![image](https://user-images.githubusercontent.com/70957719/120172094-5fa4d980-c20b-11eb-8c1c-b1859b3892f6.png)

### Current behavior

The PHP Wrappers for the PivotGrid do not have the correct schema configuration.

### Expected/desired behavior

The PHP Wrappers for the PivotGrid should have the correct schema configuration.

### Environment

* **Kendo UI version:** 2021.2.511
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by martintabakov** [comment]
Closing the bug due to the deprecation of the PHP wrappers.
