### ISSUE TITLE
ImageEditor's canvas overflows its container when the Toolbars wraps on a 2nd row with Core wrappers 

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#6452]
### Bug report

When the ImageEditor is resized and the Toolbar wraps on 2 rows the canvas of the Component overflows its container. 

### Reproduction of the problem
1. Add the following code to a Telerik UI for ASP .NET Core project:
```snippet
<div class="demo-section k-content">
    @(Html.Kendo().ImageEditor()
        .Name("imageEditor")
        .Height(900)
        .SaveAs(s => s.FileName("image_edited.png"))
        .ImageUrl(@Url.Content("~/images/latest-available version.png"))
        .Events(e=>e.ImageRendered("rendered").Execute("executed"))
    )
</div>
<div class="mt-5 card">  <div class="card-body">48px margin above</div></div>
```
2. Resize the window until the Toolbar of the ImageEditor wraps on 2 rows.

### Current behavior
The margin between the ImageEditor and the following div disappears as the ImageEditor overflows its container

### Expected/desired behavior
The ImageEditor's should fit in its div container

### Environment

* **Kendo UI version:** 2021.2.511
* **Telerik UI for ASP .NET Core
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
No longer reproducible with v2024.1.130 - [REPL](https://netcorerepl.telerik.com/wIkmvJOU281mgu8s30)
