### ISSUE TITLE
"selectable: "multiple, row"" option blocks ability to copy content of table with formatting.

### ISSUE THREAD

**Issue by v-olg** [telerik/kendo-ui-core#6458]
### Bug report

For example we have a grid:

```
<div id="grid"></div>
<script>
$("#grid").kendoGrid({
  columns: [
    { field: "name" },
    { field: "age" }
  ],
  dataSource: [
    { name: "Jane Doe", age: 30 },
    { name: "John Doe", age: 33 }
  ],
  selectable: "multiple, row"
});
</script>
```
Without  `selectable: "multiple, row"` option, I can copy the contents of the grid and send it in an email like this:

![image](https://user-images.githubusercontent.com/77701769/122428293-76cd2080-cf9a-11eb-8208-d0bb5a5d7f33.png)

It is the native capability of browser.

### Expected/desired behavior
When I use `selectable: "multiple, row"` in project should be supported the native capability of browser to copy html and paste it to editors supported html:

![example](https://user-images.githubusercontent.com/77701769/122430173-04f5d680-cf9c-11eb-955b-afdf53d52bd7.gif)

### Environment

Kendo UI version: "2020.3.1118"
Browser: Chrome 90.0.4430.212

**Comment by ag-petrov** [comment]
This is not a bug and is the expected default behavior. If selection of HTML is enabled by default this may cause unexpected and undesired behavior. Enabling it is possible by unbinding to the select event of the user events like demonstrated below.

```
$("#grid").kendoGrid({
            columns: [
                { field: "name" },
                { field: "age" }
            ],
            dataSource: [
                { name: "Jane Doe", age: 30 },
                { name: "John Doe", age: 33 }
            ],
            selectable: "multiple, row"
        });

        $("#grid").getKendoGrid().selectable.userEvents.unbind("select");
```

**Comment by v-olg** [comment]
> This is not a bug and is the expected default behavior. If selection of HTML is enabled by default this may cause unexpected and undesired behavior. Enabling it is possible by unbinding to the select event of the user events like demonstrated below.
> 
> ```
> $("#grid").kendoGrid({
>             columns: [
>                 { field: "name" },
>                 { field: "age" }
>             ],
>             dataSource: [
>                 { name: "Jane Doe", age: 30 },
>                 { name: "John Doe", age: 33 }
>             ],
>             selectable: "multiple, row"
>         });
> 
>         $("#grid").getKendoGrid().selectable.userEvents.unbind("select");
> ```

Thanks for investigation of the issue and detailed reply.

Unfortunatly, your solution does not work in the demo in dojo - it allows copy only one letter:
![image](https://user-images.githubusercontent.com/77701769/123598007-b8609580-d7fc-11eb-82b3-24696078e2d5.png)

I don't quite agree that is not a bug because copying html is native functional of browser and removing this functionality without providing any alternatives is a bug in my opinion.

For example:

For example, msazure is not allows you to copy html but they provide the alternative - I just select several work items in table, press ctrl + c and may paste it in outhlook mail or here:

![image](https://user-images.githubusercontent.com/77701769/123598553-53596f80-d7fd-11eb-8fbd-89b872c5557e.png)
<html>
<body>


ID | Title | Assigned To | State | Area Path | Tags | Comments
-- | -- | -- | -- | -- | -- | --
10195309 | ARIA: issues with strange behaviour | Dmitrii Barkalov | New | One\Azure Compute\CIS | Accessibility bug; Frontend&Data; Nickel Planning | 1
10195118 | ARIA: keyboard accessibility issues: PART 2 | Dmitrii Barkalov | New | One\Azure Compute\CIS | Accessibility bug; Frontend&Data; Nickel Planning | 1
10195634 | ARIA narrator: part 6 \| another issues | Dmitrii Barkalov | New | One\Azure Compute\CIS | Accessibility bug; Frontend&Data; Nickel Planning | 1


</body>
</html>

Is it possible to provide something like that if we can't copy html?

**Comment by ag-petrov** [comment]
I did test the above approach prior to suggesting it in an isolated sample but it did not work correctly in all cases as it seems. That said I suggest setting the [allowCopy ](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/allowcopy)property to true. That way you should be able to load the selected items into the clipboard when pressing ctrl + C. [Here ](https://dojo.telerik.com/ohUBuQUl/3)is a modified version of the dojo that enables this.
