### ISSUE TITLE
DatePicker is rendered in the Form when the string could be evaluated as Date

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6461]
### Bug report

When a string that could be evaluated as a Date is used in the Form, a DatePicker is rendered instead of TextBox

### Reproduction of the problem
1. Open the [Dojo linked here](https://dojo.telerik.com/@NeliKondova/iDafUWek)

### Current behavior
The fromData for the first field is set as string _'TextBox1: "12/11/1969"'_, however, the '12/11/1969' could be evaluated as a Date. Thus, the From displays a DatePicker although the field is not explicitly casted to Date. 

### Expected/desired behavior
 When the value is not explicitly set as a Date a TextBox should be rendered in the Form.

### Workaround
```
var MyModel = kendo.data.Model.define({
              fields: {
                  "TextBox1": {
                      type: "string"
                  },
                  "TextBox2": {
                      type: "string"
                  }
              }
          });
```
[Dojo ](https://dojo.telerik.com/@NeliKondova/eYEBAJEZ)

### Environment

* **Kendo UI version:** 2021.2.616
* **Browser:** [all]

**Comment by martintabakov** [comment]
Also reported in ticket #1533298

**Comment by veselints** [comment]
Closing this as the recognition of Date string is made on purpose. That facilitates scenarios in which data in the Form arrives as a string. Disabling this functionality will introduce a breaking change for all users that rely on the logic.
