### ISSUE TITLE
groupPaging and groupHeaderColumnTemplate cause an error in the Grid

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#6480]
### Bug report

The DataSource's property groupPaging: true prevents the Grid's group from expanding if it has a defined groupHeaderColumnTemplate.

### Reproduction of the problem
1. Open [this Dojo](https://dojo.telerik.com/@Stoyan/UgivApOy)
2. Note the rows are not rendered
3. Comment out the `groupPaging:true` configuration and the rows will be rendered as expected.

> Also reproducible in the Core wrapper where an error is thrown: **kendo.all.js:8743 Uncaught TypeError: Cannot read property 'hasSubgroups' of undefined**

Additional clarification on the item - when using Kendo UI for jQuery the rows are not rendered and no error is thrown as seen in the dojo. When using the HTML wrappers the behavior is the same - rows are not rendered, but trying to expand/collapse a row throws a JS error - [example](https://netcorerepl.telerik.com/QREqFAEL39ouXSLB40):
```
VM1148 kendo.all.min.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'hasSubgroups')
    at init.groupCount (VM1148 kendo.all.min.js:10:69661)
    at init._calculateGroupsTotal (VM1148 kendo.all.min.js:10:69506)
    at init.collapseGroup (VM1148 kendo.all.min.js:10:1728998)
    at t._groupableClickHandler.t._groupableClickHandler (VM1148 kendo.all.min.js:10:1645626)
    at HTMLTableElement.dispatch (VM1147 jquery.min.js:3:12445)
    at r.handle (VM1147 jquery.min.js:3:9174)
```

### Current behavior
groupPaging is not compatible with the groupHeaderColumnTemplate

### Expected/desired behavior
groupPaging and the groupHeaderColumnTemplate should be compatible

### Environment

* **Kendo UI version:** 2021.2.616

* **Browser:** [all]

**Comment by mihaela-lukanova** [comment]
It is reported in ticket [#1543637](https://supportheroes.telerik.com/ticket/1543637) as well.

**Comment by mihaela-lukanova** [comment]
Increased priority due to a report in TicketID: [1545544](https://supportheroes.telerik.com/ticket/1545544)

**Comment by mihaela-lukanova** [comment]
Increased priority due to a report in [public feedback item](https://feedback.telerik.com/aspnet-core-ui/1527224-grouppaging-and-groupheadercolumntemplate-cause-an-error-in-the-grid).

**Comment by aleksandarevangelatov** [comment]
Reported in ticket 1612373

**Comment by mihaela-lukanova** [comment]
Reported in ticket 1620786.

**Comment by ag-petrov** [comment]
@StoyanGoranov @mihaela-lukanova  the problem is not reproducible with the dojo. Can we please revise the sample and update it accordingly?

**Comment by StoyanGoranov** [comment]
> @StoyanGoranov @mihaela-lukanova the problem is not reproducible with the dojo. Can we please revise the sample and update it accordingly?

Yesa, the Dojo was malconfigured, here is a version that reproduces the issue: https://dojo.telerik.com/@Stoyan/UgivApOy
