### ISSUE TITLE
Cannot change width of a Grid column via keyboard

### ISSUE THREAD

**Issue by dmitriy-barkalov** [telerik/kendo-ui-core#6494]
### Bug report 

Grid control doesn’t allow to change width of columns via keyboard. Column width adjustments could be done only via mouse. It would be great to have this ability from the accessibility perspective. 

### Reproduction of the problem

1. Open https://demos.telerik.com/kendo-ui/grid/index
2. Set focus on header of any column
3. Try to change width of the column

### Current behavior

No hot key to change width.

### Expected/desired behavior
Any hot key (e.g. Shift + Arrow Left / Right) to change width of a column.

### Environment

Kendo UI version: "2020.3.1118"
Browser: Chrome 90.0.4430.212

**Comment by gdenchevprog** [comment]
This is not a bug, but a feature request and it should be logged as such through the [Feedback Portal](https://feedback.telerik.com/kendo-jquery-ui).
