### ISSUE TITLE
Tooltip width is calculated incorrectly with dynamic content in IE 

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-ui-core#6499]
### Bug report

When the tooltip is loading dynamic content that consists of image tags and "onerror" event is fired the automatic width is not calculated properly in Internet Explorer. As a result the tooltip width is narrower than its content. The issue starts to appear with version 2020.2.513. 

### Reproduction of the problem - since 2020.2.513
https://dojo.telerik.com/UdAYiFic/2 
Hover the second column of second grid row

### Current behavior
The tooltip width is less than the content and the image is cut
### Expected/desired behavior with versions prior 2020.2.513
https://dojo.telerik.com/igAjOcij 
The tooltip width is calculated in accordance with the content.

Ticket ID: 1528673

### Environment

* **Kendo UI version:** 2021.2.616
* **Browser:** [IE 11] 

Might be related to 
https://github.com/telerik/kendo-themes/issues/316#issuecomment-551949681
https://github.com/telerik/kendo-ui-core/issues/6205

**Comment by mparvanov** [comment]
As a workaround the tooltip content might be wrapped into a div container with min-width set: https://dojo.telerik.com/UdAYiFic/6

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
