### ISSUE TITLE
NVDA screen reader pronounce all options for drop down instead of just selected one

### ISSUE THREAD

**Issue by dmitriy-barkalov** [telerik/kendo-ui-core#6504]
### Bug report

NVDA screen reader (https://www.nvaccess.org/download/) pronounce all options for drop down with "filter: "contains"". In case there are a lot of options it could be annoying. And it is deferent behavior from regular HTML dropdown.

### Reproduction of the problem
1. Go to https://dojo.telerik.com/UmaNuBiC
2. Turn on NVDA
3. Expand Kendo UI drop down

### Current behavior

NVDA reads all items in drop down

### Expected/desired behavior

NVDA should read only selected item in dropdown. Please use regular HTML drop down for reference.

### Environment

* Kendo UI version: "2020.3.1118"
* Browser: Chrome 90.0.4430.212
* NVDA 2021.1

**Comment by Dimitar-Goshev** [comment]
The filter functionality in the DropDownList requires different solution than a simple select element scenario.When the DropDownList has enabled filter, the items in the dropdown will change dynamically on typing in the filter and returning only filtered results. To indicate this live region change to users using assistive technologies, the dropdown has [aria-live](https://www.w3.org/TR/wai-aria-1.2/#aria-live) attribute set to `polite`. This attribute is used by NVDA to read all items in the dropdown.

When there is no filter defined, the DropDownList has `aria-live` set to `off`. This setup resembles the scenario of a simple select element - dropdown items do not change dynamically. And the NVDA behavior is the same - only the selected item is read.
