### ISSUE TITLE
The buttonLayout option of the Dialog has no effect when using the SASS themes.

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6518]
### Bug report

The buttonLayout option of the Dialog has no effect when using the SASS themes.

### Reproduction of the problem

1. Open this Dojo example. https://dojo.telerik.com/@martin.tabakov@progress.com/opEyIMos/4

### Current behavior

The buttons rendering is not changed

### Expected/desired behavior
The buttons should be changed according to the buttonLayout option.

### Environment

* **Kendo UI version:** 2021.2.616
* **Browser:** [all]

**Comment by TeyaVes** [comment]
No longer reproducible as of Kendo v. 2022.1.119

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible since 2021.3.914 - [Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/OsEjenoc)
