### ISSUE TITLE
Calendar in DatePicker or DateTimePicker is not properly styled when used in grid filter

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-ui-core#6523]
**Describe the bug**
When datePicker or dateTimePicker is used in grid filter in SASS themes it is not properly styled.

**To reproduce**

1. Go to https://demos.telerik.com/kendo-ui/grid/remote-data-binding or use this Dojo: https://dojo.telerik.com/ogIGOgoZ
1. Click filter icon for column 'Order Date'
2. Click the calendar icon on any of the filter value fields
3. See the calendar in the popup window.

**Expected behavior**
The calendar should look like this:
![image](https://user-images.githubusercontent.com/52446546/122363396-93993200-cf61-11eb-91d6-d74dbfe67c20.png)

For componentType: "modern":
![image](https://user-images.githubusercontent.com/52446546/122362893-2d141400-cf61-11eb-8b02-acee18df0be2.png)

**Screenshots**
The look of the Kendo datePicker when in grid's filter:
![image](https://user-images.githubusercontent.com/52446546/122360568-26849d00-cf5f-11eb-9729-662478659a3b.png)
For componentType: "modern"
![image](https://user-images.githubusercontent.com/52446546/122361608-15885b80-cf60-11eb-916b-ff191e1b8a4d.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
The issue is related to calendar popup no being appended to the body. Another way would be to revisit how we style components inside the filter menu, though this will be less than ideal
