### ISSUE TITLE
Page scrolls to Spreadsheet component when a SASS theme is used

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6526]
**Describe the bug**
When using a SASS theme and there is a Spreadsheet on the page, on page load the page scrolls to the Spreadsheet

**To reproduce**
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/IJUFEqUs)
2. On load, the page scrolls to the Spreadsheet

**Expected behavior**
On load, the page should not scroll to the Spreadsheet, similar to the behavior when a LESS theme is used [example](https://dojo.telerik.com/@AleksandarEvangelatov/iToCAzIs)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Comment by Dimitar-Goshev** [comment]
This is logged - [Reconsider Spreadsheet auto-focus on a cell, when page containing the widget is loaded](https://github.com/telerik/kendo-ui-core/issues/2107)
