### ISSUE TITLE
Spreadsheet.saveJSON() creates corrupt data when Workbook contains images

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#6529]
### Bug report

Spreadsheet.saveJSON() creates corrupt data when Workbook contains images

### Reproduction of the problem
* Run the following Dojo: https://dojo.telerik.com/iPeNEmOR/13
* Click the button to call .saveJSON() and save the file
* Try to open the file in Excel - it has an error

### Expected/desired behavior
Workbook with images should be properly exported

### Environment

* **Kendo UI version:** 2021.2.616

**Comment by veselints** [comment]
Related to: https://github.com/telerik/kendo-ui-core/issues/6411

**Comment by mishoo** [comment]
Closing as duplicate of #6411.
