### ISSUE TITLE
AutoComplete in FilterCell shouldn't clone Grid's datasource with the filters

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6538]
### Bug report

When the Filterable mode is set to Row and the grid has filters set initially, the data sources of the AutoComplete widgets inside the FilterCell clone the filters. When the filter is cleared from the grid, the cloned filter remains in the data source of the AutoComplete and there is no way to see the full data set.

### Reproduction of the problem
1. Create a grid with Filterable.Row
1. Set an initial Filter to the Freight column
1. Type some value in the ShipName filter row.
1. Some of the options are missing
1. The AutoCompete inside the FilterCell remains with the filtered data source.

https://dojo.telerik.com/@AleksandarEvangelatov/AliMIboB

### Expected/desired behavior
The data source of the AutoComplete should be cloning the grid's data source without the filters.

### Environment

* **Kendo UI version:** 2021.1.330
* **Browser:** [all ]

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1530749

**Comment by gdenchevprog** [comment]
Can not reproduce.
https://dojo.telerik.com/IGEnOKaB

**Comment by gdenchevprog** [comment]
Reopening, reproducable in https://dojo.telerik.com/@AleksandarEvangelatov/AliMIboB
