### ISSUE TITLE
PanelBar's TagHelper item url property incorrectly loads content instead of redirecting 

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#6545]
### Bug report
PanelBar's TagHelper item url property incorrectly loads content instead of redirecting in v. 2021.2.616

### Reproduction of the problem
1. Create a project that uses Kendo version 2021.2.616
2. Initialize the following PanelBar with TagHelper:
```
    <kendo-panelbar name="panelbar1" class="k-scrollable" style="font-size:smaller" expand-mode="single">
        <items>
            <panelbar-item name="item1" text="First Item (/Index)" url="/Index" />
            <panelbar-item name="item1" text="Second Item (/Privacy)" url="/Privacy" />
            <panelbar-item name="item2" text="Third Item (Telerik demos)" url="https://demos.telerik.com/aspnet-core/"/>
        </items>
    </kendo-panelbar>
```
3. Compare with the PanelBar with HtmlHelper:
```
      @(Html.Kendo().PanelBar()
                  .Name("panelbar")
                  .ExpandMode(PanelBarExpandMode.Single)
                  .Items(panelbar =>
                  {
                      panelbar.Add().Text("First Item (/Index)").Url("/Index");
                      panelbar.Add().Text("Second Item (/Privacy)").Url("/Privacy");
                      panelbar.Add().Text("Third Item (Telerik demos)").Url("https://demos.telerik.com/aspnet-core/");
                  })
            )
```

### Current behavior
The Url property of the TagHelper loads content instead of redirecting.

### Expected/desired behavior
The Url property should redirect and not load content.

### Environment

* **Kendo UI version:** 2021.2.616
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1534385

**Comment by Dimitar-Goshev** [comment]
@aleksandarevangelatov  The solution breaks the fix for this scenario: https://github.com/telerik/kendo-ui-core/issues/5756
