### ISSUE TITLE
After adding a new task and editing an existing one, the "Add Child/Above/Below" menu unexpectedly appears in Gantt and JS error is thrown on selecting Add Above/Below

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6547]
### Bug report
The menu that determines where to add new task incorrectly appears after creating a new task and editing an existing one.

**Regression introduced with 2021.1.330**  from this issue - [TreeList does not trigger change event on checkbox select](https://github.com/telerik/kendo-ui-core/issues/6300)

### Reproduction of the problem
1. Open this Dojo example - https://dojo.telerik.com/uBAHUgOy
2. Add new task.
3. Randomly edit another task or click on the timeline so that no item is selected in the Gantt TreeList.
4. Click the Add Task button again.

### Current behavior
The Add Child/Above/Below menu appears unexpectedly.
Clicking on Add Above or Below option throws a JS error:
`Cannot read properties of undefined (reading 'get')`

### Expected/desired behavior
The menu should not appear and a new task should be added at the bottom of the list.

### Environment
* **Kendo UI version:** 2021.3.914
* **Browser:** [all]

**Comment by veselints** [comment]
This is a very good candidate for a functional test. At the end of the test we should check whether the add task pop-up is visible.
