### ISSUE TITLE
On dropping a text in the Editor it is not always pasted in the widget's content

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6566]
### Bug report

When text is copied and dragged to the Editor it is pasted only if it is dropped on the first row. It is not pasted if it is dropped below the first row of the content.

### Reproduction of the problem
1. Open the [Overview Demo](https://demos.telerik.com/kendo-ui/editor/index) in Chrome, Edge or IE
2. Clear the content
3. Copy part of the 'Overview' text that is above the example
4. Drag it to the Editor and drop it

### Current behavior
The text is pasted in the Editor only if it is dropped on the first line.  In case the text is dropped below the first line the cursor is not visible and the text is not pasted.

### Expected/desired behavior
The text should be pasted in the Editor even if it is dropped below the first line.

#### The issue is regression since version 2019 R2 SP1 (2019.2.619)
Related issue:  #5454

### Environment

* **Kendo UI version:** 2019.2.619
* **Browser:** [Chrome |IE XX | Edge ]

**Comment by veselints** [comment]
Introduced with: https://github.com/telerik/kendo/commit/384c85dd24460c0a5632419ebf35a8e5b8d5d226

To fix: https://github.com/telerik/kendo-ui-core/issues/4994
