### ISSUE TITLE
Incorrect k-selected class remains on the first dropdown item of virtual DropDownList when using jQuery 3.4.1+ and setting value through value method

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6567]
### Bug report

In a virtual DropDownList with a value set, the first item is marked as selected as well. The issue occurs when using jQuery 3.4.1 or later.

### Reproduction of the problem
1. Open this Dojo example. - https://dojo.telerik.com/@martin.tabakov@progress.com/UkOmiYEj
2. Open the DropDownList.

Second Dojo example, with the DropDownList as editor - https://dojo.telerik.com/@martin.tabakov@progress.com/agAYiliz

### Current behavior

Two items are marked as selected.

### Expected/desired behavior
Only the item with value 3 should appear as selected.

### Environment

* **Kendo UI version:** 2021.3.914
* **jQuery version: 3.4.1 and later
* **Browser:** [all]

**Comment by martintabakov** [comment]
The client reporting the bug has done some debugging and has shared his findings:

"The issue disappears in the newer jQuery versions when the implementation in kendo.virtuallist.js inside the function deferredRange is changed from

$.when.apply($, defs).then(function() {
to

$.when.apply($, defs).done(function() {
That prob. works because .done() runs synchronously in some situations where .then() doesn't run synchronously in newer jQuery versions.
See https://jquery.com/upgrade-guide/3.0/"

**Comment by tskarman** [comment]
Any time estimate on this?
It's a real problem that modern jQuery versions cannot be used as customers look at SBOM more and more closely. Using an outdated jQuery version raises eyebrows.
