### ISSUE TITLE
DatePicker popup has inconsistent min-height

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#6576]
### Bug report

The DatePicker's popup has a CSS min-height property set that causes it to sometimes have an empty blank space at the bottom.

### Reproduction of the problem
1. Open the [DatePicker Demo](https://demos.telerik.com/kendo-ui/datepicker/index)
2. Expand the monthpicker

Review [another occurence.](https://supportheroes.telerik.com/clientsfiles/1e2c0514-ca0d-413c-acd2-a529dc3b3edd_datepicker-now.png)

### Expected/desired behavior
There should be a blank space in the DatePicker's popup.

### Environment

* **Kendo UI version:** 2021.3.914
* **Browser:** [all]

**Comment by NikoPenev21** [comment]
Not a bug. The calendar has a min-height set so the height is persistent in all views. 
For custom scenarios, we can override the _$calendar-view-height_ variable to achieve the desired result.
