### ISSUE TITLE
Gantt duplicates requests when reordering items in the TreeList part 

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6597]
### Bug report

When tasks are reordered in Gantt duplicated requests are sent for updating.

### Reproduction of the problem
1. Open the [Gantt Overview Demo ](https://demos.telerik.com/kendo-ui/gantt/index)
2. Reorder two tasks and inspect the requests in the Network tab

### Current behavior
For example, in case two tasks on the same level are changing their places, four requests are sent, two by two the requests are the same. 
In case a task is moved on a different level multiple requests are sent, as all are duplicated. 

### Expected/desired behavior
There should be no duplicated requests when reordering tasks in Gantt

This is a regression introduced with R3 2020 (2020.3.915)

### Environment

* **Kendo UI version:** 2021.3.914
* **Browser:** [all ]

**Comment by veselints** [comment]
Needs e2e test to be added in order to add the scenario in question.
