### ISSUE TITLE
MVC Grid's refresh button has a different class compared to the Kendo UI Grid

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6605]
### Bug report
A note related to the scenario described below: when the setOptions method of the MVC Grid is called, the button renders with the correct class that the Kendo UI Grid uses. 

### Reproduction of the problem
1. Enable the Refresh button:
```
.Pageable(pager => pager
    .Refresh(true)
)
```
2. Inspect the button and compare it to the button rendered by the Kendo UI for jQuery Grid

### Current behavior
The button renders has the following classes:
```
<span class="k-icon k-i-refresh"></span>
```

### Expected/desired behavior
The expected classes: 
```
<span class="k-icon k-i-reload"></span>
```

### Environment

* **Kendo UI version:** 2021.3.914
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by eyupyusein** [comment]
The rendering seems fine with the latest version:

jQuery grid:
![image](https://user-images.githubusercontent.com/11816856/170946006-79d379ca-5eb5-4184-9a09-89b5d257fe58.png)

MVC grid:
![image](https://user-images.githubusercontent.com/11816856/170946403-b098a854-2065-4453-bd17-4977afabbf05.png)

Reload and Refresh classes lead to the same icon:
![image](https://user-images.githubusercontent.com/11816856/170946894-2d1e9085-b690-41d1-94f8-0bb8a356ef20.png)

**Comment by eyupyusein** [comment]
https://github.com/telerik/kendo/pull/15444
