### ISSUE TITLE
Subitems of a Menu do not open after the first time in IE with scrollable:true and openOnClick

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6618]
### Bug report

The sub items in a Menu only open the first time in IE when scrollable is set to true and openOnClick.rootMenuItems:true.

**Regression introduced with version 2020.1.114.**

### Reproduction of the problem

1. Open this Dojo example in IE - https://dojo.telerik.com/@martin.tabakov@progress.com/unuNEsOh
2. Hover a subitem in Item 1 or Item 2
3. Hover the subitem once again

### Current behavior

The subitems open only the first time

### Expected/desired behavior
The subitems should open every time you hover them

### Environment

* **Kendo UI version:** 2021.3.914
* **Browser:** [IE]

**Comment by Dimitar-Goshev** [comment]
Closing this issue as IE is not supported since R1 2023.
