### ISSUE TITLE
Cannot filter second time for the same value

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#662]
Steps:

1. Open the [server filtering demo](http://kendobuild/staging-kendo-ui/dropdownlist/serverfiltering)
2. Type "*to*" in the filter input
3. Select "*Tofu*"
4. Open the DropDownList again
5. Type "*to*"

Nothing happens at this point. The expected result is list to be filtered.

The same can be reproduced also in [virtualization mode](http://demos.telerik.com/kendo-ui/dropdownlist/virtualization). Write "*toms*" instead of "*to*".

**Comment by ggkrustev** [comment]
Fixed with 3d4e7ddc6675cb1f1c04d9c89d112ed057a2fd3e

**Comment by ggkrustev** [comment]
Cherry-picked in production with bcf15f3a782cc0882bc35ac00c0086b204180b7c
