### ISSUE TITLE
[DataSourceRequest] is not an attribute

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-ui-core#6627]
Hello,

i have upgraded our solution to the latest public .NET 5.0.

I was using Kendo.MVC  2020.1.114.0  and i have tons of controllers with actions like this 

`
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
...
... LogGridNew([DataSourceRequest] DataSourceRequest request)`

and it worked wonderfully.

However, after upgrade to .NET 5.0, runtime exception from Kendo.MVC was trhown because of breaking changes in .NET core 3.1
(https://github.com/dotnet/runtime/issues/48162)

After upgrade of Kendo.MVC to version 2021.3.1109.545 
i have got error that [DataSourceRequest] is not an attribute. 

Where can i find the DLL with DataSourceRequest? I though that there is breaking change in the usage of DataSource, however,,.. you are still using:

[DataSourceRequest] DataSourceRequest request

in your examples...

**I am using DLL from paid  Telerik UI for ASP.nET MVC R3 2021 / Wrappers / AspnetMVC / Binaries / MVC5** 

I have bought that ASP .NET Core as well.. so maybe correct DLL is somewhere there..

**Comment by mparvanov** [comment]
Thank you for your post and for your interest in Telerik UI for ASP.NET products! **Telerik UI for ASP.NET MVC** is a set of server-side wrappers that bring the HTML/JavaScript Kendo UI widgets to .NET MVC and it requires .NET Framework. On the other hand for ASP.NET Core framework there is another set of components called **Telerik UI for ASP.NET Core**
https://www.telerik.com/aspnet-core-ui
https://docs.telerik.com/aspnet-core/introduction
As this GitHub Issues list is for bug reports only, so I'm going to close this issue with this comment.
If you are looking for direct support from our team, you can purchase a Telerik UI for ASP.NET Core license (or any other license that includes Telerik UI for ASP.NET Corel). This will grant you read-write access to the Premium forums, the ability to submit tickets in our support system, and access to additional professional-grade widgets, charts and graphs.
Thanks again for your post and I hope you enjoy working with Telerik UI for ASP.NET Core!

**Comment by montella1507** [comment]
Hi @mparvanov  thank you  for your response.. However....

I still see little problem in Kendo DLL naming convention...

**Telerik UI for ASP.NET MVC has its DLL (without DataSourceRequest) in:**
.../wrappers/aspnetmvc/binaries/MVC5/ **Kendo.Mvc.dll** (2.7MB size)


**Telerik UI for ASP .NET Core has its DLL (WITH DatasourceResult) in:**
../wrappers/aspnetcore/binaries/aspnet.core/Telerik.UI.For.Aspnet.Core (NUGET Archive) 
There, in the NUGET archive is folder LIB/NET5.0/ and there is **Kendo.MVC.dll** (5.8MB size) 

My questions and maybe the issues are..
1) Why are both named Kendo.MVC.dll  ? Why is not that DLL in Kendo ui for aspnet.core something like Kendo.AspnetCore.dll ?? 

2) Why is that important DLL packed in NUGET archive and not the same way how is Kendo.MVC.dll (in UI for ASP MVC) provided?

**Comment by mparvanov** [comment]
Our convention currently is to have both assemblies called Kendo.MVC.dll. As **Telerik UI for ASP.NET MVC** and Telerik UI for **ASP.NET Core** are different products and technologies, their assemblies could not be referenced in one and the same project and should not be mixed. 
Telerik UI for ASP.NET Core is distributed as NuGet package which is an archive and it consists of dlls for the different .NET Core flavours. 
https://www.screencast.com/t/wgiDKitiklm
However you could extract the assemblies from the nuget and reference them as dlls also in ASP.NET Core project if you wish:
https://www.screencast.com/t/NfQjieBVenBR

**Comment by montella1507** [comment]
Ok, got your idea, thank you.
