### ISSUE TITLE
Select event not fired when clicking on an already selected ComboBox/MultiColumnComboBox item

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#6638]
### Bug report
[Select event](https://docs.telerik.com/kendo-ui/api/javascript/ui/multicolumncombobox/events/select) not fired on clicking over already selected ComboBox/MultiColumnComboBox item. According to the event description, it should be "Fired when an item from the popup is selected by the user either with mouse/tap or with keyboard navigation". It is fired when pressing Down arrow again when the last item is selected, but not fired if the last item is clicked.
Regression since [2018.3.1017 - Dojo](https://dojo.telerik.com/@Dimitar-Goshev/UcUYObUG) introduced with the fix for [Unexpected ComboBox value selection, instead of text, when an item is selected with Enter](https://github.com/telerik/kendo-ui-core/issues/4516)

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/multicolumncombobox/events
2. Expand the widget.
3. Click on Item 3.
4. Expand the widget again.
5. Click on Item 3.

### Current behavior
Select event is NOT fired.
If we expand the widget and press Down arrow, select event is fired once again for Item 3.

### Expected/desired behavior
Select event is fired as with version [2018.3.911 - Dojo](https://dojo.telerik.com/@Dimitar-Goshev/UzukOcaJ).

### Environment
* **Kendo UI version:** 2021.3.1109
* **Browser:** all

**Comment by Iankodj** [comment]
The described behaviour is expected - the select event should not be raised when clicking on an already selected item. Also, when performing selection using the keys also select event should not be fired when item is selected. 

We can use this issue to evaluate and revise the entire mechanism for the select event and unify it across the list components instead of bringing back the old select event's behaviour.

**Comment by Dimitar-Goshev** [comment]
As the reported behavior is expected, I am closing the issue. If the current behavior should be re-evaluated, we should open a new item for it.
