### ISSUE TITLE
Map custom markers are not positioned correctly when zoom out using less themes

### ISSUE THREAD

**Issue by yanisslav** [telerik/kendo-ui-core#6641]
### Bug report
Not reproducible with Sass themes.

### Reproduction of the problem
https://dojo.telerik.com/ejaVeZUD/7

### Current behavior
Map custom markers are not positioned correctly when zooming out using 'Less' themes

### Expected/desired behavior
Markers are positioned correctly when zooming out.

### Environment

* **Kendo UI version:** 2021.3.1109
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by magdalenaan** [comment]
The issue is not reproducible with the 2022.3.913 version.
