### ISSUE TITLE
Widget returns data items with offset by 1 when option label is defined

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#665]
### Repro steps:

1. Open http://demos.telerik.com/kendo-ui/dropdownlist/cascadingdropdownlist
2. Get the data item of the first dropdownlist using this code:

``` javascript
$("#categories").data("kendoDropDownList").dataItem(0);
```

Notice that the returned data item is not the optionLabel.

Reported in Ticket ID: 920693

**Comment by naskog** [comment]
One more Ticket ID: 921592
