### ISSUE TITLE
Editor Table Wizard keyboard navigation improvements

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6655]
### Enhancement
- [x] "Create a Table"  tool works only by pressing `Alt + Down Arrow` and expands a popup. I suggest expanding the popup on `Space` or `Enter` as well. Thus the current `Alt + Down Arrow` behavior could work as well.

- [x] It is not possible to focus through keyboard the "Table Wizard" tool inside "Create a Table" popup:
![image](https://user-images.githubusercontent.com/14364791/145046878-a2899a12-5c24-4075-a460-8aebbc2b39cc.png)

### Reproduction of the problem
1. Go to https://demos.telerik.com/kendo-ui/editor/index
1. Focus Editor
1. Press F10 to focus toolbar
1. Press Tab key until "Create a Table" tool is focused
1. Press Space/Enter to activate it - nothing happens.
1. Press Alt + Down Arrow to expand the popup
1. Press Down Arrow to select table size

### Current behavior
It is not possible to select the Table Wizard tool neither through arrow keys nor through Tab

### Expected/desired behavior
When the bottom table size cell is reached, pressing Down Arrow once again moves the focus to the Table Wizard tool.
When Table Wizard tool is focused, pressing Up Arrow moves the focus to the bottom table size cell.

### Environment
* **Kendo UI version:** 2021.3.1109
* **Browser:** all

**Comment by ashutosh-kendurkar** [comment]
Hello Team,

for the earlier versions of Kendo library, is there any work-around or fix available for this behavior? 

any help is appreciated.

**Comment by veselints** [comment]
Hi @ashutosh-kendurkar,
You will need to update the Kendo version used in order to benefit from the improvements in question. Patch for previous versions is not available.
