### ISSUE TITLE
Multiple IDs are getting generated when clicking parent label in dropdowntree widget treeview

### ISSUE THREAD

**Issue by Yeswanth-JG** [telerik/kendo-ui-core#6669]
### Bug report

When we have `checkChidren` set to true under `checkboxes` option for kendo **dropdowntree**, clicking on parent label in treeview is creating duplicate IDs for the self (parent) and it's children.

### Reproduction of the problem
Dojo : [https://dojo.telerik.com/EjOVIlep](https://dojo.telerik.com/EjOVIlep).
### Current behavior
> Right now whenever the parent label is clicked, duplicate IDs are getting created for the self and for its  childrens. But the same isn't happening when we click input checkbox.

### Expected/desired behavior
> Duplicate ID's shouldn't be generated.
Dojo(2021.3.914) : https://dojo.telerik.com/EjOVIlep/11

### Environment

* **Kendo UI version:** 2021.3.1207 (Reproducible since 2021.3.1109)
* **jQuery version:** 1.12.4
* **Browser:** "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62"

**Comment by Yeswanth-JG** [comment]
Thanks @mparvanov 👍

**Comment by veselints** [comment]
The bug was actually in the TreeView. The issue could no longer be reproduced with the current state of the TreeView widget.
