### ISSUE TITLE
ContextMenu is not scrollable with SASS themes

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6673]
related to:
https://github.com/telerik/kendo-themes/issues/2961

### Bug report

ContextMenu is not scrollable with SASS themes. The arrow for scrolling is missing.

1. Open in Dojo the [scrollable](https://docs.telerik.com/kendo-ui/api/javascript/ui/contextmenu/configuration/scrollable) example in the ContextMenu API
1. Right-click to see the ContextMenu

**Expected behavior**
The ContextMenu should be scrollable with SASS themes when the scrollable option is enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/14364791/141467599-5aab293d-84e4-445b-8de0-420edf6b454e.png)

### Current behavior
Currently, the ContextMenu is not scrollable when SASS themes are used.

**Additional context**
Regression since version: 2020.2.513

### Environment

* **Kendo UI version:** 2021.3.1207
* **Browser:** [all]

**Comment by veselints** [comment]
No longer reproducible with themes v 5.0.0

**Comment by Dimitar-Goshev** [comment]
Themes v5 are released with Kendo UI version 2022.1.119 - working [Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/UDAMeruH).
