### ISSUE TITLE
GridView ExportToXlsx - Generates excel with wrong header/data

### ISSUE THREAD

**Issue by sfaccendatetrillo** [telerik/kendo-ui-core#6685]
### Bug report
I have a problem related to exporting Excel from a gridview using the ExportToXlsx function. It works fine but in some cases the generated excel "mixes" header and row data

### Reproduction of the problem
unfortunately the behavior is quite strange as even with large amounts of data it works correctly but sometimes it generates excel where the header and data content is mixed without any criteria

`public void Export()
        {
            string extension = "xlsx";
            var dialog = new SaveFileDialog();
            dialog.DefaultExt = extension;
            dialog.Filter = String.Format("{1} files (*.{0})|*.{0}|All files (*.*)|*.*", extension, "Excel");
            dialog.FilterIndex = 1;

            if (dialog.ShowDialog() == true)
            {
                using (var stream = dialog.OpenFile())
                {
                    var exportOptions = new GridViewDocumentExportOptions();
                    exportOptions.ShowColumnFooters = true;
                    exportOptions.ShowColumnHeaders = true;
                    exportOptions.ShowGroupFooters = true;

                    grdPag.ExportToXlsx(stream, exportOptions);
                }
            }
        }`

### Current behavior
_(optional)_
Provide additional information if the steps for reproducing the faulty behavior are not sufficient to describe the issue.

### Expected/desired behavior
the generated excel is a replica of the grid view

### Environment
Telerik.Windows.Controls.GridView.Export, Version=2015.1.401.40, Culture=neutral, PublicKeyToken=5803cfa389c90ce7
Browser: Chrome Version 97.0.4692.99 (Official Build) (64-bit)

**Comment by MilenaCh** [comment]
I'm not able to replicate the wrong behavior based on the provided information. Can you provide a runnable project that demonstrates the problem?
