### ISSUE TITLE
Incorrect popup height in DropDownList with LESS themes

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6688]
### Bug report
The height of the DropDownList popup is incorrect when using LESS themes.

Regression introduced with version 2022.1.119.

### Reproduction of the problem
1. Open this Dojo example - https://dojo.telerik.com/@martin.tabakov@progress.com/oMohisUF
2. Open the DropDownList
### Current behavior

The popup height is incorrect. 

### Expected/desired behavior
The popup height should be big enough to fit the list.

### Environment

* **Kendo UI version:** 2022.1.119
* **Browser:** [all]

**Comment by veselints** [comment]
Reopening this as there is an issue in Grouping scenario: 
https://kendobuild-windows.dev.progress.com/kendo-ui/combobox/grouping?autoRun=true&theme=default-main
