### ISSUE TITLE
Initializing a Kendo Button overrides the type attribute of the button tag 

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#6689]
### Bug report

Initializing a Kendo Button from a `<button type="submit></button>` overrides the type attribute. 
This is a regression introduced with v2022.1.119

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/uSIhEkUQ)
1. Inspect the generated markup

### Current behavior
```
<button id="primaryTextButton" type="submit">Primary Button</button>

        <script>
          $(document).ready(function () {
            $("#primaryTextButton").kendoButton({
              themeColor: "primary"
            });

          });
        </script>
```
The generated button has a `type="button"`
```
<button id="primaryTextButton" type="button" data-role="button" class="k-button k-button-md k-button-rectangle k-rounded-md k-button-solid k-button-solid-primary" role="button" aria-disabled="false" tabindex="0">
    <span class="k-button-text">Primary Button</span>
</button>
```

### Expected/desired behavior
Type property should  correctly set the button's type to 'submit'
[Dojo v2021.3.1207](https://dojo.telerik.com/@AleksandarEvangelatov/oMuluHEc)

### Environment

* **Kendo UI version:** 2022.1.119
* **Browser:** [all]

**Comment by IvanDanchev** [comment]
Also reported in Ticket ID: 1551642 for the Button MVC helper:
```
@Html.Kendo().Button().Name("foo2").Content("Hello2").HtmlAttributes(new { type="submit"})
```

**Comment by StoyanGoranov** [comment]
Also reported in Ticket ID: 1550739
