### ISSUE TITLE
numeric value filter not working in kendo grid if value is null

### ISSUE THREAD

**Issue by shriram0436** [telerik/kendo-ui-core#6700]
Steps to Reproduce:

open dojo link pasted below
try applying filter on age value and select Is **greater than equal to** and enter **0** and click on apply filter.
Observed: **filtered result shows null value**s in list

Expected: **null** values should not be shown

[https://dojo.telerik.com/eHekUmuN](url)

**Comment by ag-petrov** [comment]
I am afraid that this is not a bug. Generally the described filtering clause converts to a the following statement - Age >= 0. In the case of null >= 0 it returns true and this is why the value is displayed. It is a normal JavaScript behavior. If null values are not desired the filter should also contain a 'Is not null'
