### ISSUE TITLE
Expose the method Data(string handler) inside the Transport configuration for Telerik UI for ASP.NET Core version of the Editor's ImageBrowser

### ISSUE THREAD

**Issue by alestoya** [telerik/kendo-ui-core#6721]
### Bug report

The Telerik UI for ASP.NET Core version of the Editor's ImageBrowser [Transport](https://docs.telerik.com/aspnet-core/api/Kendo.Mvc.UI.Fluent/EditorFileBrowserSettingsBuilder#transportsystemactionkendomvcuifluenteditorfilebrowsertransportsettingsbuilder) CRUD methods does not support the .Data(string handler) in order to send additional parameters. This is supported for the available ImageBrowser CRUD methods outside the Transport configuration.

### Reproduction of the problem

Currently, it is not possible to pass additional data within the Transport configuration's CRUD methods when using the Telerik UI for ASP.NET Core HTML Helper. 

For example:

```
@(Html.Kendo().Editor()
    .Name("editor")
    .ImageBrowser(imageBrowser => imageBrowser
        .Transport(t => {
            t.Read(r=>r.Url("/Editor/ImageBrowser?handler=Read").Data("dataHandler"));
            t.Create(c => c.Url("/Editor/ImageBrowser?handler=Create").Data("dataHandler"));
            t.Destroy(d=>d.Url("/Editor/ImageBrowser?handler=Destroy").Data("dataHandler"));                
        })
        .Schema(schema => schema
        .Model(model => model.Fields(fields =>
            {
             fields.Name(name => name.Field("Name"));
             fields.Size(size => size.Field("Size"));
             fields.Type(type => type.Field("EntryType"));
            })
        ))
    )
)
```
In the Kendo UI for jQuery suite, we can pass additional parameters within the transport configuration as follows:

```
$("#editor").kendoEditor({
  imageBrowser: {
    transport: {
      read: {
        data: {
          id: 42,
          name: "John Doe"
        }
      }
    }
  }
});
```
### Current behavior

It is not possible to pass additional data within the Transport configuration when using the Telerik UI for ASP.NET Core HTML Helper.

### Expected/desired behavior
It should be possible to pass additional data within the Transport configuration when using the Telerik UI for ASP.NET Core HTML Helper.

### Environment

* **Kendo UI version:** 2022.1.119
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1565155

**Comment by eyupyusein** [comment]
Reported in: 1659493
