### ISSUE TITLE
Make drag to select functionality in the Selectable widget optional

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#6726]
Create a setting that will enable/disable the drag to select when Multiple Selection is enabled.

### Current behavior
The **Selectable** widget which has drag selection functionality is always turned on, but in some cases it conflicts with other logic like drag and drop.

### Expected/desired behavior
Create a setting to enable/disable drag-selection.

### Environment
* **Kendo UI version:** all

**Comment by ag-petrov** [comment]
This is now implemented - https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/selectable.dragtoselect
