### ISSUE TITLE
Button's text cannot be inserted through $scope in AngularJS

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6727]
### Bug report
The text of a Button a cannot be modified through $scope using AngularJS.

**Regression introduced with 2022.1.119**

### Reproduction of the problem
1. Open the Dojo example - https://dojo.telerik.com/@martin.tabakov@progress.com/uzEdoger/2
### Current behavior

The buttonName value is not displayed as the Button's text

### Expected/desired behavior
The buttonName value should be displayed as text for the Button.

### Environment

* **Kendo UI version:** 2022.1.119
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Closing this issue with Won't fix - [Kendo UI and AngularJS 1.x Support End of Life](https://www.telerik.com/blogs/kendo-ui-angularjs-1.x-support-end-life-plans) - R2 2022.

**Comment by veselints** [comment]
- [ ] Check whether all is in order with the implementation when using `setOptions()` on the Button.
