### ISSUE TITLE
IE - when the page is scrolled in Right To Left the popup window's position is wrong

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#673]
Ticket: 716410 
In IE 8 - when the page is scrolled in Right To Left the popup window's position is wrong

**Comment by ggkrustev** [comment]
For more details - telerik/kendo#1847

**Comment by ipeshev** [comment]
Looks like it is not working on IE10 [check here](http://dojo.telerik.com/@ipeshev/EKATA), also zomming might create problems too.

**Comment by tsvetomir** [comment]
Browser zooming is generally unsupported as it breaks a lot of the DOM APIs

**Comment by ggkrustev** [comment]
The demo didn't work, because it was missing a 'k-rtl' class from the BODY tag. Once this is added, the widget behaves as expected:
http://dojo.telerik.com/aCOhE

I will second @tsvetomir on the zooming issue. It could work, but in generally is not 100% supported right now.

There is no change in the code base.

I will close the issue as resolved. Please reopen it if I am missing something.
