### ISSUE TITLE
The PanelBar's dataBound event does not fire when loading data using the Items collection

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6730]
### Bug report
The dataBound event of the PanelBar does not fire when it is loaded with data through its **Items** configuration option. This is inconsistent with the behavior of the Kendo UI for jQuery PanelBar and the MVC TreeView, for which the event fires in the same scenario (local data).  

### Reproduction of the problem
Run the following example:

```
@(Html.Kendo().PanelBar()
    .Name("panelbar")
    .ExpandMode(PanelBarExpandMode.Single)
    .Events(events => events
        .DataBound("databound")
    )
    .Items(panelbar =>
    {
        panelbar.Add().Text("Root1")
            .Expanded(true)
            .Items(items =>
            {
                items.Add().Text("Sub-Item 2.1");
                items.Add().Text("Sub-Item 2.2");
            });

        panelbar.Add().Text("Root2")
            .Items(items =>
            {
                items.Add().Text("Sub-Item 2.1");
                items.Add().Text("Sub-Item 2.2");
            });
    })
)

<script>
    function databound(e) {
        alert('databound');
    }
</script>
```

### Current behavior
The dataBound event does not fire.

### Expected/desired behavior
The dataBound event fires.

### Environment

* **Kendo UI version:** 2022.1.119
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
The `dataBound` event is fired when the component is bound to a DataSource. When the `Items` configuration is used the component generates internally the required HTML markup that is later used for its initialization. Similar to the [Kendo UI for jQuery PanelBar in the same scenario](https://dojo.telerik.com/ovusEwIZ) - a dataBound event is not fired.
