### ISSUE TITLE
Kendo ColumnMenu sorted items is not persisted with hovering away from column menu

### ISSUE THREAD

**Issue by iorivera** [telerik/kendo-ui-core#6733]
### Bug report

The sorted kendo column menu items are not persisted when hovering away from the column pop up. They sort correctly when I click the button and hover over to the list. However when I hover away from the column list the it closes(as expected) but when I hover back on the items are no longer sorted. Its like if the Open function only gets called once. Is there another function I should  attach an event to?

I am using Kendo UI Jquery version 2021.2.511

I have posted below the sample code to initialize the kendo column button, and the custom sorting function.

Adding the columnMenu.sort propert does not allow for sorting.

`function ESNReviewShowColumnSelections() {
    var grid = $("#MyGrid").data("kendoGrid");

    $("#MyButton").kendoColumnMenu({
        filterable: false,
        sortable: false,
        dataSource: grid.dataSource,
        columns: true,
        owner: grid,
        init: function (e) {
            sortColumnMenu(e);
        },
        open: function (e) {
            sortColumnMenu(e);
        },
    });
}`

`function sortColumnMenu(e) {

    var list = e.container.find('.k-columns-item ul')
    var items = list.find('li');

    items.each(function (x, y) {
        $(y).removeClass('k-first k-last')
    })

    items.sort(function (a, b) {
        a = $(a);
        b = $(b);

        //var firstText = a.find('input[data-field]').attr('data-field');
        //var secondText = b.find('input[data-field]').attr('data-field');
        var firstText = a.find('input[data-field]').attr('title').toUpperCase();
        var secondText = b.find('input[data-field]').attr('title').toUpperCase();

        return ((firstText < secondText) ? -1 : ((firstText > secondText) ? 1 : 0));
    })

    items.first().addClass('k-first');
    items.last().addClass('k-last');

    items.each(function (y, x) {
        list.append($(x));
    })
}`

**Comment by ag-petrov** [comment]
With the current implementation and version that is being used in the mentioned project there is no need to manually sort the items. One can use [this ](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/columnmenu.columns.sort)property to apply sorting. Here is a dojo that demonstrates [this](https://dojo.telerik.com/uXateNUl/2).
