### ISSUE TITLE
Grid pageSize DropDown value is cut off in Less Material theme

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#6737]
### Bug report

The Grid's Pager pageSize DropDown selected value is not shown properly in the Less Material theme

### Reproduction of the problem
1. Run [this Demo](https://demos.telerik.com/kendo-ui/grid/pager-functionality?autoRun=true&theme=materialblack)

### Expected/desired behavior
The value of the DropDown should be shown as expected

### Environment

* **Kendo UI version:** 2022.1.119
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Fixed in 2022.1.301 - not reproducible on online demos anymore.
