### ISSUE TITLE
Paging in FileManager does not work correctly when in List View

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6739]
### Bug report

Paging in FileManager's List view does not work as expected. Paging in Grid View behaves as expected.

### Reproduction of the problem
1. Open this Dojo example - https://dojo.telerik.com/@sspasova/iGuYupaH
2. Open the Images folder

### Current behavior
 Only one page is displayed in the pager

### Expected/desired behavior
The pager should be updated to show the correct number of pages.

### Environment

* **Kendo UI version:** 2023.3.1114
* **Browser:** [all]

**Comment by gdenchevprog** [comment]
Raising priority: 1605982

**Comment by NikoPenev21** [comment]
Raising priority: 1633583

**Comment by iordanGrancharov** [comment]
"Not reproducible in the latest version"
