### ISSUE TITLE
[Grid] Grid takes 800000px in a flex parent with flex-shrink: 0

### ISSUE THREAD

**Issue by Jahrenski** [telerik/kendo-ui-core#6745]
### Reproduction of the problem
The kendo grid believes it needs 800,000px in width to display it's grid.
Parent flex with flex-shrink: 0

[https://dojo.telerik.com/EJanoNeW](https://dojo.telerik.com/EJanoNeW)

### Environment

* **Kendo UI version:** 2022.1.119
* **jQuery version:** 3.6.0
* **Browser:** [all]

**Comment by MilenaCh** [comment]
The observed behavior is expected, because when there is no width set to the Grid, it takes 100% of the parent's container width. See [this ](https://docs.telerik.com/kendo-ui/controls/data-management/grid/appearance/width)help article for more information.
