### ISSUE TITLE
MultiSelect tags are not removed after dataSource filtering when item(s) are selected after manual input.

### ISSUE THREAD

**Issue by jwkoller** [telerik/kendo-ui-core#6746]
### Bug report

MultiSelect tags are not removed after dataSource filtering when item(s) are selected after manual input.

### Reproduction of the problem
Dojo: http://dojo.telerik.com/otiNEYUD/2

Click on the first multiSelect, select "kitchen". Click on second multiSelect, type "ta", select "table". Go back to first multiSelect, click 'x' to removed "kitchen". The "table" tag on the second multiSelect is still visible, though no values are available. See console log to confirm no value is selected. Clicking on the 'x' of the still present table tag produces an error: "Uncaught TypeError: l.select(...).done is not a function"

### Current behavior
It should be noted that the intention is to have the available values of the second mulitSelect be dependent on selected values of the first (ignoring the initial load). If nothing is selected in the first, the second is intended to be empty (and not have any tags).

This issue only occurs if the user manually types to further filter the values down and selects an item. If no manual input occurs, tags are cleared as expected.

This is similar to an issue that was corrected previously when programmatically clearing all values of a multiSelect.
See: https://github.com/telerik/kendo-ui-core/issues/3788
In this case I don't want to clear all values, just the ones not available due to filtering of the data source. 

I've tried clearing all filters first with multiSelect.dataSource.filter({}), then passing in the new filter object, but the results are same.

### Expected/desired behavior
Tags should be removed when selected item(s) are no longer available due to dataSource filtering.

### Environment

* **Kendo UI version:** 2018.2.516 (also tried with 2022.1.119 with same results)
* **jQuery version:** 3.3.1
* **Browser:** [all]

**Comment by larshoeppner** [comment]
I can confirm this is still an issue.

The problem originates in the implementation of StaticList.select(), which can return a jQuery deferred (which is what the caller expects) but also return a plain array (which then causes the "is not a function" error for code that tries to use the .done() function).

This can be "fixed" fairly easily by returning the same deferred object in this line https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.list.js#L2149

Although the entire implementation should probably be reviewed, it seems rather pointless for the function to always return an already resolved deferred object unless it's fulfilling an external contract somewhere.

**Comment by ag-petrov** [comment]
This is not actually a bug but rather an implementation scenario. The correct approach here would be to re-apply the value after filtering is done so the multiselect can check whether it matches any of its items. Here is a modified dojo - https://dojo.telerik.com/otiNEYUD/5
