### ISSUE TITLE
SheetsBar scroll will prevent formula definition

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#6747]
### Bug report
When the SheetsBar contains more sheets pressing the SheetsBar left/right navigation arrow will close the formula editor.

### Reproduction of the problem
* Run the following Dojo: https://dojo.telerik.com/ETOsIzUP
* In cell A1 press "=" key (to open edit formula mode)
* Press scroll right button on SheetsBar (to scroll to the last Sheet)
* Formula editing mode stops and "A1" cell contains "=" char

### Expected/desired behavior
Formula editing mode should remain when pressing the scroll arrow.

### Environment
* **Kendo UI version:** 2022.1.119
* **Browser:** [all]

**Comment by nelito987** [comment]
Similar scenario:
- In the Dojo select 'Sheet number 2' sheet
- In a random cell press "=" key (to open edit formula mode)
- Select 'Sheet number 1'
- Click on the horizontal scrollbar on the bottom

The cell in the 'Sheet number 2' is not in editing mode and contains "`="
