### ISSUE TITLE
AMD loading broken once again [2022.1.301]

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#6752]
### Bug report

In the commercial distribution for jQuery (zip file, not npm package), a file like `kendo.colorpicker.js` has:

```
(function(f, define){
    define('colorpicker/colorselector',[ "../kendo.core" ], f);
})(function(){
```

but `kendo.core.js` cannot be found  in the parent directory as it is located in the same directory as `kendo.colorpicker.js`.

Many other files are concerned. Another example is `kendo.dataviz.diagram.js`:

```
(function(f, define){
    define('dataviz/diagram/utils',[ "../../kendo.core" ], f);
})(function(){
```

### Reproduction of the problem

Download `kendoui.for.jquery.2022.1.301.commercial-source.zip` and use an AMD loader

### Current behavior

Files cannot be found (again, see #6683).

### Expected/desired behavior

AMD loader should load file.

### Environment

Kendo UI version: 2022.1.301
jQuery version: 3.6.0
Browser: all

**Comment by Iankodj** [comment]
We replaced the AMD loader we use to compile the scripts with RequireJS and this might be the reason for this. Can you please share the SystemJS config you are using?

**Comment by jlchereau** [comment]
@Iankodj I use SystemJS v0.21.6 for component development and unit tests. I use webpack latest version for the entire solution. I had to replace `"../kendo.` and `"../../kendo.` with `"kendo.` in all kendo UI js files to fix loading both with SystemJS and webpack.

[system.config.zip](https://github.com/telerik/kendo-ui-core/files/8195852/system.config.zip)

**Comment by Iankodj** [comment]
Thanks for the update. Yes there is folder organization and later files are being optimized. The reason is the switch to RequireJS optimizer due to modernization. We will look into it and if possible tweak the compilation process.

**Comment by nelito987** [comment]
Reported in ticket ID: 1562499
