### ISSUE TITLE
Resize handlers are visible after an image is deleted in Editor

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6771]
### Bug report

The resize handlers in Editor are visible after an image has been deleted

### Reproduction of the problem
1. Open the Demo - https://demos.telerik.com/kendo-ui/editor/index
2. Select the image and delete it using 'Delete' button
3. Press Ctrl+Z and then delete the image again

### Current behavior
The image disappears, but the resize handlers remain visible

### Expected/desired behavior
The resize handlers should be hidden when an image is deleted.

### Workaround

```
<script>
var editor = $('#editor').kendoEditor().data('kendoEditor');

$(editor.body).keydown(function(e){
     if(e.key === "Delete"){    
          $(editor.body).find('.k-element-resize-handle-wrapper').hide()
     }
})
</script>
```

[Dojo](https://dojo.telerik.com/@NeliKondova/OxIXASOl/2)

### Environment

* **Kendo UI version:** 2022.1.301
* **Browser:** [all ]

**Comment by sspasova** [comment]
I am closing this as duplicated.
