### ISSUE TITLE
Build `all.js` failed : 

### ISSUE THREAD

**Issue by 625781186** [telerik/kendo-ui-core#6773]
Can you share a script about `gulp custom -c all `  , Thanks .

**Comment by 625781186** [comment]
![image](https://user-images.githubusercontent.com/30521429/159147447-3edeb38f-c28b-4949-b05e-b5e8a3a570eb.png)

I found docs about build all , but the gulpfils.js not handle it.

![image](https://user-images.githubusercontent.com/30521429/159147489-e75a1525-d54d-4384-a144-43d7e3e36baa.png)

**Comment by MilenaCh** [comment]
kendo-ui-core repo doesn't contain a combined kendo.all.js file and that's the reason for the error, you can execute 'npx gulp custom -c all' task only in the bundles, where kendo.all.js file exists.
