### ISSUE TITLE
Tooltip not rendering loading icon with AJAX content

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6777]
### Bug report

A Tooltip that fetches its content using AJAX request doesn't render a loading icon while waiting for the response.

**Regression introduced with version 2021.1.224**
Video to demonstrate the problem - http://somup.com/c3eTiwTNd9

Introduced while fixing: https://github.com/telerik/kendo-ui-core/issues/6148

### Reproduction of the problem

1. Open this Dojo example - https://dojo.telerik.com/@martin.tabakov@progress.com/onUlEMiT/5
2. Hover the images.

### Current behavior
Issue 1. No loading icon is rendered.
Issue 2. The Tooltip doesn't render until the response from the server arrives.

### Expected/desired behavior
The Tooltip should render immediately with a loading icon until the response from the server arrives.

### Environment

* **Kendo UI version:** 2022.1.301
* **Browser:** [all]

**Comment by veselints** [comment]
Test also: https://github.com/telerik/kendo-ui-core/issues/6148
