### ISSUE TITLE
DropDownList empty option label not properly styled in LESS themes

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6778]
### Bug report
Regression introduced in R1 2022. Reproducible only with the LESS themes.

### Reproduction of the problem
Dojo example: [https://dojo.telerik.com/UQOniRab](https://dojo.telerik.com/UQOniRab)

1. Click the DropDownList to open its dropdown

### Current behavior
The option label item's height is very small and no hover/select styles are applied to it. When the option label has some text, its height is ok, but again no hover/select styles are applied.

### Expected/desired behavior
The option label item's appearance should match that of the other items. 

### Environment

* **Kendo UI version:** 2022.1.301
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by veselints** [comment]
No longer reproducible with the latest release. Height of the DDL and selected/hover styles are applied to it:
https://dojo.telerik.com/UQOniRab/6
