### ISSUE TITLE
Editor is not displayed as expected on iPad in Safari desktop mode

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6791]
### Bug report

When the Editor is opened on iPad in desktop mode it seems like it has not been initialized. It is displayed as a standard textarea. 

### Reproduction of the problem
1. Open the Demos on ipad in desktop mode. - [https://demos.telerik.com/kendo-ui/editor/index](https://demos.telerik.com/kendo-ui/editor/index)

### Current behavior
The Editor is displayed as a standard textarea. There is no toolbar rendered. 
![image](https://user-images.githubusercontent.com/14364791/163324184-2e7c2a31-da60-4a2b-9d33-ab9407448491.png)

### Expected/desired behavior
The Editor should be rendered as on the other devices/browsers. 

### Environment

* **Kendo UI version:** 2022.1.412
* **Browser:** [all ]

**Comment by yanisslav** [comment]
Reported in ticket id: 1570431

**Comment by Dimitar-Goshev** [comment]
Reported in ticket id: 1573774

**Comment by nelito987** [comment]
Reported in ticket ID: 1576342
