### ISSUE TITLE
Grid throws error when model object name is a number

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#6827]
### Bug report

Kendo grid throws a JavaScript error when the model property name contains only numbers. Ticket ID - 1563890

### Reproduction of the problem
Run the following dojo - https://dojo.telerik.com/elegEmAf/2

### Current behavior
A JavaScript error occurs

### Expected/desired behavior
The data should be visualized correctly.

**Comment by sspasova** [comment]
I am closing this issue because it is no longer reproducible. Tested with Kendo UI 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/OpIHIKUp
