### ISSUE TITLE
Popup that has an AutoComplete closes when trying to filter

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6834]
### Bug report

In a Popup that has an AutoComplete, the Popup closes when you type in the AutoComplete input field.

**Regression introduced with 2022.1.301**

### Reproduction of the problem

1. Open this Dojo example - https://dojo.telerik.com/ajubEhox/12
2. Click the Open button
3. Type in the AutoComplete

### Current behavior

The Popup closes

### Expected/desired behavior
The Popup should remain open

### Environment

* **Kendo UI version:** 2022.2.510
* **Browser:** [all]

**Comment by veselints** [comment]
No longer reproducible with the latest release: https://dojo.telerik.com/ajubEhox/18

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible even with 2022.2.621 - https://dojo.telerik.com/@Dimitar-Goshev/iboxiviL
