### ISSUE TITLE
[Kendo Grid] use Column values can not set value and send value to server

### ISSUE THREAD

**Issue by vzsoft** [telerik/kendo-ui-core#6836]
### Bug report

i use Column Values and edit row but kendo grid can not set value and send value in server

### Reproduction of the problem

1- i use Column Values 
`columns : {{field:"UserType",title:"UserType","encoded":true,"values":[{value:0,text:"Guest"},{value:1,text:"Member"}] }`

2-edit column ("UserType") and select value

3-kendo grid can not set value and send to server

A Dojo sample for reproduction Column name "UserType" [https://dojo.telerik.com/APiGEFIr](https://dojo.telerik.com/APiGEFIr)

### Expected/desired behavior
column "UserType" set value in row and send value to server for save record

### Environment

* **Kendo UI version:** 2022.2.510
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by vzsoft** [comment]
> ### Bug report
> i use Column Values and edit row but kendo grid can not set value and send value in server
> 
> ### Reproduction of the problem
> 1- i use Column Values `columns : {{field:"UserType",title:"UserType","encoded":true,"values":[{value:0,text:"Guest"},{value:1,text:"Member"}] }`
> 
> 2-edit column ("UserType") and select value
> 
> 3-kendo grid can not set value and send to server
> 
> A Dojo sample for reproduction Column name "UserType" https://dojo.telerik.com/APiGEFIr
> 
> ### Expected/desired behavior
> column "UserType" set value in row and send value to server for save record
> 
> ### Environment
> * **Kendo UI version:** 2022.2.510
> * **jQuery version:** 1.12.4
> * **Browser:** [all]

**Comment by vzsoft** [comment]
> ### Bug report
> i use Column Values and edit row but kendo grid can not set value and send value in server
> 
> ### Reproduction of the problem
> 1- i use Column Values `columns : {{field:"UserType",title:"UserType","encoded":true,"values":[{value:0,text:"Guest"},{value:1,text:"Member"}] }`
> 
> 2-edit column ("UserType") and select value
> 
> 3-kendo grid can not set value and send to server
> 
> A Dojo sample for reproduction Column name "UserType" https://dojo.telerik.com/APiGEFIr
> 
> ### Expected/desired behavior
> column "UserType" set value in row and send value to server for save record
> 
> ### Environment
> * **Kendo UI version:** 2022.2.510
> * **jQuery version:** 1.12.4
> * **Browser:** [all]

**Comment by MilenaCh** [comment]
Hi, you can see how to add custom dropdown editor to Grid and apply the changes in batch editing in [this ](https://demos.telerik.com/kendo-ui/grid/editing-custom)demo.

**Comment by vzsoft** [comment]
Hi [Milena](https://github.com/MilenaCh)
I do not want custom dropdown editor
i need use this Ability in column values
`columns : {{field:"UserType",title:"UserType","encoded":true,"values":[{value:0,text:"Guest"},{value:1,text:"Member"}] }`

ty

**Comment by vzsoft** [comment]
> Hi, you can see how to add custom dropdown editor to Grid and apply the changes in batch editing scenario in [this ](https://demos.telerik.com/kendo-ui/grid/editing-custom)demo.



> Hi [Milena](https://github.com/MilenaCh) I do not want custom dropdown editor i need use this Ability in column values `columns : {{field:"UserType",title:"UserType","encoded":true,"values":[{value:0,text:"Guest"},{value:1,text:"Member"}] }`
> 
> ty

Hi [Milena](https://github.com/MilenaCh)
I do not want custom dropdown editor
i need use this Ability in column values
columns : {{field:"UserType",title:"UserType","encoded":true,"values":[{value:0,text:"Guest"},{value:1,text:"Member"}] }

ty

**Comment by MilenaCh** [comment]
UserType is not part of the datasource, which is used to bind the Grid in your example. So, there is not a clear relation between Title and UserType and Grid don't know how to apply UserType value in this context. You can see how to properly setup the datasource and use columns.values functionality in Grid's api [reference](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/columns.values).
