### ISSUE TITLE
Fastpass is finding the accessibility issues "ARIA attribute is not allowed: aria-expanded="false" with kendo multiselect

### ISSUE THREAD

**Issue by ArjunHcl** [telerik/kendo-ui-core#6843]
I have using the kendo-multiselect control in our application **Power App Portal** Version **9.4.3.40**, and we are trying to Be Fixing accessibility issues outlined by the FastPass tool. Fastpass is finding the accessibility issues "ARIA attribute is not allowed: aria-expanded="false" with kendo multiselect.

Kindly refer the attached doc.

![image](https://user-images.githubusercontent.com/105625694/168583594-554ef899-8fe3-4c8b-877e-615a088bd63a.png)
![image](https://user-images.githubusercontent.com/105625694/168583904-cf009573-0a12-447f-9db1-2e62ca565707.png)

**Comment by veselints** [comment]
@ArjunHcl I would recommend you to update the Kendo jQuery version used in your application to our latest release. We are constantly improving the accessibility of our components. As you can see on the [MultiSelect Basic usage demo](https://demos.telerik.com/kendo-ui/multiselect/index) the `textbox` element of the widget no longer has an `aria-expanded` attribute set.

**Comment by ArjunHcl** [comment]
@veselints Thanks for your response!!

I am unable to download the latest version of kendo control jQuery file, So could you please suggest from where we can download.

**Comment by veselints** [comment]
You should download the Kendo distribution from your [Telerik account}(https://www.telerik.com/account/). Note that you will need an active license to obtain the latest Kendo version. In case you have any further questions, please open a ticket in our [Support system](https://www.telerik.com/account/support-center/contact-us/technical-support?pid=949&q=&supcId=84d9f699-a526-c6b8-f754-68abacb50618&fbp=false).
