### ISSUE TITLE
Grid - ToolBar Template Documentation

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#6845]
### Bug report

The [Kendo UI Grid's Toolbar Template UI for ASP.NET MVC documentation](https://docs.telerik.com/aspnet-mvc/html-helpers/data-management/grid/toolbar#toolbar-template) displays an approach used for [UI for ASP.NET Core](https://docs.telerik.com/aspnet-core/html-helpers/data-management/grid/toolbar#toolbar-template).  The [ClientTemplate and ClientTemplateID](https://docs.telerik.com/aspnet-mvc/api/Kendo.Mvc.UI.Fluent/GridToolBarCommandFactory#kendomvcuifluentgridtoolbarcommandfactory) are not available for UI for ASP.NET MVC.

### Reproduction of the problem
Please try the approach used in the documentation.  It is not available for UI for ASP.NET MVC.

### Expected/desired behavior
Either include the approach for UI for ASP.NET MVC, or modify the documentation.

### Environment

* **Kendo UI version:** 2022.2.510
* **jQuery version:** 3.6
* **Browser:** all

**Comment by StoyanGoranov** [comment]
This issue is resolved with the commits related to this issue: https://github.com/telerik/kendo-ui-core/issues/7469
