### ISSUE TITLE
Maximum call stack error is thrown when ToolBar is initialized in kendo.mobile.Application

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6846]
### Bug report

When ToolBar with buttons is initialized in _kendo.mobile.Application_ an error _Maximum call stack size exceeded_ is thrown in the browser console

### Reproduction of the problem
1. Open the [Dojo example](https://dojo.telerik.com/@NeliKondova/OZawujok). 

### Current behavior
Currently,  _Maximum call stack size exceeded_ is thrown in the browser console

### Expected/desired behavior
There should be no errors in the browser console when initializing a Toolbar in the mobile Application. - [Working Dojo](https://dojo.telerik.com/@NeliKondova/eneMakic)

### Environment

* **Kendo UI version:** 2022.2.510
* **Browser:** [all ]

**Comment by veselints** [comment]
@Iankodj can you also review the above within the current ToolBar effort?

**Comment by nelito987** [comment]
Possible workaround: 
```
 kendo.html.HTMLBase.fn._initOptions = function(options) {
          this.options = $.extend({}, this.options, options);
        }
```
[Dojo](https://dojo.telerik.com/@NeliKondova/ELUPuTEN)
