### ISSUE TITLE
DropDownList.toggle() method TypeScript declaration

### ISSUE THREAD

**Issue by Rus7am** [telerik/kendo-ui-core#6849]
### Bug report

`DropDownList.toggle()` method [TypeScript declaration](https://github.com/telerik/kendo-ui-core/blob/master/typescript/kendo.all.d.ts#L4120) requires a parameter:

` 
toggle(toggle: boolean): void;
`

but it's not required in the [documentation](https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist/methods/toggle) and in reality.

### Environment

* **Kendo UI version:** 2022.1.301
* **jQuery version:** 3.6.0
* **Browser:** [ Edge 101.0.1210.47 (Official build) (64-bit) ]

**Comment by ag-petrov** [comment]
Actually a parameter can be passed to the function and it is optional. We should update our docs and definitions to reflect this. If a boolean value is passed to the method determine whether to open/close the popup. For example in the case where true is passed the popup will always be opened.
