### ISSUE TITLE
When the user clicks between date and time expanding icons CSS class is removed

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#685]
There is a problem with the Date/Time picker where when you select the date, then immediately select the time, without clicking out of the element, the classes of k-state-border-up/down are removed from the elements, which is incorrect behavior. 

screencast: http://screencast.com/t/9bTFMoLgt
ticket: 822010

**Comment by KirilNN** [comment]
In order to fix this issue the anchor needs to be aware of other elements(popups) attached to the same element. Currently we do not have a solution for the above issue, but we remain open for any suggestions.
