### ISSUE TITLE
KendoLicensing.setScriptKey not working in typescript files

### ISSUE THREAD

**Issue by jvalkeejarvi** [telerik/kendo-ui-core#6850]
### Bug report

With `@progress/kendo-ui` version 2022.2.510 licensing is required. However there are no typings for KendoLicensing.setScriptKey so it cannot be used in typescript file.

### Current behavior
TypeScript compilation fails because there are no typings for KendoLicensing.

### Expected/desired behavior
Setting script key in typescript file works.

### Environment

* **Kendo UI version:** 202.r.ddd
* **jQuery version:** 3.5.1
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
@jvalkeejarvi Thank you for this report. We have updated our TypeScript definitions and the fix will be included in our next release:
https://github.com/telerik/kendo-ui-core/commit/bc9f32b4308d0d5c984b45d1e3cd4e9d1af45804
