### ISSUE TITLE
RangeSlider doesn't rerender on resize 

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-ui-core#6852]
RangeSlider is responsive, however only when first render time. If you resize parent element, its not re-rendered correctly:

- i am not sure but i think it worked correctly in previous versions?

https://stackblitz.com/edit/angular-7j7hu2?file=src%2Fapp%2Fapp.component.ts

https://user-images.githubusercontent.com/10418323/169268242-1c5b78af-723d-46b7-bb44-f9fb7cd10e78.mp4

If its not considered as a bug, is there a way how to rerender it manually? (render() funkction) ? 

Or we have to attach resizeObserver on the parent and do some kind of hacks with ngIf -> setTimeout(ngIf)  ?

**Comment by Dimitar-Goshev** [comment]
@montella1507 
Thank you for your feedback. To avoid sizing issues on browser window resizing, the RangeSlider [resize() method](https://docs.telerik.com/kendo-ui/api/javascript/ui/rangeslider/methods/resize) may be used to resize the component on window resize event - [Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/EZOjANAk).

**Comment by montella1507** [comment]
Helo @Dimitar-Goshev thanks for the answer. Thats my bad i put the Issue in the wrong repository, wanted to report that to the kendo-angular.
