### ISSUE TITLE
In mobile application Button is not focused after click

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6854]
### Bug report

In mobile apps when a Button is clicked it is not getting focused. This leads to the focus not being removed from the previously focused element.

### Reproduction of the problem
1. Open the [Dojo](https://dojo.telerik.com/@NeliKondova/iWewuFEg)
2. Type something in the input and click the Button.

### Current behavior
The returned value of the TextBox is null as the Button is not focused and the TextBox is not focused out.

### Expected/desired behavior
The Button should be focused when it is clicked, thus the TextBox to be focused out.

### Environment

* **Kendo UI version:** 2022.2.510
* **Browser:** [all ]

**Comment by ag-petrov** [comment]
Closing this as the mobile suite is now depricated.
