### ISSUE TITLE
The overflow menu of the Toolbar hides on specific window size 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-ui-core#6860]
### Bug report
The overflow menu of the Toolbar gets hidden below one of its tools. This issue is replicable in scenarios with a lot of tools or when a Toolbar is opened on a small screen. 

### Reproduction of the problem
1. Open [this Dojo example](https://dojo.telerik.com/ICEPoQuY/2)
2. Start resizing the window in which the Toolbar is loaded in a way its tools start to move in the overflow menu

### Current behavior
At some point, the last visible Toolbar element is hiding the icon of the overflow menu.
<img width="398" alt="image" src="https://user-images.githubusercontent.com/41293735/170236541-62f20700-4511-49f9-9c19-710337a70c5d.png">

### Expected/desired behavior
The icon of the overflow menu should be constantly visible, no matter the number of elements in the Toolbar or the size of the screen. 
![image](https://user-images.githubusercontent.com/41293735/170236626-7c3ab871-08ce-4553-8804-6a303e18d1ba.png)

### Environment

* **Kendo UI version:** 2022.2.510
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by PekoPPT** [comment]
The issue is replicable **only** in the SASS themes. In the SASS themes, there is a CSS gap set for the Toolbar items.

**Comment by Iankodj** [comment]
Addressed in https://github.com/telerik/kendo/pull/15463
