### ISSUE TITLE
A custom class cannot be applied to the Breadcrumb through the HtmlAttributes configuration

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6882]
### Reproduction of the problem

1. Set a class in the Breadcrumb's HtmlAttributes, e.g.,

```
.HtmlAttributes(new { @class = "test" })
```
2. Inspect the rendering of the component.

### Current behavior
The custom class is not applied to the Breadcrumb.

### Expected/desired behavior
The custom class is applied to the Breadcrumb along with the pre-defined Kendo classes.

### Environment

* **Kendo UI version:** 2022.2.510
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by eyupyusein** [comment]
I have tested this and it seems to work as expected, at least with the latest master:
    `@(Html.Kendo().Breadcrumb()
            .Name("breadcrumb")
            .HtmlAttributes(new { @class = "test" })`

Result:
![image](https://user-images.githubusercontent.com/11816856/173678485-599a4628-6ab0-4cfd-ad3a-f1f51ef83c3d.png)
