### ISSUE TITLE
The TextBox TagHelper does not render the maxlength and placeholder attributes

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#6884]
### Bug report

The TextBox TagHelper does not render the maxlength and placeholder attributes when set via data annotations.

### Reproduction of the problem
For a model property defined the following way
```
[Display(Name = "Example", Prompt = "Example Prompt")]
[StringLength(maximumLength : 5, MinimumLength = 1, ErrorMessage = "Must be between 1 and 5")]
public string Example { get ; set ; }
```
the TextBox TagHelper generetes
```
<input
  class="form-control k-input-inner"
  data-val="true"
  data-val-length="Must be between 1 and 5"
  data-val-length-max="5"
  data-val-length-min="1"
  id="Example"
  name="Example"
  value=""
  data-role="textbox"
  style="width: 100%;"
  aria-disabled="false"
  autocomplete="off"
  aria-invalid="true"
  aria-describedby="Example_validationMessage">
```

when the default ASP.NET Core TagHelper generates markup containing the maxlength and placeholder attributes:
```
<input
  class="form-control k-invalid"
  type="text"
  data-val="true"
  data-val-length="Must be between 1 and 5"
  data-val-length-max="5"
  data-val-length-min="1"
  id="Example"
  maxlength="5"
  name="Example"
  placeholder="Example Prompt"
  value=""
  aria-invalid="true"
  aria-describedby="Example_validationMessage">
```

### Expected/desired behavior
The maxlength and placeholder attributes are set to the generated input element.

### Environment

* **Kendo UI version:** 2022.2.510
* **Browser:** [all]

**Comment by lmastin** [comment]
Hi Aleksandar!

Just to confirm, there are two possible ways in which the _maxlength_ attribute might be generated when data annotations are present:

- If the [MaxLength] data annotation is present (which was just fixed in time for the next release);
- If the [StringLength] data annotation is present and has it's _maximumLength_ property set.

Please let me know if you need any additional details!
