### ISSUE TITLE
Cannot read property 'firstChild' of undefined error thrown in Scheduler Month view when resources datasource is empty

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6886]
### Bug report

When the dataSource for the resources is empty and the Month view is selected the 'Cannot read property 'firstChild' of undefined error is thrown in Scheduler.

### Reproduction of the problem
1. Open the Dojo and observe the browser console [https://dojo.telerik.com/@NeliKondova/IvIJeLAw](https://dojo.telerik.com/@NeliKondova/IvIJeLAw)

### Current behavior
'Cannot read property 'firstChild' of undefined error is thrown in Scheduler when the Month view is selected.

### Expected/desired behavior
No error should be thrown with an empty resources dataSource in Scheduler.

**The issue is a regression starting with 2020 R1 (2020.1.114) release**

### Environment

* **Kendo UI version:** 2022.2.510
* **Browser:** [all  ]

**Comment by Dimitar-Goshev** [comment]
Similar fixed issue, but with autoBind: false - https://github.com/telerik/kendo-ui-core/issues/5806

**Comment by veselints** [comment]
Having a resource with no items (and no remote endpoints configured) is rather a non valid configuration for the Scheduler. We will fix the current error, but such a configuration of the widget may lead to other issues.
