### ISSUE TITLE
After using setOptions the HTML structure of Grids column header is different.

### ISSUE THREAD

**Issue by yanisslav** [telerik/kendo-ui-core#6888]
### Bug report
After using setOptions() the HTML structure of Grids column header is different.

### Reproduction of the problem

In the following demo: 
https://demos.telerik.com/aspnet-mvc/grid/persist-state

1. Inspect the HTML structure of a column header.
2. Click the Load State button.

### Current behavior

When the button is clicked, setOptions() called for the Grid and the structure of the column headers is now different. 

### Expected/desired behavior

When setOpitons() is called with no options that may affect the headers the HTML structure of the column headers should be the same. 

### Environment

* **Kendo UI version:** 2022.2.510
* **Browser:** [all]

**Comment by gyankov** [comment]
The only difference I found between the two states is a title on the header cells. Which is an incorrect behavior in the client side component. I've logged an issue to address that https://github.com/telerik/kendo-ui-core/issues/7585.
