### ISSUE TITLE
DropDownList popup does not close when clicking on the arrow icon

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#6891]
### Bug report
When a DropDownList is open, clicking on the arrow icon closes its popup and immediately opens it again. 

### Reproduction of the problem
1. Run the following Dojo - https://dojo.telerik.com/@Dimitar-Goshev/IRIxOkIj
2. Click on the arrow icon to open the popup - the popup becomes visible.
3. Click on the arrow icon once again.

### Current behavior
The popup closes and opens once again ([screencast](https://www.screencast.com/t/FfRhrCVJmyj)) . The issue does not appear every time.

### Expected/desired behavior
The popup should close if it is opened, and should open if it is closed. The behavior should be consistent as when clicking on the DropDownList itself.
The expected behavior is reproducible with 2021.3.1207 - https://dojo.telerik.com/@Dimitar-Goshev/ALuCOPat

**Regression since: 2022 R1 2022.1.119**

### Environment
* **Kendo UI version:** 2022.2.802
* **Browser:** [all]

**Comment by martintabakov** [comment]
Also reported in #1568904

**Comment by veselints** [comment]
Could no longer reproduce the bug.

**Comment by Dimitar-Goshev** [comment]
@veselints The issue's description was ambiguous. I updated it and the steps and the issue is reproducible.
