### ISSUE TITLE
Missing files when generating custom script file for CircularProgressBar through Custom Download Tool

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6895]
### Bug report

Files are missing when trying to generate a script file for CircularProgressBar only through the Custom Download Tool.

### Reproduction of the problem

1. Open the custom download tool - https://www.telerik.com/download/custom-download
2. Select CircularProgressBar

### Current behavior
There are missing files in the exported custom file.

### Expected/desired behavior
All necessary files should be included in the custom script file.

### Environment

* **Kendo UI version:** 2022.2.621
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Fixed with https://github.com/telerik/kendo/commit/420421a1f9945290479aec89bf170b6c73d730c9
