### ISSUE TITLE
Adding unicode "\u00a0" in Gantt Timeline cells results in additional visible character on pages with  charset=iso-8859-1

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#6897]
### Bug report
Adding unicode "\u00a0" in Gantt Timeline cells results in additional visible character on pages with  charset=iso-8859-1

### Reproduction of the problem
* Run the following Dojo in Full screen: https://dojo.telerik.com/OBiKOxUH

### Expected/desired behavior
No visible character should be present in the cells of the Timeline. We may have to use "&nbsp;" instead of "\u00a0"

### Environment

* **Kendo UI version:** 2022.2.513
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Seems to be working fine. Closing this one.
