### ISSUE TITLE
RadioGroupFor does not work correctly when used as an Editor for the Grid

### ISSUE THREAD

**Issue by yanisslav** [telerik/kendo-ui-core#6909]
### Bug report

When a RadioGroupFor is used as an editor template for the Grid, the property of the model is not bound to the component. The data-bind attribute is missing in the rendered HTML.

### Reproduction of the problem

In the attached project, try to edit a record from the Grid. The property RGVal is not bound to the RadioGroup editor.
Adding the following configuration fixes the behavior:
.HtmlAttributes(new { data_bind="value:RGVal"})

### Current behavior

The property is not bound to the editor.

### Expected/desired behavior

The property should be bound to the editor.

### Environment

* **Kendo UI version:** 2022.2.510
* **Browser:** [all]

[TelerikMvcApp18.zip](https://github.com/telerik/kendo-ui-core/files/9054514/TelerikMvcApp18.zip)

**Comment by yanisslav** [comment]
Also reported in 1575192

**Comment by antonmironovv** [comment]
Reported in 1596825
