### ISSUE TITLE
Broken Link {Grid - FAQ}

### ISSUE THREAD

**Issue by JoshuaGarrison27** [telerik/kendo-ui-core#691]
Website Perm URL: http://docs.telerik.com/kendo-ui/aspnet-mvc/helpers/grid/faq#how-do-i-create-a-custom-popup-editor

The "Custom Popup Editor" link is broken

**Comment by KirilNN** [comment]
@JoshuaGarrison27 

Thanks for reporting this!

**Comment by JoshuaGarrison27** [comment]
You're welcome! Keep up the great work.
