### ISSUE TITLE
ColorPicker incorrect styles in a Mobile Application

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#6914]
### Bug report

The slider in the ColorPicker popup, when used in Mobile Application, is not styled correctly. 

### Reproduction of the problem

1. Open this example - https://dojo.telerik.com/EfiQUGad/10
2. Open the ColorPicker.

### Current behavior

The slider is not styled.

### Expected/desired behavior
The slider in the popup should be displayed appropriately.

### Environment

* **Kendo UI version:** 2022.2.621
* **Browser:** [all]

**Comment by magdalenaan** [comment]
The Kendo UI Mobile LESS themes are [officially deprecated](https://www.telerik.com/blogs/future-plans-telerik-kendo-ui-less-themes#what-about-the-kendo-ui-mobile-less-themes) with R1 2022.
