### ISSUE TITLE
Kendo UI break on angular 14 version?

### ISSUE THREAD

**Issue by kapilSoni101** [telerik/kendo-ui-core#6915]
### Bug report
Kendo UI break on chrome
Hi Team,
I have implemented kendo-UI in the angular 14 but kendo UI totally break. can you please let me know why i got this issue.check below attached screenshot for reference

### Current behavior
Kendo UI break on chrome

### Expected/desired behavior
UI working properly

### Environment

* **Kendo UI version:** 4.1.1
* **jQuery version:** 3.4.1
* **Browser:**  Chrome and firefox

![image](https://user-images.githubusercontent.com/26578635/177992882-f4a432c6-2a8d-47ae-894f-be9f2d5f2dce.png)

**Comment by Dimitar-Goshev** [comment]
@kapilSoni101 Judging by the Kendo UI version specified in the issue - 4.1.1, it is not related to Kendo UI for jQuery. If you are using Kendo UI for Angular, please log this issue in its issue tracker repository - https://github.com/telerik/kendo-angular or open a support ticket with more details about the issue.

**Comment by kapilSoni101** [comment]
@Dimitar-Goshev - yes sir I am using kendo UI for angular and thanks for the update
