### ISSUE TITLE
Blurred PDFViewer text

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#6923]
### Bug report
Text of PDF documents in PDFViewer may be blurred.

### Reproduction of the problem
1. Go to [PDFViewer demo](https://demos.telerik.com/kendo-ui/pdfviewer/index) or run the following [Dojo snippet](https://dojo.telerik.com/@iankodj/AwaFUjOj)

### Current behavior
Text is blurred, most visible on small letters.

### Expected/desired behavior
Text is not blurred.

### Environment
* **Kendo UI version:** 2022.2.621
* **Browser:** [Chrome 103 | Firefox 102| Edge 102]

**Comment by Iankodj** [comment]
Suggested fix: 


>    the canvas content is upscaled since we have more than physical 1 pixel per CSS pixel
>   the fix is to render a larger canvas, but keep it's layout dimensions the same
>    canvas.width should be element.offsetWidth * window.devicePixelRatio
>   same for height
