### ISSUE TITLE
Widget does not allow to select last items in the popup on mobile device when filtering is enabled

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#693]
### Description
Widget does not calculate the popup height on a mobile device when filtering is enabled. This results in inability to select the last few items.

Repro steps:
1. Open http://demos.telerik.com/kendo-ui/dropdownlist/serverfiltering
2. Open the popup and filter to the last item
3. Notice how it cannot be clicked

Reported in TicketID: 922922

**Comment by ggkrustev** [comment]
Probably related to #394

**Comment by ggkrustev** [comment]
The real solution is to change current rendering. We will need to wrap the UL element (the one that holds the items) and make that element scrollable. This means that the [list](http://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist#fields-list) element will not be scrollable anymore.
Because of the need of such breaking change, we will postpone the fix for Q2 2015 release.

**Comment by valchev** [comment]
Closed with 87cfc66
