### ISSUE TITLE
The Grid's row reorder hint does not work properly in a smaller column

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-ui-core#6932]
### Bug report

The row reordering functionality does not work correctly when the draggable column has a small width.

### Reproduction of the problem

https://dojo.telerik.com/@sspasova/ekariwuV

Open the Dojo and try to reorder a row. The icon inside the hint will keep changing and in some cases, you won't be able to drop the row to the expected position.

If you move the hint a bit to the right(towards the next column) this behavior disappears.

### Current behavior

The reorder hint shimmers and in some cases does not allow for reordering. This occurs when the column width is small(30px in the example).

### Expected/desired behavior

Reorder should work as expected, regardless of the column width.

### Environment

* **Kendo UI version:** 2023.3.1114
* **jQuery version:** 3.4.1
* **Browser:** [all]

**Comment by gdenchevprog** [comment]
Also reported in 1594695. Increasing priority.

**Comment by nelito987** [comment]
Reported in ticket ID: 1603244

**Comment by kjartanvalur** [comment]
Also reported in ticket Ticket 1631132

**Comment by alestoya** [comment]
Reported 1656516
