### ISSUE TITLE
Scheduler scrolls top after editing an event

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#6946]
### Bug report
Regression introduced in R1 2022 SP1. 

### Reproduction of the problem
Dojo example: [https://dojo.telerik.com/akaJaXin/4](https://dojo.telerik.com/akaJaXin/4)

1. Scroll down the Scheduler and add a new event. 
2. Double-click the newly added event and after the editor shows up, click on the "Cancel" or on the "Delete" button.

### Current behavior
The popup closes and the Scheduler automatically scrolls to the top of the view. 

### Expected/desired behavior
The scroll position should remain. The current behavior is not user friendly, because if the user has multiple events with similar start times to remove, they will have to scroll back down every time they delete an event. 

### Environment

* **Kendo UI version:** 2022.2.621
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by veselints** [comment]
As a temporary workaround for the bug, one can turn on the _selectable_ feature in the Scheduler that would keep the focus on the selected event/slot: `selectable: true,`.
