### ISSUE TITLE
Toolbar's SplitButton redirects twice if "target":"_blank" attribute is set

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#6950]
### Bug report

The relevant attributes are applied to the list item instead of the anchor tag of the Toolbar's dropdown. 

This is a regression bug introduced in version 2022.2.621.

### Reproduction of the problem
1. Run [this Dojo](https://dojo.telerik.com/@Stoyan/EkUFetAg)
2. Expand the SplitButton and redirect

### Current behavior
Both the current and the newly open tab redirect to the link

### Expected/desired behavior
Only the newly open tab should redirect

### Environment

* **Kendo UI version:** 2022.2.621

**Comment by mihaela-lukanova** [comment]
Reported in Ticket Id: 1581640
