### ISSUE TITLE
The background-color of a selected Grid row disappears in the LESS themes

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-ui-core#6972]
**Describe the bug**

When using the LESS themes, the row selection feature doesn't behave as expected. The background-color of the selected row disappears as soon as the row stops being hovered.

**To reproduce**

The problem can be observed in the [Grid's selection demo](https://demos.telerik.com/kendo-ui/grid/selection?autoRun=true&theme=bootstrap). Just choose any of the LESS themes(tested with bootstrap and default) and click on one of the rows to select it.

Move the cursor outside of the row and the background-color disappears.
Move the cursor back to the row and the background-color reappears.

**Expected behavior**

The background-color should stay as long as the row is selected, not just when the row is hovered.

**Screenshots**

Select the row:
![image](https://user-images.githubusercontent.com/70957719/183406467-db205f73-6a8c-4448-8d78-30c9dbb1ae49.png)

Move the cursor out:
![image](https://user-images.githubusercontent.com/70957719/183406510-78e7f745-542c-47f2-985f-9c6526f89679.png)

Move the cursor in:
![image](https://user-images.githubusercontent.com/70957719/183406561-baa8816e-c2b8-492d-9a7d-74b1889e4696.png)

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery (observed in jQuery)

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1575837

**Comment by ag-petrov** [comment]
https://github.com/telerik/kendo/pull/15967 PR with the fix
