### ISSUE TITLE
State prefix must be removed from CSS state classes in PHP and JSP wrappers and demos

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#6995]
### Bug report
With version 2022.2.802 we have removed the state prefix from state CSS classes in Kendo jQuery. The same prefix must also be removed from JSP and PHP wrappers as those relay on the old classes.

### Expected/desired behavior
No `state` prefix should be present in the wrappers.

### Environment
* **Kendo UI version:** 2022.2.802
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by vafadarnaghi** [comment]
Hi,

Is this bug still actual in new releases?

Thank you!

**Comment by Dimitar-Goshev** [comment]
Hi, the issue is still present in version 2022.3.1109

**Comment by Dimitar-Goshev** [comment]
@vafadarnaghi The issue will be fixed with our next release later in January.
