### ISSUE TITLE
Jquery Kendo Grid Accesibility error from Wave tool: Empty table header

### ISSUE THREAD

**Issue by pacoweb** [telerik/kendo-ui-core#6996]
### Reproduction of the problem

The WAVE tool warns of an error when you use a Kendo Grid using Filterable (mode Row) and Editable (InLine).
The error is **Empty table header** (on the filter header of the command column because is empty)

To reproduce this behavior:

1. Install the extension WAVE Evaluation Tool (https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) in Chrome
2. Open this url http://dojo.telerik.com/uRAKUbUn/2
3. Use the option **FullScreen**
4. Activate wave tool
5. Check the errors list

![image](https://user-images.githubusercontent.com/1198633/186131563-5b7470b5-8c9a-4470-8c5c-a43553a34fc5.png)

![image](https://user-images.githubusercontent.com/1198633/186131381-694f5254-83ca-4f53-bb30-8c45fe55da06.png)

### Expected/desired behavior
Maybe a property to set the text in that "filter" header

### Environment

* **Kendo UI version:** 2022.2.621 and 2022.2.802
* **jQuery version:** 3.6.0
* **Browser:** [all]

**Comment by veselints** [comment]
@pacoweb thank you for your report!

This issue has already been fixed. The fix will be shipped with the upcoming R3 2022 release scheduled for mid September.

Fixed with: https://github.com/telerik/kendo/issues/15303

**Comment by pacoweb** [comment]
Thanks!
