### ISSUE TITLE
Turkish character problem in Combobox filtering

### ISSUE THREAD

**Issue by devranerogul** [telerik/kendo-ui-core#7007]
### Bug report
[https://dojo.telerik.com/uBElIMah](https://dojo.telerik.com/uBElIMah
)

This issue is still exists   **accentFoldingFiltering**  property set to **tr-TR** as mentioned in https://github.com/telerik/kendo-ui-core/issues/3268 and https://docs.telerik.com/kendo-ui/api/javascript/data/datasource/configuration/accentfoldingfiltering

### Reproduction of the problem

Type : DEMİR 

### Current behavior

Combobox shows one result : "DEMİR"

### Expected/desired behavior

Result should be "DEMİR" and "Küçükdemirci" as they both contains "demir". 

### Environment

* **Kendo UI version:** 2022.2.802
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
@devranerogul 
Note that **accentFoldingFiltering** is a property of the **DataSource**, not the ComboBox, and this is why it does nothing on the reproduction Dojo snippet.
The following [Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/ocEhiQAZ) shows the correct setup of datasource with accentFoldingFiltering and typing DEMİR returns both "DEMİR" and "Küçükdemirci" .
