### ISSUE TITLE
All Date Inputs - Days of the week labels - broken styles

### ISSUE THREAD

**Issue by krzysztof-raciniewski** [telerik/kendo-ui-core#7011]
### Reproduction of the problem
1. Go to Kenod UI for Angular documentation > Date Inputs > Date Picker > Overview
2. Select Date Inputs > Date Picker > Overview
3. Click on the calendar icon

### Current behavior
![image](https://user-images.githubusercontent.com/7010367/187913365-0c8f9a13-e946-4fe8-867b-7fdbd1ffa26a.png)

There are no spaces in the day names

### Expected/desired behavior
Day names should be aligned

### Environment

* **Kendo UI version:** 
```
    "@progress/kendo-angular-buttons": "8.0.0",
    "@progress/kendo-angular-common": "3.1.0",
    "@progress/kendo-angular-dateinputs": "7.1.0",
    "@progress/kendo-angular-dialog": "7.1.2",
    "@progress/kendo-angular-dropdowns": "7.0.3",
    "@progress/kendo-angular-editor": "4.1.7",
    "@progress/kendo-angular-excel-export": "5.0.1",
    "@progress/kendo-angular-grid": "7.2.4",
    "@progress/kendo-angular-inputs": "9.0.4",
    "@progress/kendo-angular-intl": "4.1.0",
    "@progress/kendo-angular-l10n": "4.0.0",
    "@progress/kendo-angular-label": "4.0.1",
    "@progress/kendo-angular-layout": "7.1.1",
    "@progress/kendo-angular-menu": "4.0.1",
    "@progress/kendo-angular-messages": "1.35.0",
    "@progress/kendo-angular-pdf-export": "4.0.0",
    "@progress/kendo-angular-popup": "5.0.0",
    "@progress/kendo-angular-scheduler": "4.3.0",
    "@progress/kendo-angular-toolbar": "6.0.3",
    "@progress/kendo-angular-treelist": "5.0.4",
    "@progress/kendo-angular-treeview": "7.1.0",
    "@progress/kendo-data-query": "1.6.0",
    "@progress/kendo-drawing": "1.17.0",
    "@progress/kendo-licensing": "1.2.2",
    "@progress/kendo-recurrence": "1.0.3",
    "@progress/kendo-theme-bootstrap": "5.6.0",
```

* **jQuery version:** 3.6.0
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Hi @krzysztof-raciniewski 
Thank you for your feedback. This repository is for Kendo UI for jQuery.
Please look for the issue in the Kendo UI for Angular repository - https://github.com/telerik/kendo-angular/issues and log it there, if not present.

**Comment by krzysztof-raciniewski** [comment]
Hello @Dimitar-Goshev 
It's my mistake, sorry.

I moved this issue to correct repository: https://github.com/telerik/kendo-angular/issues/3759.
You can close this issue. Thank you.
