### ISSUE TITLE
Upload popup is not opened if you click near the button's border

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7013]
### Bug report

The Upload popup is not opened if you click near the button's border

### Reproduction of the problem

1. Open this Dojo example - https://dojo.telerik.com/uSedeSUq/7
2. Click the button as close to the border as possible

### Current behavior

The select popup does not open

### Expected/desired behavior

The select popup should open

### Environment

* **Kendo UI version:** 2022.2.802
* **Browser:** [all]

**Comment by sspasova** [comment]
I am closing this issue because it is no longer reproducible using Kendo Ui 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/IkuFeCEW
