### ISSUE TITLE
Reordering column in TreeList throws an error when there is a Grid on the page

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7014]
### Bug report

When there are Grid and Gantt on the same page and a column in the Gantt has reordered an error in the console is thrown:
_kendo.all.js:133531 Uncaught TypeError: Cannot read properties of undefined (reading 'lockable')_

### Reproduction of the problem
1. Open the [Dojo](https://dojo.telerik.com/@NeliKondova/EfUNUNIG). There is no relation in the configuration between the Grid and the Gantt widgets. 
2. Reorder the columns in Gantt

### Current behavior
The following error is thrown:
_kendo.all.js:133531 Uncaught TypeError: Cannot read properties of undefined (reading 'lockable')_

### Expected/desired behavior
There should be no error in the console when reordering columns in Gantt, even if there is a Grid on the page.

### Environment

* **Kendo UI version:** 2022.2.802
* **Browser:** [all]

**Comment by veselints** [comment]
The bug is no longer reproducible with R3 2022 SP1 (2022.3.1109)
