### ISSUE TITLE
Wrong dropdown width when set through list.width

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7031]
### Bug report

When the width of the DropDownList is set using the list.width() and the DropDownList gets opened there is a slight delay in expanding the popup width.

### Reproduction of the problem
1. Open the [Dojo](https://dojo.telerik.com/@NeliKondova/EHobUqOV) and open the DropDownList

### Current behavior
There is a delay in expanding the popup width.

#### The issue is a regression starting with 2022 R1 SP1

####Workaround
`    $('.k-popup').width(600);
`
[Dojo](https://dojo.telerik.com/@NeliKondova/OgENipOl)

### Expected/desired behavior
There should be no delay when the width od the DropDownlist is set.. 

### Environment

* **Kendo UI version:** 2022.2.802
* **Browser:** [all ]

**Comment by veselints** [comment]
Due to the changes introduced with the unified rendering of the DropDownList the proper way of setting manually the list with has changed to:

```js
categories.list.parent().width(600);
```

Here is a Dojo sample implementing the above suggestion:
https://dojo.telerik.com/omeBeqEn
