### ISSUE TITLE
The Form TagHelper does not support for hidden fields

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#7037]
### Bug report

The Form TagHelper does not provide support for hidden fields, similar to the HtmlHelper. 

### Reproduction of the problem
The Form TagHelper does not allow similar built-in configuration:
```
.Items(i =>
            {
            i.Add()
                .Field(f => f.UserID)
                .Editor(editor => editor.Hidden());
            })
```

### Expected/desired behavior
The Form TagHelper should support hidden inputs.

### Workaround
Similar result can be achieved by setting the `editor-handler` attribute, creating a hidden input and setting an empty label:
```
<form-items>
    <form-item field="UserID" editor-handler="hiddenEditor" >
        <item-label text=" " />
    </form-item>
</form-items>

<script>
    function hiddenEditor(container, options) {
        $('<input type="hidden" data-bind="value: ' + options.field + '" name="' + options.field + '"/>')
            .appendTo(container);
    }
</script>
```

### Environment

* **Kendo UI version:** 2022.3.913
* **Browser:** [all]

**Comment by gyankov** [comment]
I suggest implementing a boolean field `hidden-input` for the `FormItemTagHelper`. When set to `true`, the `editor` property will be `hidden`.

e.g.
```
        <form-item field="TextBox" hidden-editor="true">
        </form-item>
```

I prefer this approach as implementing a separate editor tag helper just for setting a single string property seems like overkill.

**Comment by ydinesh** [comment]
How to hide only the label not the editor?
