### ISSUE TITLE
TreeList Inline editing missing Update button

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#7040]
### Bug report

When the data-command="createChild" in the TreeList's DataBound handler is hidden the Update button also disappears - 
`
if (dataItem.isNew()) {
                                    row.find("[data-command='createchild']").hide();
                                }
`

### Reproduction of the problem
1. Run [this Dojo](https://dojo.telerik.com/@Stoyan/UHIWUdEf)
2. Click on "Add new record" or "Add child"

### Expected/desired behavior
The Update button shouldn't be hidden

### Environment

* **Kendo UI version:** 2022.3.913

**Comment by Dimitar-Goshev** [comment]
Not reproducible on the Dojo.
