### ISSUE TITLE
Upload in toolbar does not work

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#7044]
### Bug report
Kendo Upload does not work when placed in a Toolbar template item.
Dojo reproducing the problem - https://dojo.telerik.com/ituRAnuf/2

Additional scenario:
Kendo Checkbox  doesn't work - it cannot be checked - https://dojo.telerik.com/IVECApOZ/ and https://dojo.telerik.com/IVECApOZ/2

### Current behavior
The upload popup is not opened.

### Expected/desired behavior
The upload should function correctly.

Broken with version 2022.3.913

**Comment by nelito987** [comment]
Additional scenario: Text can not be cleared when 'input type="search"' is placed in the template. 
1. Open the Dojo - https://dojo.telerik.com/@NeliKondova/IyAcifeh
2. Type some text and try to clear it by using the 'x' icon.
