### ISSUE TITLE
FloatingLabel does not work in the latest version

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-ui-core#7048]
### Bug report

The FloatingLabel does not work as expected in the latest version of the product.

### Reproduction of the problem

https://dojo.telerik.com/oKiHUNIp

### Current behavior

The floating label is always floating.

### Expected/desired behavior

The floating label should behave as it did in the previous version.

### Environment

* **Kendo UI version:** 2022.3.913(Regression)
* **jQuery version:** 1.12.3
* **Browser:** [all]

**Comment by trendoid** [comment]
Just got bit by this bug.  Thanks for fixing it!
