### ISSUE TITLE
Grid PopUp Editor misaligned on mobile devices

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#7062]
### Bug report

When the Grid's PopUp Editing is enabled on mobile devices there are additional inputs or missing styling in the PopUp.

Regression starting 2022.2.802

### Reproduction of the problem
1. Open https://dojo.telerik.com/@sspasova/arIjisEt
3. Click the ''Edit'

**Note:** The issue doesn't reproduce in a browser's DevTools on desktop

### Current behavior
The PopUp is misaligned or its styles are missing on mobile devices

### Environment

* **Kendo UI version:** 2024.1.130
* **Browser:** [ Mobile Chrome | Android Web Browser | iOS Safari ]

**Comment by icesasoftcorp** [comment]
Hi please check this problem also add other controls in edit form 
![image](https://user-images.githubusercontent.com/43230784/215253094-55158261-a583-4e84-a833-989bb9fec909.png)

**Comment by gyankov** [comment]
Issue replicates in jQuery with custom editor: 
- https://dojo.telerik.com/AcOzIWum/4

**Comment by gdenchevprog** [comment]
This no longer seems to be reproducible (using latest):

https://dojo.telerik.com/@gdenchev/oQAreWOQ

Checked using Android device, iOS device and browser's devtools.
