### ISSUE TITLE
Checkbox selection for all rows not firing change event on grid

### ISSUE THREAD

**Issue by douglas2** [telerik/kendo-ui-core#7066]
### Bug report

The checkbox to select all rows doesn't fire the event **[change](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/events/change)** for the grid.

### Reproduction of the problem

1. The online demo: [https://demos.telerik.com/kendo-ui/grid/checkbox-selection](https://demos.telerik.com/kendo-ui/grid/checkbox-selection), [https://demos.telerik.com/aspnet-core/grid/checkbox-selection](https://demos.telerik.com/aspnet-core/grid/checkbox-selection) or this [https://dojo.telerik.com/opEdIkUD](https://dojo.telerik.com/opEdIkUD)
2. Click the checkbox to select all rows.
3. Note that the console log doesn't show anything when selecting all rows.

### Current behavior
The event **[change](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/events/change)** on the grid is triggered.

### Expected/desired behavior
The event change should be triggered to know that all rows has been checked in the grid.

### Environment

* **Kendo UI version:** 2022.3.913
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by delossan** [comment]
Did you ever get a response on how to fix this?  I am having the same issue.

**Comment by douglas2** [comment]
I am using v2022.3.1109 where this is working.

Also the online demo works now:
https://demos.telerik.com/kendo-ui/grid/checkbox-selection

**Comment by ahawes-clarity** [comment]
> > We are using .NET Core with Telerik.UI.for.AspNet.Core 2022.3.913 (latest stable) and it doesn't work.
> 
> Agreed. Same for me.

Upgraded to 2023.1.117 and it seems to be working.

**Comment by delossan** [comment]
We upgraded to 2023.1.117 and it's working now.  Thank you.
