### ISSUE TITLE
Enhance performance for large data sets - remove aria-level and aria-setsize attributes as they can be inferred from DOM

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-ui-core#7067]
### Description
Since 2022.2.802 TreeView renders `aria-level` and `aria-setsize` ARIA attributes to its nodes to enhance its Accessibility compliance. Currently this results in decreased performance with large data sets.

### Workaround
Override the _ariaItems() method before initializing the TreeView:
`kendo.ui.TreeView.prototype._ariaItems = function() { return false; }`

### Reproduction of the problem
1. Run the following [Dojo snippet](https://dojo.telerik.com/aMiZevEg) and check times logged in console

### Current behavior
TreeView loads in about 2 seconds

### Expected/desired behavior
TreeView loads in less then 0.5 sec - https://dojo.telerik.com/@Dimitar-Goshev/EyowoxiX

### Environment
* **Kendo UI version:** 2022.3.913
* **Browser:** all

**Comment by veselints** [comment]
We decided to entirely remove the `_ariaItems()` method.
