### ISSUE TITLE
The Change event of the Grid is not working with header checkbox click

### ISSUE THREAD

**Issue by antonmironovv** [telerik/kendo-ui-core#7072]
### Reproduction of the problem

1. Open [this dojo example](https://dojo.telerik.com/@anton.mironov/ebARolAd)
2. Click the header checkbox

### Current behavior

The change event of the Grid is not working when the header checkbox is selected.

### Expected/desired behavior

The change event should be handled when the header checkbox is clicked.

### TicketID:
1581803

### Environment

* **Kendo UI version:** 2022.3.913
* **Browser:** [all]

**Comment by douglas2** [comment]
Same issue reported here:
[https://github.com/telerik/kendo-ui-core/issues/7066](https://github.com/telerik/kendo-ui-core/issues/7066)
