### ISSUE TITLE
Quotes in the HtmlAttributes configuration option cannot be applied for the Grid's columns

### ISSUE THREAD

**Issue by alestoya** [telerik/kendo-ui-core#7101]
### Reproduction of the problem

- Run the following [Telerik REPL](https://netcorerepl.telerik.com/GcvaxvEg50e0ALSD38).
- Notice the logged error within the console.

### Current behavior
Having a grid with a similar column setup will result in an error.
```
.Columns(columns =>
{
    columns.Bound(p => p.UnitsInStock).HtmlAttributes(new { @class = "#: UnitsInStock == 39 ? 'test' : 'a' #" });
})
```

### Expected/desired behavior
Having a grid with a similar column setup should not result in an error.

```
.Columns(columns =>
{
    columns.Bound(p => p.UnitsInStock).HtmlAttributes(new { @class = "#: UnitsInStock == 39 ? 'test' : 'a' #" });
})
```

### Environment

* **Kendo UI version:** 2022.3.913
* **Browser:** [all]

**Comment by ogorodnikovInfopulse** [comment]
Original bug was not related to single quotes but to french letters. Ticket number 1584947

var arr = new char[]{(char)68, (char)233, (char)116, (char)97, (char)105, (char)108 };
var strCreated = new string(arr); //"Détail" - get from localization from french
x.Template(string.Empty)
.HtmlAttributes(new {title = strCreated});

**Comment by aleksandarevangelatov** [comment]
With the fix, the HtmlAttributes, HeaderHtmlAttributes and FooterHtmlAttributes methods will accept an additional optional Boolean parameter that would indicate whether the attributes should be encoded or not. By default, the attributes passed are encoded using the default HTML encoder. 

The following configuration will NOT encode the passed attributes:

```
.Columns(columns =>
    {
        columns.Bound(p => p.UnitsInStock).HtmlAttributes(new {title = "Détail"}, false);
    })
```
