### ISSUE TITLE
Drawing in the Signature in mobile landscape mode.

### ISSUE THREAD

**Issue by yanisslav** [telerik/kendo-ui-core#7111]
### Bug report

1. Open the following demo on a mobile device in landscape mode: 
https://demos.telerik.com/kendo-ui/signature/index
2. Try to draw.

### Current behavior
Drawing line is being offsetted.

### Expected/desired behavior
Drawing line should be applied correctly.

The issue might be related to #7108 

### Environment
* **Kendo UI version:** 2022.3.1109
* **Browser:** [all]

**Comment by sspasova** [comment]
I am closing this issue because it is reproducible in the Demos only. I cannot reproduce it in Dojo. Tested on iOS and Android using Kendo UI 2023.3.1114.
