### ISSUE TITLE
Switch is cut off in the Bootstrap V3 theme

### ISSUE THREAD

**Issue by magdalenaan** [telerik/kendo-ui-core#7112]
### Bug report
Top and bottom borders of Switch is cut off in the Bootstrap V3 theme.

### Reproduction of the problem
open the following Dojo: https://dojo.telerik.com/eHeDeWuS/3

### Current behavior
![image](https://user-images.githubusercontent.com/4389590/201309237-016f1072-f4e9-4810-8e55-8186f4ae7240.png)

### Expected/desired behavior
![image](https://user-images.githubusercontent.com/4389590/201309546-3673d6eb-36a6-4362-b244-e04093179982.png)

### Environment

* **Kendo UI version:** 2022.3.1109
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Dimitar-Goshev** [comment]
Closing this issue as R1 2023 is the last official release of Kendo jQuery, where Less Themes are supported and shipped with the product.
