### ISSUE TITLE
Grid drag&drop row to an empty Grid is not working

### ISSUE THREAD

**Issue by yanisslav** [telerik/kendo-ui-core#7116]
### Bug report

Dragging a row from a Grid to another empty Grid is not working.

### Reproduction of the problem

1. Open the following dojo: 
https://dojo.telerik.com/@sspasova/IDuYISoJ
2. Try to drag a row to the empty Grid

### Current behavior
The row is not inserted in the empty Grid

### Expected/desired behavior
The row should be inserted in the empty Grid.

### Environment

* **Kendo UI version:** 2024.1.130
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1598712

**Comment by aleksandarevangelatov** [comment]
Reported in ticket 1599167

**Comment by mihaela-lukanova** [comment]
Reported in ticket 1621408

**Comment by nelito987** [comment]
Reported in ticket: 1626225

**Comment by iordanGrancharov** [comment]
After discussion, we decided that the right way to handle this issue is by custom implementation since the drag and drop between grids is a custom implementation as well. An example will be provided in the demo for the "Drag and Drop" in the Grid's documentation.
