### ISSUE TITLE
Missing encoded feature for the Breadcrumb items

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7121]
### Bug report

Entities are not decoded in the Breadcrumb Items.

### Reproduction of the problem
1. Open this dojo example -  https://dojo.telerik.com/UfayAQoP/5

### Current behavior
The ' character is encoded in the last Breadcrumb item

### Expected/desired behavior
The ' character shouldn't be encoded in the last Breadcrumb item

### Environment

* **Kendo UI version:** 2022.3.1118 
* **Browser:** [all]

**Comment by Iankodj** [comment]
The fix will be addressed by adding an encoded option for the items collection so that one can choose whether the text to be encoded or not.
