### ISSUE TITLE
Disabling a button of a ToolBar inside TabStrip hides the button instead in LESS themes

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7123]
### Bug report

In a Toolbar that is placed within a TabStrip, using the enable method to disable a button hides it instead. The issue in reproduceable only with LESS themes.

Regression introduced with R1 2022

### Reproduction of the problem

1. Open this example - https://dojo.telerik.com/uLovUyon/5
2. Press the button above the TabStrip to disable the one in the Toolbar

### Current behavior

The Toolbar button is being hidden

### Expected/desired behavior
The button should only become disabled.

### Environment

* **Kendo UI version:** 2022.3.1118 
* **Browser:** [all]

**Comment by MilenaCh** [comment]
Still reproducible for LESS

**Comment by veselints** [comment]
This is a regression in the LESS themes caused by the following style:
```
.k-tabstrip .k-button.k-disabled {
    pointer-events: none;
    opacity: 0;
}
```

Commit: https://github.com/telerik/kendo/commit/ccfbbe1c6db9e2c5815dd574f36080e12e063371#diff-0b5d2bc7ecdeb628ebff545076158f9a10d7321eab82242494bbbc7d969b8782R269
