### ISSUE TITLE
Virtualized list does not show a result on second filtering

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#714]
### Description
Widget does not show filtered result on second filtering attempt.

Repro demo: http://dojo.telerik.com/oMOSU/2

Repro steps:
1. Open popup
2. Type 2000 and select (with mouse) the found item
3. Open again and type 1234

Notice how the list is not scrolled back and the widget never displays the filter result.

Reported in Ticket ID: 924593

**Comment by ggkrustev** [comment]
Probably related to #710

**Comment by valchev** [comment]
Added tests with c5cb391
