### ISSUE TITLE
Unable to set Scheduler editable window options

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#7141]
### Bug report
Some of the options of the Scheduler's **Editable.Window** configuration do not work. 

### Reproduction of the problem
Configure Editable as shown below:
```
.Editable(editable =>
{
    editable.TemplateName("CustomEditorTemplate");
    editable.EditRecurringMode(SchedulerEditRecurringMode.Series);
    editable.Window(w => w.Position(p => p.Top(40)).HtmlAttributes(new { @class="test", style = "top: 40px; max-height: calc(100vh - 80px); min-width: 680px;" }).Scrollable(true));
})
```

### Current behavior
The **Top** and **HtmlAttributes** options have no effect. A custom class is not applied to the wrapping element. 

### Expected/desired behavior
The options should work as intended. 

### Environment

**Kendo UI version:** 2022.2.913
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
The HtmlAttributes method is inherited from the WidgetBuilderBase class and it sets attributes to the generated html. However, in the context of the editor, no html is generated as the actual popup window is created on the client when the user double clicks to open the popup editor. In other words, the configuration from the Editable.Window is serialized to a JS object which then is used when the window is created on the client. Therefore, the object passed to HtmlAttributes is ignored.

As possible workaround is to add the desired attributes to the container within the Edit event handler of the Scheduler:
```
.Events(ev=>ev.Edit("onEdit"))

<script>
function onEdit(e) {
    e.container.addClass('test');
}
</script>
```

In addition, a [Feature Request](https://feedback.telerik.com/kendo-jquery-ui/1611964-expose-attribute-configuration-option-for-the-window-component) on exposing the `attributes` configuration is now present, so the HtmlAttributes can be applied to the generated popup window.
