### ISSUE TITLE
Selected item text/dataItem is not updated

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#715]
Can be replicated here with latest kendo version: 
[http://dojo.telerik.com/eGUJi/2](http://dojo.telerik.com/eGUJi/2)

**Comment by frankhuiskamp** [comment]
This is the same issue (and link) as this issue:
https://github.com/telerik/kendo-ui-core/issues/557

**Comment by ggkrustev** [comment]
No, it isn't. The problem is with DropDownList, that does not update the selected text, once the model is updated.
