### ISSUE TITLE
DPLProcessing files are included in the UI for PHP source distribution

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7153]
### Bug report

The following files are included in the UI for PHP source distribution:

kendoui\wrappers\php\lib\Kendo\UI\PDFViewerDplProcessing.download.php
kendoui\wrappers\php\lib\Kendo\UI\PDFViewerDplProcessing.read.php
kendoui\wrappers\php\lib\Kendo\UI\PDFViewerDplProcessing.upload.php

The files are also duplicated with: 

PDFViewerDplProcessingDownload.php, 
PDFViewerDplProcessingRead.php 
PDFViewerDplProcessingUpload.php

### Expected/desired behavior
The DplProcessing should not be included in the UI for PHP source distribution 

### Environment

* **Kendo UI version:** 2022.3.1109
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
Closing the bug due to the deprecation of the PHP wrappers.
