### ISSUE TITLE
Select Upload Button Not Functional on First Click in Firefox

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#7155]
### Bug report

When a user clicks the Kendo UI Upload's "select files" button in Firefox, they will need to click twice.

### Reproduction of the problem

1. Please visit [this Kendo UI Upload Live Demo ](https://demos.telerik.com/kendo-ui/upload/async?autoRun=true&theme=fluent-main)with FireFox,.
2. Click the select button, and click again.

### Expected/desired behavior
The first click should trigger the menu to open for uploading files.

### Environment

* **Kendo UI version:** 2022.3.1109
* **jQuery version:** All Supported Versions
* **Browser:** Firefox 108.0

**Comment by lgiambalvo-virtualstrongbox** [comment]
Please note I reported this issue, and I was only able to reproduce it when using the Fluent theme. It seems like all the other themes work fine. Seems strange that a theme would cause a click event issue, but I have seen stranger things happen too.

**Comment by Dimitar-Goshev** [comment]
The issue is not reproducible anymore on my side. Tested with Firefox 113.02 and 114.0.1 on https://demos.telerik.com/kendo-ui/upload/async?autoRun=true&theme=fluent-main (Fluent theme) - The demo uses Kendo UI for jQuery version 2023.2.606 and themes version 6.4.0.
