### ISSUE TITLE
Grid Accesibility error from Wave tool: Empty table header using detailTemplate

### ISSUE THREAD

**Issue by pacoweb** [telerik/kendo-ui-core#7169]
The WAVE tool warns of an error when you use a Kendo Grid using deatailTemplate.
The error is Empty table header (on the header of the detail column because is empty)

### To reproduce this behavior:
1. Install the extension WAVE Evaluation Tool (https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) in Chrome
2. Open this url https://dojo.telerik.com/@Dimitar-Goshev/abIZiTow - Use the option FullScreen
3. Activate wave tool
4. Check the errors list
![image](https://user-images.githubusercontent.com/1198633/212936112-0e614f39-115b-4182-9789-529ad2a8f7ef.png)
![image](https://user-images.githubusercontent.com/1198633/212935945-daa9bf5b-c6cc-46dc-bfda-119345ffda23.png)

### Expected/desired behavior
Maybe a property to set the text in that "detail" column header

### Environment
Kendo UI version: 2023.3.1114
jQuery version: 3.6.1
Browser: all

**Comment by gdenchevprog** [comment]
A property to add text to the header of the detail template column is available:

https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/messages.expandcollapsecolumnheader
