### ISSUE TITLE
Formatting logic is not executed in the Grid column's HtmlAttributes

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#7174]
### Bug report
Regression in R1 2023. 

### Reproduction of the problem
1. Set the following HtmlAttributes configuration in a Grid column:

```
columns.Bound(p => p.OrderDate).HtmlAttributes(new { title = "Order Date: #=kendo.toString(OrderDate, 'dd-MM-yyyy')# " });
```

### Current behavior
kendo.toString is not executed and as a result the date is not formatted. The exact value of the title attribute, as shown above is rendered as title of the cell. 

### Expected/desired behavior
The logic is executed and the OrderDate value is rendered in the title with the specified format. 

### Environment

* **Kendo UI version:** 2023.1.117
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
Similar issue is reported in ticket 1594526

**Comment by aleksandarevangelatov** [comment]
Also observed in Kendo UI for jQuery - [example](https://dojo.telerik.com/@AleksandarEvangelatov/uCAyuZud) - hover over ShipName column to observe the issue. Works as expected with [v2022.3.1109](https://dojo.telerik.com/@AleksandarEvangelatov/aruPiqEK)

**Comment by gyankov** [comment]
As a result of the CSP compliance initiative, we had to remove all kendo templates from the source of our components, as they are not compatible with the `unsafe-eval` directive.

From now on, the suggested approach to achieve the same attribute binding result, we deliver a new HtmlAttributes overload that accepts a single string parameter, the name of the JS handler that returns the attributes.

e.g.

```
// column configuration
columns.Bound(p => p.OrderDate).HtmlAttributes("attributesHandler");

//handler

function attributesHandler(data) {
  return { title: `Order Date: ${kendo.toString(data.OrderDate, 'dd-MM-yyyy')} ` }
}
```
