### ISSUE TITLE
Error is thrown when using templates in MobileListView

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7185]
### Bug report

Error is thrown when templates are used in MobileListView.

### Reproduction of the problem
1. Open the link from the api below
- https://docs.telerik.com/kendo-ui/api/javascript/mobile/ui/listview/configuration/datasource
2. Run the examples in Dojo and observe the console.

### Current behavior
An error _"Cannot read properties of undefined (reading 'uid')"_ is thrown and the ListView is not displayed

### Expected/desired behavior
No error should appear ad the widget should be displayed as expected.

### Environment

* **Kendo UI version:** 2023.1.117
* **Browser:** [all  ]

**Comment by martintabakov** [comment]
Also  in Ticket 1597287

**Comment by niclasbb** [comment]
I am facing the same problem. Can not upgrade to versions >= 2023.1.117

**Comment by nelito987** [comment]
Reported also in ticket id: 1607344

**Comment by ag-petrov** [comment]
Closing this issue as the mobile suite is now depricated.

**Comment by pklaes** [comment]
Is there an offcial statement for the depreciation of the mobile suite? We are still depending on some controls for our suite of business apps and would have to plan for their migration.
