### ISSUE TITLE
Zooming in on a large image loaded in the ImageEditor results in poor performance.

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#7189]
### Bug report

Zooming in on a large image loaded in the ImageEditor results in poor performance.

### Reproduction of the problem
A sample application is available in ticket 1595292. Run the application and zoom in on the top ImageEditor.

### Current behavior
Zooming in takes too much time.

### Expected/desired behavior
Zooming should be faster.

### Workaround
Issue is possibly related to the check on whether an image is exportable - [link](https://github.com/telerik/kendo/blob/0223c1a07f227d1e0a41ea9ca2a2d6689d94f1cd/src/kendo.imageeditor.js#L313). A possible workaround is to bypass the check:
```
      kendo.ui.ImageEditor.fn._toggleTools = function () {
            var that = this,
                canRedo = that.redoStack.length > 0,
                canUndo = that.undoStack.length > 0,
                hasImage = !!that._image;

            that.toolbar.toggleTools({
                redo: canRedo,
                undo: canUndo,
                enable: hasImage,
                canExport: true, // Avoid checking if image can be exported. Causes performance issues.
            });
        };
```
[Example](https://dojo.telerik.com/EhabaKEl)
### Environment

* **Kendo UI version:** 2023.1.117
* **Browser:** [all]

**Comment by ag-petrov** [comment]
Seems to be fixed in the latest versions
