### ISSUE TITLE
Selecting optionLabel in DropDownList when value primitive set to false does not set the whole model

### ISSUE THREAD

**Issue by subev** [telerik/kendo-ui-core#720]
When the optionLabel is selected inside the DropDownList and the value primitive is disabled the model is still updated with just the value field instead of the whole object.

Example [here](http://dojo.telerik.com/@pesho/oGEgU)

**Comment by naskog** [comment]
Open the popup and do NOT change the value 
Result: "change" event is fired and the "dirty" flag is set

**Comment by ggkrustev** [comment]
Fixes with 0a8935d8a4b64ce668172846eec390d293f236a3
