### ISSUE TITLE
Scheduler for react cell is shrinked that date isn't recognizable in grouped resource showed in week and month horizontally.

### ISSUE THREAD

**Issue by jhunexjun** [telerik/kendo-ui-core#7200]
### Bug report

Date is almost not recognized when the view is week or month with room and person resources in a horizontal view.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/6801369/217639240-3ee0b119-5f1d-4ff5-9a5b-80d46b30c868.png">

### Reproduction of the problem
Go to https://www.telerik.com/kendo-react-ui/components/scheduler/ and select Week or Month view.

### Current behavior
Cell is shrinked that the content is not readable like Saturday becomes "turd". In Week view the cell date becomes "e, 6/"

### Expected/desired behavior
That the cell width should adjust the content of the date cell and that the entire width of the Scheduler should be scrollable horizontally so that even if there are more resources it won't shrink just to fit its width.

### Environment

* **"@progress/kendo-react-scheduler": "^5.11.0"
* **"@progress/kendo-theme-bootstrap": "^5.12.0"
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Hello @jhunexjun . Thank you for your feedback. This repository is for Kendo UI for jQuery components. Please log the issue in the Kendo React bug tracker repository - https://github.com/telerik/kendo-react
