### ISSUE TITLE
OptionLabel value not consistent

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#721]
Reported in Ticket ID: 925344 

Repro dojo: [http://dojo.telerik.com/@naskog/OZIqa](http://dojo.telerik.com/@naskog/OZIqa)
Click "get"
Result is: 
for Q3 2014 SP3: "-1"
for Q1 2015: "1"
for Q1 2015 SP1: "" (blank)

Possibly related to workitem #720

**Comment by ggkrustev** [comment]
Duplicate with #725
