### ISSUE TITLE
Infinite render loop with the Grid component when `input.checked` is instrumented

### ISSUE THREAD

**Issue by BenoitZugmeyer** [telerik/kendo-ui-core#7218]
### Bug report

I am one of the [Datadog Browser SDK](https://github.com/DataDog/browser-sdk/) maintainers. A customer using the `@progress/kendo-angular-grid` component had an issue when integrating our SDK to their website: a page using the grid component was consuming 100% of the CPU and eventually crashed.

After investigation, it turned out that it was related to the way our SDK integrates with DOM elements. We'll adjust our SDK to support this usecase, but this could still happen with other libraries integrating with DOM elements in the same way, so I'm opening the issue just to let you know about this problem.

For reference, here is our related fix: https://github.com/DataDog/browser-sdk/pull/2030

### Reproduction of the problem

1. open the official Kendo UI grid example: https://www.telerik.com/kendo-angular-ui/components/grid/examples/filter-all-columns/?theme=default-ocean-blue&themeVersion=6.1.0

2. execute the following code in the console:
```js
Object.defineProperty(HTMLInputElement.prototype, 'checked', { set() { setTimeout(() => { }) } })
```

3. click on the first checkbox

### Current behavior

The CPU usage increases to 100%, the page is crashing eventually

### Expected/desired behavior

Low CPU usage, no page crash

### Diagnostic

* Angular is using Zone.js to track asynchronous executions (like `setTimeout`), and apparently in some cases triggers a component re-render when a `setTimeout` executes its callback.

* The grid component is likely using something like `input.checked = true` when being rendered.

* The Browser SDK instrumentation of `input.checked` uses `setTimeout` every time this property is set.

Thus, we have an infinite render loop consuming the CPU.

### Environment

* **Kendo UI version:** latest
* **jQuery version:** no jquery used?
* **Browser:** probably all, but tested on Chrome version 110.0.5481.100 (Official Build) (arm64)

**Comment by Dimitar-Goshev** [comment]
Hi @BenoitZugmeyer 
Thank you for your detailed feedback. This repository is for Kendo UI for jQuery.
Please look for the issue in the Kendo UI for Angular repository - https://github.com/telerik/kendo-angular/issues and log it there, if not present.
