### ISSUE TITLE
MultiSelect's animation container has display:block style if open event is prevented.

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7220]
### Bug report

If the MultiSelect open event is prevented, the animation container has display:block style, blocking inputs beneath the MultiSelect

### Reproduction of the problem
1. Open this example - https://dojo.telerik.com/EqOSOReM/38
2. Type something in the MultiSelect and blur, without selecting an item.
3. Focus the MultiSelect again
4. Try to focus the input beneath

**Regression introduced with 2022.2.621**

**Workaround**: manually hide the animation container - https://dojo.telerik.com/EqOSOReM/38

### Current behavior
The k-animation-container has display:block style, preventing the input beneath it from being focused

### Expected/desired behavior
The k-animation-container should have display:none style.

### Environment

* **Kendo UI version:** 2023.1.117
* **Browser:** [all]

**Comment by veselints** [comment]
The issue is no longer present in R1 2023.1.314
