### ISSUE TITLE
Wrong resized height of splitter when its height is expanded to 100%

### ISSUE THREAD

**Issue by magdalenaan** [telerik/kendo-ui-core#7226]
### Bug report
If the splitter container has 100%, the height of the Splitter panes is changed when the splitbar is moved to the right or left.

### Reproduction of the problem
1) open the following example: https://dojo.telerik.com/@sspasova/IdAJaPeM
2) move the splitter to right and left
3) The height of panes is different depending on moving the Splitbar to the left or right

### Current behavior
The panes of the splitter have the wrong height when it is moved to the left and the correct one when it is moved to the right.

### Expected/desired behavior
Splitbar panes should have the same height regardless of splitbar moving.

### Tip for fixing
When the splitbar is moved to the left, the left position of the second splitbar pane should be updated before its width. For now, it is updated after it, which causes showing a horizontal scrollbar of the Splitter parent for a moment. As a result, the Splitter pane height is miscalculated.

### Environment

* **Kendo UI version:** 2024.1.130
* **jQuery version:** 3.4.1
* **Browser:** [all]

**Comment by martintabakov** [comment]
Regression with 2022.1.119

**Comment by pepinho24** [comment]
This should be fixed with the introduction of the flex based rendering of the Splitter
