### ISSUE TITLE
Pressing the clear button in the DropDownTree does not change the value in the change event

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7231]
### Bug report

Pressing the clear button of the DropDownTree does not change the component's value in the change event.

### Reproduction of the problem
1. Open this Dojo - https://dojo.telerik.com/aREzEWaK/13
2. Open the browser console
3. Select an item
4. Press the clear button

### Current behavior

The value is the same as before pressing the button

### Expected/desired behavior
The value should be an empty string after pressing the clear button

### Environment

* **Kendo UI version:** 2023.1.117
* **Browser:** [all]

**Comment by veselints** [comment]
This regression has been introduced with 2022.3.913 release.
