### ISSUE TITLE
Loading indicator does not appear when child nodes are reloaded

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-ui-core#7247]
### Bug report

The TreeList does not display the loading indicator when a parent with more than one child is reloaded.

### Reproduction of the problem

Open and run the following Dojo:
https://dojo.telerik.com/@gdenchev/eqUCAfeh

1. Expand the first parent element.
2. Then expand and collapse Employee 5(Anika) several times.
3. Repeat the same process of expanding/collapsing for Employee 2(Guy).

Step 3 can be repeated for any other node that has more than 1 child.

### Current behavior

Notice how in the case of Anika(5), the loading indicator appears every single time. However, for Guy(2) it appears only the first time the node is expanded.

### Expected/desired behavior

Since the children are reloaded and a new request is made(this can be seen in the network tab), it is expected that the loading indicator also appears for Guy(2).

### Environment

* **Kendo UI version:** 2023.1.117
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by gyankov** [comment]
After this fix, an infinite recursion occurs when you have a server grouped and filtered grid, and you try to add a new item:

- https://dojo.telerik.com/IboWEdUl
