### ISSUE TITLE
Text cannot be selected in PDFViewer with pdfjs v3.4.120

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7250]
### Bug report

Text cannot be selected in the PDFViewer with pdfjs v3.4.120.

### Reproduction of the problem
1. Open this example - https://dojo.telerik.com/IxuSuPuV
2. Try to select some text

### Current behavior

Text cannot be selected

### Expected/desired behavior
Text should be selectable

### Environment

* **Kendo UI version:** 2023.1.117
* **Browser:** [all]

**Comment by nelito987** [comment]
Reported in ticket: 1607495

**Comment by antonmironovv** [comment]
Reported in ticket: 1616280
