### ISSUE TITLE
Setting a class through the attributes property in the SplitButton makes the button unclickable

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7251]
### Bug report

If you set a class through the items.attributes configuration in the SplitButton, the respective button is unclickable

### Reproduction of the problem
1. Open this example - https://dojo.telerik.com/IvakivUc/5
2. Try to click the Item2 button
### Current behavior
The button is unclickable

### Expected/desired behavior

ТThe button should be clickable

### Environment

* **Kendo UI version:** 2023.1.117
* **Browser:** [all ]

**Comment by Dimitar-Goshev** [comment]
Closing it as duplicate of https://github.com/telerik/kendo-ui-core/issues/7207 , which is fixed in 2023.1.425 .
