### ISSUE TITLE
ListView throws exception when no template handler is supplied

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#7264]
### Bug report
ListView throws exception when no template handler is supplied

### Reproduction of the problem
Configure a ListView with template id and don't provide a template handler.

### Current behavior
An exception is thrown.

### Expected/desired behavior
No exception is thrown.

### Workaround
Set a ClientTemplateHandler with a dummy value.

```
.ClientTemplateHandler("template")
```

### Environment
* **Kendo UI version:** 2023.1.314
* **Browser:** all

**Comment by DoomerDGR8** [comment]
If there is a patch out already, then good, I'll wait for the new setup, but with the temporary fix, if `.Scrollable()` is added to the mix, the whole UI control doesn't show up the runtime. To make this work, I had to remove `.Scrollable()`.

**Comment by gyankov** [comment]
Hi @ DoomerDGR8, please verify that you set the component's height. 
```
.HtmlAttributes(new { style = "height:350px;" })
```

If no height is supplied with enabled scrolling, the component will shrink to 0px.

On a side note, we've removed the `k-widget` class from the element, if you previously used it as a selector to set the height, this might be causing the behavior.
