### ISSUE TITLE
The Upload 'Select files' localization isn't working

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#7265]
### Bug report

The Upload '[Select files](https://docs.telerik.com/kendo-ui/api/javascript/ui/upload/configuration/localization.select)' localization isn't working.

The behavior is a regression occurring in version 2023.1.314

### Reproduction of the problem
1. Run this [Dojo](https://dojo.telerik.com/@Stoyan/aDuBaluv)

### Current behavior
The localization.select configuration doesn't have effect.

### Environment
* **Kendo UI version:** 2023.1.314
* **Browser:** [all]

**Comment by nelito987** [comment]
Reported also in ticket ID: **1602513**

**Comment by NikoPenev21** [comment]
Reported also in #1602699

**Comment by ThomasMaij** [comment]
Also cursor styling is broken..
