### ISSUE TITLE
Grid Toolbar attributes aren't applied

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#7266]
### Bug report

Html Attributes aren't applied to the items of the Grid's Toolbar. 

The behavior is a regression occurring in version 2023.1.314

### Reproduction of the problem
1. Run this [Dojo](https://dojo.telerik.com/IcepUjob/5)
2. Inspect the Toolbar button

### Expected/desired behavior
Configuring the **attributes** property of the item should apply them to the Html.

### Environment
* **Kendo UI version:** 2023.1.314

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1604415

**Comment by rdorris** [comment]
Was this fixed in 2013.1.425? Still having the issue.

**Comment by twurm** [comment]
It seems like it was partially fixed however only the first attribute is passed through the others are ignored.

**Comment by aleksandarevangelatov** [comment]
Passing an onclick attribute is not applied as expected and a JS error is thrown:
1. [Run this dojo](https://dojo.telerik.com/@AleksandarEvangelatov/eRENOhAm)
2. Click on the custom button

The following command configuration
```
        {
          attr: "onclick=\"myClickHandler(event, 1)\"",
          text: " ",
          name: null,
          iconClass: "k-icon k-i-list-ordered"
        }
```

renders the following markup where the onclick attribute is truncated:
```
<button data-role="" class="k-button k-button-md k-rounded-md k-button-solid k-button-solid-base k-icon-button k-toolbar-button k-grid- k-toolbar-tool" type="button" role="button" aria-disabled="false" tabindex="0" onclick="myClickHandler(event," data-uid="b305b56b-9d36-4c29-9a1f-e0c7c476a8a6">
  <span class="k-icon k-i-list-ordered k-button-icon"></span>
</button>
```

**Comment by veselints** [comment]
@aleksandarevangelatov The attributes must be passed in the tool configuration as members of an object:
```js
attr: { 
    onclick: "myClickHandler(event, 1)",
    class: "esp-export-excel esp-exportTool  esp-tb-btn"
}
```

Here is a modified sample implementing the proper approach:
https://dojo.telerik.com/EJaROXEW/3

@twurm May I ask you to share an example where only the first member of the `attr` is passed to the tool and the rest are ignored? Thank you!

**Comment by twurm** [comment]
@veselints take a look at this REPL: [https://netcorerepl.telerik.com/QHEJkNvP432lEYnO30](https://netcorerepl.telerik.com/QHEJkNvP432lEYnO30).  Its producing the following HTML:

![image](https://github.com/telerik/kendo-ui-core/assets/23122687/612d3120-5cdd-41b1-a5ca-57f402506b1f)

As you can see one of the classes is "esp-export-excel" however none of the other custom classes are present.

**Comment by veselints** [comment]
@twurm, thank you for the additional clarification! We will further discuss the case internally, so that the most appropriate fix will be implemented.
