### ISSUE TITLE
Filter in the Grid is not rendered correctly after clicking on the TimePicker

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7279]
### Bug report

The popup of the filter does not contains all items after selecting the timepicker. 

### Reproduction of the problem
1. Open the [Filter Demo](https://demos.telerik.com/kendo-ui/grid/filter-menu-customization)
2. Open the filter popup for the Birth Date.
3. Click on the 'clock' icon to display time.

### Current behavior
The filter popup is closed. After the filter is opened again it displays only times. The filter popup should be closed and opened again to be rendered as expected.

### Expected/desired behavior
After selecting the TimePicker the filter popup should not close, should display times.

### Environment

* **Kendo UI version:** 2023.1.314
* **Browser:** [all  ]

**Comment by dtopuzov** [comment]
Fixed, will be released with 2023 R2.
