### ISSUE TITLE
Tooltip closes, instead of updating its content, on hovering a new target, while the tooltip is shown

### ISSUE THREAD

**Issue by alestoya** [telerik/kendo-ui-core#7283]
### Bug report

Tooltip closes, instead of updating its content, on hovering a new target, while the tooltip is shown.

**Regression introduced with 2023.1.314**

### Reproduction of the problem
1. Navigate to the [Loading Content with AJAX](https://demos.telerik.com/kendo-ui/tooltip/ajax) or the [Content Template](https://demos.telerik.com/kendo-ui/tooltip/template) demos. Or, open the following [dojo](https://dojo.telerik.com/oGoQiveC).
2. Hover over the first element.
3. Hover over the second element and notice that the content is not shown. 

### Current behavior
For every second hover, the Tooltip does not display the element's content.

### Expected/desired behavior
For every second hover, the Tooltip should display the element's content. Similar to [prior versions](https://dojo.telerik.com/OtUlAkiz).

### Environment

* **Kendo UI version:** 2023.1.314
* **Browser:** [all]

**Comment by dtopuzov** [comment]
Fix will be released with 2023 R2.
