### ISSUE TITLE
Upload cursor styling broken, no cursor: pointer is visible on Select document button

### ISSUE THREAD

**Issue by ThomasMaij** [telerik/kendo-ui-core#7284]
### Reproduction of the problem
see https://dojo.telerik.com/@Stoyan/aDuBaluv

### Current behavior
no cursor change when hovering the button

### Expected/desired behavior
cursor pointer, usually a hand, is visible. 

### Environment

Kendo UI version: 2023.1.314
Browser: [all]

**Comment by mihaela-lukanova** [comment]
Increased priority due to a report in TicketID: 1606474

**Comment by aleksandarevangelatov** [comment]
Raising the priority, as this  is actually a regression introduced with v2023.1.314 Behavior is related to https://github.com/telerik/kendo/issues/17590 and hover styling not being applied to the Upload's button.

**Comment by ThomasMaij** [comment]
Any progress so far?

**Comment by pepinho24** [comment]
Hi @ThomasMaij, as a temporary workaround you can use the following style to fix the cursor on hover:
- https://dojo.telerik.com/@pmilchev/oPAxOXaP
- https://stackoverflow.com/a/23860302
```
<style>
      .k-upload input[type=file], /* FF, IE7+, chrome (except button) */
      .k-upload input[type=file]::-webkit-file-upload-button { /* chromes and blink button */
        cursor: pointer; 
      }
</style>
```
