### ISSUE TITLE
Editing any item in the TreeList InCell will add the k-dirty indicator to its top-left data cell

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7290]
### Bug report

Editing any item in the TreeList InCell will add the k-dirty indicator to its top-left data cell

**Regression introduced with R1 2023**

### Reproduction of the problem

1. Open the TreeList InCell editing demo - https://demos.telerik.com/kendo-ui/treelist/editing-incell
2. Edit any cell in the TreeList
3. The `k-dirty` indicator will appear on its top-left data cell

### Current behavior

The top-left data cell is marked as dirty

### Expected/desired behavior

The top-left data cell shouldn't be marked as dirty

### Environment

* **Kendo UI version:** 2023.1.314
* **Browser:** [all]

**Comment by veselints** [comment]
This is a regression in the TreeList. Therfore, I have changed title, description and tags accordingly.

Most probably introduced with:
https://github.com/telerik/kendo/commit/e264312ea52af00ef6e717c7d9fdb371272b863c
