### ISSUE TITLE
The imageClass of the TreeList command column has no effect

### ISSUE THREAD

**Issue by eyupyusein** [telerik/kendo-ui-core#7298]
### Bug report

The imageClass setting of the TreeList command column doesn't work (neither in jQuery/MVC/Core)
Currently _undefined_ class is added to the 'k-button' element.

### Reproduction of the problem
1. Run the example in the API - https://docs.telerik.com/kendo-ui/api/javascript/ui/treelist/configuration/columns.command#columnscommandimageclass

### Current behavior
There is no icon added in the command button and _undefined_ class is added to the 'k-button' element.

### Expected/desired behavior
There should be icon displayed in the button based on the added class in the imageClass configuration option

#### The issue is a regression - Starting with the 2023 R1 SP1 release
**Note**: Starting with the **2022 R1** release _undefined_ class is added to the _k-button_ element, but still the icon is displayed as icon classes are added to the inner span element. 

Rendering with  **2022 R1**
![image](https://github.com/telerik/kendo-ui-core/assets/14364791/37363671-41f4-4b87-88bf-c26c6d7639b4)

Rendering starting with **2023 R1 SP1**
![image](https://github.com/telerik/kendo-ui-core/assets/14364791/af213f6d-3ec2-4438-867d-6220647a9614)

#### Workaround
 dataBound: function(){
      $('.k-button-text').addClass('k-icon k-i-trash k-button-icon')
      $('.k-button-text').text('')
    },
Dojo - https://dojo.telerik.com/@NeliKondova/oPEvOcus

### Environment

* **Kendo UI version:** 2023.1.425
* **Browser:** [all ]

**Comment by nelito987** [comment]
Reported in ticket ID: 1609147

**Comment by pepinho24** [comment]
With the  2023 R1 SP1 release, to show the icon, either a font one or an SVG one, you would need to simply declare the icon name via the `.icon` property instead of the `.imageClass` one. The image class will just add the class to the icon element if you need it for further customization of the icon.

**Comment by palhal** [comment]
I'm experiencing this issue as well when using the ASP.NET Core wrapper. I hope the wrappers get fixed in the next release.
