### ISSUE TITLE
Passing an object to kendo.observable results in an e.bind not a function error 

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7300]
### Bug report

Passing an object to kendo.observable method results in an error.

**Regression related to the fix for [this issue ](https://github.com/telerik/kendo-ui-core/issues/5973)**

### Reproduction of the problem

1. Open the attached example in VS code.
2. Click the Call Iframe button 

### Current behavior

An e.bind is not a function error occurs in the browser console

### Expected/desired behavior
No errors should be thrown

### Environment

* **Kendo UI version:** 2023.1.314 
* **Browser:** [all] 

[New folder (3).zip](https://github.com/telerik/kendo-ui-core/files/11199980/New.folder.3.zip)

**Comment by gdenchevprog** [comment]
Not reproducible in latest.
Fixed with https://github.com/telerik/kendo/pull/18507
