### ISSUE TITLE
The ExportAs command's dropdown is blank when the exportAs configuration of the Editor is configured

### ISSUE THREAD

**Issue by alestoya** [telerik/kendo-ui-core#7302]
### Bug report

The ExportAs command's dropdown options are not populated when the client-side `exportAs` configuration of the Editor is additionally configured.

**Regression introduced with 2023.1.314**

### Reproduction of the problem

1. Open the following [dojo](https://dojo.telerik.com/@alexander64836/EmUKOrId/13)
2. Notice that the dropdown is blank and no data is populated.

![image](https://user-images.githubusercontent.com/92315320/231455511-351e9a09-505c-40e7-83dd-8cc1cefb3030.png)

### Current behavior

The ExportAs command's dropdown is blank.

### Expected/desired behavior
The ExportAs command's dropdown data should not be blank.

### Environment

* **Kendo UI version:** 2023.1.314
* **Browser:** [all]

**Comment by dtopuzov** [comment]
It somehow got fixed, no idea which commit, but works with staging cdn and dodjo.
