### ISSUE TITLE
PDFViewer buttons in pager not working when pager items are set manually

### ISSUE THREAD

**Issue by antonmironovv** [telerik/kendo-ui-core#7303]
### Bug report

Regression in the last version("2023.1.314") with PDFViewer pager buttons.

### Reproduction of the problem

- Open [this dojo example](https://dojo.telerik.com/@anton.mironov/IYacOzit)
- Upload a multi-page PDF file
- Use the toolbar pager buttons 

### Current behavior
The pages of the PDF file are not changing.

### Expected/desired behavior
The pages of the PDF file should change accordingly.

### Environment

* **Kendo UI version:** 2023.1.314
* **Browser:** [all]

**Comment by piotr-placzek** [comment]
I'm using v 16.8 and this problem still exists. Has anything been done to resolve this?
