### ISSUE TITLE
Menu has incorrect rendering after unification

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#7304]
### Bug report

The menu should have a **div** with "**k-menu-popup k-popup**" classes wrapping the **ul**. Currently k-menu-popup is not even present. Can be checked by running [this ](https://demos.telerik.com/kendo-ui/menu/index)demo and inspecting the animation containers. Rendering can be checked [here](https://github.com/telerik/kendo-themes/blob/develop/tests/menu/menu.html#L48-L87). 

### Reproduction of the problem
Inspect rendering of animation containers from [this ](https://demos.telerik.com/kendo-ui/menu/index)demo

### Current behavior
Rendering lacks classes and a wrapper element

### Expected/desired behavior
Rendering should have an additional element with classes

### Environment

All

**Comment by dtopuzov** [comment]
The fix will be released with 2023 R2.
