### ISSUE TITLE
Resizing a frozen column in Grid causes row cell misalignment

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7305]
### Bug report

When you decrease the width of a frozen column in the Grid, eventually it will become misaligned against the preceding column.

[Video to demonstrate the behaviour](http://somup.com/c0fbjJ4TEG)

**Regression introduced with 2023.1.314**

### Reproduction of the problem
1. Open the Grid Frozen column demo - https://demos.telerik.com/kendo-ui/grid/frozen-columns
2. Resize the Ship Name column to reduce its width

### Current behavior

The column becomes misaligned when reducing the width.

### Expected/desired behavior

The column should remain aligned.

### Environment

* **Kendo UI version:** 2023.1.314
* **Browser:** [all]

**Comment by gdenchevprog** [comment]
Seems to no longer be reproducible as of 2023.2.606
