### ISSUE TITLE
Switch is not working in Chrome on Android devices

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7313]
### Bug report

Switch component can not be turned on/off in Chrome on Android devices.

### Reproduction of the problem
1. [Open the demos](https://demos.telerik.com/kendo-ui/switch/index) in Chrome on Android device in mobile mode.

### Current behavior
The Switch can not be turned on/off.  
The Switch works as expected when the browsers is switched to desktop mode.

### Expected/desired behavior
The Switch should work as expected in Chrome in Andorid. 

### Environment

* **Kendo UI version:** 2023.1.314
* **Browser:** [all ]

**Comment by nelito987** [comment]
Reported in ticket ID: 1607627

**Comment by sspasova** [comment]
I am closing this because the issue is no longer reproducible with Kendo UI 2023.3.1114. Tested on Android & iOS.
