### ISSUE TITLE
Popover does not show when mouse is moved with normal speed

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7314]
### Bug report

The popover does not show when the mouse is moved normally. It will show only when the mouse is moved very slowly.

### Reproduction of the problem
1. Open the dojo - https://dojo.telerik.com/@NeliKondova/UniXoPuJ
2. Move the mouse

### Current behavior
Popover is not displayed over every item but on every second item. It is displayed on every item only if the mouse moves slowly.

### Expected/desired behavior
The popover should show over every item.

### Environment

* **Kendo UI version:** 2023.1.314
* **Browser:** [all]

**Comment by pepinho24** [comment]
Most probably caused by the same bug as https://github.com/telerik/kendo-ui-core/issues/7283
