### ISSUE TITLE
DropDownList's width changes based on selected value

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#7315]
### Bug report

The DropDownList stretches to adapt to the length of the selected item.

### Reproduction of the problem
1. Run [this Dojo](https://dojo.telerik.com/@sspasova/aRuGeQuX)
2. Change the selected item

### Expected/desired behavior
The width of the DropDownList should be consistent.

### Environment

* **Kendo UI version:** 2023.3.1114

**Comment by aleksandarevangelatov** [comment]
The DropDownList's wrapper has a `.k-picker` class applied. The class sets the width of the component to `width:100%;`. Thus the component will expand to fill the container element. In the provided example non of the containers has any width defined, thus the observed behavior is expected - the DropDownList's wrapper will expand to 100% of the document's body. 

To set a specific width of the DropDownList either [set a width of the container element](https://dojo.telerik.com/EGUYOXEh), e.g:
```
.-k-w-300 {
    width: 300px;
}
```
or [set the desired width on the `<input />` element](https://dojo.telerik.com/EGUYOXEh/2) used for initialization of the DropDownList.
