### ISSUE TITLE
Grid Toolbar does not add attributes correctly

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#7326]
### Bug report

The Grid's Toolbar only renders one class out of a listed set when the attributes are set as a string
```JavaScript
    attr: ' class="esp-export-excel esp-exportTool  esp-tb-btn"'
```
This is a regression bug introduced in 2023.1.314.

### Reproduction of the problem
1. Run [this REPL](https://netcorerepl.telerik.com/mRYfOcvQ323JbC3T08)
2. Inspect the `Excel Export` button of the Grid

The wrappers serialize the attributes as a string.

### Expected/desired behavior
All of the classes passed to the  HtmlAttributes object must be rendered.

### Environment

* **Kendo UI version:** 2023.1.314

**Comment by aleksandarevangelatov** [comment]
Probably related to https://github.com/telerik/kendo-ui-core/issues/7266

**Comment by marcmss** [comment]
Not sure if it is related but if you add a style attribute and the attribute value contains a space, it get truncated at the space.
You can see it here: https://netcorerepl.telerik.com/cdYfwHbP49ggdqLC50

**Comment by Dimitar-Goshev** [comment]
@marcmss The respective issue is not reproducible on my side after the fix. The fix will be included in the coming R2 2023 release.
