### ISSUE TITLE
Missing class k-list-container of DropDownList's popup element

### ISSUE THREAD

**Issue by grozevg** [telerik/kendo-ui-core#7327]
### Bug report

The DropDownList's popup should have a **div** with "**k-list-container k-popup**" classes. Currently, **k-list-container** is missing. Rendering can be checked [here](https://github.com/telerik/kendo-themes/blob/develop/tests/popup/popup-list.html#L38). 

### Reproduction of the problem
Inspect the rendering of DropDownList's popup

### Current behavior
Rendering lacks a class

### Expected/desired behavior
Rendering should have an additional class

### Environment

All

**Comment by grozevg** [comment]
1607704

**Comment by Dimitar-Goshev** [comment]
@Juveniel @TeyaVes I see there is rendering test for [opened dropdownlist](https://github.com/telerik/kendo-themes/blob/develop/tests/dropdownlist/dropdownlist-opened.html#L33) and other components with popup. And `k-list-container` is not added to them as well and also there is no animation container. Should the popup-list rendering be the base for the other list "-opened" tests?
