### ISSUE TITLE
Attributes handler overload is not executed when a column is hidden

### ISSUE THREAD

**Issue by alestoya** [telerik/kendo-ui-core#7329]
### Bug report

The [attributes](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/columns.attributes) handler overload does not get executed when the column is initially marked as hidden.

### Reproduction of the problem

1. Open the following [dojo](https://dojo.telerik.com/@sspasova/uduSulOv).
2. Change the `hidden` property of the **ContactTitle** field to `true`.

### Current behavior

The attributes handler is not executed when the column is hidden.

### Expected/desired behavior
The attributes handler should be executed when the column is hidden.

### Environment

* **Kendo UI version:** 2024.1.130
* **Browser:** [all]

**Comment by mihaela-lukanova** [comment]
Increased priority due to a report in 1618460.

**Comment by gdenchevprog** [comment]
No longer reproducible with the latest release:

https://dojo.telerik.com/lrxLFYyS
