### ISSUE TITLE
The DropDownList does not change its popup height when items added/removed from its source

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#7334]
### Bug report

The DropDownList does not change its popup height when items added/removed from its source.

This is a regression introduced with 2023.1.314 release.

### Reproduction of the problem

- Run the following Dojo: https://dojo.telerik.com/aCoHAZuK/4
- Add new item to the list
- Open the popup again - a vertical scroll will be present, while the popup should be resized to display all the three items

### Expected/desired behavior

The popup height should change according to the new number of items.

### Environment

* **Kendo UI version:** 2023.1.425
* **Browser:** [all]

**Comment by martintabakov** [comment]
Possible workaround - https://dojo.telerik.com/aCoHAZuK/7

**Comment by PMcDonough11** [comment]
Reported in 1613429

**Comment by StoyanGoranov** [comment]
> Possible workaround - https://dojo.telerik.com/aCoHAZuK/7

The workaround doesn't work reliably: https://dojo.telerik.com/@Stoyan/iXErobAN

**Comment by alestoya** [comment]
Reported in: 1616542

**Comment by zstoyanova9** [comment]
Reported in: 1618149

**Comment by nelito987** [comment]
Reported in ticket: 1619014

**Comment by mselley** [comment]
Hi,
any update on this or a reliable workaround?

**Comment by gdenchevprog** [comment]
Seems to be working with the latest version:

https://dojo.telerik.com/@gdenchev/IhEZIgeY
