### ISSUE TITLE
MultiSelect k-disabled class remains in tags after enabling the component

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#7341]
### Reproduction of the problem
Dojo: [https://dojo.telerik.com/oQeDIxUv](https://dojo.telerik.com/oQeDIxUv)

1. Inspect the selected tag of the MultiSelect. It has the k-disabled class. 
2. Click the anchor above the component to enable it. 

### Current behavior
After the component is enabled, the k-disabled class remains in the tag. 

### Expected/desired behavior
The k-disabled class is removed. 

### Environment

* **Kendo UI version:** 2023.1.425
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by sspasova** [comment]
I am closing this issue because it is no longer reproducible using Kendo UI version 2023.3.1114. I am linking a working Dojo example -> https://dojo.telerik.com/oQeDIxUv/2
