### ISSUE TITLE
Filters are not rendered on TreeList when it is in a tab of a TabStrip.

### ISSUE THREAD

**Issue by antonmironovv** [telerik/kendo-ui-core#7342]
### Bug report

Filters are not rendered on TreeList when it is in a tab of a TabStrip.

### Reproduction of the problem

1. Implement a Telerik UI TabStrip with two tabs.
2. In one of the tabs add a filterable TreeList.
3. In the other tab add a filterable Grid.

### Current behavior

When the tab with the Grid is opened by default, the TreeList does not have filter icons.

### Expected/desired behavior

The TreeList should be rendered with filter icons.

### Environment

* **Kendo UI version:** 2023.1.425
* **jQuery version:** 3.4.1.
* **Browser:** [all]

**Comment by veselints** [comment]
We must change the expression that looks for the header cell to:
```
COLUMNHEADERATTR = ".k-table-th"
```

**Comment by veselints** [comment]
PR here: https://github.com/telerik/kendo/pull/17914
