### ISSUE TITLE
Warning due to usage of strlen in the PanelBar

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-ui-core#7351]
### Bug report

In the source code for the PHP PanelBar, the strlen function is used to retrieve the length of the contentUrl property. This property can be null as the `contentUrl` property isn't required to use the PanelBar. For example, when you wish to initialize the PanelBar using existing HTML.

Starting v8.1 of PHP, `strlen` cannot accept null values and this leads to the following warning:

`Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in ...\kendo\wrappers\php\lib\Kendo\UI\PanelBar.php on line 24`

### Reproduction of the problem

Initialize a PHP PanelBar without providing the `contentUrl` property.

### Current behavior

The above warning will appear.

### Expected/desired behavior

The `contentUrl` property should be checked for null values before the `strlen` function is called.

### Environment

* **Kendo UI version:** 2023.1.425
* **PHP version:** 8.2
* **jQuery version:** 3.6.0
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
Closing the bug due to the deprecation of the PHP wrappers.
