### ISSUE TITLE
Upload submit button opens the Select files popup in iOS

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7352]
### Bug report

When the 'Select files' button and the 'Submit' button are rendered close to each other and the 'Submit' button is clicked the 'Select files' popup is opened. Thus, the selected file could not be submitted. The issue appears on IOS in Safari and Chrome. 

### Reproduction of the problem
1. Open the [Dojo linked here](https://dojo.telerik.com/@NeliKondova/aGUnEyan) on iOS device
2. Click the 'Submit' button

### Current behavior
The 'Select files' popup is opened.

### Expected/desired behavior
In case there are selected files when the submit button is clicked, the files should be submitted. The 'Select files' popup should not be opened. 

### Environment

* **Kendo UI version:** 2023.1.425
* **Browser:** [ iOS XX Safari | iOS Chrome ]

**Comment by antonmironovv** [comment]
Reported in ticket #1609300

**Comment by pepinho24** [comment]
It might get resolved once this is fixed: https://github.com/telerik/kendo-ui-core/issues/7284

**Comment by alestoya** [comment]
The current workaround would be to:

- Explicitly incorporate the following CSS rule:
  ```
  <style>
       .k-upload-button-wrap input{
          z-index: 0;
      }
  </style>
  ```
-  From there, through client-side intervention, explicitly the click method of following the sibling of the `Select Files` button.
   ```
   <script>
      $(document).ready(function() {
          $("#files").kendoUpload();
          $(document).on("click", ".k-upload-button-wrap .k-button", function(ev) {
             $(ev.target).next("[type=file]").click();
          })
      });
    </script>
   ```
The following [dojo](https://dojo.telerik.com/@pmilchev/AmemiQik) example tackles the aforementioned approach.

**Comment by gdenchevprog** [comment]
This could potentially be related to the following issue:
https://github.com/telerik/kendo-themes/issues/4682

**Comment by martintabakov** [comment]
Also reported in 1627909
