### ISSUE TITLE
Menu item does not close when scrollable and closeOnClick are enabled

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7354]
### Bug report

When scrollable and closeOnClick are enabled and the user click on an item, the Menu does not close.

### Reproduction of the problem
1. Open the Dojo - https://dojo.telerik.com/@NeliKondova/AwaqAqIP
2. Click on an item in the Menu.

### Current behavior
The Menu does not close.

### Expected/desired behavior
The Menu should close after the user click on an item. 

### Environment

* **Kendo UI version:** 2023.1.425
* **Browser:** [all  ]

**Comment by elizondg** [comment]
Hello, I just found out same issue with newest version of Kendo.

**Comment by gdenchevprog** [comment]
Hi, @elizondg 

I tested the Dojo from the initial comment using the latest version here:
https://dojo.telerik.com/rgnhpvkA

However, it seems to be working as expected.

Could you share a Dojo with a broken example so that I can take a look at it?
