### ISSUE TITLE
Tooltip flickers when being shown multiple times

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-ui-core#7361]
### Bug report

When the tooltip is being displayed time and time again at a certain point it starts to flicker.

### Reproduction of the problem
1. Open the dojo - https://dojo.telerik.com/@sspasova/ufoQAley
2. Hover over the svg until a tooltip is displayed
3. Hover over the body
4. Hover on the svg again and hold
5. Repeat the above steps until the tooltip begins to flicker

### Current behavior
The tooltip flickers

### Expected/desired behavior
The tooltip should not flicker

### Environment
* **Kendo UI version:** 2023.3.1114
* **Browser:** [all ]

**Comment by sspasova** [comment]
The flickering is fixed but the tooltip sometimes disappears unexpectedly. The fix needs to be reviewed.
