### ISSUE TITLE
Grid pager buttons rendered as anchor elements

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#7366]
### Bug report
Not reproducible with the UI for ASP.NET Core Grid helper. 

### Reproduction of the problem
1. Set the Total option of the DataSource in a Grid:

```
.DataSource(dataSource => dataSource
    .Ajax()
    .PageSize(15)
    .Read(read => read.Action("Orders_Read", "Grid"))
    .Total(50)
)
```

2. Compare the rendering of the pager "next page" and "last page" buttons with the **Total** option set and without it.

### Current behavior
The "next page" and "last page" buttons in the Grid's pager are rendered as anchor Html elements when Total is set in the DataSource. When it is not set, the buttons are rendered as button Html elements. 

### Expected/desired behavior
The rendering of the pager buttons should be consistent and they should render as button Html elements.

### Environment

* **Kendo UI version:** 2023.1.425(regression after R1 2023. The 2022.3.1109 version is the last one with the old behavior)
* **jQuery version:** x.y
* **Browser:** [all]

**Comment by antonmironovv** [comment]
Reported in ticket #1611942

**Comment by IvanDanchev** [comment]
Model binding is another scenario, in which the pager's buttons are rendered as anchors:

```
@model IEnumerable<GridInJqueryDialog.Models.OrderViewModel>
@(Html.Kendo().Grid(Model)
    .Name("grid")
    .Columns(columns =>
    {
        columns.Bound(p => p.OrderID).Filterable(false);
        columns.Bound(p => p.Freight);
        columns.Bound(p => p.OrderDate).Format("{0:MM/dd/yyyy}");
        columns.Bound(p => p.ShipName);
        columns.Bound(p => p.ShipCity);
    })
    .Pageable(p => p.Enabled(true).PageSizes(new int[] { 10, 20, 100, 500 }))
    .Scrollable(a => a.Height(350))
    .Resizable(resize => resize.Columns(true))
    .Sortable(a => a.Enabled(true))
    .DataSource(dataSource => dataSource
        .Ajax()
        .ServerOperation(false)
        .PageSize(20)
    )
)
```

**Comment by aleksandarevangelatov** [comment]
> Re-opening the issue, since there is another case that must be covered: binding to the model, but with DataSource **.Server()**
> 
> ```
> @model TelerikMvcApp2.Models.SampleModel
> 
> 
> @(Html.Kendo().Grid(Model.GridData)
>     .Name("grid")
>     .EnableCustomBinding(true)
>     .Columns(col =>
>     {
>         col.Bound(o => o.OrderID);
>         col.Bound(o => o.ShipName);
>         col.Bound(o => o.ShipCountry);
>     })
>     .Scrollable()
>     .Sortable(a => a.Enabled(true))
>     .Pageable(a => a.Enabled(true).Responsive(false).Info(true))
>     .DataSource(dataSource => dataSource
>         .Server()
>         .PageSize(10)
>         .Total(50)
>     )
> )
> ```

The above configuration is a valid scenario when anchor tags should be rendered. When the Telerik UI for [ASP.NET MVC Grid is configured for server binding](https://docs.telerik.com/aspnet-mvc/html-helpers/data-management/grid/binding/server-binding) it will render anchor tags instead of buttons and will make a `HTTP GET` requests when paging. Use [Ajax binding](https://docs.telerik.com/aspnet-mvc/html-helpers/data-management/grid/binding/ajax-binding), as in the [comment above](https://github.com/telerik/kendo-ui-core/issues/7366#issuecomment-1628775151) in order for the Telerik UI for ASP.NET MVC Grid to render buttons and make ajax requests for data when paging is performed.
