### ISSUE TITLE
kendo.dateinput.js and kendo.datepicker.js are missing 

### ISSUE THREAD

**Issue by ddTech** [telerik/kendo-ui-core#7368]
the two files kendo.dateinput.js and kendo.datepicker.js are missing in the download and not listed under src.

**Comment by Dimitar-Goshev** [comment]
@ddTech Thank you for you feedback. The files are now available again - https://github.com/telerik/kendo-ui-core/commit/db16f60ee6ee43506173a9628723b3de1ed73266
