### ISSUE TITLE
Improve the performance of the slotByElement method in Scheduler

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7380]
When the **_slotByElement_** method is used for multiple elements this could lead to performance issues in Scheduler. 
For example the difference in the performance can be observed in the Dojo examples linked below when loading the Scheduler and when changing the selected resources:
- Dojo with 2023.1.314 - https://dojo.telerik.com/@NeliKondova/UJOcEJoC
- Dojo with 2023.1.425 - https://dojo.telerik.com/@NeliKondova/UHisivuC

The issue occurs starting with the 2023 R1 SP1 release and could be due to the following fix - https://github.com/telerik/kendo-ui-core/issues/7260

**Comment by gurpreet48** [comment]
When trying to fetch the information of the cell with the help of slotByElement. It's very slow and takes to slow load the scheduler in comparison to the previous versions. Please do it on urgent bases.

**Comment by gdenchevprog** [comment]
Requested several more time in the public item - 1612730
