### ISSUE TITLE
Navigatable Grid with Row filter mode and detailTemplate does not execute filter

### ISSUE THREAD

**Issue by antonmironovv** [telerik/kendo-ui-core#7384]
### Bug report
Navigatable Grid with Row filter Mode does not execute the filter for the first column when the Enter key is used. The issue is represented when a detailTemplate is used.

Used to work before the focus changes in R3 2022.

### Reproduction of the problem
1. Open [this dojo example](https://dojo.telerik.com/@anton.mironov/uneFUKIc).
2. In the first column filter input type "Nancy".
3. Press the Enter key.

### Current behavior
The filter is not executed and the input value of the filter is cleared.

### Expected/desired behavior
The filter should apply to the first column.

### TicketID:
1612562

### Environment
* **Kendo UI version:** 2023.2.606
* **Browser:** [all]

**Comment by sayassyk** [comment]
Hi Dears,
Any further updates on this? We are waiting for this bugfix!

**Comment by Dimitar-Goshev** [comment]
Hi, @sayassyk ,
The issue is fixed and the fix is scheduled for the next release at the end of August.
