### ISSUE TITLE
The repeatHeaders option of the Grid is not working

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7386]
### Bug report

The Grid's pdf.repeatHeaders option does not display the column headers for each new page when exporting the Grid to PDF

**Regression introduced with 2023.1.314**

### Reproduction of the problem

1. Open the Grid  Export to PDF demo - https://demos.telerik.com/kendo-ui/grid/pdf-export
2. Export the Grid

### Current behavior

The column headers are displayed only on the first PDF page

### Expected/desired behavior
The column headers should be present for each PDF page

### Environment

* **Kendo UI version:** 2023.2.606
* **Browser:** [all]

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1614027
