### ISSUE TITLE
ListBox's toolbar buttons are at the "top" if the position is set to "bottom"

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7390]
### Bug report

The ListBox toolbar buttons are set to "top" even if you set the toolbar position to "bottom"

**Regression with v2023.1.314** 

**Workaround - https://dojo.telerik.com/@sspasova/epIHUpAh**

### Reproduction of the problem

Open this Dojo example - https://dojo.telerik.com/@sspasova/ElIcOFIL

### Current behavior
The toolbar buttons are at the top

### Expected/desired behavior
The toolbar buttons should be visible on the bottom

### Environment

* **Kendo UI version:** 2023.3.1114
* **Browser:** [all]

**Comment by gdenchevprog** [comment]
Related - https://github.com/telerik/kendo-themes/issues/4704
