### ISSUE TITLE
Kendo Editor with Angular 14

### ISSUE THREAD

**Issue by Mohanbr1** [telerik/kendo-ui-core#7391]
### Reproduction of the problem
_(bug report only)_
Kendo editor giving build error with angular 14.
![IMG_5255](https://github.com/telerik/kendo-ui-core/assets/137368235/3629fcb5-6eec-42af-b428-594cbaa60c69)
Please see above build error in screenshot. Kendo editor Prosemirror-view conflicting with angular prose mirror.

### Current behavior
_(optional)_
Provide additional information if the steps for reproducing the faulty behavior are not sufficient to describe the issue.

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment

* **Kendo UI version:** latest
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Dimitar-Goshev** [comment]
Hello @Mohanbr1 . This repository is for issues about Kendo UI for jQuery. Please use the Kendo UI for Angular Issue tracker repository https://github.com/telerik/kendo-angular/issues to search for and log the current issue.
