### ISSUE TITLE
Editing a Grid cell with enter key causes the Grid to scroll to the top.

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7396]
### Bug report

In an in-cell edit mode, if you edit a Grid cell with enter key, the Grid will scroll to the top.

Regression introduced with v2020.3.1021

### Reproduction of the problem

1. Open this Dojo example - https://dojo.telerik.com/ICoceZUp/3
2. Scroll to the one of the last items 
3. Edit a cell
4. Close the cell with Enter key

### Current behavior
The Grid scrolls to the top

### Expected/desired behavior
The Grid shouldn't scroll to the top.
### Environment

* **Kendo UI version:** 2023.2.606
* **Browser:** [all]

**Comment by mihaela-lukanova** [comment]
The same behavior occurs when:

- The "navigatable" option is enabled.
- The Grid is configured for "InLine" editing.
- Scroll down, edit a specified row, and click the "Save" command.
A Dojo sample for reproduction: https://dojo.telerik.com/etUsoPEb
