### ISSUE TITLE
Missing size class when using template for Grid toolbar

### ISSUE THREAD

**Issue by palhal** [telerik/kendo-ui-core#7403]
### Bug report
When using a custom template as grid toolbar, a `k-toolbar-{size}` class is missing from the toolbar container element.

### Reproduction of the problem
Render a grid with a custom toolbar:

```js
$("#grid").kendoGrid({
    // toolbar: ['create']
    toolbar: 'My grid'
})
```

### Current behavior
In 2023.1.117 and earlier, the built-in (create) toolbar and custom (My grid) toolbar are rendered equally as
```html
<div class="k-grid-toolbar k-toolbar">...</div>
```

In 2023.1.314 and later, the built-in toolbar is rendered as
```html
<div class="k-grid-toolbar k-toolbar k-toolbar-md">...</div>
```

but the custom toolbar is rendered as
```html
<div class="k-grid-toolbar k-toolbar">My grid</div>
```

### Expected/desired behavior
The toolbar is rendered with a size class according to the `size` parameter of the grid, also when using a template.

 ```html
<div class="k-grid-toolbar k-toolbar k-toolbar-{size}">My grid</div>
```

### Workaround
```js
$('.k-grid > .k-toolbar').addClass('k-toolbar-md')
```

### Environment

* **Kendo UI version:** 2023.2.606
* **jQuery version:** 3.6.2

### Edit
I see now that toolbars without a size class can be modified in SASS with the `$kendo-toolbar-{padding-x, padding-y, spacing}` variables. Maybe this is by design?

**Comment by ag-petrov** [comment]
Fixed in the latest versions
