### ISSUE TITLE
When tabbing in a batch editable Grid cells do not enter edit mode

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#7409]
### Bug report

When tabbing in a batch editable Grid each second cell does not enter edit mode. 
This is a regression introduced with v 2023.2.606.

### Reproduction of the problem
1. Run [this dojo](https://dojo.telerik.com/@AleksandarEvangelatov/EcigAqaQ)
2. Click on a cell in Product Name column - an editor is generated
3. Press the Tab key

### Current behavior
The corresponding Unit Price is focused, but an editor is not generated

### Expected/desired behavior
The cell should enter edit mode, as with v2023.1.425 - [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/uJOmUWuT)

### Environment

* **Kendo UI version:** 2023.2.606
* **Browser:** [all]

**Comment by mihaela-lukanova** [comment]
Reported in 1617881

**Comment by aleksandarevangelatov** [comment]
Also reported in ticket 1618151

Another scenario when the behavior is observed is when keyboard navigation is disabled and multiple row selection enabled - [example](https://dojo.telerik.com/@AleksandarEvangelatov/UhaFinUJ)

**Comment by alestoya** [comment]
Reported in 1619448

**Comment by P1l3T0** [comment]
Reported again in 1622489

**Comment by gdenchevprog** [comment]
Again 1623120

**Comment by mihaela-lukanova** [comment]
Reported in 1623349

**Comment by mihaela-lukanova** [comment]
Reported again in 1617881

**Comment by antonmironovv** [comment]
Reported in Mozilla Firefox in ticket #1630102
