### ISSUE TITLE
TreeList cell in edit mode automatically closes when a Kendo Editor is used

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-ui-core#7416]
### Bug report

When the TreeList uses a custom editor that is the Kendo Editor component, the edited cell automatically closes as soon as it's opened and does not allow the user to interact with the editor in any way.

Reproducible only with "incell" mode.

This is a regression in the latest release. The editor seems to function as expected in 2023.1.425.

### Reproduction of the problem

1. Run the following Dojo:
https://dojo.telerik.com/@gdenchev/eREZaMIN

2. Click on one of the cells under "Last Name" and give it a second or two to load the editor. The Kendo Editor flashes for a brief moment and then closes itself.

### Current behavior

The Kendo Editor cannot be used as a cell editor.

### Expected/desired behavior

The editor should remain open until the user manually blurs the cell.

### Environment

* **Kendo UI version:** 2023.2.606(regression)
* **jQuery version:** 3.4.1
* **Browser:** [all]

**Comment by mihaela-lukanova** [comment]
The same behavior appears when the Editor is added as a custom editor of a Grid column (reported in ticket #1616355).

**Comment by eyupyusein** [comment]
Reported in 1623842
