### ISSUE TITLE
Menu popup container closes on hover when scrollable is enabled

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-ui-core#7417]
### Bug report

Menu popup container closes on hover when `scrollable` is enabled. 
This is a regression introduced with v2023.2.606.

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/eHeZemIn)
2. Hover a menu item and try to select a subitem
[screencast](https://screenrec.com/share/gyY23R1MSv)

### Current behavior
Popup container closes on hover and subitems cannot be selected.
### Expected/desired behavior
Popup container should not close on hover.

### Environment

* **Kendo UI version:** 2023.2.606
* **Browser:** [all]

**Comment by martintabakov** [comment]
Also reported in #1613808

**Comment by martintabakov** [comment]
Also reported in #1615947

**Comment by martintabakov** [comment]
Also reported in 1616745

**Comment by zstoyanova9** [comment]
Also reported in #1625401

**Comment by martintabakov** [comment]
The issue still reproduces when there is a subitem. First-time expand is OK, then the menu starts to close. https://dojo.telerik.com/uDIfAJof/4

**Comment by PekoPPT** [comment]
The issue with the subitem is also reported in ticket **1628549**
