### ISSUE TITLE
ClientX error when dragging html link

### ISSUE THREAD

**Issue by jensmeichler** [telerik/kendo-ui-core#7419]
### Reproduction of the problem
1. Create a simple grid with a template column that contains a link (eg: <a href="/">test</a>)
2. Drag this link (like you can drag every html link)

### Current behavior
The following error occurs in progress-kendo-angular-grid.mjs:
'Cannot read properties of undefined (reading 'clientX')'

### Expected/desired behavior
You can just use the drag drop feature for a link like normal, when you just use a simple grid.

### Environment

* **Kendo UI version:** 13.1.0
* **Angular CLI version:** 15.2.8
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
Hello @jensmeichler . This repository is for Kendo UI for jQuery issues. Please use the Kendo UI for Angular Issue tracker repository https://github.com/telerik/kendo-angular/issues to search for and log the current issue.
