### ISSUE TITLE
Change event is triggered in DropDownList with local data and virtualization enabled when popup is opened

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7425]
### Bug report

In a DropDownList with local data and virtualization enabled. when the value is set after initialization using the value method, the change event is fired when the component is opened and closed, without actually changing its value.

### Reproduction of the problem
1. Open the Dojo - https://dojo.telerik.com/@NeliKondova/EmOCUqiq and observe the browser console
2. Open and close the popup without selecting a value.

### Current behavior
The change event is fired.

### Expected/desired behavior
The change event should not be fired when the value is set through the value method.

### Environment

* **Kendo UI version:** 2023.2.606
* **Browser:** [all  ]

**Comment by ag-petrov** [comment]
Not reproducible with the latest version
