### ISSUE TITLE
Required Attribute Ignored for Boolean Property In Form

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#7428]
### Bug report

Using a UI for ASP.NET MVC/Core Form, if a boolean property is defined as required with the [Required] attribute, and the Hint() option is not defined, the Form does not validate the checkbox.

### Reproduction of the problem
Please visit the [following Live demo](https://demos.telerik.com/aspnet-core/form), and submit the form.  

### Current behavior
The form will submit without validating the checkbox.

### Expected/desired behavior
The Required attribute should be evaluated for validation.  

### Environment

* **Kendo UI version:** 2023.2.606
* **jQuery version:** All Supported Versions
* **Browser:** all

**Comment by gyankov** [comment]
The required attribute does not enforce true, it just enforces either true or false, which is always the case, as the framework will render two inputs with hardcoded true/false values. Thus, the inputs are never lacking value, and validation never fails.
