### ISSUE TITLE
Search icon not aligned in the filter menu since svg icons introduced.

### ISSUE THREAD

**Issue by NikoPenev21** [telerik/kendo-ui-core#7440]
### Bug report

Input is missing `k-input-icon` class. See [the HTML spec](https://github.com/telerik/kendo-themes/blob/develop/packages/html/src/searchbox/searchbox.spec.tsx#L92) for reference.

### Reproduction of the problem

Dojo: https://dojo.telerik.com/@sspasova/eqeNETIx

![image](https://github.com/telerik/kendo-ui-core/assets/46747298/e9ef7e3d-bd5e-44a6-98c2-8c8a54d92844)

### Expected/desired behavior
Search icon shall be aligned in the filter menu.

### Environment

* **Kendo UI version:** 2023.3.1114
* **jQuery version:** [all]
* **Browser:** [all]

**Comment by iordanGrancharov** [comment]
Fixed as part of https://github.com/telerik/kendo/issues/20412
