### ISSUE TITLE
Remove unnecessary dependencies added due to FontIcon and SvgIcon references

### ISSUE THREAD

**Issue by gyankov** [telerik/kendo-ui-core#7443]
As `FontIcon` and `SvgIcon` packages target netstandart, a lot of unused dependencies are downloaded once they are installed in a .Net Framework app.

Multiple clients have reported the behavior, so we should investigate a way around it. Some clients even requested a configuration to avoid adding the icons packages, as they don't use components with server rendering.

**Comment by VicTachev** [comment]
related https://github.com/telerik/kendo-icons/issues/214
