### ISSUE TITLE
Date components are missing from open-source distribution

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-ui-core#7456]
### Bug report

The Date components such as DatePicker, DateRangePicker, DateInput, etc., are missing from the open-source distribution:

![image](https://github.com/telerik/kendo-ui-core/assets/70957719/717ef8c1-4d48-4f40-809d-64b0d6535acc)

### Reproduction

You can download the open-source version of Kendo from your Telerik profile and examine it.

### Environment

* **Kendo UI version:** 2023.2.718(starting 2023.2.606)
* **jQuery version:** 3.4.1
* **Browser:** [all]

**Comment by ddTech** [comment]
they are still missing in the 2023.2.829 release  :-(
