### ISSUE TITLE
Grid Toolbar sets incorrect name property in UI for MVC

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-ui-core#7461]
### Bug report

Since Telerik UI for MVC uses server-rendering it serializes the Grid's Toolbar buttons in a different manner than the internal configuration of the `toolbar`.

```
"toolbar": [{
            "name": null,
            "text": "Export to Excel"
        }]
```
During execution this doesn't affect the behavior. However, if [Grid State Persistence](https://demos.telerik.com/aspnet-core/grid/persist-state) is employed upon loading of the saved options the Toolbar buttons don't work as expected.

Issue has occurred in version 2023.2.606.

### Reproduction of the problem
1. Inspect the serialized script of the [Grid Overview Demo for MVC](https://demos.telerik.com/aspnet-mvc/grid);
2. Find and copy the Toolbar's configuration;
3. Paste the `toolbar` options in [this Dojo](https://dojo.telerik.com/@Stoyan/ESeLOXAT) and run it to test whether the configuration is correct. 

### Expected/desired behavior
The serialized script should contain properties that correspond to the Html that is rendered for the Toolbar buttons.

### Environment

* **Kendo UI version:** 2023.2.718

**Comment by JLOrwell** [comment]
indeed, if you attempt to apply the layout to a grid, it will throw an error to the javascript console complaining that commands need to be named.

**Comment by aleksandarevangelatov** [comment]
Fixed with https://github.com/telerik/kendo/commit/56bc213ac5b50a33ebccf9d6dc7be92011da4a22
