### ISSUE TITLE
The Filter component's custom operator text does not display correctly

### ISSUE THREAD

**Issue by eyupyusein** [telerik/kendo-ui-core#7471]
### Bug report

The Filter component's custom operator text displays [Object object] instead of 'Odd numbers'.

**Regression with version 2023.2.718**

### Reproduction of the problem
You can see the issue in the live demos:
https://demos.telerik.com/kendo-ui/filter/operators

![image](https://github.com/telerik/kendo-ui-core/assets/11816856/ad2a91d5-a9b3-4341-8107-d257dfe8778a)

### Current behavior
[Object object]

### Workaround

          $('select[data-bind="value: operator"]').each(function(){
            var ddl=$(this).data().kendoDropDownList;
            var items = ddl.items();
            for (var i = 0; i < items.length; i++) {
              var item = $(items[i]);
              if(item.text()=='[object Object]'){
                item.find(".k-list-item-text").text(ddl.dataItems()[i].text.text);
              }
            }
          });
Dojo:
https://dojo.telerik.com/@sspasova/oXorebur

### Expected/desired behavior
Odd numbers

### Environment

* **Kendo UI version:** 2023.3.1114
* **jQuery version:** 3.7.0
* **Browser:** [all ]

**Comment by martintabakov** [comment]
Also reported in 1659919
