### ISSUE TITLE
Grid PopUp Edit Mode validation fires immediately on Create

### ISSUE THREAD

**Issue by antonmironovv** [telerik/kendo-ui-core#7473]
### Bug report

When creating a new item in a Grid with PopUp Edit Mode, if the first field is required string, the validation fires immediately.
This happens after version "2023.1.425"(this is the last version working as expected).

### Reproduction of the problem

Create an MVC Grid with PopUp Edit Mode in version "2023.2.606"(or the latest). The first field of the Grid should be a required string. Click the Create button.

### Current behavior

The validation for the first field fires immediately.

### Expected/desired behavior

The validation should fire only after a blur of the required input.

### Environment

* **Browser:** [all]

**Comment by antonmironovv** [comment]
Reported in tickets: #1617784 and #1618673

**Comment by alestoya** [comment]
Reported in 1621132
