### ISSUE TITLE
Context Menu contains '="" attribute

### ISSUE THREAD

**Issue by antonmironovv** [telerik/kendo-ui-core#7475]
### Bug report

When a ContextMenu is implemented for a Grid, it contains '="" attribute.

### Reproduction of the problem

Implement a ContextMenu for a Telerik UI Grid.

### Current behavior

The list items of the ContextMenu contains '="".

### Expected/desired behavior
The '="" attribute should not exist.

### Environment

* **Kendo UI version:** 2023.2.718
* **Browser:** [all]

**Comment by antonmironovv** [comment]
Reported in ticket #1619067

**Comment by antonmironovv** [comment]
The client from ticket #1219067 shared that they are experiencing the issue for context menus on a TreeList as well.

**Comment by aleksandarevangelatov** [comment]
The behavior is also observed in Kendo UI for jQuery, when a ContextMenu is initialized from local or remote data, for items that do not have child items - [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/eKOPIZaM):
![image](https://github.com/telerik/kendo-ui-core/assets/46348689/5c7619ba-42d8-43b3-a77a-2f717d3c25c0)
