### ISSUE TITLE
The pager of the Grid is not rendering correctly when placed in PanelBar

### ISSUE THREAD

**Issue by antonmironovv** [telerik/kendo-ui-core#7476]
### Bug report

When a Kendo UI Grid is nested in a Kendo UI PanelBar, the grid pagers are not rendering correctly.

### Reproduction of the problem

- Implement a Grid into a PanelBar.
- Collapse the tab of the PanelBar. 
- Expand the tab of the PanelBar.

### Current behavior

The pager of the Grid is not rendered correctly.

### Expected/desired behavior

The pager should appear correctly.

### Environment

* **Kendo UI version:** 2023.2.718
* **Browser:** [all]

**Comment by antonmironovv** [comment]
Reported in ticket #1619349

**Comment by aleksandarevangelatov** [comment]
The behavior observed is expected. When the Gird is initialized in a collapsed PanelBar item it is essentially initialized in a container with a `display: none;` style. In such scenarios the Pager may not appear or be the smallest responsible Pager, as [documented](https://docs.telerik.com/aspnet-mvc/html-helpers/data-management/grid/appearance/hidden-containers). 

In the scenario in question animation for the PanelBar is enabled, so the `resize` method should be called in the PanelBar's [`activate`](https://docs.telerik.com/kendo-ui/api/javascript/ui/panelbar/events/activate) event handler. The [`expand`](https://docs.telerik.com/kendo-ui/api/javascript/ui/panelbar/events/expand) event will fire when a PanelBar item is expanded and the `activate` event will fire when the animation has completed.
