### ISSUE TITLE
Destroying the Upload after an upload is completed results in JS error

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7484]
### Bug report

If you destroy the Upload after uploading a file, a JS error occurs in the console.

### Reproduction of the problem
1. Open this example - https://dojo.telerik.com/IVEfeMID/11
2. Upload a file

### Current behavior
An error is thrown after destroying the component

### Expected/desired behavior
No errors should be thrown

### Environment

* **Kendo UI version:** 2023.2.718
* **Browser:** [all]

**Comment by sspasova** [comment]
I am closing this issue because it is no longer reproducible with Kendo UI 2023.3.1114. I am linking a working Dojo example - https://dojo.telerik.com/@sspasova/etEqUHUV
