### ISSUE TITLE
Dependencies can not be deleted in Gantt

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7491]
### Bug report

The dependencies in the Gantt can not be removed.

### Reproduction of the problem
1. Open the demos - https://demos.telerik.com/kendo-ui/gantt/index
2. Select a dependency line and press the 'Delete' key.

### Current behavior
Nothing happens, there is no confirmation popup, and the dependency is not removed.

### Expected/desired behavior
A confirmation dialog for confirming the deletion appears and the dependency should be removed.

### Environment

* **Kendo UI version:** 2023.3.1114
* **Browser:** [all ]

**Comment by pepinho24** [comment]
Requested Design and Accessibility review of the Gantt KB spec and behavior here: https://github.com/telerik/web-components-ux/issues/942

**Comment by martintabakov** [comment]
Also reported in 1620759

**Comment by alestoya** [comment]
Reported in 1657897

**Comment by alestoya** [comment]
A workaround would be to re-add the TabIndex attribute to the Timeline Wrapper element of the Gantt

```JavaScript
<script>
    function tabIndex(target) {
        target = target;

        var element = target,
            TABINDEX = "tabindex",
            tabindex = target.attr(TABINDEX) || element.attr(TABINDEX);

        element.removeAttr(TABINDEX);
        target.attr(TABINDEX, !isNaN(tabindex) ? tabindex : 0);
    }

    $(document).ready(function () {
        // Gantt initialization logic.
        tabIndex($(".k-gantt-timeline"));
    })
</script>
```
[Dojo Example](https://dojo.telerik.com/@alexander64836/EPoqIQAd/4)

**Comment by ag-petrov** [comment]
From an accessibility stand point the editing the dependencies using the keyboard is not crucial. We have updated our UX and now the editing can be performed using the Gantt Popup Form. Closing this one.
