### ISSUE TITLE
Allow customization of the PivotGridV2 measure caption.

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-ui-core#7503]
### Enhancement

Allow customization of the measure names in the PivotGridV2 when using local data.

Take a look at the following Dojo example:

https://dojo.telerik.com/@gdenchev/UlICUFaZ

If you attempt to change the measure name from 'Sum' to 'Test', the PivotGridV2 won't allow you.

```javascript
// Allowed
measures: {
   "Sum": { field: "Revenue", format: "{0:c}", aggregate: "sum" },
}

// Not allowed
measures: {
   "Test": { field: "Revenue", format: "{0:c}", aggregate: "sum" },
}
```

 This functionality was available in the old PivotGrid.

**Comment by antonmironovv** [comment]
Reported in ticket 1620927.
