### ISSUE TITLE
Signature signing delay on Android device 

### ISSUE THREAD

**Issue by P1l3T0** [telerik/kendo-ui-core#7505]
### Reproduction of the problem
Open a **Signature** Component demo and try to draw/sign fast on an **_Android_** device.

### Current behavior
When signing fast on an _**Android**_ device on the Signature component, making a signature from multiple parts by picking up the finger several times, the signature process freezes for a small period of time.
See attached videos where we tested on Android and IOS devices:

[Android](https://github.com/telerik/kendo-ui-core/assets/95146724/2e7afde5-c0e8-4947-b66c-764b251fe8c9)
[IOS](https://github.com/telerik/kendo-ui-core/assets/95146724/731a3a60-f95b-480f-ab02-b116ed2c6e13)

### Expected/desired behavior
Signing/drawing should be smooth

### Environment

* **Kendo UI version:** 2023.2.829
* **Browser:** [Android Chrome]

**Comment by ag-petrov** [comment]
Seems to be working fine with the latest versions
