### ISSUE TITLE
Using defineName method to create qualified names in the Spreadsheet does not work correctly

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7512]
### Bug report

When the reference to a cell in a specific Sheet is added in the defineName function, using the name leads to invalid result. 

### Reproduction of the problem
1. Open the Dojo - https://dojo.telerik.com/@NeliKondova/eWeVASOK
2. Select a cell and type '=Foo'

### Current behavior
The returned result is '#NAME?'

### Expected/desired behavior
The returned result should depend on the referenced cell value. In the example above B2 have a value 5, thus the value in the selected cell should be also 5.

The issue also appears when importing an Excel file with defined names in the Spreadsheet. The names in the attached Excel file are created as in the image below:
![image](https://github.com/telerik/kendo-ui-core/assets/14364791/bf46cd18-53bf-4da0-adc5-beb14ec38236)

[test.xlsx](https://github.com/telerik/kendo-ui-core/files/12551122/test.xlsx)

### Environment

* **Kendo UI version:** 2023.2.829
* **Browser:** [all ]

**Comment by NikoPenev21** [comment]
Another report from another user in the original thread #1622773
