### ISSUE TITLE
Cancelling row changes while there is a hidden column breaks the layout of the content.

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-ui-core#7514]
### Bug report

When a column is hidden and row changes are cancelled, the layout of the Grid content breaks. This can happen both when the `hidden` property is set to true and when `media` queries are used.

### Reproduction of the problem

Run the following Dojo:

https://dojo.telerik.com/@gdenchev/eSureJOV

Click on one of the rows to edit it.
Close the popup by clicking on "Cancel".

### Current behavior

The layout of the Grid gets messed up.

![image](https://github.com/telerik/kendo-ui-core/assets/70957719/755c53c9-b1b8-42b5-bab5-c60510d98c38)

### Expected/desired behavior

The layout should not be affected by the cancellation of the changes.

### Environment

* **Kendo UI version:** 2023.2.829 (Regression starting this version)
* **jQuery version:** 3.4.1
* **Browser:** [all]

**Comment by vzsoft** [comment]
[show hide column in the row and messing up the row on popup edit click cancel button](https://github.com/telerik/kendo-ui-core/issues/7507)

**Comment by alestoya** [comment]
Reported in 1625011

**Comment by pepinho24** [comment]
Should be fixed with https://github.com/telerik/kendo/pull/18723

**Comment by drmcleod** [comment]
If anyone is looking for a temp solution, you can add this style to your page to fix the issue.

td[data-style-display="none"] {
    display:none;
}
