### ISSUE TITLE
Canceling Inline/Popup Edit Displays Hidden Columns

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#7515]
### Bug report

When a user cancels an inline edit, hidden columns appear instead of staying hidden.

### Reproduction of the problem

1. Go to [this Progress Kendo UI Dojo](https://dojo.telerik.com/@PMcDonou/IwosAMEM)
2. Click Edit, and cancel the edit

### Expected/desired behavior
The hidden columns should remain hidden upon canceling an edited row.

### Environment

* **Kendo UI version:** 2023.2.829
* **jQuery version:** All Supported Versions
* **Browser:** all

**Comment by PMcDonough11** [comment]
This behavior is also occurring in popup editing([dojo](https://dojo.telerik.com/@PMcDonou/AzoSEkip)).

**Comment by vzsoft** [comment]
[issues-7514](https://github.com/telerik/kendo-ui-core/issues/7514)
[issues-7507](https://github.com/telerik/kendo-ui-core/issues/7507)

**Comment by nelito987** [comment]
Reported in ticket ID: 1624093
