### ISSUE TITLE
Grid Pager doesn't show on load 

### ISSUE THREAD

**Issue by P1l3T0** [telerik/kendo-ui-core#7520]
### Bug report
When bound to local data the Pager items of the Grid are initially hidden.
This is a regression introduced with v2023.2.829

### Reproduction of the problem
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/AJuFEpef/2)
2. Note the defined pager items are missing

Reproduction with HTML Helpers:
Have a Grid bound to local data (see below code snippets and screenshot)
```
@model Pager_issue.Models.GridViewModel

@(Html.Kendo().Grid(Model.Items)
    .Name("grid")
    .Columns(columns =>
    {
        columns.Bound(p => p.OrderID).Filterable(false);
        columns.Bound(p => p.Freight);
        columns.Bound(p => p.OrderDate).Format("{0:MM/dd/yyyy}");
        columns.Bound(p => p.ShipName);
        columns.Bound(p => p.ShipCity);
    })
    .Pageable(p => p.PageSizes(new[] { "5", "10", "50", "all" }).PreviousNext(false))
    .Sortable()
    .Scrollable()
    .Filterable()
    .HtmlAttributes(new { style = "height:550px;" })
    .DataSource(dataSource => dataSource
        .Ajax()
        .Batch(true)
        .ServerOperation(false)
    )
)
```

```
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var model = new GridViewModel
            {
                Items = Enumerable.Range(0, 200).Select(i => new OrderViewModel
                {
                    OrderID = i,
                    Freight = i * 10,
                    OrderDate = DateTime.Now.AddDays(i),
                    ShipName = "ShipName " + i,
                    ShipCity = "ShipCity " + i
                })
            };

            return View(model);
        }
```

![no pager](https://github.com/telerik/kendo-ui-core/assets/95146724/611dd4e4-49f5-4ecc-9f1e-eb56df1a42aa)

### Current behavior
When filling the Grid with data via a ViewModel, the pager doesn't show on load

### Expected/desired behavior
The pager should be visible on load

### Workaround
A possible workaround is to disable the responsive behavior of the Pager via the [pageable.responsive](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/pageable.responsive) option or when using the HTML Helpers:
```
 .Pageable(p => p.PageSizes(new[] { "5", "10", "50", "all" }).PreviousNext(false).Responsive(false))
```

### Environment

* **Kendo UI version:** 2023.2.829
* **Browser:** [all]

**Comment by pepinho24** [comment]
Should be fixed with 18701
