### ISSUE TITLE
Chart Wrapper with .Aggregate(ChartSeriesAggregate.SumOrNull) throwns an error

### ISSUE THREAD

**Issue by eyupyusein** [telerik/kendo-ui-core#7524]
### Bug report
The same data and project works properly with `.Aggregate(ChartSeriesAggregate.Sum)`.

### Reproduction of the problem
Download and run the project from this link:
https://supportheroes.telerik.com/clientsfiles/29bc090e-c558-4023-98fe-4958be506e77_telerikmvcapp9.zip

### Expected/desired behavior
The Chart should function properly with `.Aggregate(ChartSeriesAggregate.SumOrNull)` as well.

**Comment by raphaotten** [comment]
The parameter "sumornull" is written without capitalized letters.

Is uses "sumornull" in the javascript instead of "sumOrNull"
