### ISSUE TITLE
DataSource filter method performance is getting slower

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7529]
### Bug report

The performance when using the filter method to filter the data in DataSource and Hierarchical datasource is decreased.

### Reproduction of the problem
1. Open the following Dojo example and test it with different Kendo versions: - https://dojo.telerik.com/@NeliKondova/UGomaNEX

### Current behavior
There is a perfromance decrease when using the filter method with the latest Kendo version:
![image](https://github.com/telerik/kendo-ui-core/assets/14364791/1542b5fb-2bee-4f24-b73a-703441f5f840)

### Expected/desired behavior
The performance of the filter method should be improved.

### Environment

* **Kendo UI version:** 2023.2.829
* **Browser:** [all]

**Comment by ag-petrov** [comment]
There seems to be a slight delay but the general scenario is a problematic one. When having such large sets of data server filtering is a must.
