### ISSUE TITLE
Widget does not render the items when autoBind is set to false and source is bound

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#753]
#### Description: 
ComboBox widget in grid custom editor template does not request its data when autoBind is set to false. Initially it works fine, but it fails on each subsequent opening.

Repro demo: http://dojo.telerik.com/@boyan.dim/InevU (use version 2015.1.408)

Repro steps:
1. Open the Products combobox (try to edit any Product Name) and click the arrow. It works fine. 
2. Click anywhere on the page in order to loose the foces. 
3. Repeat the first step. There is no request to the server and there is no data in the combobox. 

Reported in TicketID: 928019

**Comment by naskog** [comment]
When you enter edit mode (after step one) current value disappears

Navigate to: [http://dojo.telerik.com/@naskog/icEHA](http://dojo.telerik.com/@naskog/icEHA)
Click in the first column
Result: You do not see the value you clicked on when you enter edit mode
