### ISSUE TITLE
Calling setOptions on a disabled NumericTextBox enables the component

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-ui-core#7546]
### Bug report

When you have a disabled numerictextbox and the setOptions method is called, the component gets enabled.

### Reproduction of the problem

Run the following Dojo:

https://dojo.telerik.com/@gdenchev/aQEnAlic

Click on the button and observe the result.

### Current behavior

The numerictextbox becomes enabled.

### Expected/desired behavior

The numerictextbox should remain disabled after setOptions is called.

### Environment

* **Kendo UI version:** 2023.2.829 (Last working version 2022.3.913)
* **jQuery version:** 3.4.1
* **Browser:** [all]

**Comment by pepinho24** [comment]
the case looks similar to a fixed issue for the date picker https://github.com/telerik/kendo-ui-core/issues/6885
