### ISSUE TITLE
Grid popup editor cancel shows hidden columns in grid

### ISSUE THREAD

**Issue by mdstevensjr** [telerik/kendo-ui-core#7555]
### Bug report
When you have a grid with hidden columns, they are displayed after cancelling edit.

### Reproduction of the problem
Can be reproduced here - https://dojo.telerik.com/@mstevens@kingschools.com/UXeDUHUB
1. Click Edit
2. Then Cancel

### Current behavior
Columns configured as hidden are displayed in the grid after cancelling an edit.

### Expected/desired behavior
Columns configured as hidden should not be displayed in the grid after cancelling an edit.

### Environment

* **Kendo UI version:** 2023.2.829
* **jQuery version:** 3.6.4
* **Browser:** all

**Comment by martintabakov** [comment]
Duplicated of #7514
