### ISSUE TITLE
TreeList resets its column template when expanding

### ISSUE THREAD

**Issue by eyupyusein** [telerik/kendo-ui-core#7583]
### Bug report

There is a regression issue with the treelist column template - the content state is no longer preserved when expanding another parent row.

### Reproduction of the problem
1. Open this dojo built with version 2022.1.119:
https://dojo.telerik.com/OdaNIFap/3
2. Click on the first CEO checkbox.
3. Expand the second item
4. Expected Result - the checked state is preserved:

![image](https://github.com/telerik/kendo-ui-core/assets/11816856/10477b74-f753-422a-9d1d-03efccd62826)

Now, do the same with version 2023.3.1010 and the result is that the checkbox selection is cleared:
https://dojo.telerik.com/eJijIZUm/2

Result:

![image](https://github.com/telerik/kendo-ui-core/assets/11816856/7431bf12-5a8e-42f7-b615-6d142b015180)

**Comment by gdenchevprog** [comment]
Fixed with - https://github.com/telerik/kendo-ui-core/issues/7551

It's going to be live with the upcoming release
