### ISSUE TITLE
The change and moveEnd events of the TaskBoard are triggered twice

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7590]
### Bug report

The change end moveEnd events of the TaskBoard are triggered twice.

### Reproduction of the problem

1. Open this DOjo example - https://dojo.telerik.com/iNEqiDEc/3
2. Open the browser console
3. Move a card to another column

### Current behavior
The events are triggered twice.

### Expected/desired behavior

The events should be thrown once.

### Environment

* **Kendo UI version:** 2023.3.1010 
* **Browser:** [all]

**Comment by gdenchevprog** [comment]
It is true that the events are triggered twice, however the reason behind that behavior is that that the trigger is for two separate actions. The first one is for the card being removed from one of the columns and the second one is for the card being received by another column.

As such, these are not duplicated and it is expected that two of them are fired off at the same time.

![image](https://github.com/telerik/kendo-ui-core/assets/70957719/b22c370d-cdae-4731-bd95-b251e4a3cbad)
