### ISSUE TITLE
Loading indicator and down arrow icon overlaps when loading data in DropDownList

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7592]
### Bug report

When remote data is loaded in the DropDownList and the loading icon appears while loading, the down arrow icon remains visible. Thus, both icons are overlapping.

### Reproduction of the problem
1. Open the [ Dojo ](https://dojo.telerik.com/@NeliKondova/ohoLApoT)
Note: if the data loads fast and the issue does not occur, open the browser developer tools in order to hit the debugger in the requestEnd event handler

### Current behavior
Both - the loading indicator and the down arrow icon appear at the same time:
![image](https://github.com/telerik/kendo/assets/14364791/5c6f2220-191b-4a5a-9a1b-e902b1f231df)

### Expected/desired behavior
The down arrow icon should disappear while the loading indicator is displayed. 

### Environment

* **Kendo UI version:** 2023.3.1010
* **Browser:** [all]

**Comment by gkitsos** [comment]
Hello, is there any temporary solution for this bug?

**Comment by sspasova** [comment]
> Hello, is there any temporary solution for this bug?

Hello @gkitsos, we have already released the fix for this bug in Kendo UI 2024 Q1 (version 2024.1.130).  Please update to the latest version of our product so you can get the solution.
