### ISSUE TITLE
Unstick column remove all classes  from the cells in the column in Grid

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7608]
### Bug report

When a column is unsticked either through the built-in context menu or through the unstickColumn method all the casses from the cells in that column are removed, even the 'k-table-td' class.

### Reproduction of the problem
1. Open the [Dojo ](https://dojo.telerik.com/@NeliKondova/OhIMUJOB)and inspect the cells in the ShipAddress column
2. Unstick the column

### Current behavior
All classes in that column are removed
```
<td class="" style="" role="gridcell">Boulevard Tirou, 255</td>
```

Note: Initially the cells have the k-table-td class twice which is also not expected 
```
<td class="k-grid-content-sticky k-table-td k-table-td" style="left: 0px; right: 0px;" role="gridcell">Boulevard Tirou, 255</td>
```

### Expected/desired behavior
Only the 'k-grid-content-sticky' class should be added or removed when sticking/unsticking a column.

### Environment

* **Kendo UI version:** 2023.3.1114
* **Browser:** [all  ]

**Comment by gdenchevprog** [comment]
The following PR must have resolved this issue:
[fix](https://github.com/telerik/kendo/pull/19084)
