### ISSUE TITLE
Gantt select incorrect item after filtering

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7610]
### Bug report

When there is a selected item and filtering is performed in the Gantt, sometimes a task in the new filter result is displayed as selected.

### Reproduction of the problem
1. Open the demo - https://demos.telerik.com/kendo-ui/gantt/columns
2. Filter the tasks by ID 18
3. Select the task with ID = 18
4. Filter the tasks that have ID equal to 11
**Additional steps according to the video**
5. Select the task with ID = 11
6. Filter the tasks by ID = 18 or clear filter

### Current behavior
Sometimes the task with ID 11 is marked as selected. The issue does not appear consistently, so you may need to perform the test multiple times.
screencast - https://somup.com/c0XZ6DgaRA

**Observation from the screencast**
When the filter is cleared or set back to ID = 18, the task with ID 18 is selected and the selection on task with ID 11 is lost

### Expected/desired behavior
The tasks that have not been selected, should not be displayed as selected after filtering.

### Environment

* **Kendo UI version:** 2023.3.1114
* **Browser:** [all]

**Comment by pepinho24** [comment]
The filtering in older versions is inconsistent as well. The TreeList that is used in the Gantt for the tasks does not currently support the selection persistence when filtering and sorting. 

You can cast your vote for the Persist Selection in TreeList feature request here: 
- https://feedback.telerik.com/kendo-jquery-ui/1549986-persist-selection-for-treelist

As a workaround, you can manually persist the selection similar to the approach described in the following KB article: 
- https://docs.telerik.com/kendo-ui/knowledge-base/persist-selection-remote-bound-treelist-datasource
