### ISSUE TITLE
Menu component rendering mismatch

### ISSUE THREAD

**Issue by NickIliev** [telerik/kendo-ui-core#7619]
### Bug report

The **Menu** component in **Kendo UI for JQuery** is rendered with a missing `k-header` class which is a rendering mismatch with the source of truth tests https://github.com/telerik/kendo-themes/blob/develop/tests/menu/menu.html#L25 

### Reproduction of the problem

1. Load the **Menu** overview demo at https://demos.telerik.com/kendo-ui/menu/index or the related [dojo demo](https://dojo.telerik.com/?_gl=1*riyih1*_gcl_aw*R0NMLjE3MDExNTYxMDMuQ2p3S0NBaUFtWkdyQmhBbkVpd0FvOXFIaVhaQXV3a2Z5cHFSMWNZYUczV3ZKYTFSdVNHdmpkbnJSN1RzOXJ0NHdqX25fTkNram1WQlF4b0MyaGNRQXZEX0J3RQ..*_gcl_dc*R0NMLjE3MDExNTYxMDMuQ2p3S0NBaUFtWkdyQmhBbkVpd0FvOXFIaVhaQXV3a2Z5cHFSMWNZYUczV3ZKYTFSdVNHdmpkbnJSN1RzOXJ0NHdqX25fTkNram1WQlF4b0MyaGNRQXZEX0J3RQ..*_gcl_au*MTQzMDQ5MTY2MS4xNjk3NzgwMTg0*_ga*MTg2ODA2ODkwNC4xNjEyNzc3MzU3*_ga_9JSNBCSF54*MTcwMTIzODYwOC4xMC4xLjE3MDEyNDA4MzQuNTguMC4w)

2. Inspect the top **ul** element of the **Menu**

    ![image](https://github.com/telerik/kendo-ui-core/assets/18008302/90afe81e-e1e7-4c45-9681-b5f5c136871b)

3.  Compare the rendering of the **<ul>** with the source of truth here: https://github.com/telerik/kendo-themes/blob/develop/tests/menu/menu.html#L25

Result: The `k-header` class is missing, which causes custom Kendo themes not to work as expected (reported through ThemeBuilder).

### Expected/desired behavior

The top **UL** should have a `k.header` class.

### Environment

* **Kendo UI version:** 2023.3.1114
* **jQuery version:** x.y
* **Browser:** all 

Reported through t.1632507

**Comment by gdenchevprog** [comment]
I'll check it out, thanks!

**Comment by gdenchevprog** [comment]
The `k-menu-link-text` span element is rendered when a text value is directly provided to the `<li>` element, ex:

```html
 <li>My Text</li>
```

When the Menu is initialized, the element will be transformed into the following one:

```html
<li class="k-item k-menu-item"><span class="k-link k-menu-link"><span class="k-menu-link-text">My Text</span></span></li>
```

However, if some type of custom rendering is used (such as an `<a>` element inside the `<li>`)

```html
 <li><a href="#">My Text</a></li>
```

Then it is up to the developer to apply the menu classes to the custom element.
