### ISSUE TITLE
Dirty indicator is not positioned correctly when the model.set method is used in the Grid

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7625]
### Bug report

When the editable option is set to 'inline' or 'popup' and the **model.set** method is used the dirty indicator is displayed always on the first column, first row.

### Reproduction of the problem
1. Open the Dojo - https://dojo.telerik.com/@NeliKondova/EbUnipUb
2. Check a checkbox in the 'Discontinued' column.

### Current behavior
The dirty indicator is displayed on the 'Chai' cell.

### Expected/desired behavior
The dirty indicator should be displayed on the edited cell.

### Environment

* **Kendo UI version:** 2023.3.1114
* **Browser:** [all  ]

**Comment by Dimitar-Goshev** [comment]
Also logged in kendo-themes - https://github.com/telerik/kendo-themes/issues/4205
