### ISSUE TITLE
Grid column header remains hidden after showing the column

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#7630]
### Bug report
Regression introduced in R3 2023 SP1
If an initially hidden column is shown with the **showColumn** API method, the column header remains hidden because of the **k-hidden** class that remains in the th element. 

### Reproduction of the problem

1. Click on the button above the Grid in the example below

```
<input type="button" name="btn1" value="Show the hidden columns" onclick="btn1Click()" />
<br />
<br />

@(Html.Kendo().Grid<TelerikMvcApp1.Models.OrderViewModel>()
    .Name("Grid")
    .Columns(columns =>
    {
        columns.Bound(p => p.OrderID);
        columns.Bound(p => p.Freight);
        columns.Bound(p => p.ShipName);
        columns.Bound(p => p.ShipCity).Hidden(true);
        columns.Bound(p => p.OrderDate).Format("{0:MM/dd/yyyy}").Hidden(true);
    })
    .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(20)
        .Read(read => read.Action("Orders_Read", "Grid"))
    )
)

<script>
    function btn1Click() {
        var grid = $("#Grid").data("kendoGrid");

        grid.showColumn("ShipCity");
        grid.showColumn("OrderDate");
    }
</script>
```

### Current behavior
The hidden columns are shown but their headers remain hidden.

As a workaround, the **k-hidden** class can be removed from the column header, after showing the column:

```
grid.showColumn("ShipCity");
$(".k-grid .k-header[data-field='ShipCity']").removeClass("k-hidden");
```

### Expected/desired behavior
The columns and their headers are shown.

### Environment

* **Kendo UI version:** 2023.3.1114
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by greg-galbraith** [comment]
this workaround seems to work for me:
`.k-grid-header .k-table-th.k-hidden:not([style*="display: none"]) {
    display: table-cell !important;
}`

disclaimer: not thoroughly tested.  table-cell is the default display for k-table-th, but may not be your fallback value, depending on any custom styling.
