### ISSUE TITLE
DatePicker with enabled DateInput does not work with "fr-CH" culture

### ISSUE THREAD

**Issue by eyupyusein** [telerik/kendo-ui-core#7636]
### Bug report

Selecting dates with keyboard is not possible. Year works only for last number.
Reproduction:
https://dojo.telerik.com/EzeLotEW/7

### Expected/desired behavior
The picker should work properly in any culture.

Can be related to this: https://github.com/telerik/kendo-ui-core/issues/7451
_"The issue is a regression starting with the 2023 R2 (2023.2.606) release and it is due to an issue in kendo-dateinputs-common package"_

### Related tickets
- 1633704

**Comment by nelito987** [comment]
Reported in ticket: 1634703 - the issue is reproducible also with 'de-DE' and 'cs-CZ' cultures.
