### ISSUE TITLE
Zooming a file in the PDFViewer beyond 200% + results in a blank page on mobile devices

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7638]
### Bug report

When previewing a file in the PDFViewer on a mobile device, if you try to zoom to a specific scale, the page goes blank.

### Reproduction of the problem

1. Open the PDFViewer demo on a mobile device - https://demos.telerik.com/kendo-ui/pdfviewer/index
2. If opened on iOS device in Chrome, try to zoom beyond 240%. On Safari, try to zoom beyond 225%.
3. If opened on Android in Chrome, try to zoom beyond 300%.

### Current behavior

The page goes blank if zoom beyond the above scales.

### Expected/desired behavior

The document pages should remain visible.

### Environment

* **Kendo UI version:** 2024.1.130
* **Browser:** [Chrome/Safari]

**Comment by ag-petrov** [comment]
Related issue - https://github.com/telerik/kendo-ui-core/issues/7389

**Comment by NikoPenev21** [comment]
According to the client from ticket 1632091 can be replicated with any PDF file.

**Comment by sspasova** [comment]
The issue is fixed with https://github.com/telerik/kendo/issues/20260
