### ISSUE TITLE
Footer templates not compiled

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#766]
Can be replicated on: [http://dojo.telerik.com/uTuRu/2](http://dojo.telerik.com/uTuRu/2)

Click on the checkbox outside the grid - "1" is logged in the console
Click  on a checkbox in the footer template of the grid - "1" is NOT logged in the console
Expected:  Click  on a checkbox in the footer template of the grid - "1" should be logged in the console

Reported in Ticket ID: 929210

**Comment by michaelbeckersgit** [comment]
Hi,

Any idea when this issue will be fixed, because I would need it to go to production in a few weeks.

Kind regards,

**Comment by naskog** [comment]
Hello @michaelbeckersgit,
This is an issue with the grid (which is not part of Kendo UI Core) and thus moved to Kendo UI private repo.
The problem is already resolved and will be available in our next internal build due by the end of next week.
