### ISSUE TITLE
Tooltip rendering mismatch for jQuery

### ISSUE THREAD

**Issue by Martin-Hristov** [telerik/kendo-ui-core#7667]
### Bug report
The Tooltip component in Kendo UI for jQuery has additional classes .k-widget and .k-popup which are not part of the source of truth https://github.com/telerik/kendo-themes/blob/develop/tests/tooltip/tooltip.html

### Reproduction of the problem
1. Open the demo for the tooltip https://demos.telerik.com/kendo-ui/tooltip/index and inspect the element with the .k-tooltip class

### Current behavior
The element has additional classes lasses .k-widget and .k-popup which are not part of the source of truth

### Expected/desired behavior
The element should not have these classes

### Environment

* **Kendo UI version:** 202x.r.ddd
* **jQuery version:** x.y
* **Browser:** Chrome

**Comment by kvelikov** [comment]
tagging managers for prioritization

@ag-petrov @nenchef

**Comment by sspasova** [comment]
I am closing this issue because the `k-widget` class has already been removed.
Regarding the `k-popup` class -> jQuery and Blazor render this class as shown in themes tests - https://github.com/telerik/kendo-themes/blob/develop/tests/tooltip/tooltip.html#L232
