### ISSUE TITLE
Double tap to edit a Grid in incell edit mode does not work on iOS in Chrome and Edge browsers

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#7675]
### Bug report
The Grid cell does not enter edit mode on double tap on iOS in Chrome and Edge. Works correctly in Safari.

### Reproduction of the problem
1. Run this dojo example on iOS in Chrome or Edge: https://dojo.telerik.com/idOVAZiP/3
2. Double tap a cell to edit its value

### Current behavior
The cell does not enter edit mode.

### Expected/desired behavior
The cell enters edit mode.

### Environment

* **Kendo UI version:** 2023.3.1114
* **jQuery version:** x.y
* **Browser:** [iOS Chrome, iOS Edge]

**Comment by gdenchevprog** [comment]
Duplicated - https://github.com/telerik/kendo-ui-core/issues/7817

Technically the other issue is the duplicate, but it is already assigned so I am closing this one.
