### ISSUE TITLE
Use Unicode CLDR Project for Kendo UI cultures generation

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#768]
### Description

Currently, we use Windows 8 for cultures generation. Although it is very popular OS, there are some omissions that causes problems with the date/number formatting. 
### Proposition

The best way to address these limitations is to build our cultures from CLDR project:
- [http://cldr.unicode.org/index/downloads](http://cldr.unicode.org/index/downloads)
- [https://github.com/unicode-cldr/cldr-json](https://github.com/unicode-cldr/cldr-json)

**Comment by ggkrustev** [comment]
Even though this is a nice enhancement, it is quite time consuming and error prone. We will need to add dependency to CLDR-DATA repository, which I am not sure how will be implemented.

Nevertheless, if it is considered, the whole logic is already done in https://github.com/telerik/kendo-intl.

**Comment by tsvetomir** [comment]
One problem with using the CLDR database is the huge dataset size. Perhaps we should give up on this as it will:

* Introduce potential breaking changes **or** two separate implementations
* Increase the payload size dramatically

**Comment by danielkaradachki** [comment]
Indeed, it is huge but this is not an issue. We can generate culture files with the same size if we support only the current features.

**Comment by matanasov** [comment]
Starting from R3 2017 The Kendo UI culture scripts are generated from the Windows and .NET (currently Windows 10, .NET 4.7) server-side culture definitions and match them by design. To customize the culture in your application, refer to the article on [culture definition](http://docs.telerik.com/kendo-ui/framework/globalization/definecultureinfo).
