### ISSUE TITLE
Switch does not behave consistently with different font sizes

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#769]
[Switch moves by 1-2 px.](http://www.telerik.com/clientsfiles/ad09daff-34dd-4b15-9b75-c9b4a02940b8_Switch.png?sfvrsn=0) due to the dimensions being set in em and the way the browser interprets them. 

Ticket ID: 928387

**Comment by inikolova** [comment]
Different font-size must be set before Switch widget initialization -> http://dojo.telerik.com/@Iliana/OlEkA
