### ISSUE TITLE
MultiSelect's clear button does not clear all selected items in single tag mode (TagHelper)

### ISSUE THREAD

**Issue by brunoviveiros-dev** [telerik/kendo-ui-core#7695]
As issue [3506](https://github.com/telerik/kendo-ui-core/issues/3506) has already been closed, I am opening a new one to be properly addressed.

### Bug report
Clicking the clear button ('X' button) only removes the last selected item in MultiSelect (single tag mode). This only happens with TagHelper, HtmlHelper is working fine.

### Reproduction of the problem
Component code:
```html
<kendo-multiselect name="CollectorMultiSelect" 
    datatextfield="Text" 
    datavaluefield="Value" 
    placeholder="Collectors..."
    tag-mode="@MultiSelectTagMode.Single" 
    down-arrow="true" 
    auto-close="false" 
    clear-button="true"
    item-template="<input type='checkbox'/> #:data.Text#" 
    on-change="onMultiSelectChange"
    on-data-bound="onMultiSelectDataBound" 
    style="width:100%;">
    <datasource type="DataSourceTagHelperType.Custom" server-filtering="true">
        <transport>
            <read url="@Url.Action(" GetData", "DataController" , new { Area="Dashboards" } )" />
        </transport>
    </datasource>
</kendo-multiselect>
``` 

![MultiSelect_SingleTagMode](https://github.com/telerik/kendo-ui-core/assets/81095417/e33c19b2-18e3-4f73-991d-e0f3eb3a7116)

If I change from `tag-mode="@MultiSelectTagMode.Single"` to `tag-mode="@MultiSelectTagMode.Multiple"`, the same behavior happens, but if I remove `tag-mode="@MultiSelectTagMode.Single"`, it works correctly.

![MultiSelect_MultipleTagMode](https://github.com/telerik/kendo-ui-core/assets/81095417/9b4d0a5a-3129-46f5-af4d-2eadb36acb64)

Using Progress Telerik Repl for ASP.NET Core the code snippet works fine, since it does not support TagHelper mode it is not possible to reproduce the error. https://netcorerepl.telerik.com/GIOPFhvB23H3Pijj46

### Kendo UI version:** 2022.1.119

**Comment by FedericoNembrini** [comment]
In my case it removes the first two selected items leaving the others selected.

```
<kendo-multiselect for="StatusId" class="w-100"
                   filter="FilterType.Contains"
                   datatextfield="Text"
                   datavaluefield="Value"
                   down-arrow="true"
                   auto-close="false"
                   tag-mode="@MultiSelectTagMode.Single"
                   on-data-bound="statusId_onDataBound">
    <label content="@Localizer["Status"].Value" floating="true" />
    <datasource type="DataSourceTagHelperType.Custom"
                custom-type="aspnetmvc-ajax"
                on-error="statusId_onError">
        <transport>
            <read url="@Url.Action("", "")" />
        </transport>
        <schema data="Data" total="Total" errors="Errors">
        </schema>
    </datasource>
</kendo-multiselect>
```

Kendo UI version: 23.3.1114

**Comment by aleksandarevangelatov** [comment]
@brunoviveiros-dev while I look at the report I just want to make a note on the following:

> Using Progress Telerik Repl for ASP.NET Core the code snippet works fine, since it does not support TagHelper mode it is not possible to reproduce the error. https://netcorerepl.telerik.com/GIOPFhvB23H3Pijj46

The Progress Telerik REPL for ASP.NET Core supports the use for TagHelpers, you just need to add the `@addTagHelper "*, Kendo.Mvc"` directive to the cshtml. [In the same way you would do in a regular cshtml file.](https://docs.telerik.com/aspnet-core/html-helpers/helper-basics/fundamentals#tag-helpers) 

Here is a [REPL example](https://netcorerepl.telerik.com/ceElGUvQ40FXWiMP48) of the behavior reported, for a MultiSelect configured using TagHelpers.
