### ISSUE TITLE
Stack Bar Chart is not rendered correctly when type is set

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7706]
### Bug report

The stack bar chart is not rendered as expected when **_stack.type_** is set

### Reproduction of the problem
1. Open d the Demos - https://demos.telerik.com/kendo-ui/bar-charts/stacked100-bar or the API
- https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart/configuration/series.stack#seriesstacktype
- https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart/configuration/seriesdefaults.stack.type
 

### Current behavior
The Chart is not rendered correctly, the bars are misaligned. 

### Expected/desired behavior
The bars should be aligned. 

### Environment

* **Kendo UI version:** 2024.1.130
* **Browser:** [all ]

**Comment by nelito987** [comment]
The related item in kendo-charts repo: https://github.com/telerik/kendo-charts/issues/431

**Comment by mihaela-lukanova** [comment]
Reported in TicketID: 1637459
