### ISSUE TITLE
The Kendo prompt dialog has different dimensions due to styles from k-prompt class

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7713]
### Bug report

Until the 2024.1.130 release, the k-prompt class of the kendo.prompt dialog was not bringing in any styles. With 2024.1.130, the k-prompt class now comes with its own styles and changes the current styling of the kendo.prompt dialog.

### Reproduction of the problem
 
1, Open and run this example - https://dojo.telerik.com/aHiZUpUm
2. Compare the dialog's dimensions to the previous version.

### Current behavior

The dialog's dimensions are bigger compared to the expected ones

### Environment

* **Kendo UI version:** 2024.1.130
* **Browser:** [all]

**Comment by NikoPenev21** [comment]
Also reported in ticket #1641792
