### ISSUE TITLE
In the Grid "tabbed" columnMenu, the Column Visibility and Autosize options are missing

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7717]
### Bug report

With the introduction of the Columns tools in the Grid toolbar, if the columnMenu is set to tabbed, the menu is missing the Column Visibility and Autosize options.

**Regression introduced with 2024.1.130**

### Reproduction of the problem

1. Open this demo - https://demos.telerik.com/kendo-ui/grid/column-menu
2. Open the Column Menu

### Current behavior

The Column Visibility and Autosize options are missing

### Expected/desired behavior

The Column Visibility and Autosize options should be visible.

### Environment

* **Kendo UI version:** 2024.1.130 
* **Browser:** [all]

**Comment by gdenchevprog** [comment]
Note: The auto size options must be explicitly enabled through `columnMenu: { autoSize: true }`, otherwise they won't appear.
