### ISSUE TITLE
Provide support for latest pdf.js 4.X version in PDFViewer

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7725]
Currently, when the PDFViewer is used with the latest pdf.js version 4.0.379 an error is thrown in the browser console. 
```(Uncaught (in promise) Error: No "textContentSource" parameter specified.)```

1. You can test the behavior in the Dojo linked here - https://dojo.telerik.com/@NeliKondova/eBUYEDAb. 
2.  Run the example
3.  Wait for the pdf file to be loaded, then check the browser console.

**Comment by abrousseau-hcgov** [comment]
Using the latest supported version, 3.11.174, I am given this message in the console (to help determine how Telerik upgrades their PDF Viewer control): 
Deprecated API usage: The TextLayerRender `textContent`/`textContentStream` parameters will be removed in the future, please use `textContentSource` instead.

This is the message that we were seeing using 4.x about textContextSource

**Comment by abrousseau-hcgov** [comment]
@smfeest I just put in another ticket with Telerik to see if we can get insight into their roadmap for this. I will update the issue once I hear back.

**Comment by abrousseau-hcgov** [comment]
@smfeest 2024 November is the timeline per the milestone added.

**Comment by sspasova** [comment]
Fixed with https://github.com/telerik/kendo/issues/20260
