### ISSUE TITLE
Expose delegate overload for .AddHtml() API of the Template Component

### ISSUE THREAD

**Issue by alestoya** [telerik/kendo-ui-core#7757]
### Overview

Currently, the only way to nest conventional HTML tag content for the Template Component would be through the following configuration

```
@(Html.Kendo().Template()
    .AddHtml("<div>")
    .AddHtml("<p>Test</p>")
    .AddHtml("</div>")
)
```
It would be beneficial if the configuration accepts a [delegate overload](https://learn.microsoft.com/en-us/dotnet/api/system.func-2?view=net-8.0) that would allow transpose the previous configuration to the following

```

@(Html.Kendo().Template()
    .AddHtml(@<text>
           <div>
                 <p>Some Value</p>
           </div>
    </text>)
)
```

### Current behavior
Currently, the Template component does not expose a delegate overload for the `.AddHtml()` API configuration.

### Expected/desired behavior
The Template component should expose a delegate overload for the `.AddHtml()` API configuration.

### Environment

* **Kendo UI version:** 2024.1.130
* **Browser:** [all]

**Comment by daver77** [comment]
Thanks for raising this, it will be really useful!

**Comment by daver77** [comment]
Hi @alestoya , has this been released yet?
