### ISSUE TITLE
Inline Editor is not closing if you change its position

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7775]
### Bug report

Inline Editor does not close if you drag it to another position. ~Additionally, while dragging, occasionally the Editor will disappear, or it will have a padding from the cursor.~ - Logged as a separate bug.

**Regression introduced with 2023.2.606**

Video - http://somup.com/cZeOQ5CYa8

### Reproduction of the problem
1. Open this Dojo example - https://dojo.telerik.com/OvumAcaH/7
2. Open and drag the inline Editors to observe the behavior. 

Additional scenario:
1. Open the Demo - https://demos.telerik.com/kendo-ui/editor/inline-editing 
2. Delete all text in an editor
3. Click the bold tool
4. Leave the field

Additional scenario#2:
1. Open this Dojo - https://dojo.telerik.com/@martin.tabakov@progress.com/ecIpIBIV/2
2. Type some text
3. From the Editor, choose a font name/size for the text
4. Blur the textarea

### Current behavior

The inline Editor remains open when it loses focus
### Expected/desired behavior

Thе inline Editor should close when it loses focus

### Environment

* **Kendo UI version:** 2024.1.319
* **Browser:** [all]

**Comment by nelito987** [comment]
Reported in ticket id: **1647187**

**Comment by martintabakov** [comment]
Also reported in 1649358

**Comment by martintabakov** [comment]
Also reported in 1652296

**Comment by nelito987** [comment]
Also reported in : 1652670

**Comment by martintabakov** [comment]
Also reported in 1655696

**Comment by gdenchevprog** [comment]
The following part is a separate bug:

_Additionally, while dragging, occasionally the Editor will disappear, or it will have a padding from the cursor._

https://github.com/telerik/kendo-ui-core/issues/7881
