### ISSUE TITLE
Can't bind popupCollision in Menu using MVVM

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7786]
### Bug report

The popupCollision option of the Menu cannot be set in MVVM

### Reproduction of the problem

1. Open this Dojo example - https://dojo.telerik.com/izaZIkAK/7
2. Test a scenario in which the popupCollision would apply, or check the Menu options in the browser console.

### Current behavior

The popupCollision cannot be set 

### Expected/desired behavior

You should be able to set the option in MVVM scenario

### Environment

* **Kendo UI version:** 2024.1.319 
* **Browser:** [all]

**Comment by gdenchevprog** [comment]
The bug will be fixed, however the correct syntax should be:

`data-popup-collision` instead of `data-popupCollision`.
