### ISSUE TITLE
Closing a Window from a Dialog action results in an error in the console

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7796]
### Bug report

If you attempt to close a Kendo Window from a Dialog action, an error is thrown on the console.

**Regression introduced with 2024.1.319**

Workaround: https://dojo.telerik.com/afUPoQuX/3

### Reproduction of the problem

1. Open this Dojo example - https://dojo.telerik.com/afUPoQuX/2
2. Open the browser console 
3. Click the OK action

### Current behavior

An error is thrown on the console

### Expected/desired behavior

No errors should be thrown

### Environment

* **Kendo UI version:** 2024.1.319
* **Browser:** [all]

**Comment by martintabakov** [comment]
Also reported in #1649898

**Comment by ag-petrov** [comment]
Related item https://github.com/telerik/kendo-ui-core/issues/7787
