### ISSUE TITLE
Grid throws an error when partial update is executed and selection is persisted

### ISSUE THREAD

**Issue by alestoya** [telerik/kendo-ui-core#7797]
### Bug report

Grid throws error when partial update is executed and selection is persisted

### Reproduction of the problem

1. Open the following [dojo](https://dojo.telerik.com/@alexander64836/ORifEPOV).
2. Select a row.
3. Place it into edit mode.
4. Make some changes and click on the `Save` command button.
5. Try to select another row.

### Current behavior
The Grid throws an error when the partial update is executed and the selection is persisted.

### Expected/desired behavior
The Grid should not throw an error when the partial update is executed and the selection is persisted.

### Environment

* **Kendo UI version:** 2024.1.319
* **Browser:** [all]

**Comment by mihaela-lukanova** [comment]
Reported in TicketID: 1648477
