### ISSUE TITLE
Checkbox has become required after update if there is a label after the wrapper element.

### ISSUE THREAD

**Issue by antonmironovv** [telerik/kendo-ui-core#7798]
Regression in version 2024.1.319

### Bug report

After updating to Telerik UI for ASP.NET Core version 2024.1.319, the checkboxes for non-nullable booleans are not valid when the value is false and if there is a label after the wrapper element.
Introduced after [this issue](https://github.com/telerik/kendo-ui-core/issues/7495)

### Reproduction of the problem

Implement a Form with a CheckBox. Submit the Form with the false value for the CheckBox.

### Current behavior

The Form is not submitted and the validation for the CheckBox fires.

### Expected/desired behavior

The Form should be submitted with the false value for the CheckBox.

### Environment

* **Kendo UI version:** 2024.1.319
* **Browser:** [all]

**Comment by aldrashan** [comment]
Will there be a small release to fix this or should everyone just skip version 2024.1.319 and wait for the next major release?
