### ISSUE TITLE
Pasting modified cell values from Excel to Spreadsheet has no effect

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7799]
### Bug report

Modified date value from Excel is not correctly updated when pasting in the Spreadsheet.

**Regression introduced with 2023 R1**

### Reproduction of the problem

1. Open this Dojo example - https://dojo.telerik.com/AZateGoC/6
2. Copy the Spreadsheet content
3. Paste in to an Excel file
4. Change the date cell value
5. Copy and paste back in the Spreadsheet

### Current behavior

The updated date cell is not pasted in the Spreadsheet

### Expected/desired behavior

The updated cell's value should be pasted in the Spreadsheet

### Environment

* **Kendo UI version:** 2024.1.319
* **Browser:** [all]

**Comment by gdenchevprog** [comment]
Related - https://github.com/telerik/kendo-ui-core/issues/6433

For some reason the data-sheets-* attributes are copied over as well. Since Excel does not support editing them, they should be discarded if the clipboard data comes from Excel specifically.
