### ISSUE TITLE
Unintended Behavior in <kendo-grid-column-chooser> - View jumps when opening the popup

### ISSUE THREAD

**Issue by denny-in4out** [telerik/kendo-ui-core#7804]
### Bug report
The popup of `<kendo-grid-column-chooser>` has a new behavior since the update

- from @progress/kendo-theme-default v6.2.0 to v6.7.0 and
- from @progress/kendo-angular-xx v12.1.0 to v13.5.0,

which has a disturbing effect on a certain scenario.

The point is that after opening, the view is realigned with the popup. This means that the current view can jump. In other words, if the user has scrolled somewhere, after opening the popup this will be adjusted.
It becomes particularly tedious if there is enough space above the grid so that the popup can be placed above the icon. Then the view jumps so much that the Grid is barely visible. As a result, you have to scroll down again.

### Reproduction of the problem
I have provided you with a playground so that you can try it out for yourself:
[https://stackblitz.com/edit/angular-e5mp3d-2u1bzh?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-e5mp3d-2u1bzh?file=src%2Fapp%2Fapp.component.ts)

I have added a large green area at the top and bottom so that this behavior can be simulated.

1. Scroll down to the grid
2. click on the <kendo-grid-column-chooser> menu icon
3. Repeat the process at different scroll depths and observe the behavior.

### Expected/desired behavior
We liked the behavior before the update better. Alternatively, it would be great if the `<kendo-grid-column-chooser>` could be parameterized like a regular popup. [With a regular popup, you can control the opening position yourself](https://www.telerik.com/kendo-angular-ui/components/popup/aligning-positioning/). 

With such a system, we could at least say that it is always allowed to place itself below the icon. Then the jump would only be slightly worse, as the grid would still remain visible.

### Environment

* **Kendo UI version:** 13.5.0
* **Browser:** Chrome Version 123.0.6312.123

**Comment by Dimitar-Goshev** [comment]
Hello @denny-in4out . This repository is for Kendo UI for jQuery issues. Please use the Kendo UI for Angular Issue tracker repository https://github.com/telerik/kendo-angular/issues to search for and log the current issue.

**Comment by denny-in4out** [comment]
Hello @Dimitar-Goshev . All right, then I'll post it there. Thank you!
