### ISSUE TITLE
Spreadsheet insert sheet is not working propperly

### ISSUE THREAD

**Issue by iordanGrancharov** [telerik/kendo-ui-core#7822]
### Bug report

Inserting sheets in the Spreadsheet component is not working as expected.

### Reproduction of the problem
1. Open this Dojo example https://dojo.telerik.com/EyEzOcER/8
2. Click on the `Load New Sheet` Button
3. Click again
4. Open the Browser console to see the error:
 
![image](https://github.com/telerik/kendo-ui-core/assets/121674157/1bc38471-72bd-472c-9e8a-c4613da9f3d5)

### Current behavior
Error is thrown.

### Expected/desired behavior
Error to not be persistent.

### Environment

* **Kendo UI version:** 2024.1.319
* **Browser:** [all]

**Comment by pepinho24** [comment]
When the sheet options object is passed to the Spreadsheet insertSheet method, it modifies the formula references and converts them from a string to an object. That is why when you try to load the new sheet, the sheet is actually not the original one but the converted, hence the error. 

The solution is to pass a deep clone of the sheet options, e.g. using the structuredClone method: 
- https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone
- `data: structuredClone(mySheetsTwo[0])`
