### ISSUE TITLE
TextBox Widget Missing

### ISSUE THREAD

**Issue by dday9** [telerik/kendo-ui-core#7866]
### Bug report
The TextBox widget is missing from Kendo-UI Core but listed as supported in the README.

### Reproduction of the problem
1. Attempt to call `.kendoTextBox` on a jQuery element

Minimal Demo: https://dojo.telerik.com/eceTuziz

### Current behavior
1. An error is thrown in the console: `TypeError: $(...).kendoTextBox is not a function`
2. The TextBox does not include any of the styling of the TextBox widget.

### Expected/desired behavior
No error and the desired configuration gets applied.

### Environment
* **Kendo UI version:** 2014.2.716
* **jQuery version:** 3.7.1
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
@dday9 The TextBox component is listed as present in the latest version of the README file. But it is not listed in the version of the README file corresponding to the Kendo UI version 2014.2.716, e.g. here - https://github.com/telerik/kendo-ui-core/tree/2014.Q2

**Comment by dday9** [comment]
@Dimitar-Goshev - As a work around, I suppose I can use the MaskedTextBox without any configuration. Do you know if there are any plans to include the (most basic) widget?
