### ISSUE TITLE
The inline Editor does not hide when activating some of its tools

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#7871]
### Reproduction of the problem
1. Run this dojo example: https://dojo.telerik.com/eVOVEdaR
2. Click the bold, italic, and underline tools to activate all 3 of them
3. Click away from the inline Editor

Alternatively to step 2, click the first justify tool and then consecutively click the other 3 justify buttons. 

### Current behavior

The Editor's toolbar does not close. 

### Expected/desired behavior
The Editor toolbar closes

**Workaround:** https://dojo.telerik.com/eVOVEdaR/5

### Reproduction of the problem
1. Run this dojo example: https://dojo.telerik.com/oVAViPiD/2
2. Click the format dropdown in the middle (the green dot in the screenshot) so the dropdown appears
![image](https://github.com/user-attachments/assets/0d0fb992-863d-4257-bae5-811f9e6a58c9)

3. Click away from the inline Editor
 
EDIT: Clicking anywhere on the toolbar will prevent it from disappearing 
https://github.com/user-attachments/assets/bce20d12-29e3-48fb-bcd3-46a54121831d

### Current behavior
The Editor's toolbar does not close. 

### Expected/desired behavior
The Editor toolbar closes

### Environment

* **Kendo UI version:** 2024.2.514
* **jQuery version:** x.y
* **Browser:** [Chrome XX]

**Comment by NikoPenev21** [comment]
also reported in #1661859

**Comment by gdenchevprog** [comment]
The main scenarios seem to already be addressed by the fixes in the following issue(there were additional changes after the release so not everything will be live at the moment):

https://github.com/telerik/kendo-ui-core/issues/7775

> EDIT: Clicking anywhere on the toolbar will prevent it from disappearing

This one however, appears to still be happening locally as well. If you click on an empty space in the toolbar and then attempt to focus it out, the toolbar will remain open.
