### ISSUE TITLE
An error is thrown when removing an item if autoClose is set to false and the popup has never been opened

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-ui-core#789]
Ticket: 933523 

Repro demo: http://dojo.telerik.com/@SiliconSoul/uYoxe

Repro steps:
1. Run the demo
2. Delete a tag and check the console for errors

Could be fixed by checking if the popup is opened before calling the _position method

    _close: function() {
        var that = this;
        if (that.options.autoClose) {
            that.close();
        } else {
            that.popup._position();
        }
    },

**Comment by ggkrustev** [comment]
Fixed with 19d1ec0b03404dff968673600b1881621a68c0f7
