### ISSUE TITLE
Gantt Month View has blank space

### ISSUE THREAD

**Issue by eyupyusein** [telerik/kendo-ui-core#7895]
### Bug report

When selecting the Month View of the Gantt, unexpected blank space appears and the cell headers are not properly aligned.

### Reproduction of the problem

1. Open this demo:
https://demos.telerik.com/kendo-ui/gantt/basic-usage

2. Click Edit in Kendo UI Dojo:
https://dojo.telerik.com/OparoYUJ

3. Zoom out the browser so the Gantt has some larger Width and you will notice the blank space + misaligned headers:

![image](https://github.com/user-attachments/assets/e9d547c1-8b1a-4cee-864d-3c9e8605df13)

**Comment by eyupyusein** [comment]
It turns out that the Gantt does not provide dynamic calculation of its cells. I have logged this capability as a Feature Request and closing this bug item:
https://feedback.telerik.com/kendo-jquery-ui/1658310-calculate-gantt-cell-width-dynamically-to-remove-blank-space

**Comment by pepinho24** [comment]
To give more information on the topic

The Gantt renders only the range it has defined. Rendering more cells with no events just to fill up the empty space would show incorrect data. Refer to this demo where you can give a big enough range where an empty space would not be rendered:
- ⁠https://demos.telerik.com/kendo-ui/gantt/selected-date-and-range

The other thing is the width of the slots in the timeline section. It does not support dynamic width as it would be confusing or misleading for the client. The slot size can be configured per view to fill the empty space but when the range should not be increased:

- ⁠https://docs.telerik.com/kendo-ui/api/javascript/ui/gantt/configuration/views.slotsize
