### ISSUE TITLE
"Invalid template" error when CSP is implemented in CDN

### ISSUE THREAD

**Issue by pexa-ashek** [telerik/kendo-ui-core#7896]
### Bug report

After implementing Content Security Policy for web pages using Kendo UI and JQuery, it seems like there is a issue with the loading of the `kendo.custom-2019.2.514.min` script.

Note that the Content-Security-Policy response header is being injected in the AWS CloudFront CDN.

Sample code is
```
dashGrid.kendoGrid({
     rowTemplate: kendo.template($("#dashboardGridTemplate").html()),
})
```

```
<script type="text/x-kendo-template" id="dashboardGridTemplate">
```

### Reproduction of the problem

```
Error: Invalid template:'<span #= item.enabled === false ? "disabled" : "" # # if (item.badge) { #data-badge="#=item.badge#"# } #>#= icon(iconClass) ##= image(item) ##= text #</span>' Generated code:'var $kendoOutput, $kendoHtmlEncode = kendo.htmlEncode;with(data){$kendoOutput='<span '+( item.enabled === false ? "disabled" : "" )+' '; if (item.badge) { ;$kendoOutput+='data-badge="'+(item.badge)+'"'; } ;$kendoOutput+='>'+( icon(iconClass) )+''+( image(item) )+''+( text )+'</span>';}return $kendoOutput;'
    at Object.compile (kendo.custom-2019.2.514.min.js:1:8911)
```

### Environment

* **Kendo UI version:** Kendo UI 2019.2.514
* **jQuery version:** 1.12.4
* **Browser:** [all ]

**Comment by pepinho24** [comment]
Hello Andrew, 
The stacktrace of the error you are showing indicates that the script is loaded and executed correctly, so your configuration for the CDN is correct. 

On the other hand, the inline and external templates require 'unsafe-eval' to be present in the meta tag. If you need to remove it, you should upgrade to at least R1 2023 and rewrite the templates into CSP-compatible functional templates.

```
<meta http-equiv="Content-Security-Policy" content="script-src 'unsafe-eval' 'self' https://your-cdn-here.com;">
```

Here are some articles about the CSP compliance of the Kendo UI for jQuery suite and its templates: 
- https://docs.telerik.com/kendo-ui/framework/templates/get-started-csp-templates
- https://docs.telerik.com/kendo-ui/intro/widget-basics/content-security-policy
