### ISSUE TITLE
RadioGroup not getting initialized when nested in Grid toolbar 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-ui-core#7904]
### Bug report
Reproducible with the Grid's tag helper. Works as expected in the Html helper.

### Reproduction of the problem
1. Run this example: https://netcorerepl.telerik.com/QSuBQmlo123kvYQt54

### Current behavior
The toolbar does not show the RadioGroup.

### Expected/desired behavior

A RadioGroup should appear in the toolbar, as set in the toolbar command template:
```
<toolbar-command-template>
    <kendo-radiogroup name="test">
        <kendo-radiogroup-items>
            <kendo-radiogroup-item label="Factor" value="F"></kendo-radiogroup-item>
            <kendo-radiogroup-item label="Equation" value="E"></kendo-radiogroup-item>
        </kendo-radiogroup-items>
    </kendo-radiogroup>
</toolbar-command-template>
```

### Environment

* **Kendo UI version:** 2024.2.514
* **jQuery version:** x.y
* **Browser:** [all ]

**Comment by aleksandarevangelatov** [comment]
IAlready fixed with https://github.com/telerik/kendo/commit/00526cab467f35f6fed48522bce9af6a45b9d65b
