### ISSUE TITLE
DatePicker, TimePicker and DateTimePicker are not entirely visible when width in pixels is set

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7915]
### Bug report

When the width of the DatePicker and DateTimePicker is set through style attribute and is set with fixed pixels, the buttons with icons for opening the popup might be hidden.

### Reproduction of the problem
1. Open the Dojo - https://dojo.telerik.com/@sspasova/OLicaHih

### Current behavior
Depending on the browser used the buttons containing the calendar and time icons are partially visible or entirely hidden. The issue does not occur if the width is set in percentages.

### Expected/desired behavior
The DatePicker and DateTimePicker components should be entirely visible when the width is set in pixels through the style attribute.

**Workaround:** Set the input element's width to 100%:

for DatePicker:
```
.k-datepicker input {
      width: 100% !important;
}
```
for TimePicker:

```
.k-timepicker input {
      width: 100% !important;
}
```

### Environment

* **Kendo UI version:** 2024.2.514
* **Browser:** [all ]

**Comment by alestoya** [comment]
Reported in 1659651

**Comment by martintabakov** [comment]
Also reported in 1659706

**Comment by eyupyusein** [comment]
reported in 1659468

**Comment by IvanDanchev** [comment]
Also reported in: 1659775, 1659793, 1659761

**Comment by mihaela-lukanova** [comment]
Also reported in: 1659326

**Comment by nelito987** [comment]
Also reported in: 1659953, 1659956, 1659706, 1660132, 1659959
