### ISSUE TITLE
Editor with grouped tools does not reflect select state

### ISSUE THREAD

**Issue by MihailRizov** [telerik/kendo-ui-core#7919]
### Bug report
When a tool is placed inside a group with indent and outdent tools, it loses the ability to indicate when it is selected.  

### Current behavior
![image](https://github.com/user-attachments/assets/9db7a677-073d-46be-8bd6-f52b672add2e)
As you can see the Insert Unordered List should be selected, but it is not.
here is [demo](https://dojo.telerik.com/UFUjadaW)

### Expected/desired behavior
The Insert Unordered List should be selected.

### Environment

* **Kendo UI version:** 2024.2.514

**Comment by Iankodj** [comment]
Along with the bug fix we need to ensure that the new way of grouping tools is properly documented in the API reference and a unit test to ensure that long-term support. 

```js
               // Undocumented tool grouping
                tools: [
                  "bold",
										['insertUnorderedList', 'insertOrderedList', 'indent', 'outdent'],
                ]
```
