### ISSUE TITLE
Editor Outdent tool lose focus

### ISSUE THREAD

**Issue by MihailRizov** [telerik/kendo-ui-core#7920]
### Bug report
When clicking on seemingly disabled outdent tool the editor lose focus.
Note: the issue is also reproducible with other disabled buttons, such as Undo, Redo and Remove hyperlink - [All tools demo](https://demos.telerik.com/kendo-ui/editor/all-tools)

### Reproduction of the problem
You can use this [demo](https://dojo.telerik.com/eQeXAMaF/2)

- Click at the beginning of a paragraph.
- Make sure that the state of the outdent tool is disabled.
- Click on the outdent tool.

**Side note:** if you continue to click on the button the editor portion of the demo will be selected indicated by the blue color:
![image](https://github.com/user-attachments/assets/df525db9-318d-4b5c-a281-ff8c01aad931)

### Current behavior
The editor lose focus. Thе text has no cursor.

### Expected/desired behavior
The editor should remain focused. Thе text should have cursor.

### Environment
* **Kendo UI version:** 2024.2.514
* **Browser:** all

**Comment by Dimitar-Goshev** [comment]
The behavior described above is actually the default browser behavior when a disabled button is clicked. It should not be considered a Bug. The fix that was applied to the above scenario led to two new issues - https://github.com/telerik/kendo-ui-core/issues/8194 and https://github.com/telerik/kendo-ui-core/issues/8246 . We are reverting the fix and fixing these new issues.
