### ISSUE TITLE
Unable to attach a dragstart event on Grid rows when dragToSelect is set to false

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-ui-core#7948]
### Bug report

When the selectable.dragToSelect option is set to false, you can't assign a dragstart event on the Grid's rows.

**Regression introduced with v2024.2.514**

### Reproduction of the problem

1. Open this Dojo example - https://dojo.telerik.com/@martin.tabakov@progress.com/aROGEpaQ/3
2. Try to drag a row

### Current behavior

The dragstart from the dataBound event is not triggering

### Expected/desired behavior

The dragstart event should be triggering

### Environment

* **Kendo UI version:** 2024.3.806 
* **Browser:** [all]

**Comment by gdenchevprog** [comment]
The current behavior is the correct one.

The functionality was broken in v2024.1.130 and v2024.1.319 which allowed the `dragstart` to work with the multiple selection mode, however this is not expected.

In fact, any versions prior to 2024.1.130 behave in the exact same manner as now.

My advice would be for developers to find an alternative approach to implement the functionality that they are after. Nevertheless, if one wishes to use the "broken" version, they can override the following method from the Grid's selectable component:

```javascript
 $("#inStockProductsGrid").data("kendoGrid").selectable._allowPreventDefault = (target) => {
        return !$(target).is(".k-table-td");
 }
```

If you're using the built-in paste feature of the Grid, enabling the [`allowPaste`](https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/allowpaste) config will also restore the `dragstart` behavior and you won't need the above override.

```javascript
$("#grid").kendoGrid({
 allowPaste: true 
});
```
