### ISSUE TITLE
Error is thrown when the copySelectionToClipboard is used and the last column in the Grid is hidden

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-ui-core#7956]
### Bug report

When the last column in the Grid is _hidden_ and the _copySelectionToClipboard_ is used an error is thrown in the console.

### Reproduction of the problem
1. Open the Dojo example - https://dojo.telerik.com/@NeliK/OYapiLOL.
2. Click the button and observe the console.

### Current behavior
There is an error `kendo.all.js:123327 Uncaught TypeError: Cannot read properties of undefined (reading 'title')` in the console.

### Expected/desired behavior
There should be no error.

### Environment

* **Kendo UI version:** 2024.3.806
* **Browser:** [all ]

**Comment by sspasova** [comment]
duplicate of #7621
