### ISSUE TITLE
Grid Hidden Column is set as exportable by default for Pdf and Excel

### ISSUE THREAD

**Issue by alestoya** [telerik/kendo-ui-core#7959]
### Bug report
Grid Hidden Column is set as exportable by default for Pdf and Excel

### Reproduction of the problem
1. Set a Column as hidden through the [Hidden()](https://docs.telerik.com/aspnet-core/api/kendo.mvc.ui.fluent/gridboundcolumnbuilder#hiddensystemboolean) API configuration.
2. Add both the [ToolBar.Excel()](https://docs.telerik.com/aspnet-core/api/kendo.mvc.ui.fluent/gridtoolbarcommandfactory#excel) and [ToolBar.Pdf()](https://docs.telerik.com/aspnet-core/api/kendo.mvc.ui.fluent/gridtoolbarcommandfactory#pdf) API configurations.
3. Notice, that the hidden column is exported.

### Current behavior
The Grid Hidden Column is set as exportable by default for Pdf and Excel.

### Expected/desired behavior
The Grid Hidden Column should NOT be set as exportable by default for Pdf and Excel.

### Workarounds
If you wish to set the hidden columns as non-exportable on a global scale, then a possible recommendation would be handle the [DataBound](https://docs.telerik.com/aspnet-core/api/kendo.mvc.ui.fluent/grideventbuilder?_gl=1*h6ugjk*_gcl_au*MTE4NzQ0ODEwLjE3MjQ3NzE3NTE.*_ga*OTUxODQ1MTM3LjE2ODUwMjY4NzI.*_ga_9JSNBCSF54*MTcyNDk5ODAwMi42NS4xLjE3MjUwMjIzNTcuNTkuMC4w#databoundsystemstring) event of the Grid and add the following layer of logic:

```JavaScript
.Events(events => events.DataBound("onDataBound"))

<script>
    function onDataBound(e){
        var columns = e.sender.columns.filter(column => {
            return column.hidden == true;
        }).forEach(column => column.exportable = false);
    }
</script>
```
If you wish to set the exportable state of the hidden columns granularly, a possible recommendation would be use the [Columns.Bound.Exportable()](https://docs.telerik.com/aspnet-core/api/kendo.mvc.ui.fluent/gridboundcolumnbuilder?_gl=1*5nzh57*_gcl_au*MTE4NzQ0ODEwLjE3MjQ3NzE3NTE.*_ga*OTUxODQ1MTM3LjE2ODUwMjY4NzI.*_ga_9JSNBCSF54*MTcyNDk5ODAwMi42NS4xLjE3MjUwMjIyODUuMTIuMC4w#exportablesystemboolean) API configuration.

```JavaScript
.Columns(columns =>
{
    columns.Bound(p => p.Freight).Hidden(true).Exportable(false);
    columns.Bound(p => p.OrderDate);
})
```

### Environment
* **Kendo UI version:** 2024.3.806
* **Browser:** all

**Comment by MilaTsv** [comment]
Reported in 1663424
