### ISSUE TITLE
Custom Filter Order in Telerik UI ASP.NET Core Grid Using TagHelpers

### ISSUE THREAD

**Issue by ivaylo-milanov** [telerik/kendo-ui-core#7966]
### Bug report

The custom ordering of the filter values in the Telerik UI ASP.NET Core Grid does not function correctly when using TagHelpers.

### Reproduction of the problem

1. Include operator configuration for string fields in the filterable settings.
2. Add filter values
3. The filter values are not in the configured order.

A REPL sample for reproduction: https://netcorerepl.telerik.com/wIYNvEvn00CAqNGL14

### Expected/desired behavior

The filter values should be presented in the same order as specified in the Filterable configuration.

### Environment

* **Kendo UI version: 2024.3.806

**Comment by aleksandarevangelatov** [comment]
Closing as item is already reported https://github.com/telerik/kendo-ui-core/issues/7259 
Monitor the linked issue for further details.
