### ISSUE TITLE
Kendo dropdown popup position is not correct

### ISSUE THREAD

**Issue by SumanManna1** [telerik/kendo-ui-core#7970]
### Bug report

The input field of the Combobox is being shifted left . It was working fine with Windows OS Build 17763.5820 and Edge Browser version 128.0.2739.67 (Official build) (64-bit) but post upgradation with OS Build 19045.4780 and Edge Browser version 126.0.2592.61 (Official build) (64-bit) its displaced all kendo dropdown controls.

### Reproduction of the problem
_(bug report only)_
Open [this Dojo example](https://dojo.telerik.com/aLEWaGEJ)
Run it and see the floating "Rib Knit" text which is the input field of the Combobox
<img width="576" alt="KendoDropDownPositionIssue" src="https://github.com/user-attachments/assets/73cff1b8-95b1-4f06-a7aa-716fd5189950">

### Current behavior
_(optional)_
The input field of the Combobox is being shifted left 

### Expected/desired behavior
ComboBox pop-up should appear in correct position according to the set "top, bottom, left, right" parameters.

### Environment

OS: Windows OS Build 19045.4780
Browser : Edge
Version : 126.0.2592.61 (Official build) (64-bit)
Kendo version : 2020.3.1021

**Comment by sspasova** [comment]
Hello @SumanManna1, 

Thank you for bringing this to our attention.
I've checked the provided Dojo example and saw that you use _appendTo_.
I advise you to use _anchor_ so you can achieve the correct position of the popup.
Here is an example of how to do it -> https://dojo.telerik.com/@gdenchev/aqIGASOF
