### ISSUE TITLE
TimePicker with min setting does not change correctly initially selected value

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-ui-core#7985]
### Bug report

When trying to select a value from the modern Kendo UI TimePicker configured with Min ranges, the currently selected value of the TimePicker is not updated.  

### Reproduction of the problem

1. Go to [this Progress Kendo UI Dojo.](https://dojo.telerik.com/@PMcDonou/uPUGOsoL)
2. Open the TimePicker - notice it's at _9:00_
3. Click _Set_
4. Value is set to _00:00_.

### Expected/desired behavior

The value should be set upon initial selection.

### Potential Workarounds

- Use Classic ComponentType
- Turn off animations, and open/close the TimePicker. ([Dojo](https://dojo.telerik.com/@PMcDonou/ecoPOkAD))

### Environment

* **Kendo UI version:** 2024.3.806
* **jQuery version:** [All Supported Versions](https://docs.telerik.com/kendo-ui/intro/supporting/jquery-support)
* **Browser:** All

**Comment by sspasova** [comment]
Might be related to this bug -> https://github.com/telerik/kendo-ui-core/issues/7965
