### ISSUE TITLE
Win Phone 8: Not able to focus filtering input

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#801]
Steps:
Navigate to: [http://demos.telerik.com/kendo-ui/dropdownlist/events](http://demos.telerik.com/kendo-ui/dropdownlist/events)
Open the DropDownList
Tap in the filtering input

Result: Widget is closed and the user is not able to filter the options.

**Comment by ggkrustev** [comment]
I will close this in favor of Win Phone 10 issues.

**Comment by zdravkov** [comment]
Seems to be working correctly when adding the following metatag that is required for mobile devices:

`<meta name="viewport" content="width=device-width, initial-scale=1.0" />`
