### ISSUE TITLE
Kendo UI for jQuery doesn't work at all on iPad Mini 4 (iOS 12.4) after version 2024.1.319

### ISSUE THREAD

**Issue by ChristosMylonas** [telerik/kendo-ui-core#8010]
### Reproduction of the problem
Kendo UI for jQuery doesn't work at all on **iPad Mini 4 (iOS 12.4) after version 2024.1..319** I have also tested on IOS 13 and seems to be problem here as well. All newer versions of iOS work correctly.

More specifically kendo versions:

- 2023.3.1114   Works correctly
- 2024.1.130    Works correctly
- 2024.1.319    Produces an Error (kendo.version is undefined)
- 2024.2.514   Produces an Error (kendo.version is undefined)
- 2024.3.806  Produces an Error (kendo.version is undefined)
- 2024.3.1015 Produces an Error (kendo.version is undefined)

### Current behavior
To simplify and reproduce I've created a dojo just to show the `kendo.version` and I tested on online test environment.
https://dojo.telerik.com/HKrcQCJW

On attached screenshots you can find the error on 2024.1.319 and how it works correctly on 2023.3.1114 & 2024.1.130.

### Expected/desired behavior
Kendo should initialize and work.
`kendo.version` should return the current version.

### Environment

* **Kendo UI version:** 2024.1.319
* **jQuery version:** 3.6.0
* **Browser:** [all ] 
* **Platform** iOS < 14

### See also
Reported also on https://www.telerik.com/forums/kendo-ui-for-jquery-doesn-t-work-at-all-on-ipad-mini-4-ios-12-4-after-version-2024-1-319
![2023 3 1114](https://github.com/user-attachments/assets/27e55a48-287d-4485-8277-b5ec4f2dd443)

![2024 1 130](https://github.com/user-attachments/assets/68ed1b6c-7d05-4421-816b-8c11c95067c5)

![2024 1 319](https://github.com/user-attachments/assets/9a6ee7da-0e0d-4dd9-95a5-0e7ac4bc1ad0)

**Comment by martintabakov** [comment]
We managed to reproduce the issue on iOS 12. However, our [Operation System support](https://docs.telerik.com/kendo-ui/intro/supporting/os-support) is for the two latest versions of the OS at the time of the Kendo release. As iOS 12 was released in 2018, it falls outside of the boundaries mentioned in the article. Kindly upgrade your iOS version as the error doesn't occur there.
