### ISSUE TITLE
Odata 4 '@odata.etag' property ignored on POST or PUT

### ISSUE THREAD

**Issue by RainerAtSpirit** [telerik/kendo-ui-core#802]
While trying to using a kendo dataSource with an Odata 4 endpoint we're facing an issue with the `@odata.etag` property during POST or PUT requests.

Our response looks similar to the example at http://www.odata.org/getting-started/basic-tutorial
```
{
    "value": [
        {
            "@odata.etag": "W/"08D1694BD49A0F11"",
            "UserName": "russellwhyte",
            "FirstName": "Russell",
            "LastName": "Whyte"
        }
}
```

During a PUT request we're adding the etag information in our custom Transport `update` method
```
        ...   
        if ( fn.checkNested(options, 'data', '@odata.etag') ) {

            extend(true, request, {
                headers: {
                    "If-Match": options.data['@odata.etag']
                }
            });

        }
        ...
```

When the response comes back the udpated `@odata.etag` isn't synchronized with the local data, so that a second update on the same item fails with a `412 precondition...` error, because the incorrect older etag is added.

Same is true for a POST request, where the the `odata.etag` value, which is part of the response,  isn't added to the local data.

In both cases it looks like the `@odata.etag` is simple ignored during the sync process.

We have implemented a temporary workaround by storing a Id2etag map on the datasource, but that seems to be overly complicated.

```
// on request end store etags in a Id2etag map

function onRequestEnd ( e ) {
    var response;

    if ( e.response === undefined || e.type === 'read' || e.type === 'destroy' ) {

        return;
    }

    response = isArray(e.response) ? e.response : [e.response];

    _.each(response, function( item, idx ) {

        this._Id2EtagMap[item.Id] = item['@odata.etag'];

    }, this);

}

// on sync add updated etag silently on each dataItem

function onSync ( e ) {

    _.each(this._Id2EtagMap, function( etag, id ) {
        var dataItem = this.get(id);

        if ( dataItem ) {
            dataItem['@odata.etag'] = etag;
        }

    }, this);

    this._Id2EtagMap = {};
}
```

**Comment by rkonstantinov** [comment]
Indeed, the all `@data` fields in the response are currently removed as DataSource cannot correctly merge them due to the prefix in their name. 

In order to implement the scenario in question you will need to manually persist the etag value. You approach seems legit. However, I can suggest similar one but using the schema.parse and serialize functions, something similar to the following:

````javascript
              schema: {
                        parse: function (response) {
                            var data = response.value ? response.value : [response];
                            for (var idx = 0; idx < data.length; idx++) {
                                data[idx].etag = data[idx]["@odata.etag"];
                            }
                            return response;
                        },
                        serialize: function(data) {
                            for (var idx = 0; idx < data.length; idx++) {
                                data[idx]["@odata.etag"] = data[idx].etag;
                                delete data[idx].etag;
                            }
                            return data;
                        }
                 }
