### ISSUE TITLE
Wrong icon endered in WP with flat theme

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#803]
![image](https://cloud.githubusercontent.com/assets/961037/7697335/3c6e949a-fe0f-11e4-8a09-476d63433cb4.png)

The hamburger icon (shown by the black arrow above) is only set in Kendo demos, so its issue is easily replicated when those styles are removed or Kendo Mobile is used outside of demos. However the icon font and images do have a hamburger icon and this can be easily fixed.

**Comment by yordanov** [comment]
Not reproducible on real device. Screenshot:
![wp_ss_20150925_0002](https://cloud.githubusercontent.com/assets/1118895/10095653/0b3713aa-6374-11e5-8628-35e9c61bccbb.png)

Pay attention that the drawer icon name is "drawer-icon":

```html
<a data-role="button" data-rel="drawer" href="#drawer" data-icon="drawer-icon" data-align="left"></a>
```
