### ISSUE TITLE
WP8: Flat skin icons broken

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#804]
![image](https://cloud.githubusercontent.com/assets/961037/7697354/90499128-fe0f-11e4-86c0-10de85e02df9.png)

**Comment by yordanov** [comment]
Not reproducible on real device. Tested with dark and light WP phone background. Screenshot:
![wp_ss_20150925_0002](https://cloud.githubusercontent.com/assets/1118895/10095653/0b3713aa-6374-11e5-8628-35e9c61bccbb.png)

Pay attention that the drawer icon name is "drawer-icon":

```html
<a data-role="button" data-rel="drawer" href="#drawer" data-icon="drawer-icon" data-align="left"></a>
```
