### ISSUE TITLE
kendo spliter drag spliter bar to left, wrong height

### ISSUE THREAD

**Issue by Euroncap** [telerik/kendo-ui-core#8052]
kendo spliter drag spliter bar to left, wrong height
    <body>
  <link href="styles/classic-silver.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script src="scripts/kendo.ui.core.min.js"></script> 
<div id="class_dlg" title="Doc Category" class="class_dlg">
  <div id="class_splitter"   class="class_splitter"> 
    <div>split1</div>
    <div>split2</div>
   </div>
</div> 
</body>
<style>
.class_splitter{
  flex-grow: 1;   
  height:calc(100% - 10px); 
} 
</style>
<script>
        this.dlg=$("#class_dlg").kendoDialog({
            modal: true,
            width:800,
            height:600,
            title:'x'
        }); 

        $("#class_splitter").kendoSplitter( {   panes: [ {  size: "500px"}]}); 
</script>

[testsplitter.txt](https://github.com/user-attachments/files/17810151/testsplitter.txt)
 
![Image](https://github.com/user-attachments/assets/4f5a0675-ed47-45ad-b49a-dab23be51c35)

**Comment by pepinho24** [comment]
Hello, 

Please review the custom styles if they are affecting the appearance of the Splitter as with the regular Kendo Themes, the issues does not seem to be present:
- https://dojo.telerik.com/FyrLqfUe
![Image](https://github.com/user-attachments/assets/2e92b13d-2f50-4071-8809-70ee1162314e)

If you manage to recreate the issue using the default themes and styles, please edit the Dojo example to reproduce the issue and share it with us here.
