### ISSUE TITLE
Angular $location breaks routing in mobile application

### ISSUE THREAD

**Issue by uloco** [telerik/kendo-ui-core#816]
In a kendo mobile application, if there are two different views with its' own controller, and the angular `$location` service is injected to one of them, the url in the address bar changes from `localhost:8080/#!foo` to `localhost:8080/#/!foo`. This breaks the `kendo-mobile-back-button` and the normal browser back button behaviour entirely. Perhaps it should be mentioned somewhere, that this is not working properly and which (kendo) service we should use for this instead.

**Comment by underlog** [comment]
the location service and the router are not supported in the Kendo UI Mobile Application context. this is described in the documentation.

**Comment by uloco** [comment]
The router is not supported, yes I know. But I didn't find the section where `$location` is mentioned in the documentation. The misleading thing here is, that you actually don't have to do anything with the location service to reproduce this behaviour. By simply injecting it to a controller, it changes without warnings... (Perhaps a warning message would be possible / nice here...) 
Thanks for clarification though
