### ISSUE TITLE
NumericTextBox missing borders

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-ui-core#818]
![border-numeric](https://cloud.githubusercontent.com/assets/1118895/7816729/ae8f8bb4-03d8-11e5-8c01-cf88f2c205de.png)

**Comment by naskog** [comment]
In support thread 941875 client reported missing bottom borders in Bootstrap theme (using Chrome 43).
In our [RTL demo](http://demos.telerik.com/kendo-ui/numerictextbox/right-to-left-support) left border is not visible with Chrome also:

![image](https://cloud.githubusercontent.com/assets/961037/8034832/3c3662e2-0df4-11e5-95b4-1ab83ca607c1.png)

**Comment by Raisolution** [comment]
@yordanov - The issue should be reviewed for all themes
