### ISSUE TITLE
WinPhone: Input mask not obeyed leads to broken widget state

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#826]
Steps:
1. Navigate to: [http://demos.telerik.com/kendo-ui/m/index#maskedtextbox/events](http://demos.telerik.com/kendo-ui/m/index#maskedtextbox/events)
Issue: With Windows Phone it is possible to enter a letter for the first character.
2. Enter a letter as for the first character and delete it (the widget is now in a kind of broken/unclear state)
3.Enter valid input (10 digits)
Issue:
The the cursor is moved at the end of the mask and valid output is logged after the mask

Reported in Ticket ID: 939318 
 
Valid for Windows Phone 8 and 10

**Comment by naskog** [comment]
Note: We should notify the customer when the issue is fixed.

**Comment by MilenaCh** [comment]
The problem still exists on **Windows Phone 8**:

1.Navigate to:
http://kendobuild-staging.openstack.progress.com/staging-kendo-ui/maskedtextbox/index
2.Enter some letter in "Phone Number" input

Result: maskedtextbox accepts the letter as a valid value

**Comment by hadjieva** [comment]
[Use `input` event only for tracking user input in the MaskedTextBox widget](https://github.com/telerik/kendo/issues/6739)

**Comment by jlchereau** [comment]
May I suggest looking at the following issues at the same time as they seem related?
- https://github.com/telerik/kendo-ui-core/issues/154
- https://github.com/telerik/kendo-ui-core/issues/2096
