### ISSUE TITLE
Kendo Grid frozen columns search in Chrome broken

### ISSUE THREAD

**Issue by sjaanus** [telerik/kendo-ui-core#845]
In Kendo grid, with frozen columns, when user searches the page with CTRL+F, then only the frozen columns will be scrolled down and not other content.

For example:
http://demos.telerik.com/kendo-ui/grid/frozen-columns

When searching for a ship name `Magazzini` with ctrl+F on the page, you can see that the frozen columns will scroll down, while the content in the right does not change.

This results in a display of invalid data, for example a row:

     10275	Magazzini Alimentari Riuniti Austria	Graz	Kirchgasse 6

While in reality it should be:

     10275	Magazzini Alimentari Riuniti Italy	Bergamo	Via Ludovico il Moro 22

This happens in Google chrome, while in Firefox, it does show that it found 1 result, but does not scroll to that result. 

I think this behaviour is not intended and any suggestions how to fix it?

**Comment by rkonstantinov** [comment]
Hi sjaanus,

Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (Professional, UI for MVC, PHP, JSP) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI!
