### ISSUE TITLE
Not able to select color on mobile phone

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#847]
Easily reproducible on: [http://demos.telerik.com/kendo-ui/colorpicker/api](http://demos.telerik.com/kendo-ui/colorpicker/api)

When "Apply" button is out of the screen you cannot scroll to it.

**Comment by gyoshev** [comment]
The window can be scrolled by dragging the popup elements that do not capture the drag command, such as the input / preview area.
