### ISSUE TITLE
Add support for SVG icons

### ISSUE THREAD

**Issue by bundyo** [telerik/kendo-ui-core#852]
There is a growing trend for the use of SVG for icons. The downside of these technique is that you need to use inline SVG with at least an use element (the other techniques don't have good cross-browser support and this is the only one that allows easy colorization of the icons):
http://24ways.org/2014/an-overview-of-svg-sprite-creation-techniques/

Currently Kendo UI supports only IMG and sprite icons with the addition of possible font-icon support. Can you add support for specifying templates for the icon element? This should be enough to allow SVG icon support.

What do you think?

**Comment by tsvetomir** [comment]
We went on the font icons route for the time being.
