### ISSUE TITLE
Scheduler: missing German localization bits

### ISSUE THREAD

**Issue by Casimodo72** [telerik/kendo-ui-core#861]
Hi, some of the scheduler's messages are not available in German:
![issue-kendo-scheduler-localization-01](https://cloud.githubusercontent.com/assets/10551738/8117542/3c1155dc-1089-11e5-9f27-fa3ab31ce144.PNG)

**Comment by tsvetomir** [comment]
Hello,

We're not very confident with our German skills hence the placeholders.

Please, feel free to hit us with a pull request.
