### ISSUE TITLE
Source binding does not destroy widgets

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#862]
Reported by Brady Mulhollem

> The source binding does not call destroy on widgets that it creates.
   If an item is removed, the bindings will be cleaned up for the removed item, but not any widgets.

```
<script id="template" type="text/x-kendo-template">
    <div><input data-role="dropdownlist"></div>
</script>

<div data-bind="source: items" data-template="template"></div>
```

**Comment by rwinscot** [comment]
Destroyed widgets never getting cleaned up = nasty memory leak... also, this effectively breaks any kind of automation (e.g. Selenium selectors). IMO, severity needs to be 'High' for the memory leak alone.

Fix ETA?
