### ISSUE TITLE
Misleading visualization when last character from the selected item is deleted

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#870]
Steps:
Navigate to [http://demos.telerik.com/kendo-ui/autocomplete/virtualization](http://demos.telerik.com/kendo-ui/autocomplete/virtualization)
Type "Vins" (data is filtered)
Select "10248 Vins ...."
Press Backspace ONCE to open the popup again

Result:
All "Vins" items but the one actually selected are visualized as selected 

![image](https://cloud.githubusercontent.com/assets/961037/8182363/57e1a56c-1437-11e5-9938-e0a8f90d4d5e.png)

**Comment by valchev** [comment]
The issue occurs because AutoComplete widget does not have `dataValueField`.

Because of this the `dataTextField` (`ShipName`) is used for both text and value field. In our demo page, `ShipName` has duplicating "Vins ..." values which is why VirtualList selects all of them.
