### ISSUE TITLE
Mobile ListView's click event is not fired if you scroll the widget while pull to refresh is in progress

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-ui-core#879]
Reproducible in this dojo:
http://dojo.telerik.com/Ibifi/2

1. Use PullToRefresh on listview
2. During the refresh process, make a quick motion down and up on list view
3. After refresh is completed user is unable to trigger click event on list view item.

Issue occurs **only on iOS and AppBuilder iOS Simulator**.

Ticket ID: 945368

**Comment by underlog** [comment]
Fixed with this: d77713f
