### ISSUE TITLE
Upgrade to AngularJS 1.4.*

### ISSUE THREAD

**Issue by pascalberger** [telerik/kendo-ui-core#889]
Since AngularJS 1.4 is now officially release, add support for the latest AngularJS version (1.4.1) at the moment.

**Comment by KirilNN** [comment]
Hi @pascalberger,

AngularJS 1.4 is not yet a stable release. We have just upgraded to the latest stable --> https://github.com/telerik/kendo-ui-core/issues/734

**Comment by pascalberger** [comment]
What are you considering a stable release? Its out of Beta and RC and officially downloadable from the Angular site. In my understanding this fulfills all requirements of stable.

**Comment by pascalberger** [comment]
And here's the blog post of the official release of 1.4: http://angularjs.blogspot.ch/2015/05/angular-140-jaracimrman-existence.html

**Comment by underlog** [comment]
Please check the screenshot from AngularJS website.  

![screen shot 2015-06-24 at 4 39 57 pm](https://cloud.githubusercontent.com/assets/13347/8331202/b23ef51a-1a8f-11e5-8e8f-d41271274073.png)

**Comment by stefan-schweiger** [comment]
Now there is not even a download offered for 1.3.x anymore on the website, and 1.4 is their stable version.

![](http://i.imgur.com/ytQC3ej.png)

**Comment by underlog** [comment]
@stefan-schweiger  :+1: We will upgrade to 1.4 at our next iteration. Notice that the current Kendo UI release does not have any known issues with Angular 1.4.* - you should be safe using it. 

You may subscribe to the new issue here. https://github.com/telerik/kendo-ui-core/issues/955

**Comment by jeroenvheel** [comment]
i have a issue with 1.4.* 
if i create a kendo-combo-box like :

```html
<select kendo-combo-box ng-model="legendItem.StyleArea.BrushStyle"
        ng-options="BrushStyle.Value as BrushStyle.Text for BrushStyle in legendItem.StyleArea.BrushStyleList"
        ng-selected="legendItem.StyleArea.BrushStyle"
        ng-disabled="legendItem.Cache"
        style="width:368px;"></select>

```
the correct node is not selected its selects the first option thats createed in the select box
the ng-model has a value of "number:1" and thats not correct.
```js
{
    legendItem.StyleArea.BrushStyle : "number:0"
}
```
is there a other way to do this ?
