### ISSUE TITLE
TabStrip active tab should not have a visible bottom border when scrolling is not used

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#895]
Selected tab appears detached from the content below

![image](https://cloud.githubusercontent.com/assets/961037/8376035/7840064c-1c0b-11e5-8831-46f3cb406481.png)

To be reviewed for all themes.

Reported in Ticket ID: 947699

**Comment by moshemal** [comment]
I submitted a pull request #988 for this issue
