### ISSUE TITLE
Unexpected scrolling up triggered in navigatable ListView

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#897]
Can be reproduced on: [http://dojo.telerik.com/OqagO/9](http://dojo.telerik.com/OqagO/9)

Scroll down the first ListView
Click on Tofu

Result: Tofu is selected, but the ListView is scrolled to its top

Reported in Ticket ID: 947414

**Comment by simonssspirit** [comment]
The issue is reported again in ticket: 1117733

Also, noticed that if there is a click handler, the click event is not fired on the first item when scrolling to the bottom: http://dojo.telerik.com/uhoJo

The issue is also reproducible in Chrome.
