### ISSUE TITLE
Incorrect position of caret in MaskedTextBox

### ISSUE THREAD

**Issue by bakura10** [telerik/kendo-ui-core#91]
Hi,

I'm having problem with the MaskedTextBox component on Chrome (didn't try other browsers). I'm using the source on master.

I'm creating a masked text for a credit card:

``` js
myElement.kendoMaskedTextBox({
      mask: '0000 0000 0000 0000',
      promptChar: ' '
    });
```

If I click inside the input (approximately in the middle of the input), we can see a very fast visual glitch where the caret initially positionned at the middle of the input, then go back at the expected position (beginning of the input). However, if I click again in the middle of the field, the caret is position there, even though I typed nothing.

**Comment by feelcollins** [comment]
Hi guys, I know this is very old but I am experiencing the issue bakura mentionned. I understand that the cursor moving is a feature of the masked field. My problem is that the behavior is not the same in IE and in chrome. During the first click on IE you can move your mouse without moving the cursor, on chrome on the other hand you move 1px while clicking and the cursor goes where you clicked. 1px is very easy to reproduce so the control is a pain to use. This is clearly an issue. Thank you

**Comment by dazinator** [comment]
I have raised a user voice here: http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback/suggestions/31274014-maskedtextbox
