### ISSUE TITLE
Widget list keeps selected items after filtering

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-ui-core#917]
Steps:

1. Open http://demos.telerik.com/kendo-ui/multiselect/index
2. Focus the widget, clear pre-selected values
3. Type "s", list should display one item "Steven White". Select it.
4. Type "s", list should display one **selected** item "Steven White". Deselect it.
5. Open the list.

Result "Steven White" is still selected in the StaticList, although the MultiSelect has no selected items.

Expected: "Steve White" should not be selected.

The same issue does not occur in virtual mode.

**Comment by nemalp** [comment]
Also reported in support thread 952126 and 952211.

**Comment by ggkrustev** [comment]
Reported in Ticket ID: 954609 too
