### ISSUE TITLE
ng-model does not work as expected without option label and local data

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#924]
Please refer to the http://dojo.telerik.com/eMepO/19 in order to replicate the issue with the third DropDownList. Please note that option label option does resolve the problem. 

Reported in ticket ID 920187

**Comment by chrisdostert** [comment]
+1

**Comment by KirilNN** [comment]
fixed with https://github.com/telerik/kendo-ui-core/commit/bbdd4c5eb2c847aa1c392934e8a0d50b5c16848c

working with the SP2 version:

http://dojo.telerik.com/eMepO/33
