### ISSUE TITLE
Button icons don't align correctly when font-size is bigger or less than 14px;

### ISSUE THREAD

**Issue by nemalp** [telerik/kendo-ui-core#935]
Can be reproduced here: http://demos.telerik.com/kendo-ui/button/index

Steps: 
1. Select Basic Usage or Anular JS
2. Select Bootstrap Theme 
3. Increase or decrease the font-size

Reported in Ticket ID: 950520

similar issue: https://github.com/telerik/kendo-ui-core/issues/3335

**Comment by Iankodj** [comment]
Here is a dojo with 2017.2.504: http://dojo.telerik.com/alERUV

And a screenshot of the problem: 
![image](https://user-images.githubusercontent.com/4222379/27072457-16e42be0-5029-11e7-89d9-6a6f5dba9dc6.png)

**Comment by Dimitar-Goshev** [comment]
The issue is still reproducible for Fiori theme:
![image](https://user-images.githubusercontent.com/6614183/28778156-d19c6e04-7606-11e7-98bd-3bcc2080b3ee.png)

**Comment by joneff** [comment]
@mvgmvg flex box is quite supported now. We could use it for modern browsers to tackle the alignment issues. See web/common/button.less for details. I think the code there already fixes this issue.
