### ISSUE TITLE
MVVM data-* widget configuration attributes break ComboBox when virtualization is enabled

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#942]
The problem could be reproduced with the http://dojo.telerik.com/Ejusi/5 example. Once the data-value-primitive="true" is removed from the second input element everything works fine. Both ComboBox widgets on the page have pretty much same configuration. 

Reported in ticket ID 951517

**Comment by ggkrustev** [comment]
After further investigation, we found out that the issue is due the fact that `kendo.bind` will override the widget's options during initialization. This is expected and the creator of the custom widget should implement setOptions method accordingly in order to persist the dataSource option.
