### ISSUE TITLE
Widget binds DataSource when value is null

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#946]
Can be replicated on [http://dojo.telerik.com/@naskog/uVazI](http://dojo.telerik.com/@naskog/uVazI)

Reported in Ticket ID: 951913

**Comment by naskog** [comment]
We should notify the client when the issue is resolved.

**Comment by naskog** [comment]
Additional feedback from the customer:
"The additional side affect of this bug is that it is causing a higher load on the backend server by making unnecessary calls. This in turn impacts our server usage statistics."

**Comment by ggkrustev** [comment]
Fixed with telerik/kendo-ui-core#1250

**Comment by naskog** [comment]
Customer is notifies of the fix.
