### ISSUE TITLE
FireFox: SplitButton focus not applied accordingly

### ISSUE THREAD

**Issue by naskog** [telerik/kendo-ui-core#951]
Steps:
Open page with a ToolBar
Select SplitButton option

Result:
![image](https://cloud.githubusercontent.com/assets/961037/8651344/d2013318-2980-11e5-807a-e676410e4821.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/961037/8651274/8e677bbc-2980-11e5-92a6-858e1cdd4cf2.png)

**Comment by valchev** [comment]
Related to telerik/kendo#4677
