### ISSUE TITLE
Returning only IDs 

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-ui-core#956]
As per the [documentation](http://docs.telerik.com/kendo-ui/framework/datasource/crud#create-remote):
> It is possible to return only the ID field(s) and value(s). In this case these IDs will be assigned to the client-side data items in the same order in which the newly created data items have been submitted.

This doesn't seem to work in practice:
```html
    <pre id="log"></pre>
    <script>
      var dataSource = new kendo.data.DataSource({
        autoSync: true,
        schema: {
          model: {
            id: "ID",
            fields: {
              Name: { type: "string" }
            }
          }
        },
        transport: {
          read: function(e) {
            e.success([]);
          },
          create: function(e) {
            e.success([{ ID: 123 }]);
          }
        }
      });
      
      dataSource.read();
      dataSource.add({ Name: "myname" });
      
      $("pre").html(JSON.stringify(dataSource.view()[0], null, 2));
    </script>
```

**Comment by rkonstantinov** [comment]
Unfortunately, we cannot support this as it will break multiple other functionalities.
