### ISSUE TITLE
kendo.grid does not define kendo.filtercell dependency

### ISSUE THREAD

**Issue by frankhuiskamp** [telerik/kendo-ui-core#959]
Version: 2015.2.264

When using RequireJS to load the Kendo Grid and setting
filterable: { mode: 'row' } 
The grid initialization will fail with an error:
Uncaught TypeError: $(...).attr(...).kendoFilterCell is not a function

It seems './kendo.filtercell' is missing from the define([...]) call in kendo.grid.js

**Comment by KirilNN** [comment]
Hi [name],

Thanks for your post, and for your interest in Kendo UI! Unfortunately, your request is related to a commercial version of Kendo UI (Professional, UI for MVC, PHP, JSP) and this repository is *only* for Kendo UI Core. I’m going to close this request with this comment, but I encourage you to leverage the [Kendo UI Premium Forums](http://www.telerik.com/forums/kendo-ui-framework) or our support system at Telerik.com as both are benefits you receive as a part of being a commercial license-holder.

Thanks again for using Kendo UI
