### ISSUE TITLE
Tooltip widget doesn't work after the first time it was opened with expand effect    

### ISSUE THREAD

**Issue by moshemal** [telerik/kendo-ui-core#965]
Tested on Chrome Linux, Firefox Linux, IE11 Win7, IE8 Win7

**Comment by KirilNN** [comment]
Can be reproduced here:

http://dojo.telerik.com/ozeKo

**Comment by moshemal** [comment]
The tooltip div (selector: "".k-widget.k-tooltip.k-tooltip-closable.k-popup.k-group.k-reset.k-state-border-up"" ) gets style attribute opacity=0 and this is making the div invisible.
