### ISSUE TITLE
Setting widget options in link function of custom directive will not reflect the widget

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-ui-core#973]
Can be reproduced here: http://dojo.telerik.com/ejAri/3

used to work in previous versions due to the timeout initialization, which was removed with the latest release.

@mishoo @underlog  Do you guys think that we should support this scenario?

**Comment by underlog** [comment]
No.

**Comment by underlog** [comment]
It can be worked around using `$timeout` and `k-ng-delay`, though. I consider this to be an anti-pattern. People who use custom directives should not nest the kendo directives - they should use `$().kendo*()` syntax instead.

**Comment by KirilNN** [comment]
Here is the workaround suggested: http://dojo.telerik.com/ejAri/6
