### ISSUE TITLE
MVVM the initial value is set and auto-bind is disabled (false) it will reset the value when the widget is bound to data 

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-ui-core#975]
Please refer to ticket 954276. 

When the initial value is set (data-auto-bind="false") when the widget is bound to data (opening the items list) will clear the value in MVVM scenario. Please refer to the http://dojo.telerik.com/ewoLO/3 example. 

Please note that it was working fine in 2015 Q1 SP1.

**Comment by ggkrustev** [comment]
Addressed in Q1 2016
