### ISSUE TITLE
Toolbar button click event is not triggered when parent container mousedown event is prevented

### ISSUE THREAD

**Issue by rkonstantinov** [telerik/kendo-ui-core#976]
Reported in #954529.

[Here](http://dojo.telerik.com/@rkonstantinov/aCOQe) is a test page of the scenario. Note that the "normal" button click is triggered but the Toolbar Button click is not. 

Most probably it is caused by how the UserEvents are handling the click/tap.

**Comment by boog** [comment]
I'd like this issue to be escalated because it prevents buttons from being placed within the detail template area of a Grid. See this [reproduction example](http://dojo.telerik.com/udEza).

**Comment by underlog** [comment]
Fixed the scenario with https://github.com/telerik/kendo-ui-core/issues/1176
