### ISSUE TITLE
autoComplete closes on scroll

### ISSUE THREAD

**Issue by avbrychak** [telerik/kendo-ui-core#979]
if body is higher than screen(can be scrolled) and autocomplete popup list has scroll, scroll it to the last item, and it will be closed. even in it's hovered
example http://jsfiddle.net/gJa74/72/

**Comment by ggkrustev** [comment]
Hi @avbrychak,

The widget is designed to close the popup on scroll. On the other hand it allows default browser behavior once the end of the list is reached.

I would suggest you refer to this "how-to" demo that shows one possible workaround of the described limitation:
- http://docs.telerik.com/kendo-ui/web/dropdownlist/how-to/prevent-close-on-scroll

I will close this thread with this message, as the reported behavior is limitation that is not confirmed as bug. If you need further assistance I would suggest you public your questions in StackOverflow.
