### ISSUE TITLE
Widget appends its popup in the wrong place when put in PanelBar

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#985]
Repro demo: http://dojo.telerik.com/eBeNA

Reported in TicketID: 955648

**Comment by ggkrustev** [comment]
The fix is to avoid putting "k-group" class to the UL element, because the POPUP widget will append the element to that container. This is due to Menu widget is desired support of putting editors (datepicker and etc) inside of a Menu.

That being said, this issue is clearly related only to MVC wrappers rendering.

**Comment by underlog** [comment]
I suggest that we document the workaround and close this.
