### ISSUE TITLE
The selected tab in the TabStrip now has underline

### ISSUE THREAD

**Issue by moshemal** [telerik/kendo-ui-core#987]
### Current version:
![image](https://cloud.githubusercontent.com/assets/2989198/8901835/be27fb0e-3454-11e5-9f3a-f735b5871161.png)

### Few versions before (as it should be):
![image](https://cloud.githubusercontent.com/assets/2989198/8901811/8857bfbe-3454-11e5-8d5e-4eaa97823ae2.png)

**Comment by naskog** [comment]
Duplicate of #895
