### ISSUE TITLE
Widget in 'Single' tag mode does not update the underlying SELECT value

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-ui-core#996]
### Description
The widget skips SELECT value update when `tagMode: single`

Repro demo: http://demos.telerik.com/kendo-ui/multiselect/tag-mode
Steps: 
1. Select new value
2. Inspect the value of the SELECT element. Notice how the value is not updated

Reported in TicketID: 956824

**Comment by geniuscodemonkey** [comment]
I was just looking at using this in our application today and found the same issue. Thanks for jumping on this. Can you say when the Q2 SP will be released?

**Comment by ggkrustev** [comment]
Hi @geniuscodemonkey,

The Q2 SP is due to the mid of next week

**Comment by geniuscodemonkey** [comment]
Cheers! I wait with baited breath!
