### ISSUE TITLE
mobile listview performs unnecessary rendering when MVVM bound and item is changed

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#998]
http://dojo.telerik.com/Ulazi/2

**Comment by simonwaterer** [comment]
This should be added as a breaking change in http://docs.telerik.com/kendo-ui/backwards-compatibility/2015/2015-backward-compatibility 

There could apps that relied on the mobile listview rebinding when dataSource itemChange fires.

**Comment by underlog** [comment]
You are correct, although the behavior itself is more of a bug then a feature. Notice that this affects only MVVM bound listviews, which should not use template syntax anyway.
